import type {PixelArtWorldEventPropPack} from '@/project/pixelArtWorldEventProps';
import {waterSupportExample,validateWaterSupportExample,WATER_SUPPORT_SOURCE} from '@/project/pixelArtWorldWaterSupport';
import type {TilesetReferenceCategory} from '@/project/tilesetReferences';
/** Requires both exact user originals; no bundled art and no project map mutation. */
export function appendWaterSupportReferences(pack:PixelArtWorldEventPropPack,atlas:HTMLCanvasElement,sewer:HTMLImageElement,assetId:string,refs:TilesetReferenceCategory){
  const draw=(example:ReturnType<typeof waterSupportExample>)=>{const c=document.createElement('canvas');c.width=example.width*32;c.height=example.height*32;const ctx=c.getContext('2d')!;ctx.imageSmoothingEnabled=false;for(const layer of[example.lowerTiles,example.upperTiles])layer.forEach((t,i)=>{if(t>=0)ctx.drawImage(sewer,t%8*32,Math.floor(t/8)*32,32,32,i%example.width*32,Math.floor(i/example.width)*32,32,32);});for(const e of example.events){const f=e.pages[0].graphic.pattern;ctx.drawImage(atlas,f%4*pack.frameWidth,Math.floor(f/4)*pack.frameHeight,pack.frameWidth,pack.frameHeight,e.x*32+16-pack.frameWidth/2,e.y*32+32-pack.frameHeight,pack.frameWidth,pack.frameHeight);}return c;};
  for(const variant of pack.variants.filter(v=>v.kind==='loop')){
    const example=waterSupportExample(pack,variant,assetId);if(validateWaterSupportExample(example,example).length)throw Error('물줄기 지지 표본 오류');
    const incorrect=structuredClone(example);for(const cell of example.supportCells)incorrect.lowerTiles[cell.y*example.width+cell.x]=0;
    const errors=validateWaterSupportExample(example,incorrect),good=draw(example),bad=draw(incorrect),comparison=document.createElement('canvas');comparison.width=good.width*2+8;comparison.height=good.height;comparison.getContext('2d')!.drawImage(good,0,0);comparison.getContext('2d')!.drawImage(bad,good.width+8,0);
    const id=variant.id+'-sewer-support';refs.images.push({id,name:id+'.png',caption:'왼쪽 벽 배수구와 수면에 닿는 물보라. 오른쪽 실제 수면을 마른바닥으로 바꾼 오류.',dataUrl:comparison.toDataURL()});
    refs.documents.push({id,name:variant.name+' · 실제 하수도 지지.md',markdown:[`# ${variant.name} · 별도 하수도 표본`,example.notes,`배경 원본 ${WATER_SUPPORT_SOURCE.filename}, SHA256 ${WATER_SUPPORT_SOURCE.sha256},32px8열. 물줄기 원본${pack.filename}, SHA256 ${pack.sha256}, assetId:${assetId}. 두 원본은 별도 파일이다. 배경 PNG를 native 하수도 타일셋으로 가져온 다음 아래 숫자를 쓴다. 타일셋 ID를 다른 칩셋으로 대체하지 않는다.`, '하위 전체→상위 전체→1이벤트를 순서대로 적용한다. 이벤트는 바닥 중앙 앵커로 고정하고 그림 전체를 한 프레임으로 바꾼다. 120ms는 편집 예시속도다. 반복 페이지는 parallel, 정지는 같은 길이 static variant의 첫 프레임/명령0개다. 완성 그림 내부의 배수구를 별도 ST 배수구와 중복하지 않는다.','아래 source 좌표/전체 배열/events/commands를 모두 사용한다. 오류예제는 이벤트를 옮기지 않고 물보라 밑 수면선304를 마른바닥0으로 바꿨다. 좌표검사는 이 고정 표본의 범위에 한하며 실제 프로젝트의 임의 물리/고도를 자동 검증하지 않는다.',`\`\`\`json\n${JSON.stringify({expected:example,incorrect,errors},null,2)}\n\`\`\``,`![정상과 받침 오류](image:${id})`,`[제작자 사용 예](${WATER_SUPPORT_SOURCE.sourcePage}) · ${pack.rights.credit} · 사용자 로컬 생성, 소재 재배포 금지.`].join('\n\n')});
  }
}
