/** Source-raster focused controls. Geometric fixtures only; no production drawing or semantic art approval. */
import { strict as assert } from 'node:assert';
import { mkdtempSync,writeFileSync,readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createImage,cloneImage,pixelAt,setPixel,type RgbaImage,type Rgba } from '../../monster-collect-species/pixel/image';
import { readPng,writePng } from '../../monster-collect-species/node/png';
import { importRasterAtlas,checkCharset,VERSION,toEditorCharset,framesFromNative,pack } from './motion';
import { run } from './cli';
const results:{name:string;pass:true;detail?:unknown}[]=[];
const record=(name:string,detail?:unknown)=>results.push({name,pass:true,...(detail===undefined?{}:{detail})});
function rectangle(im:RgbaImage,x:number,y:number,w:number,h:number,p:Rgba){for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++)setPixel(im,xx,yy,p);}
function fixtures(){return Array.from({length:12},(_,i)=>{const f=createImage(16,32),pose=i%3,dx=Math.floor(i/3)-1,dy=pose===1?0:1;rectangle(f,4+dx,11+dy,8,8,[30,40,50,255]);rectangle(f,4+dx,19+dy,8,6,[100,80,180,255]);rectangle(f,5+dx,25+dy,2,6,[20,30,40,255]);rectangle(f,9+dx,25+dy,2,6,[20,30,40,255]);if(pose===0)rectangle(f,4+dx,29+dy,3,2,[20,30,40,255]);if(pose===2)rectangle(f,10+dx,29+dy,3,2,[20,30,40,255]);return f;});}
function sourceAtlas(frames:RgbaImage[],factor=4){const frameWidth=frames[0]!.width,source=createImage(frameWidth*3*factor,32*4*factor);frames.forEach((f,i)=>{for(let y=0;y<32;y++)for(let x=0;x<frameWidth;x++)for(let yy=0;yy<factor;yy++)for(let xx=0;xx<factor;xx++)setPixel(source,(i%3)*frameWidth*factor+x*factor+xx,Math.floor(i/3)*32*factor+y*factor+yy,pixelAt(f,x,y));});return source;}
async function main(){
  const base=mkdtempSync(join(tmpdir(),'pokemon-raster-verifier-')),raw=sourceAtlas(fixtures()),source=join(base,'upscaled-12frames.png'),prompt=join(base,'fixture-prompt.txt');writePng(source,raw);writeFileSync(prompt,'Source-raster geometric fixture, for validation only; never ship as character art.');
  const direct=importRasterAtlas(raw),checked=checkCharset(direct.image);assert.equal(checked.pass,true,checked.errors.join('; '));assert.equal(direct.phase,.5);assert.equal(direct.alphaThreshold,128);assert.equal(direct.sampling,'common-source-raster');assert(direct.scale>0&&direct.scale<1);assert.equal(direct.rects.length,12);for(const f of direct.commonScaleFit.frames){assert(f.leftExtent*direct.scale<=8+1e-8);assert(f.rightExtent*direct.scale<=8+1e-8);assert(f.topRelativeHeight*direct.scale<=21+1e-8);}assert.equal(direct.commonScaleFit.frames.length,12);record('upscaled twelve-frame direct raster valid',{scale:direct.scale,phase:direct.phase,fit:direct.commonScaleFit});
  const metrics=Object.fromEntries(['up','right','down','left'].map(dir=>{const m=checked.metrics[dir] as {jitterX:number;jitterY:number;stepChange:number};assert(m.jitterX<=1&&m.jitterY<=1);assert(m.stepChange>=4);return [dir,m];}));record('head roots and real stride change remain valid',metrics);
  assert.equal(direct.image.width,48);assert.equal(direct.image.height,128);const editor=toEditorCharset(direct.image);assert.equal(editor.width,72);assert.equal(editor.height,128);assert.deepEqual(pack(framesFromNative(editor)).data,direct.image.data);for(let i=0;i<12;i++)for(let y=0;y<32;y++)for(let x=0;x<24;x++)if(x<4||x>=20)assert.equal(pixelAt(editor,(i%3)*24+x,Math.floor(i/3)*32+y)[3],0);record('native48x128 and exact x4 editor72x128 adapter, no stretch');
  const badEditor=cloneImage(editor);setPixel(badEditor,3,20,[30,40,50,255]);assert.throws(()=>framesFromNative(badEditor),/outside central16/);record('editor ink outside central16 rejected rather than cropped');
  const legacy=createImage(288,256);for(let y=0;y<128;y++)for(let x=0;x<72;x++)setPixel(legacy,x,y,pixelAt(editor,x,y));assert.deepEqual(pack(framesFromNative(legacy,0)).data,direct.image.data);setPixel(legacy,20,20,[30,40,50,255]);assert.throws(()=>framesFromNative(legacy,0),/outside central16/);record('legacy pack central16 extraction and outside-ink rejection');
  const visible128=cloneImage(raw);for(let i=3;i<visible128.data.length;i+=4)if(visible128.data[i])visible128.data[i]=128;assert.deepEqual(importRasterAtlas(visible128).image.data,direct.image.data);record('foreground alpha128 remains visible');
  const invisible127=cloneImage(raw);for(let i=3;i<invisible127.data.length;i+=4)if(invisible127.data[i])invisible127.data[i]=127;assert.throws(()=>importRasterAtlas(invisible127),/empty source head/);record('foreground alpha127 is background');
  const hidden=cloneImage(raw);for(let i=0;i<hidden.data.length;i+=4)if(!hidden.data[i+3]){hidden.data[i]=(i*7)%256;hidden.data[i+1]=(i*13)%256;hidden.data[i+2]=(i*17)%256;}
  assert.deepEqual(importRasterAtlas(hidden).image.data,direct.image.data);record('hidden transparent RGB invariant');
  const faint=cloneImage(raw);for(let i=0;i<faint.data.length;i+=4)if(!faint.data[i+3]){faint.data[i]=20;faint.data[i+1]=200;faint.data[i+2]=40;faint.data[i+3]=127;}assert.deepEqual(importRasterAtlas(faint).image.data,direct.image.data);record('alpha127 background invariant');
  const magenta=cloneImage(raw);for(let i=0;i<magenta.data.length;i+=4)if(!magenta.data[i+3]){magenta.data[i]=255;magenta.data[i+1]=0;magenta.data[i+2]=255;magenta.data[i+3]=255;}assert.deepEqual(importRasterAtlas(magenta).image.data,direct.image.data);record('opaque flat magenta background removed honestly');
  const asymmetric=fixtures().map(f=>{const wide=createImage(40,32);for(let y=0;y<32;y++)for(let x=0;x<16;x++)setPixel(wide,x+20,y,pixelAt(f,x,y));return wide;});rectangle(asymmetric[0]!,0,22,24,4,[100,80,180,255]);assert.throws(()=>importRasterAtlas(sourceAtlas(asymmetric)),/clips|baseline/);record('asymmetric large arm cannot fit native bounds and baseline together');
  const moderate=fixtures().map((f,i)=>{const wide=createImage(24,32);for(let y=0;y<32;y++)for(let x=0;x<16;x++)setPixel(wide,x+2,y,pixelAt(f,x,y));const dx=Math.floor(i/3)-1,dy=i%3===1?0:1;rectangle(wide,6+dx,9+dy,8,2,[30,40,50,255]);return wide;});rectangle(moderate[0]!,0,22,7,3,[100,80,180,255]);const fitted=importRasterAtlas(sourceAtlas(moderate)),fittedCheck=checkCharset(fitted.image);assert(!fittedCheck.errors.some(error=>error.includes('native ink bounds')),fittedCheck.errors.join('; '));assert(fitted.scale<Math.min(fitted.commonScaleFit.widthScale,fitted.commonScaleFit.heightScale));for(const f of fitted.commonScaleFit.frames){assert(f.leftExtent*fitted.scale<=8+1e-8);assert(f.rightExtent*fitted.scale<=8+1e-8);}record('moderate asymmetry imports without clipping using one shared scale; gait gate stays independent',{scale:fitted.scale,fit:fitted.commonScaleFit,gaitGateErrors:fittedCheck.errors});
  const empty=createImage(raw.width,raw.height);assert.throws(()=>importRasterAtlas(empty),/empty source head/);record('empty alpha source head rejected');
  const emptyMagenta=createImage(raw.width,raw.height);for(let i=0;i<emptyMagenta.data.length;i+=4)emptyMagenta.data.set([255,0,255,255],i);assert.throws(()=>importRasterAtlas(emptyMagenta),/empty source head/);record('background-only magenta source rejected');
  const originalLog=console.log;let candidate='';console.log=(...items:unknown[])=>{if(typeof items[0]==='string'&&items[0].includes('/candidates/'))candidate=items[0];};
  const command=(stage:string,args:string[]=[])=>run([stage,'--sandbox',base,...args]);
  assert.equal(await command('import',['--role','hero','--source',source,'--prompt-file',prompt,'--sampling','raster']),0);console.log=originalLog;assert(candidate);
  const provenance=JSON.parse(readFileSync(join(candidate,'provenance.json'),'utf8'));assert.equal(provenance.sampling,'common-source-raster');assert.equal(provenance.phase,.5);assert.equal(provenance.alphaThreshold,128);assert.equal(provenance.headAlignment,'source dominant contiguous skull-row median before sampling');assert.equal(provenance.scale,direct.scale);assert.deepEqual(provenance.commonScaleFit,direct.commonScaleFit);assert.deepEqual(readPng(join(candidate,'charset.png')).data,direct.image.data);record('actual CLI raster provenance and exact native bytes');
  assert.equal(await command('check',['--candidate',candidate]),0);assert.equal(await command('preview',['--candidate',candidate]),0);assert.equal(await command('gate',['--candidate',candidate]),1);record('raster full gate blocks absent semantic review');
  const evidence=join(base,'fixture-review.txt');writeFileSync(evidence,'Raster executable fixture ledger mechanics only; NOT a character aesthetic approval.');assert.equal(await command('review',['--candidate',candidate,'--who','executable-raster-fixture','--why','fixture ledger control only','--verdict','pass','--evidence',evidence]),0);assert.equal(await command('gate',['--candidate',candidate]),0);assert.equal(await command('build',['--candidate',candidate]),0);record('actual raster CLI complete local lifecycle');
  const built=join(base,'output','hero');assert.deepEqual(readPng(join(built,'editor-charset.png')).data,toEditorCharset(readPng(join(built,'charset.png'))).data);const oldProvenance=readFileSync(join(candidate,'provenance.json'));writeFileSync(join(candidate,'provenance.json'),oldProvenance.toString().replace(VERSION,'pokemon-motion-1'));assert.equal(await command('check',['--candidate',candidate]),1);assert.equal(await command('build',['--candidate',candidate]),1);writeFileSync(join(candidate,'provenance.json'),oldProvenance);record('obsolete version1 provenance cannot check or build');
  assert.equal(await command('import',['--role','hero','--source',source,'--prompt-file',prompt,'--sampling','invented']),1);record('unknown sampling rejected');
  const asymmetricPath=join(base,'asymmetric-source.png');writePng(asymmetricPath,sourceAtlas(asymmetric));assert.equal(await command('import',['--role','hero','--source',asymmetricPath,'--prompt-file',prompt,'--sampling','raster']),1);record('actual CLI refuses incompatible asymmetric source');
  const emptyPath=join(base,'no-head.png');writePng(emptyPath,empty);assert.equal(await command('import',['--role','hero','--source',emptyPath,'--prompt-file',prompt,'--sampling','raster']),1);record('actual CLI refuses empty head source');
  const report={version:VERSION,base,results,count:results.length,candidate};writeFileSync(join(base,'verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}
main().catch(error=>{console.error(error);process.exitCode=1;});
