import { buildSharedScene, inspectSharedScene, sharedSceneList, type SharedSceneLinks } from '@/project/sharedSceneAuthoring';
import { ToolError, type ToolDefinition } from './types';
const linkSchema = { type: 'string' as const, enum: ['reject', 'omit', 'include'], description: 'include=원본 전이로 연결된 모든 맵, omit=외부 목적맵을 참조하는 이벤트를 제외하고 명시, reject=외부 연결이 있으면 중단' };
export const SHARED_SCENE_TOOLS: readonly ToolDefinition[] = [
    { name: 'list_shared_scenes', mode: 'read', domains: ['map', 'tile', 'world'], description: '사용자가 설치한 공용 학교·교실·시설 실내·주택·도시의 실제 완성 장면을 검색한다. 원본 타일셋, 두 레이어, 저장된 이벤트를 재사용하여 편집 가능한 새 맵으로 만들 수 있다. 자료만 있는 소품 목록과 구별한다. query는 이름/태그/ID 검색. 다음 페이지는 nextOffset.', parameters: { type: 'object', properties: { query: { type: 'string' }, libraryId: { type: 'string' }, offset: { type: 'integer', minimum: 0 } }, additionalProperties: false }, run(_p, a) { const all = sharedSceneList(String(a.query ?? ''), a.libraryId as string | undefined), offset = Number(a.offset ?? 0); if (!Number.isSafeInteger(offset) || offset < 0)
            throw new ToolError('Invalid offset'); return { summary: `공용 장면 ${all.length}개`, data: { scenes: all.slice(offset, offset + 20), nextOffset: offset + 20 < all.length ? offset + 20 : null, total: all.length } }; } },
    { name: 'inspect_shared_scene', mode: 'read', domains: ['map', 'tile', 'world'], description: '선택한 공용 장면의 맵 구성·외부 출입 연결·정적 예제 한계·현재 revision을 읽는다. reference에 표시된 read_spatial_reference 문서/그림을 확인한 다음 build_shared_scene으로 독립 사본을 만든다. 학교 전체는 네 층을 포함하며 도시 links=include는 연결된 시설 내부까지 포함한다.', parameters: { type: 'object', properties: { id: { type: 'string' }, links: linkSchema }, required: ['id'], additionalProperties: false }, run(_p, a) { return { summary: '공용 장면 구성과 연결', data: inspectSharedScene(String(a.id), (a.links ?? 'omit') as SharedSceneLinks) }; } },
    { name: 'build_shared_scene', mode: 'write', domains: ['map', 'tile', 'world'], description: '조회한 공용 장면을 새 맵들로 실제 구현한다. inspect_shared_scene의 revision과 새 namespace를 전달한다. 원본 두 레이어·그림·통행·사건과 포함된 맵 사이 전이를 보존하고 ID를 재연결한다. 기존 맵은 덮지 않는다. 학교/도시/교실/실내를 구현한 뒤 show_map_region으로 확인하고 일반 편집 도구로 수정할 수 있다. 정적 그림에 없는 판매/문/전이 동작을 만들어냈다고 보고하지 않는다. 원본을 재사용하는 결정론 도구이며 임의 평면 생성기가 아니다.', parameters: { type: 'object', properties: { id: { type: 'string' }, namespace: { type: 'string' }, revision: { type: 'string' }, links: linkSchema, setStart: { type: 'boolean' } }, required: ['id', 'namespace', 'revision', 'links'], additionalProperties: false }, run(p, a) { const data = buildSharedScene(p, String(a.id), String(a.namespace), String(a.revision), a.links as SharedSceneLinks, a.setStart === true); return { summary: `공용 장면 ${data.maps.length}개 맵 구현`, data, ...(data.omittedEvents.length ? { warnings: [`외부 목적맵이 없어 이벤트 ${data.omittedEvents.length}개를 제외했습니다. omittedEvents를 확인하고 출입을 별도로 연결하세요.`] } : {}) }; } },
];
