import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {randomBytes,timingSafeEqual} from 'node:crypto';import {spawnSync} from 'node:child_process';
import {openStore,list,packageFor,stateFor,decide,assertAllowed,buildApproved,read} from './store.mjs';
const equal=(a,b)=>typeof a==='string'&&typeof b==='string'&&a.length===b.length&&timingSafeEqual(Buffer.from(a),Buffer.from(b));
export async function serve({data,host,port}){if(!Number.isSafeInteger(port)||port<1024||port>65535)throw Error('명시적인 포트가 필요합니다');const store=openStore(data),sessions=new Map();const reference=path.join(data,'reference');if(!fs.existsSync(path.join(reference,'walk.gif'))){const r=spawnSync('python3',[path.join(import.meta.dirname,'reference_media.py'),'--out',reference],{encoding:'utf8'});if(r.status!==0)throw Error(r.stderr);}const page=fs.readFileSync(path.join(import.meta.dirname,'review.html'));const server=http.createServer(async(req,res)=>{const json=(status,value)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(value));};try{const url=new URL(req.url,'http://localhost');if(req.method==='GET'&&url.pathname==='/'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Frame-Options':'SAMEORIGIN','Content-Security-Policy':"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'self'"});res.end(page);return;}if(req.method==='GET'&&url.pathname==='/api/session'){const token=randomBytes(32).toString('hex');sessions.set(token,Date.now()+12*60*60*1000);for(const [k,v] of sessions)if(v<Date.now())sessions.delete(k);res.setHeader('Set-Cookie','casting_session='+token+'; HttpOnly; SameSite=Strict; Path=/');json(200,{csrf:token});return;}if(req.method==='GET'&&url.pathname==='/api/candidates'){json(200,{items:list(store),decisionsPersisted:true});return;}
 if(req.method==='GET'&&url.pathname==='/reference/walk.gif'){res.writeHead(200,{'Content-Type':'image/gif','Cache-Control':'no-store'});res.end(fs.readFileSync(path.join(reference,'walk.gif')));return;}
 const asset=url.pathname.match(/^\/candidate\/([-a-z0-9]+)\/([a-z.]+)$/);if(req.method==='GET'&&asset){const [,id,file]=asset;if(!['charset.png','walk.gif','context.png','recipe.json','template.png','changes.png'].includes(file)){json(404,{error:'없는 파일'});return;}const pkg=packageFor(store,id);const mime=file.endsWith('.png')?'image/png':file.endsWith('.gif')?'image/gif':'application/json';res.writeHead(200,{'Content-Type':mime,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(fs.readFileSync(path.join(pkg.folder,file)));return;}
 const download=url.pathname.match(/^\/download\/([-a-z0-9]+)\.zip$/);if(req.method==='GET'&&download){const id=download[1],pkg=assertAllowed(store,id),out=path.join(store.data,'approved',id,'decision-'+pkg.decision.seq);buildApproved(store,id,out);const zip=out+'.zip';const r=spawnSync('python3',['-c',"from pathlib import Path;import zipfile,sys;d=Path(sys.argv[1]);z=zipfile.ZipFile(sys.argv[2],'w',zipfile.ZIP_DEFLATED);[z.write(p,p.name) for p in d.iterdir() if p.is_file()];z.close()",out,zip],{encoding:'utf8'});if(r.status!==0)throw Error(r.stderr);assertAllowed(store,id);res.writeHead(200,{'Content-Type':'application/zip','Content-Disposition':'attachment; filename="'+id+'.zip"','Cache-Control':'no-store'});res.end(fs.readFileSync(zip));return;}
 if(req.method==='POST'&&url.pathname==='/api/decisions'){const expected='http://'+req.headers.host;if(req.headers.origin!==expected)throw Error('같은 검토 화면에서 선택하세요');if(req.headers['content-type']!=='application/json')throw Error('JSON 요청만 허용합니다');const cookie=req.headers.cookie?.split(';').map(s=>s.trim()).find(s=>s.startsWith('casting_session='))?.slice(16);const token=req.headers['x-casting-csrf'];if(!equal(cookie,token)||!sessions.has(token)||sessions.get(token)<Date.now())throw Error('검토 세션이 만료되었습니다. 새로고침하세요');let bytes=0,body='';for await(const chunk of req){bytes+=chunk.length;if(bytes>16384)throw Error('요청이 너무 큽니다');body+=chunk;}const result=decide(store,JSON.parse(body));json(200,{item:result,saved:true});return;}
 json(404,{error:'없는 경로'});
 }catch(e){json(409,{error:e.message});}});
 await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,host,resolve);});const address=server.address();console.log(JSON.stringify({host,port:address.port,data,reviewUrl:'http://'+(host==='0.0.0.0'?'mdc-server':host)+':'+address.port+'/'}));server.once('close',()=>store.db.close());return server;
}
