import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {createHash} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {spawnSync} from 'node:child_process';
export const ROOT=path.resolve(import.meta.dirname,'../../../..');
export const DEFAULT_DATA=path.join(os.homedir(),'.local/share/oprn/pokemon-character-casting');
export const hash=b=>createHash('sha256').update(b).digest('hex');
export const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
export const save=(p,value)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(value,null,2)+'\n');};
export const ROLES=['hero','rival','professor','nurse','merchant','mother','resident','gym_leader','company_agent','captain','worker','explorer','student','ranger','moon_leader','hiker'];
export function native(args){const r=spawnSync(process.execPath,[path.join(ROOT,'src/harnesses/pokemon-character-motion/node/cli.mjs'),...args],{cwd:ROOT,encoding:'utf8',maxBuffer:8*1024*1024});if(r.status!==0)throw Error('네이티브 관문 실패: '+(r.stderr+r.stdout).slice(-2400));return r.stdout.trim();}
export function implementationSha(){return hash(['cli.ts','motion.ts','portrait.ts','../../monster-collect-species/pixel/grid.ts','../../monster-collect-species/pixel/image.ts','../../monster-collect-species/pixel/oklab.ts','../../monster-collect-species/node/png.ts'].map(f=>hash(fs.readFileSync(path.resolve(ROOT,'src/harnesses/pokemon-character-motion/node',f)))).join(':'));}
export function openStore(data=DEFAULT_DATA){data=path.resolve(data);fs.mkdirSync(data,{recursive:true});const db=new DatabaseSync(path.join(data,'casting.sqlite'));db.exec(`PRAGMA journal_mode=WAL;PRAGMA busy_timeout=5000;CREATE TABLE IF NOT EXISTS candidates(id TEXT PRIMARY KEY,role TEXT NOT NULL,package_sha TEXT NOT NULL,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS decisions(seq INTEGER PRIMARY KEY AUTOINCREMENT,candidate_id TEXT NOT NULL,package_sha TEXT NOT NULL,verdict TEXT NOT NULL CHECK(verdict IN ('allow','deny')),note TEXT NOT NULL,observed_json TEXT NOT NULL,at TEXT NOT NULL,client TEXT NOT NULL CHECK(client='browser-user'));CREATE TABLE IF NOT EXISTS candidate_lifecycle(candidate_id TEXT PRIMARY KEY,withdrawn INTEGER NOT NULL CHECK(withdrawn IN (0,1)),reason TEXT NOT NULL,at TEXT NOT NULL);`);return {data,db};}
function safeId(id){if(typeof id!=='string'||!/^[-a-z0-9]{1,100}$/.test(id))throw Error('잘못된 후보 id');return id;}
export function packageFor(store,id){safeId(id);const row=store.db.prepare('SELECT * FROM candidates WHERE id=?').get(id);if(!row)throw Error('후보가 없습니다');const folder=path.join(store.data,'candidates',id),raw=fs.readFileSync(path.join(folder,'package.json'));if(hash(raw)!==row.package_sha)throw Error('후보 설명이 변경되었습니다. 새 후보로 등록하세요');const pack=JSON.parse(raw);if(pack.id!==id||pack.role!==row.role||!ROLES.includes(pack.role))throw Error('후보 역할이 변경되었습니다');for(const [file,sha] of Object.entries(pack.files)){if(path.basename(file)!==file||fs.lstatSync(path.join(folder,file)).isSymbolicLink()||hash(fs.readFileSync(path.join(folder,file)))!==sha)throw Error('후보 그림·GIF·출처가 변경되었습니다. 재승인이 필요합니다');}if(pack.implementationSha256!==implementationSha())throw Error('네이티브 검사 구현이 변경되었습니다. 다시 등록하세요');for(const [file,sha] of Object.entries(pack.nativeFiles)){const name=path.join(folder,'native',file);if(path.basename(file)!==file||fs.lstatSync(name).isSymbolicLink()||hash(fs.readFileSync(name))!==sha)throw Error('네이티브 후보가 변경되었습니다. 재승인이 필요합니다');}return {row,pack,folder,packageSha256:row.package_sha};}
export function stateFor(store,id){let pkg;try{pkg=packageFor(store,id)}catch(e){const row=store.db.prepare('SELECT role FROM candidates WHERE id=?').get(id);let old={};try{old=read(path.join(store.data,'candidates',id,'package.json'));}catch{}return {id,role:row?.role,label:old.label??row?.role??id,variant:old.variant??'',description:old.description??'',state:'stale',error:e.message};}const d=store.db.prepare('SELECT * FROM decisions WHERE candidate_id=? ORDER BY seq DESC LIMIT 1').get(id);const lifecycle=store.db.prepare('SELECT withdrawn,reason FROM candidate_lifecycle WHERE candidate_id=?').get(id);let state=lifecycle?.withdrawn?'withdrawn':!d?'pending':d.package_sha!==pkg.packageSha256?'stale':d.verdict==='deny'?'denied':'allowed';if(state==='allowed'){const latest=store.db.prepare("SELECT d.* FROM decisions d JOIN candidates c ON c.id=d.candidate_id WHERE c.role=? AND d.verdict='allow' ORDER BY d.seq DESC LIMIT 1").get(pkg.pack.role);if(latest.candidate_id!==id)state='superseded';}return {...pkg.pack,id,state,withdrawalReason:lifecycle?.withdrawn?lifecycle.reason:null,packageSha256:pkg.packageSha256,decision:d?{seq:d.seq,note:d.note,at:d.at,verdict:d.verdict}:null};}
export function list(store){return store.db.prepare('SELECT id FROM candidates ORDER BY created_at,id').all().map(r=>stateFor(store,r.id));}
export function queue(store,bundle){bundle=path.resolve(bundle);const meta=read(path.join(bundle,'candidate.json'));if(!ROLES.includes(meta.role)||typeof meta.label!=='string'||typeof meta.variant!=='string')throw Error('후보 역할·이름·버전이 필요합니다');const names=['charset.png','walk.gif','context.png','origin.txt','recipe.json'];const files=Object.fromEntries(names.map(n=>[n,hash(fs.readFileSync(path.join(bundle,n)))]));const id=meta.role+'-'+hash(JSON.stringify({meta,files,implementation:implementationSha()})).slice(0,16);const existing=store.db.prepare('SELECT id FROM candidates WHERE id=?').get(id);if(existing){packageFor(store,id);return id;}
 const peerIds=store.db.prepare('SELECT id FROM candidates').all().map(r=>r.id).filter(peer=>{try{const p=packageFor(store,peer);return !store.db.prepare('SELECT withdrawn FROM candidate_lifecycle WHERE candidate_id=?').get(peer)?.withdrawn;}catch{return false;}});if(peerIds.length){const bundlesFile=path.join(store.data,'queue-diversity-bundles.json'),reportFile=path.join(store.data,'queue-diversity.json');save(bundlesFile,[bundle,...peerIds.map(peer=>path.join(store.data,'candidates',peer))]);const result=spawnSync('python3',[path.join(import.meta.dirname,'diversity.py'),'--bundles',bundlesFile,'--out',reportFile],{encoding:'utf8'});if(result.status!==0)throw Error('색이나 머리만 바꾼 동일 몸체 후보를 거부합니다. 체형·몸통·다리 원본을 구분하세요. '+result.stdout);}
 const folder=path.join(store.data,'candidates',id);if(fs.existsSync(folder))throw Error('불완전한 후보 폴더가 있습니다: '+id);fs.mkdirSync(folder,{recursive:true});try{for(const n of names)fs.copyFileSync(path.join(bundle,n),path.join(folder,n));const imported=native(['import','--native','--role',meta.role,'--source',path.join(folder,'charset.png'),'--prompt-file',path.join(folder,'origin.txt'),'--sandbox',path.join(folder,'scratch')]);const nativePath=imported.split('\n').at(-1);fs.renameSync(nativePath,path.join(folder,'native'));fs.rmSync(path.join(folder,'scratch'),{recursive:true,force:true});native(['check','--candidate',path.join(folder,'native')]);native(['preview','--candidate',path.join(folder,'native')]);const checked=read(path.join(folder,'native/check.json'));const proof=spawnSync('python3',[path.join(import.meta.dirname,'verify_bundle.py'),'--bundle',folder],{encoding:'utf8'});if(proof.status!==0)throw Error(proof.stderr);const media=JSON.parse(proof.stdout);const nativeFiles=Object.fromEntries(['source.png','prompt.txt','charset.png','provenance.json','preview.html','preview-receipt.json'].map(n=>[n,hash(fs.readFileSync(path.join(folder,'native',n)))]));if(nativeFiles['source.png']!==files['charset.png'])throw Error('원본 픽셀 해시 불일치');const pack={version:1,id,...meta,kind:'walking',files,nativeFiles,implementationSha256:implementationSha(),structural:{pass:checked.pass,errors:checked.errors},media,sourceSha256:files['charset.png'],scope:'Native walking candidate. Map context is a placement mockup, not runtime QA.'};save(path.join(folder,'package.json'),pack);const sha=hash(fs.readFileSync(path.join(folder,'package.json')));store.db.prepare('INSERT INTO candidates VALUES(?,?,?,?)').run(id,meta.role,sha,new Date().toISOString());return id;}catch(e){fs.rmSync(folder,{recursive:true,force:true});throw e;}}
export function decide(store,input){const {id,packageSha256,verdict}=input;if(!['allow','deny'].includes(verdict))throw Error('Allow 또는 Deny만 허용됩니다');const pkg=packageFor(store,id);if(packageSha256!==pkg.packageSha256)throw Error('화면의 후보가 변경되었습니다. 다시 읽으세요');const note=String(input.note??'').trim();if(note.length>1500)throw Error('이유는1500자 이하');const observed=input.observed??[];if(!Array.isArray(observed)||observed.some(s=>typeof s!=='string'))throw Error('검토 항목 오류');const required=['directions','gait','poses','context'];if(pkg.pack.base)required.push('identity');if(verdict==='allow'&&store.db.prepare('SELECT withdrawn FROM candidate_lifecycle WHERE candidate_id=?').get(id)?.withdrawn)throw Error('제작자가 철회한 이전 후보입니다. 현재 후보를 선택하세요');if(verdict==='allow'&&(!pkg.pack.structural.pass||required.some(k=>!observed.includes(k))))throw Error('네 방향·발 교대·12포즈·맵 배치를 모두 확인하세요');if(verdict==='deny'&&!note)throw Error('수정할 부분을 남겨주세요');const at=new Date().toISOString();store.db.exec('BEGIN IMMEDIATE');let seq;try{const r=store.db.prepare("INSERT INTO decisions(candidate_id,package_sha,verdict,note,observed_json,at,client) VALUES(?,?,?,?,?,?,'browser-user')").run(id,pkg.packageSha256,verdict,note,JSON.stringify(observed),at);seq=Number(r.lastInsertRowid);const receipt={version:1,seq,id,role:pkg.pack.role,packageSha256:pkg.packageSha256,sourceSha256:pkg.pack.sourceSha256,verdict,note,observed,at,client:'browser-user'};save(path.join(store.data,'receipts',seq+'.json'),receipt);store.db.exec('COMMIT');}catch(e){store.db.exec('ROLLBACK');throw e;}if(verdict==='allow'){native(['review','--candidate',path.join(pkg.folder,'native'),'--who','browser-user','--why',note||'사용자가 걷기와 포즈·배치를 확인하고 Allow함','--verdict','pass','--evidence',path.join(store.data,'receipts',seq+'.json')]);native(['gate','--candidate',path.join(pkg.folder,'native')]);}return stateFor(store,id);}
export function assertAllowed(store,id){const state=stateFor(store,id);if(state.state!=='allowed')throw Error('사용자의 현재 Allow가 없습니다: '+state.state);const pkg=packageFor(store,id),receipt=read(path.join(store.data,'receipts',state.decision.seq+'.json'));if(receipt.packageSha256!==pkg.packageSha256||receipt.verdict!=='allow'||receipt.sourceSha256!==pkg.pack.sourceSha256)throw Error('승인 영수증 불일치');const review=read(path.join(pkg.folder,'native/review.json'));if(!review.evidence.some(e=>e.sha256===hash(fs.readFileSync(path.join(store.data,'receipts',receipt.seq+'.json')))))throw Error('현재 사용자 판정이 네이티브 검수와 다릅니다');return {...pkg,decision:receipt};}
export function assertApprovedSource(data,role,sourceSha){if(!data)throw Error('새 걷기 후보는 사용자 Allow가 필요합니다. selection.humanReview.dataDir을 지정하세요');const store=openStore(data);try{const candidates=store.db.prepare('SELECT id FROM candidates WHERE role=?').all(role);for(const {id} of candidates){try{const pkg=assertAllowed(store,id);if(pkg.pack.sourceSha256===sourceSha)return {id,packageSha256:pkg.packageSha256,decisionSeq:pkg.decision.seq,nativeCandidate:path.join(pkg.folder,'native'),walkGifFile:path.join(pkg.folder,'walk.gif'),walkGifSha256:pkg.pack.files['walk.gif'],sourceRecipeFile:path.join(pkg.folder,'recipe.json'),sourceRecipeSha256:pkg.pack.files['recipe.json']};}catch{}}throw Error('이 역할·그림에 대한 현재 사용자 Allow가 없습니다: '+role);}finally{store.db.close();}}
export function buildApproved(store,id,out){const pkg=assertAllowed(store,id);native(['gate','--candidate',path.join(pkg.folder,'native')]);out=path.resolve(out);const forbidden=path.resolve(ROOT,'public');if(out===forbidden||out.startsWith(forbidden+path.sep)||out.startsWith(path.join(store.data,'candidates')+path.sep))throw Error('먼저 로컬 승인 결과를 만드세요. 공용 등록은 별도 단계입니다');native(['build','--candidate',path.join(pkg.folder,'native'),'--out',out]);assertAllowed(store,id);for(const name of ['walk.gif','recipe.json','origin.txt'])fs.copyFileSync(path.join(pkg.folder,name),path.join(out,name));save(path.join(out,'human-approval.json'),{...pkg.decision,dataDir:store.data,nativeCandidate:path.join(pkg.folder,'native'),packageSha256:pkg.packageSha256,editorPlacement:{assetId:'oprn_emerald_field_cast_'+(Math.floor(ROLES.indexOf(pkg.pack.role)/8)+1),slot:ROLES.indexOf(pkg.pack.role)%8,width:72,height:128,frameWidth:24,frameHeight:32,paddingX:4,resizing:false}});return {id,out,decisionSeq:pkg.decision.seq};}

export function activateWave(store,ids,reason){if(!ids.length)throw Error('Empty wave');for(const id of ids)packageFor(store,id);store.db.exec('BEGIN IMMEDIATE');try{const selected=new Set(ids),at=new Date().toISOString();for(const {id} of store.db.prepare('SELECT id FROM candidates').all())store.db.prepare('INSERT INTO candidate_lifecycle VALUES(?,?,?,?) ON CONFLICT(candidate_id) DO UPDATE SET withdrawn=excluded.withdrawn,reason=excluded.reason,at=excluded.at').run(id,selected.has(id)?0:1,selected.has(id)?'':reason,at);store.db.exec('COMMIT');}catch(e){store.db.exec('ROLLBACK');throw e;}return {current:ids.length,withdrawn:store.db.prepare('SELECT count(*) AS n FROM candidate_lifecycle WHERE withdrawn=1').get().n};}
