/** Focused approval plumbing verification. Every synthetic Allow/Deny uses a disposable copied store. Production decisions are read-only. */
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';import {chromium} from 'playwright';
import {openStore,DEFAULT_DATA,ROOT,list,read,assertAllowed,buildApproved,packageFor,hash} from './store.mjs';import {serve} from './server.mjs';
const args=process.argv.slice(2);let out;for(let i=0;i<args.length;i+=2){assert.equal(args[i],'--out');out=path.resolve(args[i+1]);}assert(out);fs.mkdirSync(out,{recursive:true});
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'pokemon-casting-qa-')),fixture=path.join(temp,'fixture'),live=openStore(DEFAULT_DATA),copy=openStore(fixture),checks=[];const check=(name,pass,details)=>{checks.push({name,pass,...(details?{details}:{})});if(!pass){fs.writeFileSync(path.join(out,'failed-record.json'),JSON.stringify({name,details,checks},null,2));console.error(JSON.stringify({name,details}));}assert(pass,name)};let server,browser;
try{
 const production=list(live);const before=live.db.prepare('SELECT count(*) AS n FROM decisions').get().n;check('production has six structurally checked candidates and no automated decisions',production.length===6&&production.every(i=>i.structural.pass&&i.state==='pending')&&before===0);
 const rows=live.db.prepare('SELECT * FROM candidates').all();for(const row of rows){fs.cpSync(path.join(DEFAULT_DATA,'candidates',row.id),path.join(fixture,'candidates',row.id),{recursive:true});copy.db.prepare('INSERT INTO candidates VALUES(?,?,?,?)').run(row.id,row.role,row.package_sha,row.created_at);}
 const first=production.find(i=>i.role==='rival'&&i.variant==='A'),second=production.find(i=>i.role==='rival'&&i.variant==='B');
 assert.throws(()=>buildApproved(copy,first.id,path.join(temp,'pending-output')),/Allow/);check('pending candidate cannot build',!fs.existsSync(path.join(temp,'pending-output')));
 server=await serve({data:fixture,host:'127.0.0.1',port:18586});const url='http://127.0.0.1:18586';browser=await chromium.launch({args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1100,height:900}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('requestfailed',r=>errors.push(r.url()+':'+r.failure()?.errorText));await page.goto(url);await page.waitForSelector('.pick');await page.locator('.pick[data-id="'+first.id+'"]').click();await page.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth));check('Allow stays disabled until four observations checked',await page.locator('#allow').isDisabled());
 await page.locator('#phase').fill('2');check('frame slider freezes visible native/correct integer-scale previews',await page.locator('#paused-large').isVisible()&&await page.locator('#paused-native').isVisible());const pixels=await page.locator('#paused-native').evaluate(c=>({size:[c.width,c.height],rgba:[...c.getContext('2d').getImageData(0,0,c.width,c.height).data]}));check('frame slider produces native68x32 texture pixels',pixels.size.join(',')==='68,32'&&pixels.rgba.some((v,i)=>i%4===3&&v===255));await page.locator('#pause').click();check('GIF animation can resume',await page.locator('.gif').first().isVisible()&&!await page.locator('#paused-native').isVisible());
 const bad=await page.evaluate(async({id,packageSha256})=>{const s=await(await fetch('/api/session')).json();const r=await fetch('/api/decisions',{method:'POST',headers:{'Content-Type':'application/json','X-Casting-CSRF':s.csrf},body:JSON.stringify({id,packageSha256,verdict:'allow',observed:[],note:''})});await r.text();return r.status;},{id:first.id,packageSha256:first.packageSha256});check('server rejects Allow with missing observations',bad===409);await page.reload();await page.waitForSelector('.pick');await page.locator('.pick[data-id="'+first.id+'"]').click();
 for(const input of await page.locator('.checks input').all())await input.check();await page.locator('#note').fill('QA fixture only: observed poses. Not a production user approval.');await page.locator('#allow').click();await page.waitForFunction(()=>document.getElementById('notice').textContent.includes('Allow 저장 완료'));check('browser Allow persists and enables native gate/build',assertAllowed(copy,first.id).decision.verdict==='allow');const built=buildApproved(copy,first.id,path.join(temp,'approved-output'));check('approved build preserves native/output dimensions and receipt',fs.existsSync(path.join(built.out,'editor-charset.png'))&&read(path.join(built.out,'human-approval.json')).packageSha256===first.packageSha256);
 await page.reload();await page.waitForSelector('.pick');await page.locator('.pick[data-id="'+first.id+'"]').click();check('decision survives browser reload',await page.locator('#download').count()===1);const download=await context.request.get(url+'/download/'+first.id+'.zip');check('approved package download is actual zip',download.status()===200&&(await download.body()).subarray(0,2).toString()==='PK');
 await page.locator('#note').fill('QA fixture only: revoke prior approval.');await page.locator('#deny').click();await page.waitForFunction(()=>document.getElementById('notice').textContent.includes('Deny 저장 완료'));assert.throws(()=>buildApproved(copy,first.id,path.join(temp,'denied-output')),/denied/);check('Deny revokes old approval and blocks download', (await context.request.get(url+'/download/'+first.id+'.zip')).status()===409);
 await page.locator('.pick[data-id="'+first.id+'"]').click();for(const input of await page.locator('.checks input').all())await input.check();await page.locator('#allow').click();await page.waitForFunction(()=>document.getElementById('notice').textContent.includes('Allow 저장 완료'));await page.locator('.pick[data-id="'+second.id+'"]').click();for(const input of await page.locator('.checks input').all())await input.check();await page.locator('#allow').click();await page.waitForFunction(()=>document.getElementById('notice').textContent.includes('Allow 저장 완료'));assert.throws(()=>assertAllowed(copy,first.id),/superseded/);check('role has one current Allow and switching variants invalidates old build permission',assertAllowed(copy,second.id).decision.verdict==='allow');
 const folder=packageFor(copy,second.id).folder,old=fs.readFileSync(path.join(folder,'walk.gif'));fs.appendFileSync(path.join(folder,'walk.gif'),'tampered');assert.throws(()=>assertAllowed(copy,second.id),/stale/);check('changed GIF makes approval stale',list(copy).find(i=>i.id===second.id).state==='stale');fs.writeFileSync(path.join(folder,'walk.gif'),old);
 const csrfReject=await page.evaluate(async()=>{const r=await fetch('/api/decisions',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await r.text();return r.status;});check('mutation requires active same-origin browser session/CSRF',csrfReject===409);check('browser has no JavaScript/resource errors',errors.length===0,errors);await context.close();await browser.close();browser=null;await new Promise(r=>server.close(r));server=null;
 const reopened=openStore(fixture);check('SQLite reopening preserves approvals and deny reasons',reopened.db.prepare('SELECT count(*) AS n FROM decisions').get().n===4&&list(reopened).find(i=>i.id===second.id).state==='allowed');reopened.db.close();
 const generation=read(path.join(ROOT,'public/assets/harnesses/pokemon-character-motion/emerald/generation.json'));const selection={walk:{},trainers:{},clip:null};for(const entry of generation.roles){if(entry.role.startsWith('trainer-'))selection.trainers[entry.role.slice(8)]=entry.source;else if(entry.role==='professor-intro')selection.clip=entry.source;else selection.walk[entry.role]=entry.source;}selection.walk.rival=path.join(DEFAULT_DATA,'candidates',first.id,'native');selection.humanReview={dataDir:DEFAULT_DATA};const file=path.join(temp,'selection.json');fs.writeFileSync(file,JSON.stringify(selection));const watched=['public/assets/emerald-monster/cast/cast-1.png','public/assets/emerald-monster/cast/cast-2.png','public/assets/harnesses/pokemon-character-motion/emerald/generation.json'],saved=watched.map(n=>hash(fs.readFileSync(path.join(ROOT,n))));const rejection=spawnSync(process.execPath,[path.join(ROOT,'scripts/content/register-pokemon-character-motion.mjs'),file],{cwd:ROOT,encoding:'utf8'});check('shared registrar blocks unapproved changed NPC before any writes',rejection.status!==0&&rejection.stderr.includes('Allow')&&watched.every((n,i)=>hash(fs.readFileSync(path.join(ROOT,n)))===saved[i]));
 const publicContext=await (browser=await chromium.launch({args:['--no-sandbox']})).newContext({viewport:{width:1100,height:900}}),livePage=await publicContext.newPage();await livePage.goto('http://mdc-server:18316/');await livePage.waitForSelector('.pick');await livePage.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth));for(const width of [1100,320]){await livePage.setViewportSize({width,height:900});await livePage.screenshot({path:path.join(out,'live-'+width+'.png'),fullPage:true});const dimensions=await livePage.evaluate(()=>({documentWidth:document.documentElement.scrollWidth,viewport:innerWidth,gifs:[...document.querySelectorAll('.gif')].map(i=>({native:[i.naturalWidth,i.naturalHeight],display:[i.width,i.height]}))}));check('live review fits'+width+'px and preserves native68x32 GIF',dimensions.documentWidth===width&&dimensions.gifs.every(i=>i.native.join(',')==='68,32'),dimensions);}check('live page never auto-approves real candidates',live.db.prepare('SELECT count(*) AS n FROM decisions').get().n===before&&list(live).every(i=>i.state==='pending'));await publicContext.close();
 const record={pass:true,scope:'Isolated copied candidate store exercises synthetic browser Allow/Deny. Production browser viewing and pending registrar rejection are read-only with zero real decisions.',productionData:DEFAULT_DATA,fixtureData:fixture,productionDecisionCount:before,checks};fs.writeFileSync(path.join(out,'record.json'),JSON.stringify(record,null,2)+'\n');fs.writeFileSync(path.join(out,'SUMMARY.md'),'# Character casting QA\n\n'+checks.length+' focused checks passed. Production decisions: '+before+'. Synthetic approvals are only in disposable fixture storage.\n\nInspect live-320.png first.\n\n'+checks.map(c=>'- PASS '+c.name).join('\n')+'\n');console.log(JSON.stringify({pass:true,checks:checks.length,productionDecisions:before,out}));
}finally{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));live.db.close();copy.db.close();}
