import { mkdir } from "node:fs/promises";
import { chromium } from 'playwright';
await mkdir("output/evidence/village-design", { recursive: true });
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1586,height:992}});
page.setDefaultTimeout(20000);
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{for(const key of ['oprn:editor-welcome-dismissed','oprn:standard-welcome-seen','oprn:coachmarks-basic-v1'])localStorage.setItem(key,'1');localStorage.setItem('rpg-zzu:editor-ui-mode','expert');});
await page.goto(`${process.env.VILLAGE_QA_URL ?? 'http://127.0.0.1:40261'}/?blankProject=1`,{waitUntil:'domcontentloaded'});
await page.getByTestId('edit-canvas').waitFor({timeout:120000});
for(const id of ['login-guest','standard-welcome-start','coach-mark-skip'])if(await page.getByTestId(id).isVisible())await page.getByTestId(id).click();
await page.getByTestId('toolbar-database').click();
if(!await page.getByTestId('db-tab-villages').isVisible())await page.getByTestId('db-tab-group-world').click();
await page.getByTestId('db-tab-villages').click();
await page.getByTestId('db-village-kind-preset').click();
await page.getByTestId('db-village-create').click();
await page.getByTestId('db-village-design-studio').waitFor();
await page.screenshot({path:'output/evidence/village-design/houses-1586.png'});
await page.getByTestId('db-village-design-tab-layout').click();
await page.getByTestId('db-village-design-count-min').fill('4');await page.getByTestId('db-village-design-count-min').press('Tab');
await page.getByTestId('db-village-design-tab-interior').click();await page.getByTestId('db-village-design-interior').uncheck();
await page.getByTestId('db-village-design-tab-houses').click();
await page.getByTestId('db-village-preset-preview-run').click();
await page.waitForFunction(()=>document.querySelector('[data-testid="db-village-preset-preview"]')?.dataset.previewState!=='idle');
await page.screenshot({path:'output/evidence/village-design/preview-1586.png'});
const preview=await page.getByTestId('db-village-preset-preview-note').innerText();
for(const tab of ['mood','houses','layout','nature','interior','residents'])await page.getByTestId('db-village-design-tab-'+tab).click();
await page.getByTestId('db-village-design-tab-nature').click();
await page.getByTestId('db-village-design-water-kind').selectOption('river');
await page.getByTestId('db-village-design-forest-density').selectOption('dense');
await page.screenshot({path:'output/evidence/village-design/nature-1586.png'});
const sizes=[];for(const width of [1280,1024]){await page.setViewportSize({width,height:900});sizes.push(await page.getByTestId('db-village-design-studio').evaluate(el=>({width:innerWidth,overflow:el.scrollWidth-el.clientWidth})));await page.screenshot({path:`output/evidence/village-design/nature-${width}.png`});}
const settings={water:await page.getByTestId('db-village-design-water-kind').inputValue(),forest:await page.getByTestId('db-village-design-forest-density').inputValue()};
console.log(JSON.stringify({errors,preview,sizes,settings},null,2));
if(errors.length || !preview.includes('집 4채') || sizes.some(size=>size.overflow>0))throw new Error('Browser contract failed');
await browser.close();
