#!/usr/bin/env python3
"""새 기물 8차 — 장르를 넓힌다(2026-10-03, 사용자 「이 에디터 사용자가 더이상 에셋을 안 만들어도 될정도로 졸라 다양한 에셋들」).
지금 시트·새 기물(1~7차)에 없는 장르: 동양(조선·일본·중국) · SF 우주선 · 공장·스팀펑크 · 아틀리에·음악 · 계절 행사 · 동물 ·
캠핑 · 사막 · 설국 · 해적 · 마법학교 · 요정·드워프 · 우체국·은행·서점·전당포 · 현대 운동·취미 · 병원·편의점 더하기 · 공포 폐가 더하기.
거의 1~2칸. 대형(밑그림이 필요한 3×2 이상)은 넣지 않았다. 후보는 판마다 2장(N_DEFAULT).
  python3 tiledata/hand-interior/new/batch8.py   # items.json 에 덧붙인다(같은 id 는 건너뛴다)
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import batch2  # noqa: E402
import batch7  # noqa: E402,F401  (분류 이름표)

batch2.CAT.update({'east': '동양 실내', 'scifi': 'SF 우주선', 'factory': '공장·스팀펑크', 'atelier': '아틀리에·음악', 'season': '계절·행사',
                   'pet': '동물', 'camp': '캠핑', 'desert': '사막', 'snowland': '설국', 'pirate': '해적선', 'school_magic': '마법학교',
                   'fairy': '요정·드워프', 'town': '마을 관청·가게', 'm_hobby': '현대 운동·취미'})

# (id, 이름, 분류, kind, 폭칸, 발밑칸, 캔버스W, H, 맥락 방, use, 설명, 놓는 곳, 짝, refs, 태그)
I = [
 # ── 동양 실내 ──
 ('tatami mat', '다다미', 'east', 'flat', 1, 2, 16, 32, 'hobbit', ['walk'],
  '바닥에 깐 다다미 한 장(1×2칸 남북, 밟을 수 있음) — 연두빛 짚 결이 가로로 촘촘하고 긴 두 변에 검푸른 천 테.', '일본식 방 바닥(여러 장 이어 깐다).', ['zabuton'], ['runner'], ['동양', '일본', '방']),
 ('zabuton', '방석', 'east', 'flat', 1, 1, 16, 16, 'hobbit', ['sit'],
  '바닥에 놓은 네모 방석(밟을 수 있음) — 쪽빛 천, 가운데 술 하나와 눌린 자국.', '좌식 상 둘레.', ['low dining tray'], ['round rug'], ['동양', '방']),
 ('low dining tray', '좌식 밥상', 'east', 'floor', 1, 1, 16, 16, 'hobbit', ['read'],
  '다리가 짧은 붉은 칠 밥상(8px 높이). 상판 윗면 6행에 밥그릇·국그릇·반찬 접시 셋과 수저, 남쪽 면에 상판 두께 1행과 다리.', '좌식 방 가운데.', ['zabuton'], ['tea 2x2'], ['동양', '조선', '방']),
 ('futon bedding', '요와 이불', 'east', 'flat', 1, 2, 16, 32, 'hobbit', ['sleep'],
  '바닥에 편 요(1×2칸 남북, 밟을 수 있음) — 북쪽 끝 메밀 베개, 남쪽으로 덮은 꽃무늬 솜이불, 아래 흰 요 가장자리가 비친다.', '좌식 방 바닥.', ['folding screen'], ['straw bed'], ['동양', '침실']),
 ('mother of pearl chest', '자개장', 'east', 'wall', 2, 1, 32, 32, 'manor', ['search'],
  '검은 옻칠 자개장(2칸, 16px 솟음). 꼭대기 윗면 3행, 남쪽 면 문짝 넷에 무지갯빛 자개 학·꽃 무늬, 놋쇠 경첩과 고리.', '안방 북쪽 벽.', ['futon bedding'], ['wardrobe'], ['동양', '조선', '안방']),
 ('bandaji chest', '반닫이', 'east', 'wall', 1, 1, 16, 32, 'manor', ['search'],
  '나무 반닫이 궤(12px 솟음). 뚜껑 윗면 4행, 남쪽 면 위쪽 절반이 앞으로 여는 문, 큰 놋쇠 경첩판과 자물쇠 장식.', '방 벽 앞.', ['mother of pearl chest'], ['chest'], ['동양', '조선']),
 ('low writing desk', '서안', 'east', 'floor', 1, 1, 16, 16, 'scholar', ['read'],
  '낮은 나무 서안(10px 높이). 상판 윗면 6행에 펼친 한지 책·붓 걸이·벼루, 양끝이 살짝 말려 올라간 판, 짧은 다리.', '사랑방 창가.', ['zabuton'], ['desk 1x1'], ['동양', '조선', '서재']),
 ('hanging scroll', '족자', 'east', 'hang', 1, 0, 16, 16, 'scholar', ['read'],
  '벽에 건 세로 족자(벽면 윗줄) — 위아래 나무 축, 흰 비단에 먹으로 그린 대나무 한 그루.', '방 벽 윗줄.', [], ['picture'], ['동양', '서재']),
 ('paper lantern stand', '등롱', 'east', 'floor', 1, 1, 16, 32, 'hobbit', ['light'],
  '나무 받침 위의 네모 한지 등롱(16px 솟음). 꼭대기 윗면 2행, 사면 한지가 안의 촛불로 노랗게 빛나고 나무 살 격자.', '방 구석·복도.', ['futon bedding'], ['candle stand'], ['동양', '방']),
 ('jangdok jars', '장독 무리', 'east', 'floor', 1, 1, 16, 32, 'hobbit', ['search'],
  '갈색 옹기 장독 셋(큰 것 하나 작은 것 둘, 14px 솟음). 독마다 둥근 뚜껑 윗면 3행이 밝고 배가 불룩, 유약 광택 한 점.', '부엌 뒤·광.', ['clay cook hearth'], ['water jar', 'pot'], ['동양', '조선', '부엌']),
 ('ancestral offering table', '제사상', 'east', 'floor', 2, 1, 32, 32, 'chapel', ['read'],
  '붉은 칠 제사상(2칸, 12px 솟음). 상판 윗면 7행에 과일 접시(사과·배·감)·떡·향로·촛대 둘·위패, 남쪽 면에 다리와 앞 장식.', '대청 북쪽.', ['incense burner'], ['altar'], ['동양', '조선', '제사']),
 ('kamidana shelf', '가미다나', 'east', 'hang', 1, 0, 16, 16, 'hobbit', ['read'],
  '벽 높은 곳의 작은 신단 선반(벽면 윗줄) — 흰 나무 사당 모양, 앞에 금줄과 흰 종이 술, 작은 술병 둘.', '일본식 방 벽 윗줄.', [], ['shelf:candle'], ['동양', '일본']),
 ('samurai armor display', '사무라이 갑옷', 'east', 'floor', 1, 1, 16, 32, 'throne', ['read'],
  '받침 상자 위에 앉힌 붉은 실 사무라이 갑옷(16px 솟음). 투구 윗면 3행과 금 뿔 장식, 가슴판 가로 띠, 받침 윗면 2행.', '무가 저택 대청.', ['katana rack'], ['armor stand'], ['동양', '일본', '무가']),
 ('katana rack', '도검 걸이', 'east', 'floor', 1, 1, 16, 16, 'throne', ['read'],
  '낮은 검은 칠 받침에 가로로 얹은 칼 둘(10px 높이). 받침 윗면 5행, 칼집은 검고 손잡이는 마름모 끈 무늬.', '도장·무가 저택.', ['samurai armor display'], ['weapon rack'], ['동양', '일본', '무가']),
 ('noren curtain', '노렌', 'east', 'hang', 2, 0, 32, 16, 'tavern', ['read'],
  '문 위에 늘어뜨린 쪽빛 천 노렌(벽면 윗줄 2칸) — 세 폭으로 갈라지고 가운데 흰 둥근 문양.', '가게·주방 입구 위.', [], ['curtained window'], ['동양', '일본', '가게']),
 ('mahjong table', '마작 탁자', 'east', 'floor', 2, 2, 32, 32, 'casino', ['read'],
  '초록 펠트 네모 마작 탁자(2×2칸, 12px 높이). 남쪽 위에서 내려다본 3/4: 꼭대기 윗면 22행 — 초록 판 위에 네 변으로 늘어선 흰 패 줄과 가운데 주사위 둘, 그 아래 남쪽 면에 나무 테 두께 3행과 다리.', '찻집·도박장.', ['stool'], ['felt 2x2'], ['동양', '중국', '도박']),
 ('bamboo blind', '대나무 발', 'east', 'hang', 1, 0, 16, 16, 'hobbit', ['read'],
  '창에 내린 대나무 발(벽면 윗줄) — 가는 가로 대 줄, 아래 끝을 말아 끈으로 묶었다.', '방 창 윗줄.', [], ['curtained window'], ['동양', '여름']),
 ('tea brazier set', '다기와 풍로', 'east', 'floor', 1, 1, 16, 16, 'hobbit', ['search'],
  '작은 흙 풍로 위 쇠 주전자와 옆의 찻잔 둘(10px 높이). 주전자 뚜껑 윗면 3행, 풍로 구멍의 주황 불씨.', '다실·사랑방.', ['low writing desk'], ['stove'], ['동양', '다실']),
 ('buddhist altar cabinet', '불단', 'east', 'wall', 1, 1, 16, 32, 'chapel', ['read'],
  '검은 칠 금장 불단(16px 솟음). 지붕 모양 꼭대기 윗면 3행, 열린 문 안 금빛 불상 하나와 촛대·꽃병, 아래 서랍.', '집 안쪽 벽.', ['incense burner'], ['reredos'], ['동양', '일본', '신앙']),
 ('chinese moon screen', '둥근 창 병풍', 'east', 'floor', 2, 1, 32, 48, 'tower', ['block'],
  '붉은 나무 틀에 둥근 달 창을 뚫은 칸막이(2칸, 32px 솟음). 위 가로대 윗면 2행, 둥근 창 안으로 뒤 벽이 비치고 둘레에 꽃살 격자.', '중국풍 방 칸막이.', ['mahjong table'], ['folding screen'], ['동양', '중국']),
 # ── SF 우주선 ──
 ('cryo pod', '냉동 수면 캡슐', 'scifi', 'floor', 1, 2, 16, 48, 'magitek', ['sleep'],
  '흰 냉동 수면 캡슐(1×2칸 남북, 16px 솟음). 남쪽 위에서 내려다본 3/4: 꼭대기 윗면 26행 — 둥근 유리 덮개 너머 하늘빛 냉기와 잠든 사람 실루엣, 덮개 둘레 흰 껍데기와 파란 불빛 띠. 남쪽 면에 조작판.', '우주선 수면실 줄로.', ['ship console'], ['coffin'], ['SF', '우주선']),
 ('holo table', '홀로그램 탁자', 'scifi', 'floor', 2, 2, 32, 48, 'magitek', ['read'],
  '둥근 금속 작전 탁자(2×2칸, 12px 높이) 위에 떠 있는 하늘빛 행성 홀로그램(16px 위로). 남쪽 위에서 내려다본 3/4: 꼭대기 윗면 22행 — 빛나는 원판과 격자선, 그 아래 남쪽 면에 테 두께 3행과 불빛 띠.', '함교 가운데.', ['ship console'], ['war table'], ['SF', '우주선', '함교']),
 ('ship console', '우주선 조종판', 'scifi', 'wall', 2, 1, 32, 32, 'magitek', ['read'],
  '벽에 붙은 금속 조종판(2칸, 16px 솟음). 기운 판 윗면 6행에 화면 둘(초록 레이더·파란 그래프)과 색 버튼 줄, 남쪽 면에 흰 패널과 환기 틈.', '함교·기관실 벽.', ['captain seat sf'], ['control console'], ['SF', '우주선']),
 ('captain seat sf', '함장 의자', 'scifi', 'floor', 1, 1, 16, 32, 'magitek', ['sit'],
  '흰 껍데기 함장 의자(16px 솟음), 남쪽을 본다. 좌판 윗면 4행, 둥근 등받이 윗면 2행, 팔걸이 끝 작은 조작판(불빛), 원기둥 받침.', '함교 가운데.', ['ship console'], ['armchair'], ['SF', '우주선', '함교']),
 ('robot charger', '로봇 충전대', 'scifi', 'wall', 1, 1, 16, 48, 'magitek', ['search'],
  '벽 충전대에 선 작은 둥근 로봇(32px 솟음). 로봇 머리 윗면 3행과 파란 눈 둘, 등 뒤 충전 케이블, 아래 원형 받침판.', '정비실 벽.', ['ship console'], ['mannequin'], ['SF', '정비실']),
 ('spacesuit locker', '우주복 보관함', 'scifi', 'wall', 1, 1, 16, 48, 'magitek', ['search'],
  '유리문 보관함 안의 흰 우주복(32px 솟음). 보관함 꼭대기 윗면 2행, 유리 너머 헬멧 둥근 창과 몸통 주황 띠.', '에어록 옆 벽.', ['robot charger'], ['armor stand'], ['SF', '우주선']),
 ('regen tank', '재생 탱크', 'scifi', 'floor', 1, 1, 16, 48, 'magitek', ['search'],
  '초록 액체가 든 유리 원통 탱크(32px 솟음). 금속 뚜껑 윗면 2행, 원통 안 떠오르는 거품, 아래 받침과 관.', '의무실.', ['cryo pod'], ['fish tank'], ['SF', '의무실', '실험실']),
 ('cargo container', '화물 컨테이너', 'scifi', 'floor', 2, 1, 32, 32, 'magitek', ['block'],
  '골진 금속 화물 상자(2칸, 16px 솟음). 꼭대기 윗면 5행에 노란 경고 띠 모서리, 남쪽 면에 세로 골·문 손잡이·번호 표.', '화물칸.', ['robot charger'], ['crate'], ['SF', '화물칸', '부두']),
 ('hydroponic rack', '수경 재배 선반', 'scifi', 'wall', 2, 1, 32, 32, 'magitek', ['search'],
  '보라 생장등 아래 수경 재배 선반(2칸, 16px 솟음). 위 등 윗면 2행, 두 단 판마다 초록 새싹 줄, 관 따라 흐르는 물빛.', '우주선 농장·연구소.', ['ship console'], ['seedling shelf'], ['SF', '농장']),
 ('space window', '우주 창', 'scifi', 'hang', 2, 0, 32, 16, 'magitek', ['read'],
  '벽 윗줄의 둥근 모서리 큰 창(2칸) — 검은 우주에 별 점과 푸른 행성 반쪽, 금속 테.', '함교·선실 벽 윗줄.', [], ['round window'], ['SF', '우주선']),
 ('energy core', '에너지 핵', 'scifi', 'floor', 1, 1, 16, 48, 'magitek', ['light'],
  '금속 고리 셋에 둘러싸인 빛나는 하늘빛 구(32px 솟음). 구 꼭대기가 가장 밝고, 고리 윗면이 밝다, 아래 받침과 관.', '기관실 가운데.', ['ship console'], ['magitek engine'], ['SF', '기관실']),
 ('laser rifle rack', '광선총 걸이', 'scifi', 'hang', 1, 0, 16, 16, 'magitek', ['search'],
  '벽 고정대에 건 흰 광선총 둘(벽면 윗줄) — 총열 끝 파란 렌즈, 아래 작은 충전 불빛.', '무기고 벽 윗줄.', [], ['weapon rack'], ['SF', '무기고']),
 ('teleporter pad sf', '전송 패드', 'scifi', 'flat', 1, 1, 16, 16, 'magitek', ['walk'],
  '바닥의 둥근 금속 전송 패드(밟을 수 있음) — 가운데 빛나는 하늘빛 원과 둘레 점 불빛 여섯.', '전송실 바닥.', ['ship console'], ['teleport circle'], ['SF', '우주선']),
 ('med bay bed', '의무실 침대', 'scifi', 'floor', 1, 2, 16, 48, 'magitek', ['sleep'],
  '흰 금속 진단 침대(1×2칸 남북, 12px 솟음). 남쪽 위에서 내려다본 3/4: 꼭대기 윗면 26행 — 파란 패드와 북쪽 베개, 머리맡 위 진단 화면 판(윗면 2행), 침대 둘레 파란 불빛 띠. 남쪽 면은 기둥 받침.', '의무실.', ['regen tank'], ['hospital bed'], ['SF', '의무실']),
 # ── 공장·스팀펑크 ──
 ('conveyor belt', '컨베이어 벨트', 'factory', 'floor', 2, 1, 32, 32, 'magitek', ['block'],
  '쇠 틀 위 검은 고무 벨트(2칸, 12px 솟음). 벨트 윗면 6행에 가로 마디 줄과 실린 나무 상자 하나, 양끝 둥근 굴대, 남쪽 면에 쇠 다리.', '공장 작업장.', ['pressure tank'], ['mine cart'], ['공장']),
 ('pressure tank', '압력 탱크', 'factory', 'floor', 1, 1, 16, 48, 'magitek', ['block'],
  '세운 놋쇠 압력 탱크(32px 솟음). 둥근 머리 윗면 3행과 압력계·밸브 바퀴, 몸통 리벳 띠, 아래 받침 다리.', '보일러실.', ['valve wheel'], ['steam boiler'], ['공장', '스팀펑크']),
 ('valve wheel', '밸브 바퀴', 'factory', 'hang', 1, 0, 16, 16, 'magitek', ['switch'],
  '벽 관에 달린 붉은 밸브 바퀴(벽면 윗줄) — 바퀴 살 넷, 관은 놋쇠, 옆에 작은 압력계.', '기관실 벽 윗줄.', ['pressure tank'], ['wall lever'], ['공장', '스팀펑크']),
 ('lathe machine', '선반 기계', 'factory', 'floor', 2, 1, 32, 32, 'smithy', ['search'],
  '쇠 선반 기계(2칸, 16px 솟음). 위 윗면 5행에 물린 쇠막대와 깎는 날, 서쪽 굴대 상자, 남쪽 면에 핸들 바퀴 둘과 기름때.', '작업장.', ['tool cart'], ['grindstone'], ['공장', '작업장']),
 ('tool cart', '공구 수레', 'factory', 'floor', 1, 1, 16, 32, 'smithy', ['search'],
  '빨간 철제 공구 수레(14px 솟음). 위 판 윗면 5행에 렌치·망치·드라이버, 서랍 셋, 아래 바퀴.', '작업장.', ['lathe machine'], ['tool wall'], ['공장', '정비소', '현대']),
 ('oil drum', '기름 드럼통', 'factory', 'floor', 1, 1, 16, 32, 'magitek', ['block'],
  '파란 철제 드럼통(16px 솟음). 둥근 뚜껑 윗면 4행에 마개 둘, 몸통 가로 테 둘과 흘러내린 검은 기름 자국.', '창고·정비소.', ['tool cart'], ['barrel'], ['공장', '창고']),
 ('pallet boxes', '팔레트 짐', 'factory', 'floor', 2, 1, 32, 32, 'magitek', ['block'],
  '나무 팔레트 위에 쌓은 종이 상자 넷(2칸, 16px 솟음). 맨 위 상자 윗면 5행에 테이프 줄, 남쪽 면에 상자 옆면과 팔레트 틈.', '창고.', ['cargo container'], ['crate'], ['공장', '창고', '현대']),
 ('wall fan industrial', '공장 환풍기', 'factory', 'hang', 1, 0, 16, 16, 'magitek', ['block'],
  '벽 윗줄의 둥근 철망 환풍기(1칸) — 날개 넷이 비치고 둘레 쇠 테, 먼지 낀 그늘.', '공장 벽 윗줄.', [], ['gear wall'], ['공장']),
 ('steam automaton', '증기 자동인형', 'factory', 'floor', 1, 1, 16, 48, 'magitek', ['read'],
  '놋쇠 증기 자동인형(32px 솟음), 남쪽을 본다. 둥근 머리 윗면 2행과 렌즈 눈, 가슴 압력계, 등에서 오르는 김 한 줄, 굵은 쇠다리.', '스팀펑크 공방.', ['pressure tank'], ['magitek armor'], ['스팀펑크', '공방']),
 ('punch clock', '출근 기록기', 'factory', 'wall', 1, 1, 16, 32, 'magitek', ['read'],
  '벽의 출근 기록기와 카드꽂이(16px 솟음). 위 시계 얼굴, 가운데 카드 넣는 틈, 옆 꽂이에 종이 카드 줄.', '공장 입구 벽.', [], ['wall clock'], ['공장']),
 ('big scale', '큰 저울', 'factory', 'floor', 1, 1, 16, 32, 'butcher', ['read'],
  '바닥 쇠 저울판과 기둥 눈금(16px 솟음). 저울판 윗면 4행에 자루 하나, 뒤 기둥 꼭대기 둥근 눈금판.', '방앗간·창고.', ['sack:grain'], ['balance scale'], ['창고', '가게']),
 # ── 아틀리에·음악 ──
 ('easel canvas', '이젤과 캔버스', 'atelier', 'floor', 1, 1, 16, 48, 'opera', ['read'],
  '나무 이젤에 세운 그리다 만 캔버스(32px 솟음). 캔버스 위 테 윗면 1행, 앞면에 푸른 하늘과 언덕 그림, 이젤 다리 셋.', '화가 작업실.', ['paint table'], ['picture'], ['아틀리에']),
 ('paint table', '물감 탁자', 'atelier', 'floor', 1, 1, 16, 32, 'opera', ['search'],
  '물감 묻은 작은 탁자(12px 솟음). 상판 윗면 6행에 팔레트 판(색 점 여섯)·붓 꽂은 병·물감 튜브, 남쪽 면에 물감 얼룩.', '이젤 옆.', ['easel canvas'], ['table:potion+flask'], ['아틀리에']),
 ('sculpture stand', '조각대', 'atelier', 'floor', 1, 1, 16, 48, 'opera', ['read'],
  '돌림 받침 위의 깎다 만 흰 돌 조각(32px 솟음) — 머리 윗면 2행은 매끈하고 아래는 거친 덩이, 받침 윗면 2행과 끌 하나.', '조각가 작업실.', ['easel canvas'], ['statue'], ['아틀리에']),
 ('canvas stack', '캔버스 더미', 'atelier', 'floor', 1, 1, 16, 32, 'opera', ['block'],
  '벽에 기대 세운 캔버스 여럿(16px 솟음) — 맨 앞은 뒤판(나무 틀 십자), 뒤로 그림 모서리 셋이 삐져나온다.', '작업실 구석.', ['easel canvas'], ['picture'], ['아틀리에']),
 ('drum kit', '드럼 세트', 'atelier', 'floor', 2, 1, 32, 32, 'opera', ['read'],
  '드럼 세트(2칸, 16px 솟음). 위에서 본 북 윗면(흰 둥근 가죽) 넷과 금빛 심벌즈 둘, 가운데 큰 베이스 드럼 앞면(남쪽)과 의자.', '무대·연습실.', ['amp speaker'], ['footlights'], ['음악', '현대']),
 ('amp speaker', '앰프 스피커', 'atelier', 'floor', 1, 1, 16, 32, 'opera', ['read'],
  '검은 앰프 상자(16px 솟음). 위 윗면 3행에 손잡이와 다이얼 줄, 남쪽 면 그물 아래 둥근 스피커.', '무대·연습실.', ['drum kit'], ['crate'], ['음악', '현대']),
 ('mic stand', '마이크 스탠드', 'atelier', 'floor', 1, 1, 16, 32, 'opera', ['read'],
  '검은 마이크 스탠드(16px 솟음) — 꼭대기 은빛 둥근 마이크 머리 2행, 가는 기둥, 세 갈래 받침, 늘어진 줄.', '무대 앞.', ['amp speaker'], ['music stand'], ['음악', '무대']),
 ('cello stand', '첼로', 'atelier', 'floor', 1, 1, 16, 48, 'opera', ['read'],
  '받침에 세운 첼로와 활(32px 솟음) — 머리 소용돌이 윗면 1행, 붉은 갈색 몸통의 f 구멍 둘·줄 넷, 아래 받침.', '연주실·극장.', ['music stand'], ['lute'], ['음악']),
 ('gramophone', '축음기', 'atelier', 'floor', 1, 1, 16, 32, 'manor', ['read'],
  '나무 상자 위 금빛 나팔 축음기(16px 솟음). 상자 윗면 4행에 검은 음반과 바늘 팔, 나팔꽃 모양 나팔이 북동쪽으로 벌어진다.', '응접실·찻집.', ['armchair'], ['music box'], ['음악', '저택']),
 ('stage spotlight', '무대 조명', 'atelier', 'floor', 1, 1, 16, 32, 'opera', ['light'],
  '삼각대 위의 검은 원통 조명(16px 솟음), 북쪽 무대를 향한다. 원통 윗면 2행, 앞 렌즈의 노란 빛, 세 다리.', '무대 옆.', ['mic stand'], ['footlights'], ['극장', '무대']),
 # ── 계절·행사 ──
 ('christmas tree', '성탄 나무', 'season', 'floor', 1, 1, 16, 48, 'manor', ['light'],
  '화분 받침의 전나무(32px 솟음) — 꼭대기 금별, 층층 가지 윗면이 밝은 초록, 빨강·금 구슬과 노란 전구 점, 아래 선물 상자 하나.', '거실·광장 실내.', ['gift boxes'], ['white tree'], ['계절', '겨울', '축제']),
 ('pumpkin lantern', '호박 등', 'season', 'floor', 1, 1, 16, 16, 'manor', ['light'],
  '눈·입을 판 주황 호박 등(12px 높이). 꼭지 윗면 2행, 파낸 구멍 안 노란 촛불 빛.', '현관·축제 방.', ['candle'], ['crate:pumpkin'], ['계절', '가을', '축제']),
 ('birthday cake table', '생일 케이크 탁자', 'season', 'floor', 1, 1, 16, 32, 'bakery', ['read'],
  '흰 천 덮은 작은 둥근 탁자(12px 솟음). 상판 윗면 7행에 초 꽂은 딸기 케이크(초 불꽃 셋)와 접시 둘, 천 자락이 남쪽으로.', '집·여관 잔치.', ['gift boxes'], ['table:cake+pie'], ['계절', '축제']),
 ('festival lantern string', '축제 등 줄', 'season', 'hang', 2, 0, 32, 16, 'tavern', ['light'],
  '벽 윗줄에 늘어진 줄과 색 종이등 넷(2칸) — 빨강·노랑·초록·파랑, 등마다 아래 술.', '축제 날 방 벽 윗줄.', [], ['hanging lantern'], ['계절', '축제']),
 ('new year decoration', '새해 장식', 'season', 'floor', 1, 1, 16, 32, 'hobbit', ['read'],
  '받침 위의 새해 장식(16px 솟음) — 대나무 세 대를 비스듬히 자른 끝 윗면이 밝고, 둘레 솔가지와 새끼줄.', '현관 옆.', [], ['plant'], ['계절', '새해', '동양']),
 ('snowman indoor', '작은 눈사람', 'season', 'floor', 1, 1, 16, 32, 'narshe', ['read'],
  '쟁반 위 작은 눈사람(16px 솟음) — 머리 윗면 2행에 빨간 털모자, 숯 눈·당근 코, 몸통 둘.', '창가·현관.', ['christmas tree'], ['statue'], ['계절', '겨울']),
 ('wreath', '화환', 'season', 'hang', 1, 0, 16, 16, 'manor', ['read'],
  '벽에 건 둥근 솔가지 화환(벽면 윗줄) — 초록 고리에 빨간 열매와 아래 빨간 리본.', '문 위·벽 윗줄.', ['christmas tree'], ['hang:flower'], ['계절', '겨울']),
 # ── 동물 ──
 ('dog bed', '개 쿠션', 'pet', 'floor', 1, 1, 16, 16, 'manor', ['sleep'],
  '둥근 갈색 개 쿠션에 웅크려 자는 흰 개(10px 높이). 쿠션 테 윗면이 밝고 개 등이 가장 밝다, 옆에 밥그릇.', '거실 구석.', ['sleeping cat'], ['fur rug'], ['동물', '집']),
 ('cat tower', '캣타워', 'pet', 'floor', 1, 1, 16, 48, 'manor', ['read'],
  '천을 감은 기둥과 판 세 단의 캣타워(32px 솟음) — 맨 위 판 윗면 3행에 엎드린 얼룩 고양이, 중간 판과 둥근 굴.', '창가.', ['dog bed'], ['coat rack'], ['동물', '집']),
 ('rabbit hutch', '토끼장', 'pet', 'floor', 2, 1, 32, 32, 'stable', ['search'],
  '나무 토끼장(2칸, 16px 솟음). 지붕 윗면 4행, 남쪽 면 철망 너머 흰 토끼 둘과 당근, 아래 짚.', '헛간·마당 창고.', ['hay bale'], ['cage'], ['동물', '농가']),
 ('pet food bowls', '먹이 그릇', 'pet', 'floor', 1, 1, 16, 16, 'manor', ['search'],
  '바닥 매트 위 그릇 둘(4px 높이) — 하나는 사료 알갱이, 하나는 물(하늘빛 반사).', '부엌 구석.', ['dog bed'], ['feed trough'], ['동물', '집']),
 ('terrarium', '사육장', 'pet', 'wall', 1, 1, 16, 32, 'tower', ['read'],
  '장 위 유리 사육장(16px 솟음) — 뚜껑 윗면 2행 철망, 안에 모래·돌·작은 도마뱀과 초록 풀, 유리 반사 한 줄.', '연구실·방 벽.', ['specimen jar big'], ['fish tank'], ['동물', '연구실']),
 ('parrot perch', '앵무새 횃대', 'pet', 'floor', 1, 1, 16, 32, 'dwarf', ['read'],
  '나무 횃대 기둥 위 빨강·파랑 앵무새(16px 솟음) — 가로 막대 윗면 1행, 새 머리가 가장 밝다, 아래 모이 접시.', '선장실·가게.', [], ['owl perch'], ['동물', '해적']),
 ('horse stall gate', '마구간 칸막이', 'pet', 'floor', 2, 1, 32, 32, 'stable', ['gate'],
  '나무 마구간 칸막이 문(2칸, 16px 솟음). 위 가로 판 윗면 2행, 반쯤 열린 아래 문, 쇠 빗장, 안쪽 짚.', '마구간 줄로.', ['saddle rack'], ['feed trough'], ['동물', '마구간']),
 # ── 캠핑 ──
 ('sleeping bag', '침낭', 'camp', 'flat', 1, 2, 16, 32, 'mine', ['sleep'],
  '바닥에 편 주황 침낭(1×2칸 남북, 밟을 수 있음) — 북쪽 둥근 머리 덮개, 가운데 지퍼 줄, 남쪽 끝 접힘.', '동굴·텐트 바닥.', ['camp lantern'], ['straw bed'], ['캠핑', '동굴']),
 ('camp lantern', '캠핑 등', 'camp', 'floor', 1, 1, 16, 16, 'mine', ['light'],
  '바닥에 둔 쇠 손잡이 등(12px 높이) — 위 손잡이와 뚜껑 윗면 2행, 유리 안 노란 불빛.', '침낭 옆.', ['sleeping bag'], ['candle'], ['캠핑', '동굴']),
 ('folding camp chair', '접이 의자', 'camp', 'floor', 1, 1, 16, 32, 'mine', ['sit'],
  '초록 천 접이 의자(14px 솟음), 남쪽을 본다. 천 좌판 윗면 4행, 등받이 천, X 자 쇠다리.', '캠프 모닥불 둘레.', ['camp lantern'], ['stool'], ['캠핑']),
 ('cooler box', '아이스박스', 'camp', 'floor', 1, 1, 16, 16, 'mine', ['search'],
  '파랑·흰 아이스박스(12px 높이). 흰 뚜껑 윗면 5행과 손잡이, 남쪽 면 파란 몸통.', '캠프·배.', ['folding camp chair'], ['chest'], ['캠핑', '현대']),
 ('campfire pit', '모닥불 화덕', 'camp', 'floor', 1, 1, 16, 16, 'mine', ['light'],
  '돌로 두른 모닥불(12px 높이) — 돌 고리 윗면이 밝고 가운데 장작 십자 위 주황·노랑 불꽃.', '동굴 안 쉼터.', ['sleeping bag'], ['brazier'], ['캠핑', '동굴']),
 ('backpack pile', '배낭 더미', 'camp', 'floor', 1, 1, 16, 16, 'mine', ['search'],
  '기대 놓은 큰 배낭 둘(12px 높이) — 배낭 윗면 4행에 말아 묶은 깔개, 주머니와 끈.', '쉼터 구석.', ['sleeping bag'], ['sack'], ['캠핑', '여행']),
 # ── 사막 ──
 ('floor cushions', '바닥 쿠션 더미', 'desert', 'floor', 1, 1, 16, 16, 'tailor', ['sit'],
  '바닥에 쌓은 비단 쿠션 셋(10px 높이) — 붉은·금·청록 천, 모서리 금 술, 윗면이 밝다.', '사막 저택 방.', ['brass tray table'], ['round rug'], ['사막', '아라비안']),
 ('brass tray table', '놋쇠 쟁반 탁자', 'desert', 'floor', 1, 1, 16, 32, 'tailor', ['read'],
  '접는 나무 다리 위 둥근 놋쇠 쟁반(12px 솟음). 쟁반 윗면 7행에 새김 무늬와 찻주전자·작은 유리잔 둘, 아래 X 자 다리.', '쿠션 둘레 가운데.', ['floor cushions'], ['roundtable'], ['사막', '아라비안']),
 ('magic lamp stand', '요술 램프 받침', 'desert', 'floor', 1, 1, 16, 32, 'tower', ['read'],
  '비단 덮은 받침 위의 금 기름 램프(16px 솟음) — 램프 뚜껑 윗면 2행과 긴 주둥이, 주둥이에서 오르는 보랏빛 연기.', '보물 방·마법 상점.', ['treasure pile'], ['crown stand'], ['사막', '보물']),
 ('big clay urn', '큰 토기 항아리', 'desert', 'floor', 1, 1, 16, 32, 'tailor', ['search'],
  '사람 허리만 한 붉은 토기 항아리(16px 솟음) — 아가리 윗면 3행이 둥글고 어둡다, 배에 기하 무늬 띠.', '사막 집 구석.', ['floor cushions'], ['pot', 'water jar'], ['사막']),
 ('hanging carpet rack', '양탄자 걸이', 'desert', 'floor', 2, 1, 32, 48, 'tailor', ['read'],
  '나무 틀에 걸어 늘어뜨린 무늬 양탄자 셋(2칸, 32px 솟음) — 위 가로대 윗면 1행, 붉은·청록·금 무늬 천이 겹친다.', '양탄자 상점.', ['floor cushions'], ['tapestry'], ['사막', '상점']),
 ('sand hourglass table', '모래시계 탁자', 'desert', 'floor', 1, 1, 16, 32, 'tower', ['read'],
  '작은 돌 탁자 위의 모래시계와 별자리 두루마리(16px 솟음). 탁자 윗면 5행, 모래시계 위 테 윗면 1행과 흐르는 금모래.', '점성술사 방.', ['star chart'], ['big hourglass'], ['사막', '마법']),
 # ── 설국 ──
 ('ski rack', '스키 걸이', 'snowland', 'hang', 1, 0, 16, 16, 'narshe', ['search'],
  '벽 걸이에 세운 나무 스키 한 벌과 지팡이 둘(벽면 윗줄) — 스키 끝이 위로 휘고 끈 묶음.', '산장 현관 벽 윗줄.', ['sled'], ['pick rack'], ['설국', '산장']),
 ('sled', '썰매', 'snowland', 'floor', 2, 1, 32, 16, 'narshe', ['block'],
  '나무 썰매(2칸, 8px 높이). 판 윗면 6행에 묶은 짐 자루와 털가죽, 앞쪽이 위로 말린 쇠 날.', '산장 현관·창고.', ['ski rack'], ['mine cart'], ['설국']),
 ('fur coat rack', '털옷 걸이', 'snowland', 'floor', 1, 1, 16, 48, 'narshe', ['read'],
  '나무 옷걸이에 건 두꺼운 털외투와 털모자(32px 솟음) — 모자 윗면 2행, 갈색 털옷 가장자리 흰 털, 아래 장화 한 켤레.', '산장 현관.', ['ski rack'], ['coat rack'], ['설국', '산장']),
 ('ice fishing bucket', '얼음 낚시 통', 'snowland', 'floor', 1, 1, 16, 16, 'narshe', ['search'],
  '나무 통 안 얼음과 물고기 둘(10px 높이) — 통 안 윗면 6행, 옆에 짧은 낚싯대.', '설국 오두막.', ['sled'], ['barrel:fish+ice'], ['설국', '낚시']),
 ('wood stove snow', '무쇠 난로', 'snowland', 'floor', 1, 1, 16, 48, 'narshe', ['light'],
  '검은 무쇠 장작 난로와 위로 솟은 굴뚝 관(32px 솟음). 난로 윗면 4행에 끓는 주전자, 남쪽 면 유리문 안 불, 관은 위로 칸 밖까지.', '산장 거실.', ['firewood bundle'], ['stove'], ['설국', '산장']),
 # ── 해적선 ──
 ('rum barrel', '럼주 통', 'pirate', 'floor', 1, 1, 16, 32, 'dwarf', ['search'],
  '눕힌 작은 럼주 통 둘을 겹친 받침(14px 솟음) — 통 윗면 3행에 쇠테, 둥근 바닥면에 해골 낙인과 꼭지.', '선창·해적 주점.', ['captain chair'], ['barrel'], ['해적', '배']),
 ('captain chair', '선장 의자', 'pirate', 'floor', 1, 1, 16, 32, 'dwarf', ['sit'],
  '붉은 벨벳 등받이 높은 나무 의자(16px 솟음), 남쪽을 본다. 좌판 윗면 4행, 등받이 꼭대기 조각 윗면 2행과 금 못.', '선장실 해도 탁자 앞.', ['map table'], ['armchair'], ['해적', '배', '선장실']),
 ('wanted pirate flag', '해적기', 'pirate', 'hang', 1, 0, 16, 16, 'dwarf', ['read'],
  '벽에 편 검은 해적기(벽면 윗줄) — 흰 해골과 엇갈린 뼈, 가장자리 해진 올.', '선장실 벽 윗줄.', ['captain chair'], ['banner red'], ['해적', '배']),
 ('treasure map table', '보물 지도 상자', 'pirate', 'floor', 1, 1, 16, 16, 'dwarf', ['read'],
  '작은 나무 상자 위 펼친 보물 지도(10px 높이) — 상자 뚜껑 윗면 6행, 지도의 점선과 빨간 X, 위에 나침반.', '선장실.', ['captain chair'], ['map scroll bin'], ['해적', '보물']),
 ('ship lantern', '선박 등', 'pirate', 'hang', 1, 0, 16, 16, 'dwarf', ['light'],
  '벽 쇠고리에 건 놋쇠 선박 등(벽면 윗줄) — 유리 안 노란 불, 위 둥근 뚜껑과 손잡이.', '선실 벽 윗줄.', [], ['wall sconce'], ['배', '해적']),
 ('capstan', '닻줄 감개', 'pirate', 'floor', 1, 1, 16, 32, 'dwarf', ['search'],
  '나무 닻줄 감개(캡스턴, 16px 솟음) — 둥근 머리 윗면 4행에 막대 꽂는 구멍 여섯, 몸통에 감긴 굵은 밧줄.', '갑판 아래.', ['anchor'], ['rope coil'], ['배', '해적']),
 # ── 마법학교 ──
 ('floating candles', '떠 있는 촛불', 'school_magic', 'hang', 2, 0, 32, 16, 'tower', ['light'],
  '벽 윗줄 높이에 떠 있는 흰 초 다섯(2칸) — 초마다 노란 불꽃과 아래 옅은 빛 점, 받침 없음.', '마법학교 홀 벽 윗줄.', [], ['wall sconce'], ['마법학교', '마법']),
 ('house banner stand', '기숙사 깃발대', 'school_magic', 'floor', 1, 1, 16, 48, 'tower', ['read'],
  '세운 깃대에 건 세로 깃발(32px 솟음) — 깃대 꼭대기 금 창끝, 초록 천에 금 뱀 문양, 아래 돌 받침 윗면 2행.', '학교 홀 양옆.', [], ['banner green'], ['마법학교']),
 ('potion class desk', '물약 수업 책상', 'school_magic', 'floor', 2, 1, 32, 32, 'tower', ['search'],
  '긴 나무 책상(2칸, 14px 솟음). 상판 윗면 6행에 작은 솥 둘(연기)·약재 접시·펼친 교과서, 남쪽 면에 칠 벗겨진 판.', '물약 교실.', ['cauldron'], ['alchemy table'], ['마법학교', '교실']),
 ('crystal ball shelf', '수정구 선반', 'school_magic', 'wall', 1, 1, 16, 32, 'tower', ['read'],
  '벽 선반 세 단의 작은 수정구들(16px 솟음) — 꼭대기 판 윗면 2행, 단마다 받침 위 구 둘(보라·하늘·연두 빛).', '점술 교실 벽.', ['crystal lamp'], ['shelf:skull+crystal'], ['마법학교', '점술']),
 ('wand box wall', '지팡이 상자 벽', 'school_magic', 'wall', 2, 1, 32, 48, 'tailor', ['search'],
  '천장까지 쌓인 길쭉한 지팡이 상자 벽(2칸, 32px 솟음) — 꼭대기 판 윗면 2행, 칸마다 가는 상자 끝(갈색·검정·흰 뚜껑)이 줄로.', '지팡이 상점 벽.', ['staff rack'], ['scroll rack'], ['마법학교', '상점']),
 ('sorting stool hat', '모자 의자', 'school_magic', 'floor', 1, 1, 16, 32, 'tower', ['read'],
  '세 발 나무 의자 위 낡은 뾰족 마법사 모자(16px 솟음) — 모자 끝이 꺾였다, 의자 좌판 윗면 3행.', '입학식 홀 앞.', [], ['stool'], ['마법학교']),
 # ── 요정·드워프 ──
 ('mushroom table', '버섯 탁자', 'fairy', 'floor', 1, 1, 16, 32, 'elf', ['read'],
  '큰 빨간 버섯 갓을 상판으로 쓴 탁자(14px 솟음) — 갓 윗면 7행에 흰 점, 굵은 흰 자루.', '요정 집.', ['mushroom stool'], ['roundtable'], ['요정', '숲']),
 ('mushroom stool', '버섯 의자', 'fairy', 'floor', 1, 1, 16, 16, 'elf', ['sit'],
  '작은 갈색 버섯 의자(10px 높이) — 둥근 갓 윗면 5행, 짧은 자루.', '버섯 탁자 둘레.', ['mushroom table'], ['stool'], ['요정', '숲']),
 ('vine chair', '덩굴 의자', 'fairy', 'floor', 1, 1, 16, 32, 'elf', ['sit'],
  '살아 있는 덩굴을 엮은 의자(16px 솟음), 남쪽을 본다. 좌판 윗면 4행에 이끼 방석, 등받이 덩굴 고리와 잎.', '엘프 집.', ['elven bed'], ['armchair'], ['엘프', '숲']),
 ('glowing flower pot', '빛나는 꽃 화분', 'fairy', 'floor', 1, 1, 16, 32, 'elf', ['light'],
  '흙 화분의 종 모양 꽃 셋(16px 솟음) — 꽃마다 안에서 하늘빛으로 빛나고 둘레 반딧불 점.', '엘프 집·요정 방.', ['vine chair'], ['potted flowering'], ['엘프', '마법']),
 ('dwarf ale keg', '드워프 큰 술통', 'fairy', 'floor', 2, 1, 32, 32, 'dwarf', ['search'],
  '받침에 눕힌 큰 술통(2칸, 16px 솟음) — 통 윗면 5행에 굵은 쇠테 셋과 룬 낙인, 둥근 앞면에 놋쇠 꼭지와 거품 잔.', '드워프 주점.', ['beer tap barrel'], ['keg rack'], ['드워프', '주점']),
 ('rune anvil', '룬 모루', 'fairy', 'floor', 1, 1, 16, 32, 'dwarf', ['search'],
  '돌 받침 위 검은 모루(14px 솟음) — 모루 윗면 4행에 빛나는 하늘빛 룬, 뿔 끝, 옆에 망치.', '드워프 대장간.', ['forge'], ['anvil'], ['드워프', '대장간']),
 # ── 마을 관청·가게 ──
 ('mail sorting shelf', '우편 분류함', 'town', 'wall', 2, 1, 32, 32, 'scholar', ['search'],
  '작은 칸 스무 개의 나무 분류함(2칸, 16px 솟음) — 꼭대기 윗면 2행, 칸마다 꽂힌 하얀 편지 끝, 아래 판 위 소포 하나.', '우체국 벽.', ['parcel pile'], ['scroll rack'], ['우체국', '마을']),
 ('parcel pile', '소포 더미', 'town', 'floor', 1, 1, 16, 32, 'scholar', ['search'],
  '끈으로 묶은 갈색 종이 소포 넷(14px 솟음) — 맨 위 소포 윗면 4행에 십자 끈과 붉은 봉랍.', '우체국 바닥.', ['mail sorting shelf'], ['crate'], ['우체국', '마을']),
 ('bank teller window', '은행 창구', 'town', 'floor', 2, 1, 32, 48, 'throne', ['counter'],
  '대리석 창구와 위의 쇠창살 칸막이(2칸, 32px 솟음). 상판 윗면 5행에 동전 쟁반·장부, 위로 금빛 창살과 작은 창 구멍.', '은행.', ['safe'], ['counter 2x1'], ['은행', '마을']),
 ('book display table', '서점 평대', 'town', 'floor', 2, 1, 32, 32, 'scholar', ['read'],
  '낮은 나무 평대(2칸, 12px 솟음). 판 윗면 7행에 눕혀 쌓은 책 더미 넷(표지 색 다름)과 세운 추천 팻말.', '서점 가운데.', ['bookshelf 3w'], ['table:book+scroll'], ['서점', '가게']),
 ('pawn shop shelf', '전당포 진열장', 'town', 'wall', 2, 1, 32, 32, 'tailor', ['search'],
  '유리문 진열장(2칸, 16px 솟음) — 꼭대기 윗면 2행, 단마다 잡동사니(회중시계·촛대·반지 상자·낡은 칼), 가격표.', '전당포 벽.', ['pawn counter'], ['cabinet:gem+gemr'], ['상점', '전당포']),
 ('pawn counter', '전당포 창구', 'town', 'floor', 2, 1, 32, 32, 'tailor', ['counter'],
  '나무 창구(2칸, 16px 솟음) — 상판 윗면 6행에 돋보기·저울·장부, 남쪽 면에 쇠 보강판.', '전당포 안쪽.', ['pawn shop shelf'], ['counter 2x1'], ['상점', '전당포']),
 ('clock shop wall', '시계방 벽', 'town', 'hang', 2, 0, 32, 16, 'tailor', ['read'],
  '벽 윗줄에 걸린 크기 다른 시계 넷(2칸) — 둥근·네모·뻐꾸기 시계, 바늘이 모두 다른 시각.', '시계방 벽 윗줄.', ['grandfather clock'], ['wall clock'], ['상점', '시계방']),
 ('town notice kiosk', '관청 안내대', 'town', 'floor', 1, 1, 16, 32, 'throne', ['read'],
  '기운 판의 안내대(16px 솟음) — 판 윗면 5행에 펼친 등록부와 깃펜, 앞에 「안내」 문장 판.', '관청 입구.', [], ['lectern'], ['관청', '마을']),
 ('toy shop shelf', '장난감 진열대', 'town', 'wall', 2, 1, 32, 32, 'tailor', ['read'],
  '색칠한 진열대(2칸, 16px 솟음) — 꼭대기 윗면 2행, 단마다 나무 병정·곰 인형·팽이·작은 배.', '장난감 가게 벽.', ['rocking horse'], ['shelf:toy'], ['상점', '장난감']),
 # ── 현대 운동·취미 ──
 ('treadmill', '러닝머신', 'm_hobby', 'floor', 1, 2, 16, 48, 'manor', ['read'],
  '러닝머신(1×2칸 남북, 16px 솟음), 앞이 북쪽. 남쪽 위에서 내려다본 3/4: 꼭대기 윗면 22행 — 검은 벨트 판과 양옆 회색 테, 북쪽 끝 손잡이 막대와 화면 판(윗면 2행). 남쪽 면에 판 두께.', '헬스장·집.', ['dumbbell rack'], ['mine cart'], ['현대', '운동']),
 ('dumbbell rack', '아령 받침', 'm_hobby', 'floor', 1, 1, 16, 32, 'manor', ['search'],
  '두 단 아령 받침(14px 솟음) — 단마다 검은 아령 셋(크기 다름), 받침 윗면 3행.', '헬스장.', ['treadmill'], ['weapon rack'], ['현대', '운동']),
 ('bench press', '벤치 프레스', 'm_hobby', 'floor', 1, 2, 16, 48, 'manor', ['sit'],
  '벤치 프레스(1×2칸 남북, 16px 솟음). 남쪽 위에서 내려다본 3/4: 꼭대기 윗면 22행 — 검은 가죽 벤치 판과 북쪽 끝 기둥 둘에 걸친 은빛 봉·검은 원판. 남쪽 면에 다리.', '헬스장.', ['dumbbell rack'], ['bench 2'], ['현대', '운동']),
 ('guitar stand', '기타 스탠드', 'm_hobby', 'floor', 1, 1, 16, 32, 'manor', ['read'],
  '받침에 세운 통기타(16px 솟음) — 헤드 윗면 1행, 둥근 몸통 소리 구멍과 줄, 받침 다리.', '방 구석.', ['amp speaker'], ['lute'], ['현대', '음악']),
 ('gaming chair', '게이밍 의자', 'm_hobby', 'floor', 1, 1, 16, 32, 'manor', ['sit'],
  '검정·빨강 게이밍 의자(16px 솟음), 북쪽 책상을 본다(등이 남쪽). 높은 등받이 꼭대기 윗면 2행, 빨간 줄무늬, 다섯 갈래 바퀴.', '컴퓨터 책상 앞.', ['office pc desk'], ['office chair'], ['현대', '방']),
 ('aquarium cabinet small', '작은 어항', 'm_hobby', 'floor', 1, 1, 16, 32, 'manor', ['read'],
  '낮은 장 위의 둥근 금붕어 어항(16px 솟음) — 어항 아가리 윗면 3행, 물빛 안 주황 금붕어 둘과 물풀.', '거실·현관.', [], ['fish tank'], ['현대', '집']),
 ('model train table', '기차 모형 탁자', 'm_hobby', 'floor', 2, 2, 32, 32, 'manor', ['read'],
  '모형 기차 판(2×2칸, 12px 높이). 남쪽 위에서 내려다본 3/4: 꼭대기 윗면 22행 — 초록 판 위 둥근 선로와 작은 기차·집 둘·나무, 그 아래 남쪽 면에 판 두께 3행과 다리.', '취미방.', [], ['tea 2x2'], ['현대', '취미']),
 ('sewing machine table', '재봉틀', 'm_hobby', 'floor', 1, 1, 16, 32, 'tailor', ['search'],
  '무쇠 다리 탁자 위 검은 재봉틀(16px 솟음) — 재봉틀 윗면 3행에 금 무늬, 옆 실패, 아래 발판.', '옷가게·방.', ['ironing board'], ['spinning wheel'], ['현대', '옷가게']),
 ('telescope modern', '천체 망원경(현대)', 'm_hobby', 'floor', 1, 1, 16, 48, 'tower', ['read'],
  '세 다리 위 흰 경통 천체 망원경(32px 솟음) — 경통이 북동쪽 하늘로 기울고 윗면이 밝다, 접안부와 작은 보조경.', '옥상 방·창가.', [], ['telescope'], ['현대', '취미']),
 ('massage chair', '안마 의자', 'm_hobby', 'floor', 1, 1, 16, 32, 'manor', ['sit'],
  '두툼한 갈색 안마 의자(16px 솟음), 남쪽을 본다. 좌판 윗면 4행, 머리 받침 윗면 2행, 팔 덮개와 리모컨 줄.', '거실·찜질방.', [], ['armchair'], ['현대', '집']),
 # ── 현대 병원·편의점 더하기 ──
 ('operating table', '수술대', 'm_hospital', 'floor', 1, 2, 16, 48, 'pharmacy', ['read'],
  '은빛 기둥 위 수술대(1×2칸 남북, 16px 솟음). 남쪽 위에서 내려다본 3/4: 꼭대기 윗면 22행 — 초록 천 덮은 좁은 판과 북쪽 머리 받침, 옆 은빛 기구 쟁반. 남쪽 면에 기둥 받침.', '수술실 가운데.', ['surgery lamp'], ['hospital bed'], ['현대', '병원', '수술실']),
 ('surgery lamp', '수술등', 'm_hospital', 'hang', 1, 0, 16, 16, 'pharmacy', ['light'],
  '벽 윗줄에서 뻗은 팔 끝의 둥근 수술등(1칸) — 둥근 갓 안 흰 전구 여섯, 아래 빛 번짐.', '수술실 벽 윗줄.', ['operating table'], ['hanging lantern'], ['현대', '병원']),
 ('medicine cart', '약 카트', 'm_hospital', 'floor', 1, 1, 16, 32, 'pharmacy', ['search'],
  '흰 서랍 약 카트(14px 솟음) — 위 판 윗면 5행에 약병·주사기 쟁반, 색 서랍 넷, 바퀴.', '병동 복도.', ['hospital bed'], ['apothecary drawers'], ['현대', '병원']),
 ('oden pot counter', '어묵통', 'm_cafe', 'floor', 1, 1, 16, 32, 'bakery', ['search'],
  '편의점 계산대 옆 네모 어묵통(14px 솟음) — 칸 나눈 국물 윗면 6행에 꼬치 어묵·달걀·무, 김 한 줄.', '편의점 계산대 옆.', ['price scanner counter'], ['cauldron'], ['현대', '편의점']),
 ('instant noodle shelf', '컵라면 진열대', 'm_shop', 'wall', 1, 1, 16, 32, 'tailor', ['search'],
  '세 단 진열대에 빽빽한 컵라면(16px 솟음) — 꼭대기 판 윗면 2행, 단마다 빨강·주황·초록 뚜껑 컵 줄.', '편의점 벽.', ['store shelf'], ['shelf:jar+jarb+jarg'], ['현대', '편의점']),
 ('shower booth', '샤워 부스', 'm_home', 'wall', 1, 1, 16, 48, 'manor', ['search'],
  '유리 샤워 부스(32px 솟음) — 위 은빛 샤워기 머리, 반투명 유리 벽에 물방울 점과 반사 한 줄, 바닥 흰 받침 윗면 3행.', '욕실 구석.', ['modern toilet'], ['bathtub'], ['현대', '욕실']),
 ('office partition', '사무실 칸막이', 'm_office', 'floor', 2, 1, 32, 32, 'magitek', ['block'],
  '회색 천 사무실 칸막이(2칸, 16px 솟음) — 위 테 윗면 2행, 천 면에 꽂은 메모지 셋과 달력.', '사무실 책상 사이.', ['office pc desk'], ['folding screen'], ['현대', '사무실']),
 ('boss desk', '사장 책상', 'm_office', 'floor', 3, 1, 48, 32, 'manor', ['read'],
  '짙은 나무 큰 사장 책상(3칸, 16px 솟음). 상판 윗면 6행에 초록 갓 스탠드·명패·서류 쟁반·만년필, 남쪽 면에 양쪽 서랍 장과 가운데 패널.', '사장실.', ['gaming chair'], ['desk 3x1'], ['현대', '사무실']),
 ('printer stand', '프린터', 'm_office', 'floor', 1, 1, 16, 32, 'scholar', ['search'],
  '작은 장 위의 회색 프린터(16px 솟음) — 프린터 윗면 4행에 종이 나오는 판과 흰 종이, 장 안 종이 묶음.', '사무실 구석.', ['copy machine'], ['printing press'], ['현대', '사무실']),
 # ── 공포 폐가 더하기 ──
 ('broken bed', '부서진 침대', 'horror', 'floor', 1, 2, 16, 48, 'manor', ['search'],
  '한쪽 다리가 부러져 기운 쇠침대(1×2칸 남북, 12px 솟음). 남쪽 위에서 내려다본 3/4: 꼭대기 윗면 22행 — 얼룩진 매트리스와 찢긴 홑이불, 녹슨 머리판(윗면 2행). 남쪽 면에 부러진 다리.', '폐가 침실.', ['dusty doll pile'], ['bed red'], ['공포', '폐가']),
 ('dusty doll pile', '인형 무더기', 'horror', 'floor', 1, 1, 16, 16, 'manor', ['search'],
  '바닥에 쌓인 낡은 인형 셋(12px 높이) — 단추 눈, 해진 옷, 하나는 고개가 꺾였다, 먼지 회색.', '폐가 아이 방.', ['broken bed'], ['old doll'], ['공포', '폐가']),
 ('static tv', '노이즈 TV', 'horror', 'floor', 1, 1, 16, 32, 'manor', ['read'],
  '바닥에 놓인 브라운관 TV(16px 솟음) — TV 윗면 3행에 토끼귀 안테나, 남쪽 화면은 흰 노이즈 점.', '폐가 거실.', [], ['crt tv stand'], ['공포', '폐가']),
 ('talisman box', '부적 붙은 상자', 'horror', 'floor', 1, 1, 16, 32, 'chapel', ['open'],
  '노란 부적을 붙이고 붉은 끈으로 묶은 검은 상자(12px 솟음) — 뚜껑 윗면 5행에 부적 셋, 끈 매듭.', '봉인된 방.', ['candle circle'], ['chest'], ['공포', '동양']),
 ('candle circle', '촛불 원', 'horror', 'flat', 2, 2, 32, 32, 'chapel', ['walk'],
  '바닥에 둥글게 세운 초 여덟과 가운데 분필 원(2×2칸, 밟을 수 있음) — 초마다 노란 불꽃 점과 녹은 촛농.', '의식 방 바닥.', ['talisman box'], ['magic circle'], ['공포', '의식']),
 ('boarded closet', '판자 박은 옷장', 'horror', 'wall', 1, 1, 16, 32, 'manor', ['open'],
  '판자를 엇갈려 못 박은 낡은 옷장(16px 솟음) — 꼭대기 윗면 3행, 문틈 사이 검은 어둠, 판자 셋.', '폐가 방 벽.', ['broken bed'], ['wardrobe'], ['공포', '폐가']),
 ('rocking chair', '흔들의자', 'horror', 'floor', 1, 1, 16, 32, 'manor', ['sit'],
  '낡은 나무 흔들의자(16px 솟음), 남쪽을 본다. 좌판 윗면 4행에 접힌 숄, 등받이 살 넷, 아래 휜 흔들 다리.', '거실·폐가.', ['fireplace'], ['armchair'], ['집', '공포']),
]
assert len({x[0] for x in I}) == len(I), '같은 id 가 둘'

if __name__ == '__main__':
    import common
    for row in I:
        o = dict(id=row[0], kind=row[3], footprint=dict(w=row[4], h=row[5]), description=row[10], image=dict(w=row[6], h=row[7]))
        errs = common.spec_top_lint(o)
        if errs: raise SystemExit('\n'.join(errs))
    print('항목', len(I))
    batch2.I = I
    batch2.main()
