"""Local repair: explicit, hand-chosen ASCII spans, coordinates zero based.

The input is the preserved current draft, not another frame. No pixel copying
between poses, geometry generation, image extraction or automatic filling.
Final actions remain complete literal 96 x 96 grids.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PATCHES = {
    'poison_b': '''
37 54 omsr
38 53 omsrr
39 53 omssr
40 53 omss
41 54 os
''',
    'sleep_b': '''
54 30 lllllllllmmmmmmmmbkkffkb...................
55 30 llllllllmmmmmbcttkkffkb....................
56 30 lllllllmmmmbcthhcttccb..obccb...............
57 30 llllllmmbobcttcbttccbb...obcttcb............
58 30 llllmmbobcthhttcbcccbb....obcthhtcb.........
59 30 llmbobcthhhttccbocctcb.....obcthhttcb........
60 30 cbobcthhhttccbobcthtcb.....obcthhttcb........
61 30 thobcthhttccbommmbctcb....obcthhttcb.........
62 30 ttccobcthttcGgkkoctcb...obcthhttccb..........
63 30 tcccbobcthttcgGkFFFfko.obcthhttcccb..........
64 30 cccbttcobctccbokFFfffkothttccccb............
65 30 cbbcttccbbmobbbokobctttcccGgkko.............
66 30 ssmmbctccbbsssobccccccgGkFFFfko.............
67 30 .rrsssbcccbbrobccccbokFFfffkoccb............
68 30 .....rrrbbb..rrrrrrokfffkkobcthttccb........
69 30 ...................okkkkobobcthhttccb......
70 30 ...........................obcthhttcccb....
71 55 ...obcthttccccb...
72 54 ...obctttccccb...
73 53 ...obctttccccb...
74 52 ...obctttccccb...
75 51 ...obctttcccbb...
76 50 ..obctttcccbb....
77 49 ..obctttcccbbcbbb
78 48 .obcttccbbcttttttttttcccbb
79 30 ..bcttccb........obctccb...bbccctttttttcccbb
80 30 ..bcttcb..........bctcb.......bbcccttttttcccbb
81 30 ..bctccb...........bccb..........bbcccttttcccbb
82 29 ..bctccb.............bb...............bbcccttccbb
83 28 ..bctcb................b..................bcttccbb
84 27 ..bccb.......................................bcttccb
85 26 ..bcb........................................bctccb..
86 26 ..bb........................................bctcb...
87 26 ...b.......................................bccb....
88 66 ...bccb.....
89 65 ...bcb......
90 65 ...bb.......
91 65 ....b.......
''',
}

def apply():
    for name, spans in PATCHES.items():
        path = ROOT / 'actions' / f'{name}.pxgrid'
        rows = [list(s) for s in (ROOT/'before-contour-breath-repair'/'actions'/path.name).read_text().splitlines()]
        for line in spans.strip().splitlines():
            y, x, ink = line.split()
            y, x = int(y), int(x)
            assert x + len(ink) <= 96
            rows[y][x:x+len(ink)] = list(ink)
        path.write_text('\n'.join(''.join(row) for row in rows) + '\n')

if __name__ == '__main__':
    apply()
