from pathlib import Path
import json
from PIL import Image, ImageDraw
ROOT=Path(__file__).parent
palette={'o':'#20242A','h':'#3E4647','H':'#737D79','s':'#AD785B','t':'#D5A27B','u':'#F1CEA2','b':'#855D49','w':'#A9BBB3','W':'#E9EADB','g':'#33463E','m':'#586C50','l':'#829474','r':'#6E3437','R':'#AA5D4D','c':'#75613B','C':'#C2AF70','e':'#48A892','E':'#C4EAD3'}
(ROOT/'palette.json').write_text(json.dumps(palette,indent=2)+'\n')
def blank(): return [list('.'*64) for _ in range(64)]
def block(a,x,y,rows):
    for j,row in enumerate(rows.strip('\n').splitlines()):
        for i,ch in enumerate(row):
            a[y+j][x+i]=ch
    return a
def patch(a,entries):
    for x,y,s in entries:
        a[y][x:x+len(s)]=s
    return a
def save(name,a,action=False):
    p=ROOT/('actions' if action else 'poses')/(name+'.pxgrid')
    p.write_text('\n'.join(''.join(r) for r in a)+'\n')
def read(name,action=False):
    return [list(r) for r in (ROOT/('actions' if action else 'poses')/(name+'.pxgrid')).read_text().splitlines()]
def png(a):
    im=Image.new('RGBA',(64,64))
    for y,row in enumerate(a):
        for x,ch in enumerate(row):
            if ch!='.': im.putpixel((x,y),tuple(bytes.fromhex(palette[ch][1:]))+(255,))
    return im
idle=block(blank(),12,8,'''
................ooo
...............oHhho
...............ohhho
..............oohooo
.............oHhssssso
............oHhsuuuuuto
............ohsuuuuuutto
............ohsuuuuuuutto
............ohsuuubbtuubto
............ohsuuuuttuuttu
............ohsuuuoWtuoWto
............ohsuuuoutuotto
............ohstuuuuttuutto
.............osstuuutsutto
.............owstttbuutto
.............owWstttttwo
..............owWWtWWWo
..............owWWWWWo
.............ogwWWWWwggo
...........ogmlwWWWwgmlggo
.........ogmlllwwWwgmlmlmggo
........ogmllllmwWgmlmlmmmmgo
.......ogmllllmmwgmlmlmmgmmmgo
......ogmlllllmmmgmlmlmgmmmgo
......ogmlllmmmmmgmlmlgmmgo
.....ogmlllmmmmmgmlmlgmgo
.....ogmllmmmmmgmlmlmgmo...ostto
.....ogmlmmmmmgmlmlmgmmo..osuutto
.....ogmmmmmmgmlmlmgmmmgo..ottto
......ogmmmgmlmlmgmmgmmgo..ocCo
.......ogmgmlmlmgmmgmmmgo..ocCo
........ogrRRrgmgmmgmmo....cCo
........ogrrRRrmgmmgmmo....cCo
........ogrrrRrgmmgmmgo....cCo
........ogrrRrgmmgmmmgo....cCo
........ogggggmmgmmmmgo....cCo
........ogmllmmgmmmmlmgo...cCo
.......ogmllmmgmmmmmllmgo..cCo
.......ogmlllmgmmmmgmlmmgo..cCo
.......ogmllmmgmmmrgmlmmgo..cCo
......ogmlllmgmmmrRgmlmmgo..cCo
......ogmlllmgmmrRRgmllmmgo.cCo
.....ogmlllmmgmrRRRgmlmmmgo.cCo
.....ogmllmmgmrRRRrgmlmmmgo.cCo
.....ogmlmmgmrRRRrgmmmmmgo..cCo
.....ogmmmggrRRRrggmmmmgo...cCo
......ogggrrRRRr...ogggo....cCo
........oHHhho....oHHhho....cCo
........ohhhho....ohhhho....cCo
.......ohhhhho....ohhhhho...cCo
.......ohhhhoo....ohhhhhoo..cCo
......oooooooo...oooooooo..cCo
......ooooooo....ooooooo...oco
''')
# Explicit bell cluster, and literal shaft rows: no geometric drawing.
block(idle,45,12,'''
...oo
..ocCo
.oCCcCo
ocC..cCo
ocC..cCo
.ocCCco
..ocCo
.oCCcCo
.oCccCo
..ocCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
''')
# Grip overlaps the shaft with a connected thumb and fingers.
patch(idle,[(43,33,'osttcCo'),(42,34,'osuuutCo'),(43,35,'ottccCo'),(40,32,'gmmmgo'),(40,33,'gmmo'),(40,34,'gmo')])
save('idle_a',idle)
png(idle).save(ROOT/'progress/idle.png')
png(idle).resize((512,512),Image.Resampling.NEAREST).save(ROOT/'progress/idle-8x.png')
png(idle).crop((23,8,44,30)).resize((168,176),Image.Resampling.NEAREST).save(ROOT/'progress/face.png')
# Idle refinement: broad cloth planes, attached forward sleeve, continuous staff.
for y in range(27,61): idle[y]=list('.'*64)
block(idle,17,27,'''
......ogmlwWWWwgmgo
....ogmlllwwWwgmlmggo
...ogmllllmwWgmlmmmllmggo
..ogmllllmmwgmlmmmllllmmgo
.ogmlllllmmmgmlmmgmmllllmmgo
.ogmllllmmmmgmlmmgmmmllllmgo
ogmllllmmgggmlmmgmmmllmmgo..osttcCo
ogmlllmmgmlmlmmgmmmlllmmgo.osuuutCo
ogmllmmgmlmmmmmggmmmmmmgo..ottccCo
ogmlmmgmlmmmmmmmggrRRrgo......cCo
.ogmmgmlmmmmmmmggrRRrgo.......cCo
..ogggmllmmmmmmmggrrgo........cCo
...ogrRRrmmmmmmmgggo..........cCo
...ogrrRRrmmmmmmggo...........cCo
...ogrrrRrmmmmmmgo............cCo
...ogrrRrgmmmmmgo.............cCo
...ogggggmmmmmmgo.............cCo
...ogmlllmmmmgmmmgo...........cCo
..ogmllllmmmgmmmmllgo.........cCo
..ogmllllmmgmmmmmllmgo........cCo
..ogmlllmmgmmrrgmmllmgo.......cCo
.ogmllllmmgmrRRgmmmllmgo......cCo
.ogmlllmmgmrRRRgmmmllmgo......cCo
ogmllllmmgmrRRRgmmmlllmmgo.....cCo
ogmlllmmgmrRRRrgmmmllmmgo......cCo
ogmllmmgmrRRRrgmmmlllmmgo......cCo
ogmmmmggrRRRrggmmmmmmgo........cCo
.ogggrrRRRr....oggggo..........cCo
...oHHhho......oHHhho..........cCo
...ohhhho......ohhhho..........cCo
..ohhhhho......ohhhhho.........cCo
..ohhhhoo......ohhhhhoo........cCo
.oooooooo.....oooooooo........cCo
.ooooooo......ooooooo.........oco
''')
# Clear stray shaft symbols from the authored body rows, using selected erasures.
patch(idle,[(46,36,'.....'),(46,37,'.....'),(46,38,'.....'),(46,39,'.....'),(46,40,'.....'),(46,41,'.....'),(46,42,'.....'),(46,43,'.....'),(46,44,'.....'),(46,45,'.....'),(46,46,'.....'),(46,47,'.....'),(46,48,'.....'),(46,49,'.....'),(46,50,'.....'),(46,51,'.....'),(46,52,'.....'),(46,53,'.....'),(46,54,'.....'),(46,55,'.....'),(46,56,'.....'),(46,57,'.....'),(46,58,'.....'),(46,59,'.....'),(46,60,'.....')])
block(idle,48,22,'''
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
oco
''')
patch(idle,[(44,33,'osttcCo'),(43,34,'osuuutCo'),(44,35,'ottccCo')])
save('idle_a',idle)
png(idle).save(ROOT/'progress/idle.png')
png(idle).resize((512,512),Image.Resampling.NEAREST).save(ROOT/'progress/idle-8x.png')
png(idle).crop((23,8,44,30)).resize((168,176),Image.Resampling.NEAREST).save(ROOT/'progress/face.png')
patch(idle,[(24,18,'ohsuuuWotuWoto'),(24,19,'ohsuuuuotuuoto'),(22,39,'rRostto'),(23,40,'rrttto')])
save('idle_a',idle)
png(idle).save(ROOT/'progress/idle.png')
png(idle).resize((512,512),Image.Resampling.NEAREST).save(ROOT/'progress/idle-8x.png')
png(idle).crop((23,8,44,30)).resize((168,176),Image.Resampling.NEAREST).save(ROOT/'progress/face.png')
# Breathing cels: chosen sleeve, beard and foot clusters only.
a=read('idle_a')
patch(a,[(19,30,'gmlllllmm'),(18,31,'gmllllllmm'),(20,37,'gmllmm'),(28,26,'wWWWW'),(27,27,'lwWWWw'),(28,28,'wwWWw'),(36,46,'mmmlll'),(35,52,'mmmllmm'),(20,58,'hHHh')])
save('idle_b',a)
a=read('idle_a')
patch(a,[(25,11,'oHHho'),(24,12,'oHhssssso'),(24,18,'ohsuuuWotuWoto'),(24,19,'ohsuuuuotuuoto'),(18,31,'gmllllmmm'),(17,32,'gmlllllmmm'),(26,27,'mlwWWWWw'),(27,28,'llwwWw'),(29,34,'lmmmmmmg'),(35,48,'gmmlllmm'),(36,53,'mmmmg')])
save('idle_c',a)
# Windup: both forearms gather beside the breast; vertical bell raised.
a=blank()
block(a,24,8,'''
...ooo
..oHhho
..ohhho
.oohooo
.oHhssssso
.oHhsuuuuuto
.ohsuuuuuutto
.ohsuuuuuuutto
.ohsuuubbtuubto
.ohsuuuuttuuttu
.ohsuuuWotuWoto
.ohsuuuuotuuoto
.ohstuuuuttuutto
..osstuuutsutto
..owstttbuutto
..owWstttttwo
...owWWtWWWo
...owWWWWWo
..ogwWWWWwggo
''')
block(a,18,27,'''
......ogmlwWWWwggo
....ogmlllwwWwgmlgo
...ogmllllmwWgmlmmgo
..ogmllllmmwgmlmmllgo
.ogmlllllmmmgmlmmmllgo
ogmlllllmmggmlmmmmllmgo
ogmllllmmgmlmmmostttuugo
ogmlllmmgmlmmosuuuttccCo
.ogmllmmgmlmmosttttcCCo
..ogmmmgggmmlgosttoocCo
...ogrrRRrggmlmmgmmocCo
...ogrrrRRrggmmmmmgocCo
....ogrrRRrggmmmmmgocCo
....oggggggmmmmmmgo.cCo
....ogmlllmmmmmmmgo.cCo
....ogmllllmmgmmmgo.cCo
...ogmllllmmgmmmmgo.cCo
...ogmlllmmgmmrRmggo.cCo
...ogmlllmmgmrRRgmllgo.cCo
..ogmllllmmgmrRRgmmllgo.cCo
..ogmlllmmgmrRRRgmllmmgo.cCo
..ogmlllmmgmrRRRgmllmmgo.cCo
.ogmllllmmgmrRRrgmlllmmgo.cCo
.ogmlllmmgmrRRrgmllmmmgo.cCo
.ogmllmmgmrRRrgmllmmmgo..cCo
.ogmmmmggrRRrggmmmmmgo...cCo
..oggggrRRRr...ogggo.....cCo
....oHHhho.....oHHhho....cCo
....ohhhho.....ohhhho....cCo
...ohhhhho.....ohhhhho...cCo
...ohhhhoo.....ohhhhhoo..cCo
..oooooooo....oooooooo..cCo
..ooooooo.....ooooooo...oco
''')
# Bell tip at x43..49, independently authored hanging bronze lobes.
block(a,43,10,'''
..oo
.ocCo
ocCCco
oc..Co
ocCCCo
.ocCo
ocCcCo
ocCCCo
.ocCo
..cCo
..cCo
..cCo
..cCo
..cCo
..cCo
..cCo
..cCo
..cCo
..cCo
..cCo
..cCo
..cCo
..cCo
..cCo
''')
# Staff below gathered hands, complete chosen rows.
block(a,45,35,'''
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
oco
''')
# Remove surplus draft handle at selected coordinates behind sleeve.
patch(a,[(41,37,'go..'),(41,38,'go..'),(41,39,'o...'),(40,40,'go...'),(39,41,'go....'),(39,42,'go....'),(39,43,'go....'),(39,44,'go....'),(39,45,'go....'),(40,46,'go...'),(41,47,'go..'),(42,48,'o..'),(43,49,'..'),(43,50,'..'),(42,51,'o..'),(42,52,'o..'),(41,53,'o...'),(40,54,'o....'),(41,55,'....'),(41,56,'....'),(41,57,'....'),(41,58,'....'),(42,59,'...'),(41,60,'....')])
save('windup',a)
# Wide step, trunk leans forward, open trailing sleeve and broad split hem.
a=blank()
block(a,27,10,'''
..ooo
.oHhho
.ohhho
oohoo
oHhssssso
oHhsuuuuuto
ohsuuuuuutto
ohsuuubbtuubto
ohsuuuuttuuttu
ohsuuuWotuWoto
ohstuuuotuutto
.osstuuutsutto
.owstttbuutto
.owWstttttwo
..owWWtWWWo
..owWWWWWo
.ogwWWWWwggo
''')
block(a,10,27,'''
................ogmlwWWWwggo
.............oggmlllwwWwgmlgo
.........ogggmlllllmmwWgmlmlgo
......oggmllllllmmmmmgmlmmmllgo
....ogmllllllmmmgggmlmmmmmllmgo
...ogmllllmmmmgggmlmmmmmmllmmgo
..ogmlllmmmmgggmlmmmmmmllmmmgo
..ogmlllmmmggmlmmmmmmllmmmmgo..ostto
...ogmllmmgmlmmmmmmllmmmrrgo..osuutto
....ogmmgmlmmmmmmmllmmmrRRgo..ottccCo
.....ogrrRRrmmmmmmmggggrRRgo....cCo
......ogrrrRRrmmmmmgggrrrgo.....cCo
.......ogrrRRrgmmmmmgggggo......cCo
........ogggggmmmmmmmgo.........cCo
.........ogmllllmmmmmmggo.......cCo
........ogmllllmmmmmgmmmllgo....cCo
.......ogmllllmmmmmggmmmlllgo...cCo
......ogmllllmmmmggrRgmlllllmgo..cCo
.....ogmllllmmmggrRRRgmllllllmgo.cCo
....ogmllllmmmgrRRRRrgmmllllllmgo.cCo
...ogmllllmmgrRRRRRr..ogmmmllllmgo.cCo
..ogmllllmmgrRRRRr......ogmmmlllgo.cCo
..ogmlllmmgrRRRr.........ogmmlllgo.cCo
...ogmmmgggrRr............ogmllmgo.cCo
....ogggg..................ogmmgo.cCo
...oHHhho...................ogggo.cCo
..ohhhhho...................oHHhho.cCo
.ohhhhho....................ohhhho.cCo
.ohhhhoo....................ohhhhho.cCo
.oooooooo...................ohhhhhoo.cCo
.ooooooo....................oooooooo.cCo
............................ooooooo.oco
''')
# Forward staff pitched by manually selected shaft pairs, not a transformed line.
block(a,49,17,'''
...oo
..ocCo
.oCCcCo
ocC..cCo
ocC..cCo
.ocCCco
..ocCo
.oCCcCo
.oCccCo
..ocCo
..cCo
..cCo
..cCo
.cCo
.cCo
.cCo
.cCo
cCo
cCo
cCo
''')
patch(a,[(49,35,'sttcCo'),(49,36,'ttcCo'),(49,37,'ocCo'),(49,38,'cCo'),(48,39,'cCo'),(48,40,'cCo'),(48,41,'cCo'),(47,42,'cCo'),(47,43,'cCo'),(47,44,'cCo'),(46,45,'cCo'),(46,46,'cCo'),(46,47,'cCo'),(45,48,'cCo'),(45,49,'cCo'),(45,50,'cCo'),(44,51,'cCo'),(44,52,'cCo'),(44,53,'cCo'),(43,54,'cCo'),(43,55,'cCo'),(43,56,'cCo'),(42,57,'cCo'),(42,58,'cCo'),(42,59,'oco')])
# Erase accidental draft shaft at far right, explicitly selected blank runs.
patch(a,[(54,37,'.....'),(54,38,'.....'),(54,39,'.....'),(54,40,'.....'),(54,41,'.....'),(54,42,'.....'),(54,43,'.....'),(54,44,'.....'),(54,45,'.....'),(54,46,'.....'),(54,47,'.....'),(54,48,'.....'),(54,49,'.....'),(54,50,'.....'),(54,51,'.....'),(54,52,'.....'),(54,53,'.....'),(54,54,'.....'),(54,55,'.....'),(54,56,'.....'),(54,57,'.....'),(54,58,'.....'),(54,59,'.....')])
save('move',a)

a=read('windup')
for y in range(27,61): a[y]=list('.'*64)
block(a,18,27,'''
......ogmlwWWWwggo
....ogmlllwwWwgmlgo
...ogmllllmwWgmlmmgo
..ogmllllmmwgmlmmllgo
.ogmlllllmmmgmlmmmllgo
ogmlllllmmggmlmmmmllmgo
ogmllllmmgmlmmmmmllllmgo
ogmlllmmgmlmmmrrgmmlllgo..osttcCo
.ogmllmmgmlmmrRRggmmlgo.osuuutCo
..ogmmmgggmmrRRRrggmgo..ottccCo
...ogrrRRrggmlmmmmgggo......cCo
...ogrrrRRrggmmmmmmgo
....ogrrRRrggmmmmmgo
....oggggggmmmmmmgo
....ogmlllmmmmmmmgo
....ogmllllmmgmmmgo
...ogmllllmmgmmmmgo
...ogmlllmmgmmrRmggo
...ogmlllmmgmrRRgmllgo
..ogmllllmmgmrRRgmmllgo
..ogmlllmmgmrRRRgmllmmgo
..ogmlllmmgmrRRRgmllmmgo
.ogmllllmmgmrRRrgmlllmmgo
.ogmlllmmgmrRRrgmllmmmgo
.ogmllmmgmrRRrgmllmmmgo
.ogmmmmggrRRrggmmmmmgo
..oggggrRRRr...ogggo
....oHHhho.....oHHhho
....ohhhho.....ohhhho
...ohhhhho.....ohhhhho
...ohhhhho.....ohhhhho
...ohhhhoo.....ohhhhhoo
..oooooooo....oooooooo
..ooooooo.....ooooooo
''')
block(a,45,27,'''
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
oco
''')
patch(a,[(40,34,'ostttcCo'),(39,35,'osuuutcCo'),(40,36,'otttccCo')])
save('windup',a)
a=read('move')
for y in range(27,61): a[y]=list('.'*64)
block(a,10,27,'''
................ogmlwWWWwggo
.............oggmlllwwWwgmlgo
.........ogggmlllllmmwWgmlmlgo
......oggmllllllmmmmmgmlmmmllgo
....ogmllllllmmmgggmlmmmmmllmgo
...ogmllllmmmmgggmlmmmmmmllmmgo
..ogmlllmmmmgggmlmmmmmmllmmmgo
..ogmlllmmmggmlmmmmmmllmmmmgo
...ogmllmmgmlmmmmmmllmmmrrgo..ostto
....ogmmgmlmmmmmmmllmmmrRRgo.osuutto
.....ogrrRRrmmmmmmmggggrRRgo..ottto
......ogrrrRRrmmmmmgggrrrgo
.......ogrrRRrgmmmmmgggggo
........ogggggmmmmmmmgo
.........ogmllllmmmmmmggo
........ogmllllmmmmmgmmmllgo
.......ogmllllmmmmmggmmmlllgo
......ogmllllmmmmggrRgmlllllmgo
.....ogmllllmmmggrRRRgmllllllmgo
....ogmllllmmmgrRRRRrgmmllllllmgo
...ogmllllmmgrRRRRRr..ogmmmllllmgo
..ogmllllmmgrRRRRr......ogmmmlllgo
..ogmlllmmgrRRRr.........ogmmlllgo
...ogmmmgggrRr............ogmllmgo
....ogggg..................ogmmgo
...oHHhho...................ogggo
..ohhhhho...................oHHhho
.ohhhhho....................ohhhho
.ohhhhho....................ohhhhho
.ohhhhoo....................ohhhhhoo
.ohhhhoo....................ohhhhhoo
.oooooooo...................oooooooo
.oooooooo...................oooooooo
.ooooooo....................ooooooo
''')
# Extended forward grip joins a single shaft, y27..60, x51.
block(a,51,27,'''
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
cCo
oco
''')
patch(a,[(49,24,'..ocCo..'),(49,25,'.oCccCo.'),(49,26,'..ocCo..'),(45,35,'ostttcCo'),(44,36,'osuuuttCo'),(45,37,'ottcccCo')])
save('move',a)
for name in ['windup','move']:
    png(read(name)).resize((384,384),Image.Resampling.NEAREST).save(ROOT/'progress'/(name+'-6x.png'))
# Attack: open shoulders, low planted stance, right hand extends the bell.
a=blank()
block(a,26,11,'''
...ooo
..oHhho
..ohhho
.oohooo
.oHhssssso
.oHhsuuuuuto
.ohsuuuuuutto
.ohsuuubbtuubto
.ohsuuuuttuuttu
.ohsuuuWotuWoto
.ohstuuuotuutto
..osstuuutsutto
..owstttbuutto
..owWstttttwo
...owWWtWWWo
...owWWWWWo
..ogwWWWWwggo
..ogmlwWWWwmggo
''')
block(a,9,29,'''
.................ogmlwwWwgmlggo
..............oggmlllmmwgmlmllmggo
..........ogggmllllmmmgmlmmmllllmmggo
.......oggmlllllmmggggmlmmmllllllllmmgo
.....ogmllllmmggggmlllmmmmggmmmllllllmgo
....ogmllllmmg..ogmllmmmmmg..ogmllmmrrRgo
...ogmllllmmgo..ogmlmmmmmg....oggmrrRRRgo
..ogmllllmmgo....ogmmmmmg.......ogrrRRgo
.ogmlllmmmgo.....ogmmmmmgo.......ogggo
ogmlllmmmgo......ogmmmmmgo
ogmlmmrrgo.......ogmmmmmgo
ogmmrrRRgo.......ogmmmmmgo
.ogrrRRgo........ogmllllmggo
..ogrrgo........ogmllllmmmlmggo
...ossto.......ogmllllmmgmmllmgo
...ottto......ogmllllmmgrRgmllmgo
.............ogmllllmmgrRRgmlllmgo
............ogmllllmmgrRRRgmllllmgo
...........ogmllllmmgrRRRrgmlllllmgo
..........ogmllllmmgrRRRRrgmmmllllmgo
.........ogmllllmmgrRRRRr..ogmmllllmgo
........ogmlllmmgrRRRRr....ogmmllllmgo
.......ogmlllmmgrRRRr......ogmmmlllgo
......ogmlllmmgrRRr.........ogmmllmgo
......ogmllmmgggr............ogmmmgo
.......ogggggo...............ogggo
.......oHHhho................oHHhho
......ohhhhho................ohhhho
.....ohhhhho.................ohhhhho
.....ohhhhoo.................ohhhhhoo
....oooooooo................oooooooo
....ooooooo.................ooooooo
''')
# Shoulder-to-palm contact sits underneath the horizontal shaft.
patch(a,[(43,32,'mllllmostttu'),(44,33,'mmmllgosuutto'),(45,34,'mrrRgoottto')])
patch(a,[(29,31,'occcccccccCCCCCCCCCCCCCCo'),(30,32,'occccccccccccccccccccco')])
block(a,53,27,'''
...oo
..ocCo
.oCCcCo
ocC..cCo
ocCCCCCo
.ocCCco
..ocCo
.oCCcCo
.oCccCo
..ocCo
''')
# Green expulsive jet, anchored directly to bell's right rim x60 y31.
patch(a,[(59,26,'..ee'),(58,27,'..eEe'),(59,28,'.eEe'),(60,29,'eEe'),(60,30,'EEe'),(60,31,'EEe'),(60,32,'eEe'),(59,33,'eeEe'),(58,34,'..ee'),(59,35,'.ee')])
save('attack',a)
# Recovery: wrists lower, split hem gathers, staff settles at a steep slant.
a=blank()
block(a,24,9,'''
...ooo
..oHhho
..ohhho
.oohooo
.oHhssssso
.oHhsuuuuuto
.ohsuuuuuutto
.ohsuuuuuuutto
.ohsuuubbtuubto
.ohsuuuuttuuttu
.ohsuuuWotuWoto
.ohsuuuuotuuoto
.ohstuuuuttuutto
..osstuuutsutto
..owstttbuutto
..owWstttttwo
...owWWtWWWo
...owWWWWWo
..ogwWWWWwggo
''')
block(a,16,28,'''
.......ogmlwWWWwggo
.....ogmlllwwWwgmlggo
....ogmllllmwWgmlmmllgo
...ogmllllmmwgmlmmmllmgo
..ogmlllllmmmgmlmmmlllgo
.ogmlllllmmmgmlmmmlllmmgo
ogmllllmmmmgmlmmmllllmmgo
ogmlllmmmmgmlmmmlllmmmgo
.ogmllmmmgmlmmmlllmmmgo
..ogmlmmgmlmmmlllmmmgo
...ogmmgmlmmgmmmmmgo
....ogrrRRrgmlmmrrgo
....ogrrrRRrgmmrRRgo
.....ogrrRRrmmrRRRgo
.....ogrrrggmmrrRgo
......osttoggmrrgo
......ottto.ggggo
......ogmlllmmmmgo
.....ogmllllmmgmmgo
.....ogmllllmmgmmllgo
....ogmllllmmgrRgmllmgo
....ogmlllmmgrRRgmllmmgo
...ogmllllmmgrRRRgmlllmmgo
...ogmlllmmgrRRRrgmlllmmgo
...ogmllmmgrRRRRrgmlmmmgo
...ogmmmmggRRRRrggmmmmgo
....oggggrRRRr...ogggo
......oHHhho.....oHHhho
......ohhhho.....ohhhho
.....ohhhhho.....ohhhhho
....ohhhhhoo.....ohhhhhoo
....oooooooo....oooooooo
....ooooooo.....ooooooo
''')
block(a,42,27,'''
.oo
ocCo
ocCCco
oc..Co
ocCCCo
.ocCo
ocCcCo
ocCCCo
.ocCo
..cCo
..cCo
...cCo
...cCo
....cCo
....cCo
.....cCo
.....cCo
......cCo
......cCo
.......cCo
.......cCo
........cCo
........cCo
.........cCo
.........cCo
..........cCo
..........cCo
...........cCo
...........cCo
............cCo
............cCo
.............cCo
.............cCo
..............oco
''')
patch(a,[(38,41,'rRRosttcCo'),(38,42,'rrgosuutCo'),(39,43,'go.ottcCo')])
save('recover',a)
# Recoil: elbow folds toward ribs, torso bends back, eyes narrowed and brow pinched.
a=blank()
block(a,21,11,'''
...ooo
..oHhho
..ohhho
.oohooo
.oHhssssso
.oHhsuuuuuto
.ohsuuuuuutto
.ohsuuuubtuubto
.ohsuuubbuubbto
.ohsuuuWotuWoto
.ohstuuuotuutto
..osstuuutsutto
..owstttbbtuto
..owWsttbtwo
...owWWtWWo
...owWWWWo
..ogwWWWWwggo
''')
block(a,13,28,'''
.......ogmlwWWWwggo
.....ogmlllwwWwgmlggo
...oggmllllmwWgmlmmmllgo
..ogmllllllmmwgmlmmllllgo
.ogmlllllmmmggmlmmllllmmgo
ogmllllmmgggmlmmmlllmmgo
ogmlllmmggmlmmmllllmmgo
.ogmllmmgmlmmmllllmmgo
..ogmmmggmlmmllllmmgo
...ogrrRRrggmlmmmrrgo
...ogrrrRRrggmmrRRgo
....ogrrRRrggmrRRRgo
.....oggggggmmrrRgo
......ogmllllmmrrgo
......ogmllllmmgggo
......ogmllllmmgmmgo
.....ogmllllmmgmmmllgo
....ogmllllmmgmrRgmllgo
...ogmllllmmgmrRRgmllmgo
..ogmllllmmgmrRRRgmllmmgo
..ogmlllmmgmrRRRRgmllmmgo
...ogmlmmgmrRRRRrgmllmmgo
....ogmmggrRRRRrggmmmgo
.....ogggrRRRr...ogggo
......oHHhho.....oHHhho
......ohhhho.....ohhhho
.....ohhhhho.....ohhhhho
.....ohhhhho.....ohhhhho
....ohhhhhoo.....ohhhhhoo
....ohhhhhoo.....ohhhhhoo
....oooooooo....oooooooo
....oooooooo....oooooooo
....ooooooo.....ooooooo
''')
block(a,42,30,'''
.oo
ocCo
ocCCco
oc..Co
ocCCCo
.ocCo
ocCcCo
ocCCCo
.ocCo
..cCo
...cCo
...cCo
....cCo
....cCo
.....cCo
......cCo
......cCo
.......cCo
.......cCo
........cCo
.........cCo
.........cCo
..........cCo
..........cCo
...........cCo
............cCo
............cCo
.............cCo
.............cCo
..............cCo
..............oco
''')
patch(a,[(33,37,'rRRosttto'),(33,38,'rRgosuutto'),(34,39,'gmmotttto'),(37,40,'rrRosttccCo'),(38,41,'rRgosuutcCo'),(39,42,'go..ottcCo')])
save('hit',a)
# Fallen: independently drawn sideward head, bent forearm, crumpled robe and tucked feet.
a=blank()
block(a,12,42,'''
.....oooo
....oHhhhoo
...oHhhhhHho
..oHhssssooooo
..ohsuuuuttttto
.ohsuuuuuuttutto
.ohsuuubbuutbbtto
.ohsuuuuuuttuuttto
..osstuuubooubttto
..owstttttuusutto
...owWsttttttstto
....owWWsttWWwo
.....owWWWWWwo
......owWWwwgggo
.......owwgmlmlggo
........ogmlllmmmggo
''')
block(a,27,49,'''
......oggggo
....ogmllmmggo
..ogmllllmmmlmggo
.ogmlllllmmmmmllmggo
ogmllllmmmmgmmmlllmmgo
ogmlllmmggrRRrgmmmmmgo
.ogmllmggrRRRRrgmmmmgo
..ogmmggrRRRRRrggmmgo
...ogggRRRRRrggmmmgo
...ogrrRRRrggmmmmgo
..ogrrRRrggmmmmgggo
..oggggggggggggggo
''')
block(a,47,53,'''
..oHHho
.ohhhho
.ohhhho
ohhhhho
ohhhhoo
ohhhho
oooooo
ooooo
''')
patch(a,[(23,54,'ogmllmmgosttto'),(22,55,'ogmlllmgosuutto'),(23,56,'ogmmmrrgotttto'),(24,57,'ogggrRgo'),(25,58,'oggggo')])
patch(a,[(28,59,'occcccccccccccccccCCCCCCCCCCo'),(29,60,'occcccccccccccccccccccccccco')])
block(a,54,53,'''
..oo
.ocCo
ocCCco
oc..Co
ocCCCo
.ocCo
ocCcCo
ocCCCo
''')
save('dead',a)
for name in ['attack','recover','hit','dead']:
    png(read(name)).resize((384,384),Image.Resampling.NEAREST).save(ROOT/'progress'/(name+'-6x.png'))
# Skill charge: left palm cups a compact soul ember at the breast.
a=blank()
block(a,24,9,'''
...ooo
..oHhho
..ohhho
.oohooo
.oHhssssso
.oHhsuuuuuto
.ohsuuuuuutto
.ohsuuuuuuutto
.ohsuuubbtuubto
.ohsuuuuttuuttu
.ohsuuuWotuWoto
.ohstuuuotuutto
.ohstuuuuttuutto
..osstuuutsutto
..owstttbuutto
..owWstttttwo
...owWWtWWWo
...owWWWWWo
..ogwWWWWwggo
''')
block(a,17,28,'''
......ogmlwWWWwggo
....ogmlllwwWwgmlgo
...ogmllllmwWgmlmmgo
..ogmllllmmwgmlmmmllgo
.ogmlllllmmmgmlmmmlllgo
ogmlllllmmggmlmmmmmlllgo
ogmllllmmgmlmmmmmllllmgo
ogmlllmmgmlmmrrgmmmllmgo
.ogmllmmgmlmrRRgmmmllmgo
..ogmmmgggmrRRRgmmlllgo
...ogrrRRrgmrRRgmmmllmgo
....ogrrrRRrgmmgmmmllmmgo
.....ogrrRRrggmmgmmmmmgo
......ogggggmmmgggmmmgo
......ogmlllmmmg..oggo
......ogmlllmmgmmgo
.....ogmllllmmgmmllgo
.....ogmlllmmgmrRgmllgo
....ogmllllmmgmrRRgmllmgo
....ogmlllmmgmrRRRgmllmmgo
...ogmllllmmgmrRRRgmlllmmgo
...ogmlllmmgmrRRRrgmlllmmgo
...ogmllmmgmrRRRRrgmllmmmgo
...ogmmmmggRRRRrggmmmmmgo
....oggggrRRRr....ogggo
......oHHhho......oHHhho
......ohhhho......ohhhho
.....ohhhhho......ohhhhho
.....ohhhhho......ohhhhho
....ohhhhhoo......ohhhhhoo
....ohhhhhoo......ohhhhhoo
....oooooooo.....oooooooo
....ooooooo......ooooooo
''')
block(a,45,14,'''
...oo
..ocCo
.oCCcCo
ocC..cCo
ocC..cCo
.ocCCco
..ocCo
.oCCcCo
.oCccCo
..ocCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...cCo
...oco
''')
patch(a,[(31,34,'ee'),(30,35,'eEe'),(29,36,'eEEEe'),(30,37,'eEEe'),(31,38,'eee'),(30,39,'ostttu'),(31,40,'ottto'),(40,38,'mlllmosttcCo'),(40,39,'mmrrgosuutCo'),(41,40,'rrgo..ottcCo')])
save('skill_a',a,True)
# Skill contact: torso opens; forward bell releases three separately shaped tongues.
a=blank()
block(a,25,11,'''
...ooo
..oHhho
..ohhho
.oohooo
.oHhssssso
.oHhsuuuuuto
.ohsuuuuuutto
.ohsuuubbtuubto
.ohsuuuuttuuttu
.ohsuuuWotuWoto
.ohstuuuotuutto
..osstuuutsutto
..owstttbuutto
..owWstttttwo
...owWWtWWWo
...owWWWWWo
..ogwWWWWwggo
..ogmlwWWWwggo
''')
block(a,13,29,'''
............ogmlwwWwgmlgo
.........oggmlllmmwgmlmmggo
.......ogmlllllmmmgmlmmmllmggo
.....ogmlllllmmgggmlmmmmlllmmgo
...ogmllllmmgggmlmmmmmlllllmmgo
..ogmllllmmggmlmmmmmllllmmmggo
.ogmllllmmgmlmmmmmmllmmmggo
ogmlllmmggmlmmmmmmllmmggo
ogmllmmgmlmmmmmgggggggo
.ogmmmggmlmmmmgggo
..ogrrRRrggmmmmgo
...ogrrrRRrggmmgo
....ogrrRRrggmgo
.....ogggggmmgo
......ogmllllmmggo
.....ogmllllmmgmmllgo
....ogmllllmmgrRgmlllgo
...ogmllllmmgrRRgmllllmgo
..ogmllllmmgrRRRgmllllmmgo
.ogmllllmmgrRRRRgmlllllmmgo
ogmllllmmgrRRRRrgmmmllllmmgo
ogmlllmmgrRRRRr..ogmmmlllmmgo
.ogmllmmgrRRRr....ogmmmlllgo
..ogmmmggRRr.......ogmmmllgo
...oggggo...........ogmmmgo
...oHHhho............ogggo
..ohhhhho............oHHhho
..ohhhhho............ohhhho
.ohhhhhoo............ohhhhho
.ohhhhhoo............ohhhhhoo
.oooooooo...........oooooooo
.ooooooo............ooooooo
''')
patch(a,[(31,34,'ostttu'),(31,35,'osuuto'),(32,36,'ottto'),(39,33,'llmmmgo'),(39,34,'mmrrRmostttu'),(40,35,'rrRgosuutto'),(41,36,'rgo.otttto')])
# Long slanted shaft to right bell: rows chosen individually.
patch(a,[(51,25,'cCo'),(50,26,'cCo'),(50,27,'cCo'),(49,28,'cCo'),(49,29,'cCo'),(48,30,'cCo'),(48,31,'cCo'),(47,32,'cCo'),(47,33,'cCo'),(46,34,'cCo'),(46,35,'cCo'),(45,36,'cCo'),(45,37,'cCo'),(44,38,'cCo'),(44,39,'cCo'),(43,40,'cCo'),(43,41,'cCo'),(42,42,'cCo'),(42,43,'cCo'),(41,44,'cCo'),(41,45,'cCo'),(40,46,'cCo'),(40,47,'cCo'),(39,48,'cCo'),(39,49,'cCo'),(38,50,'cCo'),(38,51,'cCo'),(37,52,'cCo'),(37,53,'cCo'),(36,54,'cCo'),(36,55,'oco')])
block(a,49,16,'''
...oo
..ocCo
.oCCcCo
ocC..cCo
ocC..cCo
.ocCCco
..ocCo
.oCCcCo
.oCccCo
..ocCo
''')
# Three soul branches: hooked upper flame, broad central crest, torn lower tongue.
patch(a,[(59,11,'..ee'),(59,12,'.eEe'),(58,13,'.eEEe'),(57,14,'.eEEe'),(57,15,'eEEe'),(56,16,'eEEe'),(55,17,'eEEe'),(55,18,'EEe'),(55,19,'EEe'),(55,20,'EEee'),(55,21,'eEEEee'),(56,22,'eEEEEee'),(56,23,'eEEEEEe'),(55,24,'eeEEEEe'),(56,25,'.eeEEEe'),(55,26,'eEEe.ee'),(55,27,'EEe'),(56,28,'EEe'),(56,29,'eEEe'),(57,30,'eEEEe'),(58,31,'eEEEe'),(59,32,'eEEe'),(60,33,'ee')])
save('skill_b',a,True)
# Skill recovery: hands open and lowered, robe returns to a narrow base; detached remnants.
a=blank()
block(a,24,8,'''
...ooo
..oHhho
..ohhho
.oohooo
.oHhssssso
.oHhsuuuuuto
.ohsuuuuuutto
.ohsuuuuuuutto
.ohsuuubbtuubto
.ohsuuuuttuuttu
.ohsuuuWotuWoto
.ohsuuuuotuuoto
.ohstuuuuttuutto
..osstuuutsutto
..owstttbuutto
..owWstttttwo
...owWWtWWWo
...owWWWWWo
..ogwWWWWwggo
''')
block(a,17,27,'''
......ogmlwWWWwggo
....ogmlllwwWwgmlggo
...ogmllllmwWgmlmmllgo
..ogmllllmmwgmlmmmlllgo
.ogmlllllmmmgmlmmmlllmmgo
ogmlllllmmmgmlmmmllllmmgo
ogmllllmmmmgmlmmmlllmmmgo
ogmlllmmmmgmlmmmlllmmmgo
.ogmllmmmgmlmmmlllmmmgo
..ogmlmmgmlmmmlllmmmgo
...ogmmgmlmmgmmmmmmgo
...ogrrRRrgmlmmgmmmgo
...ogrrrRRrgmmgmmrrgo
....ogrrRRrmmgmmrRRgo
....ogrrrggmmgmrRRRgo
.....osttoggmmgrrRgo
.....ottto.gmmgrrgo
.....ogmlllmmmggggo
....ogmllllmmgmmmgo
....ogmllllmmgmmllgo
...ogmllllmmgrRgmllmgo
...ogmlllmmgrRRgmllmmgo
..ogmllllmmgrRRRgmlllmmgo
..ogmlllmmgrRRRrgmlllmmgo
..ogmllmmgrRRRRrgmlmmmgo
..ogmmmmggRRRRrggmmmmgo
...oggggrRRRr...ogggo
.....oHHhho.....oHHhho
.....ohhhho.....ohhhho
....ohhhhho.....ohhhhho
....ohhhhho.....ohhhhho
...ohhhhhoo.....ohhhhhoo
...oooooooo....oooooooo
...ooooooo.....ooooooo
''')
block(a,46,20,'''
.oo
ocCo
ocCCco
oc..Co
ocCCCo
.ocCo
ocCcCo
ocCCCo
.ocCo
..cCo
..cCo
..cCo
...cCo
...cCo
...cCo
....cCo
....cCo
....cCo
.....cCo
.....cCo
.....cCo
......cCo
......cCo
......cCo
.......cCo
.......cCo
.......cCo
........cCo
........cCo
........cCo
.........cCo
.........cCo
.........cCo
..........cCo
..........cCo
..........cCo
...........cCo
...........cCo
...........cCo
............cCo
............oco
''')
patch(a,[(40,40,'rrRostttu'),(40,41,'rrgosuuuttccCo'),(41,42,'go..ottttccCo'),(52,13,'ee'),(52,14,'eEe'),(53,15,'ee'),(59,21,'eEe'),(60,22,'ee'),(56,29,'eE'),(56,30,'ee'),(60,36,'e')])
save('skill_c',a,True)
for name in ['skill_a','skill_b','skill_c']:
    png(read(name,True)).resize((384,384),Image.Resampling.NEAREST).save(ROOT/'progress'/(name+'-6x.png'))
# Poison A: abdomen held, shoulders rounded, narrowed eyes and pursed mouth.
a=blank()
block(a,26,13,'''
...ooo
..oHhho
..ohhho
.oohooo
.oHhssssso
.oHhsuuuuuto
.ohsuuuuuutto
.ohsuuubbtuubto
.ohsuuubbuubbto
.ohsuuuWotuWoto
.ohstuuuotuutto
..osstuuutsutto
..owstttbbtuto
..owWsttbtwo
...owWWtWWWo
...owWWWWWo
..ogwWWWWwggo
..ogmlwWWWwggo
..ogmmlwwWwggo
''')
block(a,16,32,'''
.........ogmlllmmwgmlgo
.......ogmllllmmmgmlmmgo
.....ogmlllllmmmggmlmmllgo
...ogmlllllmmmggmlmmmlllgo
..ogmllllmmmggmlmmmllllmgo
.ogmllllmmggmlmmmllllmmmgo
ogmlllmmggmlmmmllllmmmmgo
ogmllmmgmlmmmllllmmgggggo
.ogmmmggmlmmllllmggrRRgo
..ogrrRRrggllllmggrRRRgo
...ogrrrRRrggmmgggmrRRgo
....ogrrRRrggggmmmmrrgo
.....ogggggmmmmmgggggo
......ogmlllmmgmmmgo
.....ogmllllmmgrRgmllgo
....ogmllllmmgrRRgmllmgo
...ogmllllmmgrRRRgmllmmgo
...ogmlllmmgrRRRRgmllmmgo
....ogmlmmgrRRRRrgmllmmgo
.....ogmmggrRRRRrggmmmgo
......ogggrRRRr...ogggo
.......oHHhho.....oHHhho
.......ohhhho.....ohhhho
......ohhhhho.....ohhhhho
......ohhhhho.....ohhhhho
.....ohhhhhoo.....ohhhhhoo
.....ohhhhhoo.....ohhhhhoo
.....oooooooo....oooooooo
.....ooooooo.....ooooooo
''')
block(a,45,28,'''
.oo
ocCo
ocCCco
oc..Co
ocCCCo
.ocCo
ocCcCo
ocCCCo
.ocCo
..cCo
..cCo
...cCo
...cCo
....cCo
....cCo
.....cCo
.....cCo
......cCo
......cCo
.......cCo
.......cCo
........cCo
........cCo
.........cCo
.........cCo
..........cCo
..........cCo
...........cCo
...........cCo
............cCo
............cCo
.............cCo
.............oco
''')
patch(a,[(32,42,'ostttu'),(33,43,'osuuto'),(34,44,'ottto'),(40,42,'mrrRostttcCo'),(41,43,'rrgosuuuttCo'),(42,44,'go..ottccCo')])
# Individually placed toxic bubbles, with dark hollow centres.
patch(a,[(14,17,'ee'),(13,18,'eEge'),(13,19,'egge'),(14,20,'ee'),(53,16,'e'),(52,17,'eEe'),(53,18,'e'),(10,36,'ee'),(9,37,'eEge'),(9,38,'egge'),(10,39,'ee'),(58,43,'ee'),(57,44,'eEge'),(57,45,'egge'),(58,46,'ee')])
save('poison_a',a,True)
# Poison B: cough into raised left palm, weight sinks farther into the knees.
a=blank()
block(a,25,14,'''
...ooo
..oHhho
..ohhho
.oohooo
.oHhssssso
.oHhsuuuuuto
.ohsuuuuuutto
.ohsuuubbtuubto
.ohsuuubbuubbto
.ohsuuuWotuWoto
.ohstuuuotuutto
..osstuuutsutto
..owstttbbtuto
..owWsttbbwo
...owWWtWWWo
...owWWWWWo
..ogwWWWWwggo
..ogmlwWWWwggo
''')
block(a,15,32,'''
..........ogmlllmmwgmlgo
........ogmllllmmmgmlmmgo
......ogmlllllmmmggmlmmllgo
....ogmlllllmmmggmlmmmlllgo
...ogmllllmmmggmlmmmllllmgo
..ogmllllmmggmlmmmllllmmmgo
.ogmllllmmgmlmmmllllmmmmgo
ogmlllmmggmlmmllllmmmgggo
ogmllmmgmlmmllllmmggrRRgo
.ogmmmggmlmmlllmmggrRRRgo
..ogrrRRrgglllmmggmrRRgo
...ogrrrRRrggmmgggmmrrgo
....ogrrRRrggggmmmmggggo
.....ogggggmmmmmggmgo
......ogmlllmmgmrRgmllgo
.....ogmllllmmgrRRgmllmgo
....ogmllllmmgrRRRgmllmmgo
....ogmlllmmgrRRRRgmllmmgo
.....ogmlmmgrRRRRrgmllmmgo
......ogmmggrRRRRrggmmmgo
.......ogggrRRRr...ogggo
........oHHhho.....oHHhho
........ohhhho.....ohhhho
.......ohhhhho.....ohhhhho
.......ohhhhho.....ohhhhho
......ohhhhhoo.....ohhhhhoo
......ohhhhhoo.....ohhhhhoo
......oooooooo....oooooooo
......ooooooo.....ooooooo
''')
# Raised elbow and small hand at the mouth, explicit redraw of the chest sleeve.
block(a,25,28,'''
........ostto
.......osuutto
......ogotttto
.....ogmlrrgo
....ogmllrRRgo
...ogmlllmrRRgo
..ogmllllmmrRgo
.ogmllllmmmgggo
ogmllllmmmgggo
ogmlllmmmgggo
.ogmmmmmgggo
..oggggggo
''')
block(a,46,30,'''
.oo
ocCo
ocCCco
oc..Co
ocCCCo
.ocCo
ocCcCo
ocCCCo
.ocCo
..cCo
..cCo
...cCo
...cCo
....cCo
....cCo
.....cCo
.....cCo
......cCo
......cCo
.......cCo
.......cCo
........cCo
........cCo
.........cCo
.........cCo
..........cCo
..........cCo
...........cCo
...........cCo
............cCo
............oco
''')
patch(a,[(41,43,'mrrRostttcCo'),(42,44,'rrgosuuuttCo'),(43,45,'go..ottccCo'),(12,23,'e'),(11,24,'eEe'),(12,25,'e'),(49,11,'ee'),(48,12,'eEge'),(48,13,'egge'),(49,14,'ee'),(11,45,'eee'),(10,46,'eEgge'),(10,47,'eggge'),(11,48,'eee'),(58,36,'e'),(57,37,'eEe'),(58,38,'e')])
save('poison_b',a,True)
# Stun A: slack mouth, sagging shoulders, hands hanging, knees buckle inward.
a=blank()
block(a,22,12,'''
...ooo
..oHhho
..ohhho
.oohooo
.oHhssssso
.oHhsuuuuuto
.ohsuuuuuutto
.ohsuuubbtuubto
.ohsuuuuttuuttu
.ohsuuuWotuWoto
.ohstuuuotuutto
..osstuuutsutto
..owstttbuutto
..owWsttobtwo
...owWWoWWWo
...owWWWWWo
..ogwWWWWwggo
..ogmlwWWWwggo
''')
block(a,13,30,'''
........ogmlllwwWwgmlgo
......ogmllllmmwWgmlmmggo
....ogmllllllmmwgmlmmmllgo
...ogmlllllmmmmgmlmmmlllgo
..ogmlllllmmmmgmlmmmllllgo
.ogmllllmmmmmgmlmmmllllmmgo
ogmllllmmmmmggmlmmllllmmmgo
ogmlllmmmmggmlmmmllllmmmgo
.ogmllmmmggmlmmmllllmmmgo
.ogmlmmmggmlmmmlllmmmgo
..ogmmmgmlmmmgggmmmgo
..ogrrRRrgmlmmggrRRgo
...ogrrrRRrmmmmggrRRRgo
....ogrrRRrmmmmggmrRRgo
.....ogrrrggmmmmmmrrgo
......osttoggmmgggggo
......ottto.gmgggo
......ogmlllmmgrRgmllgo
.....ogmllllmmgrRRgmllmgo
.....ogmlllmmgrRRRgmllmmgo
......ogmlmmgrRRRrgmllmmgo
.......ogmmggrRRrggmmmgo
........ogggRRRr...ogggo
........oHHhho.....oHHhho
.......ohhhhho.....ohhhho
.......ohhhhho.....ohhhhho
......ohhhhhoo.....ohhhhho
......ohhhhhoo.....ohhhhhoo
......ohhhhhoo.....ohhhhhoo
......oooooooo....oooooooo
......ooooooo.....ooooooo
''')
block(a,43,32,'''
.oo
ocCo
ocCCco
oc..Co
ocCCCo
.ocCo
ocCcCo
ocCCCo
.ocCo
..cCo
...cCo
...cCo
....cCo
....cCo
.....cCo
.....cCo
......cCo
......cCo
.......cCo
.......cCo
........cCo
........cCo
.........cCo
.........cCo
..........cCo
..........cCo
...........cCo
...........cCo
............oco
''')
patch(a,[(38,44,'rrRostttcCo'),(39,45,'rrgosuuuttCo'),(40,46,'go..ottccCo')])
# Four-prong stars, manually chosen unequal clusters.
patch(a,[(16,6,'C'),(15,7,'CuC'),(13,8,'CCuuuCC'),(15,9,'CuC'),(16,10,'C'),(43,10,'C'),(42,11,'CuC'),(41,12,'CuuuC'),(42,13,'CuC'),(43,14,'C')])
save('stun_a',a,True)
# Stun B: head sways right, one shoulder drops, mouth opens farther.
a=blank()
block(a,26,13,'''
..ooo
.oHhho
.ohhho
oohooo
oHhssssso
oHhsuuuuuto
ohsuuuuuutto
ohsuuubbtuubto
ohsuuuuttuuttu
ohsuuuWotuWoto
ohstuuuotuutto
.osstuuutsutto
.owstttbuutto
.owWsttobtto
..owWWooWWo
..owWWWWWo
.ogwWWWWwggo
.ogmlwWWWwggo
''')
block(a,14,31,'''
...........ogmllwwWwgmlgo
........oggmllllmwWgmlmmgo
......ogmlllllmmmwgmlmmmllgo
....ogmlllllmmmmmgmlmmmlllgo
...ogmllllmmmmmmgmlmmmllllgo
..ogmllllmmmmgggmlmmllllmmgo
.ogmllllmmgggmlmmmllllmmmgo
ogmlllmmggmlmmmllllmmmmmgo
ogmllmmggmlmmmlllmmmmmgo
.ogmmmggmlmmmlllmmmgggo
..ogrrRRrgmlmmgggmmrrgo
...ogrrrRRrmmmmggrRRRgo
....ogrrRRrmmmmggmrRRgo
.....ogrrrggmmmmmmrrgo
......osttoggmmgggggo
......ottto.gmgggo
.......ogmlllmmgrRgmllgo
......ogmllllmmgrRRgmllmgo
......ogmlllmmgrRRRgmllmmgo
.......ogmlmmgrRRRrgmllmmgo
........ogmmggrRRrggmmmgo
.........ogggRRRr...ogggo
........oHHhho.....oHHhho
.......ohhhhho.....ohhhho
.......ohhhhho.....ohhhhho
......ohhhhhoo.....ohhhhho
......ohhhhhoo.....ohhhhhoo
......ohhhhhoo.....ohhhhhoo
......oooooooo....oooooooo
......ooooooo.....ooooooo
''')
block(a,45,33,'''
.oo
ocCo
ocCCco
oc..Co
ocCCCo
.ocCo
ocCcCo
ocCCCo
.ocCo
..cCo
...cCo
...cCo
....cCo
....cCo
.....cCo
.....cCo
......cCo
......cCo
.......cCo
.......cCo
........cCo
........cCo
.........cCo
.........cCo
..........cCo
..........cCo
...........cCo
...........oco
''')
patch(a,[(41,44,'rrRostttcCo'),(42,45,'rrgosuuuttCo'),(43,46,'go..ottccCo'),(21,8,'C'),(20,9,'CuC'),(18,10,'CCuuuCC'),(20,11,'CuC'),(21,12,'C'),(46,5,'C'),(45,6,'CuC'),(44,7,'CuuuC'),(45,8,'CuC'),(46,9,'C')])
save('stun_b',a,True)
# Sleep A: eyelids closed, chin sinks into the beard; both hands rest low.
a=blank()
block(a,24,14,'''
...ooo
..oHhho
..ohhho
.oohooo
.oHhssssso
.oHhsuuuuuto
.ohsuuuuuutto
.ohsuuuuuuutto
.ohsuuubbtuubto
.ohsuuuuttuuttu
.ohsuuubbtuubbto
.ohstuuuuttuutto
..osstuuutsutto
..owstttbuutto
..owWstttttwo
...owWWtWWWo
...owWWWWWo
..ogwWWWWwggo
''')
block(a,16,32,'''
.......ogmlwWWWwggo
.....ogmlllwwWwgmlgo
....ogmllllmwWgmlmmgo
...ogmllllmmwgmlmmmllgo
..ogmlllllmmmgmlmmmlllgo
.ogmlllllmmmgmlmmmlllmmgo
ogmllllmmmmgmlmmmllllmmgo
ogmlllmmmmgmlmmmlllmmmgo
.ogmllmmmgmlmmmlllmmmgo
..ogmlmmgmlmmmlllmmmgo
...ogmmgmlmmgmmmmmgo
....ogrrRRrgmlmmrrgo
....ogrrrRRrgmmrRRgo
.....ogrrRRrmmrRRRgo
.....ogrrrggmmrrRgo
......osttoggmrrgo
......ottto.ggggo
.....ogmllllmmgrRgmllgo
....ogmllllmmgrRRgmllmgo
....ogmlllmmgrRRRgmllmmgo
....ogmllmmgrRRRRrgmlmmmgo
....ogmmmmggRRRRrggmmmmgo
.....oggggrRRRr...ogggo
.......oHHhho.....oHHhho
.......ohhhho.....ohhhho
......ohhhhho.....ohhhhho
.....ohhhhhoo.....ohhhhhoo
.....oooooooo....oooooooo
.....ooooooo.....ooooooo
''')
block(a,43,32,'''
.oo
ocCo
ocCCco
oc..Co
ocCCCo
.ocCo
ocCcCo
ocCCCo
.ocCo
..cCo
...cCo
...cCo
....cCo
....cCo
.....cCo
.....cCo
......cCo
......cCo
.......cCo
.......cCo
........cCo
........cCo
.........cCo
.........cCo
..........cCo
..........cCo
...........cCo
...........cCo
............oco
''')
patch(a,[(38,45,'rrRostttcCo'),(39,46,'rrgosuuuttCo'),(40,47,'go..ottccCo')])
save('sleep_a',a,True)
# Sleep B: deeper nod, sinking shoulders, forearm relaxes and chest cloth exhales.
a=blank()
block(a,25,15,'''
...ooo
..oHhho
..ohhho
.oohooo
.oHhssssso
.oHhsuuuuuto
.ohsuuuuuutto
.ohsuuuuuuutto
.ohsuuubbtuubto
.ohsuuuuttuuttu
.ohsuuubbtuubbto
.ohstuuuuttuutto
..osstuuutsutto
..owstttbuutto
..owWstttttwo
...owWWtWWWo
...owWWWWWo
..ogwWWWWwggo
''')
block(a,16,33,'''
........ogmlwWWWwggo
......ogmlllwwWwgmlgo
.....ogmllllmwWgmlmmgo
....ogmllllmmwgmlmmmllgo
...ogmlllllmmmgmlmmmlllgo
..ogmlllllmmmgmlmmmlllmmgo
.ogmllllmmmmgmlmmmllllmmgo
ogmlllmmmmgmlmmmlllmmmgo
ogmllmmmmgmlmmmlllmmmgo
.ogmlmmmgmlmmmlllmmmgo
..ogmmmggmlmmgmmmmmgo
...ogrrRRrgmlmmrrgo
....ogrrrRRrgmmrRRgo
.....ogrrRRrmmrRRRgo
.....ogrrrggmmrrRgo
......osttoggmrrgo
......ottto.ggggo
.....ogmllllmmgrRgmllgo
....ogmllllmmgrRRgmllmgo
....ogmlllmmgrRRRgmllmmgo
....ogmllmmgrRRRRrgmlmmmgo
....ogmmmmggRRRRrggmmmmgo
.....oggggrRRRr...ogggo
.......oHHhho.....oHHhho
......ohhhhho.....ohhhhho
.....ohhhhhoo.....ohhhhhoo
.....oooooooo....oooooooo
.....ooooooo.....ooooooo
''')
block(a,44,33,'''
.oo
ocCo
ocCCco
oc..Co
ocCCCo
.ocCo
ocCcCo
ocCCCo
.ocCo
..cCo
...cCo
...cCo
....cCo
....cCo
.....cCo
.....cCo
......cCo
......cCo
.......cCo
.......cCo
........cCo
........cCo
.........cCo
.........cCo
..........cCo
..........cCo
...........cCo
...........oco
''')
patch(a,[(39,46,'rrRostttcCo'),(40,47,'rrgosuuuttCo'),(41,48,'go..ottccCo')])
save('sleep_b',a,True)
for name in ['poison_a','poison_b','stun_a','stun_b','sleep_a','sleep_b']:
    png(read(name,True)).resize((384,384),Image.Resampling.NEAREST).save(ROOT/'progress'/(name+'-6x.png'))
# Final connection pass: explicit elbow-to-wrist cloth planes and grips.
a=read('windup')
patch(a,[(48,34,'.....'),(48,35,'.....'),(48,36,'.....'),(34,34,'gmlmmm'),(34,35,'mrRRgo'),(34,36,'rRostt'),(35,37,'gosuut'),(36,38,'gottto')])
save('windup',a)
a=read('move')
patch(a,[(39,34,'mllllmmmgo'),(39,35,'mmmllmostttcCo'),(40,36,'mmrrRosuuuttCo'),(41,37,'rrRgoottcccCo')])
save('move',a)
a=read('attack')
patch(a,[(45,32,'mmmllmgo'),(45,33,'mmrrRosttcCo'),(46,34,'rrRgosuutcCo'),(47,35,'rgo.otttcco')])
save('attack',a)
a=read('recover')
patch(a,[(35,36,'mllllmgo'),(35,37,'mllllmmgo'),(35,38,'mlllmmmgo'),(35,39,'mllmmmrrgo'),(36,40,'mmmmmrrRgo'),(37,41,'gggrRosttcCo'),(38,42,'ggrRgosutcCo'),(39,43,'grRgoottcCo')])
save('recover',a)
a=read('hit')
patch(a,[(33,35,'mllllmmgo'),(33,36,'mllllmmgo'),(34,37,'mlllmmmgo'),(35,38,'mlllmmrrgo'),(36,39,'mmmrrRRgo'),(37,40,'gggrRostcCo'),(38,41,'ggrRosucCo'),(39,42,'grRgoottcCo')])
save('hit',a)
a=read('dead')
patch(a,[(13,50,'.osstuuubbtuubbto'),(14,52,'.owWstttbtttstto')])
save('dead',a)
a=read('skill_a',True)
patch(a,[(38,36,'mllllmmgo'),(38,37,'mmmllmmrrgo'),(39,38,'mmrrRosttcCo'),(40,39,'rrRgosuutCo'),(41,40,'rgo.ottcCo'),(51,39,'.....'),(51,40,'.....')])
save('skill_a',a,True)
a=read('skill_b',True)
patch(a,[(39,32,'mllllmmgo'),(40,33,'mlllmmgo'),(40,34,'mmrrRostcCo'),(41,35,'rrRgosucCo'),(42,36,'rgoottcCo')])
save('skill_b',a,True)
a=read('skill_c',True)
patch(a,[(35,37,'mllllmmmgo'),(36,38,'mllllmmmmgo'),(37,39,'mmmllmmmrrgo'),(38,40,'gggmmmrrRosttcCo'),(39,41,'ggrRRggo.osutcCo'),(40,42,'grRRggo..ottcCo')])
save('skill_c',a,True)
a=read('poison_a',True)
patch(a,[(38,39,'mllllmmmgo'),(38,40,'mllllmmmmgo'),(39,41,'mmmllmmmrrgo'),(40,42,'gggmmmrrRosttcCo'),(41,43,'ggrRRggo.osutcCo'),(42,44,'grRRggo..ottcCo')])
save('poison_a',a,True)
a=read('poison_b',True)
patch(a,[(39,40,'mllllmmmgo'),(39,41,'mllllmmmmgo'),(40,42,'mmmllmmmrrgo'),(41,43,'gggmmmrrRosttcCo'),(42,44,'ggrRRggo.osutcCo'),(43,45,'grRRggo..ottcCo')])
save('poison_b',a,True)
a=read('stun_a',True)
patch(a,[(34,41,'mllllmmmgo'),(35,42,'mllllmmmmgo'),(36,43,'mmmllmmmrrgo'),(37,44,'gggmmmrrRosttcCo'),(38,45,'ggrRRggo.osutcCo'),(39,46,'grRRggo..ottcCo'),(33,25,'boob'),(34,26,'oo')])
save('stun_a',a,True)
a=read('stun_b',True)
patch(a,[(37,41,'mllllmmmgo'),(38,42,'mllllmmmmgo'),(39,43,'mmmllmmmrrgo'),(40,44,'gggmmmrrRosttcCo'),(41,45,'ggrRRggo.osutcCo'),(42,46,'grRRggo..ottcCo'),(37,26,'boob'),(38,27,'oo')])
save('stun_b',a,True)
a=read('sleep_a',True)
patch(a,[(35,42,'mllllmmmgo'),(35,43,'mllllmmmmgo'),(36,44,'mmmllmmmrrgo'),(37,45,'gggmmmrrRosttcCo'),(38,46,'ggrRRggo.osutcCo'),(39,47,'grRRggo..ottcCo')])
save('sleep_a',a,True)
a=read('sleep_b',True)
patch(a,[(36,43,'mllllmmmgo'),(36,44,'mllllmmmmgo'),(37,45,'mmmllmmmrrgo'),(38,46,'gggmmmrrRosttcCo'),(39,47,'ggrRRggo.osutcCo'),(40,48,'grRRggo..ottcCo')])
save('sleep_b',a,True)
# Inspection sheet decodes final source, nearest enlargement is for viewing only.
names=['idle_a','idle_b','idle_c','windup','move','attack','recover','hit','dead','skill_a','skill_b','skill_c','poison_a','poison_b','stun_a','stun_b','sleep_a','sleep_b']
sheet=Image.new('RGB',(720,1560),'#777975')
draw=ImageDraw.Draw(sheet)
for i,name in enumerate(names):
    art=png(read(name,i>=9))
    x=(i%3)*240; y=(i//3)*260
    draw.text((x+8,y+5),name,fill='#ffffff')
    for cy in range(64):
        for cx in range(64):
            col='#B9BCB2' if ((cx//8+cy//8)%2)==0 else '#95998F'
            draw.rectangle((x+8+cx*3,y+28+cy*3,x+10+cx*3,y+30+cy*3),fill=col)
    sheet.paste(art.resize((192,192),Image.Resampling.NEAREST),(x+8,y+28),art.resize((192,192),Image.Resampling.NEAREST))
    sheet.paste(art,(x+168,y+196),art)
    art.save(ROOT/'progress'/(name+'.png'))
    art.resize((384,384),Image.Resampling.NEAREST).save(ROOT/'progress'/(name+'-6x.png'))
sheet.save(ROOT/'progress/suite.png')
# Keep each grip on its actual pre-authored shaft, removing gold spurs at wrists.
a=read('hit'); patch(a,[(43,42,'ottcCo'),(49,42,'.')]); save('hit',a)
a=read('skill_b',True)
patch(a,[(40,34,'mmrrRgo......'),(41,35,'rrRgo........'),(42,36,'rgo..........'),(42,34,'osttcCo'),(42,35,'osutcCo'),(42,36,'ottcCo')]);save('skill_b',a,True)
a=read('poison_a',True)
patch(a,[(38,39,'mllllmmgo.......'),(38,40,'mlllmmrrgo......'),(39,41,'mmmrrRgo.......'),(40,42,'gggrRgo.........'),(41,43,'ggrRgo.........'),(42,44,'grRgo..........'),(48,39,'cCo'),(48,40,'cCo'),(49,41,'cCo'),(45,42,'osttcCo'),(46,43,'osutcCo'),(47,44,'ottcCo')]);save('poison_a',a,True)
a=read('poison_b',True)
patch(a,[(39,40,'mllllmmgo.......'),(39,41,'mlllmmrrgo......'),(40,42,'mmmrrRgo.......'),(41,43,'gggrRgo.........'),(42,44,'ggrRgo.........'),(43,45,'grRgo..........'),(48,40,'cCo'),(49,41,'cCo'),(49,42,'cCo'),(46,43,'osttcCo'),(46,44,'osutcCo'),(48,45,'ottcCo')]);save('poison_b',a,True)
a=read('stun_a',True)
patch(a,[(34,41,'mllllmmgo.......'),(35,42,'mlllmmrrgo......'),(36,43,'mmmrrRgo.......'),(37,44,'gggrRgo.........'),(38,45,'ggrRgo.........'),(39,46,'grRgo..........'),(45,41,'cCo'),(46,42,'cCo'),(46,43,'cCo'),(43,44,'osttcCo'),(43,45,'osutcCo'),(45,46,'ottcCo'),(22,24,'.owstttboobto.....'),(22,25,'.owWstttooWo.....'),(22,26,'..owWWtWWWo......')]);save('stun_a',a,True)
a=read('stun_b',True)
patch(a,[(37,41,'mllllmmgo.......'),(37,42,'mlllmmrrgo......'),(38,43,'mmmrrRgo.......'),(39,44,'gggrRgo.........'),(40,45,'ggrRgo.........'),(41,46,'grRgo..........'),(47,41,'cCo'),(47,42,'cCo'),(48,43,'cCo'),(44,44,'osttcCo'),(45,45,'osutcCo'),(46,46,'ottcCo'),(26,25,'.owstttboobto.....'),(26,26,'.owWstttooWo.....'),(26,27,'..owWWtWWWo......')]);save('stun_b',a,True)
a=read('sleep_a',True)
patch(a,[(35,42,'mllllmmgo.......'),(35,43,'mlllmmrrgo......'),(36,44,'mmmrrRgo.......'),(37,45,'gggrRgo.........'),(38,46,'ggrRgo.........'),(39,47,'grRgo..........'),(46,42,'cCo'),(46,43,'cCo'),(47,44,'cCo'),(43,45,'osttcCo'),(44,46,'osutcCo'),(45,47,'ottcCo')]);save('sleep_a',a,True)
a=read('sleep_b',True)
patch(a,[(36,43,'mllllmmgo.......'),(36,44,'mlllmmrrgo......'),(37,45,'mmmrrRgo.......'),(38,46,'gggrRgo.........'),(39,47,'ggrRgo.........'),(40,48,'grRgo..........'),(47,43,'cCo'),(47,44,'cCo'),(48,45,'cCo'),(44,46,'osttcCo'),(45,47,'osutcCo'),(46,48,'ottcCo')]);save('sleep_b',a,True)
# Redecode after the wrist/face fixes.
sheet=Image.new('RGB',(720,1560),'#777975'); draw=ImageDraw.Draw(sheet)
for i,name in enumerate(names):
    art=png(read(name,i>=9)); x=(i%3)*240; y=(i//3)*260
    draw.text((x+8,y+5),name,fill='#ffffff')
    for cy in range(64):
        for cx in range(64):
            col='#B9BCB2' if ((cx//8+cy//8)%2)==0 else '#95998F'
            draw.rectangle((x+8+cx*3,y+28+cy*3,x+10+cx*3,y+30+cy*3),fill=col)
    large=art.resize((192,192),Image.Resampling.NEAREST)
    sheet.paste(large,(x+8,y+28),large); sheet.paste(art,(x+168,y+196),art)
    art.save(ROOT/'progress'/(name+'.png'))
    art.resize((384,384),Image.Resampling.NEAREST).save(ROOT/'progress'/(name+'-6x.png'))
sheet.save(ROOT/'progress/suite.png')
# Remove the individually observed isolated outline remnants from wrist revisions.
a=read('stun_a',True);patch(a,[(53,45,'.')]);save('stun_a',a,True)
a=read('stun_b',True);patch(a,[(55,44,'.'),(55,45,'..'),(56,46,'.')]);save('stun_b',a,True)
a=read('sleep_a',True);patch(a,[(53,46,'.')]);save('sleep_a',a,True)
a=read('sleep_b',True);patch(a,[(54,47,'.')]);save('sleep_b',a,True)
a=read('poison_a',True);patch(a,[(56,43,'.')]);save('poison_a',a,True)
a=read('poison_b',True);patch(a,[(57,44,'.')]);save('poison_b',a,True)
a=read('attack')
patch(a,[(45,32,'mmmllmosttu'),(45,33,'mmrrRosttto'),(46,34,'rrRgootto'),(47,35,'rgo....')])
block(a,53,27,'''
...oo
..ocCo
.oCCcCo
ocC..cCo
ocCCCCCo
.ocCCco
..ocCo
.oCCcCo
.oCccCo
..ocCo
''')
patch(a,[(59,26,'..ee'),(58,27,'..eEe'),(59,28,'.eEe'),(60,29,'eEe'),(60,30,'EEe'),(60,31,'EEe'),(60,32,'eEe'),(59,33,'eeEe'),(58,34,'..ee'),(59,35,'.ee')])
save('attack',a)
# Final contact sheet: source remains the literal 64x64 grids, all enlargement is inspection.
sheet=Image.new('RGB',(720,1560),'#777975'); draw=ImageDraw.Draw(sheet)
for i,name in enumerate(names):
    art=png(read(name,i>=9)); x=(i%3)*240; y=(i//3)*260
    draw.text((x+8,y+5),name,fill='#ffffff')
    for cy in range(64):
        for cx in range(64):
            col='#B9BCB2' if ((cx//8+cy//8)%2)==0 else '#95998F'
            draw.rectangle((x+8+cx*3,y+28+cy*3,x+10+cx*3,y+30+cy*3),fill=col)
    large=art.resize((192,192),Image.Resampling.NEAREST)
    sheet.paste(large,(x+8,y+28),large); sheet.paste(art,(x+168,y+196),art)
    art.save(ROOT/'progress'/(name+'.png'))
    art.resize((384,384),Image.Resampling.NEAREST).save(ROOT/'progress'/(name+'-6x.png'))
sheet.save(ROOT/'progress/suite.png')
