// Real destination-specific controls/authoring regions, not generic db-body wrappers.
export const DATABASE_PRIMARY_SENTINELS: Readonly<Record<string, string>> = {
  overview: '[data-testid="db-overview-stat-actors"]',
  worldCanon: '[data-testid="db-world-canon-name"]',
  worldCodex: '[data-testid="world-add-entity"]',
  actors: '[data-testid="db-actor-tab-identity"]',
  characterAppearances: '[data-testid="appearance-search"]',
  classes: '[data-testid="db-classes-bm88-workbench"]',
  promotionTree: '[data-testid="growth-studio-promotion"] .growth-toolbar',
  skills: '.oprn-record-skills .db-skill-composer',
  skillTrees: '[data-testid="growth-studio-skill"] .growth-toolbar',
  items: '[data-testid="db-catalog-search"]',
  enemies: '[data-testid="db-enemy-section-basic-tab"]',
  monsterSpecies: '[data-testid="db-monster-species-search"]',
  troops: '[data-testid="db-troop-member-add"]',
  factions: '[data-testid="db-faction-search"]',
  elements: '[data-testid="db-elements-search"]',
  states: '.oprn-detail-states .db-state-oprn-workbench',
  animations: '[data-testid="db-animation-play"]',
  battleScreen: '[data-testid="db-battle-screen-troop-search"]',
  battleCommands: '[data-testid="db-battle-command-search"]',
  crops: '[data-testid="db-crop-search"]',
  characters: '[data-testid="db-character-search"]',
  lifeCrafting: '[data-testid="db-life-section-skills"]',
  dailyWeather: '[data-testid="db-weather-search"], [data-testid="db-weather-seed-defaults"]',
  farmAnimals: '[data-testid="db-farm-animals-seed-defaults"], [data-testid="db-farm-animals-workspace"] .db-ws-list-title',
  farmSpatial: '[data-testid="db-spatial-search"]',
  lifeCollections: '[data-testid="db-life-collections-search"]',
  spatialTiles: '[data-testid="spatial-shell-tiles"]',
  spatialObjects: '[data-testid="spatial-shell-objects"]',
  spatialPlaces: '[data-testid="spatial-shell-places"]',
  spatialRegions: '[data-testid="spatial-shell-regions"]',
  spatialWorlds: '[data-testid="spatial-shell-worlds"]',
  commonEvents: '[data-testid="db-common-event-search"]',
  system: '[data-testid="db-system-nav-font"]',
  opening: '[data-testid="db-cinematic-opening"] [data-testid="db-cinematic-enabled"]',
  gameOver: '[data-testid="db-cinematic-game-over"] [data-testid="db-cinematic-game-over-title"]',
  characterGraphics: '[data-testid="db-cg-import-json"]',
  terms: '[data-testid="db-terms-search"]',
  switches: '[data-testid="db-switch-search"]',
  variables: '[data-testid="db-variable-search"]',
};
