"""Literal native pixel clusters, selected by the author. No drawing primitives.
Only empty canvas allocation, literal row placement and serialization occur here.
Final .pxgrid files, rather than this convenience writer, are the deliverable.
"""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
PAL={'K':'#172329','D':'#392D32','S':'#633B36','B':'#93503E','L':'#BD7750','H':'#E0A96D','U':'#173C3C','V':'#245951','G':'#36796A','J':'#62A385','N':'#A4C599','W':'#68776F','C':'#BCC4AA','F':'#F1E9CE','O':'#9F7436','Y':'#E6BB52','E':'#FFF0AA','P':'#916DAD'}
(ROOT/'palette.json').write_text(json.dumps(PAL,indent=2)+'\n')
def blank(): return [list('.'*128) for _ in range(128)]
def put(a,x,y,rows):
    rows=rows.strip('\n').splitlines()
    for dy,row in enumerate(rows):
        if not 0<=y+dy<128 or x+len(row)>128: raise ValueError((x,y,dy,len(row)))
        for dx,c in enumerate(row):
            if c!='.' and c not in PAL: raise ValueError(c)
            if c!='.': a[y+dy][x+dx]=c
    return a

def crown(a):
    return put(a,8,6,"""
................................................KKK
..............................................KKVJJK
............................................KKVGJNNK
.....................................KK....KVGJJNGVK
...................................KKJJK..KVGJJNGGVUK
..................................KVJNJK.KVGJJJGGVVUK
.................................KVGJNJKKVGJJGGGVVVUKK
......................KK.......KKVGJJGJJGJJGGGGVVVVUGVK
.....................KJJK.....KVGJJJGGJJJJGGVVVVVUUVGVK
...................KKJNJK....KVGJJGGGGGGGGVVVVUUVGJJGVUK
..................KVGJNJK..KKVGJJGGGGGGVVVVUUUUVGGGGVVUK
................KKVGJJGVK.KVGJJJGGGGVVVUUVVGJJJGGGGVVUK
.............KKKVGJJJGGVKKVGJJGGGGGVVUUVGJJJGGGGGVVVUUKK
...........KKVGJJJJGGGVVGJJJJGGGGVVUUVGGGGGGGGGVVVUUUVGVUKK
.........KKVGJJGGGGGGGGJJGGGGGGVVUUVGGGGGGGGVVVVUUUVGJJGGVUK
......KKKVGJJGGGGGGGGGGGGGGGVVVUUVGGGGGGVVVVUUUVGJJJJGGGVVUKK
.....KVGJJJJGGGGGGGGGGGGVVVVVUUVGGGGVVVVVUUUUVGJJGGGGGGGVVVUK
...KKVGJJGGGGGGGGGGVVVVVVUUUUUVVVVVVVUUUUVGJJJGGGGGGGVVVVUUKK
..KVJJGGGGGGGGGVVVVVVUUUUUUUUUUUUUUUUVGJJGGGGGGGVVVVVUUUUVGVK
.KVJGGGGGGGGVVVVVVUUUUUVVGGVVUUUUUUUVGJGGGGGGGVVVVVUUUUVGJJGVUK
KVGGGGGVVVVVVVUUUUVVGJJJGGGGVUUUUUVGGGGGGGGVVVVUUUUUVGJJGGGVVUK
KVVVVVVVUUUUUVVGJJJJGGGGGGGVVUUVGGGGGGGVVVVVUUUUUVGJJJGGGGVVVUKK
KUUUUUUUUUVVGJJJJJGGGGGGGGVVVUGGGGGVVVVVUUUUUVGJJJJGGGGGVVVUUUVK
.KKUUUVVGJJJJJGGGGGGGGVVVVVUUVVVVVVVUUUUUVGJJJGGGGGGGGVVVUUVGJJVK
...KKVGJJJJGGGGGGGGVVVVVUUUUUUUUUUUUUVGJJJJGGGGGGGVVVVVUUVGJGGVUK
..KVGJJGGGGGGGGVVVVVUUUUVVGGVVUUUUVGJJJGGGGGGGVVVVVUUUUVGGGGVVUKK
.KVGJGGGGGGGVVVVVUUUVVGJJJJGGGVUUVGJJGGGGGGVVVVVUUUUUVGGGGVVVVUUUK
KVGGGGGGVVVVVVUUUVVGJJJGGGGGGVVUUGGGGGGVVVVVUUUUUVGGGGVVVVUUUUUKK
KGGGGVVVVUUUUUVVGJJJJGGGGGGVVVUUVVVVVVVUUUUUUUVGGGVVVVUUUUUUKKK
KVVVVVUUUUVVGJJJJGGGGGGGVVVVUUUUUUUUUUUVVGJJGGGVVVVUUUUKKKKK
KUUUUUVVGJJJJGGGGGGGVVVVVUUUUUVVVUUUVVGJJJGGGGVVVVUUUKK
.KKVVGJJJGGGGGGGVVVVVUUUUUVVGGGGVVVGJJJGGGGVVVVVUUUKK
...KVGGGGGGGGVVVVVUUUUUVVGJJJGGGGGGGGGGGGVVVVUUUUKKK
..KVGJGGGGVVVVVUUUUVVGJJGGGGGGGVVVVGGGVVVVUUUKKKK
.KVGGGGVVVVVUUUVVGGJJGGGGGGVVVVVVUUUUVVVUUUKK
KVGGGVVVVUUUUVGJJJGGGGGVVVVVUUUUUUKKKUUUKK
KVVVVVUUUUKKKVGGGGGVVVVVUUUUUKKKKK...KKK
KUUUUUUKKK...KVVVVVVUUUUKKKKK
.KKKKKK.......KUUUUUKKKK
...............KKKKK
""")

def trunk(a):
    return put(a,40,39,"""
................KKDDDSSSSKK
..............KKSLHHLLBSSSDDK
.............KSLHHHLLLBBSSSDDKK
...........KKSLHHHHLLLBBSSSSDDDK
..........KSLHHHHHLLLBBSSSSDDDDDK
.........KSLHHHLLLBBBDDBBBSSDDDDDK
........KSLHHLLLBBBBDDBLLLBBSSDDDDK
.......KSLHLLLBBBSSDDDBLLLBBSSSDDDDK
......KSLHLLBBSSSDDDBBLLLLBBSSSDDDDK
.....KSLHLLBBSSDDDBBLLLLLBBSSSSDDDDK
....KSLHLLBBSSSDDBBLLLLLLBBSSSSDDDDDK
...KSLHLLBBSSDDDKKSSLLLLBBSSSSDDDDDDK
..KSLHLLBBSSDDDKKOOOOKKBBSSKKOOOOKDDK
.KSLHLLBBBSSDDKOOYYYEOKBBKOOYYEOKSDDK
KSLHLLLBBBSSDDDKOYYEEKBBSSKOYYEKSSDDDK
KSLHLLLLBBSSDDDKKOOOKLLBSSDKOOKSSSDDDK
KSLHLLLLBBSSDDDBLLLLHHLLBBSSSSSSDDDDDK
KSLHLLLLBBBSSDDDBLLLHHHLLBBSSSSDDDDDDK
KSLHLLLBBBBSSDDDBBLLHHHLLBBSSSSDDDDDDK
KSLHLLBBBBBSSDDDDBBLLHLLBBSSSSDDDDDDDK
KSLHLBBBSSSSDDDDDDBBLLBBSSSSDDDDDDDDDK
KSLHLBBSSDDDKKWWCCCLLLCCWWKDDDDDDDDDK
KSLHLBBSSDDKWCFFFFFFCCFFFFCWKDDDDDDDDK
KSLHLLBBSSDKWCFFFFFFFCFFFFFCWKDDDDDDDK
KSLHLLLBBSDKWCFFFFFCCFFFFFFFCWKDDDDDDK
KSLHLLLBBSDKWCFFFFFCWCCFFFFFCWKDDDDDDK
KSLHLLBBSSDKWCFFFFFCWWCFFFFFCCWKDDDDDK
KSLHLLBBSSDDKWCFFFFCCWWCFFFFFCCWKDDDDK
KSLHLLBBSSDDKWCFFFFFCWWWCCFFFFCWKDDDK
KSLHLLBBBSSDDKWCFFFFFCWWWCCFFFCWKDDDK
KSLHLLBBBSSDDKWCFFFFFCWWWWCFFFCWKDDK
KSLHLLBBBSSDDDKWCFFFFCCWWWCCFFCWKDDK
KSLHLLBBBSSDDDKWCFFFFFCWWWWCFCWKDDK
KSLHLLBBBSSDDDDKWCFFFFCWKWWCCWKDDDK
KSLHLLBBBSSDDDDKWCFFFCCWKDWWWKDDDDK
KSLHLLLBBSSDDDDDKWCFFCWKDDDDDDDDDDK
KSLHLLLBBBSSDDDDKWCFCWKDDDDDDDDDDDK
KSLHLLLLBBSSDDDDDKWCWKDDDDDDDDDDDDK
KSLHLLLLBBBSSDDDDDKKDDSSSSDDDDDDDDK
KSLHLLLLBBBDDDDDDDDDDDBBBSSSDDDDDDK
KSLHLLLBBBBDDDDDDDDDDBLLBBSSDDDDDDK
KSLHLLBBBSSDDDBBDDDDBLLLBBSSDDDDDDK
KSLHLLBBSSDDDBLLBDDBLLLLBBSSDDDDDDK
KSLHLLBBSSDDDBLLLBBLLLLBBBSSDDDDDDK
KSLHLLLBBSSDDDBLLLLLLLBBBSSDDDDDDDK
KSLHLLLLBBSSDDDBLLLLLBBBSSSDDDDDDDK
.KSLHLLLLBBSSDDDBLLLBBSSSSDDDDDDDK
.KSLHHLLLBBSSDDDBBLBBSSSSDDDDDDDK
..KSLHHLLBBSSDDDBBBBSSSSSDDDDDDDK
..KSLHHLLBBSSDDDBBBSSSSDDDDDDDDK
..KSLHLLBBBSSDDDBBBSSDDDDDDDDDKK
..KSLHLLBBBSSDDDBBBSSDDDDDDDDK
.KSLHHLLBBBSSDDDBBBSSSDDDDDDDK
KSLHHLLLBBBSSDDDBBBSSSDDDDDDDK
KSLHHLLBBSSSDDDDDBBBSSSDDDDDDK
KSLHHLLBBSSDDDDDDDBBBSSDDDDDDK
KSLHLLBBSSDDDDDDDDDBBBSSDDDDDK
KSLHLLBBSSDDDDDDDDDBBBBSSDDDDDK
KSLHLLBBSSDDDDDDDDDDBBBBSSDDDDDK
KSLHLLBBSSDDDDDDDDDDBBBBSSDDDDDDK
KSLHLLBBSSDDDDDDDDDDBBBBBSSDDDDDDK
KSLHLLBBSSDDDDDDDDDDBBBBBBSSDDDDDDK
""")

def left_arm(a):
    return put(a,10,47,"""
...........................KKSSSSKK
........................KKSLHLLBBSSK
......................KKSLHHLLBBSSDDK
....................KKSLHHLLBBBSSDDDK
..................KKSLHHLLBBBSSDDDDK
................KKSLHHLLBBBSSDDDDKK
..............KKSLHHLLBBSSDDDDDKK
.............KSLHHLLBBBSSDDDDKK
............KSLHHLLBBBSSDDDDK
...........KSLHHLLBBBSSDDDDK
...........KSLHHLLBBBSSDDDDK
............KSLHHLLBBSSDDDK
.............KSLHHLLBBSSDDDK
.............KSLHHLLBBBSSDDDK
..............KSLHLLBBBSSDDDK
...............KSLHLLBBBSSDDDK
...............KSLHLLBBBSSDDDK
................KSLHLLBBBSSDDDK
................KSLHLLBBSSDDDDK
.................KSLHLLBBSSDDDDK
.................KSLHLLLBBSSDDDK
................KSLHLLLBBBSSDDDK
...............KSLHLLLLBBBSSDDDK
..............KSLHLLLLBBSSSSDDDK
.............KSLHLLLBBSSDDSSSDDK
............KSLHLLBBSSDDKSSSDDK
...........KSLHLLBBSSDDK.BSSDDK
..........KSLHLLBBSSDDK..BSSDDK
.........KSLHLLBBSSDDK...KSDDK
........KSLHLLBBSSDDK.....KDK
........KSLHLLBBSSDDK......K
.........KSLHLLBBSSDK
..........KSLHLLBBSDK
...........KSLHLLBDK
............KSLHBDK
.............KLLDK
..............KKK
""")

def right_arm(a):
    return put(a,77,48,"""
....KKKKK
...KSLHLLBSKK
..KSLHHLLBBSSKK
.KSLHHHLLBBSSSDKK
KSLHHHLLLBBBSSDDDKK
KSLHHLLLBBBBSSDDDSSK
KSLHLLLBBBSSDDDSLLBSK
KSLHLLBBBSSDDDSLHLLBSK
.KSLHLLBBSSDDDSLHLLBBSDK
..KSLHLLBBSSDDDBLHLLBBSDK
...KSLHLLBBSSDDDBLHLLBBSDK
....KSLHLLBBSSDDDBLHLLBBSDK
.....KSLHLLBBSSDDDBLHLLBBSDK
......KSLHLLBBSSDDDBLHLLBBSDK
.......KSLHLLBBSSDDDBLHLLBBSDK
........KSLHLLBBSSDDDBLHLLBBSDK
.........KSLHLLBBSSDDDBLHLLBBSDK
..........KSLHLLBBSSDDDLHLLBBSDK
...........KSLHLLBBSSDDLHLLBBSDK
............KSLHLLBBSSDLHLLBBSDK
.............KSLHLLBBSSLLHLLBBSDK
..............KSLHLLBBBLLHLLBBSDK
...............KSLHLLBLLHLLBBSSDK
...............KSLHLLLLHLLBBSSDDK
...............KSLHLLLLLLBBSSDDDK
...............KSLHHHLLLBBSSDDDDK
..............KSLHHHLLLBBSSDDDDK
.............KSLHHHLLLBBSSDDDDK
............KSLHHLLLBBBSSDDDDK
...........KSLHHLLLBBBSSDDDDK
..........KSLHHLLLBBSSDDDDK
.........KSLHHLLLBBSSDDDDK
........KSLHHLLLBBSSDDDDK
.......KSLHHLLLBBSSDDDDK
......KSLHHLLLBBSSDDDDK
.....KSLHHLLLBBSSDDDDK
....KSLHHLLLBBSSDDDDK
...KSLHHLLLBBSSDDDDK
...KSLHLLLBBBSSDDDK
....KSLHLLBBSSDDDK
.....KSLHLLBBSSDDK
......KSLHLLBBSSDK
.......KSLHLLBSSK
........KSLBBSSK
.........KSDDK
..........KK
""")

def feet(a):
    return put(a,22,100,"""
................KKSLHLLBBSSDDDK.......KSLHLLBBSSDDDDDK
...............KSLHHLLBBSSDDDDK........KSLHLLLBBSSDDDDDK
..............KSLHHLLLBBSSDDDK.........KSLHLLLBBBSSDDDDDK
.............KSLHHHLLLBBSSDDK..........KSLHLLLLBBBSSDDDDDK
............KSLHHHLLLBBSSDDK...........KSLHLLLLLBBBSSDDDDDK
...........KSLHHHLLLBBSSDDK............KSLHHLLLLLBBBSSDDDDDK
..........KSLHHHLLLBBSSDDK.............KSLHHLLLLLLBBBSSDDDDDK
.........KSLHHHLLLBBSSDDK..............KSLHHLLLLLLLBBBSSDDDDDK
........KSLHHHLLLBBSSDDK...............KSLHHHLLLLLLBBBSSDDDDDK
.......KSLHHHLLLBBSSDDK.................KSLHHHLLLLLLBBBSSDDDDDK
......KSLHHHLLLBBSSDDK...................KSLHHHLLLLLLBBBSSDDDDDK
.....KSLHHHLLLBBSSDDK.....................KSLHHHLLLLLLBBBSSDDDDDK
....KSLHHHLLLBBSSDDK.......................KSLHHHLLLLLLBBBSSDDDDDK
...KSLHHHLLLBBSSDDK.........................KSLHHHLLLLLLBBBSSDDDDDK
..KSLHHHLLLBBSSDDK...........................KSLHHHLLLLLLBBBSSDDDDDK
.KSLHHHLLLBBSSDDK.............................KSLHHHLLLLLLBBBSSDDDDDK
KSLHHHLLLBBSSDDK...............................KSLHHHLLLLLLBBBSSDDDDDK
KSLHHHLLLBBSSDDK................................KSLHHHLLLLLLBBBSSDDDDDK
KSLHHHLLLLBBSSDDKKK..............................KSLHHHLLLLLLBBBSSDDDDDK
KSLHHHHLLLLLBBSSSSSDKKK............................KSLHHHLLLLLLLLBBSSSSDDDKK
KSLHHHHHHLLLLLLLLBBSSSDKK..........................KSLHHHHHHLLLLLLLLBBSSSSDDKK
KSLHHHLLLLBBLLLBBLLLBBSSDKK.......................KSLHHHHLLLLBBLLLBBLLLBBSSDDK
.KSLHLLLBBSSLLBBSSLLLBBSSDDK......................KSLHLLLBBSSLLBBSSLLLBBSSDDK
..KSLBBSSDDDDBSSDDDBBSSDDDK........................KSLBBSSDDDDBSSDDDBBSSDDDK
...KKDDDKKKKDDDKKKKDDDKKK...........................KKDDDKKKKDDDKKKKDDDKKK
""")

def stand():
    a=blank(); crown(a); left_arm(a); trunk(a); right_arm(a); feet(a); return a

def save(name,a,action=False):
    p=ROOT/('actions' if action else 'poses')/(name+'.pxgrid')
    p.write_text('\n'.join(''.join(r) for r in a)+'\n')

if __name__=='__main__': save('idle_a',stand())

# Individually selected grafts: crown-bearing wood, shoulders, heavy root volume.
def grafts(a):
    put(a,43,31,"""
............KSLHLLBBSSDK
...........KSLHHLLBBSSDDK
..........KSLHHHLLBBSSDDDK
.........KSLHHHLLLBBSSDDDK
........KSLHHHLLLLBBSSDDDDK
.......KSLHHHHLLLLBBSSDDDDK
......KSLHHHHLLLLLBBSSDDDDK
.....KSLHHHHLLLLLLBBSSDDDDK
....KSLHHHHLLLLLLLBBSSDDDDK
...KSLHHHHLLLLLLLBBBSSDDDDK
..KSLHHHHLLLLLLLBBBBSSDDDDK
.KSLHHHHLLLLLLLBBBBBSSDDDDK
KSLHHHHLLLLLLLBBBBBBSSDDDDK
KSLHHHLLLLLLLBBBBBBBSSDDDDK
KSLHHLLLLLLBBBBBBBBBSSDDDDK
KSLHLLLLLBBBBBBBBBBBSSDDDDK
""")
    return a

def shoulders(a):
    put(a,33,48,"""
.....KKSLHLLBBSSSSDK
....KSLHHLLLBBSSDDDK
...KSLHHHLLLBBSSDDDK
..KSLHHHLLLLBBSSDDDK
.KSLHHHLLLLBBBSSDDDK
KSLHHHLLLLBBBSSDDDDK
SLHHHLLLLBBBSSDDDDDK
LHHHLLLLBBBSSDDDDDK
HHHLLLLBBBSSDDDDDK
HHLLLLBBBSSDDDDDK
HLLLLBBBSSDDDDDK
LLLLBBBSSDDDDDK
""")
    put(a,72,48,"""
..KKSLHLLBBSSDK
.KSLHHLLLBBSSDDK
KSLHHHLLLBBSSDDDK
SLHHHHLLLBBSSDDDDK
LHHHHLLLLBBBSSDDDDK
HHHHLLLLBBBBSSDDDDK
HHHLLLLLBBBBSSDDDDK
HHLLLLLBBBBBSSDDDDK
HLLLLLBBBBBSSDDDDK
LLLLLBBBBBSSDDDDK
LLLLBBBBBSSDDDDK
LLLBBBBBSSDDDDK
LLBBBBBSSDDDDK
LBBBBBSSDDDDK
BBBBBSSDDDDK
""")
    return a

def pine_tips(a):
    put(a,77,20,"""
...........KK
..........KJJK
.........KJNJK
........KJJGVK
.......KJJGGVK
......KJJGGVVUK
.....KJJGGGVVUK
....KJJGGGVVVUKK
...KJJGGGGVVVUGVK
..KJJGGGGVVVVUGJJK
.KJJGGGGVVVVUGJJGVK
KJJGGGGVVVVUGJGGVVUK
JGGGGGVVVVUGGGGVVVUKK
GGGGGVVVVUGGGVVVVUUUK
GGGVVVVVUGGVVVVUUUUK
GVVVVVVUGVVVVUUUUKK
VVVVVUUVVVVUUUUKK
VVVUUUUVVUUUUKK
VUUUUUKUUUUKK
UUUKKK.KKKK
KKK
""")
    return a

def heavy_roots(a):
    put(a,31,102,"""
........KSLHHHLLLLBBSSDDK
.......KSLHHHLLLLBBSSDDDK
......KSLHHHHLLLLBBSSDDDK
.....KSLHHHHLLLLBBSSDDDK
....KSLHHHHLLLLBBSSDDDK
...KSLHHHHLLLLBBSSDDDK
..KSLHHHHLLLLBBSSDDDK
.KSLHHHHLLLLBBSSDDDK
KSLHHHHLLLLBBSSDDDK
SLHHHHLLLLBBSSDDDK
LHHHHLLLLBBSSDDDK
HHHHLLLLBBSSDDDK
HHHLLLLBBSSDDDK
HHLLLLBBSSDDDK
HLLLLBBSSDDDK
LLLLBBSSDDDK
LLLBBSSDDDK
""")
    put(a,69,103,"""
KSLHHHLLLLBBBSSDDDDK
KSLHHHLLLLLBBBSSDDDDK
KSLHHHHLLLLLBBBSSDDDDK
KSLHHHHLLLLLLBBBSSDDDDK
KSLHHHHLLLLLLLBBBSSDDDDK
.KSLHHHHLLLLLLLBBBSSDDDDK
..KSLHHHHLLLLLLLBBBSSDDDDK
...KSLHHHHLLLLLLLBBBSSDDDDK
....KSLHHHHLLLLLLLBBBSSDDDDK
.....KSLHHHHLLLLLLLBBBSSDDDDK
......KSLHHHHLLLLLLLBBBSSDDDDK
.......KSLHHHHLLLLLLLBBBSSDDDDK
........KSLHHHHLLLLLLLBBBSSDDDDK
.........KSLHHHHLLLLLLLBBBSSDDDDK
..........KSLHHHHLLLLLLLBBBSSDDDDK
...........KSLHHHHLLLLLLLBBBSSDDDDK
""")
    return a

# Retain unfinished preliminary rows in this helper, with the finished baseline below.
def stand():
    a=blank();grafts(a);crown(a);pine_tips(a);left_arm(a);trunk(a);right_arm(a);shoulders(a);feet(a);heavy_roots(a);return a
if __name__=='__main__':save('idle_a',stand())

def right_crown(a):
    put(a,61,17,"""
...................KK
.................KKJJK
................KJJNJK
..............KKJJJGVK
.............KJJJJGGVK
............KJJJGGGGVUK
..........KKJJGGGGGGVUK
.........KJJJGGGGGGVVUKK
.......KKJJGGGGGGGVVUGVK
......KJJGGGGGGGGVVVUGJJK
....KKJJGGGGGGGVVVVUGJJGVK
...KJJGGGGGGGVVVVVUGJGGGVUK
..KJJGGGGGGVVVVVVUGGGGGVVUKK
.KJJGGGGGVVVVVVVUGGGGVVVVUUK
KJJGGGGVVVVVVVVUGGGVVVVUUUUK
JGGGGGVVVVVVVUUGGVVVVVUUUKK
GGGGVVVVVVVUUUGVVVVVUUUKK
GVVVVVVVVUUUUVVVVVUUUKK
VVVVVVVUUUUUVVVVUUUKK
VVVVUUUUUUUUVVUUUKK
VUUUUUUUKKKKUUUKK
UUUUUKKK....KKK
KKKKK
""")
    return a

def stand():
    a=blank();grafts(a);crown(a);right_crown(a);left_arm(a);right_arm(a);shoulders(a);trunk(a);feet(a);heavy_roots(a);return a
if __name__=='__main__':save('idle_a',stand())
