from w6lib import emit
LG = {'O':'straw:1','Q':'straw:0','v':'straw:6','u':'straw:5','t':'straw:4','s':'straw:3','S':'straw:2',
 'L':'linen:6','l':'linen:5','n':'linen:4','m':'linen:3','k':'linen:2',
 'c':'wood:3','d':'wood:5','e':'wood:2','~':'P:~','-':'P:-'}
A = """
................
................
.....LLLLn......
....LLLLLLnn....
....LlLLLlnnm...
....OknnnnnkO...
...OecdcdcdceO..
..OvuttttttsSO..
..OutstttttsSO..
..OuttttsttssSO.
..OttsttttstsSO.
..OtttttsttsSSO.
..OSsttttssSSSO.
...OSsssssSSSQ..
....QQQSSSQQQ...
................
""".strip('\n').split('\n')
B = """
................
................
....LLLLLn......
...LLLLLLLnn....
...LLLlLLllnm...
...OknnnnnnkO...
...OecdcdcdceO..
..OvvutttttsSO..
..OvutttttssSO..
..OutttsttssSSO.
..OutttttttsSSO.
..OuttttttssSSO.
..OtsttttsSSSSO.
...OSsssSSSSSQ..
....QQQQQQQQ~~..
.....~~~~~~~~---
""".strip('\n').split('\n')
emit('../w6-A.pxg', LG, A)
emit('../w6-B.pxg', LG, B)
