import type { OntologyCapability } from "./ontologyTypes";

export const ONTOLOGY_CAPABILITIES = [
  {
    id: "MapEditing",
    label: "Map Editing",
    purpose: "Tile placement, layers, map tree operations, start position, and editor canvas behavior.",
    entities: ["GameMap", "MapTreeNode", "TilesetDef", "GameEvent"],
    typeSurfaces: ["src/project/types/project.ts", "src/project/types/base.ts"],
    uiSurfaces: ["src/editor/EditScene.ts", "src/editor/panels/tilePalette.ts", "src/editor/panels/mapList.ts"],
    runtimeSurfaces: ["src/project/collision.ts", "src/player/playSceneMapRuntime.ts", "src/player/playSceneMovement.ts"],
    storageSurfaces: ["src/project/io/guards.ts", "src/project/io/shape.ts", "src/project/io/references.ts"],
    testSurfaces: ["test/mapEditCommands.test.ts", "test/e2e/oprn-map-editor.spec.ts", "test/e2e/oprn-map-runtime.spec.ts"],
    docsSurfaces: ["docs/specs/2026-06-18-oprn-overhaul-design.md"],
    commonTasks: [
      {
        id: "map-editing-add-tool",
        label: "Add or change a map editing tool",
        taskAliases: ["add map tool", "change map editing", "edit canvas behavior"],
        checkSurfaces: ["type", "ui", "runtime", "tests"],
        implementationOrder: ["types", "editor state", "canvas interaction", "runtime semantics", "tests"],
        requiredTests: ["test/mapEditCommands.test.ts", "test/e2e/oprn-map-editor.spec.ts"],
      },
    ],
    contracts: ["map-uses-existing-tileset", "map-tile-array-size", "supabase-project-root"],
  },
  {
    id: "EventAuthoring",
    label: "Event Authoring",
    purpose: "Event pages, conditions, graphics, command editing, and command picker workflows.",
    entities: ["GameEvent", "EventPage", "Command", "CommonEvent", "SwitchDef", "VariableDef"],
    typeSurfaces: ["src/project/types/events.ts", "src/project/types/project.ts"],
    uiSurfaces: [
      "src/editor/panels/eventEditor/commandPicker.ts",
      "src/editor/panels/eventEditor/commandBody.ts",
      "src/editor/panels/eventEditor/commandSummary.ts",
      "src/editor/panels/eventEditor/pageProps.ts",
    ],
    runtimeSurfaces: ["src/player/interpreter.ts", "src/player/interpreter/commandCatalog.ts", "src/player/playSceneInterpreter.ts"],
    storageSurfaces: ["src/project/io/shapeCommandFields.ts", "src/project/io/commandReferenceValidation.ts"],
    testSurfaces: ["test/interpreter.test.ts", "test/eventPages.test.ts", "test/e2e/oprn-event-commands.spec.ts"],
    docsSurfaces: ["docs/specs/oprn-event-command-buttons.md"],
    commonTasks: [
      {
        id: "event-authoring-add-command",
        label: "Add an event command",
        taskAliases: ["add event command", "new event command", "change command picker"],
        checkSurfaces: ["type", "ui", "runtime", "storage", "tests"],
        implementationOrder: ["command type", "command factory", "editor body", "interpreter handler", "shape guards", "tests"],
        requiredTests: ["test/interpreter.test.ts", "test/e2e/oprn-event-commands.spec.ts"],
      },
    ],
    contracts: ["command-references-existing-map", "command-references-existing-record"],
  },
  {
    id: "TilesetSemantics",
    label: "Tileset Semantics",
    purpose: "Tile metadata, tile groups, pattern grammar, terrain tags, passability, and AI tile meaning.",
    entities: ["TilesetDef", "Tile", "TileAiMetadata", "TileGroupMetadata"],
    typeSurfaces: ["src/project/types/base.ts"],
    uiSurfaces: [
      "src/editor/panels/tilesetMetadataEditor.ts",
      "src/editor/panels/tilesetAiQuestionEditor.ts",
    ],
    runtimeSurfaces: ["src/project/tilesetPassage.ts", "src/project/aiPreviewGenerator.ts", "src/project/aiPreviewContracts.ts"],
    storageSurfaces: ["src/project/io/guards.ts", "src/project/io/shapeResourceFields.ts", "src/project/tileMetadataDb.ts"],
    testSurfaces: ["test/tileMetadataDb.test.ts", "test/aiPreviewContracts.test.ts", "test/e2e/oprn-tileset-readability.spec.ts"],
    docsSurfaces: ["docs/specs/2026-06-27-oprn-development-ontology-design.md"],
    commonTasks: [
      {
        id: "tileset-semantics-improve-classification",
        label: "Improve tile meaning classification",
        taskAliases: ["tile meaning", "tileset semantics", "improve tile classification"],
        checkSurfaces: ["type", "ui", "runtime", "storage", "tests"],
        implementationOrder: ["metadata shape", "AI mapping", "editor controls", "runtime consumers", "tests"],
        requiredTests: ["test/aiPreviewContracts.test.ts", "test/tileMetadataDb.test.ts"],
      },
    ],
    contracts: ["tileset-runtime-array-size", "tile-group-ids-in-range"],
  },
  {
    id: "DatabaseRecords",
    label: "Database Records",
    purpose: "Actors, classes, skills, items, equipment, enemies, troops, states, and animation records.",
    entities: ["ActorRecord", "SkillRecord", "ItemRecord", "EquipmentRecord", "EnemyRecord", "TroopRecord", "StateRecord", "BattleAnimationRecord"],
    typeSurfaces: ["src/project/types/database.ts"],
    uiSurfaces: [
      "src/editor/panels/database.ts",
      "src/editor/panels/databaseRecordViews.ts",
      "src/editor/panels/databaseControls.ts",
      "src/editor/panels/databaseStateRecordView.ts",
      "src/editor/panels/databaseTroopRecordView.ts",
      "src/project/ontology/databaseStateOntology.ts",
      "src/styles/database/states.css",
      "src/styles/database/troops.css",
    ],
    runtimeSurfaces: ["src/battle/runtime.ts", "src/player/interpreter.ts", "src/player/playSceneBattle.ts"],
    storageSurfaces: ["src/project/io/shapeDatabaseFields.ts", "src/project/io/references.ts"],
    testSurfaces: ["test/defaultDatabase.test.ts", "test/battleRuntimeDb.test.ts", "test/e2e/oprn-database.spec.ts", "test/e2e/oprn-database-states.spec.ts"],
    docsSurfaces: ["docs/specs/2026-06-18-oprn-overhaul-design.md"],
    commonTasks: [
      {
        id: "database-records-add-field",
        label: "Add or change a database record field",
        taskAliases: ["add database field", "change actor item skill enemy troop", "database records"],
        checkSurfaces: ["type", "ui", "runtime", "storage", "tests"],
        implementationOrder: ["record type", "defaults", "database UI", "runtime readers", "shape guards", "tests"],
        requiredTests: ["test/defaultDatabase.test.ts", "test/e2e/oprn-database.spec.ts"],
      },
    ],
    contracts: ["database-record-references-exist"],
  },
  {
    id: "BattleRuntime",
    label: "Battle Runtime",
    purpose: "Battle turns, battlers, rewards, troop events, animations, and battle UI behavior.",
    entities: ["EnemyRecord", "TroopRecord", "SkillRecord", "ItemRecord", "BattleAnimationRecord"],
    typeSurfaces: ["src/battle/types.ts", "src/project/types/database.ts"],
    uiSurfaces: [
      "src/player/battleDom.ts",
      "src/player/battleFieldDom.ts",
      "src/editor/panels/databaseTroopRecordView.ts",
      "src/editor/panels/databaseTroopBattleEventPanel.ts",
      "src/styles/database/troops.css",
    ],
    runtimeSurfaces: ["src/battle/runtime.ts", "src/battle/battleEvents.ts", "src/battle/battleRewards.ts"],
    storageSurfaces: ["src/project/io/shapeDatabaseFields.ts"],
    testSurfaces: ["test/battleRuntime.test.ts", "test/battleRuntimeDb.test.ts", "test/e2e/oprn-battle.spec.ts"],
    docsSurfaces: ["docs/specs/2026-06-18-oprn-overhaul-design.md"],
    commonTasks: [
      {
        id: "battle-runtime-change-mechanic",
        label: "Change a battle mechanic",
        taskAliases: ["battle runtime", "add battle mechanic", "change troop event"],
        checkSurfaces: ["type", "runtime", "ui", "tests"],
        implementationOrder: ["battle types", "runtime state", "DOM display", "database records", "tests"],
        requiredTests: ["test/battleRuntime.test.ts", "test/e2e/oprn-battle.spec.ts"],
      },
    ],
    contracts: ["database-record-references-exist"],
  },
  {
    id: "ResourcePipeline",
    label: "Resource Pipeline",
    purpose: "Supabase-root resource payloads, local cache/bootstrap files, resource profiles, picker UI, and Phaser loading.",
    entities: ["AssetRef", "UploadedAsset", "ResourceProfile"],
    typeSurfaces: ["src/project/types/base.ts"],
    uiSurfaces: ["src/editor/panels/resourceManager.ts", "src/editor/panels/resourceModal.ts", "src/editor/panels/eventEditor/npcGraphicPicker.ts"],
    runtimeSurfaces: ["src/assets/bundled.ts", "src/assets/generatedAssetResourceResolver.ts", "src/assets/supabaseResourceCache.ts", "src/player/resourceDisplay.ts"],
    storageSurfaces: ["src/project/io/resourceReferenceValidation.ts", "src/project/io/shapeResourceFields.ts"],
    testSurfaces: ["test/generatedAssetResourceResolver.test.ts", "test/supabaseResourceCache.test.ts", "test/e2e/oprn-resource-manager.spec.ts"],
    docsSurfaces: ["public/assets/MANIFEST.md"],
    commonTasks: [
      {
        id: "resource-pipeline-add-kind",
        label: "Add a resource kind",
        taskAliases: ["add resource kind", "new asset type", "resource picker"],
        checkSurfaces: ["type", "ui", "runtime", "storage", "tests"],
        implementationOrder: ["resource type", "manifest/defaults", "picker UI", "runtime resolver", "reference validation", "tests"],
        requiredTests: ["test/generatedAssetResourceResolver.test.ts", "test/e2e/oprn-resource-manager.spec.ts"],
      },
    ],
    contracts: ["resource-reference-exists", "supabase-resource-root", "bundled-resource-not-user-deletable"],
  },
  {
    id: "ProjectPersistence",
    label: "Project Persistence",
    purpose: "Serialization, package export, migration, shape guards, reference validation, and Supabase current_json sync.",
    entities: ["Project", "ProjectSession", "SaveSlot", "GameMap", "Command", "ResourceProfile"],
    typeSurfaces: ["src/project/types/project.ts", "src/project/types/events.ts", "src/project/types/base.ts"],
    uiSurfaces: ["src/editor/saveActions.ts", "src/editor/panels/menu.ts"],
    runtimeSurfaces: ["src/project/session.ts", "src/project/package.ts"],
    storageSurfaces: [
      "src/project/io.ts",
      "src/project/io/guards.ts",
      "src/project/io/references.ts",
      "src/project/io/migration.ts",
      "src/project/supabaseProjectSync.ts",
    ],
    testSurfaces: ["test/io.test.ts", "test/storePersistence.test.ts", "test/supabaseProjectSync.test.ts"],
    docsSurfaces: ["docs/specs/2026-06-18-oprn-overhaul-design.md"],
    commonTasks: [
      {
        id: "project-persistence-change-schema",
        label: "Change project storage shape",
        taskAliases: ["project schema", "save format", "migration", "reference validation"],
        checkSurfaces: ["type", "storage", "runtime", "tests"],
        implementationOrder: ["types", "defaults", "migration", "guards", "reference validation", "tests"],
        requiredTests: ["test/io.test.ts", "test/migrationFixtures.ts"],
      },
    ],
    contracts: ["map-uses-existing-tileset", "command-references-existing-record", "resource-reference-exists", "supabase-project-root", "supabase-resource-root"],
  },
] satisfies readonly OntologyCapability[];
