# 비 내리는 수직 폐허 도시 — 조각 메타(굽는 스크립트가 읽는다). 모든 조각에 ko/desc/rules.
B, O, D, WL, WK, AT, FL = 'building', 'prop', 'decal', 'wall', 'terrain', 'autotile', 'floor'
META = {
 # ---------------- 건물 키트
 'stair_house': dict(kind='object', role=B, brows=2, ko='바깥 계단 3층 집',
   desc='밤비 젖은 3층 돌·반목조 집: 1층 벽을 따라 오르는 돌 바깥 계단(쇠 난간) → 2층 층계참 발코니(빨래·2층 문), 3층 작은 쇠 발코니, 덧문, 창 두 개 불빛, 청회색 슬레이트 지붕.',
   rules='아래 2줄(1층 벽·계단)만 막힘, 위는 지붕·벽(걷기+가림). 옹벽 바로 앞 단 뒤쪽에 등을 대고 놓고 문(1층 왼쪽 둘째 칸) 앞 한 칸은 길. 같은 집을 나란히 셋 이상 두지 말 것.'),
 'gable_tall': dict(kind='object', role=B, brows=2, ko='박공 정면 좁은 집',
   desc='박공이 앞을 향한 좁은 3층 집(4칸 폭): 2층 쇠 난간 발코니에 빨래, 다락 둥근 창에 불빛, 덧문 단 창. 비탈 거리의 키 큰 집.',
   rules='아래 2줄만 막힘. 문은 가운데 칸, 문 앞 한 칸은 길. 위 단 길 바로 앞에는 2층짜리 변형을 쓴다(3층은 위 단 앞줄을 가린다).'),
 'gable_low': dict(kind='object', role=B, brows=2, ko='박공 정면 2층 집',
   desc='박공 정면 좁은 집의 2층 변형(4칸): 2층 발코니·빨래, 창 하나에 불. 위 단 길 앞에 놓아도 위 길을 가리지 않는 높이.',
   rules='아래 2줄만 막힘, 문 앞 한 칸은 길. 키 큰 3층 집 사이에 섞어 지붕선이 들쭉날쭉하게.'),
 'ruin_house': dict(kind='object', role=B, brows=2, ko='지붕 꺼진 폐가',
   desc='비에 꺼진 2층 돌집: 슬레이트 용마루가 내려앉아 앞 경사에 서까래가 드러난 구멍, 판자로 막은 문, 깨진 창, 무너진 굴뚝. 불빛 없음.',
   rules='아래 2줄만 막힘. 멀쩡한 집 사이에 하나씩 끼워 폐허 도시로 읽히게(몰아 두지 말 것). 앞에 슬레이트 조각·잔해를 흩는다.'),
 'shop_house': dict(kind='object', role=B, brows=2, ko='셔터 내린 가게 집',
   desc='2층 가게 집: 1층 가게 창은 나무 셔터로 닫혔고 찢긴 줄무늬 차양, 문 옆 쇠 간판 걸이(빈 판), 2층 덧문 창(하나에 불).',
   rules='아래 2줄만 막힘. 문은 왼쪽 둘째 칸, 가게 창 앞(차양 밑)은 길. 광장·큰길 둘레에.'),
 'clock_tower': dict(kind='object', role=B, brows=2, ko='언덕 위 시계탑',
   desc='회색 마름돌 네모 탑(모서리 큰 돌·층 띠돌): 아래 아치 문, 가는 아치 창, 숫자 없는 시계판(눈금 점·멈춘 바늘), 쌍 아치 종실(희미한 등), 청회색 네모뿔 첨탑과 쇠 꼭지.',
   rules='3칸 폭, 아래 2줄만 막힘. 언덕 꼭대기 광장 뒤쪽에 하나만. 문 앞 한 칸은 광장 판석.'),
 'theatre_ruin': dict(kind='object', role=B, brows=2, ko='무너진 옛 극장',
   desc='9칸 넓은 마름돌 정면 2층(높은 아치 창 줄), 가운데 기둥 현관(박공·기둥 넷·어두운 큰 문, 한 짝 기움), 지붕 가운데가 크게 꺼졌고 오른쪽 모서리가 계단꼴로 무너져 돌무더기, 담쟁이.',
   rules='아래 2줄만 막힘, 현관 문(가운데) 앞은 광장. 언덕 위 시계탑 옆 같은 높이에. 앞에 넘어진 기둥·잔해를 둔다.'),
 # ---------------- 불빛
 'lamppost_lit': dict(kind='object', role=O, brows=1, ko='켜진 가로등',
   desc='젖은 쇠 기둥 꼭대기 사각 등에 노란 불, 등 둘레 희미한 빛 번짐. 밤 거리의 기준 빛.', rules='밑 1칸만 막힘, 위 2칸은 걷기+가림. 길 가장자리·계단 머리·다리 끝에 6~10칸 간격으로, 일렬로 촘촘히 세우지 말 것. 밑에 등불 웅덩이를 두면 좋다.'),
 'lamp_double_lit': dict(kind='object', role=O, brows=1, ko='두 갈래 가로등',
   desc='가운데 쇠 기둥에서 양쪽 팔로 매단 등 둘(켜짐). 광장 양쪽·분수 둘레의 큰 등.', rules='밑 1줄(2칸) 막힘. 광장에 둘(대칭이 아니어도 된다), 길에는 한 갈래 등을 쓴다.'),
 'lamp_wall': dict(kind='decal', role=D, brows=0, ko='벽 등',
   desc='벽에서 나온 쇠 까치발에 매단 켜진 등. 집 벽·옹벽 앞면에 붙이는 위층 덧그림.', rules='막힘 없음(붙은 벽이 이미 막힘). 1층 문 위나 2층 높이 벽에, 집마다 하나를 넘지 않게.'),
 # ---------------- 물·배수
 'drain_grate': dict(kind='decal', role=D, brows=0, ko='길 배수구',
   desc='쇠 살 다섯 줄 사이 검은 물, 테 윗모 빗물 맺힘. 배수로 끝·광장 낮은 곳.', rules='걷기, 사람 아래. 배수로(autotile-gutter) 끝 칸이나 웅덩이 옆에.'),
 'puddle_small': dict(kind='decal', role=D, brows=0, ko='작은 웅덩이',
   desc='젖은 돌 테 + 하늘 비친 매끈한 물(위쪽 밝은 줄, 가로 반사 줄).', rules='걷기. 판석·자갈 위 아무 데나 덩이로 2~3개, 큰 웅덩이는 autotile-puddle.'),
 'puddle_lamp': dict(kind='decal', role=D, brows=0, ko='등불 비친 웅덩이',
   desc='물 위에 노란 등불이 세로로 일렁이는 짧은 줄 몇 토막(2칸).', rules='걷기. 켜진 가로등 바로 아래(한 칸 남쪽)에만 — 등 없는 곳에 두면 빛이 어디서 왔는지 모른다.'),
 'sewer_outlet': dict(kind='wall', role=WL, brows=0, ko='하수구 물줄기',
   desc='옹벽 앞면에 박힌 돌 아치 배수구: 쐐기돌 테, 검은 굴, 녹슨 쇠 창살(하나 부러짐), 쏟아지는 물줄기가 벽을 타고 떨어져 거품.', rules='옹벽 앞면 3줄에 겹쳐 찍고, 바로 아래 칸은 물(항구·수로)이어야 한다. 길 위로 떨어지게 두지 말 것.'),
 'downpipe': dict(kind='decal', role=D, brows=0, ko='홈통',
   desc='처마에서 벽을 타고 내려온 쇠 홈통, 꺾인 주둥이에서 물이 흘러 작은 웅덩이.', rules='집 벽 모서리(오른쪽 끝 칸)에 붙여 찍는다. 막힘 없음.'),
 'rain_barrel': dict(kind='object', role=O, brows=1, ko='빗물 받는 통',
   desc='넘칠 듯 찬 나무 통(쇠 테), 물낯 고리, 옆으로 흘러내린 물.', rules='밑 1칸 막힘. 홈통 밑·집 모서리·계단 옆.'),
 # ---------------- 거리 소품
 'bench_wet': dict(kind='object', role=O, brows=1, ko='젖은 거리 의자', desc='쇠 다리 + 나무 등받이·앉음판, 윗모에 빗물.', rules='밑 1줄(2칸) 막힘. 광장 가장자리·난간 앞, 좌우 뒤집어 섞어 쓴다.'),
 'crates_tarp': dict(kind='object', role=O, brows=1, ko='방수포 덮은 상자 더미', desc='나무 상자 셋을 쌓고 젖은 방수포를 밧줄로 묶었다.', rules='밑 1줄 막힘. 부두·가게 옆에 통과 함께 덩이로.'),
 'barrels_wet': dict(kind='object', role=O, brows=1, ko='젖은 나무통 둘', desc='하나는 서 있고 하나는 넘어져 누웠다(쇠 테, 뚜껑 물 고임).', rules='밑 1줄 막힘. 상자 더미 옆·골목 끝.'),
 'cart_tarp': dict(kind='object', role=O, brows=1, ko='버려진 손수레', desc='바퀴 하나 빠져 기운 손수레, 짐칸에 젖은 방수포.', rules='밑 1줄 막힘. 광장 구석·부두. 길 한가운데 막지 말 것.'),
 'bollard_stone': dict(kind='object', role=O, brows=1, ko='돌 계선주', desc='부두·다리 끝 짧은 돌기둥, 둥근 머리가 젖어 빛남, 밑동 이끼.', rules='막힘 1칸. 부두 물가 줄에 5~8칸 간격(일정하지 않게).'),
 'notice_column': dict(kind='object', role=O, brows=1, ko='광고 기둥', desc='둥근 돌 기둥에 찢어지고 젖은 빈 종이(글자 없음)가 겹겹이, 둥근 쇠 갓.', rules='밑 1칸 막힘, 위 2칸 걷기+가림. 광장·큰길 모퉁이에 하나.'),
 'fountain_rain': dict(kind='object', role=O, brows=2, ko='빗물 찬 광장 분수', desc='둥근 돌 수반(두꺼운 테 윗면이 젖어 빛남), 가운데 부러진 기둥, 넘친 물 자국. 물은 멈췄고 빗물만 고였다.', rules='3x3칸, 아래 2줄 막힘. 광장 가운데에 하나, 둘레 2칸은 비워 돌아갈 수 있게.'),
 'statue_weathered': dict(kind='object', role=O, brows=1, ko='닳은 석상', desc='두 단 받침 위 두건 쓴 망토 형상(얼굴 없음), 긴 지팡이, 부러진 왼팔, 이끼·빗물 얼룩.', rules='밑 1줄(2칸) 막힘. 언덕 광장·극장 앞에 하나.'),
 'iron_gate': dict(kind='object', role=O, brows=1, ko='녹슨 쇠 대문', desc='돌 기둥 둘 사이 반쯤 열린 쇠살문, 한 짝은 경첩이 빠져 기울었다.', rules='3칸 폭, 밑 1줄 막힘(가운데 칸은 문 이벤트로 열 수 있게). 담·옹벽 틈, 묘지·저택 앞.'),
 'flowerbox_wilted': dict(kind='decal', role=D, brows=0, ko='시든 창가 꽃상자', desc='처진 시든 꽃·젖은 흙의 나무 상자.', rules='집 창 아래 벽에 붙이는 덧그림. 막힘 없음.'),
 'planter_cypress': dict(kind='object', role=O, brows=1, ko='돌 화분 측백', desc='네모 돌 화분에 심은 젖은 측백(버들항 측백 형태).', rules='밑 1칸만 막힘, 위 걷기+가림. 광장 모서리·계단 옆에 하나씩.'),
 'sign_bracket': dict(kind='decal', role=D, brows=0, ko='가게 걸이 간판', desc='벽에서 나온 쇠 팔에 매단 나무 판, 글자 대신 열쇠 그림.', rules='가게 집 문 옆 벽에 붙이는 위층 덧그림. 막힘 없음.'),
 'umbrella_dropped': dict(kind='decal', role=D, brows=0, ko='떨어진 우산', desc='뒤집혀 나뒹구는 검은 우산, 꺾인 살, 안에 고인 빗물.', rules='걷기. 광장·골목에 하나만(이야기 소품).'),
 'leaves_wet': dict(kind='decal', role=D, brows=0, ko='젖은 낙엽', desc='길 가장자리·배수구 둘레에 몰린 짙은 갈색·누런 잎.', rules='걷기. 벽 밑·배수구 옆에 덩이로.'),
 'slates_fallen': dict(kind='decal', role=D, brows=0, ko='떨어진 슬레이트 조각', desc='깨진 청회색 지붕판 몇 장.', rules='걷기. 폐가 처마 밑 한두 칸.'),
 'rubble_masonry': dict(kind='object', role=O, brows=1, ko='무너진 마름돌 무더기', desc='깨진 큰 돌·작은 돌이 쌓였고 윗돌이 젖어 빛남, 틈에 잡풀.', rules='밑 1줄(2칸) 막힘. 무너진 건물·옹벽 밑. 일렬로 늘어놓지 말 것.'),
 'column_fallen': dict(kind='object', role=O, brows=1, ko='넘어진 기둥 토막', desc='홈 판 기둥이 세 토막으로 부러져 누웠다, 이끼.', rules='밑 1줄 막힘. 극장·신전 앞에만.'),
 'ivy_wall': dict(kind='decal', role=D, brows=0, ko='벽 담쟁이', desc='벽·옹벽 앞면을 덮어 내려온 젖은 담쟁이 커튼.', rules='옹벽 앞면 윗줄이나 집 벽에 붙이는 덧그림. 계단·폭포 칸은 피한다.'),
 'moss_stones': dict(kind='decal', role=D, brows=0, ko='이끼 낀 돌 틈', desc='판석 가장자리·계단 옆 이끼 덩이와 잔풀, 물방울 빛.', rules='걷기. 벽 밑·그늘진 구석.'),
 'laundry_line': dict(kind='decal', role=D, brows=0, ko='골목 빨랫줄', desc='두 집 벽 사이에 처진 줄, 젖은 셔츠·홑청·수건(4칸).', rules='위층 덧그림(걷기+가림). 이웃한 두 집 사이 골목(틈 1~3칸) 위층 높이에 줄 양끝이 벽에 닿게.'),
 'rowboat': dict(kind='object', role=O, brows=0, ko='매어 둔 작은 배', desc='비에 바닥까지 물이 찬 나무 배, 걸쳐 둔 노.', rules='물 칸 위에만(이미 막힘). 선착장·부두 물가에.'),
 'dock_planks': dict(kind='walk', role=WK, brows=0, ko='나무 선착장', desc='물 위로 나간 판자 바닥, 앞 끝 굵은 말뚝 둘, 젖어 빛나는 판(3x3칸).', rules='물 칸 위에 깔고 판 칸(위 3줄)을 걷기로 바꾼다. 부두 끝에 붙여 이어지게.'),
 'arch_footbridge': dict(kind='walk', role=WK, brows=0, ko='돌 아치 인도교',
   desc='동서로 놓인 젖은 판석 바닥(걷기), 앞뒤 쇠 난간, 앞면 마름돌 아치(밑은 비어 물이 비친다), 양 끝 기둥 위 켜진 등(4칸 폭).',
   rules='남북으로 흐르는 2칸 물길 위: 그림을 물길 왼쪽 한 칸부터 찍고, 바닥 줄(그림 위에서 10~26px)을 걷기로 바꾼다. 아치는 다리 아래 물 칸에 걸친다. 폭포 바로 위에 놓을 수 있다.'),
 # ---------------- 바닥·벽 표본
 'ground-wetflag': dict(kind='floor', role=FL, ko='젖은 판석길', desc='버들항 회색 판석(두 줄/칸, 엇갈림)을 밤비 톤으로 — 판석마다 젖은 정도, 윗모 하늘빛 맺힘, 줄눈 고인 물.', rules='골목·계단참 바닥. 이어 붙여도 이음새 없음(48x48).'),
 'ground-bigflag': dict(kind='floor', role=FL, ko='광장 큰 판석', desc='24x24 큰 판석 엇갈려 깔기, 판석마다 톤·젖음·윗모 빛 맺힘. 옹벽 마름돌과 크기가 달라 벽과 섞이지 않는다.', rules='광장·언덕 위 바닥. 둘레에 자갈 연석.'),
 'ground-mossflag': dict(kind='floor', role=FL, ko='이끼 낀 젖은 판석', desc='줄눈에 이끼가 끼고 아랫단 판석 끝이 푸르게 물든 젖은 판석.', rules='그늘진 골목·옹벽 밑·폐허 둘레.'),
 'ground-wetcobble': dict(kind='floor', role=FL, ko='젖은 자갈길', desc='버들항 회색 자갈 칸을 밤비 톤으로, 돌마다 밝은 윗모가 하늘빛, 틈엔 고인 물 빛.', rules='큰길·부두 바닥. 풀과 만나는 쪽은 연석.'),
 'face_mossy_retaining': dict(kind='wall', role=WL, ko='이끼 낀 젖은 옹벽', desc='옹벽 앞면 표본(3줄 높이 규칙): 갓돌, 큰 마름돌(돌마다 오래된 정도), 갓돌 밑으로 흘러내린 빗물 얼룩, 아랫단 이끼.', rules='단과 단 사이 남향 옹벽 앞면(terrain.MASONRY_FN = 이 재료). 계단·폭포 칸은 다른 그림.'),
 # ---------------- 오토타일
 'autotile-puddle': dict(kind='autotile', role='terrain', layer='lower', ko='빗물 웅덩이 오토타일', desc='포장 위 투명 가장자리 웅덩이 16변형: 젖은 돌 테, 하늘 비친 물, 북쪽 안 테 빛 한 줄, 가로 반사 줄.', rules='아래층, 걷기. 판석·자갈 위 2~6칸 덩이. 계단·물가·난간 칸은 피한다.'),
 'autotile-gutter': dict(kind='autotile', role='terrain', layer='lower', ko='돌 배수로 오토타일', desc='칸 가운데 폭 6px 돌 홈(턱 위·왼 밝음)에 흐르는 빗물 16변형, 외톨이는 쇠 배수구 뚜껑.', rules='아래층, 걷기. 집 앞 처마 낙수 줄을 따라 한 줄로, 끝 칸에 배수구.'),
 'autotile-ironrail': dict(kind='autotile', role='fence', layer='upper', ko='젖은 쇠 난간 오토타일', desc='손잡이·살·돌 받침 턱의 쇠 난간 16변형(동서는 앞모습, 남북은 3/4 세로 줄), 손잡이 빗물 맺힘.', rules='위층, 모든 칸 막힘. 단 끝줄(옹벽 위)·다리·광장 가장자리를 따라. 계단 머리 칸은 비운다.'),
}
