"""Literal authored native clusters only. No geometric masks or pose transforms.
Coordinates are zero based. Blocks contain manually chosen row segments;
serialization pads transparent space and writes complete 64 by 64 rows.
"""
from pathlib import Path
import json
ROOT = Path(__file__).resolve().parent
PALETTE = {'O':'#201D19','D':'#382B24','S':'#554031','B':'#795539','L':'#A77C4B','H':'#C79C64','c':'#938C73','C':'#CEC5A3','W':'#F1E7C9','K':'#10151A','g':'#283B28','m':'#42603B','n':'#698344','h':'#A0A45A','t':'#755238','T':'#B78748','e':'#EBC37C','v':'#AC77B7'}
FRAMES={}
def block(name,x,y,rows):
    canvas=[list('.'*64) for _ in range(64)]
    for dy,row in enumerate(rows.strip('\n').splitlines()):
        for dx,p in enumerate(row):
            assert 0<=x+dx<64 and 0<=y+dy<64
            assert p=='.' or p in PALETTE, (name,p)
            canvas[y+dy][x+dx]=p
    FRAMES[name]=canvas

def patch(name,edits):
    for x,y,s in edits:
        for dx,p in enumerate(s):
            assert p=='.' or p in PALETTE
            FRAMES[name][y][x+dx]=p

def write():
    (ROOT/'palette.json').write_text(json.dumps(PALETTE,indent=2)+'\n')
    for name,grid in FRAMES.items():
        folder='poses' if name in ['idle_a','idle_b','idle_c','windup','move','attack','recover','hit','dead'] else 'actions'
        (ROOT/folder/(name+'.pxgrid')).write_text('\n'.join(''.join(r) for r in grid)+'\n')

# Broad warm flank; three lumpy moss lobes; cream forehead stripe and
# dark eye band. Hindquarter on the left, near shoulder and forepaw right.
block('idle_a',5,25,'''
...............ggggg..............................
............gggmnnnmg..gggg.......................
..........ggmnnhhhnnmggmnngg......................
.........gmnnhhhhhnnnmnnnhnmg.....................
........gmnnhhnnnnmmmnnnhhnnmg....................
.......gmnnnnmmmmnngmnnnnnnnmg........OOO.........
.......gmmmmggmmmngggmmmmnnmmg.......OCCcO........
......OgggggmmnmmggggmmmmmgggOO....OCWWCcO.......
.....OLLLHHHgggggLLLggggggBLLLLOOOOCCWWCcDO......
....OLHHHHHLLLLLLLLLLLLLLLBLLLLLSSCCWWWCCSDOO.....
...OLHHHHLLLLLLLLLLLLLLLLLBBBBLSSCCWWWCDSSSSO....
..OLHHHLLLLLLLLLLLLLLBBBBBBBBBBSSCCWWWCDDKKSSO...
..OLLLLLLLLLLLLLLLBBBBBBBBBBBBBSSCCWWCDDWWKSSO...
..OLLLLLLLLLLBBBBBBBBBBBBBBBBBBSSCCWCCDSSSSSSSO..
..OLLLLLLLLBBBBBBBBBBBBBBBBBBBSSCCWCCSSSCCCCCOKO.
..OBLLLLLBBBBBBBBBBBBBBBBBBBBSSCCCWCCSCCCCCCCKKO.
OOOBBBBBBBBBBBBBBBBBBBBBBBBBBSSCCCCCcCCCCCCcKKO..
OLBBBBBBBBBBBBBBBBBBBBBBBBBBBSSSCCCcCCCCCccOO....
OSBBBBBBBBBBBBBBBBBBBBBBLLBBBBSSDDccccccDDOO......
.OSSSBBBBBBBBBBBBBBBBBLLLLBBBBSSDDDDDDDO.........
..OOSSSBBBBBBBBBBBBBBBLLLLBBBBSSSDDDDDO..........
....OSSSBBBBBBBBBBSSBBLLLBBBBSSSSDDDDO...........
.....OSSSBBBBBBBSSSSSBLLBBBBSSSSSDDDDO...........
......OSSSBBBBSSSSSSSBBBSSSSSSSSDDDDDO...........
.......OSSBBBSSSSSSSSBSSSSSSSSDDDDDSSO...........
.......OSBBBSSSSSSSDDDDSSSSSSDDDDDSSSO...........
.......OSBBSSSSDDDOOOODDDDDDDDDDDSSSO...........
.......OSBBSSSDDOO....OOOOOOOOODDDSSSO...........
......OSBBBSSSDO.........ODSSSSDDDSSSO...........
......OSBBSSSSDO.........ODSSSSSSSSSSO...........
.....OSBBBSSSSDO.........ODSSSBBSSSSSO...........
.....OSBBBBSSSSO.........OSSSBBBBSSSSSO..........
....OSBBBBBSSSSO.........OSBBBBBBBBSSSSO.........
....OCcCcCcSSSSO.........OCcCcCcCcSSSSSO.........
.....OOOOOOOOOO...........OOOOOOOOOOOO..........
''')
# Explicit sole and far-limb clusters after first visual inspection.
patch('idle_a',[(11,60,'OOOOOOOOOO'),(32,60,'OOOOOOOOOOOOO'),(28,52,'DDDO'),(28,53,'DSSO'),(28,54,'DSSSO'),(28,55,'DcCcO'),(28,56,'OOOOO'),(51,48,'DSO'),(51,49,'DSSO'),(51,50,'DSSO'),(51,51,'DSSO'),(51,52,'DcCcO'),(51,53,'OOOOO')])
# Idles keep the planted soles. Only chosen breath, ear, moss and cheek
# clusters change; no shifts or transformed frame are used.
FRAMES['idle_b']=[r[:] for r in FRAMES['idle_a']]
patch('idle_b',[(18,25,'ggggggg'),(17,26,'gmnnhnmg'),(19,28,'nhhhhhnn'),(12,35,'HHHHHLLLLLL'),(13,37,'LLLLLLLLLLBBB'),(41,34,'SCCWWWC'),(43,43,'CCCWCCS'),(43,44,'CCCCcCC'),(17,48,'BBBBBSSS'),(41,54,'SSBBSSS')])
FRAMES['idle_c']=[r[:] for r in FRAMES['idle_a']]
patch('idle_c',[(20,25,'ggggg'),(19,26,'gmnnhmg'),(19,28,'nnhhhhnm'),(12,35,'HHHLLLLLLLL'),(13,37,'LLLLLLBBBBBBB'),(44,37,'WWCDDSSS'),(48,38,'DDKKKSS'),(48,39,'DDDDSSS'),(41,44,'CCCccCC'),(17,48,'BBBBSSSS'),(41,54,'SBBBSSS')])

# Hunched haunches, compressed neck, shoulder pulled back and forepaw
# folded under chest. The rear toe presses the floor in preparation.
block('windup',4,29,'''
................ggggg............................
............ggggmnnhmggggg.......................
..........ggmnnhhhhnnnmnnnmg......................
.........gmnhhhhnnnnnnnhnnnmg.....................
........gmnnnnnnmmmnnnnhnnnmg....................
.......gmmnmmmmgggmmnnnnnmmmg......OOO...........
......OgggggmmmmmggggmmmmgggOO....OCCcO..........
.....OLHHHHHgggggLLLLgggggLLLLLOOOCWWCcO.........
....OLHHHHLLLLLLLLLLLLLLLBBLLLSSCCWWWCCDO........
...OLHHHLLLLLLLLLLLLLLBBBBBBBLSSCCWWWCDSSOO......
...OLLLLLLLLLLLLLLLBBBBBBBBBBSSCCWWWCDDKKSSO.....
...OLLLLLLLLLLLBBBBBBBBBBBBBSSCCWWCCDDWKSSSO.....
..OLLLLLLLLLBBBBBBBBBBBBBBBBSSCCWCCSSSSSSSSO....
..OLLLLLLLBBBBBBBBBBBBBBBBBSSCCCWCCSCCCCCCOKO....
OOOBLLLLBBBBBBBBBBBBBBBBBBSSCCCCCCSCCCCCCKKO.....
OLBBBBBBBBBBBBBBBBBBBBBBBBSSSCCCCcCCCCCcOO.......
OSBBBBBBBBBBBBBBBBBBBBBBBBSSSScccccccDDO.........
.OSSSBBBBBBBBBBBBBBBBBBBBBBSSSDDDDDDDO...........
..OSSSBBBBBBBBBBBBBBBBBBBBBBSSDDDDDDO............
...OSSSBBBBBBBBBBBBBBBBBBBBBBSSDDDDDO............
....OSSSBBBBBBBBBBBBBBBBBLLBBSSDDDDDO............
.....OSSSBBBBBBBBBBBBBBLLLLBBSSDDDDDO............
......OSSSBBBBBBBBBSSBLLLBBBSSDDDDDO.............
......OSSSBBBBBBBSSSSBBBBBSSSDDDDDO..............
.....OSSSBBBBBSSSSSSDDDDDDDDDDDSSO..............
.....OSSBBBBBSSSSDDDOOOOOODDDDDDSSO.............
....OSSBBBBBSSSSDDOO.....ODDDDDDSSSO............
...OSSBBBBBSSSSDOO.......ODDSSSSBSSSO...........
..OSBBBBBBSSSSDO.........ODSBBBBBBSSSO..........
..OCcCcCcSSSSSO..........OCcCcCcCcSSSO..........
...OOOOOOOOOOO............OOOOOOOOOOO...........
...OOOOOOOOOOO............OOOOOOOOOOO...........
''')
# Low lunge: rear leg extended back, tucked far foreleg, near shoulder
# advancing and front wrist reaches forward. Different belly contour.
block('move',2,28,'''
...................ggggg..........................
................gggmnnnmg..gggg...................
..............ggmnhhhhhnmggmnng...................
............ggmnnhhhnnnnmmnnnnmg..................
...........gmnnhnnnnmmmnnnnhhnnmg......OOO........
..........gmnnnnmmggggmnnnnhnnnmg.....OCCcO.......
.........Oggggggmmmngggmmnnnnmmmg....OCWWCcO......
........OLHHHHHHggggLLLgggggggggLOOOCWWWCcDO.....
.......OLHHHHHLLLLLLLLLLLLLLLLBLSSCCWWWCCSSDO.....
......OLHHHLLLLLLLLLLLLLLBBBBBBLSSCCWWWCDSSSSO....
.....OLLLLLLLLLLLLLLBBBBBBBBBBBSSCCWWWCDDKKSSO...
.....OLLLLLLLLLLBBBBBBBBBBBBBBBSSCCWWCDDWWKSSSO..
....OLLLLLLLLBBBBBBBBBBBBBBBBBSSCCWCCSSSSSSSSSO.
....OLLLLLBBBBBBBBBBBBBBBBBBBSSCCWCCSCCCCCCCOKO.
...OOBBBBBBBBBBBBBBBBBBBBBBBBSSCCCCCCSCCCCCCKKO.
..OLBBBBBBBBBBBBBBBBBBBBBBBBBSSCCCCcCCCCCCcOO...
.OOBBBBBBBBBBBBBBBBBBBBBBBBBBSSSCCcCCCCCccOO....
OSSSBBBBBBBBBBBBBBBBBBBBBBBBBBSSDDccccccDO......
OSSSSSBBBBBBBBBBBBBBBBBBBBLLBBSSDDDDDDDO........
.OOSSSSSBBBBBBBBBBBBBBBLLLLLBBSSDDDDDDO.........
...OSSSSSBBBBBBBBBBBBBBLLLLBBSSSDDDDDDO.........
...OSSSSBBBBBBBBBBSSSSBBBLLBBSSDDDDDDDO.........
..OSSSBBBBBBBBSSSSSDDDDSSBBBSSDDDDDSSSO.........
..OSSBBBBBBBSSSSDDDOOOODDDDDDDDDDDSSSSO.........
.OSSBBBBBBSSSDDOOO....OOOODDDDDDDSSSSSO.........
.OSBBBBBSSSSDOO.........ODDDDDSSSSSSSO.........
.OSBBBSSSSDOO............ODDDSSSSBBBSSO........
.OSBBSSSDOO..............ODDSSSBBBBBBSSO.......
OSBBBSSDO................ODSSBBBBBBBBSSSO......
OCcCcSSO.................OCcCcCcCcSSSSSSO......
.OOOOOO...................OOOOOOOOOOOOOO.......
...........................OOOOOOOOOOOOO.......
...........................OOOOOOOOOOOOO.......
''')
# Contact: planted rear paw, diagonal upper foreleg continuously joins
# shoulder, large palm laid flat on ground on the right.
block('attack',3,28,'''
..................ggggg...........................
...............gggmnhnmgggg........................
.............ggmnhhhhhnmnnng.......................
...........ggmnhhhhnnnnnnhnmg......................
..........gmnnnnnnmmnnnnhhnnmg....................
.........gmnnnmmgggmmnnnnnnnmg.....OOO............
........Ogggggmmmngggmmmnnnmmg....OCCcO...........
.......OLHHHHHggggLLLgggggggggLOOOCWWCcO..........
......OLHHHHLLLLLLLLLLLLLLLLBLSSCCWWWCCDO.........
.....OLHHHLLLLLLLLLLLLBBBBBBBLSSCCWWWCDSSOO.......
....OLLLLLLLLLLLLLLBBBBBBBBBBSSCCWWWCDDKKSSO......
....OLLLLLLLLLBBBBBBBBBBBBBBBSSCCWWCDDWWKSSO......
....OLLLLLLBBBBBBBBBBBBBBBBBBSSCCWCCDSSSSSSSO.....
....OLLLLBBBBBBBBBBBBBBBBBBBSSCCWCCSSSCCCCCOKO....
...OOBBBBBBBBBBBBBBBBBBBBBBBSSCCCCCSCCCCCCCKKO....
..OLBBBBBBBBBBBBBBBBBBBBBBBBSSCCCCcCCCCCCCcOO.....
.OOBBBBBBBBBBBBBBBBBBBBBBBBBSSCCCcCCCCCccOO.......
OSSSBBBBBBBBBBBBBBBBBBBBBBBBBSSDDccccccDO.........
OSSSSBBBBBBBBBBBBBBBBBBBBBBBBSSDDDDDDDO...........
.OOSSSBBBBBBBBBBBBBBBBBLLBBBBSSDDDDDDO............
...OSSSBBBBBBBBBBBBBLLLLLBBBBSSSDDDDDO............
....OSSSBBBBBBBBSSSBLLLLLBBBSSSSDDDDDO............
.....OSSSBBBBBSSSSSBBLLLBBBSSSSSDDDDDO............
.....OSSSBBBSSSSDDDDDDBBBBSSSSSSDDDDSSO...........
.....OSSBBBSSSDDOOOOODBBBSSSSSSDDDDSSSSO..........
.....OSBBBSSSDOO.....ODBBBSSSSSDDDDSSSSSO.........
....OSBBBSSSDO.......ODBBBBBSSSSDDDDSSSSSO........
....OSBBSSSSDO.......ODBBBBBBBSSSSDDSSSSSSO.......
...OSBBBSSSSDO.......ODBBBBBBBBBBSSSSSBBBSSOO.....
...OSBBBBSSSSO.......ODSSBBBBBBBBBBBBBBBBBSSSO....
...OCcCcCcSSSO........OOSSSBBBBBBBBBBBBBBSSSSSO...
....OOOOOOOOO...........OCcCcCcCcCcCcCcCcSSSSSO...
....OOOOOOOOO............OOOOOOOOOOOOOOOOOOOOO...
''')
# Recovery lifts the striking wrist and restores the rear leg's support.
block('recover',5,26,'''
...............ggggg..............................
............gggmnnnmg..gggg.......................
..........ggmnnhhhnnmggmnngg......................
.........gmnnhhhhhnnnmnnnhnmg.....................
........gmnnhhnnnnmmmnnnhhnnmg....................
.......gmnnnnmmmmnngmnnnnnnnmg....................
.......gmmmmggmmmngggmmmmnnmmg.......OOO..........
......OgggggmmnmmggggmmmmmgggOO....OCCcO.........
.....OLLLHHHgggggLLLggggggBLLLLOOOCWWCcO.........
....OLHHHHHLLLLLLLLLLLLLLLBLLLLSSCCWWWCCDO........
...OLHHHHLLLLLLLLLLLLLLLLLBBBBLSSCCWWWCDSSOO......
..OLHHHLLLLLLLLLLLLLLBBBBBBBBBBSSCCWWWCDDKKSSO....
..OLLLLLLLLLLLLLLLBBBBBBBBBBBBBSSCCWWCDDWWKSSO....
..OLLLLLLLLLLBBBBBBBBBBBBBBBBBBSSCCWCCDSSSSSSSO...
..OLLLLLLLLBBBBBBBBBBBBBBBBBBBSSCCWCCSSSCCCCCOKO..
..OBLLLLLBBBBBBBBBBBBBBBBBBBBSSCCCWCCSCCCCCCCKKO..
OOOBBBBBBBBBBBBBBBBBBBBBBBBBBSSCCCCCcCCCCCCcKKO...
OLBBBBBBBBBBBBBBBBBBBBBBBBBBBSSSCCCcCCCCCccOO.....
OSBBBBBBBBBBBBBBBBBBBBBBLLBBBBSSDDccccccDDO.......
.OSSSBBBBBBBBBBBBBBBBBLLLLBBBBSSDDDDDDDO..........
..OOSSSBBBBBBBBBBBBBBBLLLLBBBBSSSDDDDDO...........
....OSSSBBBBBBBBBBSSBBLLLBBBBSSSSDDDDO............
.....OSSSBBBBBBBSSSSSBLLBBBBSSSSSDDDDO............
......OSSSBBBBSSSSSSSBBBSSSSSSSSDDDDSSO...........
.......OSSBBBSSSSSSSSBSSSSSSSSDDDDDSSSO..........
.......OSBBBSSSSSSSDDDDSSSSSSDDDDDSSBBSSO........
.......OSBBSSSSDDDOOOODDDDDDDDDSSBBBBBSSO.......
.......OSBBSSSDDOO....OOOOOOODDSSBBBBBBSSO.......
......OSBBBSSSDO............ODDSSBBBBBSSSO.......
......OSBBSSSSDO............ODSSBBBBSSSSO........
.....OSBBBSSSSDO............OCcCcCcSSSSO.........
.....OSBBBBSSSSO.............OOOOOOOOOO..........
....OSBBBBBSSSSO.................................
....OCcCcCcSSSSO.................................
.....OOOOOOOOOO..................................
''')
# Hit: shoulder buckles, face recoils left and up; clenched eye, open jaw.
block('hit',4,25,'''
..............ggggg...............................
...........gggmnnnmggggg..........................
..........gmnnhhhhnmnnmg..........................
.........gmnnhhhhnnnhnnmg.......OOO...............
........gmnnnnnmmmnnnnnmg......OCCcO..............
.......gmnnmmmgggmmmnnmmg.....OCWWCcO.............
......OggggmmmmmgggmmmmmggOOOCCWWWCcDO............
.....OLHHHHgggggLLLLgggggLLSSCCWWWCCSDO...........
....OLHHHHLLLLLLLLLLLLLLLBSSCCWWWCDSSSSO..........
...OLHHLLLLLLLLLLLLLLLLLBBSSCCWWCDDKKKSSO.........
...OLLLLLLLLLLLLLBBBBBBBBSSCCWWCDDSSSSSSO.........
..OLLLLLLLLLBBBBBBBBBBBBBSSCCWCCSSCCCCCCOKO........
..OLLLLLLBBBBBBBBBBBBBBBSSCCWCCSCCCCCCCKKO........
..OLLLLBBBBBBBBBBBBBBBBBSSCCCCCCSCCCCcOO..........
..OBBBBBBBBBBBBBBBBBBBBBSSCCCCcCCccDDDO...........
OOOBBBBBBBBBBBBBBBBBBBBBSSSCCcCCDDKKDO............
OLBBBBBBBBBBBBBBBBBBBBBBSSDDccccDKKDO.............
OSBBBBBBBBBBBBBBBBBBBBBBBSSDDDDDCCcO..............
.OSSSBBBBBBBBBBBBBBBBBBBBBSSDDDDOOO...............
..OOSSSBBBBBBBBBBBBBBBBBBLLSSDDDO.................
....OSSSBBBBBBBBBBBBBBBLLLLSSDDDO.................
.....OSSSBBBBBBBBBBBSSBBLLBBSSDDO................
......OSSSBBBBBBBSSSSSBBBBBSSSDDO.................
.......OSSBBBBSSSSDDDDSSBBBSSSSDO.................
.......OSSBBBSSSDDDDDDDSSSSSSSSSO................
.......OSBBBSSSDDDOODDDDSSSSSSBSSO...............
......OSBBBSSSDDOO..OODDDDSSSBBBSSSO..............
......OSBBSSSDDO......OODDDSSBBBBSSSO.............
.....OSBBBSSSDO.........ODDSSBBBBBSSSO............
.....OSBBSSSSDO.........ODDSSBBBBBBSSSO...........
....OSBBBSSSSDO.........ODDSSSBBBBBBSSSO..........
....OSBBBBSSSSO.........ODSSSSSBBBBSSSSO..........
...OSBBBBBSSSSO.........ODSSSSSSBBSSSSSO..........
...OCcCcCcSSSSO.........OCcCcCcCcSSSSSSO..........
....OOOOOOOOOO...........OOOOOOOOOOOOOO...........
....OOOOOOOOOO...........OOOOOOOOOOOOOO...........
''')
# Dead: flank rests on the floor; flattened moss, closed eye; the near
# forepaw lies forward while the hind limb folds beneath the haunch.
block('dead',4,40,'''
.................gggggg..........................
.............ggggmnnnnmggggg.....................
...........ggmnnnhhhhhnmmnnmg....................
..........gmnnnhhnnnnnnnnhnnmg...................
........Oggmmnnnmmmmmmnnnnnmmg...................
......OOLLLggggggmmmggggggggggOO.................
.....OLHHHHHHHLLLgggLLLLLLLLLBBLOO.......OOO.....
....OLHHHHHLLLLLLLLLLLLLLLLBBBBBSSOO....OCCcO....
...OLHHLLLLLLLLLLLLLLLLLBBBBBBBBSSSSOOOCCWWCcO...
..OLLLLLLLLLLLLLLLLBBBBBBBBBBBBBBSSSSCCWWWCCDO...
..OLLLLLLLLLLBBBBBBBBBBBBBBBBBBBBSSSCCWWWCDSSOO..
..OLLLLLLBBBBBBBBBBBBBBBBBBBBBBBSSSCCWWCDDKKKSSO.
.OOBBBBBBBBBBBBBBBBBBBBBBBBBBBBSSSCCWCCDDSSSSSSO.
OLBBBBBBBBBBBBBBBBBBBBBBBBBBBBBSSSCCWCCSCCCCCOKO.
OSBBBBBBBBBBBBBBBBBBBBBBBBBBBBSSSCCCCCSCCCCCKKO..
OSSSBBBBBBBBBBBBBBBBBBBBBBBBSSSSCCCcCCCCCCcOO...
.OSSBBBBBBBBBBBBBBBBBBBBBBSSSSSDDccccccccDO.....
.OSSSBBBBBBBBBBBSSSBBBSSSSSSSSSDDDDDDDDDBBSOO...
..OSSSBBBBBBSSSSSSSSDDDDDSSSSSSDDDDDBBBBBBSSSO..
..OCcCcSSSSSSSSSSSSSDDDDDSSSSSSSBBBcCcCcSSSSSO.
...OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO..
''')
# Visual correction: detached far forepaw (x51..55,y48..53) is erased,
# then the shoulder-to-wrist diagonal is chosen explicitly, never filled.
for name in ['idle_a','idle_b','idle_c']:
 patch(name,[(51,48,'.....'),(51,49,'.....'),(51,50,'.....'),(51,51,'.....'),(51,52,'.....'),(51,53,'.....'),(40,45,'DDDO'),(40,46,'DDSSO'),(40,47,'DDSSSO'),(40,48,'DDSSSSO'),(40,49,'DDSSSSSO'),(44,50,'DSSSSO'),(45,51,'DSSSSO'),(45,52,'DcCcSO'),(45,53,'OOOOOO')])

# Earth charge: distinctly high bent wrist, elbow remains attached to
# the shoulder, the ochre light sits on its pads and claw roots.
block('skill_a',4,27,'''
................ggggg............................
.............gggmnnnmg..gggg......................
...........ggmnnhhhnnmggmnngg.....................
..........gmnnhhhhhnnnmnnnhnmg....................
.........gmnnhhnnnnmmmnnnhhnnmg...................
........gmnnnnmmmmnngmnnnnnnnmg.....OOO...........
........gmmmmggmmmngggmmmmnnmmg....OCCcO..........
.......OgggggmmnmmggggmmmmmgggOOOOCWWCcO.........
......OLLLHHHgggggLLLggggggBLLLSSCCWWWCCDO........
.....OLHHHHHLLLLLLLLLLLLLLLBLLLSSCCWWWCDSSOO......
....OLHHHHLLLLLLLLLLLLLLLLLBBBBSSCCWWWCDDKKSSO....
...OLHHHLLLLLLLLLLLLLLBBBBBBBBBSSCCWWCDDWWKSSO....
...OLLLLLLLLLLLLLLLBBBBBBBBBBBBSSCCWCCDSSSSSSSO...
...OLLLLLLLLLLBBBBBBBBBBBBBBBBSSCCWCCSSSCCCCCOKO..
...OLLLLLLLLBBBBBBBBBBBBBBBBBBSSCCCWCCSCCCCCKKO...
...OBLLLLLBBBBBBBBBBBBBBBBBBBBSSCCCCCcCCCCcOO.....
.OOOBBBBBBBBBBBBBBBBBBBBBBBBBBSSSCCCcCCCccDO......
OLBBBBBBBBBBBBBBBBBBBBBBBBBBBBSSDDccccccDDO.......
OSBBBBBBBBBBBBBBBBBBBBBBBBLBBBBSSDDDDDDDO.........
.OSSSBBBBBBBBBBBBBBBBBBBLLLBBBBSSDDDDDDO..........
..OOSSSBBBBBBBBBBBBBBBBBLLLBBBBSSDDDDDO...........
....OSSSBBBBBBBBBBBSSSSBBLLBBBSSDDDDDSSO..........
.....OSSSBBBBBBBBSSSSSSBBBBBBSSDDDDDSSSSOO........
......OSSSBBBBSSSSSSSSSBBBBBSSDDDDSSBBBBSSO.......
.......OSSBBBSSSSSSDDDDDDDDDDDDDDSSBLLLBBSSO.....
.......OSBBBSSSSDDDOOOODDDDDDDDDDSSBLLBBTTTeO....
.......OSBBSSSDDDOO....OOOOOODDDDDDSSBBTeeTeO....
......OSBBBSSDDOO...........ODDDDDDDSSSTeWeTO....
......OSBBSSSDO..............ODDDDDDDDSTeeTO.....
.....OSBBBSSSDO...............OOOOOOOOTTTO......
.....OSBBBBSSSO.................................
....OSBBBBBSSSO.................................
....OCcCcCcSSSO.................................
.....OOOOOOOOO..................................
''')
# Cast: body crouches over two supporting rear pads. Neck and striking
# shoulder flow into the glowing palm on the floor. Effects authored below.
block('skill_b',2,29,'''
...............ggggg.............................
............gggmnhnmgggg.........................
..........ggmnhhhhhnmnnng........................
........ggmnhhhhnnnnnnhnmg.......................
.......gmnnnnnnmmnnnnhhnnmg.....................
......gmnnnmmgggmmnnnnnnnmg....OOO...............
.....Ogggggmmmngggmmmnnnmmg...OCCcO..............
....OLHHHHHggggLLLgggggggggLOOCWWCcO.............
...OLHHHHLLLLLLLLLLLLLLLLBLSSCCWWWCCDO...........
..OLHHHLLLLLLLLLLLLBBBBBBBLSSCCWWWCDSSOO.........
..OLLLLLLLLLLLLLBBBBBBBBBBSSCCWWWCDDKKSSO........
..OLLLLLLLLBBBBBBBBBBBBBBBSSCCWWCDDWWKSSO........
..OLLLLLBBBBBBBBBBBBBBBBBSSCCWCCDSSSSSSSO........
..OLLLBBBBBBBBBBBBBBBBBBSSCCWCCSSCCCCCCOKO.......
.OOBBBBBBBBBBBBBBBBBBBBBSSCCCCCSCCCCCCKKO........
OLBBBBBBBBBBBBBBBBBBBBBBSSCCCCcCCCCCCcOO.........
OSBBBBBBBBBBBBBBBBBBBBBBSSCCCcCCCCCccOO..........
OSSSBBBBBBBBBBBBBBBBBBBBBSSDDccccccDO............
.OSSSBBBBBBBBBBBBBBBBBBBBSSDDDDDDDO..............
..OSSSBBBBBBBBBBBBBLLBBBBSSDDDDDDO...............
...OSSSBBBBBBBBBBLLLLBBBBSSDDDDDDO...............
....OSSSBBBBBBBBBLLLBBBBSSSDDDDDDO...............
.....OSSSBBBBBBSSSBBBBBSSSSDDDDDDO...............
.....OSSBBBBBSSSSDDDBBSSSSSDDDDDSSO..............
....OSSBBBBSSSSDDDDDDSSSSSSDDDDSSSSO.............
...OSSBBBSSSSDDDOOOODDDDDDDDDDSSBBBSSO...........
..OSBBBSSSSDDDOO....OODDDDDDDSSBBBBBSSO..........
..OSBBSSSSDDOO.......ODDDDSSBBBBBBSSSTTO.........
..OSBBSSSSDO.........ODDDSSBBBBBSTTeeTeTO........
..OCcCcSSSSO.........ODSSSSBBBSTeeWeeTTTO........
...OOOOOOOO...........OCcCcCcTeWeeTTttO.........
...OOOOOOOO............OOOOOTTTttttOO...........
''')
# Three unequal stone prongs: left short, central tallest, right leaning
# outward. All meet the pad-origin earth ridge at y57..60, x38..60.
patch('skill_b',[
 (53,21,'OtO'),(52,22,'OTeO'),(52,23,'OTeTO'),(51,24,'OTeeTO'),
 (51,25,'OTeeTO'),(51,26,'OTeTtO'),(50,27,'OTeeTtO'),
 (50,28,'OTeeTtO'),(50,29,'OTeTTtO'),(49,30,'OTeeTTtO'),
 (58,29,'OtO'),(57,30,'OTeO'),(57,31,'OTeTO'),
 (49,31,'OTeTTtO'),(49,32,'OTeTTtO'),(56,32,'OTeeTO'),
 (46,33,'OtO'),(49,33,'OTeeTtO'),(56,33,'OTeeTO'),
 (45,34,'OTeO'),(49,34,'OTeTTtO'),(56,34,'OTeTtO'),
 (45,35,'OTeTO'),(49,35,'OTeTTtO'),(55,35,'OTeeTtO'),
 (44,36,'OTeeTO'),(49,36,'OTeTTtO'),(55,36,'OTeTTtO'),
 (44,37,'OTeeTO'),(49,37,'OTTTttO'),(55,37,'OTeTTtO'),
 (43,38,'OTeeTtO'),(49,38,'OTeTttO'),(55,38,'OTeTTtO'),
 (43,39,'OTeTTtO'),(49,39,'OTeTttO'),(55,39,'OTTTttO'),
 (43,40,'OTeTTtO'),(49,40,'OTeTttO'),(54,40,'OTeTTttO'),
 (43,41,'OTeTTtO'),(49,41,'OTTTttO'),(54,41,'OTeTTttO'),
 (43,42,'OTTTttO'),(49,42,'OTeTttO'),(54,42,'OTeTTttO'),
 (43,43,'OTeTttO'),(49,43,'OTeTttO'),(54,43,'OTeTTttO'),
 (43,44,'OTeTttO'),(49,44,'OTTtttO'),(54,44,'OTTTtttO'),
 (42,45,'OTeTTttO'),(49,45,'OTTtttO'),(54,45,'OTeTtttO'),
 (42,46,'OTeTTttO'),(49,46,'OTTtttO'),(54,46,'OTeTtttO'),
 (42,47,'OTTTtttO'),(49,47,'OTttttO'),(54,47,'OTTttttO'),
 (42,48,'OTeTtttO'),(49,48,'OTttttO'),(54,48,'OTTttttO'),
 (42,49,'OTeTtttO'),(49,49,'OTttttO'),(54,49,'OTtttttO'),
 (41,50,'OTeTTtttO'),(49,50,'OTttttO'),(54,50,'OTtttttO'),
 (41,51,'OTTTttttO'),(49,51,'OTttttO'),(54,51,'OTtttttO'),
 (41,52,'OTeTttttO'),(49,52,'OTttttO'),(54,52,'OTtttttO'),
 (41,53,'OTTtttttO'),(49,53,'OTttttO'),(54,53,'OttttttO'),
 (40,54,'OTeTTttttTTTTttttttttO'),
 (40,55,'OTeTTttttTTTtttttttttO'),
 (39,56,'OTeeTTTTTTTTtttttttttO'),
 (38,57,'OTeeeTTTTTTTttttttttttO'),
 (37,58,'OTeWeeTTTTTTtttttttttttO'),
 (37,59,'OTeeeTTTTTTttttttttttttO'),
 (38,60,'OOOOOOOOOOOOOOOOOOOOOO')])
# Recovery from earth strike: raised muddy wrist and shattered clods.
block('skill_c',4,27,'''
................ggggg............................
.............gggmnnnmg..gggg......................
...........ggmnnhhhnnmggmnngg.....................
..........gmnnhhhhhnnnmnnnhnmg....................
.........gmnnhhnnnnmmmnnnhhnnmg...................
........gmnnnnmmmmnngmnnnnnnnmg.....OOO...........
........gmmmmggmmmngggmmmmnnmmg....OCCcO..........
.......OgggggmmnmmggggmmmmmgggOOOOCWWCcO.........
......OLLLHHHgggggLLLggggggBLLLSSCCWWWCCDO........
.....OLHHHHHLLLLLLLLLLLLLLLBLLLSSCCWWWCDSSOO......
....OLHHHHLLLLLLLLLLLLLLLLLBBBBSSCCWWWCDDKKSSO....
...OLHHHLLLLLLLLLLLLLLBBBBBBBBBSSCCWWCDDWWKSSO....
...OLLLLLLLLLLLLLLLBBBBBBBBBBBBSSCCWCCDSSSSSSSO...
...OLLLLLLLLLLBBBBBBBBBBBBBBBBSSCCWCCSSSCCCCCOKO..
...OLLLLLLLLBBBBBBBBBBBBBBBBBBSSCCCWCCSCCCCCKKO...
...OBLLLLLBBBBBBBBBBBBBBBBBBBBSSCCCCCcCCCCcOO.....
.OOOBBBBBBBBBBBBBBBBBBBBBBBBBBSSSCCCcCCCccDO......
OLBBBBBBBBBBBBBBBBBBBBBBBBBBBBSSDDccccccDDO.......
OSBBBBBBBBBBBBBBBBBBBBBBBBLBBBBSSDDDDDDDO.........
.OSSSBBBBBBBBBBBBBBBBBBBLLLBBBBSSDDDDDDO..........
..OOSSSBBBBBBBBBBBBBBBBBLLLBBBBSSDDDDDO...........
....OSSSBBBBBBBBBBBSSSSBBLLBBBSSDDDDDSSO..........
.....OSSSBBBBBBBBSSSSSSBBBBBBSSDDDDDSSSSO.........
......OSSSBBBBSSSSSSSSSBBBBBSSDDDDSSBBBSSO........
.......OSSBBBSSSSSSDDDDDDDDDDDDDDSSBBBBBSSO.......
.......OSBBBSSSSDDDOOOODDDDDDDDDSSBBBBBSSSO......
.......OSBBSSSDDDOO....OOOOOODDDDSSSBBTTTSO......
......OSBBBSSDDOO...........ODDDDDDSSTeTTTO......
......OSBBSSSDO..............ODDDDDDDSTeTTO......
.....OSBBBSSSDO...............OOOOOOOOTTTO.......
.....OSBBBBSSSO..................................
....OSBBBBBSSSO..................................
....OCcCcCcSSSO..................................
.....OOOOOOOOO...................................
''')
patch('skill_c',[(54,32,'tT'),(53,33,'TeTO'),(53,34,'TTtO'),(54,35,'OO'),(59,40,'tO'),(58,41,'TTO'),(58,42,'ttO'),(51,44,'tT'),(50,45,'TeTO'),(50,46,'TttO'),(51,47,'OO'),(55,51,'Tt'),(55,52,'ttO'),(57,56,'TtO'),(49,57,'tTO'),(49,58,'ttO'),(44,59,'tTtt'),(45,60,'OOO')])

# Poison: hunched head; lifted near paw cradles sore jaw. The other
# foreleg carries weight. Violet bubbles are separate authored clusters.
block('poison_a',4,29,'''
...............ggggg..............................
............gggmnnnmg..gggg.......................
..........ggmnnhhhnnmggmnngg......................
.........gmnnhhhhhnnnmnnnhnmg.....................
........gmnnhhnnnnmmmnnnhhnnmg....................
.......gmnnnnmmmmnngmnnnnnnnmg....................
.......gmmmmggmmmngggmmmmnnmmg....................
......OgggggmmnmmggggmmmmmgggOO...................
.....OLLLHHHgggggLLLggggggBLLLLOO....OOO.........
....OLHHHHHLLLLLLLLLLLLLLLBLLLLLSSOOOCCcO........
...OLHHHHLLLLLLLLLLLLLLLLLBBBBLSSSCCWWCcO........
..OLHHHLLLLLLLLLLLLLLBBBBBBBBBBSSCCWWWCCDO........
..OLLLLLLLLLLLLLLLBBBBBBBBBBBBBSSCCWWWCDSSOO......
..OLLLLLLLLLLBBBBBBBBBBBBBBBBBBSSCCWWCDDKKSSO....
..OLLLLLLLLBBBBBBBBBBBBBBBBBBBSSCCWCDDSSSSSSSO...
..OBLLLLLBBBBBBBBBBBBBBBBBBBBSSCCWCCSSCCCCCCOKO..
OOOBBBBBBBBBBBBBBBBBBBBBBBBBBSSCCCCCSCCCCCCKKO...
OLBBBBBBBBBBBBBBBBBBBBBBBBBBBSSCCCcCCCCCCcOO.....
OSBBBBBBBBBBBBBBBBBBBBBBLLBBBBSSDDccccccDDO.......
.OSSSBBBBBBBBBBBBBBBBBLLLLBBBBSSDDDDDDDSSO.......
..OOSSSBBBBBBBBBBBBBBBLLLLBBBBSSDDDDSSBBBSSO.....
....OSSSBBBBBBBBBBSSBBLLLBBBBSSSDDDSSBLLBBBSSO...
.....OSSSBBBBBBBSSSSSBLLBBBBSSSDDDDSSBBBBcCcO....
......OSSSBBBBSSSSSSSBBBSSSSSSDDDDDSSBBcCCOO.....
.......OSSBBBSSSSSSSSBSSSSSSSDDDDDDSSOOOO........
.......OSBBBSSSSSSSDDDDSSSSSDDDDDDSSSO...........
.......OSBBSSSSDDDOOOODDDDDDDDDDDSSSO...........
......OSBBBSSSDDOO....OOOOOOOOODDDSSSSO..........
......OSBBSSSSDO.........ODDSSSSDDDSSSO..........
.....OSBBBSSSSDO.........ODSSSSSSSSSSSO..........
.....OCcCcCcSSSO.........OCcCcCcCcSSSSO..........
......OOOOOOOOO...........OOOOOOOOOOOO...........
''')
patch('poison_a',[(48,24,'ggg'),(47,25,'gvWvg'),(47,26,'gv.vg'),(48,27,'ggg'),(55,31,'gg'),(54,32,'gvvg'),(55,33,'gg'),(44,30,'v')])
block('poison_b',4,28,'''
................ggggg.............................
.............gggmnnnmg..gggg......................
...........ggmnnhhhnnmggmnngg.....................
..........gmnnhhhhhnnnmnnnhnmg....................
.........gmnnhhnnnnmmmnnnhhnnmg...................
........gmnnnnmmmmnngmnnnnnnnmg...................
........gmmmmggmmmngggmmmmnnmmg...................
.......OgggggmmnmmggggmmmmmgggOO..................
......OLLLHHHgggggLLLggggggBLLLLOO................
.....OLHHHHHLLLLLLLLLLLLLLLBLLLLSSOO...OOO........
....OLHHHHLLLLLLLLLLLLLLLLLBBBBLSSSOOOCCcO.......
...OLHHHLLLLLLLLLLLLLLBBBBBBBBBBSSSCCWWCcO.......
...OLLLLLLLLLLLLLLLBBBBBBBBBBBBBSSCCWWWCCDO.......
...OLLLLLLLLLLBBBBBBBBBBBBBBBBBBSSCCWWWCDSSOO.....
...OLLLLLLLLBBBBBBBBBBBBBBBBBBBSSCCWWCDDKKKSSO...
...OBLLLLLBBBBBBBBBBBBBBBBBBBBSSCCWCDDSSSSSSSO...
.OOOBBBBBBBBBBBBBBBBBBBBBBBBBBSSCCWCCSSCCCCCCOKO.
OLBBBBBBBBBBBBBBBBBBBBBBBBBBBBSSCCCCCSCCCCCCKKO..
OSBBBBBBBBBBBBBBBBBBBBBBBBLBBBBSSCCCcCCCCCCcOO....
.OSSSBBBBBBBBBBBBBBBBBBBLLLBBBBSSDDccccccDDO......
..OOSSSBBBBBBBBBBBBBBBBBLLLBBBBSSDDDDDDDSSO......
....OSSSBBBBBBBBBBBSSSSBBLLBBBSSDDDDSSBBBSSO.....
.....OSSSBBBBBBBBSSSSSSBBBBBBSSDDDDSSBLLBBSSO....
......OSSSBBBBSSSSSSSSSBBBBBSSDDDDDSSBBBBcCcO....
.......OSSBBBSSSSSSDDDDDDDDDDDDDDDDSSBBcCCOO.....
.......OSBBBSSSSDDDOOOODDDDDDDDDDDDSSOOOO........
.......OSBBSSSDDDOO....OOOOOODDDDDDDSSSO.........
......OSBBBSSDDOO...........ODDDDDDDSSSO.........
......OSBBSSSDO..............ODDSSSSSSSSO.........
.....OSBBBSSSDO..............ODSSSSSSSSSO.........
.....OSBBBBSSSO..............OSSSBBBBSSSO.........
....OCcCcCcSSSO..............OCcCcCcSSSSO.........
.....OOOOOOOOO................OOOOOOOOOO..........
''')
patch('poison_b',[(51,20,'v'),(46,23,'gg'),(45,24,'gvWg'),(45,25,'gvvg'),(46,26,'gg'),(56,27,'ggg'),(55,28,'gvWvg'),(55,29,'gv.vg'),(56,30,'ggg'),(52,33,'v')])

# Stun: dropped muzzle, bent wrist, head hangs between shoulder and
# standing paw; ears fold. Stars have hand-chosen unequal silhouettes.
block('stun_a',4,29,'''
...............ggggg..............................
............gggmnnnmg..gggg.......................
..........ggmnnhhhnnmggmnngg......................
.........gmnnhhhhhnnnmnnnhnmg.....................
........gmnnhhnnnnmmmnnnhhnnmg....................
.......gmnnnnmmmmnngmnnnnnnnmg....................
.......gmmmmggmmmngggmmmmnnmmg....................
......OgggggmmnmmggggmmmmmgggOO...................
.....OLLLHHHgggggLLLggggggBLLLLOO.................
....OLHHHHHLLLLLLLLLLLLLLLBLLLLLSSOO..............
...OLHHHHLLLLLLLLLLLLLLLLLBBBBLSSSSSOO............
..OLHHHLLLLLLLLLLLLLLBBBBBBBBBBSSSSCCcOOO.........
..OLLLLLLLLLLLLLLLBBBBBBBBBBBBBSSCCWWWCCcO........
..OLLLLLLLLLLBBBBBBBBBBBBBBBBBBSSCCWWWCCDSSOO.....
..OLLLLLLLLBBBBBBBBBBBBBBBBBBBSSCCWWCCDDSSSSSO....
..OBLLLLLBBBBBBBBBBBBBBBBBBBBSSCCWWCDDKKKSSSO....
OOOBBBBBBBBBBBBBBBBBBBBBBBBBBSSCCWCCDDSSSSSSSO...
OLBBBBBBBBBBBBBBBBBBBBBBBBBBBSSCCCCCSSCCCCCCOKO..
OSBBBBBBBBBBBBBBBBBBBBBBLLBBBBSSCCCcCCSCCCCKKO...
.OSSSBBBBBBBBBBBBBBBBBLLLLBBBBSSDDccccCCCcOO.....
..OOSSSBBBBBBBBBBBBBBBLLLLBBBBSSDDDDccccDO........
....OSSSBBBBBBBBBBSSBBLLLBBBBSSSDDDDDDOO..........
.....OSSSBBBBBBBSSSSSBLLBBBBSSSSDDDDDO...........
......OSSSBBBBSSSSSSSBBBSSSSSSSSDDDDDO...........
.......OSSBBBSSSSSSSSBSSSSSSSSDDDDDSSO...........
.......OSBBBSSSSSSSDDDDSSSSSSDDDDDSSSO...........
.......OSBBSSSSDDDOOOODDDDDDDDDDDSSSO...........
......OSBBBSSSDDOO....OOOOOOOOODDDSSSSO..........
......OSBBSSSSDO.........ODDSSSSDDDSSSO..........
.....OSBBBSSSSDO.........ODSSSSSSSSSSSO..........
.....OCcCcCcSSSO.........OCcCcCcCcSSSSO..........
......OOOOOOOOO...........OOOOOOOOOOOO...........
''')
patch('stun_a',[(43,23,'e'),(43,24,'We'),(41,25,'eWWWe'),(42,26,'eWe'),(43,27,'e'),(55,33,'e'),(53,34,'eWWe'),(55,35,'e')])
block('stun_b',4,28,'''
................ggggg.............................
.............gggmnnnmg..gggg......................
...........ggmnnhhhnnmggmnngg.....................
..........gmnnhhhhhnnnmnnnhnmg....................
.........gmnnhhnnnnmmmnnnhhnnmg...................
........gmnnnnmmmmnngmnnnnnnnmg...................
........gmmmmggmmmngggmmmmnnmmg...................
.......OgggggmmnmmggggmmmmmgggOO..................
......OLLLHHHgggggLLLggggggBLLLLOO................
.....OLHHHHHLLLLLLLLLLLLLLLBLLLLSSOO..............
....OLHHHHLLLLLLLLLLLLLLLLLBBBBLSSSSOO............
...OLHHHLLLLLLLLLLLLLLBBBBBBBBBBSSSSSOO...........
...OLLLLLLLLLLLLLLLBBBBBBBBBBBBBSSSCCccOO.........
...OLLLLLLLLLLBBBBBBBBBBBBBBBBBBSSCCWWWCcDO.......
...OLLLLLLLLBBBBBBBBBBBBBBBBBBBSSCCWWWCCDDSSO.....
...OBLLLLLBBBBBBBBBBBBBBBBBBBBSSCCWWCCDDSSSSO....
.OOOBBBBBBBBBBBBBBBBBBBBBBBBBBSSCCWWCDDKKKSSO....
OLBBBBBBBBBBBBBBBBBBBBBBBBBBBBSSCCWCCDDSSSSSSO...
OSBBBBBBBBBBBBBBBBBBBBBBBBLBBBBSSCCCCCSSCCCCOKO..
.OSSSBBBBBBBBBBBBBBBBBBBLLLBBBBSSCCCcCCSCCCKKO...
..OOSSSBBBBBBBBBBBBBBBBBLLLBBBBSSDDccccCCCcOO.....
....OSSSBBBBBBBBBBBSSSSBBLLBBBSSDDDDDccccO........
.....OSSSBBBBBBBBSSSSSSBBBBBBSSDDDDDDDOO.........
......OSSSBBBBSSSSSSSSSBBBBBSSDDDDDDDDO..........
.......OSSBBBSSSSSSDDDDDDDDDDDDDDDDSSSO..........
.......OSBBBSSSSDDDOOOODDDDDDDDDDDDSSSO..........
.......OSBBSSSDDDOO....OOOOOODDDDDDDSSSO.........
......OSBBBSSDDOO...........ODDDDDDDSSSO.........
......OSBBSSSDO..............ODDSSSSSSSSO.........
.....OSBBBSSSDO..............ODSSSSSSSSSO.........
.....OSBBBBSSSO..............OSSSBBBBSSSO.........
....OCcCcCcSSSO..............OCcCcCcSSSSO.........
.....OOOOOOOOO................OOOOOOOOOO..........
''')
patch('stun_b',[(51,25,'e'),(50,26,'eWe'),(49,27,'eWWWWe'),(51,28,'eWe'),(52,29,'e'),(38,24,'e'),(37,25,'eWe'),(38,26,'e')])

# Sleep is a deep, stable curl, not a flattened corpse. Back arches high;
# closed eye over the muzzle which rests on the folded front wrists.
block('sleep_a',4,33,'''
...............ggggg.............................
............gggmnnnmg..gggg......................
..........ggmnnhhhnnmggmnngg.....................
.........gmnnhhhhhnnnmnnnhnmg....................
........gmnnhhnnnnmmmnnnhhnnmg...................
.......gmnnnnmmmmnngmnnnnnnnmg...................
.......gmmmmggmmmngggmmmmnnmmg...................
......OgggggmmnmmggggmmmmmgggOO..................
.....OLLLHHHgggggLLLggggggBLLLLOO................
....OLHHHHHLLLLLLLLLLLLLLLBLLLLLSSOO.............
...OLHHHHLLLLLLLLLLLLLLLLLBBBBLSSSSSOO...........
..OLHHHLLLLLLLLLLLLLLBBBBBBBBBBSSSCCcOOO........
..OLLLLLLLLLLLLLLLBBBBBBBBBBBBBSSCCWWWCCcO.......
..OLLLLLLLLLLBBBBBBBBBBBBBBBBBBSSCCWWWCCDSSOO....
..OLLLLLLLLBBBBBBBBBBBBBBBBBBBSSCCWWCCDDSSSSSO...
..OBLLLLLBBBBBBBBBBBBBBBBBBBBSSCCWWCDDKKKSSSO...
OOOBBBBBBBBBBBBBBBBBBBBBBBBBBSSCCWCCDDSSSSSSSO..
OLBBBBBBBBBBBBBBBBBBBBBBBBBBBSSCCCCCSSCCCCCCOKO.
OSBBBBBBBBBBBBBBBBBBBBBBLLBBBBSSCCCcCCSCCCCKKO..
OSSSBBBBBBBBBBBBBBBBBBLLLLBBBBSSDDccccCCCcOO....
.OSSBBBBBBBBBBBBBBBBBBLLLLBBBBSSDDDDDccccDO.....
.OSSSBBBBBBBBBBBBBBSSBLLLBBBBSSSDDDDDDDDO.......
..OSSSBBBBBBBBBBBBSSSSBLLBBBSSSSDDDDDDDO........
..OSSSBBBBBBBBBBSSSSSSSBBBBSSSSSSSSBBBBSSOO.....
..OSSSSBBBBBBSSSSSSSSSSSSSSSSSSSSBBBBBBBSSSO...
..OCcCcSSSSSSSSSSSSSSSSSSSSSSSSBBcCcCcSSSSSO..
...OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO..
...OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO..
''')
block('sleep_b',4,32,'''
................ggggg............................
.............gggmnnnmg..gggg.....................
...........ggmnnhhhnnmggmnngg....................
..........gmnnhhhhhnnnmnnnhnmg...................
.........gmnnhhnnnnmmmnnnhhnnmg..................
........gmnnnnmmmmnngmnnnnnnnmg..................
........gmmmmggmmmngggmmmmnnmmg..................
.......OgggggmmnmmggggmmmmmgggOO.................
......OLLLHHHgggggLLLggggggBLLLLOO...............
.....OLHHHHHLLLLLLLLLLLLLLLBLLLLLSSOO............
....OLHHHHLLLLLLLLLLLLLLLLLBBBBLSSSSSOO..........
...OLHHHLLLLLLLLLLLLLLBBBBBBBBBBSSSSCCcOO........
...OLLLLLLLLLLLLLLLBBBBBBBBBBBBBSSCCWWWCCcO......
...OLLLLLLLLLLBBBBBBBBBBBBBBBBBBSSCCWWWCCDSSOO...
...OLLLLLLLLBBBBBBBBBBBBBBBBBBBSSCCWWCCDDSSSSSO..
...OBLLLLLBBBBBBBBBBBBBBBBBBBBSSCCWWCDDKKKSSSO..
.OOOBBBBBBBBBBBBBBBBBBBBBBBBBBSSCCWCCDDSSSSSSSO.
OLBBBBBBBBBBBBBBBBBBBBBBBBBBBBSSCCCCCSSCCCCCCOKO
OSBBBBBBBBBBBBBBBBBBBBBBBBLBBBBSSCCCcCCSCCCCKKO.
OSSSBBBBBBBBBBBBBBBBBBBBBLLBBBBSSDDccccCCCcOO...
.OSSBBBBBBBBBBBBBBBBBBBBLLBBBBSSDDDDDccccDO....
.OSSSBBBBBBBBBBBBBBBSSSBBLLBBBSSDDDDDDDDDO......
..OSSSBBBBBBBBBBBBSSSSSSBBBBBBSSDDDDDDDDO.......
..OSSSBBBBBBBBBBSSSSSSSSBBBBBSSSSSSDDDDDO.......
..OSSSSBBBBBBSSSSSSSSSSSSSSSSSSSSSSBBBBSSOO....
..OSSSSSBBBSSSSSSSSSSSSSSSSSSSSSBBBBBBBSSSSO...
..OCcCcSSSSSSSSSSSSSSSSSSSSSSSSBBcCcCcSSSSSO..
...OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO..
...OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO..
''')
# Second visual pass: cheek edits had overrun the narrow muzzle contour.
# Restore only the named rows to chosen facial strings, preserving breath.
patch('idle_b',[
(0,34,'.........OLHHHHHLLLLLLLLLLLLLLLBLLLLLSSCCWWWCCSDOO..............'),
(0,43,'.....OSBBBBBBBBBBBBBBBBBBBBBBLLBBBBSSDDccccccDDOO...............'),
(0,44,'......OSSSBBBBBBBBBBBBBBBBBLLLLBBBBSSDDDDDDDO...................')])
patch('idle_c',[
(0,37,'.......OLLLLLLLLLLLBBBBBBBBBBBBBBBBBSSCCWWCDDSSKSSO.............'),
(0,38,'.......OLLLLLLLLLLBBBBBBBBBBBBBBBBBBSSCCWCCDSSSSSSSO............'),
(0,39,'.......OLLLLLLLLBBBBBBBBBBBBBBBBBBBSSCCWCCSSSCCCCCOKO...........'),
(0,44,'......OSSSBBBBBBBBBBBBBBBBBLLLLBBBBSSDDDDDDDO...................')])
# Keep the far foreleg joined and give it a planted shorter pad behind
# the large near paw: y53..58 are explicitly written native clusters.
for name in ['idle_a','idle_b','idle_c']:
 patch(name,[(45,53,'DDSSSSO'),(45,54,'DDSSSSO'),(46,55,'DSSSSSO'),(46,56,'DSSSSSSO'),(46,57,'DcCcSSSO'),(47,58,'OOOOOO')])
# Light-background inspection: give the authored stars an ochre edge so
# white star centers retain shape against pale backgrounds.
patch('stun_a',[(43,23,'T'),(42,24,'TeT'),(40,25,'TeWWeT'),(42,26,'TeT'),(43,27,'T'),(55,33,'T'),(53,34,'TeWeT'),(55,35,'T')])
patch('stun_b',[(51,25,'T'),(50,26,'TeT'),(48,27,'TeWWWeT'),(50,28,'TeT.'),(51,29,'T.'),(38,24,'T'),(37,25,'TeT'),(38,26,'T')])
write()
