import { createServer } from "vite";
import assert from "node:assert/strict";
import { writeFile, rm } from "node:fs/promises";
const root = process.cwd();
const cache = `${root}/.vite-cache/st_01a076ed-public`;
const server = await createServer({ configFile: false, root, cacheDir: cache, resolve: { alias: { "@": `${root}/src` } }, server: { middlewareMode: true, watch: null }, appType: "custom", logLevel: "error" });
const observations = [];
try {
  const { createFarmingDemoProject } = await server.ssrLoadModule("/src/project/defaults.ts");
  const { startSession } = await server.ssrLoadModule("/src/project/session.ts");
  const { serialize, deserialize } = await server.ssrLoadModule("/src/project/io.ts");
  const { resolveToolUseOnTile, toolActionRulesOf } = await server.ssrLoadModule("/src/project/toolActions.ts");
  const { interactWithFarmPlot, farmIntentForHand, advanceFarmPlotsForDay } = await server.ssrLoadModule("/src/player/farming.ts");
  const { placeObject, ensureChest } = await server.ssrLoadModule("/src/project/placeables.ts");
  const project = createFarmingDemoProject();
  project.session.homeDecorationPlacements = [];
  project.session.farmBuildingPlacements = [];
  const map = project.maps[project.startMapId];
  map.lowerTiles.fill(0); map.upperTiles.fill(-1);
  project.tilesets[map.tilesetId].passability[0] = { up: true, down: true, left: true, right: true };
  project.system.toolActions = toolActionRulesOf(project).map(rule => ({ ...rule }));
  const session = startSession(project, 1);
  session.equippedToolItemId = "item_hoe";
  const act = (x, y) => interactWithFarmPlot(project, session, map, x, y, farmIntentForHand(project, session));
  assert.equal(act(4, 5).kind, "tilled");
  session.equippedToolItemId = "item_potato_seed";
  assert.equal(act(4, 5).kind, "planted");
  session.equippedToolItemId = "item_watering_can";
  assert.equal(act(4, 5).kind, "watered");
  advanceFarmPlotsForDay(project, session);
  assert.equal(act(4, 5).kind, "watered");
  advanceFarmPlotsForDay(project, session);
  project.system.toolActions.unshift({ id: "special-harvest", action: "harvest", itemId: "item_hoe", farmTool: "axe" });
  const before = structuredClone(session);
  assert.equal(act(4, 5).kind, "ignored");
  assert.deepEqual(session, before);
  session.equippedToolItemId = "item_hoe";
  const harvest = act(4, 5);
  assert.equal(harvest.kind, "harvested");
  observations.push({ path: "actual farm authority", harvest, refusedWrongHandUnchanged: true });
  for (const [kind, action] of [["tree", "chop"], ["rock", "mine"]]) {
    project.system.toolActions = [{ id: `special-${action}`, action, itemId: "item_hoe", requiresFarmable: false }];
    placeObject(session, { id: kind, kind, itemId: "item_potato", mapId: map.id, x: 1, y: 1 });
    const result = act(1, 1);
    assert.equal(result.kind, "harvested");
    assert.equal(result.source, kind);
    observations.push({ path: "actual placeable authority", result });
  }
  project.system.toolActions = [{ id: "outside", action: "till", farmTool: "hoe", requiresFarmable: false }];
  const restored = deserialize(serialize(project));
  assert.equal(restored.version, 4);
  assert.equal(restored.system.toolActions[0].requiresFarmable, false);
  assert.equal(interactWithFarmPlot(restored, session, map, 1, 1, "till").kind, "tilled");
  ensureChest(session, { id: "occupied", mapId: map.id, x: 2, y: 1 });
  const occupiedBefore = structuredClone(session);
  assert.equal(interactWithFarmPlot(restored, session, map, 2, 1, "till").kind, "ignored");
  assert.deepEqual(session, occupiedBefore);
  observations.push({ path: "Project4 false roundtrip and occupied refusal", version: restored.version, rules: restored.system.toolActions, unchanged: true });
  project.system.toolActions = [{ id: "fish-any-tool", action: "fish" }];
  const fishRule = resolveToolUseOnTile(project, session, map, 1, 1, "fish");
  assert.equal(fishRule.ruleId, "fish-any-tool");
  session.equippedToolItemId = "item_potato_seed";
  assert.equal(resolveToolUseOnTile(project, session, map, 1, 1, "fish"), undefined);
  observations.push({ path: "fish resolver ONLY; input/catch wiring belongs to task10", fishRule, seedRefused: true });
  await writeFile(`${root}/.omo/evidence/life-full-20260906/phase3-verification/tools/public-state.json`, JSON.stringify({ nativePlayer: false, authority: "real imported public modules", observations }, null, 2) + "\n");
  console.log("Public authority probe passed: crop lifecycle, harvest permission, chop/mine, false Project4 roundtrip, occupancy refusal, fish resolver.");
} finally {
  await server.close();
  await rm(cache, { recursive: true, force: true });
}
