GK={'fish':'생선','fishr':'붉은 생선','fishg':'푸른 생선','squid':'오징어','crab':'게','shell':'조개','cabbage':'양배추','carrot':'당근','tomato':'토마토','pumpkin':'호박','potato':'감자','onion':'양파','eggplant':'가지','apple':'사과','lemon':'레몬','grape':'포도','loaf':'식빵','baguette':'바게트','bun':'둥근빵','pie':'파이','cake':'케이크','potion':'물약','herb':'약초','vial':'약병','jar':'단지','mushroom':'버섯','flower':'꽃','book':'책','scroll':'두루마리','gem':'보석','coins':'동전','yarn':'실타래','bolt':'옷감','bottle':'술병','candle':'초','cheese':'치즈','egg':'달걀','ham':'햄','sausage':'소시지','steak':'고기','ingot':'주괴','horseshoe':'편자','wool':'양모','toy':'인형','skull':'해골','ice':'얼음','plate':'접시','mug':'잔','flask':'플라스크','cup':'찻잔'}
CK={'ice chest':'얼음 진열함','crate':'궤짝','basket':'바구니','barrel':'통','shelf':'벽 선반','cabinet':'진열장','hang':'걸이','table':'탁자','sack':'자루'}
UK={'apothecary drawers':'약재 서랍장','mortar and pestle':'절구','alembic':'증류기','cauldron':'가마솥','herb drying rack':'약초 건조대','balance scale':'천칭','fish ice chest':'얼음 생선함','fish tank':'수조','fishing net':'그물','chopping block':'도마 통나무','meat hooks':'고기 걸이대','bread oven':'빵 화덕','dough table':'반죽대','cake display case':'케이크 진열장','anvil':'모루','forge':'용광로','grindstone':'숫돌','quench barrel':'담금질 통','armor stand':'갑옷 거치대','weapon barrel':'무기 통','tool wall':'공구 걸이','keg rack':'술통 선반','dart board':'다트판','piano':'피아노','lute':'류트','bar stool':'바 의자','pew':'교회 긴의자','altar':'제단','lectern':'성경대','pipe organ':'파이프 오르간','stained glass':'스테인드글라스','candelabra':'촛대(큰)','holy water font':'성수반','writing desk':'책상','globe':'지구의','telescope':'망원경','scroll rack':'두루마리 선반','armchair':'안락의자','sofa':'소파','coat rack':'옷걸이','nightstand lamp':'협탁 등','vanity mirror':'화장대','washbasin':'세면대','bathtub':'욕조','cradle':'요람','canopy bed':'닫집 침대','straw bed':'짚 침대','kitchen sink':'개수대','dish rack':'그릇 선반','hanging pans':'냄비 걸이','firewood pile':'장작더미','water jar':'물독','crystal ball':'수정구','spellbook stand':'마법서 받침','magic circle':'마법진','treasure pile':'보물 더미','wall clock':'벽시계','deer trophy':'사슴 박제','wall map':'벽 지도','notice board':'게시판','curtained window':'커튼 창','wall sconce':'벽등','throne':'왕좌','royal chest':'왕실 상자','tea table':'찻상','mannequin':'마네킹','spinning wheel':'물레','loom':'베틀','sewing table':'재봉대','fabric bolt rack':'옷감 선반','tailor mirror':'전신 거울','round rug':'둥근 양탄자','runner':'긴 양탄자','fur rug':'모피 깔개','green rug':'초록 양탄자','purple rug':'보라 양탄자','stool':'스툴','cupboard':'서랍장','wardrobe':'옷장','clock':'괘종시계','chest':'상자','barrel':'통','crate':'궤짝','sack':'자루','plant':'화분','pot':'항아리','candle':'촛대','fireplace':'벽난로','window':'창','picture':'그림','shelf pots':'단지 선반','bottles':'병 선반','stove':'화덕','stairs down':'내려가는 계단','doormat':'발깔개','roundtable':'원탁','weapon rack':'무기걸이','shield':'방패','rug red':'붉은 양탄자','counter 3':'카운터 3칸','counter 2':'카운터 2칸','stairs up stone':'돌 계단','stairs up wood':'나무 계단','bench 2':'벤치 2칸','bench 3':'벤치 3칸'}
COLK={'blue':'파랑','red':'빨강','teal':'청록','yellow':'노랑','green':'초록'}
CAT={'veg':'채소','fish':'생선가게','bake':'빵집','pharm':'약국','misc':'잡화','butcher':'정육점','smith':'대장간','tavern':'선술집','church':'예배당','study':'서재','home':'가구·살림','kitchen':'부엌','magic':'마법','decor':'장식','tailor':'재단사','shop':'상점'}
def ko(n):
    if ':' in n:
        c,g=n.split(':'); out=[]
        for x in g.split('+'):
            t=GK.get(x) or GK.get(x[:-1],x)
            if t not in out: out.append(t)
        return '·'.join(out)+' '+CK[c]
    if n in UK: return UK[n]
    for pre,k in (('tall vase ','키큰 꽃병 '),('banner ','깃발 '),('bed ','침대 '),('double bed ','2인 침대 '),('chair ','의자 '),('table ','식탁 '),('bookshelf ','책장 '),('display ','진열 '),('potted ','화분 ')):
        if n.startswith(pre):
            r=n[len(pre):]; return k+COLK.get(r,{'fern':'고사리','flowering':'꽃','sapling':'묘목','cactus':'선인장','potion':'물약','apple':'사과','bread':'빵'}.get(r,r))
    return n
