"""labels.json → src/assets/seCatalogRuntime.ts + src/assets/seCatalog.ts

    python scripts/se/build-se-catalog.py [--staging dist/se-staging]

BGM 카탈로그와 같은 2분할이다: 런타임(게임)은 id→경로만 알면 되고, 제목·카테고리·태그 같은
에디터 메타데이터가 리소스 해석기를 타고 플레이어 번들에 실리면 안 된다.

BGM 과 다른 점 둘:
- SE 파일은 레포에 있다. CDN 조립 모듈(bgmCdn.ts) 대응물이 필요 없다.
- SE 는 원샷이라 loop 플래그가 없다.
"""
import argparse, json, os, sys

try:
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
except Exception:
    pass

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))

HEADER = """// Generated by scripts/se/build-se-catalog.py. Do not edit by hand.
// 원본: CC0 효과음 8팩(Kenney 5 + OpenGameArt 3). 전량 CC0-1.0.
// 출처·제외 근거는 public/assets/ATTRIBUTION.md 「CC0 효과음 카탈로그」 절에 있다.
//
// 재생성: python scripts/se/fetch-se-packs.py
//         python scripts/se/place-se-assets.py
//         python scripts/se/build-se-labels.py
//         python scripts/se/build-se-catalog.py
"""

RUNTIME_DOC = """//
// 이 파일은 **런타임(게임) 전용 최소 정보**다. 제목·카테고리·태그 같은 에디터 메타데이터는
// seCatalog.ts 에 있다. 둘을 합치면 에디터 메타데이터가 리소스 해석기를 타고 플레이어
// 번들에까지 실린다 — 게임은 재생할 파일 경로만 알면 된다.
//
// BGM 과 달리 파일이 레포에 있으므로(public/assets/se/) 경로를 그대로 담는다. CDN 없음.
"""


def ts_str(s):
    return json.dumps(s, ensure_ascii=False)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--staging', default=os.path.join(REPO, 'dist', 'se-staging'))
    args = ap.parse_args()
    staging = os.path.abspath(args.staging)

    rows = json.load(open(os.path.join(staging, 'labels.json'), encoding='utf-8'))
    if not rows:
        raise SystemExit('labels.json 이 비었다 — build-se-labels.py 를 먼저 돌려라')

    # 카테고리 등장 순서를 피커 그룹 순서로 쓴다(labels.py 의 CAT_ORDER 가 이미 정렬해 둔다).
    cats = []
    for r in rows:
        if r['category'] not in cats:
            cats.append(r['category'])

    total_seconds = round(sum(r['seconds'] for r in rows), 3)

    # ── 런타임 ────────────────────────────────────────────────────────────
    out = [HEADER, RUNTIME_DOC, '',
           '/** 리소스 id → public/ 하위 경로. */',
           'const SE_RUNTIME_ENTRIES: readonly (readonly [string, string])[] = [']
    for r in rows:
        out.append('  [%s, %s],' % (ts_str(r['id']), ts_str(r['path'])))
    out += ['];', '',
            'const BY_ID: ReadonlyMap<string, string> = new Map(SE_RUNTIME_ENTRIES);', '',
            '/** 카탈로그 효과음 수. 테스트의 기대 수량보다 줄면 카탈로그 회귀다. */',
            'export const SE_CATALOG_COUNT = SE_RUNTIME_ENTRIES.length;', '',
            '/** 카탈로그 총 길이(초). 개수만 세면 놓치는 "파일이 바뀐" 회귀를 잡는다. */',
            'export const SE_CATALOG_TOTAL_SECONDS = %s;' % total_seconds, '',
            '/** 이 리소스 id 가 CC0 효과음 카탈로그 소속인지. */',
            'export function isSeCatalogResourceId(resourceId: string): boolean {',
            '  return BY_ID.has(resourceId);', '}', '',
            '/** 리소스 id → public/ 하위 경로. 카탈로그 밖이면 undefined. */',
            'export function findSeRuntimePath(resourceId: string): string | undefined {',
            '  return BY_ID.get(resourceId);', '}', '',
            '/** 카탈로그의 모든 리소스 id(카탈로그 순서). */',
            'export function seCatalogResourceIds(): readonly string[] {',
            '  return SE_RUNTIME_ENTRIES.map(([id]) => id);', '}', '']
    runtime_path = os.path.join(REPO, 'src', 'assets', 'seCatalogRuntime.ts')
    open(runtime_path, 'w', encoding='utf-8', newline='\n').write('\n'.join(out))

    # ── 에디터 메타데이터 ─────────────────────────────────────────────────
    out = [HEADER,
           '//', '// 에디터 전용 메타데이터. 재생에 필요한 경로는 seCatalogRuntime.ts 에 있다.',
           '//', '// 라벨 근거의 한계: 제목/태그는 원본 파일명 의미 + 원본 팩 폴더 분류 +',
           '// 측정값(길이/피크/RMS)으로만 붙였다. 음색 형용사는 지어내지 않았다 —',
           '// 청취 후 수정은 dist/se-staging/audition.html 로 모아 재생성한다.', '',
           '/** 번들 CC0 효과음 하나의 에디터용 메타데이터. */',
           'export type SeCatalogEntry = {',
           '  readonly id: string;',
           '  /** 한국어 표시 제목("결정 01"). 피커 라벨이다. */',
           '  readonly title: string;',
           '  /** 슬롯 분류("UI · 결정 · 취소"). 피커 그룹 헤더와 검색 태그의 근거다. */',
           '  readonly category: string;',
           '  /** 변형을 뺀 기본 이름("결정"). 같은 소리의 변형끼리 묶는 축이다. */',
           '  readonly baseName: string;',
           '  /** 변형 번호. 변형이 하나뿐이면 null. */',
           '  readonly variant: number | null;',
           '  readonly seconds: number;',
           '  readonly bytes: number;',
           '  readonly sha256: string;',
           '  readonly codec: string;',
           '  readonly sampleRate: number;',
           '  readonly channels: number;',
           '  /** 피크/RMS. Ogg 는 디코더가 없어 측정하지 못했다(null). */',
           '  readonly peak: number | null;',
           '  readonly rms: number | null;',
           '  /** 원본 팩과 저작자. CC0 라 표기 의무는 없으나 재검증을 위해 남긴다. */',
           '  readonly sourceName: string;',
           '  /** 원본 팩 안에서의 경로. 원본 대조용. */',
           '  readonly sourceRel: string;',
           '  readonly tags: readonly string[];',
           '};', '',
           'export const SE_CATALOG_LICENSE = "CC0-1.0" as const;',
           'export const SE_CATALOG_SOURCE_NAME = "CC0 효과음 카탈로그 (Kenney + OpenGameArt)" as const;', '',
           '/** 피커 그룹 순서. 카탈로그 등장 순서와 같다. */',
           'export const SE_CATALOG_CATEGORIES: readonly string[] = [']
    for c in cats:
        out.append('  %s,' % ts_str(c))
    out += ['];', '', 'export const SE_CATALOG: readonly SeCatalogEntry[] = [']
    for r in rows:
        out += ['  {',
                '    id: %s,' % ts_str(r['id']),
                '    title: %s,' % ts_str(r['title']),
                '    category: %s,' % ts_str(r['category']),
                '    baseName: %s,' % ts_str(r['baseName']),
                '    variant: %s,' % ('null' if r['variant'] is None else r['variant']),
                '    seconds: %s,' % r['seconds'],
                '    bytes: %s,' % r['bytes'],
                '    sha256: %s,' % ts_str(r['sha256']),
                '    codec: %s,' % ts_str(r['codec']),
                '    sampleRate: %s,' % r['sampleRate'],
                '    channels: %s,' % r['channels'],
                '    peak: %s,' % ('null' if r['peak'] is None else r['peak']),
                '    rms: %s,' % ('null' if r['rms'] is None else r['rms']),
                '    sourceName: %s,' % ts_str(r['sourceName']),
                '    sourceRel: %s,' % ts_str(r['sourceRel']),
                '    tags: [%s],' % ', '.join(ts_str(t) for t in r['tags']),
                '  },']
    out += ['];', '']
    catalog_path = os.path.join(REPO, 'src', 'assets', 'seCatalog.ts')
    open(catalog_path, 'w', encoding='utf-8', newline='\n').write('\n'.join(out))

    print('%d개 / 총 %.1f초' % (len(rows), total_seconds))
    for p in (runtime_path, catalog_path):
        print('  %-40s %8d B' % (os.path.relpath(p, REPO).replace(os.sep, '/'),
                                 os.path.getsize(p)))
    print('  카테고리 %d개: %s' % (len(cats), ' / '.join(cats)))


if __name__ == '__main__':
    main()
