export const M2_PARTIAL_EFFECT_DECLARATIONS = [
  {
    ids: [
      "m2-022-change-actor-name",
      "m2-023-change-actor-nickname",
      "m2-025-change-actor-faceset",
    ],
    supportedEffects: ["session actor-state recording"],
    unsupportedEffects: ["live native actor and database parity"],
  },
  {
    ids: [
      "m2-036-get-player-location",
      "m2-037-move-to-variable-location",
      "m2-038-get-on-off-vehicle",
      "m2-039-set-vehicle-location",
      "m2-040-set-event-location",
      "m2-041-swap-event-location",
      "m2-042-get-terrain-id",
      "m2-043-get-event-id",
      "m2-044-hide-screen",
      "m2-045-show-screen",
      "m2-063-memorize-current-bgm",
      "m2-064-play-memorized-bgm",
      "m2-068-change-tileset",
      "m2-069-change-parallax-back",
      "m2-070-set-encounter-rate",
      "m2-072-set-teleportation-point",
      "m2-073-teleportation-on-off",
      "m2-074-set-escape-location",
      "m2-075-change-escape-access",
      "m2-077-change-save-access",
      "m2-079-change-menu-access",
    ],
    supportedEffects: ["deterministic session and world-state recording"],
    unsupportedEffects: ["complete player-surface application"],
  },
  {
    ids: [
      "m2-076-open-save-menu",
      "m2-078-open-menu-screen",
      "m2-093-open-load-menu",
      "m2-094-exit-game",
      "m2-095-toggle-atb-wait-mode",
      "m2-096-toggle-fullscreen-mode",
      "m2-097-open-video-options",
    ],
    supportedEffects: ["host shell-action request"],
    unsupportedEffects: ["host UI completion"],
  },
  {
    ids: ["m2-085-end-event-processing"],
    supportedEffects: ["interpreter termination request"],
    unsupportedEffects: ["native command-shape parity"],
  },
  {
    ids: [
      "m2-026-change-vehicle-graphic",
      "m2-027-change-system-bgm",
      "m2-028-change-system-se",
      "m2-029-change-system-graphic",
      "m2-030-change-screen-transition",
      "m2-054-show-animation",
      "m2-055-show-animation",
      "m2-056-flash-event",
      "m2-066-play-movie",
    ],
    supportedEffects: ["safe fallback recording"],
    unsupportedEffects: ["player-visible media and system effect"],
  },
  {
    ids: [
      "m2-202-screen-effect",
      "m2-205-pathfind-move",
      "m2-206-wait-until",
      "m2-207-region-trigger",
      "m2-208-quest-objective",
      "m2-209-advanced-dialogue",
      "m2-210-sound-layer",
      "m2-211-weighted-branch",
      "m2-212-cutscene-control",
      "m2-213-checkpoint-save",
      "m2-214-ui-command",
      "m2-215-debug-log",
      "m2-216-evaluate-expression",
      "m2-217-data-query",
    ],
    supportedEffects: ["deterministic modern runtime-state mutation"],
    unsupportedEffects: ["end-to-end owner-surface completion"],
  },
] as const;
