# metadata for the v4 props: id, English name, Korean description, category, tags, placement rules, related (id, why),
# variants group, animation frames. Footprint / role grid / image size / overhang come from the images (build_meta.py).
def R(*pairs): return [dict(id=i,why=w) for i,w in pairs]
M={
 '쌍등 가로등':('lamp_double','Double street lamp','철 기둥 양팔에 등 두 개를 단 큰 가로등. 광장 네 모서리에 세운다.','street',['market','plaza'],['광장 모서리 칸','문 앞 2칸 금지'],R(('festoon','광장 조명 한 벌')),'lamp',None),
 '목 굽은 가로등':('lamp_crook','Crook street lamp','목이 굽은 철 기둥에 등 하나를 매단 가로등. 2칸 폭 큰길과 부두 옆 잔디 가장자리에 10칸 간격으로 세운다.','street',['street','harbour'],['길과 맞닿은 잔디 칸 (길 쪽이 앞)','다른 가로등과 10칸 이상','문 앞 2칸 금지'],R(('bench_wood','밤에 앉는 자리를 비춤')),'lamp',None),
 '나무 벤치':('bench_wood','Wooden bench','쇠다리에 나무 널을 댄 등받이 벤치. 광장·분수·우물 쉼터를 바라보게 둔다.','street',['plaza','park'],['광장·분수·우물 옆 3칸 안','앉는 면이 정면(아래)을 향함'],R(('fountain_small','앉아서 바라볼 것'),('well_roofed','쉼터 한 벌')),'bench',None),
 '주막 탁자':('table_mugs','Tavern table with mugs','맥주잔과 빵이 놓인 긴 탁자와 앞뒤 벤치. 여관 문 옆에만 둔다.','shop',['inn'],['여관 간판이 걸린 집 문 옆 1~2칸','문 앞 2칸 금지'],R(('sign_inn','여관임을 알리는 간판'),('parasol_table','여관 앞마당 한 벌')),'table',None),
 '파라솔 탁자':('parasol_table','Parasol table','줄무늬 파라솔을 꽂은 둥근 탁자. 여관·빵집 문 옆에 둔다.','shop',['inn','bakery'],['가게 문 옆','파라솔은 겹침층'],R(('sign_bakery','빵집 앞 자리'),('table_mugs','여관 앞마당 한 벌')),'table',None),
 '현자 석상':('statue_sage','Sage statue','지팡이 든 현자 석상과 받침대. 언덕 위 한 곳에 기념물로 하나만 둔다.','monument',['hill'],['넓은 길 가장자리 또는 광장, 지구마다 하나','윗 두 칸은 겹침층'],R(('planter_round','기념물 둘레 장식')),'statue',None),
 '기념 원주':('column_monument','Memorial column','금빛 구슬을 얹은 돌 원기둥. 성 앞마당에 하나 둔다.','monument',['castle'],['성 앞마당 판석 칸'],R(('flagpole','성 앞 의장 한 벌')),'statue',None),
 '작은 분수':('fountain_small','Small fountain','물줄기 하나가 솟는 둥근 돌 분수(움직임 4장). 신전 마당과 골목 광장에 둔다.','water',['plaza','temple'],['2×2 막힘, 둘레 1칸 비움'],R(('bench_wood','분수를 바라보는 자리')),'fountain',4),
 '물고기 연못 분수':('fish_pool','Fish pool fountain','물고기상이 물을 뿜는 긴 연못(움직임 4장). 항구 광장 한가운데에 하나.','water',['harbour'],['항구 광장 칸, 3×2 막힘'],R(('anchor_display','항구 광장 표지 한 벌'),('flagpole','광장 입구 의장')),'fountain',4),
 '긴 꽃상자':('flowerbox_long','Long flower box','꽃이 핀 긴 나무 화분 상자. 살림집 문 옆에 둔다.','planter',['residential'],['집 앞줄 문 옆, 문 칸 금지','2칸 폭 길 가장자리만'],R(('door_pots','같은 집 앞 장식 (둘 중 하나만)')),'planter',None),
 '둥근 돌 화분':('planter_round','Round stone planter','꽃을 심은 둥근 돌 화분. 계단 위·아래 양옆과 신전 마당에 짝으로 둔다.','planter',['stair','temple'],['계단 발치·꼭대기 양옆에 대칭으로'],R(('stair_rail','계단을 표시하는 한 벌')),'planter',None),
 '문간 화분 둘':('door_pots','Pair of door pots','꽃 핀 토분 두 개. 집이나 가게 문 바로 옆 칸에 둔다.','planter',['residential','shop'],['문 옆 칸 (문 앞 칸 금지)'],R(('flowerbox_long','같은 집 앞 장식 (둘 중 하나만)')),'planter',None),
 '화분 속 가로수':('tree_planter','Tree in a planter','돌 화분에 심은 가로수(칩셋 덤불 수관). 큰길(33~34줄) 가에 8칸 간격으로 심는다.','planter',['street'],['큰길과 맞닿은 잔디 칸','아래 1줄 막힘, 수관 2줄은 겹침층'],R(('lamp_crook','큰길 가로 한 벌')),'tree',None),
 '다듬은 산울타리':('hedge','Clipped hedge','네모로 다듬은 산울타리 3칸 길이. 우물 쉼터 뒤를 두른다.','planter',['park'],['쉼터 뒤쪽 가장자리'],R(('well_roofed','쉼터의 뒤 담')),'hedge',None),
 '입간판 (분필)':('sandwich_board','Chalk sandwich board','분필로 쓴 A자 입간판. 빵집·약방·서점 등 가게 문 옆에 둔다.','shop',['shop'],['가게 문 옆 1칸'],R(('sign_bakery','같은 가게 표시'),('sign_pharm','같은 가게 표시')),'sign',None),
 '깃대 (나부낌)':('flagpole','Flagpole with pennant','제비꼬리 깃발이 나부끼는 깃대(움직임 4장). 광장 입구와 성 앞마당에 쌍으로 세운다.','monument',['market','harbour','castle'],['광장 입구 양쪽 대칭','아래 1줄 막힘'],R(('column_monument','성 앞 의장'),('fish_pool','항구 광장 입구')),'flag',4),
 '노점: 치즈·고기':('stall_cheese_meat','Stall: cheese & meat','파란 차양 아래 치즈 바퀴와 매단 고기를 파는 노점.','market',['market'],['시장 광장 칸만','아래 2줄 막힘, 차양은 겹침층','앞 1칸 손님 자리'],R(('stall_veg','시장 줄')),'stall',None),
 '노점: 옹기·술병':('stall_jug_bottle','Stall: jugs & bottles','빨간 차양 아래 옹기와 유리병을 파는 노점.','market',['market'],['시장 광장 칸만','앞 1칸 손님 자리'],R(('stall_cheese_meat','시장 줄')),'stall',None),
 '노점: 약초·꽃':('stall_herb_flower','Stall: herbs & flowers','약초 다발과 꽃을 파는 노점.','market',['market'],['시장 광장 칸만'],R(('flower_cart','꽃 파는 자리 옆')),'stall',None),
 '노점: 호박·양배추':('stall_veg','Stall: pumpkins & cabbages','호박과 양배추를 쌓아 파는 3칸 노점.','market',['market','harbour'],['시장·항구 광장 칸만'],R(('veg_cart','채소 파는 자리 옆')),'stall',None),
 '꽃 수레':('flower_cart','Flower cart','꽃 양동이 셋을 실은 손수레. 시장 광장 안에 둔다.','market',['market'],['광장 칸'],R(('stall_herb_flower','꽃 파는 자리')),'cart',None),
 '채소 손수레':('veg_cart','Vegetable handcart','채소를 수북이 실은 손수레. 시장 광장과 청과상 앞에 둔다.','market',['market','grocer'],['광장 또는 청과상 문 옆'],R(('sign_grocer','청과상 표시'),('crate_apple','같은 물건')),'cart',None),
 '과일 상자':('crate_apple','Open crate of apples','사과가 담긴 나무 상자. 청과상 문 옆과 시장에 둔다.','shop',['grocer','market'],['가게 문 옆'],R(('sign_grocer','청과상 표시')),'crate',None),
 '양배추 상자':('crate_cabbage','Open crate of cabbages','양배추가 담긴 나무 상자. 청과상 문 옆과 시장에 둔다.','shop',['grocer','market'],['가게 문 옆'],R(('sign_grocer','청과상 표시')),'crate',None),
 '생선 상자':('crate_fish','Open crate of fish','얼음 위 생선이 담긴 상자. 생선 가게 문 옆에 둔다.','shop',['fish'],['생선 가게 문 옆'],R(('sign_fish','생선 가게 표시')),'crate',None),
 '통·상자·자루 더미':('goods_pile','Barrel, crate & sack pile','술통·나무 상자·곡식 자루 짐 더미. 부두 물가, 창고·대장간·푸줏간 옆에 둔다.','storage',['harbour','warehouse'],['건물 옆 또는 부두 물가 줄'],R(('crane','부리는 짐')),'pile',None),
 '빨래 건조대':('laundry_rack','Laundry drying rack','빨래를 넌 두 기둥 건조대. 살림집 바로 옆 잔디에 띄엄띄엄 둔다.','residential',['residential'],['집 옆벽에 붙은 칸','다른 건조대와 16칸 이상'],R(('laundry_line','주거지 표시')),'laundry',None),
 '골목 빨랫줄':('laundry_line','Laundry line across an alley','두 집 벽 사이 1~3칸 틈 위에 걸린 빨랫줄. 발자국 없는 겹침층.','residential',['residential'],['같은 줄에 선 서로 다른 두 집 사이','통행 안 막음 (공중)'],R(('laundry_rack','주거지 표시')),'laundry',None),
 '등불 줄 (깜빡임)':('festoon','Festoon lanterns','시장 광장 위를 가로지르는 등불 줄(깜빡임 6장). 발자국 없는 겹침층.','street',['market'],['시장 광장 북쪽 한 줄'],R(('lamp_double','광장 조명 한 벌')),'lamp',6),
 '계선주':('mooring_bollard','Mooring bollard','밧줄이 감긴 무쇠 계선주. 부두 물가 줄과 잔교 머리 양옆에 둔다.','harbour',['harbour'],['물과 맞닿은 부두 줄','잔교 머리 양옆'],R(('pier','배를 매는 곳')),'bollard',None),
 '그물 건조대':('net_rack','Net drying rack','찌 달린 그물을 넌 건조대. 부두와 항구 광장에 둔다.','harbour',['harbour'],['부두 물가 줄 또는 항구 광장'],R(('fish_crates','어부의 부두')),'net',None),
 '닻 전시대':('anchor_display','Anchor on a stand','나무 받침에 세운 큰 닻. 항구 광장 표지물로 하나.','harbour',['harbour'],['항구 광장, 하나만'],R(('fish_pool','항구 광장 한 벌')),'monument',None),
 '부두 기중기':('crane','Treadwheel dock crane','쳇바퀴와 비스듬한 붐으로 짐 상자를 매단 부두 기중기(갈고리 흔들림 4장). 창고 앞 부두에 하나.','harbour',['harbour','warehouse'],['창고 앞 부두 물가 줄, 아래 1줄 막힘','붐·짐은 겹침층'],R(('goods_pile','부리는 짐')),'crane',4),
 '얼음 생선 궤짝':('fish_crates','Fish crates on ice','얼음 위 생선 궤짝 두 개. 생선 가게 앞과 부두에 둔다.','harbour',['harbour','fish'],['부두 물가 줄 또는 생선 가게 문 옆'],R(('sign_fish','생선 가게 표시'),('net_rack','어부의 부두')),'crate',None),
 '생선 통':('fish_barrel','Fish barrel','생선 꼬리가 삐져나온 나무 통. 생선 가게 앞에 둔다.','shop',['fish','harbour'],['가게 문 옆'],R(('sign_fish','생선 가게 표시')),'barrel',None),
 '빵 진열대':('bread_rack','Bread rack','빵을 얹은 3단 진열대. 빵집 문 옆에 둔다.','shop',['bakery'],['빵집 문 옆'],R(('sign_bakery','빵집 표시')),'rack',None),
 '약초 걸이·절구':('herb_rack','Herb rack & mortar','약초 다발 걸이와 절구. 약방 문 옆에 둔다.','shop',['pharm'],['약방 문 옆'],R(('sign_pharm','약방 표시')),'rack',None),
 '옷감 걸이':('cloth_stand','Cloth stand','색 옷감 네 필을 건 틀. 재단사 문 옆에 둔다.','shop',['tailor'],['재단사 문 옆'],R(('sign_tailor','재단사 표시')),'rack',None),
 '칼 꽂은 통':('sword_barrel','Barrel of swords','칼 세 자루를 꽂은 통. 대장간 문 옆에 둔다.','shop',['smith'],['대장간 문 옆'],R(('sign_smith','대장간 표시')),'barrel',None),
 '계단 난간':('stair_rail','Stair railing','계단 양옆을 따라 내려가는 쇠 난간. 모든 계단 양쪽에 겹침층으로 붙는다.','street',['stair'],['계단 좌우 가장자리 (계단은 통행)'],R(('planter_round','계단 발치 장식')),'rail',None),
 '돌 우물 (지붕)':('well_roofed','Roofed stone well','지붕 얹은 돌 우물(기존 채택 조각). 뒤에 산울타리, 옆에 꽃밭·벤치를 둔 동네 쉼터의 중심.','water',['residential','park'],['길에서 1칸 안쪽 잔디','아래 2줄 막힘','앞(아래)에 길이 닿아야 함'],R(('bench_wood','쉼터 자리'),('hedge','쉼터 뒤 담')),'well',None),
 '꽃밭':('flowerbed','Flower bed','작은 꽃밭(기존 조각). 우물 쉼터 옆에 둔다.','planter',['park'],['쉼터 옆'],R(('well_roofed','쉼터 한 벌')),'planter',None),
}
TRADE_EN={'bakery':'bakery','fish':'fishmonger','pharm':'apothecary','smith':'smithy','inn':'inn','tailor':'tailor','jewel':'jeweller','butcher':'butcher','grocer':'greengrocer','books':'bookshop'}
TRADE_REL={'bakery':['bread_rack','sandwich_board','parasol_table'],'fish':['crate_fish','fish_crates','fish_barrel'],'pharm':['herb_rack','sandwich_board'],
 'smith':['sword_barrel','goods_pile'],'inn':['table_mugs','parasol_table','sandwich_board'],'tailor':['cloth_stand','door_pots'],'jewel':['door_pots','sandwich_board'],
 'butcher':['goods_pile','sandwich_board'],'grocer':['crate_apple','crate_cabbage','veg_cart'],'books':['sandwich_board','planter_round']}
