import { nativeManifestEntry } from "../specTypes";

export const STATE_SPECS = {
  setSwitch: nativeManifestEntry("state", { kind: "setSwitch", switchId: "switch_contract", value: true }),
  setVariable: nativeManifestEntry("state", {
    kind: "setVariable",
    variableId: "variable_contract",
    op: "=",
    value: 7,
  }),
  timer: nativeManifestEntry("state", { kind: "timer", action: "set", seconds: 30, timerId: "timer1" }),
  advanceTime: nativeManifestEntry("state", { kind: "advanceTime", minutes: 15 }),
  advanceCropGrowth: nativeManifestEntry("state", { kind: "advanceCropGrowth", days: 1 }),
  setTime: nativeManifestEntry("state", { kind: "setTime", hour: 9, minute: 30 }),
  sleepUntilMorning: nativeManifestEntry("state", { kind: "sleepUntilMorning" }),
  learnSkill: nativeManifestEntry("state", {
    kind: "learnSkill",
    actorId: "actor_contract",
    skillId: "skill_contract",
  }),
  changeExp: nativeManifestEntry("state", { kind: "changeExp", actorId: "actor_contract", op: "+=", amount: 10 }),
  changeLevel: nativeManifestEntry("state", { kind: "changeLevel", actorId: "actor_contract", op: "+=", amount: 1 }),
  // 생활 스킬 XP — kind 만 추가되고 매니페스트 엔트리가 누락돼 있었다.
  changeLifeSkillExp: nativeManifestEntry("state", { kind: "changeLifeSkillExp", skillId: "skill_farming", op: "+=", amount: 10 }),
  promoteActor: nativeManifestEntry("state", {
    kind: "promoteActor",
    actorId: "actor_contract",
    toClassId: "class_contract",
    successBranch: [],
    failureBranch: [],
  }),
  changeEquipment: nativeManifestEntry("state", {
    kind: "changeEquipment",
    actorId: "actor_contract",
    slot: "weapon",
    equipmentId: "item_contract",
  }),
  changeActorHp: nativeManifestEntry("state", { kind: "changeActorHp", actorId: "actor_contract", op: "-=", amount: 5 }),
  changeActorMp: nativeManifestEntry("state", { kind: "changeActorMp", actorId: "actor_contract", op: "-=", amount: 3 }),
  recoverAll: nativeManifestEntry("state", { kind: "recoverAll", actorId: "actor_contract" }),
  changeGold: nativeManifestEntry("state", { kind: "changeGold", op: "+=", amount: 10 }),
  changeItem: nativeManifestEntry("state", { kind: "changeItem", itemId: "item_contract", op: "+=", amount: 1 }),
  craftRecipe: nativeManifestEntry("state", { kind: "craftRecipe", recipeId: "recipe_contract" }),
  applyItemUpgrade: nativeManifestEntry("state", { kind: "applyItemUpgrade", upgradeId: "upgrade_contract" }),
  equipTool: nativeManifestEntry("state", { kind: "equipTool", itemId: "item_contract" }),
  changeFriendship: nativeManifestEntry("state", { kind: "changeFriendship", npcKey: "npc_contract", delta: 5 }),
  getFriendship: nativeManifestEntry("state", {
    kind: "getFriendship",
    npcKey: "npc_contract",
    variableId: "variable_contract",
  }),
  changeParty: nativeManifestEntry("state", { kind: "changeParty", actorId: "actor_contract", action: "add" }),
  giveMonster: nativeManifestEntry("state", { kind: "giveMonster", speciesId: "species_contract", level: 5 }),
  moveMonster: nativeManifestEntry("state", {
    kind: "moveMonster",
    instanceId: "monster_contract",
    to: "party",
  }),
  evolveMonster: nativeManifestEntry("state", {
    kind: "evolveMonster",
    instanceId: "monster_contract",
    toSpeciesId: "species_evolved_contract",
    successBranch: [],
    failureBranch: [],
  }),
  addFollower: nativeManifestEntry("state", {
    kind: "addFollower",
    actorId: "actor_contract",
    name: "Contract follower",
  }),
  removeFollower: nativeManifestEntry("state", { kind: "removeFollower", name: "Contract follower" }),
  setFlag: nativeManifestEntry("state", { kind: "setFlag", flag: "flag_contract", value: true }),
  setSelfSwitch: nativeManifestEntry("state", { kind: "setSelfSwitch", key: "A", value: true }),
  checkpointSave: nativeManifestEntry("state", { kind: "checkpointSave" }),
} as const;
