from write_rows import write

write('poses/idle_b.pxgrid', '''
.
.
.
.
.
.
.
.
.........................oooooooooo
........................ohhkkkkkkkko
........................ohkkkkkkkkko
........................ohkkkkkkkkko
........................ohkkkkkkkkko
........................okkkkkkkkkko
.......................ohhkkkkkkkkkko
..................oohhhhhhhkkkkkkkkkkkkkkkoo
................ohkkkkkkkkkkkkkkkkkkkkkkkkkko
..................ookkkkkkkkoooooooooohhoo
......................okhhpuuuuuuttttko.......................w
......................ohkpuuuuuuuuutttko.....................w
......................okkpppuuupppuuttko....................wv
......................okkpuuuuuuuuuuttko...................wmv
......................okkpkeuuukepuuttto.................wmmv
......................okkpwkuuuwekutuuto................wmmv
......................okkptuuuuuuuutttpo...............wmv
.......................okpttuuuuuttttpo..............wmmv
.........................kpttuuupettpo..............wmmv
..........................optttttppo...............wmv
........................okkoptttpo...............wmmv
......................ookocllutplco..............wmv
....................osclllllcppillco...........wmmv
...................osclllllcijidillco.........wmmv
..................oscllllccijjiddicccso......wmv
.................oscllllccsijiiddiiccso....wmmv
.................ocllllccssijidddiiccso..hwmmv
................osclllccsssiidddiiccsso.hmmv
................ocllcccsssiidddiicclco.hjvj
.................ocllccssiiddiclllccpuueoh
.................osccccsiiddiclllccpuutko
..................osccccscccllcccsootpo
....................osccccssccididdccso
......................oscirRRRRrrddcso
......................oscirrRRrrrRrdco
......................osclciidddirRrptpoho
.....................oscllciidddirrdtutokho
.....................oscllciidddiddiptpookho
.....................oscllciidddidiiccso.okho
....................osclllcijidddiicccso..okho
....................oscllcijjiiddiiccccso..oko
...................osclllcijjiiddiicclcso...oko
...................oscllccijjiiddiicclcso....oo
..................osclllcijjiiiddiicclcso
..................oscllccijjiiiddiicclcso
...................oscclccijiiidddicclccso
....................osccccciiidddicclccso
.....................osccccciiddiiccccso
......................osccccssiissssoo
......................oossssoooookhhkko
.....................ohhhkko.....ohhkkko
.....................okkkkko....okkkkkkko
.....................ooooooo....ooooooooo
.
.
.
''')

write('poses/idle_c.pxgrid', '''
.
.
.
.
.
.
.
.
.........................oooooooooo
........................ohhkkkkkkkko
........................ohkkkkkkkkko
........................ohkkkkkkkkko
........................ohkkkkkkkkko
........................okkkkkkkkkko
.......................ohhkkkkkkkkkko
..................oohhhhhhhkkkkkkkkkkkkkkkoo
................ohkkkkkkkkkkkkkkkkkkkkkkkkkko
..................ookkkkkkkkoooooooooohhoo
......................okhhpuuuuuuttttko.......................w
......................ohkpuuuuuuuuutttko.....................w
......................okkpppuuupppuuttko....................wv
......................okkpuuuuuuuuuuttko...................wmv
......................okkpkeuuukepuuttto.................wmmv
......................okkpwkuuuwekutuuto................wmmv
......................okkptuuuuuuuutttpo...............wmv
.......................okpttuuuuuttttpo..............wmmv
.........................kpttuuupettpo..............wmmv
..........................optttttppo...............wmv
.........................okoptttpo...............wmmv
........................okcllutplco............wmmv
......................osclllcppillco...........wmv
.....................osclllcijidillco........wmmv
....................osclllcijjiddiccso......wmmv
...................osclllccijiiddiiccso....wmv
..................osclllccsijidddiiccso..hwmmv
..................ocllccsssiidddiiccsso..hmmv
..................ocllccssiidddiicclco..hjvj
...................ocllcsiiddiclllcpuueoho
...................oscccsiiddicllcpuutkoo
....................osccscccllcccsoptpo
.....................oscccssccididdccso
......................oscirRRRRrrddcso
......................oscirrRRrrrRrdco
......................osclciidddirRrptpoho
.....................oscllciidddirrdtutokho
.....................oscllciidddiddiptpookho
.....................oscllciidddidiicso..okho
.....................oscllcijidddiicccso..okho
.....................oscllcijjiiddiicccso..oko
.....................osclccijjiiddiicclcso..oko
....................oscllccijjiiddiicclcso...oo
....................oscllcijjiiiddiicclcso
....................osclccijjiiiddiicclcso
....................oscclcijiiidddicclccso
.....................oscccciiidddicclccso
......................oscccciiddiiccccso
......................osccccssiissssoo
......................oossssoooookhhkko
.....................ohhhkko.....ohhkkko
.....................okkkkko....okkkkkkko
.....................ooooooo....ooooooooo
.
.
.
''')

write('poses/windup.pxgrid', '''
.
.
.
.
.
.
.
.
.
.
........................oooooooooo
.......................ohhkkkkkkkko
.......................ohkkkkkkkkko
.......................ohkkkkkkkkko
.......................ohkkkkkkkkko
.......................okkkkkkkkkko
......................ohhkkkkkkkkkko
.................oohhhhhhhkkkkkkkkkkkkkkoo
...............ohkkkkkkkkkkkkkkkkkkkkkkkkko
.................ookkkkkkkkoooooooooohhoo
.....................okhhpuuuuuuttttko
.....................ohkpuuuuuuuuutttko
.....................okkpppuuupppuuttko
.....................okkpuuuuuuuuuuttko
.....................okkpkeuuukepuuttto
.....................okkpwkuuuwekutuuto
.....................okkptuuuuuuuutttpo
......................okpttuuuuuttttpo
........................kpttuuupettpo
.........................optttttppo
.......................okkoptttpo
.....................oosclllutplco
....................oscllllcppillco
...................oscllllccijidillco
..................osclllcccsijjiddiccso
.................osclllcccssijiiddiiccso
.................oclllccsssiijidddiiccso
.................ocllccssiiddiclllcclcso
..................ocllcsiiddicllllccsso
...................osccsiiidiclllcccsso
....................oscccsscllcccspuupo
......................osccssccidipuutpeo
.......................oscirRRRRrpupkoho
.......................oscirrRRrrRrptohhko
......................oscllciidddirtuueohkko
.....................osclllciidddirpttko.hkko
....................osclllcciidddiddpo...hokko
....................osclllccijiiddiicso...hokko
...................osclllccijjiiddiicccso...hoko
..................osclllccijjiiiddiiccccso...hoo
.................osclllccijjiiiddiicclccso
................osclllccijjiidddiiccllcso
.................osclccijjiidddiiccclllccso
..................osccijjiiddddiiccclllccso
...................oscijjiidddiiccssscccco
....................osiiidddoooscclcssso
.....................osssooo...oosccsso
....................ohhhkko.....ohhhkko
...................ohhhkkko.....ohhkkkko
...................okkkkkko.....okkkkkkko
...................oooooooo.....ooooooooo
.
.
.
''')

write('poses/move.pxgrid', '''
.
.
.
.
.
.
.
.
.
...........................ooooooooo
..........................ohhkkkkkkko
..........................ohkkkkkkkko
..........................ohkkkkkkkko
..........................ohkkkkkkkko
.........................ohhkkkkkkkkko
.....................oohhhhhkkkkkkkkkkkkoo
..................oohhkkkkkkkkkkkkkkkkkkkkko
....................ookkkkkkkkkkooooohhhoo
........................okhhpuuuuuuttttko
........................ohkpuuuuuuuuutttko
........................okkpppuuupppuuttko
........................okkpuuuuuuuuuuttko
........................okkpkeuuukepuuttto
........................okkpwkuuuwekutuuto
........................okkptuuuuuuuutttpo
.........................okpttuuuuuttttpo
...........................kpttuuupettpo
............................optttttppo
.........................okkoptttpo
.......................oscllllutplco
.....................osclllllcppillco
....................oscllllccijidillccoo
..................oosclllcccsijjiddiccclso
.................osclllcccssijiiddiicccllco
................osclllccsssiijidddiicclllco
...............oscllccssssiiddddiicllccsco
..............oscllccssiiddicllcccsclllccso
...............osccccsiiddicllccsoscllccsso
................osccsiiddicllccso.osclccsso
.................osccssccclccsso...opuuttpo
...................oscccsscciddddo.opuupkoho
......................oscirRRRRrrdo.otppohhko
......................oscirrRRrrrRro...ohhhko
.....................osclciidddirRrdo....hokko
....................oscllciidddirrddco....hokko
...................osclllciidddiddicco.....hokko
..................osclllccijidddiicclco.....hokko
................osclllcccijjiiddiiccllco.....hoko
..............oosclllcccijjiiddiiccllllco......hoo
.............oscllllccijjiiddiicclllllcco
............oscllllccijjiiddiiccllllllcso
............oscllccijjiidddiiccllllccccso
.............osccijjiiddddiicclllccccssco
..............osijjiiddddiiiccclccssicco
...............osiiddddoooscccsssciicco
................ossssoo...osccssciicco
..............oohhhkko......osssciicco
.............ohhhkkko.........oshhhkko
............ohhkkkko.........ohhhkkkko
............okkkkkko........okkkkkkkkko
............oooooooo........ooooooooooo
.
.
.
''')

write('poses/attack.pxgrid', '''
.
.
.
.
.
.
.
.
.
.
.
.
.....................oooooooooo
....................ohhkkkkkkkko
....................ohkkkkkkkkko
....................ohkkkkkkkkko
....................ohkkkkkkkkko
....................okkkkkkkkkko
...................ohhkkkkkkkkkko
...............oohhhhhhhkkkkkkkkkkkkkoo
.............ohkkkkkkkkkkkkkkkkkkkkkkkkko
...............ookkkkkkkkoooooooooohhoo
...................okhhpuuuuuuttttko
...................ohkpuuuuuuuuutttko
...................okkpppuuupppuuttko
...................okkpuuuuuuuuuuttko
...................okkpkeuuukepuuttto
...................okkpwkuuuwekutuuto
...................okkptuuuuuuuutttpo
....................okpttuuuuuttttpo
......................kpttuuupettpo
....................ookoptttttppo
..................oscllllutttplco
.................oscllllccppilllccoo
................osclllccijidilllllccco.........wwwwwwwwwwwwwwwww
...............oscllccsijjiddiccllllcccoh..wwwwmmmmmmmmmmmmmmmv
...............ocllccssijiiddiiccllcccpuuuehmmmmmmmmmmmmmmmmmmvv
................ocllcssijidddiicclcccpuuutkhvvvvvvvvvvvvvvvvv
.................occcssiiddddicclcccssotppoho
..................osccsiiddddiclccssso..ooo
...................osccssccidddiccso
.....................oscirRRRRrrdcso
.....................oscirrRRrrrRrdo
....................oscllciidddirRrdco
...................osclllciidddirrddcco
..................osclllcciidddiddiicco
.................osclllcccijidddiiccllco
................osclllccijjiiddiiccllllco
...............osclllccijjiidddiiccllllcco
..............osclllccijjiiddddiiiccllllcso
.............osclllccijjiiddddooiccllllccso
............oscllccijjiiddddoo..osclllccsso
...........oscllccijjiiddddoo....oscllccssco
...........osclccijjiidddoo.......oscllccsco
............osccijjiiddoo.........osclccsco
.............osijjiidoo............osccsso
..............ossiio...............osssso
.............ohhhkko...............ohhhkko
............ohhhkkko...............ohhkkkko
...........okkkkkkko..............okkkkkkkkko
...........ooooooooo..............ooooooooooo
.
.
.
''')

write('poses/recover.pxgrid', '''
.
.
.
.
.
.
.
.
.
........................oooooooooo
.......................ohhkkkkkkkko
.......................ohkkkkkkkkko
.......................ohkkkkkkkkko
.......................ohkkkkkkkkko
.......................okkkkkkkkkko
......................ohhkkkkkkkkkko
.................oohhhhhhhkkkkkkkkkkkkkkkoo
...............ohkkkkkkkkkkkkkkkkkkkkkkkkkko
.................ookkkkkkkkoooooooooohhoo
.....................okhhpuuuuuuttttko
.....................ohkpuuuuuuuuutttko
.....................okkpppuuupppuuttko
.....................okkpuuuuuuuuuuttko
.....................okkpkeuuukepuuttto
.....................okkpwkuuuwekutuuto
.....................okkptuuuuuuuutttpo
......................okpttuuuuuttttpo
........................kpttuuupettpo
.........................optttttppo
.......................okkoptttpo
.....................oscllllutplco
....................oscllllcppillco
...................osclllccijidillco
..................osclllccsijjiddiccso
..................oclllccssijiiddiiccco
.................oscllccsssiijidddiicclco
.................ocllccsssiidddiicclllco
..................ocllcssiiddiclllccclco
...................osccsiiddicllcccclcso
....................osccscccllcccssclcso
.....................oscccssccidddisccso
......................oscirRRRRrrddcpuupo
......................oscirrRRrrrRrpuutpeo
.....................oscllciidddirRrtppkhh
....................osclllciidddirrddoo.hvm
...................osclllcciidddiddiicso.vmww
...................osclllccijidddiicclcso.vmmw
..................osclllccijjiiddiicclccso.vmmw
..................oscllccijjiiddiicclllccso.vmww
.................osclllccijjiiddiicclllccso..vmmw
.................oscllccijjiiddiiccllllccso...vmmw
................osclllccijjiiddiiccllllccso....vmw
.................osclccijjiidddiicclllccso......vmww
..................osccijjiiddddiiccllccso.......vmmw
...................oscijjiidddiicclccsso.........vmmw
....................osiiidddoooscclcssso..........vmw
.....................osssooo...oosccsso............vw
....................ohhhkko.....ohhhkko............w
...................ohhhkkko.....ohhkkkko
...................okkkkkko.....okkkkkkko
...................oooooooo.....ooooooooo
.
.
.
''')

write('poses/hit.pxgrid', '''
.
.
.
.
.
.
.
.
.
....................oooooooooo
...................ohhkkkkkkkko
...................ohkkkkkkkkko
...................ohkkkkkkkkko
...................ohkkkkkkkkko
...................okkkkkkkkkko
..................ohhkkkkkkkkkko
.............oohhhhhhhkkkkkkkkkkkkkkoo
...........ohkkkkkkkkkkkkkkkkkkkkkkkkko
.............ookkkkkkkkoooooooooohhoo
.................okhhpuuuuuuttttko
.................ohkpuuuuuuuuutttko
.................okkppuupuuuppuuttko
.................okkpuuuuuuuuuuttko
.................okkpkeuuukepuuttto
.................okkptwkuuuwekututo
.................okkpttuuuuuuuutttpo
..................okpttuuuppttttpo
....................kpttuuewettpo
.....................optttttppo
..................ookkoptttpo
................osclllllutplco
..............osclllllccppillco
.............oscllllccsijidillcco
............osclllcccssijjiddiccco
............oclllccsssiijiiddiicclco
.............ocllccsssiijidddiiccllco
..............ocllcsssiiddddicclllccco
...............osccsiiddddiclllcclllcco
................osccsiiiddicllcccscllcso
..................osccsscllcccso.osclcso
....................osccsscciddo..opuuttpo
......................oscirRRRRro.opuutpeo
......................oscirrRRrrRrotppkhh
.....................oscllciidddirRroo.hvm
....................osclllciidddirrddo..vmww
...................osclllcciidddiddiicco.vmmw
..................osclllccijidddiiccllco..vmmw
.................osclllccijjiiddiicclllco...vmww
................osclllccijjiidddiiccllcso....vmmw
................oscllccijjiiddddiiccllccso....vmmw
.................osccijjiiddddiiccclllccso.....vmw
..................osijjiiddddiiicclllccso......vmww
...................osiidddoooscccclllccso.......vmmw
....................osssoo...osccclllcso........vmmw
.....................ossso...osccclccso..........vmw
....................ohhhkko...oscccssso...........vw
...................ohhhkkko....ossssso............w
...................okkkkkko....ohhhkko
...................okkkkkko...ohhkkkko
...................okkkkkko..okkkkkkkko
...................oooooooo..oooooooooo
.
.
.
''')

write('poses/dead.pxgrid', '''
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.....................ooooooo
...................ookhhhhhkkko
..................okhhhkkkkkkkkko
.................okhhkkpuuuuttttko
.................okhkpuuuuuuuutttko
.................okkpuuuuuuuuutttko...oooo
.................okkpueeeuuueepttto..oscllco
..................okptuuuuuuuutttpoosclllcco
.........ooo.......okpttuuupttttposcllllcccso
........ohhko.......okpttttttttposclllccsiicso...oooo
.......ohhkkko........opptttppposcllccsiiddicso.oscccco
......ohhkkkkko.........oooplcllllccsiidddiccsoscllccco
.....ohhkkkkkkko.........osclllcccssiidddirRRRRrcllccso
.....ohkkkkkkkkko.......osclllccssiiidddirRRrrrciicccso
.....okkkkkkkkkko.......ocllcccssiiidddicccciiddiicccsso
....ohhkkkkkkkkkko.......ocllcccssiidddicccciiddiicccsso
...ohhkkkkkkkkkkkkoo......oscllccssiiiddicccllcciiiccsso
..ohkkkkkkkkkkkkkkkkkoo....oscllcccsiidicccllccssiicso
...ookkkkkkkkkkkkkkkkkko....osccclccscccccccsooshhhkko
.....ooooooohhhhhhooooo........oscccclcpuuttpeohhkkkko
................................oosssoptppko.okkkkkkko
.................................ooo..hhjvvvvmmmmmmmmmmmmmmwwww
.
.
.
''')
