from write_rows import write

write('actions/skill_a.pxgrid', '''
.
.
.
.
.
.
.
.
.
.
..........................oooooooooo
.........................ohhkkkkkkkko
.........................ohkkkkkkkkko
.........................ohkkkkkkkkko
.........................ohkkkkkkkkko
.........................okkkkkkkkkko
........................ohhkkkkkkkkkko
...................oohhhhhhhkkkkkkkkkkkkkkoo
.................ohkkkkkkkkkkkkkkkkkkkkkkkkko
...................ookkkkkkkkoooooooooohhoo
.......................okhhpuuuuuuttttko
.......................ohkpuuuuuuuuutttko
.......................okkpppuuupppuuttko
.......................okkpuuuuuuuuuuttko
.......................okkpkeuuukepuuttto
.......................okkpwkuuuwekutuuto
.......................okkptuuuuuuuutttpo
........................okpttuuuuuttttpo
..........................kpttuuupettpo
...........................optttttppo
.........................okkoptttpo
.......................oscllllutplco
.....................ooscllllcppillco
....................oscllllccijidillco
...................osclllcccsijjiddiccso
..................osclllcccssijiiddiiccso
..................oclllccsssiijidddiiccco
.................oscllccsssiidddiicclllcco
.................ocllccssiiddiclllcclllcco
..................ocllcsiiddiclllccssllcco
...................osccsiiddiclllccsssccso
....................oscccsccllcccsossccso
.....................oscccssccidddopuupo
......................oscirRRRRrrdpuutpo
......................opuuttpirrRRrRrptpoho
.....................hpuutpeocllciiddirtuoho
...................hjmptpkooscllciidddirppoho
................wmwmmvh...oscllciidddiddiicoko
..............wmwmmv.....osclllccijidddiiccsohko
...........mwwmmmv......osclllccijjiiddiicccsohko
.........mwwwmmv.......osclllccijjiiddiicclccsoho
.......mwwmmmv........osclllccijjiiddiicclllccso
.....mwmmmmv.........osclllccijjiiddiiccllllccso
....wmwmv............osclccijjiidddiiccllllccso
...mmwwm..............osccijjiiddddiicclllccso
....mvm................oscijjiidddiiccllccsso
......v.................osiiidddoooscclcssso
.........................osssooo...oosccsso
........................ohhhkko.....ohhhkko
.......................okkkkkko....okkkkkkko
.......................oooooooo....ooooooooo
.
.
.
''')

write('actions/skill_b.pxgrid', '''
.
.
.
.
.
.
.
.
.
.
..........................oooooooooo
.........................ohhkkkkkkkko
.........................ohkkkkkkkkko
.........................ohkkkkkkkkko
.........................ohkkkkkkkkko............mw
.........................okkkkkkkkkko..............mmww
........................ohhkkkkkkkkkko..............vmmww
...................oohhhhhhhkkkkkkkkkkkkkkoo..........vmmww
.................ohkkkkkkkkkkkkkkkkkkkkkkkkko...........vmmww
...................ookkkkkkkkoooooooooohhoo..............vmmww
.......................okhhpuuuuuuttttko..................vmmww
.......................ohkpuuuuuuuuutttko.................vmmww
.......................okkpppuuupppuuttko..................vmmw
.......................okkpuuuuuuuuuuttko..................vmmw
.......................okkpkeuuukepuuttto..................vmmw
.......................okkpwkuuuwekutuuto..................vmmw
.......................okkptuuuuuuuutttpo..................vmmw
........................okpttuuuuuttttpo..............wmmmmmmww
..........................kpttuuupettpo.............wmm....vmmw
...........................optttttppo..............wmmv...mmmww
.........................okkoptttpo...............wmmv.mmmmmmww
.......................oscllllutplco.............wmmv...vmmmmww
.....................osclllllcppillco...........wmmv.....vmmmww
....................oscllllccijidillccoo.......wmmv......vmmmww
...................osclllcccsijjiddiccllcso...wmmv.......vmmmww
..................osclllccssijiiddiiccllccso.hwmmv......vmmmww
.................osclllccsssiijidddiiclllcpuueoh.......vmmmww
.................ocllccsssiiddddiicllcccpuuutko......vmmmww
..................ocllcssiiddicllcccclcsootpo......vmmmww
...................osccsiiddicllcccsccso..........vmmmww
....................osccssccclccssciiddo.........vmmmww
......................oscirRRRRrrddccso........vmmmww
......................oscirrRRrrrRrddco.......vmmmww
.....................oscllciidddirRrddco.....vmmmww
....................osclllciidddirrddiicco..vmmmww
...................osclllcciidddiddiicclco.vmmww
..................osclllcccijidddiiccllccovmmww
.................osclllccijjiiddiicclllccsovmw
................osclllccijjiidddiiccllllccso
...............osclllccijjiiddddiiiccllllccso
..............oscllccijjiiddddooicclllllccsso
.............oscllccijjiiddddoo.oscllllccssco
.............osclccijjiidddoo....osclllccssco
..............osccijjiiddoo......osclllccsco
...............osijjiidoo........oscllccsco
................ossiio...........osclccso
...............ohhhkko............osssso
..............ohhhkkko............ohhhkko
.............ohhkkkko............ohhhkkkko
.............okkkkkko..........okkkkkkkkkko
.............oooooooo..........oooooooooooo
.
.
.
''')

write('actions/skill_c.pxgrid', '''
.
.
.
.
.
.
.
.
.
........................oooooooooo
.......................ohhkkkkkkkko
.......................ohkkkkkkkkko
.......................ohkkkkkkkkko
.......................ohkkkkkkkkko
.......................okkkkkkkkkko
......................ohhkkkkkkkkkko
.................oohhhhhhhkkkkkkkkkkkkkkkoo
...............ohkkkkkkkkkkkkkkkkkkkkkkkkkko
.................ookkkkkkkkoooooooooohhoo
.....................okhhpuuuuuuttttko
.....................ohkpuuuuuuuuutttko
.....................okkpppuuupppuuttko
.....................okkpuuuuuuuuuuttko
.....................okkpkeuuukepuuttto
.....................okkpwkuuuwekutuuto
.....................okkptuuuuuuuutttpo...................mm
......................okpttuuuuuttttpo...................mw
........................kpttuuupettpo..................vm
.........................optttttppo....................v
.......................okkoptttpo
.....................oscllllutplco
....................oscllllcppillco
...................oscllllccijidillco
..................oscllllccsijjiddiccso................vmw
..................oclllcccssijiiddiiccso...............mw
.................osclllccsssiijidddiiccso..............vm
.................ocllccsssiidddiicclllcco.............v
..................ocllcssiiddiclllcccllco
...................osccsiiddiclllcccclco
....................osccscccllcccscclcso
.....................oscccssccidddcccso
......................oscirRRRRrrddpuupo
......................oscirrRRrrrRrpuutpeo.......mw
.....................oscllciidddirRrtppkhho......vm
....................osclllciidddirrdopuueovwm....v
...................osclllcciidddiddiiptpokvwm
..................osclllcccijidddiiccso..kvwm
.................osclllccijjiiddiicclccso..kvm
................osclllccijjiiddiiccllccso..kho
...............osclllccijjiiddiiccllllccso..okko
..............osclllccijjiiddiicclllllccso...okko
..............oscllccijjiidddiiccllllccso.....oo
...............osclccijjiiddddiiccllccso
................osccijjiiddddiicclccsso
.................oscijjiidddiicclccssso
..................osiiidddoooscclcssso
...................osssooo...oosccsso
..................ohhhkko.....ohhhkko
.................ohhhkkko.....ohhkkkko
.................okkkkkko....okkkkkkkko
.................oooooooo....oooooooooo
.
.
.
''')
