from write_rows import write

write('actions/poison_a.pxgrid', '''
.
.
.
.
.
.
.
.
.
.
.
........................oooooooooo
.......................ohhkkkkkkkko
.......................ohkkkkkkkkko
.......................ohkkkkkkkkko
.......................ohkkkkkkkkko
.......................okkkkkkkkkko
......................ohhkkkkkkkkkko
.................oohhhhhhhkkkkkkkkkkkkkkoo
...............ohkkkkkkkkkkkkkkkkkkkkkkkkko
.................ookkkkkkkkoooooooooohhoo
.....................okhhpuuuuuuttttko
.....................ohkpuuuuuuuuutttko
.........rr..........okkppuupuuuppuuttko
........rRpl.........okkpuuuuuuuuuuttko
........rppR.........okkpekuuuuepuuttto
.........rr..........okkptwkuuuwekututo
.....................okkpttuuuuuuuutttpo
......................okpttuuuppttttpo
........................kpttuuewettpo
.........................optttttppo
......................ookkoptttpo.............rr
....................osclllllutplco...........rRplr
...................oscllllccppillco..........rppRR
..................osclllcccsijidillco..........rr
..................oclllcccssijjiddiccso
.................oscllccsssiijiiddiiccso
.................ocllccsssiijidddiicclco
.................ocllccsssiiddddicclllco
..................ocllcssiiddiclllccllco
..................oscccsiiiddiclllcccsco
...................osccsccclllccpuuttco
...................osccssccidddpuutpeo
...................opuupoRRRRrrtppkho
...................opuutpeoRRrrRrcohvm
....................optppoiddirRrdco.vmw
.....................oscllciidddirrddco.vmmw
....................osclllciidddiddiicco.vmmw
...................osclllccijidddiicclco..vmww
...................oscllccijjiiddiiccllcso..vmmw
..................oscllccijjiidddiiccllccso..vmmw
..................osclccijjiiddddiiccllccso...vmw
...................osccijjiiddddiiccllccso....vmww
....................osijjiiddddiiiccllccso.....vmmw
.....................osiidddoooscccclcso.......vmw
......................osssoo...oscccssso.......vw
......................osssso....ossssso.........w
.....................ohhhkko....ohhhkko
....................ohhhkkko....ohhkkkko
....................okkkkkko...okkkkkkkko
....................oooooooo...oooooooooo
.
.
.
''')

write('actions/poison_b.pxgrid', '''
.
.
.
.
.
.
.
.
.
.
.
.
......................oooooooooo
.....................ohhkkkkkkkko
.....................ohkkkkkkkkko
.....................ohkkkkkkkkko
.....................ohkkkkkkkkko
.....................okkkkkkkkkko
....................ohhkkkkkkkkkko
...............oohhhhhhhkkkkkkkkkkkkkkoo
.............ohkkkkkkkkkkkkkkkkkkkkkkkkko
...............ookkkkkkkkoooooooooohhoo.......rr
...................okhhpuuuuuuttttko.........rRpl
...................ohkpuuuuuuuuutttko........rppR
...................okkppuupuuuppuuttko........rr
...................okkpuuuuuuuuuuttko
...................okkpekuuuuepuuttto
...................okkptwkuuuwekututo
...................okkpttuuuuuuuutttpo
....................okpttuuuppttttpo
.........rr...........kpttuuewettpo
........rRplr..........optttttppo
........rppRR.......ookkoptttpo
.........rr.......osclllllutplco
.................oscllllccppillco
................osclllcccsijidillco
................oclllcccssijjiddiccso
................ocllccsssiijiiddiiccso
...............oscllccsssiijidddiccllco
...............ocllccsssiiddddiclllcpuupo
................ocllcssiiddiclllcccpuutpeo
.................osccsiiiddicllcccssotppo
..................osccscccllcccscidddco
...................osccssccirRRRRrrddco
....................oscllcirrRRrrrRrdco
....................oscllcpuuttpdirRrdco
....................oscllcpuutpeoirrddco
....................oscllccotppkhoiddiicco
...................osclllccijidhvmddiicclco
...................oscllccijjiidvmwwiicclcso
..................oscllccijjiiddovmmwclllccso
..................osclccijjiiddoo.vmmwllccsso
...................osccijjiiddoo...vmwwccsso
....................osijjiiddoo.....vmmwcsso
.....................osiiddoo.......vmmwsso
......................osssoo.........vmwso
.....................ohhhkko.........vmmw
....................ohhhkkko....ohhhkkovmw
....................okkkkkko....ohhkkkko.vw
....................okkkkkko...okkkkkkkkow
....................oooooooo...oooooooooo
.
.
.
''')

write('actions/stun_a.pxgrid', '''
.
.
...................u
..................uwu.......................u
................uuwuuu....................uuwu
.................uuwu......................wu
..................u.u.....................u..u
.
.
.
........................oooooooooo
.......................ohhkkkkkkkko
.......................ohkkkkkkkkko
.......................ohkkkkkkkkko
.......................ohkkkkkkkkko
.......................okkkkkkkkkko
......................ohhkkkkkkkkkko
.................oohhhhhhhkkkkkkkkkkkkkkoo
...............ohkkkkkkkkkkkkkkkkkkkkkkkkko
.................ookkkkkkkkoooooooooohhoo
.....................okhhpuuuuuuttttko
.....................ohkpuuuuuuuuutttko
.....................okkpppuuupppuuttko
.....................okkpuuuuuuuuuuttko
.....................okkpkeuuukepuuttto
.....................okkpwkuuuwekutuuto
.....................okkptuuuuuuuutttpo
......................okpttuuuppttttpo
........................kpttuuepettpo
.........................optttttppo
.......................okkoptttpo
.....................oscllllutplco
...................ooscllllcppillco
..................osclllcccsijidillcco
.................osclllcccssijjiddicclco
................osclllccsssijiiddiiccllco
................oclllccsssiijidddiiccllco
...............osclllccsssiidddiiccllllco
...............oclllccsssiiidddiiccllllco
...............ocllccssoiiiddddiccllllco
...............ocllccsoosiiddddicclllcco
................osccsso.oiirRRRRrrcllcco
................osccso..oirrRRrrrRrccsso
................opuupo..osclciidddirccso
................opuutpeooscllciidddircso
.................optppo.oscllciidddidpuupo
.......................osclllciidddidpuutpeo
......................osclllccijidddioptpkho
.....................osclllccijjiiddiicchvm
....................osclllccijjiiddiicclcvmw
....................oscllccijjiidddiiccllvmmw
...................osclllccijjiidddiiccllcvmww
....................osclccijjiiddddiiccllccvmmw
.....................osccijjiiddddiiccllccsovmmw
......................oscijjiidddiicclccsso..vmw
.......................osiiidddoooscclcssso...vmmw
........................osssooo...oosccsso....vmw
.......................ohhhkko.....ohhhkko......vw
......................ohhhkkko.....ohhkkkko......w
......................okkkkkko....okkkkkkkko
......................oooooooo....oooooooooo
.
.
.
''')

write('actions/stun_b.pxgrid', '''
.
.
.............................u
...........................uuwu
............................wuuu
...........................uuwu..............u
...........................u.u.............uuwuu
............................................uwu
............................................u.u
.
.
.........................oooooooooo
........................ohhkkkkkkkko
........................ohkkkkkkkkko
........................ohkkkkkkkkko
........................ohkkkkkkkkko
........................okkkkkkkkkko
.......................ohhkkkkkkkkkko
..................oohhhhhhhkkkkkkkkkkkkkkoo
................ohkkkkkkkkkkkkkkkkkkkkkkkkko
..................ookkkkkkkkoooooooooohhoo
......................okhhpuuuuuuttttko
......................ohkpuuuuuuuuutttko
......................okkpppuuupppuuttko
......................okkpuuuuuuuuuuttko
......................okkpkeuuukepuuttto
......................okkpwkuuuwekutuuto
......................okkptuuuuuuuutttpo
.......................okpttuuuppttttpo
.........................kpttuuepettpo
..........................optttttppo
........................okkoptttpo
......................oscllllutplco
....................ooscllllcppillco
...................osclllcccsijidillcco
..................osclllcccssijjiddicclco
.................osclllccsssijiiddiiccllco
.................oclllccsssiijidddiicclllco
................osclllccsssiidddiiccllllco
................oclllccsssiiidddiiccllllco
................ocllccssoiiiddddiccllllco
................osclccsoosiiddddiccllllco
.................osccsso.oiirRRRRrrclllcco
.................osccso..oirrRRrrrRrclccso
.................opuupo..osclciidddirccsso
.................opuutpeooscllciidddirccso
..................optppooscllciidddidccso
.......................osclllciidddidpuupo
......................osclllccijidddipuutpeo
.....................osclllccijjiiddioptpkho
.....................oscllccijjiiddiicclhvm
....................oscllccijjiidddiicclcvmw
...................oscllccijjiiddddiiccllcvmmw
....................osccijjiiddddiicccllccvmww
.....................osijjiiddddiiiccllccsovmmw
......................osiidddoooscccllccso..vmmw
.......................osssoo...osccclccso...vmw
......................ohhhkko....osccssso....vmmw
.....................ohhhkkko.....ohhhkko.....vmw
.....................okkkkkko....ohhkkkko.......vw
.....................oooooooo...oooooooooo......w
.
.
.
''')

write('actions/sleep_a.pxgrid', '''
.
.
.
.
.
.
.
.
.
.
.
.
........................ooooooooo
.......................ohhkkkkkkko
.......................ohkkkkkkkko
.......................ohkkkkkkkko
.......................ohkkkkkkkkko
.......................okkkkkkkkkko
......................ohhkkkkkkkkkko
.................oohhhhhhhkkkkkkkkkkkkkkoo
...............ohkkkkkkkkkkkkkkkkkkkkkkkkko
.................ookkkkkkkkoooooooooohhhhkoo
.....................okhhpuuuuuuttttko
.....................ohkpuuuuuuuuutttko
.....................okkpppuuupppuuttko
.....................okkpuuuuuuuuuuttko
.....................okkpteeuuueepttutto
.....................okkpttuuuuuuuuututo
.....................okkpttuuuuuuuutttpo
......................okpttuuuuuttttpo
........................kpttuuupettpo
.........................optttttppo
.......................okkoptttpo
.....................oscllllutplco
....................oscllllcppillco
...................oscllllccijidillco
..................oscllllccsijjiddiccso
..................oclllcccssijiiddiiccso
.................osclllccsssiijidddiiccco
.................ocllccsssiidddiicclllcco
..................ocllcssiiddiclllccllco
...................osccsiiddiclllccclcso
....................osccscccllcccscclcso
.....................osccsspuuttpdcccsso
......................oscirpuutperddcso
......................oscirrptpporRrpuupo
.....................oscllciidddirRrpuutpeo
....................osclllciidddirrddotpkho
....................osclllcciidddiddiicohvm
...................osclllccijidddiiccllcovmw
...................oscllccijjiiddiiccllccvmmw
..................oscllccijjiidddiicclllcvmww
..................osclccijjiiddddiiccllccsvmmw
...................osccijjiiddddiiccllccsovmmw
....................oscijjiidddiicclccsso..vmw
.....................osiiidddoooscclcssso..vmmw
......................osssooo...oosccsso...vmw
.....................ohhhkko.....ohhhkko.....vw
....................ohhhkkko.....ohhkkkko.....w
....................okkkkkko....okkkkkkkko
....................oooooooo....oooooooooo
.
.
.
''')

write('actions/sleep_b.pxgrid', '''
.
.
.
.
.
.
.
.
.
.
.
.
........................ooooooooo
.......................ohhkkkkkkko
.......................ohkkkkkkkko
.......................ohkkkkkkkko
.......................ohkkkkkkkkko
.......................okkkkkkkkkko
......................ohhkkkkkkkkkko
.................oohhhhhhhkkkkkkkkkkkkkkoo
...............ohkkkkkkkkkkkkkkkkkkkkkkkkko
.................ookkkkkkkkoooooooooohhhhkoo
.....................okhhpuuuuuuttttko
.....................ohkpuuuuuuuuutttko
.....................okkpppuuupppuuttko
.....................okkpuuuuuuuuuuttko
.....................okkpteeuuueepttutto
.....................okkpttuuuuuuuuututo
.....................okkpttuuuuuuuutttpo
......................okpttuuuuuttttpo
........................kpttuuupettpo
.........................optttttppo
......................ookkoptttpo
....................osclllllutplco
...................osclllllcppillco
..................oscllllccsijidillco
.................oscllllccssijjiddiccso
.................oclllcccsssijiiddiiccso
................osclllccssssiijidddiiccco
................ocllccssssiidddiicclllcco
.................ocllccssiiddiclllccllco
..................oscccsiiddiclllccclcso
...................oscccscccllcccscclcso
....................oscccsspuuttpdcccsso
......................oscirpuutperddcso
......................oscirrptpporRrpuupo
.....................oscllciidddirRrpuutpeo
....................osclllciidddirrddotpkho
...................oscllllcciidddiddiicohvm
...................osclllccijidddiiccllcovmw
..................osclllccijjiiddiiccllccvmmw
..................oscllccijjiidddiicclllcvmww
.................oscllccijjiiddddiicclllccsvmmw
..................oscccijjiiddddiicclllccsvmmw
...................osccijjiidddiiccllccsso..vmw
....................osiiiidddoooscclccssso.vmmw
.....................ossssooo...ooscccsso...vmw
.....................ohhhkko.....ohhhkko.....vw
....................ohhhkkko.....ohhkkkko.....w
....................okkkkkko....okkkkkkkko
....................oooooooo....oooooooooo
.
.
.
''')
