(() => {
 const rect=r=>({x:r.x,y:r.y,width:r.width,height:r.height,top:r.top,right:r.right,bottom:r.bottom,left:r.left});
 const basic=e=>{const s=getComputedStyle(e);return {tag:e.tagName,id:e.id,testid:e.dataset.testid,class:e.className,display:s.display,visibility:s.visibility,opacity:s.opacity,overflowX:s.overflowX,overflowY:s.overflowY,transform:s.transform,width:s.width,height:s.height,minWidth:s.minWidth,minHeight:s.minHeight,playScale:s.getPropertyValue('--play-scale'),rect:rect(e.getBoundingClientRect()),scrollTop:e.scrollTop,scrollLeft:e.scrollLeft,scrollWidth:e.scrollWidth,scrollHeight:e.scrollHeight,clientWidth:e.clientWidth,clientHeight:e.clientHeight,clientTop:e.clientTop,clientLeft:e.clientLeft};};
 const geo=e=>{if(!e)return {present:false};const own=basic(e),ancestors=[];let hidden=own.display==='none'||own.visibility!=='visible'||Number(own.opacity)===0;let left=Math.max(0,own.rect.left),right=Math.min(innerWidth,own.rect.right),top=Math.max(0,own.rect.top),bottom=Math.min(innerHeight,own.rect.bottom);for(let a=e.parentElement;a;a=a.parentElement){const b=basic(a);ancestors.push(b);hidden ||= b.display==='none'||b.visibility!=='visible'||Number(b.opacity)===0;const sx=a.offsetWidth?b.rect.width/a.offsetWidth:1,sy=a.offsetHeight?b.rect.height/a.offsetHeight:1;if(['auto','scroll','hidden','clip'].includes(b.overflowX)){left=Math.max(left,b.rect.left+a.clientLeft*sx);right=Math.min(right,b.rect.left+(a.clientLeft+a.clientWidth)*sx);}if(['auto','scroll','hidden','clip'].includes(b.overflowY)){top=Math.max(top,b.rect.top+a.clientTop*sy);bottom=Math.min(bottom,b.rect.top+(a.clientTop+a.clientHeight)*sy);}}
 const visibleWidth=hidden?0:Math.max(0,right-left),visibleHeight=hidden?0:Math.max(0,bottom-top);
 return {present:true,...own,data:{...e.dataset},text:e.textContent,disabled:e.disabled,tabIndex:e.tabIndex,ariaCurrent:e.getAttribute('aria-current'),ariaPressed:e.getAttribute('aria-pressed'),ancestors,effectiveVisibility:hidden?'css-hidden':visibleWidth<=0||visibleHeight<=0?'outside-clipped-viewport':visibleWidth+0.5>=own.rect.width&&visibleHeight+0.5>=own.rect.height?'fully-visible':'partially-visible',visibleRect:{left,top,width:visibleWidth,height:visibleHeight},values:own.testid?.match(/^shop-(summary-)?stat-/)?Object.fromEntries(['current','next','delta'].map(k=>[k,e.hasAttribute('data-'+k)?Number(e.dataset[k]):null])):undefined};};
 const ids=['shop-scene','shop-detail-card','shop-stat-slot','shop-detail-open','shop-summary-reason','shop-comparison','shop-detail-scroll','shop-preview-reason','shop-detail-close','shop-actor-actor_hero','shop-slot-weapon','shop-sell-equip_sword',...['attack','defense','mind','agility'].flatMap(k=>['shop-summary-stat-'+k,'shop-stat-'+k])];
 return {url:location.href,viewport:{width:innerWidth,height:innerHeight,devicePixelRatio},media:{compact:matchMedia('(max-width:860px), (max-height:600px)').matches,tiny:matchMedia('(max-width:460px), (max-height:360px)').matches},focus:document.activeElement?.dataset.testid,activeDescendant:document.activeElement?.getAttribute('aria-activedescendant'),selectors:Object.fromEntries(ids.map(id=>[id,geo(document.querySelector('[data-testid="'+id+'"]'))])),surfaces:[...document.querySelectorAll('.player-layout,.play-viewport,.play-stage,.runtime-shop-overlay,.runtime-shop-detail-panel')].map(basic),state:window.__oprnDebug.readState()};
})()
