import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { loadProjectFromLegacyDb } from '/home/main/z-project/rpg-zzu/src/project/legacyDbProjectSync.ts';
const out=new URL('./',import.meta.url).pathname;
const env=Object.fromEntries((await readFile('/home/main/z-project/rpg-zzu/.env.local','utf8')).split('\n').filter(l=>l.includes('=')&&!l.startsWith('#')).map(l=>{const i=l.indexOf('=');return [l.slice(0,i),l.slice(i+1).replace(/^['"]|['"]$/g,'')]}));
const projectId='oprn-e98456e1d8';
const project=await loadProjectFromLegacyDb({url:env.VITE_LEGACY_DB_URL,anonKey:env.VITE_LEGACY_DB_ANON_KEY,projectId});
if(!project)throw new Error('Canonical project missing');
const text=JSON.stringify(project);
await writeFile(out+'canonical-project.json',text);
const prior=await readFile(out+'../weapon-shop/positive-control/canonical-project.json','utf8');
const sha=(s:string)=>createHash('sha256').update(s).digest('hex');
const map=project.maps.map_weapon_shop;
const evidence={projectId,loadedAt:new Date().toISOString(),loader:'/home/main/z-project/rpg-zzu/src/project/legacyDbProjectSync.ts#loadProjectFromLegacyDb',snapshotSha256:sha(text),priorSnapshotSha256:sha(prior),identicalToPrior:text===prior,title:project.meta.title,startMapId:project.startMapId,startPos:project.startPos,system:project.system,session:project.session,merchant:map.events?.find(e=>e.id==='ev_villager_35c9ba59-6f59-47a3-b0fb-bcf9b6de5c25'),equipment:project.database.equipment,items:project.database.items,actors:project.database.actors};
await writeFile(out+'provenance.json',JSON.stringify(evidence,null,2));
console.log(JSON.stringify({projectId,sha256:sha(text),identicalToPrior:evidence.identicalToPrior,title:project.meta.title}));
