import type { EquipmentRecord } from "../types";
import { normalizeEquipmentRecord } from "../databaseRecordModel";
import {
  ACTOR_CLERIC_ID,
  ACTOR_GUARDIAN_ID,
  ACTOR_MAGE_ID,
  ACTOR_RANGER_ID,
  ACTOR_SCOUT_ID,
  ALL_ACTOR_IDS,
  ALL_CLASS_IDS,
  CLASS_CLERIC_ID,
  CLASS_GUARDIAN_ID,
  CLASS_MAGE_ID,
  CLASS_RANGER_ID,
  CLASS_SCOUT_ID,
} from "./defaultDatabaseRecordIds";

export function defaultCatalogFillEquipmentRecords(): EquipmentRecord[] {
  return [
    normalizeEquipmentRecord({
      id: "equip_fill_shield_buckler",
      name: "매사냥꾼 원형 방패",
      slot: "shield",
      price: 145,
      imageResourceId: "cc0-jetrel-gen-shield-wood",
      iconResourceId: "cc0-jetrel-gen-shield-wood",
      description: "가벼운 원형 틀이 팔의 움직임을 살려 빠른 반격과 급소 공격을 돕습니다.",
      statBonuses: { attack: 0, defense: 6, mind: 0, agility: 1 },
      criticalRate: 2,
      equippableActorIds: [ACTOR_GUARDIAN_ID, ACTOR_RANGER_ID, ACTOR_SCOUT_ID],
      equippableClassIds: [CLASS_GUARDIAN_ID, CLASS_RANGER_ID, CLASS_SCOUT_ID],
    }),
    normalizeEquipmentRecord({
      id: "equip_fill_shield_ember_ward",
      name: "잿불 수호 방패",
      slot: "shield",
      price: 275,
      imageResourceId: "cc0-jetrel-gen-shield-iron",
      iconResourceId: "cc0-jetrel-gen-shield-iron",
      description: "겹친 철판 사이의 내열재가 화염을 흩어 뜨거운 전장에서 전열을 지킵니다.",
      statBonuses: { attack: 0, defense: 9, mind: 2, agility: 0 },
      elementalDefenseIds: ["fire"],
      equippableActorIds: [ACTOR_GUARDIAN_ID, ACTOR_CLERIC_ID],
      equippableClassIds: [CLASS_GUARDIAN_ID, CLASS_CLERIC_ID],
    }),
    normalizeEquipmentRecord({
      id: "equip_fill_shield_fortress",
      name: "요새문 대방패",
      slot: "shield",
      price: 470,
      imageResourceId: "cc0-jetrel-gen-shield-tower",
      iconResourceId: "cc0-jetrel-gen-shield-tower",
      description: "성문처럼 두꺼운 판이 타격을 받아 내지만 무거워서 움직임이 크게 둔해집니다.",
      statBonuses: { attack: 0, defense: 16, mind: 0, agility: -2 },
      elementalDefenseIds: ["hit"],
      effectFlags: {
        preemptive: false,
        doubleAttack: false,
        attackAll: false,
        ignoreDodge: false,
        preventCriticalHits: false,
        increasePhysicalDodge: false,
        halfMpCost: false,
        negateTerrainDamage: false,
        fixedEquipment: true,
      },
      equippableActorIds: [ACTOR_GUARDIAN_ID],
      equippableClassIds: [CLASS_GUARDIAN_ID],
    }),
    normalizeEquipmentRecord({
      id: "equip_fill_shield_hymn",
      name: "성가대 은방패",
      slot: "shield",
      price: 315,
      imageResourceId: "cc0-jetrel-gen-shield-mirror",
      iconResourceId: "cc0-jetrel-gen-shield-mirror",
      description: "은빛 공명판이 주문의 흐름을 붙들어 침묵 저주 속에서도 기도를 이어 가게 합니다.",
      statBonuses: { attack: 0, defense: 8, mind: 5, agility: -1 },
      stateResistanceChance: 35,
      stateDefenseIds: ["state_silence"],
      equippableActorIds: [ACTOR_CLERIC_ID],
      equippableClassIds: [CLASS_CLERIC_ID],
    }),
    normalizeEquipmentRecord({
      id: "equip_fill_shield_moon_mirror",
      name: "월광 거울 방패",
      slot: "shield",
      price: 420,
      imageResourceId: "cc0-jetrel-gen-shield-mirror",
      iconResourceId: "cc0-jetrel-gen-shield-mirror",
      description: "달빛으로 닦은 거울 면이 암흑 마력을 흘려보내고 정확한 방패술을 보조합니다.",
      statBonuses: { attack: 1, defense: 11, mind: 4, agility: 0 },
      accuracy: 99,
      elementalDefenseIds: ["dark"],
      equippableActorIds: [ACTOR_GUARDIAN_ID, ACTOR_CLERIC_ID],
      equippableClassIds: [CLASS_GUARDIAN_ID, CLASS_CLERIC_ID],
    }),
    normalizeEquipmentRecord({
      id: "equip_fill_armor_storm_chain",
      name: "폭풍고리 사슬갑옷",
      slot: "armor",
      price: 430,
      imageResourceId: "cc0-jetrel-gen-armor-chain",
      iconResourceId: "cc0-jetrel-gen-armor-chain",
      description: "절연 가죽으로 엮은 가벼운 사슬이 번개를 분산하면서 기동성을 유지합니다.",
      statBonuses: { attack: 0, defense: 12, mind: 2, agility: 1 },
      elementalDefenseIds: ["thunder"],
      equippableActorIds: [ACTOR_GUARDIAN_ID, ACTOR_RANGER_ID, ACTOR_SCOUT_ID],
      equippableClassIds: [CLASS_GUARDIAN_ID, CLASS_RANGER_ID, CLASS_SCOUT_ID],
    }),
    normalizeEquipmentRecord({
      id: "equip_fill_armor_oath_plate",
      name: "불퇴서약 판금갑옷",
      slot: "armor",
      price: 650,
      imageResourceId: "cc0-jetrel-gen-armor-plate",
      iconResourceId: "cc0-jetrel-gen-armor-plate",
      description: "맞물린 판금과 고정 끈이 공격을 약화시키는 위압에도 자세가 무너지지 않게 합니다.",
      statBonuses: { attack: 0, defense: 19, mind: 1, agility: -3 },
      stateResistanceChance: 40,
      stateDefenseIds: ["state_attack_down"],
      equippableActorIds: [ACTOR_GUARDIAN_ID],
      equippableClassIds: [CLASS_GUARDIAN_ID],
    }),
    normalizeEquipmentRecord({
      id: "equip_fill_helmet_falcon",
      name: "매눈 정찰 투구",
      slot: "helmet",
      price: 150,
      imageResourceId: "cc0-jetrel-gen-helm-leather",
      iconResourceId: "cc0-jetrel-gen-helm-leather",
      description: "넓은 시야를 남긴 가죽 덮개가 민첩한 정찰과 빈틈을 찌르는 공격에 알맞습니다.",
      statBonuses: { attack: 1, defense: 4, mind: 0, agility: 2 },
      accuracy: 100,
      criticalRate: 2,
      equippableActorIds: [ACTOR_RANGER_ID, ACTOR_SCOUT_ID],
      equippableClassIds: [CLASS_RANGER_ID, CLASS_SCOUT_ID],
    }),
    normalizeEquipmentRecord({
      id: "equip_fill_helmet_frost_hood",
      name: "설원 현자 두건",
      slot: "helmet",
      price: 225,
      imageResourceId: "cc0-jetrel-gen-helm-leather",
      iconResourceId: "cc0-jetrel-gen-helm-leather",
      description: "서리풀을 누빈 두건이 냉기를 막고 긴 야영 중에도 정신을 맑게 유지합니다.",
      statBonuses: { attack: 0, defense: 3, mind: 5, agility: 1 },
      elementalDefenseIds: ["ice"],
      stateResistanceChance: 25,
      stateDefenseIds: ["state_sleep"],
      equippableActorIds: [ACTOR_MAGE_ID, ACTOR_CLERIC_ID, ACTOR_RANGER_ID],
      equippableClassIds: [CLASS_MAGE_ID, CLASS_CLERIC_ID, CLASS_RANGER_ID],
    }),
    normalizeEquipmentRecord({
      id: "equip_fill_helmet_rune",
      name: "침묵파쇄 룬투구",
      slot: "helmet",
      price: 335,
      imageResourceId: "cc0-jetrel-gen-helm-iron",
      iconResourceId: "cc0-jetrel-gen-helm-iron",
      description: "관자놀이의 룬 각인이 정신을 보호해 적의 침묵 마법에도 주문 집중을 붙잡습니다.",
      statBonuses: { attack: 0, defense: 7, mind: 4, agility: -1 },
      stateResistanceChance: 45,
      stateDefenseIds: ["state_silence"],
      equippableActorIds: [ACTOR_GUARDIAN_ID, ACTOR_MAGE_ID, ACTOR_CLERIC_ID],
      equippableClassIds: [CLASS_GUARDIAN_ID, CLASS_MAGE_ID, CLASS_CLERIC_ID],
    }),
    normalizeEquipmentRecord({
      id: "equip_fill_helmet_vanguard",
      name: "선봉대 뿔투구",
      slot: "helmet",
      price: 410,
      imageResourceId: "cc0-jetrel-gen-helm-horned",
      iconResourceId: "cc0-jetrel-gen-helm-horned",
      description: "앞으로 굽은 뿔과 보강 이마판이 돌격의 위력을 높이고 공격 약화를 버텨 냅니다.",
      statBonuses: { attack: 3, defense: 9, mind: 1, agility: 0 },
      criticalRate: 4,
      stateResistanceChance: 30,
      stateDefenseIds: ["state_attack_down"],
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
  ];
}
