import type { ItemRecord } from "../types";
import { normalizeItemRecord } from "../databaseRecordModel";
import { DEFAULT_ITEM_ID, DEFAULT_STATE_ID } from "./constants";
import { generatedItemRecords } from "./generatedItemRecords";
import { applyGeneratedBattleEffectItemBindings } from "./generatedBattleEffectBindings";

export function defaultItemRecords(): ItemRecord[] {
  const records = [
    normalizeItemRecord({
      id: DEFAULT_ITEM_ID,
      name: "회복약",
      type: "medicine",
      scope: "ally",
      price: 50,
      description: "아군 하나의 HP를 50 회복합니다.",
      imageResourceId: "cc0-jetrel-potion-red",
      iconResourceId: "cc0-jetrel-potion-red",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      hpRecovery: { flat: 50, percentMax: 0 },
      skillId: "skill_item_potion",
    }),
    normalizeItemRecord({
      id: "item_capture_orb",
      name: "포획 구슬",
      type: "special",
      scope: "enemy",
      price: 80,
      description: "약해진 몬스터를 포획하는 기본 구슬입니다.",
      imageResourceId: "cc0-jetrel-capture-orb",
      iconResourceId: "cc0-jetrel-capture-orb",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
      captureProfile: { multiplier: 1 },
    }),
    normalizeItemRecord({
      id: "item_ether",
      name: "마력약",
      type: "medicine",
      scope: "ally",
      price: 120,
      description: "아군 하나의 MP를 30 회복합니다.",
      imageResourceId: "cc0-jetrel-ether-blue",
      iconResourceId: "cc0-jetrel-ether-blue",
      animationId: "anim_magic",
      occasion: "always",
      consumable: true,
      mpRecovery: { flat: 30, percentMax: 0 },
      skillId: "skill_item_ether",
    }),
    normalizeItemRecord({
      id: "item_antidote",
      name: "해독초",
      type: "medicine",
      scope: "ally",
      price: 30,
      description: "독 상태를 해제합니다.",
      imageResourceId: "cc0-jetrel-antidote-green",
      iconResourceId: "cc0-jetrel-antidote-green",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      healStateIds: [DEFAULT_STATE_ID],
      stateEffects: [{ stateId: DEFAULT_STATE_ID, chance: 100, operation: "remove" }],
      skillId: "skill_item_antidote",
    }),
    normalizeItemRecord({
      id: "item_wake_herb",
      name: "각성초",
      type: "medicine",
      scope: "ally",
      price: 40,
      description: "수면 상태를 해제합니다.",
      imageResourceId: "cc0-jetrel-wake-herb",
      iconResourceId: "cc0-jetrel-wake-herb",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      healStateIds: ["state_sleep"],
      stateEffects: [{ stateId: "state_sleep", chance: 100, operation: "remove" }],
      skillId: "skill_item_wake",
    }),
    normalizeItemRecord({
      id: "item_poison_dart",
      name: "독침",
      type: "special",
      scope: "enemy",
      price: 80,
      description: "적 하나에게 약한 피해를 주고 독 상태를 노립니다.",
      imageResourceId: "cc0-jetrel-poison-dart",
      iconResourceId: "cc0-jetrel-poison-dart",
      skillId: "skill_poison_sting",
      animationId: "anim_poison",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_old_key",
      name: "낡은 열쇠",
      type: "normalGoods",
      scope: "none",
      price: 0,
      description: "오래된 문을 열 수 있을 것 같은 열쇠입니다.",
      imageResourceId: "cc0-jetrel-old-key",
      iconResourceId: "cc0-jetrel-old-key",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_hi_potion",
      name: "상급 회복약",
      type: "medicine",
      scope: "ally",
      price: 180,
      description: "아군 하나의 HP를 150 회복하는 상급 약입니다.",
      imageResourceId: "cc0-jetrel-hi-potion",
      iconResourceId: "cc0-jetrel-hi-potion",
      skillId: "skill_item_hi_potion",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      hpRecovery: { flat: 150, percentMax: 0 },
    }),
    normalizeItemRecord({
      id: "item_elixir",
      name: "엘릭서",
      type: "medicine",
      scope: "ally",
      price: 600,
      description: "아군 하나의 HP와 MP를 모두 크게 회복하는 귀한 약입니다.",
      imageResourceId: "cc0-jetrel-elixir",
      iconResourceId: "cc0-jetrel-elixir",
      skillId: "skill_item_elixir",
      animationId: "anim_magic",
      occasion: "always",
      consumable: true,
      hpRecovery: { flat: 0, percentMax: 100 },
      mpRecovery: { flat: 0, percentMax: 100 },
    }),
    normalizeItemRecord({
      id: "item_panacea",
      name: "만능약",
      type: "medicine",
      scope: "ally",
      price: 220,
      description: "독과 수면처럼 흔한 상태이상을 한 번에 정리하는 치료약입니다.",
      imageResourceId: "cc0-jetrel-panacea",
      iconResourceId: "cc0-jetrel-panacea",
      skillId: "skill_item_panacea",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      healStateIds: [DEFAULT_STATE_ID, "state_sleep"],
      stateEffects: [{ stateId: DEFAULT_STATE_ID, chance: 100, operation: "remove" }, { stateId: "state_sleep", chance: 100, operation: "remove" }],
    }),
    normalizeItemRecord({
      id: "item_smelling_salts",
      name: "각성 가루",
      type: "medicine",
      scope: "ally",
      price: 75,
      description: "수면에 빠진 아군을 깨우는 휴대용 가루입니다.",
      imageResourceId: "cc0-jetrel-smelling-salts",
      iconResourceId: "cc0-jetrel-smelling-salts",
      skillId: "skill_item_wake",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      healStateIds: ["state_sleep"],
      stateEffects: [{ stateId: "state_sleep", chance: 100, operation: "remove" }],
    }),
    normalizeItemRecord({
      id: "item_throwing_knife",
      name: "투척 단검",
      type: "special",
      scope: "enemy",
      price: 110,
      description: "적 하나에게 던져 피해를 주는 전투용 소모품입니다.",
      imageResourceId: "cc0-jetrel-throwing-knife",
      iconResourceId: "cc0-jetrel-throwing-knife",
      skillId: "skill_throwing_knife",
      animationId: "anim_arrow",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_poison_vial",
      name: "독병",
      type: "special",
      scope: "enemy",
      price: 140,
      description: "적 하나에게 독을 노리는 투척용 병입니다.",
      imageResourceId: "cc0-jetrel-poison-vial",
      iconResourceId: "cc0-jetrel-poison-vial",
      skillId: "skill_item_poison_vial",
      animationId: "anim_poison",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_warp_scroll",
      name: "귀환 주문서",
      type: "normalGoods",
      scope: "none",
      price: 250,
      description: "마을이나 안전 지점으로 돌아가는 이벤트 조건에 쓰는 주문서입니다.",
      imageResourceId: "cc0-jetrel-scroll",
      iconResourceId: "cc0-jetrel-scroll",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_sword_manual",
      name: "검술 교본",
      type: "book",
      scope: "ally",
      price: 320,
      description: "검격 기술을 익히게 하는 스킬북입니다.",
      imageResourceId: "cc0-jetrel-book-sword",
      iconResourceId: "cc0-jetrel-book-sword",
      skillId: "skill_sword_slash",
      learnedSkillId: "skill_sword_slash",
      occasion: "field",
      occasionField: true,
      occasionBattle: false,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_magic_primer",
      name: "마법 입문서",
      type: "book",
      scope: "ally",
      price: 360,
      description: "기초 공격 마법(마법탄)을 익히게 하는 스킬북입니다.",
      imageResourceId: "cc0-jetrel-book-magic",
      iconResourceId: "cc0-jetrel-book-magic",
      skillId: "skill_arcane_bolt",
      learnedSkillId: "skill_arcane_bolt",
      occasion: "field",
      occasionField: true,
      occasionBattle: false,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_guard_talisman",
      name: "수호 부적",
      type: "special",
      scope: "ally",
      price: 260,
      description: "전투 중 아군의 방어를 높이는 부적입니다.",
      imageResourceId: "cc0-jetrel-talisman",
      iconResourceId: "cc0-jetrel-talisman",
      skillId: "skill_item_guard",
      activateSkillId: "skill_item_guard",
      animationId: "anim_heal",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_armor_patch",
      name: "가죽 수선 도구",
      type: "normalGoods",
      scope: "none",
      price: 90,
      description: "방어구 수리 이벤트나 제작 재료로 쓰기 좋은 일반 아이템입니다.",
      imageResourceId: "cc0-jetrel-repair-kit",
      iconResourceId: "cc0-jetrel-repair-kit",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_mystic_cloth",
      name: "신비한 천",
      type: "normalGoods",
      scope: "none",
      price: 160,
      description: "로브 제작, 마법 의식, 퀘스트 재료에 어울리는 소재입니다.",
      imageResourceId: "cc0-jetrel-mystic-cloth",
      iconResourceId: "cc0-jetrel-mystic-cloth",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_traveler_badge",
      name: "여행자 표식",
      type: "normalGoods",
      scope: "none",
      price: 0,
      description: "길드 가입, 통행 허가, 동료 합류 조건에 쓰기 좋은 키 아이템입니다.",
      imageResourceId: "cc0-jetrel-badge",
      iconResourceId: "cc0-jetrel-badge",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_lucky_charm",
      name: "행운의 부적",
      type: "normalGoods",
      scope: "none",
      price: 300,
      description: "보물상자, 퀘스트 보상, 희귀 이벤트 조건에 쓰기 좋은 부적입니다.",
      imageResourceId: "cc0-jetrel-lucky-charm",
      iconResourceId: "cc0-jetrel-lucky-charm",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_ale",
      name: "ale",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "ale 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-ale",
      iconResourceId: "cc0-jetrel-ale",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_antidote_plus",
      name: "antidote plus",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "antidote-plus 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-antidote-plus",
      iconResourceId: "cc0-jetrel-antidote-plus",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_apple",
      name: "apple",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "apple 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-apple",
      iconResourceId: "cc0-jetrel-apple",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_arrow_bundle",
      name: "arrow bundle",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "arrow-bundle 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-arrow-bundle",
      iconResourceId: "cc0-jetrel-arrow-bundle",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_bandages",
      name: "bandages",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "bandages 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-bandages",
      iconResourceId: "cc0-jetrel-bandages",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_battery",
      name: "battery",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "battery 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-battery",
      iconResourceId: "cc0-jetrel-battery",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_bell",
      name: "bell",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "bell 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-bell",
      iconResourceId: "cc0-jetrel-bell",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_bomb",
      name: "bomb",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "bomb 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-bomb",
      iconResourceId: "cc0-jetrel-bomb",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_bone",
      name: "bone",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "bone 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-bone",
      iconResourceId: "cc0-jetrel-bone",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_boots",
      name: "boots",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "boots 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-boots",
      iconResourceId: "cc0-jetrel-boots",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_bread",
      name: "bread",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "bread 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-bread",
      iconResourceId: "cc0-jetrel-bread",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_bronze_sword",
      name: "bronze sword",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "bronze-sword 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-bronze-sword",
      iconResourceId: "cc0-jetrel-bronze-sword",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_bullet",
      name: "bullet",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "bullet 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-bullet",
      iconResourceId: "cc0-jetrel-bullet",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_camera",
      name: "camera",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "camera 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-camera",
      iconResourceId: "cc0-jetrel-camera",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_candle",
      name: "candle",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "candle 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-candle",
      iconResourceId: "cc0-jetrel-candle",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_candy",
      name: "candy",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "candy 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-candy",
      iconResourceId: "cc0-jetrel-candy",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_cheese",
      name: "cheese",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "cheese 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-cheese",
      iconResourceId: "cc0-jetrel-cheese",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_claw",
      name: "claw",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "claw 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-claw",
      iconResourceId: "cc0-jetrel-claw",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_cloak",
      name: "cloak",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "cloak 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-cloak",
      iconResourceId: "cc0-jetrel-cloak",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_clock",
      name: "clock",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "clock 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-clock",
      iconResourceId: "cc0-jetrel-clock",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_coal",
      name: "coal",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "coal 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-coal",
      iconResourceId: "cc0-jetrel-coal",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_coffee",
      name: "coffee",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "coffee 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-coffee",
      iconResourceId: "cc0-jetrel-coffee",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_coin_pouch",
      name: "coin pouch",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "coin-pouch 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-coin-pouch",
      iconResourceId: "cc0-jetrel-coin-pouch",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_compass",
      name: "compass",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "compass 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-compass",
      iconResourceId: "cc0-jetrel-compass",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_cookie",
      name: "cookie",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "cookie 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-cookie",
      iconResourceId: "cc0-jetrel-cookie",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_corn",
      name: "corn",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "corn 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-corn",
      iconResourceId: "cc0-jetrel-corn",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_crystal",
      name: "crystal",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "crystal 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-crystal",
      iconResourceId: "cc0-jetrel-crystal",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_earth_ore",
      name: "earth ore",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "earth-ore 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-earth-ore",
      iconResourceId: "cc0-jetrel-earth-ore",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_egg",
      name: "egg",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "egg 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-egg",
      iconResourceId: "cc0-jetrel-egg",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_eye_drops",
      name: "eye drops",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "eye-drops 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-eye-drops",
      iconResourceId: "cc0-jetrel-eye-drops",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_fang",
      name: "fang",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "fang 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-fang",
      iconResourceId: "cc0-jetrel-fang",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_fire_bomb",
      name: "fire bomb",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "fire-bomb 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-fire-bomb",
      iconResourceId: "cc0-jetrel-fire-bomb",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_fish",
      name: "fish",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "fish 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-fish",
      iconResourceId: "cc0-jetrel-fish",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_fishing_rod",
      name: "fishing rod",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "fishing-rod 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-fishing-rod",
      iconResourceId: "cc0-jetrel-fishing-rod",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_flute",
      name: "flute",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "flute 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-flute",
      iconResourceId: "cc0-jetrel-flute",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_focus_charm",
      name: "focus charm",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "focus-charm 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-focus-charm",
      iconResourceId: "cc0-jetrel-focus-charm",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_focus_ring",
      name: "focus ring",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "focus-ring 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-focus-ring",
      iconResourceId: "cc0-jetrel-focus-ring",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gear",
      name: "gear",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "gear 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-gear",
      iconResourceId: "cc0-jetrel-gear",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gem_emerald",
      name: "gem emerald",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "gem-emerald 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-gem-emerald",
      iconResourceId: "cc0-jetrel-gem-emerald",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gem_ruby",
      name: "gem ruby",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "gem-ruby 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-gem-ruby",
      iconResourceId: "cc0-jetrel-gem-ruby",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gem_sapphire",
      name: "gem sapphire",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "gem-sapphire 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-gem-sapphire",
      iconResourceId: "cc0-jetrel-gem-sapphire",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gloves",
      name: "gloves",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "gloves 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-gloves",
      iconResourceId: "cc0-jetrel-gloves",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gold_bar",
      name: "gold bar",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "gold-bar 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-gold-bar",
      iconResourceId: "cc0-jetrel-gold-bar",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_herb_blue",
      name: "herb blue",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "herb-blue 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-herb-blue",
      iconResourceId: "cc0-jetrel-herb-blue",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_herb_green",
      name: "herb green",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "herb-green 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-herb-green",
      iconResourceId: "cc0-jetrel-herb-green",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_hide",
      name: "hide",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "hide 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-hide",
      iconResourceId: "cc0-jetrel-hide",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_hoe",
      name: "hoe",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "hoe 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-hoe",
      iconResourceId: "cc0-jetrel-hoe",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_holy_water",
      name: "holy water",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "holy-water 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-holy-water",
      iconResourceId: "cc0-jetrel-holy-water",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_honey",
      name: "honey",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "honey 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-honey",
      iconResourceId: "cc0-jetrel-honey",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_ice_shard",
      name: "ice shard",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "ice-shard 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-ice-shard",
      iconResourceId: "cc0-jetrel-ice-shard",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_ink",
      name: "ink",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "ink 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-ink",
      iconResourceId: "cc0-jetrel-ink",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_iron_ore",
      name: "iron ore",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "iron-ore 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-iron-ore",
      iconResourceId: "cc0-jetrel-iron-ore",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_iron_shield",
      name: "iron shield",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "iron-shield 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-iron-shield",
      iconResourceId: "cc0-jetrel-iron-shield",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_iron_sword",
      name: "iron sword",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "iron-sword 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-iron-sword",
      iconResourceId: "cc0-jetrel-iron-sword",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_lantern",
      name: "lantern",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "lantern 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-lantern",
      iconResourceId: "cc0-jetrel-lantern",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_leather_armor",
      name: "leather armor",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "leather-armor 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-leather-armor",
      iconResourceId: "cc0-jetrel-leather-armor",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_leather_patch",
      name: "leather patch",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "leather-patch 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-leather-patch",
      iconResourceId: "cc0-jetrel-leather-patch",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_letter",
      name: "letter",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "letter 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-letter",
      iconResourceId: "cc0-jetrel-letter",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_mage_hat",
      name: "mage hat",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "mage-hat 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-mage-hat",
      iconResourceId: "cc0-jetrel-mage-hat",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_mage_staff",
      name: "mage staff",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "mage-staff 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-mage-staff",
      iconResourceId: "cc0-jetrel-mage-staff",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_mana_tea",
      name: "mana tea",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "mana-tea 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-mana-tea",
      iconResourceId: "cc0-jetrel-mana-tea",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_map",
      name: "map",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "map 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-map",
      iconResourceId: "cc0-jetrel-map",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_meat",
      name: "meat",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "meat 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-meat",
      iconResourceId: "cc0-jetrel-meat",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_medal",
      name: "medal",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "medal 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-medal",
      iconResourceId: "cc0-jetrel-medal",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_milk",
      name: "milk",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "milk 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-milk",
      iconResourceId: "cc0-jetrel-milk",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_mirror",
      name: "mirror",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "mirror 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-mirror",
      iconResourceId: "cc0-jetrel-mirror",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_mushroom",
      name: "mushroom",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "mushroom 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-mushroom",
      iconResourceId: "cc0-jetrel-mushroom",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_mystic_robe",
      name: "mystic robe",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "mystic-robe 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-mystic-robe",
      iconResourceId: "cc0-jetrel-mystic-robe",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_necklace",
      name: "necklace",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "necklace 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-necklace",
      iconResourceId: "cc0-jetrel-necklace",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_net",
      name: "net",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "net 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-net",
      iconResourceId: "cc0-jetrel-net",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_notebook",
      name: "notebook",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "notebook 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-notebook",
      iconResourceId: "cc0-jetrel-notebook",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_oak_shield",
      name: "oak shield",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "oak-shield 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-oak-shield",
      iconResourceId: "cc0-jetrel-oak-shield",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_oil",
      name: "oil",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "oil 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-oil",
      iconResourceId: "cc0-jetrel-oil",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_old_key_scroll",
      name: "old key scroll",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "old-key-scroll 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-old-key-scroll",
      iconResourceId: "cc0-jetrel-old-key-scroll",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_pass",
      name: "pass",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "pass 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-pass",
      iconResourceId: "cc0-jetrel-pass",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_pearl",
      name: "pearl",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "pearl 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-pearl",
      iconResourceId: "cc0-jetrel-pearl",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_phoenix_down",
      name: "phoenix down",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "phoenix-down 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-phoenix-down",
      iconResourceId: "cc0-jetrel-phoenix-down",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_pickaxe",
      name: "pickaxe",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "pickaxe 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-pickaxe",
      iconResourceId: "cc0-jetrel-pickaxe",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_potato",
      name: "potato",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "potato 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-potato",
      iconResourceId: "cc0-jetrel-potato",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_quill",
      name: "quill",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "quill 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-quill",
      iconResourceId: "cc0-jetrel-quill",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_radio",
      name: "radio",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "radio 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-radio",
      iconResourceId: "cc0-jetrel-radio",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_rice_ball",
      name: "rice ball",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "rice-ball 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-rice-ball",
      iconResourceId: "cc0-jetrel-rice-ball",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_ring",
      name: "ring",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "ring 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-ring",
      iconResourceId: "cc0-jetrel-ring",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_rope",
      name: "rope",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "rope 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-rope",
      iconResourceId: "cc0-jetrel-rope",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_scale",
      name: "scale",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "scale 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-scale",
      iconResourceId: "cc0-jetrel-scale",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_scout_dagger",
      name: "scout dagger",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "scout-dagger 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-scout-dagger",
      iconResourceId: "cc0-jetrel-scout-dagger",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_screw",
      name: "screw",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "screw 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-screw",
      iconResourceId: "cc0-jetrel-screw",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_seed_bag",
      name: "seed bag",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "seed-bag 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-seed-bag",
      iconResourceId: "cc0-jetrel-seed-bag",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_shell",
      name: "shell",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "shell 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-shell",
      iconResourceId: "cc0-jetrel-shell",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_skill_book",
      name: "skill book",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "skill-book 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-skill-book",
      iconResourceId: "cc0-jetrel-skill-book",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_sleeping_powder",
      name: "sleeping powder",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "sleeping-powder 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-sleeping-powder",
      iconResourceId: "cc0-jetrel-sleeping-powder",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_smoke_bomb",
      name: "smoke bomb",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "smoke-bomb 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-smoke-bomb",
      iconResourceId: "cc0-jetrel-smoke-bomb",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_soap",
      name: "soap",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "soap 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-soap",
      iconResourceId: "cc0-jetrel-soap",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_soup",
      name: "soup",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "soup 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-soup",
      iconResourceId: "cc0-jetrel-soup",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_stamina_drink",
      name: "stamina drink",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "stamina-drink 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-stamina-drink",
      iconResourceId: "cc0-jetrel-stamina-drink",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_steel_armor",
      name: "steel armor",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "steel-armor 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-steel-armor",
      iconResourceId: "cc0-jetrel-steel-armor",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_steel_sword",
      name: "steel sword",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "steel-sword 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-steel-sword",
      iconResourceId: "cc0-jetrel-steel-sword",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_stew",
      name: "stew",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "stew 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-stew",
      iconResourceId: "cc0-jetrel-stew",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_strawberry",
      name: "strawberry",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "strawberry 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-strawberry",
      iconResourceId: "cc0-jetrel-strawberry",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_tea",
      name: "tea",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "tea 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-tea",
      iconResourceId: "cc0-jetrel-tea",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_thunder_stone",
      name: "thunder stone",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "thunder-stone 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-thunder-stone",
      iconResourceId: "cc0-jetrel-thunder-stone",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_ticket",
      name: "ticket",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "ticket 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-ticket",
      iconResourceId: "cc0-jetrel-ticket",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_tomato",
      name: "tomato",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "tomato 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-tomato",
      iconResourceId: "cc0-jetrel-tomato",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_torch",
      name: "torch",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "torch 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-torch",
      iconResourceId: "cc0-jetrel-torch",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_traveler_badge",
      name: "traveler badge",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "traveler-badge 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-traveler-badge",
      iconResourceId: "cc0-jetrel-traveler-badge",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_traveler_hat",
      name: "traveler hat",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "traveler-hat 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-traveler-hat",
      iconResourceId: "cc0-jetrel-traveler-hat",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_trophy",
      name: "trophy",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "trophy 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-trophy",
      iconResourceId: "cc0-jetrel-trophy",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_warp_scroll",
      name: "warp scroll",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "warp-scroll 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-warp-scroll",
      iconResourceId: "cc0-jetrel-warp-scroll",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_water_flask",
      name: "water flask",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "water-flask 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-water-flask",
      iconResourceId: "cc0-jetrel-water-flask",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_watering_can",
      name: "watering can",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "watering-can 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-watering-can",
      iconResourceId: "cc0-jetrel-watering-can",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_wind_feather",
      name: "wind feather",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "wind-feather 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-wind-feather",
      iconResourceId: "cc0-jetrel-wind-feather",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_wine",
      name: "wine",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "wine 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-wine",
      iconResourceId: "cc0-jetrel-wine",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_wood",
      name: "wood",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "wood 기본 아이템입니다.",
      imageResourceId: "cc0-jetrel-wood",
      iconResourceId: "cc0-jetrel-wood",
      occasion: "never",
      consumable: false,
    }),
    // 생성 아이콘 100종 중 소비품·재료·열쇠 계열 (무기·방어구·장식은 equipment 로 분리).
    ...generatedItemRecords(),
  ];
  applyGeneratedBattleEffectItemBindings(records);
  return records;
}
