import type { EquipmentRecord } from "../types";
import { normalizeEquipmentRecord } from "../databaseRecordModel";
import { DEFAULT_ACTOR_ID, DEFAULT_CLASS_ID, DEFAULT_EQUIPMENT_ID } from "./constants";
import { defaultCatalogFillEquipmentRecords } from "./defaultCatalogFillEquipment";
import { generatedEquipmentRecords } from "./generatedItemRecords";
import {
  ACTOR_GUARDIAN_ID,
  ACTOR_MAGE_ID,
  ACTOR_CLERIC_ID,
  ACTOR_RANGER_ID,
  ACTOR_SCOUT_ID,
  ALL_ACTOR_IDS,
  ALL_CLASS_IDS,
  CLASS_CLERIC_ID,
  CLASS_GUARDIAN_ID,
  CLASS_MAGE_ID,
  CLASS_RANGER_ID,
  CLASS_SCOUT_ID,
  EQUIPMENT_FOCUS_CHARM_ID,
  EQUIPMENT_LEATHER_ARMOR_ID,
  EQUIPMENT_MAGE_STAFF_ID,
  EQUIPMENT_MYSTIC_ROBE_ID,
  EQUIPMENT_OAK_SHIELD_ID,
  EQUIPMENT_SCOUT_DAGGER_ID,
  EQUIPMENT_TRAVELER_HAT_ID,
} from "./defaultDatabaseRecordIds";

export function defaultEquipmentRecords(): EquipmentRecord[] {
  return [
    normalizeEquipmentRecord({
      id: DEFAULT_EQUIPMENT_ID,
      name: "청동 검",
      slot: "weapon",
      price: 100,
      imageResourceId: "cc0-jetrel-bronze-sword",
      iconResourceId: "cc0-jetrel-bronze-sword",
      description: "명중 손실 없이 기본기에 충실한 초보 전사의 기준 검입니다.",
      statBonuses: { attack: 8, defense: 0, mind: 0, agility: 0 },
      equippableActorIds: [DEFAULT_ACTOR_ID, ACTOR_GUARDIAN_ID],
      equippableClassIds: [DEFAULT_CLASS_ID, CLASS_GUARDIAN_ID],
    }),
    normalizeEquipmentRecord({
      id: EQUIPMENT_MAGE_STAFF_ID,
      name: "수습 지팡이",
      slot: "weapon",
      price: 120,
      imageResourceId: "cc0-jetrel-mage-staff",
      iconResourceId: "cc0-jetrel-mage-staff",
      description: "낮은 물리 화력 대신 주문 정신력을 안정적으로 높이는 입문 지팡이입니다.",
      statBonuses: { attack: 3, defense: 0, mind: 7, agility: 0 },
      attackElementIds: ["hit"],
      accuracy: 96,
      equippableActorIds: [ACTOR_MAGE_ID, ACTOR_CLERIC_ID],
      equippableClassIds: [CLASS_MAGE_ID, CLASS_CLERIC_ID],
    }),
    normalizeEquipmentRecord({
      id: EQUIPMENT_SCOUT_DAGGER_ID,
      name: "정찰 단검",
      slot: "weapon",
      price: 90,
      imageResourceId: "cc0-jetrel-scout-dagger",
      iconResourceId: "cc0-jetrel-scout-dagger",
      description: "민첩을 보태고 약점을 노려 치명타를 내는 정찰병의 기습 단검입니다.",
      statBonuses: { attack: 5, defense: 0, mind: 0, agility: 3 },
      attackElementIds: ["sword"],
      criticalRate: 4,
      accuracy: 96,
      equippableActorIds: [DEFAULT_ACTOR_ID, ACTOR_SCOUT_ID, ACTOR_RANGER_ID],
      equippableClassIds: [DEFAULT_CLASS_ID, CLASS_SCOUT_ID, CLASS_RANGER_ID],
    }),
    normalizeEquipmentRecord({
      id: "equip_iron_sword",
      name: "철 검",
      slot: "weapon",
      price: 180,
      imageResourceId: "cc0-jetrel-iron-sword",
      iconResourceId: "cc0-jetrel-iron-sword",
      description: "청동 검보다 무겁지만 검술의 균형을 잃지 않은 표준 철제 무기입니다.",
      statBonuses: { attack: 14, defense: 0, mind: 0, agility: 0 },
      attackElementIds: ["sword"],
      accuracy: 97,
      equippableActorIds: [DEFAULT_ACTOR_ID, ACTOR_GUARDIAN_ID],
      equippableClassIds: [DEFAULT_CLASS_ID, CLASS_GUARDIAN_ID],
    }),
    normalizeEquipmentRecord({
      id: "equip_steel_sword",
      name: "강철 검",
      slot: "weapon",
      price: 260,
      imageResourceId: "cc0-jetrel-steel-sword",
      iconResourceId: "cc0-jetrel-steel-sword",
      description: "높은 공격력과 맞바꿔 민첩과 명중을 조금 포기한 강철 장검입니다.",
      statBonuses: { attack: 20, defense: 0, mind: 0, agility: -1 },
      attackElementIds: ["sword"],
      accuracy: 92,
      equippableActorIds: [DEFAULT_ACTOR_ID, ACTOR_GUARDIAN_ID],
      equippableClassIds: [DEFAULT_CLASS_ID, CLASS_GUARDIAN_ID],
    }),
    normalizeEquipmentRecord({
      id: "equip_short_sword",
      name: "단검",
      slot: "weapon",
      price: 80,
      imageResourceId: "cc0-jetrel-scout-dagger",
      iconResourceId: "cc0-jetrel-scout-dagger",
      description: "위력은 낮아도 정확하게 찌르며 선수를 잡기 좋은 예비 칼날입니다.",
      statBonuses: { attack: 4, defense: 0, mind: 0, agility: 2 },
      attackElementIds: ["sword"],
      criticalRate: 2,
      accuracy: 100,
      equippableActorIds: [DEFAULT_ACTOR_ID, ACTOR_SCOUT_ID, ACTOR_RANGER_ID],
      equippableClassIds: [DEFAULT_CLASS_ID, CLASS_SCOUT_ID, CLASS_RANGER_ID],
    }),
    normalizeEquipmentRecord({
      id: EQUIPMENT_OAK_SHIELD_ID,
      name: "참나무 방패",
      slot: "shield",
      price: 80,
      imageResourceId: "cc0-jetrel-oak-shield",
      iconResourceId: "cc0-jetrel-oak-shield",
      description: "속도 손실 없이 방어를 보태는 전열 입문용 참나무 방패입니다.",
      statBonuses: { attack: 0, defense: 5, mind: 0, agility: 0 },
      equippableActorIds: [DEFAULT_ACTOR_ID, ACTOR_GUARDIAN_ID, ACTOR_CLERIC_ID],
      equippableClassIds: [DEFAULT_CLASS_ID, CLASS_GUARDIAN_ID, CLASS_CLERIC_ID],
    }),
    normalizeEquipmentRecord({
      id: EQUIPMENT_LEATHER_ARMOR_ID,
      name: "가죽 갑옷",
      slot: "armor",
      price: 140,
      imageResourceId: "cc0-jetrel-leather-armor",
      iconResourceId: "cc0-jetrel-leather-armor",
      description: "어떤 민첩한 전사도 부담 없이 입을 수 있는 물리 방어의 기준 갑옷입니다.",
      statBonuses: { attack: 0, defense: 6, mind: 0, agility: 0 },
      equippableActorIds: [DEFAULT_ACTOR_ID, ACTOR_GUARDIAN_ID, ACTOR_SCOUT_ID, ACTOR_RANGER_ID],
      equippableClassIds: [DEFAULT_CLASS_ID, CLASS_GUARDIAN_ID, CLASS_SCOUT_ID, CLASS_RANGER_ID],
    }),
    normalizeEquipmentRecord({
      id: EQUIPMENT_MYSTIC_ROBE_ID,
      name: "견습 로브",
      slot: "armor",
      price: 130,
      imageResourceId: "cc0-jetrel-mystic-robe",
      iconResourceId: "cc0-jetrel-mystic-robe",
      description: "낮은 방어를 정신력으로 보완해 주문 수련에 집중시키는 기본 로브입니다.",
      statBonuses: { attack: 0, defense: 3, mind: 4, agility: 0 },
      equippableActorIds: [ACTOR_MAGE_ID, ACTOR_CLERIC_ID],
      equippableClassIds: [CLASS_MAGE_ID, CLASS_CLERIC_ID],
    }),
    normalizeEquipmentRecord({
      id: EQUIPMENT_TRAVELER_HAT_ID,
      name: "여행자 모자",
      slot: "helmet",
      price: 80,
      imageResourceId: "cc0-jetrel-traveler-hat",
      iconResourceId: "cc0-jetrel-traveler-hat",
      description: "방어와 정신력을 고르게 보태며 수면에 빠질 위험을 조금 낮추는 모자입니다.",
      statBonuses: { attack: 0, defense: 2, mind: 1, agility: 0 },
      stateResistanceChance: 20,
      stateDefenseIds: ["state_sleep"],
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: EQUIPMENT_FOCUS_CHARM_ID,
      name: "집중 부적",
      slot: "accessory",
      price: 190,
      imageResourceId: "cc0-jetrel-focus-charm",
      iconResourceId: "cc0-jetrel-focus-charm",
      description: "정신과 몸놀림을 함께 가다듬고 침묵 주문에 버틸 틈을 주는 부적입니다.",
      statBonuses: { attack: 0, defense: 0, mind: 2, agility: 2 },
      stateResistanceChance: 25,
      stateDefenseIds: ["state_silence"],
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    // 손수 만든 고전 장비는 초중반의 기준·상태 대응 단계이고, 생성 팩은 명중·치명타·속성·광역 특화 단계를 맡는다.
    normalizeEquipmentRecord({
      id: "equip_iron_shield",
      name: "용병 철갑 방패",
      slot: "shield",
      price: 220,
      imageResourceId: "cc0-jetrel-iron-shield",
      iconResourceId: "cc0-jetrel-iron-shield",
      description: "민첩을 희생해 철벽을 세우고 마비 충격에도 버티는 용병 방패입니다.",
      statBonuses: { attack: 0, defense: 9, mind: 0, agility: -1 },
      stateResistanceChance: 25,
      stateDefenseIds: ["state_paralysis"],
      equippableActorIds: [DEFAULT_ACTOR_ID, ACTOR_GUARDIAN_ID, ACTOR_CLERIC_ID],
      equippableClassIds: [DEFAULT_CLASS_ID, CLASS_GUARDIAN_ID, CLASS_CLERIC_ID],
    }),
    normalizeEquipmentRecord({
      id: "equip_steel_armor",
      name: "용병대 강철 흉갑",
      slot: "armor",
      price: 360,
      imageResourceId: "cc0-jetrel-steel-armor",
      iconResourceId: "cc0-jetrel-steel-armor",
      description: "발이 느려지는 대신 화염 피해를 줄이고 전열을 오래 지키는 흉갑입니다.",
      statBonuses: { attack: 0, defense: 13, mind: 0, agility: -1 },
      elementalDefenseIds: ["fire"],
      equippableActorIds: [DEFAULT_ACTOR_ID, ACTOR_GUARDIAN_ID, ACTOR_SCOUT_ID, ACTOR_RANGER_ID],
      equippableClassIds: [DEFAULT_CLASS_ID, CLASS_GUARDIAN_ID, CLASS_SCOUT_ID, CLASS_RANGER_ID],
    }),
    normalizeEquipmentRecord({
      id: "equip_mage_hat",
      name: "별무늬 수습모",
      slot: "helmet",
      price: 180,
      imageResourceId: "cc0-jetrel-mage-hat",
      iconResourceId: "cc0-jetrel-mage-hat",
      description: "주문 집중과 가벼운 몸놀림을 돕고 침묵 저항까지 익히게 하는 수습모입니다.",
      statBonuses: { attack: 0, defense: 1, mind: 4, agility: 1 },
      stateResistanceChance: 30,
      stateDefenseIds: ["state_silence"],
      equippableActorIds: [ACTOR_MAGE_ID, ACTOR_CLERIC_ID],
      equippableClassIds: [CLASS_MAGE_ID, CLASS_CLERIC_ID],
    }),
    normalizeEquipmentRecord({
      id: "equip_gloves",
      name: "검객 손보호대",
      slot: "accessory",
      price: 120,
      imageResourceId: "cc0-jetrel-gloves",
      iconResourceId: "cc0-jetrel-gloves",
      description: "손잡이를 단단히 고정해 공격 속도를 유지하면서 치명타 기회를 높입니다.",
      statBonuses: { attack: 2, defense: 0, mind: 0, agility: 1 },
      criticalRate: 2,
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_boots",
      name: "바람길 가죽 장화",
      slot: "accessory",
      price: 170,
      imageResourceId: "cc0-jetrel-boots",
      iconResourceId: "cc0-jetrel-boots",
      description: "방어 한 겹을 남긴 채 순수한 기동력을 크게 끌어올리는 여행 장화입니다.",
      statBonuses: { attack: 0, defense: 1, mind: 0, agility: 4 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_cloak",
      name: "순례자 방풍 망토",
      slot: "accessory",
      price: 180,
      imageResourceId: "cc0-jetrel-cloak",
      iconResourceId: "cc0-jetrel-cloak",
      description: "비바람과 냉기를 막아 물리·마법 방어를 함께 챙기는 순례자 망토입니다.",
      statBonuses: { attack: 0, defense: 2, mind: 2, agility: 0 },
      elementalDefenseIds: ["ice"],
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_ring",
      name: "마력 각인 반지",
      slot: "accessory",
      price: 170,
      imageResourceId: "cc0-jetrel-ring",
      iconResourceId: "cc0-jetrel-ring",
      description: "정신력을 안정시키며 침묵에 걸릴 가능성을 낮추는 은빛 주문 반지입니다.",
      statBonuses: { attack: 0, defense: 0, mind: 3, agility: 0 },
      stateResistanceChance: 20,
      stateDefenseIds: ["state_silence"],
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_necklace",
      name: "청옥 수호 목걸이",
      slot: "accessory",
      price: 230,
      imageResourceId: "cc0-jetrel-necklace",
      iconResourceId: "cc0-jetrel-necklace",
      description: "방어와 정신력을 함께 올리고 맹독이 스미는 것을 억누르는 청옥 목걸이입니다.",
      statBonuses: { attack: 0, defense: 1, mind: 4, agility: 0 },
      stateResistanceChance: 35,
      stateDefenseIds: ["state_deep_poison"],
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_focus_ring",
      name: "푸른별 집중 반지",
      slot: "accessory",
      price: 290,
      imageResourceId: "cc0-jetrel-focus-ring",
      iconResourceId: "cc0-jetrel-focus-ring",
      description: "다른 능력을 포기해 주문 정신력을 극대화하고 침묵을 절반가량 막는 반지입니다.",
      statBonuses: { attack: 0, defense: 0, mind: 6, agility: 0 },
      stateResistanceChance: 50,
      stateDefenseIds: ["state_silence"],
      equippableActorIds: [ACTOR_MAGE_ID, ACTOR_CLERIC_ID],
      equippableClassIds: [CLASS_MAGE_ID, CLASS_CLERIC_ID],
    }),
    // 생성 아이콘 100종 중 무기·방어구·장식 계열. 가격은 특수 축의 강도와 명중·능력치 대가를 함께 반영한다.
    ...generatedEquipmentRecords(),
    ...defaultCatalogFillEquipmentRecords(),
  ];
}
