import type { ItemRecord } from "../types";
import { normalizeItemRecord } from "../databaseRecordModel";
import { DEFAULT_ANIMATION_ID, DEFAULT_ITEM_ID, DEFAULT_STATE_ID } from "./constants";

export function defaultItemRecords(): ItemRecord[] {
  return [
    normalizeItemRecord({
      id: DEFAULT_ITEM_ID,
      name: "회복약",
      scope: "ally",
      price: 50,
      skillId: "skill_item_potion",
      description: "아군 하나의 HP를 50 회복합니다.",
      imageResourceId: "cc0-jetrel-potion-red",
      iconResourceId: "cc0-jetrel-potion-red",
      animationId: "anim_heal",
      hpRecovery: { flat: 50, percentMax: 0 },
    }),
    normalizeItemRecord({
      id: "item_ether",
      name: "마력약",
      scope: "ally",
      price: 120,
      skillId: "skill_item_ether",
      description: "아군 하나의 MP를 30 회복합니다.",
      imageResourceId: "cc0-jetrel-ether-blue",
      iconResourceId: "cc0-jetrel-ether-blue",
      animationId: "anim_magic",
      mpRecovery: { flat: 30, percentMax: 0 },
    }),
    normalizeItemRecord({
      id: "item_antidote",
      name: "해독초",
      scope: "ally",
      price: 30,
      description: "독 상태를 해제합니다.",
      imageResourceId: "cc0-jetrel-antidote-green",
      iconResourceId: "cc0-jetrel-antidote-green",
      stateEffects: [{ stateId: DEFAULT_STATE_ID, chance: 100, operation: "remove" }],
    }),
    normalizeItemRecord({
      id: "item_wake_herb",
      name: "각성초",
      scope: "ally",
      price: 40,
      description: "수면 상태를 해제합니다.",
      imageResourceId: "cc0-jetrel-wake-herb",
      iconResourceId: "cc0-jetrel-wake-herb",
      stateEffects: [{ stateId: "state_sleep", chance: 100, operation: "remove" }],
    }),
    normalizeItemRecord({
      id: "item_poison_dart",
      name: "독침",
      scope: "enemy",
      price: 80,
      skillId: "skill_poison_sting",
      description: "적 하나에게 약한 피해를 주고 독 상태를 노립니다.",
      imageResourceId: "cc0-jetrel-poison-dart",
      iconResourceId: "cc0-jetrel-poison-dart",
      animationId: "anim_poison",
      stateEffects: [{ stateId: DEFAULT_STATE_ID, chance: 70, operation: "add" }],
    }),
    normalizeItemRecord({
      id: "item_old_key",
      name: "낡은 열쇠",
      scope: "none",
      price: 0,
      description: "오래된 문을 열 수 있을 것 같은 열쇠입니다.",
      imageResourceId: "cc0-jetrel-old-key-scroll",
      iconResourceId: "cc0-jetrel-old-key-scroll",
      type: "normalGoods",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_hi_potion",
      name: "상급 회복약",
      scope: "ally",
      price: 180,
      skillId: "skill_item_potion",
      description: "전투와 탐험 중 아군 하나의 HP를 크게 회복하는 상급 약입니다.",
      imageResourceId: "cc0-jetrel-potion-red",
      iconResourceId: "cc0-jetrel-potion-red",
      animationId: "anim_heal",
    }),
    normalizeItemRecord({
      id: "item_elixir",
      name: "엘릭서",
      scope: "ally",
      price: 600,
      skillId: "skill_item_ether",
      description: "귀한 마력 회복약입니다. 장기 던전의 후반부 보상으로 쓰기 좋습니다.",
      imageResourceId: "cc0-jetrel-ether-blue",
      iconResourceId: "cc0-jetrel-ether-blue",
      animationId: "anim_magic",
    }),
    normalizeItemRecord({
      id: "item_panacea",
      name: "만능약",
      scope: "ally",
      price: 220,
      description: "독과 수면처럼 흔한 상태이상을 한 번에 정리하는 치료약입니다.",
      imageResourceId: "cc0-jetrel-antidote-green",
      iconResourceId: "cc0-jetrel-antidote-green",
      stateEffects: [
        { stateId: DEFAULT_STATE_ID, chance: 100, operation: "remove" },
        { stateId: "state_sleep", chance: 100, operation: "remove" },
      ],
    }),
    normalizeItemRecord({
      id: "item_smelling_salts",
      name: "각성 가루",
      scope: "ally",
      price: 75,
      description: "수면에 빠진 아군을 깨우는 휴대용 가루입니다.",
      imageResourceId: "cc0-jetrel-wake-herb",
      iconResourceId: "cc0-jetrel-wake-herb",
      stateEffects: [{ stateId: "state_sleep", chance: 100, operation: "remove" }],
    }),
    normalizeItemRecord({
      id: "item_throwing_knife",
      name: "투척 단검",
      scope: "enemy",
      price: 110,
      skillId: "skill_poison_sting",
      description: "적 하나에게 던져 피해를 주는 전투용 소모품입니다.",
      imageResourceId: "cc0-jetrel-scout-dagger",
      iconResourceId: "cc0-jetrel-scout-dagger",
      animationId: "anim_poison",
      stateEffects: [{ stateId: DEFAULT_STATE_ID, chance: 35, operation: "add" }],
    }),
    normalizeItemRecord({
      id: "item_poison_vial",
      name: "독병",
      scope: "enemy",
      price: 140,
      skillId: "skill_poison_sting",
      description: "적 하나에게 독을 노리는 투척용 병입니다.",
      imageResourceId: "cc0-jetrel-poison-dart",
      iconResourceId: "cc0-jetrel-poison-dart",
      animationId: "anim_poison",
      stateEffects: [{ stateId: DEFAULT_STATE_ID, chance: 85, operation: "add" }],
    }),
    normalizeItemRecord({
      id: "item_warp_scroll",
      name: "귀환 주문서",
      scope: "none",
      price: 250,
      description: "마을이나 안전 지점으로 돌아가는 이벤트용 핵심 아이템입니다.",
      imageResourceId: "cc0-jetrel-old-key-scroll",
      iconResourceId: "cc0-jetrel-old-key-scroll",
      type: "normalGoods",
      occasion: "field",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_sword_manual",
      name: "검술 교본",
      scope: "ally",
      price: 320,
      skillId: "skill_sword_slash",
      description: "검격 계열 기술을 익히게 하는 스킬북형 아이템입니다.",
      imageResourceId: "cc0-jetrel-bronze-sword",
      iconResourceId: "cc0-jetrel-bronze-sword",
      type: "book",
      occasion: "field",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_magic_primer",
      name: "마법 입문서",
      scope: "ally",
      price: 360,
      skillId: "skill_arcane_bolt",
      description: "기초 공격 마법을 익히게 하는 스킬북형 아이템입니다.",
      imageResourceId: "cc0-jetrel-mage-staff",
      iconResourceId: "cc0-jetrel-mage-staff",
      type: "book",
      occasion: "field",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_guard_talisman",
      name: "수호 부적",
      scope: "ally",
      price: 260,
      skillId: "skill_focus",
      description: "전투 중 방어적인 버프나 이벤트 보상으로 쓰기 좋은 부적입니다.",
      imageResourceId: "cc0-jetrel-oak-shield",
      iconResourceId: "cc0-jetrel-oak-shield",
      animationId: DEFAULT_ANIMATION_ID,
    }),
    normalizeItemRecord({
      id: "item_armor_patch",
      name: "가죽 수선 도구",
      scope: "none",
      price: 90,
      description: "방어구 수리 이벤트나 제작 재료로 쓰기 좋은 일반 아이템입니다.",
      imageResourceId: "cc0-jetrel-leather-armor",
      iconResourceId: "cc0-jetrel-leather-armor",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_mystic_cloth",
      name: "신비한 천",
      scope: "none",
      price: 160,
      description: "로브 제작, 마법 의식, 퀘스트 재료에 어울리는 소재입니다.",
      imageResourceId: "cc0-jetrel-mystic-robe",
      iconResourceId: "cc0-jetrel-mystic-robe",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_traveler_badge",
      name: "여행자 표식",
      scope: "none",
      price: 0,
      description: "길드 가입, 통행 허가, 동료 합류 조건에 쓰기 좋은 키 아이템입니다.",
      imageResourceId: "cc0-jetrel-traveler-hat",
      iconResourceId: "cc0-jetrel-traveler-hat",
      type: "normalGoods",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_lucky_charm",
      name: "행운의 부적",
      scope: "none",
      price: 300,
      description: "보물상자, 퀘스트 보상, 희귀 이벤트 조건에 쓰기 좋은 부적입니다.",
      imageResourceId: "cc0-jetrel-focus-charm",
      iconResourceId: "cc0-jetrel-focus-charm",
      type: "normalGoods",
      occasion: "never",
      consumable: false,
    }),
  ];
}
