import type { ItemRecord } from "../types";
import { normalizeItemRecord } from "../databaseRecordModel";
import { DEFAULT_ITEM_ID, DEFAULT_STATE_ID } from "./constants";
import { generatedItemRecords } from "./generatedItemRecords";
import { expandedDefaultItemRecords } from "./defaultExpandedItemRecords";
import { applyGeneratedBattleEffectItemBindings } from "./generatedBattleEffectBindings";

export function defaultItemRecords(): ItemRecord[] {
  const records = [
    normalizeItemRecord({
      id: DEFAULT_ITEM_ID,
      name: "회복약",
      type: "medicine",
      scope: "ally",
      price: 50,
      description: "아군 하나의 HP를 50 회복합니다.",
      imageResourceId: "cc0-jetrel-potion-red",
      iconResourceId: "cc0-jetrel-potion-red",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      hpRecovery: { flat: 50, percentMax: 0 },
      skillId: "skill_item_potion",
    }),
    normalizeItemRecord({
      id: "item_capture_orb",
      name: "포획 구슬",
      type: "special",
      scope: "enemy",
      price: 80,
      description: "약해진 몬스터를 포획하는 기본 구슬입니다.",
      imageResourceId: "cc0-jetrel-capture-orb",
      iconResourceId: "cc0-jetrel-capture-orb",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
      captureProfile: { multiplier: 1 },
    }),
    normalizeItemRecord({
      id: "item_ether",
      name: "마력약",
      type: "medicine",
      scope: "ally",
      price: 120,
      description: "아군 하나의 MP를 30 회복합니다.",
      imageResourceId: "cc0-jetrel-ether-blue",
      iconResourceId: "cc0-jetrel-ether-blue",
      animationId: "anim_magic",
      occasion: "always",
      consumable: true,
      mpRecovery: { flat: 30, percentMax: 0 },
      skillId: "skill_item_ether",
    }),
    normalizeItemRecord({
      id: "item_antidote",
      name: "해독초",
      type: "medicine",
      scope: "ally",
      price: 30,
      description: "독 상태를 해제합니다.",
      imageResourceId: "cc0-jetrel-antidote-green",
      iconResourceId: "cc0-jetrel-antidote-green",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      healStateIds: [DEFAULT_STATE_ID],
      stateEffects: [{ stateId: DEFAULT_STATE_ID, chance: 100, operation: "remove" }],
      skillId: "skill_item_antidote",
    }),
    normalizeItemRecord({
      id: "item_wake_herb",
      name: "각성초",
      type: "medicine",
      scope: "ally",
      price: 40,
      description: "수면 상태를 해제합니다.",
      imageResourceId: "cc0-jetrel-wake-herb",
      iconResourceId: "cc0-jetrel-wake-herb",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      healStateIds: ["state_sleep"],
      stateEffects: [{ stateId: "state_sleep", chance: 100, operation: "remove" }],
      skillId: "skill_item_wake",
    }),
    normalizeItemRecord({
      id: "item_poison_dart",
      name: "독침",
      type: "special",
      scope: "enemy",
      price: 80,
      description: "적 하나에게 약한 피해를 주고 독 상태를 노립니다.",
      imageResourceId: "cc0-jetrel-poison-dart",
      iconResourceId: "cc0-jetrel-poison-dart",
      skillId: "skill_poison_sting",
      animationId: "anim_poison",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_old_key",
      name: "낡은 열쇠",
      type: "normalGoods",
      scope: "none",
      price: 0,
      description: "오래된 문을 열 수 있을 것 같은 열쇠입니다.",
      imageResourceId: "cc0-jetrel-old-key",
      iconResourceId: "cc0-jetrel-old-key",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_hi_potion",
      name: "상급 회복약",
      type: "medicine",
      scope: "ally",
      price: 180,
      description: "아군 하나의 HP를 150 회복하는 상급 약입니다.",
      imageResourceId: "cc0-jetrel-hi-potion",
      iconResourceId: "cc0-jetrel-hi-potion",
      skillId: "skill_item_hi_potion",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      hpRecovery: { flat: 150, percentMax: 0 },
    }),
    normalizeItemRecord({
      id: "item_elixir",
      name: "엘릭서",
      type: "medicine",
      scope: "ally",
      price: 600,
      description: "아군 하나의 HP와 MP를 모두 크게 회복하는 귀한 약입니다.",
      imageResourceId: "cc0-jetrel-elixir",
      iconResourceId: "cc0-jetrel-elixir",
      skillId: "skill_item_elixir",
      animationId: "anim_magic",
      occasion: "always",
      consumable: true,
      hpRecovery: { flat: 0, percentMax: 100 },
      mpRecovery: { flat: 0, percentMax: 100 },
    }),
    normalizeItemRecord({
      id: "item_panacea",
      name: "만능약",
      type: "medicine",
      scope: "ally",
      price: 220,
      description: "독과 수면처럼 흔한 상태이상을 한 번에 정리하는 치료약입니다.",
      imageResourceId: "cc0-jetrel-panacea",
      iconResourceId: "cc0-jetrel-panacea",
      skillId: "skill_item_panacea",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      healStateIds: [DEFAULT_STATE_ID, "state_sleep"],
      stateEffects: [{ stateId: DEFAULT_STATE_ID, chance: 100, operation: "remove" }, { stateId: "state_sleep", chance: 100, operation: "remove" }],
    }),
    normalizeItemRecord({
      id: "item_smelling_salts",
      name: "각성 가루",
      type: "medicine",
      scope: "ally",
      price: 75,
      description: "수면에 빠진 아군을 깨우는 휴대용 가루입니다.",
      imageResourceId: "cc0-jetrel-smelling-salts",
      iconResourceId: "cc0-jetrel-smelling-salts",
      skillId: "skill_item_wake",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      healStateIds: ["state_sleep"],
      stateEffects: [{ stateId: "state_sleep", chance: 100, operation: "remove" }],
    }),
    normalizeItemRecord({
      id: "item_throwing_knife",
      name: "투척 단검",
      type: "special",
      scope: "enemy",
      price: 110,
      description: "적 하나에게 던져 피해를 주는 전투용 소모품입니다.",
      imageResourceId: "cc0-jetrel-throwing-knife",
      iconResourceId: "cc0-jetrel-throwing-knife",
      skillId: "skill_throwing_knife",
      animationId: "anim_arrow",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_poison_vial",
      name: "독병",
      type: "special",
      scope: "enemy",
      price: 140,
      description: "적 하나에게 독을 노리는 투척용 병입니다.",
      imageResourceId: "cc0-jetrel-poison-vial",
      iconResourceId: "cc0-jetrel-poison-vial",
      skillId: "skill_item_poison_vial",
      animationId: "anim_poison",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_warp_scroll",
      name: "귀환 주문서",
      type: "normalGoods",
      scope: "none",
      price: 250,
      description: "마을이나 안전 지점으로 돌아가는 이벤트 조건에 쓰는 주문서입니다.",
      imageResourceId: "cc0-jetrel-warp-scroll",
      iconResourceId: "cc0-jetrel-warp-scroll",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_sword_manual",
      name: "검술 교본",
      type: "book",
      scope: "ally",
      price: 320,
      description: "검격 기술을 익히게 하는 스킬북입니다.",
      imageResourceId: "cc0-jetrel-book-sword",
      iconResourceId: "cc0-jetrel-book-sword",
      skillId: "skill_sword_slash",
      learnedSkillId: "skill_sword_slash",
      occasion: "field",
      occasionField: true,
      occasionBattle: false,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_magic_primer",
      name: "마법 입문서",
      type: "book",
      scope: "ally",
      price: 360,
      description: "기초 공격 마법(마법탄)을 익히게 하는 스킬북입니다.",
      imageResourceId: "cc0-jetrel-book-magic",
      iconResourceId: "cc0-jetrel-book-magic",
      skillId: "skill_arcane_bolt",
      learnedSkillId: "skill_arcane_bolt",
      occasion: "field",
      occasionField: true,
      occasionBattle: false,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_guard_talisman",
      name: "수호 부적",
      type: "special",
      scope: "ally",
      price: 260,
      description: "전투 중 아군의 방어를 높이는 부적입니다.",
      imageResourceId: "cc0-jetrel-talisman",
      iconResourceId: "cc0-jetrel-talisman",
      skillId: "skill_item_guard",
      activateSkillId: "skill_item_guard",
      animationId: "anim_heal",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_armor_patch",
      name: "가죽 수선 도구",
      type: "normalGoods",
      scope: "none",
      price: 90,
      description: "방어구 수리 이벤트나 제작 재료로 쓰기 좋은 일반 아이템입니다.",
      imageResourceId: "cc0-jetrel-repair-kit",
      iconResourceId: "cc0-jetrel-repair-kit",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_mystic_cloth",
      name: "신비한 천",
      type: "normalGoods",
      scope: "none",
      price: 160,
      description: "로브 제작, 마법 의식, 퀘스트 재료에 어울리는 소재입니다.",
      imageResourceId: "cc0-jetrel-mystic-cloth",
      iconResourceId: "cc0-jetrel-mystic-cloth",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_traveler_badge",
      name: "여행자 표식",
      type: "normalGoods",
      scope: "none",
      price: 0,
      description: "길드 가입, 통행 허가, 동료 합류 조건에 쓰기 좋은 키 아이템입니다.",
      imageResourceId: "cc0-jetrel-traveler-badge",
      iconResourceId: "cc0-jetrel-traveler-badge",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_lucky_charm",
      name: "행운의 부적",
      type: "normalGoods",
      scope: "none",
      price: 300,
      description: "보물상자, 퀘스트 보상, 희귀 이벤트 조건에 쓰기 좋은 부적입니다.",
      imageResourceId: "cc0-jetrel-lucky-charm",
      iconResourceId: "cc0-jetrel-lucky-charm",
      occasion: "never",
      consumable: false,
    }),
    ...expandedDefaultItemRecords(),
    // 생성 아이콘 100종 중 소비품·재료·열쇠 계열 (무기·방어구·장식은 equipment 로 분리).
    ...generatedItemRecords(),
  ];
  applyGeneratedBattleEffectItemBindings(records);
  return records;
}
