import type { EquipmentRecord } from "../types";
import { normalizeEquipmentRecord } from "../databaseRecordModel";
import { DEFAULT_ACTOR_ID, DEFAULT_CLASS_ID, DEFAULT_EQUIPMENT_ID } from "./constants";
import { generatedEquipmentRecords } from "./generatedItemRecords";
import {
  ACTOR_GUARDIAN_ID,
  ACTOR_MAGE_ID,
  ACTOR_CLERIC_ID,
  ACTOR_RANGER_ID,
  ACTOR_SCOUT_ID,
  ALL_ACTOR_IDS,
  ALL_CLASS_IDS,
  CLASS_CLERIC_ID,
  CLASS_GUARDIAN_ID,
  CLASS_MAGE_ID,
  CLASS_RANGER_ID,
  CLASS_SCOUT_ID,
  EQUIPMENT_FOCUS_CHARM_ID,
  EQUIPMENT_LEATHER_ARMOR_ID,
  EQUIPMENT_MAGE_STAFF_ID,
  EQUIPMENT_MYSTIC_ROBE_ID,
  EQUIPMENT_OAK_SHIELD_ID,
  EQUIPMENT_SCOUT_DAGGER_ID,
  EQUIPMENT_TRAVELER_HAT_ID,
} from "./defaultDatabaseRecordIds";

export function defaultEquipmentRecords(): EquipmentRecord[] {
  return [
    normalizeEquipmentRecord({
      id: DEFAULT_EQUIPMENT_ID,
      name: "청동 검",
      slot: "weapon",
      price: 100,
      imageResourceId: "cc0-jetrel-bronze-sword",
      iconResourceId: "cc0-jetrel-bronze-sword",
      description: "균형 잡힌 초보자용 검입니다.",
      statBonuses: { attack: 8, defense: 0, mind: 0, agility: 0 },
      equippableActorIds: [DEFAULT_ACTOR_ID, ACTOR_GUARDIAN_ID],
      equippableClassIds: [DEFAULT_CLASS_ID, CLASS_GUARDIAN_ID],
    }),
    normalizeEquipmentRecord({
      id: EQUIPMENT_MAGE_STAFF_ID,
      name: "수습 지팡이",
      slot: "weapon",
      price: 120,
      imageResourceId: "cc0-jetrel-mage-staff",
      iconResourceId: "cc0-jetrel-mage-staff",
      description: "마력을 조금 끌어올리는 나무 지팡이입니다.",
      statBonuses: { attack: 3, defense: 0, mind: 7, agility: 0 },
      equippableActorIds: [ACTOR_MAGE_ID, ACTOR_CLERIC_ID],
      equippableClassIds: [CLASS_MAGE_ID, CLASS_CLERIC_ID],
    }),
    normalizeEquipmentRecord({
      id: EQUIPMENT_SCOUT_DAGGER_ID,
      name: "정찰 단검",
      slot: "weapon",
      price: 90,
      imageResourceId: "cc0-jetrel-scout-dagger",
      iconResourceId: "cc0-jetrel-scout-dagger",
      description: "빠른 움직임에 맞춘 가벼운 단검입니다.",
      statBonuses: { attack: 5, defense: 0, mind: 0, agility: 3 },
      equippableActorIds: [DEFAULT_ACTOR_ID, ACTOR_SCOUT_ID, ACTOR_RANGER_ID],
      equippableClassIds: [DEFAULT_CLASS_ID, CLASS_SCOUT_ID, CLASS_RANGER_ID],
    }),
    normalizeEquipmentRecord({
      id: "equip_iron_sword",
      name: "철 검",
      slot: "weapon",
      price: 180,
      imageResourceId: "cc0-jetrel-iron-sword",
      iconResourceId: "cc0-jetrel-iron-sword",
      description: "기본 검보다 더 묵직한 초보자용 철검입니다.",
      statBonuses: { attack: 14, defense: 0, mind: 0, agility: 0 },
      equippableActorIds: [DEFAULT_ACTOR_ID, ACTOR_GUARDIAN_ID],
      equippableClassIds: [DEFAULT_CLASS_ID, CLASS_GUARDIAN_ID],
    }),
    normalizeEquipmentRecord({
      id: "equip_steel_sword",
      name: "강철 검",
      slot: "weapon",
      price: 260,
      imageResourceId: "cc0-jetrel-steel-sword",
      iconResourceId: "cc0-jetrel-steel-sword",
      description: "공격력이 크게 오르는 강철 검입니다.",
      statBonuses: { attack: 20, defense: 0, mind: 0, agility: -1 },
      equippableActorIds: [DEFAULT_ACTOR_ID, ACTOR_GUARDIAN_ID],
      equippableClassIds: [DEFAULT_CLASS_ID, CLASS_GUARDIAN_ID],
    }),
    normalizeEquipmentRecord({
      id: "equip_short_sword",
      name: "단검",
      slot: "weapon",
      price: 70,
      imageResourceId: "cc0-jetrel-scout-dagger",
      iconResourceId: "cc0-jetrel-scout-dagger",
      description: "가볍고 다루기 쉬운 예비 무기입니다.",
      statBonuses: { attack: 4, defense: 0, mind: 0, agility: 2 },
      equippableActorIds: [DEFAULT_ACTOR_ID, ACTOR_SCOUT_ID, ACTOR_RANGER_ID],
      equippableClassIds: [DEFAULT_CLASS_ID, CLASS_SCOUT_ID, CLASS_RANGER_ID],
    }),
    normalizeEquipmentRecord({
      id: EQUIPMENT_OAK_SHIELD_ID,
      name: "참나무 방패",
      slot: "shield",
      price: 80,
      imageResourceId: "cc0-jetrel-oak-shield",
      iconResourceId: "cc0-jetrel-oak-shield",
      description: "튼튼하지만 무겁지 않은 소형 방패입니다.",
      statBonuses: { attack: 0, defense: 5, mind: 0, agility: 0 },
      equippableActorIds: [DEFAULT_ACTOR_ID, ACTOR_GUARDIAN_ID, ACTOR_CLERIC_ID],
      equippableClassIds: [DEFAULT_CLASS_ID, CLASS_GUARDIAN_ID, CLASS_CLERIC_ID],
    }),
    normalizeEquipmentRecord({
      id: EQUIPMENT_LEATHER_ARMOR_ID,
      name: "가죽 갑옷",
      slot: "armor",
      price: 140,
      imageResourceId: "cc0-jetrel-leather-armor",
      iconResourceId: "cc0-jetrel-leather-armor",
      description: "여행자를 위한 기본 방어구입니다.",
      statBonuses: { attack: 0, defense: 6, mind: 0, agility: 0 },
      equippableActorIds: [DEFAULT_ACTOR_ID, ACTOR_GUARDIAN_ID, ACTOR_SCOUT_ID, ACTOR_RANGER_ID],
      equippableClassIds: [DEFAULT_CLASS_ID, CLASS_GUARDIAN_ID, CLASS_SCOUT_ID, CLASS_RANGER_ID],
    }),
    normalizeEquipmentRecord({
      id: EQUIPMENT_MYSTIC_ROBE_ID,
      name: "견습 로브",
      slot: "armor",
      price: 130,
      imageResourceId: "cc0-jetrel-mystic-robe",
      iconResourceId: "cc0-jetrel-mystic-robe",
      description: "마법 수련생에게 맞춘 가벼운 로브입니다.",
      statBonuses: { attack: 0, defense: 3, mind: 4, agility: 0 },
      equippableActorIds: [ACTOR_MAGE_ID, ACTOR_CLERIC_ID],
      equippableClassIds: [CLASS_MAGE_ID, CLASS_CLERIC_ID],
    }),
    normalizeEquipmentRecord({
      id: EQUIPMENT_TRAVELER_HAT_ID,
      name: "여행자 모자",
      slot: "helmet",
      price: 60,
      imageResourceId: "cc0-jetrel-traveler-hat",
      iconResourceId: "cc0-jetrel-traveler-hat",
      description: "먼 길을 떠나는 파티의 기본 모자입니다.",
      statBonuses: { attack: 0, defense: 2, mind: 1, agility: 0 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: EQUIPMENT_FOCUS_CHARM_ID,
      name: "집중 부적",
      slot: "accessory",
      price: 160,
      imageResourceId: "cc0-jetrel-focus-charm",
      iconResourceId: "cc0-jetrel-focus-charm",
      description: "마음가짐을 다잡아 주는 작은 부적입니다.",
      statBonuses: { attack: 0, defense: 0, mind: 2, agility: 2 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    // 생성 아이콘 100종 중 무기·방어구·장식 계열.
    ...generatedEquipmentRecords(),
  ];
}
