import { normalizeEnemyRecord } from "../databaseRecordModel";
import { archetypeActions, BOSS_ELEMENT_SKILLS, SPIRIT_ELEMENT_SKILLS } from "./enemyActionArchetypes";

// 생성된 몬스터 배틀러(manifest.mjs MONSTERS)에 대응하는 적 레코드.
// PNG 가 실제로 존재하는 slug 만 등록한다(없는 리소스는 런타임에 폴백 스프라이트가 뜬다).
// 계열 순서(슬라임→…→드래곤·보스)로 난이도가 완만하게 오르며, 보스급은 HP 가 눈에 띄게 높다.
//
// 스탯 규약 두 가지(Task 5):
//  - `mind` = 그 적의 `attack`. 데미지형 정체성 스킬(속성기·독침)이 전부 `statistic:"mind"`
//    라, mind 가 전원 10 이던 시절에는 공격력이 큰 적에서 마법 위력이 `power + 5` 에 묶여
//    물리 무료기에 영구히 졌다. 근거와 검사는 enemyActionArchetypes.ts 헤더 참고.
//  - `maxMp` = 10, 단 드래곤·보스 구획 10마리만 40. 4MP 속성기를 10회 쓸 예산이다.
//    MP 부족은 점수 계산 **전에** 필터되므로(runtime.ts:1798) turn 조건 버스트도 같이 죽는다.
export function generatedEnemyRecords() {
  return [
      // 슬라임·젤리
      normalizeEnemyRecord({ ...{"id":"enemy_slime_blue","name":"푸른 슬라임","level":1,"monsterResourceId":"generated-enemy-slime-blue","stats":{"maxHp":78,"maxMp":10,"attack":11,"defense":15,"mind":11,"agility":8},"rewards":{"exp":33,"gold":30,"dropRatePercent":15}}, actions: archetypeActions("blob") }),
      normalizeEnemyRecord({ ...{"id":"enemy_slime_red","name":"붉은 슬라임","level":2,"monsterResourceId":"generated-enemy-slime-red","stats":{"maxHp":82,"maxMp":10,"attack":13,"defense":16,"mind":13,"agility":9},"rewards":{"exp":34,"gold":32,"dropRatePercent":15}}, actions: archetypeActions("blob") }),
      normalizeEnemyRecord({ ...{"id":"enemy_slime_green","name":"초록 슬라임","level":2,"monsterResourceId":"generated-enemy-slime-green","stats":{"maxHp":83,"maxMp":10,"attack":13,"defense":16,"mind":13,"agility":9},"rewards":{"exp":35,"gold":32,"dropRatePercent":15}}, actions: archetypeActions("blob") }),
      normalizeEnemyRecord({ ...{"id":"enemy_slime_metal","name":"금속 슬라임","level":3,"monsterResourceId":"generated-enemy-slime-metal","stats":{"maxHp":91,"maxMp":10,"attack":14,"defense":17,"mind":14,"agility":10},"rewards":{"exp":38,"gold":35,"dropRatePercent":15}}, actions: archetypeActions("blob") }),
      normalizeEnemyRecord({ ...{"id":"enemy_slime_king","name":"슬라임 왕","level":3,"monsterResourceId":"generated-enemy-slime-king","stats":{"maxHp":92,"maxMp":10,"attack":14,"defense":17,"mind":14,"agility":10},"rewards":{"exp":38,"gold":35,"dropRatePercent":15}}, actions: archetypeActions("blob") }),
      normalizeEnemyRecord({ ...{"id":"enemy_slime_cube","name":"젤리 큐브","level":4,"monsterResourceId":"generated-enemy-slime-cube","stats":{"maxHp":93,"maxMp":10,"attack":15,"defense":17,"mind":15,"agility":11},"rewards":{"exp":39,"gold":36,"dropRatePercent":15}}, actions: archetypeActions("blob") }),
      normalizeEnemyRecord({ ...{"id":"enemy_ooze_black","name":"검은 점액","level":4,"monsterResourceId":"generated-enemy-ooze-black","stats":{"maxHp":94,"maxMp":10,"attack":15,"defense":17,"mind":15,"agility":11},"rewards":{"exp":39,"gold":36,"dropRatePercent":15}}, actions: archetypeActions("blob") }),
      normalizeEnemyRecord({ ...{"id":"enemy_ooze_acid","name":"산성 점액","level":5,"monsterResourceId":"generated-enemy-ooze-acid","stats":{"maxHp":102,"maxMp":10,"attack":15,"defense":17,"mind":15,"agility":12},"rewards":{"exp":43,"gold":39,"dropRatePercent":15}}, actions: archetypeActions("blob") }),
      // 곤충·절지
      normalizeEnemyRecord({ ...{"id":"enemy_bat_cave","name":"동굴 박쥐","level":6,"monsterResourceId":"generated-enemy-bat-cave","stats":{"maxHp":96,"maxMp":10,"attack":19,"defense":18,"mind":19,"agility":12},"rewards":{"exp":40,"gold":37,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      normalizeEnemyRecord({ ...{"id":"enemy_bat_vampire","name":"흡혈 박쥐","level":6,"monsterResourceId":"generated-enemy-bat-vampire","stats":{"maxHp":97,"maxMp":10,"attack":19,"defense":18,"mind":19,"agility":13},"rewards":{"exp":40,"gold":37,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      normalizeEnemyRecord({ ...{"id":"enemy_bee_giant","name":"거대 벌","level":7,"monsterResourceId":"generated-enemy-bee-giant","stats":{"maxHp":104,"maxMp":10,"attack":20,"defense":19,"mind":20,"agility":13},"rewards":{"exp":43,"gold":40,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      normalizeEnemyRecord({ ...{"id":"enemy_spider_cave","name":"동굴 거미","level":7,"monsterResourceId":"generated-enemy-spider-cave","stats":{"maxHp":105,"maxMp":10,"attack":20,"defense":19,"mind":20,"agility":14},"rewards":{"exp":44,"gold":40,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      normalizeEnemyRecord({ ...{"id":"enemy_spider_widow","name":"과부 거미","level":7,"monsterResourceId":"generated-enemy-spider-widow","stats":{"maxHp":106,"maxMp":10,"attack":20,"defense":19,"mind":20,"agility":15},"rewards":{"exp":44,"gold":41,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      normalizeEnemyRecord({ ...{"id":"enemy_scorpion_sand","name":"모래 전갈","level":8,"monsterResourceId":"generated-enemy-scorpion-sand","stats":{"maxHp":110,"maxMp":10,"attack":21,"defense":19,"mind":21,"agility":16},"rewards":{"exp":46,"gold":42,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      normalizeEnemyRecord({ ...{"id":"enemy_beetle_horn","name":"뿔 딱정벌레","level":8,"monsterResourceId":"generated-enemy-beetle-horn","stats":{"maxHp":111,"maxMp":10,"attack":21,"defense":19,"mind":21,"agility":16},"rewards":{"exp":46,"gold":43,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      normalizeEnemyRecord({ ...{"id":"enemy_mantis_blade","name":"칼날 사마귀","level":9,"monsterResourceId":"generated-enemy-mantis-blade","stats":{"maxHp":112,"maxMp":10,"attack":22,"defense":20,"mind":22,"agility":17},"rewards":{"exp":47,"gold":43,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      normalizeEnemyRecord({ ...{"id":"enemy_centipede_fire","name":"화염 지네","level":9,"monsterResourceId":"generated-enemy-centipede-fire","stats":{"maxHp":112,"maxMp":10,"attack":22,"defense":20,"mind":22,"agility":18},"rewards":{"exp":47,"gold":43,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      normalizeEnemyRecord({ ...{"id":"enemy_moth_dust","name":"가루 나방","level":9,"monsterResourceId":"generated-enemy-moth-dust","stats":{"maxHp":113,"maxMp":10,"attack":22,"defense":20,"mind":22,"agility":19},"rewards":{"exp":47,"gold":43,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      normalizeEnemyRecord({ ...{"id":"enemy_worm_sand","name":"모래 지렁이","level":10,"monsterResourceId":"generated-enemy-worm-sand","stats":{"maxHp":121,"maxMp":10,"attack":23,"defense":20,"mind":23,"agility":19},"rewards":{"exp":50,"gold":47,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      normalizeEnemyRecord({ ...{"id":"enemy_ant_soldier","name":"병정 개미","level":10,"monsterResourceId":"generated-enemy-ant-soldier","stats":{"maxHp":122,"maxMp":10,"attack":23,"defense":20,"mind":23,"agility":20},"rewards":{"exp":51,"gold":47,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      // 야수
      normalizeEnemyRecord({ ...{"id":"enemy_wolf_grey","name":"회색 늑대","level":11,"monsterResourceId":"generated-enemy-wolf-grey","stats":{"maxHp":148,"maxMp":10,"attack":26,"defense":22,"mind":26,"agility":10},"rewards":{"exp":62,"gold":57,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_wolf_dire","name":"다이어 울프","level":11,"monsterResourceId":"generated-enemy-wolf-dire","stats":{"maxHp":149,"maxMp":10,"attack":26,"defense":22,"mind":26,"agility":10},"rewards":{"exp":62,"gold":57,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_boar_tusk","name":"송곳니 멧돼지","level":12,"monsterResourceId":"generated-enemy-boar-tusk","stats":{"maxHp":157,"maxMp":10,"attack":27,"defense":23,"mind":27,"agility":11},"rewards":{"exp":65,"gold":60,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_bear_brown","name":"갈색 곰","level":12,"monsterResourceId":"generated-enemy-bear-brown","stats":{"maxHp":158,"maxMp":10,"attack":27,"defense":23,"mind":27,"agility":11},"rewards":{"exp":66,"gold":61,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_tiger_saber","name":"검치호","level":12,"monsterResourceId":"generated-enemy-tiger-saber","stats":{"maxHp":159,"maxMp":10,"attack":27,"defense":23,"mind":27,"agility":12},"rewards":{"exp":66,"gold":61,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_rat_giant","name":"거대 쥐","level":13,"monsterResourceId":"generated-enemy-rat-giant","stats":{"maxHp":160,"maxMp":10,"attack":28,"defense":23,"mind":28,"agility":12},"rewards":{"exp":67,"gold":62,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_bird_hawk","name":"매","level":13,"monsterResourceId":"generated-enemy-bird-hawk","stats":{"maxHp":161,"maxMp":10,"attack":28,"defense":23,"mind":28,"agility":13},"rewards":{"exp":67,"gold":62,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_snake_viper","name":"독사","level":13,"monsterResourceId":"generated-enemy-snake-viper","stats":{"maxHp":162,"maxMp":10,"attack":28,"defense":23,"mind":28,"agility":13},"rewards":{"exp":68,"gold":62,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_cat_shadow","name":"그림자 고양이","level":13,"monsterResourceId":"generated-enemy-cat-shadow","stats":{"maxHp":163,"maxMp":10,"attack":28,"defense":23,"mind":28,"agility":14},"rewards":{"exp":68,"gold":63,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_goat_mountain","name":"산양","level":14,"monsterResourceId":"generated-enemy-goat-mountain","stats":{"maxHp":168,"maxMp":10,"attack":29,"defense":24,"mind":29,"agility":14},"rewards":{"exp":70,"gold":65,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_crab_rock","name":"바위 게","level":14,"monsterResourceId":"generated-enemy-crab-rock","stats":{"maxHp":169,"maxMp":10,"attack":29,"defense":24,"mind":29,"agility":15},"rewards":{"exp":70,"gold":65,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_hound_hell","name":"지옥 사냥개","level":14,"monsterResourceId":"generated-enemy-hound-hell","stats":{"maxHp":170,"maxMp":10,"attack":29,"defense":24,"mind":29,"agility":15},"rewards":{"exp":71,"gold":65,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_ape_stone","name":"석상 유인원","level":15,"monsterResourceId":"generated-enemy-ape-stone","stats":{"maxHp":180,"maxMp":10,"attack":31,"defense":25,"mind":31,"agility":16},"rewards":{"exp":75,"gold":69,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_deer_forest","name":"숲 사슴","level":15,"monsterResourceId":"generated-enemy-deer-forest","stats":{"maxHp":181,"maxMp":10,"attack":31,"defense":25,"mind":31,"agility":16},"rewards":{"exp":75,"gold":70,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      // 언데드
      normalizeEnemyRecord({ ...{"id":"enemy_skeleton_bone","name":"해골","level":16,"monsterResourceId":"generated-enemy-skeleton-bone","stats":{"maxHp":178,"maxMp":10,"attack":30,"defense":27,"mind":30,"agility":8},"rewards":{"exp":74,"gold":68,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      normalizeEnemyRecord({ ...{"id":"enemy_skeleton_archer","name":"해골 궁수","level":16,"monsterResourceId":"generated-enemy-skeleton-archer","stats":{"maxHp":179,"maxMp":10,"attack":30,"defense":27,"mind":30,"agility":9},"rewards":{"exp":75,"gold":69,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      normalizeEnemyRecord({ ...{"id":"enemy_skeleton_knight","name":"해골 기사","level":17,"monsterResourceId":"generated-enemy-skeleton-knight","stats":{"maxHp":181,"maxMp":10,"attack":32,"defense":27,"mind":32,"agility":9},"rewards":{"exp":75,"gold":70,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      normalizeEnemyRecord({ ...{"id":"enemy_zombie_rot","name":"썩은 좀비","level":17,"monsterResourceId":"generated-enemy-zombie-rot","stats":{"maxHp":182,"maxMp":10,"attack":32,"defense":27,"mind":32,"agility":10},"rewards":{"exp":76,"gold":70,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      normalizeEnemyRecord({ ...{"id":"enemy_ghoul_grave","name":"무덤 구울","level":17,"monsterResourceId":"generated-enemy-ghoul-grave","stats":{"maxHp":183,"maxMp":10,"attack":32,"defense":27,"mind":32,"agility":10},"rewards":{"exp":76,"gold":70,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      normalizeEnemyRecord({ ...{"id":"enemy_ghost_pale","name":"창백한 유령","level":18,"monsterResourceId":"generated-enemy-ghost-pale","stats":{"maxHp":188,"maxMp":10,"attack":32,"defense":28,"mind":32,"agility":11},"rewards":{"exp":78,"gold":72,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      normalizeEnemyRecord({ ...{"id":"enemy_wraith_dark","name":"어둠 망령","level":18,"monsterResourceId":"generated-enemy-wraith-dark","stats":{"maxHp":190,"maxMp":10,"attack":32,"defense":28,"mind":32,"agility":11},"rewards":{"exp":79,"gold":73,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      normalizeEnemyRecord({ ...{"id":"enemy_lich_frost","name":"서릿 리치","level":19,"monsterResourceId":"generated-enemy-lich-frost","stats":{"maxHp":199,"maxMp":10,"attack":34,"defense":29,"mind":34,"agility":12},"rewards":{"exp":83,"gold":77,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      normalizeEnemyRecord({ ...{"id":"enemy_mummy_bandage","name":"미라","level":19,"monsterResourceId":"generated-enemy-mummy-bandage","stats":{"maxHp":201,"maxMp":10,"attack":34,"defense":29,"mind":34,"agility":12},"rewards":{"exp":84,"gold":77,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      normalizeEnemyRecord({ ...{"id":"enemy_banshee_wail","name":"밴시","level":19,"monsterResourceId":"generated-enemy-banshee-wail","stats":{"maxHp":202,"maxMp":10,"attack":34,"defense":29,"mind":34,"agility":13},"rewards":{"exp":84,"gold":78,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      normalizeEnemyRecord({ ...{"id":"enemy_revenant_vengeful","name":"복수의 사령","level":20,"monsterResourceId":"generated-enemy-revenant-vengeful","stats":{"maxHp":207,"maxMp":10,"attack":35,"defense":30,"mind":35,"agility":13},"rewards":{"exp":86,"gold":80,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      normalizeEnemyRecord({ ...{"id":"enemy_bonepile_crawler","name":"뼈 무더기","level":20,"monsterResourceId":"generated-enemy-bonepile-crawler","stats":{"maxHp":209,"maxMp":10,"attack":35,"defense":30,"mind":35,"agility":14},"rewards":{"exp":87,"gold":80,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      // 정령·원소
      normalizeEnemyRecord({ ...{"id":"enemy_spirit_fire","name":"불의 정령","level":21,"monsterResourceId":"generated-enemy-spirit-fire","stats":{"maxHp":206,"maxMp":10,"attack":36,"defense":26,"mind":36,"agility":10},"rewards":{"exp":86,"gold":79,"dropRatePercent":15}}, actions: archetypeActions("caster", SPIRIT_ELEMENT_SKILLS.enemy_spirit_fire) }),
      normalizeEnemyRecord({ ...{"id":"enemy_spirit_water","name":"물의 정령","level":21,"monsterResourceId":"generated-enemy-spirit-water","stats":{"maxHp":207,"maxMp":10,"attack":36,"defense":26,"mind":36,"agility":11},"rewards":{"exp":86,"gold":80,"dropRatePercent":15}}, actions: archetypeActions("caster", SPIRIT_ELEMENT_SKILLS.enemy_spirit_water) }),
      normalizeEnemyRecord({ ...{"id":"enemy_spirit_earth","name":"땅의 정령","level":22,"monsterResourceId":"generated-enemy-spirit-earth","stats":{"maxHp":209,"maxMp":10,"attack":37,"defense":26,"mind":37,"agility":11},"rewards":{"exp":87,"gold":80,"dropRatePercent":15}}, actions: archetypeActions("caster", SPIRIT_ELEMENT_SKILLS.enemy_spirit_earth) }),
      normalizeEnemyRecord({ ...{"id":"enemy_spirit_wind","name":"바람의 정령","level":22,"monsterResourceId":"generated-enemy-spirit-wind","stats":{"maxHp":211,"maxMp":10,"attack":37,"defense":26,"mind":37,"agility":12},"rewards":{"exp":88,"gold":81,"dropRatePercent":15}}, actions: archetypeActions("caster", SPIRIT_ELEMENT_SKILLS.enemy_spirit_wind) }),
      normalizeEnemyRecord({ ...{"id":"enemy_spirit_light","name":"빛의 정령","level":23,"monsterResourceId":"generated-enemy-spirit-light","stats":{"maxHp":220,"maxMp":10,"attack":39,"defense":27,"mind":39,"agility":13},"rewards":{"exp":92,"gold":85,"dropRatePercent":15}}, actions: archetypeActions("caster", SPIRIT_ELEMENT_SKILLS.enemy_spirit_light) }),
      normalizeEnemyRecord({ ...{"id":"enemy_spirit_dark","name":"어둠의 정령","level":23,"monsterResourceId":"generated-enemy-spirit-dark","stats":{"maxHp":222,"maxMp":10,"attack":39,"defense":27,"mind":39,"agility":13},"rewards":{"exp":93,"gold":85,"dropRatePercent":15}}, actions: archetypeActions("caster", SPIRIT_ELEMENT_SKILLS.enemy_spirit_dark) }),
      normalizeEnemyRecord({ ...{"id":"enemy_wisp_blue","name":"푸른 도깨비불","level":24,"monsterResourceId":"generated-enemy-wisp-blue","stats":{"maxHp":232,"maxMp":10,"attack":39,"defense":27,"mind":39,"agility":14},"rewards":{"exp":97,"gold":89,"dropRatePercent":15}}, actions: archetypeActions("caster", SPIRIT_ELEMENT_SKILLS.enemy_wisp_blue) }),
      normalizeEnemyRecord({ ...{"id":"enemy_sylph_air","name":"실프","level":24,"monsterResourceId":"generated-enemy-sylph-air","stats":{"maxHp":234,"maxMp":10,"attack":39,"defense":27,"mind":39,"agility":15},"rewards":{"exp":98,"gold":90,"dropRatePercent":15}}, actions: archetypeActions("caster", SPIRIT_ELEMENT_SKILLS.enemy_sylph_air) }),
      normalizeEnemyRecord({ ...{"id":"enemy_undine_sea","name":"운디네","level":25,"monsterResourceId":"generated-enemy-undine-sea","stats":{"maxHp":239,"maxMp":10,"attack":41,"defense":28,"mind":41,"agility":15},"rewards":{"exp":100,"gold":92,"dropRatePercent":15}}, actions: archetypeActions("caster", SPIRIT_ELEMENT_SKILLS.enemy_undine_sea) }),
      normalizeEnemyRecord({ ...{"id":"enemy_salamander_flame","name":"샐러맨더","level":25,"monsterResourceId":"generated-enemy-salamander-flame","stats":{"maxHp":241,"maxMp":10,"attack":41,"defense":28,"mind":41,"agility":16},"rewards":{"exp":100,"gold":93,"dropRatePercent":15}}, actions: archetypeActions("caster", SPIRIT_ELEMENT_SKILLS.enemy_salamander_flame) }),
      // 골렘·구조물
      normalizeEnemyRecord({ ...{"id":"enemy_golem_stone","name":"돌 골렘","level":26,"monsterResourceId":"generated-enemy-golem-stone","stats":{"maxHp":279,"maxMp":10,"attack":40,"defense":40,"mind":40,"agility":6},"rewards":{"exp":116,"gold":107,"dropRatePercent":15}}, actions: archetypeActions("bulwark") }),
      normalizeEnemyRecord({ ...{"id":"enemy_golem_iron","name":"철 골렘","level":26,"monsterResourceId":"generated-enemy-golem-iron","stats":{"maxHp":281,"maxMp":10,"attack":40,"defense":40,"mind":40,"agility":6},"rewards":{"exp":117,"gold":108,"dropRatePercent":15}}, actions: archetypeActions("bulwark") }),
      normalizeEnemyRecord({ ...{"id":"enemy_golem_clay","name":"점토 골렘","level":27,"monsterResourceId":"generated-enemy-golem-clay","stats":{"maxHp":294,"maxMp":10,"attack":41,"defense":41,"mind":41,"agility":7},"rewards":{"exp":123,"gold":113,"dropRatePercent":15}}, actions: archetypeActions("bulwark") }),
      normalizeEnemyRecord({ ...{"id":"enemy_golem_crystal","name":"수정 골렘","level":27,"monsterResourceId":"generated-enemy-golem-crystal","stats":{"maxHp":296,"maxMp":10,"attack":41,"defense":41,"mind":41,"agility":7},"rewards":{"exp":123,"gold":114,"dropRatePercent":15}}, actions: archetypeActions("bulwark") }),
      normalizeEnemyRecord({ ...{"id":"enemy_armor_living","name":"살아있는 갑옷","level":28,"monsterResourceId":"generated-enemy-armor-living","stats":{"maxHp":303,"maxMp":10,"attack":42,"defense":42,"mind":42,"agility":8},"rewards":{"exp":126,"gold":117,"dropRatePercent":15}}, actions: archetypeActions("bulwark") }),
      normalizeEnemyRecord({ ...{"id":"enemy_sword_flying","name":"부유하는 검","level":28,"monsterResourceId":"generated-enemy-sword-flying","stats":{"maxHp":305,"maxMp":10,"attack":42,"defense":42,"mind":42,"agility":8},"rewards":{"exp":127,"gold":117,"dropRatePercent":15}}, actions: archetypeActions("bulwark") }),
      normalizeEnemyRecord({ ...{"id":"enemy_mimic_chest","name":"미믹 상자","level":29,"monsterResourceId":"generated-enemy-mimic-chest","stats":{"maxHp":319,"maxMp":10,"attack":43,"defense":43,"mind":43,"agility":9},"rewards":{"exp":133,"gold":123,"dropRatePercent":15}}, actions: archetypeActions("bulwark") }),
      normalizeEnemyRecord({ ...{"id":"enemy_scarecrow_field","name":"허수아비","level":29,"monsterResourceId":"generated-enemy-scarecrow-field","stats":{"maxHp":321,"maxMp":10,"attack":43,"defense":43,"mind":43,"agility":9},"rewards":{"exp":134,"gold":123,"dropRatePercent":15}}, actions: archetypeActions("bulwark") }),
      normalizeEnemyRecord({ ...{"id":"enemy_puppet_string","name":"실 인형","level":30,"monsterResourceId":"generated-enemy-puppet-string","stats":{"maxHp":329,"maxMp":10,"attack":44,"defense":43,"mind":44,"agility":10},"rewards":{"exp":137,"gold":127,"dropRatePercent":15}}, actions: archetypeActions("bulwark") }),
      normalizeEnemyRecord({ ...{"id":"enemy_totem_cursed","name":"저주받은 토템","level":30,"monsterResourceId":"generated-enemy-totem-cursed","stats":{"maxHp":331,"maxMp":10,"attack":44,"defense":43,"mind":44,"agility":10},"rewards":{"exp":138,"gold":127,"dropRatePercent":15}}, actions: archetypeActions("bulwark") }),
      // 인간형
      normalizeEnemyRecord({ ...{"id":"enemy_goblin_scout","name":"고블린 정찰병","level":31,"monsterResourceId":"generated-enemy-goblin-scout","stats":{"maxHp":311,"maxMp":10,"attack":48,"defense":37,"mind":48,"agility":12},"rewards":{"exp":130,"gold":120,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_goblin_brute","name":"고블린 폭력배","level":31,"monsterResourceId":"generated-enemy-goblin-brute","stats":{"maxHp":312,"maxMp":10,"attack":48,"defense":37,"mind":48,"agility":13},"rewards":{"exp":130,"gold":120,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_orc_warrior","name":"오크 전사","level":32,"monsterResourceId":"generated-enemy-orc-warrior","stats":{"maxHp":319,"maxMp":10,"attack":49,"defense":38,"mind":49,"agility":13},"rewards":{"exp":133,"gold":123,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_orc_shaman","name":"오크 주술사","level":32,"monsterResourceId":"generated-enemy-orc-shaman","stats":{"maxHp":320,"maxMp":10,"attack":49,"defense":38,"mind":49,"agility":14},"rewards":{"exp":133,"gold":123,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_kobold_digger","name":"코볼트 광부","level":32,"monsterResourceId":"generated-enemy-kobold-digger","stats":{"maxHp":322,"maxMp":10,"attack":49,"defense":38,"mind":49,"agility":14},"rewards":{"exp":134,"gold":124,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_bandit_mask","name":"복면 산적","level":32,"monsterResourceId":"generated-enemy-bandit-mask","stats":{"maxHp":323,"maxMp":10,"attack":49,"defense":38,"mind":49,"agility":15},"rewards":{"exp":135,"gold":124,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_mage_rogue","name":"이단 마법사","level":33,"monsterResourceId":"generated-enemy-mage-rogue","stats":{"maxHp":335,"maxMp":10,"attack":50,"defense":38,"mind":50,"agility":15},"rewards":{"exp":140,"gold":129,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_knight_fallen","name":"타락한 기사","level":33,"monsterResourceId":"generated-enemy-knight-fallen","stats":{"maxHp":336,"maxMp":10,"attack":50,"defense":38,"mind":50,"agility":16},"rewards":{"exp":140,"gold":129,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_lizardman_spear","name":"리자드맨","level":33,"monsterResourceId":"generated-enemy-lizardman-spear","stats":{"maxHp":337,"maxMp":10,"attack":50,"defense":38,"mind":50,"agility":17},"rewards":{"exp":140,"gold":130,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_harpy_cliff","name":"하피","level":34,"monsterResourceId":"generated-enemy-harpy-cliff","stats":{"maxHp":349,"maxMp":10,"attack":52,"defense":39,"mind":52,"agility":17},"rewards":{"exp":145,"gold":134,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_minotaur_maze","name":"미노타우로스","level":34,"monsterResourceId":"generated-enemy-minotaur-maze","stats":{"maxHp":351,"maxMp":10,"attack":52,"defense":39,"mind":52,"agility":18},"rewards":{"exp":146,"gold":135,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_centaur_plains","name":"켄타우로스","level":34,"monsterResourceId":"generated-enemy-centaur-plains","stats":{"maxHp":352,"maxMp":10,"attack":52,"defense":39,"mind":52,"agility":18},"rewards":{"exp":147,"gold":135,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_troll_cave","name":"동굴 트롤","level":34,"monsterResourceId":"generated-enemy-troll-cave","stats":{"maxHp":354,"maxMp":10,"attack":52,"defense":39,"mind":52,"agility":19},"rewards":{"exp":148,"gold":136,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_ogre_club","name":"오거","level":35,"monsterResourceId":"generated-enemy-ogre-club","stats":{"maxHp":360,"maxMp":10,"attack":52,"defense":39,"mind":52,"agility":19},"rewards":{"exp":150,"gold":138,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_imp_mischief","name":"임프","level":35,"monsterResourceId":"generated-enemy-imp-mischief","stats":{"maxHp":362,"maxMp":10,"attack":52,"defense":39,"mind":52,"agility":20},"rewards":{"exp":151,"gold":139,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      // 수생·비행
      normalizeEnemyRecord({ ...{"id":"enemy_fish_piranha","name":"피라냐","level":36,"monsterResourceId":"generated-enemy-fish-piranha","stats":{"maxHp":357,"maxMp":10,"attack":57,"defense":36,"mind":57,"agility":16},"rewards":{"exp":149,"gold":137,"dropRatePercent":15}}, actions: archetypeActions("flyer") }),
      normalizeEnemyRecord({ ...{"id":"enemy_squid_deep","name":"심해 오징어","level":37,"monsterResourceId":"generated-enemy-squid-deep","stats":{"maxHp":370,"maxMp":10,"attack":57,"defense":37,"mind":57,"agility":17},"rewards":{"exp":154,"gold":142,"dropRatePercent":15}}, actions: archetypeActions("flyer") }),
      normalizeEnemyRecord({ ...{"id":"enemy_shark_land","name":"육상 상어","level":37,"monsterResourceId":"generated-enemy-shark-land","stats":{"maxHp":373,"maxMp":10,"attack":57,"defense":37,"mind":57,"agility":19},"rewards":{"exp":155,"gold":143,"dropRatePercent":15}}, actions: archetypeActions("flyer") }),
      normalizeEnemyRecord({ ...{"id":"enemy_eel_electric","name":"전기 뱀장어","level":38,"monsterResourceId":"generated-enemy-eel-electric","stats":{"maxHp":380,"maxMp":10,"attack":59,"defense":38,"mind":59,"agility":20},"rewards":{"exp":158,"gold":146,"dropRatePercent":15}}, actions: archetypeActions("flyer") }),
      normalizeEnemyRecord({ ...{"id":"enemy_griffin_sky","name":"그리핀","level":38,"monsterResourceId":"generated-enemy-griffin-sky","stats":{"maxHp":383,"maxMp":10,"attack":59,"defense":38,"mind":59,"agility":21},"rewards":{"exp":160,"gold":147,"dropRatePercent":15}}, actions: archetypeActions("flyer") }),
      normalizeEnemyRecord({ ...{"id":"enemy_wyvern_cliff","name":"와이번","level":39,"monsterResourceId":"generated-enemy-wyvern-cliff","stats":{"maxHp":391,"maxMp":10,"attack":60,"defense":38,"mind":60,"agility":22},"rewards":{"exp":163,"gold":150,"dropRatePercent":15}}, actions: archetypeActions("flyer") }),
      normalizeEnemyRecord({ ...{"id":"enemy_roc_giant","name":"거대 로크","level":39,"monsterResourceId":"generated-enemy-roc-giant","stats":{"maxHp":394,"maxMp":10,"attack":60,"defense":38,"mind":60,"agility":24},"rewards":{"exp":164,"gold":152,"dropRatePercent":15}}, actions: archetypeActions("flyer") }),
      normalizeEnemyRecord({ ...{"id":"enemy_gargoyle_stone","name":"가고일","level":40,"monsterResourceId":"generated-enemy-gargoyle-stone","stats":{"maxHp":402,"maxMp":10,"attack":61,"defense":39,"mind":61,"agility":25},"rewards":{"exp":168,"gold":155,"dropRatePercent":15}}, actions: archetypeActions("flyer") }),
      normalizeEnemyRecord({ ...{"id":"enemy_phoenix_rebirth","name":"불사조","level":40,"monsterResourceId":"generated-enemy-phoenix-rebirth","stats":{"maxHp":404,"maxMp":10,"attack":61,"defense":39,"mind":61,"agility":26},"rewards":{"exp":168,"gold":155,"dropRatePercent":15}}, actions: archetypeActions("flyer") }),
      // 드래곤·보스
      normalizeEnemyRecord({ ...{"id":"enemy_dragon_whelp","name":"새끼 용","level":36,"monsterResourceId":"generated-enemy-dragon-whelp","stats":{"maxHp":536,"maxMp":40,"attack":71,"defense":40,"mind":71,"agility":10},"rewards":{"exp":223,"gold":206,"dropRatePercent":15}}, actions: archetypeActions("boss", BOSS_ELEMENT_SKILLS.enemy_dragon_whelp) }),
      normalizeEnemyRecord({ ...{"id":"enemy_dragon_red","name":"붉은 용","level":37,"monsterResourceId":"generated-enemy-dragon-red","stats":{"maxHp":552,"maxMp":40,"attack":72,"defense":41,"mind":72,"agility":11},"rewards":{"exp":230,"gold":212,"dropRatePercent":15}}, actions: archetypeActions("boss", BOSS_ELEMENT_SKILLS.enemy_dragon_red) }),
      normalizeEnemyRecord({ ...{"id":"enemy_dragon_blue","name":"청룡","level":38,"monsterResourceId":"generated-enemy-dragon-blue","stats":{"maxHp":560,"maxMp":40,"attack":74,"defense":42,"mind":74,"agility":11},"rewards":{"exp":233,"gold":215,"dropRatePercent":15}}, actions: archetypeActions("boss", BOSS_ELEMENT_SKILLS.enemy_dragon_blue) }),
      normalizeEnemyRecord({ ...{"id":"enemy_dragon_bone","name":"본 드래곤","level":39,"monsterResourceId":"generated-enemy-dragon-bone","stats":{"maxHp":568,"maxMp":40,"attack":75,"defense":42,"mind":75,"agility":12},"rewards":{"exp":237,"gold":218,"dropRatePercent":15}}, actions: archetypeActions("boss", BOSS_ELEMENT_SKILLS.enemy_dragon_bone) }),
      normalizeEnemyRecord({ ...{"id":"enemy_hydra_three","name":"히드라","level":40,"monsterResourceId":"generated-enemy-hydra-three","stats":{"maxHp":576,"maxMp":40,"attack":77,"defense":43,"mind":77,"agility":13},"rewards":{"exp":240,"gold":222,"dropRatePercent":15}}, actions: archetypeActions("boss", BOSS_ELEMENT_SKILLS.enemy_hydra_three) }),
      normalizeEnemyRecord({ ...{"id":"enemy_behemoth_horn","name":"베히모스","level":41,"monsterResourceId":"generated-enemy-behemoth-horn","stats":{"maxHp":584,"maxMp":40,"attack":78,"defense":44,"mind":78,"agility":13},"rewards":{"exp":243,"gold":225,"dropRatePercent":15}}, actions: archetypeActions("boss", BOSS_ELEMENT_SKILLS.enemy_behemoth_horn) }),
      normalizeEnemyRecord({ ...{"id":"enemy_demon_lord","name":"마왕","level":42,"monsterResourceId":"generated-enemy-demon-lord","stats":{"maxHp":600,"maxMp":40,"attack":80,"defense":44,"mind":80,"agility":14},"rewards":{"exp":250,"gold":231,"dropRatePercent":15}}, actions: archetypeActions("boss", BOSS_ELEMENT_SKILLS.enemy_demon_lord) }),
      normalizeEnemyRecord({ ...{"id":"enemy_angel_fallen","name":"타락 천사","level":43,"monsterResourceId":"generated-enemy-angel-fallen","stats":{"maxHp":616,"maxMp":40,"attack":81,"defense":45,"mind":81,"agility":15},"rewards":{"exp":257,"gold":237,"dropRatePercent":15}}, actions: archetypeActions("boss", BOSS_ELEMENT_SKILLS.enemy_angel_fallen) }),
      normalizeEnemyRecord({ ...{"id":"enemy_eye_floating","name":"부유하는 눈","level":44,"monsterResourceId":"generated-enemy-eye-floating","stats":{"maxHp":608,"maxMp":40,"attack":83,"defense":46,"mind":83,"agility":15},"rewards":{"exp":253,"gold":234,"dropRatePercent":15}}, actions: archetypeActions("boss", BOSS_ELEMENT_SKILLS.enemy_eye_floating) }),
      normalizeEnemyRecord({ ...{"id":"enemy_plant_carnivore","name":"식충 식물","level":45,"monsterResourceId":"generated-enemy-plant-carnivore","stats":{"maxHp":624,"maxMp":40,"attack":84,"defense":46,"mind":84,"agility":16},"rewards":{"exp":260,"gold":240,"dropRatePercent":15}}, actions: archetypeActions("boss", BOSS_ELEMENT_SKILLS.enemy_plant_carnivore) }),
  ];
}
