import type { EquipmentRecord, ItemRecord } from "../types";
import { normalizeEquipmentRecord, normalizeItemRecord } from "../databaseRecordModel";
import { DEFAULT_ACTOR_ID, DEFAULT_CLASS_ID, DEFAULT_STATE_ID } from "./constants";
import {
  ACTOR_CLERIC_ID,
  ACTOR_GUARDIAN_ID,
  ACTOR_MAGE_ID,
  ACTOR_RANGER_ID,
  ACTOR_SCOUT_ID,
  ALL_ACTOR_IDS,
  ALL_CLASS_IDS,
  CLASS_CLERIC_ID,
  CLASS_GUARDIAN_ID,
  CLASS_MAGE_ID,
  CLASS_RANGER_ID,
  CLASS_SCOUT_ID,
} from "./defaultDatabaseRecordIds";

// scripts/asset-gen/manifest.mjs 의 생성 아이콘 100종에 대응하는 DB 레코드.
// 아이콘 id 규약: cc0-jetrel-<slug> / 레코드 id 규약: item_<slug 밑줄> · equip_<slug 밑줄>.
//
// 밸런스 기준선(기존 곡선):
//   회복약 item_potion HP 50 / 50G, 상급 회복약 HP 150 / 180G, 마력약 MP 30 / 120G, 엘릭서 600G.
//   무기 equip_sword 청동 atk8/100 · 철 atk14/180 · 강철 atk20/260.
//   방어구 참나무 방패 def5/80, 가죽 갑옷 def6/140, 견습 로브 def3+mind4/130.
// 이 범위에서 등급별로 스케일링한다. 재료·열쇠는 사용 효과 없는 보관용.

// 물리 전사계(검·도끼·창·철퇴·망치·낫·총) 착용 권한.
const WARRIOR_ACTORS = [DEFAULT_ACTOR_ID, ACTOR_GUARDIAN_ID];
const WARRIOR_CLASSES = [DEFAULT_CLASS_ID, CLASS_GUARDIAN_ID];
// 민첩 계열(단검·활·채찍·발톱·부메랑) 착용 권한.
const AGILE_ACTORS = [DEFAULT_ACTOR_ID, ACTOR_SCOUT_ID, ACTOR_RANGER_ID];
const AGILE_CLASSES = [DEFAULT_CLASS_ID, CLASS_SCOUT_ID, CLASS_RANGER_ID];
// 마법 계열(지팡이·마법봉·로브) 착용 권한.
const CASTER_ACTORS = [ACTOR_MAGE_ID, ACTOR_CLERIC_ID];
const CASTER_CLASSES = [CLASS_MAGE_ID, CLASS_CLERIC_ID];
// 방패 착용 권한.
const SHIELD_ACTORS = [DEFAULT_ACTOR_ID, ACTOR_GUARDIAN_ID, ACTOR_CLERIC_ID];
const SHIELD_CLASSES = [DEFAULT_CLASS_ID, CLASS_GUARDIAN_ID, CLASS_CLERIC_ID];
// 물리 갑옷 착용 권한.
const BODY_ACTORS = [DEFAULT_ACTOR_ID, ACTOR_GUARDIAN_ID, ACTOR_SCOUT_ID, ACTOR_RANGER_ID];
const BODY_CLASSES = [DEFAULT_CLASS_ID, CLASS_GUARDIAN_ID, CLASS_SCOUT_ID, CLASS_RANGER_ID];

export function generatedItemRecords(): ItemRecord[] {
  return [
    // ── 회복 소비품 ──
    normalizeItemRecord({
      id: "item_gen_potion_small",
      name: "작은 물약",
      type: "medicine",
      scope: "ally",
      price: 30,
      description: "아군 하나의 HP를 30 회복하는 작은 물약입니다.",
      imageResourceId: "cc0-jetrel-gen-potion-small",
      iconResourceId: "cc0-jetrel-gen-potion-small",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      hpRecovery: { flat: 30, percentMax: 0 },
      skillId: "skill_item_potion",
    }),
    normalizeItemRecord({
      id: "item_gen_potion_large",
      name: "큰 물약",
      type: "medicine",
      scope: "ally",
      price: 100,
      description: "아군 하나의 HP를 100 회복하는 큰 물약입니다.",
      imageResourceId: "cc0-jetrel-gen-potion-large",
      iconResourceId: "cc0-jetrel-gen-potion-large",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      hpRecovery: { flat: 100, percentMax: 0 },
      skillId: "skill_item_hi_potion",
    }),
    normalizeItemRecord({
      id: "item_gen_ether_vial",
      name: "에테르 병",
      type: "medicine",
      scope: "ally",
      price: 90,
      description: "아군 하나의 MP를 20 회복합니다.",
      imageResourceId: "cc0-jetrel-gen-ether-vial",
      iconResourceId: "cc0-jetrel-gen-ether-vial",
      animationId: "anim_magic",
      occasion: "always",
      consumable: true,
      mpRecovery: { flat: 20, percentMax: 0 },
      skillId: "skill_item_ether",
    }),
    normalizeItemRecord({
      id: "item_gen_ether_grand",
      name: "고급 에테르",
      type: "medicine",
      scope: "ally",
      price: 200,
      description: "아군 하나의 MP를 60 회복하는 고급 에테르입니다.",
      imageResourceId: "cc0-jetrel-gen-ether-grand",
      iconResourceId: "cc0-jetrel-gen-ether-grand",
      animationId: "anim_magic",
      occasion: "always",
      consumable: true,
      mpRecovery: { flat: 60, percentMax: 0 },
      skillId: "skill_item_ether",
    }),
    normalizeItemRecord({
      id: "item_gen_elixir_gold",
      name: "황금 엘릭서",
      type: "medicine",
      scope: "ally",
      price: 650,
      description: "아군 하나의 HP와 MP를 모두 완전히 회복하는 귀한 약입니다.",
      imageResourceId: "cc0-jetrel-gen-elixir-gold",
      iconResourceId: "cc0-jetrel-gen-elixir-gold",
      animationId: "anim_magic",
      occasion: "always",
      consumable: true,
      hpRecovery: { flat: 0, percentMax: 100 },
      mpRecovery: { flat: 0, percentMax: 100 },
      skillId: "skill_item_elixir",
    }),
    normalizeItemRecord({
      id: "item_gen_panacea_jar",
      name: "도자기 만능약",
      type: "medicine",
      scope: "ally",
      price: 220,
      description: "도자기 병에 담긴 약으로 독과 수면 상태를 한 번에 치료합니다.",
      imageResourceId: "cc0-jetrel-gen-panacea-jar",
      iconResourceId: "cc0-jetrel-gen-panacea-jar",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      healStateIds: [DEFAULT_STATE_ID, "state_sleep"],
      stateEffects: [{ stateId: DEFAULT_STATE_ID, chance: 100, operation: "remove" }, { stateId: "state_sleep", chance: 100, operation: "remove" }],
      skillId: "skill_item_panacea",
    }),
    normalizeItemRecord({
      id: "item_gen_antidote_leaf",
      name: "해독 잎",
      type: "medicine",
      scope: "ally",
      price: 25,
      description: "독 상태를 해제하는 약초 잎입니다.",
      imageResourceId: "cc0-jetrel-gen-antidote-leaf",
      iconResourceId: "cc0-jetrel-gen-antidote-leaf",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      healStateIds: [DEFAULT_STATE_ID],
      stateEffects: [{ stateId: DEFAULT_STATE_ID, chance: 100, operation: "remove" }],
      skillId: "skill_item_antidote",
    }),
    normalizeItemRecord({
      id: "item_gen_eyedrops",
      name: "눈약",
      type: "medicine",
      scope: "ally",
      price: 35,
      description: "수면에 빠진 아군을 깨우는 눈약입니다.",
      imageResourceId: "cc0-jetrel-gen-eyedrops",
      iconResourceId: "cc0-jetrel-gen-eyedrops",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      healStateIds: ["state_sleep"],
      stateEffects: [{ stateId: "state_sleep", chance: 100, operation: "remove" }],
      skillId: "skill_item_wake",
    }),
    normalizeItemRecord({
      id: "item_gen_echo_bell",
      name: "메아리 종",
      type: "medicine",
      scope: "ally",
      price: 45,
      description: "맑은 종소리로 수면에 빠진 아군을 깨웁니다.",
      imageResourceId: "cc0-jetrel-gen-echo-bell",
      iconResourceId: "cc0-jetrel-gen-echo-bell",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      healStateIds: ["state_sleep"],
      stateEffects: [{ stateId: "state_sleep", chance: 100, operation: "remove" }],
      skillId: "skill_item_wake",
    }),
    normalizeItemRecord({
      id: "item_gen_revive_feather",
      name: "부활 깃털",
      type: "medicine",
      scope: "ally",
      price: 400,
      description: "쓰러진 아군 하나를 HP 절반으로 되살리는 깃털입니다.",
      imageResourceId: "cc0-jetrel-gen-revive-feather",
      iconResourceId: "cc0-jetrel-gen-revive-feather",
      animationId: "anim_heal",
      occasion: "field",
      occasionField: true,
      occasionBattle: false,
      consumable: true,
      onlyEffectiveOnDeadActors: true,
      hpRecovery: { flat: 0, percentMax: 50 },
    }),
    normalizeItemRecord({
      id: "item_gen_phoenix_ash",
      name: "불사조 재",
      type: "medicine",
      scope: "ally",
      price: 800,
      description: "쓰러진 아군 하나를 HP 가득 채워 되살리는 귀한 재입니다.",
      imageResourceId: "cc0-jetrel-gen-phoenix-ash",
      iconResourceId: "cc0-jetrel-gen-phoenix-ash",
      animationId: "anim_heal",
      occasion: "field",
      occasionField: true,
      occasionBattle: false,
      consumable: true,
      onlyEffectiveOnDeadActors: true,
      hpRecovery: { flat: 0, percentMax: 100 },
    }),
    normalizeItemRecord({
      id: "item_gen_bandage_roll",
      name: "붕대",
      type: "medicine",
      scope: "ally",
      price: 20,
      description: "아군 하나의 HP를 20 회복하는 응급 붕대입니다.",
      imageResourceId: "cc0-jetrel-gen-bandage-roll",
      iconResourceId: "cc0-jetrel-gen-bandage-roll",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      hpRecovery: { flat: 20, percentMax: 0 },
      skillId: "skill_item_potion",
    }),
    normalizeItemRecord({
      id: "item_gen_herb_bundle",
      name: "약초 다발",
      type: "medicine",
      scope: "ally",
      price: 40,
      description: "아군 하나의 HP를 40 회복하는 약초 다발입니다.",
      imageResourceId: "cc0-jetrel-gen-herb-bundle",
      iconResourceId: "cc0-jetrel-gen-herb-bundle",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      hpRecovery: { flat: 40, percentMax: 0 },
      skillId: "skill_item_potion",
    }),
    normalizeItemRecord({
      id: "item_gen_honey_jar",
      name: "꿀단지",
      type: "medicine",
      scope: "ally",
      price: 80,
      description: "아군 하나의 HP를 60, MP를 10 회복하는 달콤한 꿀입니다.",
      imageResourceId: "cc0-jetrel-gen-honey-jar",
      iconResourceId: "cc0-jetrel-gen-honey-jar",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      hpRecovery: { flat: 60, percentMax: 0 },
      mpRecovery: { flat: 10, percentMax: 0 },
      skillId: "skill_item_potion",
    }),
    normalizeItemRecord({
      id: "item_gen_milk_bottle",
      name: "우유병",
      type: "medicine",
      scope: "ally",
      price: 45,
      description: "아군 하나의 HP를 30, MP를 5 회복하는 신선한 우유입니다.",
      imageResourceId: "cc0-jetrel-gen-milk-bottle",
      iconResourceId: "cc0-jetrel-gen-milk-bottle",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      hpRecovery: { flat: 30, percentMax: 0 },
      mpRecovery: { flat: 5, percentMax: 0 },
      skillId: "skill_item_potion",
    }),
    // ── 공격 소비품 ──
    normalizeItemRecord({
      id: "item_gen_fire_bomb",
      name: "화염탄",
      type: "special",
      scope: "enemy",
      price: 100,
      description: "적 하나에게 화염 피해를 주는 투척용 폭탄입니다.",
      imageResourceId: "cc0-jetrel-gen-fire-bomb",
      iconResourceId: "cc0-jetrel-gen-fire-bomb",
      skillId: "skill_fire",
      animationId: "anim_magic",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_gen_ice_shard",
      name: "얼음 조각",
      type: "special",
      scope: "enemy",
      price: 100,
      description: "적 하나에게 냉기 피해를 주는 날카로운 얼음 조각입니다.",
      imageResourceId: "cc0-jetrel-gen-ice-shard",
      iconResourceId: "cc0-jetrel-gen-ice-shard",
      skillId: "skill_water",
      animationId: "anim_magic",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_gen_thunder_rod",
      name: "번개 막대",
      type: "special",
      scope: "enemy",
      price: 120,
      description: "적 하나에게 전격 피해를 방출하는 마법 막대입니다.",
      imageResourceId: "cc0-jetrel-gen-thunder-rod",
      iconResourceId: "cc0-jetrel-gen-thunder-rod",
      skillId: "skill_arcane_bolt",
      animationId: "anim_magic",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_gen_poison_flask",
      name: "독 플라스크",
      type: "special",
      scope: "enemy",
      price: 140,
      description: "적 하나에게 독을 노리는 투척용 플라스크입니다.",
      imageResourceId: "cc0-jetrel-gen-poison-flask",
      iconResourceId: "cc0-jetrel-gen-poison-flask",
      skillId: "skill_item_poison_vial",
      animationId: "anim_poison",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_gen_smoke_ball",
      name: "연막탄",
      type: "special",
      scope: "enemy",
      price: 60,
      description: "적 하나의 공격을 낮추는 짙은 연막을 퍼뜨리는 구슬입니다.",
      imageResourceId: "cc0-jetrel-gen-smoke-ball",
      iconResourceId: "cc0-jetrel-gen-smoke-ball",
      skillId: "skill_weaken",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_gen_throwing_knife",
      name: "균형 투척 단검",
      type: "special",
      scope: "enemy",
      price: 110,
      description: "무게중심을 맞춰 적 하나에게 정확히 던지는 전투용 단검입니다.",
      imageResourceId: "cc0-jetrel-gen-throwing-knife",
      iconResourceId: "cc0-jetrel-gen-throwing-knife",
      skillId: "skill_throwing_knife",
      animationId: "anim_arrow",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_gen_shuriken",
      name: "수리검",
      type: "special",
      scope: "enemy",
      price: 120,
      description: "적 하나에게 날려 피해를 주는 동방식 수리검입니다.",
      imageResourceId: "cc0-jetrel-gen-shuriken",
      iconResourceId: "cc0-jetrel-gen-shuriken",
      skillId: "skill_throwing_knife",
      animationId: "anim_arrow",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_gen_holy_water",
      name: "성수",
      type: "special",
      scope: "enemy",
      price: 130,
      description: "적 하나에게 신성한 피해를 주는 축복받은 물입니다.",
      imageResourceId: "cc0-jetrel-gen-holy-water",
      iconResourceId: "cc0-jetrel-gen-holy-water",
      skillId: "skill_arcane_bolt",
      animationId: "anim_magic",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_gen_net_trap",
      name: "포획 그물",
      type: "special",
      scope: "enemy",
      price: 100,
      description: "약해진 몬스터를 포획하는 데 쓰는 튼튼한 그물입니다.",
      imageResourceId: "cc0-jetrel-gen-net-trap",
      iconResourceId: "cc0-jetrel-gen-net-trap",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
      captureProfile: { multiplier: 1.1 },
    }),
    normalizeItemRecord({
      id: "item_gen_capture_sphere",
      name: "강화 포획 구슬",
      type: "special",
      scope: "enemy",
      price: 120,
      description: "약해진 몬스터를 포획하는 성능 좋은 구슬입니다.",
      imageResourceId: "cc0-jetrel-gen-capture-sphere",
      iconResourceId: "cc0-jetrel-gen-capture-sphere",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
      captureProfile: { multiplier: 1.2 },
    }),
    // ── 재료 (사용 효과 없는 보관용) ──
    normalizeItemRecord({
      id: "item_gen_ore_copper",
      name: "구리 광석",
      type: "normalGoods",
      scope: "none",
      price: 15,
      description: "구리가 섞인 광석 덩어리입니다. 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-ore-copper",
      iconResourceId: "cc0-jetrel-gen-ore-copper",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_ore_iron",
      name: "제련용 철 광석",
      type: "normalGoods",
      scope: "none",
      price: 30,
      description: "철이 박힌 광석 덩어리입니다. 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-ore-iron",
      iconResourceId: "cc0-jetrel-gen-ore-iron",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_ore_mythril",
      name: "미스릴 광석",
      type: "normalGoods",
      scope: "none",
      price: 120,
      description: "미스릴 결정이 빛나는 희귀 광석입니다. 고급 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-ore-mythril",
      iconResourceId: "cc0-jetrel-gen-ore-mythril",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_ingot_gold",
      name: "금괴",
      type: "normalGoods",
      scope: "none",
      price: 200,
      description: "순금으로 주조한 작은 금괴입니다. 비싸게 팔 수 있습니다.",
      imageResourceId: "cc0-jetrel-gen-ingot-gold",
      iconResourceId: "cc0-jetrel-gen-ingot-gold",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_gem_ruby",
      name: "루비",
      type: "normalGoods",
      scope: "none",
      price: 150,
      description: "붉게 빛나는 보석입니다. 장신구 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-gem-ruby",
      iconResourceId: "cc0-jetrel-gen-gem-ruby",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_gem_sapphire",
      name: "사파이어",
      type: "normalGoods",
      scope: "none",
      price: 150,
      description: "푸르게 빛나는 보석입니다. 장신구 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-gem-sapphire",
      iconResourceId: "cc0-jetrel-gen-gem-sapphire",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_gem_emerald",
      name: "에메랄드",
      type: "normalGoods",
      scope: "none",
      price: 150,
      description: "초록빛으로 빛나는 보석입니다. 장신구 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-gem-emerald",
      iconResourceId: "cc0-jetrel-gen-gem-emerald",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_pelt_wolf",
      name: "늑대 가죽",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "늑대에게서 벗긴 가죽입니다. 방어구 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-pelt-wolf",
      iconResourceId: "cc0-jetrel-gen-pelt-wolf",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_fang_beast",
      name: "야수 이빨",
      type: "normalGoods",
      scope: "none",
      price: 25,
      description: "날카로운 야수의 이빨입니다. 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-fang-beast",
      iconResourceId: "cc0-jetrel-gen-fang-beast",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_scale_dragon",
      name: "용의 비늘",
      type: "normalGoods",
      scope: "none",
      price: 300,
      description: "영롱한 빛을 내는 용의 비늘입니다. 최고급 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-scale-dragon",
      iconResourceId: "cc0-jetrel-gen-scale-dragon",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_feather_raven",
      name: "까마귀 깃털",
      type: "normalGoods",
      scope: "none",
      price: 10,
      description: "윤기 나는 검은 깃털입니다. 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-feather-raven",
      iconResourceId: "cc0-jetrel-gen-feather-raven",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_thread_silk",
      name: "명주실",
      type: "normalGoods",
      scope: "none",
      price: 40,
      description: "고운 명주실 한 타래입니다. 로브 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-thread-silk",
      iconResourceId: "cc0-jetrel-gen-thread-silk",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_plank_oak",
      name: "떡갈 판자",
      type: "normalGoods",
      scope: "none",
      price: 15,
      description: "떡갈나무로 만든 판자 더미입니다. 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-plank-oak",
      iconResourceId: "cc0-jetrel-gen-plank-oak",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_slime_jelly",
      name: "슬라임 젤리",
      type: "normalGoods",
      scope: "none",
      price: 12,
      description: "말랑말랑한 슬라임의 젤리입니다. 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-slime-jelly",
      iconResourceId: "cc0-jetrel-gen-slime-jelly",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_mushroom_cave",
      name: "동굴 버섯",
      type: "normalGoods",
      scope: "none",
      price: 18,
      description: "동굴에서 자란 보라색 버섯입니다. 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-mushroom-cave",
      iconResourceId: "cc0-jetrel-gen-mushroom-cave",
      occasion: "never",
      consumable: false,
    }),
    // ── 열쇠·퀘스트 (사용 효과 없는 보관용) ──
    normalizeItemRecord({
      id: "item_gen_key_rusty",
      name: "녹슨 열쇠",
      type: "normalGoods",
      scope: "none",
      price: 0,
      description: "녹슨 철 열쇠입니다. 오래된 문을 열 수 있을 것 같습니다.",
      imageResourceId: "cc0-jetrel-gen-key-rusty",
      iconResourceId: "cc0-jetrel-gen-key-rusty",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_key_gold",
      name: "황금 열쇠",
      type: "normalGoods",
      scope: "none",
      price: 0,
      description: "화려한 황금 열쇠입니다. 중요한 문을 열 수 있을 것 같습니다.",
      imageResourceId: "cc0-jetrel-gen-key-gold",
      iconResourceId: "cc0-jetrel-gen-key-gold",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_map_scroll",
      name: "지도 두루마리",
      type: "normalGoods",
      scope: "none",
      price: 0,
      description: "붉은 X 표시가 있는 지도 두루마리입니다. 보물의 위치를 가리킵니다.",
      imageResourceId: "cc0-jetrel-gen-map-scroll",
      iconResourceId: "cc0-jetrel-gen-map-scroll",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_letter_sealed",
      name: "봉인된 편지",
      type: "normalGoods",
      scope: "none",
      price: 0,
      description: "붉은 밀랍으로 봉인된 편지입니다. 누군가에게 전달해야 합니다.",
      imageResourceId: "cc0-jetrel-gen-letter-sealed",
      iconResourceId: "cc0-jetrel-gen-letter-sealed",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_lamp_oil",
      name: "기름 등불",
      type: "normalGoods",
      scope: "none",
      price: 50,
      description: "어두운 곳을 밝히는 황동 기름 등불입니다.",
      imageResourceId: "cc0-jetrel-gen-lamp-oil",
      iconResourceId: "cc0-jetrel-gen-lamp-oil",
      occasion: "never",
      consumable: false,
    }),
  ];
}

export function generatedEquipmentRecords(): EquipmentRecord[] {
  return [
    // ── 무기 ──
    normalizeEquipmentRecord({
      id: "equip_gen_sword_bronze",
      name: "보급형 청동 검",
      slot: "weapon",
      price: 100,
      imageResourceId: "cc0-jetrel-gen-sword-bronze",
      iconResourceId: "cc0-jetrel-gen-sword-bronze",
      description: "균형 잡힌 초보자용 청동 검입니다.",
      statBonuses: { attack: 8, defense: 0, mind: 0, agility: 0 },
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_sword_iron",
      name: "제련소 철 검",
      slot: "weapon",
      price: 180,
      imageResourceId: "cc0-jetrel-gen-sword-iron",
      iconResourceId: "cc0-jetrel-gen-sword-iron",
      description: "묵직한 철제 장검입니다.",
      statBonuses: { attack: 14, defense: 0, mind: 0, agility: 0 },
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_sword_steel",
      name: "기사단 강철 검",
      slot: "weapon",
      price: 260,
      imageResourceId: "cc0-jetrel-gen-sword-steel",
      iconResourceId: "cc0-jetrel-gen-sword-steel",
      description: "기사단 규격으로 벼려 공격력을 크게 높이는 강철 검입니다.",
      statBonuses: { attack: 20, defense: 0, mind: 0, agility: -1 },
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_sword_flame",
      name: "화염 검",
      slot: "weapon",
      price: 420,
      imageResourceId: "cc0-jetrel-gen-sword-flame",
      iconResourceId: "cc0-jetrel-gen-sword-flame",
      description: "불꽃이 감도는 마법 검입니다.",
      statBonuses: { attack: 26, defense: 0, mind: 0, agility: 0 },
      attackElementIds: ["fire"],
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_sword_frost",
      name: "서릿 검",
      slot: "weapon",
      price: 420,
      imageResourceId: "cc0-jetrel-gen-sword-frost",
      iconResourceId: "cc0-jetrel-gen-sword-frost",
      description: "서리가 내려앉은 마법 검입니다.",
      statBonuses: { attack: 26, defense: 0, mind: 0, agility: 0 },
      attackElementIds: ["water"],
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_dagger_scout",
      name: "경량 정찰 단검",
      slot: "weapon",
      price: 90,
      imageResourceId: "cc0-jetrel-gen-dagger-scout",
      iconResourceId: "cc0-jetrel-gen-dagger-scout",
      description: "정찰 임무의 빠른 움직임에 맞춘 가벼운 단검입니다.",
      statBonuses: { attack: 5, defense: 0, mind: 0, agility: 3 },
      equippableActorIds: [...AGILE_ACTORS],
      equippableClassIds: [...AGILE_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_rapier_noble",
      name: "귀족 레이피어",
      slot: "weapon",
      price: 300,
      imageResourceId: "cc0-jetrel-gen-rapier-noble",
      iconResourceId: "cc0-jetrel-gen-rapier-noble",
      description: "화려하면서도 날카로운 귀족용 레이피어입니다.",
      statBonuses: { attack: 16, defense: 0, mind: 0, agility: 4 },
      equippableActorIds: [...AGILE_ACTORS],
      equippableClassIds: [...AGILE_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_axe_battle",
      name: "전투 도끼",
      slot: "weapon",
      price: 320,
      imageResourceId: "cc0-jetrel-gen-axe-battle",
      iconResourceId: "cc0-jetrel-gen-axe-battle",
      description: "한 손으로 휘두르는 묵직한 전투 도끼입니다.",
      statBonuses: { attack: 22, defense: 0, mind: 0, agility: -1 },
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_axe_great",
      name: "대형 도끼",
      slot: "weapon",
      price: 520,
      imageResourceId: "cc0-jetrel-gen-axe-great",
      iconResourceId: "cc0-jetrel-gen-axe-great",
      description: "양손으로 휘둘러 막대한 피해를 주는 대형 도끼입니다.",
      statBonuses: { attack: 30, defense: 0, mind: 0, agility: -2 },
      twoHanded: true,
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_spear_iron",
      name: "철 창",
      slot: "weapon",
      price: 240,
      imageResourceId: "cc0-jetrel-gen-spear-iron",
      iconResourceId: "cc0-jetrel-gen-spear-iron",
      description: "긴 리치를 가진 철제 창입니다.",
      statBonuses: { attack: 18, defense: 0, mind: 0, agility: 1 },
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_halberd_guard",
      name: "경비 할버드",
      slot: "weapon",
      price: 380,
      imageResourceId: "cc0-jetrel-gen-halberd-guard",
      iconResourceId: "cc0-jetrel-gen-halberd-guard",
      description: "도끼날과 창끝을 함께 지닌 경비대용 할버드입니다.",
      statBonuses: { attack: 24, defense: 2, mind: 0, agility: 0 },
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_mace_heavy",
      name: "중형 철퇴",
      slot: "weapon",
      price: 300,
      imageResourceId: "cc0-jetrel-gen-mace-heavy",
      iconResourceId: "cc0-jetrel-gen-mace-heavy",
      description: "무거운 철제 철퇴입니다. 방어구를 무시하는 타격을 줍니다.",
      statBonuses: { attack: 21, defense: 0, mind: 0, agility: -1 },
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_hammer_war",
      name: "전쟁 망치",
      slot: "weapon",
      price: 480,
      imageResourceId: "cc0-jetrel-gen-hammer-war",
      iconResourceId: "cc0-jetrel-gen-hammer-war",
      description: "양손으로 내리치는 거대한 전쟁 망치입니다.",
      statBonuses: { attack: 28, defense: 0, mind: 0, agility: -2 },
      twoHanded: true,
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_bow_short",
      name: "단궁",
      slot: "weapon",
      price: 160,
      imageResourceId: "cc0-jetrel-gen-bow-short",
      iconResourceId: "cc0-jetrel-gen-bow-short",
      description: "가볍고 다루기 쉬운 짧은 활입니다.",
      statBonuses: { attack: 12, defense: 0, mind: 0, agility: 2 },
      equippableActorIds: [...AGILE_ACTORS],
      equippableClassIds: [...AGILE_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_bow_long",
      name: "장궁",
      slot: "weapon",
      price: 280,
      imageResourceId: "cc0-jetrel-gen-bow-long",
      iconResourceId: "cc0-jetrel-gen-bow-long",
      description: "먼 거리까지 화살을 날리는 긴 활입니다.",
      statBonuses: { attack: 18, defense: 0, mind: 0, agility: 3 },
      equippableActorIds: [...AGILE_ACTORS],
      equippableClassIds: [...AGILE_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_crossbow_hand",
      name: "손 석궁",
      slot: "weapon",
      price: 220,
      imageResourceId: "cc0-jetrel-gen-crossbow-hand",
      iconResourceId: "cc0-jetrel-gen-crossbow-hand",
      description: "작지만 관통력이 뛰어난 손 석궁입니다.",
      statBonuses: { attack: 16, defense: 0, mind: 0, agility: 2 },
      equippableActorIds: [...AGILE_ACTORS],
      equippableClassIds: [...AGILE_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_staff_oak",
      name: "떡갈나무 지팡이",
      slot: "weapon",
      price: 120,
      imageResourceId: "cc0-jetrel-gen-staff-oak",
      iconResourceId: "cc0-jetrel-gen-staff-oak",
      description: "수습 마도사가 마력을 안정시키도록 돕는 나무 지팡이입니다.",
      statBonuses: { attack: 3, defense: 0, mind: 7, agility: 0 },
      equippableActorIds: [...CASTER_ACTORS],
      equippableClassIds: [...CASTER_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_staff_crystal",
      name: "수정 지팡이",
      slot: "weapon",
      price: 320,
      imageResourceId: "cc0-jetrel-gen-staff-crystal",
      iconResourceId: "cc0-jetrel-gen-staff-crystal",
      description: "수정 구슬을 얹어 마법을 크게 증폭하는 지팡이입니다.",
      statBonuses: { attack: 4, defense: 0, mind: 14, agility: 0 },
      equippableActorIds: [...CASTER_ACTORS],
      equippableClassIds: [...CASTER_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_wand_spark",
      name: "불꽃 마법봉",
      slot: "weapon",
      price: 240,
      imageResourceId: "cc0-jetrel-gen-wand-spark",
      iconResourceId: "cc0-jetrel-gen-wand-spark",
      description: "끝에서 불꽃이 일렁이는 마법봉입니다.",
      statBonuses: { attack: 2, defense: 0, mind: 10, agility: 0 },
      attackElementIds: ["fire"],
      equippableActorIds: [...CASTER_ACTORS],
      equippableClassIds: [...CASTER_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_katana_east",
      name: "동방 도",
      slot: "weapon",
      price: 400,
      imageResourceId: "cc0-jetrel-gen-katana-east",
      iconResourceId: "cc0-jetrel-gen-katana-east",
      description: "동방에서 온 날렵한 곡도입니다.",
      statBonuses: { attack: 23, defense: 0, mind: 0, agility: 3 },
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_claw_beast",
      name: "야수 발톱",
      slot: "weapon",
      price: 260,
      imageResourceId: "cc0-jetrel-gen-claw-beast",
      iconResourceId: "cc0-jetrel-gen-claw-beast",
      description: "손에 감아 휘두르는 세 갈래 강철 발톱입니다.",
      statBonuses: { attack: 14, defense: 0, mind: 0, agility: 5 },
      equippableActorIds: [...AGILE_ACTORS],
      equippableClassIds: [...AGILE_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_whip_leather",
      name: "가죽 채찍",
      slot: "weapon",
      price: 200,
      imageResourceId: "cc0-jetrel-gen-whip-leather",
      iconResourceId: "cc0-jetrel-gen-whip-leather",
      description: "긴 리치로 적을 휘감는 가죽 채찍입니다.",
      statBonuses: { attack: 15, defense: 0, mind: 0, agility: 2 },
      equippableActorIds: [...AGILE_ACTORS],
      equippableClassIds: [...AGILE_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_scythe_reaper",
      name: "사신 낫",
      slot: "weapon",
      price: 600,
      imageResourceId: "cc0-jetrel-gen-scythe-reaper",
      iconResourceId: "cc0-jetrel-gen-scythe-reaper",
      description: "거대한 낫으로 양손으로 휘둘러 막대한 피해를 줍니다.",
      statBonuses: { attack: 32, defense: 0, mind: 0, agility: -2 },
      twoHanded: true,
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_gun_flint",
      name: "화승총",
      slot: "weapon",
      price: 460,
      imageResourceId: "cc0-jetrel-gen-gun-flint",
      iconResourceId: "cc0-jetrel-gen-gun-flint",
      description: "화약으로 탄환을 발사하는 화승총입니다.",
      statBonuses: { attack: 25, defense: 0, mind: 0, agility: 1 },
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_boomerang_wood",
      name: "부메랑",
      slot: "weapon",
      price: 150,
      imageResourceId: "cc0-jetrel-gen-boomerang-wood",
      iconResourceId: "cc0-jetrel-gen-boomerang-wood",
      description: "던지면 되돌아오는 나무 부메랑입니다.",
      statBonuses: { attack: 10, defense: 0, mind: 0, agility: 4 },
      equippableActorIds: [...AGILE_ACTORS],
      equippableClassIds: [...AGILE_CLASSES],
    }),
    // ── 방어구: 방패 ──
    normalizeEquipmentRecord({
      id: "equip_gen_shield_wood",
      name: "나무 방패",
      slot: "shield",
      price: 70,
      imageResourceId: "cc0-jetrel-gen-shield-wood",
      iconResourceId: "cc0-jetrel-gen-shield-wood",
      description: "가볍고 소박한 나무 방패입니다.",
      statBonuses: { attack: 0, defense: 4, mind: 0, agility: 0 },
      equippableActorIds: [...SHIELD_ACTORS],
      equippableClassIds: [...SHIELD_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_shield_iron",
      name: "철 방패",
      slot: "shield",
      price: 160,
      imageResourceId: "cc0-jetrel-gen-shield-iron",
      iconResourceId: "cc0-jetrel-gen-shield-iron",
      description: "튼튼한 철제 연 방패입니다.",
      statBonuses: { attack: 0, defense: 8, mind: 0, agility: 0 },
      equippableActorIds: [...SHIELD_ACTORS],
      equippableClassIds: [...SHIELD_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_shield_tower",
      name: "타워 실드",
      slot: "shield",
      price: 320,
      imageResourceId: "cc0-jetrel-gen-shield-tower",
      iconResourceId: "cc0-jetrel-gen-shield-tower",
      description: "몸을 통째로 가리는 거대한 방패입니다.",
      statBonuses: { attack: 0, defense: 14, mind: 0, agility: -1 },
      equippableActorIds: [...SHIELD_ACTORS],
      equippableClassIds: [...SHIELD_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_shield_mirror",
      name: "거울 방패",
      slot: "shield",
      price: 280,
      imageResourceId: "cc0-jetrel-gen-shield-mirror",
      iconResourceId: "cc0-jetrel-gen-shield-mirror",
      description: "빛을 반사하는 은빛 거울 방패입니다.",
      statBonuses: { attack: 0, defense: 10, mind: 3, agility: 0 },
      equippableActorIds: [...SHIELD_ACTORS],
      equippableClassIds: [...SHIELD_CLASSES],
    }),
    // ── 방어구: 갑옷 ──
    normalizeEquipmentRecord({
      id: "equip_gen_armor_leather",
      name: "사냥꾼 가죽 갑옷",
      slot: "armor",
      price: 140,
      imageResourceId: "cc0-jetrel-gen-armor-leather",
      iconResourceId: "cc0-jetrel-gen-armor-leather",
      description: "여행자를 위한 기본 가죽 갑옷입니다.",
      statBonuses: { attack: 0, defense: 6, mind: 0, agility: 0 },
      equippableActorIds: [...BODY_ACTORS],
      equippableClassIds: [...BODY_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_armor_chain",
      name: "사슬 갑옷",
      slot: "armor",
      price: 240,
      imageResourceId: "cc0-jetrel-gen-armor-chain",
      iconResourceId: "cc0-jetrel-gen-armor-chain",
      description: "사슬을 엮어 만든 튼튼한 갑옷입니다.",
      statBonuses: { attack: 0, defense: 10, mind: 0, agility: -1 },
      equippableActorIds: [...BODY_ACTORS],
      equippableClassIds: [...BODY_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_armor_plate",
      name: "판금 갑옷",
      slot: "armor",
      price: 420,
      imageResourceId: "cc0-jetrel-gen-armor-plate",
      iconResourceId: "cc0-jetrel-gen-armor-plate",
      description: "강철판으로 온몸을 감싸는 중갑옷입니다.",
      statBonuses: { attack: 0, defense: 16, mind: 0, agility: -2 },
      equippableActorIds: [...BODY_ACTORS],
      equippableClassIds: [...BODY_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_armor_mythril",
      name: "미스릴 갑옷",
      slot: "armor",
      price: 700,
      imageResourceId: "cc0-jetrel-gen-armor-mythril",
      iconResourceId: "cc0-jetrel-gen-armor-mythril",
      description: "미스릴로 만들어 가볍고도 단단한 최고급 갑옷입니다.",
      statBonuses: { attack: 0, defense: 22, mind: 0, agility: 2 },
      equippableActorIds: [...BODY_ACTORS],
      equippableClassIds: [...BODY_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_robe_cloth",
      name: "천 로브",
      slot: "armor",
      price: 100,
      imageResourceId: "cc0-jetrel-gen-robe-cloth",
      iconResourceId: "cc0-jetrel-gen-robe-cloth",
      description: "마법 수련생을 위한 소박한 천 로브입니다.",
      statBonuses: { attack: 0, defense: 3, mind: 2, agility: 0 },
      equippableActorIds: [...CASTER_ACTORS],
      equippableClassIds: [...CASTER_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_robe_mage",
      name: "마법사 로브",
      slot: "armor",
      price: 300,
      imageResourceId: "cc0-jetrel-gen-robe-mage",
      iconResourceId: "cc0-jetrel-gen-robe-mage",
      description: "마력을 북돋우는 정통 마법사 로브입니다.",
      statBonuses: { attack: 0, defense: 5, mind: 8, agility: 0 },
      equippableActorIds: [...CASTER_ACTORS],
      equippableClassIds: [...CASTER_CLASSES],
    }),
    // ── 방어구: 투구 ──
    normalizeEquipmentRecord({
      id: "equip_gen_helm_leather",
      name: "가죽 투구",
      slot: "helmet",
      price: 60,
      imageResourceId: "cc0-jetrel-gen-helm-leather",
      iconResourceId: "cc0-jetrel-gen-helm-leather",
      description: "가볍게 머리를 보호하는 가죽 투구입니다.",
      statBonuses: { attack: 0, defense: 3, mind: 0, agility: 0 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_helm_iron",
      name: "철 투구",
      slot: "helmet",
      price: 140,
      imageResourceId: "cc0-jetrel-gen-helm-iron",
      iconResourceId: "cc0-jetrel-gen-helm-iron",
      description: "튼튼한 철제 투구입니다.",
      statBonuses: { attack: 0, defense: 6, mind: 0, agility: 0 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_helm_horned",
      name: "뿔 투구",
      slot: "helmet",
      price: 220,
      imageResourceId: "cc0-jetrel-gen-helm-horned",
      iconResourceId: "cc0-jetrel-gen-helm-horned",
      description: "뿔 장식이 달린 위압적인 투구입니다.",
      statBonuses: { attack: 2, defense: 8, mind: 0, agility: 0 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_hat_traveler",
      name: "개척자 여행 모자",
      slot: "helmet",
      price: 60,
      imageResourceId: "cc0-jetrel-gen-hat-traveler",
      iconResourceId: "cc0-jetrel-gen-hat-traveler",
      description: "개척지의 햇빛과 비바람을 막아 주는 튼튼한 모자입니다.",
      statBonuses: { attack: 0, defense: 2, mind: 1, agility: 0 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_hat_witch",
      name: "마녀 모자",
      slot: "helmet",
      price: 200,
      imageResourceId: "cc0-jetrel-gen-hat-witch",
      iconResourceId: "cc0-jetrel-gen-hat-witch",
      description: "마력을 끌어올리는 뾰족한 마녀 모자입니다.",
      statBonuses: { attack: 0, defense: 2, mind: 6, agility: 0 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    // ── 방어구: 장신구(신발·장갑·망토·허리띠) ──
    normalizeEquipmentRecord({
      id: "equip_gen_boots_leather",
      name: "가죽 장화",
      slot: "accessory",
      price: 120,
      imageResourceId: "cc0-jetrel-gen-boots-leather",
      iconResourceId: "cc0-jetrel-gen-boots-leather",
      description: "발걸음을 가볍게 하는 가죽 장화입니다.",
      statBonuses: { attack: 0, defense: 2, mind: 0, agility: 2 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_boots_swift",
      name: "신속 장화",
      slot: "accessory",
      price: 260,
      imageResourceId: "cc0-jetrel-gen-boots-swift",
      iconResourceId: "cc0-jetrel-gen-boots-swift",
      description: "날개 장식이 달려 발걸음을 크게 빠르게 하는 장화입니다.",
      statBonuses: { attack: 0, defense: 0, mind: 0, agility: 5 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_gloves_iron",
      name: "철 장갑",
      slot: "accessory",
      price: 180,
      imageResourceId: "cc0-jetrel-gen-gloves-iron",
      iconResourceId: "cc0-jetrel-gen-gloves-iron",
      description: "주먹에 힘을 싣는 철제 건틀릿입니다.",
      statBonuses: { attack: 3, defense: 2, mind: 0, agility: 0 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_cloak_shadow",
      name: "그림자 망토",
      slot: "accessory",
      price: 240,
      imageResourceId: "cc0-jetrel-gen-cloak-shadow",
      iconResourceId: "cc0-jetrel-gen-cloak-shadow",
      description: "몸놀림을 가볍게 하는 어두운 망토입니다.",
      statBonuses: { attack: 0, defense: 3, mind: 0, agility: 3 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_belt_champion",
      name: "챔피언 벨트",
      slot: "accessory",
      price: 300,
      imageResourceId: "cc0-jetrel-gen-belt-champion",
      iconResourceId: "cc0-jetrel-gen-belt-champion",
      description: "힘과 맷집을 함께 길러주는 챔피언의 허리띠입니다.",
      statBonuses: { attack: 2, defense: 3, mind: 0, agility: 0 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    // ── 장식 ──
    normalizeEquipmentRecord({
      id: "equip_gen_ring_silver",
      name: "은 반지",
      slot: "accessory",
      price: 120,
      imageResourceId: "cc0-jetrel-gen-ring-silver",
      iconResourceId: "cc0-jetrel-gen-ring-silver",
      description: "마력을 살짝 북돋우는 은 반지입니다.",
      statBonuses: { attack: 0, defense: 0, mind: 2, agility: 0 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_ring_power",
      name: "힘의 반지",
      slot: "accessory",
      price: 260,
      imageResourceId: "cc0-jetrel-gen-ring-power",
      iconResourceId: "cc0-jetrel-gen-ring-power",
      description: "힘을 끌어올리는 루비 박힌 금반지입니다.",
      statBonuses: { attack: 4, defense: 0, mind: 0, agility: 0 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_amulet_moon",
      name: "달 부적",
      slot: "accessory",
      price: 180,
      imageResourceId: "cc0-jetrel-gen-amulet-moon",
      iconResourceId: "cc0-jetrel-gen-amulet-moon",
      description: "달의 가호가 서린 부적입니다.",
      statBonuses: { attack: 0, defense: 1, mind: 3, agility: 0 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_amulet_sun",
      name: "태양 부적",
      slot: "accessory",
      price: 220,
      imageResourceId: "cc0-jetrel-gen-amulet-sun",
      iconResourceId: "cc0-jetrel-gen-amulet-sun",
      description: "태양의 기운이 담긴 부적입니다.",
      statBonuses: { attack: 2, defense: 0, mind: 2, agility: 0 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_brooch_rose",
      name: "장미 브로치",
      slot: "accessory",
      price: 200,
      imageResourceId: "cc0-jetrel-gen-brooch-rose",
      iconResourceId: "cc0-jetrel-gen-brooch-rose",
      description: "장미 모양의 우아한 브로치입니다.",
      statBonuses: { attack: 0, defense: 2, mind: 2, agility: 0 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_earring_jade",
      name: "옥 귀걸이",
      slot: "accessory",
      price: 240,
      imageResourceId: "cc0-jetrel-gen-earring-jade",
      iconResourceId: "cc0-jetrel-gen-earring-jade",
      description: "마력을 북돋우는 옥 귀걸이입니다.",
      statBonuses: { attack: 0, defense: 0, mind: 4, agility: 0 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_charm_luck",
      name: "행운 부적",
      slot: "accessory",
      price: 160,
      imageResourceId: "cc0-jetrel-gen-charm-luck",
      iconResourceId: "cc0-jetrel-gen-charm-luck",
      description: "행운을 불러오는 작은 부적입니다.",
      statBonuses: { attack: 0, defense: 0, mind: 1, agility: 3 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_orb_mana",
      name: "마나 구슬",
      slot: "accessory",
      price: 320,
      imageResourceId: "cc0-jetrel-gen-orb-mana",
      iconResourceId: "cc0-jetrel-gen-orb-mana",
      description: "마력을 크게 증폭하는 투명한 구슬입니다.",
      statBonuses: { attack: 0, defense: 0, mind: 6, agility: 0 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_badge_guard",
      name: "경비 배지",
      slot: "accessory",
      price: 140,
      imageResourceId: "cc0-jetrel-gen-badge-guard",
      iconResourceId: "cc0-jetrel-gen-badge-guard",
      description: "방어를 다져주는 경비대 배지입니다.",
      statBonuses: { attack: 0, defense: 3, mind: 0, agility: 0 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_mask_fox",
      name: "여우 가면",
      slot: "accessory",
      price: 200,
      imageResourceId: "cc0-jetrel-gen-mask-fox",
      iconResourceId: "cc0-jetrel-gen-mask-fox",
      description: "날렵함을 북돋우는 여우 가면입니다.",
      statBonuses: { attack: 2, defense: 0, mind: 0, agility: 2 },
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
  ];
}
