import { normalizeEnemyRecord } from "../databaseRecordModel";
import { archetypeActions, BOSS_ELEMENT_SKILLS, SPIRIT_ELEMENT_SKILLS } from "./enemyActionArchetypes";

// 생성된 몬스터 배틀러(manifest.mjs MONSTERS)에 대응하는 적 레코드.
// PNG 가 실제로 존재하는 slug 만 등록한다(없는 리소스는 런타임에 폴백 스프라이트가 뜬다).
// 계열 순서(슬라임→…→드래곤·보스)로 난이도가 완만하게 오르며, 보스급은 HP 가 눈에 띄게 높다.
//
// 스탯 규약 두 가지(Task 5):
//  - `mind` = 그 적의 `attack`. 데미지형 정체성 스킬(속성기·독침)이 전부 `statistic:"mind"`
//    라, mind 가 전원 10 이던 시절에는 공격력이 큰 적에서 마법 위력이 `power + 5` 에 묶여
//    물리 무료기에 영구히 졌다. 근거와 검사는 enemyActionArchetypes.ts 헤더 참고.
//  - `maxMp` = 10, 단 드래곤·보스 구획 10마리만 40. 4MP 속성기를 10회 쓸 예산이다.
//    MP 부족은 점수 계산 **전에** 필터되므로(runtime.ts:1798) turn 조건 버스트도 같이 죽는다.
export function generatedEnemyRecords() {
  return [
      // 슬라임·젤리
      normalizeEnemyRecord({ ...{"id":"enemy_slime_blue","name":"푸른 슬라임","level":1,"monsterResourceId":"generated-enemy-slime-blue","stats":{"maxHp":324,"maxMp":10,"attack":57,"defense":15,"mind":57,"agility":34},"rewards":{"exp":98,"gold":30,"dropRatePercent":15}}, actions: archetypeActions("blob") }),
      normalizeEnemyRecord({ ...{"id":"enemy_slime_red","name":"붉은 슬라임","level":2,"monsterResourceId":"generated-enemy-slime-red","stats":{"maxHp":320,"maxMp":10,"attack":58,"defense":16,"mind":58,"agility":34},"rewards":{"exp":96,"gold":32,"dropRatePercent":15}}, actions: archetypeActions("blob") }),
      normalizeEnemyRecord({ ...{"id":"enemy_slime_green","name":"초록 슬라임","level":2,"monsterResourceId":"generated-enemy-slime-green","stats":{"maxHp":320,"maxMp":10,"attack":58,"defense":16,"mind":58,"agility":34},"rewards":{"exp":96,"gold":32,"dropRatePercent":15}}, actions: archetypeActions("blob") }),
      normalizeEnemyRecord({ ...{"id":"enemy_slime_metal","name":"금속 슬라임","level":3,"monsterResourceId":"generated-enemy-slime-metal","stats":{"maxHp":320,"maxMp":10,"attack":60,"defense":17,"mind":60,"agility":34},"rewards":{"exp":96,"gold":35,"dropRatePercent":15}}, actions: archetypeActions("blob") }),
      normalizeEnemyRecord({ ...{"id":"enemy_slime_king","name":"슬라임 왕","level":3,"monsterResourceId":"generated-enemy-slime-king","stats":{"maxHp":320,"maxMp":10,"attack":60,"defense":17,"mind":60,"agility":34},"rewards":{"exp":96,"gold":35,"dropRatePercent":15}}, actions: archetypeActions("blob") }),
      normalizeEnemyRecord({ ...{"id":"enemy_slime_cube","name":"젤리 큐브","level":4,"monsterResourceId":"generated-enemy-slime-cube","stats":{"maxHp":320,"maxMp":10,"attack":61,"defense":17,"mind":61,"agility":34},"rewards":{"exp":96,"gold":36,"dropRatePercent":15}}, actions: archetypeActions("blob") }),
      normalizeEnemyRecord({ ...{"id":"enemy_ooze_black","name":"검은 점액","level":4,"monsterResourceId":"generated-enemy-ooze-black","stats":{"maxHp":320,"maxMp":10,"attack":61,"defense":17,"mind":61,"agility":34},"rewards":{"exp":96,"gold":36,"dropRatePercent":15}}, actions: archetypeActions("blob") }),
      normalizeEnemyRecord({ ...{"id":"enemy_ooze_acid","name":"산성 점액","level":5,"monsterResourceId":"generated-enemy-ooze-acid","stats":{"maxHp":329,"maxMp":10,"attack":62,"defense":17,"mind":62,"agility":34},"rewards":{"exp":99,"gold":39,"dropRatePercent":15}}, actions: archetypeActions("blob") }),
      // 곤충·절지
      normalizeEnemyRecord({ ...{"id":"enemy_bat_cave","name":"동굴 박쥐","level":6,"monsterResourceId":"generated-enemy-bat-cave","stats":{"maxHp":324,"maxMp":10,"attack":63,"defense":18,"mind":63,"agility":35},"rewards":{"exp":98,"gold":37,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      normalizeEnemyRecord({ ...{"id":"enemy_bat_vampire","name":"흡혈 박쥐","level":6,"monsterResourceId":"generated-enemy-bat-vampire","stats":{"maxHp":324,"maxMp":10,"attack":63,"defense":18,"mind":63,"agility":35},"rewards":{"exp":98,"gold":37,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      normalizeEnemyRecord({ ...{"id":"enemy_bee_giant","name":"거대 벌","level":7,"monsterResourceId":"generated-enemy-bee-giant","stats":{"maxHp":324,"maxMp":10,"attack":64,"defense":19,"mind":64,"agility":35},"rewards":{"exp":98,"gold":40,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      normalizeEnemyRecord({ ...{"id":"enemy_spider_cave","name":"동굴 거미","level":7,"monsterResourceId":"generated-enemy-spider-cave","stats":{"maxHp":324,"maxMp":10,"attack":64,"defense":19,"mind":64,"agility":35},"rewards":{"exp":98,"gold":40,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      normalizeEnemyRecord({ ...{"id":"enemy_spider_widow","name":"과부 거미","level":7,"monsterResourceId":"generated-enemy-spider-widow","stats":{"maxHp":324,"maxMp":10,"attack":64,"defense":19,"mind":64,"agility":35},"rewards":{"exp":98,"gold":41,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      normalizeEnemyRecord({ ...{"id":"enemy_scorpion_sand","name":"모래 전갈","level":8,"monsterResourceId":"generated-enemy-scorpion-sand","stats":{"maxHp":329,"maxMp":10,"attack":66,"defense":19,"mind":66,"agility":35},"rewards":{"exp":99,"gold":42,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      normalizeEnemyRecord({ ...{"id":"enemy_beetle_horn","name":"뿔 딱정벌레","level":8,"monsterResourceId":"generated-enemy-beetle-horn","stats":{"maxHp":329,"maxMp":10,"attack":66,"defense":19,"mind":66,"agility":35},"rewards":{"exp":99,"gold":43,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      normalizeEnemyRecord({ ...{"id":"enemy_mantis_blade","name":"칼날 사마귀","level":9,"monsterResourceId":"generated-enemy-mantis-blade","stats":{"maxHp":324,"maxMp":10,"attack":67,"defense":20,"mind":67,"agility":35},"rewards":{"exp":98,"gold":43,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      normalizeEnemyRecord({ ...{"id":"enemy_centipede_fire","name":"화염 지네","level":9,"monsterResourceId":"generated-enemy-centipede-fire","stats":{"maxHp":324,"maxMp":10,"attack":67,"defense":20,"mind":67,"agility":35},"rewards":{"exp":98,"gold":43,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      normalizeEnemyRecord({ ...{"id":"enemy_moth_dust","name":"가루 나방","level":9,"monsterResourceId":"generated-enemy-moth-dust","stats":{"maxHp":324,"maxMp":10,"attack":67,"defense":20,"mind":67,"agility":35},"rewards":{"exp":98,"gold":43,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      normalizeEnemyRecord({ ...{"id":"enemy_worm_sand","name":"모래 지렁이","level":10,"monsterResourceId":"generated-enemy-worm-sand","stats":{"maxHp":333,"maxMp":10,"attack":68,"defense":20,"mind":68,"agility":35},"rewards":{"exp":100,"gold":47,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      normalizeEnemyRecord({ ...{"id":"enemy_ant_soldier","name":"병정 개미","level":10,"monsterResourceId":"generated-enemy-ant-soldier","stats":{"maxHp":333,"maxMp":10,"attack":68,"defense":20,"mind":68,"agility":35},"rewards":{"exp":100,"gold":47,"dropRatePercent":15}}, actions: archetypeActions("venom") }),
      // 야수
      normalizeEnemyRecord({ ...{"id":"enemy_wolf_grey","name":"회색 늑대","level":11,"monsterResourceId":"generated-enemy-wolf-grey","stats":{"maxHp":333,"maxMp":10,"attack":69,"defense":22,"mind":69,"agility":36},"rewards":{"exp":100,"gold":57,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_wolf_dire","name":"다이어 울프","level":11,"monsterResourceId":"generated-enemy-wolf-dire","stats":{"maxHp":333,"maxMp":10,"attack":69,"defense":22,"mind":69,"agility":36},"rewards":{"exp":100,"gold":57,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_boar_tusk","name":"송곳니 멧돼지","level":12,"monsterResourceId":"generated-enemy-boar-tusk","stats":{"maxHp":342,"maxMp":10,"attack":70,"defense":23,"mind":70,"agility":36},"rewards":{"exp":103,"gold":60,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_bear_brown","name":"갈색 곰","level":12,"monsterResourceId":"generated-enemy-bear-brown","stats":{"maxHp":342,"maxMp":10,"attack":70,"defense":23,"mind":70,"agility":36},"rewards":{"exp":103,"gold":61,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_tiger_saber","name":"검치호","level":12,"monsterResourceId":"generated-enemy-tiger-saber","stats":{"maxHp":342,"maxMp":10,"attack":70,"defense":23,"mind":70,"agility":36},"rewards":{"exp":103,"gold":61,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_rat_giant","name":"거대 쥐","level":13,"monsterResourceId":"generated-enemy-rat-giant","stats":{"maxHp":347,"maxMp":10,"attack":72,"defense":23,"mind":72,"agility":37},"rewards":{"exp":105,"gold":62,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_bird_hawk","name":"매","level":13,"monsterResourceId":"generated-enemy-bird-hawk","stats":{"maxHp":347,"maxMp":10,"attack":72,"defense":23,"mind":72,"agility":37},"rewards":{"exp":105,"gold":62,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_snake_viper","name":"독사","level":13,"monsterResourceId":"generated-enemy-snake-viper","stats":{"maxHp":347,"maxMp":10,"attack":72,"defense":23,"mind":72,"agility":37},"rewards":{"exp":105,"gold":62,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_cat_shadow","name":"그림자 고양이","level":13,"monsterResourceId":"generated-enemy-cat-shadow","stats":{"maxHp":347,"maxMp":10,"attack":72,"defense":23,"mind":72,"agility":37},"rewards":{"exp":105,"gold":63,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_goat_mountain","name":"산양","level":14,"monsterResourceId":"generated-enemy-goat-mountain","stats":{"maxHp":351,"maxMp":10,"attack":73,"defense":24,"mind":73,"agility":38},"rewards":{"exp":106,"gold":65,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_crab_rock","name":"바위 게","level":14,"monsterResourceId":"generated-enemy-crab-rock","stats":{"maxHp":351,"maxMp":10,"attack":73,"defense":24,"mind":73,"agility":38},"rewards":{"exp":106,"gold":65,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_hound_hell","name":"지옥 사냥개","level":14,"monsterResourceId":"generated-enemy-hound-hell","stats":{"maxHp":351,"maxMp":10,"attack":73,"defense":24,"mind":73,"agility":38},"rewards":{"exp":106,"gold":65,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_ape_stone","name":"석상 유인원","level":15,"monsterResourceId":"generated-enemy-ape-stone","stats":{"maxHp":356,"maxMp":10,"attack":74,"defense":25,"mind":74,"agility":38},"rewards":{"exp":107,"gold":69,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      normalizeEnemyRecord({ ...{"id":"enemy_deer_forest","name":"숲 사슴","level":15,"monsterResourceId":"generated-enemy-deer-forest","stats":{"maxHp":356,"maxMp":10,"attack":74,"defense":25,"mind":74,"agility":38},"rewards":{"exp":107,"gold":70,"dropRatePercent":15}}, actions: archetypeActions("brute") }),
      // 언데드
      normalizeEnemyRecord({ ...{"id":"enemy_skeleton_bone","name":"해골","level":16,"monsterResourceId":"generated-enemy-skeleton-bone","stats":{"maxHp":360,"maxMp":10,"attack":75,"defense":27,"mind":75,"agility":38},"rewards":{"exp":108,"gold":68,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      normalizeEnemyRecord({ ...{"id":"enemy_skeleton_archer","name":"해골 궁수","level":16,"monsterResourceId":"generated-enemy-skeleton-archer","stats":{"maxHp":360,"maxMp":10,"attack":75,"defense":27,"mind":75,"agility":38},"rewards":{"exp":108,"gold":69,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      normalizeEnemyRecord({ ...{"id":"enemy_skeleton_knight","name":"해골 기사","level":17,"monsterResourceId":"generated-enemy-skeleton-knight","stats":{"maxHp":365,"maxMp":10,"attack":76,"defense":27,"mind":76,"agility":39},"rewards":{"exp":110,"gold":70,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      normalizeEnemyRecord({ ...{"id":"enemy_zombie_rot","name":"썩은 좀비","level":17,"monsterResourceId":"generated-enemy-zombie-rot","stats":{"maxHp":365,"maxMp":10,"attack":76,"defense":27,"mind":76,"agility":39},"rewards":{"exp":110,"gold":70,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      normalizeEnemyRecord({ ...{"id":"enemy_ghoul_grave","name":"무덤 구울","level":17,"monsterResourceId":"generated-enemy-ghoul-grave","stats":{"maxHp":365,"maxMp":10,"attack":76,"defense":27,"mind":76,"agility":39},"rewards":{"exp":110,"gold":70,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      normalizeEnemyRecord({ ...{"id":"enemy_ghost_pale","name":"창백한 유령","level":18,"monsterResourceId":"generated-enemy-ghost-pale","stats":{"maxHp":369,"maxMp":10,"attack":78,"defense":28,"mind":78,"agility":40},"rewards":{"exp":111,"gold":72,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      normalizeEnemyRecord({ ...{"id":"enemy_wraith_dark","name":"어둠 망령","level":18,"monsterResourceId":"generated-enemy-wraith-dark","stats":{"maxHp":369,"maxMp":10,"attack":78,"defense":28,"mind":78,"agility":40},"rewards":{"exp":111,"gold":73,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      normalizeEnemyRecord({ ...{"id":"enemy_lich_frost","name":"서릿 리치","level":19,"monsterResourceId":"generated-enemy-lich-frost","stats":{"maxHp":383,"maxMp":10,"attack":79,"defense":29,"mind":79,"agility":41},"rewards":{"exp":115,"gold":77,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      normalizeEnemyRecord({ ...{"id":"enemy_mummy_bandage","name":"미라","level":19,"monsterResourceId":"generated-enemy-mummy-bandage","stats":{"maxHp":383,"maxMp":10,"attack":79,"defense":29,"mind":79,"agility":41},"rewards":{"exp":115,"gold":77,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      normalizeEnemyRecord({ ...{"id":"enemy_banshee_wail","name":"밴시","level":19,"monsterResourceId":"generated-enemy-banshee-wail","stats":{"maxHp":383,"maxMp":10,"attack":79,"defense":29,"mind":79,"agility":41},"rewards":{"exp":115,"gold":78,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      normalizeEnemyRecord({ ...{"id":"enemy_revenant_vengeful","name":"복수의 사령","level":20,"monsterResourceId":"generated-enemy-revenant-vengeful","stats":{"maxHp":383,"maxMp":10,"attack":80,"defense":30,"mind":80,"agility":41},"rewards":{"exp":115,"gold":80,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      normalizeEnemyRecord({ ...{"id":"enemy_bonepile_crawler","name":"뼈 무더기","level":20,"monsterResourceId":"generated-enemy-bonepile-crawler","stats":{"maxHp":383,"maxMp":10,"attack":80,"defense":30,"mind":80,"agility":41},"rewards":{"exp":115,"gold":80,"dropRatePercent":15}}, actions: archetypeActions("curse") }),
      // 정령·원소
      normalizeEnemyRecord({ ...{"id":"enemy_spirit_fire","name":"불의 정령","level":21,"monsterResourceId":"generated-enemy-spirit-fire","stats":{"maxHp":405,"maxMp":10,"attack":81,"defense":26,"mind":81,"agility":43},"rewards":{"exp":122,"gold":79,"dropRatePercent":15}}, actions: archetypeActions("caster", SPIRIT_ELEMENT_SKILLS.enemy_spirit_fire) }),
      normalizeEnemyRecord({ ...{"id":"enemy_spirit_water","name":"물의 정령","level":21,"monsterResourceId":"generated-enemy-spirit-water","stats":{"maxHp":405,"maxMp":10,"attack":81,"defense":26,"mind":81,"agility":43},"rewards":{"exp":122,"gold":80,"dropRatePercent":15}}, actions: archetypeActions("caster", SPIRIT_ELEMENT_SKILLS.enemy_spirit_water) }),
      normalizeEnemyRecord({ ...{"id":"enemy_spirit_earth","name":"땅의 정령","level":22,"monsterResourceId":"generated-enemy-spirit-earth","stats":{"maxHp":414,"maxMp":10,"attack":82,"defense":26,"mind":82,"agility":44},"rewards":{"exp":125,"gold":80,"dropRatePercent":15}}, actions: archetypeActions("caster", SPIRIT_ELEMENT_SKILLS.enemy_spirit_earth) }),
      normalizeEnemyRecord({ ...{"id":"enemy_spirit_wind","name":"바람의 정령","level":22,"monsterResourceId":"generated-enemy-spirit-wind","stats":{"maxHp":414,"maxMp":10,"attack":82,"defense":26,"mind":82,"agility":44},"rewards":{"exp":125,"gold":81,"dropRatePercent":15}}, actions: archetypeActions("caster", SPIRIT_ELEMENT_SKILLS.enemy_spirit_wind) }),
      normalizeEnemyRecord({ ...{"id":"enemy_spirit_light","name":"빛의 정령","level":23,"monsterResourceId":"generated-enemy-spirit-light","stats":{"maxHp":428,"maxMp":10,"attack":84,"defense":27,"mind":84,"agility":44},"rewards":{"exp":129,"gold":85,"dropRatePercent":15}}, actions: archetypeActions("caster", SPIRIT_ELEMENT_SKILLS.enemy_spirit_light) }),
      normalizeEnemyRecord({ ...{"id":"enemy_spirit_dark","name":"어둠의 정령","level":23,"monsterResourceId":"generated-enemy-spirit-dark","stats":{"maxHp":428,"maxMp":10,"attack":84,"defense":27,"mind":84,"agility":44},"rewards":{"exp":129,"gold":85,"dropRatePercent":15}}, actions: archetypeActions("caster", SPIRIT_ELEMENT_SKILLS.enemy_spirit_dark) }),
      normalizeEnemyRecord({ ...{"id":"enemy_wisp_blue","name":"푸른 도깨비불","level":24,"monsterResourceId":"generated-enemy-wisp-blue","stats":{"maxHp":441,"maxMp":10,"attack":85,"defense":27,"mind":85,"agility":45},"rewards":{"exp":133,"gold":89,"dropRatePercent":15}}, actions: archetypeActions("caster", SPIRIT_ELEMENT_SKILLS.enemy_wisp_blue) }),
      normalizeEnemyRecord({ ...{"id":"enemy_sylph_air","name":"실프","level":24,"monsterResourceId":"generated-enemy-sylph-air","stats":{"maxHp":441,"maxMp":10,"attack":85,"defense":27,"mind":85,"agility":45},"rewards":{"exp":133,"gold":90,"dropRatePercent":15}}, actions: archetypeActions("caster", SPIRIT_ELEMENT_SKILLS.enemy_sylph_air) }),
      normalizeEnemyRecord({ ...{"id":"enemy_undine_sea","name":"운디네","level":25,"monsterResourceId":"generated-enemy-undine-sea","stats":{"maxHp":441,"maxMp":10,"attack":86,"defense":28,"mind":86,"agility":47},"rewards":{"exp":133,"gold":92,"dropRatePercent":15}}, actions: archetypeActions("caster", SPIRIT_ELEMENT_SKILLS.enemy_undine_sea) }),
      normalizeEnemyRecord({ ...{"id":"enemy_salamander_flame","name":"샐러맨더","level":25,"monsterResourceId":"generated-enemy-salamander-flame","stats":{"maxHp":441,"maxMp":10,"attack":86,"defense":28,"mind":86,"agility":47},"rewards":{"exp":133,"gold":93,"dropRatePercent":15}}, actions: archetypeActions("caster", SPIRIT_ELEMENT_SKILLS.enemy_salamander_flame) }),
      // 골렘·구조물
      normalizeEnemyRecord({ ...{"id":"enemy_golem_stone","name":"돌 골렘","level":26,"monsterResourceId":"generated-enemy-golem-stone","stats":{"maxHp":428,"maxMp":10,"attack":87,"defense":40,"mind":87,"agility":47},"rewards":{"exp":129,"gold":107,"dropRatePercent":15}}, actions: archetypeActions("bulwark") }),
      normalizeEnemyRecord({ ...{"id":"enemy_golem_iron","name":"철 골렘","level":26,"monsterResourceId":"generated-enemy-golem-iron","stats":{"maxHp":428,"maxMp":10,"attack":87,"defense":40,"mind":87,"agility":47},"rewards":{"exp":129,"gold":108,"dropRatePercent":15}}, actions: archetypeActions("bulwark") }),
      normalizeEnemyRecord({ ...{"id":"enemy_golem_clay","name":"점토 골렘","level":27,"monsterResourceId":"generated-enemy-golem-clay","stats":{"maxHp":441,"maxMp":10,"attack":88,"defense":41,"mind":88,"agility":48},"rewards":{"exp":133,"gold":113,"dropRatePercent":15}}, actions: archetypeActions("bulwark") }),
      normalizeEnemyRecord({ ...{"id":"enemy_golem_crystal","name":"수정 골렘","level":27,"monsterResourceId":"generated-enemy-golem-crystal","stats":{"maxHp":441,"maxMp":10,"attack":88,"defense":41,"mind":88,"agility":48},"rewards":{"exp":133,"gold":114,"dropRatePercent":15}}, actions: archetypeActions("bulwark") }),
      normalizeEnemyRecord({ ...{"id":"enemy_armor_living","name":"살아있는 갑옷","level":28,"monsterResourceId":"generated-enemy-armor-living","stats":{"maxHp":450,"maxMp":10,"attack":90,"defense":42,"mind":90,"agility":50},"rewards":{"exp":135,"gold":117,"dropRatePercent":15}}, actions: archetypeActions("bulwark") }),
      normalizeEnemyRecord({ ...{"id":"enemy_sword_flying","name":"부유하는 검","level":28,"monsterResourceId":"generated-enemy-sword-flying","stats":{"maxHp":450,"maxMp":10,"attack":90,"defense":42,"mind":90,"agility":50},"rewards":{"exp":135,"gold":117,"dropRatePercent":15}}, actions: archetypeActions("bulwark") }),
      normalizeEnemyRecord({ ...{"id":"enemy_mimic_chest","name":"미믹 상자","level":29,"monsterResourceId":"generated-enemy-mimic-chest","stats":{"maxHp":473,"maxMp":10,"attack":91,"defense":43,"mind":91,"agility":51},"rewards":{"exp":142,"gold":123,"dropRatePercent":15}}, actions: archetypeActions("bulwark") }),
      normalizeEnemyRecord({ ...{"id":"enemy_scarecrow_field","name":"허수아비","level":29,"monsterResourceId":"generated-enemy-scarecrow-field","stats":{"maxHp":473,"maxMp":10,"attack":91,"defense":43,"mind":91,"agility":51},"rewards":{"exp":142,"gold":123,"dropRatePercent":15}}, actions: archetypeActions("bulwark") }),
      normalizeEnemyRecord({ ...{"id":"enemy_puppet_string","name":"실 인형","level":30,"monsterResourceId":"generated-enemy-puppet-string","stats":{"maxHp":486,"maxMp":10,"attack":92,"defense":43,"mind":92,"agility":52},"rewards":{"exp":146,"gold":127,"dropRatePercent":15}}, actions: archetypeActions("bulwark") }),
      normalizeEnemyRecord({ ...{"id":"enemy_totem_cursed","name":"저주받은 토템","level":30,"monsterResourceId":"generated-enemy-totem-cursed","stats":{"maxHp":486,"maxMp":10,"attack":92,"defense":43,"mind":92,"agility":52},"rewards":{"exp":146,"gold":127,"dropRatePercent":15}}, actions: archetypeActions("bulwark") }),
      // 인간형
      normalizeEnemyRecord({ ...{"id":"enemy_goblin_scout","name":"고블린 정찰병","level":31,"monsterResourceId":"generated-enemy-goblin-scout","stats":{"maxHp":513,"maxMp":10,"attack":93,"defense":37,"mind":93,"agility":53},"rewards":{"exp":154,"gold":120,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_goblin_brute","name":"고블린 폭력배","level":31,"monsterResourceId":"generated-enemy-goblin-brute","stats":{"maxHp":513,"maxMp":10,"attack":93,"defense":37,"mind":93,"agility":53},"rewards":{"exp":154,"gold":120,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_orc_warrior","name":"오크 전사","level":32,"monsterResourceId":"generated-enemy-orc-warrior","stats":{"maxHp":527,"maxMp":10,"attack":94,"defense":38,"mind":94,"agility":55},"rewards":{"exp":159,"gold":123,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_orc_shaman","name":"오크 주술사","level":32,"monsterResourceId":"generated-enemy-orc-shaman","stats":{"maxHp":527,"maxMp":10,"attack":94,"defense":38,"mind":94,"agility":55},"rewards":{"exp":159,"gold":123,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_kobold_digger","name":"코볼트 광부","level":32,"monsterResourceId":"generated-enemy-kobold-digger","stats":{"maxHp":527,"maxMp":10,"attack":94,"defense":38,"mind":94,"agility":55},"rewards":{"exp":159,"gold":124,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_bandit_mask","name":"복면 산적","level":32,"monsterResourceId":"generated-enemy-bandit-mask","stats":{"maxHp":527,"maxMp":10,"attack":94,"defense":38,"mind":94,"agility":55},"rewards":{"exp":159,"gold":124,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_mage_rogue","name":"이단 마법사","level":33,"monsterResourceId":"generated-enemy-mage-rogue","stats":{"maxHp":540,"maxMp":10,"attack":96,"defense":38,"mind":96,"agility":56},"rewards":{"exp":162,"gold":129,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_knight_fallen","name":"타락한 기사","level":33,"monsterResourceId":"generated-enemy-knight-fallen","stats":{"maxHp":540,"maxMp":10,"attack":96,"defense":38,"mind":96,"agility":56},"rewards":{"exp":162,"gold":129,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_lizardman_spear","name":"리자드맨","level":33,"monsterResourceId":"generated-enemy-lizardman-spear","stats":{"maxHp":540,"maxMp":10,"attack":96,"defense":38,"mind":96,"agility":56},"rewards":{"exp":162,"gold":130,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_harpy_cliff","name":"하피","level":34,"monsterResourceId":"generated-enemy-harpy-cliff","stats":{"maxHp":563,"maxMp":10,"attack":97,"defense":39,"mind":97,"agility":57},"rewards":{"exp":169,"gold":134,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_minotaur_maze","name":"미노타우로스","level":34,"monsterResourceId":"generated-enemy-minotaur-maze","stats":{"maxHp":563,"maxMp":10,"attack":97,"defense":39,"mind":97,"agility":57},"rewards":{"exp":169,"gold":135,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_centaur_plains","name":"켄타우로스","level":34,"monsterResourceId":"generated-enemy-centaur-plains","stats":{"maxHp":563,"maxMp":10,"attack":97,"defense":39,"mind":97,"agility":57},"rewards":{"exp":169,"gold":135,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_troll_cave","name":"동굴 트롤","level":34,"monsterResourceId":"generated-enemy-troll-cave","stats":{"maxHp":563,"maxMp":10,"attack":97,"defense":39,"mind":97,"agility":57},"rewards":{"exp":169,"gold":136,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_ogre_club","name":"오거","level":35,"monsterResourceId":"generated-enemy-ogre-club","stats":{"maxHp":576,"maxMp":10,"attack":98,"defense":39,"mind":98,"agility":59},"rewards":{"exp":173,"gold":138,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      normalizeEnemyRecord({ ...{"id":"enemy_imp_mischief","name":"임프","level":35,"monsterResourceId":"generated-enemy-imp-mischief","stats":{"maxHp":576,"maxMp":10,"attack":98,"defense":39,"mind":98,"agility":59},"rewards":{"exp":173,"gold":139,"dropRatePercent":15}}, actions: archetypeActions("tactician") }),
      // 수생·비행
      normalizeEnemyRecord({ ...{"id":"enemy_fish_piranha","name":"피라냐","level":36,"monsterResourceId":"generated-enemy-fish-piranha","stats":{"maxHp":599,"maxMp":10,"attack":99,"defense":36,"mind":99,"agility":60},"rewards":{"exp":180,"gold":137,"dropRatePercent":15}}, actions: archetypeActions("flyer") }),
      normalizeEnemyRecord({ ...{"id":"enemy_squid_deep","name":"심해 오징어","level":37,"monsterResourceId":"generated-enemy-squid-deep","stats":{"maxHp":621,"maxMp":10,"attack":100,"defense":37,"mind":100,"agility":62},"rewards":{"exp":187,"gold":142,"dropRatePercent":15}}, actions: archetypeActions("flyer") }),
      normalizeEnemyRecord({ ...{"id":"enemy_shark_land","name":"육상 상어","level":37,"monsterResourceId":"generated-enemy-shark-land","stats":{"maxHp":621,"maxMp":10,"attack":100,"defense":37,"mind":100,"agility":62},"rewards":{"exp":187,"gold":143,"dropRatePercent":15}}, actions: archetypeActions("flyer") }),
      normalizeEnemyRecord({ ...{"id":"enemy_eel_electric","name":"전기 뱀장어","level":38,"monsterResourceId":"generated-enemy-eel-electric","stats":{"maxHp":630,"maxMp":10,"attack":102,"defense":38,"mind":102,"agility":63},"rewards":{"exp":189,"gold":146,"dropRatePercent":15}}, actions: archetypeActions("flyer") }),
      normalizeEnemyRecord({ ...{"id":"enemy_griffin_sky","name":"그리핀","level":38,"monsterResourceId":"generated-enemy-griffin-sky","stats":{"maxHp":630,"maxMp":10,"attack":102,"defense":38,"mind":102,"agility":63},"rewards":{"exp":189,"gold":147,"dropRatePercent":15}}, actions: archetypeActions("flyer") }),
      normalizeEnemyRecord({ ...{"id":"enemy_wyvern_cliff","name":"와이번","level":39,"monsterResourceId":"generated-enemy-wyvern-cliff","stats":{"maxHp":648,"maxMp":10,"attack":103,"defense":38,"mind":103,"agility":65},"rewards":{"exp":195,"gold":150,"dropRatePercent":15}}, actions: archetypeActions("flyer") }),
      normalizeEnemyRecord({ ...{"id":"enemy_roc_giant","name":"거대 로크","level":39,"monsterResourceId":"generated-enemy-roc-giant","stats":{"maxHp":648,"maxMp":10,"attack":103,"defense":38,"mind":103,"agility":65},"rewards":{"exp":195,"gold":152,"dropRatePercent":15}}, actions: archetypeActions("flyer") }),
      normalizeEnemyRecord({ ...{"id":"enemy_gargoyle_stone","name":"가고일","level":40,"monsterResourceId":"generated-enemy-gargoyle-stone","stats":{"maxHp":1192,"maxMp":10,"attack":192,"defense":39,"mind":192,"agility":67},"rewards":{"exp":358,"gold":155,"dropRatePercent":15}}, actions: archetypeActions("flyer") }),
      normalizeEnemyRecord({ ...{"id":"enemy_phoenix_rebirth","name":"불사조","level":40,"monsterResourceId":"generated-enemy-phoenix-rebirth","stats":{"maxHp":1192,"maxMp":10,"attack":192,"defense":39,"mind":192,"agility":67},"rewards":{"exp":358,"gold":155,"dropRatePercent":15}}, actions: archetypeActions("flyer") }),
      // 드래곤·보스
      normalizeEnemyRecord({ ...{"id":"enemy_dragon_whelp","name":"새끼 용","level":36,"monsterResourceId":"generated-enemy-dragon-whelp","stats":{"maxHp":1048,"maxMp":40,"attack":171,"defense":40,"mind":171,"agility":60},"rewards":{"exp":315,"gold":206,"dropRatePercent":15}}, actions: archetypeActions("boss", BOSS_ELEMENT_SKILLS.enemy_dragon_whelp) }),
      normalizeEnemyRecord({ ...{"id":"enemy_dragon_red","name":"붉은 용","level":37,"monsterResourceId":"generated-enemy-dragon-red","stats":{"maxHp":1088,"maxMp":40,"attack":176,"defense":41,"mind":176,"agility":62},"rewards":{"exp":327,"gold":212,"dropRatePercent":15}}, actions: archetypeActions("boss", BOSS_ELEMENT_SKILLS.enemy_dragon_red) }),
      normalizeEnemyRecord({ ...{"id":"enemy_dragon_blue","name":"청룡","level":38,"monsterResourceId":"generated-enemy-dragon-blue","stats":{"maxHp":1104,"maxMp":40,"attack":181,"defense":42,"mind":181,"agility":63},"rewards":{"exp":332,"gold":215,"dropRatePercent":15}}, actions: archetypeActions("boss", BOSS_ELEMENT_SKILLS.enemy_dragon_blue) }),
      normalizeEnemyRecord({ ...{"id":"enemy_dragon_bone","name":"본 드래곤","level":39,"monsterResourceId":"generated-enemy-dragon-bone","stats":{"maxHp":1136,"maxMp":40,"attack":186,"defense":42,"mind":186,"agility":65},"rewards":{"exp":341,"gold":218,"dropRatePercent":15}}, actions: archetypeActions("boss", BOSS_ELEMENT_SKILLS.enemy_dragon_bone) }),
      normalizeEnemyRecord({ ...{"id":"enemy_hydra_three","name":"히드라","level":40,"monsterResourceId":"generated-enemy-hydra-three","stats":{"maxHp":1176,"maxMp":40,"attack":192,"defense":43,"mind":192,"agility":67},"rewards":{"exp":353,"gold":222,"dropRatePercent":15}}, actions: archetypeActions("boss", BOSS_ELEMENT_SKILLS.enemy_hydra_three) }),
      normalizeEnemyRecord({ ...{"id":"enemy_behemoth_horn","name":"베히모스","level":41,"monsterResourceId":"generated-enemy-behemoth-horn","stats":{"maxHp":1200,"maxMp":40,"attack":197,"defense":44,"mind":197,"agility":68},"rewards":{"exp":360,"gold":225,"dropRatePercent":15}}, actions: archetypeActions("boss", BOSS_ELEMENT_SKILLS.enemy_behemoth_horn) }),
      normalizeEnemyRecord({ ...{"id":"enemy_demon_lord","name":"마왕","level":42,"monsterResourceId":"generated-enemy-demon-lord","stats":{"maxHp":1248,"maxMp":40,"attack":202,"defense":44,"mind":202,"agility":70},"rewards":{"exp":375,"gold":231,"dropRatePercent":15}}, actions: archetypeActions("boss", BOSS_ELEMENT_SKILLS.enemy_demon_lord) }),
      normalizeEnemyRecord({ ...{"id":"enemy_angel_fallen","name":"타락 천사","level":43,"monsterResourceId":"generated-enemy-angel-fallen","stats":{"maxHp":1288,"maxMp":40,"attack":208,"defense":45,"mind":208,"agility":72},"rewards":{"exp":387,"gold":237,"dropRatePercent":15}}, actions: archetypeActions("boss", BOSS_ELEMENT_SKILLS.enemy_angel_fallen) }),
      normalizeEnemyRecord({ ...{"id":"enemy_eye_floating","name":"부유하는 눈","level":44,"monsterResourceId":"generated-enemy-eye-floating","stats":{"maxHp":1312,"maxMp":40,"attack":214,"defense":46,"mind":214,"agility":74},"rewards":{"exp":394,"gold":234,"dropRatePercent":15}}, actions: archetypeActions("boss", BOSS_ELEMENT_SKILLS.enemy_eye_floating) }),
      normalizeEnemyRecord({ ...{"id":"enemy_plant_carnivore","name":"식충 식물","level":45,"monsterResourceId":"generated-enemy-plant-carnivore","stats":{"maxHp":1360,"maxMp":40,"attack":220,"defense":46,"mind":220,"agility":76},"rewards":{"exp":408,"gold":240,"dropRatePercent":15}}, actions: archetypeActions("boss", BOSS_ELEMENT_SKILLS.enemy_plant_carnivore) }),
  ];
}
