import type { EquipmentRecord, ItemRecord } from "../types";
import { normalizeEquipmentRecord, normalizeItemRecord } from "../databaseRecordModel";
import { DEFAULT_ACTOR_ID, DEFAULT_CLASS_ID, DEFAULT_STATE_ID } from "./constants";
import {
  ACTOR_CLERIC_ID,
  ACTOR_GUARDIAN_ID,
  ACTOR_MAGE_ID,
  ACTOR_RANGER_ID,
  ACTOR_SCOUT_ID,
  ALL_ACTOR_IDS,
  ALL_CLASS_IDS,
  CLASS_CLERIC_ID,
  CLASS_GUARDIAN_ID,
  CLASS_MAGE_ID,
  CLASS_RANGER_ID,
  CLASS_SCOUT_ID,
} from "./defaultDatabaseRecordIds";

// scripts/asset-gen/manifest.mjs 의 생성 아이콘 100종에 대응하는 DB 레코드.
// 아이콘 id 규약: cc0-jetrel-<slug> / 레코드 id 규약: item_<slug 밑줄> · equip_<slug 밑줄>.
//
// 밸런스 기준선(기존 곡선):
//   회복약 item_potion HP 50 / 50G, 상급 회복약 HP 150 / 180G, 마력약 MP 30 / 120G, 엘릭서 600G.
//   무기 equip_sword 청동 atk8/100 · 철 atk14/180 · 강철 atk20/260.
//   방어구 참나무 방패 def5/80, 가죽 갑옷 def6/140, 견습 로브 def3+mind4/130.
// 이 범위에서 등급별로 스케일링한다. 재료·열쇠는 사용 효과 없는 보관용.

// 물리 전사계(검·도끼·창·철퇴·망치·낫·총) 착용 권한.
const WARRIOR_ACTORS = [DEFAULT_ACTOR_ID, ACTOR_GUARDIAN_ID];
const WARRIOR_CLASSES = [DEFAULT_CLASS_ID, CLASS_GUARDIAN_ID];
// 민첩 계열(단검·활·채찍·발톱·부메랑) 착용 권한.
const AGILE_ACTORS = [DEFAULT_ACTOR_ID, ACTOR_SCOUT_ID, ACTOR_RANGER_ID];
const AGILE_CLASSES = [DEFAULT_CLASS_ID, CLASS_SCOUT_ID, CLASS_RANGER_ID];
// 마법 계열(지팡이·마법봉·로브) 착용 권한.
const CASTER_ACTORS = [ACTOR_MAGE_ID, ACTOR_CLERIC_ID];
const CASTER_CLASSES = [CLASS_MAGE_ID, CLASS_CLERIC_ID];
// 방패 착용 권한.
const SHIELD_ACTORS = [DEFAULT_ACTOR_ID, ACTOR_GUARDIAN_ID, ACTOR_CLERIC_ID];
const SHIELD_CLASSES = [DEFAULT_CLASS_ID, CLASS_GUARDIAN_ID, CLASS_CLERIC_ID];
// 물리 갑옷 착용 권한.
const BODY_ACTORS = [DEFAULT_ACTOR_ID, ACTOR_GUARDIAN_ID, ACTOR_SCOUT_ID, ACTOR_RANGER_ID];
const BODY_CLASSES = [DEFAULT_CLASS_ID, CLASS_GUARDIAN_ID, CLASS_SCOUT_ID, CLASS_RANGER_ID];

export function generatedItemRecords(): ItemRecord[] {
  return [
    // ── 회복 소비품 ──
    normalizeItemRecord({
      id: "item_gen_potion_small",
      name: "작은 물약",
      type: "medicine",
      scope: "ally",
      price: 30,
      description: "아군 하나의 HP를 30 회복하는 작은 물약입니다.",
      imageResourceId: "cc0-jetrel-gen-potion-small",
      iconResourceId: "cc0-jetrel-gen-potion-small",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      hpRecovery: { flat: 30, percentMax: 0 },
      skillId: "skill_item_potion",
    }),
    normalizeItemRecord({
      id: "item_gen_potion_large",
      name: "큰 물약",
      type: "medicine",
      scope: "ally",
      price: 100,
      description: "아군 하나의 HP를 100 회복하는 큰 물약입니다.",
      imageResourceId: "cc0-jetrel-gen-potion-large",
      iconResourceId: "cc0-jetrel-gen-potion-large",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      hpRecovery: { flat: 100, percentMax: 0 },
      skillId: "skill_item_hi_potion",
    }),
    normalizeItemRecord({
      id: "item_gen_ether_vial",
      name: "에테르 병",
      type: "medicine",
      scope: "ally",
      price: 90,
      description: "아군 하나의 MP를 20 회복합니다.",
      imageResourceId: "cc0-jetrel-gen-ether-vial",
      iconResourceId: "cc0-jetrel-gen-ether-vial",
      animationId: "anim_magic",
      occasion: "always",
      consumable: true,
      mpRecovery: { flat: 20, percentMax: 0 },
      skillId: "skill_item_ether",
    }),
    normalizeItemRecord({
      id: "item_gen_ether_grand",
      name: "고급 에테르",
      type: "medicine",
      scope: "ally",
      price: 200,
      description: "아군 하나의 MP를 60 회복하는 고급 에테르입니다.",
      imageResourceId: "cc0-jetrel-gen-ether-grand",
      iconResourceId: "cc0-jetrel-gen-ether-grand",
      animationId: "anim_magic",
      occasion: "always",
      consumable: true,
      mpRecovery: { flat: 60, percentMax: 0 },
      skillId: "skill_item_ether",
    }),
    normalizeItemRecord({
      id: "item_gen_elixir_gold",
      name: "황금 엘릭서",
      type: "medicine",
      scope: "ally",
      price: 650,
      description: "아군 하나의 HP와 MP를 모두 완전히 회복하는 귀한 약입니다.",
      imageResourceId: "cc0-jetrel-gen-elixir-gold",
      iconResourceId: "cc0-jetrel-gen-elixir-gold",
      animationId: "anim_magic",
      occasion: "always",
      consumable: true,
      hpRecovery: { flat: 0, percentMax: 100 },
      mpRecovery: { flat: 0, percentMax: 100 },
      skillId: "skill_item_elixir",
    }),
    normalizeItemRecord({
      id: "item_gen_panacea_jar",
      name: "도자기 만능약",
      type: "medicine",
      scope: "ally",
      price: 220,
      description: "도자기 병에 담긴 약으로 독과 수면 상태를 한 번에 치료합니다.",
      imageResourceId: "cc0-jetrel-gen-panacea-jar",
      iconResourceId: "cc0-jetrel-gen-panacea-jar",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      healStateIds: [DEFAULT_STATE_ID, "state_sleep"],
      stateEffects: [{ stateId: DEFAULT_STATE_ID, chance: 100, operation: "remove" }, { stateId: "state_sleep", chance: 100, operation: "remove" }],
      skillId: "skill_item_panacea",
    }),
    normalizeItemRecord({
      id: "item_gen_antidote_leaf",
      name: "해독 잎",
      type: "medicine",
      scope: "ally",
      price: 25,
      description: "독 상태를 해제하는 약초 잎입니다.",
      imageResourceId: "cc0-jetrel-gen-antidote-leaf",
      iconResourceId: "cc0-jetrel-gen-antidote-leaf",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      healStateIds: [DEFAULT_STATE_ID],
      stateEffects: [{ stateId: DEFAULT_STATE_ID, chance: 100, operation: "remove" }],
      skillId: "skill_item_antidote",
    }),
    normalizeItemRecord({
      id: "item_gen_eyedrops",
      name: "눈약",
      type: "medicine",
      scope: "ally",
      price: 35,
      description: "수면에 빠진 아군을 깨우는 눈약입니다.",
      imageResourceId: "cc0-jetrel-gen-eyedrops",
      iconResourceId: "cc0-jetrel-gen-eyedrops",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      healStateIds: ["state_sleep"],
      stateEffects: [{ stateId: "state_sleep", chance: 100, operation: "remove" }],
      skillId: "skill_item_wake",
    }),
    normalizeItemRecord({
      id: "item_gen_echo_bell",
      name: "메아리 종",
      type: "medicine",
      scope: "ally",
      price: 45,
      description: "맑은 종소리로 수면에 빠진 아군을 깨웁니다.",
      imageResourceId: "cc0-jetrel-gen-echo-bell",
      iconResourceId: "cc0-jetrel-gen-echo-bell",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      healStateIds: ["state_sleep"],
      stateEffects: [{ stateId: "state_sleep", chance: 100, operation: "remove" }],
      skillId: "skill_item_wake",
    }),
    normalizeItemRecord({
      id: "item_gen_revive_feather",
      name: "부활 깃털",
      type: "medicine",
      scope: "ally",
      price: 400,
      description: "쓰러진 아군 하나를 HP 절반으로 되살리는 깃털입니다.",
      imageResourceId: "cc0-jetrel-gen-revive-feather",
      iconResourceId: "cc0-jetrel-gen-revive-feather",
      animationId: "anim_heal",
      occasion: "field",
      occasionField: true,
      occasionBattle: false,
      consumable: true,
      onlyEffectiveOnDeadActors: true,
      hpRecovery: { flat: 0, percentMax: 50 },
    }),
    normalizeItemRecord({
      id: "item_gen_phoenix_ash",
      name: "불사조 재",
      type: "medicine",
      scope: "ally",
      price: 800,
      description: "쓰러진 아군 하나를 HP 가득 채워 되살리는 귀한 재입니다.",
      imageResourceId: "cc0-jetrel-gen-phoenix-ash",
      iconResourceId: "cc0-jetrel-gen-phoenix-ash",
      animationId: "anim_heal",
      occasion: "field",
      occasionField: true,
      occasionBattle: false,
      consumable: true,
      onlyEffectiveOnDeadActors: true,
      hpRecovery: { flat: 0, percentMax: 100 },
    }),
    normalizeItemRecord({
      id: "item_gen_bandage_roll",
      name: "붕대",
      type: "medicine",
      scope: "ally",
      price: 20,
      description: "아군 하나의 HP를 20 회복하는 응급 붕대입니다.",
      imageResourceId: "cc0-jetrel-gen-bandage-roll",
      iconResourceId: "cc0-jetrel-gen-bandage-roll",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      hpRecovery: { flat: 20, percentMax: 0 },
      skillId: "skill_item_potion",
    }),
    normalizeItemRecord({
      id: "item_gen_herb_bundle",
      name: "약초 다발",
      type: "medicine",
      scope: "ally",
      price: 40,
      description: "아군 하나의 HP를 40 회복하는 약초 다발입니다.",
      imageResourceId: "cc0-jetrel-gen-herb-bundle",
      iconResourceId: "cc0-jetrel-gen-herb-bundle",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      hpRecovery: { flat: 40, percentMax: 0 },
      skillId: "skill_item_potion",
    }),
    normalizeItemRecord({
      id: "item_gen_honey_jar",
      name: "꿀단지",
      type: "medicine",
      scope: "ally",
      price: 80,
      description: "아군 하나의 HP를 60, MP를 10 회복하는 달콤한 꿀입니다.",
      imageResourceId: "cc0-jetrel-gen-honey-jar",
      iconResourceId: "cc0-jetrel-gen-honey-jar",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      hpRecovery: { flat: 60, percentMax: 0 },
      mpRecovery: { flat: 10, percentMax: 0 },
      skillId: "skill_item_potion",
    }),
    normalizeItemRecord({
      id: "item_gen_milk_bottle",
      name: "우유병",
      type: "medicine",
      scope: "ally",
      price: 45,
      description: "아군 하나의 HP를 30, MP를 5 회복하는 신선한 우유입니다.",
      imageResourceId: "cc0-jetrel-gen-milk-bottle",
      iconResourceId: "cc0-jetrel-gen-milk-bottle",
      animationId: "anim_heal",
      occasion: "always",
      consumable: true,
      hpRecovery: { flat: 30, percentMax: 0 },
      mpRecovery: { flat: 5, percentMax: 0 },
      skillId: "skill_item_potion",
    }),
    // ── 공격 소비품 ──
    normalizeItemRecord({
      id: "item_gen_fire_bomb",
      name: "화염탄",
      type: "special",
      scope: "enemy",
      price: 100,
      description: "적 하나에게 화염 피해를 주는 투척용 폭탄입니다.",
      imageResourceId: "cc0-jetrel-gen-fire-bomb",
      iconResourceId: "cc0-jetrel-gen-fire-bomb",
      skillId: "skill_fire",
      animationId: "anim_magic",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_gen_ice_shard",
      name: "얼음 조각",
      type: "special",
      scope: "enemy",
      price: 100,
      description: "적 하나에게 냉기 피해를 주는 날카로운 얼음 조각입니다.",
      imageResourceId: "cc0-jetrel-gen-ice-shard",
      iconResourceId: "cc0-jetrel-gen-ice-shard",
      skillId: "skill_water",
      animationId: "anim_magic",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_gen_thunder_rod",
      name: "번개 막대",
      type: "special",
      scope: "enemy",
      price: 120,
      description: "적 하나에게 전격 피해를 방출하는 마법 막대입니다.",
      imageResourceId: "cc0-jetrel-gen-thunder-rod",
      iconResourceId: "cc0-jetrel-gen-thunder-rod",
      skillId: "skill_item_thunder_stone",
      animationId: "anim_magic",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_gen_poison_flask",
      name: "독 플라스크",
      type: "special",
      scope: "enemy",
      price: 140,
      description: "적 하나에게 독을 노리는 투척용 플라스크입니다.",
      imageResourceId: "cc0-jetrel-gen-poison-flask",
      iconResourceId: "cc0-jetrel-gen-poison-flask",
      skillId: "skill_item_poison_vial",
      animationId: "anim_poison",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_gen_smoke_ball",
      name: "연막탄",
      type: "special",
      scope: "enemy",
      price: 60,
      description: "적 하나의 방어를 낮추는 짙은 연막을 퍼뜨리는 구슬입니다.",
      imageResourceId: "cc0-jetrel-gen-smoke-ball",
      iconResourceId: "cc0-jetrel-gen-smoke-ball",
      skillId: "skill_weaken",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_gen_throwing_knife",
      name: "균형 투척 단검",
      type: "special",
      scope: "enemy",
      price: 110,
      description: "무게중심을 맞춰 적 하나에게 정확히 던지는 전투용 단검입니다.",
      imageResourceId: "cc0-jetrel-gen-throwing-knife",
      iconResourceId: "cc0-jetrel-gen-throwing-knife",
      skillId: "skill_throwing_knife",
      animationId: "anim_arrow",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_gen_shuriken",
      name: "수리검",
      type: "special",
      scope: "enemy",
      price: 120,
      description: "적 하나에게 날려 피해를 주는 동방식 수리검입니다.",
      imageResourceId: "cc0-jetrel-gen-shuriken",
      iconResourceId: "cc0-jetrel-gen-shuriken",
      skillId: "skill_throwing_knife",
      animationId: "anim_arrow",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_gen_holy_water",
      name: "성수",
      type: "special",
      scope: "enemy",
      price: 130,
      description: "적 하나에게 신성한 피해를 주는 축복받은 물입니다.",
      imageResourceId: "cc0-jetrel-gen-holy-water",
      iconResourceId: "cc0-jetrel-gen-holy-water",
      skillId: "skill_item_holy_water",
      animationId: "anim_magic",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
    }),
    normalizeItemRecord({
      id: "item_gen_net_trap",
      name: "포획 그물",
      type: "special",
      scope: "enemy",
      price: 100,
      description: "약해진 몬스터를 포획하는 데 쓰는 튼튼한 그물입니다.",
      imageResourceId: "cc0-jetrel-gen-net-trap",
      iconResourceId: "cc0-jetrel-gen-net-trap",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
      captureProfile: { multiplier: 1.5, ballClass: "great" },
    }),
    normalizeItemRecord({
      id: "item_gen_capture_sphere",
      name: "강화 포획 구슬",
      type: "special",
      scope: "enemy",
      price: 120,
      description: "약해진 몬스터를 포획하는 성능 좋은 구슬입니다.",
      imageResourceId: "cc0-jetrel-gen-capture-sphere",
      iconResourceId: "cc0-jetrel-gen-capture-sphere",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
      captureProfile: { multiplier: 2, ballClass: "ultra" },
    }),
    // 볼 등급 사다리의 최상단 — gen1 공식은 master 를 확정 포획(255/255)으로 처리한다.
    // rm2k3 공식은 배율만 읽는데 정규화가 100 으로 상한을 두므로 ×100 — 포획 가능한
    // 종이라면 실질적으로 항상 성공한다.
    normalizeItemRecord({
      id: "item_gen_master_orb",
      name: "마스터 구슬",
      type: "special",
      scope: "enemy",
      price: 5000,
      description: "어떤 몬스터든 반드시 포획하는 전설의 구슬입니다.",
      imageResourceId: "cc0-jetrel-gen-capture-sphere",
      iconResourceId: "cc0-jetrel-gen-capture-sphere",
      occasion: "battle",
      occasionField: false,
      occasionBattle: true,
      consumable: true,
      captureProfile: { multiplier: 255, ballClass: "master" },
    }),
    // ── 재료 (사용 효과 없는 보관용) ──
    normalizeItemRecord({
      id: "item_gen_ore_copper",
      name: "구리 광석",
      type: "normalGoods",
      scope: "none",
      price: 15,
      description: "구리가 섞인 광석 덩어리입니다. 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-ore-copper",
      iconResourceId: "cc0-jetrel-gen-ore-copper",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_ore_iron",
      name: "제련용 철 광석",
      type: "normalGoods",
      scope: "none",
      price: 30,
      description: "철이 박힌 광석 덩어리입니다. 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-ore-iron",
      iconResourceId: "cc0-jetrel-gen-ore-iron",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_ore_mythril",
      name: "미스릴 광석",
      type: "normalGoods",
      scope: "none",
      price: 120,
      description: "미스릴 결정이 빛나는 희귀 광석입니다. 고급 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-ore-mythril",
      iconResourceId: "cc0-jetrel-gen-ore-mythril",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_ingot_gold",
      name: "금괴",
      type: "normalGoods",
      scope: "none",
      price: 200,
      description: "순금으로 주조한 작은 금괴입니다. 비싸게 팔 수 있습니다.",
      imageResourceId: "cc0-jetrel-gen-ingot-gold",
      iconResourceId: "cc0-jetrel-gen-ingot-gold",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_gem_ruby",
      name: "루비",
      type: "normalGoods",
      scope: "none",
      price: 150,
      description: "붉게 빛나는 보석입니다. 장신구 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-gem-ruby",
      iconResourceId: "cc0-jetrel-gen-gem-ruby",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_gem_sapphire",
      name: "사파이어",
      type: "normalGoods",
      scope: "none",
      price: 150,
      description: "푸르게 빛나는 보석입니다. 장신구 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-gem-sapphire",
      iconResourceId: "cc0-jetrel-gen-gem-sapphire",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_gem_emerald",
      name: "에메랄드",
      type: "normalGoods",
      scope: "none",
      price: 150,
      description: "초록빛으로 빛나는 보석입니다. 장신구 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-gem-emerald",
      iconResourceId: "cc0-jetrel-gen-gem-emerald",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_pelt_wolf",
      name: "늑대 가죽",
      type: "normalGoods",
      scope: "none",
      price: 20,
      description: "늑대에게서 벗긴 가죽입니다. 방어구 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-pelt-wolf",
      iconResourceId: "cc0-jetrel-gen-pelt-wolf",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_fang_beast",
      name: "야수 이빨",
      type: "normalGoods",
      scope: "none",
      price: 25,
      description: "날카로운 야수의 이빨입니다. 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-fang-beast",
      iconResourceId: "cc0-jetrel-gen-fang-beast",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_scale_dragon",
      name: "용의 비늘",
      type: "normalGoods",
      scope: "none",
      price: 300,
      description: "영롱한 빛을 내는 용의 비늘입니다. 최고급 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-scale-dragon",
      iconResourceId: "cc0-jetrel-gen-scale-dragon",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_feather_raven",
      name: "까마귀 깃털",
      type: "normalGoods",
      scope: "none",
      price: 10,
      description: "윤기 나는 검은 깃털입니다. 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-feather-raven",
      iconResourceId: "cc0-jetrel-gen-feather-raven",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_thread_silk",
      name: "명주실",
      type: "normalGoods",
      scope: "none",
      price: 40,
      description: "고운 명주실 한 타래입니다. 로브 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-thread-silk",
      iconResourceId: "cc0-jetrel-gen-thread-silk",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_plank_oak",
      name: "떡갈 판자",
      type: "normalGoods",
      scope: "none",
      price: 15,
      description: "떡갈나무로 만든 판자 더미입니다. 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-plank-oak",
      iconResourceId: "cc0-jetrel-gen-plank-oak",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_slime_jelly",
      name: "슬라임 젤리",
      type: "normalGoods",
      scope: "none",
      price: 12,
      description: "말랑말랑한 슬라임의 젤리입니다. 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-slime-jelly",
      iconResourceId: "cc0-jetrel-gen-slime-jelly",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_mushroom_cave",
      name: "동굴 버섯",
      type: "normalGoods",
      scope: "none",
      price: 18,
      description: "동굴에서 자란 보라색 버섯입니다. 제작 재료로 쓰입니다.",
      imageResourceId: "cc0-jetrel-gen-mushroom-cave",
      iconResourceId: "cc0-jetrel-gen-mushroom-cave",
      occasion: "never",
      consumable: false,
    }),
    // ── 열쇠·퀘스트 (사용 효과 없는 보관용) ──
    normalizeItemRecord({
      id: "item_gen_key_rusty",
      name: "녹슨 열쇠",
      type: "normalGoods",
      scope: "none",
      price: 0,
      description: "녹슨 철 열쇠입니다. 오래된 문을 열 수 있을 것 같습니다.",
      imageResourceId: "cc0-jetrel-gen-key-rusty",
      iconResourceId: "cc0-jetrel-gen-key-rusty",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_key_gold",
      name: "황금 열쇠",
      type: "normalGoods",
      scope: "none",
      price: 0,
      description: "화려한 황금 열쇠입니다. 중요한 문을 열 수 있을 것 같습니다.",
      imageResourceId: "cc0-jetrel-gen-key-gold",
      iconResourceId: "cc0-jetrel-gen-key-gold",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_map_scroll",
      name: "지도 두루마리",
      type: "normalGoods",
      scope: "none",
      price: 0,
      description: "붉은 X 표시가 있는 지도 두루마리입니다. 보물의 위치를 가리킵니다.",
      imageResourceId: "cc0-jetrel-gen-map-scroll",
      iconResourceId: "cc0-jetrel-gen-map-scroll",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_letter_sealed",
      name: "봉인된 편지",
      type: "normalGoods",
      scope: "none",
      price: 0,
      description: "붉은 밀랍으로 봉인된 편지입니다. 누군가에게 전달해야 합니다.",
      imageResourceId: "cc0-jetrel-gen-letter-sealed",
      iconResourceId: "cc0-jetrel-gen-letter-sealed",
      occasion: "never",
      consumable: false,
    }),
    normalizeItemRecord({
      id: "item_gen_lamp_oil",
      name: "기름 등불",
      type: "normalGoods",
      scope: "none",
      price: 50,
      description: "어두운 곳을 밝히는 황동 기름 등불입니다.",
      imageResourceId: "cc0-jetrel-gen-lamp-oil",
      iconResourceId: "cc0-jetrel-gen-lamp-oil",
      occasion: "never",
      consumable: false,
    }),
  ];
}

export function generatedEquipmentRecords(): EquipmentRecord[] {
  return [
    // ── 무기 ──
    normalizeEquipmentRecord({
      id: "equip_gen_sword_bronze",
      name: "보급형 청동 검",
      slot: "weapon",
      price: 110,
      imageResourceId: "cc0-jetrel-gen-sword-bronze",
      iconResourceId: "cc0-jetrel-gen-sword-bronze",
      description: "기준 검보다 조금 강하지만 명중은 소폭 낮은 보급대용 청동 검입니다.",
      statBonuses: { attack: 9, defense: 0, mind: 0, agility: 0 },
      attackElementIds: ["sword"],
      accuracy: 98,
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_sword_iron",
      name: "제련소 철 검",
      slot: "weapon",
      price: 200,
      imageResourceId: "cc0-jetrel-gen-sword-iron",
      iconResourceId: "cc0-jetrel-gen-sword-iron",
      description: "단단한 칼날로 꾸준한 검 피해를 내되 빠른 적에게는 조금 불리합니다.",
      statBonuses: { attack: 15, defense: 0, mind: 0, agility: 0 },
      attackElementIds: ["sword"],
      accuracy: 95,
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_sword_steel",
      name: "기사단 강철 검",
      slot: "weapon",
      price: 330,
      imageResourceId: "cc0-jetrel-gen-sword-steel",
      iconResourceId: "cc0-jetrel-gen-sword-steel",
      description: "높은 검격과 치명타 가능성을 얻는 대신 명중과 민첩을 내준 기사단 무기입니다.",
      statBonuses: { attack: 21, defense: 0, mind: 0, agility: -1 },
      attackElementIds: ["sword"],
      criticalRate: 4,
      accuracy: 90,
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_sword_flame",
      name: "화염 검",
      slot: "weapon",
      price: 460,
      imageResourceId: "cc0-jetrel-gen-sword-flame",
      iconResourceId: "cc0-jetrel-gen-sword-flame",
      description: "화염 약점을 태우는 고화력 마검으로, 순수 강철 무기보다 값이 비쌉니다.",
      statBonuses: { attack: 26, defense: 0, mind: 0, agility: 0 },
      accuracy: 94,
      attackElementIds: ["fire"],
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_sword_frost",
      name: "서릿 검",
      slot: "weapon",
      price: 460,
      imageResourceId: "cc0-jetrel-gen-sword-frost",
      iconResourceId: "cc0-jetrel-gen-sword-frost",
      description: "얼음 공격과 작은 방어 보너스로 화력보다 생존을 택한 마법 검입니다.",
      statBonuses: { attack: 25, defense: 1, mind: 0, agility: 0 },
      accuracy: 96,
      attackElementIds: ["ice"],
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_dagger_scout",
      name: "경량 정찰 단검",
      slot: "weapon",
      price: 140,
      imageResourceId: "cc0-jetrel-gen-dagger-scout",
      iconResourceId: "cc0-jetrel-gen-dagger-scout",
      description: "공격력보다 민첩과 치명타 기회를 중시하는 정찰대의 보조 단검입니다.",
      statBonuses: { attack: 6, defense: 0, mind: 0, agility: 3 },
      attackElementIds: ["sword"],
      criticalRate: 5,
      accuracy: 98,
      equippableActorIds: [...AGILE_ACTORS],
      equippableClassIds: [...AGILE_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_rapier_noble",
      name: "귀족 레이피어",
      slot: "weapon",
      price: 360,
      imageResourceId: "cc0-jetrel-gen-rapier-noble",
      iconResourceId: "cc0-jetrel-gen-rapier-noble",
      description: "낮춘 기본 위력을 정확한 찌르기와 높은 치명타율로 만회하는 결투검입니다.",
      statBonuses: { attack: 15, defense: 0, mind: 0, agility: 4 },
      attackElementIds: ["sword"],
      criticalRate: 9,
      accuracy: 100,
      equippableActorIds: [...AGILE_ACTORS],
      equippableClassIds: [...AGILE_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_axe_battle",
      name: "전투 도끼",
      slot: "weapon",
      price: 320,
      imageResourceId: "cc0-jetrel-gen-axe-battle",
      iconResourceId: "cc0-jetrel-gen-axe-battle",
      description: "명중이 불안정하지만 강한 타격과 치명타를 노리는 한손 전투 도끼입니다.",
      statBonuses: { attack: 22, defense: 0, mind: 0, agility: -1 },
      attackElementIds: ["hit"],
      criticalRate: 8,
      accuracy: 88,
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_axe_great",
      name: "대형 도끼",
      slot: "weapon",
      price: 560,
      imageResourceId: "cc0-jetrel-gen-axe-great",
      iconResourceId: "cc0-jetrel-gen-axe-great",
      description: "방패와 명중을 포기하고 큰 치명타 한 방에 투자하는 양손 도끼입니다.",
      statBonuses: { attack: 30, defense: 0, mind: 0, agility: -2 },
      attackElementIds: ["hit"],
      criticalRate: 12,
      accuracy: 80,
      twoHanded: true,
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_spear_iron",
      name: "철 창",
      slot: "weapon",
      price: 260,
      imageResourceId: "cc0-jetrel-gen-spear-iron",
      iconResourceId: "cc0-jetrel-gen-spear-iron",
      description: "긴 창끝으로 안정적으로 급소를 찌르는 정확도 중심의 전열 무기입니다.",
      statBonuses: { attack: 18, defense: 0, mind: 0, agility: 1 },
      attackElementIds: ["spear"],
      criticalRate: 3,
      accuracy: 100,
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_halberd_guard",
      name: "경비 할버드",
      slot: "weapon",
      price: 410,
      imageResourceId: "cc0-jetrel-gen-halberd-guard",
      iconResourceId: "cc0-jetrel-gen-halberd-guard",
      description: "창의 명중과 도끼의 위력을 절충해 방어까지 보태는 경비대 무기입니다.",
      statBonuses: { attack: 24, defense: 2, mind: 0, agility: 0 },
      attackElementIds: ["spear"],
      criticalRate: 4,
      accuracy: 94,
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_mace_heavy",
      name: "중형 철퇴",
      slot: "weapon",
      price: 340,
      imageResourceId: "cc0-jetrel-gen-mace-heavy",
      iconResourceId: "cc0-jetrel-gen-mace-heavy",
      description: "빠른 적은 놓치기 쉽지만 타격과 함께 방어를 무너뜨릴 수 있는 철퇴입니다.",
      statBonuses: { attack: 21, defense: 0, mind: 0, agility: -1 },
      stateInflictionChance: 20,
      stateInflictIds: ["state_defense_down"],
      attackElementIds: ["hit"],
      accuracy: 88,
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_hammer_war",
      name: "전쟁 망치",
      slot: "weapon",
      price: 540,
      imageResourceId: "cc0-jetrel-gen-hammer-war",
      iconResourceId: "cc0-jetrel-gen-hammer-war",
      description: "느리고 부정확한 양손 일격으로 마비를 노리는 전열 파괴용 망치입니다.",
      statBonuses: { attack: 28, defense: 0, mind: 0, agility: -2 },
      stateInflictionChance: 18,
      stateInflictIds: ["state_paralysis"],
      attackElementIds: ["hit"],
      criticalRate: 8,
      accuracy: 82,
      twoHanded: true,
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_bow_short",
      name: "단궁",
      slot: "weapon",
      price: 160,
      imageResourceId: "cc0-jetrel-gen-bow-short",
      iconResourceId: "cc0-jetrel-gen-bow-short",
      description: "위력보다 빠른 조준과 안정적인 활 명중을 택한 기동 사격 무기입니다.",
      statBonuses: { attack: 12, defense: 0, mind: 0, agility: 2 },
      attackElementIds: ["bow"],
      accuracy: 98,
      equippableActorIds: [...AGILE_ACTORS],
      equippableClassIds: [...AGILE_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_bow_long",
      name: "장궁",
      slot: "weapon",
      price: 310,
      imageResourceId: "cc0-jetrel-gen-bow-long",
      iconResourceId: "cc0-jetrel-gen-bow-long",
      description: "민첩 보너스와 완전한 조준으로 먼 적의 약점을 찌르는 장거리 활입니다.",
      statBonuses: { attack: 18, defense: 0, mind: 0, agility: 3 },
      attackElementIds: ["bow"],
      criticalRate: 3,
      accuracy: 100,
      equippableActorIds: [...AGILE_ACTORS],
      equippableClassIds: [...AGILE_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_crossbow_hand",
      name: "손 석궁",
      slot: "weapon",
      price: 260,
      imageResourceId: "cc0-jetrel-gen-crossbow-hand",
      iconResourceId: "cc0-jetrel-gen-crossbow-hand",
      description: "민첩 상승은 낮지만 빗나가지 않는 관통 사격과 치명타를 제공하는 석궁입니다.",
      statBonuses: { attack: 16, defense: 0, mind: 0, agility: 2 },
      attackElementIds: ["bow"],
      criticalRate: 5,
      accuracy: 100,
      equippableActorIds: [...AGILE_ACTORS],
      equippableClassIds: [...AGILE_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_staff_oak",
      name: "떡갈나무 지팡이",
      slot: "weapon",
      price: 140,
      imageResourceId: "cc0-jetrel-gen-staff-oak",
      iconResourceId: "cc0-jetrel-gen-staff-oak",
      description: "대지의 기운을 빌려 정신력을 안정시키는 수습 마도사의 타격 지팡이입니다.",
      statBonuses: { attack: 3, defense: 0, mind: 8, agility: 0 },
      attackElementIds: ["earth"],
      accuracy: 96,
      equippableActorIds: [...CASTER_ACTORS],
      equippableClassIds: [...CASTER_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_staff_crystal",
      name: "수정 지팡이",
      slot: "weapon",
      price: 360,
      imageResourceId: "cc0-jetrel-gen-staff-crystal",
      iconResourceId: "cc0-jetrel-gen-staff-crystal",
      description: "정신력을 크게 증폭하고 침묵을 유발할 수 있지만 물리 타격은 약한 지팡이입니다.",
      statBonuses: { attack: 4, defense: 0, mind: 14, agility: 0 },
      stateInflictionChance: 15,
      stateInflictIds: ["state_silence"],
      attackElementIds: ["holy"],
      accuracy: 94,
      equippableActorIds: [...CASTER_ACTORS],
      equippableClassIds: [...CASTER_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_wand_spark",
      name: "불꽃 마법봉",
      slot: "weapon",
      price: 260,
      imageResourceId: "cc0-jetrel-gen-wand-spark",
      iconResourceId: "cc0-jetrel-gen-wand-spark",
      description: "낮은 물리 공격을 감수하고 화염 약점을 정확히 겨냥하는 주문 촉매입니다.",
      statBonuses: { attack: 2, defense: 0, mind: 10, agility: 0 },
      accuracy: 98,
      attackElementIds: ["fire"],
      equippableActorIds: [...CASTER_ACTORS],
      equippableClassIds: [...CASTER_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_katana_east",
      name: "동방 도",
      slot: "weapon",
      price: 440,
      imageResourceId: "cc0-jetrel-gen-katana-east",
      iconResourceId: "cc0-jetrel-gen-katana-east",
      description: "기본 위력을 낮춘 대신 민첩과 높은 치명타율로 승부하는 동방 곡도입니다.",
      statBonuses: { attack: 21, defense: 0, mind: 0, agility: 3 },
      attackElementIds: ["sword"],
      criticalRate: 11,
      accuracy: 95,
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_claw_beast",
      name: "야수 발톱",
      slot: "weapon",
      price: 340,
      imageResourceId: "cc0-jetrel-gen-claw-beast",
      iconResourceId: "cc0-jetrel-gen-claw-beast",
      description: "한 번의 위력을 낮추고 두 차례 연속 할퀴는 민첩형 강철 발톱입니다.",
      statBonuses: { attack: 9, defense: 0, mind: 0, agility: 5 },
      effectFlags: {
        preemptive: false,
        doubleAttack: true,
        attackAll: false,
        ignoreDodge: false,
        preventCriticalHits: false,
        increasePhysicalDodge: false,
        halfMpCost: false,
        negateTerrainDamage: false,
        fixedEquipment: false,
      },
      attackElementIds: ["sword"],
      accuracy: 94,
      equippableActorIds: [...AGILE_ACTORS],
      equippableClassIds: [...AGILE_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_whip_leather",
      name: "가죽 채찍",
      slot: "weapon",
      price: 240,
      imageResourceId: "cc0-jetrel-gen-whip-leather",
      iconResourceId: "cc0-jetrel-gen-whip-leather",
      description: "긴 채찍으로 적의 발을 얽어 민첩을 낮추는 제어형 무기입니다.",
      statBonuses: { attack: 15, defense: 0, mind: 0, agility: 2 },
      stateInflictionChance: 25,
      stateInflictIds: ["state_agility_down"],
      attackElementIds: ["hit"],
      accuracy: 92,
      equippableActorIds: [...AGILE_ACTORS],
      equippableClassIds: [...AGILE_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_scythe_reaper",
      name: "사신 낫",
      slot: "weapon",
      price: 680,
      imageResourceId: "cc0-jetrel-gen-scythe-reaper",
      iconResourceId: "cc0-jetrel-gen-scythe-reaper",
      description: "명중과 속도를 크게 희생해 치명타와 맹독을 함께 노리는 양손 낫입니다.",
      statBonuses: { attack: 32, defense: 0, mind: 0, agility: -2 },
      stateInflictionChance: 20,
      stateInflictIds: ["state_deep_poison"],
      attackElementIds: ["dark"],
      criticalRate: 10,
      accuracy: 78,
      twoHanded: true,
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_gun_flint",
      name: "화승총",
      slot: "weapon",
      price: 520,
      imageResourceId: "cc0-jetrel-gen-gun-flint",
      iconResourceId: "cc0-jetrel-gen-gun-flint",
      description: "재장전 때문에 빗나갈 수 있지만 가장 높은 치명타율을 지닌 화약 무기입니다.",
      statBonuses: { attack: 25, defense: 0, mind: 0, agility: 1 },
      attackElementIds: ["hit"],
      criticalRate: 15,
      accuracy: 85,
      equippableActorIds: [...WARRIOR_ACTORS],
      equippableClassIds: [...WARRIOR_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_boomerang_wood",
      name: "부메랑",
      slot: "weapon",
      price: 210,
      imageResourceId: "cc0-jetrel-gen-boomerang-wood",
      iconResourceId: "cc0-jetrel-gen-boomerang-wood",
      description: "개별 위력을 낮추는 대신 살아 있는 모든 적을 한 번씩 훑는 투척 무기입니다.",
      statBonuses: { attack: 8, defense: 0, mind: 0, agility: 4 },
      effectFlags: {
        preemptive: false,
        doubleAttack: false,
        attackAll: true,
        ignoreDodge: false,
        preventCriticalHits: false,
        increasePhysicalDodge: false,
        halfMpCost: false,
        negateTerrainDamage: false,
        fixedEquipment: false,
      },
      attackElementIds: ["hit"],
      accuracy: 90,
      equippableActorIds: [...AGILE_ACTORS],
      equippableClassIds: [...AGILE_CLASSES],
    }),
    // ── 방어구: 방패 ──
    normalizeEquipmentRecord({
      id: "equip_gen_shield_wood",
      name: "나무 방패",
      slot: "shield",
      price: 80,
      imageResourceId: "cc0-jetrel-gen-shield-wood",
      iconResourceId: "cc0-jetrel-gen-shield-wood",
      description: "가장 싼 가격으로 활 피해를 줄이며 가볍게 전열을 보조하는 방패입니다.",
      statBonuses: { attack: 0, defense: 4, mind: 0, agility: 0 },
      elementalDefenseIds: ["bow"],
      equippableActorIds: [...SHIELD_ACTORS],
      equippableClassIds: [...SHIELD_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_shield_iron",
      name: "철 방패",
      slot: "shield",
      price: 200,
      imageResourceId: "cc0-jetrel-gen-shield-iron",
      iconResourceId: "cc0-jetrel-gen-shield-iron",
      description: "철판으로 검격을 줄이고 방어 하락에도 버틸 여지를 주는 중급 방패입니다.",
      statBonuses: { attack: 0, defense: 8, mind: 0, agility: 0 },
      stateResistanceChance: 20,
      stateDefenseIds: ["state_defense_down"],
      elementalDefenseIds: ["sword"],
      equippableActorIds: [...SHIELD_ACTORS],
      equippableClassIds: [...SHIELD_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_shield_tower",
      name: "타워 실드",
      slot: "shield",
      price: 390,
      imageResourceId: "cc0-jetrel-gen-shield-tower",
      iconResourceId: "cc0-jetrel-gen-shield-tower",
      description: "민첩을 잃는 대신 타격 피해와 마비를 함께 막는 거대한 성벽형 방패입니다.",
      statBonuses: { attack: 0, defense: 14, mind: 0, agility: -1 },
      stateResistanceChance: 35,
      stateDefenseIds: ["state_paralysis"],
      elementalDefenseIds: ["hit"],
      equippableActorIds: [...SHIELD_ACTORS],
      equippableClassIds: [...SHIELD_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_shield_mirror",
      name: "거울 방패",
      slot: "shield",
      price: 340,
      imageResourceId: "cc0-jetrel-gen-shield-mirror",
      iconResourceId: "cc0-jetrel-gen-shield-mirror",
      description: "물리 방어보다 정신 보호에 치중해 신성·암흑 피해를 줄이는 은빛 방패입니다.",
      statBonuses: { attack: 0, defense: 10, mind: 3, agility: 0 },
      elementalDefenseIds: ["holy", "dark"],
      equippableActorIds: [...SHIELD_ACTORS],
      equippableClassIds: [...SHIELD_CLASSES],
    }),
    // ── 방어구: 갑옷 ──
    normalizeEquipmentRecord({
      id: "equip_gen_armor_leather",
      name: "사냥꾼 가죽 갑옷",
      slot: "armor",
      price: 190,
      imageResourceId: "cc0-jetrel-gen-armor-leather",
      iconResourceId: "cc0-jetrel-gen-armor-leather",
      description: "기본 가죽보다 단단하고 독에 강해 야외 사냥에 맞춘 경갑입니다.",
      statBonuses: { attack: 0, defense: 7, mind: 0, agility: 0 },
      stateResistanceChance: 25,
      stateDefenseIds: ["state_poison"],
      equippableActorIds: [...BODY_ACTORS],
      equippableClassIds: [...BODY_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_armor_chain",
      name: "사슬 갑옷",
      slot: "armor",
      price: 290,
      imageResourceId: "cc0-jetrel-gen-armor-chain",
      iconResourceId: "cc0-jetrel-gen-armor-chain",
      description: "민첩을 조금 잃지만 검격과 마비에 대응하는 촘촘한 사슬 갑옷입니다.",
      statBonuses: { attack: 0, defense: 10, mind: 0, agility: -1 },
      stateResistanceChance: 20,
      stateDefenseIds: ["state_paralysis"],
      elementalDefenseIds: ["sword"],
      equippableActorIds: [...BODY_ACTORS],
      equippableClassIds: [...BODY_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_armor_plate",
      name: "판금 갑옷",
      slot: "armor",
      price: 500,
      imageResourceId: "cc0-jetrel-gen-armor-plate",
      iconResourceId: "cc0-jetrel-gen-armor-plate",
      description: "큰 민첩 손실을 감수하고 타격과 화염을 함께 줄이는 전면 중갑입니다.",
      statBonuses: { attack: 0, defense: 16, mind: 0, agility: -2 },
      elementalDefenseIds: ["hit", "fire"],
      equippableActorIds: [...BODY_ACTORS],
      equippableClassIds: [...BODY_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_armor_mythril",
      name: "미스릴 갑옷",
      slot: "armor",
      price: 820,
      imageResourceId: "cc0-jetrel-gen-armor-mythril",
      iconResourceId: "cc0-jetrel-gen-armor-mythril",
      description: "높은 가격으로 민첩까지 보존하며 화염·냉기·번개를 두루 막는 최고급 갑옷입니다.",
      statBonuses: { attack: 0, defense: 22, mind: 0, agility: 2 },
      elementalDefenseIds: ["fire", "ice", "thunder"],
      equippableActorIds: [...BODY_ACTORS],
      equippableClassIds: [...BODY_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_robe_cloth",
      name: "천 로브",
      slot: "armor",
      price: 120,
      imageResourceId: "cc0-jetrel-gen-robe-cloth",
      iconResourceId: "cc0-jetrel-gen-robe-cloth",
      description: "낮은 방어 대신 침묵 주문에 약간 버티며 수련을 이어 가는 값싼 로브입니다.",
      statBonuses: { attack: 0, defense: 3, mind: 2, agility: 0 },
      stateResistanceChance: 20,
      stateDefenseIds: ["state_silence"],
      equippableActorIds: [...CASTER_ACTORS],
      equippableClassIds: [...CASTER_CLASSES],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_robe_mage",
      name: "마법사 로브",
      slot: "armor",
      price: 360,
      imageResourceId: "cc0-jetrel-gen-robe-mage",
      iconResourceId: "cc0-jetrel-gen-robe-mage",
      description: "정신력을 크게 높이고 화염·냉기 피해를 줄이는 정통 원소술사 로브입니다.",
      statBonuses: { attack: 0, defense: 5, mind: 8, agility: 0 },
      elementalDefenseIds: ["fire", "ice"],
      equippableActorIds: [...CASTER_ACTORS],
      equippableClassIds: [...CASTER_CLASSES],
    }),
    // ── 방어구: 투구 ──
    normalizeEquipmentRecord({
      id: "equip_gen_helm_leather",
      name: "가죽 투구",
      slot: "helmet",
      price: 75,
      imageResourceId: "cc0-jetrel-gen-helm-leather",
      iconResourceId: "cc0-jetrel-gen-helm-leather",
      description: "값싼 머리 방어와 함께 수면 상태에 빠질 확률을 조금 낮추는 투구입니다.",
      statBonuses: { attack: 0, defense: 3, mind: 0, agility: 0 },
      stateResistanceChance: 15,
      stateDefenseIds: ["state_sleep"],
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_helm_iron",
      name: "철 투구",
      slot: "helmet",
      price: 180,
      imageResourceId: "cc0-jetrel-gen-helm-iron",
      iconResourceId: "cc0-jetrel-gen-helm-iron",
      description: "정신 보너스는 없지만 타격 피해와 마비 충격을 막는 철제 투구입니다.",
      statBonuses: { attack: 0, defense: 6, mind: 0, agility: 0 },
      stateResistanceChance: 20,
      stateDefenseIds: ["state_paralysis"],
      elementalDefenseIds: ["hit"],
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_helm_horned",
      name: "뿔 투구",
      slot: "helmet",
      price: 260,
      imageResourceId: "cc0-jetrel-gen-helm-horned",
      iconResourceId: "cc0-jetrel-gen-helm-horned",
      description: "방어와 공격을 함께 얻는 대신 적의 방어를 깎는 난전형 돌격 투구입니다.",
      statBonuses: { attack: 2, defense: 8, mind: 0, agility: 0 },
      stateInflictionChance: 12,
      stateInflictIds: ["state_defense_down"],
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_hat_traveler",
      name: "개척자 여행 모자",
      slot: "helmet",
      price: 110,
      imageResourceId: "cc0-jetrel-gen-hat-traveler",
      iconResourceId: "cc0-jetrel-gen-hat-traveler",
      description: "네 능력치의 균형을 해치지 않고 독을 막아 주는 개척지용 모자입니다.",
      statBonuses: { attack: 0, defense: 2, mind: 1, agility: 1 },
      stateResistanceChance: 20,
      stateDefenseIds: ["state_poison"],
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_hat_witch",
      name: "마녀 모자",
      slot: "helmet",
      price: 250,
      imageResourceId: "cc0-jetrel-gen-hat-witch",
      iconResourceId: "cc0-jetrel-gen-hat-witch",
      description: "물리 방어보다 정신력과 침묵 저항에 투자한 주문사 전용 성향의 모자입니다.",
      statBonuses: { attack: 0, defense: 2, mind: 6, agility: 0 },
      stateResistanceChance: 40,
      stateDefenseIds: ["state_silence"],
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    // ── 방어구: 장신구(신발·장갑·망토·허리띠) ──
    normalizeEquipmentRecord({
      id: "equip_gen_boots_leather",
      name: "가죽 장화",
      slot: "accessory",
      price: 150,
      imageResourceId: "cc0-jetrel-gen-boots-leather",
      iconResourceId: "cc0-jetrel-gen-boots-leather",
      description: "방어와 민첩을 함께 보태며 민첩 하락 효과를 버티는 실용 장화입니다.",
      statBonuses: { attack: 0, defense: 2, mind: 0, agility: 2 },
      stateResistanceChance: 20,
      stateDefenseIds: ["state_agility_down"],
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_boots_swift",
      name: "신속 장화",
      slot: "accessory",
      price: 310,
      imageResourceId: "cc0-jetrel-gen-boots-swift",
      iconResourceId: "cc0-jetrel-gen-boots-swift",
      description: "방어를 완전히 포기해 최고 민첩과 민첩 하락 저항을 얻는 날개 장화입니다.",
      statBonuses: { attack: 0, defense: 0, mind: 0, agility: 5 },
      stateResistanceChance: 40,
      stateDefenseIds: ["state_agility_down"],
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_gloves_iron",
      name: "철 장갑",
      slot: "accessory",
      price: 210,
      imageResourceId: "cc0-jetrel-gen-gloves-iron",
      iconResourceId: "cc0-jetrel-gen-gloves-iron",
      description: "공격과 방어를 동시에 보태고 일반 공격의 치명타 가능성을 조금 높이는 건틀릿입니다.",
      statBonuses: { attack: 3, defense: 2, mind: 0, agility: 0 },
      criticalRate: 2,
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_cloak_shadow",
      name: "그림자 망토",
      slot: "accessory",
      price: 290,
      imageResourceId: "cc0-jetrel-gen-cloak-shadow",
      iconResourceId: "cc0-jetrel-gen-cloak-shadow",
      description: "방어와 민첩을 나누어 얻으며 암흑 피해와 수면 기습을 막는 망토입니다.",
      statBonuses: { attack: 0, defense: 3, mind: 0, agility: 3 },
      stateResistanceChance: 25,
      stateDefenseIds: ["state_sleep"],
      elementalDefenseIds: ["dark"],
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_belt_champion",
      name: "챔피언 벨트",
      slot: "accessory",
      price: 350,
      imageResourceId: "cc0-jetrel-gen-belt-champion",
      iconResourceId: "cc0-jetrel-gen-belt-champion",
      description: "힘과 맷집을 동시에 끌어올리고 공격 하락에 저항하는 투사의 허리띠입니다.",
      statBonuses: { attack: 2, defense: 3, mind: 0, agility: 0 },
      stateResistanceChance: 30,
      stateDefenseIds: ["state_attack_down"],
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    // ── 장식 ──
    normalizeEquipmentRecord({
      id: "equip_gen_ring_silver",
      name: "은 반지",
      slot: "accessory",
      price: 140,
      imageResourceId: "cc0-jetrel-gen-ring-silver",
      iconResourceId: "cc0-jetrel-gen-ring-silver",
      description: "작은 정신력 보너스와 침묵 저항을 저렴하게 제공하는 입문 주문 반지입니다.",
      statBonuses: { attack: 0, defense: 0, mind: 2, agility: 0 },
      stateResistanceChance: 15,
      stateDefenseIds: ["state_silence"],
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_ring_power",
      name: "힘의 반지",
      slot: "accessory",
      price: 300,
      imageResourceId: "cc0-jetrel-gen-ring-power",
      iconResourceId: "cc0-jetrel-gen-ring-power",
      description: "방어를 주지 않는 대신 공격력과 치명타율을 직접 끌어올리는 루비 반지입니다.",
      statBonuses: { attack: 4, defense: 0, mind: 0, agility: 0 },
      criticalRate: 3,
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_amulet_moon",
      name: "달 부적",
      slot: "accessory",
      price: 230,
      imageResourceId: "cc0-jetrel-gen-amulet-moon",
      iconResourceId: "cc0-jetrel-gen-amulet-moon",
      description: "정신 방어를 보태고 수면과 암흑 피해를 함께 막는 밤의 수호 부적입니다.",
      statBonuses: { attack: 0, defense: 1, mind: 3, agility: 0 },
      stateResistanceChance: 35,
      stateDefenseIds: ["state_sleep"],
      elementalDefenseIds: ["dark"],
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_amulet_sun",
      name: "태양 부적",
      slot: "accessory",
      price: 270,
      imageResourceId: "cc0-jetrel-gen-amulet-sun",
      iconResourceId: "cc0-jetrel-gen-amulet-sun",
      description: "공격과 정신을 나누어 올리며 화염 피해와 맹독을 억누르는 낮의 부적입니다.",
      statBonuses: { attack: 2, defense: 0, mind: 2, agility: 0 },
      stateResistanceChance: 20,
      stateDefenseIds: ["state_deep_poison"],
      elementalDefenseIds: ["fire"],
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_brooch_rose",
      name: "장미 브로치",
      slot: "accessory",
      price: 240,
      imageResourceId: "cc0-jetrel-gen-brooch-rose",
      iconResourceId: "cc0-jetrel-gen-brooch-rose",
      description: "방어와 정신을 고르게 보태고 독이 스미는 것을 막는 사교계 브로치입니다.",
      statBonuses: { attack: 0, defense: 2, mind: 2, agility: 0 },
      stateResistanceChance: 30,
      stateDefenseIds: ["state_poison"],
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_earring_jade",
      name: "옥 귀걸이",
      slot: "accessory",
      price: 290,
      imageResourceId: "cc0-jetrel-gen-earring-jade",
      iconResourceId: "cc0-jetrel-gen-earring-jade",
      description: "순수 정신력과 침묵 저항에 집중해 주문 사용을 지키는 옥 장신구입니다.",
      statBonuses: { attack: 0, defense: 0, mind: 4, agility: 0 },
      stateResistanceChance: 35,
      stateDefenseIds: ["state_silence"],
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_charm_luck",
      name: "행운 부적",
      slot: "accessory",
      price: 190,
      imageResourceId: "cc0-jetrel-gen-charm-luck",
      iconResourceId: "cc0-jetrel-gen-charm-luck",
      description: "작은 정신력과 높은 민첩에 더해 치명타 기회까지 얻는 행운 장식입니다.",
      statBonuses: { attack: 0, defense: 0, mind: 1, agility: 3 },
      criticalRate: 2,
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_orb_mana",
      name: "마나 구슬",
      slot: "accessory",
      price: 390,
      imageResourceId: "cc0-jetrel-gen-orb-mana",
      iconResourceId: "cc0-jetrel-gen-orb-mana",
      description: "방어 능력 없이 정신력을 극대화하고 침묵을 강하게 막는 투명 구슬입니다.",
      statBonuses: { attack: 0, defense: 0, mind: 6, agility: 0 },
      stateResistanceChance: 50,
      stateDefenseIds: ["state_silence"],
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_badge_guard",
      name: "경비 배지",
      slot: "accessory",
      price: 180,
      imageResourceId: "cc0-jetrel-gen-badge-guard",
      iconResourceId: "cc0-jetrel-gen-badge-guard",
      description: "순수 방어력과 방어 하락 저항으로 전열의 안정성을 높이는 경비대 표식입니다.",
      statBonuses: { attack: 0, defense: 3, mind: 0, agility: 0 },
      stateResistanceChance: 35,
      stateDefenseIds: ["state_defense_down"],
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
    normalizeEquipmentRecord({
      id: "equip_gen_mask_fox",
      name: "여우 가면",
      slot: "accessory",
      price: 240,
      imageResourceId: "cc0-jetrel-gen-mask-fox",
      iconResourceId: "cc0-jetrel-gen-mask-fox",
      description: "공격과 민첩을 함께 올리고 치명타율도 보태는 기습가의 가면입니다.",
      statBonuses: { attack: 2, defense: 0, mind: 0, agility: 2 },
      criticalRate: 3,
      equippableActorIds: [...ALL_ACTOR_IDS],
      equippableClassIds: [...ALL_CLASS_IDS],
    }),
  ];
}
