import type { TerrainTemplateMetadata } from "@/project/types";

export const SMALL_HOUSE_01_TERRAIN_TEMPLATE = {
  id: "small_house_01_table",
  name: "small_house_01 표 템플릿",
  sourceMapName: "small_house_01 변형 1",
  buildPlan: {
    fence: { x: 2, y: 2, width: 17, height: 15 },
    house: {
      roof: { origin: { x: 7, y: 4 }, width: 11 },
      wall: { origin: { x: 7, y: 8 }, width: 11, rows: 3 },
      door: { x: 13, topY: 9, bottomY: 10 },
      windows: [
        { x: 10, y: 9 },
        { x: 15, y: 9 },
      ],
    },
    roads: [
      { x: 13, y: 11, width: 2, height: 6 },
      { x: 13, y: 14, width: 4, height: 2 },
    ],
  },
  grammar: [
    { kind: "roof-row", role: "roof-top", layer: "upper", left: 375, middle: 375, right: 377, meaning: "지붕 길이를 먼저 정한 뒤, 안쪽 지붕 최상단 상위 행을 만든다. 왼쪽 내부 끝도 다른 평평한 지붕면과 똑같이 375를 쓰고, 가운데도 375 반복, 오른쪽 내부 끝은 377로 닫는다." },
    { kind: "roof-row", role: "roof-body", layer: "upper", middle: 375, meaning: "지붕 footprint 안쪽의 반복 상위 본체. 폭을 넓힐 때는 375를 가로로 반복하되 좌우 끝 캡을 유지한다." },
    { kind: "roof-row", role: "roof-lower-slope", layer: "lower", left: 405, middle: 405, right: 405, meaning: "벽 footprint 바로 위 하위 지붕면. 지붕 최하단부 lower는 전부 405로 반복한다." },
    { kind: "overlay", role: "left-diagonal-roof", layer: "upper", tiles: [354, 376], meaning: "354/376은 지붕 footprint의 왼쪽 끝 상위 대각면이다. 같은 좌표의 lower는 지붕 타일을 깔지 않고 바탕 지형으로 비워 둔다." },
    { kind: "overlay", role: "right-diagonal-roof", layer: "upper", tiles: [355, 377], meaning: "355/377은 지붕 footprint의 오른쪽 끝 상위 대각면이다. 같은 좌표의 lower는 지붕 타일을 깔지 않고 바탕 지형으로 비워 둔다." },
    { kind: "wall-row", role: "wall-top", layer: "lower", left: 15, middle: 16, right: 17, meaning: "지붕과 직접 닿는 첫 벽 행. 지붕 하단부 바로 아래는 반드시 wall-top 15/16/17이어야 한다.", mustTouch: "roof-lower-slope" },
    { kind: "wall-row", role: "wall-middle", layer: "lower", left: 45, middle: 46, right: 47, meaning: "벽 중단부 반복 행. 지붕과 직접 닿으면 안 되고, 창문 upper 장식은 이 행 위에만 놓는다.", mustTouch: "wall-top-or-wall-middle" },
    { kind: "wall-row", role: "wall-bottom", layer: "lower", left: 75, middle: 76, right: 77, meaning: "벽 하단부 마감 행. 문의 하단 타일은 이 행을 대체할 수 있다.", mustTouch: "wall-middle" },
  ],
  rows: [
    { section: "ground", coord: "default", lower: [240], upper: [], stack: [], meaning: "템플릿 바탕 풀밭. roof/wall/fence 재료가 아니다." },
    { section: "roof", coord: "upper roof body/right cap", lower: [], upper: [375, 377], stack: [], meaning: "상위 지붕의 안쪽 가로 행. 지붕 길이를 먼저 잡고, 양 끝 대각 지붕 354/355 안쪽에 375 반복 행을 배치한다. 오른쪽 내부 끝만 377로 닫고, 왼쪽 내부 끝도 본체와 같은 타일을 쓴다." },
    { section: "roof", coord: "lower roof front", lower: [405], upper: [], stack: [], meaning: "하위 지붕 최하단부. 지붕 최하단부 lower는 전부 405로 반복하고, 바로 아래에는 wall-top이 와야 한다." },
    { section: "roof", coord: "left upper diagonal", lower: [], upper: [354, 376, 384], stack: [], meaning: "위쪽 왼쪽 대각 지붕. 354/376은 지붕 footprint의 왼쪽 끝이고, 최하단 왼쪽 마감은 405 위 upper 384로 얹는다. 같은 좌표의 lower에는 roof/body/front 타일을 깔지 않는다." },
    { section: "roof", coord: "right upper diagonal", lower: [], upper: [355, 377, 385], stack: [], meaning: "위쪽 오른쪽 대각 지붕. 355/377은 지붕 footprint의 오른쪽 끝이고, 최하단 오른쪽 마감은 405 위 upper 385로 얹는다. 같은 좌표의 lower에는 roof/body/front 타일을 깔지 않는다." },
    { section: "wall", coord: "wall-top row", lower: [15, 16, 17], upper: [], stack: [], meaning: "벽 상단부. 벽 footprint는 지붕 footprint와 같은 x폭으로 잡는다. 354/355 아래쪽에도 벽이 있어야 하며, 지붕과 직접 닿는 행은 무조건 15(left)/16(middle)/17(right)이다." },
    { section: "wall", coord: "wall-middle row", lower: [45, 46, 47], upper: [], stack: [], meaning: "벽 중단부. small_house_01 표준 벽은 정확히 3칸 높이이며 이 행은 두 번째 행이다. 창문은 이 행 위 upper에 규칙적으로 놓는다." },
    { section: "wall", coord: "wall-bottom row", lower: [75, 76, 77], upper: [], stack: [], meaning: "벽 하단부. small_house_01 표준 벽의 정확히 세 번째 행이며, 문을 놓을 때 문 하단 146이 이 칸을 대체한다." },
    { section: "opening", coord: "door", lower: [116, 146], upper: [], stack: [], meaning: "문은 벽 하단부에 설치한다. 상단 116은 문 시작 칸, 하단 146은 wall-bottom 칸을 대체한다. 116/146은 같은 x에 세로로 이어지고, 문 아래 첫 칸부터 길을 연결한다." },
    { section: "opening", coord: "windows", lower: [], upper: [87], stack: [], meaning: "창문 장식. wall-middle 행 위 upper에만 놓는다. 같은 행에 좌우 균형으로 배치하고, 창문끼리는 최소 2칸 이상 띄우며, 문 바로 옆이나 벽 끝에 붙이지 않는다." },
    { section: "fence", coord: "upper boundary", lower: [], upper: [378, 379, 380, 408, 438, 409, 410], stack: [], meaning: "울타리는 집 영역의 상위 레이어 경계다. 생성 순서는 울타리를 먼저 깔고, 그 안에 집을 올린 뒤, 마지막에 길을 깐다. 울타리는 집/지붕/길/창문/문과 절대로 같은 좌표에 겹치지 않는다." },
    { section: "road", coord: "road autotile corners", lower: [390, 392, 450, 452], upper: [], stack: [], meaning: "흙길 모서리. road 영역 모양에 따라 autotile이 자동으로 고른다." },
    { section: "road", coord: "road autotile edges", lower: [391, 420, 422, 451], upper: [], stack: [], meaning: "흙길 가장자리. road 영역의 외곽 경계를 표현한다." },
    { section: "road", coord: "road autotile body", lower: [421], upper: [], stack: [], meaning: "흙길 내부 몸통. 직접 421만 칠하지 말고 road rect를 만든 뒤 autotile shaping으로 390~452를 산출한다. 길 좌표 위에는 어떤 오브젝트도 올리지 않는다." },
  ],
  rules: [
    "이 표는 small_house_01 변형 1의 좌표를 기준으로 한다.",
    "집을 새로 만들 때는 footprint를 먼저 정하고, 각 행을 roof-row/wall-row 문법으로 생성한다. 단순히 기존 집을 여러 번 겹쳐 찍지 않는다.",
    "지붕 길이를 먼저 정하고 roof footprint를 확정한다. 그 다음 354/355는 지붕 footprint의 양 끝에 upper 대각 지붕으로 놓고, 그 안쪽 지붕 행은 375 반복으로 배치하되 오른쪽 내부 끝만 377로 닫는다.",
    "벽 footprint는 지붕 footprint와 같은 x폭으로 파생한다. 354/355가 놓인 지붕 양 끝 아래에도 404/405 지붕 전면부와 wall-top 벽이 이어져야 한다.",
    "지붕 최상단 행은 왼쪽 내부 끝을 별도 캡으로 만들지 않는다. upper 375 반복 / right 377을 유지한다.",
    "지붕 최하단부 lower는 전부 405로 반복한다. 제일 왼쪽 최하단부는 405 위 upper 384, 제일 오른쪽 최하단부는 405 위 upper 385로 마감한다.",
    "354/355는 지붕 footprint의 양 끝 최상단 대각 지붕이고, 376은 왼쪽, 377은 오른쪽으로 기울어진 상위 대각 지붕면이다.",
    "지붕 전면 하단부 405 아래에는 반드시 벽이 있어야 한다. 354/355 아래 x좌표도 예외가 아니며, 지붕 하단부 바로 아래가 wall-top 15/16/17이 아니면 실패다.",
    "위쪽 대각 지붕은 상위 레이어에만 둔다. 같은 좌표의 lower에는 375/404/405 같은 지붕 타일을 깔지 않고 바탕 지형으로 비워 둔다.",
    "지붕과 직접 닿는 벽면은 반드시 wall-top 패턴 15/16/17이어야 한다. 45/46/47 같은 벽 중단부가 지붕 바로 아래 오면 실패다.",
    "벽 행은 left/middle/right 규칙을 따른다: 상단 15/16/17, 중단 45/46/47, 하단 75/76/77.",
    "small_house_01의 벽은 정확히 세로 3칸이다: 1행 wall-top 15/16/17, 2행 wall-middle 45/46/47, 3행 wall-bottom 75/76/77. 더 높게 늘리지 않는다.",
    "창문은 벽 중단부 위 upper 장식으로 놓고, 같은 wall-middle 행에 좌우 균형으로 배치한다. 창문끼리는 최소 2칸 이상 띄운다. 문 바로 옆이나 벽 끝에 붙이지 않는다.",
    "문은 벽 하단부에 설치한다. 문 상단 116은 문 시작 칸이고, 문 하단 146은 wall-bottom 칸을 대체한다. 문 아래 첫 칸부터 길을 연결한다.",
    "생성 순서는 반드시 울타리 → 집 → 길이다. 울타리를 먼저 상위 레이어 경계로 깔고, 그 안에 집을 올린 뒤, 마지막에 길을 깐다.",
    "울타리는 집/지붕/길/창문/문과 절대로 같은 좌표에 겹쳐서는 안 된다. 길과 겹치는 울타리/upper/stack은 비워 출입구를 만든다.",
    "나무/꽃/벤치/표지판 같은 prop 또는 nature object는 집 지형 템플릿에 포함하지 않는다. 260/288/289/290/292/293 계열은 템플릿 생성 대상이 아니다.",
    "240은 roof/wall/fence 재료가 아니라 템플릿 바탕 ground 타일이다.",
    "road는 327/328 벤치 타일이 아니라 390~452 흙길 autotile 코너/가장자리/몸통으로 해석한다. road는 paintAutoRoad/shapeRoadEdges 같은 autotile 경로로 생성해야 한다.",
    "길 위에는 어떠한 오브젝트도 없어야 한다. road lower 타일이 놓인 좌표의 upper는 비어 있어야 하고, lowerTileStacks/upperTileStacks도 없어야 한다.",
  ],
} as const satisfies TerrainTemplateMetadata;
