// Ship(배) 칩셋(tex_easyrpg_chipset_ship) 타일 그림판의 AI 검색용 큐레이션 시맨틱 테이블.
// 6x 업스케일 행 스트립(.omo/evidence/chipset-strips/ship/row-00..15.png) 전수 판독으로 작성했다.
// tileSemanticsDungeon.ts / tileSemanticsInterior.ts 와 동일한 계약: tileset.tileMeta[] 와 별개로
// 관리되는 검색 전용 데이터다. 통행성/레이어 계약은 tilesetHarness 가, 타일별 정밀 라벨은 여기가 담당한다.
//
// 좌표 규약: 30타일/행, ID = 행×30 + 열. 아트가 없는 슬롯(완전 투명 또는 분홍 컬러키 단색)은
// 서술할 대상이 없으므로 엔트리를 만들지 않는다 — scripts/verify-tile-semantics.mts 가 픽셀에서
// 그 목록을 직접 구해 커버리지를 검증한다.
// 판독이 애매한 타일은 단정 대신 형태 서술을 쓰고 "판독보류" 태그를 남겼다(실내 465~467 전례).
//
// 실측: 도화 가능 464칸 전수 서술, 고유 라벨 366개.
// 조립: scripts/build-tile-semantics.mts (수기 편집 대신 이 스크립트로 재생성한다).

import type { CombinedTownTileSemanticEntry } from "./tileSemanticsCombinedTown";

export type ShipTileSemanticEntry = CombinedTownTileSemanticEntry;

function entries(
  indexes: readonly number[],
  label: string,
  role: string,
  passage: "passable" | "solid",
  tags: readonly string[]
): ShipTileSemanticEntry[] {
  return indexes.map((index) => ({ index, label, role, passage, tags: [label, ...tags] }));
}

function one(
  index: number,
  label: string,
  role: string,
  passage: "passable" | "solid",
  tags: readonly string[]
): ShipTileSemanticEntry {
  return { index, label, role, passage, tags: [label, ...tags] };
}

export const SHIP_TILE_SEMANTICS: readonly ShipTileSemanticEntry[] = [
  // ── 0행 (인덱스 0-29) ─────────────────────────────────────────────
  one(0, "바다 물결", "water", "passable", ["바다", "물", "ocean", "물결"]),
  one(1, "파도치는 바다", "water", "passable", ["바다", "파도", "wave", "물"]),
  one(2, "잔잔한 바다", "water", "passable", ["바다", "잔물결", "sea", "물"]),
  one(3, "모래 해변 물가", "sand", "passable", ["모래", "해변", "물가", "beach"]),
  one(4, "모래섬 물웅덩이", "sand", "passable", ["모래", "물", "섬", "웅덩이"]),
  one(5, "모래 해안 물결", "sand", "passable", ["모래", "해안", "바다", "coast"]),
  one(6, "나무 갑판", "floor", "passable", ["갑판", "목재", "deck", "판자"]),
  one(7, "나무 갑판 판자", "floor", "passable", ["갑판", "목재", "deck", "판자"]),
  one(8, "짙은 갈색 나무 벽", "wall", "solid", ["벽", "목재", "wall", "어두운"]),
  one(9, "세로 이음 나무 판", "floor", "passable", ["목재", "세로", "갑판", "wood"]),
  one(10, "가로 이음 나무 판", "floor", "passable", ["목재", "가로", "갑판", "wood"]),
  one(11, "짙은 갈색 나무 벽면", "wall", "solid", ["벽", "목재", "벽면", "어두운"]),
  one(12, "갈색 나무 바닥", "floor", "passable", ["바닥", "목재", "floor", "판자"]),
  one(13, "밝은 나무 바닥", "floor", "passable", ["바닥", "목재", "deck", "밝은"]),
  one(14, "짙은 갈색 나무 바닥", "floor", "passable", ["바닥", "목재", "floor", "판자"]),
  one(15, "밝은 나무 바닥 판", "floor", "passable", ["바닥", "목재", "deck", "밝은"]),
  one(16, "나무 갑판 널", "floor", "passable", ["갑판", "목재", "deck", "목판"]),
  one(17, "세로 이음 나무 판", "floor", "passable", ["목재", "세로", "갑판", "wood"]),
  one(18, "장식 나무 벽면", "wall", "solid", ["벽", "목재", "장식", "패널"]),
  one(19, "두 쪽 문 모양 나무", "wall", "solid", ["벽", "목재", "문", "패널"]),
  one(20, "장식 나무 벽판", "wall", "solid", ["벽", "목재", "장식", "판자"]),
  one(21, "대칭 장식 나무 판", "wall", "solid", ["벽", "목재", "대칭", "패널"]),
  one(22, "대각선 나무 경사", "path", "passable", ["경사", "목재", "대각", "ramp"]),
  one(23, "줄무늬 나무 경사", "path", "passable", ["경사", "목재", "줄무늬", "deck"]),
  one(25, "어두운 나무 경사로", "path", "passable", ["경사", "목재", "ramp", "어두운"]),
  one(26, "뾰족한 어두운 경사 조각", "cliff", "solid", ["경사", "절벽", "어두운", "cliff"]),
  one(27, "어두운 나무 경사로", "path", "passable", ["경사", "목재", "ramp", "경사로"]),
  one(28, "나무 경사 모서리", "path", "passable", ["경사", "목재", "모서리", "corner"]),
  one(29, "어두운 경사 끝 조각", "cliff", "solid", ["경사", "절벽", "끝", "cliff"]),

  // ── 1행 (인덱스 30-59) ─────────────────────────────────────────────
  one(30, "바다 물결", "water", "passable", ["바다", "물", "ocean", "물결"]),
  one(31, "파도치는 바다", "water", "passable", ["바다", "파도", "wave", "물"]),
  one(32, "잔잔한 바다", "water", "passable", ["바다", "잔물결", "sea", "물"]),
  one(33, "모래 자갈 물가", "water", "passable", ["물가", "모래", "바다", "shore"]),
  one(34, "모래 해안 바닷물", "water", "passable", ["해안", "모래", "바다", "water"]),
  one(35, "모래 가장자리 바다", "water", "passable", ["바다", "모래", "가장자리", "edge"]),
  one(36, "짙은 나무 선체 벽", "wall", "solid", ["벽", "목재", "선체", "어두운"]),
  one(37, "짙은 나무 벽", "wall", "solid", ["벽", "목재", "wall", "어두운"]),
  one(38, "짙은 나무 격벽", "wall", "solid", ["벽", "목재", "격벽", "무거운"]),
  one(39, "짙은 나무 벽판", "wall", "solid", ["벽", "목재", "벽판", "어두운"]),
  one(40, "짙은 나무 벽 조각", "wall", "solid", ["벽", "목재", "조각", "패널"]),
  one(41, "짙은 나무 칸막이", "wall", "solid", ["벽", "목재", "칸막이", "partition"]),
  one(42, "나무 바닥", "floor", "passable", ["바닥", "목재", "deck", "floor"]),
  one(43, "밝은 경사 나무", "path", "passable", ["경사", "목재", "밝은", "ramp"]),
  one(44, "대각 나무 경사", "path", "passable", ["경사", "목재", "대각", "slope"]),
  one(45, "급해진 나무 경사", "path", "passable", ["경사", "목재", "급경사", "slope"]),
  one(46, "나무 격자 판", "fence", "solid", ["목재", "격자", "칸막이", "판독보류"]),
  one(47, "나무 격자 장식판", "fence", "solid", ["목재", "격자", "장식", "판독보류"]),
  one(48, "나무 경사 구석", "path", "passable", ["경사", "목재", "구석", "corner"]),
  one(49, "청록 나무 구조물", "awning", "solid", ["천막", "청록", "구조물", "판독보류"]),
  one(50, "청록 줄무늬 천막", "awning", "solid", ["천막", "줄무늬", "청록", "캐노피"]),
  one(51, "청록 천막 가장자리", "awning", "solid", ["천막", "청록", "가장자리", "판독보류"]),
  one(52, "어두운 나무 경사", "path", "passable", ["경사", "목재", "어두운", "ramp"]),
  one(53, "장식 틀 창문", "window", "solid", ["창문", "장식", "틀", "판독보류"]),
  one(54, "비스듬한 나무 경사", "path", "passable", ["경사", "목재", "비스듬", "ramp"]),
  one(55, "긴 나무 경사", "path", "passable", ["경사", "목재", "길다", "slope"]),
  one(56, "짙은 나무 경사", "path", "passable", ["경사", "목재", "어두운", "slope"]),
  one(57, "작은 금속 장식물", "prop", "solid", ["장식", "금속", "작다", "판독보류"]),
  one(58, "대칭 장식 조각", "decoration", "solid", ["장식", "대칭", "조각", "판독보류"]),
  one(59, "대칭 장식 무늬", "decoration", "solid", ["장식", "대칭", "무늬", "판독보류"]),

  // ── 2행 (인덱스 60-89) ─────────────────────────────────────────────
  one(60, "파도 바다", "water", "passable", ["바다", "파도", "water", "물"]),
  one(61, "물결 바다", "water", "passable", ["바다", "물결", "ocean", "물"]),
  one(62, "바다 물", "water", "passable", ["바다", "물", "sea", "wave"]),
  one(63, "어두운 절벽 물가", "water", "passable", ["물가", "절벽", "바다", "shore"]),
  one(64, "물가 벼랑", "water", "passable", ["물가", "벼랑", "바다", "cliff"]),
  one(65, "바위 해안 바다", "water", "passable", ["해안", "바다", "바위", "coast"]),
  one(66, "짙은 갈색 나무 벽", "wall", "solid", ["벽", "목재", "wall", "어두운"]),
  one(67, "아주 짙은 갈색 벽", "wall", "solid", ["벽", "짙은", "갈색", "무늬"]),
  one(68, "짙은 나무 벽면", "wall", "solid", ["벽", "목재", "벽면", "어두운"]),
  one(69, "짙은 나무 벽판", "wall", "solid", ["벽", "목재", "벽판", "패널"]),
  one(70, "아주 짙은 벽", "wall", "solid", ["벽", "짙은", "벽면", "무늬"]),
  one(71, "짙은 나무 칸막이", "wall", "solid", ["벽", "목재", "칸막이", "partition"]),
  one(72, "나무 장식 구조물", "prop", "solid", ["구조물", "목재", "장식", "판독보류"]),
  one(73, "나무 창문", "window", "solid", ["창문", "목재", "창틀", "window"]),
  one(74, "대각 격자 나무", "path", "passable", ["격자", "목재", "대각", "경사"]),
  one(75, "경사 격자 나무", "path", "passable", ["격자", "목재", "경사", "slope"]),
  one(76, "장식 나무 격자판", "fence", "solid", ["목재", "격자", "장식", "판독보류"]),
  one(77, "테두리 장식 나무", "wall", "solid", ["나무", "테두리", "장식", "가장자리"]),
  one(78, "어두운 나무 격자", "wall", "solid", ["나무", "격자", "어두운", "무늬"]),
  one(79, "나무 경사 구석", "path", "passable", ["경사", "목재", "구석", "corner"]),
  one(80, "대칭 장식 조각", "decoration", "solid", ["장식", "대칭", "조각", "판독보류"]),
  one(81, "어두운 나무 경사", "path", "passable", ["경사", "목재", "어두운", "ramp"]),
  one(82, "어두운 나무 격자 무늬", "wall", "solid", ["나무", "격자", "어두운", "무늬"]),
  one(83, "청록 줄무늬 천막", "awning", "solid", ["천막", "줄무늬", "청록", "판독보류"]),
  one(84, "나무 경사 구조물", "path", "passable", ["경사", "목재", "구조물", "slope"]),
  one(85, "나무 경사 구조", "path", "passable", ["경사", "목재", "구조", "slope"]),
  one(86, "가느다란 기둥 꼭대기", "pillar", "solid", ["기둥", "꼭대기", "가늘다", "판독보류"]),
  one(87, "가느다란 기둥 끝", "pillar", "solid", ["기둥", "끝", "가늘다", "판독보류"]),
  one(88, "벽 꼭대기 장식", "fence", "solid", ["벽", "꼭대기", "장식", "판독보류"]),
  one(89, "벽 모서리 장식", "fence", "solid", ["벽", "모서리", "장식", "판독보류"]),

  // ── 3행 (인덱스 90-119) ─────────────────────────────────────────────
  one(90, "바다 물결", "water", "passable", ["바다", "물", "ocean", "물결"]),
  one(91, "파도치는 바다", "water", "passable", ["바다", "파도", "wave", "물"]),
  one(92, "잔잔한 바다", "water", "passable", ["바다", "잔물결", "sea", "물"]),
  one(93, "물가 모래 해안", "water", "passable", ["물가", "모래", "해안", "shore"]),
  one(94, "아래 물가 해안", "water", "passable", ["물가", "해안", "바다", "coast"]),
  one(95, "물가 모래 바다", "water", "passable", ["물가", "모래", "바다", "shore"]),
  one(96, "짙은 나무 벽", "wall", "solid", ["벽", "목재", "wall", "어두운"]),
  one(97, "짙은 갈색 벽", "wall", "solid", ["벽", "짙은", "갈색", "무늬"]),
  one(98, "짙은 나무 벽면", "wall", "solid", ["벽", "목재", "벽면", "어두운"]),
  one(99, "짙은 나무 벽판", "wall", "solid", ["벽", "목재", "벽판", "패널"]),
  one(100, "짙은 나무 격벽", "wall", "solid", ["벽", "목재", "격벽", "어두운"]),
  one(101, "짙은 나무 칸막이", "wall", "solid", ["벽", "목재", "칸막이", "partition"]),
  one(102, "나무 장식 구조물", "prop", "solid", ["구조물", "목재", "장식", "판독보류"]),
  one(103, "나무 창문", "window", "solid", ["창문", "목재", "창틀", "window"]),
  one(104, "나무 기둥 벽면", "wall", "solid", ["기둥", "목재", "벽", "패널"]),
  one(105, "나무 기둥 판", "wall", "solid", ["기둥", "목재", "판자", "패널"]),
  one(106, "높은 나무 벽", "wall", "solid", ["벽", "목재", "높다", "기둥"]),
  one(107, "높은 나무 기둥", "pillar", "solid", ["기둥", "목재", "높다", "마스트"]),
  one(108, "나무 장식 구조물", "prop", "solid", ["구조물", "목재", "장식", "판독보류"]),
  one(109, "대각 격자 나무 판", "path", "passable", ["격자", "목재", "대각", "경사"]),
  one(110, "장식 틀 구조물", "prop", "solid", ["구조물", "장식", "틀", "판독보류"]),
  one(111, "경사 격자 나무 판", "path", "passable", ["격자", "목재", "경사", "slope"]),
  one(112, "나무 장식 구조물", "prop", "solid", ["구조물", "목재", "장식", "판독보류"]),
  one(113, "청록 줄무늬 천막", "awning", "solid", ["천막", "줄무늬", "청록", "판독보류"]),
  one(114, "비스듬한 나무 경사", "path", "passable", ["경사", "목재", "비스듬", "ramp"]),
  one(115, "어두운 나무 경사", "path", "passable", ["경사", "목재", "어두운", "slope"]),
  one(116, "긴 나무 경사", "path", "passable", ["경사", "목재", "길다", "ramp"]),
  one(117, "어두운 경사 조각", "cliff", "solid", ["경사", "절벽", "어두운", "cliff"]),
  one(118, "나무 경사판", "path", "passable", ["경사", "목재", "판자", "ramp"]),
  one(119, "작은 장식 문양", "prop", "solid", ["장식", "문양", "작다", "판독보류"]),

  // ── 4행 (인덱스 120-149) ─────────────────────────────────────────────
  one(120, "짙은 파도 바닷물", "water", "passable", ["물", "wave", "sea", "깊은"]),
  one(121, "짙은 물결 바닷물", "water", "passable", ["바다", "파도", "deep", "ocean"]),
  one(122, "짙은 파도 바닷물", "water", "passable", ["물", "wave", "sea"]),
  one(123, "옅은 파도 바닷물", "water", "passable", ["물결", "shallow", "sea"]),
  one(124, "옅은 물결 바닷물", "water", "passable", ["바다", "foam", "wave"]),
  one(125, "옅은 파도 바닷물", "water", "passable", ["물", "sparkle", "sea"]),
  one(126, "중앙 어두운 반점 나무 갑판", "prop", "solid", ["갑판", "목재", "어둠", "판독보류"]),
  one(127, "나무 갑판 널빤지", "floor", "passable", ["데크", "wood", "판자"]),
  one(128, "어두운 개구부 목재 틀", "wall", "solid", ["목재", "어둠", "틀", "판독보류"]),
  one(129, "나무 갑판 널빤지", "floor", "passable", ["데크", "planks", "wood"]),
  one(130, "나무 갑판 널빤지", "floor", "passable", ["데크", "deck", "널빤지"]),
  one(131, "어두운 개구부 목재 틀", "wall", "solid", ["목재", "문", "개구", "판독보류"]),
  one(132, "무늬 나무 갑판", "floor", "passable", ["데크", "deck", "pattern"]),
  one(133, "나무 판자 바닥", "floor", "passable", ["갑판", "planks", "wood"]),
  one(134, "나무 판자 바닥", "floor", "passable", ["데크", "deck", "목재"]),
  one(135, "나무 판자 바닥", "floor", "passable", ["데크", "planks", "deck"]),
  one(136, "가장자리 음영 나무 판자", "floor", "passable", ["갑판", "shade", "목재"]),
  one(137, "금빛 장식이 섞인 나무", "decoration", "solid", ["갑판", "wood", "장식"]),
  one(138, "줄무늬 천 가장자리 목재", "awning", "solid", ["천", "stripes", "판독보류"]),
  one(139, "금빛 장식 나무", "decoration", "solid", ["갑판", "ornament", "목재"]),
  one(140, "금빛 목재 격자 난간", "fence", "solid", ["격자", "grille", "판독보류"]),
  one(141, "금빛 장식 나무", "decoration", "solid", ["갑판", "장식", "lantern"]),
  one(142, "줄무늬 천 목재 장식", "awning", "solid", ["천막", "cloth", "판독보류"]),
  one(143, "금빛 띠 장식 목재 판넬", "decoration", "solid", ["장식", "border", "나무"]),
  one(144, "작은 기둥 조형물", "pillar", "solid", ["기둥", "statue", "판독보류"]),
  one(145, "작은 기둥 조형물", "pillar", "solid", ["조형", "pillar", "판독보류"]),
  one(146, "비스듬한 목재 곡선 조각", "prop", "solid", ["곡선", "curved", "판독보류"]),
  one(147, "비스듬한 목재 이음매", "floor", "passable", ["갑판", "seam", "대각"]),
  one(148, "작은 다색 조형물", "prop", "solid", ["조형", "figure", "판독보류"]),
  one(149, "떠 있는 나무 판자 조각", "prop", "solid", ["판자", "plank", "덩어리"]),

  // ── 5행 (인덱스 150-179) ─────────────────────────────────────────────
  one(150, "짙은 파도 바닷물", "water", "passable", ["물", "sea", "wave"]),
  one(151, "짙은 물결 바닷물", "water", "passable", ["바다", "deep", "파도"]),
  one(152, "짙은 파도 바닷물", "water", "passable", ["물결", "ocean", "wave"]),
  one(153, "옅은 파도 바닷물", "water", "passable", ["물", "shallow", "sea"]),
  one(154, "옅은 물결 바닷물", "water", "passable", ["바다", "foam", "파도"]),
  one(155, "옅은 파도 바닷물", "water", "passable", ["물결", "wave", "sea"]),
  one(156, "목재 위 어두운 바닥", "wall", "solid", ["벽", "wood", "어둠", "판독보류"]),
  one(157, "목재 상단 어두운 하단", "wall", "solid", ["경계", "boundary", "판독보류"]),
  one(158, "목재 남쪽 어두움", "wall", "solid", ["경계", "edge", "판독보류"]),
  one(159, "목재 서쪽 어두운 벽", "wall", "solid", ["경계", "wall", "판독보류"]),
  one(160, "목재와 어둠 경사 벽", "wall", "solid", ["경사", "slope", "판독보류"]),
  one(161, "어둠과 우측 목재 벽", "wall", "solid", ["벽", "wood", "판독보류"]),
  one(162, "비스듬한 목재 격자", "decoration", "solid", ["격자", "lattice", "판독보류"]),
  one(163, "비스듬한 목재 사선 무늬", "decoration", "solid", ["사선", "diagonal", "판독보류"]),
  one(164, "비스듬한 목재 격자", "decoration", "solid", ["격자", "lattice", "무늬"]),
  one(165, "위 목재 아래 금빛 무늬", "decoration", "solid", ["금", "decor", "판독보류"]),
  one(166, "비스듬한 목재 격자", "decoration", "solid", ["무늬", "pattern", "판독보류"]),
  one(167, "금빛 띠 목재 무늬", "decoration", "solid", ["띠", "band", "판독보류"]),
  one(168, "거친 잔물결 바닷물", "water", "passable", ["물", "net", "dot", "판독보류"]),
  one(169, "거친 잔물결 바닷물", "water", "passable", ["바다", "texture", "파도"]),
  one(170, "거친 잔물결 바닷물", "water", "passable", ["물결", "deep", "sea"]),
  one(171, "거친 잔물결 바닷물", "water", "passable", ["물", "wave", "surface"]),
  one(172, "금빛 모서리 장식 목재", "decoration", "solid", ["금", "corner", "장식"]),
  one(173, "금빛 모서리 장식 목재", "decoration", "solid", ["목재", "ornament", "모서리"]),
  one(174, "비스듬한 목재 곡선 조각", "prop", "solid", ["곡선", "hull", "판독보류"]),
  one(175, "비스듬한 목재 격자 무늬", "prop", "solid", ["격자", "lattice", "판독보류"]),
  one(176, "비스듬한 목재 곡선 조각", "prop", "solid", ["곡선", "curved", "판독보류"]),
  one(177, "비스듬한 목재 곡선 조각", "prop", "solid", ["목재", "curve", "판독보류"]),
  one(178, "비스듬한 목재 곡선 조각", "prop", "solid", ["곡선", "hull", "조각"]),

  // ── 6행 (인덱스 180-209) ─────────────────────────────────────────────
  one(180, "짙은 파도 바닷물", "water", "passable", ["물", "wave", "deep"]),
  one(181, "짙은 물결 바닷물", "water", "passable", ["바다", "sea", "파도"]),
  one(182, "짙은 파도 바닷물", "water", "passable", ["물결", "ocean", "wave"]),
  one(183, "옅은 파도 바닷물", "water", "passable", ["물", "shallow", "sea"]),
  one(184, "옅은 물결 바닷물", "water", "passable", ["파도", "foam", "바다"]),
  one(185, "옅은 파도 바닷물", "water", "passable", ["물결", "wave", "sea"]),
  one(186, "목재 위 어두운 바닥", "wall", "solid", ["벽", "wood", "어둠", "판독보류"]),
  one(187, "새까만 어두운 벽", "wall", "solid", ["흑", "void", "어둠"]),
  one(188, "우측 목재 어두운 벽", "wall", "solid", ["경계", "boundary", "판독보류"]),
  one(189, "좌측 목재 어두운 벽", "wall", "solid", ["벽", "edge", "판독보류"]),
  one(190, "새까만 어두운 벽", "wall", "solid", ["검정", "void", "어둠"]),
  one(191, "어둠과 우측 목재 벽", "wall", "solid", ["벽", "wood", "판독보류"]),
  one(192, "금빛 테 목재 문", "door", "solid", ["문", "door", "금테", "판독보류"]),
  one(193, "세로 결 무늬 나무 갑판", "floor", "passable", ["데크", "grain", "널빤지"]),
  one(194, "비스듬한 목재 금빛 격자", "decoration", "solid", ["격자", "lattice", "금"]),
  one(195, "비스듬한 목재 사선 무늬", "decoration", "solid", ["사선", "diagonal", "무늬"]),
  one(196, "비스듬한 목재 격자", "decoration", "solid", ["목재", "lattice", "대각"]),
  one(197, "금빛 목재 격자 무늬", "decoration", "solid", ["격자", "pattern", "판독보류"]),
  one(198, "금빛 목재 짜임 무늬", "decoration", "solid", ["짜임", "weave", "판독보류"]),
  one(199, "금빛 목재 격자 무늬", "decoration", "solid", ["무늬", "lattice", "금"]),
  one(200, "금빛 목재 짜임 무늬", "decoration", "solid", ["짜임", "pattern", "판독보류"]),
  one(201, "금빛 목재 격자 무늬", "decoration", "solid", ["격자", "weave", "금빛"]),
  one(202, "가로 목재 격자 난간", "fence", "solid", ["격자", "fence", "난간"]),
  one(203, "금빛 격자 망", "fence", "solid", ["격자", "grille", "판독보류"]),
  one(204, "받침대 작은 등불", "prop", "solid", ["등불", "lamp", "받침"]),
  one(205, "담색 덩어리 더미", "prop", "solid", ["더미", "heap", "판독보류"]),
  one(206, "작은 목재 조각", "prop", "solid", ["목재", "chip", "조각"]),
  one(207, "비스듬한 목재 격자", "decoration", "solid", ["격자", "lattice", "무늬"]),
  one(208, "비스듬한 목재 곡선 조각", "prop", "solid", ["곡선", "hull", "조각"]),
  one(209, "비스듬한 목재 곡선 조각", "prop", "solid", ["곡선", "curve", "판독보류"]),

  // ── 7행 (인덱스 210-239) ─────────────────────────────────────────────
  one(210, "짙은 파도 바닷물", "water", "passable", ["물", "wave", "바다"]),
  one(211, "짙은 물결 바닷물", "water", "passable", ["바다", "deep", "파도"]),
  one(212, "짙은 파도 바닷물", "water", "passable", ["물결", "sea", "ocean"]),
  one(213, "옅은 파도 바닷물", "water", "passable", ["물", "shallow", "sea"]),
  one(214, "옅은 물결 바닷물", "water", "passable", ["파도", "foam", "바다"]),
  one(215, "옅은 파도 바닷물", "water", "passable", ["물결", "wave", "sea"]),
  one(216, "목재 북쪽 경계 어두움", "wall", "solid", ["경계", "boundary", "판독보류"]),
  one(217, "목재 남쪽 경계 어두움", "wall", "solid", ["경계", "edge", "판독보류"]),
  one(218, "목재 동쪽 경계 어두움", "wall", "solid", ["경계", "boundary", "판독보류"]),
  one(219, "목재 서쪽 경계 어두움", "wall", "solid", ["벽", "edge", "판독보류"]),
  ...entries([220, 221], "목재 모서리 어두움", "wall", "solid", ["모서리", "corner", "판독보류"]),
  one(222, "금빛 테 나무 판자", "floor", "passable", ["갑판", "trim", "금테"]),
  one(223, "세로 결 금빛 나무 갑판", "floor", "passable", ["데크", "grain", "널빤지"]),
  one(224, "짜임 목재 격자 무늬", "decoration", "solid", ["짜임", "weave", "판독보류"]),
  one(225, "짜임 목재 격자 무늬", "decoration", "solid", ["격자", "lattice", "무늬"]),
  one(226, "줄무늬 천 장식 목재", "awning", "solid", ["천", "stripes", "판독보류"]),
  one(227, "금빛 장식 곡선 목재", "decoration", "solid", ["금", "decor", "판독보류"]),
  one(228, "금빛 목재 격자 무늬", "fence", "solid", ["격자", "lattice", "판독보류"]),
  one(229, "목재 격자 무늬", "fence", "solid", ["격자", "weave", "판독보류"]),
  one(230, "금빛 목재 격자 무늬", "fence", "solid", ["무늬", "grille", "판독보류"]),
  one(231, "금빛 목재 격자 무늬", "fence", "solid", ["격자", "lattice", "금"]),
  one(232, "색무늬 목재 문 패널", "door", "solid", ["문", "panel", "판독보류"]),
  one(234, "위 목재 아래 어두운 축", "prop", "solid", ["목재", "beam", "판독보류"]),
  one(235, "금빛 상단 목재 조각", "prop", "solid", ["목재", "gold", "조각"]),
  one(236, "매달린 금빛 장식", "decoration", "solid", ["장식", "hanging", "판독보류"]),
  one(237, "모서리 목재 금빛 조각", "prop", "solid", ["목재", "corner", "조각"]),
  one(238, "금빛 곡선 장식 목재", "decoration", "solid", ["금", "decor", "곡선"]),
  one(239, "금빛 줄무늬 천", "awning", "solid", ["천", "stripes", "장식"]),

  // ── 8행 (인덱스 240-269) ─────────────────────────────────────────────
  one(240, "거친 점 모래땅", "sand", "passable", ["sand", "해변", "바닥"]),
  one(241, "고운 노란 모래", "sand", "passable", ["sand", "모래사장", "노랑"]),
  one(242, "밝은 모래사장", "sand", "passable", ["sand", "해변", "밝은흙"]),
  one(243, "잔디 고립 덩이", "terrain", "passable", ["grass", "풀밭", "고립"]),
  one(244, "잔디 한가운데", "terrain", "passable", ["grass", "풀밭", "중심"]),
  one(245, "잔디 오목 모서리", "terrain", "passable", ["grass", "안쪽모서리", "경계"]),
  one(246, "왼쪽 세로줄 갑판", "floor", "passable", ["deck", "나무", "세로줄눈"]),
  one(247, "가로 널 갑판", "floor", "passable", ["deck", "널빤지", "가로결"]),
  one(248, "오른쪽 세로줄 갑판", "floor", "passable", ["deck", "나무", "우측"]),
  one(249, "작은 벽돌 갑판", "floor", "passable", ["deck", "벽돌무늬", "나무판"]),
  one(250, "두 쪽 세로 갑판", "floor", "passable", ["deck", "세로널", "이음"]),
  one(251, "이음새 가로 갑판", "floor", "passable", ["deck", "가로결", "중앙선"]),
  one(252, "빗금 선실벽", "wall", "solid", ["cabin", "선실", "모서리"]),
  one(253, "왼쪽 검은 선실벽", "wall", "solid", ["cabin", "가로널", "어둠"]),
  one(254, "짙은 가로 선실판", "floor", "passable", ["cabin", "마루", "가로널"]),
  one(255, "짙은 가로 널바닥", "floor", "passable", ["wood", "마루", "선실바닥"]),
  one(256, "갑판 관통 돛대", "pillar", "solid", ["mast", "돛대", "기둥"]),
  one(257, "회색 둥근 금속물", "prop", "solid", ["metal", "회색", "판독보류"]),
  one(259, "회색 쇠닻", "prop", "solid", ["anchor", "닻", "선구"]),
  one(260, "좌하 대각 들보", "ship", "solid", ["beam", "사선", "목재"]),
  one(261, "작은 나무 끝촉", "prop", "solid", ["peg", "말뚝", "판독보류"]),
  one(262, "우하 대각 들보", "ship", "solid", ["beam", "사선", "굵은목"]),
  one(263, "감긴 밧줄 더미", "rope", "solid", ["coil", "로프", "선구"]),
  one(264, "검은 사각 면", "decoration", "solid", ["black", "어둠", "판독보류"]),
  one(265, "굵은 대각 선체판", "ship", "solid", ["hull", "사선", "판재"]),
  one(266, "북서 삼각 선체", "ship", "solid", ["hull", "모서리", "분홍키"]),
  one(267, "북동 삼각 선체", "ship", "solid", ["hull", "모서리", "상부"]),
  one(268, "좌상 대각 선체", "ship", "solid", ["hull", "사선", "판재"]),
  one(269, "남서 삼각 선체", "ship", "solid", ["hull", "모서리", "하부"]),

  // ── 9행 (인덱스 270-299) ─────────────────────────────────────────────
  one(270, "거친 점 모래땅", "sand", "passable", ["sand", "해변", "바닥"]),
  one(271, "고운 노란 모래", "sand", "passable", ["sand", "모래사장", "노랑"]),
  one(272, "밝은 모래사장", "sand", "passable", ["sand", "해변", "밝은흙"]),
  one(273, "잔디 북쪽 경계", "terrain", "passable", ["grass", "북측", "모래경계"]),
  one(274, "잔디 한가운데", "terrain", "passable", ["grass", "풀밭", "중심"]),
  one(275, "잔디 북동 모서리", "terrain", "passable", ["grass", "북동", "경계"]),
  one(276, "왼쪽 벽돌 갑판", "floor", "passable", ["deck", "벽돌무늬", "좌측"]),
  one(277, "가운데 가로 갑판", "floor", "passable", ["deck", "널빤지", "중앙"]),
  one(278, "오른쪽 벽돌 갑판", "floor", "passable", ["deck", "벽돌무늬", "우측"]),
  one(279, "잔벽돌 나무판", "floor", "passable", ["deck", "작은벽돌", "나무"]),
  one(280, "넓적 세로 갑판", "floor", "passable", ["deck", "세로널", "넓은판"]),
  one(281, "가로결 나무판", "floor", "passable", ["deck", "가로결", "마루"]),
  one(282, "금줄 문턱 선실벽", "wall", "solid", ["cabin", "문턱", "선실"]),
  one(283, "두 짝 나무 선실문", "door", "solid", ["door", "쌍문", "선실"]),
  one(284, "짙은 나무 선실벽", "wall", "solid", ["cabin", "벽", "가로널"]),
  one(285, "왼쪽 갑판 가장자리", "floor", "passable", ["deck", "가장자리", "검은테"]),
  one(286, "오른쪽 갑판 널", "floor", "passable", ["deck", "널빤지", "우측"]),
  one(287, "갑판 위 포탄", "floor", "passable", ["cannonball", "포탄", "갑판"]),
  one(288, "붉은 삼각 깃발", "banner", "solid", ["flag", "페넌트", "빨강"]),
  one(289, "가는 대각 가로대", "ship", "solid", ["spar", "사선", "얇은목"]),
  one(290, "짧은 나무 말뚝", "prop", "solid", ["post", "그루터기", "판독보류"]),
  one(291, "가로대 달린 돛대", "ship", "solid", ["mast", "야드암", "십자"]),
  one(292, "가로 돛대 활대", "ship", "solid", ["yard", "가로대", "활대"]),
  one(293, "남서 대각 판재", "ship", "solid", ["hull", "사선", "하부"]),
  one(294, "나무 위 검은 구멍", "decoration", "solid", ["hatch", "어둠", "판독보류"]),
  one(295, "엇갈린 은색 검", "decoration", "solid", ["swords", "교차", "무기"]),
  one(296, "굵은 우상 선체판", "ship", "solid", ["hull", "사선", "판재"]),
  one(297, "북서 작은 판조각", "ship", "solid", ["hull", "조각", "모서리"]),
  one(298, "늘어진 갈색 밧줄", "rope", "solid", ["rope", "로프", "세로줄"]),
  one(299, "원형 나무 단면", "barrel", "solid", ["log", "토막", "나이테"]),

  // ── 10행 (인덱스 300-329) ────────────────────────────────────────────
  one(300, "거친 점 모래땅", "sand", "passable", ["sand", "해변", "바닥"]),
  one(301, "고운 노란 모래", "sand", "passable", ["sand", "모래사장", "노랑"]),
  one(302, "밝은 모래사장", "sand", "passable", ["sand", "해변", "밝은흙"]),
  one(303, "잔디 동쪽 경계", "terrain", "passable", ["grass", "동측", "모래경계"]),
  one(304, "잔디 한가운데", "terrain", "passable", ["grass", "풀밭", "중심"]),
  one(305, "잔디 동측 가장자리", "terrain", "passable", ["grass", "동쪽", "경계"]),
  one(306, "왼쪽 각진 갑판", "floor", "passable", ["deck", "벽돌무늬", "좌측"]),
  one(307, "가운데 벽돌 갑판", "floor", "passable", ["deck", "벽돌무늬", "중앙"]),
  one(308, "오른쪽 각진 갑판", "floor", "passable", ["deck", "벽돌무늬", "우측"]),
  one(309, "사각 나무벽돌", "floor", "passable", ["deck", "사각블록", "나무"]),
  one(310, "널찍한 나무판", "floor", "passable", ["deck", "넓은널", "마루"]),
  one(311, "가로 이음 나무판", "floor", "passable", ["deck", "가로결", "이음"]),
  one(312, "둥근 윗면 나무벽", "wall", "solid", ["cabin", "곡선", "판독보류"]),
  one(313, "검은 창 선실벽", "window", "solid", ["window", "선실", "창구멍"]),
  one(314, "주황 모 깎인 벽", "wall", "solid", ["cabin", "모서리", "주황"]),
  one(315, "왼쪽 굽은 선체", "ship", "solid", ["hull", "곡선", "좌현"]),
  one(316, "가운데 굽은 선체", "ship", "solid", ["hull", "곡선", "선측"]),
  one(317, "검은 모 굽은 널", "ship", "solid", ["hull", "곡선", "가장자리"]),
  one(318, "붉은 금장 깃발", "banner", "solid", ["flag", "금장", "빨강"]),
  one(319, "가는 사선 버팀대", "ship", "solid", ["brace", "사선", "얇은목"]),
  one(320, "얇은 대각 목재", "ship", "solid", ["spar", "사선", "버팀"]),
  one(321, "나란한 두 돛대", "ship", "solid", ["mast", "쌍기둥", "세로대"]),
  one(322, "사선 가는 들보", "ship", "solid", ["beam", "사선", "가는목"]),
  one(323, "대각 널빤지 조각", "ship", "solid", ["plank", "사선", "조각"]),
  one(324, "왼쪽 향한 대포", "machine", "solid", ["cannon", "포신", "좌향"]),
  one(325, "오른쪽 향한 대포", "machine", "solid", ["cannon", "포차", "우향"]),
  one(326, "정면 포구 대포", "machine", "solid", ["cannon", "포구", "정면"]),
  one(327, "회색 둥근 포탄", "prop", "solid", ["cannonball", "포탄", "구체"]),
  one(328, "가로 나무 살창", "decoration", "solid", ["grate", "가로살", "판독보류"]),
  one(329, "은밑 갈색 원통", "barrel", "solid", ["barrel", "원통", "판독보류"]),

  // ── 11행 (인덱스 330-359) ────────────────────────────────────────────
  one(330, "거친 점 모래땅", "sand", "passable", ["sand", "해변", "바닥"]),
  one(331, "고운 노란 모래", "sand", "passable", ["sand", "모래사장", "노랑"]),
  one(332, "밝은 모래사장", "sand", "passable", ["sand", "해변", "밝은흙"]),
  one(333, "잔디 남서 모서리", "terrain", "passable", ["grass", "남서", "모래경계"]),
  one(334, "잔디 한가운데", "terrain", "passable", ["grass", "풀밭", "중심"]),
  one(335, "잔디 남동 경계", "terrain", "passable", ["grass", "남동", "모래변"]),
  one(336, "왼쪽 아래 갑판", "floor", "passable", ["deck", "하단", "좌측"]),
  one(337, "가운데 아래 갑판", "floor", "passable", ["deck", "하단", "중앙"]),
  one(338, "오른쪽 아래 갑판", "floor", "passable", ["deck", "하단", "우측"]),
  one(339, "하단 벽돌 갑판", "floor", "passable", ["deck", "벽돌무늬", "하단"]),
  one(340, "하단 세로 갑판", "floor", "passable", ["deck", "세로널", "하단"]),
  one(341, "하단 가로 갑판", "floor", "passable", ["deck", "가로결", "하단"]),
  one(342, "창틀 난 선실벽", "window", "solid", ["window", "창틀", "선실"]),
  one(343, "문구멍 선실벽", "door", "solid", ["door", "개구부", "선실"]),
  one(344, "역브이 선실 천장", "roof", "solid", ["gable", "박공", "선실"]),
  one(345, "검은 세로 문틀", "door", "solid", ["doorframe", "문틀", "세로홈"]),
  one(346, "문 안쪽 어둠", "door", "solid", ["doorway", "어둠", "개구"]),
  one(347, "가로 널 선체판", "floor", "passable", ["plank", "가로널", "선체"]),
  one(348, "붉은 금장 깃발", "banner", "solid", ["flag", "금장", "빨강"]),
  one(349, "사선 나무 버팀", "ship", "solid", ["brace", "사선", "목재"]),
  one(350, "굵은 사선 목재", "ship", "solid", ["beam", "사선", "굵은목"]),
  one(351, "회색 날 세로막대", "prop", "solid", ["pole", "금속날", "판독보류"]),
  one(352, "대각 버팀 널판", "ship", "solid", ["brace", "사선", "널판"]),
  one(353, "사선 선체 널판", "ship", "solid", ["hull", "사선", "널판"]),
  one(354, "좌향 포차 대포", "machine", "solid", ["cannon", "포차", "좌향"]),
  one(355, "우향 포신 대포", "machine", "solid", ["cannon", "포신", "우향"]),
  one(356, "정면 포구만", "machine", "solid", ["cannon", "포구", "머즐"]),
  one(357, "포미 나무 포차", "machine", "solid", ["cannon", "포미", "포차"]),
  one(358, "초록 풍경 나무액자", "decoration", "solid", ["picture", "액자", "풍경"]),
  one(359, "주황 불빛 나무액자", "decoration", "solid", ["picture", "액자", "불빛"]),

  // ── 12행 (인덱스 360-389) ────────────────────────────────────────────
  one(360, "갈색 흙바닥", "terrain", "passable", ["dirt", "흙", "지형"]),
  one(361, "노란 모래바닥", "sand", "passable", ["sand", "모래", "해변"]),
  one(362, "모서리 모래 흙바닥", "terrain", "passable", ["dirt", "sand corner", "모서리"]),
  one(366, "테두리 회색 석벽", "wall", "solid", ["stone", "석조", "테두리"]),
  one(367, "회색 석재 벽돌", "wall", "solid", ["brick", "석벽", "회색"]),
  one(368, "회색 석재 무늬벽", "wall", "solid", ["stone", "무늬", "벽돌"]),
  one(369, "나무 사각 창틀", "window", "solid", ["window", "창", "목틀"]),
  one(370, "창 너머 어둠", "window", "solid", ["dark", "내부", "검정"]),
  one(371, "십자 창살 창문", "window", "solid", ["window", "창살", "십자"]),
  one(372, "세로 널빤지 벽", "wall", "solid", ["wood", "벽판", "세로결"]),
  one(373, "나무 벽널 가운데", "wall", "solid", ["wood", "선실벽", "널빤지"]),
  one(374, "나무 벽널 오른쪽", "wall", "solid", ["wood", "벽면", "우측"]),
  one(375, "나무벽 세로 이음", "wall", "solid", ["wood", "이음새", "홈"]),
  one(376, "어두운 아궁이", "wall", "solid", ["hearth", "화덕", "벽감"]),
  one(377, "나무벽 왼쪽 이음", "wall", "solid", ["wood", "이음새", "좌측"]),
  one(378, "밝은 세로 나무결", "wall", "solid", ["wood", "밝은널", "세로"]),
  one(379, "사각 나무 상자", "crate", "solid", ["crate", "궤짝", "화물"]),
  one(380, "왼쪽 사선 나무판", "decoration", "solid", ["diagonal", "각재", "분홍배경"]),
  one(381, "오른쪽 사선 나무판", "decoration", "solid", ["diagonal", "각재", "분홍배경"]),
  one(382, "나무 서랍 가구", "furniture", "solid", ["drawer", "서랍장", "협탁"]),
  one(383, "세로 나무판 기둥", "pillar", "solid", ["pillar", "목재", "수직"]),
  one(384, "책이 꽂힌 책장", "shelf", "solid", ["bookshelf", "서적", "선반"]),
  one(385, "둥근 나무 술통", "barrel", "solid", ["barrel", "통", "화물"]),
  one(386, "흰 도자기 항아리", "decoration", "solid", ["vase", "도기", "항아리"]),
  one(387, "둥근 나무 탁자", "furniture", "solid", ["table", "원탁", "가구"]),
  one(388, "바다 그림 왼액자", "decoration", "solid", ["painting", "액자", "풍경"]),
  one(389, "바다 그림 오른액자", "decoration", "solid", ["painting", "액자", "풍경"]),

  // ── 13행 (인덱스 390-419) ────────────────────────────────────────────
  one(390, "흙 북서 모래사면", "terrain", "passable", ["dirt", "sand", "북서"]),
  one(391, "흙 북쪽 모래경계", "terrain", "passable", ["dirt", "sand edge", "북쪽"]),
  one(392, "흙 북동 모래사면", "terrain", "passable", ["dirt", "sand", "북동"]),
  one(396, "석벽 왼쪽 상단테", "wall", "solid", ["stone", "좌상", "테두리"]),
  one(397, "석벽 상단 그림자", "wall", "solid", ["stone", "상단", "음영"]),
  one(398, "석벽 오른쪽 상단테", "wall", "solid", ["stone", "우상", "테두리"]),
  one(399, "창틀 좌상단 모서리", "window", "solid", ["window", "창틀", "좌상"]),
  one(400, "창틀 상단 가로대", "window", "solid", ["window", "가로목", "상단"]),
  one(401, "창틀 우상단 모서리", "window", "solid", ["window", "창틀", "우상"]),
  one(402, "짙은 세로 나무벽", "wall", "solid", ["wood", "암색벽", "세로"]),
  one(403, "평평한 나무 벽면", "wall", "solid", ["wood", "매끈", "벽판"]),
  one(404, "나무벽 오른쪽면", "wall", "solid", ["wood", "우측벽", "선실"]),
  one(405, "나무 겹벽 이음", "wall", "solid", ["wood", "이음", "겹판"]),
  one(406, "가로 나무 마루", "floor", "passable", ["floor", "갑판", "가로결"]),
  one(407, "마루 우측 둥근테", "floor", "passable", ["floor", "곡면", "우측"]),
  one(408, "사선 들보 나무판", "decoration", "solid", ["beam", "사선", "목재"]),
  one(409, "굵은 사선 각재", "decoration", "solid", ["diagonal", "각재", "분홍배경"]),
  one(410, "얇은 오른쪽 사선", "decoration", "solid", ["diagonal", "얇은판", "우측"]),
  one(411, "얇은 왼쪽 사선", "decoration", "solid", ["diagonal", "얇은판", "좌측"]),
  one(412, "반대 굵은 사선각", "decoration", "solid", ["diagonal", "각재", "분홍배경"]),
  one(413, "사선 들보 오른판", "decoration", "solid", ["beam", "사선", "우측"]),
  one(414, "책장 윗칸 선반", "shelf", "solid", ["bookshelf", "상단", "서적"]),
  one(415, "열린 나무통 윗면", "barrel", "solid", ["barrel", "윗면", "통"]),
  one(416, "흰 베개 침대", "bed", "solid", ["bed", "침구", "베개"]),
  one(417, "작은 둥근 나무덩이", "prop", "solid", ["round", "소형", "판독보류"]),
  one(418, "가는 세로 나무기둥", "pillar", "solid", ["pillar", "장대", "수직"]),
  one(419, "세로 나무 장대", "pillar", "solid", ["pole", "기둥", "목재"]),

  // ── 14행 (인덱스 420-449) ────────────────────────────────────────────
  one(420, "흙 서쪽 모래경계", "terrain", "passable", ["dirt", "sand edge", "서쪽"]),
  one(421, "갈색 흙바닥", "terrain", "passable", ["dirt", "흙", "지형"]),
  one(422, "흙 동쪽 모래경계", "terrain", "passable", ["dirt", "sand edge", "동쪽"]),
  one(426, "석벽 왼쪽 가장자리", "wall", "solid", ["stone", "좌측", "가장자리"]),
  one(427, "회색 석재 벽돌", "wall", "solid", ["brick", "석벽", "회색"]),
  one(428, "석벽 오른쪽 가장자리", "wall", "solid", ["stone", "우측", "가장자리"]),
  one(429, "창틀 왼쪽 세로대", "window", "solid", ["window", "세로목", "좌측"]),
  one(430, "창 너머 어둠", "window", "solid", ["dark", "내부", "검정"]),
  one(431, "창틀 오른쪽 세로대", "window", "solid", ["window", "세로목", "우측"]),
  one(432, "나무 선반장 왼쪽", "shelf", "solid", ["shelf", "찬장", "좌측"]),
  one(433, "나무 선반장 가운데", "shelf", "solid", ["shelf", "찬장", "중앙"]),
  one(434, "나무 선반장 오른쪽", "shelf", "solid", ["shelf", "찬장", "우측"]),
  one(435, "고른 세로 나무널", "wall", "solid", ["wood", "널빤지", "세로"]),
  one(436, "사선 무늬 나무벽", "wall", "solid", ["wood", "사선무늬", "벽"]),
  one(437, "반대 사선 나무벽", "wall", "solid", ["wood", "사선무늬", "벽"]),
  one(438, "쌍줄 사선 각재", "decoration", "solid", ["diagonal", "쌍줄", "분홍배경"]),
  one(439, "우상단 작은 각", "decoration", "solid", ["corner", "조각", "우상"]),
  one(440, "오목한 나무 곡면", "ship", "solid", ["curve", "선체", "오목"]),
  one(441, "반대 나무 곡면", "ship", "solid", ["curve", "선체", "볼록"]),
  one(442, "좌상단 작은 각", "decoration", "solid", ["corner", "조각", "좌상"]),
  one(443, "반대 쌍줄 사선", "decoration", "solid", ["diagonal", "쌍줄", "분홍배경"]),
  one(444, "오른쪽 나무 계단", "stairs", "passable", ["stairs", "계단", "우측"]),
  one(445, "왼쪽 나무 계단", "stairs", "passable", ["stairs", "계단", "좌측"]),
  one(446, "흰 커버 침대끝", "bed", "solid", ["bed", "이불", "발치"]),
  one(447, "가로 나무 들보", "decoration", "solid", ["beam", "가로목", "들보"]),
  one(448, "십자 나무 들보", "decoration", "solid", ["beam", "십자", "교차"]),
  one(449, "가로 나무 장선", "decoration", "solid", ["beam", "가로목", "장선"]),

  // ── 15행 (인덱스 450-479) ────────────────────────────────────────────
  one(450, "흙 남서 모래모서리", "terrain", "passable", ["dirt", "sand corner", "남서"]),
  one(451, "흙 남쪽 모래경계", "terrain", "passable", ["dirt", "sand edge", "남쪽"]),
  one(452, "흙 남동 모래모서리", "terrain", "passable", ["dirt", "sand corner", "남동"]),
  one(456, "석벽 좌측 하단면", "wall", "solid", ["stone", "좌하단", "벽면"]),
  one(457, "회색 석재 벽돌", "wall", "solid", ["brick", "석벽", "회색"]),
  one(458, "석벽 우측 하단면", "wall", "solid", ["stone", "우하단", "벽면"]),
  one(459, "창틀 좌하단 모서리", "window", "solid", ["window", "창틀", "좌하"]),
  one(460, "창틀 하단 가로대", "window", "solid", ["window", "가로목", "하단"]),
  one(461, "창틀 우하단 모서리", "window", "solid", ["window", "창틀", "우하"]),
  one(462, "왼쪽홈 가로 마루", "floor", "passable", ["floor", "가로결", "좌측홈"]),
  one(463, "어두운 빈 벽장", "furniture", "solid", ["closet", "벽감", "빈칸"]),
  one(464, "오른쪽홈 가로 마루", "floor", "passable", ["floor", "가로결", "우측홈"]),
  one(465, "세로널 오른쪽 홈", "wall", "solid", ["wood", "세로결", "홈"]),
  one(466, "고른 가로 마루판", "floor", "passable", ["floor", "갑판", "평판"]),
  one(467, "가로 마루 우측결", "floor", "passable", ["floor", "갑판", "우측"]),
  one(468, "우측 사선 얇은판", "decoration", "solid", ["diagonal", "얇은판", "우측"]),
  one(469, "우상 사선 조각", "decoration", "solid", ["diagonal", "조각", "우상"]),
  one(470, "나무 탁자 옆면", "furniture", "solid", ["table", "옆모습", "가구"]),
  one(471, "좌상 사선 조각", "decoration", "solid", ["diagonal", "조각", "좌상"]),
  one(472, "세로 나무 다리", "furniture", "solid", ["leg", "다리", "수직"]),
  one(473, "좌측 사선 얇은판", "decoration", "solid", ["diagonal", "얇은판", "좌측"]),
  one(474, "나무 장롱 왼쪽", "furniture", "solid", ["wardrobe", "옷장", "좌측"]),
  one(475, "나무 장롱 오른쪽", "furniture", "solid", ["wardrobe", "옷장", "우측"]),
  one(476, "침대 베개 옆면", "bed", "solid", ["bed", "베개", "측면"]),
  one(477, "침대 이불 옆면", "bed", "solid", ["bed", "이불", "측면"]),
  one(478, "세로 가는 기둥끝", "pillar", "solid", ["pillar", "장대", "하단"]),
  one(479, "가로 나무 막대", "decoration", "solid", ["beam", "가로목", "막대"]),
];
