// retro_House(레트로 집) 칩셋(tex_easyrpg_chipset_retro_house) 타일 그림판의 AI 검색용 큐레이션 시맨틱 테이블.
// 6x 업스케일 행 스트립(.omo/evidence/chipset-strips/retro_house/row-00..15.png) 전수 판독으로 작성했다.
// tileSemanticsDungeon.ts / tileSemanticsInterior.ts 와 동일한 계약: tileset.tileMeta[] 와 별개로
// 관리되는 검색 전용 데이터다. 통행성/레이어 계약은 tilesetHarness 가, 타일별 정밀 라벨은 여기가 담당한다.
//
// 좌표 규약: 30타일/행, ID = 행×30 + 열. 아트가 없는 슬롯(완전 투명 또는 분홍 컬러키 단색)은
// 서술할 대상이 없으므로 엔트리를 만들지 않는다 — scripts/verify-tile-semantics.mts 가 픽셀에서
// 그 목록을 직접 구해 커버리지를 검증한다.
// 판독이 애매한 타일은 단정 대신 형태 서술을 쓰고 "판독보류" 태그를 남겼다(실내 465~467 전례).
//
// 실측: 도화 가능 478칸 전수 서술, 고유 라벨 425개.
// 조립: scripts/build-tile-semantics.mts (수기 편집 대신 이 스크립트로 재생성한다).

import type { CombinedTownTileSemanticEntry } from "./tileSemanticsCombinedTown";

export type RetroHouseTileSemanticEntry = CombinedTownTileSemanticEntry;

function one(
  index: number,
  label: string,
  role: string,
  passage: "passable" | "solid",
  tags: readonly string[]
): RetroHouseTileSemanticEntry {
  return { index, label, role, passage, tags: [label, ...tags] };
}

export const RETRO_HOUSE_TILE_SEMANTICS: readonly RetroHouseTileSemanticEntry[] = [
  // ── 0행 (인덱스 0-29) ─────────────────────────────────────────────
  one(0, "두레박 달린 우물", "prop", "solid", ["well", "우물", "목재테두리"]),
  one(1, "돌로 쌓은 우물", "prop", "solid", ["well", "석축", "테두리"]),
  one(2, "물 가득한 우물", "prop", "solid", ["well", "수면", "우물통"]),
  one(3, "잔잔한 파란 물", "water", "passable", ["water", "호수", "물결"]),
  one(4, "잔물결이 인 물", "water", "passable", ["water", "파문", "수면"]),
  one(5, "굵은 물결 수면", "water", "passable", ["water", "파도", "물결"]),
  one(6, "흰꽃 핀 관목", "plant", "solid", ["bush", "꽃덤불", "수풀"]),
  one(7, "고른 연두 잔디", "terrain", "passable", ["grass", "잔디밭", "초원"]),
  one(8, "흰 민무늬 벽면", "wall", "solid", ["white", "회반죽", "벽"]),
  one(9, "짙은 녹음 나무", "tree", "solid", ["tree", "수목", "어두운잎"]),
  one(10, "고른 연두 잔디", "terrain", "passable", ["grass", "초원", "평지"]),
  one(11, "빽빽한 어두운 나무", "tree", "solid", ["tree", "밀림", "그늘"]),
  one(12, "나무 침대 머리 좌", "furniture", "solid", ["침대", "bed", "침구", "목재"]),
  one(13, "나무 침대 머리 중앙", "furniture", "solid", ["침대", "bed", "베개", "침구"]),
  one(14, "나무 침대 머리 우", "furniture", "solid", ["침대", "bed", "침구", "목재"]),
  one(15, "나무 침대 발치 좌", "furniture", "solid", ["침대", "bed", "이불", "목재"]),
  one(16, "나무 침대 발치 중앙", "furniture", "solid", ["침대", "bed", "이불", "침구"]),
  one(17, "나무 침대 발치 우", "furniture", "solid", ["침대", "bed", "이불", "목재"]),
  one(18, "왼쪽 잿빛 석벽", "wall", "solid", ["wall", "석조", "회색"]),
  one(19, "가운데 잿빛 석벽", "wall", "solid", ["wall", "회색돌", "벽면"]),
  one(20, "오른쪽 잿빛 석벽", "wall", "solid", ["wall", "석조", "회색"]),
  one(21, "왼쪽 어두운 석벽", "wall", "solid", ["wall", "어두운돌", "벽"]),
  one(22, "오른쪽 어두운 석벽", "wall", "solid", ["wall", "짙은벽", "석재"]),
  one(23, "가운데 어두운 석벽", "wall", "solid", ["wall", "어두운돌", "벽면"]),
  one(24, "어두운 사다리 왼쪽", "ladder", "solid", ["ladder", "사다리", "왼쪽"]),
  one(25, "어두운 사다리 오른쪽", "ladder", "solid", ["ladder", "사다리", "오른쪽"]),
  one(26, "뾰족한 어두운 구조물", "decoration", "solid", ["dark", "구조물", "판독보류"]),
  one(27, "검푸른 덩어리 구조물", "decoration", "solid", ["dark", "덩어리", "판독보류"]),
  one(28, "세로 검푸른 기둥", "pillar", "solid", ["post", "기둥", "어두운"]),
  one(29, "보라꽃 장식 덤불", "decoration", "solid", ["purple", "장식", "판독보류"]),

  // ── 1행 (인덱스 30-59) ─────────────────────────────────────────────
  one(30, "잔디 낀 물가", "water", "passable", ["water", "물가", "잔디"]),
  one(31, "풀섶 낀 물가", "water", "passable", ["water", "풀숲", "호숫가"]),
  one(32, "잔디 모서리 물가", "water", "passable", ["water", "모서리", "잔디"]),
  one(33, "짙은 파란 물결", "water", "passable", ["water", "파도", "진청색"]),
  one(34, "예리한 물결 수면", "water", "passable", ["water", "물결", "수면"]),
  one(35, "포개진 물결 수면", "water", "passable", ["water", "파문", "겹물결"]),
  one(36, "흰꽃 무성한 수풀", "plant", "solid", ["bush", "꽃밭", "수풀"]),
  one(37, "흰꽃 낀 초원", "terrain", "passable", ["grass", "꽃밭", "연두"]),
  one(38, "흰꽃 낀 덤불", "plant", "solid", ["bush", "흰꽃", "꽃덤불"]),
  one(39, "울창한 초록 나무", "tree", "solid", ["tree", "수목", "잎"]),
  one(40, "그늘진 짙은 나무", "tree", "solid", ["tree", "어두운잎", "수풀"]),
  one(41, "무성한 나무 군락", "tree", "solid", ["tree", "밀림", "숲"]),
  one(42, "자줏빛 무늬 기와", "roof", "solid", ["roof", "보라기와", "지붕"]),
  one(43, "보라 화려한 기와", "roof", "solid", ["roof", "화려", "타일"]),
  one(44, "연보라 무늬 기와", "roof", "solid", ["roof", "연보라", "지붕"]),
  one(45, "회백 크림 기와", "roof", "solid", ["roof", "크림", "미색"]),
  one(46, "밝은 크림 기와", "roof", "solid", ["roof", "크림색", "밝은"]),
  one(47, "크림 무늬 기와", "roof", "solid", ["roof", "무늬", "미색"]),
  one(48, "왼쪽 회청 석벽", "wall", "solid", ["wall", "회청색", "벽"]),
  one(49, "연한 회색 석벽", "wall", "solid", ["wall", "회색돌", "연한"]),
  one(50, "오른쪽 회청 석벽", "wall", "solid", ["wall", "청회색", "벽면"]),
  one(51, "왼쪽 짙은 석벽", "wall", "solid", ["wall", "짙은돌", "벽"]),
  one(52, "가운데 짙은 석벽", "wall", "solid", ["wall", "어두운돌", "벽면"]),
  one(53, "오른쪽 짙은 석벽", "wall", "solid", ["wall", "짙은벽", "석재"]),
  one(54, "북서 방향 계단", "stairs", "passable", ["stairs", "계단", "좌상단"]),
  one(55, "북동 방향 계단", "stairs", "passable", ["stairs", "계단", "우상단"]),
  one(56, "남서 방향 계단", "stairs", "passable", ["stairs", "계단", "좌하단"]),
  one(57, "남동 방향 계단", "stairs", "passable", ["stairs", "계단", "우하단"]),
  one(58, "회색 격자 울타리", "fence", "solid", ["fence", "격자", "나무"]),
  one(59, "회보라 장식 구조물", "decoration", "solid", ["purple", "장식", "판독보류"]),

  // ── 2행 (인덱스 60-89) ─────────────────────────────────────────────
  one(60, "나무둑 낀 물가", "water", "passable", ["water", "물가", "목재"]),
  one(61, "목재 둑 낀 물가", "water", "passable", ["water", "둑", "나무"]),
  one(62, "통나무 낀 물가", "water", "passable", ["water", "통나무", "물가"]),
  one(63, "고른 파란 수면", "water", "passable", ["water", "수면", "물"]),
  one(64, "잔잔한 수면 물", "water", "passable", ["water", "호수", "잔잔"]),
  one(65, "푸른 잔물결", "water", "passable", ["water", "잔물결", "수면"]),
  one(66, "흰꽃 초록 덤불", "plant", "solid", ["bush", "흰꽃", "꽃밭"]),
  one(67, "흰 민무늬 벽면", "wall", "solid", ["white", "회벽", "평면"]),
  one(68, "흰꽃 섞인 잔디", "terrain", "passable", ["grass", "꽃밭", "연두"]),
  one(69, "짙은 숲 나무", "tree", "solid", ["tree", "숲", "어두운잎"]),
  one(70, "빽빽한 숲 나무", "tree", "solid", ["tree", "밀림", "수풀"]),
  one(71, "그윽한 숲 그늘", "tree", "solid", ["tree", "그늘", "숲"]),
  one(72, "붉은 갈 무늬 기와", "roof", "solid", ["roof", "적갈색", "지붕"]),
  one(73, "붉은색 무늬 기와", "roof", "solid", ["roof", "붉은무늬", "타일"]),
  one(74, "진홍 무늬 기와", "roof", "solid", ["roof", "장미빛", "지붕"]),
  one(75, "미색 무늬 기와", "roof", "solid", ["roof", "미색", "평면"]),
  one(76, "하얀 크림 기와", "roof", "solid", ["roof", "하양", "밝은"]),
  one(77, "베이지 무늬 기와", "roof", "solid", ["roof", "베이지", "지붕"]),
  one(78, "왼쪽 회색 돌벽", "wall", "solid", ["wall", "회색돌", "벽"]),
  one(79, "거친 회색 돌벽", "wall", "solid", ["wall", "거친돌", "벽면"]),
  one(80, "오른쪽 회색 돌벽", "wall", "solid", ["wall", "돌벽", "회색"]),
  one(81, "왼쪽 어두운 돌벽", "wall", "solid", ["wall", "어두운돌", "벽"]),
  one(82, "가운데 어두운 돌벽", "wall", "solid", ["wall", "짙은돌", "석조"]),
  one(83, "오른쪽 어두운 돌벽", "wall", "solid", ["wall", "어두운돌", "벽면"]),
  one(84, "타오르는 화톳불", "torch", "solid", ["campfire", "불꽃", "야영"]),
  one(85, "나무 문틀", "gate", "solid", ["gate", "문틀", "목재"]),
  one(86, "걸린 표지판", "sign", "solid", ["sign", "간판", "표지"]),
  one(87, "뾰족한 유리창", "window", "solid", ["window", "창틀", "뾰족"]),
  one(88, "뾰족한 나무문", "door", "solid", ["door", "나무문", "출입구"]),
  one(89, "청록 잎 무더기", "decoration", "solid", ["leaves", "청록", "판독보류"]),

  // ── 3행 (인덱스 90-119) ─────────────────────────────────────────────
  one(90, "기둥 세운 물가", "water", "passable", ["water", "기둥", "물가"]),
  one(91, "목책 둘린 물가", "water", "passable", ["water", "목책", "물"]),
  one(92, "세로 기둥 낀 물", "water", "passable", ["water", "세로기둥", "물가"]),
  one(93, "격자무늬 물결", "water", "passable", ["water", "격자", "물결"]),
  one(94, "휘감긴 물결", "water", "passable", ["water", "파문", "수면"]),
  one(95, "무늬진 수면", "water", "passable", ["water", "무늬", "물결"]),
  one(96, "흰꽃 낀 초록 덤불", "plant", "solid", ["bush", "흰꽃", "꽃밭"]),
  one(97, "흰 민무늬 벽면", "wall", "solid", ["white", "회벽", "평면"]),
  one(98, "흰꽃 핀 초록 덤불", "plant", "solid", ["bush", "꽃덤불", "초목"]),
  one(99, "어두운 수풀 나무", "tree", "solid", ["tree", "수풀", "어두운"]),
  one(100, "빽빽한 나무숲", "tree", "solid", ["tree", "밀림", "숲"]),
  one(101, "짙은 잎 나무", "tree", "solid", ["tree", "짙은잎", "수목"]),
  one(102, "짙은 갈색 기와", "roof", "solid", ["roof", "진갈색", "지붕"]),
  one(103, "밤빛 무늬 기와", "roof", "solid", ["roof", "밤색", "타일"]),
  one(104, "갈색 줄 기와", "roof", "solid", ["roof", "갈색줄", "지붕"]),
  one(105, "먼지 낀 갈 기와", "roof", "solid", ["roof", "먼지", "기와"]),
  one(106, "어두운 갈 기와", "roof", "solid", ["roof", "진색", "지붕"]),
  one(107, "어두운 무늬 기와", "roof", "solid", ["roof", "짙은", "무늬"]),
  one(108, "왼쪽 짙은 석벽", "wall", "solid", ["wall", "짙은돌", "벽"]),
  one(109, "가운데 짙은 석벽", "wall", "solid", ["wall", "회색돌", "벽면"]),
  one(110, "오른쪽 짙은 석벽", "wall", "solid", ["wall", "어두운돌", "벽"]),
  one(111, "회색 조약돌 바닥", "floor", "passable", ["cobble", "포장", "회색"]),
  one(112, "청회 타일 바닥", "floor", "passable", ["tile", "타일", "청회색"]),
  one(113, "잿빛 타일 바닥", "floor", "passable", ["tile", "잿빛", "바닥"]),
  one(114, "갈색 둥근 항아리", "prop", "solid", ["urn", "항아리", "갈색"]),
  one(115, "작은 나무 통", "barrel", "solid", ["barrel", "통", "목재"]),
  one(116, "붉은 갈 벽면", "wall", "solid", ["wall", "적갈색", "벽"]),
  one(117, "둥근 갈색 천막 지붕", "awning", "solid", ["awning", "천막", "지붕"]),
  one(118, "어두운 갈색 천막", "awning", "solid", ["awning", "천막", "어두운"]),
  one(119, "새긴 회색 석상", "statue", "solid", ["statue", "석상", "조각"]),

  // ── 4행 (인덱스 120-149) ─────────────────────────────────────────────
  one(120, "고요한 물", "water", "passable", ["water", "잔잔"]),
  one(121, "잔잔한 물", "water", "passable", ["water", "고요"]),
  one(122, "푸른 물바닥", "water", "passable", ["water", "바닥"]),
  one(123, "깊은 물바닥", "water", "passable", ["water", "깊이"]),
  one(124, "잔물결 물", "water", "passable", ["wave", "물결"]),
  one(125, "고요한 물바닥", "water", "passable", ["water", "고요"]),
  one(126, "잔디 가장자리 지붕", "roof", "solid", ["roof", "지붕", "변두리"]),
  one(127, "무성한 잔디밭", "terrain", "passable", ["grass", "지면"]),
  one(128, "장밋빛 지붕면", "roof", "solid", ["roof", "표면"]),
  one(129, "잔디 위 돌덩어리", "rock", "solid", ["rock", "바위", "판독보류"]),
  one(130, "푸른 잔디밭", "terrain", "passable", ["grass", "지면"]),
  one(131, "회색 돌바닥", "floor", "passable", ["stone", "포장"]),
  one(132, "갈색 나무 벽", "wall", "solid", ["wall", "wood", "목재"]),
  one(133, "나무 벽면", "wall", "solid", ["wall", "wood"]),
  one(134, "갈색 판자 벽", "wall", "solid", ["wall", "plank", "판자"]),
  one(135, "짜임 나무 벽", "wall", "solid", ["wall", "짜임"]),
  one(136, "나무 벽 표면", "wall", "solid", ["wall", "wood", "표면"]),
  one(137, "나무 창틀 창문", "window", "solid", ["window", "창틀"]),
  one(138, "물과 잔디 경계", "water", "passable", ["water", "물가", "shore"]),
  one(139, "잔디와 물 경계", "water", "passable", ["water", "물가", "shore"]),
  one(140, "고요한 물", "water", "passable", ["water", "잔잔"]),
  one(141, "잔잔한 물", "water", "passable", ["water", "고요"]),
  one(142, "물가 풀밭", "water", "passable", ["water", "물가"]),
  one(143, "풀밭 물가", "water", "passable", ["water", "물가"]),
  one(144, "나무 판자", "prop", "solid", ["wood", "board", "판독보류"]),
  one(145, "물가 나무 구조물", "prop", "solid", ["wood", "structure", "판독보류"]),
  one(146, "적갈색 헛간", "prop", "solid", ["barn", "건물", "판독보류"]),
  one(147, "나무 기둥", "pillar", "solid", ["pillar", "post", "기둥"]),
  one(148, "나무 말뚝", "pillar", "solid", ["post", "stake", "말뚝"]),
  one(149, "물 위 나무 다리", "prop", "solid", ["bridge", "wood", "판독보류"]),

  // ── 5행 (인덱스 150-179) ─────────────────────────────────────────────
  one(150, "잔잔한 물", "water", "passable", ["water", "고요"]),
  one(151, "고요한 물바닥", "water", "passable", ["water", "바닥"]),
  one(152, "푸른 물빛", "water", "passable", ["water", "푸른"]),
  one(153, "물 표면", "water", "passable", ["water", "표면"]),
  one(154, "잔물결 물", "water", "passable", ["wave", "물결"]),
  one(155, "깊은 물바닥", "water", "passable", ["water", "깊이"]),
  one(156, "잔디가 낀 지붕", "roof", "solid", ["roof", "잔디"]),
  one(157, "지붕 표면", "roof", "solid", ["roof", "표면"]),
  one(158, "잔디 언저리 지붕", "roof", "solid", ["roof", "변두리"]),
  one(159, "잔디 낀 돌길", "path", "passable", ["stone", "길", "path"]),
  one(160, "돌길 모서리", "path", "passable", ["stone", "길", "edge"]),
  one(161, "잔디와 돌길", "path", "passable", ["stone", "길", "path"]),
  one(162, "밝은 나무 벽", "wall", "solid", ["wall", "wood", "목재"]),
  one(163, "나무 벽면", "wall", "solid", ["wall", "wood"]),
  one(164, "갈색 목재 벽", "wall", "solid", ["wall", "목재"]),
  one(165, "목재 벽면", "wall", "solid", ["wall", "목재"]),
  one(166, "나무 벽 표면", "wall", "solid", ["wall", "wood", "표면"]),
  one(167, "무늬 있는 나무 벽", "wall", "solid", ["wall", "wood", "무늬"]),
  one(168, "나무 판자 바닥", "floor", "passable", ["wood", "plank", "바닥"]),
  one(169, "판자 바닥", "floor", "passable", ["wood", "plank"]),
  one(170, "나무 바닥", "floor", "passable", ["wood", "바닥"]),
  one(171, "널빤지 마루", "floor", "passable", ["wood", "plank"]),
  one(172, "나무 마루", "floor", "passable", ["wood", "마루"]),
  one(173, "목재 마루", "floor", "passable", ["wood", "마루"]),
  one(174, "나무 격자 울타리", "fence", "solid", ["fence", "lattice", "격자"]),
  one(175, "나무 탁자", "furniture", "solid", ["table", "furniture", "판독보류"]),
  one(176, "나무 벤치", "furniture", "solid", ["bench", "furniture", "판독보류"]),
  one(177, "쇠테 나무 상자", "chest", "solid", ["chest", "box", "판독보류"]),
  one(178, "알록달록 꽃송이", "decoration", "solid", ["flower", "꽃", "장식"]),
  one(179, "붉은 깃발", "banner", "solid", ["flag", "banner", "깃발"]),

  // ── 6행 (인덱스 180-209) ─────────────────────────────────────────────
  one(180, "잔잔한 물", "water", "passable", ["water", "고요"]),
  one(181, "잔잔한 물바닥", "water", "passable", ["water", "바닥"]),
  one(182, "고요한 물", "water", "passable", ["water", "잔잔"]),
  one(183, "잔잔한 물", "water", "passable", ["water", "고요"]),
  one(184, "잔물결 물", "water", "passable", ["wave", "물결"]),
  one(185, "깊은 물바닥", "water", "passable", ["water", "깊이"]),
  one(186, "잔디 가장자리 지붕", "roof", "solid", ["roof", "변두리"]),
  one(187, "지붕 표면", "roof", "solid", ["roof", "표면"]),
  one(188, "잔디가 낀 지붕", "roof", "solid", ["roof", "잔디"]),
  one(189, "돌길 언저리", "path", "passable", ["stone", "길", "edge"]),
  one(190, "회색 돌바닥", "floor", "passable", ["stone", "포장"]),
  one(191, "잔디 섞인 돌바닥", "floor", "passable", ["stone", "바닥"]),
  one(192, "나무 판자 바닥", "floor", "passable", ["wood", "plank", "바닥"]),
  one(193, "구멍 난 나무 바닥", "floor", "passable", ["wood", "damaged", "바닥"]),
  one(194, "무늬 새긴 나무 문", "door", "solid", ["door", "wood", "문양"]),
  one(195, "색 무늬 나무 문", "door", "solid", ["door", "wood", "무늬"]),
  one(196, "따뜻한 빛 문", "door", "passable", ["door", "입구", "빛"]),
  one(197, "밝은 문 입구", "door", "passable", ["door", "entrance", "입구"]),
  one(198, "나무 마루 바닥", "floor", "passable", ["wood", "마루"]),
  one(199, "판자 마루", "floor", "passable", ["wood", "plank", "마루"]),
  one(200, "나무 바닥", "floor", "passable", ["wood", "바닥"]),
  one(201, "무늬 돌바닥", "floor", "passable", ["stone", "mosaic", "바닥"]),
  one(202, "창문 달린 나무 벽", "wall", "solid", ["wall", "wood", "창문"]),
  one(203, "붉은 지붕 나무 벽", "wall", "solid", ["wall", "roof", "지붕"]),
  one(204, "나무 격자판", "fence", "solid", ["fence", "lattice", "판독보류"]),
  one(205, "나무 기둥", "pillar", "solid", ["pillar", "post", "기둥"]),
  one(206, "나무 말뚝", "pillar", "solid", ["post", "stake", "말뚝"]),
  one(207, "나무 격자 무늬", "fence", "solid", ["fence", "lattice", "판독보류"]),
  one(208, "붉은 지붕 모서리", "roof", "solid", ["roof", "corner", "모서리"]),
  one(209, "붉은 지붕 박공", "roof", "solid", ["roof", "gable", "박공"]),

  // ── 7행 (인덱스 210-239) ─────────────────────────────────────────────
  one(210, "잔잔한 물바닥", "water", "passable", ["water", "바닥"]),
  one(211, "고요한 물", "water", "passable", ["water", "잔잔"]),
  one(212, "잔잔한 물", "water", "passable", ["water", "고요"]),
  one(213, "푸른 물빛", "water", "passable", ["water", "푸른"]),
  one(214, "잔물결 물", "water", "passable", ["wave", "물결"]),
  one(215, "깊은 물바닥", "water", "passable", ["water", "깊이"]),
  one(216, "잔디 언저리 지붕", "roof", "solid", ["roof", "변두리"]),
  one(217, "지붕 표면", "roof", "solid", ["roof", "표면"]),
  one(218, "잔디가 낀 지붕", "roof", "solid", ["roof", "잔디"]),
  one(219, "잔디 섞인 돌길", "path", "passable", ["stone", "길", "path"]),
  one(220, "돌바닥 가장자리", "floor", "passable", ["stone", "바닥", "edge"]),
  one(221, "돌과 잔디 바닥", "path", "passable", ["stone", "길", "path"]),
  one(222, "나무 마루", "floor", "passable", ["wood", "마루"]),
  one(223, "가장자리 나무 바닥", "floor", "passable", ["wood", "바닥", "edge"]),
  one(224, "장식 나무 문", "door", "solid", ["door", "wood", "장식"]),
  one(225, "틀 있는 나무 문", "door", "solid", ["door", "frame", "틀"]),
  one(226, "열린 나무 문", "door", "passable", ["door", "open", "입구"]),
  one(227, "밝은 문 입구", "door", "passable", ["door", "entrance", "입구"]),
  one(228, "나무 판자 마루", "floor", "passable", ["wood", "plank", "마루"]),
  one(229, "우드 바닥", "floor", "passable", ["wood", "바닥"]),
  one(230, "나무 바닥", "floor", "passable", ["wood", "바닥"]),
  one(231, "금빛 무늬 바닥", "floor", "passable", ["floor", "mosaic", "무늬"]),
  one(232, "흰색 울타리", "fence", "solid", ["fence", "white", "울타리"]),
  one(234, "어두운 나무 벽", "wall", "solid", ["wall", "dark", "어두움"]),
  one(235, "짙은 갈색 벽", "wall", "solid", ["wall", "갈색"]),
  one(236, "어두운 목재 벽", "wall", "solid", ["wall", "dark", "목재"]),
  one(237, "틀 있는 어두운 벽", "wall", "solid", ["wall", "frame", "틀"]),
  one(238, "붉은 지붕 경사", "roof", "solid", ["roof", "slope", "경사"]),
  one(239, "붉은 지붕 경사면", "roof", "solid", ["roof", "slope", "경사"]),

  // ── 8행 (인덱스 240-269) ─────────────────────────────────────────────
  one(240, "성긴 연두 잔디", "terrain", "passable", ["grass", "풀밭"]),
  one(241, "고른 연두 잔디", "terrain", "passable", ["grass", "초원"]),
  one(242, "밝은 점무늬 잔디", "terrain", "passable", ["grass", "연두색"]),
  one(243, "짙은 풀숲 무늬", "terrain", "passable", ["grass", "수풀"]),
  one(244, "듬성한 밝은 잔디", "terrain", "passable", ["grass", "들판"]),
  one(245, "촘촘한 풀잎 무늬", "terrain", "passable", ["grass", "초목"]),
  one(246, "사각 테두리 돌벽", "wall", "solid", ["stone", "석조"]),
  one(247, "작은 점무늬 잔디", "terrain", "passable", ["grass", "초록"]),
  one(248, "세로 테두리 돌벽", "wall", "solid", ["stone", "회색벽"]),
  one(249, "검은 균열 돌벽", "wall", "solid", ["stone", "어두운벽"]),
  one(250, "넓은 연두 풀밭", "terrain", "passable", ["grass", "잔디밭"]),
  one(251, "거친 검정 암벽", "wall", "solid", ["rock", "균열"]),
  one(252, "분홍 나뭇결 판", "floor", "passable", ["wood", "분홍색"]),
  one(253, "푸른 비늘 돌판", "floor", "passable", ["stone", "청회색"]),
  one(254, "갈색 기둥 벽돌벽", "wall", "solid", ["brick", "목재보강"]),
  one(255, "왼쪽 기둥 벽돌벽", "wall", "solid", ["brick", "목재기둥"]),
  one(256, "오른쪽 보강 회벽", "wall", "solid", ["plaster", "갈색기둥"]),
  one(257, "왼쪽 보강 회벽", "wall", "solid", ["plaster", "나무보"]),
  one(259, "마른 나무 밑동", "tree", "solid", ["stump", "고목"]),
  one(260, "연두 나무 우듬지", "tree", "solid", ["foliage", "나뭇잎"]),
  one(261, "갈라진 마른 가지", "tree", "solid", ["branch", "고사목"]),
  one(262, "오른쪽 연두 관목", "plant", "solid", ["shrub", "수풀"]),
  one(263, "둥근 연두 관목", "plant", "solid", ["bush", "관목숲"]),
  one(264, "흰 대각 빛무늬", "decoration", "solid", ["white", "판독보류"]),
  one(265, "잎 달린 굵은 가지", "tree", "solid", ["branch", "녹색잎"]),
  one(266, "방패 문양 묘비", "decoration", "solid", ["gravestone", "석물"]),
  one(267, "회색 이오니아 기둥", "pillar", "solid", ["column", "석조"]),
  one(268, "왼쪽 회색 난간상", "decoration", "solid", ["silhouette", "판독보류"]),
  one(269, "오른쪽 회색 난간상", "decoration", "solid", ["silhouette", "판독보류"]),

  // ── 9행 (인덱스 270-299) ─────────────────────────────────────────────
  one(270, "성긴 연두 잔디", "terrain", "passable", ["grass", "풀밭"]),
  one(271, "고른 연두 잔디", "terrain", "passable", ["grass", "초원"]),
  one(272, "밝은 점무늬 잔디", "terrain", "passable", ["grass", "연두색"]),
  one(273, "짙은 풀숲 무늬", "terrain", "passable", ["grass", "수풀"]),
  one(274, "가는 잎 풀숲 무늬", "terrain", "passable", ["grass", "초목"]),
  one(275, "굵은 잎 풀숲 무늬", "terrain", "passable", ["grass", "밀생"]),
  one(276, "왼쪽 테두리 돌벽", "wall", "solid", ["stone", "회색벽"]),
  one(277, "가운데 사각 돌벽", "wall", "solid", ["stone", "석재판"]),
  one(278, "오른쪽 테두리 돌벽", "wall", "solid", ["stone", "회색벽"]),
  one(279, "왼쪽 검은 균열벽", "wall", "solid", ["rock", "어두운벽"]),
  one(280, "가운데 검은 균열벽", "wall", "solid", ["rock", "갈라짐"]),
  one(281, "오른쪽 검은 균열벽", "wall", "solid", ["rock", "암벽"]),
  one(282, "연보라 나뭇결 판", "floor", "passable", ["wood", "보라색"]),
  one(283, "비늘 돌판", "floor", "passable", ["stone", "회녹색"]),
  one(284, "이끼 낀 푸른 벽돌", "wall", "solid", ["brick", "녹색이끼"]),
  one(285, "왼쪽 이끼 벽돌벽", "wall", "solid", ["brick", "푸른벽"]),
  one(286, "가운데 이끼 벽돌벽", "wall", "solid", ["brick", "덩굴"]),
  one(287, "오른쪽 이끼 벽돌벽", "wall", "solid", ["brick", "초록싹"]),
  one(288, "보라꽃 둥근 관목", "plant", "solid", ["flower", "꽃덤불"]),
  one(289, "진초록 둥근 관목", "plant", "solid", ["bush", "상록수"]),
  one(290, "잎 달린 나무 밑동", "tree", "solid", ["trunk", "녹색잎"]),
  one(291, "곧은 갈색 나무줄기", "tree", "solid", ["trunk", "뿌리"]),
  one(292, "왼쪽 잎과 나무뿌리", "tree", "solid", ["roots", "수관"]),
  one(293, "오른쪽 잎과 나무뿌리", "tree", "solid", ["roots", "나뭇잎"]),
  one(294, "옅은 대각 빛무늬", "decoration", "solid", ["white", "판독보류"]),
  one(295, "새잎 돋은 나뭇가지", "tree", "solid", ["branch", "연두잎"]),
  one(296, "얼굴 새긴 돌조각", "statue", "solid", ["carving", "석상"]),
  one(297, "홈 파인 회색 기둥", "pillar", "solid", ["column", "건축"]),
  one(298, "왼쪽 갈색 창틀", "window", "solid", ["window", "유리창"]),
  one(299, "오른쪽 갈색 창틀", "window", "solid", ["window", "유리창"]),

  // ── 10행 (인덱스 300-329) ────────────────────────────────────────────
  one(300, "성긴 연두 잔디", "terrain", "passable", ["grass", "풀밭"]),
  one(301, "고른 연두 잔디", "terrain", "passable", ["grass", "초원"]),
  one(302, "밝은 점무늬 잔디", "terrain", "passable", ["grass", "연두색"]),
  one(303, "짙은 풀숲 무늬", "terrain", "passable", ["grass", "수풀"]),
  one(304, "세로 잎 풀숲 무늬", "terrain", "passable", ["grass", "밀생"]),
  one(305, "사선 잎 풀숲 무늬", "terrain", "passable", ["grass", "초목"]),
  one(306, "왼쪽 회색 석판벽", "wall", "solid", ["stone", "회색벽"]),
  one(307, "가운데 회색 석판벽", "wall", "solid", ["stone", "돌판"]),
  one(308, "오른쪽 회색 석판벽", "wall", "solid", ["stone", "석조"]),
  one(309, "왼쪽 검정 암석벽", "wall", "solid", ["rock", "검은돌"]),
  one(310, "가운데 검정 암석벽", "wall", "solid", ["rock", "균열"]),
  one(311, "오른쪽 검정 암석벽", "wall", "solid", ["rock", "어두운벽"]),
  one(312, "조약돌 바닥", "floor", "passable", ["cobble", "포장"]),
  one(313, "자주색 조약돌 바닥", "floor", "passable", ["cobble", "보라돌"]),
  one(314, "밝은 갈색 벽돌벽", "wall", "solid", ["brick", "회벽"]),
  one(315, "왼쪽 밝은 벽돌벽", "wall", "solid", ["brick", "석회색"]),
  one(316, "가운데 밝은 벽돌벽", "wall", "solid", ["brick", "갈색줄눈"]),
  one(317, "오른쪽 밝은 벽돌벽", "wall", "solid", ["brick", "밝은벽"]),
  one(318, "노란 불꽃 벽횃불", "torch", "solid", ["flame", "조명"]),
  one(319, "검은 세로 돌기", "decoration", "solid", ["switch", "판독보류"]),
  one(320, "연두 문양 표지판", "sign", "solid", ["signboard", "안내판"]),
  one(321, "세로 갈색 밧줄", "rope", "solid", ["rope", "매듭"]),
  one(322, "갈색 나무 사다리", "ladder", "passable", ["ladder", "오르기"]),
  one(323, "보라 십자 석상", "statue", "solid", ["monument", "장식물"]),
  one(324, "밝은 대각 빛무늬", "decoration", "solid", ["white", "판독보류"]),
  one(325, "덩굴잎 달린 가지", "plant", "solid", ["vine", "녹색잎"]),
  one(326, "회색 매달린 장식", "decoration", "solid", ["hanging", "판독보류"]),
  one(327, "왼쪽 통나무 선반", "counter", "solid", ["wood", "가로대"]),
  one(328, "오른쪽 통나무 선반", "counter", "solid", ["wood", "가구"]),
  one(329, "검은 사각 바닥", "floor", "passable", ["black", "어둠"]),

  // ── 11행 (인덱스 330-359) ────────────────────────────────────────────
  one(330, "성긴 연두 잔디", "terrain", "passable", ["grass", "풀밭"]),
  one(331, "고른 연두 잔디", "terrain", "passable", ["grass", "초원"]),
  one(332, "밝은 점무늬 잔디", "terrain", "passable", ["grass", "연두색"]),
  one(333, "짙은 풀숲 무늬", "terrain", "passable", ["grass", "수풀"]),
  one(334, "아래로 흐른 풀잎", "terrain", "passable", ["grass", "세로무늬"]),
  one(335, "꺾인 연두 풀잎", "terrain", "passable", ["grass", "잎무늬"]),
  one(336, "왼쪽 짙은 석판벽", "wall", "solid", ["stone", "회색벽"]),
  one(337, "가운데 짙은 석판벽", "wall", "solid", ["stone", "돌판"]),
  one(338, "오른쪽 짙은 석판벽", "wall", "solid", ["stone", "석조"]),
  one(339, "왼쪽 거친 검은벽", "wall", "solid", ["rock", "암석"]),
  one(340, "가운데 거친 검은벽", "wall", "solid", ["rock", "갈라짐"]),
  one(341, "오른쪽 거친 검은벽", "wall", "solid", ["rock", "어두운돌"]),
  one(342, "회갈색 사각 석벽", "wall", "solid", ["masonry", "돌쌓기"]),
  one(343, "원형 문양 석벽", "wall", "solid", ["masonry", "원무늬"]),
  one(344, "갈색 회반죽 벽돌", "wall", "solid", ["brick", "회색줄눈"]),
  one(345, "왼쪽 갈색 벽돌벽", "wall", "solid", ["brick", "회반죽"]),
  one(346, "가운데 갈색 벽돌벽", "wall", "solid", ["brick", "석조벽"]),
  one(347, "오른쪽 갈색 벽돌벽", "wall", "solid", ["brick", "갈색돌"]),
  one(348, "흩어진 들꽃 무리", "plant", "solid", ["flowers", "꽃밭"]),
  one(349, "조각된 갈색 목문", "door", "solid", ["wooden", "출입구"]),
  one(350, "붉은 위쪽 화살표", "sign", "solid", ["arrow", "방향표시"]),
  one(351, "붉은꽃 화분", "plant", "solid", ["flowerpot", "정원"]),
  one(352, "황토색 둥근 항아리", "prop", "solid", ["jar", "저장용기"]),
  one(353, "자주색 서랍장", "furniture", "solid", ["cabinet", "수납"]),
  one(354, "주황 지붕 왼쪽면", "roof", "solid", ["roof", "기와"]),
  one(355, "주황 지붕 오른쪽면", "roof", "solid", ["roof", "갈색기와"]),
  one(356, "남색 지붕 왼쪽면", "roof", "solid", ["roof", "푸른기와"]),
  one(357, "남색 지붕 오른쪽면", "roof", "solid", ["roof", "보라기와"]),
  one(358, "세로 통나무 기둥", "pillar", "solid", ["wooden", "지지대"]),
  one(359, "어둠 속 보라 울타리", "fence", "solid", ["fence", "검은배경"]),

  // ── 12행 (인덱스 360-389) ────────────────────────────────────────────
  one(360, "잔디 둘레 자갈밭", "terrain", "passable", ["gravel", "잔디", "고립형"]),
  one(361, "꽃핀 초원", "terrain", "passable", ["grass", "들판", "야생화"]),
  one(362, "어두운 자갈 바닥", "terrain", "passable", ["gravel", "갈색", "돌길"]),
  one(363, "잔디 둘레 모래밭", "sand", "passable", ["sand", "잔디", "고립형"]),
  one(364, "연두 꽃핀 잔디", "terrain", "passable", ["grass", "초원", "꽃"]),
  one(365, "밝은 모래 바닥", "sand", "passable", ["sand", "베이지", "평지"]),
  one(366, "금속틀 검은 바닥", "floor", "passable", ["floor", "검정", "테두리"]),
  one(367, "검은 석재 바닥", "floor", "passable", ["stone", "암색", "실내"]),
  one(368, "금속 모서리 암색 바닥", "floor", "passable", ["floor", "검은색", "모서리장식"]),
  one(369, "회색틀 보라 바닥", "floor", "passable", ["floor", "보라색", "테두리"]),
  one(370, "짙은 보라 바닥", "floor", "passable", ["purple", "실내", "평면"]),
  one(371, "회색 모서리 보라 바닥", "floor", "passable", ["floor", "자주색", "모서리장식"]),
  one(372, "검보라 벽돌벽", "wall", "solid", ["brick", "어두운벽", "석조"]),
  one(373, "분홍 석재벽", "wall", "solid", ["stone", "벽돌", "장밋빛"]),
  one(374, "주황 술장식 차양", "awning", "solid", ["awning", "주황색", "상점"]),
  one(375, "붉은 기와지붕", "roof", "solid", ["roof", "적갈색", "기와"]),
  one(376, "황금빛 붉은 기와", "roof", "solid", ["roof", "금색무늬", "지붕"]),
  one(377, "짙은 적갈 지붕", "roof", "solid", ["roof", "갈색기와", "건물"]),
  one(378, "나무 울타리 왼쪽끝", "fence", "solid", ["fence", "목재", "좌측"]),
  one(379, "뾰족 나무 울타리", "fence", "solid", ["fence", "말뚝", "목책"]),
  one(380, "나무 울타리 오른쪽끝", "fence", "solid", ["fence", "목재", "우측"]),
  one(381, "장작 위 모닥불", "torch", "solid", ["campfire", "불꽃", "야영"]),
  one(382, "보라 돌무더기", "rock", "solid", ["rock", "자주색", "돌더미"]),
  one(383, "깨진 항아리", "prop", "solid", ["pottery", "도기", "파편"]),
  one(384, "붉은 지붕 왼쪽사선", "roof", "solid", ["roof", "적색", "대각선"]),
  one(385, "붉은 지붕 오른쪽사선", "roof", "solid", ["roof", "적갈색", "대각선"]),
  one(386, "푸른 지붕 왼쪽사선", "roof", "solid", ["roof", "청색", "대각선"]),
  one(387, "푸른 지붕 오른쪽사선", "roof", "solid", ["roof", "남색", "대각선"]),
  one(388, "세로 통나무 기둥", "pillar", "solid", ["log", "목재", "수직"]),
  one(389, "체크 침대 머리", "bed", "solid", ["bed", "침구", "머리판"]),

  // ── 13행 (인덱스 390-419) ────────────────────────────────────────────
  one(390, "자갈길 북서 경계", "terrain", "passable", ["gravel", "잔디경계", "좌상단"]),
  one(391, "자갈길 북쪽 경계", "terrain", "passable", ["gravel", "잔디경계", "상단"]),
  one(392, "자갈길 북동 경계", "terrain", "passable", ["gravel", "잔디경계", "우상단"]),
  one(393, "모래길 북서 경계", "sand", "passable", ["sand", "잔디경계", "좌상단"]),
  one(394, "모래길 북쪽 경계", "sand", "passable", ["sand", "잔디경계", "상단"]),
  one(395, "모래길 북동 경계", "sand", "passable", ["sand", "잔디경계", "우상단"]),
  one(396, "검은 바닥 북서 금속틀", "floor", "passable", ["floor", "회색테두리", "좌상단"]),
  one(397, "검은 바닥 북쪽 금속틀", "floor", "passable", ["floor", "회색테두리", "상단"]),
  one(398, "검은 바닥 북동 금속틀", "floor", "passable", ["floor", "회색테두리", "우상단"]),
  one(399, "보라 바닥 북서 회색틀", "floor", "passable", ["purple", "바닥경계", "좌상단"]),
  one(400, "보라 바닥 북쪽 회색틀", "floor", "passable", ["purple", "바닥경계", "상단"]),
  one(401, "보라 바닥 북동 회색틀", "floor", "passable", ["purple", "바닥경계", "우상단"]),
  one(402, "이끼 낀 분홍 벽돌", "wall", "solid", ["brick", "이끼", "장밋빛"]),
  one(403, "덩굴 덮인 검은 벽돌", "wall", "solid", ["brick", "덩굴", "어두운벽"]),
  one(404, "주황 천막 술장식", "awning", "solid", ["awning", "노란술", "상점"]),
  one(405, "붉은 지붕 황금 테두리", "roof", "solid", ["roof", "금색띠", "처마"]),
  one(406, "푸른 지붕 밝은 무늬", "roof", "solid", ["roof", "보라빛", "장식기와"]),
  one(407, "짙은 푸른 기와지붕", "roof", "solid", ["roof", "남색", "기와"]),
  one(408, "세로로 늘어진 밧줄", "rope", "solid", ["rope", "갈색끈", "수직"]),
  one(409, "촘촘한 목책 울타리", "fence", "solid", ["fence", "나무말뚝", "목재"]),
  one(410, "목책 울타리 오른쪽 굴곡", "fence", "solid", ["fence", "목재", "굽은끝"]),
  one(411, "흩어진 빵 조각", "prop", "solid", ["bread", "음식", "낱개"]),
  one(412, "갈색 선술집 간판", "sign", "solid", ["pub", "주점", "나무표지"]),
  one(413, "회색 십자 구조물", "decoration", "solid", ["cross", "금속", "판독보류"]),
  one(414, "비문 석판 왼쪽 윗돌", "statue", "solid", ["monument", "회색돌", "좌상단"]),
  one(415, "비문 석판 둥근 윗돌", "statue", "solid", ["monument", "회색돌", "상단중앙"]),
  one(416, "비문 석판 오른쪽 윗돌", "statue", "solid", ["monument", "회색돌", "우상단"]),
  one(417, "베이지 천막 왼쪽 지붕", "awning", "solid", ["tent", "천막천", "좌상단"]),
  one(418, "베이지 천막 중앙 지붕", "awning", "solid", ["tent", "천막천", "상단중앙"]),
  one(419, "베이지 천막 오른쪽 지붕", "awning", "solid", ["tent", "천막천", "우상단"]),

  // ── 14행 (인덱스 420-449) ────────────────────────────────────────────
  one(420, "자갈길 서쪽 경계", "terrain", "passable", ["gravel", "잔디경계", "좌측"]),
  one(421, "자갈길 중앙 바닥", "terrain", "passable", ["gravel", "갈색돌", "중앙"]),
  one(422, "자갈길 동쪽 경계", "terrain", "passable", ["gravel", "잔디경계", "우측"]),
  one(423, "모래길 서쪽 경계", "sand", "passable", ["sand", "잔디경계", "좌측"]),
  one(424, "모래길 중앙 바닥", "sand", "passable", ["sand", "베이지", "중앙"]),
  one(425, "모래길 동쪽 경계", "sand", "passable", ["sand", "잔디경계", "우측"]),
  one(426, "검은 바닥 서쪽 금속틀", "floor", "passable", ["floor", "회색테두리", "좌측"]),
  one(427, "검은 바닥 중앙판", "floor", "passable", ["floor", "암색", "중앙"]),
  one(428, "검은 바닥 동쪽 금속틀", "floor", "passable", ["floor", "회색테두리", "우측"]),
  one(429, "보라 바닥 서쪽 회색틀", "floor", "passable", ["purple", "바닥경계", "좌측"]),
  one(430, "보라 바닥 중앙판", "floor", "passable", ["purple", "실내바닥", "중앙"]),
  one(431, "보라 바닥 동쪽 회색틀", "floor", "passable", ["purple", "바닥경계", "우측"]),
  one(432, "초록 이끼 돌벽", "wall", "solid", ["moss", "석조", "녹색"]),
  one(433, "회색 자갈 돌벽", "wall", "solid", ["stone", "회색벽", "거친돌"]),
  one(434, "회색 계단 좌상단", "stairs", "passable", ["stairs", "석재", "대각선"]),
  one(435, "회색 계단 우상단", "stairs", "passable", ["stairs", "석재", "상부"]),
  one(436, "푸른 쌍창 상단", "window", "solid", ["window", "남색", "격자"]),
  one(437, "푸른 기와 벽면", "roof", "solid", ["roof", "청색기와", "건물"]),
  one(438, "목책 울타리 왼쪽 굴곡", "fence", "solid", ["fence", "목재", "굽은끝"]),
  one(439, "갈색 말뚝 울타리", "fence", "solid", ["fence", "나무", "뾰족말뚝"]),
  one(440, "쌓아 둔 장작더미", "prop", "solid", ["firewood", "통나무", "목재"]),
  one(441, "갈색 널빤지 바닥", "floor", "passable", ["wood", "마룻바닥", "판자"]),
  one(442, "청록 병 상점간판", "sign", "solid", ["shop", "물약병", "표지"]),
  one(443, "붉은 글자 여관간판", "sign", "solid", ["inn", "숙소", "표지"]),
  one(444, "비문 석판 왼쪽 몸돌", "statue", "solid", ["monument", "문자무늬", "좌측"]),
  one(445, "비문 석판 중앙 몸돌", "statue", "solid", ["monument", "문자무늬", "중앙"]),
  one(446, "비문 석판 오른쪽 몸돌", "statue", "solid", ["monument", "문자무늬", "우측"]),
  one(447, "천막 입구 왼쪽 휘장", "awning", "solid", ["tent", "베이지천", "좌측"]),
  one(448, "천막 입구 중앙 그늘", "awning", "solid", ["tent", "검은입구", "중앙"]),
  one(449, "천막 입구 오른쪽 휘장", "awning", "solid", ["tent", "베이지천", "우측"]),

  // ── 15행 (인덱스 450-479) ────────────────────────────────────────────
  one(450, "자갈길 남서 경계", "terrain", "passable", ["gravel", "잔디경계", "좌하단"]),
  one(451, "자갈길 남쪽 경계", "terrain", "passable", ["gravel", "잔디경계", "하단"]),
  one(452, "자갈길 남동 경계", "terrain", "passable", ["gravel", "잔디경계", "우하단"]),
  one(453, "모래길 남서 경계", "sand", "passable", ["sand", "잔디경계", "좌하단"]),
  one(454, "모래길 남쪽 경계", "sand", "passable", ["sand", "잔디경계", "하단"]),
  one(455, "모래길 남동 경계", "sand", "passable", ["sand", "잔디경계", "우하단"]),
  one(456, "검은 바닥 남서 금속틀", "floor", "passable", ["floor", "회색테두리", "좌하단"]),
  one(457, "검은 바닥 남쪽 금속틀", "floor", "passable", ["floor", "회색테두리", "하단"]),
  one(458, "검은 바닥 남동 금속틀", "floor", "passable", ["floor", "회색테두리", "우하단"]),
  one(459, "보라 바닥 남서 회색틀", "floor", "passable", ["purple", "바닥경계", "좌하단"]),
  one(460, "보라 바닥 남쪽 회색틀", "floor", "passable", ["purple", "바닥경계", "하단"]),
  one(461, "보라 바닥 남동 회색틀", "floor", "passable", ["purple", "바닥경계", "우하단"]),
  one(462, "돌틈 보라꽃 왼쪽", "plant", "solid", ["flower", "바위틈", "좌측"]),
  one(463, "돌틈 보라꽃 오른쪽", "plant", "solid", ["flower", "바위틈", "우측"]),
  one(464, "회색 계단 좌하단", "stairs", "passable", ["stairs", "석재", "하부"]),
  one(465, "회색 계단 우하단", "stairs", "passable", ["stairs", "난간", "우측"]),
  one(466, "푸른 쌍창 하단", "window", "solid", ["window", "보라유리", "세로창"]),
  one(467, "푸른 기와 흰 테두리", "roof", "solid", ["roof", "남색기와", "아랫띠"]),
  one(468, "나무 아치 왼쪽 기둥", "decoration", "solid", ["arch", "목재", "좌측"]),
  one(469, "나무 아치 중앙 받침", "decoration", "solid", ["arch", "목재", "중앙"]),
  one(470, "나무 아치 오른쪽 기둥", "decoration", "solid", ["arch", "목재", "우측"]),
  one(471, "나무 들보 중앙 돌기", "decoration", "solid", ["beam", "목재", "갈색"]),
  one(472, "보라 병 상점간판", "sign", "solid", ["shop", "물약", "표지"]),
  one(473, "빨간 항아리 상점간판", "sign", "solid", ["shop", "도기", "표지"]),
  one(474, "비문 석판 왼쪽 받침", "statue", "solid", ["monument", "회색돌", "좌하단"]),
  one(475, "비문 석판 중앙 받침", "statue", "solid", ["monument", "회색돌", "하단중앙"]),
  one(476, "비문 석판 오른쪽 받침", "statue", "solid", ["monument", "회색돌", "우하단"]),
  one(477, "천막 왼쪽 휘장 자락", "awning", "solid", ["tent", "베이지천", "좌하단"]),
  one(478, "천막 중앙 어두운 입구", "awning", "solid", ["tent", "검은공간", "하단중앙"]),
  one(479, "천막 오른쪽 휘장 자락", "awning", "solid", ["tent", "베이지천", "우하단"]),
];
