// retro_Exterior(레트로 바깥) 칩셋(tex_easyrpg_chipset_retro_exterior) 타일 그림판의 AI 검색용 큐레이션 시맨틱 테이블.
// 6x 업스케일 행 스트립(.omo/evidence/chipset-strips/retro_exterior/row-00..15.png) 전수 판독으로 작성했다.
// tileSemanticsDungeon.ts / tileSemanticsInterior.ts 와 동일한 계약: tileset.tileMeta[] 와 별개로
// 관리되는 검색 전용 데이터다. 통행성/레이어 계약은 tilesetHarness 가, 타일별 정밀 라벨은 여기가 담당한다.
//
// 좌표 규약: 30타일/행, ID = 행×30 + 열. 아트가 없는 슬롯(완전 투명 또는 분홍 컬러키 단색)은
// 서술할 대상이 없으므로 엔트리를 만들지 않는다 — scripts/verify-tile-semantics.mts 가 픽셀에서
// 그 목록을 직접 구해 커버리지를 검증한다.
// 판독이 애매한 타일은 단정 대신 형태 서술을 쓰고 "판독보류" 태그를 남겼다(실내 465~467 전례).
//
// 실측: 도화 가능 478칸 전수 서술, 고유 라벨 383개.
// 조립: scripts/build-tile-semantics.mts (수기 편집 대신 이 스크립트로 재생성한다).

import type { CombinedTownTileSemanticEntry } from "./tileSemanticsCombinedTown";

export type RetroExteriorTileSemanticEntry = CombinedTownTileSemanticEntry;

function entries(
  indexes: readonly number[],
  label: string,
  role: string,
  passage: "passable" | "solid",
  tags: readonly string[]
): RetroExteriorTileSemanticEntry[] {
  return indexes.map((index) => ({ index, label, role, passage, tags: [label, ...tags] }));
}

function one(
  index: number,
  label: string,
  role: string,
  passage: "passable" | "solid",
  tags: readonly string[]
): RetroExteriorTileSemanticEntry {
  return { index, label, role, passage, tags: [label, ...tags] };
}

export const RETRO_EXTERIOR_TILE_SEMANTICS: readonly RetroExteriorTileSemanticEntry[] = [
  // ── 0행 (인덱스 0-29) ─────────────────────────────────────────────
  ...entries([0, 1, 2], "바닷가 물가 애니메이션", "coast", "solid", ["물", "해안", "애니메이션"]),
  ...entries([3, 4, 5], "바다 물결 애니메이션", "water", "solid", ["물", "바다", "애니메이션"]),
  one(6, "잔디 위 회백색 바위", "rock", "passable", ["돌", "잔디", "바위"]),
  one(7, "푸른 잔디 평지", "terrain", "passable", ["잔디", "바닥", "grass"]),
  one(8, "하얀 벽면", "wall", "solid", ["벽", "하양", "건물"]),
  one(9, "둥근 푸른 나무", "tree", "solid", ["나무", "수풀"]),
  one(10, "잔디 바닥", "terrain", "passable", ["잔디", "바닥"]),
  one(11, "붉은 열매 나무", "tree", "solid", ["나무", "열매", "빨강"]),
  one(12, "갈아엎은 흙밭", "terrain", "passable", ["흙", "밭", "경작지"]),
  one(13, "이랑이 진 흙밭", "terrain", "passable", ["흙", "밭"]),
  one(14, "거친 흙밭", "terrain", "passable", ["흙", "밭"]),
  one(15, "흙과 모래 땅 (상단)", "sand", "passable", ["모래", "흙", "해변"]),
  one(16, "모래밭 (상하 흙 경계)", "sand", "passable", ["모래", "해변"]),
  one(17, "모래밭 (모서리 흙)", "sand", "passable", ["모래", "흙"]),
  one(18, "물 가장자리 (우측 물결)", "water", "solid", ["물", "가장자리", "파도"]),
  one(19, "물 가장자리 (좌우 물결)", "water", "solid", ["물", "가장자리"]),
  one(20, "물 가장자리 (좌측 물결)", "water", "solid", ["물", "가장자리"]),
  one(21, "잔잔한 수면 (얼룩)", "water", "solid", ["물", "수면"]),
  one(22, "잔물결 수면", "water", "solid", ["물", "수면"]),
  one(23, "잔잔한 바닷물", "water", "solid", ["물", "바다"]),
  one(24, "물가 절벽 (잔디 끝)", "cliff", "solid", ["절벽", "물", "잔디"]),
  one(25, "물가 땅 끝 (잔디)", "cliff", "solid", ["절벽", "물", "잔디"]),
  one(26, "물가 푸른 덤불", "tree", "solid", ["수풀", "물", "나무"]),
  one(27, "물가 잔디 절벽", "cliff", "solid", ["절벽", "물", "잔디"]),
  one(28, "물 위 초록 섬", "tree", "solid", ["섬", "물", "수풀"]),
  one(29, "작은 회색 바위", "rock", "solid", ["바위", "돌"]),

  // ── 1행 (인덱스 30-59) ─────────────────────────────────────────────
  ...entries([30, 31, 32], "바닷가 물가 애니메이션", "coast", "solid", ["물", "해안", "애니메이션"]),
  ...entries([33, 34, 35], "바다 물결 애니메이션", "water", "solid", ["물", "바다", "애니메이션"]),
  one(36, "흰 벽 (위 잔디)", "wall", "solid", ["벽", "하양", "건물"]),
  one(37, "흰 벽 (잔디 가장자리)", "wall", "solid", ["벽", "하양"]),
  one(38, "흰 벽 (우하 잔디)", "wall", "solid", ["벽", "하양"]),
  one(39, "붉은 열매 나무", "tree", "solid", ["나무", "열매"]),
  one(40, "울창한 나무", "tree", "solid", ["나무", "수풀"]),
  one(41, "빽빽한 나무 수풀", "tree", "solid", ["나무", "수풀"]),
  one(42, "흙 경작지", "terrain", "passable", ["흙", "밭"]),
  one(43, "트인 흙밭", "terrain", "passable", ["흙", "밭"]),
  one(44, "흙 비탈 경작지", "terrain", "passable", ["흙", "밭"]),
  one(45, "모래밭 (좌측 흙)", "sand", "passable", ["모래", "해변"]),
  one(46, "평평한 모래밭", "sand", "passable", ["모래", "해변", "sand"]),
  one(47, "모래밭 (우측 흙)", "sand", "passable", ["모래", "해변"]),
  one(48, "물가 포말 (우측)", "water", "solid", ["물", "포말"]),
  one(49, "거친 회색 돌절벽", "cliff", "solid", ["절벽", "돌"]),
  one(50, "물가 포말 (좌측)", "water", "solid", ["물", "포말"]),
  one(51, "새파란 바닷물", "water", "solid", ["물", "바다"]),
  one(52, "푸른 수면", "water", "solid", ["물", "수면"]),
  one(53, "깊고 잔잔한 바다", "water", "solid", ["물", "바다"]),
  one(54, "물가 구석 (우하 모서리)", "water", "solid", ["물", "가장자리"]),
  one(55, "물가 구석 (좌상 모서리)", "water", "solid", ["물", "가장자리"]),
  one(56, "물가 구석 (우하 파임)", "water", "solid", ["물", "가장자리"]),
  one(57, "물가 구석 (좌상 파임)", "water", "solid", ["물", "가장자리"]),
  one(58, "물 위 작은 덤불", "tree", "solid", ["섬", "물", "수풀"]),
  one(59, "회색 돌멩이", "rock", "solid", ["돌", "바위"]),

  // ── 2행 (인덱스 60-89) ─────────────────────────────────────────────
  ...entries([60, 61, 62], "바닷가 물가 애니메이션", "coast", "solid", ["물", "해안", "애니메이션"]),
  ...entries([63, 64, 65], "바다 물결 애니메이션", "water", "solid", ["물", "바다", "애니메이션"]),
  one(66, "흰 벽 (좌상 잔디)", "wall", "solid", ["벽", "하양"]),
  one(67, "새하얀 벽", "wall", "solid", ["벽", "하양", "건물"]),
  one(68, "흰 벽 (우측 잔디)", "wall", "solid", ["벽", "하양"]),
  one(69, "무성한 나무", "tree", "solid", ["나무", "수풀"]),
  one(70, "큰 나무 수풀", "tree", "solid", ["나무", "수풀"]),
  one(71, "붉은 열매 수풀", "tree", "solid", ["나무", "열매"]),
  one(72, "마른 흙밭", "terrain", "passable", ["흙", "밭", "dirt"]),
  one(73, "흙과 모래 섞인 밭", "terrain", "passable", ["흙", "모래"]),
  one(74, "새로 간 흙밭", "terrain", "passable", ["흙", "밭"]),
  one(75, "모래밭 (좌측 흙 경계)", "sand", "passable", ["모래", "흙"]),
  one(76, "너른 모래밭", "sand", "passable", ["모래", "해변"]),
  one(77, "모래밭 (우측 흙 경계)", "sand", "passable", ["모래", "흙"]),
  one(78, "물 가장자리 (포말)", "water", "solid", ["물", "가장자리", "포말"]),
  one(79, "이끼 낀 돌절벽", "cliff", "solid", ["절벽", "돌", "이끼"]),
  one(80, "물가 파도 물결", "water", "solid", ["물", "파도"]),
  one(81, "푸른 물 (얼룩)", "water", "solid", ["물", "수면"]),
  one(82, "잔잔한 바다", "water", "solid", ["물", "바다"]),
  one(83, "고요한 물", "water", "solid", ["물", "수면"]),
  one(84, "색색의 꽃밭", "plant", "solid", ["꽃", "화단", "색"]),
  one(85, "주황 줄무늬 천막", "awning", "solid", ["천막", "차양", "시장"]),
  one(86, "돌 우물터", "prop", "solid", ["물", "샘", "원형"]),
  one(87, "파란 줄무늬 차양", "awning", "solid", ["차양", "천막"]),
  one(88, "주황 상자 (청색 무늬)", "crate", "solid", ["상자", "궤짝", "crate"]),
  one(89, "흩어진 밝은 반짝임", "decoration", "solid", ["판독보류", "반짝임", "입자"]),

  // ── 3행 (인덱스 90-119) ─────────────────────────────────────────────
  ...entries([90, 91, 92], "바닷가 물가 애니메이션", "coast", "solid", ["물", "해안", "애니메이션"]),
  ...entries([93, 94, 95], "바다 물결 애니메이션", "water", "solid", ["물", "바다", "애니메이션"]),
  one(96, "흰 벽 (좌측 잔디)", "wall", "solid", ["벽", "하양"]),
  one(97, "흰 벽면 (아래 잔디)", "wall", "solid", ["벽", "하양", "건물"]),
  one(98, "흰 벽 (우하 잔디)", "wall", "solid", ["벽", "하양"]),
  one(99, "짙은 초록 나무", "tree", "solid", ["나무", "수풀"]),
  one(100, "우거진 나무", "tree", "solid", ["나무", "수풀"]),
  one(101, "열매 진 나무", "tree", "solid", ["나무", "열매"]),
  one(102, "적갈색 흙밭", "terrain", "passable", ["흙", "밭"]),
  one(103, "흙밭 (하단 그림자)", "terrain", "passable", ["흙", "밭"]),
  one(104, "갈색 흙밭", "terrain", "passable", ["흙", "밭"]),
  one(105, "흙밭 (어두운 끝)", "terrain", "passable", ["흙", "밭"]),
  one(106, "마른 황토밭", "terrain", "passable", ["흙", "밭"]),
  one(107, "무늬 진 경작지", "terrain", "passable", ["흙", "밭", "무늬"]),
  one(108, "물가 포말 (우상)", "water", "solid", ["물", "포말"]),
  one(109, "물가 포말 (좌상)", "water", "solid", ["물", "포말"]),
  one(110, "물가 포말 (좌측 물결)", "water", "solid", ["물", "포말"]),
  one(111, "갈라진 돌절벽", "cliff", "solid", ["절벽", "돌", "균열"]),
  one(112, "암석 절벽면", "cliff", "solid", ["절벽", "돌"]),
  one(113, "균열 있는 돌벽", "cliff", "solid", ["절벽", "돌"]),
  one(114, "주황 반구형 물체", "prop", "solid", ["판독보류", "주황", "둥근"]),
  one(115, "주황 줄무늬 차양 (우)", "awning", "solid", ["천막", "차양"]),
  one(116, "주황 줄무늬 천막 (좌)", "awning", "solid", ["천막", "차양"]),
  one(117, "흙바닥 지면", "terrain", "passable", ["흙", "바닥"]),
  one(118, "흙 경사면", "terrain", "passable", ["흙", "언덕"]),
  one(119, "청회색 작은 물체", "prop", "solid", ["판독보류", "청색", "작은"]),

  // ── 4행 (인덱스 120-149) ─────────────────────────────────────────────
  one(120, "짙은 남색 창문 3연", "window", "solid", ["창문", "window", "집"]),
  one(121, "남색 창문 3연 밝은틀", "window", "solid", ["창문", "window", "벽"]),
  one(122, "남색 창문 3연 어두운틀", "window", "solid", ["창문", "window", "어두운틀"]),
  one(123, "우물 상단 두레박줄", "prop", "solid", ["우물", "well", "두레박"]),
  one(124, "우물 하단 돌테", "prop", "solid", ["우물", "well", "stone"]),
  one(125, "우물 내부 어둠 오버레이", "prop", "solid", ["우물", "well", "내부"]),
  one(126, "마른 흙바닥 북서 모서리", "terrain", "passable", ["흙", "dirt", "모서리"]),
  one(127, "마른 풀밭 바닥", "terrain", "passable", ["풀", "grass", "황무지"]),
  one(128, "마른 흙바닥 중앙", "terrain", "passable", ["흙", "dirt", "ground"]),
  one(129, "황무지 풀숲", "plant", "passable", ["수풀", "bush", "황무지"]),
  one(130, "마른 풀밭 오버레이", "terrain", "passable", ["풀", "grass", "overlay"]),
  one(131, "마른 수풀 전면 오버레이", "plant", "passable", ["수풀", "bush", "풀숲"]),
  one(132, "울타리 상단 가로대", "fence", "solid", ["울타리", "fence", "나무"]),
  one(133, "울타리 중간 결", "fence", "solid", ["울타리", "fence", "결"]),
  one(134, "울타리 오른쪽 끝", "fence", "solid", ["울타리", "fence", "끝"]),
  one(135, "울타리 왼쪽 끝", "fence", "solid", ["울타리", "fence", "끝"]),
  one(136, "울타리 아래 마감", "fence", "solid", ["울타리", "fence", "하단"]),
  one(137, "흙길 십자 교차로", "path", "passable", ["길", "road", "교차로"]),
  one(138, "자갈바닥 좌측 상단", "floor", "passable", ["자갈", "gravel", "사분면"]),
  one(139, "자갈바닥 우측 상단", "floor", "passable", ["자갈", "gravel", "사분면"]),
  one(140, "자갈바닥 좌측 하단", "floor", "passable", ["자갈", "gravel", "사분면"]),
  one(141, "자갈바닥 우측 하단", "floor", "passable", ["자갈", "gravel", "사분면"]),
  one(142, "자갈 유리창 좌하단", "window", "solid", ["창문", "window", "자갈"]),
  one(143, "자갈 유리창 우하단", "window", "solid", ["창문", "window", "자갈"]),
  one(144, "회색 벽돌벽", "wall", "solid", ["벽", "wall", "brick"]),
  one(145, "나무 문 오른쪽 설계도", "door", "solid", ["door", "문", "blueprint"]),
  one(146, "나무 문 왼쪽 설계도", "door", "solid", ["door", "문", "blueprint"]),
  one(147, "벽 속 빈 틀", "wall", "solid", ["벽", "wall", "빈틀"]),
  one(148, "벽 속 넓은 빈 틀", "wall", "solid", ["벽", "wall", "빈틀"]),
  one(149, "벽 모서리 사선 마감", "wall", "solid", ["벽", "wall", "모서리"]),

  // ── 5행 (인덱스 150-179) ─────────────────────────────────────────────
  one(150, "남색 원형 장식 상단", "decoration", "solid", ["장식", "원형", "만화경"]),
  one(151, "남색 원형 장식 중앙", "decoration", "solid", ["장식", "원형", "패턴"]),
  one(152, "남색 원형 장식 하단", "decoration", "solid", ["장식", "원형", "문양"]),
  one(153, "우물 반복 타일", "prop", "solid", ["우물", "well", "타일"]),
  one(154, "우물 원형 테 두께", "prop", "solid", ["우물", "well", "원형"]),
  one(155, "우물 중앙 결 오버레이", "prop", "solid", ["우물", "well", "중앙"]),
  one(156, "마른 흙 사분면 좌상", "terrain", "passable", ["흙", "dirt", "사분면"]),
  one(157, "마른 흙 사분면 우상", "terrain", "passable", ["흙", "dirt", "사분면"]),
  one(158, "마른 흙 사분면 우하", "terrain", "passable", ["흙", "dirt", "사분면"]),
  one(159, "황무지 수풀 좌상단", "plant", "passable", ["수풀", "bush", "사분면"]),
  one(160, "황무지 수풀 우상단", "plant", "passable", ["수풀", "bush", "사분면"]),
  one(161, "황무지 수풀 우하단", "plant", "passable", ["수풀", "bush", "사분면"]),
  one(162, "나무판 벽 위 홈 3단", "wall", "solid", ["나무벽", "wood", "홈"]),
  one(163, "나무판 벽 아래 홈 3단", "wall", "solid", ["나무벽", "wood", "홈"]),
  one(164, "나무판 벽 오른쪽 연장", "wall", "solid", ["나무벽", "wood", "연장"]),
  one(165, "나무판 벽 왼쪽 연장", "wall", "solid", ["나무벽", "wood", "연장"]),
  one(166, "나무판 벽 중앙 연장", "wall", "solid", ["나무벽", "wood", "연장"]),
  one(167, "울타리 중간 기둥 강조", "fence", "solid", ["울타리", "fence", "기둥"]),
  one(168, "통나무 울타리 위 색띠", "fence", "solid", ["울타리", "fence", "통나무"]),
  one(169, "울타리 몸통 채움", "fence", "solid", ["울타리", "fence", "몸통"]),
  one(170, "울타리 몸통 우측 마감", "fence", "solid", ["울타리", "fence", "마감"]),
  one(171, "울타리 흔적 왼쪽 세로", "fence", "solid", ["울타리", "fence", "잔상"]),
  one(172, "울타리 흔적 중앙 블록", "fence", "solid", ["울타리", "fence", "잔상"]),
  one(173, "울타리 흔적 오른쪽 세로", "fence", "solid", ["울타리", "fence", "잔상"]),
  one(174, "벽돌벽 반짝 광택", "wall", "solid", ["벽", "wall", "광택"]),
  one(175, "벽돌 조각 상부 곡선", "wall", "solid", ["벽돌", "brick", "곡선"]),
  one(176, "벽돌 조각 하부 곡선", "wall", "solid", ["벽돌", "brick", "곡선"]),
  one(177, "안쪽 벽 창문들", "window", "solid", ["창문", "window", "실내"]),
  one(178, "벽 안쪽 후면부", "wall", "solid", ["벽", "wall", "내부"]),
  one(179, "붉은 지붕 하단 처마", "roof", "solid", ["지붕", "roof", "처마"]),

  // ── 6행 (인덱스 180-209) ─────────────────────────────────────────────
  one(180, "짙은 남색 창살 3연", "window", "solid", ["창살", "window", "bar"]),
  one(181, "남색 창살 3연 밝은틀", "window", "solid", ["창살", "window", "bar"]),
  one(182, "남색 창살 3연 어두운틀", "window", "solid", ["창살", "window", "bar"]),
  one(183, "우물 조합 반복 블록", "prop", "solid", ["우물", "well", "반복"]),
  one(184, "우물 외곽 왼쪽 연결", "prop", "solid", ["우물", "well", "외곽"]),
  one(185, "우물 하이라이트", "prop", "solid", ["우물", "well", "highlight"]),
  one(186, "흙길 좌측 상단 코너", "path", "passable", ["길", "road", "코너"]),
  one(187, "흙길 중앙 사분면", "path", "passable", ["길", "road", "사분면"]),
  one(188, "흙길 우하 코너 풀", "path", "passable", ["길", "road", "풀"]),
  one(189, "황무지 풀숲 좌상 코너", "plant", "passable", ["풀숲", "bush", "코너"]),
  one(190, "황무지 풀숲 중앙", "plant", "passable", ["풀숲", "bush", "풀"]),
  one(191, "황무지 풀숲 우하 코너", "plant", "passable", ["풀숲", "bush", "코너"]),
  one(192, "울타리 판금 상단", "fence", "solid", ["울타리", "fence", "판금"]),
  one(193, "울타리 손잡이 돌기", "fence", "solid", ["울타리", "fence", "돌기"]),
  one(194, "울타리 위 기와 얼굴벽", "fence", "solid", ["울타리", "fence", "기와"]),
  one(195, "울타리 위 높은 받침", "fence", "solid", ["울타리", "fence", "받침"]),
  one(196, "울타리 위 회색 지붕", "fence", "solid", ["울타리", "fence", "지붕"]),
  one(197, "울타리 높은 받침 지붕", "fence", "solid", ["울타리", "fence", "지붕"]),
  one(198, "울타리 맞배 좌측 상", "fence", "solid", ["울타리", "fence", "맞배"]),
  one(199, "울타리 맞배 우측 상", "fence", "solid", ["울타리", "fence", "맞배"]),
  one(200, "울타리 맞배 정면", "fence", "solid", ["울타리", "fence", "맞배"]),
  one(201, "회색 포장 반복 블록", "floor", "passable", ["포장", "pavement", "블록"]),
  one(202, "포장 위 원형 문양 상", "floor", "passable", ["포장", "문양", "pattern"]),
  one(203, "포장 위 원형 문양 하", "floor", "passable", ["포장", "문양", "pattern"]),
  one(204, "나무 도어 상부 틀", "door", "solid", ["door", "문", "틀"]),
  one(205, "나무 도어 하부 틀", "door", "solid", ["door", "문", "틀"]),
  one(206, "나무 도어 하부 쐐기", "door", "solid", ["door", "문", "쐐기"]),
  one(207, "나무 도어 박스 문양", "door", "solid", ["door", "문", "문양"]),
  one(208, "참나무 원목 문짝", "door", "solid", ["door", "oak", "원목"]),
  one(209, "원목 판 상단 타일", "floor", "passable", ["원목", "wood", "판"]),

  // ── 7행 (인덱스 210-239) ─────────────────────────────────────────────
  one(210, "짙은 남색 벽돌 상단", "wall", "solid", ["벽돌", "brick", "상단"]),
  one(211, "짙은 남색 벽돌 중앙", "wall", "solid", ["벽돌", "brick", "중앙"]),
  one(212, "짙은 남색 벽돌 하단", "wall", "solid", ["벽돌", "brick", "하단"]),
  one(213, "우물 세로 반복 블록", "prop", "solid", ["우물", "well", "블록"]),
  one(214, "우물 외곽 오른쪽 연결", "prop", "solid", ["우물", "well", "외곽"]),
  one(215, "우물 내부 그림자", "prop", "solid", ["우물", "well", "그림자"]),
  one(216, "흙길 상단 코너 황토", "path", "passable", ["길", "road", "황토"]),
  one(217, "흙길 중앙 황토 블록", "path", "passable", ["길", "road", "황토"]),
  one(218, "흙길 우하 황토 코너", "path", "passable", ["길", "road", "황토"]),
  one(219, "황무지 풀숲 좌상 하이라이트", "plant", "passable", ["풀숲", "bush", "하이라이트"]),
  one(220, "황무지 풀숲 밑동", "plant", "passable", ["풀숲", "bush", "밑동"]),
  one(221, "황무지 풀숲 우하 밑동", "plant", "passable", ["풀숲", "bush", "밑동"]),
  one(222, "울타리 낮은 판 전체", "fence", "solid", ["울타리", "fence", "낮은판"]),
  one(223, "울타리 낮은판 흙받침", "fence", "solid", ["울타리", "fence", "받침"]),
  one(224, "무지개 패널 세로 중앙", "decoration", "solid", ["무지개", "rainbow", "패널"]),
  one(225, "무지개 패널 세로 양옆", "decoration", "solid", ["무지개", "rainbow", "패널"]),
  one(226, "무지개 패널 가로 중앙", "decoration", "solid", ["무지개", "rainbow", "패널"]),
  one(227, "무지개 패널 가로 양옆", "decoration", "solid", ["무지개", "rainbow", "패널"]),
  one(228, "울타리 맞배 좌측 하", "fence", "solid", ["울타리", "fence", "맞배"]),
  one(229, "울타리 맞배 우측 하", "fence", "solid", ["울타리", "fence", "맞배"]),
  one(230, "울타리 맞배 하단 마감", "fence", "solid", ["울타리", "fence", "마감"]),
  one(231, "황금 장식 문양 코인", "decoration", "solid", ["황금", "gold", "장식"]),
  one(232, "포장 바닥 연결부", "floor", "passable", ["포장", "pavement", "연결"]),
  one(234, "울타리 게이트 좌측 문", "gate", "passable", ["게이트", "gate", "문"]),
  one(235, "울타리 게이트 우측 문", "gate", "passable", ["게이트", "gate", "문"]),
  one(236, "울타리 게이트 중앙 문", "gate", "passable", ["게이트", "gate", "문"]),
  one(237, "울타리 이중 십자 결", "fence", "solid", ["울타리", "fence", "십자"]),
  one(238, "참나무 문 상단 이음", "door", "solid", ["door", "oak", "이음"]),
  one(239, "참나무 문 하단 이음", "door", "solid", ["door", "oak", "이음"]),

  // ── 8행 (인덱스 240-269) ─────────────────────────────────────────────
  one(240, "잔디", "terrain", "passable", ["grass", "풀"]),
  one(241, "잔디밭", "terrain", "passable", ["lawn", "잔디", "초원"]),
  one(242, "잔디", "terrain", "passable", ["grass", "들판"]),
  one(243, "꽃 핀 잔디", "terrain", "passable", ["grass", "flower", "꽃", "잔디"]),
  one(244, "잔디밭", "terrain", "passable", ["grass", "잔디", "밭"]),
  one(245, "꽃 핀 잔디", "terrain", "passable", ["grass", "flower", "꽃잔디"]),
  one(246, "돌바닥", "terrain", "passable", ["stone", "돌", "바닥", "포장"]),
  one(247, "잔디", "terrain", "passable", ["grass", "풀밭"]),
  one(248, "돌바닥 자동타일", "terrain", "passable", ["stone", "autotile", "돌"]),
  one(249, "돌바닥", "terrain", "passable", ["stone", "돌", "지면"]),
  one(250, "잔디", "terrain", "passable", ["grass", "초지"]),
  one(251, "돌바닥 경계", "terrain", "passable", ["stone", "edge", "돌", "경계"]),
  one(252, "나무 바닥", "floor", "passable", ["wood", "plank", "판자", "바닥"]),
  one(253, "물", "water", "passable", ["water", "호수"]),
  one(254, "나무 판자", "floor", "passable", ["wood", "plank", "판자", "목재"]),
  one(255, "나무 판자", "floor", "passable", ["wood", "plank", "바닥"]),
  one(256, "목재 바닥", "floor", "passable", ["wood", "deck", "목재", "바닥"]),
  one(257, "목재 바닥", "floor", "passable", ["wood", "deck", "마루"]),
  one(259, "나무 통", "prop", "solid", ["barrel", "통", "나무", "술통"]),
  one(260, "나무", "tree", "solid", ["tree", "숲", "나뭇잎"]),
  one(261, "나무 기둥", "prop", "solid", ["post", "기둥", "목재", "굴뚝"]),
  one(262, "덤불 나무", "tree", "solid", ["tree", "bush", "덤불", "나무"]),
  one(263, "나무", "tree", "solid", ["tree", "잎"]),
  one(264, "흰 구조물", "decoration", "solid", ["white", "구조물", "판독보류"]),
  one(265, "나무 울타리", "fence", "solid", ["fence", "울타리", "나무", "가로대"]),
  one(266, "금속 난간", "fence", "solid", ["railing", "fence", "난간", "철"]),
  one(267, "돌 울타리", "fence", "solid", ["fence", "stone", "울타리", "돌"]),
  one(268, "바위 절벽", "cliff", "solid", ["cliff", "rock", "절벽", "바위"]),
  one(269, "바위 절벽", "cliff", "solid", ["cliff", "rock", "절벽", "암벽"]),

  // ── 9행 (인덱스 270-299) ─────────────────────────────────────────────
  one(270, "잔디", "terrain", "passable", ["grass", "푸른"]),
  one(271, "잔디밭", "terrain", "passable", ["grass", "잔디", "초원"]),
  one(272, "잔디", "terrain", "passable", ["grass", "들"]),
  one(273, "꽃 핀 잔디", "terrain", "passable", ["grass", "flower", "꽃", "잔디"]),
  one(274, "잔디 밭", "terrain", "passable", ["grass", "잔디", "화초"]),
  one(275, "꽃 핀 잔디", "terrain", "passable", ["grass", "flower", "꽃잔디"]),
  one(276, "돌바닥", "terrain", "passable", ["stone", "돌", "바닥"]),
  one(277, "돌바닥 자동타일", "terrain", "passable", ["stone", "autotile", "돌"]),
  one(278, "돌바닥 경계", "terrain", "passable", ["stone", "edge", "돌", "경계"]),
  one(279, "돌바닥", "terrain", "passable", ["stone", "돌", "지면"]),
  one(280, "돌바닥 자동타일", "terrain", "passable", ["stone", "autotile", "지면"]),
  one(281, "돌바닥 경계", "terrain", "passable", ["stone", "edge", "돌"]),
  one(282, "분홍빛 지면", "terrain", "passable", ["pink", "지면", "판독보류"]),
  one(283, "회색 지면", "terrain", "passable", ["grey", "지면", "판독보류"]),
  one(284, "물가 자동타일", "water", "passable", ["water", "shore", "물가", "물"]),
  one(285, "물가 자동타일", "water", "passable", ["water", "shore", "물가", "물가장자리"]),
  one(286, "물가 자동타일", "water", "passable", ["water", "shore", "물가"]),
  one(287, "물가 자동타일", "water", "passable", ["water", "shore", "물", "호숫가"]),
  one(288, "꽃 덤불", "plant", "solid", ["bush", "flower", "꽃", "덤불"]),
  one(289, "덤불", "plant", "solid", ["bush", "수풀"]),
  one(290, "풀 언덕", "cliff", "solid", ["hill", "grass", "언덕", "풀"]),
  one(291, "나무 기둥", "prop", "solid", ["post", "기둥", "나무", "기둥목"]),
  one(292, "흙 비탈", "cliff", "solid", ["slope", "dirt", "비탈", "흙"]),
  one(293, "흙 비탈", "cliff", "solid", ["slope", "dirt", "흙", "둑"]),
  one(294, "흰 구조물", "decoration", "solid", ["white", "구조물", "판독보류"]),
  one(295, "풀 흙 비탈", "cliff", "solid", ["slope", "grass", "비탈", "흙"]),
  one(296, "금속 난간", "fence", "solid", ["railing", "fence", "난간"]),
  one(297, "금속 울타리", "fence", "solid", ["fence", "metal", "울타리", "철"]),
  one(298, "바위 지면", "rock", "passable", ["rock", "stone", "바위", "지면"]),
  one(299, "바위 지면", "rock", "passable", ["rock", "stone", "바위", "돌바닥"]),

  // ── 10행 (인덱스 300-329) ────────────────────────────────────────────
  one(300, "잔디", "terrain", "passable", ["grass"]),
  one(301, "잔디밭", "terrain", "passable", ["grass", "잔디", "초원"]),
  one(302, "잔디", "terrain", "passable", ["grass", "풀"]),
  one(303, "꽃 핀 잔디", "terrain", "passable", ["grass", "flower", "꽃", "잔디"]),
  one(304, "꽃 핀 잔디", "terrain", "passable", ["grass", "flower", "꽃잔디"]),
  one(305, "잔디 밭", "terrain", "passable", ["grass", "잔디", "화초"]),
  one(306, "돌바닥", "terrain", "passable", ["stone", "돌", "바닥"]),
  one(307, "돌바닥 자동타일", "terrain", "passable", ["stone", "autotile", "돌"]),
  one(308, "돌바닥 경계", "terrain", "passable", ["stone", "edge", "돌"]),
  one(309, "돌바닥", "terrain", "passable", ["stone", "돌", "지면"]),
  one(310, "돌바닥 자동타일", "terrain", "passable", ["stone", "autotile"]),
  one(311, "돌바닥 경계", "terrain", "passable", ["stone", "edge", "돌", "경계"]),
  one(312, "돌 바닥", "terrain", "passable", ["stone", "돌", "바닥"]),
  one(313, "돌 포장", "path", "passable", ["stone", "paving", "포장", "돌"]),
  one(314, "돌 포장 길", "path", "passable", ["stone", "path", "포장길", "돌"]),
  one(315, "돌 포장 길", "path", "passable", ["stone", "path", "포장"]),
  one(316, "돌 포장", "path", "passable", ["stone", "paving", "돌길"]),
  one(317, "돌 포장", "path", "passable", ["stone", "paving", "포장", "길"]),
  one(318, "횃불", "torch", "solid", ["torch", "불", "화염"]),
  one(319, "나무 기둥", "prop", "solid", ["post", "기둥", "나무", "말뚝"]),
  one(320, "큰 나무", "tree", "solid", ["tree", "나무", "큰나무"]),
  one(321, "나무 기둥", "prop", "solid", ["post", "기둥", "나무", "줄기"]),
  one(322, "나무 판벽", "fence", "solid", ["panel", "wall", "판벽", "나무"]),
  one(323, "나무 상자", "crate", "solid", ["crate", "box", "상자", "나무"]),
  one(324, "흰 구조물", "decoration", "solid", ["white", "구조물", "판독보류"]),
  one(325, "풀 흙 비탈", "cliff", "solid", ["slope", "grass", "비탈"]),
  one(326, "돌기둥", "pillar", "solid", ["pillar", "stone", "기둥", "돌"]),
  one(327, "나무 판자", "fence", "solid", ["plank", "fence", "판자", "나무"]),
  one(328, "나무 판자", "fence", "solid", ["plank", "fence", "널빤지"]),
  one(329, "검은 바위", "rock", "passable", ["black", "rock", "바위", "판독보류"]),

  // ── 11행 (인덱스 330-359) ────────────────────────────────────────────
  one(330, "잔디", "terrain", "passable", ["grass"]),
  one(331, "잔디밭", "terrain", "passable", ["grass", "잔디", "초원"]),
  one(332, "잔디", "terrain", "passable", ["grass", "풀밭"]),
  one(333, "잔디 밭", "terrain", "passable", ["grass", "잔디", "초지"]),
  one(334, "꽃 핀 잔디", "terrain", "passable", ["grass", "flower", "꽃", "잔디"]),
  one(335, "꽃 핀 잔디", "terrain", "passable", ["grass", "flower", "꽃잔디"]),
  one(336, "돌바닥", "terrain", "passable", ["stone", "돌", "바닥"]),
  one(337, "돌바닥 자동타일", "terrain", "passable", ["stone", "autotile", "돌"]),
  one(338, "돌바닥 경계", "terrain", "passable", ["stone", "edge", "돌", "경계"]),
  one(339, "돌바닥", "terrain", "passable", ["stone", "돌", "지면"]),
  one(340, "돌바닥 자동타일", "terrain", "passable", ["stone", "autotile", "지면"]),
  one(341, "돌바닥 경계", "terrain", "passable", ["stone", "edge", "돌"]),
  one(342, "돌 포장", "path", "passable", ["stone", "paving", "포장", "돌"]),
  one(343, "돌 포장", "path", "passable", ["stone", "paving", "석재"]),
  one(344, "자갈 포장", "path", "passable", ["cobblestone", "gravel", "자갈", "포장"]),
  one(345, "자갈 포장", "path", "passable", ["cobblestone", "gravel", "자갈길"]),
  one(346, "자갈 포장", "path", "passable", ["cobblestone", "gravel", "포장길"]),
  one(347, "자갈 포장", "path", "passable", ["cobblestone", "gravel", "자갈"]),
  one(348, "빨간 배너", "banner", "solid", ["banner", "flag", "배너", "빨간"]),
  one(349, "나무 가판대", "counter", "solid", ["stall", "counter", "가판대", "나무"]),
  one(350, "큰 횃불", "torch", "solid", ["torch", "fire", "횃불", "화로"]),
  one(351, "붉은 천막", "awning", "solid", ["awning", "빨간", "천막", "차양"]),
  one(352, "나무 간판", "sign", "solid", ["sign", "board", "간판", "나무"]),
  one(353, "나무 상자", "crate", "solid", ["crate", "box", "상자", "목상자"]),
  one(354, "초가 지붕", "roof", "solid", ["thatch", "roof", "지붕", "초가"]),
  one(355, "목재 지붕", "roof", "solid", ["wood", "roof", "지붕", "목재"]),
  one(356, "파란 천막", "awning", "solid", ["awning", "blue", "천막", "파란"]),
  one(357, "파란 천막", "awning", "solid", ["awning", "blue", "천막"]),
  one(358, "나무 울타리", "fence", "solid", ["fence", "wood", "울타리", "나무"]),
  one(359, "검은 바위", "rock", "passable", ["black", "rock", "바위", "판독보류"]),

  // ── 12행 (인덱스 360-389) ────────────────────────────────────────────
  one(360, "흙탕 잔디 북서 모서리", "terrain", "passable", ["soil", "grass corner", "바닥"]),
  one(361, "평지 잔디밭", "terrain", "passable", ["grass", "field", "풀판"]),
  one(362, "황토 흙바닥 전체", "terrain", "passable", ["soil", "ground", "땅"]),
  one(363, "모래 북서 잔디 모서리", "sand", "passable", ["sand", "corner", "사구"]),
  one(364, "잔디 우측 모래 경계", "sand", "passable", ["sand", "edge", "경계선"]),
  one(365, "평사장 모래 전체", "sand", "passable", ["sand", "beach", "사장"]),
  one(366, "칠흑 구멍 상단 테두리", "terrain", "solid", ["void", "black", "판독보류"]),
  one(367, "암흑 바닥 전체", "terrain", "solid", ["void", "black", "심연", "판독보류"]),
  one(368, "칠흑 바닥 모서리 조각", "terrain", "solid", ["void", "black", "판독보류"]),
  one(369, "어두운 돌 구덩이 상단", "terrain", "solid", ["dark", "pit", "판독보류"]),
  one(370, "짙은 남청 바닥", "floor", "passable", ["dark", "stone", "돌판"]),
  one(371, "어두운 돌 구덩이 사면", "terrain", "solid", ["dark", "pit", "판독보류"]),
  one(372, "돌밭 보라 꽃포기", "plant", "passable", ["flower", "purple", "꽃"]),
  one(373, "잡석 꽃밭 보라꽃", "plant", "passable", ["flower", "gravel", "꽃밭"]),
  one(374, "초가지붕 용마루", "roof", "solid", ["thatch", "ridge", "지붕"]),
  one(375, "초가지붕 가로 띠", "roof", "solid", ["thatch", "stripe", "지붕"]),
  one(376, "초가지붕 세로 이음", "roof", "solid", ["thatch", "seam", "지붕"]),
  one(377, "짚지붕 붉은 띠 무늬", "roof", "solid", ["thatch", "red band", "처마"]),
  one(378, "석벽 덩굴 우측 상단", "wall", "solid", ["stone", "vine", "넝쿨"]),
  one(379, "석벽 넝쿨 점무늬", "wall", "solid", ["stone", "ivy", "덩굴"]),
  one(380, "석벽 덩굴 좌측 하단", "wall", "solid", ["stone", "vine", "넝쿨"]),
  one(381, "석벽 노란 등불 얼룩", "torch", "solid", ["lamp", "light", "판독보류"]),
  one(382, "석벽 검은 균열 무늬", "wall", "solid", ["stone", "crack", "금"]),
  one(383, "석벽 크림색 창문", "window", "solid", ["stone", "window", "창"]),
  one(384, "짚지붕 모서리 우상 꺾임", "roof", "solid", ["thatch", "corner", "벽"]),
  one(385, "짚지붕 모서리 좌하 꺾임", "roof", "solid", ["thatch", "corner", "벽"]),
  one(386, "푸른 지붕 꺾임 우상", "roof", "solid", ["blue", "roof", "벽"]),
  one(387, "푸른 지붕 꺾임 좌하", "roof", "solid", ["blue", "roof", "벽"]),
  one(388, "석벽 나무 문짝", "door", "solid", ["wood", "door", "출입구"]),
  one(389, "석벽 밑 밀짚 단", "decoration", "solid", ["straw", "hay", "판독보류"]),

  // ── 13행 (인덱스 390-419) ────────────────────────────────────────────
  one(390, "흙 위 잔디 북쪽 경계", "terrain", "passable", ["soil", "grass edge", "바닥"]),
  one(391, "밭흙 바닥 전체", "terrain", "passable", ["soil", "field", "땅"]),
  one(392, "흙 남동 잔디 경계", "terrain", "passable", ["soil", "grass edge", "모서리"]),
  one(393, "모래 사선 북서 경계", "sand", "passable", ["sand", "diagonal", "사구"]),
  one(394, "모래밭 잔디 구석", "sand", "passable", ["sand", "corner", "풀"]),
  one(395, "모래 서쪽 경계", "sand", "passable", ["sand", "edge", "가장자리"]),
  one(396, "칠흑 북서 프레임", "terrain", "solid", ["void", "frame", "판독보류"]),
  one(397, "암흑 상단 경계", "terrain", "solid", ["void", "border", "심연", "판독보류"]),
  one(398, "칠흑 북동 프레임", "terrain", "solid", ["void", "frame", "판독보류"]),
  one(399, "구덩이 북쪽 어두운 벽", "terrain", "solid", ["pit", "dark", "판독보류"]),
  one(400, "어두운 돌바닥 전체", "floor", "passable", ["dark", "stone", "바닥"]),
  one(401, "구덩이 동쪽 경계", "terrain", "solid", ["pit", "dark", "판독보류"]),
  one(402, "풀꽃 핀 돌밭", "plant", "passable", ["flower", "grass", "풀"]),
  one(403, "잡초 무성한 흙", "plant", "passable", ["weed", "soil", "수풀"]),
  one(404, "초가지붕 상단 밑", "roof", "solid", ["thatch", "upper", "지붕"]),
  one(405, "초가지붕 처마 끝", "roof", "solid", ["thatch", "eave", "밑단"]),
  one(406, "초가지붕 이음 처마", "roof", "solid", ["thatch", "seam", "밑단"]),
  one(407, "짚지붕 처마", "roof", "solid", ["thatch", "red", "밑단"]),
  one(408, "석벽 중앙 덩굴 기둥", "wall", "solid", ["stone", "vine", "넝쿨"]),
  one(409, "석벽 넝쿨 격자 무늬", "wall", "solid", ["stone", "ivy", "덩굴"]),
  one(410, "석벽 덩굴 좌측 상단", "wall", "solid", ["stone", "vine", "넝쿨"]),
  one(411, "석벽 작은 창 불빛", "window", "solid", ["window", "glow", "판독보류"]),
  one(412, "석제 화단 흙 가운데", "prop", "solid", ["planter", "stone", "바닥"]),
  one(413, "석벽 목재 골조 틀", "wall", "solid", ["wood", "frame", "판독보류"]),
  one(414, "석벽 어두운 사선 그림자", "wall", "solid", ["stone", "shadow", "사선"]),
  one(415, "자갈돌 벽면 전체", "wall", "solid", ["gravel", "wall", "돌"]),
  one(416, "자갈 벽 어두운 사선 좌", "wall", "solid", ["gravel", "shadow", "돌"]),
  one(417, "석벽 모래 사선 우상", "wall", "solid", ["sand", "stone", "사선"]),
  one(418, "모래 언덕 상단 경계", "sand", "passable", ["dune", "edge", "능선"]),
  one(419, "석벽 모래 사선 좌하", "wall", "solid", ["sand", "stone", "사선"]),

  // ── 14행 (인덱스 420-449) ────────────────────────────────────────────
  one(420, "흙 서쪽 잔디 경계", "terrain", "passable", ["soil", "edge", "바닥"]),
  one(421, "오솔길 흙바닥", "path", "passable", ["trail", "dirt", "길"]),
  one(422, "흙 동쪽 잔디 경계", "terrain", "passable", ["soil", "edge", "모서리"]),
  one(423, "모래밭 서쪽 가장자리", "sand", "passable", ["sand", "border", "사구"]),
  one(424, "고운 모래밭 전체", "sand", "passable", ["sand", "flat", "사장"]),
  one(425, "모래 동쪽 잔디 경계", "sand", "passable", ["sand", "edge", "가장자리"]),
  one(426, "칠흑 서쪽 경계", "terrain", "solid", ["void", "border", "판독보류"]),
  one(427, "암흑 중앙 면", "terrain", "solid", ["void", "black", "심연", "판독보류"]),
  one(428, "칠흑 동쪽 경계", "terrain", "solid", ["void", "border", "판독보류"]),
  one(429, "구덩이 서쪽 경계", "terrain", "solid", ["pit", "dark", "판독보류"]),
  one(430, "어두운 암반 바닥", "floor", "passable", ["rock", "dark", "바닥"]),
  one(431, "구덩이 남동 모서리", "terrain", "solid", ["pit", "dark", "판독보류"]),
  one(432, "어두운 자갈바닥 흩어짐", "floor", "passable", ["gravel", "dark", "자갈"]),
  one(433, "어두운 자갈 조밀 무늬", "floor", "passable", ["gravel", "dense", "자갈"]),
  one(434, "돌계단 난간 좌측", "stairs", "solid", ["stone", "railing", "계단", "판독보류"]),
  one(435, "돌계단 난간 우측", "stairs", "solid", ["stone", "railing", "계단", "판독보류"]),
  one(436, "푸른 지붕 물결 골", "roof", "solid", ["blue", "ripple", "판독보류"]),
  one(437, "푸른 지붕 기와 무늬", "roof", "solid", ["blue", "tile", "지붕"]),
  one(438, "석벽 흙 얼룩 중앙", "wall", "solid", ["stone", "dirt spot", "얼룩"]),
  one(439, "석벽 흙 점무늬 벽", "wall", "solid", ["stone", "dirt spot", "벽"]),
  one(440, "석벽 큰 흙 얼룩", "wall", "solid", ["stone", "dirt spot", "넓은"]),
  one(441, "황토 길 바닥", "path", "passable", ["dirt", "road", "길"]),
  one(442, "석제 분수 물", "water", "solid", ["fountain", "stone", "물"]),
  one(443, "석제 화단 붉은 꽃", "plant", "solid", ["planter", "red flower", "꽃"]),
  one(444, "바위 절벽 좌측 자갈면", "cliff", "solid", ["rock", "gravel", "암벽"]),
  one(445, "자갈 절벽 온전 면", "cliff", "solid", ["gravel", "cliff", "암벽"]),
  one(446, "바위 절벽 우측 자갈면", "cliff", "solid", ["rock", "gravel", "암벽"]),
  one(447, "절벽 사면 좌측 검댓", "cliff", "solid", ["cliff", "dark slope", "바위"]),
  one(448, "절벽 층단 단면 전체", "cliff", "solid", ["cliff", "strata", "바위"]),
  one(449, "절벽 사면 우측 검댓", "cliff", "solid", ["cliff", "dark slope", "바위"]),

  // ── 15행 (인덱스 450-479) ────────────────────────────────────────────
  one(450, "흙 아래 잔디 남쪽 경계", "terrain", "passable", ["soil", "grass edge", "바닥"]),
  one(451, "흙 남서 잔디 모서리", "terrain", "passable", ["soil", "corner", "모서리"]),
  one(452, "흙 남동 잔디 모서리", "terrain", "passable", ["soil", "corner", "가장자리"]),
  one(453, "모래 남서 잔디 모서리", "sand", "passable", ["sand", "corner", "사구"]),
  one(454, "모래사장 안쪽 면", "sand", "passable", ["sand", "inner", "사장"]),
  one(455, "모래 남동 잔디 경계", "sand", "passable", ["sand", "edge", "가장자리"]),
  one(456, "칠흑 남서 하단 경계", "terrain", "solid", ["void", "border", "판독보류"]),
  one(457, "칠흑 남쪽 하단 경계", "terrain", "solid", ["void", "border", "심연", "판독보류"]),
  one(458, "칠흑 남동 하단 경계", "terrain", "solid", ["void", "border", "판독보류"]),
  one(459, "구덩이 남쪽 테두리", "terrain", "solid", ["pit", "dark", "판독보류"]),
  one(460, "어두운 바닥 하단", "floor", "passable", ["dark", "stone", "바닥"]),
  one(461, "구덩이 남서 테두리", "terrain", "solid", ["pit", "dark", "판독보류"]),
  one(462, "어두운 땅 하얀 돌무리 좌", "rock", "passable", ["pale stone", "dark", "돌"]),
  one(463, "어두운 땅 하얀 돌무리 우", "rock", "passable", ["pale stone", "dark", "돌"]),
  one(464, "돌계단 상부 난간 좌", "stairs", "solid", ["stone", "railing", "계단", "판독보류"]),
  one(465, "돌계단 상부 난간 우", "stairs", "solid", ["stone", "railing", "계단", "판독보류"]),
  one(466, "푸른 지붕 물결 처마", "roof", "solid", ["blue", "ripple", "판독보류"]),
  one(467, "푸른 지붕 기와 처마", "roof", "solid", ["blue", "tile", "밑단"]),
  one(468, "석벽 담쟁이 넝쿨 좌", "wall", "solid", ["ivy", "stone", "덩굴"]),
  one(469, "석벽 담쟁이 넝쿨 중앙", "wall", "solid", ["ivy", "stone", "넝쿨"]),
  one(470, "석벽 넝쿨 열매 우측", "wall", "solid", ["ivy", "berry", "판독보류"]),
  one(471, "석벽 위 흙 가장자리", "wall", "solid", ["stone", "soil top", "윗변"]),
  one(472, "석제 수조 나무판", "prop", "solid", ["basin", "wood", "수조"]),
  one(473, "석제 화단 진홍 꽃", "plant", "solid", ["planter", "crimson", "꽃"]),
  one(474, "절벽 하단 어두운 사면", "cliff", "solid", ["cliff", "dark", "바위"]),
  one(475, "절벽 층 아래 검은 층", "cliff", "solid", ["cliff", "strata", "흑색"]),
  one(476, "절벽 자갈 대각 사면", "cliff", "solid", ["cliff", "gravel", "암벽"]),
  one(477, "절벽 모서리 모래층 우", "cliff", "solid", ["cliff", "sand layer", "모서리"]),
  one(478, "검은 절벽 위 돌 하단", "cliff", "solid", ["cliff", "dark", "하단"]),
  one(479, "절벽 모서리 모래층 좌", "cliff", "solid", ["cliff", "sand layer", "모서리"]),
];
