// retro_House(레트로 집) 칩셋(tex_easyrpg_chipset_retro_house) 타일 그림판의 AI 검색용 큐레이션 시맨틱 테이블.
// 이 파일은 생성물이다 — 수기 편집 대신 scripts/build-tile-semantics.mts 로 재생성한다.
// 판독 절차(지어낸 이름이 아니라 실제 통산 과정):
//   1. gen-chipset-blocks.mts 가 4행을 경계선 없는 연속 30x4 아틀라스로 굽는다.
//      격자선을 그리지 않는 이유: 여러 칸에 걸친 물건을 다시 쪼개 놓으면 그게 그대로 오독이 된다.
//   2. 인덱스 확인은 gen-chipset-strips.mts 의 숫자 라벨로만 한다(스트립은 세로 연속성을 끊는다).
//   3. 서로 모르는 판독자 2명 이상이 독립 서술하고 role 다수결로 정리한다.
//      픽셀이 거의 같은 시트(retro_exterior/retro_house, RGB 차이 0.4%)는 판독을 합치므로 한 칸에 최대 4표다.
//   4. 다수결이 이전 라벨과 어긋나는 칸만 교정한다. 갈리는 칸은 그대로 둔다 —
//      지울 수 없는 칸을 지어내는 것이 이 테이블을 무너뜨렸던 원인이다. 보류 목록은 tile-reaudit/splits.txt.
//   5. 사람이 14~20배 크롭으로 확인한 칸은 overrides.json 이 다수결을 이긴다
//      (판독자 전원이 틀린 사례가 있었다 — 125/155/185/215 는 바닥이 아니라 석조 틀 유리창이다).
// tileSemanticsDungeon.ts / tileSemanticsInterior.ts 와 동일한 계약: tileset.tileMeta[] 와 별개로
// 관리되는 검색 전용 데이터다. 통행성/레이어 계약은 tilesetHarness 가, 타일별 정밀 라벨은 여기가 담당한다.
//
// 좌표 규약: 30타일/행, ID = 행×30 + 열. 아트가 없는 슬롯(완전 투명 또는 분홍 컬러키 단색)은
// 서술할 대상이 없으므로 엔트리를 만들지 않는다 — scripts/verify-tile-semantics.mts 가 픽셀에서
// 그 목록을 직접 구해 커버리지를 검증한다.
// 도화 가능 여부는 상수가 아니라 PNG 에서 직접 유도한다(불투명·비키색 픽셀이 하나라도 있는가).
//
// 실측: 도화 가능 478칸 전수 서술, 고유 라벨 431개.
// 조립: scripts/build-tile-semantics.mts (수기 편집 대신 이 스크립트로 재생성한다).

import type { CombinedTownTileSemanticEntry } from "./tileSemanticsCombinedTown";

export type RetroHouseTileSemanticEntry = CombinedTownTileSemanticEntry;

function entries(
  indexes: readonly number[],
  label: string,
  role: string,
  passage: "passable" | "solid",
  tags: readonly string[]
): RetroHouseTileSemanticEntry[] {
  return indexes.map((index) => ({ index, label, role, passage, tags: [label, ...tags] }));
}

function one(
  index: number,
  label: string,
  role: string,
  passage: "passable" | "solid",
  tags: readonly string[]
): RetroHouseTileSemanticEntry {
  return { index, label, role, passage, tags: [label, ...tags] };
}

export const RETRO_HOUSE_TILE_SEMANTICS: readonly RetroHouseTileSemanticEntry[] = [
  // ── 0행 (인덱스 0-29) ─────────────────────────────────────────────
  one(0, "물가 상단 프레임 1", "water", "solid", ["water", "물", "잔디 물가 물 오토타일", "연못"]),
  one(1, "물가 상단 프레임 2", "water", "solid", ["water", "물", "잔디 물가 물 오토타일", "연못"]),
  one(2, "물가 상단 프레임 3", "water", "solid", ["water", "물", "잔디 물가 물 오토타일", "연못"]),
  one(3, "석조 수로 상단 프레임 1", "water", "passable", ["water", "수로 물", "물", "석조 수로"]),
  one(4, "석조 수로 상단 프레임 2", "water", "passable", ["water", "수로 물", "물", "석조 수로"]),
  one(5, "석조 수로 상단 프레임 3", "water", "passable", ["water", "수로 물", "물", "석조 수로"]),
  one(6, "잔디 위 작은 눈밭", "terrain", "passable", ["terrain", "눈 덮인 잔디", "눈", "눈밭"]),
  one(7, "고른 연두 잔디", "terrain", "passable", ["grass", "잔디밭", "초원"]),
  one(8, "잔디 위 둥근 눈밭", "terrain", "passable", ["terrain", "눈밭 상단", "눈밭", "눈"]),
  one(9, "잔디 위 작은 덤불", "tree", "solid", ["plant", "작은 수풀", "관목", "덤불"]),
  one(10, "고른 연두 잔디", "terrain", "passable", ["grass", "초원", "평지"]),
  one(11, "잔디 위 둥근 덤불", "tree", "solid", ["plant", "짙은 수풀", "관목", "덤불"]),
  one(12, "목조 벽돌벽 상단 좌측 보", "wall", "solid", ["wall", "목조 벽돌 벽 상단 좌측", "목조 기둥 상단", "목조 보"]),
  one(13, "목조 벽돌벽 상단 중앙 보", "wall", "solid", ["wall", "목조 벽돌 벽 상단 중앙", "목조 보 상단", "목조 보"]),
  one(14, "목조 벽돌벽 상단 우측 보", "wall", "solid", ["wall", "목조 벽돌 벽 상단 우측", "목조 기둥 상단", "목조 보"]),
  one(15, "목조 회벽 상단 좌측 보", "wall", "solid", ["wall", "목조 회벽 상단 좌측", "목조 기둥 상단", "목조 보"]),
  one(16, "목조 회벽 상단 중앙 보", "wall", "solid", ["wall", "목조 회벽 상단 중앙", "목조 보 상단", "목조 보"]),
  one(17, "목조 회벽 상단 우측 보", "wall", "solid", ["wall", "목조 회벽 상단 우측", "목조 기둥 상단", "목조 보"]),
  one(18, "왼쪽 잿빛 석벽", "wall", "solid", ["wall", "석조", "회색"]),
  one(19, "석조 아치문 상단 중앙", "wall", "solid", ["wall", "성벽 다리 통로 상단", "성문 상부 아치", "석조 아치문"]),
  one(20, "오른쪽 잿빛 석벽", "wall", "solid", ["wall", "석조", "회색"]),
  one(21, "왼쪽 어두운 석벽", "wall", "solid", ["wall", "어두운돌", "벽"]),
  one(22, "오른쪽 어두운 석벽", "wall", "solid", ["wall", "짙은벽", "석재"]),
  one(23, "가운데 어두운 석벽", "wall", "solid", ["wall", "어두운돌", "벽면"]),
  one(24, "원형 돌 우물 상단 좌측", "prop", "solid", ["prop", "석조 우물 상단 좌측", "우물 상단 좌측", "돌 우물"]),
  one(25, "원형 돌 우물 상단 우측", "prop", "solid", ["prop", "석조 우물 상단 우측", "우물 상단 우측", "돌 우물"]),
  one(26, "석조 화덕 상단 좌측", "prop", "solid", ["prop", "돌 구덩이", "석조 화덕", "검게 찬 원형 돌 구덩이"]),
  one(27, "석조 화덕 상단 우측", "prop", "solid", ["prop", "돌 구덩이", "석조 화덕", "검게 찬 원형 돌 구덩이"]),
  one(28, "묘비", "prop", "solid", ["prop"]),
  one(29, "자수정 원석", "rock", "solid", ["rock", "광석 더미", "돌 무더기", "바위 더미"]),

  // ── 1행 (인덱스 30-59) ─────────────────────────────────────────────
  one(30, "세로 수로 물 프레임 1", "water", "passable", ["water", "수로 물", "물", "잔디 물가 물 오토타일"]),
  one(31, "세로 수로 물 프레임 2", "water", "passable", ["water", "수로 물", "물", "잔디 물가 물 오토타일"]),
  one(32, "세로 수로 물 프레임 3", "water", "passable", ["water", "수로 물", "물", "잔디 물가 물 오토타일"]),
  one(33, "석조 세로 수로 물 프레임 1", "water", "passable", ["water", "수로 물", "물", "석조 수로"]),
  one(34, "석조 세로 수로 물 프레임 2", "water", "passable", ["water", "수로 물", "물", "석조 수로"]),
  one(35, "석조 세로 수로 물 프레임 3", "water", "passable", ["water", "수로 물", "물", "석조 수로"]),
  one(36, "눈밭 가장자리 좌상단", "terrain", "passable", ["terrain", "눈밭 좌상단", "눈", "눈밭"]),
  one(37, "눈밭 가장자리 상단", "terrain", "passable", ["terrain", "눈밭 상단", "눈", "눈밭"]),
  one(38, "눈밭 가장자리 우상단", "terrain", "passable", ["terrain", "눈밭 우상단", "눈", "눈밭"]),
  one(39, "덤불 가장자리 좌상단", "tree", "solid", ["plant", "숲 캐노피 좌상단", "덤불 좌상단", "덤불"]),
  one(40, "덤불 가장자리 상단", "tree", "solid", ["plant", "숲 캐노피 상단", "덤불 상단", "덤불"]),
  one(41, "덤불 가장자리 우상단", "tree", "solid", ["plant", "숲 캐노피 우상단", "덤불 우상단", "덤불"]),
  one(42, "목조 벽돌벽 중간 좌측 기둥", "wall", "solid", ["wall", "목조 기둥 석벽 좌측", "목조 벽돌 벽 좌측", "돌 벽"]),
  one(43, "목조 벽돌벽 중간 벽돌", "wall", "solid", ["wall", "벽돌 벽 중앙", "석조 벽", "돌 벽"]),
  one(44, "목조 벽돌벽 중간 우측 기둥", "wall", "solid", ["wall", "목조 기둥 석벽 우측", "목조 벽돌 벽 우측", "돌 벽"]),
  one(45, "목조 회벽 중간 좌측 기둥", "wall", "solid", ["wall", "목조 기둥 회벽 좌측", "목조 회벽 좌측", "회벽"]),
  one(46, "목조 회벽 중간 회벽", "wall", "solid", ["wall", "회반죽 벽", "회벽 중앙", "회벽"]),
  one(47, "목조 회벽 중간 우측 기둥", "wall", "solid", ["wall", "목조 기둥 회벽 우측", "목조 회벽 우측", "회벽"]),
  one(48, "석조 아치문 좌측 기둥", "wall", "solid", ["wall", "성문 통로 좌측 벽", "석조 난간 좌측", "석조 아치문"]),
  one(49, "석조 아치문 통로 바닥 상단", "floor", "passable", ["floor", "성문 통로 바닥", "성벽 다리 바닥", "석조 아치문 통로"]),
  one(50, "석조 아치문 우측 기둥", "wall", "solid", ["wall", "성문 통로 우측 벽", "석조 난간 우측", "석조 아치문"]),
  one(51, "왼쪽 짙은 석벽", "wall", "solid", ["wall", "짙은돌", "벽"]),
  one(52, "가운데 짙은 석벽", "wall", "solid", ["wall", "어두운돌", "벽면"]),
  one(53, "오른쪽 짙은 석벽", "wall", "solid", ["wall", "짙은벽", "석재"]),
  one(54, "원형 돌 우물 하단 좌측", "prop", "solid", ["prop", "석조 우물 하단 좌측", "우물 하단 좌측", "돌 우물"]),
  one(55, "원형 돌 우물 하단 우측", "prop", "solid", ["prop", "석조 우물 하단 우측", "우물 하단 우측", "돌 우물"]),
  one(56, "눈 덮인 석조 우물 하단 좌측", "prop", "solid", ["prop", "석조 화덕 하단 좌측", "돌 구덩이", "눈 덮인 석조 우물"]),
  one(57, "눈 덮인 석조 우물 하단 우측", "prop", "solid", ["prop", "석조 화덕 하단 우측", "돌 구덩이", "눈 덮인 석조 우물"]),
  one(58, "철제 격자문", "gate", "solid", ["gate", "철창 문"]),
  one(59, "작은 광석 더미", "rock", "solid", ["rock", "작은 돌과 자갈", "자수정 결정", "작은 돌더미"]),

  // ── 2행 (인덱스 60-89) ─────────────────────────────────────────────
  one(60, "가로 수로 물 프레임 1", "water", "passable", ["water", "수로 물", "물", "잔디 물가 물 오토타일"]),
  one(61, "가로 수로 물 프레임 2", "water", "passable", ["water", "수로 물", "물", "잔디 물가 물 오토타일"]),
  one(62, "가로 수로 물 프레임 3", "water", "passable", ["water", "수로 물", "물", "잔디 물가 물 오토타일"]),
  one(63, "석조 가로 수로 물 프레임 1", "water", "passable", ["water", "수로 물", "물", "석조 수로"]),
  one(64, "석조 가로 수로 물 프레임 2", "water", "passable", ["water", "수로 물", "물", "석조 수로"]),
  one(65, "석조 가로 수로 물 프레임 3", "water", "passable", ["water", "수로 물", "물", "석조 수로"]),
  one(66, "눈밭 가장자리 좌측", "terrain", "passable", ["terrain", "눈밭 좌측", "눈", "눈밭"]),
  one(67, "눈밭 중앙", "terrain", "passable", ["terrain", "눈 바닥", "눈밭", "눈"]),
  one(68, "눈밭 가장자리 우측", "terrain", "passable", ["terrain", "눈밭 우측", "눈", "눈밭"]),
  one(69, "덤불 가장자리 좌측", "tree", "solid", ["plant", "숲 캐노피 좌측", "덤불 좌측", "덤불"]),
  one(70, "숲 캐노피 중앙", "tree", "solid", ["plant", "덤불 중앙", "덤불", "숲"]),
  one(71, "덤불 가장자리 우측", "tree", "solid", ["plant", "숲 캐노피 우측", "덤불 우측", "덤불"]),
  one(72, "목조 벽돌벽 하단 좌측 기둥", "wall", "solid", ["wall", "목조 벽돌 벽 하단 좌측", "목조 기둥 석벽 좌측", "돌 벽"]),
  one(73, "목조 벽돌벽 하단 벽돌", "wall", "solid", ["wall", "벽돌 벽 하단 중앙", "석조 벽", "돌 벽"]),
  one(74, "목조 벽돌벽 하단 우측 기둥", "wall", "solid", ["wall", "목조 벽돌 벽 하단 우측", "목조 기둥 석벽 우측", "돌 벽"]),
  one(75, "목조 회벽 하단 좌측 기둥", "wall", "solid", ["wall", "목조 기둥 회벽 좌측", "목조 회벽 하단 좌측", "회벽"]),
  one(76, "목조 회벽 하단 회벽", "wall", "solid", ["wall", "회벽 하단 중앙", "회반죽 벽", "회벽"]),
  one(77, "목조 회벽 하단 우측 기둥", "wall", "solid", ["wall", "목조 기둥 회벽 우측", "목조 회벽 하단 우측", "회벽"]),
  one(78, "석조 아치문 하단 좌측 기둥", "wall", "solid", ["wall", "성벽 다리 기둥 좌측", "성문 하단 좌측 벽", "석조 아치문"]),
  one(79, "석조 아치문 통로 바닥 하단", "floor", "passable", ["floor", "성문 바닥 통로", "다리 밑 통로", "석조 아치문 통로"]),
  one(80, "석조 아치문 하단 우측 기둥", "wall", "solid", ["wall", "성벽 다리 기둥 우측", "성문 하단 우측 벽", "석조 아치문"]),
  one(81, "왼쪽 어두운 돌벽", "wall", "solid", ["wall", "어두운돌", "벽"]),
  one(82, "가운데 어두운 돌벽", "wall", "solid", ["wall", "짙은돌", "석조"]),
  one(83, "오른쪽 어두운 돌벽", "wall", "solid", ["wall", "어두운돌", "벽면"]),
  one(84, "다채로운 보석 더미", "prop", "solid", ["prop", "물품 더미", "보석 더미", "천 더미"]),
  one(85, "목재 격자 창문", "window", "solid", ["window", "격자 창문", "나무 창문", "창문"]),
  one(86, "커튼 달린 목재 창문", "window", "solid", ["window", "커튼 창문", "창문"]),
  one(87, "뾰족한 유리창", "window", "solid", ["window", "창틀", "뾰족"]),
  one(88, "닫힌 목재 덧문 창문", "window", "solid", ["window", "나무 덧문 창문"]),
  one(89, "얼음 파편", "decoration", "solid", ["decoration", "물방울"]),

  // ── 3행 (인덱스 90-119) ─────────────────────────────────────────────
  one(90, "깊은 수면 물 프레임 1", "water", "passable", ["water", "깊은 물", "물", "연못"]),
  one(91, "깊은 수면 물 프레임 2", "water", "passable", ["water", "깊은 물", "물", "연못"]),
  one(92, "깊은 수면 물 프레임 3", "water", "passable", ["water", "깊은 물", "물", "연못"]),
  one(93, "석조 수로 깊은 물 프레임 1", "water", "passable", ["water", "깊은 수로 물", "수로 물", "물"]),
  one(94, "석조 수로 깊은 물 프레임 2", "water", "passable", ["water", "깊은 수로 물", "수로 물", "물"]),
  one(95, "석조 수로 깊은 물 프레임 3", "water", "passable", ["water", "깊은 수로 물", "수로 물", "물"]),
  one(96, "눈밭 가장자리 좌하단", "terrain", "passable", ["terrain", "눈밭 좌하단", "눈", "눈밭"]),
  one(97, "눈밭 가장자리 하단", "terrain", "passable", ["terrain", "눈밭 하단", "눈", "눈밭"]),
  one(98, "눈밭 가장자리 우하단", "terrain", "passable", ["terrain", "눈밭 우하단", "눈", "눈밭"]),
  one(99, "덤불 가장자리 좌하단", "tree", "solid", ["plant", "숲 캐노피 좌하단", "덤불 좌하단", "덤불"]),
  one(100, "덤불 가장자리 하단", "tree", "solid", ["plant", "숲 캐노피 하단", "덤불 하단", "덤불"]),
  one(101, "덤불 가장자리 우하단", "tree", "solid", ["plant", "숲 캐노피 우하단", "덤불 우하단", "덤불"]),
  ...entries([102, 103, 104, 105, 106], "통나무 벽 상단", "wall", "solid", ["wall", "나무 판자 벽", "통나무 벽", "가로 통나무 벽면"]),
  one(107, "목재 격자 트렐리스", "fence", "solid", ["fence", "격자 울타리"]),
  one(108, "왼쪽 짙은 석벽", "wall", "solid", ["wall", "짙은돌", "벽"]),
  one(109, "가운데 짙은 석벽", "wall", "solid", ["wall", "회색돌", "벽면"]),
  one(110, "오른쪽 짙은 석벽", "wall", "solid", ["wall", "어두운돌", "벽"]),
  one(111, "석조 기둥 벽 좌측", "wall", "solid", ["wall", "석조 벽 하단 좌측", "석벽 하단 좌측", "낮은 돌담"]),
  one(112, "석조 판석 벽 중앙", "wall", "solid", ["wall", "석조 벽 하단 중앙", "석벽 하단 중앙", "낮은 돌담"]),
  one(113, "석조 기둥 벽 우측", "wall", "solid", ["wall", "석조 벽 하단 우측", "석벽 하단 우측", "낮은 돌담"]),
  one(114, "둥근 나무 받침대", "furniture", "solid", ["furniture", "둥근 목재 탁자", "원형 나무 탁자", "원형 탁자"]),
  one(115, "목재 격자 창문 우측", "window", "solid", ["window", "목재 창문 좌측", "나무 창문 좌측", "창문"]),
  one(116, "나무 문", "door", "solid", ["door", "목재 문"]),
  one(117, "목재 서랍장", "furniture", "solid", ["furniture", "나무 수납장", "나무 궤짝", "나무 탁자"]),
  one(118, "기울어진 목재 판자", "furniture", "solid", ["furniture", "기울어진 목재 벤치", "비스듬한 나무 탁자", "나무 작업대"]),
  one(119, "자수정 원석", "rock", "solid", ["rock", "보라색 바위", "큰 바위", "바위"]),

  // ── 4행 (인덱스 120-149) ─────────────────────────────────────────────
  ...entries([120, 121, 122], "어두운 바다", "water", "passable", ["water", "어두운 물", "깊은 물"]),
  one(123, "물결치는 어두운 물", "water", "passable", ["water", "물결 파동", "물결", "폭포"]),
  one(124, "잔물결 물", "water", "passable", ["wave", "물결"]),
  one(125, "석조 틀 청색 유리창", "window", "solid", ["창문", "window", "유리"]),
  one(126, "밭 가장자리 흙바닥", "terrain", "passable", ["terrain", "경작지 흙 모서리", "경작지 모서리", "밭"]),
  one(127, "잡초 풀밭", "terrain", "passable", ["terrain", "풀밭"]),
  one(128, "밭 흙바닥", "terrain", "passable", ["terrain", "경작지 흙", "경작지", "밭"]),
  one(129, "조약돌 길 가장자리", "terrain", "passable", ["terrain", "자갈길 가장자리", "자갈길 모서리", "돌길"]),
  one(130, "잡초 풀밭", "terrain", "passable", ["terrain", "풀밭"]),
  one(131, "조약돌 바닥 오른쪽 위", "terrain", "passable", ["terrain", "자갈길 모서리", "자갈 바닥", "돌길"]),
  one(132, "갈색 나무 벽", "wall", "solid", ["wall", "wood", "목재"]),
  one(133, "나무 벽면", "wall", "solid", ["wall", "wood"]),
  one(134, "금속 장식 목재 벽 우측 상단", "wall", "solid", ["wall", "통나무 벽 우측", "통나무 벽", "금속 장식 목재 벽"]),
  one(135, "짜임 나무 벽", "wall", "solid", ["wall", "짜임"]),
  one(136, "나무 벽 표면", "wall", "solid", ["wall", "wood", "표면"]),
  one(137, "팀버프레임 벽 상단 보", "wall", "solid", ["wall", "팀버프레임 회벽 상단", "목조 골조 벽 상단", "목조 트러스 벽"]),
  one(138, "어두운 석조 아치 입구 좌상단", "wall", "solid", ["wall", "어두운 돌벽 아치 상단 좌측", "돌 아치문 상단 좌측", "돌성벽 처마 좌측"]),
  one(139, "어두운 석조 아치 입구 우상단", "wall", "solid", ["wall", "어두운 돌벽 아치 상단 우측", "돌 아치문 상단 우측", "돌성벽 처마 우측"]),
  ...entries([140, 141], "어두운 돌벽 상단", "wall", "solid", ["wall", "어두운 석조 벽", "어두운 돌벽", "돌벽"]),
  one(142, "어두운 돌벽 창문 좌측", "window", "solid", ["window", "석조 창문 좌측", "돌벽 창문 좌측", "어두운 돌벽 창문"]),
  one(143, "어두운 돌벽 창문 우측", "window", "solid", ["window", "석조 창문 우측", "돌벽 창문 우측", "어두운 돌벽 창문"]),
  one(144, "목재 기둥 상단", "prop", "solid", ["기둥", "pillar", "목재"]),
  one(145, "커튼 달린 창문 좌측", "window", "solid", ["창문", "window", "커튼"]),
  one(146, "목재 문 하단", "door", "solid", ["최종판정", "door", "목재 문"]),
  one(147, "나무 의자", "furniture", "solid", ["의자", "chair", "목재"]),
  one(148, "나무 협탁", "furniture", "solid", ["협탁", "nightstand", "목재"]),
  one(149, "바위에 꽂힌 곡괭이", "prop", "solid", ["prop", "흙더미에 꽂힌 삽", "레버"]),

  // ── 5행 (인덱스 150-179) ─────────────────────────────────────────────
  one(150, "어두운 물 소용돌이 좌측", "water", "passable", ["water", "어두운 물 웅덩이 좌측", "깊은 물", "원형 수면"]),
  one(151, "어두운 물 소용돌이 중앙", "water", "passable", ["water", "어두운 물 웅덩이 중앙", "깊은 물", "원형 수면"]),
  one(152, "어두운 물 소용돌이 우측", "water", "passable", ["water", "어두운 물 웅덩이 우측", "깊은 물", "원형 수면"]),
  one(153, "물결치는 어두운 물", "water", "passable", ["water", "물결 파동", "물결", "폭포"]),
  one(154, "잔물결 물", "water", "passable", ["wave", "물결"]),
  one(155, "석조 틀 청색 유리창", "window", "solid", ["창문", "window", "유리"]),
  one(156, "새싹 밭이랑 좌측", "terrain", "passable", ["밭", "farmland", "새싹"]),
  one(157, "새싹 밭이랑 중앙", "terrain", "passable", ["밭", "farmland", "새싹"]),
  one(158, "새싹 밭이랑 우측", "terrain", "passable", ["밭", "farmland", "새싹"]),
  one(159, "조약돌 바닥 좌상단 가장자리", "terrain", "passable", ["terrain", "돌길 좌상단 모서리", "자갈길 좌상단", "조약돌 바닥"]),
  one(160, "조약돌 바닥 상단 가장자리", "terrain", "passable", ["terrain", "돌길 상단 가장자리", "자갈길 상단", "조약돌 바닥"]),
  one(161, "조약돌 바닥 우상단 가장자리", "terrain", "passable", ["terrain", "돌길 우상단 모서리", "자갈길 우상단", "조약돌 바닥"]),
  one(162, "밝은 나무 벽", "wall", "solid", ["wall", "wood", "목재"]),
  one(163, "나무 벽면", "wall", "solid", ["wall", "wood"]),
  one(164, "갈색 목재 벽", "wall", "solid", ["wall", "목재"]),
  one(165, "목재 벽면", "wall", "solid", ["wall", "목재"]),
  one(166, "나무 벽 표면", "wall", "solid", ["wall", "wood", "표면"]),
  one(167, "팀버프레임 목재 기둥 벽", "wall", "solid", ["wall", "팀버프레임 목재 기둥", "목재 기둥 마감재", "목재 벽 기둥"]),
  one(168, "나무 판자 벽 좌측", "wall", "solid", ["벽", "wall", "판자"]),
  one(169, "나무 판자 벽 중앙", "wall", "solid", ["벽", "wall", "판자"]),
  one(170, "나무 판자 벽 우측", "wall", "solid", ["벽", "wall", "판자"]),
  one(171, "가로 목재 판자벽 좌측", "wall", "solid", ["wall", "목재 판자 벽 좌측", "나무 판자 벽 좌측", "나무 벽 좌단"]),
  one(172, "가로 목재 판자벽 중앙", "wall", "solid", ["wall", "목재 판자 벽 중앙", "나무 판자 벽 중앙", "나무 벽 중앙"]),
  one(173, "가로 목재 판자벽 우측", "wall", "solid", ["wall", "목재 판자 벽 우측", "나무 판자 벽 우측", "나무 벽 우단"]),
  one(174, "목재 기둥 중간", "prop", "solid", ["기둥", "pillar", "목재"]),
  one(175, "나무 의자 앞모습", "furniture", "solid", ["의자", "chair", "목재"]),
  one(176, "나무 의자 뒷모습", "furniture", "solid", ["의자", "chair", "목재"]),
  one(177, "쇠테 나무 술통", "prop", "solid", ["술통", "barrel", "목재"]),
  one(178, "구운 고기 덩어리", "prop", "solid", ["prop", "통구이 고기 요리", "음식 바구니", "구운 고기"]),
  one(179, "붉은 제비꼬리 깃발 상단", "decoration", "solid", ["깃발", "banner", "문장"]),

  // ── 6행 (인덱스 180-209) ─────────────────────────────────────────────
  one(180, "어두운 물 소용돌이 하단 좌측", "water", "passable", ["water", "어두운 물 웅덩이 좌측", "깊은 물", "원형 수면"]),
  one(181, "어두운 물 소용돌이 하단 중앙", "water", "passable", ["water", "어두운 물 웅덩이 중앙", "깊은 물", "원형 수면"]),
  one(182, "어두운 물 소용돌이 하단 우측", "water", "passable", ["water", "어두운 물 웅덩이 우측", "깊은 물", "원형 수면"]),
  one(183, "물결치는 어두운 물", "water", "passable", ["water", "물결 파동", "물결", "폭포"]),
  one(184, "잔물결 물", "water", "passable", ["wave", "물결"]),
  one(185, "석조 틀 청색 유리창", "window", "solid", ["창문", "window", "유리"]),
  one(186, "새싹 밭이랑 좌측", "terrain", "passable", ["밭", "farmland", "새싹"]),
  one(187, "새싹 밭이랑 중앙", "terrain", "passable", ["밭", "farmland", "새싹"]),
  one(188, "새싹 밭이랑 우측", "terrain", "passable", ["밭", "farmland", "새싹"]),
  one(189, "조약돌 바닥 좌측 가장자리", "terrain", "passable", ["terrain", "돌길 좌측 가장자리", "자갈길 좌측", "조약돌 바닥"]),
  one(190, "조약돌 바닥 가운데", "terrain", "passable", ["terrain", "자갈 바닥 중앙", "자갈길 중앙", "돌길"]),
  one(191, "조약돌 바닥 우측 가장자리", "terrain", "passable", ["terrain", "돌길 우측 가장자리", "자갈길 우측", "조약돌 바닥"]),
  one(192, "세로 목재 판자벽", "wall", "solid", ["wall", "목재 벽 좌단", "나무 판자 벽", "목재 가옥 벽"]),
  one(193, "옹이구멍 있는 목재 벽", "wall", "solid", ["wall", "옹이 구멍 난 나무 벽", "구멍 난 목재 판자벽", "얼룩진 목재 벽/문"]),
  one(194, "돌벽 팀버프레임 상단 좌측", "wall", "solid", ["wall", "반목조 석벽 기둥 상부 1", "팀버프레임 돌벽 좌측 상단", "팀버프레임 돌벽 상단"]),
  one(195, "돌벽 팀버프레임 상단 우측", "wall", "solid", ["wall", "반목조 석벽 기둥 상부 2", "팀버프레임 돌벽 우측 상단", "팀버프레임 돌벽 상단"]),
  one(196, "회벽 팀버프레임 상단 좌측", "wall", "solid", ["wall", "반목조 석벽 기둥 상부 3", "팀버프레임 벽 좌측 상단", "팀버프레임 회벽 상단"]),
  one(197, "회벽 팀버프레임 상단 우측", "wall", "solid", ["wall", "반목조 석벽 기둥 상부 4", "팀버프레임 벽 우측 상단", "팀버프레임 회벽 상단"]),
  one(198, "나무 판자 벽 좌측", "wall", "solid", ["벽", "wall", "판자"]),
  one(199, "나무 판자 벽 중앙", "wall", "solid", ["벽", "wall", "판자"]),
  one(200, "나무 판자 벽 우측", "wall", "solid", ["벽", "wall", "판자"]),
  one(201, "석조 틀 격자창", "window", "solid", ["창문", "window", "격자"]),
  one(202, "과일 상자 노란 과일", "prop", "solid", ["prop", "노란 과일 상자", "곡물 상자", "가판대 상자"]),
  one(203, "과일 상자 빨간 과일", "prop", "solid", ["prop", "빨간 사과 상자", "사과 상자", "가판대 상자"]),
  one(204, "목재 기둥 받침", "prop", "solid", ["기둥", "pillar", "목재"]),
  one(205, "나무 의자 우향 측면", "furniture", "solid", ["의자", "chair", "목재"]),
  one(206, "나무 의자 좌향 측면", "furniture", "solid", ["의자", "chair", "목재"]),
  one(207, "나무 물통", "prop", "solid", ["물통", "bucket", "목재"]),
  one(208, "붉은 삼각 문장 깃발", "decoration", "solid", ["깃발", "pennant", "문장"]),
  one(209, "붉은 제비꼬리 깃발 하단", "decoration", "solid", ["깃발", "banner", "문장"]),

  // ── 7행 (인덱스 210-239) ─────────────────────────────────────────────
  ...entries([210, 211, 212], "어두운 바다", "water", "passable", ["water", "어두운 물", "깊은 물"]),
  one(213, "물결치는 어두운 물", "water", "passable", ["water", "물결 파동", "물결", "폭포"]),
  one(214, "잔물결 물", "water", "passable", ["wave", "물결"]),
  one(215, "석조 틀 청색 유리창", "window", "solid", ["창문", "window", "유리"]),
  one(216, "작물이 심어진 밭 좌하단", "terrain", "passable", ["terrain", "밭 새싹 좌하단 모서리", "밭"]),
  one(217, "밭 새싹 하단 가장자리", "terrain", "passable", ["terrain", "작물이 심어진 밭 하단", "밭"]),
  one(218, "작물이 심어진 밭 우하단", "terrain", "passable", ["terrain", "밭 새싹 우하단 모서리", "밭"]),
  one(219, "조약돌 바닥 좌하단 가장자리", "terrain", "passable", ["terrain", "돌길 좌하단 모서리", "자갈길 좌하단", "조약돌 바닥"]),
  one(220, "조약돌 바닥 하단 가장자리", "terrain", "passable", ["terrain", "돌길 하단 가장자리", "자갈길 하단", "조약돌 바닥"]),
  one(221, "조약돌 바닥 우하단 가장자리", "terrain", "passable", ["terrain", "돌길 우하단 모서리", "자갈길 우하단", "조약돌 바닥"]),
  one(222, "세로 목재 벽 하단", "wall", "solid", ["wall", "세로 나무 판자 벽", "목재 벽 좌하단", "목재 판자벽"]),
  one(223, "어두운 걸레받이 목재 벽", "wall", "solid", ["wall", "목재 벽 우하단 걸레받이", "나무 판자 벽 하단", "목재 판자벽 하단"]),
  one(224, "돌벽 팀버프레임 하단 좌측", "wall", "solid", ["wall", "반목조 석벽 기둥 하부 1", "팀버프레임 돌벽 기둥 좌측", "목재 기둥 돌벽 하단"]),
  one(225, "돌벽 팀버프레임 하단 우측", "wall", "solid", ["wall", "반목조 석벽 기둥 하부 2", "팀버프레임 돌벽 기둥 우측", "목재 기둥 돌벽 하단"]),
  one(226, "팀버프레임 회반죽 벽 기둥 좌측", "wall", "solid", ["wall", "회벽 팀버프레임 하단 좌측", "반목조 회벽 기둥 하부 1", "목재 기둥 회벽 하단"]),
  one(227, "팀버프레임 회반죽 벽 기둥 우측", "wall", "solid", ["wall", "회벽 팀버프레임 하단 우측", "반목조 회벽 기둥 하부 2", "목재 기둥 회벽 하단"]),
  one(228, "나무 판자 벽 하단 좌측", "wall", "solid", ["벽", "wall", "판자"]),
  one(229, "나무 판자 벽 하단 중앙", "wall", "solid", ["벽", "wall", "판자"]),
  one(230, "나무 판자 벽 하단 우측", "wall", "solid", ["벽", "wall", "판자"]),
  one(231, "원형 황금 장식창", "window", "solid", ["창문", "window", "장식"]),
  one(232, "대리석 타일 바닥", "floor", "passable", ["floor", "유리 바닥 타일", "반사 유리 바닥", "유리 바닥"]),
  one(234, "긴 나무 벤치 좌측", "furniture", "solid", ["벤치", "bench", "목재"]),
  one(235, "긴 나무 벤치 중앙", "furniture", "solid", ["벤치", "bench", "목재"]),
  one(236, "긴 나무 벤치 우측", "furniture", "solid", ["벤치", "bench", "목재"]),
  one(237, "나무 궤짝", "prop", "solid", ["궤짝", "crate", "목재"]),
  one(238, "대형 붉은 깃발 좌측", "decoration", "solid", ["깃발", "banner", "문장"]),
  one(239, "대형 붉은 깃발 우측", "decoration", "solid", ["깃발", "banner", "문장"]),

  // ── 8행 (인덱스 240-269) ─────────────────────────────────────────────
  one(240, "성긴 연두 잔디", "terrain", "passable", ["grass", "풀밭"]),
  one(241, "고른 연두 잔디", "terrain", "passable", ["grass", "초원"]),
  one(242, "밝은 점무늬 잔디", "terrain", "passable", ["grass", "연두색"]),
  one(243, "짙은 풀숲 무늬", "terrain", "passable", ["grass", "수풀"]),
  one(244, "듬성한 밝은 잔디", "terrain", "passable", ["grass", "들판"]),
  one(245, "촘촘한 풀잎 무늬", "terrain", "passable", ["grass", "초목"]),
  one(246, "사각 테두리 돌벽", "wall", "solid", ["stone", "석조"]),
  one(247, "작은 점무늬 잔디", "terrain", "passable", ["grass", "초록"]),
  one(248, "세로 테두리 돌벽", "wall", "solid", ["stone", "회색벽"]),
  one(249, "검은 균열 돌벽", "wall", "solid", ["stone", "어두운벽"]),
  one(250, "넓은 연두 풀밭", "terrain", "passable", ["grass", "잔디밭"]),
  one(251, "어두운 쇄석 석벽 단일 블록", "wall", "solid", ["wall", "어두운 돌벽 상단 테두리", "어두운 돌 벽"]),
  one(252, "분홍색 거친 자연석 바닥", "terrain", "passable", ["최종판정", "terrain", "중복시트 이관"]),
  one(253, "청회색 거친 자연석 바닥", "terrain", "passable", ["최종판정", "terrain", "중복시트 이관"]),
  one(254, "갈색 기둥 벽돌벽", "wall", "solid", ["brick", "목재보강"]),
  one(255, "왼쪽 기둥 벽돌벽", "wall", "solid", ["brick", "목재기둥"]),
  one(256, "오른쪽 보강 회벽", "wall", "solid", ["plaster", "갈색기둥"]),
  one(257, "왼쪽 보강 회벽", "wall", "solid", ["plaster", "나무보"]),
  one(259, "부러진 나무 그루터기", "prop", "solid", ["prop", "통나무 더미 상단", "나뭇가지 더미", "통나무 더미"]),
  one(260, "연두 나무 우듬지", "tree", "solid", ["foliage", "나뭇잎"]),
  one(261, "갈라진 마른 가지", "tree", "solid", ["branch", "고사목"]),
  one(262, "둥근 활엽수 좌측 상단", "tree", "solid", ["tree", "큰 활엽수 왼쪽 상단", "큰 활엽수 수관 왼쪽", "큰 나무 좌상단"]),
  one(263, "큰 활엽수 오른쪽 상단", "tree", "solid", ["tree", "큰 활엽수 수관 오른쪽", "둥근 활엽수 우측 상단", "큰 나무 우상단"]),
  one(264, "흰 대각 빛무늬", "decoration", "solid", ["white", "판독보류"]),
  one(265, "잎 달린 덩굴 상단", "plant", "passable", ["plant", "덩굴 가지 상단", "덩굴 상단", "잎 달린 덩굴"]),
  one(266, "회색 석상 머리", "prop", "solid", ["prop", "회색 석상 상단", "석상 상단", "회색 석상"]),
  one(267, "회색 원기둥 머리", "prop", "solid", ["prop", "회색 석주 주두", "석조 기둥 상단", "회색 원기둥"]),
  one(268, "아치형 창문 왼쪽 상단", "window", "solid", ["최종판정", "window", "아치형 창문", "중복시트 이관"]),
  one(269, "아치형 창문 오른쪽 상단", "window", "solid", ["최종판정", "window", "아치형 창문", "중복시트 이관"]),

  // ── 9행 (인덱스 270-299) ─────────────────────────────────────────────
  one(270, "성긴 연두 잔디", "terrain", "passable", ["grass", "풀밭"]),
  one(271, "고른 연두 잔디", "terrain", "passable", ["grass", "초원"]),
  one(272, "밝은 점무늬 잔디", "terrain", "passable", ["grass", "연두색"]),
  one(273, "짙은 풀숲 무늬", "terrain", "passable", ["grass", "수풀"]),
  one(274, "가는 잎 풀숲 무늬", "terrain", "passable", ["grass", "초목"]),
  one(275, "굵은 잎 풀숲 무늬", "terrain", "passable", ["grass", "밀생"]),
  one(276, "왼쪽 테두리 돌벽", "wall", "solid", ["stone", "회색벽"]),
  one(277, "가운데 사각 돌벽", "wall", "solid", ["stone", "석재판"]),
  one(278, "오른쪽 테두리 돌벽", "wall", "solid", ["stone", "회색벽"]),
  one(279, "왼쪽 검은 균열벽", "wall", "solid", ["rock", "어두운벽"]),
  one(280, "어두운 쇄석벽 상단 중앙", "wall", "solid", ["wall", "어두운 돌벽 상단", "어두운 쇄석벽", "어두운 돌 벽"]),
  one(281, "오른쪽 검은 균열벽", "wall", "solid", ["rock", "암벽"]),
  one(282, "연보라색 거친 자연석 바닥", "terrain", "passable", ["최종판정", "terrain", "중복시트 이관"]),
  one(283, "회녹색 거친 자연석 바닥", "terrain", "passable", ["최종판정", "terrain", "중복시트 이관"]),
  one(284, "이끼 낀 푸른 벽돌", "wall", "solid", ["brick", "녹색이끼"]),
  one(285, "왼쪽 이끼 벽돌벽", "wall", "solid", ["brick", "푸른벽"]),
  one(286, "가운데 이끼 벽돌벽", "wall", "solid", ["brick", "덩굴"]),
  one(287, "오른쪽 이끼 벽돌벽", "wall", "solid", ["brick", "초록싹"]),
  one(288, "보라꽃 둥근 관목", "plant", "solid", ["flower", "꽃덤불"]),
  one(289, "진초록 둥근 관목", "plant", "solid", ["bush", "상록수"]),
  one(290, "잎 달린 나무 밑동", "tree", "solid", ["trunk", "녹색잎"]),
  one(291, "곧은 갈색 나무줄기", "tree", "solid", ["trunk", "뿌리"]),
  one(292, "왼쪽 잎과 나무뿌리", "tree", "solid", ["roots", "수관"]),
  one(293, "오른쪽 잎과 나무뿌리", "tree", "solid", ["roots", "나뭇잎"]),
  one(294, "옅은 대각 빛무늬", "decoration", "solid", ["white", "판독보류"]),
  one(295, "잎 달린 덩굴 중단", "plant", "passable", ["plant", "덩굴 가지 중단", "덩굴 중단", "잎 달린 덩굴"]),
  one(296, "회색 석상 몸통", "prop", "solid", ["prop", "회색 석상 하단", "석상 중단", "회색 석상"]),
  one(297, "회색 원기둥 몸통", "prop", "solid", ["prop", "회색 석주 기둥부", "석조 기둥 하단", "회색 원기둥"]),
  one(298, "파이프 오르간 좌하단", "furniture", "solid", ["furniture", "책장 본체 좌측", "책장 하단 왼쪽", "책장 좌측"]),
  one(299, "파이프 오르간 우하단", "furniture", "solid", ["furniture", "책장 하단 오른쪽", "책장 본체 우측", "책장 우측"]),

  // ── 10행 (인덱스 300-329) ────────────────────────────────────────────
  one(300, "성긴 연두 잔디", "terrain", "passable", ["grass", "풀밭"]),
  one(301, "고른 연두 잔디", "terrain", "passable", ["grass", "초원"]),
  one(302, "밝은 점무늬 잔디", "terrain", "passable", ["grass", "연두색"]),
  one(303, "짙은 풀숲 무늬", "terrain", "passable", ["grass", "수풀"]),
  one(304, "세로 잎 풀숲 무늬", "terrain", "passable", ["grass", "밀생"]),
  one(305, "사선 잎 풀숲 무늬", "terrain", "passable", ["grass", "초목"]),
  one(306, "왼쪽 회색 석판벽", "wall", "solid", ["stone", "회색벽"]),
  one(307, "돌 벽 내부 바닥", "floor", "passable", ["floor", "돌길 바닥 중앙", "돌 벽 단", "돌길 바닥"]),
  one(308, "오른쪽 회색 석판벽", "wall", "solid", ["stone", "석조"]),
  one(309, "왼쪽 검정 암석벽", "wall", "solid", ["rock", "검은돌"]),
  one(310, "어두운 돌벽 내부 바닥", "floor", "passable", ["floor", "어두운 돌바닥 중앙", "어두운 돌 벽 단", "어두운 돌바닥"]),
  one(311, "오른쪽 검정 암석벽", "wall", "solid", ["rock", "어두운벽"]),
  one(312, "어두운 청회색 거친 자연석 바닥", "terrain", "passable", ["최종판정", "terrain", "중복시트 이관"]),
  one(313, "자주색 조약돌 바닥", "floor", "passable", ["cobble", "보라돌"]),
  one(314, "밝은 갈색 벽돌벽", "wall", "solid", ["brick", "회벽"]),
  one(315, "왼쪽 밝은 벽돌벽", "wall", "solid", ["brick", "석회색"]),
  one(316, "가운데 밝은 벽돌벽", "wall", "solid", ["brick", "갈색줄눈"]),
  one(317, "오른쪽 밝은 벽돌벽", "wall", "solid", ["brick", "밝은벽"]),
  one(318, "노란 불꽃 벽횃불", "torch", "solid", ["flame", "조명"]),
  one(319, "꺼진 검은 벽걸이 횃불", "prop", "passable", ["prop", "벽걸이 촛대 거치대", "벽 레버"]),
  one(320, "문양이 그려진 두루마리", "prop", "solid", ["prop", "문자가 새겨진 석판", "양피지 공고문", "벽보"]),
  one(321, "세로 갈색 밧줄", "rope", "solid", ["rope", "매듭"]),
  one(322, "나무 사다리", "stairs", "passable", ["stairs", "목제 사다리"]),
  one(323, "보라색 묘비 장식 상단", "prop", "solid", ["prop", "보라색 장식 기둥 상단", "십자가 묘비 상단", "묘비 상단"]),
  one(324, "밝은 대각 빛무늬", "decoration", "solid", ["white", "판독보류"]),
  one(325, "덩굴잎 달린 가지", "plant", "solid", ["vine", "녹색잎"]),
  one(326, "회색 석상 하단 기단", "decoration", "solid", ["최종판정", "decoration", "회색 석상", "중복시트 이관"]),
  one(327, "긴 목제 의자 왼쪽", "furniture", "solid", ["furniture", "나무 벤치 좌측", "긴 탁자 좌측", "긴 목제 의자"]),
  one(328, "긴 목제 의자 오른쪽", "furniture", "solid", ["furniture", "나무 벤치 우측", "긴 탁자 우측", "긴 목제 의자"]),
  one(329, "검은색 걸개 상단", "decoration", "passable", ["decoration", "검은 암흑 채움", "검은 사각 면", "검은색 걸개"]),

  // ── 11행 (인덱스 330-359) ────────────────────────────────────────────
  one(330, "성긴 연두 잔디", "terrain", "passable", ["grass", "풀밭"]),
  one(331, "고른 연두 잔디", "terrain", "passable", ["grass", "초원"]),
  one(332, "밝은 점무늬 잔디", "terrain", "passable", ["grass", "연두색"]),
  one(333, "짙은 풀숲 무늬", "terrain", "passable", ["grass", "수풀"]),
  one(334, "아래로 흐른 풀잎", "terrain", "passable", ["grass", "세로무늬"]),
  one(335, "꺾인 연두 풀잎", "terrain", "passable", ["grass", "잎무늬"]),
  one(336, "왼쪽 짙은 석판벽", "wall", "solid", ["stone", "회색벽"]),
  one(337, "회색 석벽 하단 중앙", "wall", "solid", ["wall", "돌 벽 하단", "회색 석벽", "돌 벽"]),
  one(338, "오른쪽 짙은 석판벽", "wall", "solid", ["stone", "석조"]),
  one(339, "왼쪽 거친 검은벽", "wall", "solid", ["rock", "암석"]),
  one(340, "어두운 쇄석벽 하단 중앙", "wall", "solid", ["wall", "어두운 돌벽 하단", "어두운 쇄석벽", "어두운 돌 벽"]),
  one(341, "오른쪽 거친 검은벽", "wall", "solid", ["rock", "어두운돌"]),
  one(342, "베이지색 석판 바닥", "floor", "passable", ["최종판정", "floor", "중복시트 이관"]),
  one(343, "원형 문양 석판 바닥", "floor", "passable", ["floor"]),
  one(344, "갈색 회반죽 벽돌", "wall", "solid", ["brick", "회색줄눈"]),
  one(345, "왼쪽 갈색 벽돌벽", "wall", "solid", ["brick", "회반죽"]),
  one(346, "가운데 갈색 벽돌벽", "wall", "solid", ["brick", "석조벽"]),
  one(347, "오른쪽 갈색 벽돌벽", "wall", "solid", ["brick", "갈색돌"]),
  one(348, "흩어진 들꽃 무리", "plant", "solid", ["flowers", "꽃밭"]),
  one(349, "통나무 더미 하단", "prop", "solid", ["prop", "장작더미", "통나무 더미"]),
  one(350, "빨간색 튜닉", "prop", "solid", ["prop", "빨간 우체통"]),
  one(351, "붉은 꽃 화분", "prop", "solid", ["prop", "꽃 화분"]),
  one(352, "황토색 둥근 항아리", "prop", "solid", ["jar", "저장용기"]),
  one(353, "보라색 장식 기둥 하단", "prop", "solid", ["prop", "십자가 묘비 하단 기단", "보라색 묘비 몸체", "묘비 하단"]),
  one(354, "주황 지붕 왼쪽면", "roof", "solid", ["roof", "기와"]),
  one(355, "주황 지붕 오른쪽면", "roof", "solid", ["roof", "갈색기와"]),
  one(356, "남색 지붕 왼쪽면", "roof", "solid", ["roof", "푸른기와"]),
  one(357, "남색 지붕 오른쪽면", "roof", "solid", ["roof", "보라기와"]),
  one(358, "세로 목재 기둥", "prop", "solid", ["prop", "원목 기둥", "나무 기둥"]),
  one(359, "동굴 입구 하단 바닥", "door", "solid", ["door", "어두운 입구 하단", "동굴 입구", "어두운 입구"]),

  // ── 12행 (인덱스 360-389) ────────────────────────────────────────────
  one(360, "잔디 둘레 자갈밭", "terrain", "passable", ["gravel", "잔디", "고립형"]),
  one(361, "초록 잔디", "terrain", "passable", ["terrain", "잔디 바닥", "잔디"]),
  one(362, "어두운 자갈 바닥", "terrain", "passable", ["gravel", "갈색", "돌길"]),
  one(363, "잔디 둘레 모래밭", "sand", "passable", ["sand", "잔디", "고립형"]),
  one(364, "연두 꽃핀 잔디", "terrain", "passable", ["grass", "초원", "꽃"]),
  one(365, "밝은 모래 바닥", "sand", "passable", ["sand", "베이지", "평지"]),
  one(366, "돌 테두리 작은 구덩이", "terrain", "solid", ["terrain", "돌 테두리 바닥"]),
  one(367, "깨진 암반 구멍 상단 좌측", "cliff", "solid", ["최종판정", "cliff", "깨진 암반 구멍", "중복시트 이관"]),
  one(368, "깨진 암반 구멍 상단 우측", "cliff", "solid", ["최종판정", "cliff", "깨진 암반 구멍", "중복시트 이관"]),
  one(369, "석조 틀 어두운 창 단일", "window", "solid", ["최종판정", "window", "석조 틀 창", "중복시트 이관"]),
  one(370, "남색 석조 벽 상단 보", "wall", "solid", ["wall", "짙은 남색 벽면", "남색 목조 골조 석조 벽", "남색 벽"]),
  one(371, "남색 석조 벽 상단 오른쪽 끝", "wall", "solid", ["wall", "짙은 남색 벽 모서리", "남색 목조 골조 석조 벽", "남색 벽"]),
  one(372, "거친 자갈 흙 바닥", "terrain", "passable", ["terrain", "짙은 흙 바닥", "붉은 자갈길"]),
  one(373, "붉은 흙 바닥", "terrain", "passable", ["terrain", "붉은 흙밭"]),
  one(374, "주황 술장식 차양", "awning", "solid", ["awning", "주황색", "상점"]),
  one(375, "붉은 기와지붕", "roof", "solid", ["roof", "적갈색", "기와"]),
  one(376, "황금빛 붉은 기와", "roof", "solid", ["roof", "금색무늬", "지붕"]),
  one(377, "짙은 적갈 지붕", "roof", "solid", ["roof", "갈색기와", "건물"]),
  one(378, "나무 울타리 왼쪽끝", "fence", "solid", ["fence", "목재", "좌측"]),
  one(379, "뾰족 나무 울타리", "fence", "solid", ["fence", "말뚝", "목책"]),
  one(380, "나무 울타리 오른쪽끝", "fence", "solid", ["fence", "목재", "우측"]),
  one(381, "장작 위 모닥불", "torch", "solid", ["campfire", "불꽃", "야영"]),
  one(382, "돌 우물", "prop", "solid", ["prop", "돌 화덕"]),
  one(383, "깨진 항아리", "prop", "solid", ["pottery", "도기", "파편"]),
  one(384, "주황색 기와 삼각지붕 왼쪽 사면", "roof", "solid", ["최종판정", "roof", "주황색 삼각지붕", "중복시트 이관"]),
  one(385, "주황색 기와 삼각지붕 오른쪽 사면", "roof", "solid", ["최종판정", "roof", "주황색 삼각지붕", "중복시트 이관"]),
  one(386, "파란색 기와 삼각지붕 왼쪽 사면", "roof", "solid", ["최종판정", "roof", "파란색 삼각지붕", "중복시트 이관"]),
  one(387, "파란색 기와 삼각지붕 오른쪽 사면", "roof", "solid", ["최종판정", "roof", "파란색 삼각지붕", "중복시트 이관"]),
  one(388, "세로 목재 기둥", "prop", "solid", ["prop", "목재 기둥 상단", "통나무 기둥", "목재 기둥"]),
  one(389, "천막 지붕 상단 장식", "roof", "solid", ["roof", "녹색 차양 지붕", "풀 덮개 차양", "천막"]),

  // ── 13행 (인덱스 390-419) ────────────────────────────────────────────
  one(390, "자갈길 북서 경계", "terrain", "passable", ["gravel", "잔디경계", "좌상단"]),
  one(391, "자갈길 북쪽 경계", "terrain", "passable", ["gravel", "잔디경계", "상단"]),
  one(392, "자갈길 북동 경계", "terrain", "passable", ["gravel", "잔디경계", "우상단"]),
  one(393, "모래길 북서 경계", "sand", "passable", ["sand", "잔디경계", "좌상단"]),
  one(394, "모래길 북쪽 경계", "sand", "passable", ["sand", "잔디경계", "상단"]),
  one(395, "모래길 북동 경계", "sand", "passable", ["sand", "잔디경계", "우상단"]),
  one(396, "돌 테두리 구덩이 좌상단", "cliff", "solid", ["최종판정", "cliff", "돌 테두리 구덩이", "중복시트 이관"]),
  one(397, "돌 테두리 구덩이 상단", "cliff", "solid", ["최종판정", "cliff", "돌 테두리 구덩이", "중복시트 이관"]),
  one(398, "돌 테두리 구덩이 우상단", "cliff", "solid", ["최종판정", "cliff", "돌 테두리 구덩이", "중복시트 이관"]),
  one(399, "남색 석조 벽 패널 왼쪽 상단", "wall", "solid", ["wall", "남색 벽 테두리 왼쪽 상단", "남색 목조 골조 석조 벽", "남색 벽"]),
  one(400, "남색 석조 벽 패널 상단", "wall", "solid", ["wall", "남색 벽 테두리 상단", "남색 목조 골조 석조 벽", "남색 벽"]),
  one(401, "남색 석조 벽 패널 오른쪽 상단", "wall", "solid", ["wall", "남색 벽 테두리 오른쪽 상단", "남색 목조 골조 석조 벽", "남색 벽"]),
  one(402, "붉은 흙 밭 새싹", "plant", "passable", ["plant", "붉은 흙 새싹 밭", "붉은 밭 작물", "밭"]),
  one(403, "자갈 흙 밭 새싹", "plant", "passable", ["plant", "짙은 흙 새싹 밭", "자갈밭 작물", "밭"]),
  one(404, "주황 천막 술장식", "awning", "solid", ["awning", "노란술", "상점"]),
  one(405, "붉은 지붕 황금 테두리", "roof", "solid", ["roof", "금색띠", "처마"]),
  one(406, "푸른 지붕 밝은 무늬", "roof", "solid", ["roof", "보라빛", "장식기와"]),
  one(407, "짙은 푸른 기와지붕", "roof", "solid", ["roof", "남색", "기와"]),
  one(408, "나무 울타리 수직 기둥", "fence", "solid", ["fence", "나무 울타리 세로 기둥", "둥근 목책 왼쪽 하단", "세로 목재 울타리"]),
  one(409, "촘촘한 목책 울타리", "fence", "solid", ["fence", "나무말뚝", "목재"]),
  one(410, "목책 울타리 오른쪽 굴곡", "fence", "solid", ["fence", "목재", "굽은끝"]),
  one(411, "흩어진 돌", "rock", "passable", ["rock"]),
  one(412, "갈색 선술집 간판", "sign", "solid", ["pub", "주점", "나무표지"]),
  one(413, "회색 십자 방향 표지판", "prop", "solid", ["prop", "철제 십자가", "석조 십자가"]),
  one(414, "대형 묘비 왼쪽 상단", "prop", "solid", ["prop", "거대 비석 좌측 상단", "거대 비석 좌상단", "룬 비석 좌상단"]),
  one(415, "거대 비석 상단 중앙", "prop", "solid", ["prop", "룬 비석 상단 중앙", "대형 묘비 상단", "거대 비석"]),
  one(416, "대형 묘비 오른쪽 상단", "prop", "solid", ["prop", "거대 비석 우측 상단", "거대 비석 우상단", "룬 비석 우상단"]),
  one(417, "베이지 천막 왼쪽 지붕", "awning", "solid", ["tent", "천막천", "좌상단"]),
  one(418, "베이지색 천막 지붕 중앙", "roof", "solid", ["roof", "천막 지붕 상단 중앙", "둥근 텐트 지붕 중앙", "베이지색 천막"]),
  one(419, "베이지 천막 오른쪽 지붕", "awning", "solid", ["tent", "천막천", "우상단"]),

  // ── 14행 (인덱스 420-449) ────────────────────────────────────────────
  one(420, "자갈길 서쪽 경계", "terrain", "passable", ["gravel", "잔디경계", "좌측"]),
  one(421, "자갈길 중앙 바닥", "terrain", "passable", ["gravel", "갈색돌", "중앙"]),
  one(422, "자갈길 동쪽 경계", "terrain", "passable", ["gravel", "잔디경계", "우측"]),
  one(423, "모래길 서쪽 경계", "sand", "passable", ["sand", "잔디경계", "좌측"]),
  one(424, "모래길 중앙 바닥", "sand", "passable", ["sand", "베이지", "중앙"]),
  one(425, "모래길 동쪽 경계", "sand", "passable", ["sand", "잔디경계", "우측"]),
  one(426, "돌 테두리 구덩이 좌측", "cliff", "solid", ["최종판정", "cliff", "돌 테두리 구덩이", "중복시트 이관"]),
  one(427, "깨진 암반 구멍 내부", "cliff", "solid", ["최종판정", "cliff", "깨진 암반 구멍", "중복시트 이관"]),
  one(428, "돌 테두리 구덩이 우측", "cliff", "solid", ["최종판정", "cliff", "돌 테두리 구덩이", "중복시트 이관"]),
  one(429, "남색 석조 벽 패널 왼쪽", "wall", "solid", ["wall", "남색 벽 테두리 왼쪽", "남색 목조 골조 석조 벽", "남색 벽"]),
  one(430, "남색 석조 벽 패널 중앙", "wall", "solid", ["wall", "짙은 남색 벽 중앙", "남색 목조 골조 석조 벽", "남색 벽"]),
  one(431, "남색 석조 벽 패널 오른쪽", "wall", "solid", ["wall", "남색 벽 테두리 오른쪽", "남색 목조 골조 석조 벽", "남색 벽"]),
  one(432, "이끼 낀 자갈 바닥", "terrain", "passable", ["terrain", "이끼 낀 돌 바닥", "이끼 낀 돌바닥"]),
  one(433, "어두운 돌 바닥", "terrain", "passable", ["terrain", "짙은 자갈 바닥", "돌바닥"]),
  one(434, "대장간 화덕 상단 좌측", "prop", "solid", ["prop", "석조 화덕 좌측 상단", "대장간 화덕", "석조 화덕"]),
  one(435, "대장간 화덕 상단 우측", "prop", "solid", ["prop", "석조 화덕 우측 상단", "대장간 화덕", "석조 화덕"]),
  one(436, "파란색 기와지붕 왼쪽 가운데", "roof", "solid", ["roof", "파란색 기와 지붕 상단", "파란 기와 지붕 처마", "파란색 기와지붕 상단"]),
  one(437, "푸른 기와 벽면", "roof", "solid", ["roof", "청색기와", "건물"]),
  one(438, "목책 울타리 왼쪽 굴곡", "fence", "solid", ["fence", "목재", "굽은끝"]),
  one(439, "갈색 말뚝 울타리", "fence", "solid", ["fence", "나무", "뾰족말뚝"]),
  one(440, "쌓아 둔 장작더미", "prop", "solid", ["firewood", "통나무", "목재"]),
  one(441, "갈색 널빤지 바닥", "floor", "passable", ["wood", "마룻바닥", "판자"]),
  one(442, "청록색 그림의 목재 간판", "prop", "solid", ["prop", "검 무기점 간판", "무기점 간판"]),
  one(443, "붉은 글씨의 여관 간판", "prop", "solid", ["prop", "INN 여관 간판", "여관 간판"]),
  one(444, "대형 묘비 왼쪽 가운데", "prop", "solid", ["prop", "거대 비석 중간 좌측", "거대 비석 좌측 중앙", "룬 비석 좌측 중앙"]),
  one(445, "글자가 새겨진 대형 묘비 가운데", "prop", "solid", ["prop", "거대 비석 중간 중앙", "거대 비석 중앙", "룬 비석 중앙"]),
  one(446, "대형 묘비 오른쪽 가운데", "prop", "solid", ["prop", "거대 비석 중간 우측", "거대 비석 우측 중앙", "룬 비석 우측 중앙"]),
  one(447, "베이지색 천막 왼쪽 벽면", "wall", "solid", ["wall", "텐트 왼쪽 천 벽", "천막 좌측 벽", "베이지색 천막"]),
  one(448, "검은 천막 입구 상단", "door", "passable", ["door", "천막 입구 상단", "베이지색 천막", "천막"]),
  one(449, "베이지색 천막 오른쪽 벽면", "wall", "solid", ["wall", "텐트 오른쪽 천 벽", "천막 우측 벽", "베이지색 천막"]),

  // ── 15행 (인덱스 450-479) ────────────────────────────────────────────
  one(450, "자갈길 남서 경계", "terrain", "passable", ["gravel", "잔디경계", "좌하단"]),
  one(451, "자갈길 남쪽 경계", "terrain", "passable", ["gravel", "잔디경계", "하단"]),
  one(452, "자갈길 남동 경계", "terrain", "passable", ["gravel", "잔디경계", "우하단"]),
  one(453, "모래길 남서 경계", "sand", "passable", ["sand", "잔디경계", "좌하단"]),
  one(454, "모래길 남쪽 경계", "sand", "passable", ["sand", "잔디경계", "하단"]),
  one(455, "모래길 남동 경계", "sand", "passable", ["sand", "잔디경계", "우하단"]),
  one(456, "돌 테두리 구덩이 좌하단", "cliff", "solid", ["최종판정", "cliff", "돌 테두리 구덩이", "중복시트 이관"]),
  one(457, "돌 테두리 구덩이 하단", "cliff", "solid", ["최종판정", "cliff", "돌 테두리 구덩이", "중복시트 이관"]),
  one(458, "돌 테두리 구덩이 우하단", "cliff", "solid", ["최종판정", "cliff", "돌 테두리 구덩이", "중복시트 이관"]),
  one(459, "남색 석조 벽 패널 왼쪽 하단", "wall", "solid", ["wall", "남색 벽 테두리 왼쪽 하단", "남색 목조 골조 석조 벽", "남색 벽"]),
  one(460, "남색 석조 벽 패널 하단", "wall", "solid", ["wall", "남색 벽 테두리 하단", "남색 목조 골조 석조 벽", "남색 벽"]),
  one(461, "남색 석조 벽 패널 오른쪽 하단", "wall", "solid", ["wall", "남색 벽 테두리 오른쪽 하단", "남색 목조 골조 석조 벽", "남색 벽"]),
  one(462, "바위 무더기 좌측", "rock", "solid", ["rock", "보라색 광석", "바위 무더기"]),
  one(463, "작은 보라색 광석", "rock", "solid", ["rock", "바위 무더기 우측", "바위 무더기"]),
  one(464, "대장간 화덕 하단 좌측", "prop", "solid", ["prop", "석조 화덕 좌측 하단", "대장간 화덕", "석조 화덕"]),
  one(465, "대장간 화덕 하단 우측", "prop", "solid", ["prop", "석조 화덕 우측 하단", "대장간 화덕", "석조 화덕"]),
  one(466, "파란색 기와지붕 왼쪽 하단", "roof", "solid", ["roof", "파란색 기와 지붕 상단", "파란색 기와지붕 중간", "파란 기와 지붕"]),
  one(467, "푸른 기와 흰 테두리", "roof", "solid", ["roof", "남색기와", "아랫띠"]),
  one(468, "목조 아치 다리 왼쪽", "floor", "passable", ["floor", "목재 다리 좌측", "목조 아치 다리", "목재 다리"]),
  one(469, "목조 아치 다리 중앙", "floor", "passable", ["floor", "목재 다리 중앙", "목조 아치 다리", "목재 다리"]),
  one(470, "목조 아치 다리 오른쪽", "floor", "passable", ["floor", "목재 다리 우측", "목조 아치 다리", "목재 다리"]),
  one(471, "목재 상판 하단 지지대", "prop", "solid", ["prop", "목재 다리 하단 받침", "목재 발판 지지대", "목재 판자 바닥"]),
  one(472, "보라 병 상점간판", "sign", "solid", ["shop", "물약", "표지"]),
  one(473, "빨간 항아리 그림의 목재 간판", "prop", "solid", ["prop", "물약 잡화점 간판", "도구점 간판", "잡화점 간판"]),
  one(474, "룬 비석 좌하단 받침대", "prop", "solid", ["prop", "거대 비석 받침대 좌측", "대형 묘비 왼쪽 하단", "거대 비석 좌측 하단"]),
  one(475, "룬 비석 하단 중앙 받침대", "prop", "solid", ["prop", "거대 비석 받침대 중앙", "거대 비석 하단 중앙", "대형 묘비 하단"]),
  one(476, "대형 묘비 오른쪽 하단", "prop", "solid", ["prop", "룬 비석 우하단 받침대", "거대 비석 받침대 우측", "거대 비석 우측 하단"]),
  one(477, "베이지색 천막 왼쪽 하단 벽면", "wall", "solid", ["wall", "텐트 왼쪽 천 벽 하단", "천막 좌하단 지지대", "천막 좌하단 기둥"]),
  one(478, "검은 천막 입구 하단", "door", "passable", ["door", "원형 천막 입구 하단", "천막 입구 하단", "베이지색 천막"]),
  one(479, "베이지색 천막 오른쪽 하단 벽면", "wall", "solid", ["wall", "텐트 오른쪽 천 벽 하단", "천막 우하단 지지대", "천막 우하단 기둥"]),
];
