// Ship(배) 칩셋(tex_easyrpg_chipset_ship) 타일 그림판의 AI 검색용 큐레이션 시맨틱 테이블.
// 이 파일은 생성물이다 — 수기 편집 대신 scripts/build-tile-semantics.mts 로 재생성한다.
// 판독 절차(지어낸 이름이 아니라 실제 통산 과정):
//   1. gen-chipset-blocks.mts 가 4행을 경계선 없는 연속 30x4 아틀라스로 굽는다.
//      격자선을 그리지 않는 이유: 여러 칸에 걸친 물건을 다시 쪼개 놓으면 그게 그대로 오독이 된다.
//   2. 인덱스 확인은 gen-chipset-strips.mts 의 숫자 라벨로만 한다(스트립은 세로 연속성을 끊는다).
//   3. 서로 모르는 판독자 2명 이상이 독립 서술하고 role 다수결로 정리한다.
//      픽셀이 거의 같은 시트(retro_exterior/retro_house, RGB 차이 0.4%)는 판독을 합치므로 한 칸에 최대 4표다.
//   4. 다수결이 이전 라벨과 어긋나는 칸만 교정한다. 갈리는 칸은 그대로 둔다 —
//      지울 수 없는 칸을 지어내는 것이 이 테이블을 무너뜨렸던 원인이다. 보류 목록은 tile-reaudit/splits.txt.
//   5. 사람이 14~20배 크롭으로 확인한 칸은 overrides.json 이 다수결을 이긴다
//      (판독자 전원이 틀린 사례가 있었다 — 125/155/185/215 는 바닥이 아니라 석조 틀 유리창이다).
// tileSemanticsDungeon.ts / tileSemanticsInterior.ts 와 동일한 계약: tileset.tileMeta[] 와 별개로
// 관리되는 검색 전용 데이터다. 통행성/레이어 계약은 tilesetHarness 가, 타일별 정밀 라벨은 여기가 담당한다.
//
// 좌표 규약: 30타일/행, ID = 행×30 + 열. 아트가 없는 슬롯(완전 투명 또는 분홍 컬러키 단색)은
// 서술할 대상이 없으므로 엔트리를 만들지 않는다 — scripts/verify-tile-semantics.mts 가 픽셀에서
// 그 목록을 직접 구해 커버리지를 검증한다.
// 도화 가능 여부는 상수가 아니라 PNG 에서 직접 유도한다(불투명·비키색 픽셀이 하나라도 있는가).
//
// 실측: 도화 가능 464칸 전수 서술, 고유 라벨 383개.
// 조립: scripts/build-tile-semantics.mts (수기 편집 대신 이 스크립트로 재생성한다).

import type { CombinedTownTileSemanticEntry } from "./tileSemanticsCombinedTown";

export type ShipTileSemanticEntry = CombinedTownTileSemanticEntry;

function entries(
  indexes: readonly number[],
  label: string,
  role: string,
  passage: "passable" | "solid",
  tags: readonly string[]
): ShipTileSemanticEntry[] {
  return indexes.map((index) => ({ index, label, role, passage, tags: [label, ...tags] }));
}

function one(
  index: number,
  label: string,
  role: string,
  passage: "passable" | "solid",
  tags: readonly string[]
): ShipTileSemanticEntry {
  return { index, label, role, passage, tags: [label, ...tags] };
}

export const SHIP_TILE_SEMANTICS: readonly ShipTileSemanticEntry[] = [
  // ── 0행 (인덱스 0-29) ─────────────────────────────────────────────
  one(0, "바다 물결", "water", "passable", ["바다", "물", "ocean", "물결"]),
  one(1, "파도치는 바다", "water", "passable", ["바다", "파도", "wave", "물"]),
  one(2, "잔잔한 바다", "water", "passable", ["바다", "잔물결", "sea", "물"]),
  ...entries([3, 4, 5], "둥근 청색 창 상단", "window", "solid", ["window", "아치형 창문 상단", "둥근 청색 창", "바다 창문"]),
  one(6, "나무 갑판", "floor", "passable", ["갑판", "목재", "deck", "판자"]),
  one(7, "나무 갑판 판자", "floor", "passable", ["갑판", "목재", "deck", "판자"]),
  one(8, "짙은 갈색 나무 벽", "wall", "solid", ["벽", "목재", "wall", "어두운"]),
  one(9, "세로 이음 나무 판", "floor", "passable", ["목재", "세로", "갑판", "wood"]),
  one(10, "가로 이음 나무 판", "floor", "passable", ["목재", "가로", "갑판", "wood"]),
  one(11, "짙은 갈색 나무 벽면", "wall", "solid", ["벽", "목재", "벽면", "어두운"]),
  one(12, "갈색 나무 바닥", "floor", "passable", ["바닥", "목재", "floor", "판자"]),
  one(13, "밝은 나무 바닥", "floor", "passable", ["바닥", "목재", "deck", "밝은"]),
  one(14, "짙은 갈색 나무 바닥", "floor", "passable", ["바닥", "목재", "floor", "판자"]),
  one(15, "밝은 나무 바닥 판", "floor", "passable", ["바닥", "목재", "deck", "밝은"]),
  one(16, "나무 갑판 널", "floor", "passable", ["갑판", "목재", "deck", "목판"]),
  one(17, "세로 이음 나무 판", "floor", "passable", ["목재", "세로", "갑판", "wood"]),
  one(18, "장식 나무 벽면", "wall", "solid", ["벽", "목재", "장식", "패널"]),
  one(19, "두 쪽 문 모양 나무", "wall", "solid", ["벽", "목재", "문", "패널"]),
  one(20, "장식 나무 벽판", "wall", "solid", ["벽", "목재", "장식", "판자"]),
  one(21, "대칭 장식 나무 판", "wall", "solid", ["벽", "목재", "대칭", "패널"]),
  one(22, "목재 사다리 왼쪽", "stairs", "passable", ["stairs", "나무 사다리", "목재 사다리", "사다리"]),
  one(23, "목재 사다리 오른쪽", "stairs", "passable", ["stairs", "나무 사다리", "목재 사다리", "사다리"]),
  one(25, "가는 대각 목재 들보 상단", "prop", "solid", ["prop", "나무 선체", "가는 대각 목재 들보"]),
  one(26, "뾰족한 어두운 경사 조각", "cliff", "solid", ["경사", "절벽", "어두운", "cliff"]),
  one(27, "굽은 목재 들보 왼쪽", "prop", "solid", ["prop", "나무 선체", "굽은 목재 들보"]),
  one(28, "굽은 목재 들보 중앙", "prop", "solid", ["prop", "나무 선체", "굽은 목재 들보"]),
  one(29, "굽은 목재 들보 끝", "prop", "solid", ["prop", "나무 선체 곡선", "굽은 목재 들보", "나무 선체"]),

  // ── 1행 (인덱스 30-59) ─────────────────────────────────────────────
  one(30, "바다 물결", "water", "passable", ["바다", "물", "ocean", "물결"]),
  one(31, "파도치는 바다", "water", "passable", ["바다", "파도", "wave", "물"]),
  one(32, "잔잔한 바다", "water", "passable", ["바다", "잔물결", "sea", "물"]),
  one(33, "둥근 청색 창 하단 왼쪽", "window", "solid", ["window", "창문", "둥근 청색 창", "바다 창문"]),
  one(34, "둥근 청색 창 하단 중앙", "window", "solid", ["window", "창문", "둥근 청색 창", "바다 창문"]),
  one(35, "둥근 청색 창 하단 오른쪽", "window", "solid", ["window", "창문", "둥근 청색 창", "바다 창문"]),
  one(36, "짙은 나무 선체 벽", "wall", "solid", ["벽", "목재", "선체", "어두운"]),
  one(37, "짙은 나무 벽", "wall", "solid", ["벽", "목재", "wall", "어두운"]),
  one(38, "짙은 나무 격벽", "wall", "solid", ["벽", "목재", "격벽", "무거운"]),
  one(39, "짙은 나무 벽판", "wall", "solid", ["벽", "목재", "벽판", "어두운"]),
  one(40, "짙은 나무 벽 조각", "wall", "solid", ["벽", "목재", "조각", "패널"]),
  one(41, "짙은 나무 칸막이", "wall", "solid", ["벽", "목재", "칸막이", "partition"]),
  one(42, "판벽 위 가는 대각 띠", "wall", "solid", ["wall", "가로 나무 벽", "대각 띠 판벽"]),
  one(43, "판벽 위 굵은 대각 띠", "wall", "solid", ["wall", "나무 벽 대각 빔", "대각 띠 판벽"]),
  one(44, "갑판 목조 계단 좌측 난간", "stairs", "solid", ["stairs", "나무 계단 상단", "목조 계단", "나무 계단"]),
  one(45, "급해진 나무 경사", "path", "passable", ["경사", "목재", "급경사", "slope"]),
  one(46, "나무 격자 판", "fence", "solid", ["목재", "격자", "칸막이", "판독보류"]),
  one(47, "나무 격자 장식판", "fence", "solid", ["목재", "격자", "장식", "판독보류"]),
  one(48, "두꺼운 대각 목재 들보 상단", "prop", "solid", ["prop", "대각선 목조 지지대 좌상단", "두꺼운 대각 목재 들보", "선체 구조물"]),
  one(49, "줄무늬 가로 덮개 왼쪽", "prop", "solid", ["prop", "주름 배관", "줄무늬 가로 덮개", "배관"]),
  one(50, "줄무늬 가로 덮개 중앙", "prop", "solid", ["prop", "주름 배관", "줄무늬 가로 덮개", "배관"]),
  one(51, "줄무늬 가로 덮개 오른쪽", "prop", "solid", ["prop", "주름 배관", "줄무늬 가로 덮개", "배관"]),
  one(52, "두꺼운 대각 목재 들보 상단", "prop", "solid", ["prop", "대각선 목조 지지대 우상단", "두꺼운 대각 목재 들보", "선체 구조물"]),
  one(53, "금속 마개 목재 기둥 상단", "prop", "solid", ["prop", "선체 수직 기둥 상단", "금속 장식 목재 기둥", "선체 구조물"]),
  ...entries([54, 55], "가는 대각 목재 들보 중앙", "prop", "solid", ["prop", "나무 선체", "가는 대각 목재 들보"]),
  one(56, "넓은 대각 목재 들보 상단", "prop", "solid", ["prop", "나무 선체", "넓은 대각 목재 들보"]),
  one(57, "작은 금속 장식물", "prop", "solid", ["장식", "금속", "작다", "판독보류"]),
  one(58, "나무 바퀴 정면", "prop", "solid", ["prop", "톱니바퀴", "나무 바퀴"]),
  one(59, "나무 바퀴 측면", "prop", "solid", ["prop", "톱니바퀴", "나무 바퀴"]),

  // ── 2행 (인덱스 60-89) ─────────────────────────────────────────────
  one(60, "파도 바다", "water", "passable", ["바다", "파도", "water", "물"]),
  one(61, "물결 바다", "water", "passable", ["바다", "물결", "ocean", "물"]),
  one(62, "바다 물", "water", "passable", ["바다", "물", "sea", "wave"]),
  one(63, "어두운 절벽 물가", "water", "passable", ["물가", "절벽", "바다", "shore"]),
  one(64, "물가 벼랑", "water", "passable", ["물가", "벼랑", "바다", "cliff"]),
  one(65, "바위 해안 바다", "water", "passable", ["해안", "바다", "바위", "coast"]),
  one(66, "짙은 갈색 나무 벽", "wall", "solid", ["벽", "목재", "wall", "어두운"]),
  one(67, "아주 짙은 갈색 벽", "wall", "solid", ["벽", "짙은", "갈색", "무늬"]),
  one(68, "짙은 나무 벽면", "wall", "solid", ["벽", "목재", "벽면", "어두운"]),
  one(69, "짙은 나무 벽판", "wall", "solid", ["벽", "목재", "벽판", "패널"]),
  one(70, "아주 짙은 벽", "wall", "solid", ["벽", "짙은", "벽면", "무늬"]),
  one(71, "짙은 나무 칸막이", "wall", "solid", ["벽", "목재", "칸막이", "partition"]),
  one(72, "나무 장식 구조물", "prop", "solid", ["구조물", "목재", "장식", "판독보류"]),
  one(73, "벽걸이 장치 세로 관 상부", "prop", "solid", ["prop", "세로 탱크", "벽걸이 금속 장치", "펌프 기계"]),
  one(74, "갑판 목조 계단 측면 난간", "stairs", "solid", ["stairs", "나무 계단", "목조 계단"]),
  one(75, "갑판 목조 계단 하단", "stairs", "solid", ["stairs", "나무 계단", "목조 계단"]),
  one(76, "목재 난간 아래 가로 홈", "wall", "solid", ["wall", "갑판 계단 측면 목조 벽", "목재 난간 기단", "갑판 구조물"]),
  one(77, "테두리 장식 나무", "wall", "solid", ["나무", "테두리", "장식", "가장자리"]),
  one(78, "두꺼운 대각 목재 들보 중앙", "prop", "solid", ["prop", "대각선 목조 지지대 좌측", "두꺼운 대각 목재 들보", "선체 구조물"]),
  one(79, "대각선 목조 지지대 중앙 좌측", "prop", "solid", ["prop", "두꺼운 대각 목재 들보 중앙", "선체 구조물", "두꺼운 대각 목재 들보"]),
  one(80, "금속 장식 목재 기둥 중단", "prop", "solid", ["prop", "세로 배관", "금속 장식 목재 기둥", "배관"]),
  one(81, "대각선 목조 지지대 중앙 우측", "prop", "solid", ["prop", "두꺼운 대각 목재 들보 중앙", "선체 구조물", "두꺼운 대각 목재 들보"]),
  one(82, "어두운 대각 목재 들보 중앙", "prop", "solid", ["prop", "대각선 목조 지지대 우측", "어두운 대각 목재 들보", "선체 구조물"]),
  one(83, "사각 금속 등", "prop", "solid", ["prop", "금속 패널", "배관"]),
  one(84, "금속 덮개와 대각 들보 접합부", "prop", "solid", ["prop", "나무 선체", "대각 목재 들보"]),
  one(85, "교차하는 굽은 목재 들보", "prop", "solid", ["prop", "나무 선체", "굽은 목재 들보"]),
  one(86, "가느다란 기둥 꼭대기", "pillar", "solid", ["기둥", "꼭대기", "가늘다", "판독보류"]),
  one(87, "긴 목재 선반 왼쪽 지지대", "furniture", "solid", ["furniture", "나무 탁자 다리", "긴 목재 선반", "나무 탁자"]),
  one(88, "긴 목재 선반 중앙", "furniture", "solid", ["furniture", "나무 탁자", "긴 목재 선반"]),
  one(89, "긴 목재 선반 오른쪽", "furniture", "solid", ["furniture", "나무 탁자", "긴 목재 선반"]),

  // ── 3행 (인덱스 90-119) ─────────────────────────────────────────────
  one(90, "바다 물결", "water", "passable", ["바다", "물", "ocean", "물결"]),
  one(91, "파도치는 바다", "water", "passable", ["바다", "파도", "wave", "물"]),
  one(92, "잔잔한 바다", "water", "passable", ["바다", "잔물결", "sea", "물"]),
  one(93, "물가 모래 해안", "water", "passable", ["물가", "모래", "해안", "shore"]),
  one(94, "아래 물가 해안", "water", "passable", ["물가", "해안", "바다", "coast"]),
  one(95, "물가 모래 바다", "water", "passable", ["물가", "모래", "바다", "shore"]),
  one(96, "짙은 나무 벽", "wall", "solid", ["벽", "목재", "wall", "어두운"]),
  one(97, "짙은 갈색 벽", "wall", "solid", ["벽", "짙은", "갈색", "무늬"]),
  one(98, "짙은 나무 벽면", "wall", "solid", ["벽", "목재", "벽면", "어두운"]),
  one(99, "짙은 나무 벽판", "wall", "solid", ["벽", "목재", "벽판", "패널"]),
  one(100, "짙은 나무 격벽", "wall", "solid", ["벽", "목재", "격벽", "어두운"]),
  one(101, "짙은 나무 칸막이", "wall", "solid", ["벽", "목재", "칸막이", "partition"]),
  one(102, "나무 장식 구조물", "prop", "solid", ["구조물", "목재", "장식", "판독보류"]),
  one(103, "벽걸이 장치 세로 관 하부", "prop", "solid", ["prop", "세로 탱크", "벽걸이 금속 장치", "펌프 기계"]),
  one(104, "나무 기둥 벽면", "wall", "solid", ["기둥", "목재", "벽", "패널"]),
  one(105, "나무 기둥 판", "wall", "solid", ["기둥", "목재", "판자", "패널"]),
  one(106, "높은 나무 벽", "wall", "solid", ["벽", "목재", "높다", "기둥"]),
  one(107, "좁은 목재 판문", "door", "solid", ["door", "나무 문", "현창"]),
  one(108, "나무 장식 구조물", "prop", "solid", ["구조물", "목재", "장식", "판독보류"]),
  one(109, "대각선 목조 지지대 하단 좌측", "prop", "solid", ["prop", "어두운 대각 목재 들보 하단", "선체 구조물", "어두운 대각 목재 들보"]),
  one(110, "장식 틀 구조물", "prop", "solid", ["구조물", "장식", "틀", "판독보류"]),
  one(111, "대각선 목조 지지대 하단 우측", "prop", "solid", ["prop", "어두운 대각 목재 들보 하단", "선체 구조물", "어두운 대각 목재 들보"]),
  one(112, "나무 장식 구조물", "prop", "solid", ["구조물", "목재", "장식", "판독보류"]),
  one(113, "가로 줄무늬 금속 막대", "prop", "solid", ["prop", "주름 배관", "배관"]),
  one(114, "긴 대각 목재 들보 왼쪽", "prop", "solid", ["prop", "나무 선체", "긴 대각 목재 들보"]),
  one(115, "긴 대각 목재 들보 중앙", "prop", "solid", ["prop", "나무 선체", "긴 대각 목재 들보"]),
  one(116, "긴 대각 목재 들보 오른쪽", "prop", "solid", ["prop", "나무 선체", "긴 대각 목재 들보"]),
  one(117, "넓은 대각 목재 들보 왼쪽", "prop", "solid", ["prop", "나무 선체", "넓은 대각 목재 들보"]),
  one(118, "넓은 대각 목재 들보 오른쪽", "prop", "solid", ["prop", "나무 선체", "넓은 대각 목재 들보"]),
  one(119, "작은 장식 문양", "prop", "solid", ["장식", "문양", "작다", "판독보류"]),

  // ── 4행 (인덱스 120-149) ─────────────────────────────────────────────
  one(120, "짙은 파도 바닷물", "water", "passable", ["물", "wave", "sea", "깊은"]),
  one(121, "짙은 물결 바닷물", "water", "passable", ["바다", "파도", "deep", "ocean"]),
  one(122, "짙은 파도 바닷물", "water", "passable", ["물", "wave", "sea"]),
  one(123, "옅은 파도 바닷물", "water", "passable", ["물결", "shallow", "sea"]),
  one(124, "옅은 물결 바닷물", "water", "passable", ["바다", "foam", "wave"]),
  one(125, "옅은 파도 바닷물", "water", "passable", ["물", "sparkle", "sea"]),
  one(126, "구멍 뚫린 목재 바닥", "floor", "passable", ["floor", "갑판 작은 구멍", "갑판 바닥"]),
  one(127, "나무 갑판 널빤지", "floor", "passable", ["데크", "wood", "판자"]),
  one(128, "십자형 구멍 뚫린 목재 바닥", "floor", "passable", ["floor", "갑판 바닥 구멍 상단", "갑판 바닥"]),
  one(129, "나무 갑판 널빤지", "floor", "passable", ["데크", "planks", "wood"]),
  one(130, "나무 갑판 널빤지", "floor", "passable", ["데크", "deck", "널빤지"]),
  one(131, "십자형 구멍 뚫린 세로 목재 바닥", "floor", "passable", ["floor", "갑판 바닥 구멍 상단", "갑판 바닥"]),
  one(132, "갑판 급수 펌프 하단부", "machine", "passable", ["펌프", "pump", "갑판"]),
  one(133, "나무 판자 바닥", "floor", "passable", ["갑판", "planks", "wood"]),
  ...entries([134, 135, 136], "둥근 구멍 아래 선체 가로 판벽", "wall", "solid", ["판벽", "hull", "목재"]),
  one(137, "목재 벽 모서리", "wall", "solid", ["wall", "목재 벽"]),
  one(138, "원통형 권양기 좌측", "prop", "solid", ["prop", "가로형 권양기 좌측", "권양기"]),
  one(139, "목조 골조 벽 좌측 사선 브레이스", "wall", "solid", ["골조", "frame", "목재"]),
  one(140, "목조 골조 벽 중앙 기둥", "wall", "solid", ["골조", "frame", "기둥"]),
  one(141, "목조 골조 벽 우측 사선 브레이스", "wall", "solid", ["골조", "frame", "목재"]),
  one(142, "원통형 권양기 우측", "prop", "solid", ["prop", "가로형 권양기 우측", "권양기"]),
  one(143, "벽 부착 가로 널 선반", "shelf", "solid", ["선반", "shelf", "목재"]),
  one(144, "작은 기둥 조형물", "pillar", "solid", ["기둥", "statue", "판독보류"]),
  one(145, "작은 기둥 조형물", "pillar", "solid", ["조형", "pillar", "판독보류"]),
  one(146, "대각선 선체 난간 상단 좌측", "wall", "solid", ["wall", "비스듬한 선체 외벽 좌상단", "선체 난간", "선체 외벽"]),
  one(147, "대각선 선체 난간 상단 우측", "wall", "solid", ["wall", "비스듬한 선체 외벽 우상단", "선체 난간", "선체 외벽"]),
  one(148, "선반 위 색색 물약병", "prop", "solid", ["물약", "potion", "선반"]),
  one(149, "갑판 목재 울타리 난간 상단", "fence", "solid", ["fence", "목재 난간", "갑판 울타리"]),

  // ── 5행 (인덱스 150-179) ─────────────────────────────────────────────
  one(150, "짙은 파도 바닷물", "water", "passable", ["물", "sea", "wave"]),
  one(151, "짙은 물결 바닷물", "water", "passable", ["바다", "deep", "파도"]),
  one(152, "짙은 파도 바닷물", "water", "passable", ["물결", "ocean", "wave"]),
  one(153, "옅은 파도 바닷물", "water", "passable", ["물", "shallow", "sea"]),
  one(154, "옅은 물결 바닷물", "water", "passable", ["바다", "foam", "파도"]),
  one(155, "옅은 파도 바닷물", "water", "passable", ["물결", "wave", "sea"]),
  one(156, "갑판 바닥 구멍 좌상단", "floor", "passable", ["floor", "갑판 큰 구멍 좌상단", "갑판 바닥 구멍", "갑판 큰 구멍"]),
  one(157, "갑판 큰 구멍 상단 중앙", "floor", "passable", ["floor", "갑판 바닥 구멍 상단", "갑판 큰 구멍", "갑판 바닥 구멍"]),
  one(158, "갑판 바닥 구멍 우상단", "floor", "passable", ["floor", "갑판 큰 구멍 우상단", "갑판 바닥 구멍", "갑판 큰 구멍"]),
  one(159, "세로 갑판 바닥 구멍 좌상단", "floor", "passable", ["floor", "갑판 세로 구멍 좌상단", "갑판 바닥 구멍", "갑판 세로 구멍"]),
  one(160, "갑판 세로 구멍 상단 중앙", "floor", "passable", ["floor", "세로 갑판 바닥 구멍 상단", "갑판 세로 구멍", "갑판 바닥 구멍"]),
  one(161, "세로 갑판 바닥 구멍 우상단", "floor", "passable", ["floor", "갑판 세로 구멍 우상단", "갑판 바닥 구멍", "갑판 세로 구멍"]),
  one(162, "대각선 계단 난간 상단 좌측", "stairs", "solid", ["stairs", "난간 계단 좌상단", "목재 계단 난간", "목재 계단"]),
  one(163, "대각선 계단 난간 상단 중앙", "stairs", "solid", ["stairs", "난간 계단 중앙 상단", "목재 계단 난간", "목재 계단"]),
  one(164, "대각선 계단 난간 상단 우측", "stairs", "solid", ["stairs", "난간 계단 우상단", "목재 계단 난간", "목재 계단"]),
  one(165, "계단 측면 목재 바닥", "floor", "passable", ["floor", "목재 갑판 바닥"]),
  one(166, "곡선 선체 난간 상단 좌측", "wall", "solid", ["wall", "계단 측면 목재 벽 좌측", "곡선 선체 난간", "계단 측면 벽"]),
  one(167, "곡선 선체 난간 상단 우측", "wall", "solid", ["wall", "계단 측면 목재 벽 우측", "곡선 선체 난간", "계단 측면 벽"]),
  ...entries([168, 169, 170, 171], "짙은 석조 벽돌 벽", "wall", "solid", ["석조", "brick", "벽돌"]),
  one(172, "세로 널 목조 벽", "wall", "solid", ["판벽", "plank", "목재"]),
  one(173, "세로 널 목조 벽 우측 곡선 테두리", "wall", "solid", ["판벽", "plank", "곡선"]),
  one(174, "곡선 선체 난간 좌상단", "wall", "solid", ["wall", "곡선 선체 외벽 좌측", "선체 난간", "선체 외벽"]),
  one(175, "비스듬한 선체 외벽 중앙", "wall", "solid", ["wall", "대각선 선체 난간", "선체 외벽", "선체 난간"]),
  one(176, "비스듬한 선체 외벽 우측", "wall", "solid", ["wall", "대각선 선체 난간", "선체 외벽", "선체 난간"]),
  one(177, "선체 곡선 난간 대각선 조각", "fence", "solid", ["난간", "rail", "선체"]),
  one(178, "비스듬한 선체 외벽 모서리", "wall", "solid", ["wall", "대각선 선체 난간", "선체 외벽", "선체 난간"]),

  // ── 6행 (인덱스 180-209) ─────────────────────────────────────────────
  one(180, "짙은 파도 바닷물", "water", "passable", ["물", "wave", "deep"]),
  one(181, "짙은 물결 바닷물", "water", "passable", ["바다", "sea", "파도"]),
  one(182, "짙은 파도 바닷물", "water", "passable", ["물결", "ocean", "wave"]),
  one(183, "옅은 파도 바닷물", "water", "passable", ["물", "shallow", "sea"]),
  one(184, "옅은 물결 바닷물", "water", "passable", ["파도", "foam", "바다"]),
  one(185, "옅은 파도 바닷물", "water", "passable", ["물결", "wave", "sea"]),
  one(186, "갑판 큰 구멍 좌측 중앙", "floor", "passable", ["floor", "갑판 바닥 구멍 좌측", "갑판 큰 구멍", "갑판 바닥 구멍"]),
  one(187, "갑판 큰 구멍 내부 중앙", "floor", "passable", ["floor", "갑판 바닥 구멍 내부", "갑판 큰 구멍", "갑판 바닥 구멍"]),
  one(188, "갑판 큰 구멍 우측 중앙", "floor", "passable", ["floor", "갑판 바닥 구멍 우측", "갑판 큰 구멍", "갑판 바닥 구멍"]),
  one(189, "세로 갑판 바닥 구멍 좌측", "floor", "passable", ["floor", "갑판 세로 구멍 좌측", "갑판 바닥 구멍", "갑판 세로 구멍"]),
  one(190, "세로 갑판 바닥 구멍 내부", "floor", "passable", ["floor", "갑판 세로 구멍 내부", "갑판 바닥 구멍", "갑판 세로 구멍"]),
  one(191, "세로 갑판 바닥 구멍 우측", "floor", "passable", ["floor", "갑판 세로 구멍 우측", "갑판 바닥 구멍", "갑판 세로 구멍"]),
  one(192, "선실 사각 창 개구부", "window", "solid", ["창문", "window", "선실"]),
  one(193, "선실 목재 벽 상단", "wall", "solid", ["wall", "세로 목재 벽", "목재 벽"]),
  one(194, "대각선 계단 난간살 상단", "stairs", "solid", ["stairs", "난간 계단 좌하단", "목재 계단 난간", "목재 계단"]),
  one(195, "대각선 계단 난간살 하단", "stairs", "solid", ["stairs", "난간 계단 우하단", "목재 계단 난간", "목재 계단"]),
  one(196, "목재 갑판 바닥 모서리", "floor", "passable", ["floor", "계단 착지 목재 바닥"]),
  one(197, "목재 벽 하단 그림자", "wall", "solid", ["wall", "어두운 목재 벽 하단", "계단 측면 벽"]),
  one(198, "목재 벽 상단 좌측", "wall", "solid", ["wall", "목재 선실 벽 좌측", "목재 벽", "목재 선실 벽"]),
  one(199, "목재 선실 벽 중앙 좌측", "wall", "solid", ["wall", "목재 벽 상단 중앙", "목재 선실 벽", "목재 벽"]),
  one(200, "목재 선실 벽 중앙 우측", "wall", "solid", ["wall", "목재 벽 상단 중앙", "목재 선실 벽", "목재 벽"]),
  one(201, "목재 벽 상단 우측", "wall", "solid", ["wall", "목재 선실 벽 우측", "목재 벽", "목재 선실 벽"]),
  one(202, "환기 격자창", "window", "solid", ["window", "환기창"]),
  one(203, "둥근 목조 기둥", "pillar", "solid", ["기둥", "pillar", "목재"]),
  one(204, "받침대 작은 등불", "prop", "solid", ["등불", "lamp", "받침"]),
  one(205, "해골과 뼈 더미", "decoration", "passable", ["해골", "skull", "뼈"]),
  one(206, "작은 목재 조각", "prop", "solid", ["목재", "chip", "조각"]),
  one(207, "선체 곡선 난간과 갑판 이음", "fence", "solid", ["난간", "rail", "선체"]),
  one(208, "비스듬한 선체 외벽 하단 우측", "wall", "solid", ["wall", "대각선 선체 난간", "선체 외벽", "선체 난간"]),
  one(209, "비스듬한 선체 외벽 우하단", "wall", "solid", ["wall", "대각선 선체 난간 하단", "선체 외벽", "선체 난간"]),

  // ── 7행 (인덱스 210-239) ─────────────────────────────────────────────
  one(210, "짙은 파도 바닷물", "water", "passable", ["물", "wave", "바다"]),
  one(211, "짙은 물결 바닷물", "water", "passable", ["바다", "deep", "파도"]),
  one(212, "짙은 파도 바닷물", "water", "passable", ["물결", "sea", "ocean"]),
  one(213, "옅은 파도 바닷물", "water", "passable", ["물", "shallow", "sea"]),
  one(214, "옅은 물결 바닷물", "water", "passable", ["파도", "foam", "바다"]),
  one(215, "옅은 파도 바닷물", "water", "passable", ["물결", "wave", "sea"]),
  one(216, "갑판 바닥 구멍 좌하단", "floor", "passable", ["floor", "갑판 큰 구멍 좌하단", "갑판 바닥 구멍", "갑판 큰 구멍"]),
  one(217, "갑판 큰 구멍 하단 중앙", "floor", "passable", ["floor", "갑판 바닥 구멍 하단", "갑판 큰 구멍", "갑판 바닥 구멍"]),
  one(218, "갑판 바닥 구멍 우하단", "floor", "passable", ["floor", "갑판 큰 구멍 우하단", "갑판 바닥 구멍", "갑판 큰 구멍"]),
  one(219, "세로 갑판 바닥 구멍 좌하단", "floor", "passable", ["floor", "갑판 세로 구멍 좌하단", "갑판 바닥 구멍", "갑판 세로 구멍"]),
  one(220, "갑판 세로 구멍 하단 중앙", "floor", "passable", ["floor", "세로 갑판 바닥 구멍 하단", "갑판 세로 구멍", "갑판 바닥 구멍"]),
  one(221, "세로 갑판 바닥 구멍 우하단", "floor", "passable", ["floor", "갑판 세로 구멍 우하단", "갑판 바닥 구멍", "갑판 세로 구멍"]),
  one(222, "세로 목재 벽 좌측 가장자리", "wall", "solid", ["wall", "선실 기둥 모서리 하단", "목재 벽"]),
  one(223, "선실 목재 벽 하단", "wall", "solid", ["wall", "세로 목재 벽", "목재 벽"]),
  one(224, "대각선 계단 난간 하단 좌측", "stairs", "solid", ["stairs", "계단 난간 지지대 좌측", "목재 계단 난간", "목재 계단"]),
  one(225, "대각선 계단 난간 기둥 하단", "stairs", "solid", ["stairs", "계단 난간 지지대 우측", "목재 계단 난간", "목재 계단"]),
  one(226, "원통형 권양기 하단 좌측", "prop", "solid", ["prop", "권양기 드럼 하단", "권양기"]),
  one(227, "원통형 권양기 하단 레버", "prop", "solid", ["prop", "권양기 손잡이 상단", "권양기"]),
  one(228, "목재 선실 벽 하단 좌측", "wall", "solid", ["wall", "목재 벽 하단 좌측", "목재 선실 벽", "목재 벽"]),
  one(229, "목재 선실 벽 하단 중앙 좌측", "wall", "solid", ["wall", "목재 벽 하단 중앙", "목재 선실 벽", "목재 벽"]),
  one(230, "목재 선실 벽 하단 중앙 우측", "wall", "solid", ["wall", "목재 벽 하단 중앙", "목재 선실 벽", "목재 벽"]),
  one(231, "목재 선실 벽 하단 우측", "wall", "solid", ["wall", "목재 벽 하단 우측", "목재 선실 벽", "목재 벽"]),
  one(232, "창살 격자 창문", "window", "solid", ["window", "격자 창문"]),
  one(234, "위 목재 아래 어두운 축", "prop", "solid", ["목재", "beam", "판독보류"]),
  one(235, "금빛 상단 목재 조각", "prop", "solid", ["목재", "gold", "조각"]),
  one(236, "선박 뱃머리 돌출봉 연결부", "prop", "solid", ["prop", "돛대 가로목 중앙 우측", "선박 이물", "돛대 가로목"]),
  one(237, "모서리 목재 금빛 조각", "prop", "solid", ["목재", "corner", "조각"]),
  one(238, "선체 난간 모서리 연결부", "fence", "solid", ["난간", "rail", "모서리"]),
  one(239, "선체 난간 모서리 금속 부속", "fence", "solid", ["난간", "rail", "금속"]),

  // ── 8행 (인덱스 240-269) ─────────────────────────────────────────────
  one(240, "거친 점 모래땅", "sand", "passable", ["sand", "해변", "바닥"]),
  one(241, "고운 노란 모래", "sand", "passable", ["sand", "모래사장", "노랑"]),
  one(242, "밝은 모래사장", "sand", "passable", ["sand", "해변", "밝은흙"]),
  one(243, "잔디 고립 덩이", "terrain", "passable", ["grass", "풀밭", "고립"]),
  one(244, "잔디 한가운데", "terrain", "passable", ["grass", "풀밭", "중심"]),
  one(245, "잔디 오목 모서리", "terrain", "passable", ["grass", "안쪽모서리", "경계"]),
  one(246, "왼쪽 세로줄 갑판", "floor", "passable", ["deck", "나무", "세로줄눈"]),
  one(247, "가로 널 갑판", "floor", "passable", ["deck", "널빤지", "가로결"]),
  one(248, "오른쪽 세로줄 갑판", "floor", "passable", ["deck", "나무", "우측"]),
  one(249, "작은 벽돌 갑판", "floor", "passable", ["deck", "벽돌무늬", "나무판"]),
  one(250, "두 쪽 세로 갑판", "floor", "passable", ["deck", "세로널", "이음"]),
  one(251, "이음새 가로 갑판", "floor", "passable", ["deck", "가로결", "중앙선"]),
  one(252, "빗금 선실벽", "wall", "solid", ["cabin", "선실", "모서리"]),
  one(253, "왼쪽 검은 선실벽", "wall", "solid", ["cabin", "가로널", "어둠"]),
  ...entries([254, 255], "선실 목재 벽 상단", "wall", "solid", ["wall", "목재 벽 상단", "선실 목재 벽", "목재 벽"]),
  one(256, "벽면 사다리 상단", "stairs", "passable", ["stairs", "사다리", "벽면 사다리"]),
  one(257, "회색 둥근 금속물", "prop", "solid", ["metal", "회색", "판독보류"]),
  one(259, "회색 쇠닻", "prop", "solid", ["anchor", "닻", "선구"]),
  one(260, "좌하 대각 들보", "ship", "solid", ["beam", "사선", "목재"]),
  one(261, "작은 나무 끝촉", "prop", "solid", ["peg", "말뚝", "판독보류"]),
  one(262, "우하 대각 들보", "ship", "solid", ["beam", "사선", "굵은목"]),
  one(263, "감긴 밧줄 더미", "rope", "solid", ["coil", "로프", "선구"]),
  one(264, "갑판 해치 입구 상단", "door", "passable", ["door", "선실 출입구 상단", "선실 입구 상단", "갑판 해치"]),
  one(265, "대각선 선체 외벽", "wall", "solid", ["wall", "선체 경사 목재", "선체 외벽", "선체"]),
  one(266, "대각선 선체 외벽 모서리", "wall", "solid", ["wall", "선체 경사 목재", "선체 외벽", "선체"]),
  ...entries([267, 268], "대각선 선체 외벽", "wall", "solid", ["wall", "선체 경사 목재", "선체 외벽", "선체"]),
  one(269, "대각선 선체 외벽 모서리", "wall", "solid", ["wall", "선체 경사 목재", "선체 외벽", "선체"]),

  // ── 9행 (인덱스 270-299) ─────────────────────────────────────────────
  one(270, "거친 점 모래땅", "sand", "passable", ["sand", "해변", "바닥"]),
  one(271, "고운 노란 모래", "sand", "passable", ["sand", "모래사장", "노랑"]),
  one(272, "밝은 모래사장", "sand", "passable", ["sand", "해변", "밝은흙"]),
  one(273, "잔디 북쪽 경계", "terrain", "passable", ["grass", "북측", "모래경계"]),
  one(274, "잔디 한가운데", "terrain", "passable", ["grass", "풀밭", "중심"]),
  one(275, "잔디 북동 모서리", "terrain", "passable", ["grass", "북동", "경계"]),
  one(276, "왼쪽 벽돌 갑판", "floor", "passable", ["deck", "벽돌무늬", "좌측"]),
  one(277, "가운데 가로 갑판", "floor", "passable", ["deck", "널빤지", "중앙"]),
  one(278, "오른쪽 벽돌 갑판", "floor", "passable", ["deck", "벽돌무늬", "우측"]),
  one(279, "잔벽돌 나무판", "floor", "passable", ["deck", "작은벽돌", "나무"]),
  one(280, "넓적 세로 갑판", "floor", "passable", ["deck", "세로널", "넓은판"]),
  one(281, "가로결 나무판", "floor", "passable", ["deck", "가로결", "마루"]),
  one(282, "금줄 문턱 선실벽", "wall", "solid", ["cabin", "문턱", "선실"]),
  one(283, "선실 목조 장식 벽판", "wall", "solid", ["wall", "선실 목재 벽면", "선실 목조 골조벽", "선실 목재 벽"]),
  one(284, "짙은 나무 선실벽", "wall", "solid", ["cabin", "벽", "가로널"]),
  one(285, "왼쪽 갑판 가장자리", "floor", "passable", ["deck", "가장자리", "검은테"]),
  one(286, "오른쪽 갑판 널", "floor", "passable", ["deck", "널빤지", "우측"]),
  one(287, "선박 기계 하단 지지대", "prop", "solid", ["prop", "조타륜 하단 받침대", "조타륜 하단", "선박 기계"]),
  one(288, "붉은 삼각 깃발", "banner", "solid", ["flag", "페넌트", "빨강"]),
  one(289, "가는 대각 가로대", "ship", "solid", ["spar", "사선", "얇은목"]),
  one(290, "빈 슬롯", "empty", "passable", ["empty"]),
  one(291, "가로대 달린 돛대", "ship", "solid", ["mast", "야드암", "십자"]),
  one(292, "가로 돛대 활대", "ship", "solid", ["yard", "가로대", "활대"]),
  one(293, "남서 대각 판재", "ship", "solid", ["hull", "사선", "하부"]),
  one(294, "나무 위 검은 구멍", "decoration", "solid", ["hatch", "어둠", "판독보류"]),
  one(295, "엇갈린 은색 검", "decoration", "solid", ["swords", "교차", "무기"]),
  one(296, "대각선 선체 외벽", "wall", "solid", ["wall", "선체 경사 외벽", "선체 외벽", "선체"]),
  one(297, "대각선 선체 외벽 모서리", "wall", "solid", ["wall", "선체 경사 외벽", "선체 외벽", "선체"]),
  one(298, "늘어진 갈색 밧줄", "rope", "solid", ["rope", "로프", "세로줄"]),
  one(299, "원형 나무 단면", "barrel", "solid", ["log", "토막", "나이테"]),

  // ── 10행 (인덱스 300-329) ────────────────────────────────────────────
  one(300, "거친 점 모래땅", "sand", "passable", ["sand", "해변", "바닥"]),
  one(301, "고운 노란 모래", "sand", "passable", ["sand", "모래사장", "노랑"]),
  one(302, "밝은 모래사장", "sand", "passable", ["sand", "해변", "밝은흙"]),
  one(303, "잔디 동쪽 경계", "terrain", "passable", ["grass", "동측", "모래경계"]),
  one(304, "잔디 한가운데", "terrain", "passable", ["grass", "풀밭", "중심"]),
  one(305, "잔디 동측 가장자리", "terrain", "passable", ["grass", "동쪽", "경계"]),
  one(306, "왼쪽 각진 갑판", "floor", "passable", ["deck", "벽돌무늬", "좌측"]),
  one(307, "가운데 벽돌 갑판", "floor", "passable", ["deck", "벽돌무늬", "중앙"]),
  one(308, "오른쪽 각진 갑판", "floor", "passable", ["deck", "벽돌무늬", "우측"]),
  one(309, "사각 나무벽돌", "floor", "passable", ["deck", "사각블록", "나무"]),
  one(310, "널찍한 나무판", "floor", "passable", ["deck", "넓은널", "마루"]),
  one(311, "가로 이음 나무판", "floor", "passable", ["deck", "가로결", "이음"]),
  one(312, "갑판 계단 상단 난간", "stairs", "passable", ["stairs", "선실 계단 입구 상단", "갑판 계단 상단", "갑판 계단"]),
  one(313, "갑판 사다리 계단", "stairs", "passable", ["stairs", "선실 계단", "갑판 계단"]),
  one(314, "목재 갑판 바닥", "floor", "passable", ["floor", "갑판 바닥"]),
  one(315, "목조 선체 곡선 테두리 왼쪽", "wall", "solid", ["wall", "곡선 선체 난간 좌측", "목조 선체", "선체 난간"]),
  one(316, "목조 선체 곡선 테두리 중앙", "wall", "solid", ["wall", "곡선 선체 난간 중앙", "목조 선체", "선체 난간"]),
  one(317, "목조 선체 곡선 테두리 오른쪽", "wall", "solid", ["wall", "곡선 선체 난간 우측", "목조 선체", "선체 난간"]),
  one(318, "붉은 금장 깃발", "banner", "solid", ["flag", "금장", "빨강"]),
  one(319, "가는 사선 버팀대", "ship", "solid", ["brace", "사선", "얇은목"]),
  one(320, "얇은 대각 목재", "ship", "solid", ["spar", "사선", "버팀"]),
  one(321, "나란한 두 돛대", "ship", "solid", ["mast", "쌍기둥", "세로대"]),
  one(322, "사선 가는 들보", "ship", "solid", ["beam", "사선", "가는목"]),
  one(323, "대각 널빤지 조각", "ship", "solid", ["plank", "사선", "조각"]),
  one(324, "왼쪽 향한 대포", "machine", "solid", ["cannon", "포신", "좌향"]),
  one(325, "오른쪽 향한 대포", "machine", "solid", ["cannon", "포차", "우향"]),
  one(326, "정면 포구 대포", "machine", "solid", ["cannon", "포구", "정면"]),
  one(327, "회색 둥근 포탄", "prop", "solid", ["cannonball", "포탄", "구체"]),
  one(328, "목재 사다리 상단", "stairs", "passable", ["stairs", "밧줄 사다리", "목재 사다리", "사다리"]),
  one(329, "은밑 갈색 원통", "barrel", "solid", ["barrel", "원통", "판독보류"]),

  // ── 11행 (인덱스 330-359) ────────────────────────────────────────────
  one(330, "거친 점 모래땅", "sand", "passable", ["sand", "해변", "바닥"]),
  one(331, "고운 노란 모래", "sand", "passable", ["sand", "모래사장", "노랑"]),
  one(332, "밝은 모래사장", "sand", "passable", ["sand", "해변", "밝은흙"]),
  one(333, "잔디 남서 모서리", "terrain", "passable", ["grass", "남서", "모래경계"]),
  one(334, "잔디 한가운데", "terrain", "passable", ["grass", "풀밭", "중심"]),
  one(335, "잔디 남동 경계", "terrain", "passable", ["grass", "남동", "모래변"]),
  one(336, "왼쪽 아래 갑판", "floor", "passable", ["deck", "하단", "좌측"]),
  one(337, "가운데 아래 갑판", "floor", "passable", ["deck", "하단", "중앙"]),
  one(338, "오른쪽 아래 갑판", "floor", "passable", ["deck", "하단", "우측"]),
  one(339, "하단 벽돌 갑판", "floor", "passable", ["deck", "벽돌무늬", "하단"]),
  one(340, "하단 세로 갑판", "floor", "passable", ["deck", "세로널", "하단"]),
  one(341, "하단 가로 갑판", "floor", "passable", ["deck", "가로결", "하단"]),
  one(342, "선실 목조 골조벽 하단 왼쪽", "wall", "solid", ["wall", "목재 벽 기둥 좌측", "선실 목재 벽 하단", "선실 목조 골조벽"]),
  one(343, "선실 목조 골조벽 하단 중앙", "wall", "solid", ["wall", "목재 벽 기둥 중앙", "선실 목재 벽 하단", "선실 목조 골조벽"]),
  one(344, "선실 목조 골조벽 하단 오른쪽", "wall", "solid", ["wall", "목재 벽 기둥 우측", "선실 목재 벽 하단", "선실 목조 골조벽"]),
  one(345, "검은 세로 문틀", "door", "solid", ["doorframe", "문틀", "세로홈"]),
  one(346, "문 안쪽 어둠", "door", "solid", ["doorway", "어둠", "개구"]),
  one(347, "가로 널 선체판", "floor", "passable", ["plank", "가로널", "선체"]),
  one(348, "붉은 금장 깃발", "banner", "solid", ["flag", "금장", "빨강"]),
  one(349, "사선 나무 버팀", "ship", "solid", ["brace", "사선", "목재"]),
  one(350, "굵은 사선 목재", "ship", "solid", ["beam", "사선", "굵은목"]),
  one(351, "회색 날 세로막대", "prop", "solid", ["pole", "금속날", "판독보류"]),
  one(352, "대각 버팀 널판", "ship", "solid", ["brace", "사선", "널판"]),
  one(353, "사선 선체 널판", "ship", "solid", ["hull", "사선", "널판"]),
  one(354, "좌향 포차 대포", "machine", "solid", ["cannon", "포차", "좌향"]),
  one(355, "우향 포신 대포", "machine", "solid", ["cannon", "포신", "우향"]),
  one(356, "정면 포구만", "machine", "solid", ["cannon", "포구", "머즐"]),
  one(357, "포미 나무 포차", "machine", "solid", ["cannon", "포미", "포차"]),
  one(358, "초록 풍경 나무액자", "decoration", "solid", ["picture", "액자", "풍경"]),
  one(359, "주황 불빛 나무액자", "decoration", "solid", ["picture", "액자", "불빛"]),

  // ── 12행 (인덱스 360-389) ────────────────────────────────────────────
  one(360, "갈색 흙바닥", "terrain", "passable", ["dirt", "흙", "지형"]),
  one(361, "노란 모래바닥", "sand", "passable", ["sand", "모래", "해변"]),
  one(362, "모서리 모래 흙바닥", "terrain", "passable", ["dirt", "sand corner", "모서리"]),
  one(366, "석재 바닥 좌상단 테두리", "floor", "passable", ["floor", "석조 바닥 상단 좌측", "석재 바닥", "석조 바닥"]),
  one(367, "석재 바닥 상단 테두리", "floor", "passable", ["floor", "석조 바닥 상단", "석재 바닥", "석조 바닥"]),
  one(368, "석재 바닥 상단 테두리", "floor", "passable", ["floor", "석조 바닥 상단 우측", "석재 바닥", "석조 바닥"]),
  one(369, "소형 목재 해치", "prop", "solid", ["prop", "소형 목조 해치", "목재 해치"]),
  one(370, "어두운 공간", "empty", "passable", ["empty", "어두운 내부"]),
  one(371, "목재 보 교차부", "prop", "solid", ["prop", "목재 보 교차점", "목재 보"]),
  one(372, "세로 널빤지 벽", "wall", "solid", ["wood", "벽판", "세로결"]),
  one(373, "나무 벽널 가운데", "wall", "solid", ["wood", "선실벽", "널빤지"]),
  one(374, "나무 벽널 오른쪽", "wall", "solid", ["wood", "벽면", "우측"]),
  one(375, "나무벽 세로 이음", "wall", "solid", ["wood", "이음새", "홈"]),
  one(376, "목재 창살 창문", "window", "solid", ["window", "목조 창살 창문", "목재 창살 벽", "목조 벽"]),
  one(377, "나무벽 왼쪽 이음", "wall", "solid", ["wood", "이음새", "좌측"]),
  one(378, "밝은 세로 나무결", "wall", "solid", ["wood", "밝은널", "세로"]),
  one(379, "사각 나무 상자", "crate", "solid", ["crate", "궤짝", "화물"]),
  one(380, "배 선수 목재 외벽 좌측", "wall", "solid", ["wall", "뱃머리 좌측 경사벽", "선체"]),
  one(381, "배 선수 목재 외벽 우측", "wall", "solid", ["wall", "뱃머리 우측 경사벽", "선체"]),
  one(382, "나무 서랍 가구", "furniture", "solid", ["drawer", "서랍장", "협탁"]),
  one(383, "세로 나무판 기둥", "pillar", "solid", ["pillar", "목재", "수직"]),
  one(384, "책이 꽂힌 책장", "shelf", "solid", ["bookshelf", "서적", "선반"]),
  one(385, "둥근 나무 술통", "barrel", "solid", ["barrel", "통", "화물"]),
  one(386, "도자기 항아리", "prop", "solid", ["prop"]),
  one(387, "둥근 나무 탁자", "furniture", "solid", ["table", "원탁", "가구"]),
  one(388, "바다 그림 왼액자", "decoration", "solid", ["painting", "액자", "풍경"]),
  one(389, "바다 그림 오른액자", "decoration", "solid", ["painting", "액자", "풍경"]),

  // ── 13행 (인덱스 390-419) ────────────────────────────────────────────
  one(390, "흙 북서 모래사면", "terrain", "passable", ["dirt", "sand", "북서"]),
  one(391, "흙 북쪽 모래경계", "terrain", "passable", ["dirt", "sand edge", "북쪽"]),
  one(392, "흙 북동 모래사면", "terrain", "passable", ["dirt", "sand", "북동"]),
  one(396, "석재 바닥 좌상단 테두리", "floor", "passable", ["floor", "석조 바닥 좌상단", "석재 바닥", "석조 바닥"]),
  one(397, "석재 바닥 상단 테두리", "floor", "passable", ["floor", "석조 바닥 상단", "석재 바닥", "석조 바닥"]),
  one(398, "석재 바닥 상단 테두리", "floor", "passable", ["floor", "석조 바닥 우상단", "석재 바닥", "석조 바닥"]),
  one(399, "대형 목조 해치 상단 좌측", "prop", "solid", ["prop", "대형 목재 해치 좌상단", "대형 목조 해치", "대형 목재 해치"]),
  one(400, "대형 목조 해치 상단 중앙", "prop", "solid", ["prop", "대형 목재 해치 상단", "대형 목조 해치", "대형 목재 해치"]),
  one(401, "대형 목조 해치 상단 우측", "prop", "solid", ["prop", "대형 목재 해치 우상단", "대형 목조 해치", "대형 목재 해치"]),
  one(402, "짙은 세로 나무벽", "wall", "solid", ["wood", "암색벽", "세로"]),
  one(403, "평평한 나무 벽면", "wall", "solid", ["wood", "매끈", "벽판"]),
  one(404, "나무벽 오른쪽면", "wall", "solid", ["wood", "우측벽", "선실"]),
  one(405, "나무 겹벽 이음", "wall", "solid", ["wood", "이음", "겹판"]),
  one(406, "가로 나무 마루", "floor", "passable", ["floor", "갑판", "가로결"]),
  one(407, "마루 우측 둥근테", "floor", "passable", ["floor", "곡면", "우측"]),
  one(408, "배 외벽 좌현 중상단", "wall", "solid", ["wall", "선체 좌측 외벽", "선체"]),
  one(409, "배 선수 목재 외벽 중좌측", "wall", "solid", ["wall", "뱃머리 좌측 경사벽", "선체"]),
  one(410, "빈 슬롯", "empty", "passable", ["empty"]),
  one(411, "배 선수 목재 외벽 중우측", "wall", "solid", ["wall", "뱃머리 중앙 우측 경사벽", "선체"]),
  one(412, "배 외벽 우측 대각선부", "wall", "solid", ["wall", "뱃머리 우측 경사벽", "선체"]),
  one(413, "배 외벽 우현 중상단", "wall", "solid", ["wall", "선체 우측 외벽", "선체"]),
  one(414, "책장 윗칸 선반", "shelf", "solid", ["bookshelf", "상단", "서적"]),
  one(415, "열린 나무통 윗면", "barrel", "solid", ["barrel", "윗면", "통"]),
  one(416, "흰 베개 침대", "bed", "solid", ["bed", "침구", "베개"]),
  one(417, "둥근 목재 의자", "furniture", "solid", ["furniture", "원형 목재 의자"]),
  ...entries([418, 419], "세로 목재 난간 상단", "fence", "solid", ["fence", "목재 기둥", "목재 난간"]),

  // ── 14행 (인덱스 420-449) ────────────────────────────────────────────
  one(420, "흙 서쪽 모래경계", "terrain", "passable", ["dirt", "sand edge", "서쪽"]),
  one(421, "갈색 흙바닥", "terrain", "passable", ["dirt", "흙", "지형"]),
  one(422, "흙 동쪽 모래경계", "terrain", "passable", ["dirt", "sand edge", "동쪽"]),
  one(426, "석재 바닥 좌측 테두리", "floor", "passable", ["floor", "석조 바닥 좌측", "석재 바닥", "석조 바닥"]),
  one(427, "석조 바닥 중앙", "floor", "passable", ["floor", "석재 바닥", "석조 바닥"]),
  one(428, "석재 바닥 우측 테두리", "floor", "passable", ["floor", "석조 바닥 우측", "석재 바닥", "석조 바닥"]),
  one(429, "대형 목재 해치 좌측", "prop", "solid", ["prop", "대형 목조 해치 좌측", "대형 목재 해치", "대형 목조 해치"]),
  one(430, "창 너머 어둠", "window", "solid", ["dark", "내부", "검정"]),
  one(431, "대형 목재 해치 우측", "prop", "solid", ["prop", "대형 목조 해치 우측", "대형 목재 해치", "대형 목조 해치"]),
  one(432, "나무 선반장 왼쪽", "shelf", "solid", ["shelf", "찬장", "좌측"]),
  one(433, "나무 선반장 가운데", "shelf", "solid", ["shelf", "찬장", "중앙"]),
  one(434, "나무 선반장 오른쪽", "shelf", "solid", ["shelf", "찬장", "우측"]),
  one(435, "고른 세로 나무널", "wall", "solid", ["wood", "널빤지", "세로"]),
  one(436, "대각선 목재 난간 좌측", "prop", "solid", ["prop", "대각선 목재 빔 좌측", "목재 난간", "대각선 목재 빔"]),
  one(437, "대각선 목재 난간 우측", "prop", "solid", ["prop", "대각선 목재 빔 우측", "목재 난간", "대각선 목재 빔"]),
  one(438, "선체 좌측 외벽 하단", "wall", "solid", ["wall", "배 외벽 좌현 중단", "선체"]),
  one(439, "빈 슬롯", "empty", "passable", ["empty"]),
  one(440, "배 선수 목재 외벽 하좌측", "wall", "solid", ["wall", "뱃머리 좌측 경사벽 하단", "선체"]),
  one(441, "배 선수 목재 외벽 하우측", "wall", "solid", ["wall", "뱃머리 우측 경사벽 하단", "선체"]),
  one(442, "빈 슬롯", "empty", "passable", ["empty"]),
  one(443, "선체 우측 외벽 하단", "wall", "solid", ["wall", "배 외벽 우현 중단", "선체"]),
  one(444, "파이프오르간 상단 좌측", "furniture", "solid", ["furniture", "파이프오르간"]),
  one(445, "파이프오르간 상단 우측", "furniture", "solid", ["furniture", "파이프오르간"]),
  one(446, "흰 커버 침대끝", "bed", "solid", ["bed", "이불", "발치"]),
  one(447, "가로 목재 난간 좌측", "fence", "solid", ["fence", "가로 목재 난간", "목재 난간"]),
  one(448, "십자 목재 난간 교차점", "fence", "solid", ["fence", "목재 난간 십자 교차점", "목재 난간"]),
  one(449, "가로 목재 난간 우측", "fence", "solid", ["fence", "가로 목재 난간", "목재 난간"]),

  // ── 15행 (인덱스 450-479) ────────────────────────────────────────────
  one(450, "흙 남서 모래모서리", "terrain", "passable", ["dirt", "sand corner", "남서"]),
  one(451, "흙 남쪽 모래경계", "terrain", "passable", ["dirt", "sand edge", "남쪽"]),
  one(452, "흙 남동 모래모서리", "terrain", "passable", ["dirt", "sand corner", "남동"]),
  one(456, "석재 바닥 좌측 테두리", "floor", "passable", ["floor", "석조 바닥 좌하단", "석재 바닥", "석조 바닥"]),
  one(457, "석조 바닥 하단", "floor", "passable", ["floor", "석재 바닥", "석조 바닥"]),
  one(458, "석재 바닥 우측 테두리", "floor", "passable", ["floor", "석조 바닥 우하단", "석재 바닥", "석조 바닥"]),
  one(459, "대형 목조 해치 하단 좌측", "prop", "solid", ["prop", "대형 목재 해치 좌하단", "대형 목조 해치", "대형 목재 해치"]),
  one(460, "대형 목조 해치 하단 중앙", "prop", "solid", ["prop", "대형 목재 해치 하단", "대형 목조 해치", "대형 목재 해치"]),
  one(461, "대형 목조 해치 하단 우측", "prop", "solid", ["prop", "대형 목재 해치 우하단", "대형 목조 해치", "대형 목재 해치"]),
  one(462, "왼쪽홈 가로 마루", "floor", "passable", ["floor", "가로결", "좌측홈"]),
  one(463, "목재 벽난로 화로", "prop", "solid", ["prop", "목재 화덕", "목재 벽난로", "목재 카운터"]),
  one(464, "오른쪽홈 가로 마루", "floor", "passable", ["floor", "가로결", "우측홈"]),
  one(465, "세로널 오른쪽 홈", "wall", "solid", ["wood", "세로결", "홈"]),
  one(466, "고른 가로 마루판", "floor", "passable", ["floor", "갑판", "평판"]),
  one(467, "가로 마루 우측결", "floor", "passable", ["floor", "갑판", "우측"]),
  one(468, "선체 좌측 외벽 끝단", "wall", "solid", ["wall", "배 외벽 좌현 하단", "선체"]),
  one(469, "선수 전면 목재 빔 좌측", "prop", "solid", ["prop", "배 선수 목재 보 좌측", "선수", "배 선수 구조물"]),
  one(470, "배 선수 목재 십자 보 중앙", "prop", "solid", ["prop", "선수 전면 목재 기둥 좌측", "배 선수 구조물", "선수"]),
  one(471, "선수 전면 목재 기둥 우측", "prop", "solid", ["prop", "배 선수 목재 보 우측", "선수", "배 선수 구조물"]),
  one(472, "목재 선수 돌출 기둥 하단", "prop", "solid", ["prop", "선수 돌출부 끝 기둥", "배 선수 구조물", "선수"]),
  one(473, "선체 우측 외벽 끝단", "wall", "solid", ["wall", "배 외벽 우현 하단", "선체"]),
  one(474, "나무 장롱 왼쪽", "furniture", "solid", ["wardrobe", "옷장", "좌측"]),
  one(475, "나무 장롱 오른쪽", "furniture", "solid", ["wardrobe", "옷장", "우측"]),
  one(476, "침대 베개 옆면", "bed", "solid", ["bed", "베개", "측면"]),
  one(477, "침대 이불 옆면", "bed", "solid", ["bed", "이불", "측면"]),
  one(478, "세로 목재 난간 하단", "fence", "solid", ["fence", "목재 기둥 하단", "목재 난간"]),
  one(479, "가로 목재 난간 조각", "fence", "solid", ["fence", "가로 목재 난간", "목재 난간"]),
];
