// retro_Dungeon(레트로 던전) 칩셋(tex_easyrpg_chipset_retro_dungeon) 타일 그림판의 AI 검색용 큐레이션 시맨틱 테이블.
// 6x 업스케일 행 스트립(.omo/evidence/chipset-strips/retro_dungeon/row-00..15.png) 전수 판독으로 작성했다.
// tileSemanticsDungeon.ts / tileSemanticsInterior.ts 와 동일한 계약: tileset.tileMeta[] 와 별개로
// 관리되는 검색 전용 데이터다. 통행성/레이어 계약은 tilesetHarness 가, 타일별 정밀 라벨은 여기가 담당한다.
//
// 좌표 규약: 30타일/행, ID = 행×30 + 열. 아트가 없는 슬롯(완전 투명 또는 분홍 컬러키 단색)은
// 서술할 대상이 없으므로 엔트리를 만들지 않는다 — scripts/verify-tile-semantics.mts 가 픽셀에서
// 그 목록을 직접 구해 커버리지를 검증한다.
// 판독이 애매한 타일은 단정 대신 형태 서술을 쓰고 "판독보류" 태그를 남겼다(실내 465~467 전례).
//
// 실측: 도화 가능 478칸 전수 서술, 고유 라벨 341개.
// 조립: scripts/build-tile-semantics.mts (수기 편집 대신 이 스크립트로 재생성한다).

import type { CombinedTownTileSemanticEntry } from "./tileSemanticsCombinedTown";

export type RetroDungeonTileSemanticEntry = CombinedTownTileSemanticEntry;

function entries(
  indexes: readonly number[],
  label: string,
  role: string,
  passage: "passable" | "solid",
  tags: readonly string[]
): RetroDungeonTileSemanticEntry[] {
  return indexes.map((index) => ({ index, label, role, passage, tags: [label, ...tags] }));
}

function one(
  index: number,
  label: string,
  role: string,
  passage: "passable" | "solid",
  tags: readonly string[]
): RetroDungeonTileSemanticEntry {
  return { index, label, role, passage, tags: [label, ...tags] };
}

export const RETRO_DUNGEON_TILE_SEMANTICS: readonly RetroDungeonTileSemanticEntry[] = [
  // ── 0행 (인덱스 0-29) ─────────────────────────────────────────────
  one(0, "이끼 낀 동굴 암벽 상단", "rock", "solid", ["cave", "동굴", "암벽", "이끼"]),
  one(1, "이끼 낀 동굴 암벽 북동", "rock", "solid", ["cave", "암벽", "북동"]),
  one(2, "이끼 낀 동굴 암벽 북서", "rock", "solid", ["cave", "암벽", "북서"]),
  one(3, "푸른 석재 벽돌 벽", "wall", "solid", ["masonry", "벽돌", "석재", "벽"]),
  one(4, "푸른 석재 벽돌 벽면", "wall", "solid", ["masonry", "벽돌", "벽면"]),
  one(5, "푸른 벽돌 담벼락", "wall", "solid", ["벽돌", "담", "담벼락"]),
  ...entries([6, 7, 8], "하얀 얼음 바닥", "ice", "passable", ["ice", "얼음", "바닥"]),
  one(9, "얼음 바닥 물구멍", "ice", "passable", ["ice", "얼음", "물구멍", "water"]),
  one(10, "희고 깨끗한 얼음", "ice", "passable", ["ice", "얼음", "백색"]),
  one(11, "얼음 낀 물 웅덩이", "water", "solid", ["water", "물", "웅덩이", "얼음"]),
  one(12, "적갈색 흙바닥 상단", "floor", "passable", ["흙", "바닥", "dirt", "상단"]),
  one(13, "적갈색 흙바닥 중앙", "floor", "passable", ["흙", "바닥", "dirt", "중앙"]),
  one(14, "적갈색 흙바닥 하단", "floor", "passable", ["흙", "바닥", "dirt", "하단"]),
  one(15, "갈색 흙바닥", "floor", "passable", ["흙", "바닥", "earth", "갈색"]),
  one(16, "갈색 흙바닥 상단", "floor", "passable", ["흙", "바닥", "상단"]),
  one(17, "갈색 흙바닥 경계", "floor", "passable", ["흙", "바닥", "경계"]),
  one(18, "짙은 회색 돌바닥 상단", "floor", "passable", ["돌", "바닥", "stone", "상단"]),
  one(19, "짙은 회색 돌바닥 중앙", "floor", "passable", ["돌", "바닥", "stone", "중앙"]),
  one(20, "짙은 회색 돌바닥 하단", "floor", "passable", ["돌", "바닥", "stone", "하단"]),
  one(21, "회청색 돌바닥", "floor", "passable", ["돌", "바닥", "stone"]),
  one(22, "청회색 석재 바닥", "floor", "passable", ["석재", "바닥", "stone"]),
  one(23, "푸른빛 회색 바닥", "floor", "passable", ["회색", "바닥", "stone"]),
  one(24, "물가 절벽 경계", "water", "solid", ["water", "물가", "절벽", "경계"]),
  one(25, "깊은 물 풀", "water", "solid", ["water", "물", "깊음"]),
  one(26, "물가 암석 가장자리", "water", "solid", ["water", "물가", "가장자리"]),
  one(27, "금빛 장식 소품", "prop", "solid", ["금빛", "장식", "gold", "판독보류"]),
  one(28, "금빛 조형 소품", "prop", "solid", ["금빛", "조형", "gold", "판독보류"]),
  one(29, "금빛 휘날리는 장식", "prop", "solid", ["금빛", "휘날림", "gold", "판독보류"]),

  // ── 1행 (인덱스 30-59) ─────────────────────────────────────────────
  one(30, "동굴 암벽 상단 경계", "rock", "solid", ["cave", "암벽", "동굴", "경계"]),
  one(31, "동굴 암벽 북동 경계", "rock", "solid", ["cave", "암벽", "북동"]),
  one(32, "동굴 암벽 북서 경계", "rock", "solid", ["cave", "암벽", "북서"]),
  one(33, "청회색 벽돌 벽", "wall", "solid", ["masonry", "벽돌", "벽"]),
  one(34, "청회색 벽돌 벽면", "wall", "solid", ["masonry", "벽돌", "벽면"]),
  one(35, "청회색 벽돌 담", "wall", "solid", ["벽돌", "담", "wall"]),
  ...entries([36, 37, 38], "하얀 얼음 바닥", "ice", "passable", ["ice", "얼음", "바닥"]),
  one(39, "얼음 가장자리 물", "water", "solid", ["water", "얼음", "가장자리"]),
  one(40, "얼음 사이 물가", "water", "solid", ["water", "얼음", "물가"]),
  one(41, "얼음 낀 물가", "water", "solid", ["water", "얼음", "물가"]),
  one(42, "적갈색 벽돌 바닥 상단", "floor", "passable", ["벽돌", "바닥", "brick", "상단"]),
  one(43, "적갈색 벽돌 바닥 중앙", "floor", "passable", ["벽돌", "바닥", "brick", "중앙"]),
  one(44, "적갈색 벽돌 바닥 하단", "floor", "passable", ["벽돌", "바닥", "brick", "하단"]),
  one(45, "갈색 토양 바닥", "floor", "passable", ["흙", "토양", "바닥"]),
  one(46, "갈색 흙밭", "floor", "passable", ["흙", "흙밭", "earth"]),
  one(47, "갈색 모래흙 바닥", "floor", "passable", ["흙", "모래", "바닥"]),
  ...entries([48, 49, 50], "깊은 물", "water", "solid", ["water", "물", "깊음"]),
  one(51, "얼룩진 회청색 바닥", "floor", "passable", ["회색", "바닥", "stone"]),
  one(52, "얼룩진 청회색 돌바닥", "floor", "passable", ["돌", "바닥", "stone"]),
  one(53, "반점 낀 회청색 바닥", "floor", "passable", ["회색", "반점", "바닥"]),
  one(54, "나무 난간 상단", "fence", "solid", ["wood", "나무", "난간", "울타리", "상단"]),
  one(55, "나무 난간 하단", "fence", "solid", ["wood", "나무", "난간", "하단"]),
  one(56, "나무 울타리 가로대", "fence", "solid", ["wood", "울타리", "가로대"]),
  one(57, "나무 울타리 격자", "fence", "solid", ["wood", "울타리", "격자"]),
  one(58, "나무 난간 격자", "fence", "solid", ["wood", "난간", "격자"]),
  one(59, "나무 울타리 가로대 경계", "fence", "solid", ["wood", "울타리", "가로대"]),

  // ── 2행 (인덱스 60-89) ─────────────────────────────────────────────
  one(60, "동굴 암벽 상단 모서리", "rock", "solid", ["cave", "암벽", "모서리"]),
  one(61, "동굴 암벽 북동 모서리", "rock", "solid", ["cave", "암벽", "북동"]),
  one(62, "동굴 암벽 북서 모서리", "rock", "solid", ["cave", "암벽", "북서"]),
  one(63, "석재 벽돌 벽 좌측", "wall", "solid", ["masonry", "벽돌", "벽"]),
  one(64, "석재 벽돌 벽 중앙", "wall", "solid", ["masonry", "벽돌", "벽"]),
  one(65, "석재 벽돌 벽 우측", "wall", "solid", ["masonry", "벽돌", "벽"]),
  ...entries([66, 67, 68], "하얀 얼음 바닥", "ice", "passable", ["ice", "얼음", "바닥"]),
  one(69, "얼음 위 물 경계", "water", "solid", ["water", "얼음", "경계"]),
  one(70, "깊은 얼음 물", "water", "solid", ["water", "얼음", "깊음"]),
  one(71, "얼음 변두리 물", "water", "solid", ["water", "얼음", "변두리"]),
  one(72, "적갈색 흙 바닥 우측", "floor", "passable", ["흙", "바닥", "dirt"]),
  one(73, "적갈색 흙 바닥 좌측", "floor", "passable", ["흙", "바닥", "dirt"]),
  one(74, "적갈색 흙 바닥 경계", "floor", "passable", ["흙", "바닥", "dirt"]),
  one(75, "진갈색 흙바닥", "floor", "passable", ["흙", "바닥", "earth"]),
  one(76, "갈색 흙바닥 좌측", "floor", "passable", ["흙", "바닥", "earth"]),
  one(77, "갈색 흙바닥 우측", "floor", "passable", ["흙", "바닥", "earth"]),
  one(78, "깊고 어두운 물", "water", "solid", ["water", "물", "어두움"]),
  one(79, "분홍빛 석재 바닥", "floor", "passable", ["석재", "바닥", "stone"]),
  one(80, "살구빛 석재 바닥", "floor", "passable", ["석재", "바닥", "stone"]),
  one(81, "어두운 물 웅덩이", "water", "solid", ["water", "물", "웅덩이"]),
  one(82, "살구빛 흙바닥", "floor", "passable", ["흙", "바닥", "earth"]),
  one(83, "갈색 점토 바닥", "floor", "passable", ["흙", "점토", "바닥"]),
  one(84, "나무 펜스 상단", "fence", "solid", ["wood", "펜스", "울타리", "상단"]),
  one(85, "나무 펜스 하단", "fence", "solid", ["wood", "펜스", "울타리", "하단"]),
  one(86, "나무 울타리 좌측", "fence", "solid", ["wood", "울타리", "좌측"]),
  one(87, "나무 울타리 우측", "fence", "solid", ["wood", "울타리", "우측"]),
  one(88, "나무 난간 중앙", "fence", "solid", ["wood", "난간", "중앙"]),
  one(89, "나무 울타리 격자 하단", "fence", "solid", ["wood", "울타리", "격자"]),

  // ── 3행 (인덱스 90-119) ─────────────────────────────────────────────
  one(90, "동굴 암벽 측면", "rock", "solid", ["cave", "암벽", "측면"]),
  one(91, "동굴 암벽 우측 경계", "rock", "solid", ["cave", "암벽", "우측"]),
  one(92, "동굴 암벽 좌측 경계", "rock", "solid", ["cave", "암벽", "좌측"]),
  one(93, "벽돌 석벽 상단", "wall", "solid", ["masonry", "벽돌", "석벽", "상단"]),
  one(94, "벽돌 석벽 중앙", "wall", "solid", ["masonry", "벽돌", "석벽", "중앙"]),
  one(95, "벽돌 석벽 하단", "wall", "solid", ["masonry", "벽돌", "석벽", "하단"]),
  ...entries([96, 97, 98], "하얀 얼음 바닥", "ice", "passable", ["ice", "얼음", "바닥"]),
  one(99, "얼음 바닥 물줄기", "ice", "passable", ["ice", "얼음", "물줄기", "water"]),
  one(100, "물가 얼음 경계", "water", "solid", ["water", "얼음", "물가"]),
  one(101, "얼음 낀 물 가장자리", "water", "solid", ["water", "얼음", "가장자리"]),
  one(102, "갈색 흙 지면", "floor", "passable", ["흙", "지면", "earth"]),
  one(103, "갈색 토양 지면", "floor", "passable", ["흙", "토양", "지면"]),
  one(104, "갈색 흙바닥 중앙", "floor", "passable", ["흙", "바닥", "earth"]),
  one(105, "어두운 적갈색 바닥", "floor", "passable", ["흙", "바닥", "dirt", "어두움"]),
  one(106, "적갈색 흙 무늬 바닥", "floor", "passable", ["흙", "무늬", "바닥", "dirt"]),
  one(107, "적갈색 암석 바닥", "floor", "passable", ["암석", "바닥", "stone"]),
  one(108, "분홍빛 미색 바닥", "floor", "passable", ["미색", "바닥", "stone"]),
  one(109, "살구빛 석회 바닥", "floor", "passable", ["석회", "바닥", "stone"]),
  one(110, "보랏빛 석재 바닥", "floor", "passable", ["보랏빛", "석재", "바닥", "stone"]),
  one(111, "밝은 회색 석회 바닥", "floor", "passable", ["회색", "석회", "바닥"]),
  one(112, "풀 낀 흙바닥", "floor", "passable", ["풀", "흙", "바닥", "grass"]),
  one(113, "잡초 낀 흙바닥", "floor", "passable", ["풀", "잡초", "흙", "grass"]),
  one(114, "나무 난간 좌측", "fence", "solid", ["wood", "난간", "좌측"]),
  one(115, "나무 난간 우측", "fence", "solid", ["wood", "난간", "우측"]),
  one(116, "나무 울타리 가로 빗장", "fence", "solid", ["wood", "울타리", "빗장"]),
  one(117, "나무 난간 가로 빗장", "fence", "solid", ["wood", "난간", "빗장"]),
  one(118, "뾰족한 청색 창날", "prop", "solid", ["창", "창날", "spear", "판독보류"]),
  one(119, "사선으로 솟은 창날", "prop", "solid", ["창", "창날", "spear", "판독보류"]),

  // ── 4행 (인덱스 120-149) ─────────────────────────────────────────────
  ...entries([120, 121, 122], "파란 깊은 물", "water", "solid", ["물", "water", "애니메이션"]),
  one(123, "물보라 흰 거품", "water", "solid", ["물", "거품", "foam"]),
  one(124, "맑은 얕은 물", "water", "solid", ["물", "얕음", "water"]),
  one(125, "물 위 바위 섬", "rock", "solid", ["물", "바위", "island"]),
  ...entries([126, 127, 128], "동굴 바위 바닥", "floor", "passable", ["바위", "rock", "동굴"]),
  one(129, "균열 난 검은 바위", "rock", "passable", ["바위", "균열", "crack"]),
  one(130, "거친 동굴 바위 바닥", "floor", "passable", ["바위", "rock", "동굴"]),
  one(131, "검은 동굴 구멍", "decoration", "solid", ["구멍", "어둠", "hole"]),
  one(132, "갈색 벽돌 바닥", "floor", "passable", ["벽돌", "brick", "갈색"]),
  one(133, "갈색 벽돌 벽면", "wall", "solid", ["벽돌", "wall", "갈색"]),
  one(134, "모래색 벽돌 바닥", "floor", "passable", ["벽돌", "brick", "모래"]),
  one(135, "회색 돌담 벽", "wall", "solid", ["돌", "stone", "벽"]),
  one(136, "석조 벽돌 벽면", "wall", "solid", ["돌", "stone", "회색"]),
  one(137, "돌 무늬 담벼락", "wall", "solid", ["돌", "wall", "무늬"]),
  ...entries([138, 139, 140], "타오르는 용암", "lava", "solid", ["용암", "lava", "애니메이션"]),
  ...entries([141, 142, 143], "갈색 석조 계단", "stairs", "passable", ["계단", "돌", "stairs"]),
  one(144, "물과 돌 섞인 바닥", "terrain", "passable", ["물", "돌", "판독보류"]),
  one(145, "회백색 석판 바닥", "floor", "passable", ["석판", "stone", "회색"]),
  one(146, "밝은 석조 바닥", "floor", "passable", ["돌", "stone", "밝음"]),
  one(147, "회색 돌 무늬 벽", "wall", "solid", ["돌", "wall", "회색"]),
  one(148, "어두운 석벽 면", "wall", "solid", ["돌", "벽", "어두움"]),
  one(149, "물결 섞인 돌 바닥", "terrain", "passable", ["물", "돌", "판독보류"]),

  // ── 5행 (인덱스 150-179) ─────────────────────────────────────────────
  ...entries([150, 151, 152], "푸른 파도 물", "water", "solid", ["물", "water", "애니메이션"]),
  one(153, "물보라 이는 물가", "water", "solid", ["물", "거품", "파도"]),
  one(154, "깊은 색 물 바닥", "water", "solid", ["물", "water", "깊음"]),
  one(155, "물 위 흰 바위", "rock", "solid", ["물", "바위", "rock"]),
  ...entries([156, 157, 158], "거친 바위 바닥", "floor", "passable", ["바위", "rock", "거침"]),
  one(159, "어두운 바위 틈", "rock", "passable", ["바위", "틈", "crack"]),
  one(160, "검은 바위 구덩이", "rock", "solid", ["바위", "구덩이", "pit"]),
  one(161, "그늘진 바위 바닥", "floor", "passable", ["바위", "그늘", "rock"]),
  one(162, "잔불 깔린 바위", "terrain", "passable", ["바위", "불씨", "잔불"]),
  one(163, "재와 바위 섞인 바닥", "terrain", "passable", ["재", "바위", "ash"]),
  one(164, "불씨 박힌 흙", "terrain", "passable", ["불씨", "흙", "ember"]),
  one(165, "회색 돌 바닥", "floor", "passable", ["돌", "stone", "회색"]),
  one(166, "갈색 점토 바닥", "floor", "passable", ["점토", "갈색", "clay"]),
  one(167, "석회암 돌 바닥", "floor", "passable", ["돌", "stone", "밝음"]),
  ...entries([168, 169, 170], "붉은 용암 불꽃", "lava", "solid", ["용암", "lava", "애니메이션"]),
  one(171, "갈색 돌 계단", "stairs", "passable", ["계단", "돌", "stairs"]),
  one(172, "회색 돌 경사로", "path", "passable", ["경사로", "돌", "slope"]),
  one(173, "회색 미끄럼 경사", "path", "passable", ["경사", "돌", "slope"]),
  one(174, "물 섞인 회색 바닥", "terrain", "passable", ["물", "돌", "판독보류"]),
  one(175, "회백색 돌 바닥", "floor", "passable", ["돌", "stone", "회색"]),
  one(176, "회색 석재 바닥", "floor", "passable", ["돌", "stone", "석판"]),
  one(177, "이끼 낀 밝은 벽", "wall", "solid", ["이끼", "moss", "돌"]),
  one(178, "이끼 낀 석벽 면", "wall", "solid", ["이끼", "moss", "돌"]),
  one(179, "이끼 낀 돌 바닥", "floor", "passable", ["이끼", "moss", "돌"]),

  // ── 6행 (인덱스 180-209) ─────────────────────────────────────────────
  ...entries([180, 181, 182], "짙은 물 애니메이션", "water", "solid", ["물", "water", "애니메이션"]),
  one(183, "거품 이는 물가", "water", "solid", ["물", "거품", "foam"]),
  one(184, "맑은 물 바닥", "water", "solid", ["물", "water", "맑음"]),
  one(185, "물 위 돌 더미", "rock", "solid", ["물", "바위", "돌"]),
  ...entries([186, 187, 188], "동굴 바위 바닥", "floor", "passable", ["바위", "rock", "동굴"]),
  one(189, "어두운 돌 구덩이", "rock", "solid", ["돌", "구덩이", "pit"]),
  one(190, "새까만 어둠 구멍", "terrain", "solid", ["어둠", "구멍", "void"]),
  one(191, "어두운 바위 그늘", "floor", "passable", ["바위", "그늘", "rock"]),
  one(192, "잔불 바위 흩뿌림", "terrain", "passable", ["바위", "불씨", "잔불"]),
  one(193, "불탄 돌 바닥", "terrain", "passable", ["돌", "불", "burnt"]),
  one(194, "재덮인 바위 바닥", "terrain", "passable", ["재", "바위", "ash"]),
  one(195, "황토 석조 바닥", "floor", "passable", ["황토", "돌", "stone"]),
  one(196, "돌 바닥", "floor", "passable", ["돌", "stone", "붉음"]),
  one(197, "갈색 석재 바닥", "floor", "passable", ["돌", "stone", "갈색"]),
  ...entries([198, 199, 200], "용암 불바다", "lava", "solid", ["용암", "lava", "애니메이션"]),
  one(201, "갈색 돌 계단", "stairs", "passable", ["계단", "돌", "stairs"]),
  one(202, "회색 돌 경사로", "path", "passable", ["경사로", "돌", "slope"]),
  one(203, "회색 경사 바닥", "path", "passable", ["경사", "돌", "slope"]),
  one(204, "돌 깔린 바닥 무늬", "floor", "passable", ["돌", "무늬", "stone"]),
  one(205, "회색 바둑돌 바닥", "floor", "passable", ["바둑돌", "돌", "stone"]),
  one(206, "돌 판 데크 바닥", "floor", "passable", ["돌판", "돌", "stone"]),
  ...entries([207, 208, 209], "화롯불 불꽃", "torch", "solid", ["불", "불꽃", "fire", "애니메이션"]),

  // ── 7행 (인덱스 210-239) ─────────────────────────────────────────────
  ...entries([210, 211, 212], "파란 물결 애니메이션", "water", "solid", ["물", "water", "애니메이션"]),
  one(213, "흰 거품 돌아치는 물", "water", "solid", ["물", "거품", "foam"]),
  one(214, "잔잔한 물 바닥", "water", "solid", ["물", "water", "잔잔"]),
  one(215, "물 위 바위 섬", "rock", "solid", ["물", "바위", "island"]),
  ...entries([216, 217, 218], "동굴 바위 바닥", "floor", "passable", ["바위", "rock", "동굴"]),
  one(219, "어두운 바위 굴", "rock", "solid", ["바위", "굴", "cave"]),
  one(220, "검은 동굴 어둠", "terrain", "solid", ["어둠", "동굴", "void"]),
  one(221, "어두운 돌 바닥", "floor", "passable", ["돌", "어둠", "stone"]),
  one(222, "잔불 섞인 바위", "terrain", "passable", ["바위", "불씨", "ember"]),
  one(223, "불꽃 바위 바닥", "terrain", "passable", ["바위", "불꽃", "fire"]),
  one(224, "이끼 낀 돌 바닥", "floor", "passable", ["이끼", "moss", "돌"]),
  one(225, "불 타는 바위 층", "terrain", "passable", ["바위", "불", "burnt"]),
  one(226, "잔불 가득 돌", "terrain", "passable", ["돌", "불씨", "ember"]),
  one(227, "불씨 바위 바닥", "terrain", "passable", ["바위", "불씨", "fire"]),
  ...entries([228, 229, 230], "활활 타는 불꽃", "lava", "solid", ["불꽃", "fire", "애니메이션"]),
  one(231, "갈색 돌 계단", "stairs", "passable", ["계단", "돌", "stairs"]),
  one(232, "흰 석판 무늬 벽", "wall", "solid", ["석판", "흰색", "판독보류"]),
  one(234, "회색 바둑돌 바닥", "floor", "passable", ["바둑돌", "돌", "stone"]),
  one(235, "밝은 돌 바닥 무늬", "floor", "passable", ["돌", "무늬", "stone"]),
  one(236, "회백색 돌 바닥", "floor", "passable", ["돌", "stone", "회색"]),
  one(237, "흰 석조 벽면", "wall", "solid", ["석조", "흰색", "stone"]),
  one(238, "하얀 돌 벽", "wall", "solid", ["돌", "흰색", "wall"]),
  one(239, "밝은 석조 바닥", "floor", "passable", ["돌", "stone", "밝음"]),

  // ── 8행 (인덱스 240-269) ─────────────────────────────────────────────
  one(240, "용암 바위 지면", "lava", "solid", ["용암", "lava", "지면", "애니메이션"]),
  one(241, "용암 애니메이션 2프레임", "lava", "solid", ["용암", "lava", "바위", "애니메이션"]),
  one(242, "용암 애니메이션 3프레임", "lava", "solid", ["용암", "lava", "바위", "애니메이션"]),
  one(243, "뜨거운 용암 표면", "lava", "solid", ["용암", "lava", "용융", "불길"]),
  one(244, "용암 애니메이션 4프레임", "lava", "solid", ["용암", "lava", "바위", "애니메이션"]),
  one(245, "용암 웅덩이", "lava", "solid", ["용암", "lava", "웅덩이", "반짝"]),
  one(246, "닫힌 나무 상자", "chest", "solid", ["상자", "chest", "나무", "보물"]),
  one(247, "어두운 돌 벽", "wall", "solid", ["돌", "wall", "어두움", "동굴"]),
  one(248, "장식 띠 나무 상자", "chest", "solid", ["상자", "chest", "나무", "장식"]),
  one(249, "잔자갈 돌 바닥", "floor", "passable", ["바닥", "floor", "돌", "자갈"]),
  one(250, "새까만 돌 벽", "wall", "solid", ["돌", "wall", "검정", "어두움"]),
  one(251, "뚜껑 달린 상자", "chest", "solid", ["상자", "chest", "뚜껑", "목재"]),
  one(252, "나무 판자 벽", "wall", "solid", ["나무", "wall", "판자", "목재"]),
  one(253, "나무 널빤지 벽", "wall", "solid", ["나무", "wall", "널빤지", "목재"]),
  one(254, "테두리 나무 판자", "wall", "solid", ["나무", "wall", "판자", "테두리"]),
  one(255, "흩어진 돌무더기", "rock", "solid", ["돌", "rock", "무더기", "잔해"]),
  one(256, "돌 잔해 무더기", "rock", "solid", ["돌", "rock", "잔해", "부스러기"]),
  one(257, "작은 돌 쪼가리", "rock", "solid", ["돌", "rock", "쪼가리", "흩어짐"]),
  one(259, "바위 모서리 자동타일", "rock", "solid", ["바위", "rock", "모서리", "자동타일"]),
  one(260, "바위 가장자리 자동타일", "rock", "solid", ["바위", "rock", "가장자리", "자동타일"]),
  one(261, "회색 바위 덩어리", "rock", "solid", ["회색", "rock", "바위", "언덕"]),
  one(262, "파란 물웅덩이", "water", "solid", ["물", "water", "웅덩이", "파랑"]),
  one(263, "타오르는 불꽃 1프레임", "torch", "solid", ["불꽃", "fire", "촛불", "애니메이션"]),
  one(264, "타오르는 불꽃 2프레임", "torch", "solid", ["불꽃", "fire", "촛불", "애니메이션"]),
  one(265, "회색 산봉우리", "mountain", "solid", ["산", "mountain", "봉우리", "회색"]),
  one(266, "작은 검은 사각 덩어리", "rock", "solid", ["검정", "rock", "사각", "판독보류"]),
  one(267, "진한 남색 타원 덩어리", "water", "solid", ["남색", "덩어리", "판독보류"]),
  one(268, "검푸른 구름 덩어리", "water", "solid", ["검푸름", "덩어리", "판독보류"]),
  one(269, "남색 물감 얼룩", "water", "solid", ["남색", "얼룩", "판독보류"]),

  // ── 9행 (인덱스 270-299) ─────────────────────────────────────────────
  one(270, "용암 바위 지면", "lava", "solid", ["용암", "lava", "지면", "애니메이션"]),
  one(271, "용암 애니메이션 2프레임", "lava", "solid", ["용암", "lava", "바위", "애니메이션"]),
  one(272, "용암 애니메이션 3프레임", "lava", "solid", ["용암", "lava", "바위", "애니메이션"]),
  one(273, "뜨거운 용암 표면", "lava", "solid", ["용암", "lava", "용융", "불길"]),
  one(274, "용암 웅덩이", "lava", "solid", ["용암", "lava", "웅덩이", "반짝"]),
  one(275, "밝은 용암 물결", "lava", "solid", ["용암", "lava", "밝음", "물결"]),
  one(276, "나무 보물상자", "chest", "solid", ["보물", "chest", "나무", "목재"]),
  one(277, "띠 둘린 어두운 상자", "chest", "solid", ["상자", "chest", "띠", "어두움"]),
  one(278, "목재 장식 상자", "chest", "solid", ["상자", "chest", "목재", "장식"]),
  one(279, "뚜껑 덮인 석관", "chest", "solid", ["석관", "석재", "뚜껑", "무덤"]),
  one(280, "칠흑 같은 돌 벽", "wall", "solid", ["돌", "wall", "칠흑", "어두움"]),
  one(281, "가장자리 어두운 석관", "chest", "solid", ["석관", "어두움", "가장자리", "무덤"]),
  one(282, "흐르는 물길 1프레임", "water", "solid", ["물", "water", "물길", "애니메이션"]),
  one(283, "흐르는 물길 2프레임", "water", "solid", ["물", "water", "물길", "애니메이션"]),
  one(284, "흐르는 물길 3프레임", "water", "solid", ["물", "water", "물길", "애니메이션"]),
  one(285, "잔잔한 물 표면 1", "water", "solid", ["물", "water", "표면", "잔잔"]),
  one(286, "잔잔한 물 표면 2", "water", "solid", ["물", "water", "표면", "잔잔"]),
  one(287, "잔잔한 물 표면 3", "water", "solid", ["물", "water", "표면", "잔잔"]),
  one(288, "뾰족한 암석 결정", "rock", "solid", ["암석", "rock", "뾰족", "결정"]),
  one(289, "작은 물웅덩이", "water", "solid", ["물", "water", "웅덩이", "작음"]),
  one(290, "회색 바위 언덕", "rock", "solid", ["회색", "rock", "언덕", "바위"]),
  one(291, "둥근 회색 바위", "rock", "solid", ["회색", "rock", "둥글", "바위"]),
  one(292, "푸른 물웅덩이", "water", "solid", ["물", "water", "웅덩이", "푸름"]),
  one(293, "노란 무늬 갈색 바위", "rock", "solid", ["갈색", "rock", "노랑", "판독보류"]),
  one(294, "갈색 흙 바닥", "floor", "passable", ["흙", "floor", "갈색", "땅"]),
  one(295, "그늘 진 돌 벽", "wall", "solid", ["돌", "wall", "그늘", "어두움"]),
  one(296, "세로 나무 말뚝", "prop", "solid", ["나무", "post", "말뚝", "기둥"]),
  one(297, "나무 격자 상자", "crate", "solid", ["나무", "crate", "격자", "상자"]),
  one(298, "큰 갈색 바위", "rock", "solid", ["갈색", "rock", "바위", "큼"]),
  one(299, "매끈 회색 표면 바위", "rock", "solid", ["회색", "rock", "바위", "표면"]),

  // ── 10행 (인덱스 300-329) ────────────────────────────────────────────
  one(300, "용암 바위 지면", "lava", "solid", ["용암", "lava", "지면", "애니메이션"]),
  one(301, "용암 애니메이션 2프레임", "lava", "solid", ["용암", "lava", "바위", "애니메이션"]),
  one(302, "용암 애니메이션 3프레임", "lava", "solid", ["용암", "lava", "바위", "애니메이션"]),
  one(303, "뜨거운 용암 표면", "lava", "solid", ["용암", "lava", "용융", "불길"]),
  one(304, "용암 웅덩이", "lava", "solid", ["용암", "lava", "웅덩이", "반짝"]),
  one(305, "가장자리 용암 물결", "lava", "solid", ["용암", "lava", "가장자리", "물결"]),
  one(306, "골동 나무 상자", "chest", "solid", ["상자", "chest", "나무", "골동"]),
  one(307, "먹빛 돌 벽", "wall", "solid", ["돌", "wall", "먹빛", "어두움"]),
  one(308, "쇠장식 보물상자", "chest", "solid", ["상자", "chest", "쇠", "보물"]),
  one(309, "닫힌 돌 석관", "chest", "solid", ["석관", "석재", "닫힘", "무덤"]),
  one(310, "검은 돌 벽", "wall", "solid", ["돌", "wall", "검정", "어두움"]),
  one(311, "우측 테두리 석관", "chest", "solid", ["석관", "테두리", "무덤", "어두움"]),
  one(312, "흐르는 물길 1프레임", "water", "solid", ["물", "water", "물길", "애니메이션"]),
  one(313, "흐르는 물길 2프레임", "water", "solid", ["물", "water", "물길", "애니메이션"]),
  one(314, "흐르는 물길 3프레임", "water", "solid", ["물", "water", "물길", "애니메이션"]),
  one(315, "고요한 물 표면 1", "water", "solid", ["물", "water", "표면", "고요"]),
  one(316, "고요한 물 표면 2", "water", "solid", ["물", "water", "표면", "고요"]),
  one(317, "고요한 물 표면 3", "water", "solid", ["물", "water", "표면", "고요"]),
  one(318, "거친 어두운 바위", "rock", "solid", ["바위", "rock", "거침", "어두움"]),
  one(319, "갈색 돌덩어리", "rock", "solid", ["돌", "rock", "갈색", "덩어리"]),
  one(320, "번지는 물가 가장자리", "water", "solid", ["물", "water", "가장자리", "번짐"]),
  one(321, "맑은 물웅덩이", "water", "solid", ["물", "water", "웅덩이", "맑음"]),
  one(322, "포개진 회색 바위", "rock", "solid", ["회색", "rock", "바위", "포개짐"]),
  one(323, "낮은 회색 바위", "rock", "solid", ["회색", "rock", "바위", "낮음"]),
  one(324, "갈색 흙바닥 조각", "floor", "passable", ["흙", "floor", "갈색", "땅"]),
  one(325, "석재 기단 어두운 벽", "wall", "solid", ["돌", "wall", "기단", "어두움"]),
  one(326, "가로 나무 널빤지", "floor", "passable", ["나무", "plank", "널빤지", "바닥"]),
  one(327, "갈색 풀 덩어리", "prop", "solid", ["갈색", "풀", "덩어리", "판독보류"]),
  one(328, "갈색 뭉치 풀", "prop", "solid", ["갈색", "풀", "뭉치", "판독보류"]),
  one(329, "보석 박힌 장식판", "decoration", "solid", ["보석", "장식", "석판", "판독보류"]),

  // ── 11행 (인덱스 330-359) ────────────────────────────────────────────
  one(330, "용암 바위 지면", "lava", "solid", ["용암", "lava", "지면", "애니메이션"]),
  one(331, "용암 애니메이션 2프레임", "lava", "solid", ["용암", "lava", "바위", "애니메이션"]),
  one(332, "용암 애니메이션 3프레임", "lava", "solid", ["용암", "lava", "바위", "애니메이션"]),
  one(333, "뜨거운 용암 표면", "lava", "solid", ["용암", "lava", "용융", "불길"]),
  one(334, "용암 웅덩이", "lava", "solid", ["용암", "lava", "웅덩이", "반짝"]),
  one(335, "오른쪽 용암 물결", "lava", "solid", ["용암", "lava", "오른쪽", "물결"]),
  one(336, "고대 나무 상자", "chest", "solid", ["상자", "chest", "나무", "고대"]),
  one(337, "밑단 어두운 돌 벽", "wall", "solid", ["돌", "wall", "밑단", "어두움"]),
  one(338, "고대 목재 상자", "chest", "solid", ["상자", "chest", "목재", "고대"]),
  one(339, "돌 석관", "chest", "solid", ["석관", "석재", "관", "무덤"]),
  one(340, "아랫단 그늘 돌 벽", "wall", "solid", ["돌", "wall", "아랫단", "그늘"]),
  one(341, "오른쪽 어두운 석관", "chest", "solid", ["석관", "오른쪽", "무덤", "어두움"]),
  one(342, "흐르는 물길 1프레임", "water", "solid", ["물", "water", "물길", "애니메이션"]),
  one(343, "흐르는 물길 2프레임", "water", "solid", ["물", "water", "물길", "애니메이션"]),
  one(344, "흐르는 물길 3프레임", "water", "solid", ["물", "water", "물길", "애니메이션"]),
  one(345, "물 위 디딤돌 다리", "bridge", "passable", ["다리", "bridge", "디딤돌", "물"]),
  one(346, "물결지는 물 표면 1", "water", "solid", ["물", "water", "표면", "물결"]),
  one(347, "물결지는 물 표면 2", "water", "solid", ["물", "water", "표면", "물결"]),
  one(348, "질감 난 어두운 바위", "rock", "solid", ["바위", "rock", "질감", "어두움"]),
  one(349, "갈색 바위 덩어리", "rock", "solid", ["돌", "rock", "갈색", "덩어리"]),
  one(350, "넓은 물웅덩이", "water", "solid", ["물", "water", "웅덩이", "넓음"]),
  one(351, "연못 물결", "water", "solid", ["물", "water", "연못", "물결"]),
  one(352, "거대 회색 바위", "rock", "solid", ["회색", "rock", "바위", "거대"]),
  one(353, "매끈 회색 바위", "rock", "solid", ["회색", "rock", "바위", "매끈"]),
  one(354, "갈색 뻘 바닥", "floor", "passable", ["흙", "floor", "갈색", "뻘"]),
  one(355, "겹겹 바위 지형", "rock", "solid", ["바위", "rock", "지형", "겹겹"]),
  one(356, "갈색 돌기 덩어리", "prop", "solid", ["갈색", "돌기", "덩어리", "판독보류"]),
  one(357, "갈색 가시 덩어리", "prop", "solid", ["갈색", "가시", "덩어리", "판독보류"]),
  one(358, "갈색 돌무더기", "rock", "solid", ["갈색", "rock", "무더기", "판독보류"]),
  one(359, "화려한 무늬 장식판", "decoration", "solid", ["장식", "무늬", "석판", "판독보류"]),

  // ── 12행 (인덱스 360-389) ────────────────────────────────────────────
  ...entries([360, 361, 362], "갈색 흙 바닥", "floor", "passable", ["흙", "바닥", "floor"]),
  one(363, "이끼 낀 갈색 바닥", "floor", "passable", ["이끼", "moss", "바닥"]),
  one(364, "갈색 흙 바닥", "floor", "passable", ["흙", "바닥", "floor"]),
  one(365, "초록 이끼 바닥", "floor", "passable", ["초록", "이끼", "moss"]),
  one(366, "푸른 물웅덩이", "water", "solid", ["물", "웅덩이", "water"]),
  one(367, "짙은 파란 물", "water", "solid", ["물", "파란", "water"]),
  one(368, "가장자리 파란 물", "water", "solid", ["물", "가장자리", "water"]),
  one(369, "돌 테두리 푸른 웅덩이", "water", "solid", ["웅덩이", "돌테", "water"]),
  one(370, "어두운 물구덩이", "water", "solid", ["물", "구덩이", "water"]),
  one(371, "돌 테두리 어두운 물", "water", "solid", ["물", "돌테", "water"]),
  ...entries([372, 373, 374], "잔물결 파란 물", "water", "solid", ["잔물결", "water", "애니메이션"]),
  ...entries([375, 376, 377], "파란 무늬 흰 얼음", "ice", "passable", ["얼음", "ice", "무늬"]),
  ...entries([378, 379], "갈색 둥근 덩어리", "prop", "solid", ["둥근", "무더기", "판독보류"]),
  ...entries([380, 381], "갈색 덩어리", "prop", "solid", ["덩어리", "prop", "판독보류"]),
  one(382, "회색 둥근 바위", "rock", "solid", ["회색", "바위", "rock"]),
  one(383, "회색 둥근 돌", "rock", "solid", ["회색", "돌", "rock"]),
  one(384, "푸른 테두리 명판", "decoration", "solid", ["명판", "장식", "sign"]),
  ...entries([385, 386, 387, 388], "나무 판벽", "wall", "solid", ["wood", "판자", "목재"]),
  one(389, "나무 상자", "chest", "solid", ["나무", "상자", "wood"]),

  // ── 13행 (인덱스 390-419) ────────────────────────────────────────────
  ...entries([390, 391, 392], "갈색 흙 바닥", "floor", "passable", ["흙", "바닥", "floor"]),
  ...entries([393, 394, 395], "초록 이끼 바닥", "floor", "passable", ["초록", "이끼", "moss"]),
  one(396, "가장자리 파란 물", "water", "solid", ["물", "가장자리", "water"]),
  one(397, "짙은 파란 물", "water", "solid", ["물", "파란", "water"]),
  one(398, "가장자리 파란 물", "water", "solid", ["물", "가장자리", "water"]),
  one(399, "돌 테두리 푸른 웅덩이", "water", "solid", ["웅덩이", "돌테", "water"]),
  one(400, "어두운 물구덩이", "water", "solid", ["물", "구덩이", "water"]),
  one(401, "돌 테두리 어두운 물", "water", "solid", ["물", "돌테", "water"]),
  ...entries([402, 403, 404], "잔물결 파란 물", "water", "solid", ["잔물결", "water", "애니메이션"]),
  one(405, "왼편 그늘 어두운 돌벽", "rock", "solid", ["그늘", "돌벽", "rock"]),
  one(406, "어두운 돌 블록", "rock", "solid", ["돌", "블록", "rock"]),
  one(407, "오른편 그늘 어두운 돌벽", "rock", "solid", ["그늘", "돌벽", "rock"]),
  one(408, "흰 뾰족 암석", "rock", "solid", ["흰", "뾰족", "rock"]),
  one(409, "흰 뾰족 바위 조각", "rock", "solid", ["흰", "바위", "rock"]),
  one(410, "어두운 뾰족 암석", "rock", "solid", ["어두운", "뾰족", "rock"]),
  one(411, "어두운 뾰족 바위 조각", "rock", "solid", ["어두운", "바위", "rock"]),
  one(412, "불 붙은 화로", "torch", "solid", ["화로", "불꽃", "brazier"]),
  one(413, "푸른 뾰족 장식", "decoration", "solid", ["푸른", "장식", "판독보류"]),
  one(414, "푸른 테 흰 문", "door", "solid", ["문", "door", "푸른테"]),
  one(415, "어두운 문틀 문", "door", "solid", ["문", "door", "문틀"]),
  one(416, "흰 돌 기둥", "pillar", "solid", ["기둥", "pillar", "흰"]),
  one(417, "주황 장식 기둥", "pillar", "solid", ["기둥", "장식", "판독보류"]),
  one(418, "돌 항아리", "prop", "solid", ["항아리", "pot", "판독보류"]),
  one(419, "갈색 돌멩이", "rock", "solid", ["돌", "rock"]),

  // ── 14행 (인덱스 420-449) ────────────────────────────────────────────
  ...entries([420, 421, 422], "갈색 흙 바닥", "floor", "passable", ["흙", "바닥", "floor"]),
  ...entries([423, 424, 425], "초록 이끼 바닥", "floor", "passable", ["초록", "이끼", "moss"]),
  one(426, "가장자리 파란 물", "water", "solid", ["물", "가장자리", "water"]),
  one(427, "짙은 파란 물", "water", "solid", ["물", "파란", "water"]),
  one(428, "가장자리 파란 물", "water", "solid", ["물", "가장자리", "water"]),
  one(429, "돌 테두리 푸른 웅덩이", "water", "solid", ["웅덩이", "돌테", "water"]),
  one(430, "어두운 물구덩이", "water", "solid", ["물", "구덩이", "water"]),
  one(431, "돌 테두리 어두운 물", "water", "solid", ["물", "돌테", "water"]),
  ...entries([432, 433], "낡은 돌 벽돌 벽면", "wall", "solid", ["벽돌", "벽", "wall"]),
  one(434, "회색 돌 벽돌 벽면", "wall", "solid", ["벽돌", "벽", "wall"]),
  one(435, "왼편 그늘 회색 돌벽", "rock", "solid", ["그늘", "돌벽", "rock"]),
  one(436, "회색 둥근 바위", "rock", "solid", ["회색", "바위", "boulder", "돌덩이"]),
  one(437, "오른편 그늘 회색 돌벽", "rock", "solid", ["그늘", "돌벽", "rock"]),
  one(438, "회색 돌 경계 벽", "wall", "solid", ["돌", "벽", "wall"]),
  one(439, "회청색 돌 벽면", "wall", "solid", ["돌", "벽면", "wall"]),
  one(440, "회색 돌 경계 벽", "wall", "solid", ["돌", "벽", "wall"]),
  one(441, "갈색 격자 아치 좌측", "decoration", "solid", ["격자", "아치", "판독보류", "lattice"]),
  one(442, "갈색 격자 아치 중앙", "decoration", "solid", ["격자", "아치", "판독보류", "lattice"]),
  one(443, "갈색 격자 아치 우측", "decoration", "solid", ["격자", "아치", "판독보류", "lattice"]),
  one(444, "나무 살대 울타리 좌", "fence", "solid", ["살대", "목재", "울타리", "fence"]),
  one(445, "나무 살대 울타리 우", "fence", "solid", ["살대", "목재", "울타리", "fence"]),
  one(446, "회색 돌 기둥", "pillar", "solid", ["기둥", "pillar", "돌"]),
  one(447, "황금 왕좌 좌측 상단", "furniture", "solid", ["왕좌", "금장식", "throne", "옥좌"]),
  one(448, "붉은 왕좌 등받이", "furniture", "solid", ["왕좌", "등받이", "throne", "옥좌"]),
  one(449, "황금 왕좌 우측 상단", "furniture", "solid", ["왕좌", "금장식", "throne", "옥좌"]),

  // ── 15행 (인덱스 450-479) ────────────────────────────────────────────
  ...entries([450, 451], "갈색 흙 바닥", "floor", "passable", ["흙", "바닥", "floor"]),
  one(452, "갈색 흙돌 바닥", "floor", "passable", ["갈색", "흙돌", "floor"]),
  ...entries([453, 454, 455], "초록 이끼 바닥", "floor", "passable", ["초록", "이끼", "moss"]),
  one(456, "가장자리 파란 물", "water", "solid", ["물", "가장자리", "water"]),
  one(457, "짙은 파란 물", "water", "solid", ["물", "파란", "water"]),
  one(458, "가장자리 파란 물", "water", "solid", ["물", "가장자리", "water"]),
  one(459, "돌 테두리 푸른 웅덩이", "water", "solid", ["웅덩이", "돌테", "water"]),
  one(460, "어두운 물구덩이", "water", "solid", ["물", "구덩이", "water"]),
  one(461, "돌 테두리 어두운 물", "water", "solid", ["물", "돌테", "water"]),
  ...entries([462, 463], "낡은 돌 벽돌 벽면", "wall", "solid", ["벽돌", "벽", "wall"]),
  one(464, "어두운 돌 벽돌 벽면", "wall", "solid", ["벽돌", "벽", "wall"]),
  one(465, "왼편 그늘 회색 돌벽", "rock", "solid", ["그늘", "돌벽", "rock"]),
  one(466, "어두운 돌 블록", "rock", "solid", ["돌", "블록", "rock"]),
  one(467, "오른편 그늘 회색 돌벽", "rock", "solid", ["그늘", "돌벽", "rock"]),
  one(468, "회색 돌 경계 벽", "wall", "solid", ["돌", "벽", "wall"]),
  one(469, "회청색 돌 벽면", "wall", "solid", ["돌", "벽면", "wall"]),
  one(470, "회색 돌 경계 벽", "wall", "solid", ["돌", "벽", "wall"]),
  one(471, "갈색 격자 문양 좌측", "decoration", "solid", ["격자", "문양", "판독보류", "lattice"]),
  one(472, "갈색 격자 원형 문양", "decoration", "solid", ["격자", "원형", "판독보류", "lattice"]),
  one(473, "갈색 격자 문양 우측", "decoration", "solid", ["격자", "문양", "판독보류", "lattice"]),
  one(474, "밝은 나무 살대 좌", "fence", "solid", ["살대", "목재", "울타리", "fence"]),
  one(475, "밝은 나무 살대 우", "fence", "solid", ["살대", "목재", "울타리", "fence"]),
  one(476, "회색 돌 기둥", "pillar", "solid", ["기둥", "pillar", "돌"]),
  one(477, "황금 왕좌 좌측 팔걸이", "furniture", "solid", ["왕좌", "팔걸이", "throne", "옥좌"]),
  one(478, "붉은 왕좌 좌석", "furniture", "solid", ["왕좌", "좌석", "throne", "옥좌"]),
  one(479, "황금 왕좌 우측 팔걸이", "furniture", "solid", ["왕좌", "팔걸이", "throne", "옥좌"]),
];
