// World(월드맵) 칩셋(tex_easyrpg_chipset_world) 타일 그림판의 AI 검색용 큐레이션 시맨틱 테이블.
// 6x 업스케일 행 스트립(.omo/evidence/chipset-strips/world/row-00..15.png) 전수 판독으로 작성했다.
// tileSemanticsDungeon.ts / tileSemanticsInterior.ts 와 동일한 계약: tileset.tileMeta[] 와 별개로
// 관리되는 검색 전용 데이터다. 통행성/레이어 계약은 tilesetHarness 가, 타일별 정밀 라벨은 여기가 담당한다.
//
// 좌표 규약: 30타일/행, ID = 행×30 + 열. 아트가 없는 슬롯(완전 투명 또는 분홍 컬러키 단색)은
// 서술할 대상이 없으므로 엔트리를 만들지 않는다 — scripts/verify-tile-semantics.mts 가 픽셀에서
// 그 목록을 직접 구해 커버리지를 검증한다.
// 판독이 애매한 타일은 단정 대신 형태 서술을 쓰고 "판독보류" 태그를 남겼다(실내 465~467 전례).
//
// 실측: 도화 가능 478칸 전수 서술, 고유 라벨 381개.
// 조립: scripts/build-tile-semantics.mts (수기 편집 대신 이 스크립트로 재생성한다).

import type { CombinedTownTileSemanticEntry } from "./tileSemanticsCombinedTown";

export type WorldTileSemanticEntry = CombinedTownTileSemanticEntry;

function entries(
  indexes: readonly number[],
  label: string,
  role: string,
  passage: "passable" | "solid",
  tags: readonly string[]
): WorldTileSemanticEntry[] {
  return indexes.map((index) => ({ index, label, role, passage, tags: [label, ...tags] }));
}

function one(
  index: number,
  label: string,
  role: string,
  passage: "passable" | "solid",
  tags: readonly string[]
): WorldTileSemanticEntry {
  return { index, label, role, passage, tags: [label, ...tags] };
}

export const WORLD_TILE_SEMANTICS: readonly WorldTileSemanticEntry[] = [
  // ── 0행 (인덱스 0-29) ─────────────────────────────────────────────
  one(0, "초원 바다 해안 모서리", "coast", "solid", ["coast", "해안", "바다", "초원"]),
  one(1, "초원 바다 해안 변형", "coast", "solid", ["coast", "해안", "바다", "초원"]),
  one(2, "초원 해안 곡선 물가", "coast", "solid", ["coast", "해안", "물가", "바다"]),
  one(3, "파도 바다 해안 물가", "coast", "solid", ["coast", "해안", "파도", "바다"]),
  one(4, "물보라 바다 해안", "coast", "solid", ["coast", "해안", "물보라", "파도"]),
  one(5, "잔잔한 바다 해안", "coast", "solid", ["coast", "해안", "잔잔", "바다"]),
  one(6, "갈색 밭 흙바닥", "terrain", "passable", ["dirt", "밭", "흙", "평원"]),
  one(7, "평원 초록 잔디", "terrain", "passable", ["grass", "초원", "잔디", "평야"]),
  one(8, "초원 속 갈색 밭", "terrain", "passable", ["field", "밭", "초원", "흙"]),
  one(9, "모래 사막 바위 지대", "sand", "passable", ["desert", "사막", "모래", "바위"]),
  one(10, "초원 푸른 잔디 평야", "terrain", "passable", ["grass", "초원", "잔디", "평야"]),
  one(11, "모래 사막 초원 경계", "sand", "passable", ["desert", "사막", "경계", "모래"]),
  one(12, "갈색 바위 산악 지대", "mountain", "solid", ["rock", "바위", "산악", "산"]),
  one(13, "풀섞인 바위 고지대", "mountain", "solid", ["rock", "바위", "고지", "풀"]),
  one(14, "늪지 습지 어두운 물", "terrain", "passable", ["swamp", "늪지", "습지", "물"]),
  one(15, "늪지 진흙 물웅덩이", "terrain", "passable", ["swamp", "늪지", "진흙", "습지"]),
  one(16, "늪지 습지 검은 물", "terrain", "passable", ["swamp", "늪지", "습지", "검은물"]),
  one(17, "늪지 습지 물길", "terrain", "passable", ["swamp", "늪지", "습지", "물길"]),
  one(18, "어두운 갈색 흙바닥", "terrain", "passable", ["dirt", "흙", "갈색", "지면"]),
  one(19, "초원 어두운 흙 경계", "terrain", "passable", ["dirt", "흙", "초원", "경계"]),
  one(20, "갈색 흙 평원 바닥", "terrain", "passable", ["dirt", "흙", "평원", "평지"]),
  one(21, "갈색 밭 흙 평지", "terrain", "passable", ["dirt", "밭", "흙", "평지"]),
  one(22, "흙 땅 바다 물가", "coast", "solid", ["coast", "물가", "바다", "흙"]),
  one(23, "바다 물가 흙 해안", "coast", "solid", ["coast", "해안", "바다", "물가"]),
  one(24, "초원 언덕 경사면", "terrain", "passable", ["hill", "언덕", "초원", "경사"]),
  one(25, "언덕 초원 경사면", "terrain", "passable", ["hill", "언덕", "경사", "초원"]),
  one(26, "갈색 흙 언덕 경사", "terrain", "passable", ["hill", "언덕", "흙", "경사"]),
  one(27, "흙 언덕 경사 지면", "terrain", "passable", ["hill", "언덕", "흙", "경사"]),
  one(28, "초원 바다 물가 해안", "coast", "solid", ["coast", "물가", "바다", "초원"]),
  one(29, "바다 물가 초원 해안", "coast", "solid", ["coast", "해안", "바다", "물가"]),

  // ── 1행 (인덱스 30-59) ─────────────────────────────────────────────
  one(30, "해안 초원 바다 경계", "coast", "solid", ["coast", "해안", "바다", "초원"]),
  one(31, "해안 초원 바다 변형", "coast", "solid", ["coast", "해안", "바다", "초원"]),
  one(32, "해안 초원 바다 모서리", "coast", "solid", ["coast", "해안", "바다", "초원"]),
  one(33, "얕은 바다 백사 해안", "coast", "solid", ["coast", "해안", "백사", "바다"]),
  one(34, "백사장 얕은 바다", "coast", "solid", ["beach", "백사", "해변", "바다"]),
  one(35, "얕은 바다 해안 물가", "coast", "solid", ["coast", "해안", "물가", "바다"]),
  one(36, "초원 흙 언덕 경계", "terrain", "passable", ["hill", "언덕", "흙", "초원"]),
  one(37, "초원 흙 경사면", "terrain", "passable", ["hill", "언덕", "흙", "경사"]),
  one(38, "초원 흙 밭 경계", "terrain", "passable", ["field", "밭", "흙", "초원"]),
  one(39, "초원 사막 모래 경계", "sand", "passable", ["desert", "사막", "모래", "경계"]),
  one(40, "모래 사막 평원 바닥", "sand", "passable", ["desert", "사막", "모래", "평원"]),
  one(41, "모래 사막 언덕 경계", "sand", "passable", ["desert", "사막", "언덕", "모래"]),
  one(42, "갈색 바위 산악 암석", "mountain", "solid", ["rock", "바위", "산악", "암석"]),
  one(43, "풀 낀 바위 산악지대", "mountain", "solid", ["rock", "바위", "풀", "산악"]),
  one(44, "늪지 습지 어두운 물가", "terrain", "passable", ["swamp", "늪지", "습지", "물가"]),
  one(45, "늪지 진흙 습지 물", "terrain", "passable", ["swamp", "늪지", "진흙", "습지"]),
  one(46, "늪지 습지 검은 물가", "terrain", "passable", ["swamp", "늪지", "습지", "검은"]),
  one(47, "늪지 습지 웅덩이", "terrain", "passable", ["swamp", "늪지", "습지", "웅덩이"]),
  one(48, "초원 언덕 경사 오른쪽", "terrain", "passable", ["hill", "언덕", "초원", "경사"]),
  one(49, "언덕 초원 경사 언덕", "terrain", "passable", ["hill", "언덕", "경사", "초원"]),
  one(50, "갈색 흙 언덕 오른쪽", "terrain", "passable", ["hill", "언덕", "흙", "경사"]),
  one(51, "흙 언덕 경사 바닥", "terrain", "passable", ["hill", "언덕", "흙", "경사"]),
  one(52, "초원 바다 물가 오른쪽", "coast", "solid", ["coast", "물가", "바다", "초원"]),
  one(53, "바다 물가 초원 언덕", "coast", "solid", ["coast", "물가", "바다", "초원"]),
  one(54, "마을 가옥 지붕 무리", "town-icon", "solid", ["town", "마을", "가옥", "지붕"]),
  one(55, "마을 초가집 이중 지붕", "town-icon", "solid", ["town", "마을", "초가집", "지붕"]),
  one(56, "마을 단독 가옥 지붕", "town-icon", "solid", ["town", "마을", "가옥", "지붕"]),
  one(57, "바위산 봉우리 고원", "mountain", "solid", ["mountain", "산", "바위", "봉우리"]),
  one(58, "심해 소용돌이 물결", "water", "solid", ["water", "물", "소용돌이", "심해"]),
  one(59, "바위산 고원 봉우리", "mountain", "solid", ["mountain", "산", "바위", "고원"]),

  // ── 2행 (인덱스 60-89) ─────────────────────────────────────────────
  one(60, "해안 초원 바다 북쪽", "coast", "solid", ["coast", "해안", "바다", "초원"]),
  one(61, "해안 초원 바다 변형", "coast", "solid", ["coast", "해안", "바다", "초원"]),
  one(62, "해안 초원 바다 곡선", "coast", "solid", ["coast", "해안", "바다", "초원"]),
  one(63, "얕은 바다 해안 백사", "coast", "solid", ["coast", "해안", "백사", "바다"]),
  one(64, "백사장 해안 얕은 물", "coast", "solid", ["beach", "백사", "해변", "물가"]),
  one(65, "얕은 바다 해안 물가", "coast", "solid", ["coast", "해안", "물가", "바다"]),
  one(66, "초원 흙 구릉 경계", "terrain", "passable", ["hill", "구릉", "흙", "초원"]),
  one(67, "갈색 흙 평지 바닥", "terrain", "passable", ["dirt", "흙", "평지", "지면"]),
  one(68, "흙 초원 경사 구릉", "terrain", "passable", ["hill", "구릉", "경사", "흙"]),
  one(69, "초원 사막 모래 경계", "sand", "passable", ["desert", "사막", "모래", "경계"]),
  one(70, "모래 사막 평야 바닥", "sand", "passable", ["desert", "사막", "모래", "평야"]),
  one(71, "모래 사막 구릉 경계", "sand", "passable", ["desert", "사막", "구릉", "모래"]),
  one(72, "갈색 흙 두둑 평지", "terrain", "passable", ["dirt", "흙", "두둑", "평지"]),
  one(73, "갈색 밭 이랑 지면", "terrain", "passable", ["field", "밭", "이랑", "흙"]),
  one(74, "모래 해변 얕은 물가", "sand", "passable", ["beach", "해변", "모래", "물가"]),
  one(75, "모래 해변 물굽이", "sand", "passable", ["beach", "해변", "모래", "물굽이"]),
  one(76, "모래 해변 어귀 물가", "sand", "passable", ["beach", "해변", "모래", "어귀"]),
  one(77, "모래 해변 바다 어귀", "sand", "passable", ["beach", "해변", "모래", "바다"]),
  one(78, "초원 잔디 평원 바닥", "terrain", "passable", ["grass", "초원", "잔디", "평원"]),
  one(79, "초원 평야 푸른 잔디", "terrain", "passable", ["grass", "초원", "잔디", "평야"]),
  one(80, "초원 언덕 경사 언덕", "terrain", "passable", ["hill", "언덕", "초원", "경사"]),
  one(81, "어두운 갈색 흙 평지", "terrain", "passable", ["dirt", "흙", "갈색", "평지"]),
  one(82, "갈색 흙 평원 지면", "terrain", "passable", ["dirt", "흙", "평원", "지면"]),
  one(83, "갈색 밭 흙 이랑", "terrain", "passable", ["dirt", "밭", "흙", "이랑"]),
  one(84, "마을 탑 건물 랜드마크", "town-icon", "solid", ["town", "탑", "마을", "건물"]),
  one(85, "마을 가옥 지붕 두 채", "town-icon", "solid", ["town", "마을", "가옥", "지붕"]),
  one(86, "마을 탑 단독 랜드마크", "town-icon", "solid", ["town", "탑", "마을", "랜드마크"]),
  one(87, "동굴 바위산 봉우리", "mountain", "solid", ["mountain", "동굴", "바위", "산"]),
  one(88, "거무튀튀한 암석 구조물", "rock", "solid", ["rock", "암석", "구조물", "검은", "판독보류"]),
  one(89, "바위산 말단 봉우리", "mountain", "solid", ["mountain", "산", "바위", "말단"]),

  // ── 3행 (인덱스 90-119) ─────────────────────────────────────────────
  one(90, "해안 초원 바다 경계", "coast", "solid", ["coast", "해안", "바다", "초원"]),
  one(91, "해안 초원 바다 변형", "coast", "solid", ["coast", "해안", "바다", "초원"]),
  one(92, "해안 초원 바다 모서리", "coast", "solid", ["coast", "해안", "바다", "초원"]),
  one(93, "얕은 바다 해안 물가", "coast", "solid", ["coast", "해안", "바다", "물가"]),
  one(94, "백사장 해안 얕은 바다", "coast", "solid", ["beach", "백사", "해변", "바다"]),
  one(95, "얕은 바다 해안 백사", "coast", "solid", ["coast", "해안", "백사", "바다"]),
  one(96, "초원 흙 구릉 경계", "terrain", "passable", ["hill", "구릉", "흙", "초원"]),
  one(97, "갈색 흙 평지 지면", "terrain", "passable", ["dirt", "흙", "평지", "지면"]),
  one(98, "흙 구릉 초원 경계", "terrain", "passable", ["hill", "구릉", "흙", "초원"]),
  one(99, "초원 사막 모래 경계", "sand", "passable", ["desert", "사막", "모래", "경계"]),
  one(100, "모래 사막 평원 지면", "sand", "passable", ["desert", "사막", "모래", "평원"]),
  one(101, "모래 사막 구릉 경계", "sand", "passable", ["desert", "사막", "구릉", "모래"]),
  one(102, "갈색 밭 이랑 지면", "terrain", "passable", ["field", "밭", "이랑", "흙"]),
  one(103, "갈색 밭두둑 지면", "terrain", "passable", ["field", "밭", "두둑", "흙"]),
  one(104, "모래 해변 물가 백사", "sand", "passable", ["beach", "해변", "모래", "백사"]),
  one(105, "모래 해변 모래 평지", "sand", "passable", ["beach", "해변", "모래", "평지"]),
  one(106, "모래 해변 어귀 바다", "sand", "passable", ["beach", "해변", "모래", "어귀"]),
  one(107, "모래 해변 바다 물가", "sand", "passable", ["beach", "해변", "모래", "바다"]),
  one(108, "초원 잔디 평원 바닥", "terrain", "passable", ["grass", "초원", "잔디", "평원"]),
  one(109, "초원 평야 푸른 잔디", "terrain", "passable", ["grass", "초원", "잔디", "평야"]),
  one(110, "초원 언덕 경사 지면", "terrain", "passable", ["hill", "언덕", "초원", "경사"]),
  one(111, "갈색 흙 다진 평지", "terrain", "passable", ["dirt", "흙", "평지", "흙바닥"]),
  one(112, "갈색 흙 평원 바닥", "terrain", "passable", ["dirt", "흙", "평원", "밭"]),
  one(113, "갈색 흙 언덕 경계", "terrain", "passable", ["hill", "언덕", "흙", "경계"]),
  one(114, "마을 가옥 지붕 랜드마크", "town-icon", "solid", ["town", "마을", "가옥", "지붕"]),
  one(115, "마을 성곽 가옥 지붕", "town-icon", "solid", ["town", "마을", "성곽", "지붕"]),
  one(116, "성채 성곽 랜드마크", "town-icon", "solid", ["castle", "성", "성채", "랜드마크"]),
  one(117, "흩어진 바위 초목 무리", "prop", "solid", ["scattered", "흩어진", "바위", "초목", "판독보류"]),
  one(118, "바위 작은 섬 랜드마크", "rock", "solid", ["rock", "바위", "섬", "랜드마크"]),
  one(119, "바위 암석 덩어리 땅", "rock", "solid", ["rock", "바위", "암석", "땅"]),

  // ── 4행 (인덱스 120-149) ─────────────────────────────────────────────
  one(120, "깊은 바다 물결", "water", "solid", ["바다", "물", "애니메이션"]),
  one(121, "먼바다 잔물결", "water", "solid", ["파도", "수면", "애니메이션"]),
  one(122, "짙은 심해 수면", "water", "solid", ["심해", "어두운", "애니메이션"]),
  one(123, "물거품 이는 바다", "water", "solid", ["물거품", "파도", "애니메이션"]),
  one(124, "하얀 포말 해면", "water", "solid", ["포말", "하얀", "애니메이션"]),
  one(125, "부서지는 파도", "water", "solid", ["물보라", "파도", "애니메이션"]),
  one(126, "진주빛 심해 물결", "water", "solid", ["심해", "반짝임", "애니메이션"]),
  one(127, "초록 삼림 캐노피", "forest", "passable", ["삼림", "캐노피", "초록"]),
  one(128, "물가 초원 해안", "coast", "passable", ["해안", "초원", "물가"]),
  one(129, "하얀 물보라 물가", "coast", "solid", ["물보라", "얕은바다"]),
  one(130, "평원 초지", "terrain", "passable", ["평야", "풀밭", "초지"]),
  one(131, "초원 물가 경계", "coast", "passable", ["초원", "경계", "물가"]),
  one(132, "잿빛 암반 지대", "rock", "solid", ["암반", "바위", "잿빛"]),
  one(133, "이끼 낀 바위 지대", "rock", "solid", ["바위", "이끼", "지대"]),
  one(134, "황사 바위 언덕", "rock", "solid", ["바위", "언덕", "황사"]),
  one(135, "자갈 모래 언덕", "sand", "passable", ["자갈", "모래", "언덕"]),
  one(136, "황토 바위 사막", "sand", "passable", ["황토", "사막", "바위"]),
  one(137, "모래 바위 지대", "sand", "passable", ["모래", "바위", "지대"]),
  one(138, "흙길 난 초원", "path", "passable", ["흙길", "초원", "오솔길"]),
  one(139, "초록 목초지", "terrain", "passable", ["목초지", "초원", "풀밭"]),
  one(140, "푸른 평원 풀밭", "terrain", "passable", ["평원", "풀밭", "푸른"]),
  one(141, "갈색 산악 평원", "terrain", "passable", ["산악", "평야", "갈색"]),
  one(142, "갈색 언덕 지대", "terrain", "passable", ["언덕", "갈색", "지대"]),
  one(143, "황토 산맥 땅", "terrain", "passable", ["산맥", "황토", "땅"]),
  one(144, "불꽃 봉수대 아이콘", "torch", "solid", ["봉수대", "불꽃", "표지"]),
  one(145, "언덕 위 밝은 표지", "town-icon", "solid", ["언덕", "표지", "등불", "판독보류"]),
  one(146, "작은 바위 언덕", "rock", "solid", ["바위", "언덕", "아이콘"]),
  one(147, "기와지붕 대형 건물", "town-icon", "solid", ["건물", "지붕", "지도"]),
  one(148, "문과 창 큰 건물", "town-icon", "solid", ["건물", "창문", "문"]),
  one(149, "돌벽 큰 건물", "town-icon", "solid", ["건물", "돌벽", "지도"]),

  // ── 5행 (인덱스 150-179) ─────────────────────────────────────────────
  one(150, "깊은 바다 물결", "water", "solid", ["바다", "물", "애니메이션"]),
  one(151, "먼바다 잔물결", "water", "solid", ["파도", "수면", "애니메이션"]),
  one(152, "짙은 심해 수면", "water", "solid", ["심해", "어두운", "애니메이션"]),
  one(153, "물거품 이는 바다", "water", "solid", ["물거품", "파도", "애니메이션"]),
  one(154, "하얀 포말 해면", "water", "solid", ["포말", "하얀", "애니메이션"]),
  one(155, "부서지는 파도", "water", "solid", ["물보라", "파도", "애니메이션"]),
  one(156, "진주빛 심해 물결", "water", "solid", ["심해", "반짝임", "애니메이션"]),
  one(157, "물가 풀밭 땅", "terrain", "passable", ["풀밭", "언덕", "물가"]),
  one(158, "물가 초원 해안", "coast", "passable", ["해안", "초원", "물가"]),
  one(159, "하얀 물보라 물가", "coast", "solid", ["물보라", "휜", "해안"]),
  one(160, "평원 초지", "terrain", "passable", ["평야", "풀밭", "초지"]),
  one(161, "초원 물가 경계", "coast", "passable", ["초원", "경계", "물가"]),
  one(162, "회색 바위 지대", "rock", "solid", ["회색", "바위", "지대"]),
  one(163, "회갈색 바위 지대", "rock", "solid", ["바위", "회갈색", "지대"]),
  one(164, "바위 섞인 황토", "sand", "passable", ["바위", "황토", "사막"]),
  one(165, "모래 자갈 언덕", "sand", "passable", ["모래", "자갈", "언덕"]),
  one(166, "바위 모래 사막", "sand", "passable", ["바위", "모래", "사막"]),
  one(167, "모래 언덕 지대", "sand", "passable", ["모래", "언덕", "지대"]),
  one(168, "초원 흙길 지대", "path", "passable", ["흙길", "초원", "길"]),
  one(169, "하얀 눈 설원", "snow", "passable", ["눈", "설원", "하얀"]),
  one(170, "푸른 평원 초지", "terrain", "passable", ["평원", "초지", "푸른"]),
  one(171, "갈색 산악 지대", "terrain", "passable", ["산악", "갈색", "지대"]),
  one(172, "갈색 평야 땅", "terrain", "passable", ["평야", "갈색", "땅"]),
  one(173, "황갈색 산맥 언덕", "terrain", "passable", ["산맥", "언덕", "황토"]),
  one(174, "해자 둘러싼 성", "town-icon", "solid", ["성", "해자", "성채"]),
  one(175, "불빛 나는 창 건물", "town-icon", "solid", ["건물", "창", "불빛", "판독보류"]),
  one(176, "초록 벽 요새", "town-icon", "solid", ["요새", "성벽", "초록"]),
  one(177, "건물 좌측 아이콘", "town-icon", "solid", ["건물", "좌측", "지도"]),
  one(178, "건물 중앙 아이콘", "town-icon", "solid", ["건물", "중앙", "지도"]),
  one(179, "작은 언덕 아이콘", "rock", "solid", ["언덕", "작은", "아이콘"]),

  // ── 6행 (인덱스 180-209) ─────────────────────────────────────────────
  one(180, "깊은 바다 물결", "water", "solid", ["바다", "물", "애니메이션"]),
  one(181, "먼바다 잔물결", "water", "solid", ["파도", "수면", "애니메이션"]),
  one(182, "짙은 심해 수면", "water", "solid", ["심해", "어두운", "애니메이션"]),
  one(183, "물거품 이는 바다", "water", "solid", ["물거품", "파도", "애니메이션"]),
  one(184, "하얀 포말 해면", "water", "solid", ["포말", "하얀", "애니메이션"]),
  one(185, "부서지는 파도", "water", "solid", ["물보라", "파도", "애니메이션"]),
  one(186, "진주빛 심해 물결", "water", "solid", ["심해", "반짝임", "애니메이션"]),
  one(187, "평야 숲 초지", "terrain", "passable", ["숲", "평야", "초지", "판독보류"]),
  one(188, "물가 초원 해안", "coast", "passable", ["해안", "초원", "물가"]),
  one(189, "하얀 물보라 물가", "coast", "solid", ["물보라", "얕은바다"]),
  one(190, "평원 초지", "terrain", "passable", ["평야", "풀밭", "초지"]),
  one(191, "초원 물가 경계", "coast", "passable", ["초원", "경계", "물가"]),
  one(192, "회색 암반 지대", "rock", "solid", ["암반", "바위", "회색"]),
  one(193, "회갈색 바위 지대", "rock", "solid", ["바위", "회갈색", "지대"]),
  one(194, "바위 자갈 언덕", "sand", "passable", ["바위", "자갈", "언덕"]),
  one(195, "모래 바위 사막", "sand", "passable", ["모래", "바위", "사막"]),
  one(196, "황토 모래 언덕", "sand", "passable", ["황토", "모래", "언덕"]),
  one(197, "바위 모래 지대", "sand", "passable", ["바위", "모래", "지대"]),
  one(198, "초원 흙길 지대", "path", "passable", ["흙길", "초원", "길"]),
  one(199, "눈 덮인 설원", "snow", "passable", ["눈", "설원", "덮임"]),
  one(200, "푸른 평원 초지", "terrain", "passable", ["평원", "초지", "푸른"]),
  one(201, "갈색 산악 지대", "terrain", "passable", ["산악", "갈색", "지대"]),
  one(202, "갈색 평야 땅", "terrain", "passable", ["평야", "갈색", "땅"]),
  one(203, "황토 언덕 산맥", "terrain", "passable", ["언덕", "산맥", "황토"]),
  one(204, "작은 집 아이콘", "town-icon", "solid", ["집", "건물", "아이콘"]),
  one(205, "벽돌 쌓인 성벽", "wall", "solid", ["벽돌", "성벽", "담"]),
  one(206, "문 달린 건물", "town-icon", "solid", ["건물", "문", "지도"]),
  one(207, "물 위 목교", "bridge", "passable", ["다리", "물", "판독보류"]),
  one(208, "모래 언덕 아이콘", "sand", "passable", ["모래", "언덕", "아이콘"]),
  one(209, "작은 나무 수풀", "plant", "solid", ["나무", "수풀", "아이콘"]),

  // ── 7행 (인덱스 210-239) ─────────────────────────────────────────────
  one(210, "깊은 바다 물결", "water", "solid", ["바다", "물", "애니메이션"]),
  one(211, "먼바다 잔물결", "water", "solid", ["파도", "수면", "애니메이션"]),
  one(212, "짙은 심해 수면", "water", "solid", ["심해", "어두운", "애니메이션"]),
  one(213, "물거품 이는 바다", "water", "solid", ["물거품", "파도", "애니메이션"]),
  one(214, "하얀 포말 해면", "water", "solid", ["포말", "하얀", "애니메이션"]),
  one(215, "부서지는 파도", "water", "solid", ["물보라", "파도", "애니메이션"]),
  one(216, "진주빛 심해 물결", "water", "solid", ["심해", "반짝임", "애니메이션"]),
  one(217, "숲 가장자리 초원", "forest", "passable", ["숲", "초원", "가장자리"]),
  one(218, "물가 초원 해안", "coast", "passable", ["해안", "초원", "물가"]),
  one(219, "하얀 물보라 물가", "coast", "solid", ["물보라", "얕은바다"]),
  one(220, "평원 초지", "terrain", "passable", ["평야", "풀밭", "초지"]),
  one(221, "초원 물가 경계", "coast", "passable", ["초원", "경계", "물가"]),
  one(222, "회색 암반 지대", "rock", "solid", ["암반", "바위", "회색"]),
  one(223, "회갈색 바위 지대", "rock", "solid", ["바위", "회갈색", "지대"]),
  one(224, "바위 자갈 언덕", "sand", "passable", ["바위", "자갈", "언덕"]),
  one(225, "모래 바위 사막", "sand", "passable", ["모래", "바위", "사막"]),
  one(226, "황토 모래 언덕", "sand", "passable", ["황토", "모래", "언덕"]),
  one(227, "바위 모래 지대", "sand", "passable", ["바위", "모래", "지대"]),
  one(228, "초원 흙길 지대", "path", "passable", ["흙길", "초원", "길"]),
  one(229, "눈 덮인 설원", "snow", "passable", ["눈", "설원", "덮임"]),
  one(230, "푸른 평원 초지", "terrain", "passable", ["평원", "초지", "푸른"]),
  one(231, "갈색 산악 지대", "terrain", "passable", ["산악", "갈색", "지대"]),
  one(232, "갈색 평야 땅", "terrain", "passable", ["평야", "갈색", "땅"]),
  one(234, "불꽃 깃발 탑", "town-icon", "solid", ["탑", "불꽃", "깃발", "판독보류"]),
  one(235, "점멸 무늬 프레임", "animation", "solid", ["점멸", "애니메이션", "판독보류"]),
  one(236, "검은 배경 프레임", "animation", "solid", ["검은", "프레임", "애니메이션"]),
  one(237, "물가 기둥 구조물", "prop", "solid", ["기둥", "구조물", "물가", "판독보류"]),
  one(238, "모래 바위 아이콘", "sand", "passable", ["모래", "바위", "아이콘"]),
  one(239, "작은 나무 수풀", "plant", "solid", ["나무", "수풀", "아이콘"]),

  // ── 8행 (인덱스 240-269) ─────────────────────────────────────────────
  ...entries([240, 241], "넓은 초원 잔디", "terrain", "passable", ["초원", "grass", "terrain"]),
  one(242, "평탄한 들판 풀밭", "terrain", "passable", ["들판", "grassland", "terrain"]),
  one(243, "잔디 알갱이 초원", "terrain", "passable", ["초원", "texture", "grass"]),
  one(244, "넓은 초원 잔디", "terrain", "passable", ["초원", "grass", "terrain"]),
  one(245, "풀 포인트 초원", "terrain", "passable", ["초원", "speckle", "grass"]),
  one(246, "설원 언 얼음물", "snow", "solid", ["눈", "얼음", "물", "설원"]),
  one(247, "새하얀 설원 눈", "snow", "passable", ["설원", "snow", "지면"]),
  one(248, "설원 어는 물길", "snow", "solid", ["눈", "물", "설원", "water"]),
  one(249, "눈 덮인 흙 지면", "snow", "passable", ["설원", "dirt", "눈밭"]),
  one(250, "새하얀 설원 눈", "snow", "passable", ["설원", "snow", "지면"]),
  one(251, "눈덮인 바위 지면", "snow", "passable", ["설원", "rock", "눈밭"]),
  one(252, "풀 덮인 바위산", "mountain", "solid", ["산", "rock", "언덕"]),
  one(253, "눈 붙은 바위산", "mountain", "solid", ["산", "rock", "눈"]),
  one(254, "어두운 암석산", "mountain", "solid", ["산", "암석", "rock"]),
  one(255, "회색 바위 능선", "mountain", "solid", ["산", "능선", "rock"]),
  one(256, "바위산 비탈", "mountain", "solid", ["산", "비탈", "rock"]),
  one(257, "그늘진 바위산", "mountain", "solid", ["산", "암석", "shadow"]),
  one(259, "왕관 초록 나무", "tree", "solid", ["나무", "tree", "숲"]),
  one(260, "서 있는 나무 기둥", "tree", "solid", ["나무", "trunk", "기둥"]),
  one(261, "가로 누운 통나무", "prop", "solid", ["나무", "log", "통나무"]),
  one(262, "빨간 열매 관목", "plant", "solid", ["나무", "berry", "수풀", "빨강"]),
  one(263, "물가 바위 지대", "rock", "solid", ["바위", "물가", "rock"]),
  one(264, "바위 언덕", "rock", "solid", ["바위", "언덕", "rock"]),
  one(265, "좁은 흙길", "path", "passable", ["흙", "길", "path", "dirt"]),
  one(266, "어두운 목조 기단", "prop", "solid", ["나무", "structure", "목조"]),
  one(267, "나무 판자 갑판", "bridge", "passable", ["나무", "deck", "갑판"]),
  one(268, "나무 판자 마루", "bridge", "passable", ["나무", "plank", "마루"]),
  one(269, "이음새 나무 갑판", "bridge", "passable", ["나무", "deck", "이음새"]),

  // ── 9행 (인덱스 270-299) ─────────────────────────────────────────────
  ...entries([270, 271], "넓은 초원 잔디", "terrain", "passable", ["초원", "grass", "terrain"]),
  one(272, "평탄한 들판 풀밭", "terrain", "passable", ["들판", "grassland", "terrain"]),
  one(273, "그늘진 잔디 초원", "terrain", "passable", ["초원", "shade", "grass"]),
  one(274, "울창한 풀밭", "terrain", "passable", ["풀밭", "grass", "텍스처"]),
  one(275, "잔디 질감 들판", "terrain", "passable", ["들판", "texture", "grass"]),
  one(276, "설원 언 물가", "snow", "solid", ["눈", "얼음", "물", "설원"]),
  one(277, "설원 흐르는 물", "snow", "solid", ["눈", "물", "설원", "water"]),
  one(278, "설원 물풀 지대", "snow", "solid", ["눈", "물", "풀", "설원"]),
  one(279, "눈 섞인 흙밭", "snow", "passable", ["설원", "dirt", "눈밭"]),
  one(280, "눈덮인 진흙 지면", "snow", "passable", ["설원", "dirt", "눈밭"]),
  one(281, "흙섞인 설원 지면", "snow", "passable", ["설원", "soil", "눈밭"]),
  one(282, "숲 낀 바위산", "mountain", "solid", ["산", "숲", "rock"]),
  one(283, "눈솟은 바위산", "mountain", "solid", ["산", "눈", "rock"]),
  one(284, "암벽 바위산", "mountain", "solid", ["산", "암벽", "rock"]),
  one(285, "잿빛 바위 능선", "mountain", "solid", ["산", "능선", "rock"]),
  one(286, "바위산 돌벽", "mountain", "solid", ["산", "돌벽", "rock"]),
  one(287, "짙은 암벽 지대", "mountain", "solid", ["산", "암벽", "rock"]),
  one(288, "빨간 열매 나무", "tree", "solid", ["나무", "열매", "berry", "빨강"]),
  one(289, "초록 왕관 나무", "tree", "solid", ["나무", "canopy", "숲"]),
  one(290, "무성한 초록 나무", "tree", "solid", ["나무", "잎", "tree"]),
  one(291, "숲속 작은 연못", "water", "solid", ["연못", "water", "숲"]),
  one(292, "나무 선착장", "bridge", "passable", ["부두", "wood", "dock"]),
  one(293, "물가 목조 부두", "bridge", "passable", ["부두", "물", "dock"]),
  one(294, "모래 벌판", "sand", "passable", ["모래", "sand", "사막"]),
  one(295, "마른 모래 땅", "sand", "passable", ["모래", "sand", "땅"]),
  one(296, "해변 자갈밭", "coast", "passable", ["해변", "자갈", "coast", "sand"]),
  one(297, "수상 목조 갑판", "bridge", "passable", ["갑판", "wood", "물"]),
  one(298, "갈색 나무 갑판", "bridge", "passable", ["갑판", "wood", "deck"]),
  one(299, "나무널 갑판", "bridge", "passable", ["갑판", "plank", "deck"]),

  // ── 10행 (인덱스 300-329) ────────────────────────────────────────────
  one(300, "넓은 초원 잔디", "terrain", "passable", ["초원", "grass", "terrain"]),
  ...entries([301, 302], "평탄한 들판 풀밭", "terrain", "passable", ["들판", "grassland", "terrain"]),
  one(303, "풀무늬 초원", "terrain", "passable", ["초원", "pattern", "grass"]),
  one(304, "잔디 알갱이 초원", "terrain", "passable", ["초원", "texture", "grass"]),
  one(305, "잔디 섬돌 무늬", "terrain", "passable", ["초원", "pattern", "grass"]),
  one(306, "설원 얼음물 지대", "snow", "solid", ["눈", "얼음", "물", "설원"]),
  one(307, "설원 강물 자락", "snow", "solid", ["눈", "물", "설원", "water"]),
  one(308, "설원 수풀 물가", "snow", "solid", ["눈", "물", "풀", "설원"]),
  one(309, "눈덮인 흙 지면", "snow", "passable", ["설원", "dirt", "눈밭"]),
  one(310, "진흙설원 경계", "snow", "passable", ["설원", "soil", "눈밭"]),
  one(311, "흙섞인 설원 가장자리", "snow", "passable", ["설원", "soil", "눈밭"]),
  one(312, "사막 모래 지면", "sand", "passable", ["모래", "sand", "사막"]),
  one(313, "자갈 언덕", "rock", "passable", ["자갈", "rock", "땅"]),
  one(314, "눈 덮인 바위산", "mountain", "solid", ["산", "눈", "rock"]),
  one(315, "자줏빛 산봉우리", "mountain", "solid", ["산", "봉우리", "rock"]),
  one(316, "만년설 바위산", "mountain", "solid", ["산", "만년설", "rock"]),
  one(317, "산 정상 바위", "mountain", "solid", ["산", "정상", "rock"]),
  one(318, "숲 캐노피 덩어리", "forest", "solid", ["숲", "canopy", "forest"]),
  one(319, "숲 가장자리 캐노피", "forest", "solid", ["숲", "edge", "forest"]),
  one(320, "회색 석조 건물", "town-icon", "solid", ["건물", "stone", "구조물"]),
  one(321, "잿빛 석조 건물", "town-icon", "solid", ["건물", "stone", "구조물"]),
  one(322, "풀둑 낀 연못", "water", "solid", ["연못", "풀", "water"]),
  one(323, "둑 낀 물웅덩이", "water", "solid", ["물", "둑", "water"]),
  one(324, "모래 지면", "sand", "passable", ["모래", "sand", "지면"]),
  one(325, "바위 언덕 둔덕", "rock", "solid", ["바위", "언덕", "mound"]),
  one(326, "갈색 둑 땅", "terrain", "passable", ["흙", "둑", "dirt"]),
  one(327, "세로 나무 말뚝", "prop", "solid", ["나무", "post", "말뚝"]),
  one(328, "나무 지주", "prop", "solid", ["나무", "post", "지지대"]),
  one(329, "둑 사이 수로", "water", "solid", ["수로", "water", "물길"]),

  // ── 11행 (인덱스 330-359) ────────────────────────────────────────────
  one(330, "넓은 초원 잔디", "terrain", "passable", ["초원", "grass", "terrain"]),
  ...entries([331, 332], "평탄한 들판 풀밭", "terrain", "passable", ["들판", "grassland", "terrain"]),
  one(333, "짙은 풀 섞인 초원", "terrain", "passable", ["초원", "섞임", "grass"]),
  one(334, "풀 언덕 초지", "terrain", "passable", ["초지", "grass", "풀밭"]),
  one(335, "들판 풀 텍스처", "terrain", "passable", ["들판", "texture", "grass"]),
  one(336, "설원 얼음 물빛", "snow", "solid", ["눈", "얼음", "물", "설원"]),
  one(337, "설원 어는 강", "snow", "solid", ["눈", "물", "설원", "water"]),
  one(338, "설원 흙 물가", "snow", "solid", ["눈", "물", "흙", "설원"]),
  one(339, "눈덮인 진흙 지면", "snow", "passable", ["설원", "dirt", "눈밭"]),
  one(340, "진흙 설원 경계", "snow", "passable", ["설원", "soil", "눈밭"]),
  one(341, "흙섞인 눈밭", "snow", "passable", ["설원", "soil", "눈밭"]),
  one(342, "숲 덮인 산", "mountain", "solid", ["산", "숲", "rock"]),
  one(343, "풀 낀 모래 언덕", "sand", "passable", ["모래", "풀", "언덕", "sand"]),
  one(344, "자주빛 석조 건물", "town-icon", "solid", ["건물", "stone", "자주", "구조물"]),
  one(345, "자색 돌 건물", "town-icon", "solid", ["건물", "stone", "자주", "구조물"]),
  one(346, "보라빛 석조 구조", "town-icon", "solid", ["구조물", "stone", "보라"]),
  one(347, "그늘진 자주 건물", "town-icon", "solid", ["건물", "stone", "그늘", "구조물"]),
  one(348, "큰 초록 나무", "tree", "solid", ["나무", "숲", "tree"]),
  one(349, "숲 진 나무", "tree", "solid", ["나무", "숲", "tree"]),
  one(350, "회색 석조 건물", "town-icon", "solid", ["건물", "stone", "회색"]),
  one(351, "잿빛 돌 건물", "town-icon", "solid", ["건물", "stone", "잿빛"]),
  one(352, "덩굴 덮인 목조 건물", "town-icon", "solid", ["건물", "wood", "덩굴"]),
  one(353, "수풀 두른 갈색 집", "town-icon", "solid", ["집", "wood", "수풀"]),
  one(354, "나무 부두 갑판", "bridge", "passable", ["부두", "wood", "dock", "갑판"]),
  one(355, "갈색 흙 돔 언덕", "terrain", "passable", ["흙", "돔", "mound", "판독보류"]),
  one(356, "작은 흙 언덕", "terrain", "passable", ["흙", "언덕", "mound", "판독보류"]),
  one(357, "나무 기둥 받침대", "prop", "solid", ["나무", "post", "판독보류"]),
  one(358, "나무 말뚝 받침", "prop", "solid", ["나무", "post", "판독보류"]),
  one(359, "나무 판자 갑판", "bridge", "passable", ["나무", "deck", "갑판"]),

  // ── 12행 (인덱스 360-389) ────────────────────────────────────────────
  one(360, "초원 잔디 표면", "terrain", "passable", ["풀밭", "grass", "초원"]),
  one(361, "푸른 평야 초지", "terrain", "passable", ["평야", "grass", "풀"]),
  one(362, "숲 그늘 풀바닥", "forest", "passable", ["숲", "forest", "초원"]),
  one(363, "잔디 속 흙길", "path", "passable", ["흙길", "road", "dirt"]),
  one(364, "밝은 초장 풀밭", "terrain", "passable", ["초장", "green", "풀"]),
  one(365, "흙길 난 길목", "path", "passable", ["흙길", "path", "dirt"]),
  one(366, "짙푸른 바다 물결", "water", "solid", ["바다", "ocean", "wave"]),
  one(367, "깊은 바닷물 수면", "water", "solid", ["바다", "ocean", "deep"]),
  one(368, "해안 파도 경계", "coast", "solid", ["해안", "coast", "wave"]),
  one(369, "잔잔한 바다 수면", "water", "solid", ["바다", "calm", "water"]),
  one(370, "심해 검은 물", "water", "solid", ["심해", "ocean", "dark"]),
  one(371, "바다 속 어둠 무늬", "water", "solid", ["바다", "abyss", "wave"]),
  one(372, "노란 마름모 상징", "decoration", "solid", ["표식", "diamond", "판독보류"]),
  one(373, "노란 마름모 상징", "decoration", "solid", ["표식", "diamond", "판독보류", "애니메이션"]),
  one(374, "푸른 물 위 흰 얼음", "ice", "solid", ["얼음", "ice", "water"]),
  ...entries([375, 376, 377], "타오르는 용암", "lava", "solid", ["용암", "lava", "애니메이션"]),
  ...entries([378, 379], "불길 퍼지는 용암", "lava", "solid", ["불길", "lava", "애니메이션"]),
  one(380, "핑크 바탕 무늬", "decoration", "solid", ["pattern", "plate", "판독보류"]),
  one(381, "회갈색 덤불 무늬", "plant", "solid", ["덤불", "bush", "판독보류"]),
  one(382, "회색 자갈 바닥", "rock", "solid", ["자갈", "gravel", "판독보류"]),
  one(383, "연회색 돌 무늬", "rock", "solid", ["돌", "stone", "판독보류"]),
  one(384, "흰 눈 덮인 봉우리", "snow", "solid", ["눈", "snow", "peak"]),
  one(385, "붉은 사막 사구", "sand", "passable", ["사막", "desert", "dune"]),
  one(386, "황갈색 사구 능선", "sand", "passable", ["사구", "dune", "desert"]),
  one(387, "붉은 사구 언덕", "sand", "passable", ["사막", "sand", "dune"]),
  one(388, "바랜 사막 모래", "sand", "passable", ["사막", "desert", "sand"]),
  one(389, "보랏빛 무늬 조각", "decoration", "solid", ["보라", "pattern", "판독보류"]),

  // ── 13행 (인덱스 390-419) ────────────────────────────────────────────
  one(390, "들판 풀밭", "terrain", "passable", ["들판", "grass", "풀"]),
  one(391, "평온한 초원", "terrain", "passable", ["초원", "grass", "평야"]),
  one(392, "숲 아래 풀 지면", "forest", "passable", ["숲", "forest", "초원"]),
  one(393, "흙길 낸 초원", "path", "passable", ["흙길", "path", "dirt"]),
  one(394, "흙밭 다져진 길", "path", "passable", ["흙길", "dirt", "path"]),
  one(395, "흙언덕 길목", "path", "passable", ["흙길", "hill", "path"]),
  one(396, "거품 검바다 수면", "water", "solid", ["바다", "ocean", "wave"]),
  one(397, "짙은 바닷물", "water", "solid", ["바다", "ocean", "water"]),
  one(398, "물결 구르는 바다", "water", "solid", ["바다", "wave", "ocean"]),
  one(399, "바다 거품 이랑", "water", "solid", ["바다", "foam", "wave"]),
  one(400, "어둠 가득 심해", "water", "solid", ["심해", "ocean", "dark"]),
  one(401, "검푸른 바다 어둠", "water", "solid", ["바다", "ocean", "dark"]),
  one(402, "노란 삼각 표식", "banner", "solid", ["깃발", "banner", "판독보류"]),
  one(403, "노란 삼각 표식", "banner", "solid", ["깃발", "banner", "판독보류", "애니메이션"]),
  one(404, "하얀 눈밭 설원", "snow", "passable", ["눈", "snow", "설원"]),
  ...entries([405, 406, 407], "끓어오르는 용암", "lava", "solid", ["용암", "lava", "애니메이션"]),
  one(408, "핑크 바탕 갈색 무늬", "decoration", "solid", ["brown", "pattern", "판독보류"]),
  one(409, "핑크 바탕 암석 무늬", "rock", "solid", ["암석", "pattern", "판독보류"]),
  one(410, "핑크 바탕 틀 구조", "prop", "solid", ["structure", "frame", "판독보류"]),
  one(411, "회색 덤불 군락", "plant", "solid", ["덤불", "plant", "판독보류"]),
  one(412, "푸른 틀 사각 무늬", "prop", "solid", ["frame", "border", "판독보류"]),
  one(413, "어두운 재 무늬 지면", "terrain", "solid", ["재", "ash", "판독보류"]),
  one(414, "눈 덮인 설원 벽", "snow", "solid", ["눈", "snow", "ice"]),
  one(415, "핑크 바탕 흰 언덕", "snow", "solid", ["눈", "snow", "판독보류"]),
  one(416, "흰 눈 벽면", "snow", "solid", ["눈", "ice", "snow"]),
  one(417, "핑크 바탕 붉은 기둥", "pillar", "solid", ["기둥", "pillar", "판독보류"]),
  one(418, "붉은 지붕 겹층", "roof", "solid", ["지붕", "roof", "red"]),
  one(419, "핑크 바탕 붉은 무늬", "decoration", "solid", ["red", "pattern", "판독보류"]),

  // ── 14행 (인덱스 420-449) ────────────────────────────────────────────
  one(420, "초록 초원 표면", "terrain", "passable", ["초원", "grass", "풀"]),
  one(421, "푸른 들판 초지", "terrain", "passable", ["들판", "grass", "풀"]),
  one(422, "숲 그늘 초지", "forest", "passable", ["숲", "forest", "초원"]),
  one(423, "흙길 초원 경계", "path", "passable", ["흙길", "edge", "path"]),
  one(424, "흙길 흐른 지대", "path", "passable", ["흙길", "ground", "path"]),
  one(425, "흙길 모퉁이", "path", "passable", ["흙길", "corner", "path"]),
  one(426, "짙푸른 파도 바다", "water", "solid", ["바다", "ocean", "wave"]),
  one(427, "고요한 깊은 바다", "water", "solid", ["바다", "ocean", "deep"]),
  one(428, "물결 이는 해안", "coast", "solid", ["해안", "coast", "wave"]),
  one(429, "잔물결 바다 수면", "water", "solid", ["바다", "wave", "water"]),
  one(430, "검은 심해 물결", "water", "solid", ["심해", "ocean", "dark"]),
  one(431, "바다 물결 어둠", "water", "solid", ["바다", "wave", "dark"]),
  one(432, "황금 무늬 장식", "decoration", "solid", ["gold", "pattern", "판독보류"]),
  one(433, "주황 무늬 장식", "decoration", "solid", ["orange", "pattern", "판독보류"]),
  one(434, "핑크 바탕 흰 꽃모양", "plant", "solid", ["꽃", "flower", "판독보류"]),
  ...entries([435, 436, 437], "활활 타는 용암", "lava", "solid", ["용암", "lava", "애니메이션"]),
  one(438, "핑크 바탕 갈색 덩이", "decoration", "solid", ["brown", "blob", "판독보류"]),
  one(439, "핑크 바탕 회색 무늬", "rock", "solid", ["rock", "pattern", "판독보류"]),
  one(440, "핑크 바탕 잡석 무늬", "rock", "solid", ["잡석", "stone", "판독보류"]),
  one(441, "핑크 바탕 돌무더기", "rock", "solid", ["돌무더기", "stone", "판독보류"]),
  one(442, "푸른 틀 사각 무늬", "prop", "solid", ["frame", "border", "판독보류"]),
  one(443, "핑크 바탕 짙은 무늬", "decoration", "solid", ["dark", "pattern", "판독보류"]),
  one(444, "회백색 돌담 벽", "wall", "solid", ["돌담", "wall", "stone"]),
  one(445, "회백석 무늬 벽", "wall", "solid", ["돌", "wall", "stone"]),
  ...entries([446, 447], "흔들리는 노란 불꽃", "animation", "solid", ["불꽃", "flame", "애니메이션"]),
  ...entries([448, 449], "세차게 타는 불꽃", "animation", "solid", ["불꽃", "fire", "애니메이션"]),

  // ── 15행 (인덱스 450-479) ────────────────────────────────────────────
  one(450, "초록 평야 풀", "terrain", "passable", ["평야", "grass", "풀"]),
  one(451, "푸른 초원 바닥", "terrain", "passable", ["초원", "grass", "풀"]),
  one(452, "숲바닥 초지", "forest", "passable", ["숲", "forest", "초원"]),
  one(453, "흙길 초입 지대", "path", "passable", ["흙길", "path", "dirt"]),
  one(454, "흙길 넓은 지대", "path", "passable", ["흙길", "dirt", "ground"]),
  one(455, "흙길 트인 길", "path", "passable", ["흙길", "road", "path"]),
  one(456, "검푸른 바다 파도", "water", "solid", ["바다", "ocean", "wave"]),
  one(457, "어두운 바닷물", "water", "solid", ["바다", "ocean", "water"]),
  one(458, "거품 물결 해안", "coast", "solid", ["해안", "coast", "foam"]),
  one(459, "잔잔한 바다 수면", "water", "solid", ["바다", "calm", "water"]),
  one(460, "심해 검푸른 물", "water", "solid", ["심해", "ocean", "dark"]),
  one(461, "바다 어둠 물결", "water", "solid", ["바다", "wave", "dark"]),
  one(462, "갈색 무늬 장식", "decoration", "solid", ["brown", "pattern", "판독보류"]),
  one(463, "주황 무늬 조각", "decoration", "solid", ["orange", "pattern", "판독보류"]),
  one(464, "짙회색 무늬 판", "decoration", "solid", ["회색", "pattern", "판독보류"]),
  ...entries([465, 466, 467], "불꽃 치솟는 용암", "lava", "solid", ["용암", "lava", "애니메이션"]),
  one(468, "핑크 빛 갈색 무늬", "decoration", "solid", ["brown", "pattern", "판독보류"]),
  one(469, "핑크 빛 잡석 무늬", "rock", "solid", ["잡석", "stone", "판독보류"]),
  one(470, "회색 돌무더기 지대", "rock", "solid", ["돌무더기", "rock", "판독보류"]),
  one(471, "어둑한 바위 지대", "rock", "solid", ["바위", "rock", "판독보류"]),
  one(472, "푸른 틀 사각 무늬", "prop", "solid", ["frame", "border", "판독보류"]),
  one(473, "핑크 빛 바위 무늬", "rock", "solid", ["바위", "rock", "판독보류"]),
  one(474, "회갈색 돌벽 무늬", "wall", "solid", ["돌벽", "wall", "stone"]),
  one(475, "회갈색 벽면 타일", "wall", "solid", ["벽면", "wall", "tile"]),
  one(476, "붉은 불꽃 타오름", "animation", "solid", ["불꽃", "fire", "애니메이션"]),
  one(477, "핑크 빛 붉은 무늬", "decoration", "solid", ["red", "pattern", "판독보류"]),
  one(478, "붉은 줄무늬 지붕", "roof", "solid", ["지붕", "roof", "red"]),
  one(479, "핑크 빛 붉은 조각", "decoration", "solid", ["red", "dark", "판독보류"]),
];
