// World(월드맵) 칩셋(tex_easyrpg_chipset_world) 타일 그림판의 AI 검색용 큐레이션 시맨틱 테이블.
// 이 파일은 생성물이다 — 수기 편집 대신 scripts/build-tile-semantics.mts 로 재생성한다.
// 판독 절차(지어낸 이름이 아니라 실제 통산 과정):
//   1. gen-chipset-blocks.mts 가 4행을 경계선 없는 연속 30x4 아틀라스로 굽는다.
//      격자선을 그리지 않는 이유: 여러 칸에 걸친 물건을 다시 쪼개 놓으면 그게 그대로 오독이 된다.
//   2. 인덱스 확인은 gen-chipset-strips.mts 의 숫자 라벨로만 한다(스트립은 세로 연속성을 끊는다).
//   3. 서로 모르는 판독자 2명 이상이 독립 서술하고 role 다수결로 정리한다.
//      픽셀이 거의 같은 시트(retro_exterior/retro_house, RGB 차이 0.4%)는 판독을 합치므로 한 칸에 최대 4표다.
//   4. 다수결이 이전 라벨과 어긋나는 칸만 교정한다. 갈리는 칸은 그대로 둔다 —
//      지울 수 없는 칸을 지어내는 것이 이 테이블을 무너뜨렸던 원인이다. 보류 목록은 tile-reaudit/splits.txt.
//   5. 사람이 14~20배 크롭으로 확인한 칸은 overrides.json 이 다수결을 이긴다
//      (판독자 전원이 틀린 사례가 있었다 — 125/155/185/215 는 바닥이 아니라 석조 틀 유리창이다).
// tileSemanticsDungeon.ts / tileSemanticsInterior.ts 와 동일한 계약: tileset.tileMeta[] 와 별개로
// 관리되는 검색 전용 데이터다. 통행성/레이어 계약은 tilesetHarness 가, 타일별 정밀 라벨은 여기가 담당한다.
//
// 좌표 규약: 30타일/행, ID = 행×30 + 열. 아트가 없는 슬롯(완전 투명 또는 분홍 컬러키 단색)은
// 서술할 대상이 없으므로 엔트리를 만들지 않는다 — scripts/verify-tile-semantics.mts 가 픽셀에서
// 그 목록을 직접 구해 커버리지를 검증한다.
// 도화 가능 여부는 상수가 아니라 PNG 에서 직접 유도한다(불투명·비키색 픽셀이 하나라도 있는가).
//
// 실측: 도화 가능 478칸 전수 서술, 고유 라벨 415개.
// 조립: scripts/build-tile-semantics.mts (수기 편집 대신 이 스크립트로 재생성한다).

import type { CombinedTownTileSemanticEntry } from "./tileSemanticsCombinedTown";
import { applyChipsetLabelCorrections } from "./chipsetLabelCorrections";

export type WorldTileSemanticEntry = CombinedTownTileSemanticEntry;

function entries(
  indexes: readonly number[],
  label: string,
  role: string,
  passage: "passable" | "solid",
  tags: readonly string[]
): WorldTileSemanticEntry[] {
  return indexes.map((index) => ({ index, label, role, passage, tags: [label, ...tags] }));
}

function one(
  index: number,
  label: string,
  role: string,
  passage: "passable" | "solid",
  tags: readonly string[]
): WorldTileSemanticEntry {
  return { index, label, role, passage, tags: [label, ...tags] };
}

export const WORLD_TILE_SEMANTICS: readonly WorldTileSemanticEntry[] = applyChipsetLabelCorrections("tex_easyrpg_chipset_world", [
  // ── 0행 (인덱스 0-29) ─────────────────────────────────────────────
  one(0, "초원 바다 해안 모서리", "coast", "solid", ["coast", "해안", "바다", "초원"]),
  one(1, "초원 바다 해안 변형", "coast", "solid", ["coast", "해안", "바다", "초원"]),
  one(2, "초원 해안 곡선 물가", "coast", "solid", ["coast", "해안", "물가", "바다"]),
  one(3, "파도 바다 해안 물가", "coast", "solid", ["coast", "해안", "파도", "바다"]),
  one(4, "물보라 바다 해안", "coast", "solid", ["coast", "해안", "물보라", "파도"]),
  one(5, "잔잔한 바다 해안", "coast", "solid", ["coast", "해안", "잔잔", "바다"]),
  one(6, "갈색 밭 흙바닥", "terrain", "passable", ["dirt", "밭", "흙", "평원"]),
  one(7, "평원 초록 잔디", "terrain", "passable", ["grass", "초원", "잔디", "평야"]),
  one(8, "풀밭 모서리 흙바닥", "terrain", "passable", ["terrain", "잔디 위 흙길", "흙길"]),
  one(9, "모래 사막 바위 지대", "sand", "passable", ["desert", "사막", "모래", "바위"]),
  one(10, "초원 푸른 잔디 평야", "terrain", "passable", ["grass", "초원", "잔디", "평야"]),
  one(11, "모래 사막 초원 경계", "sand", "passable", ["desert", "사막", "경계", "모래"]),
  one(12, "보라색 돌 바닥", "floor", "passable", ["floor", "분홍빛 돌바닥"]),
  one(13, "녹회색 석재 바닥", "floor", "passable", ["floor", "청록색 돌 바닥"]),
  one(14, "보라색 벽돌 벽 상단 좌측", "wall", "solid", ["wall", "보라색 벽돌 벽"]),
  one(15, "보라색 벽돌 벽 상단 중앙 1", "wall", "solid", ["wall", "보라색 벽돌 벽"]),
  one(16, "보라색 벽돌 벽 상단 중앙 2", "wall", "solid", ["wall", "보라색 벽돌 벽"]),
  one(17, "보라색 벽돌 벽 상단 우측", "wall", "solid", ["wall", "보라색 벽돌 벽"]),
  one(18, "잔디 절벽 오목 모서리 좌측", "cliff", "solid", ["cliff", "풀밭 절벽 경사면 상단 좌측", "잔디 절벽", "풀밭 절벽"]),
  one(19, "잔디 절벽 오목 모서리 우측", "cliff", "solid", ["cliff", "풀밭 절벽 경사면 상단 우측", "잔디 절벽", "풀밭 절벽"]),
  one(20, "흙 절벽 오목 모서리 좌측", "cliff", "solid", ["cliff", "흙 절벽 경사면 상단 좌측", "흙 절벽"]),
  one(21, "흙 절벽 오목 모서리 우측", "cliff", "solid", ["cliff", "흙 절벽 경사면 상단 우측", "흙 절벽"]),
  one(22, "눈 절벽 오목 모서리 좌측", "cliff", "solid", ["cliff", "눈 절벽 경사면 상단 좌측", "눈 절벽"]),
  one(23, "눈 절벽 오목 모서리 우측", "cliff", "solid", ["cliff", "눈 절벽 경사면 상단 우측", "눈 절벽"]),
  one(24, "초록 산봉우리 좌측", "cliff", "solid", ["cliff", "녹색 산봉우리 좌측", "초록 산", "녹색 산"]),
  one(25, "초록 산봉우리 우측", "cliff", "solid", ["cliff", "녹색 산봉우리 우측", "초록 산", "녹색 산"]),
  one(26, "바위산 봉우리 좌측", "cliff", "solid", ["cliff", "갈색 산봉우리 좌측", "바위산", "갈색 산"]),
  one(27, "바위산 봉우리 우측", "cliff", "solid", ["cliff", "갈색 산봉우리 우측", "바위산", "갈색 산"]),
  one(28, "눈 덮인 설산 좌측", "cliff", "solid", ["cliff", "설산 봉우리 좌측", "설산"]),
  one(29, "눈 덮인 설산 우측", "cliff", "solid", ["cliff", "설산 봉우리 우측", "설산"]),

  // ── 1행 (인덱스 30-59) ─────────────────────────────────────────────
  one(30, "해안 초원 바다 경계", "coast", "solid", ["coast", "해안", "바다", "초원"]),
  one(31, "해안 초원 바다 변형", "coast", "solid", ["coast", "해안", "바다", "초원"]),
  one(32, "해안 초원 바다 모서리", "coast", "solid", ["coast", "해안", "바다", "초원"]),
  one(33, "얕은 바다 백사 해안", "coast", "solid", ["coast", "해안", "백사", "바다"]),
  one(34, "눈밭 속 세로 물길 2", "coast", "solid", ["water", "눈 해안 세로 강 2", "강"]),
  one(35, "얕은 바다 해안 물가", "coast", "solid", ["coast", "해안", "물가", "바다"]),
  one(36, "초원 흙 언덕 경계", "terrain", "passable", ["hill", "언덕", "흙", "초원"]),
  one(37, "풀밭과 흙길 경계 상단", "terrain", "passable", ["terrain", "잔디 경계 흙길 상단", "흙길"]),
  one(38, "초원 흙 밭 경계", "terrain", "passable", ["field", "밭", "흙", "초원"]),
  one(39, "초원 사막 모래 경계", "sand", "passable", ["desert", "사막", "모래", "경계"]),
  one(40, "모래 사막 평원 바닥", "sand", "passable", ["desert", "사막", "모래", "평원"]),
  one(41, "모래 사막 언덕 경계", "sand", "passable", ["desert", "사막", "언덕", "모래"]),
  one(42, "회색 돌 바닥", "floor", "passable", ["floor", "청회색 돌바닥"]),
  one(43, "짙은 회색 돌 바닥", "floor", "passable", ["floor", "어두운 석재 바닥"]),
  one(44, "보라색 벽돌 벽 하단 좌측", "wall", "solid", ["wall", "보라색 벽돌 벽"]),
  one(45, "보라색 벽돌 벽 하단 중앙 1", "wall", "solid", ["wall", "보라색 벽돌 벽"]),
  one(46, "보라색 벽돌 벽 하단 중앙 2", "wall", "solid", ["wall", "보라색 벽돌 벽"]),
  one(47, "보라색 벽돌 벽 하단 우측", "wall", "solid", ["wall", "보라색 벽돌 벽"]),
  one(48, "잔디 절벽 볼록 모서리 좌측", "cliff", "solid", ["cliff", "풀밭 절벽 경사면 하단 좌측", "잔디 절벽", "풀밭 절벽"]),
  one(49, "잔디 절벽 볼록 모서리 우측", "cliff", "solid", ["cliff", "풀밭 절벽 경사면 하단 우측", "잔디 절벽", "풀밭 절벽"]),
  one(50, "흙 절벽 볼록 모서리 좌측", "cliff", "solid", ["cliff", "흙 절벽 경사면 하단 좌측", "흙 절벽"]),
  one(51, "흙 절벽 볼록 모서리 우측", "cliff", "solid", ["cliff", "흙 절벽 경사면 하단 우측", "흙 절벽"]),
  one(52, "눈 절벽 볼록 모서리 좌측", "cliff", "solid", ["cliff", "눈 절벽 경사면 하단 좌측", "눈 절벽"]),
  one(53, "눈 절벽 볼록 모서리 우측", "cliff", "solid", ["cliff", "눈 절벽 경사면 하단 우측", "눈 절벽"]),
  one(54, "목재 울타리 상단 좌측", "fence", "solid", ["fence", "목재 울타리 좌상단", "목재 울타리"]),
  one(55, "목재 울타리 상단 가로", "fence", "solid", ["fence", "목재 울타리 가로 상단", "목재 울타리"]),
  one(56, "목재 울타리 상단 우측", "fence", "solid", ["fence", "목재 울타리 우상단", "목재 울타리"]),
  one(57, "바위산 봉우리 고원", "mountain", "solid", ["mountain", "산", "바위", "봉우리"]),
  one(58, "파란 수정", "prop", "solid", ["prop", "푸른 수정"]),
  one(59, "바위산 고원 봉우리", "mountain", "solid", ["mountain", "산", "바위", "고원"]),

  // ── 2행 (인덱스 60-89) ─────────────────────────────────────────────
  one(60, "해안 초원 바다 북쪽", "coast", "solid", ["coast", "해안", "바다", "초원"]),
  one(61, "해안 초원 바다 변형", "coast", "solid", ["coast", "해안", "바다", "초원"]),
  one(62, "해안 초원 바다 곡선", "coast", "solid", ["coast", "해안", "바다", "초원"]),
  one(63, "얕은 바다 해안 백사", "coast", "solid", ["coast", "해안", "백사", "바다"]),
  one(64, "백사장 해안 얕은 물", "coast", "solid", ["beach", "백사", "해변", "물가"]),
  one(65, "얕은 바다 해안 물가", "coast", "solid", ["coast", "해안", "물가", "바다"]),
  one(66, "초원 흙 구릉 경계", "terrain", "passable", ["hill", "구릉", "흙", "초원"]),
  one(67, "갈색 흙 평지 바닥", "terrain", "passable", ["dirt", "흙", "평지", "지면"]),
  one(68, "풀밭과 흙길 경계 우측", "terrain", "passable", ["terrain", "잔디 경계 흙길 우측", "흙길"]),
  one(69, "초원 사막 모래 경계", "sand", "passable", ["desert", "사막", "모래", "경계"]),
  one(70, "모래 사막 평야 바닥", "sand", "passable", ["desert", "사막", "모래", "평야"]),
  one(71, "모래 사막 구릉 경계", "sand", "passable", ["desert", "사막", "구릉", "모래"]),
  one(72, "가로 목재 바닥", "floor", "passable", ["floor", "가로 목재 마루"]),
  one(73, "구멍 난 가로 목재 바닥", "floor", "solid", ["floor", "구멍 난 목재 마루"]),
  one(74, "목조 회벽 상단 좌측", "wall", "solid", ["wall", "목조 회벽"]),
  one(75, "목조 회벽 상단 중앙", "wall", "solid", ["wall", "목조 회벽"]),
  one(76, "목조 회벽 상단 우측", "wall", "solid", ["wall", "목조 회벽"]),
  one(77, "목조 회벽 상단 좁은 기둥", "wall", "solid", ["wall", "목조 회벽 상단 기둥", "목조 회벽"]),
  one(78, "잔디 고원 좌상단 모서리", "cliff", "passable", ["최종판정", "cliff", "잔디 고원 지대"]),
  one(79, "잔디", "terrain", "passable", ["최종판정", "terrain"]),
  one(80, "잔디 고원 우상단 모서리", "cliff", "passable", ["최종판정", "cliff", "잔디 고원 지대"]),
  one(81, "흙 고원 좌상단 모서리", "cliff", "passable", ["최종판정", "cliff", "흙 고원 지대"]),
  one(82, "흙", "terrain", "passable", ["최종판정", "terrain"]),
  one(83, "흙 고원 우상단 모서리", "cliff", "passable", ["최종판정", "cliff", "흙 고원 지대"]),
  one(84, "목재 울타리 좌측 세로 기둥", "fence", "solid", ["fence", "목재 울타리 세로 좌측", "목재 울타리"]),
  one(85, "목재 울타리 중앙 연결부", "fence", "solid", ["fence", "목재 울타리 가로 구간", "목재 울타리"]),
  one(86, "목재 울타리 연결부 기둥", "fence", "solid", ["fence", "목재 울타리 세로 우측", "목재 울타리"]),
  one(87, "돌 우물", "prop", "solid", ["prop"]),
  one(88, "십자가 묘비", "prop", "solid", ["prop"]),
  one(89, "둥근 비석 상단", "prop", "solid", ["prop", "석조 묘비 상단", "둥근 비석", "석조 묘비"]),

  // ── 3행 (인덱스 90-119) ─────────────────────────────────────────────
  one(90, "해안 초원 바다 경계", "coast", "solid", ["coast", "해안", "바다", "초원"]),
  one(91, "해안 초원 바다 변형", "coast", "solid", ["coast", "해안", "바다", "초원"]),
  one(92, "해안 초원 바다 모서리", "coast", "solid", ["coast", "해안", "바다", "초원"]),
  one(93, "얕은 바다 해안 물가", "coast", "solid", ["coast", "해안", "바다", "물가"]),
  one(94, "백사장 해안 얕은 바다", "coast", "solid", ["beach", "백사", "해변", "바다"]),
  one(95, "얕은 바다 해안 백사", "coast", "solid", ["coast", "해안", "백사", "바다"]),
  one(96, "초원 흙 구릉 경계", "terrain", "passable", ["hill", "구릉", "흙", "초원"]),
  one(97, "풀밭과 흙길 경계 하단", "terrain", "passable", ["terrain", "잔디 경계 흙길 하단", "흙길"]),
  one(98, "흙 구릉 초원 경계", "terrain", "passable", ["hill", "구릉", "흙", "초원"]),
  one(99, "초원 사막 모래 경계", "sand", "passable", ["desert", "사막", "모래", "경계"]),
  one(100, "모래 사막 평원 지면", "sand", "passable", ["desert", "사막", "모래", "평원"]),
  one(101, "모래 사막 구릉 경계", "sand", "passable", ["desert", "사막", "구릉", "모래"]),
  one(102, "세로 목재 바닥 1", "floor", "passable", ["floor", "세로 목재 마루 1"]),
  one(103, "세로 목재 바닥 2", "floor", "passable", ["floor", "세로 목재 마루 2"]),
  one(104, "목조 회벽 하단 좌측", "wall", "solid", ["wall", "목조 회벽"]),
  one(105, "목조 회벽 하단 중앙", "wall", "solid", ["wall", "목조 회벽"]),
  one(106, "목조 회벽 하단 우측", "wall", "solid", ["wall", "목조 회벽"]),
  one(107, "목조 회벽 하단 좁은 기둥", "wall", "solid", ["wall", "목조 회벽 하단 기둥", "목조 회벽"]),
  one(108, "잔디 고원 좌측 테두리", "cliff", "passable", ["최종판정", "cliff", "잔디 고원 지대"]),
  one(109, "초원 평야 푸른 잔디", "terrain", "passable", ["grass", "초원", "잔디", "평야"]),
  one(110, "잔디 고원 우측 테두리", "cliff", "passable", ["최종판정", "cliff", "잔디 고원 지대"]),
  one(111, "흙 고원 좌측 테두리", "cliff", "passable", ["최종판정", "cliff", "흙 고원 지대"]),
  one(112, "흙길 타일 하단 경계", "terrain", "passable", ["terrain", "흙 고원 중앙", "흙 고원"]),
  one(113, "흙 고원 우측 테두리", "cliff", "passable", ["최종판정", "cliff", "흙 고원 지대"]),
  one(114, "목재 울타리 하단 좌측", "fence", "solid", ["fence", "목재 울타리 좌하단", "목재 울타리"]),
  one(115, "목재 울타리 하단 가로", "fence", "solid", ["fence", "목재 울타리 가로 하단", "목재 울타리"]),
  one(116, "목재 표지판", "town-icon", "solid", ["prop", "나무 표지판"]),
  one(117, "떨어진 낙엽", "decoration", "passable", ["decoration", "낙엽"]),
  one(118, "해골과 뼈", "decoration", "passable", ["decoration"]),
  one(119, "둥근 비석 하단", "prop", "solid", ["prop", "석조 묘비 하단", "둥근 비석", "석조 묘비"]),

  // ── 4행 (인덱스 120-149) ─────────────────────────────────────────────
  one(120, "깊은 바다 물결", "water", "solid", ["바다", "물", "애니메이션"]),
  one(121, "먼바다 잔물결", "water", "solid", ["파도", "수면", "애니메이션"]),
  one(122, "짙은 심해 수면", "water", "solid", ["심해", "어두운", "애니메이션"]),
  ...entries([123, 124], "소용돌이치는 물", "water", "solid", ["water", "거센 급류 상단"]),
  one(125, "마법 샘", "water", "solid", ["water", "소용돌이"]),
  one(126, "독 늪 내부", "terrain", "passable", ["terrain", "독 늪"]),
  one(127, "푸른 잔디", "forest", "passable", ["terrain", "잔디"]),
  one(128, "독 늪 웅덩이", "terrain", "passable", ["terrain", "독 늪"]),
  one(129, "설원 바닥", "terrain", "passable", ["terrain", "눈밭"]),
  one(130, "푸른 잔디", "terrain", "passable", ["terrain", "잔디"]),
  one(131, "설원 바닥 가장자리", "terrain", "passable", ["terrain", "눈밭"]),
  one(132, "자갈길 바닥", "floor", "passable", ["floor"]),
  one(133, "이끼 낀 벽돌 바닥", "floor", "passable", ["floor"]),
  one(134, "밝은 석조 벽 상단 좌측", "wall", "solid", ["wall", "밝은 벽돌 벽 상단", "석조 벽", "밝은 벽돌 벽"]),
  ...entries([135, 136], "밝은 석조 벽 상단 중앙", "wall", "solid", ["wall", "밝은 벽돌 벽 상단", "석조 벽", "밝은 벽돌 벽"]),
  one(137, "밝은 벽돌 벽 상단 우측 기둥", "wall", "solid", ["wall", "밝은 석조 벽 상단 우측", "밝은 벽돌 벽", "석조 벽"]),
  one(138, "잔디 절벽 상단 좌측", "cliff", "solid", ["cliff", "잔디 언덕 상단 좌측", "잔디 절벽", "잔디 언덕"]),
  one(139, "잔디 절벽 상단 중앙", "cliff", "solid", ["cliff", "잔디 언덕 상단 중앙", "잔디 절벽", "잔디 언덕"]),
  one(140, "잔디 절벽 상단 우측", "cliff", "solid", ["cliff", "잔디 언덕 상단 우측", "잔디 절벽", "잔디 언덕"]),
  one(141, "흙 절벽 상단 좌측", "cliff", "solid", ["cliff", "흙 절벽"]),
  one(142, "흙 절벽 상단 중앙", "cliff", "solid", ["cliff", "흙 절벽"]),
  one(143, "흙 절벽 상단 우측", "cliff", "solid", ["cliff", "흙 절벽"]),
  one(144, "벽걸이 횃불", "torch", "solid", ["prop", "벽 횃불"]),
  one(145, "시약병 선반", "town-icon", "solid", ["prop", "물약 선반"]),
  one(146, "벽걸이 석재 스위치", "prop", "solid", ["prop", "벽 스위치"]),
  one(147, "무기점 간판", "town-icon", "solid", ["prop"]),
  one(148, "방어구점 간판", "town-icon", "solid", ["prop"]),
  one(149, "잡화점 간판", "town-icon", "solid", ["prop", "시계점 간판"]),

  // ── 5행 (인덱스 150-179) ─────────────────────────────────────────────
  one(150, "깊은 바다 물결", "water", "solid", ["바다", "물", "애니메이션"]),
  one(151, "먼바다 잔물결", "water", "solid", ["파도", "수면", "애니메이션"]),
  one(152, "짙은 심해 수면", "water", "solid", ["심해", "어두운", "애니메이션"]),
  ...entries([153, 154], "소용돌이치는 물", "water", "solid", ["water", "소용돌이 급류"]),
  one(155, "마법 샘", "water", "solid", ["water", "소용돌이"]),
  one(156, "독 늪 좌상단", "terrain", "passable", ["terrain", "독 늪"]),
  one(157, "독 늪 상단 가장자리", "terrain", "passable", ["terrain", "독 늪 상단", "독 늪"]),
  one(158, "독 늪 우상단", "terrain", "passable", ["terrain", "독 늪"]),
  one(159, "설원 좌상단 가장자리", "terrain", "passable", ["terrain", "눈밭 좌상단", "설원", "눈밭"]),
  one(160, "설원 상단 가장자리", "terrain", "passable", ["terrain", "눈밭 상단", "설원", "눈밭"]),
  one(161, "설원 우상단 가장자리", "terrain", "passable", ["terrain", "눈밭 우상단", "설원", "눈밭"]),
  one(162, "밝은 석판 바닥", "floor", "passable", ["floor", "석재 벽돌 바닥"]),
  one(163, "사각 문양 석재 타일 바닥", "floor", "passable", ["floor", "사각 문양 석판"]),
  one(164, "밝은 석조 벽 하단 좌측", "wall", "solid", ["wall", "밝은 벽돌 벽 하단", "석조 벽", "밝은 벽돌 벽"]),
  ...entries([165, 166], "밝은 석조 벽 하단 중앙", "wall", "solid", ["wall", "밝은 벽돌 벽 하단", "석조 벽", "밝은 벽돌 벽"]),
  one(167, "밝은 벽돌 벽 하단 우측 기둥", "wall", "solid", ["wall", "밝은 석조 벽 하단 우측", "밝은 벽돌 벽", "석조 벽"]),
  one(168, "설원 절벽 상단 좌측", "cliff", "solid", ["cliff", "눈 절벽 좌상단", "설원 절벽", "눈 절벽"]),
  one(169, "설원 절벽 상단 중앙", "cliff", "solid", ["cliff", "눈 절벽 상단", "설원 절벽", "눈 절벽"]),
  one(170, "설원 절벽 상단 우측", "cliff", "solid", ["cliff", "눈 절벽 우상단", "설원 절벽", "눈 절벽"]),
  one(171, "흙 절벽 상단부 좌측", "cliff", "solid", ["cliff", "흙 절벽 상층 좌측", "흙 절벽"]),
  one(172, "흙 절벽 상단부 중앙", "cliff", "solid", ["cliff", "흙 절벽 상층 중앙", "흙 절벽"]),
  one(173, "흙 절벽 상단부 우측", "cliff", "solid", ["cliff", "흙 절벽 상층 우측", "흙 절벽"]),
  one(174, "풍경화 액자", "town-icon", "solid", ["decoration"]),
  one(175, "모닥불 그림 액자", "town-icon", "solid", ["decoration"]),
  one(176, "인물 초상화 액자", "town-icon", "solid", ["decoration", "초상화 액자"]),
  one(177, "여관 간판", "town-icon", "solid", ["prop"]),
  one(178, "주점 간판", "town-icon", "solid", ["prop"]),
  one(179, "십자가 간판", "prop", "solid", ["prop", "신전 간판"]),

  // ── 6행 (인덱스 180-209) ─────────────────────────────────────────────
  one(180, "깊은 바다 물결", "water", "solid", ["바다", "물", "애니메이션"]),
  one(181, "먼바다 잔물결", "water", "solid", ["파도", "수면", "애니메이션"]),
  one(182, "짙은 심해 수면", "water", "solid", ["심해", "어두운", "애니메이션"]),
  ...entries([183, 184], "소용돌이치는 물", "water", "solid", ["water", "거센 물결"]),
  one(185, "마법 샘", "water", "solid", ["water", "소용돌이"]),
  one(186, "독 늪 좌측 가장자리", "terrain", "passable", ["terrain", "독 늪 좌측", "독 늪"]),
  one(187, "독 늪 중앙", "terrain", "passable", ["terrain", "독 늪"]),
  one(188, "독 늪 우측 가장자리", "terrain", "passable", ["terrain", "독 늪 우측", "독 늪"]),
  one(189, "설원 좌측 가장자리", "terrain", "passable", ["terrain", "눈밭 좌측", "설원", "눈밭"]),
  one(190, "눈밭 중앙", "terrain", "passable", ["terrain", "설원 중앙", "눈밭", "설원"]),
  one(191, "설원 우측 가장자리", "terrain", "passable", ["terrain", "눈밭 우측", "설원", "눈밭"]),
  one(192, "어두운 석판 바닥", "floor", "passable", ["floor", "어두운 동굴 바닥"]),
  one(193, "석순 상단", "rock", "solid", ["rock", "큰 종유석", "석순"]),
  one(194, "어두운 돌벽 상단 좌측", "wall", "solid", ["wall", "어두운 석벽 상단", "어두운 돌벽", "어두운 석벽"]),
  ...entries([195, 196], "어두운 돌벽 상단 중앙", "wall", "solid", ["wall", "어두운 석벽 상단", "어두운 돌벽", "어두운 석벽"]),
  one(197, "어두운 석벽 상단 우측 기둥", "wall", "solid", ["wall", "어두운 돌벽 상단 우측", "어두운 석벽", "어두운 돌벽"]),
  one(198, "설원 절벽 중간 좌측", "cliff", "solid", ["cliff", "눈 절벽 중단 좌측", "설원 절벽", "눈 절벽"]),
  one(199, "설원 절벽 중간 중앙", "cliff", "solid", ["cliff", "눈 절벽 중단 중앙", "설원 절벽", "눈 절벽"]),
  one(200, "설원 절벽 중간 우측", "cliff", "solid", ["cliff", "눈 절벽 중단 우측", "설원 절벽", "눈 절벽"]),
  one(201, "흙 절벽 중간부 좌측", "cliff", "solid", ["cliff", "흙 절벽 중층 좌측", "흙 절벽"]),
  one(202, "흙 절벽 중간부 중앙", "cliff", "solid", ["cliff", "흙 절벽 중층 중앙", "흙 절벽"]),
  one(203, "흙 절벽 중간부 우측", "cliff", "solid", ["cliff", "흙 절벽 중층 우측", "흙 절벽"]),
  one(204, "아치형 격자 창문", "window", "solid", ["window"]),
  one(205, "나무 덧문 창문", "window", "solid", ["window", "나무 창문"]),
  one(206, "어두운 벽감 액자", "town-icon", "solid", ["decoration", "동굴 그림 액자"]),
  one(207, "갑옷 거치대 상단", "prop", "solid", ["prop", "기사 석상 상단", "갑옷 거치대", "기사 석상"]),
  one(208, "여신 석상 상단", "prop", "solid", ["prop", "석상 상단", "여신 석상", "석상"]),
  one(209, "석조 기둥 상단", "prop", "solid", ["prop", "돌기둥 상단", "석조 기둥", "돌기둥"]),

  // ── 7행 (인덱스 210-239) ─────────────────────────────────────────────
  one(210, "깊은 바다 물결", "water", "solid", ["바다", "물", "애니메이션"]),
  one(211, "먼바다 잔물결", "water", "solid", ["파도", "수면", "애니메이션"]),
  one(212, "짙은 심해 수면", "water", "solid", ["심해", "어두운", "애니메이션"]),
  ...entries([213, 214], "소용돌이치는 물", "water", "solid", ["water", "거센 물결"]),
  one(215, "마법 샘", "water", "solid", ["water", "소용돌이"]),
  one(216, "독 늪 좌하단", "terrain", "passable", ["terrain", "독 늪"]),
  one(217, "숲 가장자리 초원", "forest", "passable", ["숲", "초원", "가장자리"]),
  one(218, "독 늪 우하단", "terrain", "passable", ["terrain", "독 늪"]),
  one(219, "설원 좌하단 가장자리", "terrain", "passable", ["terrain", "눈밭 좌하단", "설원", "눈밭"]),
  one(220, "설원 하단 가장자리", "terrain", "passable", ["terrain", "눈밭 하단", "설원", "눈밭"]),
  one(221, "설원 우하단 가장자리", "terrain", "passable", ["terrain", "눈밭 우하단", "설원", "눈밭"]),
  one(222, "작은 석순 무리", "rock", "solid", ["rock", "작은 돌조각들"]),
  one(223, "석순 하단", "rock", "solid", ["rock", "종유석", "석순"]),
  one(224, "어두운 돌벽 하단 좌측", "wall", "solid", ["wall", "어두운 석벽 하단", "어두운 돌벽", "어두운 석벽"]),
  ...entries([225, 226], "어두운 돌벽 하단 중앙", "wall", "solid", ["wall", "어두운 석벽 하단", "어두운 돌벽", "어두운 석벽"]),
  one(227, "어두운 석벽 하단 우측 기둥", "wall", "solid", ["wall", "어두운 돌벽 하단 우측", "어두운 석벽", "어두운 돌벽"]),
  one(228, "설원 절벽 하단 좌측", "cliff", "solid", ["cliff", "눈 절벽 하단 좌측", "설원 절벽", "눈 절벽"]),
  one(229, "설원 절벽 하단 중앙", "cliff", "solid", ["cliff", "눈 절벽 하단 중앙", "설원 절벽", "눈 절벽"]),
  one(230, "설원 절벽 하단 우측", "cliff", "solid", ["cliff", "눈 절벽 하단 우측", "설원 절벽", "눈 절벽"]),
  one(231, "흙 절벽 하층 좌측", "cliff", "solid", ["cliff", "흙 절벽 하단 좌측", "흙 절벽"]),
  one(232, "흙 절벽 하층 중앙", "cliff", "solid", ["cliff", "흙 절벽 하단 중앙", "흙 절벽"]),
  one(234, "스테인드글라스 창문", "window", "solid", ["window"]),
  one(235, "목재 사다리", "stairs", "passable", ["stairs", "나무 사다리"]),
  one(236, "어두운 통로 입구", "door", "passable", ["door", "어두운 통로"]),
  one(237, "기사 석상 받침대 하단", "prop", "solid", ["prop", "갑옷 거치대 하단", "기사 석상", "갑옷 거치대"]),
  one(238, "여신 석상 받침대 하단", "prop", "solid", ["prop", "석상 하단", "여신 석상", "석상"]),
  one(239, "석조 기둥 받침대 하단", "prop", "solid", ["prop", "돌기둥 하단", "석조 기둥", "돌기둥"]),

  // ── 8행 (인덱스 240-269) ─────────────────────────────────────────────
  ...entries([240, 241], "넓은 초원 잔디", "terrain", "passable", ["초원", "grass", "terrain"]),
  one(242, "잔디 지형", "terrain", "passable", ["terrain"]),
  one(243, "잔디 알갱이 초원", "terrain", "passable", ["초원", "texture", "grass"]),
  one(244, "넓은 초원 잔디", "terrain", "passable", ["초원", "grass", "terrain"]),
  one(245, "짙은 잔디 지형", "terrain", "passable", ["terrain", "짙은 풀 지형", "짙은 풀 지대"]),
  one(246, "눈 덮인 침엽수", "tree", "solid", ["최종판정", "tree"]),
  one(247, "새하얀 설원 눈", "snow", "passable", ["설원", "snow", "지면"]),
  one(248, "눈 덮인 숲 조각", "tree", "solid", ["tree", "눈 덮인 나무"]),
  one(249, "눈 덮인 흙바위 더미", "rock", "solid", ["rock", "눈 쌓인 흙 둔덕"]),
  one(250, "새하얀 설원 눈", "snow", "passable", ["설원", "snow", "지면"]),
  one(251, "눈 덮인 흙바위 더미", "rock", "solid", ["rock", "눈 쌓인 흙 둔덕"]),
  one(252, "풀 자란 자갈 지형", "mountain", "solid", ["terrain", "이끼 낀 자갈 바닥", "자갈 지대"]),
  one(253, "자갈 지형", "mountain", "solid", ["terrain", "자갈 바닥", "자갈 지대"]),
  one(254, "거친 석벽 상단 좌측", "wall", "solid", ["wall", "어두운 이끼 석벽", "거친 석벽"]),
  ...entries([255, 256], "거친 석벽 상단 중앙", "wall", "solid", ["wall", "어두운 이끼 석벽", "거친 석벽"]),
  one(257, "어두운 이끼 석벽 우측 끝", "wall", "solid", ["wall", "거친 석벽 상단 우측", "어두운 이끼 석벽", "거친 석벽"]),
  one(259, "작은 활엽수", "tree", "solid", ["tree"]),
  one(260, "서 있는 나무 기둥", "tree", "solid", ["나무", "trunk", "기둥"]),
  one(261, "가로 누운 통나무", "prop", "solid", ["나무", "log", "통나무"]),
  one(262, "붉은 지붕 작은 집", "prop", "solid", ["prop", "붉은 지붕 오두막"]),
  one(263, "눈 덮인 작은 집", "prop", "solid", ["prop", "눈 덮인 오두막"]),
  one(264, "석제 안내판", "decoration", "solid", ["최종판정", "decoration"]),
  one(265, "매달린 나무통 밧줄", "prop", "solid", ["prop", "매달린 밧줄", "매달린 나무통", "밧줄"]),
  one(266, "어두운 벽난로 아궁이", "furniture", "solid", ["최종판정", "furniture", "벽난로"]),
  one(267, "책장 상단", "furniture", "solid", ["furniture", "책장"]),
  one(268, "서랍 수납장 상단", "furniture", "solid", ["furniture", "목재 선반장 상단", "서랍 수납장", "목재 선반장"]),
  one(269, "목재 장롱 상단", "furniture", "solid", ["furniture", "옷장 상단", "목재 장롱", "옷장"]),

  // ── 9행 (인덱스 270-299) ─────────────────────────────────────────────
  ...entries([270, 271], "넓은 초원 잔디", "terrain", "passable", ["초원", "grass", "terrain"]),
  one(272, "잔디 지형", "terrain", "passable", ["terrain"]),
  one(273, "그늘진 잔디 초원", "terrain", "passable", ["초원", "shade", "grass"]),
  one(274, "짙은 잔디 지형", "terrain", "passable", ["terrain", "짙은 풀 지형", "짙은 풀 지대"]),
  one(275, "잔디 질감 들판", "terrain", "passable", ["들판", "texture", "grass"]),
  one(276, "눈 덮인 숲 상단 좌측", "tree", "solid", ["tree", "눈 덮인 숲 좌상단", "눈 덮인 숲"]),
  one(277, "눈 덮인 숲 상단 중앙", "tree", "solid", ["tree", "눈 덮인 숲 중상단", "눈 덮인 숲"]),
  one(278, "눈 덮인 숲 상단 우측", "tree", "solid", ["tree", "눈 덮인 숲 우상단", "눈 덮인 숲"]),
  one(279, "눈 덮인 흙 둔덕 지대 상단 좌측", "rock", "solid", ["rock", "눈 덮인 바위 무리 상단 좌측", "눈 덮인 흙 둔덕 지대", "눈 덮인 바위 무리"]),
  one(280, "눈 덮인 흙 둔덕 지대 상단 중앙", "rock", "solid", ["rock", "눈 덮인 바위 무리 상단 중앙", "눈 덮인 흙 둔덕 지대", "눈 덮인 바위 무리"]),
  one(281, "눈 덮인 흙 둔덕 지대 상단 우측", "rock", "solid", ["rock", "눈 덮인 바위 무리 상단 우측", "눈 덮인 흙 둔덕 지대", "눈 덮인 바위 무리"]),
  one(282, "숲 낀 바위산", "mountain", "solid", ["산", "숲", "rock"]),
  one(283, "눈솟은 바위산", "mountain", "solid", ["산", "눈", "rock"]),
  one(284, "거친 석벽 하단 좌측", "wall", "solid", ["wall", "어두운 이끼 석벽", "거친 석벽"]),
  ...entries([285, 286], "거친 석벽 하단 중앙", "wall", "solid", ["wall", "어두운 이끼 석벽", "거친 석벽"]),
  one(287, "어두운 이끼 석벽 우측 끝", "wall", "solid", ["wall", "거친 석벽 하단 우측", "어두운 이끼 석벽", "거친 석벽"]),
  one(288, "꽃 핀 관목", "tree", "solid", ["plant", "꽃 덤불"]),
  one(289, "둥근 덤불", "tree", "solid", ["plant", "관목"]),
  one(290, "무성한 초록 나무", "tree", "solid", ["나무", "잎", "tree"]),
  one(291, "푸른 첨탑 성문", "gate", "passable", ["최종판정", "gate"]),
  one(292, "나무 오두막", "prop", "solid", ["prop", "목조 건물"]),
  one(293, "눈 덮인 석조 건물", "prop", "solid", ["prop", "눈 덮인 텐트"]),
  one(294, "긴 목재 탁자 상단", "furniture", "solid", ["furniture", "목재 식탁 상단", "긴 목재 탁자", "목재 식탁"]),
  one(295, "매달린 나무통", "prop", "solid", ["prop", "밧줄"]),
  one(296, "빛 효과", "decoration", "passable", ["decoration", "뿌연 김"]),
  one(297, "책장 하단", "furniture", "solid", ["furniture", "책장"]),
  one(298, "서랍 수납장 하단", "furniture", "solid", ["furniture", "목재 선반장 하단", "서랍 수납장", "목재 선반장"]),
  one(299, "목재 장롱 하단", "furniture", "solid", ["furniture", "옷장 하단", "목재 장롱", "옷장"]),

  // ── 10행 (인덱스 300-329) ────────────────────────────────────────────
  one(300, "넓은 초원 잔디", "terrain", "passable", ["초원", "grass", "terrain"]),
  ...entries([301, 302], "잔디 지형", "terrain", "passable", ["terrain"]),
  one(303, "짙은 잔디 지형", "terrain", "passable", ["terrain", "짙은 풀 지형", "짙은 풀 지대"]),
  one(304, "잔디 알갱이 초원", "terrain", "passable", ["초원", "texture", "grass"]),
  one(305, "잔디 섬돌 무늬", "terrain", "passable", ["초원", "pattern", "grass"]),
  one(306, "눈 덮인 숲 중단 좌측", "tree", "solid", ["tree", "눈 덮인 숲 좌측", "눈 덮인 숲"]),
  one(307, "눈 덮인 숲 중단 중앙", "tree", "solid", ["tree", "눈 덮인 숲 중앙", "눈 덮인 숲"]),
  one(308, "눈 덮인 숲 중단 우측", "tree", "solid", ["tree", "눈 덮인 숲 우측", "눈 덮인 숲"]),
  one(309, "눈 덮인 흙 둔덕 지대 중단 좌측", "rock", "solid", ["rock", "눈 덮인 바위 무리 중단 좌측", "눈 덮인 흙 둔덕 지대", "눈 덮인 바위 무리"]),
  one(310, "눈 덮인 흙 둔덕 지대 중단 중앙", "rock", "solid", ["rock", "눈 덮인 바위 무리 중단 중앙", "눈 덮인 흙 둔덕 지대", "눈 덮인 바위 무리"]),
  one(311, "눈 덮인 흙 둔덕 지대 중단 우측", "rock", "solid", ["rock", "눈 덮인 바위 무리 중단 우측", "눈 덮인 흙 둔덕 지대", "눈 덮인 바위 무리"]),
  one(312, "갈색 흙 지형", "sand", "passable", ["terrain", "흙 바닥"]),
  one(313, "어두운 흙 바닥", "terrain", "passable", ["terrain", "자갈빛 흙 지형"]),
  one(314, "보라색 벽돌 벽 상단 좌측", "wall", "solid", ["wall", "자수정 벽돌 벽 상단", "보라색 벽돌 벽", "자수정 벽돌 벽"]),
  ...entries([315, 316], "보라색 벽돌 벽 상단 중앙", "wall", "solid", ["wall", "자수정 벽돌 벽 상단", "보라색 벽돌 벽", "자수정 벽돌 벽"]),
  one(317, "자수정 벽돌 벽 상단 우측 끝", "wall", "solid", ["wall", "보라색 벽돌 벽 상단 우측", "자수정 벽돌 벽", "보라색 벽돌 벽"]),
  one(318, "큰 나무 잎사귀 좌측", "forest", "solid", ["tree", "큰 활엽수 좌상단", "큰 나무", "큰 활엽수"]),
  one(319, "큰 나무 잎사귀 우측", "forest", "solid", ["tree", "큰 활엽수 우상단", "큰 나무", "큰 활엽수"]),
  one(320, "회색 석조 성채 좌상단", "wall", "solid", ["wall", "석조 성채 상단 좌측", "회색 석조 성채", "석조 성채"]),
  one(321, "회색 석조 성채 우상단", "wall", "solid", ["wall", "석조 성채 상단 우측", "회색 석조 성채", "석조 성채"]),
  one(322, "푸른 첨탑 성채 좌측 지붕", "roof", "solid", ["최종판정", "roof", "푸른 첨탑 성채"]),
  one(323, "푸른 첨탑 성채 우측 지붕", "roof", "solid", ["최종판정", "roof", "푸른 첨탑 성채"]),
  one(324, "긴 목재 탁자 중단", "furniture", "solid", ["furniture", "목재 식탁 중단", "긴 목재 탁자", "목재 식탁"]),
  one(325, "회색 도자기 주전자", "prop", "solid", ["prop", "도자기 항아리"]),
  one(326, "원형 목재 탁자", "furniture", "solid", ["furniture", "둥근 목재 탁자"]),
  one(327, "목재 의자 전면", "furniture", "solid", ["furniture", "목재 안락의자"]),
  one(328, "목재 의자 후면", "furniture", "solid", ["furniture", "목재 의자"]),
  one(329, "목재 전신 거울 상단", "furniture", "solid", ["furniture", "화장대 상단", "목재 전신 거울", "화장대"]),

  // ── 11행 (인덱스 330-359) ────────────────────────────────────────────
  one(330, "넓은 초원 잔디", "terrain", "passable", ["초원", "grass", "terrain"]),
  ...entries([331, 332], "잔디 지형", "terrain", "passable", ["terrain"]),
  one(333, "짙은 풀 섞인 초원", "terrain", "passable", ["초원", "섞임", "grass"]),
  ...entries([334, 335], "짙은 잔디 지형", "terrain", "passable", ["terrain", "짙은 풀 지형", "짙은 풀 지대"]),
  one(336, "눈 덮인 숲 하단 좌측", "tree", "solid", ["tree", "눈 덮인 숲 좌하단", "눈 덮인 숲"]),
  one(337, "눈 덮인 숲 하단 중앙", "tree", "solid", ["tree", "눈 덮인 숲 중하단", "눈 덮인 숲"]),
  one(338, "눈 덮인 숲 하단 우측", "tree", "solid", ["tree", "눈 덮인 숲 우하단", "눈 덮인 숲"]),
  one(339, "눈 덮인 흙 둔덕 지대 하단 좌측", "rock", "solid", ["rock", "눈 덮인 바위 무리 하단 좌측", "눈 덮인 흙 둔덕 지대", "눈 덮인 바위 무리"]),
  one(340, "눈 덮인 흙 둔덕 지대 하단 중앙", "rock", "solid", ["rock", "눈 덮인 바위 무리 하단 중앙", "눈 덮인 흙 둔덕 지대", "눈 덮인 바위 무리"]),
  one(341, "눈 덮인 흙 둔덕 지대 하단 우측", "rock", "solid", ["rock", "눈 덮인 바위 무리 하단 우측", "눈 덮인 흙 둔덕 지대", "눈 덮인 바위 무리"]),
  one(342, "풀 섞인 흙 바닥", "mountain", "solid", ["terrain", "풀 자란 흙 지형"]),
  one(343, "풀 섞인 황토 바닥", "sand", "passable", ["terrain", "풀 자란 흙 지형"]),
  one(344, "보라색 벽돌 벽 하단 좌측", "wall", "solid", ["wall", "자수정 벽돌 벽 하단", "보라색 벽돌 벽", "자수정 벽돌 벽"]),
  ...entries([345, 346], "보라색 벽돌 벽 하단 중앙", "wall", "solid", ["wall", "자수정 벽돌 벽 하단", "보라색 벽돌 벽", "자수정 벽돌 벽"]),
  one(347, "자수정 벽돌 벽 하단 우측 끝", "wall", "solid", ["wall", "보라색 벽돌 벽 하단 우측", "자수정 벽돌 벽", "보라색 벽돌 벽"]),
  one(348, "큰 초록 나무", "tree", "solid", ["나무", "숲", "tree"]),
  one(349, "숲 진 나무", "tree", "solid", ["나무", "숲", "tree"]),
  one(350, "회색 석조 성채 좌하단", "wall", "solid", ["wall", "석조 성채 하단 좌측", "회색 석조 성채", "석조 성채"]),
  one(351, "회색 석조 성채 우하단", "wall", "solid", ["wall", "석조 성채 하단 우측", "회색 석조 성채", "석조 성채"]),
  one(352, "파란 첨탑 성 하단 좌측", "wall", "solid", ["wall", "파란 첨탑 성 좌하단", "파란 첨탑 성"]),
  one(353, "파란 첨탑 성 하단 우측", "wall", "solid", ["wall", "파란 첨탑 성 우하단", "파란 첨탑 성"]),
  one(354, "긴 목재 탁자 하단", "furniture", "solid", ["furniture", "목재 식탁 하단", "긴 목재 탁자", "목재 식탁"]),
  one(355, "작은 나무통", "prop", "solid", ["prop", "목재 통"]),
  one(356, "목재 등받이 없는 의자", "furniture", "solid", ["furniture", "원형 목재 의자"]),
  one(357, "목재 의자 우측면", "furniture", "solid", ["furniture", "목재 의자 측면"]),
  one(358, "목재 의자 좌측면", "furniture", "solid", ["furniture", "목재 의자 측면"]),
  one(359, "낮은 목재 탁자", "furniture", "solid", ["furniture", "화장대 하단", "화장대"]),

  // ── 12행 (인덱스 360-389) ────────────────────────────────────────────
  one(360, "작은 숲", "tree", "solid", ["tree"]),
  one(361, "잔디 바닥", "terrain", "passable", ["terrain", "잔디"]),
  one(362, "작은 숲", "forest", "passable", ["tree", "숲 상단", "숲"]),
  one(363, "작은 산", "cliff", "solid", ["cliff"]),
  one(364, "잔디 바닥", "terrain", "passable", ["terrain", "잔디"]),
  one(365, "산 봉우리", "cliff", "solid", ["cliff", "작은 산", "산맥"]),
  one(366, "석재 창살 난간", "wall", "solid", ["wall", "석조 벽틀", "던전 벽"]),
  one(367, "격자 구덩이 바닥", "floor", "passable", ["floor"]),
  one(368, "격자 구덩이 모서리", "floor", "passable", ["floor", "석조 바닥 모서리", "던전 바닥"]),
  one(369, "암석 구덩이 테두리", "cliff", "solid", ["최종판정", "cliff", "암석 구덩이"]),
  one(370, "어두운 암흑 바닥", "floor", "solid", ["floor", "검은 어둠 바닥"]),
  one(371, "어두운 구덩이 모서리", "floor", "passable", ["floor", "동굴 바닥 모서리", "동굴 바닥"]),
  one(372, "상향 화살표 발판", "floor", "passable", ["floor"]),
  one(373, "하향 화살표 발판", "floor", "passable", ["floor"]),
  one(374, "석재 계단", "stairs", "passable", ["stairs"]),
  one(375, "붉은 카펫 좌상단 모서리", "decoration", "passable", ["decoration", "붉은 양탄자 좌상단", "붉은 카펫", "붉은 양탄자"]),
  one(376, "붉은 카펫 상단 테두리", "decoration", "passable", ["decoration", "붉은 양탄자 상단", "붉은 카펫", "붉은 양탄자"]),
  one(377, "붉은 카펫 우상단 모서리", "decoration", "passable", ["decoration", "붉은 양탄자 우상단", "붉은 카펫", "붉은 양탄자"]),
  one(378, "큰 갈색 산 좌상단", "cliff", "solid", ["cliff", "큰 산 좌상단", "큰 갈색 산", "큰 산"]),
  one(379, "큰 갈색 산 우상단", "cliff", "solid", ["cliff", "큰 산 우상단", "큰 갈색 산", "큰 산"]),
  one(380, "원형 석탑 상단", "wall", "solid", ["wall", "돌 탑 상단", "원형 석탑", "돌 탑"]),
  one(381, "석조 유적 상단", "prop", "solid", ["prop", "석조 유적"]),
  one(382, "석조 신전", "prop", "solid", ["prop", "신전"]),
  one(383, "작은 석탑", "decoration", "solid", ["최종판정", "decoration"]),
  one(384, "세로 침대 상단", "furniture", "solid", ["furniture", "침대 상단", "세로 침대", "침대"]),
  one(385, "긴 목재 탁자 좌측", "furniture", "solid", ["furniture", "목재 탁자 좌측", "긴 목재 탁자", "목재 탁자"]),
  one(386, "긴 목재 탁자 중앙", "furniture", "solid", ["furniture", "목재 탁자 중앙", "긴 목재 탁자", "목재 탁자"]),
  one(387, "긴 목재 탁자 우측", "furniture", "solid", ["furniture", "목재 탁자 우측", "긴 목재 탁자", "목재 탁자"]),
  one(388, "작은 목재 탁자", "furniture", "solid", ["furniture", "목재 탁자"]),
  one(389, "수정구슬 점술 탁자", "prop", "solid", ["prop", "수정구 탁자"]),

  // ── 13행 (인덱스 390-419) ────────────────────────────────────────────
  one(390, "숲 좌상단", "tree", "solid", ["tree", "숲"]),
  one(391, "숲 상단 중앙", "tree", "solid", ["tree", "숲 상단", "숲"]),
  one(392, "숲 우상단", "forest", "passable", ["tree", "숲"]),
  one(393, "산맥 좌상단", "cliff", "solid", ["cliff", "산 좌상단", "산맥"]),
  one(394, "산맥 상단 중앙", "cliff", "solid", ["cliff", "산 상단", "산맥"]),
  one(395, "산맥 우상단", "cliff", "solid", ["cliff", "산 우상단", "산맥"]),
  one(396, "격자 구덩이 벽 좌상단", "wall", "solid", ["wall", "석재 난간 좌상단", "격자 구덩이", "석재 구덩이 난간"]),
  one(397, "격자 구덩이 벽 상단", "wall", "solid", ["wall", "석재 난간 상단", "격자 구덩이", "석재 구덩이 난간"]),
  one(398, "격자 구덩이 벽 우상단", "wall", "solid", ["wall", "석재 난간 우상단", "격자 구덩이", "석재 구덩이 난간"]),
  one(399, "어두운 구덩이 좌상단", "cliff", "solid", ["cliff", "암석 구덩이 좌상단", "어두운 구덩이", "암석 구덩이"]),
  one(400, "어두운 구덩이 상단", "cliff", "solid", ["cliff", "암석 구덩이 상단", "어두운 구덩이", "암석 구덩이"]),
  one(401, "어두운 구덩이 우상단", "cliff", "solid", ["cliff", "암석 구덩이 우상단", "어두운 구덩이", "암석 구덩이"]),
  one(402, "좌향 화살표 발판", "floor", "passable", ["floor"]),
  one(403, "우향 화살표 발판", "floor", "passable", ["floor"]),
  one(404, "유리창 상단", "window", "solid", ["window", "유리창"]),
  one(405, "붉은 카펫 좌측 테두리", "decoration", "passable", ["decoration", "붉은 양탄자 좌측단", "붉은 카펫", "붉은 양탄자"]),
  one(406, "붉은 양탄자 중앙", "decoration", "passable", ["decoration", "붉은 카펫 중앙", "붉은 양탄자", "붉은 카펫"]),
  one(407, "붉은 카펫 우측 테두리", "decoration", "passable", ["decoration", "붉은 양탄자 우측단", "붉은 카펫", "붉은 양탄자"]),
  one(408, "큰 갈색 산 좌하단", "cliff", "solid", ["cliff", "큰 산 좌하단", "큰 갈색 산", "큰 산"]),
  one(409, "큰 갈색 산 우하단", "rock", "solid", ["cliff", "큰 산 우하단", "큰 갈색 산", "큰 산"]),
  one(410, "원형 석탑 하단 입구", "wall", "solid", ["wall", "돌 탑 하단", "원형 석탑", "돌 탑"]),
  one(411, "석조 유적 하단 입구", "prop", "solid", ["prop", "석조 유적 하단", "석조 유적"]),
  one(412, "석조 다리 북단", "stairs", "passable", ["stairs", "석조 다리 상단", "석조 다리"]),
  one(413, "동굴 입구", "door", "passable", ["door"]),
  one(414, "세로 침대 하단", "furniture", "solid", ["furniture", "침대 하단", "세로 침대", "침대"]),
  one(415, "가로 침대 좌측", "furniture", "solid", ["furniture", "가로 침대"]),
  one(416, "가로 침대 우측", "furniture", "solid", ["furniture", "가로 침대"]),
  one(417, "빈 슬롯", "empty", "passable", ["empty"]),
  one(418, "피아노 좌측", "furniture", "solid", ["furniture", "피아노"]),
  one(419, "피아노 우측", "furniture", "solid", ["furniture", "피아노"]),

  // ── 14행 (인덱스 420-449) ────────────────────────────────────────────
  one(420, "숲 좌측", "tree", "solid", ["tree", "숲"]),
  one(421, "숲 중앙", "tree", "solid", ["tree", "숲"]),
  one(422, "숲 우측", "forest", "passable", ["tree", "숲"]),
  one(423, "산맥 좌측", "cliff", "solid", ["cliff", "산 좌측", "산맥"]),
  one(424, "산맥 중앙", "cliff", "solid", ["cliff", "산 중앙", "산맥"]),
  one(425, "산맥 우측", "cliff", "solid", ["cliff", "산 우측", "산맥"]),
  one(426, "격자 구덩이 벽 좌측", "wall", "solid", ["wall", "석재 난간 좌측", "격자 구덩이", "석재 구덩이 난간"]),
  one(427, "격자 구덩이 내부", "floor", "passable", ["floor", "격자 구덩이 중앙", "격자 구덩이", "석재 구덩이 난간"]),
  one(428, "격자 구덩이 벽 우측", "wall", "solid", ["wall", "석재 난간 우측", "격자 구덩이", "석재 구덩이 난간"]),
  one(429, "어두운 구덩이 좌측", "cliff", "solid", ["cliff", "암석 구덩이 좌측", "어두운 구덩이", "암석 구덩이"]),
  one(430, "어두운 구덩이 내부", "floor", "solid", ["floor", "암석 구덩이 중앙", "어두운 구덩이", "암석 구덩이"]),
  one(431, "어두운 구덩이 우측", "cliff", "solid", ["cliff", "암석 구덩이 우측", "어두운 구덩이", "암석 구덩이"]),
  one(432, "갈색 기와 지붕 상단", "roof", "solid", ["roof", "갈색 기와 지붕"]),
  one(433, "붉은 기와 지붕 상단", "roof", "solid", ["roof", "붉은 기와 지붕"]),
  one(434, "유리창 하단", "window", "solid", ["window", "유리창"]),
  one(435, "붉은 카펫 좌하단 모서리", "decoration", "passable", ["decoration", "붉은 양탄자 좌하단", "붉은 카펫", "붉은 양탄자"]),
  one(436, "붉은 카펫 하단 테두리", "decoration", "passable", ["decoration", "붉은 양탄자 하단", "붉은 카펫", "붉은 양탄자"]),
  one(437, "붉은 카펫 우하단 모서리", "decoration", "passable", ["decoration", "붉은 양탄자 우하단", "붉은 카펫", "붉은 양탄자"]),
  one(438, "화산 분화구 좌측", "cliff", "solid", ["cliff", "화산 좌상단", "화산"]),
  one(439, "화산 분화구 우측", "rock", "solid", ["cliff", "화산 우상단", "화산"]),
  one(440, "성채 좌상단", "wall", "solid", ["wall", "성 좌상단", "성채", "성"]),
  one(441, "성채 우상단", "wall", "solid", ["wall", "성 우상단", "성채", "성"]),
  one(442, "석조 다리 교차부", "stairs", "passable", ["stairs", "석조 다리 중단", "석조 다리"]),
  one(443, "석조 다리 가로형 좌측", "stairs", "passable", ["stairs", "수평 석조 다리 우측", "석조 다리"]),
  one(444, "파이프 오르간 파이프 좌측", "furniture", "solid", ["furniture", "파이프 오르간 좌상단", "파이프 오르간"]),
  one(445, "파이프 오르간 파이프 우측", "furniture", "solid", ["furniture", "파이프 오르간 우상단", "파이프 오르간"]),
  one(446, "붉은 1인용 왕좌 상단", "furniture", "solid", ["furniture", "붉은색 의자 등받이", "붉은 1인용 왕좌", "붉은색 등받이 의자"]),
  one(447, "빈 슬롯", "empty", "passable", ["empty"]),
  one(448, "붉은색 대형 소파 등받이 좌측", "furniture", "solid", ["furniture", "대형 붉은 왕좌 좌상단", "붉은색 대형 소파", "대형 붉은 왕좌"]),
  one(449, "붉은색 대형 소파 등받이 우측", "furniture", "solid", ["furniture", "대형 붉은 왕좌 우상단", "붉은색 대형 소파", "대형 붉은 왕좌"]),

  // ── 15행 (인덱스 450-479) ────────────────────────────────────────────
  one(450, "숲 좌하단", "tree", "solid", ["tree", "숲"]),
  one(451, "숲 하단 중앙", "tree", "solid", ["tree", "숲 하단", "숲"]),
  one(452, "숲 우하단", "forest", "passable", ["tree", "숲"]),
  one(453, "산맥 좌하단", "cliff", "solid", ["cliff", "산 좌하단", "산맥"]),
  one(454, "산맥 하단 중앙", "cliff", "solid", ["cliff", "산 하단", "산맥"]),
  one(455, "산맥 우하단", "cliff", "solid", ["cliff", "산 우하단", "산맥"]),
  one(456, "격자 구덩이 벽 좌하단", "wall", "solid", ["wall", "석재 난간 좌하단", "격자 구덩이", "석재 구덩이 난간"]),
  one(457, "격자 구덩이 벽 하단", "wall", "solid", ["wall", "석재 난간 하단", "격자 구덩이", "석재 구덩이 난간"]),
  one(458, "격자 구덩이 벽 우하단", "wall", "solid", ["wall", "석재 난간 우하단", "격자 구덩이", "석재 구덩이 난간"]),
  one(459, "어두운 구덩이 좌하단", "cliff", "solid", ["cliff", "암석 구덩이 좌하단", "어두운 구덩이", "암석 구덩이"]),
  one(460, "구덩이 하단", "cliff", "solid", ["최종판정", "cliff", "구덩이"]),
  one(461, "어두운 구덩이 우하단", "cliff", "solid", ["cliff", "암석 구덩이 우하단", "어두운 구덩이", "암석 구덩이"]),
  one(462, "갈색 기와 지붕 하단", "roof", "solid", ["roof", "갈색 기와 지붕"]),
  one(463, "붉은 기와 지붕 하단", "roof", "solid", ["roof", "붉은 기와 지붕"]),
  one(464, "환기구", "prop", "passable", ["최종판정", "prop"]),
  one(465, "붉은 양탄자 계단 좌측", "stairs", "passable", ["stairs", "붉은 카펫 계단 좌측", "붉은 양탄자 계단", "붉은 카펫 계단"]),
  one(466, "붉은 양탄자 계단 중앙", "stairs", "passable", ["stairs", "붉은 카펫 계단 중앙", "붉은 양탄자 계단", "붉은 카펫 계단"]),
  one(467, "붉은 양탄자 계단 우측", "stairs", "passable", ["stairs", "붉은 카펫 계단 우측", "붉은 양탄자 계단", "붉은 카펫 계단"]),
  one(468, "화산 기슭 좌하단", "cliff", "solid", ["cliff", "화산 좌하단", "화산"]),
  one(469, "화산 기슭 우하단", "rock", "solid", ["cliff", "화산 우하단", "화산"]),
  one(470, "성채 좌하단", "wall", "solid", ["wall", "성 좌하단", "성채", "성"]),
  one(471, "성채 우하단", "wall", "solid", ["wall", "성 우하단", "성채", "성"]),
  one(472, "석조 다리 남단", "stairs", "passable", ["stairs", "석조 다리 하단", "석조 다리"]),
  one(473, "석조 다리 가로형 우측", "stairs", "passable", ["stairs", "수평 석조 다리 난간", "석조 다리"]),
  one(474, "파이프 오르간 건반 좌측", "furniture", "solid", ["furniture", "파이프 오르간 좌하단", "파이프 오르간"]),
  one(475, "파이프 오르간 건반 우측", "furniture", "solid", ["furniture", "파이프 오르간 우하단", "파이프 오르간"]),
  one(476, "붉은 1인용 왕좌 하단", "furniture", "solid", ["furniture", "붉은색 의자 방석", "붉은 1인용 왕좌", "붉은색 등받이 의자"]),
  one(477, "붉은색 대형 소파 팔걸이 좌측", "furniture", "solid", ["furniture", "대형 붉은 왕좌 좌하단", "붉은색 대형 소파", "대형 붉은 왕좌"]),
  one(478, "붉은색 대형 소파 방석 중앙", "furniture", "solid", ["furniture", "대형 붉은 왕좌 중앙", "붉은색 대형 소파", "대형 붉은 왕좌"]),
  one(479, "붉은색 대형 소파 팔걸이 우측", "furniture", "solid", ["furniture", "대형 붉은 왕좌 우하단", "붉은색 대형 소파", "대형 붉은 왕좌"]),
]);
