// retro_World(레트로 월드맵) 칩셋(tex_easyrpg_chipset_retro_world) 타일 그림판의 AI 검색용 큐레이션 시맨틱 테이블.
// 이 파일은 생성물이다 — 수기 편집 대신 scripts/build-tile-semantics.mts 로 재생성한다.
// 판독 절차(지어낸 이름이 아니라 실제 통산 과정):
//   1. gen-chipset-blocks.mts 가 4행을 경계선 없는 연속 30x4 아틀라스로 굽는다.
//      격자선을 그리지 않는 이유: 여러 칸에 걸친 물건을 다시 쪼개 놓으면 그게 그대로 오독이 된다.
//   2. 인덱스 확인은 gen-chipset-strips.mts 의 숫자 라벨로만 한다(스트립은 세로 연속성을 끊는다).
//   3. 서로 모르는 판독자 2명 이상이 독립 서술하고 role 다수결로 정리한다.
//      픽셀이 거의 같은 시트(retro_exterior/retro_house, RGB 차이 0.4%)는 판독을 합치므로 한 칸에 최대 4표다.
//   4. 다수결이 이전 라벨과 어긋나는 칸만 교정한다. 갈리는 칸은 그대로 둔다 —
//      지울 수 없는 칸을 지어내는 것이 이 테이블을 무너뜨렸던 원인이다. 보류 목록은 tile-reaudit/splits.txt.
//   5. 사람이 14~20배 크롭으로 확인한 칸은 overrides.json 이 다수결을 이긴다
//      (판독자 전원이 틀린 사례가 있었다 — 125/155/185/215 는 바닥이 아니라 석조 틀 유리창이다).
// tileSemanticsDungeon.ts / tileSemanticsInterior.ts 와 동일한 계약: tileset.tileMeta[] 와 별개로
// 관리되는 검색 전용 데이터다. 통행성/레이어 계약은 tilesetHarness 가, 타일별 정밀 라벨은 여기가 담당한다.
//
// 좌표 규약: 30타일/행, ID = 행×30 + 열. 아트가 없는 슬롯(완전 투명 또는 분홍 컬러키 단색)은
// 서술할 대상이 없으므로 엔트리를 만들지 않는다 — scripts/verify-tile-semantics.mts 가 픽셀에서
// 그 목록을 직접 구해 커버리지를 검증한다.
// 도화 가능 여부는 상수가 아니라 PNG 에서 직접 유도한다(불투명·비키색 픽셀이 하나라도 있는가).
//
// 실측: 도화 가능 480칸 전수 서술, 고유 라벨 438개.
// 조립: scripts/build-tile-semantics.mts (수기 편집 대신 이 스크립트로 재생성한다).

import type { CombinedTownTileSemanticEntry } from "./tileSemanticsCombinedTown";

export type RetroWorldTileSemanticEntry = CombinedTownTileSemanticEntry;

function entries(
  indexes: readonly number[],
  label: string,
  role: string,
  passage: "passable" | "solid",
  tags: readonly string[]
): RetroWorldTileSemanticEntry[] {
  return indexes.map((index) => ({ index, label, role, passage, tags: [label, ...tags] }));
}

function one(
  index: number,
  label: string,
  role: string,
  passage: "passable" | "solid",
  tags: readonly string[]
): RetroWorldTileSemanticEntry {
  return { index, label, role, passage, tags: [label, ...tags] };
}

export const RETRO_WORLD_TILE_SEMANTICS: readonly RetroWorldTileSemanticEntry[] = [
  // ── 0행 (인덱스 0-29) ─────────────────────────────────────────────
  one(0, "잔디 물가 북쪽 1", "water", "solid", ["water", "풀밭 물가 좌상단", "연못"]),
  one(1, "잔디 물가 북쪽 2", "water", "solid", ["water", "풀밭 물가 상단", "연못"]),
  one(2, "잔디 물가 북쪽 3", "water", "solid", ["water", "풀밭 물가 우상단", "연못"]),
  one(3, "눈 덮인 물가 북쪽 1", "water", "solid", ["water", "눈밭 물가 좌상단", "연못"]),
  one(4, "눈 덮인 물가 북쪽 2", "water", "solid", ["water", "눈밭 물가 상단", "연못"]),
  one(5, "눈 덮인 물가 북쪽 3", "water", "solid", ["water", "눈밭 물가 우상단", "연못"]),
  one(6, "숲 사방 풀 경계", "forest", "solid", ["forest", "수풀", "사방경계"]),
  one(7, "밝은 점무늬 초원", "terrain", "passable", ["grass", "평원", "풀밭"]),
  one(8, "빽빽한 자주빛 숲", "terrain", "solid", ["forest", "수풀", "나무", "판독보류"]),
  one(9, "초원 속 둥근 사막", "sand", "passable", ["sand", "모래", "중앙"]),
  one(10, "성긴 점무늬 초원", "terrain", "passable", ["grass", "평원", "풀잎"]),
  one(11, "북쪽 열린 모래밭", "sand", "passable", ["sand", "사막", "북쪽"]),
  one(12, "분홍 석재 타일", "floor", "passable", ["floor", "붉은 돌바닥"]),
  one(13, "청회색 석재 타일", "floor", "passable", ["floor", "청회색 돌바닥"]),
  one(14, "자주색 밝은 석벽", "wall", "solid", ["wall", "돌벽", "밝은틈"]),
  one(15, "자주색 굵은 석벽", "wall", "solid", ["wall", "돌벽", "굵은돌"]),
  one(16, "자주색 엇갈린 석벽", "wall", "solid", ["wall", "돌벽", "엇갈림"]),
  one(17, "자주색 촘촘한 석벽", "wall", "solid", ["wall", "돌벽", "촘촘함"]),
  one(18, "초원 북동 대각 경계", "cliff", "solid", ["cliff", "풀밭", "북동"]),
  one(19, "초원 북쪽 쐐기 경계", "cliff", "solid", ["cliff", "풀밭", "쐐기"]),
  one(20, "자갈 대각선 절벽 좌상향", "cliff", "solid", ["cliff", "보라 자갈 절벽 좌상단", "보라 자갈 절벽"]),
  one(21, "자갈 대각선 절벽 우상향", "cliff", "solid", ["cliff", "보라 자갈 절벽 우상단", "보라 자갈 절벽"]),
  one(22, "설원 북서 대각 경계", "cliff", "solid", ["snow", "눈밭", "북서"]),
  one(23, "설원 북쪽 쐐기 경계", "cliff", "solid", ["snow", "눈밭", "쐐기"]),
  one(24, "녹색 삼각 지붕 좌측", "roof", "solid", ["roof", "초록 박공지붕 왼쪽", "녹색 삼각 지붕", "초록 박공지붕"]),
  one(25, "녹색 삼각 지붕 우측", "roof", "solid", ["roof", "초록 박공지붕 오른쪽", "녹색 삼각 지붕", "초록 박공지붕"]),
  one(26, "흑색 삼각 지붕 좌측", "roof", "solid", ["roof", "보라 박공지붕 왼쪽", "흑색 삼각 지붕", "보라 박공지붕"]),
  one(27, "흑색 삼각 지붕 우측", "roof", "solid", ["roof", "보라 박공지붕 오른쪽", "흑색 삼각 지붕", "보라 박공지붕"]),
  one(28, "흰색 눈 덮인 삼각 지붕 좌측", "roof", "solid", ["roof", "흰 박공지붕 왼쪽", "흰색 삼각 지붕", "흰 박공지붕"]),
  one(29, "흰색 눈 덮인 삼각 지붕 우측", "roof", "solid", ["roof", "흰 박공지붕 오른쪽", "흰색 삼각 지붕", "흰 박공지붕"]),

  // ── 1행 (인덱스 30-59) ─────────────────────────────────────────────
  ...entries([30, 31, 32], "초원 사이 세로 강", "water", "solid", ["river", "강물", "애니메이션"]),
  ...entries([33, 34, 35], "설원 사이 세로 강", "water", "solid", ["river", "설원", "애니메이션"]),
  one(36, "숲 서쪽 풀 경계", "forest", "solid", ["forest", "수풀", "서쪽"]),
  one(37, "숲 북쪽 풀 경계", "terrain", "solid", ["forest", "수풀", "북쪽", "판독보류"]),
  one(38, "숲 동쪽 풀 경계", "forest", "solid", ["forest", "수풀", "동쪽"]),
  one(39, "모래밭 북서 풀모서리", "sand", "passable", ["sand", "모래", "북서"]),
  one(40, "모래밭 북쪽 풀경계", "sand", "passable", ["sand", "모래", "북쪽"]),
  one(41, "모래밭 북동 풀모서리", "sand", "passable", ["sand", "모래", "북동"]),
  one(42, "연보라 석재 타일", "floor", "passable", ["floor", "분홍빛 돌바닥"]),
  one(43, "회녹색 석재 타일", "floor", "passable", ["floor", "녹회색 돌바닥"]),
  one(44, "자주색 큰돌 석벽", "wall", "solid", ["wall", "돌벽", "큰돌"]),
  one(45, "자주색 가로줄 석벽", "wall", "solid", ["wall", "돌벽", "가로줄"]),
  one(46, "자주색 밝은줄 석벽", "wall", "solid", ["wall", "돌벽", "밝은줄"]),
  one(47, "자주색 잔돌 석벽", "wall", "solid", ["wall", "돌벽", "잔돌"]),
  one(48, "초원 남서 대각 경계", "cliff", "solid", ["cliff", "풀밭", "남서"]),
  one(49, "초원 남쪽 쐐기 경계", "cliff", "solid", ["cliff", "풀밭", "남쪽"]),
  one(50, "자갈 대각선 절벽 우하향", "cliff", "solid", ["cliff", "보라 자갈 절벽 좌하단", "보라 자갈 절벽"]),
  one(51, "자갈 대각선 절벽 좌하향", "cliff", "solid", ["cliff", "보라 자갈 절벽 우하단", "보라 자갈 절벽"]),
  one(52, "설원 남서 대각 경계", "cliff", "solid", ["snow", "눈밭", "남서"]),
  one(53, "설원 남쪽 역삼각 경계", "cliff", "solid", ["snow", "눈밭", "역삼각"]),
  one(54, "오름 대각 나무울타리", "fence", "solid", ["fence", "목책", "오름대각", "분홍배경"]),
  one(55, "긴 가로 나무울타리", "fence", "solid", ["fence", "목책", "가로", "분홍배경"]),
  one(56, "내림 대각 나무울타리", "fence", "solid", ["fence", "목책", "내림대각", "분홍배경"]),
  one(57, "회백색 바위 더미", "rock", "solid", ["rock", "돌무더기", "회백색"]),
  one(58, "푸른 수정 산봉우리", "mountain", "solid", ["mountain", "산봉우리", "푸른색"]),
  one(59, "은빛 쌍봉 산맥", "mountain", "solid", ["mountain", "산맥", "쌍봉"]),

  // ── 2행 (인덱스 60-89) ─────────────────────────────────────────────
  ...entries([60, 61, 62], "초원 사이 가로 강", "water", "solid", ["river", "강물", "애니메이션"]),
  ...entries([63, 64, 65], "설원 사이 가로 강", "water", "solid", ["river", "설원", "애니메이션"]),
  one(66, "숲 북서 풀모서리", "terrain", "solid", ["forest", "수풀", "북서", "판독보류"]),
  one(67, "숲 위쪽 좁은 풀띠", "terrain", "solid", ["forest", "수풀", "풀띠", "판독보류"]),
  one(68, "숲 북동 풀모서리", "terrain", "solid", ["forest", "수풀", "북동", "판독보류"]),
  one(69, "모래밭 서쪽 풀경계", "sand", "passable", ["sand", "모래", "서쪽"]),
  one(70, "밝은 점무늬 모래밭", "sand", "passable", ["sand", "사막", "점무늬"]),
  one(71, "모래밭 동쪽 풀경계", "sand", "passable", ["sand", "모래", "동쪽"]),
  one(72, "목재 판자 바닥", "floor", "passable", ["floor", "가로 나무 바닥"]),
  one(73, "얼룩진 목재 판자 바닥", "floor", "passable", ["floor", "얼룩진 가로 나무 바닥"]),
  one(74, "좌측 기둥 회벽 상단", "wall", "solid", ["wall", "밝은 회벽 상단", "기둥 회벽", "밝은 회벽"]),
  one(75, "기둥 없는 회벽 상단", "wall", "solid", ["wall", "밝은 회벽 상단", "기둥 회벽", "밝은 회벽"]),
  one(76, "오른쪽 기둥이 있는 회벽 상단", "wall", "solid", ["wall", "우측 기둥 회벽 상단", "밝은 회벽", "기둥 회벽"]),
  one(77, "왼쪽 기둥이 있는 회벽 상단", "wall", "solid", ["wall", "양측 기둥 좁은 회벽 상단", "밝은 회벽", "기둥 회벽"]),
  one(78, "잔디 절벽 좌측 경계", "cliff", "solid", ["cliff", "풀밭 절벽 좌측", "절벽"]),
  one(79, "가운데 잎무늬 초원", "terrain", "passable", ["grass", "평원", "가운데"]),
  one(80, "잔디 절벽 우측 경계", "cliff", "solid", ["cliff", "풀밭 절벽 우측", "절벽"]),
  one(81, "자갈 절벽 좌상단 모서리", "cliff", "solid", ["cliff", "자갈 절벽 좌상단", "절벽"]),
  one(82, "자갈 절벽 상단 경계", "cliff", "solid", ["cliff", "자갈 절벽 상단", "절벽"]),
  one(83, "자갈 절벽 우상단 모서리", "cliff", "solid", ["cliff", "자갈 절벽 우상단", "절벽"]),
  one(84, "가는 세로 나무울타리", "fence", "solid", ["fence", "목책", "세로", "분홍배경"]),
  one(85, "촘촘한 가로 목책", "fence", "solid", ["fence", "울타리", "촘촘함", "분홍배경"]),
  one(86, "왼쪽 꺾인 나무울타리", "fence", "solid", ["fence", "목책", "꺾임", "분홍배경"]),
  one(87, "돌테두리 우물", "prop", "solid", ["well", "우물", "석조"]),
  one(88, "십자형 길표지판", "sign", "solid", ["sign", "이정표", "갈림길"]),
  one(89, "회색 세로 묘비", "statue", "solid", ["grave", "묘석", "회색", "분홍배경"]),

  // ── 3행 (인덱스 90-119) ─────────────────────────────────────────────
  ...entries([90, 91, 92], "초원 둘레 넓은 바다", "water", "solid", ["ocean", "바다", "애니메이션"]),
  ...entries([93, 94, 95], "설원 둘레 넓은 바다", "water", "solid", ["ocean", "설원", "애니메이션"]),
  one(96, "숲 남서 풀모서리", "forest", "solid", ["forest", "수풀", "남서"]),
  one(97, "숲 남쪽 풀경계", "terrain", "solid", ["forest", "수풀", "남쪽", "판독보류"]),
  one(98, "숲 남동 풀모서리", "forest", "solid", ["forest", "수풀", "남동"]),
  one(99, "모래밭 남서 풀모서리", "sand", "passable", ["sand", "모래", "남서"]),
  one(100, "모래밭 남쪽 풀경계", "sand", "passable", ["sand", "모래", "남쪽"]),
  one(101, "모래밭 남동 풀모서리", "sand", "passable", ["sand", "모래", "남동"]),
  one(102, "세로결 갈색 목벽", "wall", "solid", ["wood", "목재벽", "세로결"]),
  one(103, "목벽 아래 어두운 문", "door", "solid", ["door", "출입구", "목재"]),
  one(104, "좌측 기둥 회벽 하단", "wall", "solid", ["wall", "밝은 회벽 하단", "기둥 회벽", "밝은 회벽"]),
  one(105, "기둥 없는 회벽 하단", "wall", "solid", ["wall", "밝은 회벽 하단", "기둥 회벽", "밝은 회벽"]),
  one(106, "오른쪽 기둥이 있는 회벽 하단", "wall", "solid", ["wall", "우측 기둥 회벽 하단", "밝은 회벽", "기둥 회벽"]),
  one(107, "왼쪽 기둥이 있는 회벽 하단", "wall", "solid", ["wall", "양측 기둥 좁은 회벽 하단", "밝은 회벽", "기둥 회벽"]),
  one(108, "잔디 절벽 좌측 하단 경계", "cliff", "solid", ["cliff", "풀밭 절벽 좌하단", "절벽"]),
  one(109, "가운데 작은잎 초원", "terrain", "passable", ["grass", "평원", "중앙잎"]),
  one(110, "잔디 절벽 우측 하단 경계", "cliff", "solid", ["cliff", "풀밭 절벽 우하단", "절벽"]),
  one(111, "자갈 절벽 좌하단 모서리", "cliff", "solid", ["cliff", "자갈 절벽 좌측", "절벽"]),
  one(112, "자갈 절벽 하단 경계", "cliff", "solid", ["cliff", "자갈 절벽 중앙", "절벽"]),
  one(113, "자갈 절벽 우하단 모서리", "cliff", "solid", ["cliff", "자갈 절벽 우측", "절벽"]),
  one(114, "왼쪽 끝 나무울타리", "fence", "solid", ["fence", "목책", "왼쪽끝", "분홍배경"]),
  one(115, "아래쪽 가로 나무울타리", "fence", "solid", ["fence", "목책", "아래쪽", "분홍배경"]),
  one(116, "나무 이정표 표지판", "prop", "solid", ["prop", "목재 방향 표지판"]),
  one(117, "주황빛 수정 조각", "decoration", "solid", ["crystal", "수정", "파편", "분홍배경"]),
  one(118, "녹색 금속 장비 더미", "prop", "solid", ["prop", "해골과 유골"]),
  one(119, "푸른 회색 돌기둥", "pillar", "solid", ["pillar", "석주", "회색", "분홍배경"]),

  // ── 4행 (인덱스 120-149) ─────────────────────────────────────────────
  ...entries([120, 121, 122], "어두운 수면", "water", "solid", ["최종판정", "water"]),
  one(123, "얼음 폭포 물살 첫째 모습", "water", "solid", ["water", "폭포", "얼음 폭포"]),
  one(124, "얼음 박힌 회색 바위", "rock", "solid", ["rock", "빙정", "회색"]),
  one(125, "청회색 사각 발판", "floor", "passable", ["floor", "금속", "사각형"]),
  one(126, "숲 캐노피 원형 경계", "forest", "solid", ["forest", "수관", "둥근경계"]),
  one(127, "연두색 점무늬 초원", "terrain", "passable", ["grass", "평원", "연두"]),
  one(128, "빽빽한 짙은 숲", "forest", "solid", ["forest", "나무", "수풀"]),
  one(129, "초원 중앙 눈 마름모", "snow", "passable", ["snow", "설원", "마름모"]),
  one(130, "밝은 점무늬 초원", "terrain", "passable", ["grass", "평지", "밝은풀"]),
  one(131, "눈밭 네 모서리 초원", "snow", "passable", ["snow", "설원", "잔디모서리"]),
  one(132, "짙은 청회색 자갈길", "path", "passable", ["path", "자갈", "청회색"]),
  one(133, "자주색 거친 자갈길", "path", "passable", ["path", "자갈", "보라"]),
  one(134, "밝은 석조 벽 상단 왼쪽", "wall", "solid", ["wall", "밝은 석조 벽 왼쪽 상단", "밝은 석조 벽"]),
  one(135, "밝은 석조 벽 상단 중앙 왼쪽", "wall", "solid", ["wall", "밝은 석조 벽 왼쪽 위", "밝은 석조 벽"]),
  one(136, "밝은 석조 벽 상단 중앙 오른쪽", "wall", "solid", ["wall", "밝은 석조 벽 가운데 위", "밝은 석조 벽"]),
  one(137, "밝은 석조 벽 상단 오른쪽", "wall", "solid", ["wall", "밝은 석조 벽 오른쪽 위", "밝은 석조 벽"]),
  one(138, "잔디 절벽 왼쪽 상단", "cliff", "solid", ["cliff", "풀밭 절벽 상단 좌측", "잔디 절벽", "풀밭 절벽"]),
  one(139, "잔디 절벽 가운데 상단", "cliff", "solid", ["cliff", "풀밭 절벽 상단 중앙", "잔디 절벽", "풀밭 절벽"]),
  one(140, "잔디 절벽 오른쪽 상단", "cliff", "solid", ["cliff", "풀밭 절벽 상단 우측", "잔디 절벽", "풀밭 절벽"]),
  one(141, "자주색 지붕 왼쪽 상단", "roof", "solid", ["roof", "자주색 돌지붕 왼쪽", "자주색 지붕", "자주색 돌지붕"]),
  one(142, "자주색 지붕 가운데 상단", "roof", "solid", ["roof", "자주색 돌지붕 중앙", "자주색 지붕", "자주색 돌지붕"]),
  one(143, "자주색 지붕 오른쪽 상단", "roof", "solid", ["roof", "자주색 돌지붕 오른쪽", "자주색 지붕", "자주색 돌지붕"]),
  one(144, "노란 불꽃 벽횃불", "torch", "solid", ["torch", "불꽃", "벽장식"]),
  one(145, "물건 놓인 나무 선반", "shelf", "solid", ["shelf", "목재", "수납"]),
  one(146, "벽 스위치", "prop", "passable", ["최종판정", "prop"]),
  one(147, "청록 화살표 벽표지", "sign", "solid", ["sign", "방향", "청록"]),
  one(148, "보라 사각 벽표지", "sign", "solid", ["sign", "표식", "보라색"]),
  one(149, "붉은 항아리 벽표지", "sign", "solid", ["sign", "도자기", "빨강"]),

  // ── 5행 (인덱스 150-179) ─────────────────────────────────────────────
  ...entries([150, 151, 152], "어두운 소용돌이 수면 상부", "water", "solid", ["최종판정", "water", "어두운 소용돌이"]),
  one(153, "얼음 폭포 물살 둘째 모습", "water", "solid", ["water", "폭포", "얼음 폭포"]),
  one(154, "얼음 결정 박힌 바위", "rock", "solid", ["rock", "얼음결정", "회색돌"]),
  one(155, "청회색 오목 발판", "floor", "passable", ["floor", "금속판", "오목형"]),
  one(156, "숲 캐노피 상하 경계", "forest", "solid", ["forest", "수관", "상하띠"]),
  one(157, "숲 캐노피 가로 띠", "forest", "solid", ["forest", "나뭇잎", "가로형"]),
  one(158, "숲 캐노피 오른쪽 경계", "forest", "solid", ["forest", "수풀", "우측"]),
  one(159, "초원 남동쪽 눈모서리", "snow", "passable", ["snow", "설원", "남동"]),
  one(160, "초원 남쪽 눈경계", "snow", "passable", ["snow", "잔디", "남단"]),
  one(161, "초원 남서쪽 눈모서리", "snow", "passable", ["snow", "설원", "남서"]),
  one(162, "베이지 장방형 벽돌길", "path", "passable", ["path", "벽돌", "밝은돌"]),
  one(163, "베이지 나선 문양 돌판", "floor", "passable", ["floor", "소용돌이", "석판"]),
  one(164, "갈색 무늬 석조 벽 하단 왼쪽", "wall", "solid", ["wall", "갈색 석조 벽 왼쪽 상단", "밝은 석조 벽", "갈색 석조 벽"]),
  one(165, "갈색 무늬 석조 벽 하단 중앙 왼쪽", "wall", "solid", ["wall", "갈색 석조 벽 왼쪽 위", "밝은 석조 벽", "갈색 석조 벽"]),
  one(166, "갈색 무늬 석조 벽 하단 중앙 오른쪽", "wall", "solid", ["wall", "갈색 석조 벽 가운데 위", "밝은 석조 벽", "갈색 석조 벽"]),
  one(167, "갈색 무늬 석조 벽 하단 오른쪽", "wall", "solid", ["wall", "갈색 석조 벽 오른쪽 위", "밝은 석조 벽", "갈색 석조 벽"]),
  one(168, "눈 덮인 절벽 왼쪽 상부", "cliff", "solid", ["cliff", "눈 덮인 절벽 상단 좌측", "눈 덮인 절벽"]),
  one(169, "눈 덮인 절벽 가운데 상부", "cliff", "solid", ["cliff", "눈 덮인 절벽 상단 중앙", "눈 덮인 절벽"]),
  one(170, "눈 덮인 절벽 오른쪽 상부", "cliff", "solid", ["cliff", "눈 덮인 절벽 상단 우측", "눈 덮인 절벽"]),
  one(171, "뒤엉킨 목재 벽 왼쪽 상부", "wall", "solid", ["wall", "거친 목재 벽 상단 왼쪽", "뒤엉킨 목재 벽", "자주색 돌지붕 아래 목재 벽"]),
  one(172, "뒤엉킨 목재 벽 가운데 상부", "wall", "solid", ["wall", "거친 목재 벽 상단 중앙", "뒤엉킨 목재 벽", "자주색 돌지붕 아래 목재 벽"]),
  one(173, "뒤엉킨 목재 벽 오른쪽 상부", "wall", "solid", ["wall", "거친 목재 벽 상단 오른쪽", "뒤엉킨 목재 벽", "자주색 돌지붕 아래 목재 벽"]),
  one(174, "초원 풍경 액자", "decoration", "solid", ["painting", "풍경화", "벽장식"]),
  one(175, "인물 초상 액자", "decoration", "solid", ["portrait", "초상화", "벽장식"]),
  one(176, "다색 풍경 액자", "decoration", "solid", ["painting", "그림", "다채색"]),
  one(177, "붉은 글자 벽현수막", "banner", "solid", ["banner", "문자", "빨강"]),
  one(178, "남색 글자 벽현수막", "banner", "solid", ["banner", "글씨", "남색"]),
  one(179, "회색 십자형 구조물", "prop", "solid", ["structure", "교차형", "판독보류"]),

  // ── 6행 (인덱스 180-209) ─────────────────────────────────────────────
  ...entries([180, 181, 182], "어두운 소용돌이 수면 하부", "water", "solid", ["최종판정", "water", "어두운 소용돌이"]),
  one(183, "얼음 폭포 물살 셋째 모습", "water", "solid", ["water", "폭포", "얼음 폭포"]),
  one(184, "얼음 결정 솟은 바위", "rock", "solid", ["rock", "빙정", "돌출"]),
  one(185, "청회색 돌출 발판", "floor", "passable", ["floor", "금속", "볼록형"]),
  one(186, "숲 캐노피 밝은 테두리", "forest", "solid", ["forest", "수관", "밝은풀"]),
  one(187, "숲 캐노피 가는 테두리", "forest", "solid", ["forest", "나뭇잎", "가는풀"]),
  one(188, "숲 캐노피 우측 틈", "forest", "solid", ["forest", "수풀", "오른틈"]),
  one(189, "초원 동쪽 눈경계", "snow", "passable", ["snow", "잔디", "동단"]),
  one(190, "순백색 넓은 눈밭", "snow", "passable", ["snow", "설원", "흰바닥"]),
  one(191, "초원 서쪽 눈경계", "snow", "passable", ["snow", "잔디", "서단"]),
  one(192, "회색 장방형 돌바닥", "floor", "passable", ["floor", "회색벽돌", "석재"]),
  one(193, "동굴 석순 상부", "rock", "solid", ["최종판정", "rock", "동굴 석순"]),
  one(194, "남청색 거친 돌바닥", "floor", "passable", ["floor", "남청석", "거친면"]),
  one(195, "남청색 세로 돌무늬", "floor", "passable", ["floor", "어두운돌", "세로결"]),
  one(196, "남청색 굽은 돌무늬", "floor", "passable", ["floor", "암석", "굽은결"]),
  one(197, "남청색 교차 돌무늬", "floor", "passable", ["floor", "짙은돌", "교차결"]),
  one(198, "눈 덮인 절벽 왼쪽 하부", "cliff", "solid", ["cliff", "눈 덮인 절벽 좌측", "눈 덮인 절벽"]),
  one(199, "눈밭 중앙", "terrain", "passable", ["최종판정", "terrain", "눈밭"]),
  one(200, "눈 덮인 절벽 오른쪽 하부", "cliff", "solid", ["cliff", "눈 덮인 절벽 우측", "눈 덮인 절벽"]),
  one(201, "거친 목재 벽 가운데 왼쪽", "wall", "solid", ["wall", "뒤엉킨 목재 벽 왼쪽 중부", "자주색 돌지붕 아래 목재 벽", "뒤엉킨 목재 벽"]),
  one(202, "뒤엉킨 목재 벽 가운데 중부", "wall", "solid", ["wall", "거친 목재 벽 가운데 중앙", "뒤엉킨 목재 벽", "자주색 돌지붕 아래 목재 벽"]),
  one(203, "거친 목재 벽 가운데 오른쪽", "wall", "solid", ["wall", "뒤엉킨 목재 벽 오른쪽 중부", "자주색 돌지붕 아래 목재 벽", "뒤엉킨 목재 벽"]),
  one(204, "청록 유리 아치창", "window", "solid", ["window", "유리", "아치형"]),
  one(205, "청록 사각 격자창", "window", "solid", ["window", "격자", "푸른유리"]),
  one(206, "흰 커튼 나무창", "window", "solid", ["window", "커튼", "목재틀"]),
  one(207, "무기 거치대 상단", "prop", "solid", ["prop", "검 거치대 상단", "무기 거치대", "검 거치대"]),
  one(208, "문양이 새겨진 석상 상단", "prop", "solid", ["prop", "문양 새긴 묘비 상부", "문양 석상", "문양 새긴 묘비"]),
  one(209, "흰색 코린트 기둥", "pillar", "solid", ["pillar", "석주", "기둥머리"]),

  // ── 7행 (인덱스 210-239) ─────────────────────────────────────────────
  ...entries([210, 211, 212], "검은 심해 수면", "water", "solid", ["최종판정", "water", "검은 수면"]),
  one(213, "얼음 폭포 물살 넷째 모습", "water", "solid", ["water", "폭포", "얼음 폭포"]),
  one(214, "얼음 덩이 얹힌 바위", "rock", "solid", ["rock", "얼음덩이", "회색암석"]),
  one(215, "청회색 중심 발판", "floor", "passable", ["floor", "사각판", "중심광택"]),
  one(216, "숲 캐노피 왼쪽 풀틈", "forest", "solid", ["forest", "수관", "좌측풀"]),
  one(217, "숲 캐노피 아래 풀띠", "forest", "solid", ["forest", "나뭇잎", "하단풀"]),
  one(218, "숲 캐노피 오른쪽 풀틈", "forest", "solid", ["forest", "수풀", "우측풀"]),
  one(219, "초원 북동쪽 눈모서리", "snow", "passable", ["snow", "설원", "북동"]),
  one(220, "초원 북쪽 눈경계", "snow", "passable", ["snow", "잔디", "북단"]),
  one(221, "초원 북서쪽 눈모서리", "snow", "passable", ["snow", "설원", "북서"]),
  one(222, "동굴 석순 좌하부", "rock", "solid", ["최종판정", "rock", "동굴 석순"]),
  one(223, "작은 동굴 석순 무리", "rock", "solid", ["최종판정", "rock", "동굴 석순"]),
  one(224, "짙은 남청색 돌바닥", "floor", "passable", ["floor", "암석", "남청"]),
  one(225, "짙은 돌 세로 균열", "floor", "passable", ["floor", "검은돌", "세로틈"]),
  one(226, "짙은 돌 굽은 균열", "floor", "passable", ["floor", "암석", "굽은틈"]),
  one(227, "짙은 돌 교차 균열", "floor", "passable", ["floor", "남청석", "교차틈"]),
  one(228, "눈밭 남서 절벽 경계", "cliff", "solid", ["snow", "낭떠러지", "남서"]),
  one(229, "눈밭 남쪽 절벽 경계", "cliff", "solid", ["snow", "절벽선", "남단"]),
  one(230, "눈밭 남동 절벽 경계", "cliff", "solid", ["snow", "낭떠러지", "남동"]),
  one(231, "뒤엉킨 목재 벽 왼쪽 하부", "wall", "solid", ["wall", "거친 목재 벽 하단 왼쪽", "뒤엉킨 목재 벽", "자주색 돌지붕 아래 목재 벽"]),
  one(232, "뒤엉킨 목재 벽 오른쪽 하부", "wall", "solid", ["wall", "거친 목재 벽 하단 오른쪽", "뒤엉킨 목재 벽", "자주색 돌지붕 아래 목재 벽"]),
  one(233, "빈 슬롯", "empty", "passable", ["empty"]),
  one(234, "다색 깃발형 묶음", "banner", "solid", ["banner", "여러색", "판독보류"]),
  one(235, "분홍 가로대 나무사다리", "ladder", "passable", ["ladder", "목재", "가로대"]),
  one(236, "검은 출입구", "door", "passable", ["door"]),
  one(237, "자홍빛 세로형 받침 장치", "machine", "solid", ["device", "금속", "판독보류"]),
  one(238, "회색 날개 석상", "statue", "solid", ["statue", "조각상", "날개"]),
  one(239, "회색 홈무늬 기둥", "pillar", "solid", ["pillar", "석주", "세로홈"]),

  // ── 8행 (인덱스 240-269) ─────────────────────────────────────────────
  one(240, "밝은 잔디 성긴 무늬", "terrain", "passable", ["grass", "초원", "점무늬"]),
  one(241, "밝은 잔디 중앙 무늬", "terrain", "passable", ["grass", "초원", "밝은풀"]),
  one(242, "밝은 잔디 우측 무늬", "terrain", "passable", ["grass", "초지", "연두색"]),
  one(243, "짙은 잔디 바둑 무늬", "terrain", "passable", ["grass", "초원", "격자"]),
  one(244, "밝은 잔디 세로 무늬", "terrain", "passable", ["grass", "들판", "풀잎"]),
  one(245, "짙은 잔디 얼룩 무늬", "terrain", "passable", ["grass", "초지", "조밀함"]),
  one(246, "눈 덮인 산 왼쪽 꼭대기", "cliff", "solid", ["cliff", "눈 덮인 절벽 모서리", "눈 덮인 산", "눈 덮인 절벽"]),
  one(247, "잔디 위 둥근 눈밭", "snow", "passable", ["snowfield", "초원", "흰색"]),
  one(248, "암석 섞인 눈밭", "snow", "passable", ["snowfield", "바위", "얼룩"]),
  one(249, "설산 단일 봉우리", "mountain", "solid", ["snow", "산맥", "봉우리"]),
  one(250, "잔디 위 비스듬한 눈밭", "snow", "passable", ["snowfield", "초지", "사선"]),
  one(251, "설산 이중 능선", "mountain", "solid", ["snow", "산맥", "능선"]),
  one(252, "이끼 낀 돌바닥", "floor", "passable", ["floor", "어두운 돌바닥"]),
  one(253, "어두운 돌바닥", "floor", "passable", ["floor"]),
  ...entries([254, 255, 256, 257], "돌 포장 바닥", "floor", "passable", ["floor", "어두운 돌바닥"]),
  one(258, "빈 슬롯", "empty", "passable", ["empty"]),
  one(259, "둥근 잎 장식나무", "tree", "solid", ["topiary", "관목", "화분"]),
  one(260, "갈라진 마른 묘목", "tree", "solid", ["sapling", "고목", "가지"]),
  one(261, "통나무 더미", "prop", "solid", ["prop", "나무 잔해"]),
  one(262, "붉은 지붕 석조집", "town-icon", "solid", ["house", "마을", "건물"]),
  one(263, "회색 지붕 석조집", "town-icon", "solid", ["house", "마을", "회색집"]),
  one(264, "회색 격자 석판", "sign", "solid", ["stone", "표지", "격자"]),
  one(265, "굽은 세로 나무기둥", "pillar", "solid", ["wood", "갈색", "세로대"]),
  one(266, "어두운 통로 입구", "decoration", "passable", ["decoration", "검은 커튼 하단", "검은 커튼"]),
  one(267, "책 가득한 나무책장", "shelf", "solid", ["books", "서가", "목재"]),
  one(268, "빈 두칸 나무선반", "shelf", "solid", ["empty", "수납", "목재"]),
  one(269, "양문 달린 나무장", "furniture", "solid", ["cabinet", "수납장", "문짝"]),

  // ── 9행 (인덱스 270-299) ─────────────────────────────────────────────
  one(270, "연두 잔디 좌측 점무늬", "terrain", "passable", ["grass", "초원", "성긴풀"]),
  one(271, "연두 잔디 가운데 점무늬", "terrain", "passable", ["grass", "초지", "밝은점"]),
  one(272, "연두 잔디 우측 점무늬", "terrain", "passable", ["grass", "들판", "풀무늬"]),
  one(273, "빽빽한 잔디 좌측 무늬", "terrain", "passable", ["grass", "초원", "조밀함"]),
  one(274, "빽빽한 잔디 중앙 무늬", "terrain", "passable", ["grass", "초지", "짙은풀"]),
  one(275, "빽빽한 잔디 우측 무늬", "terrain", "passable", ["grass", "들판", "녹색격자"]),
  one(276, "눈 덮인 절벽 좌측", "cliff", "solid", ["cliff", "눈 덮인 산 왼쪽", "눈 덮인 절벽", "눈 덮인 산"]),
  one(277, "설원 중앙 돌무늬", "snow", "passable", ["snowfield", "회색돌", "중앙"]),
  one(278, "설원 동쪽 풀 경계", "snow", "passable", ["snowfield", "초지경계", "동쪽"]),
  one(279, "설산 서쪽 능선", "mountain", "solid", ["snow", "산맥", "서쪽"]),
  one(280, "설산 중앙 골짜기", "mountain", "solid", ["snow", "산맥", "골짜기"]),
  one(281, "설산 동쪽 능선", "mountain", "solid", ["snow", "산맥", "동쪽"]),
  one(282, "보랏빛 수정 군집", "rock", "solid", ["crystal", "광물", "동굴"]),
  one(283, "비스듬한 보라 수정", "rock", "solid", ["crystal", "원석", "사선"]),
  one(284, "회색 조약돌 바닥", "floor", "passable", ["stone", "자갈", "회색"]),
  one(285, "회색 돌바닥 좌측 무늬", "floor", "passable", ["stone", "동굴바닥", "좌측"]),
  one(286, "회색 돌바닥 중앙 무늬", "floor", "passable", ["stone", "암석바닥", "중앙"]),
  one(287, "회색 돌바닥 우측 무늬", "floor", "passable", ["stone", "자갈길", "우측"]),
  one(288, "꽃 둥근 관목", "plant", "solid", ["flower", "덤불", "노란꽃"]),
  one(289, "두갈래 초록 선인장", "plant", "solid", ["cactus", "사막", "가시"]),
  one(290, "굽은 줄기 야자나무", "tree", "solid", ["palm", "열대", "야자잎"]),
  one(291, "파란 차양 작은 건물", "town-icon", "solid", ["building", "상점", "파란지붕"]),
  one(292, "빨간 차양 노점", "prop", "solid", ["prop", "마을"]),
  one(293, "눈 덮인 마을", "prop", "solid", ["prop", "상점 가판대"]),
  one(294, "긴 목재 기둥 상단", "prop", "solid", ["prop", "목재 기둥 상단", "목재 기둥"]),
  one(295, "쇠테 두른 큰 나무통", "barrel", "solid", ["barrel", "목재", "쇠테"]),
  one(296, "분홍 체크무늬 침대", "bed", "solid", ["bed", "가구", "체크"]),
  one(297, "다색 책 꽂힌 낮은 책장", "shelf", "solid", ["books", "서가", "낮은장"]),
  one(298, "서랍 하나 나무선반", "furniture", "solid", ["drawer", "수납", "목재"]),
  one(299, "서랍 둘 나무선반", "furniture", "solid", ["drawer", "수납장", "두칸"]),

  // ── 10행 (인덱스 300-329) ────────────────────────────────────────────
  one(300, "연한 초원 왼쪽 무늬", "terrain", "passable", ["grass", "들판", "연두"]),
  one(301, "연한 초원 가운데 무늬", "terrain", "passable", ["grass", "평원", "점박이"]),
  one(302, "연한 초원 오른쪽 무늬", "terrain", "passable", ["grass", "초지", "밝은풀"]),
  one(303, "울창한 풀밭 왼쪽 무늬", "terrain", "passable", ["grass", "덤불", "조밀함"]),
  one(304, "울창한 풀밭 가운데 무늬", "terrain", "passable", ["grass", "초원", "짙은녹색"]),
  one(305, "울창한 풀밭 오른쪽 무늬", "terrain", "passable", ["grass", "들판", "격자풀"]),
  one(306, "눈 덮인 절벽 좌측", "cliff", "solid", ["cliff", "눈 덮인 산 왼쪽", "눈 덮인 절벽", "눈 덮인 산"]),
  one(307, "회색 틈 있는 중앙 설원", "snow", "passable", ["snowfield", "균열", "중앙"]),
  one(308, "이끼 드러난 동쪽 설원", "snow", "passable", ["snowfield", "이끼", "동쪽"]),
  one(309, "설산 서편 봉우리", "mountain", "solid", ["snow", "산맥", "서편"]),
  one(310, "설산 가운데 봉우리", "mountain", "solid", ["snow", "고산", "중앙"]),
  one(311, "설산 동편 봉우리", "mountain", "solid", ["snow", "산맥", "동편"]),
  one(312, "적갈색 흙", "terrain", "passable", ["terrain", "밭 흙"]),
  one(313, "자줏빛 흙", "terrain", "passable", ["terrain", "붉은 흙"]),
  one(314, "남색 벽돌벽 윗무늬", "wall", "solid", ["brick", "성벽", "남색"]),
  one(315, "남색 벽돌벽 왼무늬", "wall", "solid", ["brick", "석조", "좌측"]),
  one(316, "남색 벽돌벽 가운데무늬", "wall", "solid", ["brick", "성벽", "중앙"]),
  one(317, "남색 벽돌벽 오른무늬", "wall", "solid", ["brick", "석조", "우측"]),
  one(318, "넓은 수관 왼쪽", "tree", "solid", ["canopy", "나뭇잎", "좌측"]),
  one(319, "넓은 수관 오른쪽", "tree", "solid", ["canopy", "나뭇잎", "우측"]),
  one(320, "회색 석조 장치", "machine", "solid", ["stone", "구조물", "판독보류"]),
  one(321, "홈 석조 장치", "machine", "solid", ["stone", "붉은표식", "판독보류"]),
  one(322, "황금 성 상단 좌측", "prop", "solid", ["prop", "성 왼쪽 상단", "황금 성", "노란 성"]),
  one(323, "황금 성 상단 우측", "prop", "solid", ["prop", "성 오른쪽 상단", "황금 성", "노란 성"]),
  one(324, "긴 목재 기둥 중단", "prop", "solid", ["prop", "목재 기둥 중간", "목재 기둥"]),
  one(325, "연노랑 둥근 항아리", "prop", "solid", ["vase", "도자기", "노란색"]),
  one(326, "둥근 나무 탁자", "furniture", "solid", ["table", "원형", "목재"]),
  one(327, "등받이 높은 나무의자", "furniture", "solid", ["chair", "가구", "정면"]),
  one(328, "낮은 등받이 나무의자", "furniture", "solid", ["chair", "가구", "갈색"]),
  one(329, "흰 타원형 탁상거울", "furniture", "solid", ["mirror", "반사", "화장대"]),

  // ── 11행 (인덱스 330-359) ────────────────────────────────────────────
  one(330, "초록 평원 왼편 무늬", "terrain", "passable", ["grass", "초원", "왼편"]),
  one(331, "초록 평원 중앙 무늬", "terrain", "passable", ["grass", "들판", "중앙"]),
  one(332, "초록 평원 오른편 무늬", "terrain", "passable", ["grass", "초지", "오른편"]),
  one(333, "진한 풀숲 왼편 무늬", "terrain", "passable", ["grass", "수풀", "왼쪽"]),
  one(334, "진한 풀숲 중앙 무늬", "terrain", "passable", ["grass", "덤불", "가운데"]),
  one(335, "진한 풀숲 오른편 무늬", "terrain", "passable", ["grass", "수풀", "오른쪽"]),
  one(336, "눈 덮인 산 왼쪽 하단", "cliff", "solid", ["cliff", "눈 덮인 절벽 좌하단", "눈 덮인 산", "눈 덮인 절벽"]),
  one(337, "눈 덮인 산 가운데 하단", "cliff", "solid", ["cliff", "눈 덮인 절벽 하단", "눈 덮인 산", "눈 덮인 절벽"]),
  one(338, "눈 덮인 산 오른쪽 하단", "cliff", "solid", ["cliff", "눈 덮인 절벽 우하단", "눈 덮인 산", "눈 덮인 절벽"]),
  one(339, "설산 왼쪽 사면", "mountain", "solid", ["snow", "산맥", "좌사면"]),
  one(340, "설산 중앙 사면", "mountain", "solid", ["snow", "고산", "중앙사면"]),
  one(341, "설산 오른쪽 사면", "mountain", "solid", ["snow", "산맥", "우사면"]),
  one(342, "풀 돋은 적갈색 흙", "terrain", "passable", ["terrain", "새싹 밭", "밭"]),
  one(343, "풀 돋은 자줏빛 흙", "terrain", "passable", ["terrain", "새싹 밭", "밭"]),
  one(344, "짙은 남색 벽돌 윗면", "wall", "solid", ["brick", "어두운벽", "상단"]),
  one(345, "짙은 남색 벽돌 왼면", "wall", "solid", ["brick", "성벽", "왼쪽"]),
  one(346, "짙은 남색 벽돌 중간면", "wall", "solid", ["brick", "석벽", "가운데"]),
  one(347, "짙은 남색 벽돌 오른면", "wall", "solid", ["brick", "성벽", "오른쪽"]),
  one(348, "굵은 나무뿌리 왼쪽", "tree", "solid", ["roots", "거목", "좌측"]),
  one(349, "굵은 나무뿌리 오른쪽", "tree", "solid", ["roots", "거목", "우측"]),
  one(350, "붉은 눈 석상 왼쪽", "statue", "solid", ["stone", "붉은눈", "좌측"]),
  one(351, "붉은 눈 석상 오른쪽", "statue", "solid", ["stone", "붉은눈", "우측"]),
  one(352, "황금 성 하단 좌측", "prop", "solid", ["prop", "성 왼쪽 하단", "황금 성", "노란 성"]),
  one(353, "황금 성 하단 우측", "prop", "solid", ["prop", "성 오른쪽 하단", "황금 성", "노란 성"]),
  one(354, "긴 목재 기둥 하단", "prop", "solid", ["prop", "목재 기둥 하단", "목재 기둥"]),
  one(355, "작은 갈색 단지", "prop", "solid", ["prop", "작은 단지"]),
  one(356, "낮은 사각 나무탁자", "furniture", "solid", ["table", "가구", "낮은상"]),
  one(357, "왼쪽 향한 나무의자", "furniture", "solid", ["chair", "측면", "좌향"]),
  one(358, "오른쪽 향한 나무의자", "furniture", "solid", ["chair", "측면", "우향"]),
  one(359, "금테 두른 잠긴 보물상자", "chest", "solid", ["treasure", "상자", "자물쇠"]),

  // ── 12행 (인덱스 360-389) ────────────────────────────────────────────
  one(360, "그늘 진 숲 수관", "forest", "solid", ["forest", "수관", "그늘"]),
  one(361, "연두 점무늬 초원", "terrain", "passable", ["grass", "초원", "연두"]),
  one(362, "갈색 기슭 숲수관", "forest", "solid", ["forest", "수관", "갈색"]),
  one(363, "소나무", "tree", "solid", ["tree"]),
  one(364, "밝은 초원", "terrain", "passable", ["grass", "평원", "노란점"]),
  one(365, "소나무", "tree", "solid", ["tree"]),
  one(366, "네모서리 검은 수면", "water", "solid", ["water", "수면", "모서리"]),
  one(367, "칠흑 수면 한가운데", "water", "solid", ["water", "검은물", "중앙"]),
  one(368, "좌우 끝 검은 수면", "water", "solid", ["water", "수면", "좌우"]),
  one(369, "남색 사각 테두리", "water", "solid", ["water", "남색", "테두리"]),
  one(370, "남색 수면 한가운데", "water", "solid", ["water", "남색", "중앙"]),
  one(371, "좌우 끝 남색 수면", "water", "solid", ["water", "남색", "좌우"]),
  one(372, "노란 위화살 석판", "sign", "passable", ["arrow", "화살표", "위쪽"]),
  one(373, "노란 아래화살 석판", "sign", "passable", ["arrow", "화살표", "아래"]),
  one(374, "회색 가로 벽돌벽", "wall", "solid", ["brick", "벽돌", "회색"]),
  one(375, "붉은 양탄자 모서리", "decoration", "passable", ["decoration", "화려한 카펫 좌상", "붉은 양탄자", "화려한 카펫"]),
  one(376, "화려한 카펫 상단", "decoration", "passable", ["decoration", "붉은 양탄자", "화려한 카펫"]),
  one(377, "붉은 양탄자 모서리", "decoration", "passable", ["decoration", "화려한 카펫 우상", "붉은 양탄자", "화려한 카펫"]),
  one(378, "왼쪽 산비탈 조각", "mountain", "solid", ["mountain", "산비탈", "오버레이"]),
  one(379, "우뚝한 산봉 조각", "mountain", "solid", ["mountain", "산봉", "오버레이"]),
  one(380, "회색 두건 석상", "statue", "solid", ["statue", "석상", "두건"]),
  one(381, "황금 인물 석상", "statue", "solid", ["statue", "석상", "황금"]),
  one(382, "황금 기둥 신전", "town-icon", "solid", ["temple", "신전", "황금"]),
  one(383, "황금 둥근 기념탑", "statue", "solid", ["monument", "기념탑", "황금"]),
  one(384, "회색띠 나무 함", "furniture", "solid", ["wood", "상자", "회색띠"]),
  one(385, "왼쪽 나무 서랍장", "furniture", "solid", ["drawer", "목재", "왼쪽"]),
  one(386, "가운데 나무 서랍장", "furniture", "solid", ["drawer", "목재", "중앙"]),
  one(387, "오른쪽 나무 서랍장", "furniture", "solid", ["drawer", "목재", "오른쪽"]),
  one(388, "테두리 나무 궤짝", "chest", "solid", ["chest", "궤짝", "목재"]),
  one(389, "수정 얹은 파란 상자", "chest", "solid", ["chest", "보물", "수정"]),

  // ── 13행 (인덱스 390-419) ────────────────────────────────────────────
  one(390, "서쪽 그늘 숲수관", "forest", "solid", ["forest", "수관", "서쪽"]),
  one(391, "얼룩진 숲 캐노피", "forest", "solid", ["forest", "수관", "얼룩"]),
  one(392, "연한 올리브 수관", "forest", "solid", ["forest", "수관", "올리브"]),
  ...entries([393, 394, 395], "소나무", "tree", "solid", ["tree", "소나무 숲", "소나무숲"]),
  one(396, "검은 수면 북서 모서리", "water", "solid", ["water", "수면", "북서"]),
  one(397, "검은 수면 북쪽 테두리", "water", "solid", ["water", "수면", "북쪽"]),
  one(398, "검은 수면 북동 모서리", "water", "solid", ["water", "수면", "북동"]),
  one(399, "남색 수면 서쪽 테두리", "water", "solid", ["water", "남색", "서쪽"]),
  one(400, "남색 수면 북쪽 테두리", "water", "solid", ["water", "남색", "북쪽"]),
  one(401, "남색 수면 동쪽 테두리", "water", "solid", ["water", "남색", "동쪽"]),
  one(402, "노란 왼화살 석판", "sign", "passable", ["arrow", "화살표", "왼쪽"]),
  one(403, "노란 오른화살 석판", "sign", "passable", ["arrow", "화살표", "오른쪽"]),
  one(404, "흰 사선 유리창", "window", "solid", ["최종판정", "window"]),
  one(405, "화려한 카펫 좌", "decoration", "passable", ["decoration", "붉은 양탄자", "화려한 카펫"]),
  one(406, "화려한 카펫 중앙", "decoration", "passable", ["decoration", "붉은 양탄자", "화려한 카펫"]),
  one(407, "화려한 카펫 우", "decoration", "passable", ["decoration", "붉은 양탄자", "화려한 카펫"]),
  one(408, "둥근 갈색 바위", "rock", "solid", ["rock", "바위", "갈색"]),
  one(409, "가파른 암벽 조각", "cliff", "solid", ["cliff", "암벽", "갈색"]),
  one(410, "회색 점무늬 석주", "pillar", "solid", ["pillar", "석주", "회색"]),
  one(411, "황금 점무늬 석주", "pillar", "solid", ["pillar", "석주", "황금"]),
  one(412, "돌 우물", "prop", "solid", ["prop", "우물"]),
  one(413, "동굴 입구", "door", "solid", ["door"]),
  one(414, "붉은 나무 안락의자", "furniture", "solid", ["chair", "의자", "빨강"]),
  one(415, "베개 있는 침대 머리", "bed", "solid", ["bed", "침대", "베개"]),
  one(416, "붉은 이불 침대 발치", "bed", "solid", ["bed", "침대", "이불"]),
  one(417, "빈 슬롯", "empty", "passable", ["empty"]),
  one(418, "흰천 걸린 나무장", "furniture", "solid", ["cabinet", "서랍", "흰천"]),
  one(419, "넓은 나무장 오른쪽", "furniture", "solid", ["cabinet", "가구", "오른쪽"]),

  // ── 14행 (인덱스 420-449) ────────────────────────────────────────────
  one(420, "짙은 줄무늬 숲수관", "forest", "solid", ["forest", "수관", "줄무늬"]),
  one(421, "성긴 초록 숲수관", "forest", "solid", ["forest", "수관", "성긴잎"]),
  one(422, "고른 초록 수관", "forest", "solid", ["forest", "수관", "고른잎"]),
  ...entries([423, 424, 425], "소나무", "tree", "solid", ["tree", "소나무 숲", "소나무숲"]),
  one(426, "검은 수면 서쪽 테두리", "water", "solid", ["water", "수면", "서쪽"]),
  one(427, "검은 수면 한가운데", "water", "solid", ["water", "수면", "중심"]),
  one(428, "검은 수면 동쪽 테두리", "water", "solid", ["water", "수면", "동쪽"]),
  one(429, "남색 서쪽 세로 테두리", "water", "solid", ["water", "남색", "서쪽면"]),
  one(430, "남색 수면 내부", "water", "solid", ["water", "남색", "내부"]),
  one(431, "남색 동쪽 세로 테두리", "water", "solid", ["water", "남색", "동쪽면"]),
  one(432, "보라 회색 석벽 상단", "wall", "solid", ["최종판정", "wall", "보라 회색 석벽"]),
  one(433, "갈금 벽돌벽 상단", "wall", "solid", ["최종판정", "wall", "갈금 벽돌벽"]),
  one(434, "분홍 흰 사선무늬", "decoration", "passable", ["stripe", "사선", "분홍"]),
  one(435, "화려한 카펫 좌", "decoration", "passable", ["decoration", "붉은 양탄자", "화려한 카펫"]),
  one(436, "화려한 카펫 하단", "decoration", "passable", ["decoration", "붉은 양탄자", "화려한 카펫"]),
  one(437, "화려한 카펫 우", "decoration", "passable", ["decoration", "붉은 양탄자", "화려한 카펫"]),
  one(438, "용암 흐르는 좌산", "mountain", "solid", ["volcano", "용암", "왼쪽산"]),
  one(439, "분화하는 오른쪽 산", "mountain", "solid", ["volcano", "용암", "오른쪽산"]),
  one(440, "황금 짐승석상 왼쪽", "statue", "solid", ["statue", "짐승", "왼쪽"]),
  one(441, "황금 짐승석상 오른쪽", "statue", "solid", ["statue", "짐승", "오른쪽"]),
  one(442, "회색 격자 창문", "window", "solid", ["최종판정", "window"]),
  one(443, "회색 창턱 석벽", "wall", "solid", ["wall", "창턱", "석재"]),
  one(444, "책장 좌상", "furniture", "solid", ["furniture", "책장 상단", "책장"]),
  one(445, "책장 우상", "furniture", "solid", ["furniture", "책장 상단", "책장"]),
  one(446, "금십자 왕좌 등받이", "furniture", "solid", ["throne", "왕좌", "등받이"]),
  one(447, "왕좌 왼쪽 팔걸이", "furniture", "solid", ["throne", "팔걸이", "왼쪽"]),
  one(448, "붉은 왕좌 좌석", "furniture", "solid", ["throne", "왕좌", "좌석"]),
  one(449, "왕좌 오른쪽 팔걸이", "furniture", "solid", ["throne", "팔걸이", "오른쪽"]),

  // ── 15행 (인덱스 450-479) ────────────────────────────────────────────
  one(450, "서쪽 웅덩이 숲수관", "forest", "solid", ["forest", "수관", "웅덩이"]),
  one(451, "남쪽 밝은 숲수관", "forest", "solid", ["forest", "수관", "밝은잎"]),
  one(452, "숲 캐노피", "forest", "solid", ["forest", "수관", "노란빛"]),
  ...entries([453, 454, 455], "소나무 밑동", "tree", "solid", ["tree", "소나무", "소나무숲", "소나무 숲"]),
  one(456, "검은 수면 남서 모서리", "water", "solid", ["water", "수면", "남서"]),
  one(457, "검은 수면 남쪽 테두리", "water", "solid", ["water", "수면", "남쪽"]),
  one(458, "검은 수면 남동 모서리", "water", "solid", ["water", "수면", "남동"]),
  one(459, "남색 남서 테두리", "water", "solid", ["water", "남색", "남서"]),
  one(460, "남색 수면 남쪽 테두리", "water", "solid", ["water", "남색", "남쪽"]),
  one(461, "남색 남동 테두리", "water", "solid", ["water", "남색", "남동"]),
  one(462, "보라 회색 석벽 하단", "wall", "solid", ["최종판정", "wall", "보라 회색 석벽"]),
  one(463, "갈금 벽돌벽 하단", "wall", "solid", ["최종판정", "wall", "갈금 벽돌벽"]),
  one(464, "회색 격자 쇠창살", "decoration", "passable", ["grate", "창살", "격자"]),
  one(465, "화려한 카펫 하단 좌", "decoration", "passable", ["decoration", "붉은 양탄자", "화려한 카펫"]),
  one(466, "화려한 카펫 하단", "decoration", "passable", ["decoration", "붉은 양탄자", "화려한 카펫"]),
  one(467, "화려한 카펫 하단 우", "decoration", "passable", ["decoration", "붉은 양탄자", "화려한 카펫"]),
  one(468, "둥근 갈색 바위", "rock", "solid", ["rock", "바위", "둥근돌"]),
  one(469, "가파른 암벽 조각", "cliff", "solid", ["cliff", "암벽", "절벽"]),
  one(470, "앉은 황금석상 왼쪽", "statue", "solid", ["statue", "석상", "앉은상"]),
  one(471, "앉은 황금석상 오른쪽", "statue", "solid", ["statue", "석상", "굽은상"]),
  one(472, "회색 세로 석주", "pillar", "solid", ["pillar", "석주", "세로"]),
  one(473, "석조 아치 가로보", "wall", "solid", ["최종판정", "wall", "석조 아치"]),
  one(474, "책 꽂힌 서가 왼쪽", "shelf", "solid", ["books", "서가", "왼쪽"]),
  one(475, "책 꽂힌 서가 오른쪽", "shelf", "solid", ["books", "서가", "오른쪽"]),
  one(476, "금테 붉은 의자 등", "furniture", "solid", ["chair", "의자", "등받이"]),
  one(477, "금 의자 왼쪽 팔", "furniture", "solid", ["chair", "팔걸이", "금색"]),
  one(478, "붉은 의자 방석", "furniture", "solid", ["chair", "방석", "빨강"]),
  one(479, "금 의자 오른쪽 팔", "furniture", "solid", ["chair", "팔걸이", "오른쪽"]),
];
