// retro_Dungeon(레트로 던전) 칩셋(tex_easyrpg_chipset_retro_dungeon) 타일 그림판의 AI 검색용 큐레이션 시맨틱 테이블.
// 이 파일은 생성물이다 — 수기 편집 대신 scripts/build-tile-semantics.mts 로 재생성한다.
// 판독 절차(지어낸 이름이 아니라 실제 통산 과정):
//   1. gen-chipset-blocks.mts 가 4행을 경계선 없는 연속 30x4 아틀라스로 굽는다.
//      격자선을 그리지 않는 이유: 여러 칸에 걸친 물건을 다시 쪼개 놓으면 그게 그대로 오독이 된다.
//   2. 인덱스 확인은 gen-chipset-strips.mts 의 숫자 라벨로만 한다(스트립은 세로 연속성을 끊는다).
//   3. 서로 모르는 판독자 2명 이상이 독립 서술하고 role 다수결로 정리한다.
//      픽셀이 거의 같은 시트(retro_exterior/retro_house, RGB 차이 0.4%)는 판독을 합치므로 한 칸에 최대 4표다.
//   4. 다수결이 이전 라벨과 어긋나는 칸만 교정한다. 갈리는 칸은 그대로 둔다 —
//      지울 수 없는 칸을 지어내는 것이 이 테이블을 무너뜨렸던 원인이다. 보류 목록은 tile-reaudit/splits.txt.
//   5. 사람이 14~20배 크롭으로 확인한 칸은 overrides.json 이 다수결을 이긴다
//      (판독자 전원이 틀린 사례가 있었다 — 125/155/185/215 는 바닥이 아니라 석조 틀 유리창이다).
// tileSemanticsDungeon.ts / tileSemanticsInterior.ts 와 동일한 계약: tileset.tileMeta[] 와 별개로
// 관리되는 검색 전용 데이터다. 통행성/레이어 계약은 tilesetHarness 가, 타일별 정밀 라벨은 여기가 담당한다.
//
// 좌표 규약: 30타일/행, ID = 행×30 + 열. 아트가 없는 슬롯(완전 투명 또는 분홍 컬러키 단색)은
// 서술할 대상이 없으므로 엔트리를 만들지 않는다 — scripts/verify-tile-semantics.mts 가 픽셀에서
// 그 목록을 직접 구해 커버리지를 검증한다.
// 도화 가능 여부는 상수가 아니라 PNG 에서 직접 유도한다(불투명·비키색 픽셀이 하나라도 있는가).
//
// 실측: 도화 가능 478칸 전수 서술, 고유 라벨 410개.
// 조립: scripts/build-tile-semantics.mts (수기 편집 대신 이 스크립트로 재생성한다).

import type { CombinedTownTileSemanticEntry } from "./tileSemanticsCombinedTown";

export type RetroDungeonTileSemanticEntry = CombinedTownTileSemanticEntry;

function entries(
  indexes: readonly number[],
  label: string,
  role: string,
  passage: "passable" | "solid",
  tags: readonly string[]
): RetroDungeonTileSemanticEntry[] {
  return indexes.map((index) => ({ index, label, role, passage, tags: [label, ...tags] }));
}

function one(
  index: number,
  label: string,
  role: string,
  passage: "passable" | "solid",
  tags: readonly string[]
): RetroDungeonTileSemanticEntry {
  return { index, label, role, passage, tags: [label, ...tags] };
}

export const RETRO_DUNGEON_TILE_SEMANTICS: readonly RetroDungeonTileSemanticEntry[] = [
  // ── 0행 (인덱스 0-29) ─────────────────────────────────────────────
  one(0, "연못 상단 프레임1", "water", "solid", ["water", "풀밭 물웅덩이 상단", "연못", "물웅덩이"]),
  one(1, "연못 상단 프레임2", "water", "solid", ["water", "풀밭 물웅덩이 상단", "연못", "물웅덩이"]),
  one(2, "연못 상단 프레임3", "water", "solid", ["water", "풀밭 물웅덩이 상단", "연못", "물웅덩이"]),
  one(3, "석벽 수로 상단 프레임1", "water", "solid", ["water", "석조 수로 상단", "석벽 수로", "석조 수로"]),
  one(4, "석벽 수로 상단 프레임2", "water", "solid", ["water", "석조 수로 상단", "석벽 수로", "석조 수로"]),
  one(5, "석벽 수로 상단 프레임3", "water", "solid", ["water", "석조 수로 상단", "석벽 수로", "석조 수로"]),
  ...entries([6, 7, 8], "하얀 얼음 바닥", "ice", "passable", ["ice", "얼음", "바닥"]),
  one(9, "얼음 바닥 물구멍", "ice", "passable", ["ice", "얼음", "물구멍", "water"]),
  one(10, "눈 바닥", "ice", "passable", ["terrain"]),
  one(11, "눈밭 위 얼음 타일", "terrain", "passable", ["terrain", "얼음 타일 모서리", "빙판"]),
  one(12, "용암 지대 좌상단", "terrain", "passable", ["terrain", "용암 지대"]),
  one(13, "용암 지대 상단", "terrain", "passable", ["terrain", "용암 지대"]),
  one(14, "용암 지대 우상단", "terrain", "passable", ["terrain", "용암 지대"]),
  one(15, "흙 지형", "terrain", "passable", ["terrain", "흙 바닥"]),
  one(16, "용암 대각선 경계 좌상단", "terrain", "passable", ["terrain", "흙과 용암 경계", "용암 지대"]),
  one(17, "용암 대각선 경계 우상단", "terrain", "passable", ["terrain", "흙과 용암 경계", "용암 지대"]),
  one(18, "어두운 석벽 상단 좌측", "wall", "solid", ["최종판정", "wall", "어두운 석벽"]),
  one(19, "어두운 석벽 상단 우측", "wall", "solid", ["최종판정", "wall", "어두운 석벽"]),
  one(20, "문양이 새겨진 어두운 석벽 상단", "wall", "solid", ["wall", "문양이 새겨진 석벽", "어두운 석벽"]),
  one(21, "회청색 돌바닥", "floor", "passable", ["돌", "바닥", "stone"]),
  one(22, "청회색 석재 바닥", "floor", "passable", ["석재", "바닥", "stone"]),
  one(23, "푸른빛 회색 바닥", "floor", "passable", ["회색", "바닥", "stone"]),
  one(24, "석판 묘비 좌측", "prop", "solid", ["prop", "석비 좌측", "석판 묘비", "석비"]),
  one(25, "석판 묘비 중앙", "prop", "solid", ["prop", "석비 중앙", "석판 묘비", "석비"]),
  one(26, "석판 묘비 우측", "prop", "solid", ["prop", "석비 우측", "석판 묘비", "석비"]),
  one(27, "원형 샹들리에 좌측", "prop", "solid", ["prop", "샹들리에 좌측", "원형 샹들리에", "샹들리에"]),
  one(28, "원형 샹들리에 중앙", "prop", "solid", ["prop", "샹들리에 중앙", "원형 샹들리에", "샹들리에"]),
  one(29, "원형 샹들리에 우측", "prop", "solid", ["prop", "샹들리에 우측", "원형 샹들리에", "샹들리에"]),

  // ── 1행 (인덱스 30-59) ─────────────────────────────────────────────
  one(30, "연못 좌측 프레임1", "water", "solid", ["water", "풀밭 물웅덩이 좌측", "연못", "물웅덩이"]),
  one(31, "연못 중앙 프레임2", "water", "solid", ["water", "풀밭 물웅덩이 좌측", "연못", "물웅덩이"]),
  one(32, "연못 우측 프레임3", "water", "solid", ["water", "풀밭 물웅덩이 좌측", "연못", "물웅덩이"]),
  one(33, "석벽 수로 세로길 프레임1", "water", "solid", ["water", "석조 수로 좌측", "석벽 수로", "석조 수로"]),
  one(34, "석벽 수로 세로길 프레임2", "water", "solid", ["water", "석조 수로 좌측", "석벽 수로", "석조 수로"]),
  one(35, "석벽 수로 세로길 프레임3", "water", "solid", ["water", "석조 수로 좌측", "석벽 수로", "석조 수로"]),
  ...entries([36, 37, 38], "하얀 얼음 바닥", "ice", "passable", ["ice", "얼음", "바닥"]),
  one(39, "얼음판 좌상단", "terrain", "passable", ["terrain", "빙판 좌상단", "얼음판", "빙판"]),
  one(40, "얼음판 상단", "terrain", "passable", ["terrain", "빙판 상단", "얼음판", "빙판"]),
  one(41, "얼음판 우상단", "terrain", "passable", ["terrain", "빙판 우상단", "얼음판", "빙판"]),
  one(42, "용암 지대 좌측 가장자리", "terrain", "passable", ["terrain", "용암 지대 좌측", "용암 지대"]),
  one(43, "빛나는 용암 중앙", "terrain", "passable", ["terrain", "용암 지대 중앙", "용암 지대"]),
  one(44, "용암 지대 우측 가장자리", "terrain", "passable", ["terrain", "용암 지대 우측", "용암 지대"]),
  one(45, "어두운 흙 바닥", "terrain", "passable", ["terrain"]),
  ...entries([46, 47], "흙 바닥", "terrain", "passable", ["terrain"]),
  one(48, "어두운 석벽 좌측", "wall", "solid", ["wall", "검푸른 석벽", "어두운 석벽"]),
  one(49, "어두운 석벽 중앙", "wall", "solid", ["wall", "검푸른 석벽", "어두운 석벽"]),
  one(50, "어두운 석벽 우측", "wall", "solid", ["wall", "검푸른 석벽", "어두운 석벽"]),
  one(51, "얼룩진 회청색 바닥", "floor", "passable", ["회색", "바닥", "stone"]),
  one(52, "얼룩진 청회색 돌바닥", "floor", "passable", ["돌", "바닥", "stone"]),
  one(53, "반점 낀 회청색 바닥", "floor", "passable", ["회색", "반점", "바닥"]),
  one(54, "원형 레일 좌상단", "prop", "passable", ["prop", "원형 철로 좌상단", "원형 레일", "원형 철로"]),
  one(55, "원형 레일 우상단", "prop", "passable", ["prop", "원형 철로 우상단", "원형 레일", "원형 철로"]),
  one(56, "광산 레일 가로 분기", "prop", "passable", ["prop", "분기 철로", "광산 레일", "철로"]),
  one(57, "광산 레일 세로 교차로", "prop", "passable", ["prop", "교차 철로", "광산 레일", "철로"]),
  one(58, "광산 레일 가로 교차로", "prop", "passable", ["prop", "분기 철로", "광산 레일", "철로"]),
  one(59, "광산 레일 가로 분기선", "prop", "passable", ["prop", "분기 철로", "광산 레일", "철로"]),

  // ── 2행 (인덱스 60-89) ─────────────────────────────────────────────
  one(60, "연못 하단 프레임1", "water", "solid", ["water", "풀밭 물웅덩이 하단", "연못", "물웅덩이"]),
  one(61, "연못 하단 프레임2", "water", "solid", ["water", "풀밭 물웅덩이 하단", "연못", "물웅덩이"]),
  one(62, "연못 하단 프레임3", "water", "solid", ["water", "풀밭 물웅덩이 하단", "연못", "물웅덩이"]),
  one(63, "석벽 수로 가로길 프레임1", "water", "solid", ["water", "석조 수로 하단", "석벽 수로", "석조 수로"]),
  one(64, "석벽 수로 가로길 프레임2", "water", "solid", ["water", "석조 수로 하단", "석벽 수로", "석조 수로"]),
  one(65, "석벽 수로 가로길 프레임3", "water", "solid", ["water", "석조 수로 하단", "석벽 수로", "석조 수로"]),
  ...entries([66, 67, 68], "하얀 얼음 바닥", "ice", "passable", ["ice", "얼음", "바닥"]),
  one(69, "얼음판 좌측", "terrain", "passable", ["terrain", "빙판 좌측", "얼음판", "빙판"]),
  one(70, "얼음판 중앙", "terrain", "passable", ["terrain", "빙판 중앙", "얼음판", "빙판"]),
  one(71, "얼음판 우측", "terrain", "passable", ["terrain", "빙판 우측", "얼음판", "빙판"]),
  one(72, "용암 지대 좌하단", "terrain", "passable", ["terrain", "용암 지대"]),
  one(73, "용암 지대 하단", "terrain", "passable", ["terrain", "용암 지대"]),
  one(74, "용암 지대 우하단", "terrain", "passable", ["terrain", "용암 지대"]),
  one(75, "악마 얼굴 석조 부조", "decoration", "solid", ["decoration", "석벽의 얼굴 조각"]),
  one(76, "용암 대각선 경계 좌하단", "terrain", "passable", ["terrain", "흙과 용암 경계", "용암 지대"]),
  one(77, "용암 대각선 경계 우하단", "terrain", "passable", ["terrain", "흙과 용암 경계", "용암 지대"]),
  one(78, "짙은 회색 자갈 바닥", "floor", "passable", ["floor", "어두운 조약돌 바닥"]),
  one(79, "분홍빛 석재 바닥", "floor", "passable", ["석재", "바닥", "stone"]),
  one(80, "살구빛 석재 바닥", "floor", "passable", ["석재", "바닥", "stone"]),
  one(81, "푸른빛 자갈 바닥", "floor", "passable", ["floor", "청회색 돌 바닥"]),
  one(82, "황토색 흙 바닥", "terrain", "passable", ["terrain", "황갈색 흙 바닥"]),
  one(83, "어두운 흙 바닥", "terrain", "passable", ["terrain"]),
  one(84, "원형 레일 좌하단", "prop", "passable", ["prop", "원형 철로 좌하단", "원형 레일", "원형 철로"]),
  one(85, "원형 레일 우하단", "prop", "passable", ["prop", "원형 철로 우하단", "원형 레일", "원형 철로"]),
  ...entries([86, 87, 88, 89], "광산 레일 가로 대각선 분기", "prop", "passable", ["prop", "분기 철로", "광산 레일", "철로"]),

  // ── 3행 (인덱스 90-119) ─────────────────────────────────────────────
  one(90, "연못 안쪽 모서리 프레임1", "water", "solid", ["water", "풀밭 물웅덩이 안쪽", "연못", "물웅덩이"]),
  one(91, "연못 안쪽 모서리 프레임2", "water", "solid", ["water", "풀밭 물웅덩이 안쪽", "연못", "물웅덩이"]),
  one(92, "연못 안쪽 모서리 프레임3", "water", "solid", ["water", "풀밭 물웅덩이 안쪽", "연못", "물웅덩이"]),
  one(93, "석벽 수로 안쪽 모서리 프레임1", "water", "solid", ["water", "석조 수로 안쪽", "석벽 수로", "석조 수로"]),
  one(94, "석벽 수로 안쪽 모서리 프레임2", "water", "solid", ["water", "석조 수로 안쪽", "석벽 수로", "석조 수로"]),
  one(95, "석벽 수로 안쪽 모서리 프레임3", "water", "solid", ["water", "석조 수로 안쪽", "석벽 수로", "석조 수로"]),
  ...entries([96, 97, 98], "하얀 얼음 바닥", "ice", "passable", ["ice", "얼음", "바닥"]),
  one(99, "얼음 바닥 물줄기", "ice", "passable", ["ice", "얼음", "물줄기", "water"]),
  one(100, "얼음판 하단", "terrain", "passable", ["terrain", "빙판 하단", "얼음판", "빙판"]),
  one(101, "얼음판 우하단", "terrain", "passable", ["terrain", "빙판 우하단", "얼음판", "빙판"]),
  ...entries([102, 103, 104], "흙 바닥", "terrain", "passable", ["terrain"]),
  one(105, "붉은 석벽 좌측", "wall", "solid", ["wall", "붉은 벽돌 벽", "붉은 석벽"]),
  one(106, "붉은 석벽 중앙", "wall", "solid", ["wall", "붉은 벽돌 벽", "붉은 석벽"]),
  one(107, "붉은 석벽 우측", "wall", "solid", ["wall", "붉은 벽돌 벽", "붉은 석벽"]),
  one(108, "분홍빛 미색 바닥", "floor", "passable", ["미색", "바닥", "stone"]),
  one(109, "살구빛 석회 바닥", "floor", "passable", ["석회", "바닥", "stone"]),
  one(110, "보랏빛 석재 바닥", "floor", "passable", ["보랏빛", "석재", "바닥", "stone"]),
  one(111, "밝은 회색 석회 바닥", "floor", "passable", ["회색", "석회", "바닥"]),
  ...entries([112, 113], "새싹이 돋은 흙 바닥", "terrain", "passable", ["terrain", "풀이 난 흙 바닥"]),
  one(114, "세로 직선 광산 레일", "prop", "passable", ["prop", "세로 철로", "광산 레일", "철로"]),
  one(115, "가로 광산 레일 상향 굴곡", "prop", "passable", ["prop", "분기 철로", "광산 레일", "철로"]),
  one(116, "가로 직선 광산 레일", "prop", "passable", ["prop", "가로 철로", "광산 레일", "철로"]),
  one(117, "가로 광산 레일 하향 굴곡", "prop", "passable", ["prop", "분기 철로", "광산 레일", "철로"]),
  one(118, "푸른 수정", "prop", "solid", ["prop"]),
  one(119, "원뿔형 얼음 결정", "prop", "solid", ["prop", "얼음 바위"]),

  // ── 4행 (인덱스 120-149) ─────────────────────────────────────────────
  one(120, "푸른 수면 1", "water", "solid", ["water", "어두운 물"]),
  one(121, "푸른 수면 2", "water", "solid", ["water", "어두운 물"]),
  one(122, "잔잔한 수면 1", "water", "solid", ["water", "어두운 물"]),
  one(123, "폭포 상단 1", "water", "solid", ["water", "폭포 상단", "폭포"]),
  one(124, "물 소용돌이 상단", "water", "solid", ["water", "소용돌이 물 1", "물 소용돌이", "소용돌이 물"]),
  one(125, "푸른 기하학 문양 바닥", "floor", "passable", ["floor", "푸른 마법진 발판 1", "마법진 발판"]),
  ...entries([126, 127, 128], "동굴 바위 바닥", "floor", "passable", ["바위", "rock", "동굴"]),
  one(129, "작은 구덩이", "rock", "passable", ["cliff"]),
  one(130, "거친 동굴 바위 바닥", "floor", "passable", ["바위", "rock", "동굴"]),
  one(131, "어두운 구덩이", "cliff", "solid", ["cliff", "사각 구덩이"]),
  one(132, "갈색 벽돌 바닥", "floor", "passable", ["벽돌", "brick", "갈색"]),
  one(133, "흙 바닥 2", "floor", "passable", ["floor", "흙 바닥"]),
  one(134, "모래색 벽돌 바닥", "floor", "passable", ["벽돌", "brick", "모래"]),
  one(135, "어두운 흙 바닥 좌측 테두리", "floor", "passable", ["floor", "흙 바닥 경계"]),
  one(136, "어두운 흙 바닥", "floor", "passable", ["floor", "흙 바닥"]),
  one(137, "어두운 흙 바닥 우측 테두리", "floor", "passable", ["floor", "흙 바닥"]),
  one(138, "붉은 카펫 좌상단 모서리", "decoration", "passable", ["decoration", "붉은 양탄자 좌상단", "붉은 카펫", "붉은 양탄자"]),
  one(139, "붉은 카펫 상단 테두리", "decoration", "passable", ["decoration", "붉은 양탄자 상단", "붉은 카펫", "붉은 양탄자"]),
  one(140, "붉은 카펫 우상단 모서리", "decoration", "passable", ["decoration", "붉은 양탄자 우상단", "붉은 카펫", "붉은 양탄자"]),
  one(141, "가로 나무 다리 좌측", "floor", "passable", ["floor", "나무 발판", "나무 다리"]),
  one(142, "가로 나무 다리 중앙", "floor", "passable", ["floor", "나무 발판", "나무 다리"]),
  one(143, "가로 나무 다리 우측", "floor", "passable", ["floor", "나무 발판", "나무 다리"]),
  one(144, "목재 사다리 상단", "stairs", "passable", ["stairs", "사다리 상단", "목재 사다리", "사다리"]),
  one(145, "수도사 석상 상단", "prop", "solid", ["prop", "후드 석상 머리", "수도사 석상", "후드 석상"]),
  one(146, "가고일 석상 상단", "prop", "solid", ["prop", "가고일 석상"]),
  one(147, "십자가 묘비", "prop", "solid", ["prop"]),
  one(148, "사각 묘비", "prop", "solid", ["prop", "석조 묘비"]),
  one(149, "고드름", "decoration", "solid", ["decoration"]),

  // ── 5행 (인덱스 150-179) ─────────────────────────────────────────────
  ...entries([150, 151], "푸른 파도 물", "water", "solid", ["물", "water", "애니메이션"]),
  one(152, "잔잔한 수면 2", "water", "solid", ["water", "어두운 물"]),
  one(153, "폭포 상단 2", "water", "solid", ["water", "폭포 중간", "폭포"]),
  one(154, "물 소용돌이 중간", "water", "solid", ["water", "소용돌이 물 2", "물 소용돌이", "소용돌이 물"]),
  one(155, "푸른 기하학 문양 바닥", "floor", "passable", ["floor", "푸른 마법진 발판 2", "마법진 발판"]),
  ...entries([156, 157, 158], "거친 바위 바닥", "floor", "passable", ["바위", "rock", "거침"]),
  one(159, "대형 구덩이 좌상단", "rock", "passable", ["cliff", "대형 구덩이"]),
  one(160, "검은 바위 구덩이", "rock", "solid", ["바위", "구덩이", "pit"]),
  one(161, "대형 구덩이 우상단", "cliff", "solid", ["cliff", "대형 구덩이"]),
  one(162, "암벽 대각선 좌상단", "cliff", "solid", ["cliff", "돌 절벽 좌상단", "암벽", "돌 절벽"]),
  one(163, "암벽 대각선 우상단", "cliff", "solid", ["cliff", "돌 절벽 우상단", "암벽", "돌 절벽"]),
  one(164, "암벽 상단", "cliff", "solid", ["cliff", "돌 절벽", "암벽"]),
  one(165, "갈흙빛 돌 바닥", "floor", "passable", ["돌", "stone", "회색"]),
  one(166, "갈색 점토 바닥", "floor", "passable", ["점토", "갈색", "clay"]),
  one(167, "석회암 돌 바닥", "floor", "passable", ["돌", "stone", "밝음"]),
  one(168, "붉은 카펫 좌측 테두리", "decoration", "passable", ["decoration", "붉은 양탄자 좌측", "붉은 카펫", "붉은 양탄자"]),
  one(169, "붉은 양탄자 중앙", "decoration", "passable", ["decoration", "붉은 카펫 중앙", "붉은 양탄자", "붉은 카펫"]),
  one(170, "붉은 카펫 우측 테두리", "decoration", "passable", ["decoration", "붉은 양탄자 우측", "붉은 카펫", "붉은 양탄자"]),
  one(171, "목재 바닥 1", "floor", "passable", ["floor", "나무 다리"]),
  one(172, "위쪽 노란색 화살표 발판", "path", "passable", ["floor", "위쪽 화살표 발판", "화살표 발판"]),
  one(173, "아래쪽 노란색 화살표 발판", "path", "passable", ["floor", "아래쪽 화살표 발판", "화살표 발판"]),
  one(174, "목재 사다리 하단", "stairs", "passable", ["stairs", "사다리 하단", "목재 사다리", "사다리"]),
  one(175, "후드 석상 받침대", "prop", "solid", ["prop", "수도사 석상 하단", "후드 석상", "수도사 석상"]),
  one(176, "가고일 석상 받침대", "prop", "solid", ["prop", "가고일 석상 하단", "가고일 석상"]),
  one(177, "덩굴 가지 상단", "plant", "passable", ["plant", "식물 덩굴 분기", "덩굴", "식물 덩굴"]),
  one(178, "덩굴 줄기 우하향", "plant", "passable", ["plant", "식물 덩굴 줄기", "덩굴", "식물 덩굴"]),
  one(179, "덩굴 줄기 우상향", "plant", "passable", ["plant", "식물 덩굴 끝", "덩굴", "식물 덩굴"]),

  // ── 6행 (인덱스 180-209) ─────────────────────────────────────────────
  one(180, "푸른 수면 5", "water", "solid", ["water", "어두운 물"]),
  one(181, "푸른 수면 6", "water", "solid", ["water", "어두운 물"]),
  one(182, "잔잔한 수면 3", "water", "solid", ["water", "어두운 물"]),
  one(183, "폭포 하단 1", "water", "solid", ["water", "폭포 중간", "폭포"]),
  one(184, "물 소용돌이 중간", "water", "solid", ["water", "소용돌이 물 3", "물 소용돌이", "소용돌이 물"]),
  one(185, "푸른 기하학 문양 바닥", "floor", "passable", ["floor", "푸른 마법진 발판 3", "마법진 발판"]),
  ...entries([186, 187, 188], "동굴 바위 바닥", "floor", "passable", ["바위", "rock", "동굴"]),
  one(189, "어두운 돌 구덩이", "rock", "solid", ["돌", "구덩이", "pit"]),
  one(190, "대형 구덩이 중앙", "cliff", "solid", ["cliff", "대형 구덩이 내부", "대형 구덩이"]),
  one(191, "대형 구덩이 우측", "cliff", "solid", ["cliff", "대형 구덩이 우단", "대형 구덩이"]),
  one(192, "암벽 좌측", "cliff", "solid", ["cliff", "돌 절벽", "암벽"]),
  one(193, "암벽 중앙", "cliff", "solid", ["cliff", "돌 절벽", "암벽"]),
  one(194, "암벽 우측", "cliff", "solid", ["cliff", "돌 절벽", "암벽"]),
  one(195, "황토 석조 바닥", "floor", "passable", ["황토", "돌", "stone"]),
  one(196, "돌 바닥", "floor", "passable", ["돌", "stone", "붉음"]),
  one(197, "갈색 석재 바닥", "floor", "passable", ["돌", "stone", "갈색"]),
  one(198, "붉은 카펫 좌하단 모서리", "decoration", "passable", ["decoration", "붉은 양탄자 좌하단", "붉은 카펫", "붉은 양탄자"]),
  one(199, "붉은 카펫 하단 테두리", "decoration", "passable", ["decoration", "붉은 양탄자 하단", "붉은 카펫", "붉은 양탄자"]),
  one(200, "붉은 카펫 우하단 모서리", "decoration", "passable", ["decoration", "붉은 양탄자 우하단", "붉은 카펫", "붉은 양탄자"]),
  one(201, "목재 바닥 2", "floor", "passable", ["floor", "나무 다리"]),
  one(202, "왼쪽 노란색 화살표 발판", "path", "passable", ["floor", "왼쪽 화살표 발판", "화살표 발판"]),
  one(203, "오른쪽 노란색 화살표 발판", "path", "passable", ["floor", "오른쪽 화살표 발판", "화살표 발판"]),
  one(204, "철창 상단 좌측", "gate", "solid", ["gate", "쇠창살 좌상단", "철창", "쇠창살"]),
  one(205, "철창 상단 중앙", "gate", "solid", ["gate", "쇠창살 상단", "철창", "쇠창살"]),
  one(206, "철창 상단 우측", "gate", "solid", ["gate", "쇠창살 우상단", "철창", "쇠창살"]),
  one(207, "노란색 발광 균열 좌측", "torch", "solid", ["decoration", "황금빛 액체 튀김 좌측", "노란색 발광 균열", "황금빛 액체 튀김"]),
  one(208, "노란색 발광 균열 중앙", "torch", "solid", ["decoration", "황금빛 액체 튀김 중앙", "노란색 발광 균열", "황금빛 액체 튀김"]),
  one(209, "노란색 발광 균열 파편", "torch", "solid", ["decoration", "황금빛 액체 튀김 우측", "노란색 발광 균열", "황금빛 액체 튀김"]),

  // ── 7행 (인덱스 210-239) ─────────────────────────────────────────────
  one(210, "푸른 수면 7", "water", "solid", ["water", "어두운 물"]),
  one(211, "푸른 수면 8", "water", "solid", ["water", "어두운 물"]),
  one(212, "잔잔한 수면 4", "water", "solid", ["water", "어두운 물"]),
  one(213, "폭포 하단 2", "water", "solid", ["water", "폭포 하단", "폭포"]),
  one(214, "물 소용돌이 하단", "water", "solid", ["water", "소용돌이 물 4", "물 소용돌이", "소용돌이 물"]),
  one(215, "푸른 기하학 문양 바닥", "floor", "passable", ["floor", "푸른 마법진 발판 4", "마법진 발판"]),
  ...entries([216, 217, 218], "동굴 바위 바닥", "floor", "passable", ["바위", "rock", "동굴"]),
  one(219, "대형 구덩이 좌하단", "rock", "solid", ["cliff", "대형 구덩이"]),
  one(220, "대형 구덩이 하단", "cliff", "solid", ["cliff", "대형 구덩이"]),
  one(221, "대형 구덩이 우하단", "cliff", "solid", ["cliff", "대형 구덩이"]),
  one(222, "암벽 대각선 좌하단", "cliff", "solid", ["cliff", "돌 절벽 좌하단", "암벽", "돌 절벽"]),
  one(223, "암벽 대각선 우하단", "cliff", "solid", ["cliff", "돌 절벽 우하단", "암벽", "돌 절벽"]),
  one(224, "파란 꽃이 핀 흙 바닥", "plant", "passable", ["plant"]),
  one(225, "암벽 하단 좌측", "cliff", "solid", ["cliff", "돌벽 하단", "암벽"]),
  one(226, "암벽 하단 중앙", "cliff", "solid", ["cliff", "돌벽 하단", "암벽"]),
  one(227, "암벽 하단 우측", "cliff", "solid", ["cliff", "돌벽 하단", "암벽"]),
  one(228, "붉은 카펫 세로 무늬 좌측", "decoration", "passable", ["decoration", "붉은 양탄자 술 좌측", "붉은 카펫", "붉은 양탄자"]),
  one(229, "붉은 카펫 세로 무늬 중앙", "decoration", "passable", ["decoration", "붉은 양탄자 술 중앙", "붉은 카펫", "붉은 양탄자"]),
  one(230, "붉은 카펫 세로 무늬 우측", "decoration", "passable", ["decoration", "붉은 양탄자 술 우측", "붉은 카펫", "붉은 양탄자"]),
  one(231, "목재 바닥 3", "floor", "passable", ["floor", "나무 다리"]),
  one(232, "투명한 얼음 발판", "floor", "passable", ["floor", "사선 격자 유리판"]),
  one(234, "철창 하단 좌측", "gate", "solid", ["gate", "쇠창살 좌하단", "철창", "쇠창살"]),
  one(235, "철창 하단 중앙", "gate", "solid", ["gate", "쇠창살 하단", "철창", "쇠창살"]),
  one(236, "철창 하단 우측", "gate", "solid", ["gate", "쇠창살 우하단", "철창", "쇠창살"]),
  one(237, "눈 장식 좌측", "decoration", "passable", ["최종판정", "decoration", "눈 장식"]),
  one(238, "눈 장식 중앙", "decoration", "passable", ["최종판정", "decoration", "눈 장식"]),
  one(239, "눈 장식 우측", "decoration", "passable", ["최종판정", "decoration", "눈 장식"]),

  // ── 8행 (인덱스 240-269) ─────────────────────────────────────────────
  ...entries([240, 241, 242], "붉은 암반 바닥", "floor", "passable", ["floor", "용암 바닥"]),
  one(243, "뜨거운 용암 표면", "lava", "solid", ["용암", "lava", "용융", "불길"]),
  one(244, "붉은 암반 바닥", "floor", "passable", ["floor", "용암 바닥"]),
  one(245, "용암 웅덩이", "lava", "solid", ["용암", "lava", "웅덩이", "반짝"]),
  one(246, "1칸 구덩이", "cliff", "solid", ["cliff", "작은 구덩이"]),
  one(247, "어두운 구덩이 바닥", "cliff", "solid", ["cliff", "구덩이 상단 좌측", "구덩이"]),
  one(248, "구덩이 안쪽 모서리", "cliff", "solid", ["cliff", "구덩이 상단 우측", "구덩이"]),
  one(249, "암석 구덩이 상단 좌측", "cliff", "solid", ["cliff", "작은 흙 구덩이", "암석 구덩이"]),
  one(250, "암석 구덩이 상단 중앙", "cliff", "solid", ["cliff", "흙 구덩이 바닥", "암석 구덩이"]),
  one(251, "암석 구덩이 상단 우측", "cliff", "solid", ["cliff", "흙 구덩이 안쪽 모서리", "암석 구덩이"]),
  one(252, "나무 판자 벽", "wall", "solid", ["나무", "wall", "판자", "목재"]),
  one(253, "나무 널빤지 벽", "wall", "solid", ["나무", "wall", "널빤지", "목재"]),
  one(254, "목조 벽 상단 우측", "wall", "solid", ["wall", "목재 벽 상단", "목조 벽", "목재 벽"]),
  one(255, "석벽 상단 좌측", "wall", "solid", ["wall", "암석 벽", "석벽"]),
  one(256, "석벽 상단 중앙", "wall", "solid", ["wall", "암석 벽", "석벽"]),
  one(257, "석벽 상단 우측", "wall", "solid", ["wall", "암석 벽", "석벽"]),
  one(259, "둥근 나무 아치 좌측", "prop", "solid", ["prop", "목재 아치 좌측", "둥근 나무 아치", "목재 아치"]),
  one(260, "둥근 나무 아치 우측", "prop", "solid", ["prop", "목재 아치 우측", "둥근 나무 아치", "목재 아치"]),
  one(261, "회색 바위 덩어리", "rock", "solid", ["회색", "rock", "바위", "언덕"]),
  one(262, "얼음 석순 상단", "rock", "solid", ["rock", "얼음 석순"]),
  one(263, "타오르는 불꽃 1프레임", "torch", "solid", ["불꽃", "fire", "촛불", "애니메이션"]),
  one(264, "벽걸이 횃불", "torch", "solid", ["prop", "벽 횃불"]),
  one(265, "문자가 새겨진 석판", "prop", "solid", ["prop", "고대 문자 석판"]),
  one(266, "벽면 스위치 홈", "decoration", "passable", ["decoration", "벽면 열쇠구멍"]),
  one(267, "어두운 종유석", "rock", "solid", ["rock", "천장 종유석"]),
  one(268, "동굴 천장 암석 좌측", "cliff", "solid", ["cliff", "동굴 천장 좌측", "동굴 천장", "어두운 동굴 입구"]),
  one(269, "동굴 천장 암석 우측", "cliff", "solid", ["cliff", "동굴 천장 우측", "동굴 천장", "어두운 동굴 입구"]),

  // ── 9행 (인덱스 270-299) ─────────────────────────────────────────────
  ...entries([270, 271, 272], "붉은 암반 바닥", "floor", "passable", ["floor", "용암 바닥"]),
  one(273, "뜨거운 용암 표면", "lava", "solid", ["용암", "lava", "용융", "불길"]),
  one(274, "용암 웅덩이", "lava", "solid", ["용암", "lava", "웅덩이", "반짝"]),
  one(275, "밝은 용암 물결", "lava", "solid", ["용암", "lava", "밝음", "물결"]),
  one(276, "어두운 구덩이 좌상단", "cliff", "solid", ["cliff", "구덩이 좌상단", "어두운 구덩이", "구덩이"]),
  one(277, "어두운 구덩이 상단", "cliff", "solid", ["cliff", "구덩이 상단", "어두운 구덩이", "구덩이"]),
  one(278, "어두운 구덩이 우상단", "cliff", "solid", ["cliff", "구덩이 우상단", "어두운 구덩이", "구덩이"]),
  one(279, "암석 구덩이 좌상단", "cliff", "solid", ["cliff", "흙 구덩이 좌상단", "암석 구덩이", "흙 구덩이"]),
  one(280, "암석 구덩이 상단", "cliff", "solid", ["cliff", "흙 구덩이 상단", "암석 구덩이", "흙 구덩이"]),
  one(281, "암석 구덩이 우상단", "cliff", "solid", ["cliff", "흙 구덩이 우상단", "암석 구덩이", "흙 구덩이"]),
  one(282, "눈 덮인 바닥 좌상단", "floor", "passable", ["floor", "눈밭 좌상단", "눈 덮인 바닥", "설원"]),
  one(283, "눈 덮인 바닥 상단", "floor", "passable", ["floor", "눈밭 상단", "눈 덮인 바닥", "설원"]),
  one(284, "눈 덮인 바닥 우상단", "floor", "passable", ["floor", "눈밭 우상단", "눈 덮인 바닥", "설원"]),
  one(285, "얼음 절벽 상단 좌측", "cliff", "solid", ["cliff", "빙벽 좌상단", "얼음 절벽", "빙벽"]),
  one(286, "얼음 절벽 상단 중앙", "cliff", "solid", ["cliff", "빙벽 상단", "얼음 절벽", "빙벽"]),
  one(287, "얼음 절벽 상단 우측", "cliff", "solid", ["cliff", "빙벽 우상단", "얼음 절벽", "빙벽"]),
  one(288, "뾰족한 암석 결정", "rock", "solid", ["암석", "rock", "뾰족", "결정"]),
  one(289, "작은 얼음 덩어리", "rock", "solid", ["rock", "얼음 덩어리"]),
  one(290, "회색 바위 언덕", "rock", "solid", ["회색", "rock", "언덕", "바위"]),
  one(291, "둥근 회색 바위", "rock", "solid", ["회색", "rock", "둥글", "바위"]),
  one(292, "얼음 석순 하단", "rock", "solid", ["rock", "얼음 석순"]),
  one(293, "삼각 화로 받침대", "prop", "solid", ["prop", "목재 화로 하단", "삼각 화로", "목재 화로"]),
  one(294, "목재 기둥 상단", "prop", "solid", ["prop", "목재 기둥"]),
  one(295, "어두운 통로 상단", "door", "solid", ["door", "동굴 입구 상단", "어두운 통로", "동굴 입구"]),
  one(296, "밧줄", "stairs", "passable", ["최종판정", "stairs"]),
  one(297, "나무 사다리", "stairs", "passable", ["stairs", "목재 사다리"]),
  one(298, "목재 표지판", "prop", "solid", ["prop", "나무 표지판"]),
  one(299, "해골 장식", "prop", "solid", ["prop", "해골"]),

  // ── 10행 (인덱스 300-329) ────────────────────────────────────────────
  ...entries([300, 301, 302], "붉은 암반 바닥", "floor", "passable", ["floor", "용암 바닥"]),
  one(303, "뜨거운 용암 표면", "lava", "solid", ["용암", "lava", "용융", "불길"]),
  one(304, "용암 웅덩이", "lava", "solid", ["용암", "lava", "웅덩이", "반짝"]),
  one(305, "가장자리 용암 물결", "lava", "solid", ["용암", "lava", "가장자리", "물결"]),
  one(306, "어두운 구덩이 좌측", "cliff", "solid", ["cliff", "구덩이 좌측", "어두운 구덩이", "구덩이"]),
  one(307, "어두운 구덩이 중앙", "cliff", "solid", ["cliff", "구덩이 내부", "어두운 구덩이", "구덩이"]),
  one(308, "어두운 구덩이 우측", "cliff", "solid", ["cliff", "구덩이 우측", "어두운 구덩이", "구덩이"]),
  one(309, "암석 구덩이 좌측", "cliff", "solid", ["cliff", "흙 구덩이 좌측", "암석 구덩이", "흙 구덩이"]),
  one(310, "암석 구덩이 내부", "cliff", "solid", ["cliff", "흙 구덩이 중앙", "암석 구덩이", "흙 구덩이"]),
  one(311, "암석 구덩이 우측", "cliff", "solid", ["cliff", "흙 구덩이 우측", "암석 구덩이", "흙 구덩이"]),
  one(312, "눈 덮인 바닥 좌측", "floor", "passable", ["floor", "눈밭 좌측", "눈 덮인 바닥", "설원"]),
  one(313, "눈 덮인 바위", "rock", "solid", ["rock"]),
  one(314, "눈 덮인 바닥 우측", "floor", "passable", ["floor", "눈밭 우측", "눈 덮인 바닥", "설원"]),
  one(315, "얼음 절벽 중앙 좌측", "cliff", "solid", ["cliff", "빙벽 좌측", "얼음 절벽", "빙벽"]),
  one(316, "얼음 절벽 중앙", "cliff", "solid", ["cliff", "빙벽 중앙", "얼음 절벽", "빙벽"]),
  one(317, "얼음 절벽 중앙 우측", "cliff", "solid", ["cliff", "빙벽 우측", "얼음 절벽", "빙벽"]),
  one(318, "거친 어두운 바위", "rock", "solid", ["바위", "rock", "거침", "어두움"]),
  one(319, "갈색 돌덩어리", "rock", "solid", ["돌", "rock", "갈색", "덩어리"]),
  one(320, "빈 슬롯", "empty", "passable", ["empty"]),
  one(321, "얼음 결정 상단", "rock", "solid", ["rock", "얼음 결정"]),
  one(322, "포개진 회색 바위", "rock", "solid", ["회색", "rock", "바위", "포개짐"]),
  one(323, "낮은 회색 바위", "rock", "solid", ["회색", "rock", "바위", "낮음"]),
  one(324, "목재 기둥 중앙", "prop", "solid", ["prop", "목재 기둥 중단", "목재 기둥"]),
  one(325, "어두운 통로 중앙", "door", "passable", ["door", "동굴 입구 중단", "어두운 통로", "동굴 입구"]),
  one(326, "원형 나무 탁자", "furniture", "solid", ["furniture", "원형 목재 탁자"]),
  one(327, "나무 의자 뒷모습", "furniture", "solid", ["furniture", "목재 의자 후면"]),
  one(328, "나무 의자 뒷모습", "furniture", "solid", ["furniture", "목재 의자 전면"]),
  one(329, "목재 책장 상단", "furniture", "solid", ["furniture", "목재 책장"]),

  // ── 11행 (인덱스 330-359) ────────────────────────────────────────────
  ...entries([330, 331, 332], "붉은 암반 바닥", "floor", "passable", ["floor", "용암 바닥"]),
  one(333, "뜨거운 용암 표면", "lava", "solid", ["용암", "lava", "용융", "불길"]),
  one(334, "용암 웅덩이", "lava", "solid", ["용암", "lava", "웅덩이", "반짝"]),
  one(335, "오른쪽 용암 물결", "lava", "solid", ["용암", "lava", "오른쪽", "물결"]),
  one(336, "어두운 구덩이 좌하단", "cliff", "solid", ["cliff", "구덩이 좌하단", "어두운 구덩이", "구덩이"]),
  one(337, "어두운 구덩이 하단", "cliff", "solid", ["cliff", "구덩이 하단", "어두운 구덩이", "구덩이"]),
  one(338, "어두운 구덩이 우하단", "cliff", "solid", ["cliff", "구덩이 우하단", "어두운 구덩이", "구덩이"]),
  one(339, "암석 구덩이 좌하단", "cliff", "solid", ["cliff", "흙 구덩이 좌하단", "암석 구덩이", "흙 구덩이"]),
  one(340, "암석 구덩이 하단", "cliff", "solid", ["cliff", "흙 구덩이 하단", "암석 구덩이", "흙 구덩이"]),
  one(341, "암석 구덩이 우하단", "cliff", "solid", ["cliff", "흙 구덩이 우하단", "암석 구덩이", "흙 구덩이"]),
  one(342, "눈 덮인 바닥 좌하단", "floor", "passable", ["floor", "눈밭 좌하단", "눈 덮인 바닥", "설원"]),
  one(343, "눈 덮인 바닥 하단", "floor", "passable", ["floor", "눈밭 하단", "눈 덮인 바닥", "설원"]),
  one(344, "눈 덮인 바닥 우하단", "floor", "passable", ["floor", "눈밭 우하단", "눈 덮인 바닥", "설원"]),
  one(345, "눈사람", "prop", "solid", ["prop"]),
  one(346, "얼음 절벽 하단 좌측", "cliff", "solid", ["cliff", "빙벽 좌하단", "얼음 절벽", "빙벽"]),
  one(347, "얼음 절벽 하단 우측", "cliff", "solid", ["cliff", "빙벽 우하단", "얼음 절벽", "빙벽"]),
  one(348, "질감 난 어두운 바위", "rock", "solid", ["바위", "rock", "질감", "어두움"]),
  one(349, "갈색 바위 덩어리", "rock", "solid", ["돌", "rock", "갈색", "덩어리"]),
  one(350, "얼음 결정 좌하단", "rock", "solid", ["rock", "얼음 결정"]),
  one(351, "얼음 결정 우하단", "rock", "solid", ["rock", "얼음 결정"]),
  one(352, "거대 회색 바위", "rock", "solid", ["회색", "rock", "바위", "거대"]),
  one(353, "매끈 회색 바위", "rock", "solid", ["회색", "rock", "바위", "매끈"]),
  one(354, "목재 기둥 하단", "prop", "solid", ["prop", "목재 기둥"]),
  one(355, "동굴 입구 바닥", "floor", "passable", ["최종판정", "floor", "동굴 입구"]),
  one(356, "둥근 목재 스툴", "furniture", "solid", ["furniture", "목재 스툴"]),
  one(357, "목재 의자 좌측면", "furniture", "solid", ["furniture", "측면 나무 의자"]),
  one(358, "목재 의자 우측면", "furniture", "solid", ["furniture", "측면 나무 의자"]),
  one(359, "목재 책장 하단", "furniture", "solid", ["furniture", "목재 책장"]),

  // ── 12행 (인덱스 360-389) ────────────────────────────────────────────
  ...entries([360, 361, 362], "갈색 흙 바닥", "terrain", "passable", ["terrain"]),
  one(363, "작은 덤불 상단", "plant", "passable", ["plant", "작은 덤불", "덤불"]),
  one(364, "갈색 흙 바닥", "terrain", "passable", ["terrain"]),
  one(365, "큰 덤불 상단", "plant", "passable", ["plant", "작은 덤불", "덤불"]),
  one(366, "얼음 테두리 어두운 웅덩이 단일 타일", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(367, "얼음 테두리 어두운 웅덩이 가로 좌측", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(368, "얼음 테두리 어두운 웅덩이 가로 우측", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(369, "돌 테두리 어두운 웅덩이 단일 타일", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(370, "돌 테두리 어두운 웅덩이 가로 좌측", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(371, "돌 테두리 어두운 웅덩이 가로 우측", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(372, "얼음 폭포 상단 좌측", "water", "solid", ["water", "얼음 폭포 상단 1", "얼음 폭포"]),
  one(373, "얼음 폭포 상단 중앙", "water", "solid", ["water", "얼음 폭포 상단 2", "얼음 폭포"]),
  one(374, "얼음 폭포 상단 우측", "water", "solid", ["water", "얼음 폭포 상단 3", "얼음 폭포"]),
  one(375, "얼음 벽 상단 좌측", "wall", "solid", ["wall", "얼음 벽"]),
  one(376, "얼음 벽 상단 중앙", "wall", "solid", ["wall", "얼음 벽"]),
  one(377, "얼음 벽 상단 우측", "wall", "solid", ["wall", "얼음 벽"]),
  one(378, "붉은 광석 더미 좌측", "rock", "solid", ["최종판정", "rock", "붉은 광석 더미"]),
  one(379, "붉은 광석 더미 우측", "rock", "solid", ["최종판정", "rock", "붉은 광석 더미"]),
  one(380, "흙 더미 좌측", "prop", "solid", ["최종판정", "prop", "흙 더미"]),
  one(381, "흙 더미 우측", "prop", "solid", ["최종판정", "prop", "흙 더미"]),
  one(382, "연녹색 광석 조각 무리", "rock", "solid", ["rock", "녹색 자갈 더미"]),
  one(383, "회색 둥근 돌", "rock", "solid", ["회색", "돌", "rock"]),
  one(384, "목재 침대 상단(머리판과 베개)", "furniture", "solid", ["furniture", "침대 머리맡 상단", "세로 목재 침대", "침대"]),
  one(385, "목재 테이블 상단 좌측", "furniture", "solid", ["furniture", "긴 목재 선반 왼쪽", "목재 테이블", "긴 목재 선반"]),
  one(386, "목재 테이블 상단 중앙좌측", "furniture", "solid", ["furniture", "긴 목재 선반 중앙", "목재 테이블", "긴 목재 선반"]),
  one(387, "목재 테이블 상단 중앙우측", "furniture", "solid", ["furniture", "긴 목재 선반 오른쪽", "목재 테이블", "긴 목재 선반"]),
  one(388, "목재 테이블 상단 우측", "furniture", "solid", ["furniture", "짧은 목재 선반", "목재 테이블"]),
  one(389, "목재 서랍장", "chest", "solid", ["furniture", "목재 협탁"]),

  // ── 13행 (인덱스 390-419) ────────────────────────────────────────────
  ...entries([390, 391, 392], "갈색 흙 바닥", "terrain", "passable", ["terrain"]),
  one(393, "큰 덤불 상단 좌측", "plant", "solid", ["plant", "덤불 숲 좌상단", "큰 덤불", "덤불 숲"]),
  one(394, "덤불 숲 상단 중앙", "plant", "solid", ["plant", "큰 덤불 상단 중앙", "덤불 숲", "큰 덤불"]),
  one(395, "큰 덤불 상단 우측", "plant", "solid", ["plant", "덤불 숲 우상단", "큰 덤불", "덤불 숲"]),
  one(396, "얼음 테두리 어두운 웅덩이 상단 좌측", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(397, "얼음 테두리 어두운 웅덩이 상단 중앙", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(398, "얼음 테두리 어두운 웅덩이 상단 우측", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(399, "돌 테두리 어두운 웅덩이 상단 좌측", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(400, "돌 테두리 어두운 웅덩이 상단 중앙", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(401, "돌 테두리 어두운 웅덩이 상단 우측", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(402, "얼음 폭포 하단 좌측", "water", "solid", ["water", "얼음 폭포 하단 1", "얼음 폭포"]),
  one(403, "얼음 폭포 하단 중앙", "water", "solid", ["water", "얼음 폭포 하단 2", "얼음 폭포"]),
  one(404, "얼음 폭포 하단 우측", "water", "solid", ["water", "얼음 폭포 하단 3", "얼음 폭포"]),
  one(405, "어두운 던전 벽 상단 좌측", "wall", "solid", ["wall", "어두운 청석 벽 좌상단", "어두운 던전 벽", "어두운 청석 벽"]),
  one(406, "어두운 던전 벽 상단 중앙", "wall", "solid", ["wall", "어두운 청석 벽 상단 중앙", "어두운 던전 벽", "어두운 청석 벽"]),
  one(407, "어두운 던전 벽 상단 우측", "wall", "solid", ["wall", "어두운 청석 벽 우상단", "어두운 던전 벽", "어두운 청석 벽"]),
  one(408, "눈 더미 좌측", "prop", "solid", ["최종판정", "prop", "눈 더미"]),
  one(409, "눈 더미 우측", "prop", "solid", ["최종판정", "prop", "눈 더미"]),
  one(410, "검은 광석 더미 좌측", "rock", "solid", ["최종판정", "rock", "검은 광석 더미"]),
  one(411, "검은 광석 더미 우측", "rock", "solid", ["최종판정", "rock", "검은 광석 더미"]),
  one(412, "갈색 암석 덩어리", "rock", "solid", ["rock", "갈색 바위 무더기"]),
  one(413, "얼음 결정 파편", "rock", "solid", ["rock", "얼음 결정 무리"]),
  one(414, "목재 침대 하단(이불과 발판)", "furniture", "solid", ["furniture", "세로 침대 하단", "세로 목재 침대", "세로 침대"]),
  one(415, "가로 목재 침대 왼쪽(베개)", "furniture", "solid", ["furniture", "가로 침대 좌측 머리맡", "가로 목재 침대", "가로 침대"]),
  one(416, "가로 목재 침대 오른쪽", "furniture", "solid", ["furniture", "가로 침대 우측 발치", "가로 목재 침대", "가로 침대"]),
  one(417, "테 두른 나무 물통", "pillar", "solid", ["prop", "나무 통"]),
  one(418, "돌 항아리", "prop", "solid", ["항아리", "pot", "판독보류"]),
  one(419, "나무 스툴 의자", "furniture", "solid", ["furniture", "나무 스툴"]),

  // ── 14행 (인덱스 420-449) ────────────────────────────────────────────
  ...entries([420, 421, 422], "갈색 흙 바닥", "terrain", "passable", ["terrain"]),
  one(423, "덤불 숲 좌측 가장자리", "plant", "solid", ["plant", "큰 덤불 중앙 좌측", "덤불 숲", "큰 덤불"]),
  one(424, "덤불 숲 내부", "plant", "solid", ["plant", "큰 덤불 중앙", "덤불 숲", "큰 덤불"]),
  one(425, "덤불 숲 우측 가장자리", "plant", "solid", ["plant", "큰 덤불 중앙 우측", "덤불 숲", "큰 덤불"]),
  one(426, "얼음 테두리 어두운 웅덩이 중간 좌측", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(427, "얼음 테두리 어두운 웅덩이 내부", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(428, "얼음 테두리 어두운 웅덩이 중간 우측", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(429, "돌 테두리 어두운 웅덩이 중간 좌측", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(430, "돌 테두리 어두운 웅덩이 내부", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(431, "돌 테두리 어두운 웅덩이 중간 우측", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(432, "조약돌 바닥 경계 좌측", "floor", "passable", ["floor", "돌길 모서리 좌상단", "조약돌 바닥", "돌길"]),
  one(433, "조약돌 바닥 경계 우측", "floor", "passable", ["floor", "돌길 모서리 우상단", "조약돌 바닥", "돌길"]),
  one(434, "조약돌 바닥", "floor", "passable", ["floor"]),
  one(435, "어두운 던전 벽 하단 좌측", "wall", "solid", ["wall", "어두운 청석 벽 좌측 중앙", "어두운 던전 벽", "어두운 청석 벽"]),
  one(436, "회색 둥근 바위", "rock", "solid", ["회색", "바위", "boulder", "돌덩이"]),
  one(437, "어두운 던전 벽 하단 우측", "wall", "solid", ["wall", "어두운 청석 벽 우측 중앙", "어두운 던전 벽", "어두운 청석 벽"]),
  one(438, "대형 비석 상단 좌측", "prop", "solid", ["prop", "새김글 비석 좌상단", "대형 비석", "새김글 비석"]),
  one(439, "새김글 비석 상단 중앙", "prop", "solid", ["prop", "대형 비석 상단 중앙", "새김글 비석", "대형 비석"]),
  one(440, "대형 비석 상단 우측", "prop", "solid", ["prop", "새김글 비석 우상단", "대형 비석", "새김글 비석"]),
  one(441, "갈색 격자 아치 좌측", "decoration", "solid", ["격자", "아치", "판독보류", "lattice"]),
  one(442, "갈색 격자 아치 중앙", "decoration", "solid", ["격자", "아치", "판독보류", "lattice"]),
  one(443, "갈색 격자 아치 우측", "decoration", "solid", ["격자", "아치", "판독보류", "lattice"]),
  one(444, "아치형 이중문 아치 좌상단", "door", "solid", ["최종판정", "door", "아치형 석조 이중문"]),
  one(445, "아치형 이중문 아치 우상단", "door", "solid", ["최종판정", "door", "아치형 석조 이중문"]),
  one(446, "회색 돌 기둥", "pillar", "solid", ["기둥", "pillar", "돌"]),
  one(447, "황금 왕좌 좌측 상단", "furniture", "solid", ["왕좌", "금장식", "throne", "옥좌"]),
  one(448, "붉은 왕좌 등받이", "furniture", "solid", ["왕좌", "등받이", "throne", "옥좌"]),
  one(449, "황금 왕좌 우측 상단", "furniture", "solid", ["왕좌", "금장식", "throne", "옥좌"]),

  // ── 15행 (인덱스 450-479) ────────────────────────────────────────────
  ...entries([450, 451, 452], "갈색 흙 바닥", "terrain", "passable", ["terrain"]),
  one(453, "큰 덤불 하단 좌측", "plant", "solid", ["plant", "덤불 숲 좌하단", "큰 덤불", "덤불 숲"]),
  one(454, "덤불 숲 하단 중앙", "plant", "solid", ["plant", "큰 덤불 하단 중앙", "덤불 숲", "큰 덤불"]),
  one(455, "큰 덤불 하단 우측", "plant", "solid", ["plant", "덤불 숲 우하단", "큰 덤불", "덤불 숲"]),
  one(456, "얼음 테두리 어두운 웅덩이 하단 좌측", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(457, "얼음 테두리 어두운 웅덩이 하단 중앙", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(458, "얼음 테두리 어두운 웅덩이 하단 우측", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(459, "돌 테두리 어두운 웅덩이 하단 좌측", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(460, "돌 테두리 어두운 웅덩이 하단 중앙", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(461, "돌 테두리 어두운 웅덩이 하단 우측", "water", "solid", ["웅덩이", "pool", "자동타일", "구덩이 판독 있음"]),
  one(462, "조약돌 바닥 1", "floor", "passable", ["floor", "돌길 바닥", "돌길"]),
  one(463, "조약돌 바닥 2", "floor", "passable", ["floor", "돌길 바닥", "돌길"]),
  one(464, "어두운 조약돌 바닥", "floor", "passable", ["floor", "조약돌 바닥"]),
  one(465, "어두운 던전 벽 하단 바닥 좌측", "wall", "solid", ["wall", "어두운 청석 벽 좌하단", "어두운 던전 벽", "어두운 청석 벽"]),
  one(466, "어두운 던전 벽 하단 바닥 중앙", "wall", "solid", ["wall", "어두운 청석 벽 하단 중앙", "어두운 던전 벽", "어두운 청석 벽"]),
  one(467, "어두운 던전 벽 하단 바닥 우측", "wall", "solid", ["wall", "어두운 청석 벽 우하단", "어두운 던전 벽", "어두운 청석 벽"]),
  one(468, "대형 비석 하단 좌측", "prop", "solid", ["prop", "새김글 비석 좌하단", "대형 비석", "새김글 비석"]),
  one(469, "새김글 비석 하단 중앙(비문)", "prop", "solid", ["prop", "대형 비석 하단 중앙", "새김글 비석", "대형 비석"]),
  one(470, "대형 비석 하단 우측", "prop", "solid", ["prop", "새김글 비석 우하단", "대형 비석", "새김글 비석"]),
  one(471, "갈색 격자 문양 좌측", "decoration", "solid", ["격자", "문양", "판독보류", "lattice"]),
  one(472, "촛불 수레바퀴 샹들리에 하단 중앙", "decoration", "solid", ["decoration", "샹들리에 하단 중앙", "촛불 수레바퀴 샹들리에", "샹들리에"]),
  one(473, "갈색 격자 문양 우측", "decoration", "solid", ["격자", "문양", "판독보류", "lattice"]),
  one(474, "아치형 이중문 좌하단", "door", "solid", ["최종판정", "door", "아치형 석조 이중문"]),
  one(475, "아치형 이중문 우하단", "door", "solid", ["최종판정", "door", "아치형 석조 이중문"]),
  one(476, "회색 돌 기둥", "pillar", "solid", ["기둥", "pillar", "돌"]),
  one(477, "황금 왕좌 좌측 팔걸이", "furniture", "solid", ["왕좌", "팔걸이", "throne", "옥좌"]),
  one(478, "붉은 왕좌 좌석", "furniture", "solid", ["왕좌", "좌석", "throne", "옥좌"]),
  one(479, "황금 왕좌 우측 팔걸이", "furniture", "solid", ["왕좌", "팔걸이", "throne", "옥좌"]),
];
