"""Authored light expansion and quiet, broken water bands."""
def p(x,y,rows):return {'x':x,'y':y,'rows':rows.strip('\n').splitlines()}
PAL={'a':'#253f7d','b':'#4165a6','c':'#759bc5','d':'#add2df','e':'#dcf1ef','f':'#ffffff'}

EXPAND=p(1,4,"""
.......................dd
......................deed
.....................deffed
.....................deffed
....................defffed
...........cd......defffffed
..........cde.....defffffffed
.........cdeed...defffffffffed
........cdeffeddefffffffffffed
.......cdefffffffffffffffffffed
......cdefffffffffffffffffffffed
.....cdefffffffffffffffffffffffed
....cdefffffffffffffffffffffffffed
...cdefffffffffffffffffffffffffffed
..cdefffffffffffffffffffffffffffffed
.cdefffffffffffffffffffffffffffffffed
cdefffffffffffffffffffffffffffffffffed
cdeffffffffffffffffffffffffffffffffffed
deffffffffffffffffffffffffffffffffffffed
defffffffffffffffffffffffffffffffffffffed
efffffffffffffffffffffffffffffffffffffffed
effffffffffffffffffffffffffffffffffffffffed
effffffffffffffffffffffffffffffffffffffffed
efffffffffffffffffffffffffffffffffffffffffed
efffffffffffffffffffffffffffffffffffffffffed
effffffffffffffffffffffffffffffffffffffffffed
effffffffffffffffffffffffffffffffffffffffffed
efffffffffffffffffffffffffffffffffffffffffffed
efffffffffffffffffffffffffffffffffffffffffffed
efffffffffffffffffffffffffffffffffffffffffffed
efffffffffffffffffffffffffffffffffffffffffffed
efffffffffffffffffffffffffffffffffffffffffffed
efffffffffffffffffffffffffffffffffffffffffffed
effffffffffffffffffffffffffffffffffffffffffed
effffffffffffffffffffffffffffffffffffffffffed
efffffffffffffffffffffffffffffffffffffffffed
effffffffffffffffffffffffffffffffffffffffed
efffffffffffffffffffffffffffffffffffffffed
effffffffffffffffffffffffffffffffffffffed
deffffffffffffffffffffffffffffffffffffed
defffffffffffffffffffffffffffffffffffed
cdefffffffffffffffffffffffffffffffffed
.cdefffffffffffffffffffffffffffffffed
..cdefffffffffffffffffffffffffffffed
...cdefffffffffffffffffffffffffffed
....cdefffffffffffffffffffffffffed
.....cdefffffffffffffffffffffffed
......cdefffffffffffffffffffffed
.......cddefffffffffffffffffed
.........cddeffffffffffffed
...........cddeffffffffed
.............cddeffffed
................cdded
""")

RELEASE=p(1,3,"""
..........................de
.........................defe
........................deffe
.......................deffe
......................deffe
.....................deffe
.....................defe
......................de

..........de.....................cd
.........defe...................cde
........deffe..................cdefe
.......deffe..................cdefe
......deffe..................cdefe
......defe....................defe
.......de......................de


........................................de
.......................................defe
......................................deffe
.....................................deffe
....................................deffe
...................................deffe
.....de.............................defe
....defe.............................de
...deffe
..deffe
.deffe
.defe...............de
..de...............defe
..................deffe
.................deffffe
................deffffffe
...............deffffffffe
..............deffffffffffe
.............deffffffffffffe
............deffffffffffffffe
...........deffffffffffffffed
..........defffffffffffffed
.........deffffffffffffed
........defffffffffffed
.......deffffffffffed
......defffffffffed
.....defffffffed
.....defffffed
......defffed
.......deffed
........deed
.........dd
""")
