"""Two separately drawn branched strikes, exposed briefly over residue."""
def p(x,y,rows):return {'x':x,'y':y,'rows':rows.strip('\n').splitlines()}
PAL={'a':'#202c6c','b':'#3d64b9','c':'#79bdea','d':'#d3f2fc',
     'e':'#bc8132','f':'#ffd45b','g':'#fff0aa','h':'#ffffff'}

GUIDE=p(14,0,"""
.............bc
............bcd
............cd
...........cd
..........cd
.........cd
........cd
.......cd
......cd
.....cd
....cd
...cd
..cd
.cd
bcd
bc
.bc
..bc
...bc
....bc
.....bc
......bc
.......bc
........bc
.........bc
..........bc
...........bc
............bc
...........bc
..........bc
.........bc
........bc
.......bc
......bc
.....bc
....bc
...bc
..bc
.bc
bc
bc
.bc
..bc
...bc
....bc
.....bc
......bc
.......bc
........bc
.........bc
..........bc
...........bc
............bc
.............bc
..............bc
""")

STRIKE=p(2,0,"""
.............................bcdhhhgf
............................bcddhhhgfe
...........................bcddhhhhgfe
..........................bcddhhhhhgfe
..........................bcdhhhhhhgfe
.........................bcdhhhhhgfe
........................bcddhhhhgfe
.......................bcddhhhggfe
......................bcddhhhggfe
.....................bcddhhhgfe
....................bcddhhhhgfe
...................bcddhhhhhgfe
..................bcddhhhhgfe
.................bcddhhhgfe
.........c......bcddhhhgfe
........cd.....bcddhhhggfe
.......cdh....bcddhhhgfe
......cdhg...bcddhhhhgfe
.....cdhg...bcddhhhggfe
....cdhg...bcddhhhgfe
...cdhg...bcddhhhgfe
..cdhg...bcddhhhhgfe
.cdhg...bcddhhhhhgfe
cdhg...bcddhhhhhggfe
dhg....bcddhhhhhhhhgfe
hg......bcddhhhhhhhhgfe
g........bcddhhhhhhhhgfe
..........bcddhhhhhhhhgfe
...........bcddhhhhhhhhgfe
............bcddhhhhhhhggfe
.............bcddhhhhhhhggfe
..............bcddhhhhhhgfe.............bc
...............bcddhhhhhggfe...........bcde
................bcddhhhhhggfe.........bcdeff
.................bcddhhhhhhgfe.......bcdeffg
..................bcddhhhhhgfe.....bcdeffgh
...................bcddhhhhhgfe...bcdeffghh
....................bcddhhhhggfe.bcdeffghh
.....................bcddhhhhhgffghhhh
......................bcddhhhhhhhhg
.....................bcddhhhhhhhggfe
....................bcddhhhhhhggfe
...................bcddhhhhhggfe
..................bcddhhhhggfe
.................bcddhhhggfe
................bcddhhhgfe
...............bcddhhhgfe
..............bcddhhhgfe
.............bcddhhhggfe
............bcddhhhhgfe
...........bcddhhhhhggfe
..........bcddhhhhhhhhgfe
.........bcddhhhhhhhhhhgfe
........bcddhhhhhhhhhhhhgfe
.......bcddhhhhhhhhhhhhhhgfe
.......bcddhhhhhhhhhhhhhhhgfe
........bcddhhhhhhhhhhhhhhgfe
.........bcddhhhhhhhhhhhhhggfe
..........bcddhhhhhhhhhhhhggfe
...........bcddhhhhhhhhhhhhgfe
""")

SECOND=p(3,0,"""
.............efghhddcb
..............efghhddcb
...............efghhddcb
................efghhddcb
.................efghhhddcb
..................efghhhddcb
...................efghhhddcb
....................efghhhhddcb
.....................efghhhhddcb
......................efghhhhddcb
.......................efghhhhddcb
......................efghhhhhddcb
.....................efghhhhhddcb
....................efghhhhhddcb
...................efghhhhhddcb
..................efghhhhhddcb
.................efghhhhhddcb
................efghhhhhddcb
...............efghhhhhddcb
..............efghhhhhhddcb
.............efghhhhhhddcb
............efghhhhhhddcb
...........efghhhhhhddcb
..........efghhhhhhddcb
.........efghhhhhhddcb
........efghhhhhhddcb............cd
.......efghhhhhhddcb............cdh
......efghhhhhhddcb............cdhg
.....efghhhhhhddcb............cdhg
....efghhhhhhddcb............cdhg
...efghhhhhhhddcb..........cdhg
..efghhhhhhhhddcb........cdhg
.efghhhhhhhhhddcb......cdhg
efghhhhhhhhhhddcb....cdhg
efghhhhhhhhhhddcb..cdhg
.efghhhhhhhhhddcbdhhg
..efghhhhhhhhhhhhhhgg
...efghhhhhhhhhhhggfe
....efghhhhhhhhhggfe
.....efghhhhhhhggfe
......efghhhhhggfe
.......efghhhhggfe
........efghhhhggfe
.........efghhhhggfe
..........efghhhhggfe
...........efghhhhggfe
............efghhhhggfe
.............efghhhhggfe
..............efghhhhggfe
...............efghhhhggfe
................efghhhhggfe
.................efghhhhggfe
..................efghhhhggfe
...................efghhhhggfe
....................efghhhhggfe
.....................efghhhhggfe
......................efghhhhggfe
.......................efghhhhhggfe
........................efghhhhhhggfe
.........................efghhhhhhggfe
""")

RESIDUE=p(10,3,"""
.......................bc
......................bcd
.....................bc
....................bc
...................bc

................bc
...............bcd
..............bc

...........bc
..........bcd
.........bc
........bc
.......bc

........bc
.........bcd
..........bc
...........bc

..............bc
...............bcd
................bc

.................bc
................bc
...............bcd
..............bc

...........bc
..........bc
.........bcd
........bc
.......bc

........bc
.........bcd
..........bc
...........bc
""")

SPLASH=p(9,42,"""
...bc.............................ef
....cd...........................fgh
.....dh........................ghg
......hg......................ghg
.......hg....................ghg
........hg..........dh......ghg
.........hg........dhh.....ghg
..........hg......dhhh....ghg
...........hg....dhhhh...ghg
............hg..dhhhhh.ghg
..........cddhhddhhhhhhghg
......bcddhhhhhhhhhhhhhhhgfe
...bcddhhhhhhhhhhhhhhhhhhhhhggfe
bcddhhhhhhhhhhhhhhhhhhhhhhhhhggfe
.bcddddddddddddhhhhhhggggggggfffe
....bbbbccdddddcdhhhggggggfffe
...........bbcdhcdhgfe
............bcd..cdhgf
.............bc...cdhgfe
""")

def sequence():
 return 64,PAL,'allTargets',[
  ('전류 유도',40,[GUIDE]),('첫 낙뢰',60,[STRIKE,SPLASH]),
  ('잔전류',40,[RESIDUE]),('두 번째 낙뢰',60,[SECOND,SPLASH]),
  ('전류 소멸',60,[RESIDUE]),('바닥 방전',80,[SPLASH]),('소멸',60,[])]
