# 빙하기 설원 필드 조각 메타(굽는 스크립트가 읽는다). brows = 막히는 아랫줄 수.
# 키 큰 부드러운 물체(나무·표지·세락·엄니)는 밑동 1줄만, 단단한 몸통(천막·바위·뼈)은 몸통 줄, 칸 전체 막힘은 그림 높이.
D = dict
META = {
 # ---- 앵커: 빙벽
 'glacier_cave': D(kind='walk', role='building', brows=0, ko='빙벽 얼음 굴 입구',
   desc='빙벽 앞면에 뚫린 둥근 아치 얼음 굴(4x5): 두껍게 깎인 얼음 테, 아치 위 눈 처마와 고드름, 깊어질수록 짙푸른 안쪽과 바닥 가까이 푸른 빛, 문턱의 눈, 발치에 떨어진 얼음 덩이.',
   rules='빙벽 앞면 5줄 자리에 딱 맞춰 얹는다(바깥 투명, 앞면이 비친다). 앞면 칸은 막힘 그대로, 맨 아랫줄 가운데 두 칸만 걷기·동굴 이동 이벤트. 그 앞 땅 한 줄은 비우고 눈길로 잇는다.'),
 'frozen_beast': D(kind='decal', role='prop', brows=0, ko='얼음에 갇힌 거대 짐승',
   desc='빙벽 앞면 속에 비치는 털짐승 그림자(6x3): 굽은 등혹·늘어진 코·휜 엄니·네 다리 윤곽만 짙푸르고 둘레 얼음은 맑게 밝다. 얼굴 없음, 반투명.',
   rules='빙벽 앞면(face_icewall) 위에만 얹는 장식(앞면 칸은 원래 막힘). 앞면 가운데 높이, 처마와 발치 눈 더미를 가리지 않게. 한 지도에 하나.'),
 'icefall': D(kind='object', role='water', brows=1, ko='얼어붙은 폭포',
   desc='빙벽 꼭대기에서 흘러내리다 언 폭포(2x6): 둥근 얼음 입술, 굵기가 다른 얼음 줄기, 발치에 부푼 얼음 둔덕.',
   rules='빙벽 앞면 위에 밑이 앞면 맨 아랫줄 바로 아래 땅 한 줄에 닿게 얹는다. 맨 아랫줄(얼음 둔덕) 2칸 막힘, 위는 앞면이라 원래 막힘. 앞면이 5줄이 아니면 그림 높이를 맞춘다.'),
 'face_icewall': D(kind='wall', role='wall', brows=0, ko='빙벽 앞면',
   desc='눈 덮인 빙하 윗면 1줄 + 빙벽 앞면 5줄 + 발치 눈 1줄 표본(3x7): 세락 덩이 세로 결(왼 밝은 모·오른 그늘), 가로 나이테 띠, 흙 띠, 턱 위 눈, 눈 처마와 고드름, 발치 눈 더미.',
   rules='빙하 가장자리 남쪽에 앞면 4~6줄로 길게 잇는다. 앞면 칸 전부 막힘(굴 입구 칸만 걷기). 처마 높이는 6칸 이상 이어서 바꾸고, 밑줄은 고르게. 발치 남쪽 땅 한 줄에 푸른 그림자.'),
 # ---- 앵커: 호수
 'ice_bridge': D(kind='walk', role='terrain', brows=0, ko='얼음 다리',
   desc='물길 위로 두껍게 언 천연 얼음판(3x5): 호수 얼음 결 윗면, 가장자리 눈 띠와 밀려 솟은 얼음 조각, 동쪽 물 위 그림자.',
   rules='걷기. 동서로 흐르는 물길(autotile 물길 3줄) 위에 세로로, 북·남 끝이 얼음판 한 줄씩 얹히게. 다리 끝 앞 칸은 눈길로 잇는다. 물길이 더 넓으면 다리 가운데 줄을 이어 붙인다.'),
 'ice_floe': D(kind='object', role='water', brows=2, ko='큰 유빙',
   desc='물길에 뜬 들쭉날쭉한 얼음판(3x2): 눈가루 윗면, 앞면 두께, 물 테.', rules='물 칸 위에만(막힘 그대로). 물길 폭 안에 두세 칸 간격으로 드문드문, 다리 바로 옆은 피한다.'),
 'ice_floe_s': D(kind='object', role='water', brows=1, ko='작은 유빙',
   desc='물에 뜬 작은 얼음 조각(2x1).', rules='물 칸 위에만. 큰 유빙 사이사이, 좌우 뒤집기 섞기.'),
 'pressure_ridge': D(kind='object', role='prop', brows=1, ko='압력 얼음 둑',
   desc='언 호수 얼음판이 밀려 솟아 기운 얼음 덩이 무리(3x2), 밑동 눈 번짐.', rules='호수 얼음 위에. 밑줄 3칸 막힘, 위 걷기+가림. 물길 가까이 2~4개, 길 위 금지.'),
 'ice_crack': D(kind='decal', role='decal', brows=0, ko='얼음판 균열',
   desc='언 호수 위 갈라진 금(2x1): 어두운 틈, 밝은 턱, 낀 눈가루, 갈래.', rules='걷는 장식. 호수 얼음 위, 물길 가까이 덩이로. 일렬 금지.'),
 'frozen_reeds': D(kind='decal', role='decal', brows=0, ko='얼음에 갇힌 갈대',
   desc='호숫가 얼음판을 뚫고 나온 마른 갈대(1칸), 밑동 얼음 고리.', rules='걷는 장식. 호수 얼음 가장자리 1~2칸 안에 드문드문.'),
 # ---- 앵커: 뼈
 'mammoth_ribs': D(kind='object', role='prop', brows=1, ko='거대 짐승 갈비뼈',
   desc='반쯤 눈에 묻힌 등뼈와 휜 갈비 일곱 쌍(5x3), 먼 쪽 갈비는 어둡다, 밑동 눈 더미.', rules='밑줄 5칸 막힘, 위는 걷기+가림. 들판 볼거리로 하나, 곁에 머리뼈·엄니·뼈 조각 덩이.'),
 'mammoth_skull': D(kind='object', role='prop', brows=1, ko='거대 짐승 머리뼈',
   desc='눈에 반쯤 묻힌 둥근 머리뼈와 앞으로 뻗어 위로 휜 굵은 엄니 한 쌍(3x2), 정수리에 눈.', rules='밑줄 3칸 막힘. 갈비뼈 곁, 좌우 뒤집어 섞기.'),
 'tusk_arch': D(kind='walk', role='building', brows=1, ko='엄니 문',
   desc='거대 엄니 둘이 서로 휘어 꼭대기에서 가죽 끈으로 묶인 문(3x3), 뼈 장식, 밑동 눈 더미.',
   rules='야영지 입구 길 위에. 맨 아랫줄 양끝 2칸만 막힘, 가운데 칸은 길(지나간다). 위 칸 걷기+가림.'),
 'tusk_single': D(kind='object', role='prop', brows=1, ko='박힌 엄니',
   desc='눈에 박혀 휘어 선 거대 엄니 하나(1x2).', rules='밑동 1칸 막힘, 위 걷기+가림. 뼈 벌판·야영지 둘레에 2~4개 흩어, 일렬 금지.'),
 'bone_scatter': D(kind='decal', role='decal', brows=0, ko='흩어진 뼈',
   desc='눈에 반쯤 묻힌 짧은 뼈와 관절(1칸).', rules='걷는 장식. 갈비뼈·머리뼈 둘레 3~6칸에 덩이로.'),
 # ---- 얼음·바위·눈
 'ice_shards': D(kind='object', role='prop', brows=1, ko='얼음 결정 무리',
   desc='눈 위로 솟은 크기 다른 푸른 얼음 뾰족돌 다섯(2x2).', rules='밑줄 2칸 막힘, 위 걷기+가림. 빙벽 밑·빙하 윗면·뼈 벌판에 2~3개 덩이.'),
 'serac': D(kind='object', role='prop', brows=1, ko='빙하 세락',
   desc='결정처럼 깎인 얼음 봉우리 셋(2x3): 왼 면 밝음·능선 흰 줄·오른 면 그늘, 턱마다 눈, 금.', rules='밑줄 2칸 막힘, 위 걷기+가림. 빙벽 밑 물가와 빙하 윗면에 드문드문, 얼음 결정 무리와 섞는다.'),
 'rock_rimed': D(kind='object', role='prop', brows=1, ko='서리 앉은 바위',
   desc='두꺼운 눈 모자를 쓴 회색 바위(2x2), 바람 쪽 상고대, 앞 턱 고드름.', rules='밑줄 2칸 막힘. 들판·물가에 1~3개 덩이, 버들항 눈 바위(snowrock)와 섞는다.'),
 'rocks_snowy': D(kind='decal', role='decal', brows=0, ko='눈 덮인 잔돌', desc='눈 모자 쓴 잔돌 셋(1칸).', rules='걷는 장식. 바위 곁·길가에 드문드문.'),
 'drift_big': D(kind='object', role='prop', brows=1, ko='큰 눈 둔덕',
   desc='바람에 깎인 둥근 눈 더미(3x2), 말려 내려온 처마 능선, 앞면 푸른 그늘.', rules='밑줄 3칸 막힘, 위 걷기+가림. 빙벽 밑·바위 곁·숲가에 하나씩, 길 위 금지.'),
 'drift_small': D(kind='decal', role='decal', brows=0, ko='작은 눈 둔덕', desc='낮은 눈 더미(2x1).', rules='걷는 장식. 들판 빈 곳에 2~3개 덩이.'),
 'snow_den': D(kind='walk', role='building', brows=1, ko='설동',
   desc='큰 눈 언덕 앞에 판 굴 입구(3x2): 어두운 아치 구멍, 다진 눈 문턱, 처마 눈과 고드름.',
   rules='숲 속 빈터에. 맨 아랫줄 양끝 2칸 막힘, 가운데 칸(굴 입구)만 걷기·이동 이벤트. 앞 칸은 눈길로 잇는다.'),
 # ---- 야영지
 'fur_tent_cone': D(kind='object', role='building', brows=1, ko='원뿔 가죽 천막',
   desc='엇갈려 솟은 장대, 꿰맨 가죽 판, 걷어 올린 문 자락과 어두운 문, 털 밑단, 치마에 쌓인 눈(3x3).',
   rules='몸 아랫줄 3칸 막힘, 위 걷기+가림. 문 앞 칸(가운데 아래)에 이벤트, 비운다. 야영지 다진 눈 둘레에 모닥불을 향해 2~3채, 좌우 뒤집기 섞기.'),
 'fur_tent_dome': D(kind='object', role='building', brows=1, ko='털가죽 둥근 움막',
   desc='큰 뼈 갈빗대 틀 위 덧댄 가죽·털 판(판마다 톤이 다르다), 정수리 눈, 털 휘장 문, 밑동 돌(3x3).', rules='아랫줄 3칸 막힘. 야영지에 한 채, 원뿔 천막과 섞는다.'),
 'hide_windbreak': D(kind='object', role='prop', brows=1, ko='가죽 바람막이',
   desc='비스듬히 박은 말뚝 넷에 이어 맨 가죽 판(3x2), 처진 윗단, 앞 밑동 눈.', rules='아랫줄 3칸 막힘. 모닥불 북서쪽(바람 쪽)에 두르듯.'),
 'campfire_snow': D(kind='object', role='prop', brows=1, ko='눈밭 모닥불',
   desc='녹아 드러난 흙 둘레 돌 테, 엇갈린 장작, 불(1칸).', rules='칸 막힘. 야영지 가운데 하나, 둘레 4방향은 비워 둔다(사람이 둘러앉는 자리).'),
 'cook_tripod': D(kind='object', role='prop', brows=1, ko='요리 삼각대', desc='장대 셋에 매단 솥과 숯불(1x2).', rules='밑동 1칸 막힘, 위 걷기+가림. 모닥불 곁 한 칸.'),
 'hide_rack_fur': D(kind='object', role='prop', brows=1, ko='털가죽 말림틀', desc='기둥 둘·가로대에 끈으로 당겨 맨 털가죽(2x2), 가로대 위 눈.', rules='아랫줄 2칸 막힘. 천막 곁.'),
 'fur_pile': D(kind='object', role='prop', brows=1, ko='털가죽 더미', desc='접어 쌓은 털가죽 셋(1칸).', rules='칸 막힘. 천막 문 곁·썰매 곁.'),
 'sled_loaded': D(kind='object', role='prop', brows=1, ko='짐 썰매', desc='뼈 활주부 위 가죽 짐 셋을 묶은 썰매(2x1).', rules='칸 막힘. 야영지 가장자리·길 끝.'),
 'firewood_snow': D(kind='object', role='prop', brows=1, ko='눈 쌓인 장작', desc='쪼갠 장작 다섯과 윗면 눈(1칸).', rules='칸 막힘. 천막·모닥불 곁에 1~2개.'),
 'supply_bundles': D(kind='object', role='prop', brows=1, ko='보급 짐', desc='가죽 보따리 둘·질항아리·바구니(2x1).', rules='칸 막힘. 천막 곁.'),
 # ---- 표지
 'marker_fallen': D(kind='object', role='prop', brows=1, ko='쓰러진 표지',
   desc='눈 폭풍에 밑동이 부러져 넘어진 새김 장대(3x1): 고리 띠·마름모 새김, 해진 천, 서쪽 그루터기, 위에 쌓인 눈.', rules='칸 막힘. 길가 한 칸 떨어져 길과 나란히, 곁에 부러진 밑동(marker_stub).'),
 'marker_standing': D(kind='object', role='prop', brows=1, ko='새김 표지',
   desc='고리 띠 장대 꼭대기 짐승 뿔 장식, 바람에 날리는 천 셋, 밑동 돌무더기(1x3).', rules='밑동 1칸 막힘, 위 걷기+가림. 길 곁 갈림·물가·입구에 하나씩.'),
 'marker_stub': D(kind='object', role='prop', brows=1, ko='부러진 표지 밑동', desc='꺾여 남은 짧은 장대와 눈 더미(1칸).', rules='칸 막힘. 쓰러진 표지 서쪽 끝 곁.'),
 # ---- 나무
 'fir_laden': D(kind='tree', role='tree', brows=1, ko='눈에 짓눌린 전나무',
   desc='단마다 두툼한 눈 베개가 얹혀 가지가 처진 전나무(2x3), 줄기는 밑변 폭.', rules='줄기 1칸만 막힘, 위 걷기+가림. 버들항 눈 전나무(fir_snow_*)와 섞어 숲 덩이로. 일렬 금지.'),
 'fir_buried': D(kind='object', role='tree', brows=1, ko='눈에 묻힌 어린 전나무', desc='큰 눈 더미 위로 꼭대기 두 단만 솟은 전나무(2x2).', rules='밑줄 2칸 막힘. 숲 가장자리·눈 둔덕 곁에 드문드문.'),
 'frost_snag': D(kind='tree', role='tree', brows=1, ko='상고대 고사목', desc='잎 없는 줄기·꺾인 가지, 바람 쪽마다 흰 서리 깃(2x3).', rules='줄기 1칸만 막힘, 위 걷기+가림. 들판·뼈 벌판에 1~3그루.'),
 # ---- 작은 장식
 'frozen_grass': D(kind='decal', role='decal', brows=0, ko='서리 맞은 마른 풀', desc='눈 위로 솟은 가는 풀잎 묶음(1칸).', rules='걷는 장식. 들판·바위 곁 덩이로.'),
 'tracks_beast': D(kind='decal', role='decal', brows=0, ko='짐승 발자국', desc='큰 네 발 짐승 발자국 줄(2x1).', rules='걷는 장식. 들판·야영지 가장자리에 사선으로 하나씩.'),
 # ---- 바닥·오토타일
 'ground-snow': D(kind='floor', role='terrain', brows=0, layer='lower', ko='눈 바닥',
   desc='쌓인 눈(3x3): 칩셋 모래흙 결을 옮긴 옅은 그늘 점, 바람에 깎인 짧은 능선, 바람 물결, 잔 얼음 점.', rules='걷기. 필드 기본 땅. 넓게 깔고 둔덕·풀·바위로 끊는다.'),
 'ground-ice': D(kind='floor', role='terrain', brows=0, layer='lower', ko='언 호수 얼음',
   desc='얼음 7단(3x3): 판 균열, 짧은 사선 반짝, 갇힌 기포.', rules='걷기. 호수 속. 가장자리는 autotile-iceedge, 물길은 따로.'),
 'ground-glacier': D(kind='floor', role='terrain', brows=0, layer='lower', ko='빙하 윗면',
   desc='눈 덮인 빙하(3x3): 드러난 푸른 얼음, 짧은 크레바스.', rules='빙벽 위 배경(대개 막힘). 세락·얼음 결정을 드문드문.'),
 'ground-packed': D(kind='floor', role='terrain', brows=0, layer='lower', ko='다진 눈',
   desc='야영지 둘레 다져진 눈(3x3), 엇갈린 발자국.', rules='걷기. 야영지 가운데 둥근 덩이로(가장자리는 흔든다).'),
 'autotile-iceedge': D(kind='autotile', role='terrain', brows=0, layer='lower', ko='얼음 ↔ 눈 가장자리',
   desc='언 호수 얼음판을 눈 위에 덧그린다: 변형마다 위상이 다른 굽이진 물가(만·곶, 둥근 바깥 모서리, 오목 모서리에서도 윤곽이 대각으로 이어짐), 북쪽 둑 눈 언덕 앞면, 서쪽 둑 짙은 윤곽, 남쪽 밝은 얼음 턱, 물가 얕은 띠(밝음 → 속으로 녹음), 물가 판 균열, 속은 깊은 얼음 잔물결·반짝(7단).',
   rules='걷기. 호수 칸 전부(속 칸 포함)를 이 붓 하나로 칠한다 — 바닥 얼음(ground-ice)을 사각형으로 먼저 깔지 않는다. 호수 칸 덩이는 불규칙하게(줄마다 길이·시작이 다르게, 곶·만을 두 칸 이상), 사각형 채우기 금지. 넓은 호수 속에는 ice_crack·pressure_ridge·ice_floe 물체를 띄엄띄엄 얹어 큰 판 균열을 낸다. 물길(얼음 틈 물)은 가운데에 따로, 다리로 건넌다.'),
 'autotile-trail': D(kind='autotile', role='terrain', brows=0, layer='lower', ko='눈길 발자국',
   desc='밟아 다진 눈길: 북쪽 안벽 그늘·남쪽 안벽 밝음의 눈 둑, 발자국 쌍, 밖으로 튄 눈.', rules='걷기. 폭 2칸, 한 칸씩 굽게. 얼음판 위로도 이어 그린다.'),
 'autotile-drift': D(kind='autotile', role='terrain', brows=0, layer='lower', ko='눈 번짐 더미',
   desc='바람에 쌓인 눈이 땅·얼음 위로 번진 판: 속은 눈 결, 북·서 밝은 테, 남·동 그늘, 밖으로 흩어진 눈 점.', rules='걷기. 호숫가·빙벽 밑·들판에 3~12칸 덩이로. 외톨이 칸은 쓰지 않는다.'),
 # ================================================================ 보정 패스(웨이브 5): 빙벽 앞면 변형
 'face_icewall_icicles': D(kind='wall', role='wall', brows=0, ko='빙벽 앞면 — 고드름 발',
   desc='빙벽 앞면 변형 표본(4x7): 무게로 처진 처마 눈 아래 가운데가 긴 고드름 발(굵은 것은 3px·그림자), 고드름 밑 녹아 언 물줄기 결, 발치에 떨어진 고드름 조각.',
   rules='빙벽 앞면(face_icewall)을 길게 이을 때 4~8칸 구간에 섞는다. 앞면 칸 전부 막힘. 같은 변형을 바로 옆에 잇지 말고 기본 앞면·다른 변형과 번갈아, 굴 입구·언 폭포 칸은 피한다.'),
 'face_icewall_crack': D(kind='wall', role='wall', brows=0, ko='빙벽 앞면 — 큰 균열',
   desc='빙벽 앞면 변형 표본(4x7): 처마가 V 로 끊긴 자리에서 아래로 가늘어지는 갈지자 큰 균열(속 짙푸름·오른 속벽 밝음), 곁 금, 틈에 낀 눈, 발치 얼음 부스러기.',
   rules='빙벽 앞면 3~4칸 구간에 하나. 앞면 칸 전부 막힘(지나가는 틈 아님). 한 줄 빙벽에 둘 이하, 고드름 발·눈 얹힘 사이에.'),
 'face_icewall_snowload': D(kind='wall', role='wall', brows=0, ko='빙벽 앞면 — 눈 얹힘',
   desc='빙벽 앞면 변형 표본(4x7): 처마 위로 두껍게 얹혀 둥글게 처진 눈 처마와 그 밑 그늘, 앞면으로 흘러내린 눈 줄, 턱에 얹힌 짧은 눈 혹, 발치를 덮은 큰 눈 더미.',
   rules='빙벽 앞면 끝자락이나 바람 쪽 5~8칸 구간에. 앞면 칸 전부 막힘. 발치 눈 더미가 앞면 아랫줄을 덮으므로 그 앞 땅 한 줄은 비워 둔다.'),
 'face_icewall_rubble': D(kind='wall', role='wall', brows=0, ko='빙벽 앞면 — 무너진 처마',
   desc='빙벽 앞면 변형 표본(4x7): 가운데 처마가 떨어져 나가 모나게 내려앉은 자리(빙하 윗면 눈 + 깨진 맑은 얼음 턱), 발치에 쌓인 모난 얼음 덩이(윗면 눈가루·앞면·오른 그늘).',
   rules='빙벽 앞면 5~7칸 구간에 하나. 앞면 칸 막힘, 발치 덩이가 걸친 앞 땅 한 줄도 막거나 비워 둔다(덩이 위로 걷지 않게). 굴 입구 곁은 피한다.'),
 # ================================================================ 보정 패스: 눈밭 소품
 'rock_heads': D(kind='decal', role='decal', brows=0, ko='눈 밖 바위 머리',
   desc='눈 밖으로 머리만 내민 모난 바위 셋(2x1): 윗면 눈, 앞면 회색 돌, 밑동은 눈 더미에 묻혔고 동쪽에 바람 오목 그늘.', rules='걷는 장식. 트인 눈밭에 2~4개 덩이로, 바위 턱·서리 바위 곁에. 일렬 금지.'),
 'rock_outcrop': D(kind='object', role='prop', brows=1, ko='눈벌판 바위 턱',
   desc='눈벌판을 뚫고 층져 솟은 모난 바위 판 다섯(3x2): 판마다 윗면 눈, 앞면 돌 결·세로 금, 왼쪽 서리 깃, 동쪽 바람 오목, 밑동 눈 더미.',
   rules='밑줄 3칸 막힘, 위 걷기+가림. 넓은 눈밭 한가운데 볼거리로 1~2개, 곁에 바위 머리·마른 풀. 길 위 금지.'),
 'frozen_bush': D(kind='object', role='prop', brows=1, ko='얼어붙은 덤불',
   desc='잔가지 덤불이 얼음에 덮였다(2x2): 가지 왼쪽마다 흰 상고대, 끝에 맺힌 얼음 방울, 가지 사이 걸린 눈 뭉치, 밑동 눈 더미.',
   rules='밑줄 2칸 막힘, 위 걷기+가림. 호숫가·숲가·연못가에 2~3개 덩이로, 좌우 뒤집기 섞기.'),
 'snowshoe_trail': D(kind='decal', role='decal', brows=0, ko='설피 발자국',
   desc='사람이 신은 둥근 눈신 자국 여섯이 좌우 엇갈려 사선으로 이어진 줄(3x1): 오목 안 윗벽 그늘·아랫벽 밝음, 눈신 격자 흔적.',
   rules='걷는 장식. 야영지·길에서 연못·사냥터로 가는 트인 눈밭에 2~4개를 이어 한 줄기 발길로. 짐승 발자국(tracks_beast)과 섞지 않는다.'),
 'ice_pillar': D(kind='tree', role='prop', brows=1, ko='얼음 기둥',
   desc='땅에서 솟은 반투명한 굵은 얼음 기둥(1x3): 깎인 면(왼 밝음·가운데 흰 결·오른 그늘), 갇힌 기포, 가로 금, 꼭대기 눈 모자, 밑동 얼음 둔덕.',
   rules='밑동 1칸만 막힘, 위 걷기+가림. 빙벽 밑·얼음 구덩이 둘레에 2~4개 덩이(키 다르게 보이도록 앞뒤로 엇갈려).'),
 'mammoth_skeleton': D(kind='object', role='prop', brows=1, ko='선 채로 언 매머드 뼈대',
   desc='선 채로 얼어 남은 거대 짐승 뼈대(5x4): 등혹 위로 굽은 등뼈와 가시 돌기, 늘어진 갈비, 네 다리뼈, 골반, 앞으로 숙인 머리뼈와 크게 휜 엄니 한 쌍, 뼈 위 눈, 발치 눈 더미.',
   rules='밑줄 5칸 막힘, 위 걷기+가림. 넓은 눈벌판의 랜드마크로 지도에 하나, 둘레 3칸은 비우고 눈 둔덕·바위 머리로 받친다. 누운 갈비뼈(mammoth_ribs)와는 떨어뜨린다.'),
 'cairn_spear': D(kind='object', role='prop', brows=1, ko='돌무지와 꽂힌 창',
   desc='납작한 돌 다섯을 쌓은 사냥꾼 돌무지와 기울여 꽂은 나무 창(돌 촉·가죽 끈), 돌마다 윗면 눈(1x2).',
   rules='밑동 1칸 막힘, 위 걷기+가림. 연못·사냥터 들머리·길 갈림에 하나씩(표지 역할).'),
 'ice_fishing_hole': D(kind='object', role='prop', brows=1, ko='얼음 낚시 구멍',
   desc='언 연못·호수 얼음에 뚫은 둥근 구멍(1칸): 짙은 찬 물과 살얼음 턱, 깨내 쌓은 얼음 조각 테, 곁에 꽂은 낚싯대 막대와 늘어진 줄.',
   rules='칸 막힘(빠지는 구멍). 언 연못(autotile-frozenpond) 속 칸이나 호수 얼음 위에만 1~2개, 둘레 칸은 걷게 비운다.'),
 # ================================================================ 보정 패스: 시그니처 땅 덩이 오토타일
 'autotile-frozenpond': D(kind='autotile', role='terrain', brows=0, layer='lower', passable=True, ko='두껍게 언 연못',
   desc='눈 위에 따로 선 작은 연못이 두껍게 얼었다: 눈 기슭 둑(북쪽 둑 안 비탈 그늘·남쪽 둑 마루 밝음·동쪽 밝음·서쪽 그늘), 젖빛 두꺼운 얼음(잔 눈가루 결·서리꽃·옅은 금), 북·서 둑 그림자.',
   rules='걷기(두꺼운 얼음, 미끄럼 없음). 눈 바닥 위에 붓으로 4~20칸 불규칙 덩이로 칠한다(사각형 채우기 금지, 2칸 폭 이상 — 1칸 폭 꺾임은 안쪽 모서리가 뾰족해진다). 큰 호수 채우기는 autotile-iceedge, 이것은 따로 선 연못. 낚시 구멍·돌무지·덤불을 곁에.'),
 'autotile-snowridge': D(kind='autotile', role='terrain', brows=0, layer='lower', passable=True, ko='큰 눈 둔덕 능선',
   desc='바람에 쌓여 솟은 큰 눈 둔덕: 윗면은 바탕보다 밝은 눈과 바람 능선, 남쪽 가장자리에 5px 앞면(처마 마루·그늘), 동쪽 비탈 그늘, 남·동 밖에 옅은 그림자.',
   rules='걷기. 트인 눈밭에 6~30칸 길쭉하고 불규칙한 덩이(바람 방향 동서로 길게)로 칠한다. 눈 번짐(autotile-drift)과 겹치지 않게, 길·호수·연못 위 금지. 위에 물체를 놓지 않는다.'),
 'autotile-icepit': D(kind='autotile', role='terrain', brows=0, layer='lower', passable=False, ko='얼음 구덩이 균열',
   desc='눈벌판이 꺼진 얼음 구덩이·크레바스: 눈 입술 테, 북쪽 안벽(빙하 결 앞면·고드름), 짙푸른 바닥 모를 틈, 테에서 눈 위로 뻗은 잔 균열.',
   rules='모든 변형 막힘. 빙벽 밑·눈벌판에 2~12칸 길쭉한 덩이(크레바스는 동서로 긴 2칸 폭)로 칠한다. 길·다리 끝에서 2칸 이상 떨어뜨리고, 둘레에 얼음 기둥·얼음 결정을 둔다. 고립 칸이 생기지 않게 통로를 남긴다.'),
}

