16 48
a wood 1
b wood 6
c wood 3
d wood 4
e wood 2
f wood 5
g wood 7
i iron 3
j iron 5
k iron 1
---
................
................
................
................
................
................
................
................
................
affffffffffffffa
aggbbgggggbgggga
acccceccccecccca
aaaaaaaaaaaaaaaa
......agda......
......agda......
......agda......
......afda......
......agda......
......agca......
......agda......
......abda......
......agda......
......agda......
......agda......
......acea......
......aeaa......
......agda......
......afda......
......agda......
......abda......
......agda......
......agda......
......agca......
......agda......
......agda......
......agda......
......agda......
......agda......
......afda......
......agca......
......agda......
......agda......
......agda......
......agda......
......agda......
......agda......
......agca......
......abda......
