16 48
a wood 1
b wood 6
c wood 3
d wood 4
e wood 2
f wood 5
g wood 7
i iron 3
j iron 5
k iron 1
---
................
................
................
................
................
................
................
................
................
affffffffffffffa
aggjbgggggbgjgga
acckcecccceckcca
aaaaaaaaaaaaaaaa
......agda~~....
......agda~.....
......agda~.....
......afda~.....
......agda~.....
......agca~.....
......akka~.....
......kiik~.....
......ajia~.....
......agda~.....
......agda~.....
......agda~.....
......agca~.....
......agda~.....
......afda~.....
......agda~.....
......ajka~.....
......agda~.....
......agda~.....
......agca~.....
......agda~.....
......agda~.....
......agda~.....
......agda~.....
......akka~.....
......kiik~.....
......ajia~.....
......agda~.....
......agda~.....
......agda~.....
......agda~.....
......agda~.....
......agda~.....
......agca~.....
......abda~.....
