import { chromium } from "playwright";
const b = await chromium.launch({ headless: true, args: ["--disable-dev-shm-usage"] });
const page = await b.newPage({ viewport: { width: 1600, height: 900 } });
await page.addInitScript(() => { localStorage.setItem("oprn:standard-welcome-seen", "1"); localStorage.setItem("oprn:ai-panel-collapsed", "1"); });
await page.goto("http://127.0.0.1:9863/?freshProject=1", { waitUntil: "domcontentloaded" });
await page.getByTestId("edit-canvas").waitFor({ timeout: 90000 });
await page.waitForTimeout(3000);
await page.evaluate(() => window.__oprnEditorStore.update((d) => { d.maps[d.startMapId].tilesetId = "beodeul_city"; }));
await page.waitForSelector("[data-testid^='chipset-tile-']", { timeout: 60000 });
await page.waitForTimeout(15000);
const c = await page.context().newCDPSession(page);
await c.send("Profiler.enable"); await c.send("Profiler.setSamplingInterval", { interval: 200 });
await c.send("Profiler.start");
await page.evaluate(async () => { const sheet=document.querySelector("[data-testid='tile-palette']"); sheet.scrollTop=0; await new Promise(r=>setTimeout(r,300)); await new Promise((resolve)=>{const start=performance.now(); const step=()=>{sheet.scrollTop+=0; if(performance.now()-start<1500) requestAnimationFrame(step); else resolve();}; requestAnimationFrame(step);}); });
const _t=1;
const { profile } = await c.send("Profiler.stop");
const dt=profile.timeDeltas; const nodes=new Map(profile.nodes.map(n=>[n.id,n])); const parent=new Map(); for(const n of profile.nodes) for(const c of (n.children||[])) parent.set(c,n.id);
const self=new Map(); profile.samples.forEach((id,i)=>{const n=nodes.get(id); const k=n.callFrame.functionName+' '+n.callFrame.url.split('/').slice(-1)[0].slice(0,30)+':'+n.callFrame.lineNumber; self.set(k,(self.get(k)??0)+dt[i]/1000);}); console.log('SELF\n'+[...self].sort((a,b)=>b[1]-a[1]).slice(0,14).map(([k,v])=>v.toFixed(0)+'ms '+k).join('\n'));
const incl=new Map(); 
profile.samples.forEach((id,i)=>{ const seen=new Set(); let cur=id; while(cur!==undefined){ const n=nodes.get(cur); const k=n.callFrame.functionName+" "+n.callFrame.url.split("/").slice(-1)[0].slice(0,30)+":"+n.callFrame.lineNumber; if(!seen.has(k)){seen.add(k); incl.set(k,(incl.get(k)??0)+dt[i]/1000);} cur=parent.get(cur);} });
console.log([...incl].filter(([k])=>/\.(ts|tsx):/.test(k)).sort((a,b)=>b[1]-a[1]).slice(0,25).map(([k,v])=>v.toFixed(0)+"ms "+k).join("\n"));
await b.close();
