# 화산 지대 필드 조각 메타(굽는 스크립트가 읽는다). 이름 → (만드는 함수 경로, 메타).
# brows = 막히는 아랫줄 수. 키 큰 부드러운 물체는 1, 단단한 몸통은 1~2, 칸 전체 막힘은 그림 높이.
META = {
 # ---- 앵커
 'crater_mountain': dict(kind='object', role='prop', brows=12, ko='분화구 산',
   desc='멀리 솟은 화산(18x12): 등고선 따라 휜 현무암·응회암·재 지층, 위에서 갈라지는 골, 붉게 빛나는 분화구와 앞쪽 테두리 틈에서 흘러내린 용암 줄기, 튀는 불씨.',
   rules='지도 맨 위(북쪽) 고원 가운데에 하나만. 덮인 칸 전부 막힘(산). 위에 smoke_column 을 분화구 가운데에 맞춰 얹는다. 앞 밑동 가운데 6칸은 비어 있어 temple_gate 를 붙인다. 주변은 고원 재 땅·용암 흐름판으로 잇는다.'),
 'smoke_column': dict(kind='decal', role='prop', brows=0, ko='화산 연기 기둥',
   desc='분화구 위로 피어오르는 연기 뭉치(4x4), 밑동이 분화구 빛을 받아 붉다.',
   rules='위층 장식(걷기+가림). crater_mountain 분화구 바로 위에만 얹는다. 지도 위 가장자리에서 잘리지 않게 산을 4칸 이상 내려 놓는다.'),
 'temple_gate': dict(kind='object', role='building', brows=4, ko='화산 신전 입구',
   desc='산 밑동을 깎아 세운 현무암 신전 문(6x5): 윗면 보이는 들보와 응회암 띠·불꽃 원반 새김, 붉은 머리돌 네모 기둥 둘, 붉은 빛 새는 깊은 문간, 앞 돌계단 세 단. 양옆은 거친 바위로 산에 이어진다.',
   rules='crater_mountain 앞 밑동 가운데에 붙인다(그림 윗 2줄이 산 밑동을 덮는다). 위 4줄 막힘, 넷째 줄 가운데 칸(문)만 걷기·이동 이벤트, 맨 아랫줄 계단은 걷기. 앞에 판석 앞뜰(ground-basaltflag) 1~2줄과 화로·수호 석상 한 쌍.'),
 'temple_brazier': dict(kind='object', role='prop', brows=1, ko='신전 화로',
   desc='네모 받침 위 현무암 기둥과 쇠 대야, 활활 타는 불(1x2).', rules='밑동 1칸 막힘, 위 칸 걷기+가림. 신전 문 계단 양옆에 한 쌍으로(좌우 대칭). 길 가운데 금지.'),
 'fire_guardian': dict(kind='object', role='prop', brows=1, ko='화염 수호 석상',
   desc='마름돌 받침 위 두건 쓴 사제상이 불 그릇을 가슴에 받쳐 든 석상(2x3, 얼굴은 두건 그늘).',
   rules='받침 줄(맨 아래 2칸) 막힘, 위 2줄 걷기+가림. 신전 문 바깥 양옆에 좌우를 뒤집어 한 쌍. 혼자 들판에 세우지 않는다.'),
 'cave_mouth': dict(kind='walk', role='building', brows=0, ko='화산 동굴 입구',
   desc='절벽 앞면에 뚫린 거친 아치 굴(3x3): 안은 어둡고 바닥에서 붉은 열기가 샌다, 둘레는 모난 현무암 덩이.',
   rules='절벽 앞면 세 줄 자리에 딱 맞춰 얹는다(바깥 투명, 앞면이 비친다). 앞면 칸은 막힘 그대로, 아랫줄 가운데 칸만 걷기·동굴 이동 이벤트. 그 앞 땅 한 칸은 비운다.'),
 'basalt_bridge': dict(kind='walk', role='terrain', brows=0, ko='현무암 다리',
   desc='용암 강을 남북으로 건너는 마름돌 판석 다리(3x6), 양옆 낮은 난간 돌, 용암에 박힌 육각 교각 머리, 동쪽에 비친 그림자.',
   rules='걷기. 동서로 흐르는 용암 강 위에 세로로, 북·남 끝이 땅 한 줄씩 얹히게(용암 4줄까지). 강이 더 넓으면 가운데 판석 줄을 이어 붙인다. 다리 끝 앞 칸은 길로 잇는다.'),
 'basalt_step': dict(kind='walk', role='terrain', brows=0, ko='현무암 징검돌',
   desc='용암에서 솟은 육각 기둥 머리(1칸), 밑동이 붉게 달아올랐다.',
   rules='걷기. 폭 2~3줄 용암 위에 상하좌우로 이어지게 3~5개 지그재그(대각선만으로 이으면 못 건넌다). 양 끝은 둑에 닿게.'),
 'stairs_basalt': dict(kind='walk', role='terrain', brows=0, ko='절벽 돌계단',
   desc='절벽 앞면 세 줄을 깎아 낸 현무암 돌계단(3x3), 양옆 낮은 옆벽.',
   rules='걷기. 고원 가장자리 앞면 세 줄 자리에만, 위 끝은 고원 땅, 아래 끝은 낮은 땅 길에 잇는다. 폭 3~4칸.'),
 'lava_fall': dict(kind='liquid', role='water', brows=3, ko='용암 폭포',
   desc='절벽 앞면 꼭대기에서 넘친 용암이 세 줄 높이로 떨어져 발치에서 튄다(2x3).',
   rules='절벽 앞면 세 줄 위에 얹는다(막힘). 발치 아래 칸부터 용암 칸(autotile-lava)을 이어 강으로 흘린다.'),
 'lava_pool': dict(kind='liquid', role='water', brows=2, ko='작은 용암 웅덩이',
   desc='현무암 물가 안에서 끓는 둥근 용암 웅덩이(3x2), 껍질 균열·거품.',
   rules='칸 전체 막힘. 재 평원에 하나씩, 둘레에 흑요석·화산탄·불씨를 덩이로. 길 바로 옆은 피한다.'),
 # ---- 바위·흑요석
 'basalt_columns': dict(kind='object', role='prop', brows=1, ko='현무암 주상절리',
   desc='높이가 다른 육각 기둥 다섯이 선 무리(2x3), 윗면에 재.', rules='밑줄 2칸 막힘, 위는 걷기+가림. 고원·평원 가장자리에 2~4개 덩이(좌우 뒤집기 섞기). 일렬 금지.'),
 'basalt_columns_low': dict(kind='object', role='prop', brows=1, ko='낮은 주상절리',
   desc='무릎 높이 육각 기둥 그루터기 무리(2x2).', rules='밑줄 2칸 막힘. 큰 주상절리 곁·용암 물가에 섞어 놓는다.'),
 'basalt_boulder': dict(kind='object', role='prop', brows=1, ko='현무암 큰 바위',
   desc='모난 큰 바위, 기공 구멍, 윗면에 앉은 재(2x2).', rules='밑줄 2칸 막힘, 윗줄 걷기+가림. 덩이로 1~3개, 길 위 금지.'),
 'lava_bomb': dict(kind='object', role='prop', brows=1, ko='화산탄',
   desc='굴러 떨어진 둥근 바위, 갈라진 틈이 아직 붉다(1칸).', rules='1칸 막힘. 분화구·용암 웅덩이 둘레에 드문드문 2~4개.'),
 'obsidian_spire': dict(kind='object', role='prop', brows=1, ko='흑요석 뾰족돌',
   desc='유리처럼 빛나는 검보라 흑요석 바늘 셋(1x2).', rules='밑동 1칸 막힘, 위 칸 걷기+가림. 용암 물가·웅덩이 둘레에 2~3개 덩이.'),
 'obsidian_cluster': dict(kind='object', role='prop', brows=1, ko='흑요석 무리',
   desc='높이가 다른 흑요석 바늘 다섯 무리(2x2).', rules='밑줄 2칸 막힘. 흑요석 뾰족돌과 섞어 노두를 만든다.'),
 # ---- 그을린 나무
 'charred_tree_a': dict(kind='tree', role='tree', brows=1, ko='그을린 마른 나무',
   desc='잎 없이 타 버린 줄기와 꺾인 가지, 가지 윗면에 재, 껍질 틈의 불씨(2x3).', rules='줄기 가운데 1칸만 막힘, 가지는 걷기+가림. 3~8그루 덩이(그을린 숲), 좌우 뒤집기 섞기. 길 위 금지.'),
 'charred_tree_b': dict(kind='tree', role='tree', brows=1, ko='그을린 고목',
   desc='굵은 줄기가 갈라진 채 선 큰 고목, 드러난 뿌리(3x4).', rules='줄기 가운데 1칸만 막힘. 그을린 숲 가운데에 한두 그루.'),
 'charred_snag': dict(kind='tree', role='tree', brows=1, ko='부러진 그을린 줄기',
   desc='위가 꺾여 날카롭게 남은 밑동(1x2), 잘린 면에 불씨.', rules='밑동 1칸 막힘. 숲 가장자리·폐허 곁에 드문드문.'),
 'charred_log': dict(kind='object', role='prop', brows=1, ko='쓰러진 그을린 통나무',
   desc='숯이 된 통나무, 잘린 끝 나이테가 붉다(2x1).', rules='2칸 막힘. 숲 안에 한두 개. 여러 개를 나란히 줄 세우지 않는다.'),
 'charred_stump': dict(kind='object', role='prop', brows=1, ko='그을린 그루터기',
   desc='윗면 나이테가 붉게 탄 그루터기(1칸).', rules='1칸 막힘. 숲 가장자리에 드문드문.'),
 # ---- 유황·김
 'sulfur_vent': dict(kind='object', role='prop', brows=1, ko='유황 구멍',
   desc='노란 유황 딱지가 둘린 땅 구멍, 김이 조금 샌다(1칸).', rules='1칸 막힘. 분기공 벌판(붉은 자갈 땅)에 큰 분기공과 섞어 3~6개.'),
 'sulfur_vent_big': dict(kind='object', role='prop', brows=1, ko='큰 분기공',
   desc='유황이 굳은 낮은 둔덕 꼭대기 구멍에서 김이 뿜어 오른다(2x2).', rules='둔덕 줄(밑 2칸) 막힘, 김은 걷기+가림. 붉은 자갈 땅 가운데에 3~5개, 서로 3칸 이상.'),
 'steam_wisp': dict(kind='decal', role='prop', brows=0, ko='피어오르는 김',
   desc='반투명 가는 김 뭉치(1x2).', rules='위층 장식(걷기+가림). 유황 구멍·땅 틈 바로 위 칸에 얹는다.'),
 'sulfur_crystals': dict(kind='decal', role='decal', brows=0, ko='유황 결정',
   desc='노란 바늘 결정 무리(1칸).', rules='걷는 장식. 분기공 둘레 2칸 안에 흩는다.'),
 'fumarole_crack': dict(kind='decal', role='decal', brows=0, ko='달아오른 땅 틈',
   desc='재 땅이 갈라져 붉은 빛이 비친다(1칸).', rules='걷는 장식(피해는 이벤트). 분기공 벌판·용암 곁에 드문드문, 길 위 금지.'),
 'ember_scatter': dict(kind='decal', role='decal', brows=0, ko='흩어진 불씨',
   desc='재 위 붉은 숯 알갱이(1칸).', rules='걷는 장식. 용암·화로·웅덩이 둘레 3칸 안에만.'),
 'cooled_lava': dict(kind='decal', role='decal', brows=0, ko='식은 용암 껍질',
   desc='물가에 굳은 작은 용암 혀(2x2): 모난 현무암 덩이, 틈 일부가 붉다, 앞 끝은 어두운 턱.', rules='걷는 장식. 용암 강 물가 1~3칸에 드문드문. 넓은 벌판은 ground-lavafield 로.'),
 'ash_mound': dict(kind='decal', role='decal', brows=0, ko='재 둔덕',
   desc='바람에 쌓인 고운 재 더미(2x1).', rules='걷는 장식(낮다). 고운 재 둔덕 땅 가장자리·바위 곁.'),
 'basalt_rocks': dict(kind='decal', role='decal', brows=0, ko='잔 현무암 돌',
   desc='작은 돌 서너 개(1칸).', rules='걷는 장식. 바위·주상절리 둘레와 길가에 흩는다(일렬 금지).'),
 'pumice_scatter': dict(kind='decal', role='decal', brows=0, ko='부석 조각',
   desc='밝고 구멍 숭숭한 가벼운 돌(1칸).', rules='걷는 장식. 고운 재 둔덕 위에 드문드문.'),
 'burnt_grass': dict(kind='decal', role='decal', brows=0, ko='타다 남은 마른 풀',
   desc='끝이 검게 탄 마른 풀 포기(1칸).', rules='걷는 장식. 그을린 숲 밑·재 둔덕 가장자리에 덩이로.'),
 # ---- 뼈·표지
 'beast_ribs': dict(kind='object', role='prop', brows=1, ko='거대 짐승 갈비뼈',
   desc='재에 반쯤 묻힌 등뼈와 하늘로 휜 갈비뼈들(4x3).', rules='밑줄 4칸 막힘, 위는 걷기+가림. 평원 길 곁 볼거리로 하나, 곁에 beast_skull.'),
 'beast_skull': dict(kind='object', role='prop', brows=1, ko='짐승 머리뼈',
   desc='옆으로 누운 긴 머리뼈, 이빨 난 주둥이와 뒤로 휜 뿔(2x2).', rules='밑줄 2칸 막힘. 갈비뼈 머리 쪽 한 칸 옆에.'),
 'pilgrim_cairn': dict(kind='object', role='prop', brows=1, ko='순례 돌무더기',
   desc='현무암 돌을 쌓고 붉은 천을 맨 막대를 꽂은 길 표지(1x2).', rules='밑동 1칸 막힘. 길 굽이·입구·갈림길 곁에 하나씩(길 위 금지, 5칸 이상 간격).'),
 # ---- 바닥·벽
 'ground-ash': dict(kind='floor', role='terrain', brows=0, layer='lower', ko='화산재 땅',
   desc='칩셋 점박이 흙 결을 어두운 회흑 재로(3x3 표본, 이음새 없음).', rules='화산 필드 기본 바닥. 용암 곁은 한 단 어둡게(그을림).'),
 'ground-fineash': dict(kind='floor', role='terrain', brows=0, layer='lower', ko='고운 재 둔덕',
   desc='밝은 고운 재와 가로로 휜 바람 물결(3x3 표본).', rules='재 땅 위 덩이로(네모 금지, 가장자리 흔들기). 부석·마른 풀과 섞는다.'),
 'ground-lavafield': dict(kind='floor', role='terrain', brows=0, layer='lower', ko='식은 용암 벌판',
   desc='모난 현무암 덩이, 틈 일부가 붉은 아아 용암(3x3 표본).', rules='걷기. 용암 강·산 밑동에서 혀 모양으로 흘러나온 판(폭 3~6칸). 판 둘레 북·서는 밝은 턱, 남쪽 끝은 어두운 앞면 2px.'),
 'ground-basaltflag': dict(kind='floor', role='terrain', brows=0, layer='lower', ko='현무암 판석',
   desc='버들항 성 마름돌 결의 현무암 판석, 틈에 재(3x3 표본).', rules='신전 앞뜰·다리 머리 같은 사람 손 닿은 자리. 가장자리 1px 어두운 테.'),
 'face_basalt': dict(kind='wall', role='wall', brows=0, ko='현무암 절벽 앞면',
   desc='고원 가장자리 앞면 세 줄(3칸 폭 표본): 버들항 절벽 갈빗대 결 + 출렁이는 응회암 띠 + 재층, 위는 재 턱.',
   rules='높이 차 남쪽 가장자리마다 앞면 3줄(막힘). 한두 칸씩 들쭉날쭉하게 꺾고, 계단(stairs_basalt)·동굴(cave_mouth)·폭포(lava_fall)는 이 자리에 얹는다.'),
 # ---- 오토타일
 'autotile-lava': dict(kind='autotile', role='terrain', brows=1, layer='lower', ko='용암 ↔ 재 가장자리',
   desc='현무암 덩이 물가(바깥 모서리 둥글게)와 밝은 띠·껍질 균열·거품 점의 흐르는 용암 16변형(위1·오른2·아래4·왼8).',
   rules='모든 변형 막힘. 강은 폭 3줄 이상, 한두 칸씩 굽이치게. 다리(basalt_bridge)·징검돌(basalt_step)은 위에 얹는다. 둘레에 autotile-heat.'),
 'autotile-heat': dict(kind='autotile', role='decal', brows=0, layer='upper', ko='열기 번짐',
   desc='땅 위에 덧그리는 투명 붉은 체커 디더 + 불티 점, 가장자리로 갈수록 옅어진다(16변형).',
   rules='걷기. 용암·웅덩이·분기공 둘레 1~3칸 땅에 칠한다. 고원 위·신전 안에는 칠하지 않는다.'),
 'autotile-ashpath': dict(kind='autotile', role='terrain', brows=0, layer='lower', ko='재 오솔길',
   desc='밟아 다진 밝은 고운 재 길, 가장자리에 부석·붉은 자갈 테(16변형, 투명 덧그림).',
   rules='걷기. 폭 2칸으로 굽이치게(곧은 줄 길게 금지). 다리·계단 끝 칸은 이웃으로 쳐서 잇는다.'),
}
