# w60: v5 바구니 물건 화소를 mushroom w9-B 몸통(림 y7~y14, 접지 그림자) 위에 앉혀 w60-A.pxg 를 만든다.
import json, re, os, subprocess, sys
from PIL import Image
C = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')
C = os.path.abspath(C)
STRAW1 = (97, 76, 26, 255)
CLEAN = {(4, 8): STRAW1, (5, 8): STRAW1, (10, 8): STRAW1, (11, 8): STRAW1,
         (4, 9): (202, 176, 101, 255), (5, 9): (176, 144, 64, 255),
         (10, 9): (202, 176, 101, 255), (11, 9): (176, 144, 64, 255)}
ref = Image.open(f'{C}/basket_mushroom/v5.png').convert('RGBA')
for p, c in CLEAN.items(): ref.putpixel(p, c)
MBLK = """................
................
................
................
................
................
................
..cccccccccccc..
..cccccccccccc..
..cccccccccccc..
..ccccccccccc...
..ccccccccccc...
..ccccccccccc...
...ccccccccc....
...cccccccccc...
................"""
TBLK = """................
................
................
................
................
................
................
..655555555543..
..122222222220..
..145345343240..
..15345343242...
..13453432422...
..14534332422...
...153432422....
...1111111100...
................"""
SHADOW = """................
................
................
................
................
................
................
................
................
................
................
................
................
................
.............~-.
.........-~~~~~-"""
def letters(slug):
    m = {}
    for l in open(f'{C}/{slug}/palette.pal'):
        mm = re.match(r'^(\S)\s+#([0-9a-fA-F]{6})\b', l)
        if mm and mm.group(1) not in '.~-#_':
            h = mm.group(2); m[(int(h[0:2],16), int(h[2:4],16), int(h[4:6],16), 255)] = mm.group(1)
    return m
def compose(slug, out):
    im = Image.open(f'{C}/{slug}/v5.png').convert('RGBA'); lm = letters(slug)
    rows = []
    for y in range(16):
        r = ''
        for x in range(16):
            p = im.getpixel((x, y))
            if p[3] == 0: r += '.'; continue
            content = y <= 6 or (7 <= y <= 14 and p != ref.getpixel((x, y)))
            if y == 7: content = False
            r += lm[p] if content else '.'
        rows.append(r)
    txt = f"// {slug} w60-A — 몸통 = basket:mushroom w9-B(림·짜임·접지 그림자), 물건 = 이 기물의 v5 화소 그대로(basket_mushroom/work/w60-compose.py)\n@size 16 16\n@cell 16\n@palette palette.pal\n@mat c straw 3\n@block 0 0\n{SHADOW}\n@mblock 0 0\n{MBLK}\n@tblock 0 0\n{TBLK}\n@block 0 0\n" + '\n'.join(rows) + '\n'
    open(out, 'w').write(txt)
if __name__ == '__main__':
    todo = json.load(open(f'{C}/../variant-bodies.json'))['basket']['todo']
    for t in todo:
        s = t.replace(':', '_').replace('+', '_')
        compose(s, f'{C}/{s}/w60-A.pxg')
        print(s)
