import type { TerminologyEntry } from "./terminologyTypes";

/**
 * Event authoring and database record vocabulary. Same rule as the other entry
 * files: every `ko` value is observed, and no existing string is changed here.
 */
export const TERMINOLOGY_ENTRIES_AUTHORING = [
  // ── Event authoring ────────────────────────────────────────────────────────
  {
    key: "event.event",
    ko: "이벤트",
    en: "event",
    area: "EventAuthoring",
    partOfSpeech: "noun",
    surface: "both",
    note: "The authored object placed on the event layer. The layer is map.layerEvent; one instruction inside it is event.command.",
    sources: ["src/editor/panels/helpModal.ts", "src/project/types/events.ts"],
  },
  {
    key: "event.eventEditor",
    ko: "이벤트 편집기",
    en: "event editor",
    area: "EventAuthoring",
    partOfSpeech: "noun",
    surface: "editor",
    sources: ["src/editor/panels/helpModal.ts"],
  },
  {
    key: "event.page",
    ko: "페이지",
    en: "page",
    area: "EventAuthoring",
    partOfSpeech: "noun",
    surface: "editor",
    note: "One conditional branch of an event, not a tab and not a screen — the last page whose condition holds is the one that runs.",
    rejectedEnAliases: ["tab", "sheet"],
    sources: ["src/editor/panels/eventEditor/pageProps.ts", "src/editor/panels/helpModal.ts"],
  },
  {
    key: "event.command",
    ko: "명령",
    en: "command",
    area: "EventAuthoring",
    partOfSpeech: "noun",
    surface: "editor",
    note: "One instruction inside a page. Distinct from shell.commandPalette entries and from db.battleCommands.",
    sources: ["src/editor/panels/eventEditor/commandSummary.ts", "src/editor/panels/eventEditor/content.ts"],
  },
  {
    key: "event.condition",
    ko: "조건",
    en: "condition",
    area: "EventAuthoring",
    partOfSpeech: "property",
    surface: "editor",
    note: "The page-level test deciding whether a page is active.",
    sources: ["src/editor/panels/eventEditor/pageProps.ts", "src/editor/panels/eventEditor/commandBodyCore.ts"],
  },
  {
    key: "event.graphic",
    ko: "그래픽",
    en: "graphic",
    area: "EventAuthoring",
    partOfSpeech: "property",
    surface: "editor",
    note: "An event's appearance (character sprite or face). The underlying file is a resource.resource.",
    sources: ["src/editor/panels/eventEditor/previewMoveRoute.ts", "src/editor/panels/helpModal.ts"],
  },
  {
    key: "event.moveRoute",
    ko: "이동 경로",
    en: "move route",
    area: "EventAuthoring",
    partOfSpeech: "noun",
    surface: "both",
    sources: ["src/editor/panels/eventEditor/moveRouteDialog.ts", "src/editor/panels/eventEditor/eventEditorHelp.ts"],
  },
  {
    key: "event.commonEvent",
    ko: "공용 이벤트",
    en: "common event",
    area: "EventAuthoring",
    partOfSpeech: "noun",
    surface: "both",
    note: "A project-wide event not bound to a map cell.",
    sources: ["src/editor/panels/database.ts"],
  },
  {
    key: "event.switch",
    ko: "스위치",
    en: "switch",
    area: "EventAuthoring",
    partOfSpeech: "noun",
    surface: "both",
    note: "A named boolean of game state; not a UI toggle control.",
    rejectedEnAliases: ["toggle"],
    sources: ["src/editor/panels/database.ts"],
  },
  {
    key: "event.variable",
    ko: "변수",
    en: "variable",
    area: "EventAuthoring",
    partOfSpeech: "noun",
    surface: "both",
    note: "A named number of game state; never a source-code variable.",
    sources: ["src/editor/panels/database.ts"],
  },
  {
    key: "event.npc",
    ko: "NPC",
    en: "NPC",
    area: "EventAuthoring",
    partOfSpeech: "noun",
    surface: "both",
    note: "Left untranslated in both languages; the assistant's Korean label for creating one is 사람 만들기.",
    sources: ["src/editor/panels/helpModal.ts"],
  },
  {
    key: "event.shop",
    ko: "상점",
    en: "shop",
    area: "EventAuthoring",
    partOfSpeech: "noun",
    surface: "both",
    sources: ["src/editor/panels/helpModal.ts", "src/editor/panels/eventEditor/shopEditorModel.ts"],
  },
  {
    key: "event.inn",
    ko: "여관",
    en: "inn",
    area: "EventAuthoring",
    partOfSpeech: "noun",
    surface: "both",
    sources: ["src/editor/panels/helpModal.ts", "src/editor/panels/eventEditor/commandBodyCommerce.ts"],
  },

  // ── Database records ───────────────────────────────────────────────────────
  {
    key: "db.overview",
    ko: "개요",
    en: "overview",
    area: "DatabaseRecords",
    partOfSpeech: "noun",
    surface: "editor",
    sources: ["src/editor/panels/database.ts"],
  },
  {
    key: "db.actor",
    ko: "주인공",
    en: "actor",
    area: "DatabaseRecords",
    partOfSpeech: "noun",
    surface: "both",
    note: "The tab reads 주인공 (\"protagonist\") but the record and the English term are actor; 액터 survives in help prose.",
    acceptedKoAliases: ["액터"],
    rejectedEnAliases: ["hero", "protagonist", "character"],
    sources: ["src/editor/panels/database.ts", "src/project/types/database.ts"],
  },
  {
    key: "db.class",
    ko: "직업",
    en: "class",
    area: "DatabaseRecords",
    partOfSpeech: "noun",
    surface: "both",
    note: "Growth curves and equippable gear. \"job\" is not used; 클래스 is accepted in help prose only.",
    acceptedKoAliases: ["클래스"],
    rejectedEnAliases: ["job", "profession"],
    sources: ["src/editor/panels/database.ts", "src/editor/panels/helpModal.ts"],
  },
  {
    key: "db.skill",
    ko: "스킬",
    en: "skill",
    area: "DatabaseRecords",
    partOfSpeech: "noun",
    surface: "both",
    sources: ["src/editor/panels/database.ts"],
  },
  {
    key: "db.item",
    ko: "아이템·장비",
    en: "items and equipment",
    area: "DatabaseRecords",
    partOfSpeech: "noun",
    surface: "editor",
    note: "One tab holding two record types; singular English is \"item\" and \"equipment\" respectively.",
    sources: ["src/editor/panels/database.ts"],
  },
  {
    key: "db.enemy",
    ko: "전투 몬스터",
    en: "enemy",
    area: "DatabaseRecords",
    partOfSpeech: "noun",
    surface: "both",
    note: "The tab says 전투 몬스터 to hold it apart from db.monsterSpecies; the record and English term are enemy.",
    acceptedKoAliases: ["적"],
    rejectedEnAliases: ["monster"],
    sources: ["src/editor/panels/database.ts", "src/editor/panels/helpModal.ts"],
  },
  {
    key: "db.monsterSpecies",
    ko: "포획·성장 종족",
    en: "monster species",
    area: "DatabaseRecords",
    partOfSpeech: "noun",
    surface: "both",
    note: "Capturable, levelling creatures — a different system from db.enemy battle records.",
    sources: ["src/editor/panels/database.ts"],
  },
  {
    key: "db.troop",
    ko: "적 그룹",
    en: "troop",
    area: "DatabaseRecords",
    partOfSpeech: "noun",
    surface: "both",
    note: "A fixed encounter group of enemies. Never \"party\" — the player side is battle.party.",
    acceptedKoAliases: ["트룹"],
    rejectedEnAliases: ["party", "enemy group"],
    sources: ["src/editor/panels/database.ts", "src/editor/panels/helpModal.ts"],
  },
  {
    key: "db.state",
    ko: "상태",
    en: "state",
    area: "DatabaseRecords",
    partOfSpeech: "noun",
    surface: "both",
    note: "A status condition such as poison or sleep. Not UI state and not a save state.",
    rejectedEnAliases: ["status effect", "condition"],
    sources: ["src/editor/panels/database.ts", "src/project/ontology/databaseStateOntology.ts"],
  },
  {
    key: "db.element",
    ko: "속성",
    en: "element",
    area: "DatabaseRecords",
    partOfSpeech: "property",
    surface: "both",
    note: "Elemental attribute governing damage affinity. This Korean word is taken — \"property\" must render as 설정, see map.mapSettings.",
    rejectedEnAliases: ["attribute", "property"],
    sources: ["src/editor/panels/database.ts", "src/editor/panels/databaseElementsClassic.ts"],
  },
  {
    key: "db.terrainEffect",
    ko: "지형 효과",
    en: "terrain effect",
    area: "DatabaseRecords",
    partOfSpeech: "noun",
    surface: "both",
    note: "Battle-side effect of a terrain tag; the tile-side datum is a terrain tag, not an effect.",
    sources: ["src/editor/panels/database.ts", "src/editor/panels/databaseBattleStudio.ts"],
  },
  {
    key: "db.battleAnimation",
    ko: "전투 애니메이션",
    en: "battle animation",
    area: "DatabaseRecords",
    partOfSpeech: "noun",
    surface: "both",
    note: "Full term keeps it apart from an event graphic's walk animation.",
    shortKo: "애니메이션",
    sources: ["src/editor/panels/database.ts", "src/editor/panels/databaseBattleStudio.ts"],
  },
  {
    key: "db.battleScreen",
    ko: "전투 화면",
    en: "battle screen",
    area: "DatabaseRecords",
    partOfSpeech: "noun",
    surface: "both",
    sources: ["src/editor/panels/database.ts", "src/editor/panels/databaseBattleStudio.ts"],
  },
  {
    key: "db.battleCommands",
    ko: "전투 명령",
    en: "battle commands",
    area: "DatabaseRecords",
    partOfSpeech: "noun",
    surface: "both",
    note: "The in-battle command menu shown to the player; unrelated to event.command.",
    sources: ["src/editor/panels/database.ts", "src/editor/panels/databaseBattleStudio.ts"],
  },
  {
    key: "db.faction",
    ko: "진영",
    en: "faction",
    area: "DatabaseRecords",
    partOfSpeech: "noun",
    surface: "both",
    sources: ["src/editor/panels/database.ts"],
  },
  {
    key: "db.system",
    ko: "시스템",
    en: "system settings",
    area: "DatabaseRecords",
    partOfSpeech: "noun",
    surface: "editor",
    note: "Project-wide game settings tab; English keeps \"settings\" so it is not read as the engine.",
    sources: ["src/editor/panels/database.ts", "src/editor/panels/databaseSystemStudio.ts"],
  },
  {
    key: "db.inGameTerms",
    ko: "용어",
    en: "in-game terms",
    area: "DatabaseRecords",
    partOfSpeech: "noun",
    surface: "both",
    note: "Author-chosen wording for in-game concepts (what their game calls HP or gold) — project content, never product terminology.",
    sources: ["src/editor/panels/database.ts"],
  },
  {
    key: "db.worldCanon",
    ko: "세계 개요",
    en: "world canon",
    area: "DatabaseRecords",
    partOfSpeech: "noun",
    surface: "editor",
    note: "The settled facts of the author's world; the surface that edits it is shell.world.",
    sources: ["src/editor/panels/database.ts"],
  },
  {
    key: "db.worldCodex",
    ko: "설정집",
    en: "world codex",
    area: "DatabaseRecords",
    partOfSpeech: "noun",
    surface: "editor",
    sources: ["src/editor/panels/database.ts"],
  },
  {
    key: "db.conceptBundle",
    ko: "개념 꾸러미",
    en: "concept bundle",
    area: "DatabaseRecords",
    partOfSpeech: "noun",
    surface: "editor",
    note: "Draft room/facility concepts the assistant can build from.",
    sources: ["src/editor/panels/database.ts"],
  },
  {
    key: "db.structureKits",
    ko: "부품 보관함",
    en: "structure kit library",
    area: "DatabaseRecords",
    partOfSpeech: "noun",
    surface: "editor",
    note: "Shelf of map.structureKit entries. English says \"library\" here and for resource.resourceLibrary — always qualify which one.",
    sources: ["src/editor/panels/database.ts"],
  },
  {
    key: "db.characterGraphics",
    ko: "캐릭터·얼굴",
    en: "character and face graphics",
    area: "DatabaseRecords",
    partOfSpeech: "noun",
    surface: "editor",
    sources: ["src/editor/panels/database.ts"],
  },

] as const satisfies readonly TerminologyEntry[];
