import type { TerminologyEntry } from "./terminologyTypes";

/**
 * Battle, resource, assistant, and project vocabulary. Same rule as the other
 * entry files: every `ko` value is observed, and no existing string is changed.
 */
export const TERMINOLOGY_ENTRIES_RUNTIME = [
  // ── Battle runtime ─────────────────────────────────────────────────────────
  {
    key: "battle.battle",
    ko: "전투",
    en: "battle",
    area: "BattleRuntime",
    partOfSpeech: "noun",
    surface: "both",
    note: "One fight. shell.battleTest shortens to the same word in the top bar — keep \"test\" in English.",
    rejectedEnAliases: ["combat", "fight"],
    sources: ["src/editor/panels/helpModal.ts", "src/project/ontology/ontologyClassificationTerms.ts"],
  },
  {
    key: "battle.battler",
    ko: "배틀러",
    en: "battler",
    area: "BattleRuntime",
    partOfSpeech: "noun",
    surface: "runtime",
    note: "A combatant instance in a running battle, on either side; its authored source is db.actor or db.enemy.",
    sources: ["src/player/battleDom.ts", "src/editor/panels/databaseBalanceCompute.ts"],
  },
  {
    key: "battle.party",
    ko: "아군",
    en: "party",
    area: "BattleRuntime",
    partOfSpeech: "noun",
    surface: "runtime",
    note: "The player's side. Never \"troop\" — that is the enemy grouping (db.troop).",
    rejectedEnAliases: ["troop", "allies"],
    sources: ["src/player/battleDirectorDom.ts", "src/player/battleSequencer.ts"],
  },
  {
    key: "battle.turn",
    ko: "턴",
    en: "battle turn",
    area: "BattleRuntime",
    partOfSpeech: "noun",
    surface: "runtime",
    note: "One round of battle order. The same Korean word means an assistant exchange — see assistant.turn.",
    sources: ["src/project/ontology/ontologyClassificationTerms.ts", "src/battle/runtime.ts"],
  },

  // ── Resource pipeline ──────────────────────────────────────────────────────
  {
    key: "resource.resource",
    ko: "소재",
    en: "resource",
    area: "ResourcePipeline",
    partOfSpeech: "noun",
    surface: "editor",
    note: "Image and audio material. 자료 was retired because it collided with the database's short label.",
    acceptedKoAliases: ["리소스"],
    deprecatedKoAliases: ["자료"],
    rejectedEnAliases: ["asset", "material"],
    uiCopyKey: "resources",
    sources: ["src/editor/uiCopy.ts"],
  },
  {
    key: "resource.resourceLibrary",
    ko: "소재 보관함",
    en: "resource library",
    area: "ResourcePipeline",
    partOfSpeech: "noun",
    surface: "editor",
    note: "Where resources are reviewed and replaced. English \"library\" is shared with db.structureKits — always qualify.",
    deprecatedKoAliases: ["자료 보관함"],
    uiCopyKey: "resourceLibrary",
    sources: ["src/editor/uiCopy.ts"],
  },
  {
    key: "resource.audio",
    ko: "음악·효과음",
    en: "music and sound effects",
    area: "ResourcePipeline",
    partOfSpeech: "noun",
    surface: "editor",
    note: "One middle dot, one name. The interpunct separator is part of the approved term.",
    shortKo: "음악",
    shortEn: "Audio",
    uiCopyKey: "audio",
    sources: ["src/editor/uiCopy.ts", "src/editor/panels/helpModal.ts"],
  },
  {
    key: "resource.bgm",
    ko: "BGM",
    en: "BGM",
    area: "ResourcePipeline",
    partOfSpeech: "noun",
    surface: "both",
    note: "Background music track, untranslated in both languages; the event commands are BGM 재생 / play BGM.",
    sources: ["src/editor/panels/helpModal.ts"],
  },
  {
    key: "resource.soundEffect",
    ko: "효과음",
    en: "sound effect",
    area: "ResourcePipeline",
    partOfSpeech: "noun",
    surface: "both",
    shortEn: "SE",
    sources: ["src/editor/panels/helpModal.ts"],
  },
  {
    key: "shell.world",
    ko: "세계관",
    en: "world lore",
    area: "ResourcePipeline",
    partOfSpeech: "noun",
    surface: "editor",
    note: "The world-setting document. Not a world map and not a generated world; 세계 / 월드 were retired as dead values.",
    deprecatedKoAliases: ["세계", "월드"],
    rejectedEnAliases: ["world", "world map"],
    uiCopyKey: "world",
    sources: ["src/editor/uiCopy.ts", "src/editor/panels/helpModal.ts"],
  },

  // ── Assistant and studio ───────────────────────────────────────────────────
  {
    key: "assistant.assistant",
    ko: "조수",
    en: "assistant",
    area: "AssistantStudio",
    partOfSpeech: "noun",
    surface: "editor",
    note: "The in-editor AI collaborator. Not \"agent\" and not \"copilot\" on any user-facing surface.",
    rejectedEnAliases: ["agent", "copilot", "bot"],
    sources: ["src/editor/panels/menu.ts", "src/editor/panels/aiChatPanel.ts"],
  },
  {
    key: "assistant.aiStudio",
    ko: "AI 스튜디오",
    en: "AI Studio",
    area: "AssistantStudio",
    partOfSpeech: "noun",
    surface: "editor",
    note: "The scene-monitor shell holding the assistant. Distinct from the database's record studios (e.g. actor studio).",
    shortKo: "스튜디오",
    sources: ["src/editor/panels/menu.ts", "src/editor/aiStudioMode.ts"],
  },
  {
    key: "assistant.turn",
    ko: "턴",
    en: "assistant turn",
    area: "AssistantStudio",
    partOfSpeech: "noun",
    surface: "editor",
    note: "One request-and-response exchange with the assistant. Same Korean word as battle.turn — English must disambiguate.",
    sources: ["src/editor/panels/aiChatPanel.ts"],
  },
  {
    key: "assistant.task",
    ko: "작업",
    en: "task",
    area: "AssistantStudio",
    partOfSpeech: "noun",
    surface: "editor",
    note: "User-facing word for one assistant tool call; internally it is a tool, and the id is never shown raw.",
    sources: ["src/editor/uiCopy.ts", "src/editor/panels/helpModal.ts"],
  },
  {
    key: "assistant.taskPaintRoad",
    ko: "길 그리기",
    en: "paint road",
    area: "AssistantStudio",
    partOfSpeech: "action",
    surface: "editor",
    assistantToolNames: ["paint_road"],
    sources: ["src/editor/uiCopy.ts"],
  },
  {
    key: "assistant.taskBuildVillage",
    ko: "마을 짓기",
    en: "build village",
    area: "AssistantStudio",
    partOfSpeech: "action",
    surface: "editor",
    note: "Two tool ids share this one label, so English must stay a single term for both.",
    assistantToolNames: ["build_house", "author_village"],
    sources: ["src/editor/uiCopy.ts"],
  },
  {
    key: "assistant.taskPlaceFacility",
    ko: "시설 짓기",
    en: "place facility",
    area: "AssistantStudio",
    partOfSpeech: "action",
    surface: "editor",
    assistantToolNames: ["place_concept"],
    sources: ["src/editor/uiCopy.ts"],
  },
  {
    key: "assistant.taskMakeVillager",
    ko: "사람 만들기",
    en: "make villager",
    area: "AssistantStudio",
    partOfSpeech: "action",
    surface: "editor",
    note: "Creates an NPC event; the Korean label deliberately avoids the initialism.",
    assistantToolNames: ["make_villager"],
    sources: ["src/editor/uiCopy.ts"],
  },
  {
    key: "assistant.taskLint",
    ko: "검사",
    en: "lint check",
    area: "AssistantStudio",
    partOfSpeech: "action",
    surface: "editor",
    note: "Rule audit of the project. English keeps \"lint\" so it is not read as a play test.",
    assistantToolNames: ["run_lint"],
    sources: ["src/editor/uiCopy.ts"],
  },
  {
    key: "assistant.taskPlanWorld",
    ko: "세계 계획",
    en: "plan world",
    area: "AssistantStudio",
    partOfSpeech: "action",
    surface: "editor",
    assistantToolNames: ["plan_world"],
    sources: ["src/editor/uiCopy.ts"],
  },

  // ── Project persistence ────────────────────────────────────────────────────
  {
    key: "project.project",
    ko: "프로젝트",
    en: "project",
    area: "ProjectPersistence",
    partOfSpeech: "noun",
    surface: "editor",
    note: "One authored game. The player-visible artifact is the game, not the project.",
    sources: ["src/editor/panels/helpModal.ts", "src/project/types/project.ts"],
  },
  {
    key: "project.onlineSave",
    ko: "온라인 저장",
    en: "online save",
    area: "ProjectPersistence",
    partOfSpeech: "action",
    surface: "editor",
    note: "Saving the project to the server. Not a runtime save slot.",
    rejectedEnAliases: ["cloud save"],
    uiCopyKey: "onlineSave",
    sources: ["src/editor/uiCopy.ts", "src/editor/panels/helpModal.ts"],
  },
  {
    key: "project.export",
    ko: "내보내기",
    en: "export",
    area: "ProjectPersistence",
    partOfSpeech: "action",
    surface: "editor",
    note: "Writing the project out as a package file.",
    sources: ["src/editor/panels/helpModal.ts", "src/project/package.ts"],
  },
  {
    key: "project.import",
    ko: "가져오기",
    en: "import",
    area: "ProjectPersistence",
    partOfSpeech: "action",
    surface: "editor",
    sources: ["src/editor/panels/helpModal.ts"],
  },
  {
    key: "project.webExport",
    ko: "웹 내보내기",
    en: "web export",
    area: "ProjectPersistence",
    partOfSpeech: "action",
    surface: "editor",
    note: "Publishing a playable build, unlike project.export which produces a re-importable package.",
    sources: ["src/editor/panels/helpModal.ts", "src/project/webExportZip.ts"],
  },
] as const satisfies readonly TerminologyEntry[];
