from pathlib import Path
import json
from PIL import Image
ROOT=Path(__file__).parent
PAL={'O':'#241b2d','R':'#622337','r':'#a32d42','c':'#d64742','s':'#ef7150','p':'#ff9d71','W':'#fff1cd','w':'#e9d5b5','f':'#c5ab95','d':'#967d7c','n':'#5a485d','K':'#131b25','J':'#194b50','j':'#58ac98','G':'#8a5434','g':'#d49b44','Y':'#ffe295','E':'#ffbc87'}
(ROOT/'palette.json').write_text(json.dumps(PAL,indent=2)+'\n')
def canvas(): return [list('.'*96) for _ in range(96)]
def block(a,x,y,rows,opaque=False):
    for dy,row in enumerate(rows.strip('\n').splitlines()):
        for dx,c in enumerate(row):
            if c!='.' or opaque: a[y+dy][x+dx]=c

def save(name,a,action=False):
    path=ROOT/('actions' if action else 'poses')/(name+'.pxgrid')
    path.write_text('\n'.join(''.join(row) for row in a)+'\n')

def render(a,path,scale=1):
    im=Image.new('RGBA',(96,96))
    im.putdata([(0,0,0,0) if c=='.' else tuple(bytes.fromhex(PAL[c][1:]))+(255,) for row in a for c in row])
    if scale!=1: im=im.resize((96*scale,96*scale),Image.Resampling.NEAREST)
    im.save(path)

# Nine separate, individually chosen curved tail planes. Each block is literal.
TAILS=[(34,11,'''
........OO
.......OWWO
.......OWWWO
......OWWWWO
......OWWWWwO
......OWWWwwO
......OWWwwwO
......OWwfffO
......OpwwwsO
.....OpppsssO
.....OpsssscO
.....OpsssccO
.....OssscccO
.....OsscccrO
.....OsscccrO
......OscccrO
......OscccrO
......OscccrO
......OscccrO
.......OcccrO
.......OcccrO
.......OcccrO
.......OcccrO
.......OcccrO
.......OcccrO
......OscccrO
......OscccrO
.....OssccrrO
.....OsccrrO
....OssccrrO
....OsccrrO
...OssccrrO
...OsccrrO
..OssccrrO
..OsccrrO
.OssccrrO
.OssccrrO
OssccrrO
OsccrrO
OsccrrO
OsccrrO
OsccrrO
OssccrrO
.OssccrrO
..OsccrrO
...OccrrO
....OrrO
.....OO
'''),(18,15,'''
.OOO
OWWWO
OWWWWO
OWWWWWO
.OWWWWWO
.OWWWwwwO
..OWwwwwwO
..OWwwwffO
...OwpwwwsO
...OppppssO
....OppsssO
....OpssssO
.....OpssscO
.....OpsssccO
......OpssccO
......OpsscccO
.......OsscccO
.......OsscccrO
........OscccrO
........OscccrO
.........OcccrO
.........OcccrO
.........OcccrO
..........OcccrO
..........OcccrO
..........OcccrO
...........OcccrO
...........OcccrO
...........OcccrO
............OcccrO
............OcccrO
.............OcccrO
.............OcccrO
..............OcccrO
..............OscccrO
...............OscccrO
...............OscccrO
................OsccrrO
................OsccrrO
.................OsccrrO
.................OssccrrO
..................OsccrrO
..................OsccrrO
...................OccrrO
....................OrrO
.....................OO
'''),(46,16,'''
..........OO
.........OWWO
........OWWWO
........OWWWO
.......OWWWWwO
.......OWWWwwO
......OWWWwwwO
......OWWwwwfO
.....OWwwwpsO
.....OppppssO
....OpppssscO
....OpssssccO
....OpsssccrO
...OpsssccrO
...OsssccrrO
...OssccrrO
..OpssccrrO
..OssccrrO
..OssccrrO
..OsccrrO
..OsccrrO
..OsccrrO
..OsccrrO
..OsccrrO
..OsccrrO
..OsccrrO
..OsccrrO
..OsccrrO
..OsccrrO
.OssccrrO
.OssccrrO
.OssccrrO
OsssccrrO
OssccrrO
OsccrrO
OsccrrO
OsccrrO
OsccrrO
OssccrrO
.OssccrrO
..OsccrrO
...OccrrO
....OrrO
.....OO
'''),(7,25,'''
.OOOO
OWWWWOO
OWWWWWWOO
.OWWWWWWWO
..OWWWWWWwO
...OWWWwwwwO
....OWwwwwffO
.....OwppwwwsO
......OppppssO
.......OppsssO
........OpsssO
........OpssscO
.........OsssccO
.........OsscccO
..........OscccrO
..........OscccrO
...........OcccrO
...........OcccrO
............OcccrO
............OcccrO
.............OcccrO
.............OcccrO
..............OcccrO
..............OscccrO
...............OscccrO
...............OscccrO
................OscccrO
................OsccrrO
.................OsccrrO
..................OsccrrO
..................OssccrrO
...................OssccrrO
....................OssccrrO
.....................OsccrrO
......................OsccrrO
.......................OccrrO
........................OrrO
.........................OO
'''),(52,30,'''
...........OO
..........OWWO
.........OWWWO
........OWWWWwO
.......OWWWWwwO
......OWWWwwwfO
.....OWWWwwwfO
.....OWwwwpsO
....OppppssO
...OpppssscO
..OppsssccO
..OpsssccrO
.OpsssccrO
.OsssccrrO
.OssccrrO
OsssccrrO
OssccrrO
OsccrrO
OsccrrO
OsccrrO
OsccrrO
OsccrrO
OsccrrO
OsccrrO
OsccrrO
OsccrrO
OssccrrO
.OssccrrO
..OsccrrO
...OccrrO
....OrrO
.....OO
'''),(3,44,'''
.OOOOO
OWWWWWOO
OWWWWWWWOO
.OWWWWWWWWOO
..OWWWWWwwwwO
...OWWwwwwfffO
....OwwppppsssO
.....OppppsssscO
......OppssssccO
.......OpssscccrO
........OsssccrrO
.........OssccrrO
..........OsccrrO
...........OsccrrO
............OsccrrO
.............OsccrrO
..............OsccrrO
...............OsccrrO
................OsccrrO
.................OsccrrO
..................OsccrrO
...................OssccrrO
....................OssccrrO
.....................OssccrrO
......................OssccrrO
.......................OsccrrO
........................OccrrO
.........................OrrO
..........................OO
'''),(5,62,'''
.OOOOO
OWWWWWOO
OWWWWWWWOO
.OWWWWWwwwOO
..OWWwwwwfffOO
...OwwppppssssOO
....OppppsssscccOO
.....OppsssssccccrOO
......OssssccccccrrrOO
.......OssccccccrrrrrrOO
........OcccccrrrrrrrrrrOO
.........OrrrrrrrrrrrrrrrrOO
..........ORrrrrrrrrrrrrrrrOO
...........ORrrrrrrccccccrrrO
............ORrrrccccccccrrO
.............ORrrccccssssccrO
..............ORrccsssssccrO
...............ORrccssccrrO
................ORrccccrO
.................ORrrrrO
..................ORrrO
...................OOO
'''),(13,72,'''
........................OOOO
......................OssccrO
....................OsssssccrO
..................OssssccccrrO
................OssssccccrrrO
..............OssssscccrrrrO
.OOO.........OssssccccrrrrO
OWWWOO.....OssssscccrrrrO
OWWWWWOO.OppssscccrrrrrO
.OWWWWWwOppssscccrrrrrO
..OWWwwwwpssscccrrrrO
...OwwwwppsscccrrrrO
....OfffssscccrrrrO
.....ORrrccccrrrOO
......ORrrrrrrOO
.......ORrrrOO
........OOOO
'''),(29,73,'''
.............OOO
...........OssccO
.........OssssccrO
.......OppsssccrO
......OppsssccrO
.....OppsssccrO
....OppsssccrO
...OWppssccrO
..OWWWpsccrO
.OWWWWwccrO
OWWWWWwfrO
OWWWWwwfO
.OWWwwfO
..OwwfO
...OOO
''')]

def fan():
    a=canvas()
    for x,y,rows in TAILS: block(a,x,y,rows)
    return a

# Idle anatomy: two asymmetrical ears, long muzzle, deep ruff, barrel and four paws.
IDLE=(25,29,'''
.....................................OO
.....................................OWO
....................................OWwO.........OO
....................................OWWwO.......OWO
...................................OWWwwO......OWwO
...................................OWWfnO.....OWWwO
...................................OWfnRO....OWWfwO
...................................OWnRRO...OWWfRwO
...................................OWnRRO..OWWfnRwO
..................................OWWfROOOOWWfnRwO
..................................OWWwwWWWWWWfnwO
.................................OWWWWWWWWWWWwwwO
................................OWWWWWWWWWWWwwwwO
...............................OWWWWWWWWWWWwwwwfO
..............................OWWWWWWWWWwwwwfffwOO
.............................OWWWWWWWWWWwwnKKgWwwwOO
.............................OWWWWWWWWWwwfOKKJwwWWWWOO
.............................OWWWWWWWwwwwfnOOwwWWWWWWWOO
............................OWWWWWWWwwwwfffwwWWWWWWWWWWKO
............................OWWWWWwwwwwwwwWWWWWWWwwwwnOO
............................OWWWWwwwwwwWWWWWWwwwwnOOOO
...........................OWWWWWwwWWWWWWwwfffOOO
...........................OWWWWWWWWwwwwwwwfnO
..........................OWWWWWWWWWwwwwwwfnO
.........................OWWWWWWWWWwwwwwwfnO
........................OWWWWWWWWWWwwwwwwfnO
.......................OWWWWWWWWWWwwwwwwfndO
......................OWWWWWWWWWWWwwwwfndO
..........OOOOOOOOOOOOWWWWWWWWWWWWwwwwfndO
.......OOWWWWWWWWWWWWWWWWWWWWWWWwwwwfnO
.....OOWWWWWWWWWWWWWWWWWWWWWWWWWwwwfnO
....OWWWWWWWWWWWWWWWWWWWWWWWWWwwwwfnOO
...OWWWWWWWWWWWWWWWWWWWWWWWWWwwwfGYYgGO
..OWWWWWWWWWWWWWWWWWWWWWWWWWwwwfGYgggGO
..OWWWWWWWWWWWWWWWWWWWWWWWwwwwfGgYgGwwO
.OWWWWWWWWWWWWWWWWWWWWWwwwwwwfGgYgGwwwO
.OWWWWWWWWWWWWWWWWWWWwwwwwwffGgYgGwwwO
OWWWWWWWWWWWWWWWWWWWwwwwwwwffGgYgGwwwO
OWWWWWWWWWWWWWWWWWwwwwwwwwwffnGgYgGwwO
OWWWWWWWWWWWWWWwwwwwwwwwwwffnnGgYgGwwO
OWWWWWWWWWWWwwwwwwwwwwwwfffnddGgYgGwwO
OWWWWWWWWwwwwwwwwwwwwwwfffnddOGgYgGwwO
OWWWWWwwwwwwwwwwwwwwwffffnddO.ORgYGwwwO
OWWWwwwwwwwwwwwwwwwffffnnddO..ORjJGOwwO
OWWwwwwwwwwwwwffffffnndddOO...OGjYGOwwO
OWWwwwwwffffffffnnnnndOOO.....OGYgGOwwO
OWWwwwfffffnnnnnnnOOOO........ORccROwwO
OWWwwwfffnddOOOOOO............ORcsROwwO
.OWWwwffnddO...OffdnO.........ORccROwwO
.OWWwwffndO....OffdnO.........ORccROwwO
..OWWwffndO....OffdnO.........ORccROwwO
..OWWwffndO....OffdnO..........ORrROwwO
...OWWwfdO.....OffdnO...........OOOOWwO
...OWWwfdO.....OffdnO...............OWwO
...OWWwfdO....OfffdnO...............OWwO
...OWWwfdO....OfffdnO...............OWwO
...OWWwfdO...OffffdnO...............OWwO
...OWWwfdO...OfffffnO..............OWWwO
...OWWwfdO...OwwfffnO..............OWWwO
...OWWwfdO...OwwfddnO.............OWWWwO
..OWWWwwfdO..OnnnnnnO............OWWWWwO
.OWWWWWWwwO...OOOOOO............OWWWWWWwO
.OWWnWWnwwO.....................OWWnWWnwwO
..OOOOOOOO.......................OOOOOOOO
''')

a=fan(); block(a,*IDLE)
# Far foreleg emerges from lower chest, separately visible beyond near paw.
block(a,69,73,'''
..OffnO
..OffnO
..OffnO
..OffnO
..OffnO
..OffnO
..OffnO
..OffnO
..OffnO
..OfffnO
..OfffnO
..OwwffnO
.OwwwffnO
OwwwwffnO
OwnwnffnO
.OOOOOOO
''')
# Neck seal: broad gold edged jade pendant; tied silk below.
block(a,59,64,'''
..GYYG
.GYggYG
GYgjjgYG
GYjWJjYG
GgjjjJgG
.GgjJgG
..GggG
..RccR
.RcpscR
.RcsscR
.RcscrR
.RccrrR
.RccrrR
.RcrrR
..RRR
''')
# Small shoulder lotus embers, connected to the upper coat.
block(a,47,52,'''
..c
..cs
.cEs.c
.cYpsc
rcYEsc
rcsccr
.rccr
''')
save('idle_a',a)
render(a,ROOT/'progress/idle.png')
render(a,ROOT/'progress/idle-4x.png',4)
# Replace the obscured fifth and ninth tails with separately readable curves.
TAILS[4]=(45,36,'''
..........OO
.........OWWO
........OWWWO
.......OWWWWwO
......OWWWWwwO
.....OWWWwwwfO
....OWWwwwpfO
...OWwppppssO
..OppppssssO
.OpppssssccO
.OpsssscccrO
OssssscccrO
OsssccccrrO
OssccccrrO
OsccccrrO
OsccccrrO
OsccccrrO
OsccccrrO
OssccccrrO
.OssccccrrO
..OssccccrrO
...OssccccrrO
....OscccrrO
.....OrrrrO
......OOOO
''')
TAILS[8]=(36,70,'''
.OOO
OsscrO
OsssccO
OsssssccOO
.OsssssssccOO
..OssssssscccOO
...OssssssccccrOO
....OsssccccccrrrOO
.....OsccccccrrrrrrO
......OccccrrrrrrrcO
.......OrrrrrrrccssO
........OrrrrccssspO
.........OrrccssppwO
..........OccssppwWO
...........OcsppwWWO
............OspwWWWO
.............OWWWWWO
..............OWWWWO
...............OWWO
................OO
''')
BASE=fan(); block(BASE,*IDLE)
block(BASE,65,68,'''
..OwwfnO
..OwwffnO
..OwwffnO
..OwwffnO
..OwwffnO
...OwwffnO
....OwwfnO
.....OffnO
.....OffnO
.....OffnO
.....OffnO
.....OffnO
.....OffnO
.....OffnO
.....OffnO
.....OfffnO
.....OwwffnO
....OwwwffnO
...OwwwwffnO
...OwnwnffnO
....OOOOOOO
''')
SEAL='''
..GYYG
.GYggYG
GYgjjgYG
GYjWJjYG
GgjjjJgG
.GgjJgG
..GggG
..RccR
.RcpscR
.RcsscR
.RcscrR
.RccrrR
.RccrrR
.RcrrR
..RRR
'''
EMBER='''
..c
..cs
.cEs.c
.cYpsc
rcYEsc
rcsccr
.rccr
'''
block(BASE,59,64,SEAL); block(BASE,47,52,EMBER)
# Ruff wisps and shoulder muscle plane, selected rather than outlined bands.
block(BASE,53,53,'''
wWWWWWWww
WWWWWwwwwf
WWWwwwwff
WwwWWWwf
wwWWWWww
wWWWwwff
WWwwwwff
''')
block(BASE,41,64,'''
WWWWWWWWw
WWWWWWWww
WWWwwwwww
wwwwwwwff
wwwffffff
''')
save('idle_a',BASE); render(BASE,ROOT/'progress/idle.png'); render(BASE,ROOT/'progress/idle-4x.png',4)

def copied(a): return [row[:] for row in a]
def patch(a,x,y,rows): block(a,x,y,rows,True)

b=copied(BASE)
patch(b,60,54,'''
WWWWWWwwwfnO..
WWWWWWWwwffnO.
WWWWWWwwwffnO.
WWWWWwwwwffnO.
WWWWwwwwffndO.
WWWwwwwwfndO..
WWwwwwwffndO..
''')
patch(b,38,59,'''
WWWWWWWWWWWWWWWWww
WWWWWWWWWWWWWWWWww
WWWWWWWWWWWWWWWwww
WWWWWWWWWWWWWWwwww
WWWWWWWWWWWWwwwwww
''')
patch(b,61,73,'''
RcspscR
RcsscrR
.RcscrR
.RccrrR
..RcrR.
...RR..
''')
patch(b,41,13,'''
OWWWO.
OWWWWO
OWWWWO
OWWwwO
''')
save('idle_b',b)
c=copied(BASE)
patch(c,55,56,'''
wWWWwwwwwwff
WWWwwwwwwffn
WWWWwwwwffnd
WWWwwwwwfndO
WWwwwwwffndO
''')
patch(c,78,45,'''
fnnKgWwww
fOOKKJwwW
''')
patch(c,61,72,'''
RcpscR.
RcsscR.
RcccrR.
RccrrR.
.RcrrR.
..RRR..
''')
patch(c,29,89,'''
OWWWWwwfdO
OWWWWWwwwO
OWWnWWnwwO
.OOOOOOOO.
''')
save('idle_c',c)

# Gathered fan is a second hand-authored silhouette, used during physical compression.
GATHER=(8,22,'''
.................................OO
................OO..............OWWO
...............OWWO............OWWWO
..............OWWWO...........OWWWwwO
..............OWWWWwO.........OWWwwwO
....OO........OWWWwwO........OWWwwwfO
...OWWO.......OWWwwfO........OwwppssO
..OWWWWO......OwppssO.......OppppssO
..OWWWWwO.....OpppssO.......OpssssccO
...OWWWWwO....OpssssO.......OssscccrO
....OWWwwwO...OpssssO.......OsscccrrO
.....OWwwwfO..OpsssccO......OscccrrO
......OwppssO.OpsssccO.....OssccrrO
.......OppsssOOpsssccO.....OsccrrO
........OpssssOpsssccO.....OsccrrO
.........OsssssssssccO....OssccrrO
..........OssssssscccO....OsccrrO
.OOO.......OsssssscccO....OsccrrO
OWWWOO......OssssscccO...OssccrrO
OWWWWWO......OsssscccO...OsccrrO
.OWWWWWO......OssscccO..OssccrrO
..OWWWwwO......OsscccO..OsccrrO
...OWwwffO......OscccrOOssccrrO
....OwpPssO......OscccrOssccrrO
.....OppsssO......OscccccccrrO
......OpssssO......OsccccccrrO
.......OssssccO....OsccccccrrO
........OssscccO...OsccccccrrO
.........OssccccO..OscccccrrO
..........OsccccrO.OssccccrrO
...........OscccrrOOssccccrrO
............OscccrrOssccccrrO
.OOO.........OscccrrssccccrrO
OWWWOO........OsccccssccccrrO
OWWWWwO........OscccccccccrrO
.OWWwwwO........OsccccccccrrO
..OwppssOO.......OscccccccrrO
...OppssssOO......OscccccerrO
....OpssscccOO.....OsccccrrO
.....OssccccrrOO....OscccrrO
......OccccrrrrrOO...OccrrrO
.......OrrrrrrccccOO.OccrrrO
........OrrrrccsssccOOccrrrO
.........OrrccsssssccccccrrO
..........OrrccssssccccccrrO
...........OrrccsssscccccrrO
............OrrccsssccccrrO
..OOO........OrrccssccccrrO
.OWWWOO.......OrrccccccrrO
.OWWWWWOO......OrrccccrrO
..OWWwwffOO.....OrrccrrO
...OwppsssccOO...OrrrrO
....OppsssccrrOO..OrrO
.....OsscccerrrrOO.OO
......OcccrrrrcccOO
.......OrrrrccccrrO
........OrrcccccrrO
.........OccccccrrO
..........OccccrrO
...........OccrrO
............OrrO
.............OO
..............O
'''.replace('P','p').replace('e','c'))


# Nine exposed compact tips: one low cap was relocated and two new curves added.
COMPACT_EXTRA=[(27,29,'''
...OO
..OWWO
.OWWWWO
.OWWWWwO
..OWWWwwO
...OWwwwfO
....OwppssO
.....OppsssO
......OpssssO
.......OsssscO
........OsscccO
.........OscccrO
..........OcccrO
..........OcccrO
..........OcccrO
..........OcccrO
..........OcccrO
.........OscccrO
.........OscccrO
........OssccrrO
........OsccrrO
.......OssccrrO
.......OsccrrO
......OssccrrO
......OsccrrO
.....OssccrrO
.....OsccrrO
....OssccrrO
....OsccrrO
...OssccrrO
...OsccrrO
..OssccrrO
..OsccrrO
.OssccrrO
.OccrrO
..OrrO
...OO
'''),(34,31,'''
................OO
...............OWWO
..............OWWWWO
.............OWWWWWwO
............OWWWWwwwO
...........OWWWwwwfO
..........OWWwwwpfO
.........OwppppssO
........OppppsssO
.......OppssssccO
......OpssssccrO
.....OsssssccrO
....OsssscccrrO
...OssscccrrrO
..OssscccrrrO
.OssscccrrrO
.OssccccrrO
OssscccrrO
OssccccrrO
OsccccrrO
OsccccrrO
OsccccrrO
OsccccrrO
OsccccrrO
OsccccrrO
OsccccrrO
OsccccrrO
OssccccrrO
.OssccccrrO
..OssccccrrO
...OsccccrrO
....OccccrrO
.....OrrrrO
......OOOO
'''),(3,72,'''
.....................OOO
...................OssccO
.................OsssssccO
...............OssssccccrO
.............OppsssccccrrO
...........OppsssccccrrrO
.........OppsssccccrrrrO
.......OWppssscccrrrrO
.....OWWWpsscccrrrrO
....OWWWWwcccrrrrO
...OWWWWWwwfrrrO
..OWWWWWwwffrO
.OWWWWWWwwffO
.OWWWWWwwwfO
..OWWWWwwfO
...OWWwwfO
....OOOOO
''')]
def gathered(a):
    block(a,*GATHER)
    for x,y,rows in COMPACT_EXTRA: block(a,x,y,rows)

# Windup: lowered neck, folded elbows and planted hind hock.
WIND=(23,41,'''
.........................................OO
........................................OWO
........................................OWwO.......OO
.......................................OWWwO......OWO
.......................................OWfnO.....OWwO
......................................OWfnRO....OWfwO
.....................................OWWnRRO...OWfnwO
....................................OWWWfnROOOOWfnRwO
...................................OWWWWWWwwWWWWWwwO
..................................OWWWWWWWWWWWWWwwwO
.................................OWWWWWWWWWWWWWwwwfO
................................OWWWWWWWWWwwwwfffnwOO
...............................OWWWWWWWWWwwnKKgWwwWWWOO
..............................OWWWWWWWWWwwfOKKJwwWWWWWWOO
.............................OWWWWWWWwwwwffnOOwwWWWWWWWWKO
............................OWWWWWwwwwwwwwWWWWWWWWwwwnOO
..........OOOOOOOOOOOOOOOOOWWWWWwwwwWWWWWWWWwwnnOOOOOO
.......OOWWWWWWWWWWWWWWWWWWWWWWWWwwWWWWwwwwfnOOO
.....OOWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwfnO
....OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwfnO
...OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwfnO
..OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwffnO
.OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwffnO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwffndO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwffndO
OWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwfffndO
OWWWWWWWWWWWWWWWWWWWWWWWwwwwwwffffndO
OWWWWWWWWWWWWWWWWWWWWWwwwwwwwffffndO
OWWWWWWWWWWWWWWWWWWwwwwwwwwffffnddO
OWWWWWWWWWWWWWWWwwwwwwwwwffffnddO
OWWWWWWWWWWWwwwwwwwwwwffffnnddO
OWWWWWWWWwwwwwwwwwwfffffnndddOO
OWWWWWWwwwwwwwwfffffnnnndddOOwwO
OWWWWwwwwwwffffffnnnndddOOOwwwfO
OWWWwwwwwfffffnnnndddOOO..OwwwfO
OWWwwwwwfffnddOOOOOO......OwwwfO
.OWWwwfffndO..............OwwwfO
..OWWwwffndO..............OwwwfO
...OWWwwffndO.............OwwwfO
....OWWwwffndO...........OWwwwfO
....OWWWwwffndO.........OWWwwwfO
...OWWWwwwffndO........OWWwwffnO
..OWWWwwwffndO........OWWwwffnO
..OWWwwwffndO........OWWwwffnO
..OWWwwwffndO.......OWWwwffnO
..OWWwwwffndO.......OWWwwffnO
.OWWWwwwffndO......OWWWWwwfnO
OWWWWWwwwffnO.....OWWWWWWwwfnO
OWWnWWnwwwffO.....OWWnWWnwwffO
.OOOOOOOOOOO.......OOOOOOOOOO
''')
w=canvas();gathered(w);block(w,*WIND)
block(w,63,65,SEAL)
block(w,49,57,'''
..c
.csc
.cEsc
rcYsc
rcsccr
.rccr
''')
block(w,44,76,'''
OffdnO
OffdnO
.OffdnO
..OffdnO
...OffdnO
...OwwffnO
..OwwwffnO
.OwwwwffnO
.OwnwnffnO
..OOOOOOO
''')
save('windup',w)

# Move: stretched thorax, pushing rear hock, folded and reaching forelegs.
MOVE=(18,38,'''
..............................................OO
.............................................OWO
.............................................OWwO.....OO
............................................OWWwO....OWO
............................................OWfnO...OWwO
...........................................OWfnRO..OWfwO
..........................................OWWnROOOOWfnwO
.........................................OWWWfWWWWWWWwwO
........................................OWWWWWWWWWWWwwwO
.......................................OWWWWWWWWWWWwwffO
......................................OWWWWWWWWWWwwffnwOO
.....................................OWWWWWWWWWWwwnKKgwwwOO
....................................OWWWWWWWWWWwwfOKKJwWWWWOO
...................................OWWWWWWWWWwwwwfnOOwWWWWWWKO
..................................OWWWWWWWwwwwwwwWWWWWWwwwnOO
.................................OWWWWWwwwwwwWWWWWWwwnnOOOO
................................OWWWWWWwwWWWWWWWwwwfnOO
...............OOOOOOOOOOOOOOOOWWWWWWWWWWWWWWWwwwwfnO
............OOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwfnO
.........OOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwfnO
.......OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwfnO
.....OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwwfnO
....OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwwwwfnO
...OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwwwwfnO
..OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwwwwwffndO
.OWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwwwwwffndO
.OWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwwwwwffndO
OWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwwwwwwffndO
OWWWWWWWWWWWWWWWWWWWWWwwwwwwwwwwwwwffndOOwwO
OWWWWWWWWWWWWWWWWWWwwwwwwwwwwwwwffnddO.OwwwO
OWWWWWWWWWWWWWWWwwwwwwwwwwwwwfffnddO..OwwwO
OWWWWWWWWWWWwwwwwwwwwwwwwwfffndddO...OwwwfO
OWWWWWWWWwwwwwwwwwwwwwwfffnddddO.....OwwwfO
OWWWWWWwwwwwwwwwwwwffffnndddOOO......OwwwfO
OWWWWwwwwwwwwwfffffnnnnddOOO.........OwwwfO
OWWWwwwwwfffffnnnnnddOOO.............OwwwfO
OWWwwwffffnnnddOOOOOO................OwwwfO
OWWwwfffnddOOOO......................OwwwfO
OWWwwffndO..........................OWwwwfO
OWWwwffndO.........................OWWwwwfO
OWWwwffndO........................OWWwwwfO
OWWwwffndO.......................OWWwwwfO
OWWwwffndO......................OWWwwwfO
OWWwwffndO.....................OWWwwwfO
OWWwwffndO....................OWWwwwfO
OWWwwffndO...................OWWwwwfO
OWWwwffndO..................OWWWwwwfO
OWWwwffndO..................OWWWWwwfO
OWWwwffndO..................OWWnWnwfO
OWWwwffndO...................OOOOOOO
OWWwwffndO
OWWWwwffnO
OWWWWWwffO
OWnWWnwwfO
.OOOOOOOO
''')
m=canvas();gathered(m);block(m,*MOVE)
block(m,58,61,SEAL)
# Raised near forepaw and its connected elbow, crossing under silk.
block(m,64,70,'''
OwwwwffnO
.OwwwffnO
..OwwwffnO
...OwwwffnO
....OwwwffnO
.....OwwwffnO
......OwwwffnO
.......OwwwffnO
........OwwwffnO
.........OwwwffnO
..........OwwwffnO
...........OwwwffnO
............OwwwwfnO
............OWWWwwfO
............OWnWnwfO
.............OOOOOO
''')
block(m,33,74,'''
OfffnO
OfffnO
OfffnO
OfffnO
OfffnO
OfffnO
OfffnO
OfffnO
OffffnO
OwwfffnO
OwwnwnfnO
.OOOOOOO
''')
block(m,50,52,EMBER)
save('move',m)
# Correct eyelid coordinates on the literal idle head, preserving its muzzle.
c=copied(BASE)
patch(c,69,44,'nKKgW')
patch(c,68,45,'fOKKJ')
patch(c,55,56,'''
wWWWwwwwwwff
WWWwwwwwwffn
WWWWwwwwffnd
WWWwwwwwfndO
WWwwwwwffndO
''')
patch(c,61,72,'''
RcpscR.
RcsscR.
RcccrR.
RccrrR.
.RcrrR.
..RRR..
''')
patch(c,29,89,'''
OWWWWwwfdO
OWWWWWwwwO
OWWnWWnwwO
.OOOOOOOO.
''')
save('idle_c',c)
block(w,57,62,'''
GYYG
.GYgG
..GYgG
...GYgG
....GYgG
.....GggG
......GggG
''')
save('windup',w)

# Contact body: low long barrel, airborne rear hocks, strong forward shoulders.
CONTACT=(18,56,'''
...............OOOOOOOOOOOOOOOOOOOO
............OOWWWWWWWWWWWWWWWWWWWWWOO
.........OOWWWWWWWWWWWWWWWWWWWWWWWWWWWOO
.......OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO
.....OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO
....OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwO
...OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwO
..OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwO
.OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwffO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwfffO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwwwfffO
OWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwwwwwfffnO
OWWWWWWWWWWWWWWWWWWWWWWwwwwwwwwwwwwwfffnO
OWWWWWWWWWWWWWWWWWWWwwwwwwwwwwwwwwfffnO
OWWWWWWWWWWWWWWWWwwwwwwwwwwwwwwwfffnOO
OWWWWWWWWWWWWWwwwwwwwwwwwwwwwffffnOO
OWWWWWWWWWWwwwwwwwwwwwwwwffffnnddO
OWWWWWWWWwwwwwwwwwwwwffffnndddOOO
OWWWWWWwwwwwwwwwwffffnnndddOOO
OWWWWwwwwwwwwffffnnndddOOOO
OWWWwwwwffffnnndddOOOO
OWWwwwffnndddOOOO
.OWWwwffndO
..OWWwwffndO
...OWWwwffndO
....OWWwwffndO
.....OWWwwffndO
......OWWwwffndO
.......OWWWwwffnO
.......OWWWWWwffO
.......OWnWWnwwfO
........OOOOOOOO
''')
ATTACK_HEAD=(54,35,'''
............OO
...........OWO
...........OWwO
..........OWWwO.......OO
..........OWfnO......OWO
.........OWfnRO.....OWwO
........OWWnRRO....OWfwO
.......OWWWfnRO...OWfnwO
......OWWWWWfROOOOWfnRwO
.....OWWWWWWWWWWWWWWWwwO
....OWWWWWWWWWWWWWWWWwwwO
...OWWWWWWWWWWWWWWWWwwwfO
..OWWWWWWWWWWWWWWwwwffnwOO
.OWWWWWWWWWWWWWWwwnKKgWwwOO
OWWWWWWWWWWWWWWwwfOKKJwwWWWOO
OWWWWWWWWWWWwwwwffnOOwWWWWWWKO
OWWWWWWWWWwwwwwwwwWWWWWWWWnOO
OWWWWWWwwwwwwWWWwwwwnnOOO
OWWWWWwwwwwwWWWwwfnOKWWO
OWWWWwwwwwwWWWwwfnOKRrWO
OWWWWwwwwWWWWwwfnOKRrrWO
OWWWWwwWWWWWwwfnOKRrrrO
OWWWWWWWWWWwwfnOKRrcrO
OWWWWWWWWWwwfnOKRrcrWO
OWWWWWWWWwwfnOKRrrWwwO
OWWWWWWWwwfnOKRrWwwwO
OWWWWWWwwfnOOOWwwwwO
OWWWWWwwwwwwwwwwffO
OWWWWwwwwwwwwwffnO
OWWWwwwwwwwfffnO
OWWwwwwwwfffnO
OWwwwwffffnO
OwwwwfffnO
''')
t=canvas();gathered(t);block(t,*CONTACT);block(t,*ATTACK_HEAD)
# Near foreleg extends from shoulder to a large biting/claw contact pair.
block(t,60,66,'''
OwwwffnO
OwwwwffnO
.OWwwwffnO
..OWwwwffnO
...OWwwwffnO
....OWwwwffnO
.....OWwwwffnO
......OWwwwffnO
.......OWwwwffnO
........OWwwwffnO
.........OWwwwffnO
..........OWwwwffnO
...........OWwwwffnO
............OWwwwffnO
.............OWwwwffnO
..............OWwwwffnO
...............OWwwwwfnO
...............OWWWWWwfO
...............OWnWWnwfO
................OOOOOOO
''')
block(t,63,64,'''
OfffnO
.OfffnO
..OfffnO
...OfffnO
....OfffnO
.....OfffnO
......OfffnO
.......OfffnO
........OfffnO
.........OfffnO
..........OfffnO
...........OffffnO
............OffffnO
.............OfffffnO
..............OwwfffnO
..............OwnwnfnO
...............OOOOOOO
''')
block(t,35,75,'''
OfffnO
.OfffnO
..OfffnO
...OfffnO
....OfffnO
.....OfffnO
......OffffnO
.......OwwffnO
.......OwnwnfO
........OOOOO
''')
block(t,56,64,'''
GYYG
GYggG
GgYgG
.GgYgG
..GgYgG
...GgYgG
....GgYgG
.....GggG
''')
block(t,60,72,SEAL)
block(t,46,51,EMBER)
save('attack',t)

# Recovery: lifted chest with a bent foreknee, muzzle closing after contact.
RECOVER=(25,35,'''
.....................................OO
....................................OWO
....................................OWwO......OO
...................................OWWwO.....OWO
...................................OWfnO....OWwO
..................................OWfnRO...OWfwO
.................................OWWnRRO..OWfnwO
................................OWWWfnROOOWfnRwO
...............................OWWWWWWWWWWWWWwwO
..............................OWWWWWWWWWWWWWwwwO
.............................OWWWWWWWWWWWWWwwwfO
............................OWWWWWWWWWWWWwwwffnwOO
...........................OWWWWWWWWWWWWwwnKKgWwwOO
..........................OWWWWWWWWWWWWwwfOKKJwwWWWOO
.........................OWWWWWWWWWWWwwwwfnOOwWWWWWWKO
........................OWWWWWWWWWwwwwwwwwWWWWWWWWnOO
.......................OWWWWWWWwwwwwwWWWwwwwnnOOO
......................OWWWWWWWWwwWWWWWWwwwfnOO
.....................OWWWWWWWWWWWWWWWwwwwfnO
....................OWWWWWWWWWWWWWWWwwwwfnO
...................OWWWWWWWWWWWWWWWwwwwwfnO
..........OOOOOOOOWWWWWWWWWWWWWWWwwwwwwfnO
.......OOWWWWWWWWWWWWWWWWWWWWWWWwwwwwwffnO
.....OOWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwffnO
....OWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwffnO
...OWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwffnO
..OWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwffnO
.OWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwffnO
.OWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwffnO
OWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwffnO
OWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwwffnO
OWWWWWWWWWWWWWWWWWWWWwwwwwwwwwwffnO
OWWWWWWWWWWWWWWWWWwwwwwwwwwwfffndO
OWWWWWWWWWWWWWWwwwwwwwwwwffffnddO
OWWWWWWWWWWwwwwwwwwwwffffnndddOOO
OWWWWWWwwwwwwwwwfffffnnndddOOOwwfO
OWWWwwwwwwwwffffnnnndddOOOO..OwwfO
OWWwwwwwfffnddOOOOOOOO.......OwwfO
OWWwwwwfffndO...............OwwfO
.OWWwwwffndO................OwwfO
.OWWwwwffndO................OwwfO
..OWWwwffndO...............OWwwfO
..OWWwwffndO..............OWWwwfO
...OWWwffndO.............OWWwwfO
...OWWwffndO............OWWwwfO
...OWWwffndO...........OWWwwfO
...OWWwffndO..........OWWwwfO
...OWWwffndO..........OWWwwfO
...OWWwffndO.........OWWWwwfO
...OWWwffndO.........OWWWWwfO
..OWWWwwffnO.........OWnWnwfO
.OWWWWWwwffO..........OOOOOO
.OWnWWnwwffO
..OOOOOOOOO
''')
u=fan();block(u,*RECOVER)
block(u,56,62,SEAL)
block(u,67,70,'''
OwwffnO
OwwffnO
.OwwffnO
..OwwffnO
...OwwffnO
...OwwffnO
...OwwffnO
...OwwffnO
...OwwffnO
...OwwffnO
...OwwffnO
..OwwwffnO
.OwwwwffnO
.OwnwnffnO
..OOOOOOO
''')
block(u,40,74,'''
OfffnO
OfffnO
OfffnO
OfffnO
OfffnO
OfffnO
OfffnO
OfffnO
OffffnO
OffffnO
OwwfffnO
OwnwnfnO
.OOOOOO
''')
block(u,47,51,EMBER)
save('recover',u)
# Remove the contact head's internal contour where it joins the white shoulder.
patch(t,54,49,'''
WWWWWWW
WWWWWWW
WWWWWWW
WWWWWWW
WWWWWWW
WWWWWWW
WWWWWWW
WWWWWWW
WWWWWWW
WWWWWWW
WWWWWww
WWWWwww
WWWwwww
WWwwwww
Wwwwwww
wwwwwww
wwwwwff
''')
# Far contact leg has its own shorter reach, with shoulder still attached.
block(t,64,66,'''
OfffnO
.OfffnO
..OfffnO
...OfffnO
....OfffnO
.....OfffnO
......OfffnO
.......OfffnO
........OffffnO
.........OffffnO
..........OwwfffnO
..........OwnwnfnO
...........OOOOOOO
''')
save('attack',t)
block(u,62,65,'''
OwwffnO
OwwwffnO
.OwwwffnO
..OwwwffnO
...OwwwffnO
....OwwwffnO
.....OwwffnO
.....OwwffnO
''')
save('recover',u)

# Hit: folded hindquarters, rotated local neck planes, squeezed eyelid, dangling jaw.
HIT=(23,48,'''
..............................OO
.............................OWWO
.............................OWWwO
.............................OWWfwO
............................OWWfnwO
............................OWfnRwO
...........................OWWfnRwO......OO
..........................OWWWfnRwO.....OWWO
.........................OWWWWwwwwO....OWWwO
........................OWWWWWWWWwOOOOOWfnwO
..........OOOOOOOOOOOOOOWWWWWWWWWWWWWWfnRwO
.......OOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwO
.....OOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwO
....OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwfO
...OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwfnO
..OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWfnOO
.OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwfnwO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwfKKfnO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwfKnwwfO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwffwwwwfO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwWWWWwfO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwWWWWWWwwO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwWWWWWWWWWwO
OWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwWWWWWWWWWWwKO
OWWWWWWWWWWWWWWWWWWWWWWWwwwwwwWWWWWWWWWwwwnO
OWWWWWWWWWWWWWWWWWWWWwwwwwwwwwwfffwwwwnnOOO
OWWWWWWWWWWWWWWWWWwwwwwwwwffffnnnOwwwwfO
OWWWWWWWWWWWWWWwwwwwwwwwffffnnnOO.OwwwfO
OWWWWWWWWWWwwwwwwwwwfffffnnndOO...OwwfO
OWWWWWWwwwwwwwwwffffnnnndddOO......OOO
OWWWWwwwwwwffffnnnnddddOOO
OWWWwwwfffnddddOOOOOOOO
OWWwwwwffndO
.OWWwwwffndO
..OWWwwwffndO
...OWWwwwffndO
....OWWwwwffndO
....OWWWwwffndO
...OWWWwwwffndO
..OWWWwwwffndO
.OWWWwwwffndO
.OWWwwwffndO
OWWWWwwwffnO
OWWWWWWwwffO
OWWnWWnwwffO
.OOOOOOOOOO
''')
h=fan();block(h,*HIT)
# Two buckled forelegs visibly linked into lowered shoulder.
block(h,57,72,'''
OwwwwffnO
OwwwwffnO
.OwwwffnO
..OwwwffnO
...OwwwffnO
....OwwwffnO
.....OwwwffnO
......OwwwffnO
.......OwwwffnO
........OwwwffnO
.........OwwwffnO
..........OwwwffnO
...........OwwwffnO
............OwwwffnO
.............OwwwffnO
.............OWWWWwfO
.............OWnWnwfO
..............OOOOOO
''')
block(h,63,71,'''
OfffnO
.OfffnO
..OfffnO
...OfffnO
....OfffnO
.....OfffnO
......OfffnO
.......OfffnO
........OfffnO
.........OffffnO
..........OwwffnO
..........OwnwnfO
...........OOOOO
''')
block(h,39,78,'''
OfffnO
.OfffnO
..OfffnO
..OfffnO
..OfffnO
..OfffnO
..OfffnO
..OwwffnO
.OwwwffnO
.OwnwnfnO
..OOOOOO
''')
block(h,55,70,'''
GYYG
.GYgG
..GYgG
...GYgG
....GYgG
.....GggG
''')
block(h,57,76,SEAL)
save('hit',h)

# Folded tail fan after collapse: nine distinguishable cream terminal planes.
FOLDED=(4,45,'''
.....OO............OO
....OWWO..........OWWO
...OWWWO.........OWWWO
...OWWWWwO.......OWWWwO
....OWWWwwO.....OWWWWwwO
.....OWwwwfO....OWWwwwfO
......OwppssO...OwpppssO........OO
.......OppsssO..OpppsssO.......OWWO
........OpssssO.OpssssccO.....OWWWO
.........OssssccOpssssccO....OWWWwO
..........OssssssssscccO...OWWWwwO
...........OsssssssscccO..OWWwwwO
..OOO.......OssssssscccO.OwwppssO
.OWWWOO......OsssssscccOOppppssO
OWWWWWWOO.....OsssssccccpppsssO
.OWWWWWwwOO....OsssssssssscccO
..OWWwwfffOO....OsssssssscccrO
...OwpppssssOO...OsssssscccrrO
....OppsssssccOO..OsssscccrrrO
.....OsssssccccrrOOsssscccrrO
......OssccccccrrrsssscccrrO
.......OccccrrrrrrssscccrrO
.OOO....OrrrrrrrrccssscccrrO
OWWWOO...OrrrrrcccsssscccrrO
OWWWWWOO..OrrrcccsssscccrrO
.OWWWwwwOO.OrrcccsssscccrrO
..OWwwwfffOOrrcccsssscccrrO
...OwpPssssccrcccsssscccrrO
....OppsssscccrcccssscccrrO
.....OssscccccrrcccsscccrrO
......OcccccrrrrrccccccrrO
.......OrrrrrrrrrrccccrrrO
.OOOO...OrrrrrrrccccccrrrO
OWWWWOO..OrrrrcccccccrrrO
OWWWWWWOO.OrrccssssccrrrO
.OWWWwwffOOrrccsssssccrrO
..OwwppsssccrrccssssccrrrO
...OppsssccccrrccsssccrrrO
....OsscccccrrrrccssccrrrO
.....OrrrcccrrrrrccsccrrrO
......ORrrrrrrrrrrccccrrrO
.......ORrrrccccccrcccrrrO
........OrrccsssscccccrrrO
.........OccssssscccccrrrO
..........OcssssccccccrrrO
...........OcccccccccrrrO
............OrrrrrrrrrrO
.............OOOOOOOOOO
'''.replace('P','p'))

# Seven-to-nine folded fan correction: relocate ground cap and add two curls.
FOLDED_EXTRA=[(18,43,'''
................OO
...............OWWO
..............OWWWWO
.............OWWWWwwO
............OWWWwwwO
...........OWWwwwfO
..........OwpppssO
.........OpppsssO
........OpssssccO
.......OsssscccrO
......OsssccccrrO
.....OsssccccrrO
....OsssccccrrO
...OsssccccrrO
..OsssccccrrO
.OsssccccrrO
.OssccccrrO
OssccccrrO
OsccccrrO
OsccccrrO
OsccccrrO
OssccccrrO
.OssccccrrO
..OssccccrrO
...OsccccrrO
....OccccrrO
.....OrrrrO
......OOOO
'''),(12,63,'''
..OOO
.OWWWO
OWWWWWO
OWWWWWwO
.OWWWWwwO
..OWWwwwfO
...OwppsssO
....OppssssO
.....OpsssccO
......OssccccO
.......OscccrrO
........OscccrrO
.........OssccrrO
..........OssccrrO
...........OscccrrO
............OccrrrO
.............OrrrrO
..............OOO
'''),(11,76,'''
...........OOO
.........OsssccO
.......OsssscccrO
.....OppssscccrrO
....OppssscccrrO
...OppssscccrrO
..OppssscccrrO
.OWppsscccrrO
OWWWpscccrrO
OWWWWwccrrO
OWWWWwffrO
.OWWwwffO
..OwwwfO
...OOO
''')]
def folded(a,curled=False):
    block(a,*FOLDED)
    # Sleeping curl supplies the ninth terminal; dead uses all three extras.
    selected=FOLDED_EXTRA[:2] if curled else FOLDED_EXTRA
    for x,y,rows in selected: block(a,x,y,rows)

CORPSE=(25,69,'''
.........OOOOOOOOOOOOOOOOOO
......OOWWWWWWWWWWWWWWWWWWWOO
....OOWWWWWWWWWWWWWWWWWWWWWWWOO
...OWWWWWWWWWWWWWWWWWWWWWWWWWWWOO
..OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWOO
.OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWOO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWOO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwwfO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwwwwfO
OWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwwwwwwwffO
OWWWWWWWWWWWWWWWWWWWWWwwwwwwwwwwwwwwwwffO
OWWWWWWWWWWWWWWWWwwwwwwwwwwwwwwwwwwwfffO
OWWWWWWWWWWWWwwwwwwwwwwwwwwwwwwwwwffffO
OWWWWWWWwwwwwwwwwwwwwwwwwwwwwwwffffnnO
OWWWWwwwwwwwwwwwwwwwwwwwwwwffffnnnnO
.OWWwwwwwwwwwwwwwwwwwffffffnnnnnOOO
..OwwwwwwwwwwwfffffffndddOOOOOOO
...OwwwwwwfffndddddOOOOOO
....OOOOOOOOOOOOOO
''')
DEAD_HEAD=(62,70,'''
.......OOOO
......OWWwwOO
.......OWWWwwOO
........OWWWfwwO
.........OWWfnwwO...OOOO
..........OWfnwwOOOOWwwO
........OOWWWWWWWWWWWwwO
......OOWWWWWWWWWWWWwwwO
....OOWWWWWWWWWWWWWWwwwfO
...OWWWWWWWWWWWWWWWwwfnwO
..OWWWWWWWWWWWWWWwwwwfnnwOO
.OWWWWWWWWWWWWWWwwwfKKnnwwOO
OWWWWWWWWWWWWWWwwwffnwwwwWWWOO
OWWWWWWWWWWWwwwwwwwWWWWWWWWWWKO
OWWWWWWWWWwwwwwwWWWWWWWWwwwwnOO
OWWWWWWwwwwwwWWWWWWWwwwwnnOOOO
OWWWWWwwwwwWWWWWWwwfffOOOO
OWWWWwwwwWWWWwwffffnOO
OWWWwwwwwwwffffnndOO
OWWwwwwffffnnndOO
.OwwfffnddddOO
..OOOOOOOOOO
''')
z=canvas();folded(z);block(z,*CORPSE);block(z,*DEAD_HEAD)
# Forepaws rest along the ground; slack collar and silk lie over the coat.
block(z,66,88,'''
OwwwwwwwwwwfO
OWWWWWWWWWwfO
OWWnWWnWWnwfO
.OOOOOOOOOOO
''')
block(z,29,87,'''
OwwwwwwwwfO
OWWWWWWWWwfO
OWWnWWnWWwfO
.OOOOOOOOO
''')
block(z,50,84,'''
GYYggGG
GYgjjgYG
GgjWJjgG
.GgjJggG
..GggGRccR
....RccssccR
.....RccssccR
......RrrrrR
''')
save('dead',z)
# Keep hit ribbon above the common baseline without an isolated contact pixel.
patch(h,57,90,'''
..RrR...
...R....
........
........
''')
save('hit',h)
# Integrate the collapsed neck into the barrel, avoiding an internal black seam.
patch(z,62,80,'''
WWWWWW
WWWWWW
WWWWWw
WWWWww
WWWwww
WWwwww
Wwwwww
wwwwff
''')
save('dead',z)

# Magic brace: bowed forelegs and a lifted, short draw-back neck leave casting room.
MAGIC_BODY=(23,56,'''
.............OOOOOOOOOOOOOOOOO
..........OOWWWWWWWWWWWWWWWWWWOO
.......OOWWWWWWWWWWWWWWWWWWWWWWWOO
.....OWWWWWWWWWWWWWWWWWWWWWWWWWWWWOO
....OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO
...OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwO
..OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwO
.OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwffO
OWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwfffO
OWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwwfffO
OWWWWWWWWWWWWWWWWWWWWwwwwwwwwwfffnO
OWWWWWWWWWWWWWWWWWwwwwwwwwwwfffnO
OWWWWWWWWWWWWWWwwwwwwwwwwwfffnO
OWWWWWWWWWWwwwwwwwwwwwwffffnO
OWWWWWWwwwwwwwwwwwwffffnnddO
OWWWWwwwwwwwwwwwffffnndddOOO
OWWWwwwwwwwwwfffnnndddOOOO
OWWwwwwwwwfffndddOOOOO
OWWwwwwfffnddOOOO
.OWWwwffnddO
..OWWwwffndO
...OWWwwffndO
....OWWwwffndO
....OWWWwwffndO
...OWWWwwwffndO
..OWWWwwwffndO
..OWWwwwffndO
..OWWwwwffndO
..OWWwwwffndO
.OWWWwwwffndO
OWWWWWwwwffnO
OWWWWWWwwwffO
OWWnWWnwwwffO
.OOOOOOOOOOO
''')
MAGIC_HEAD=(48,33,'''
.........OO
........OWO
........OWwO......OO
.......OWWwO.....OWO
.......OWfnO....OWwO
......OWfnRO...OWfwO
.....OWWnRRO..OWfnwO
....OWWWfnROOOWfnRwO
...OWWWWWWWWWWWWWwwO
..OWWWWWWWWWWWWWWwwwO
.OWWWWWWWWWWWWWWWwwfO
OWWWWWWWWWWWWWWwwwfnwOO
OWWWWWWWWWWWWWwwnKKgWwwOO
OWWWWWWWWWWWWwwfOKKJwwWWWOO
OWWWWWWWWWWwwwwfnOOwWWWWWWKO
OWWWWWWWWwwwwwwwwWWWWWWWWnOO
OWWWWWWwwwwwwWWWwwwwnnOOO
OWWWWWwwwwwwWWWwwwfnOO
OWWWWwwwwwWWWWwwwwfnO
OWWWWwwwWWWWWwwwwwfnO
OWWWWWWWWWWWwwwwwffnO
OWWWWWWWWWWwwwwwffnO
OWWWWWWWWWwwwwwffnO
OWWWWWWWWwwwwwffnO
OWWWWWWWwwwwwwfnO
OWWWWWWwwwwwffnO
OWWWWWwwwwwffnO
OWWWWwwwwfffnO
OWWWwwwwfffnO
OWWwwwwfffnO
OWwwwwfffnO
OwwwwfffnO
''')
CAST_LEGS=(52,68,'''
OwwwwffnO
OwwwwffnO
.OwwwffnO
..OwwwffnO
...OwwwffnO
....OwwwffnO
....OwwwffnO
....OwwwffnO
....OwwwffnO
....OwwwffnO
....OwwwffnO
....OwwwffnO
....OwwwffnO
....OwwwffnO
....OwwwffnO
....OwwwffnO
...OwwwwffnO
..OWWWwwffnO
.OWWWWWWwwfO
.OWWnWWnwwfO
..OOOOOOOOO
''')
FAR_CAST=(61,67,'''
OfffnO
.OfffnO
..OfffnO
...OfffnO
...OfffnO
...OfffnO
...OfffnO
...OfffnO
...OfffnO
...OfffnO
...OfffnO
...OfffnO
...OfffnO
...OfffnO
...OffffnO
..OwwfffnO
.OwwwfffnO
.OwnwnffnO
..OOOOOOO
''')
sa=fan();block(sa,*MAGIC_BODY);block(sa,*MAGIC_HEAD)
# Seam replacement consists of these chosen fur pixels.
patch(sa,48,56,'''
WWWWWW
WWWWWW
WWWWWW
WWWWww
WWWwww
WWwwww
Wwwwwf
wwwwff
''')
block(sa,*FAR_CAST);block(sa,*CAST_LEGS)
block(sa,39,76,'''
OfffnO
OfffnO
OfffnO
OfffnO
OfffnO
OfffnO
OfffnO
OffffnO
OwwfffnO
OwnwnfnO
.OOOOOO
''')
block(sa,53,60,SEAL)
block(sa,47,57,'''
GYYG
GYgG
.GYgG
..GYgG
...GggG
''')
# Three different tail-tip flames, with individually shaped folded tongues.
block(sa,18,11,'''
...c
..cs
..cEc
.cYsc
.cYEc
rcYYsc
rcYEsc
rccscr
.rccr
''')
block(sa,39,6,'''
....c
...csc
..cEsc
..cYsc.c
.cYYEscs
.cYWEsc
rcYEccr
.rcscr
..rr
''')
block(sa,52,12,'''
..c
..sc
.cEsc
.cYsc
cYWEsc
rcYEsc
.rccr
''')
# Compressed golden core sits at the actual closed lip, x73 y48.
block(sa,73,45,'''
.gG
GYgG
GYWYg
.GYgG
..gG
''')
save('skill_a',sa,True)

sb=copied(sa)
# Literal open jaw/neck cluster: source-side cast, not a larger copy of core.
patch(sb,64,45,'''
wwnKKgWwwOO........
wfOKKJwwWWWOO......
fnOOwWWWWWWKO......
wwWWWWWWnOO........
WWWwwnnOOO.........
WWwwfnOKWO.........
WwwfnOKRWO.........
wwfnOKRrWO.........
wfnOKRrrWO.........
fnOKRrcWO..........
nOKRrcWO...........
OKRrWwwO...........
OOWwwwO............
wwwwfO.............
wwwfO..............
wwfO...............
wfO................
''')
# Chest swell, forward knee compression and streaming silk.
patch(sb,51,65,'''
WWWWwwwff
WWWwwwwff
WWwwwwfff
Wwwwwfffn
wwwwfffnO
''')
patch(sb,55,74,'''
RccsscR
.RccsscR
..RccscrR
...RccrrR
....RrrR
.....RR
''')
# Main mouth-connected curved explosion, torn upper and lower tongues.
block(sb,73,26,'''
..................c
.................cs
................cEs
...............cEYr
...............sYYr
..............cYWEc
.............cYWEcr
.............cYWEcr
............cYYEccr
...........cYYWEccr
..........cYYWWEccr
.........cYYWWWEccr
.........cYYWWWEccr
........cYYWWWEccr
.......cYYWWWEccr
......cYYWWWEccr
......cYWWWEccr
.....cYYWWEccr
....cYYWWEEcr
....cYWWEEcr
...cYYWEEcr
..cYYWWEEcr
.csYYWWEEccr
csYYWWWEEEccr
sYYWWWWWEEEccr
YYWWWWWWWEEEccr
YYWWWWWWWWEEEccr
YWWWWWWWWWYEEccr
YWWWWWWWWYYEEccr
YYWWWWWWYYEEcccr
sYYWWWWYYEEcccsc
csYYYYYYEEccccsEc
.ccsYYEEEccccsYsc
..ccsEEEccccsYEsc
...ccsEEcccsYYEc
....ccsEccsYYEc
.....cccssYYEc
......ccsYYEc
.......csYYEc
........csYEc
.........cYEc
..........cEc
...........cc
............c
''')
# Tail flames open into broad tips, never a repeated radial aura.
block(sb,15,7,'''
....c
....cs
...cEsc
..csYsc
.cYYWEsc
.cYWWWYsc
cYYWWYYEcr
rcYYYEEccr
.rccsccrr
..rccrr
''')
block(sb,39,3,'''
....c
...cs
...sEc
..cYsc.c
.cYYEscs
.cYWWYEs
cYYWWYEcr
rcYYYEccr
.rccsccr
..rrrr
''')
block(sb,51,8,'''
.....c
....csc
...cEsc
..csYsc
.cYYWEsc
.cYWYYEc
rcYYYEsc
.rccscr
..rrr
''')
save('skill_b',sb,True)

sc=copied(sa)
# Lip closes, ruff recoils and knee starts releasing from brace.
patch(sc,64,45,'''
wwnKKgWwwOO....
wfOKKJwwWWWOO..
fnOOwWWWWWWKO..
wwWWWWWWnOO....
WWWwwnnOOO.....
WWwwfffOO......
WwwwwffnO......
wwwwffnO.......
wwwffnO........
wwffnO.........
wffnO..........
ffnO...........
fnO............
''')
patch(sc,55,72,'''
RccR...
RcpscR.
RcsscR.
RcccrR.
.RccrrR
..RrrR.
...RR..
''')
patch(sc,56,83,'''
OWWWWwwffnO
OWWWWWwwffO
OWnWWnwwffO
.OOOOOOOOO.
''')
# Two disconnected residual embers; their broad tear shapes differ.
block(sc,84,40,'''
.....c
....cs
...cEc
..cYsc
.cYYEsc
cYWEccr
rcYccr
.rccr
..rr
''')
block(sc,87,60,'''
c
sc
sEc
cYsc
cYEcr
.cEcr
..ccr
...rr
''')
# Tail flames contract to cooling red tongues on the existing white tips.
patch(sc,39,6,'''
........
........
...c....
...sc...
..cEsc..
..cscr..
.rcscr..
..rr....
........
''')
patch(sc,18,11,'''
......
...c..
..csc.
..cEcr
..cscr
.rccr.
..rr..
......
......
''')
patch(sc,52,12,'''
.....
...c.
..csc
..cEc
.rcsr
..rr.
.....
''')
save('skill_c',sc,True)
# Hit's near hock is redrawn at the baseline, preserving actual sole contact.
patch(h,23,89,'''
OWWWWWwwffO.
OWWnWWnwwfO.
.OOOOOOOOO..
............
............
''')
save('hit',h)

# Poisoned barrel: sagged spine, tense belly and a bent rear knee.
SICK_BODY=(24,62,'''
........OOOOOOOOOOOOOOOOO
.....OOWWWWWWWWWWWWWWWWWWOO
...OOWWWWWWWWWWWWWWWWWWWWWWOO
..OWWWWWWWWWWWWWWWWWWWWWWWWWWWOO
.OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWOO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwO
OWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwwwwfO
OWWWWWWWWWWWWWWWWWWWWWwwwwwwwwwwwwwfO
OWWWWWWWWWWWWWWWWwwwwwwwwwwwwwwwwwffO
OWWWWWWWWWWWWwwwwwwwwwwwwwwwwwwffffO
OWWWWWWWWwwwwwwwwwwwwwwwwwwffffnnO
OWWWWWWwwwwwwwwwwwwwwwwffffnnnddO
OWWWWwwwwwwwwwwwwfffffnnnddddOOO
OWWWwwwwwwwwwffffnnnddddOOOOO
OWWwwwwwwwfffnddddOOOOOO
.OWWwwwwfffndO
..OWWwwwffndO
...OWWwwffndO
....OWWwffndO
....OWWwffndO
...OWWWwffndO
..OWWWWwwffnO
.OWWWWWWwwffO
.OWWnWWnwwffO
..OOOOOOOOOO
''')
POISON_HEAD=(51,47,'''
.....OOOO
....OWWwwO
....OWWfwO
....OWfnwO
....OWnRwO
....OWfnwO
...OWWfwwO
..OWWWWwwO........OO
.OWWWWWWWwO......OWWO
OWWWWWWWWWwOOO..OWWwO
OWWWWWWWWWWWWWOOWfnwO
OWWWWWWWWWWWWWWWfnRwO
OWWWWWWWWWWWWWWWWWwwO
OWWWWWWWWWWWWWWWWWwwfO
OWWWWWWWWWWWWWWWWWWwfnO
OWWWWWWWWWWWWWWWWwwfnwOO
OWWWWWWWWWWWWWWWwwfnKKfwO
OWWWWWWWWWWWWWWwwwfdKndwwO
OWWWWWWWWWWWWwwwwffnwwwwwO
OWWWWWWWWWWwwwwwwwWWWWWwwO
OWWWWWWWWwwwwwwWWWWWWWWwwO
OWWWWWWwwwwwwWWWWWWWWWWWWO
OWWWWWwwwwwwWWWWWWWWWWWWwwKO
OWWWWwwwwwwWWWWWWWWwwwwwwnOO
OWWWWwwwwwwwwwwwwwwwnnOOOO
OWWWWwwwwwwwwwwwwffOOO
OWWWWwwwwwwwwfffndO
OWWWwwwwwwffffndO
OWWwwwwffffnndO
OWwwffffnnddO
OwwfffndddOO
OfffnddOOO
.OOOOOO
''')
SICK_NEAR=(57,76,'''
OwwffnO
.OwwffnO
..OwwffnO
...OwwffnO
....OwwffnO
.....OwwffnO
......OwwffnO
......OwwffnO
......OwwffnO
.....OwwwffnO
....OWwwwffnO
...OWWWwwffnO
..OWWWWWwwfnO
..OWWnWWnwwfO
...OOOOOOOOO
''')
SICK_FAR=(63,76,'''
OfffnO
.OfffnO
..OfffnO
...OfffnO
....OfffnO
.....OfffnO
......OfffnO
.......OffffnO
........OffffnO
........OwwffnO
........OwnwnfO
.........OOOOO
''')
pa=canvas();gathered(pa);block(pa,*SICK_BODY);block(pa,*POISON_HEAD)
patch(pa,51,63,'''
WWWWWW
WWWWWW
WWWWWW
WWWWWw
WWWWww
WWWwww
WWwwww
Wwwwwf
wwwwff
wwwwff
wwwfff
''')
block(pa,*SICK_FAR);block(pa,*SICK_NEAR)
block(pa,39,79,'''
OfffnO
OfffnO
OfffnO
OfffnO
OfffnO
OffffnO
OwwfffnO
OwnwnfnO
.OOOOOO
''')
block(pa,51,73,'''
GYYG
GYggYG
GgjWJgG
.GgjJgG
..GggG
..RccR
.RcpscR
.RcsscR
..RccrR
...RrrR
....RR
''')
block(pa,49,70,'''
GYYG
.GYgG
..GYgG
...GggG
''')
# Toxic jade bubbles rise in a staggered cluster from strained breathing.
block(pa,82,54,'''
.JJJ
JjWjJ
JjjJJ
.JJJ
''')
block(pa,88,48,'''
.JJ
JjWJ
.JJ
''')
block(pa,86,63,'''
JJ
jJ
JJ
''')
save('poison_a',pa,True)

pb=copied(pa)
# A new jaw and eye cluster sinks into the shoulder; the spine also folds.
patch(pb,63,59,'''
WWWWWWWWWWwwfO......
WWWWWWWWWwwfnO......
WWWWWWWWwwfnwOO.....
WWWWWWWwwfnnKfwO....
WWWWWWwwwfdKKdwwO...
WWWWWwwwwffnwwwwwO..
WWWwwwwwwwWWWWWwwO..
WwwwwwwWWWWWWWWwwO..
wwwwwwWWWWWWWWWWWO..
wwwwwWWWWWWWWWWWWwKO
wwwwWWWWWWwwwwwwwnOO
wwwwwwwwwwwwwnnOOOO.
wwwwwwwwwwffOOO.....
wwwwwwfffndO........
wwwffffndO..........
wwffffnndO..........
''')
patch(pb,32,62,'''
.OOOOOOOOOOOOOOOOO
OWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWW
''')
patch(pb,60,82,'''
OwwffnO....
.OwwffnO...
..OwwffnO..
..OwwwffnO.
.OWwwwffnO.
OWWWwwffnO.
OWWWWWwwfnO
OWWnWWnwwfO
.OOOOOOOOO.
''')
# Remove the prior bubble silhouettes, then choose three new ones individually.
patch(pb,82,54,'''
.....
.....
.....
.....
''')
patch(pb,88,48,'''
....
....
....
''')
patch(pb,86,63,'''
..
..
..
''')
block(pb,84,50,'''
.JJJJ
JjWWjJ
JjjjjJ
.JJJJ
''')
block(pb,89,59,'''
.JJ
JjWJ
JjjJ
.JJ
''')
block(pb,80,45,'''
JjJ
.J
''')
# Gasp loosens the lowest silk knot.
patch(pb,53,81,'''
RcsscR
.RccrR
..RrrR
...RR.
''')
save('poison_b',pb,True)

# Stun head is slack, with turned ears and a drooping open mouth.
STUN_HEAD=(49,49,'''
...OOOO
..OWWwwO
..OWWfwO
..OWfnwO
..OWnRwO
...OWfnwO
...OWWwwO........OOOO
..OWWWWwwO......OWWwwO
.OWWWWWWwwOOO...OWWfwO
OWWWWWWWWWWWWOOWWfnwO
OWWWWWWWWWWWWWWWfnRwO
OWWWWWWWWWWWWWWWWWWwwO
OWWWWWWWWWWWWWWWWWWwwfO
OWWWWWWWWWWWWWWWWWWWfnO
OWWWWWWWWWWWWWWWWWwwfnwO
OWWWWWWWWWWWWWWWWwwfnKKfO
OWWWWWWWWWWWWWWWwwwfdKndwO
OWWWWWWWWWWWWWwwwffnwwwwwO
OWWWWWWWWWWwwwwwwwwWWWWwwO
OWWWWWWWWwwwwwwWWWWWWWWWwwO
OWWWWWWwwwwwwWWWWWWWWWWWWwwO
OWWWWWwwwwwwWWWWWWWWWWWWWwwKO
OWWWWwwwwwwWWWWWWWWWWwwwwnOO
OWWWWwwwwwwwwwfffwwwnnOOOO
OWWWWwwwwwwfffndOOO.OwwfO
OWWWWwwwwfffndO.....OwwfO
OWWWWwwfffndO.......OwfO
OWWWwfffndO..........OO
OWWfffnddO
OwwfnddOO
OffndOO
.OOOO
''')
sta=canvas();gathered(sta);block(sta,*SICK_BODY);block(sta,*STUN_HEAD)
patch(sta,49,63,'''
WWWWWW
WWWWWW
WWWWWW
WWWWWw
WWWWww
WWWwww
WWwwww
Wwwwwf
wwwwff
wwwwff
''')
# Stun forelegs have crumpled wrists and spread soles; no fighting reach.
block(sta,53,76,'''
OwwwwffnO
.OwwwffnO
..OwwwffnO
...OwwwffnO
....OwwwffnO
.....OwwwffnO
......OwwwffnO
......OwwwffnO
.....OwwwffnO
....OWwwwffnO
...OWWwwwffnO
..OWWWWwwffnO
.OWWWWWWWwwfO
.OWWnWWnWWwfO
..OOOOOOOOOO
''')
block(sta,62,75,'''
OfffnO
.OfffnO
..OfffnO
...OfffnO
....OfffnO
.....OfffnO
......OfffnO
.......OfffnO
........OffffnO
........OwwfffnO
........OwnwnfnO
.........OOOOOO
''')
block(sta,39,79,'''
OfffnO
OfffnO
OfffnO
OfffnO
OfffnO
OffffnO
OwwfffnO
OwnwnfnO
.OOOOOO
''')
block(sta,50,73,'''
GYYG
GYggYG
GgjWJgG
.GgjJgG
..GggG
..RccR
.RcpscR
.RcsscR
..RccrR
...RrrR
....RR
''')
block(sta,48,70,'''
GYYG
.GYgG
..GYgG
...GggG
''')
# Small five-cluster stars, no text or orbit ring.
block(sta,64,39,'''
..Y
..g
YgWYg
..g
..Y
''')
block(sta,80,48,'''
.Y
YWWY
.Y
''')
save('stun_a',sta,True)

stb=copied(sta)
# Jaw falls farther while one folded ear and the near wrist relax.
patch(stb,49,49,'''
....OOO.
...OWwwO
..OWWfwO
..OWfnwO
..OWnRwO
...OWfnw
''')
patch(stb,69,71,'''
wwnOOOO....
ffOwwfO....
ndOOwwfO...
O..OwwfO...
....OwfO...
.....OO....
''')
patch(stb,56,84,'''
OWwwwffnO....
OWWwwwffnO...
.OWWwwwffnO..
..OWWWwwffnO.
..OWWWWWWwwfO
..OWWnWWnwwfO
...OOOOOOOOO.
''')
patch(stb,64,39,'''
.....
.....
.....
.....
.....
''')
patch(stb,80,48,'''
....
....
....
''')
block(stb,77,38,'''
.Y
YWWY
.Y
''')
block(stb,60,45,'''
..Y
..g
YgWYg
..g
..Y
''')
save('stun_b',stb,True)
# Sleep is a curled reclining animal, with tucked paws and folded triangular ears.
SLEEP_BODY=(24,65,'''
...........OOOOOOOOOOOOOO
........OOWWWWWWWWWWWWWWOO
......OOWWWWWWWWWWWWWWWWWWOO
....OOWWWWWWWWWWWWWWWWWWWWWWOO
...OWWWWWWWWWWWWWWWWWWWWWWWWWWOO
..OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO
.OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwO
OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwO
OWWWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwffO
OWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwwffO
OWWWWWWWWWWWWWWWWWWWWwwwwwwwwwwffO
OWWWWWWWWWWWWWWWWWwwwwwwwwwwwwffO
OWWWWWWWWWWWWWWwwwwwwwwwwwwwwffO
OWWWWWWWWWWWwwwwwwwwwwwwwwffffO
OWWWWWWWWwwwwwwwwwwwwwwffffnnO
OWWWWWwwwwwwwwwwwwwwffffnnndO
OWWWwwwwwwwwwwwwwwfffnddddOO
OWWwwwwwwwwwwwwfffnddddOOO
.OWWwwwwwwwwffffndddOOO
..OwwwwwwffffnddOOOO
...OwwffffnddOOOO
....OOOOOOOOOO
''')
SLEEP_HEAD=(55,62,'''
......OOO
.....OWWwwO
.....OWWfwO
......OWfnwO
.......OWnRwO
........OWfnwwO.......OOO
........OWWwwwO......OWwwO
......OOWWWWWWWOOOOOOWfnwO
....OOWWWWWWWWWWWWWWWfnwO
...OWWWWWWWWWWWWWWWWWWWwwO
..OWWWWWWWWWWWWWWWWWWWWwwfO
.OWWWWWWWWWWWWWWWWWWWWwwfnwO
OWWWWWWWWWWWWWWWWWWWWwwfnnwOO
OWWWWWWWWWWWWWWWWWWWwwwfKKnnwOO
OWWWWWWWWWWWWWWWWWwwwwffnwwwwWWOO
OWWWWWWWWWWWWWWWwwwwwwwWWWWWWWWWKO
OWWWWWWWWWWWWwwwwwwWWWWWWWWWWwwnOO
OWWWWWWWWWwwwwwwWWWWWWWWwwnnOOOO
OWWWWWWwwwwwwWWWWWWwwwfffOOOO
OWWWWWwwwwwWWWWWwwwwfffndOO
OWWWWwwwwwwwwwwwffffnnddO
OWWWwwwwwwwffffnnnddddO
OWWwwwwffffnnnddddOOO
.OwwfffnddddOOOOOO
..OOOOOOOOOO
''')
sla=canvas();folded(sla,curled=True);block(sla,*SLEEP_BODY);block(sla,*SLEEP_HEAD)
# Neck joins the curled shoulder in a broad plane; closed eye stays a 2px crease.
patch(sla,55,75,'''
WWWWWWW
WWWWWWW
WWWWWWw
WWWWWww
WWWWwww
WWWwwww
WWwwwww
Wwwwwff
wwwwfff
wwwffff
''')
block(sla,61,87,'''
OwwwwwwwwfO
OWWWWWWWWwfO
OWWnWWnWWwfO
.OOOOOOOOO
''')
block(sla,38,88,'''
OwwwwwwwffO
OWWWWWWWwwfO
OWWnWWnWwwfO
.OOOOOOOOOO
''')
# Tail folds across the tucked rear hock and terminates in an ample ivory tip.
block(sla,27,82,'''
ORccccrO
ORcssccrOO
ORcssssccrOO
.ORcssssccrOO
..ORcssssccrrOO
...ORcssssccrrrOO
....ORcssssccwffwOO
.....ORcsssswWWWwwO
......ORcsswWWWWWwO
.......ORcwWWWWWwwO
........OOOOOOOOOO
''')
block(sla,50,82,'''
GYYggGG
GYgjjgYG
GgjWJjgG
.GgjJggG
..GggGRccR
....RccssccR
.....RccssccR
......RrrrrR
''')
save('sleep_a',sla,True)
slb=copied(sla)
# Breath expands the actual flank locally, not the frame or whole body.
patch(slb,32,65,'''
..OOOOOOOOOOOOOOOOOO
OWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWW
''')
patch(slb,48,77,'''
WWWWWWWWWww
WWWWWWWWwww
WWWWWWWwwww
WWWWwwwwwww
WWwwwwwwwff
Wwwwwwwwfff
wwwwwwwffff
wwwwwwffffn
''')
# Ear relaxes and shut eye remains a dark shallow horizontal crease.
patch(slb,60,63,'''
OWWwwO.
OWWfwO.
.OWfnwO
..OWnRw
''')
patch(slb,74,75,'ffnKKnnw')
patch(slb,63,87,'''
OwwwwwwwwfO
OWWWWWWWWwfO
OWWnWWnWWwfO
.OOOOOOOOO.
''')
patch(slb,56,87,'''
RccssccR
.RccsccR
..RrrrrR
...RRR..
''')
save('sleep_b',slb,True)

# Broader selected upper-left lit planes on the tall tail fan. These patches alter
# only their own tail surfaces; each final frame remains a full literal grid.
TAIL_PLANES=[(40,23,'ppssc'),(40,24,'psssc'),(40,25,'ssccc'),(41,26,'scccr'),
             (26,32,'psssccr'),(27,33,'ppssccr'),(27,34,'psssccr'),
             (50,29,'pssccr'),(50,30,'ppccrr'),(50,31,'ssccrr'),
             (19,42,'pscc'),(20,43,'sccr'),(8,49,'pppsss'),(9,50,'ppssss')]
for name,frame,is_action in [('idle_a',BASE,False),('idle_b',b,False),('idle_c',c,False),('recover',u,False),('hit',h,False),('skill_a',sa,True),('skill_b',sb,True),('skill_c',sc,True)]:
    for x,y,rows in TAIL_PLANES: block(frame,x,y,rows)
    save(name,frame,is_action)
render(BASE,ROOT/'progress/idle.png');render(BASE,ROOT/'progress/idle-4x.png',4)

patch(stb,54,87,"..\n..\n..\n..")
save('stun_b',stb,True)

for name,frame in [('idle_a',BASE),('idle_b',b),('idle_c',c)]:
    block(frame,55,53,EMBER)
    save(name,frame)
render(BASE,ROOT/'progress/idle.png');render(BASE,ROOT/'progress/idle-4x.png',4)
