export const CASTLE_PLACE_REFERENCES = [{
  id: 'river-fortress-160x144', name: '강변 성채', kind: 'completed-place' as const,
  placeKind: 'settlement' as const, revision: 1, x: 0, y: 0, width: 160, height: 144,
  tilesetId: 'castle_courtyard_harbor',
  preview: '/assets/region-references/river-fortress.png',
  tilesetPreview: '/assets/region-references/river-fortress-atlas.png',
  projectDownload: '/assets/region-references/river-fortress.oprn.json',
  sourceProjectId: 'castle-fortress-city-20260921', sourceMapId: 'grand-river-fortress',
  snapshotProjectId: 'oprn-place-river-fortress-v1',
  rules: [
    '중하부 본성, 고목 뒤뜰, 넓은 동쪽 강과 두 척의 배를 연결한 160×144 성채.',
    '남쪽 성 밖은 사용자가 선호한 개선1의 석조 건물과 정돈된 길 배치를 보존한다.',
    '칩셋과 NPC 대화를 포함한 맵 파일을 내려받을 수 있다. 다른 프로젝트에서도 공용 장소로 조회한다.',
  ],
  limitations: '배치 참고 장소. 본성 실내·승선·강 건너 쉼터로 가는 길은 포함하지 않는다. 참고 이미지의 돌다리는 제외했다.',
}, ...[
  { id: 'castle-courtyard', name: '고목·분수 뒤뜰', width: 64, height: 36,
    rules: ['고목과 분수, 노점, 포장과 녹지를 함께 구성한 성채 뒤뜰.', '상인과 안내인, 정원사의 대화를 포함한다.'] },
  { id: 'castle-small-harbor', name: '나룻배 두 척과 작은 선착장', width: 36, height: 22,
    rules: ['두 척의 배와 목제 선착장, 화물 소품을 묶은 작은 나루.', '나루 관리인의 대화를 포함한다. 승선 기능은 없다.'] },
  { id: 'castle-stone-lodge', name: '석조 관리소와 진입길', width: 46, height: 20,
    rules: ['사용자가 선택한 개선1의 석조 건물과 정돈된 진입길.', '남문 안내인과 가로등, 수목을 포함한다. 건물 실내는 없다.'] },
].map(({ id, name, width, height, rules }) => ({
  id, name, kind: 'completed-place' as const, placeKind: 'settlement' as const,
  revision: 1, x: 0, y: 0, width, height,
  tilesetId: 'castle_courtyard_harbor', preview: `/assets/region-references/${id}.png`,
  tilesetPreview: '/assets/region-references/river-fortress-atlas.png',
  projectDownload: `/assets/region-references/${id}.oprn.json`,
  sourceProjectId: 'castle-fortress-city-20260921', sourceMapId: 'grand-river-fortress',
  snapshotProjectId: `oprn-place-${id}-v1`, rules,
  limitations: '강변 성채에서 분리한 배치 참고 장소. 칩셋 포함 맵을 내려받을 수 있다. 구역 밖 이동·실내·승선은 포함하지 않는다.',
}))];
