export {
  DEFAULT_ACTOR_ID,
  DEFAULT_ANIMATION_ID,
  DEFAULT_CLASS_ID,
  DEFAULT_ENEMY_ID,
  DEFAULT_EQUIPMENT_ID,
  DEFAULT_ITEM_ID,
  DEFAULT_SKILL_ID,
  DEFAULT_SOLID_TILES,
  DEFAULT_EASYRPG_CHARSET_ID,
  DEFAULT_SPRITE_FRAME_HEIGHT,
  DEFAULT_SPRITE_FRAME_WIDTH,
  DEFAULT_STATE_ID,
  DEFAULT_TILE_COUNT,
  DEFAULT_TILE_SIZE,
  DEFAULT_TILESET_ID,
  DEFAULT_TILESET_NAME,
  DEFAULT_TILESET_TEXTURE_KEY,
  DEFAULT_TILES_PER_ROW,
  DEFAULT_TROOP_ID,
  LEGACY_RM_TILESET_ID,
  LEGACY_RM_TILESET_NAME,
  LEGACY_RM_TILESET_TEXTURE_KEY,
  TILE,
} from "./defaults/constants";
export {
  defaultAssetSet,
  defaultResourceProfiles,
  defaultSprites,
  defaultTilesets,
  defaultTileset,
  ensureBundledResourceProfiles,
  ensureBundledTilesets,
  removeLegacyRmTileset,
} from "./defaults/defaultAssets";
export {
  POKEMON_OVERWORLD_PRESET,
  pokemonPresetRole,
  pokemonPresetGroupIds,
  pokemonPresetRoleLabels,
  type PokemonChipsetPreset,
  type PokemonPresetRole,
  type PokemonPresetTool,
} from "./defaults/pokemonChipsetPreset";
export { repairInteriorTransparentPropLayers } from "./defaults/interiorTransparentPropLayerRepair";
export { createStarterHouseInteriorMap } from "./defaults/starterHouseTransfer";
export {
  defaultDatabase,
  defaultSession,
  defaultSystem,
  defaultTerms,
} from "./defaults/defaultDatabase";
export {
  createBlankMap,
  createDbExtractedHouseTemplateMap,
  createLogCabinShowcaseMap,
  createRetroHouseShowcaseMap,
  createSmallHouseVariantMap,
  createSmallHouseVariantMaps,
  createTownArchitectureCityMap,
  createTownArchitectureTestMap,
  createTownCityShowcaseMap,
  createTownHouseShowcaseMap,
  createStarterMap,
  singleNodeTree,
  type SmallHouseVariantIndex,
  type TownHouseShowcaseStyle,
} from "./defaults/defaultMaps";
export {
  createBlankProject,
  createDbExtractedHouseTemplateProject,
  createFarmingDemoProject,
  createHouseTemplateGalleryProject,
  createLogCabinShowcaseProject,
  createMarketTownProject,
  createVillageShoppingStreetProject,
  createRetroHouseShowcaseProject,
  createSampleAdventureProject,
  createScarloxyDemoProject,
  createScarloxyPokemonDemoProject,
  createSnowMountain60Project,
  createIcePlain64Project,
  createTrainingExamplesProject,
  createShopShowcaseProject,
  createSmallHouseVariantProject,
  createTownArchitectureCityProject,
  createTownArchitectureTestProject,
  createTownCityShowcaseProject,
  createTownHouseShowcaseProject,
  ensureSwitchVariableSlots,
} from "./defaults/defaultProject";
export { createModernNocturneProject } from "./defaults/modernNocturneGame";

// 《천공의 계단》 — 비주얼 중심 7층 JRPG. 배럴에서 바로 내보내 에디터 메뉴가 쓴다.
export {
  createSkyStairProject,
  SKY_BATTLE_BG,
  SKY_BGM,
  SKY_ENEMY_IDS,
  SKY_ITEM,
  SKY_MAP,
  SKY_SWITCH,
  SKY_TITLE,
  SKY_TROOP,
  SKY_VARIABLE,
} from "@/editor/content/skyStairGame";
