// Generated by scripts/content/prepare-diverse-village-regions.mjs from a canonical reload.
export const DIVERSE_VILLAGE_REGIONS = [
  {
    "id": "pine-hamlets-80x64",
    "name": "솔바람 흩어진 산촌",
    "kind": "completed-map",
    "regionKind": "settlement",
    "revision": 1,
    "width": 80,
    "height": 64,
    "tilesetId": "forest_harmony",
    "preview": "/assets/region-references/pine-hamlets.png",
    "projectDownload": "/assets/region-references/pine-hamlets.oprn.json",
    "sourceProjectId": "44d88b94-58eb-4dee-a11a-88737da7001b",
    "sourceMapId": "pine-hamlets",
    "snapshotProjectId": "oprn-region-pine-hamlets-v1",
    "rules": [
      "세 빈터에 흩어진 집, 두 둔덕, 갈라지는 오솔길과 작은 샘.",
      "집 7채의 문 앞과 계단 2곳을 시작점에서 연결한다.",
      "숲마을 · 거리별 잔디 기반. 검수한 집과 3행 숲 몸통을 재사용하고 지형·길·집 원점은 새로 설계했다.",
      "절벽·계단은 레트로 월드맵 원본 21칸을 명시적으로 이식한다. 다운로드의 tileGrafts와 통행 정보를 함께 사용한다.",
      "공용 AI 문서 「다양한 마을 · 산촌·절벽·포구」에 원본 좌표·모든 배열·조립 순서·정상/오류 비교와 검증 명령이 있다."
    ],
    "limitations": "새로 저작한 외관·타일 통행 참고 사례. 실내·NPC·문 전이 이벤트는 포함하지 않는다. 자동 생성 프리셋이 아니다."
  },
  {
    "id": "terrace-cliff-village-88x72",
    "name": "층바위 절벽마을",
    "kind": "completed-map",
    "regionKind": "settlement",
    "revision": 1,
    "width": 88,
    "height": 72,
    "tilesetId": "forest_harmony",
    "preview": "/assets/region-references/terrace-cliff-village.png",
    "projectDownload": "/assets/region-references/terrace-cliff-village.oprn.json",
    "sourceProjectId": "44d88b94-58eb-4dee-a11a-88737da7001b",
    "sourceMapId": "terrace-cliff-village",
    "snapshotProjectId": "oprn-region-terrace-cliff-village-v1",
    "rules": [
      "세 높이의 대지, 네 계단과 절벽 아래 작업 마당.",
      "집 8채의 문 앞과 계단 4곳을 시작점에서 연결한다.",
      "숲마을 · 거리별 잔디 기반. 검수한 집과 3행 숲 몸통을 재사용하고 지형·길·집 원점은 새로 설계했다.",
      "절벽·계단은 레트로 월드맵 원본 21칸을 명시적으로 이식한다. 다운로드의 tileGrafts와 통행 정보를 함께 사용한다.",
      "공용 AI 문서 「다양한 마을 · 산촌·절벽·포구」에 원본 좌표·모든 배열·조립 순서·정상/오류 비교와 검증 명령이 있다."
    ],
    "limitations": "새로 저작한 외관·타일 통행 참고 사례. 실내·NPC·문 전이 이벤트는 포함하지 않는다. 자동 생성 프리셋이 아니다."
  },
  {
    "id": "reed-bay-village-88x64",
    "name": "갈대물굽이 포구",
    "kind": "completed-map",
    "regionKind": "settlement",
    "revision": 1,
    "width": 88,
    "height": 64,
    "tilesetId": "forest_harmony",
    "preview": "/assets/region-references/reed-bay-village.png",
    "projectDownload": "/assets/region-references/reed-bay-village.oprn.json",
    "sourceProjectId": "44d88b94-58eb-4dee-a11a-88737da7001b",
    "sourceMapId": "reed-bay-village",
    "snapshotProjectId": "oprn-region-reed-bay-village-v1",
    "rules": [
      "물굽이를 따라 비껴 앉은 집, 좁은 골목과 긴 선착장.",
      "집 8채의 문 앞과 계단 1곳을 시작점에서 연결한다.",
      "숲마을 · 거리별 잔디 기반. 검수한 집과 3행 숲 몸통을 재사용하고 지형·길·집 원점은 새로 설계했다.",
      "절벽·계단은 레트로 월드맵 원본 21칸을 명시적으로 이식한다. 다운로드의 tileGrafts와 통행 정보를 함께 사용한다.",
      "공용 AI 문서 「다양한 마을 · 산촌·절벽·포구」에 원본 좌표·모든 배열·조립 순서·정상/오류 비교와 검증 명령이 있다."
    ],
    "limitations": "새로 저작한 외관·타일 통행 참고 사례. 실내·NPC·문 전이 이벤트는 포함하지 않는다. 자동 생성 프리셋이 아니다."
  }
] as const;
