// Generated by scripts/content/prepare-elf-treetop-regions.mjs from a canonical reload.
// The elf treetop village under 장소; snapshot in regionReferences/elf-treetop.json.
export const ELF_TREETOP_PLACE_REFERENCES = [
  {
    "id": "elf-treetop-village-52x40",
    "name": "엘프 나무 위 마을",
    "kind": "completed-place",
    "placeKind": "settlement",
    "revision": 1,
    "x": 0,
    "y": 0,
    "width": 52,
    "height": 40,
    "tilesetId": "forest_harmony",
    "preview": "/assets/region-references/elf-treetop-village.png",
    "tilesetPreview": "/assets/elf-treetop/treetop-parts.png",
    "projectDownload": "/assets/region-references/elf-treetop-village.oprn.json",
    "sourceProjectId": "f17f94c1-648e-408c-9520-f672414998a7",
    "sourceMapId": "elf-treetop-village",
    "snapshotProjectId": "oprn-place-elf-treetop-village-v1",
    "rules": [
      "우듬지 위 판자 데크 여섯 곳(장로 나무 광장·줄기 집 셋·정원·입구)을 밧줄 다리로 잇는 엘프 마을. 데크 사이로 아래 깊은 숲이 어둡게 내려다보이고, 큰 나무 줄기에 둥근 창과 아치 문을 낸 집이 저마다 수관을 이고 선다. 남쪽 입구 데크에서 밧줄 사다리로 숲 바닥에 내려가고, 동쪽 밧줄 다리는 맵 밖으로 이어진다.",
      "출구: 남쪽 (25,39) → 숲 바닥(밧줄 사다리 아래), 동쪽 (51,24) → 동쪽 밧줄 다리 너머 다음 맵.",
      "줄기 집 4채: 장로 나무 문 (25,15), 북서 줄기 집 문 (8,11), 북동 줄기 집 문 (43,12), 여관 줄기 집 문 (42,23). 문 앞 칸은 비워 두었다.",
      "숲마을 타일셋에 나무 위 마을 칸(3131~3310: 데크 오토타일·밧줄 다리·줄기 집·사다리·요정 등불·깊은 숲)을 이식해 그렸다. 새 프로젝트와 기존 프로젝트 모두 불러올 때 이 칸이 생긴다.",
      "사다리 아래 입구에서 모든 문 앞·출구까지 런타임 이동 규칙으로 닿는 것을 확인했다.",
      "공용 AI 문서 「엘프 나무 위 마을 · 데크·밧줄 다리·줄기 집 (개정1)」에 조립 순서·번호·전체 배열·사용 타일 사전이 있다."
    ],
    "limitations": "지형·마을 외관 참고 사례. 문 이동·NPC·이벤트는 포함하지 않는다. 자동 생성 프리셋이 아니다."
  }
] as const;
