// Generated by scripts/content/jp-city/maps/shopstreet.mjs · town.mjs --publish. 일본 도시(jp_city) 예제 under 장소; snapshots in regionReferences/jp-city-*.json.
export const JP_CITY_PLACE_REFERENCES = [
  {
    "id": "jp-city-shopstreet-48x40",
    "name": "일본 도시 · 상가 거리 (간선 교차로·생활도로·건널목)",
    "kind": "completed-place",
    "placeKind": "settlement",
    "revision": 2,
    "x": 0,
    "y": 0,
    "width": 40,
    "height": 32,
    "tilesetId": "jp_city",
    "preview": "/assets/region-references/jp-city-shopstreet.png",
    "tilesetPreview": "/assets/jp-city/jp-city-chipset.png",
    "projectDownload": "/assets/region-references/jp-city-shopstreet.oprn.json",
    "sourceProjectId": "oprn-bundled-jp-city-shopstreet",
    "sourceMapId": "jp-city-shopstreet",
    "snapshotProjectId": "oprn-place-jp-city-shopstreet-v1",
    "rules": [
      "40×32칸 상가 거리. 오른쪽 아래에 간선 4차선 교차로(키트 jp-road-trunk-x, 신호기·정지선·화살표·횡단보도 포함)의 북서 사분면이 걸치고(동·남 팔과 반대편 차로는 맵 밖으로 잘렸다), 왼쪽 위로 생활도로(폭 4칸, 보도 없음)가 동서·남북으로 뻗는다. 동서 길에는 생활도로 횡단보도 키트 1곳(jp-road-lane-crosswalk-h). 건물 8채·소품 14개·코인 파킹 1곳. 아스팔트 비율 47%.",
      "구역마다 앵커가 하나다: 편의점이 선로 곁 모퉁이를 잡고, 셔터 점포·카페·마치야·편의점·사무소 5채가 동서 길 북쪽 줄(문은 포장 앞마당에 면함)을 이루며, 단층 점포 3채와 상점가 아치(남북 골목의 입구)가 간선 보도에 면한다. 건널목(경보기 둘·올라간 차단기)은 동서 길과 남북 선로가 만나는 한 곳이고 선로 양옆은 철망 담이다.",
      "간선·건널목·아치·소품은 키트 격자 그대로 찍고(타일은 1층, 위층 칸은 3층), 생활도로·선로·철망은 오토타일 엔진 규칙(autotileNeighborMask)으로 칸마다 마스크를 계산해 썼다. 건물은 건물 조립기 결과다(뒷줄 먼저, 앞줄 나중).",
      "문 17개의 접근칸이 모두 한 길망(시작 (28,12) 기준 걸을 수 있는 1107칸 전부 도달)에서 이어지고, 건물 몸채 74칸은 엔진 통행이 모두 막는다.",
      "공용 AI 문서가 아니라 조립 예제다 — 키트 id·원점·건물 입력은 openwiki/jp-city.md 와 scripts/content/jp-city/maps/shopstreet.plan.md 를 본다."
    ],
    "limitations": "지형·건물·소품 배치 참고 사례. 움직이는 열차·차·행인·이벤트는 없다. 간선 교차로는 북서 사분면만 있고 동·남 팔·반대편 차로·신호기 둘(북동·남쪽)은 맵 밖이다(보이는 신호기 1기). 노면 글자 止まれ 는 키트(jp-road-mark-tomare-*)만 있고 이 맵에는 쓰지 않았다(180° 돌려야 해서 읽히지 않음). 생활도로·선로·철망 키트 칸 근처를 에디터에서 다시 칠하면 연결 목록에 키트 칸이 없어 끝막이로 바뀔 수 있다, 선로는 위 모서리에서 들어와 건널목을 지나 간선 보도 앞에서 끝막이로 끝나는 측선이다. 주택·역·공원·신사는 쓰지 않았다. 자동 생성 프리셋이 아니다."
  },
  {
    "id": "jp-city-town-96x80",
    "name": "일본 도시 · 동네 한 장 (역 앞·상점가·주택가·신사·학교·공원)",
    "kind": "completed-place",
    "placeKind": "settlement",
    "revision": 1,
    "x": 0,
    "y": 0,
    "width": 96,
    "height": 80,
    "tilesetId": "jp_city",
    "preview": "/assets/region-references/jp-city-town.png",
    "tilesetPreview": "/assets/jp-city/jp-city-chipset.png",
    "projectDownload": "/assets/region-references/jp-city-town.oprn.json",
    "sourceProjectId": "oprn-bundled-jp-city-town",
    "sourceMapId": "jp-city-town",
    "snapshotProjectId": "oprn-place-jp-city-town-v1",
    "rules": [
      "96×80칸 일본 동네 한 장. 위에서 아래로 띠를 쌓았다: 선로·철망 → 역 앞 줄(交番·역 앞 상가 줄·작은 역사·편의점·코인 주차·우체국·의원) → 역 앞 판석 광장 → 간선(4줄, 역 앞 횡단보도·버스·택시) → 상점가 북쪽 줄(벽 맞댄 상가 줄 키트, 셔터 가게 섞임, 입구 아치 둘) → 상점가 판석 길 → 둘째 줄(銭湯·코인 세탁소·상가 줄·町工場·슈퍼) → 생활도로 1 → 주택가(블록 담·대문·카포트) → 생활도로 2 → 신사(拝殿·도리이·석등)·小学校(교사·체육관·운동장·정문)·공원 → 생활도로 3.",
      "생활도로(폭 4칸, 보도 없음)는 가장자리 칸에 側溝 뚜껑 + 路側帯 흰 선(2층 투명 덧그림)을 깔고 7칸마다 グレーチング, 남북 길 가운데에 주황 「30」. 전봇대는 생활도로 1·2·3 남쪽 가장자리에 서고(간격 5~20칸 중 간판·창을 덜 가리는 자리 — poleRow 비용 최소화) 전선(jp-wire-L, 왼쪽 전봇대 x+3·맨 위 줄)이 이어진다 — 건물 앞에 서므로 전봇대·전선은 4층이다. 상점가 판석 길은 노보리·입간판·화분·자전거, 주택가는 블록 담·문기둥·카포트·프로판 봄베·실외기, 신사는 拝殿·도리이·手水舎·석등·참배길.",
      "건물은 손 도트 통 키트(jp-bldg-*)를 키트 격자 그대로 찍었고(3층), 생활도로·선로·철망은 오토타일 엔진 규칙으로 마스크를 계산해 썼다. 문은 모두 길(상점가 판석·생활도로·간선 보도)에 면하고 접근칸이 한 길망으로 이어진다.",
      "문 46개 접근칸 전부 시작 (41,12) 에서 도달, 막힘 칸 845개 전부 엔진이 막는다.",
      "공용 AI 문서가 아니라 조립 예제다 — 키트 id·좌표는 scripts/content/jp-city/maps/town.mjs 를 본다."
    ],
    "limitations": "열차·차·행인·이벤트 없음(차·버스는 세워 둔 소품). 건물은 정면 하나라 남쪽 줄 건물은 북쪽 길에서 지붕만 보인다. 남북 골목의 아치는 간선 쪽 입구에만 있다. 밤 조명 없음. 자동 생성 프리셋이 아니다."
  }
] as const;
