// Generated by scripts/content/jp-city/maps/shopstreet.mjs --publish. 일본 도시(jp_city) 상가 거리 예제 under 장소; snapshot in regionReferences/jp-city-shopstreet.json.
export const JP_CITY_PLACE_REFERENCES = [
  {
    "id": "jp-city-shopstreet-48x40",
    "name": "일본 도시 · 상가 거리 (간선 교차로·생활도로·건널목)",
    "kind": "completed-place",
    "placeKind": "settlement",
    "revision": 2,
    "x": 0,
    "y": 0,
    "width": 40,
    "height": 32,
    "tilesetId": "jp_city",
    "preview": "/assets/region-references/jp-city-shopstreet.png",
    "tilesetPreview": "/assets/jp-city/jp-city-chipset.png",
    "projectDownload": "/assets/region-references/jp-city-shopstreet.oprn.json",
    "sourceProjectId": "oprn-bundled-jp-city-shopstreet",
    "sourceMapId": "jp-city-shopstreet",
    "snapshotProjectId": "oprn-place-jp-city-shopstreet-v1",
    "rules": [
      "40×32칸 상가 거리. 오른쪽 아래에 간선 4차선 교차로(키트 jp-road-trunk-x, 신호기·정지선·화살표·횡단보도 포함)의 북서 사분면이 걸치고(동·남 팔과 반대편 차로는 맵 밖으로 잘렸다), 왼쪽 위로 생활도로(폭 4칸, 보도 없음)가 동서·남북으로 뻗는다. 동서 길에는 생활도로 횡단보도 키트 1곳(jp-road-lane-crosswalk-h). 건물 8채·소품 14개·코인 파킹 1곳. 아스팔트 비율 47%.",
      "구역마다 앵커가 하나다: 편의점이 선로 곁 모퉁이를 잡고, 셔터 점포·카페·마치야·편의점·사무소 5채가 동서 길 북쪽 줄(문은 포장 앞마당에 면함)을 이루며, 단층 점포 3채와 상점가 아치(남북 골목의 입구)가 간선 보도에 면한다. 건널목(경보기 둘·올라간 차단기)은 동서 길과 남북 선로가 만나는 한 곳이고 선로 양옆은 철망 담이다.",
      "간선·건널목·아치·소품은 키트 격자 그대로 찍고(타일은 1층, 위층 칸은 3층), 생활도로·선로·철망은 오토타일 엔진 규칙(autotileNeighborMask)으로 칸마다 마스크를 계산해 썼다. 건물은 건물 조립기 결과다(뒷줄 먼저, 앞줄 나중).",
      "문 17개의 접근칸이 모두 한 길망(시작 (28,12) 기준 걸을 수 있는 1107칸 전부 도달)에서 이어지고, 건물 몸채 74칸은 엔진 통행이 모두 막는다.",
      "공용 AI 문서가 아니라 조립 예제다 — 키트 id·원점·건물 입력은 openwiki/jp-city.md 와 scripts/content/jp-city/maps/shopstreet.plan.md 를 본다."
    ],
    "limitations": "지형·건물·소품 배치 참고 사례. 움직이는 열차·차·행인·이벤트는 없다. 간선 교차로는 북서 사분면만 있고 동·남 팔·반대편 차로·신호기 둘(북동·남쪽)은 맵 밖이다(보이는 신호기 1기). 노면 글자 止まれ 는 키트(jp-road-mark-tomare-*)만 있고 이 맵에는 쓰지 않았다(180° 돌려야 해서 읽히지 않음). 생활도로·선로·철망 키트 칸 근처를 에디터에서 다시 칠하면 연결 목록에 키트 칸이 없어 끝막이로 바뀔 수 있다, 선로는 위 모서리에서 들어와 건널목을 지나 간선 보도 앞에서 끝막이로 끝나는 측선이다. 주택·역·공원·신사는 쓰지 않았다. 자동 생성 프리셋이 아니다."
  }
] as const;
