// Generated by src/harnesses/modern-chipset/bake_map.py --publish. The modern city example under 장소; snapshot in regionReferences/modern-city.json.
export const MODERN_CITY_PLACE_REFERENCES = [
  {
    "id": "modern-city-60x60",
    "name": "현대 도시 · 도쿄풍 예제 거리",
    "kind": "completed-place",
    "placeKind": "settlement",
    "revision": 1,
    "x": 0,
    "y": 0,
    "width": 60,
    "height": 60,
    "tilesetId": "modern_city",
    "preview": "/assets/region-references/modern-city.png",
    "tilesetPreview": "/assets/modern-city/modern-city-chipset.png",
    "projectDownload": "/assets/region-references/modern-city.oprn.json",
    "sourceProjectId": "oprn-bundled-modern-city",
    "sourceMapId": "modern-city-example",
    "snapshotProjectId": "oprn-place-modern-city-v1",
    "rules": [
      "가로 도로 둘·세로 도로 하나(6칸 폭, 노란 이중 중앙선)가 만나는 60×60칸 도시 거리. 교차로마다 횡단보도 네 곳·정지선·직진 화살표가 있고 도로 위 차량은 정차 그림이다. 공원 한 곳(분수·연못·화단·벽돌 광장)과 건물 23채.",
      "건물은 모두 키트 하나를 통째로 3층(upperTiles)에 찍었다(변형 대체 0, 키트 그림과 화소 일치). 뒷줄 건물이 먼저, 앞줄이 나중이라 앞줄 지붕이 뒷줄 몸통 아래를 덮는다. 문 앞 한 줄 아래 칸은 모두 보도다.",
      "땅(아스팔트·보도·연석·횡단보도·공원)은 1층, 도로 표시·접지 그림자는 2층(lowerOverlayTiles), 소품·차량은 3층이고 한 칸에 둘이 겹칠 때만 4층. 사람(Actor1)·전선은 타일이 아니라 넣지 않았다.",
      "시작 위치 (20,12)에서 문 앞 접근 칸 54곳 모두 런타임 이동 규칙(canMove)으로 닿는 것을 확인했다. 소품·차량이 접근 칸 길을 막는 5곳은 한 칸 옮기고 2곳은 뺐다.",
      "공용 AI 문서 「현대 도시 · 완성 예제」에 배치 목록·네 층 전체 배열이, 「조립 정답」에 건물·도로 키트 배열이 있다."
    ],
    "limitations": "지형·건물·소품 배치 참고 사례. 움직이는 차·행인·문 이동·NPC 이벤트는 포함하지 않는다. 소품·차량은 16px 칸에 맞춰 원본 그림에서 최대 8px 옮겨 앉았고 연석 주차 칸 표시(ㄴ자 틱)는 칸이 없어 뺐다. 자동 생성 프리셋이 아니다."
  }
] as const;
