from pathlib import Path

ROOT = Path(__file__).resolve().parent

def write(name, start, block):
    # Only literal authored rows, with transparent canvas padding.
    content = block.strip('\n').splitlines()
    assert all(len(row) <= 64 for row in content), name
    assert start + len(content) <= 61, (name, start, len(content))
    rows = ['.' * 64 for _ in range(64)]
    for y, row in enumerate(content, start):
        rows[y] = row.ljust(64, '.')
    (ROOT / 'actions' / (name + '.pxgrid')).write_text('\n'.join(rows) + '\n')

write('poison_a', 11, '''
...........................KKKK
.........................KHMMLHK
........................KHMLMMHHK
.......................KHMMHYYHHHK
......................KHMMHYAYHHHHK
.....................KHHMHHHGHHHHHHK
..........JAJ........KHHHHHSSSSSPHHHK
.........JAEAJ......KHHHHHSSSSSSSPHHK
.........JA.JJ......KHHHHMPSSSSSSSSPK
..........JJ.......KHHHHHMPSSSRRSSRRPK
...................KHHHHHMPSSSSSSSSSPK
..................KHHHHHHMPSSRRKSSRRKPK
..................KHHHHHHMPSSPSSSSSPSK
.................KHHMMHHHHMPSSSSSSSSPPK
.................KHHMMHHHHHPSSSSSRRPK
................KHHMMHHHHHHPPSSSSPK
................KHHMMHHHHHHHPPPPK
...............KHHMMHHHHHKBWSSPK
...............KHHMHHHKBVWWCPCBK
..............KHHMHHKCVWWWWVCJVCBK
.............KHHMHKCVWWWWWVCJTVCWK
............KHHMHKCVWWWWWVYGJTVCWVK
............KHHHKCVWWWWVCYGTTJVCWVCK
............KHHHKCVWWVCYGTTTTJVCWVBK...............JJ
............KHHMKCVWVCYGTTTTTJVCVBCBK.............JAAJ
............KHHMKCVVCYGTTTTTTJVCBCWWK.............JA.J
............KHHHKCVBCYGTTTSSPPJVCWCVWK............JJ
............KHHHKCVBCYGTSSSSPPVCWWCVBK
............KHHHKCVBCYGTTTPPPKVCWSSPPKG
.............KHHKCBGYYYYYYGJAYYSSSPPKGY
.............KHHKBCGYYGTTTTAJYPPPPKGKIE
.............KHHKCVWWYGTTTJAJYVCBK..KIEK
.............KHHKCVWWVYGTTJATYWWVBK...KIEK
.............KHMKCVWWWVYGTTJATYWWVCK....KIEK
.............KHMKCVWWWVCYGTTATYWWWWVCK....KIEK
.............KHHKCVWWWVCYGTTTTYVWWWWVCK.....KIEK
..............KHKCVWWWWCYGTTTTYVWWWWVCK.......KIEK
...............KCVWWWWCYGTTTTTTYVWWWWVCK.......KIEK
...............KCVWWWYGTTTTTTTTTYVWWWVCK........KIEK
..............KCVWWWVYGTTTTTTTTTTYVWWVCK..........KIEK
.............KCVWWWVYGTTTTTTTTTTTYVVVCK............KIE
............KCVWWWVYGTTTTTTKTTTTTTYWVCK
............KCVWWWYGTTTTTTKK.KTTTTTYWVK
.............KCVWYGTTTTTTK....KTTTTTYWVK
..............KCYGTTTTTTK......KTTTTTYVCK
...............KTTTTTTTK........KTTTTYGCK
...............KHLLHHK..........KTTTTYKK
..............KHMMHHK...........KHLLHHK
..............KHMMHHK...........KHMMHHHK
.............KKKKKKK..........KKKKKKKKK
''')

write('poison_b', 13, '''
.............................KKKK
...........................KHMMLHK
..........................KHMLMMHHK
.........................KHMMHYYHHHK.............JA
........................KHMMHYAYHHHHK..........JAEAJ
.......................KHHMHHHGHHHHHHK.........JA..AJ
......................KHHHHHHSSSSSPHHHK.........JJJ
.....................KHHHHHHSSSSSSSPHHK
....................KHHMHHHMPSSSSSSSSPK
...................KHHMMHHHMPSSSRRSSRRPK
..................KHHMMHHHHMPSSSSSSSSSSPK
..................KHHMMHHHHMPSSRRRSSRRRPK
.................KHHMMHHHHHHMPSSPSSSSSPSK
.................KHHMMHHHHHHHMPSSSSSSSSPPK
................KHHMMHHHHHHHHPSSSSSRRPK
................KHHMMHHHHHHHHHPPSSSSPK
...............KHHMMHHHHHHHHHHHPPPPK
...............KHHMMHHHHHHKBWWSSPK
..............KHHMHHHHHKBVWWWCPCBK
.............KHHMHHHKCVWWWWWVCJVCBK
............KHHMHHKCVWWWWWWVCJTVCWK
............KHHMHKCVWWWWWVYGTTJVCWVK
............KHHHKCVWWWWVCYGTTTJVCWVCK
............KHHKCVWWWVCYGTTTTTJVCWVBK
............KHHKCVWWVCYGTTTTTTJVCVBCBK
.............KHHKCVWVCYGTTSSPPJVCBCWWK
.............KHHKCVVCYGTSSSSPPVCWCVWK
.............KHHKCVBCYGTTTPPPKVCWWCVBK
..............KHKCBGYYYYYYGJAYVCWWVCK
.........JA....KBCGYYGTTTTAJYVVCWSSPPKG
........JAEJ...KCVWWYGTTTJAJYVVWSSSPPKGY
.........JJ....KCVWWVYGTTJATYVVVPPPPKGKIE
...............KCVWWWVYGTTATYWWVVCBK..KIEK
...............KCVWWWVCYGTTTTYVWWWWVCK...KIEK
..............KCVWWWWVCYGTTTTTYVWWWWVCK....KIEK
.............KCVWWWWWVCYGTTTTTTYVWWWWWVCK....KIEK
............KCVWWWWWWCYGTTTTTTTYVWWWWWVCK.....KIEK
............KCVWWWWVCYGTTTTTTTTTTYVWWWVCK.......KIEK
.............KCVWWVVCYGTTTTTTTTTTTYVVVCK.........KIEK
..............KCVVVYGTTTTTKTTTTTTTTYVVCK..........KIE
...............KBYGTTTTTKK.KTTTTTTTTYWVK
................KGTTTTTK....KTTTTTTTTYWVK
................KTTTTTK......KTTTTTTTTYGK
................KTTTTTK.......KTTTTTTTTYK
................KHLLHHK........KTTTTTTTK
...............KHMMHHHK.........KHLLHHHK
...............KHMMHHHK.........KHMMHHHHK
..............KKKKKKKKK........KKKKKKKKKK
''')

write('stun_a', 10, '''
..............Y.................................Y
.............YEY...............................YEY
............YEEEY.............................YEEEY
.............YEY..........KKKK..................YEY
..............Y.........KHMMLHK..................Y
.......................KHMLMMHHK
......................KHMMHYYHHHK
.....................KHMMHYAYHHHHK
.....................KHMHHHGHHHHHHK
.....................KHHHHSSSSSPHHHK
.....................KHHHSSSSSSSPHHK
.....................KHHMPSSSSSSSSPK
....................KHHHMPSSRRSSRRPK
....................KHHHMPSSSSSSSSSPK
....................KHHHMPSSSKSSSSKPK
...................KHHMHMPSSSPSSSSPSK
...................KHHMHHMPSSSSSSSSPPK
..................KHHMMHMHPSSSSRSRPK
..................KHHMMHHMHPSSSSRRPK
.................KHHMMHHHHHPPPPPPK
.................KHHMHHHHKBWSSPK
................KHHMHHKBCVWWCPCBK
...............KHHMHKCVWWWWVCJVCBK
..............KHHMHKCVWWWWWVCJTVCWK
.............KHHMHKCVWWWWWVYGJTVCWVK
.............KHHHKCVWWWWVCYGTTJVCWVCK
.............KHHHKCVWWVCYGTTTTJVCWVBK
.............KHHMKCVWVCYGTTTTTJVCVBCBK
.............KHHMKCVVCYGTTTTTTJVCBCWWK
.............KHHHKCVBCYGTTTTTTJVCWCVWK
.............KHHHKCVBCYGTTTTTTJVCWWCVBK
.............KHHHKCVBCYGYYYYYYGJAYYVVCBK
..............KHHKCBYGTGTTTTTTAJYVVCWVK
..............KHHKBCYGTTTTTTJAJYVVCWVCK
..............KHHKCVWYGTTTTJATYVVCWSSPPKG
..............KHHKCVWWYGTTTJATYVVCSSSPPKGY
..............KHMKCVWWVYGTTTATYWWVPPPPKGKIE
.............KHHMKCVWWWVCYGTTTTYVWWVCBK..KIEK
.............KHHMKCVWWWVCYGTTTTTYVWWVCK...KIEK
.............KHHHKCVWWWWCYGTTTTTTYVWWVCK....KIEK
..............KHHKCVWWWCYGTTTTTTTTYVWVCK.....KIEK
...............KHKCVWWYGTTTTTTTTTTTYVVCK......KIEK
................KCVWWVYGTTTTTKTTTTTTYVCK.......KIEK
...............KCVWWWYGTTTTTK.KTTTTTTYWVK........KIEK
..............KCVWWWYGTTTTTK...KTTTTTTYWVK.........KIEK
.............KCVWWWYGTTTTTK.....KTTTTTTYWVK..........KIEK
.............KCVVYGTTTTTTK.......KTTTTTYVCK............KIE
..............KBYGTTTTTTK.........KTTTTYGCK
...............KKKHLLHHK..........KTTTTYKK
................KHMMHHK...........KHLLHHK
...............KKKKKKK...........KKKKKKKKK
''')

write('stun_b', 11, '''
........................Y
.......................YEY
......................YEEEY.................Y
.......................YEY.................YEY
........................Y..KKKK...........YEEEY
.........................KHMMLHK...........YEY
........................KHMLMMHHK...........Y
.......................KHMMHYYHHHK
......................KHMMHYAYHHHHK
.....................KHHMHHHGHHHHHHK
....................KHHHHHHSSSSSPHHHK
...................KHHHHHHSSSSSSSPHHK
..................KHHMHHHMPSSSSSSSSPK
.................KHHMMHHHMPSSSRRSSRRPK
.................KHHMMHHHMPSSSSSSSSSSPK
................KHHMMHHHHMPSSSKSSSSKPK
................KHHMMHHHHMPSSSPSSSSPSK
...............KHHMMHHHHHHMPSSSSSSSSPPK
...............KHHMMHHHHHHHPSSSSRSRPK
..............KHHMMHHHHHHHHHPPSSSRRPK
..............KHHMMHHHHHHHHHHPPPPPK
.............KHHMHHHHHHHHKBWWSSPK
.............KHHMHHHHHKBVWWWCPCBK
.............KHHMHHHKCVWWWWWVCJVCBK
.............KHHMHHKCVWWWWWWVCJTVCWK
.............KHHMHKCVWWWWWVYGTTJVCWVK
.............KHHHKCVWWWWVCYGTTTJVCWVCK
.............KHHKCVWWWVCYGTTTTTJVCWVBK
.............KHHKCVWWVCYGTTTTTTJVCVBCBK
..............KHHKCVWVCYGTTTTTTJVCBCWWK
..............KHHKCVVCYGTTTTTTTJVCWCVWK
..............KHHKCVBCYGYYYYYYGJAYVCWWCVBK
...............KHKCBYGTTTTTTTAJYVVCWSSPPKG
................KBCYGTTTTTTJAJYVVWSSSPPKGY
................KCVWYGTTTTJATYVVVPPPPKGKIE
................KCVWWYGTTTTATYWWVVCBK..KIEK
...............KCVWWWWVYGTTTTYVWWWWVCK...KIEK
..............KCVWWWWWVCYGTTTTTYVWWWWVCK...KIEK
.............KCVWWWWWWVCYGTTTTTTYVWWWWWVCK...KIEK
.............KCVWWWWWWCYGTTTTTTTTTYVWWWVCK....KIEK
..............KCVWWWVCYGTTTTTKTTTTTYVVVCK......KIEK
...............KCVVVCYGTTTTKK.KTTTTTYVVCK.......KIEK
................KBYGTTTTTK....KTTTTTTYWVK........KIEK
.................KGTTTTTK......KTTTTTTYWVK.........KIEK
.................KTTTTTK........KTTTTTTYGK..........KIEK
.................KTTTTTK.........KTTTTTTYK............KIE
.................KHLLHHK..........KTTTTTTK
................KHMMHHHK.........KHLLHHHK
................KHMMHHHK.........KHMMHHHHK
...............KKKKKKKKK........KKKKKKKKKK
''')

write('sleep_a', 10, '''
..........................KKKK
........................KHMMLHK
.......................KHMLMMHHK
......................KHMMHYYHHHK
.....................KHMMHYAYHHHHK
.....................KHMHHHGHHHHHHK
.....................KHHHHSSSSSPHHHK
.....................KHHHSSSSSSSPHHK
.....................KHHMPSSSSSSSSPK
.....................KHHMPSSRRSSRRPK
.....................KHHMPSSSSSSSSSPK
.....................KHHMPSSRRRSSRRPK
.....................KHHMPSSSPSSSSPSK
.....................KHHMPSSSSSSSSPPK
.....................KHHMHPSSSSSRSPK
.....................KHHMMHPSSSSPPK
....................KHHMMHHPPPPPK
....................KHHMMHHKBSSPK
...................KHHMHHHKBVWSPK
..................KHHMMHKBVWWCPCBK
.................KHHMHKCVWWWVCJVCBK
................KHHMKCVWWWWVCJTVCVK
...............KHHMKCVWWWWWVYGJTVCWVK
..............KHHMKCVWWWWVCYGTTJVCWVCK
..............KHMKCVWWWWVCYGTTTJVCWVCK
..............KHMKCVWWVCYGTTTTTJVCWVBK
..............KHHKCVWVCYGTTTTTTJVCVBCBK
..............KHHKCVVCYGTTTTTTTJVCBCWWK
..............KHHKCVBCYGTTTSSPPJVCWCVWK
..............KHHKCVBCYGTSSSSPPVCWWCVBK
..............KHHKCVBCYGTTTPPPKVCWSSPPKG
...............KHHKCBGYYYYYYGJAYYSSSPPKGY
...............KHHKBCGYYGTTTTAJYPPPPKGKIE
...............KHHKCVWWGTTTTJAJYVCBK..KIEK
...............KHHKCVWWYGTTTJATYVVCBK...KIEK
...............KHHKCVWWVYGTTJATYWWVVBK...KIEK
...............KHMKCVWWWVYGTTATYWWWWVCK...KIEK
...............KHMKCVWWWVCYGTTTYVWWWWVCK...KIEK
...............KHHKCVWWWVCYGTTTTYVWWWWVCK...KIEK
................KHKCVWWWWCYGTTTTYVWWWVCK...KIEK
................KHKCVWWWCYGTTTTTTYWWVVCK....KIEK
.................KCVWWWVYGTTTTTTTTYWVVCK.....KIEK
.................KCVWWWYGTTTTTTTTTTYVCK.......KIEK
................KCVWWVYGTTTTTTTTTTYWVK........KIEK
................KCVWWYGTTTTTTTTTTTYGWVK........KIEK
...............KCVWWYGTTTTTTTTTTTTTYGWVK.........KIEK
...............KCVVYGTTTTTKKTTTTTTYGWVCK...........KIE
................KBYGTTTTTK..KTTTTYGVBKK
.................KKKHLLHK....KHLLHHK
..................KHMMHK....KHMMHHHK
.................KKKKKKK....KKKKKKKKK
''')

write('sleep_b', 11, '''
...........................KKKK
.........................KHMMLHK
........................KHMLMMHHK
.......................KHMMHYYHHHK
......................KHMMHYAYHHHHK
.....................KHHMHHHGHHHHHHK
.....................KHHHHHSSSSSPHHHK
....................KHHHHHSSSSSSSPHHK
....................KHHHHMPSSSSSSSSPK
....................KHHHHMPSSSRRSSRRPK
....................KHHHHMPSSSSSSSSSSPK
...................KHHMHHMPSSRRRSSRRRPK
...................KHHMMHMPSSSPSSSSSPSK
..................KHHMMHHHMPSSSSSSSSPPK
..................KHHMMHHHHPSSSSSRSPK
.................KHHMMHHHHHHPPSSSSPK
.................KHHMMHHHHHHHPPPPK
.................KHHMHHHHHKBWWSPK
................KHHMHHHKBVWWWCPCBK
...............KHHMHHKCVWWWWVCJVCBK
..............KHHMHKCVWWWWWVCJTVCWK
..............KHHHKCVWWWWWVYGJTVCWVK
..............KHHHKCVWWWWVCYGTTJVCWVCK
..............KHHKCVWWWWVCYGTTTJVCWVCK
..............KHHKCVWWVCYGTTTTTJVCWVBK
..............KHHKCVWVCYGTTTTTTJVCVBCBK
..............KHHKCVVCYGTTSSPPJVCBCWWK
..............KHHKCVBCYGTSSSSPPVCWCVWK
..............KHHKCVBCYGTTTPPPKVCWWCVBK
...............KHHKCBGYYYYYYGJAYVCWSSPPKG
...............KHHKBCGYYGTTTTAJYVWSSSPPKGY
...............KHHKCVWWGTTTTJAJYVVPPPPKGKIE
...............KHHKCVWWYGTTTJATYWWVCBK..KIEK
...............KHMKCVWWVYGTTJATYWWWWVCK...KIEK
..............KHHMKCVWWWVYGTTATYWWWWWVCK...KIEK
..............KHHMKCVWWWVCYGTTTYVWWWWVCK....KIEK
..............KHHHKCVWWWVCYGTTTTYVWWWWVCK....KIEK
...............KHHKCVWWWWCYGTTTTYVWWWWVCK.....KIEK
................KHKCVWWWCYGTTTTTTYWWVVCK......KIEK
.................KCVWWWVYGTTTTTTTTYWVVCK.......KIEK
.................KCVWWWYGTTTTTTTTTTYVCK.........KIEK
................KCVWWVYGTTTTTTTTTTYWVK..........KIEK
................KCVWWYGTTTTTTTTTTTYGWVK...........KIEK
...............KCVWWYGTTTTTTTTTTTTTYGWVK............KIE
...............KCVVYGTTTTTKKTTTTTTYGWVCK
................KBYGTTTTTK..KTTTTYGVBKK
.................KKKHLLHK....KHLLHHK
..................KHMMHK....KHMMHHHK
..................KHMMHK....KHMMHHHK
.................KKKKKKK....KKKKKKKKK
''')
