"""Hand chosen complete row clusters for each pose, including the first outline
repair. Imported constants are unchanged clusters, never automatically moved.
"""
from author import *
# Resolve the rear hand, spool and thread as one visible chain. Rows explicitly
# replace the old dangling spool; the diagonal red thread is chosen row by row.
LOWER_ARMS=block(48,16,"""
.KpVVVVVppppppppppVVppppppppPPPPPPKppppPKKKr
.KpVVVVpppppppppppVppppppppPPPPPPPKppppPPr
.KpVVVppppppppppppVppppppppPPPPPPPKpppPrPK
.KpVVppppppppppppVVppppppPPPPPPPPPKppPrPPK
.KpVpppppppppppppVpppppPPPPPPPPPPPKpPrPPK
.KppppppppppppppVppppPPPPPggGGgggKKrPPPK
.KpppppppppppppVVppPPPPPggGGGGgggrKPPPK
.KppppppppppppVVppPPPPKKGgggggggrKPPPK
.KppppppppppVVVppPPPKKttuuuuutTrTKKKK
..KpppppppVVVppPPPKKttuUUUuuutTrTTTK
..KpppppVVVVppPPPKttuUUUUUuuurTTTTTTK
...KppVVVVppPPPPKttuUUUUUuuurtTTTTTTTK
....KpVpppPPPPPKttuuUUUUuuurttTTTTTTTK
.....KggGGgggPKssKKuuUUuurrttTTTTTTTTTK
......KgggggPKLLssKrRRRruuttTTTTTTTTTTTK
........KKKKKssSsKrReRRruuutttTTTTTTTTTK
.............KKSKrReReRruuutttTTTTTTTTTTK
...............KrRReRRruuutttTTTTTTTTTTTK
.................rRRrruuuuttttTTTTTTTTTTK
..................rruuuuuuttttTTTTTTTTTTK
""")
frame('idle_a',HEAD,TORSO,SKIRT,FEET,LOWER_ARMS)
# Idle breath changes local shoulder folds, fingers, spool and hem clusters.
IDLE_B_CHEST=block(36,16,"""
.............KKKpVKKKKPVVLSPppppPKKK
...........KKpVVVVVVVVVVVLSPppppppppKK
..........KpVVVVVVVVVVVVVLSPpppppppppPK
.........KpVVVVVVVppVVVVVLLSPpppppppppPK
........KpVVVVVVppppVVVVLLLSPpppVVppppppPK
.......KpVVVVVVpppppVVVLLLpSPppVVVVpppppPK
......KpVVVVVVppppppVVLpppppSPppVVVVpppppPK
.....KpVVVVVVpppppppVLpppppppSPppVVVppppPK......g
....KpVVVVVVppppppppVppppppppppPppVVppppKssSKggGGGg
...KpVVVVVVppppppppVVppppppppppPPppVpppKLLssGGGGGggg
..KpVVVVVVpppppppppVppppppppppPPPKppppKLLssSGGGggg
..KpVVVVVppppppppppVpppppppppPPPPPKppppKssSKggg
""")
IDLE_B_HAND=block(61,16,"""
.....KggGGgggPKssKKuuUUuurrttTTTTTTTTTK
......KgggggPKLLLsKrRRRruuttTTTTTTTTTTTK
........KKKKKssSsKrReeRruuutttTTTTTTTTTK
.............KKSKrReReRruuutttTTTTTTTTTTK
...............KrRRReRruuutttTTTTTTTTTTTK
.................rRRrruuuuttttTTTTTTTTTTK
..................rruuuuuuttttTTTTTTTTTTK
""")
IDLE_C_CHEST=block(36,16,"""
.............KKKpVKKKKPVVLSPppppPKKK
...........KKpVVVVVVVVVVVLSPppppppppKK
..........KpVVVVVVVVVVVVLsSPppppppppppPK
.........KpVVVVVVVppVVVVLLSPpppppppppppPK
........KpVVVVVVppppVVVLLLpSPpppppppppppPK
.......KpVVVVVVpppppVVLLpppSPpppVVppppppPK
......KpVVVVVVppppppVLppppppSPppVVVppppppPK
.....KpVVVVVVpppppppVppppppppSPppVVVVppppPK......g
....KpVVVVVVppppppppVppppppppppPppVVVpppKsssKggGGGg
...KpVVVVVVppppppppVVppppppppppPPppVVppKLLssGGGGGggg
..KpVVVVVVpppppppppVppppppppppPPPKppppKLLssSGGGggg
..KpVVVVVppppppppppVpppppppppPPPPPKppppKssSKggg
""")
IDLE_C_HEM=block(81,20,"""
.KttuuuuttTTttttuuuutuuuttTTTtttTTTTTTTTTK
KttuuuttTTTTttttuuutttttTTTTTTTtttTTTTTTTTK
KttuuttTTTTTttttuutttttTTTTTTTTttttTTTTTTTK
KttuuttTTTTTTtttuutttTTTTTTTTTTttttTTTTTTTK
KttttTTTTTTTTTttttttTTTTTTTTTTTTtttTTTTTTTK
.KTTTTTTTTTTTTTTKKKKTTTTTTTTTTTTTKKKKKKK
..KKKKKKKKKKKKKK....KKKKKKKKKKKKKK
""")
frame('idle_b',HEAD,TORSO,SKIRT,FEET,LOWER_ARMS,IDLE_B_CHEST,IDLE_B_HAND)
frame('idle_c',HEAD,TORSO,SKIRT,FEET,LOWER_ARMS,IDLE_C_CHEST,IDLE_C_HEM)

WINDUP_BODY=block(32,16,"""
.................KHHHHHHHHKKssSK..............g
..................KHHHHHHKPLssSPK.........ggGGg
..................KHHHHHKPVLssSPpK.......ggGGGgg
.................KKHHHHKPVLsSPppPK......gGGGGg
..............KKKpVKKKKPVVLSPppppPKKK.KsGGgg
............KKpVVVVVVVVVVVLSPppppppppKsLLSK
...........KpVVVVVVVVVVVVVLSPpppppppppKssSPK
..........KpVVVVVVVppVVVVVLLSPpppppppppKpppPK
.........KpVVVVVVppppVVVVLLLSPppppppppVVppppPK
........KpVVVVVVpppppVVVLLLpSPppppppVVVVppppPK
.......KpVVVVVVppppppVVLpppppSPppppVVVVpppppPK
......KpVVVVVVpppppppVLpppppppSPpppVVVppppppPK
.....KpVVVVVVppppppppVppppppppppPppVVppppppPPK
....KpVVVVVVppppppppVVppppppppppPPpVVpppppPPPK
...KpVVVVVVpppppppppVppppppppppPPPKppppppPPPPK
...KpVVVVVppppppppppVpppppppppPPPPPKppppPPPPPK
..KpVVVVVppppppppppVVppppppppPPPPPPPKppPPPPPK
..KpVVVVpppppppppppVppppppppPPPPPPPPPKppPPPK
..KpVVVppppppppppppVppppppppPPPPPPPPPPKPPPK
..KpVVppppppppppppVVppppppPPPPPPPPPPPPPKK.r
..KpVpppppppppppppVpppppPPPPPPPPPPPPPPK..r
..KppppppppppppppVppppPPPPPggGGgggKKKK..r
..KpppppppppppppVVppPPPPPggGGGGggggKK...r
..KppppppppppppVVppPPPPKKGgggggggKKr...r
...KpppppppppVVVppPPPKKttuuuuutTrTTr..r
...KpppppppVVVVppPPPKKttuUUUuuutTrTTr.r
....KpppppVVVVppPPPKttuUUUUUuuutTTTrTrr
.....KppVVVVppPPPPKttuUUUUUuuuuttTTTrTK
......KggGGgggPPPKssKKUUUUuuuuttTTTTrTK
.......KgggggPPPKLLssKrRRRruuttTTTTTrTTK
........KKKKKKKKssSsKrReRRruuttTTTTrTTTK
...............KKSKrReReRruuttTTTrTTTTTK
.................KrRReRRruuuttTTrTTTTTTK
...................rRRrruuuutttTTTTTTTTK
....................rruuuuuutttTTTTTTTTK
""")
WINDUP_HEM=block(79,20,"""
...KttuuuuuuttttuuuutuuuuutttttTTTTTTTTTTK
..KttuuuuuutttttuuuutuuuuttTTttTTTTTTTTTTK
..KttuuuuttTTttttuuuutuuuttTTTtttTTTTTTTTK
.KttuuuttTTTTttttuuutttttTTTTTTtttTTTTTTTK
.KttuuttTTTTTttttuutttttTTTTTTTttttTTTTTTK
.KttuuttTTTTTTtttuutttTTTTTTTTTttttTTTTTK
.KttttTTTTTTTTTttttttTTTTTTTTTTTtttTTTTTK
..KTTTTTTTTTTTTTKKKKTTTTTTTTTTTTKKKKKK
...KKKKKKKKKKKKK....KKKKKKKKKKKKK
""")
WINDUP_FEET=block(88,20,"""
..............KLLssK.......KLLssK
..............KLLssK.......KLLssK
.............KHssSK........KHHssSK
............KHHHHK.........KHHHHHHHK
............KKKKKK.........KKKKKKKKK
""")
frame('windup',HEAD,TORSO,SKIRT,WINDUP_BODY,WINDUP_HEM,WINDUP_FEET)
MOVE_HEAD=block(10,34,"""
.......KKKKK
......KHhhHHK
.....KHhhhhHHK
.....KHHhhHHHK.........GG
....KHHHHHHHHKK.....GGGg
...KHHhhhhHHHHHKKGGGgg
..KHhhhhhhhHHHHHGgg
.KHHhhhhHHHHHHHHHHK
.KHhhhHHHHHHHHHHHHHK
KHhhhHHHHHssssssSHHK
KHhhHHHHHLLLssssssHK
KHhHHHHHLLLLsssssssK
KHHHHHHHLLLsssssSSsK
KHHHHHHHLLLssKssssssK
KHHHHHHHLLsssssKsLsK
KHHHHHHHLLsssssssssK
KHHHHHHHSssSSsssSK
KHHHHHHHHSsssRssK
KHHHHHHHHKssssSK
KHHhHHHHHKSSssK
KHHhHHHHHHKSSK
KHHhHHHHHHKssK
KHHHHHHHHKKssSK
.KHHHHHHKPLssSPK
.KHHHHHKPVLssSPpK
""")
MOVE_BODY=block(35,18,"""
...............KKHHHHKPVLsSPppPKK
............KKKpVKKKKPVVLSPppppppKKK
..........KKpVVVVVVVVVVVLSPpppppppppKK
.........KpVVVVVVVVVVVVVLSPpppppppppppPK
........KpVVVVVVVppVVVVVLLSPpppppppppppPK
.......KpVVVVVVppppVVVVLLLSPppppppppppppPK
......KpVVVVVVpppppVVVLLLpSPppppVVVVpppppPK
.....KpVVVVVVppppppVVLpppppSPppVVVVVpppppPK
....KpVVVVVVpppppppVLpppppppSPppVVVVppppppPK
...KpVVVVVVppppppppVppppppppppPppVVVpppppppPK
..KpVVVVVVppppppppVVppppppppppPPpVVppppppppPK
.KpVVVVVVpppppppppVppppppppppPPPKpppppppppPPK
.KpVVVVVppppppppppVpppppppppPPPPPKppppppPPPPK....g
KpVVVVVppppppppppVVppppppppPPPPPPPKpppppPPPKsKggGGg
KpVVVVpppppppppppVppppppppPPPPPPPPKppppPPPKLLsGGGGgg
KpVVVppppppppppppVppppppppPPPPPPPPPKppPPPKssSGGGgg
KpVVppppppppppppVVppppppPPPPPPPPPPPPKPPPKKKgggg
KpVpppppppppppppVpppppPPPPPPPPPPPPPPKKK..r
KppppppppppppppVppppPPPPPggGGgggKKKK....r
KpppppppppppppVVppPPPPPggGGGGggggK......r
KppppppppppppVVppPPPPKKGgggggggKK......r
.KpppppppppVVVppPPPKKttuUUUuutTTTK....r
.KpppppppVVVVppPPPKKttuUUUUuutTTTTK..r
..KpppppVVVVppPPPKttuUUUUUuuuttTTTTKr
...KppVVVVppPPPPKttuUUUUUuuuuttTTTTrTK
....KggGGgggPPPKssKKUUUUuuuuttTTTTrTTK
.....KgggggPPPKLLssKrRRRruuttTTTTrTTTK
......KKKKKKKKssSsKrReRRruuttTTTrTTTTTK
.............KKSKrReReRruuuttTTrTTTTTTK
...............KrRReRRruuuuttTrTTTTTTTK
.................rRRrruuuuuttTTTTTTTTTTK
..................rruuuuuutttTTTTTTTTTTK
""")
MOVE_SKIRT=block(67,19,"""
..........KttuuuUUuuuuuutttTTTTTTTTTTTTTK
.........KttuuuuUuuuuuuuttttTTTTTTTTTTTTK
........KttuuuuuuuuuuuutttttTTTTTTTTTTTTK
.......KttuuuuuuuuuuuuuttttttTTTTTTTTTTTK
......KttuuuuuuuuuuuuuttttttttTTTTTTTTTTTK
.....KttuuuuuuutuuuuttuuutttttTTTTTTTTTTTK
....KttuuuuuuttuuuutuuuuttTTttTTTTTTTTTTTK
...KttuuuuuutttuuuutuuuutTTTTttTTTTTTTTTTK
..KttuuuuuuttttuuuutuuuutTTTTTtttTTTTTTTTK
.KttuuuuuutttttuuuutuuuuttTTTTTTtttTTTTTTTK
KttuuuuuuttttttuuuutuuuuttTTTTTTTtttTTTTTTK
KttuuuuutttttttuuuutuuuuttTTTTTTTTtttTTTTTK
KttuuuuttttttttuuuutuuuttTTTTTTTTTTtttTTTTK
KttuuuttTTTttttuuuutuuttTTTTTTTTTTTTtttTTTK
.KttuuttTTTTttttuuuttTTTTTTTTTTTTTTTTttTTK
.KttuuttTTTTTttttuutTTTTTTTTTTTTTTTTTTTTK
..KttttTTTTTTTttttttTTTTTTTTTTKKKLLssKKK
...KTTTTTTTTTTTTTTKKKKTTTTTTKK...KLLssK
....KKKKKKKKKKKKKK....KKKKKK.....KLLssK
.........KLLssK..................KLLssK
........KHssSK....................KLLssK
.......KHHHHK......................KHHssSK
......KHHHHK.......................KHHHHHHHK
......KKKKK........................KKKKKKKKK
""")
frame('move',MOVE_HEAD,MOVE_BODY,MOVE_SKIRT)
ATTACK_HEAD=block(14,38,"""
........KKKKK
.......KHhhhHK
......KHhhhhHHK
......KHHhhHHHK........GG
.....KHHHHHHHHKK....GGGg
....KHHhhhhHHHHHKGggg
...KHhhhhhhhHHHHHHK
..KHHhhhhHHHHHHHHHHK
.KHHhhhHHHHsssssssHHK
KHhhhHHHHHLLLssssssHK
KHhhHHHHHLLLLsssssssK
KHHHHHHHHLLLssKssssssK
KHHHHHHHLLLsssssKsLsK
KHHHHHHHLLsssssssssK
KHHHHHHHSssSSsssSK
KHHHHHHHHSsssRssK
KHHHHHHHHKssssSK
KHHhHHHHHKSSssK
KHHhHHHHHHKSSK
KHHhHHHHHHKssK
KHHHHHHHHKKssSK
.KHHHHHHKPVLssSPK
.KHHHHHKPVVLssSPpKK
""")
ATTACK_BODY=block(37,18,"""
.................KKHHHHKPVVLsSPpppKKKK
..............KKKpVKKKKPVVLLSPpppVVVVppKKK
............KKpVVVVVVVVVLLLSPppVVVVVVVVppKK
...........KpVVVVVVVVVVVLLLSPppVVVVVVVVVppPKKK
..........KpVVVVVVVppVVVLLpSPppVVVVVVVVVVppppPKKK
.........KpVVVVVVppppVVLLpppSPppVVVVVVVVVppppppppPKK
........KpVVVVVVpppppVLppppppSPppVVVVVVVppppppppppppKssK...g
.......KpVVVVVVppppppVppppppppSPppVVVVVppppppppppppppKLLsKggGGGg
......KpVVVVVVpppppppVppppppppppPppVVVVpppppppppppppppKLLsSGGGGGggg
.....KpVVVVVVppppppppVppppppppppPPpVVVpppppppppppppppPPKssSGGGGggg
....KpVVVVVVppppppppVVppppppppppPPPKpppppppppppppppPPPPKKKKgggg.r
...KpVVVVVVpppppppppVppppppppppPPPPPKpppppppppppPPPPPPPK.....r
...KpVVVVVppppppppppVpppppppppPPPPPPPKpppppppPPPPPPPPPK.....r
..KpVVVVVppppppppppVVppppppppPPPPPPPPPKpppPPPPPPPPPPPK....r
..KpVVVVpppppppppppVppppppppPPPPPPPPPPPKPPPPPPPPPPPK....r
..KpVVVppppppppppppVppppppppPPPPPPPPPPPPKKKKKKKKKKK....r
..KpVVppppppppppppVVpppppPPPPPPPPPPPPPPPggGGgggKK....r
..KpVpppppppppppppVppppPPPPPPPPPPPPPPggGGGGggggK...r
..KppppppppppppppVpppPPPPPPPPPPPPPKKGgggggggKK..r
...KpppppppppppVVppPPPPPPPPPPPKKttuUUUUuutTTrTr
...KppppppppppVVppPPPPPPPPPKKttuUUUUUuuutTTrTK
....KpppppppVVVppPPPPPPPKKttuUUUUUuuuutTTTrTTK
.....KppppVVVVppPPPPPPKttuUUUUUuuuuuuttTTrTTTK
......KggGGgggPPPPPPPKssKKUUUuuuuttTTTTrTTTTK
.......KgggggPPPPPPPKLLssKrRRRruuttTTTrTTTTTK
........KKKKKKKKKKKKssSsKrReRRruuttTrTTTTTTK
...................KKSKrReReRruutTrTTTTTTTTK
.....................KrRReRRruutTrTTTTTTTTTK
.......................rRRrruuuttTTTTTTTTTTK
........................rruuuutttTTTTTTTTTTK
""")
ATTACK_SKIRT=block(67,24,"""
..............KttuuuUUuuuuuutttTTTTTTTTTTTTK
.............KttuuuuUuuuuuuuttttTTTTTTTTTTTK
............KttuuuuuuuuuuuutttttTTTTTTTTTTTK
...........KttuuuuuuuuuuuuuttttttTTTTTTTTTTK
..........KttuuuuuuuuuuuuuttttttttTTTTTTTTTK
.........KttuuuuuuutuuuuttuuutttttTTTTTTTTTK
........KttuuuuuuttuuuutuuuuttTTttTTTTTTTTTK
.......KttuuuuuutttuuuutuuuutTTTTttTTTTTTTTK
......KttuuuuuuttttuuuutuuuutTTTTTtttTTTTTTTK
.....KttuuuuuutttttuuuutuuuuttTTTTTTtttTTTTTK
....KttuuuuuuttttttuuuutuuuuttTTTTTTTtttTTTTK
...KttuuuuuutttttttuuuutuuuuttTTTTTTTTtttTTTK
..KttuuuuuuttttttttuuuutuuuttTTTTTTTTTTtttTTK
.KttuuuuuutTTTtttttuuuutuuttTTTTTTTTTTTTtttTK
KttuuuuuttTTTTtttttuuuttTTTTTTTTTTTTTTTTttTK
KttuuttTTTTTTTttttttttTTTTTTTTTTTTTTTTTTTTK
KttttTTTTTTTTTTTttttTTTTTTTTTTTTTTKKLLssKKK
.KTTTTTTTTTTTTTTTTKKKKTTTTTTTTTTKK..KLLssK
..KKKKKKKKKKKKKKKK....KKKKKKKKKK....KLLssK
........KLLssK......................KLLssK
.......KLLsSK........................KLLssK
......KHHsSK..........................KHHssSK
....KHHHHHK...........................KHHHHHHHK
....KKKKKK............................KKKKKKKKK
""")
frame('attack',ATTACK_HEAD,ATTACK_BODY,ATTACK_SKIRT)
RECOVER_BODY=block(35,16,"""
................KKHHHHKPVLsSPppPK
.............KKKpVKKKKPVVLSPppppPKKK
...........KKpVVVVVVVVVVVLSPppppppppKK
..........KpVVVVVVVVVVVVVLSPpppppppppPK
.........KpVVVVVVVppVVVVVLLSPpppppppppPK
........KpVVVVVVppppVVVVLLLSPppppppppppPK
.......KpVVVVVVpppppVVVLLLpSPppppppppppPK
......KpVVVVVVppppppVVLpppppSPpppVVVppppPK
.....KpVVVVVVpppppppVLpppppppSPppVVVVppppPK
....KpVVVVVVppppppppVppppppppppPppVVVppppPK
...KpVVVVVVppppppppVVppppppppppPPppVVppppPK
..KpVVVVVVpppppppppVppppppppppPPPKppppppPPK
..KpVVVVVppppppppppVpppppppppPPPPPKppppPPPK
.KpVVVVVppppppppppVVppppppppPPPPPPPKpppPPPK
.KpVVVVpppppppppppVppppppppPPPPPPPPKppPPPK
.KpVVVppppppppppppVppppppppPPPPPPPPPKPPPKsK..g
.KpVVppppppppppppVVppppppPPPPPPPPPPPKKKKLLsGGGg
.KpVpppppppppppppVpppppPPPPPPPPPPPPK...KssGGGggg
.KppppppppppppppVppppPPPPPggGGgggKK....KKggGGggg
.KpppppppppppppVVppPPPPPggGGGGggggK...r....gggg
.KppppppppppppVVppPPPPKKGgggggggKK..r
.KppppppppppVVVppPPPKKttuuuuutTTTK.r
..KpppppppVVVppPPPKKttuUUUuuutTTTTrK
..KpppppVVVVppPPPKttuUUUUUuuutTTTrTTK
...KppVVVVppPPPPKttuUUUUUuuuuttTrTTTTK
....KpVpppPPPPPKttuuUUUUuuuuttTrTTTTTK
.....KggGGgggPKssKKuuUUuuuuttTrTTTTTTTK
......KgggggPKLLssKrRRRruuttTrTTTTTTTTTK
........KKKKKssSsKrReRRruuurTTTTTTTTTTTK
.............KKSKrReReRruurttTTTTTTTTTTTK
...............KrRReRRruurtttTTTTTTTTTTTK
.................rRRrruuruttttTTTTTTTTTTK
..................rruuuuuuttttTTTTTTTTTTK
""")
RECOVER_FOOT=block(88,20,"""
.............KLLssK..........KLLssK
.............KLLssK..........KLLssK
............KHHssSK.........KHHssSK
...........KHHHHHHHK........KHHHHHHHK
...........KKKKKKKKK........KKKKKKKKK
""")
frame('recover',HEAD,SKIRT,RECOVER_BODY,RECOVER_FOOT)

HIT_HEAD=block(15,29,"""
......KKKKK
.....KHhhHHK
....KHhhhhHHK
....KHHhhHHHK.........GG
...KHHHHHHHHKK.....GGGg
..KHHhhhhHHHHHKKGGGgg
.KHhhhhhhhHHHHHGgg
KHHhhhhHHHHHHHHHHK
KHhhhHHHHHssssssHHK
KHhhHHHHHLLLssssssK
KHhHHHHHLLLLsssssssK
KHHHHHHHLLLssSSsssSsK
KHHHHHHHLLLssKKssssssK
KHHHHHHHLLsssssPsLsK
KHHHHHHHLLsssssssssK
KHHHHHHHSssSSsssSK
KHHHHHHHHSsssRRsK
KHHHHHHHHKssssSK
KHHhHHHHHKSSssK
KHHhHHHHHHKSSK
KHHhHHHHHHKssK
KHHHHHHHHKKssSK
.KHHHHHHKPLssSPK
.KHHHHHKPVLssSPpK
..KHHHHKPVLsSPppPK
""")
HIT_BODY=block(40,16,"""
...........KKKpVKKKKPVVLSPpppKK
.........KKpVVVVVVVVVVLSPppppppKK
........KpVVVVVVVVVVVLLSPppppppppKK
.......KpVVVVVVppVVVVLLLSPpppppppppPK
......KpVVVVVVpppVVVVLLLpSPpppppppppPK
.....KpVVVVVVppppVVVLLpppSPppVVVpppppPK
....KpVVVVVVpppppVVVLpppppSPpVVVVppppppPK
...KpVVVVVVppppppVVVpppppppSPVVVVpppppppPK
..KpVVVVVVppppppVVVpppppppppPVVVpppppppppPK
.KpVVVVVVppppppVVVppppppppppPPVVppppppppppPK
KpVVVVVVppppppVVVppppppppppPPPpVppppppppppPK
KpVVVVVppppppVVVppppppppppPPPPPKppppppppppPK
KpVVVVppppppVVVppppppppppPPPPPPPKppppppppPPK
KpVVVppppppVVVppppppppppPPPPPPPPPKppppppPPPK
KpVVppppppVVVpppppppppPPPPPPPPPPPPKpppppPPPK
KpVpppppVVVVpppppppPPPPPPPPPPPPPPPKppppPPPK
KpppppVVVVpppPPPggGGgggKKKKPPPPPPPKpppPPPK
.KppVVVVpppPPggGGGGgggggKKssKKPPPPPKppPPPK
..KggGGgggPKgggggggKKttKLLssKrRRRrPKPPPPK
...KgggggPKKKKKKKKKttuKKssSsKrReRRrKPPPK
....KKKKKKttuuUUUUuutttKKSKrReReRrKPPPK
.........KttuuUUUUuuuuttTTKrRReRRrKPPPK
........KttuuUUUUUuuuuttTTTTrRRrrKPPPKsK
........KttuuUUUUUuuuuttTTTTTrrTTKKKKLLsK
.......KttuuUUUUUuuuuttTTTTTTTTTTTK.KssGGGg
.......KttuuuUUUuuuuttTTTTTTTTTTTTK..KggGGGg
......KttuuuUUUuuuuttTTTTTTTTTTTTTK.r..ggGGGg
......KttuuuUUuuuuuttTTTTTTTTTTTTTTK.r...gggg
.....KttuuuuUuuuuuutttTTTTTTTTTTTTTK.r
.....KttuuuuuuuuuuutttTTTTTTTTTTTTTKr
.....KttuuuuuuuuuuttttTTTTTTTTTTTTrK
""")
HIT_SKIRT=block(71,20,"""
.KttuuuuuuuuuuuutttttTTTTTTTTTTTTTTK
.KttuuuuuutuuuuttuuuttTTTTTTTTTTTTTTK
KttuuuuuttuuuutuuuuttTTTTTTTTTTTTTTTK
KttuuuuutttuuuutuuuutttTTTTTTTTTTTTTK
KttuuuuutttuuuutuuuuutttTTTTTTTTTTTTK
KttuuuuttttuuuutuuuuutttTTTTTTTTTTTTTK
KttuuuuttttuuuutuuuuuttttTTTTTTTTTTTTK
KttuuuutttttuuuutuuuuutttTTTTTTTTTTTTK
KttuuuttttttuuuutuuuuuttttTTTTTTTTTTTK
KttuuttTTttttuuuutuuuuttTTttTTTTTTTTTK
KtuuttTTTTttttuuuutuuuttTTTtttTTTTTTTK
KttttTTTTTttttuuutttttTTTTTTtttTTTTTTK
KttttTTTTTTtttuutttTTTTTTTTttttTTTTTTK
.KTTTTTTTTTTttttttTTTTTTTTTTtttTTTTTTK
..KTTTTTTTTTTTTKKKKTTTTTTTTTTTTTKKKKK
...KKKKKKKKKKKK....KKKKKKKKKKKKK
............KLLssK........KLLssK
............KLLssK........KLLssK
...........KHHssSK........KHHssSK
..........KHHHHHHHK.......KHHHHHHHK
..........KKKKKKKKK.......KKKKKKKKK
""")
frame('hit',HIT_HEAD,HIT_BODY,HIT_SKIRT)
DEAD=block(61,12,"""
...........................................KKKKK
..........................................KHhhhHK
.........................................KHhhhhHHK
........................................KHHhhHHHHK......GG
.......................................KHHHHHHHHHHKK.GGGg
......................................KHhhhhHHHHHHHGGGg
.....................................KHhhHHHHHHHHHHHHHK
....................................KHHhhHHHHHssssssHHHK
...................................KHHhhHHHHHLLLLssssHHK
...................................KHHhHHHHHLLLLssssssHK
..................................KHHHHHHHHLLLssSSsssssK
..................................KHHHHHHHHLLssPPsssLsSsK
..................................KHHHHHHHHLLsssssssssSK
..................................KHHHHHHHHSssSSsssSSK
..................................KHHHHHHHHHSsssRsssK
..............................KKKKKHHHHHHHHHKsssssSK
............................KKpVVVKHHHHHHHHHHKSSssK
.........................KKKpVVVVVpKHHHHHHHHHKssSK
.......................KKpVVVVVVVpppKHHHHHHHKLLsSPKK
....................KKKpVVVVVVVppppppKKHHHHKVLsSPpppKK
.................KKKttKpVVVVVVpppppppppKKKKPVLLSPpppppKK
.............KKKKttuuUKpVVVVVpppppppppppppppVLLSPpppppppKK
..........KKKttuuUUUUUKpVVVVppppppppppppppppLLpSPppVVVppppKK
........KKttuuUUUUUUuuKpVVVpppppppppppppppLLpppSPpVVVVpppppK
......KKttuuuUUUUUuuuuuKpVVppppppppppppppLppppppSPVVVppppppPK
....KKttuuuuuuuuuuuuuuutKpVpppppppppppppVppppppppPVVppppppPPK
...KttuuuuuuuttttuuuuuuutKpppppppppppppVppppppppppPVpppppPPPPK
..KttuuuuttTTTTtttuuuuuuutKpppppppppppVpppppPPPPPPPPKpppPPPPPK
.KttuuuttTTTTTTTtttuuuuuuutKppppppppVVVpppPPPPPPPPPPKppPPPPPK
KttttttTTTTTTTTTTttttttuuuutKggGGgggPPPggGGgggKKKPPPKKssK..g
KTTTTTTTTTTTTTTTTTTTTTTtttttKgggggPKLLssKrRRRrKKKKKKLLssGGGGg
.KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKssSKrReRRr......KssSGGGGGgg
""")
frame('dead',DEAD)

SKILL_PREP_BODY=block(35,16,"""
................KKHHHHKPVLsSPppPK
.............KKKpVKKKKPVVLSPppppPKKK
...........KKpVVVVVVVVVVVLSPppppppppKK
..........KpVVVVVVVVVVVVVLSPpppppppppPK
.........KpVVVVVVVppVVVVVLLSPpppVVVppppPK
........KpVVVVVVppppVVVVLLLSPppVVVVVppppPK
.......KpVVVVVVpppppVVVLLLpSPppVVVVVppppPK
......KpVVVVVVppppppVVLpppppSPppVVVVpppppPK
.....KpVVVVVVpppppppVLpppppppSPppVVVppppPK...g
....KpVVVVVVppppppppVppppppppppPppVVpppKsKggGGg
...KpVVVVVVppppppppVVppppppppppPPppVppKLLsGGGGgg
..KpVVVVVVpppppppppVppppppppppPPPKpppKLLsSGGGgg
..KpVVVVVppppppppppVpppppppppPPPPPKppppKssSKggg
.KpVVVVVppppppppppVVppppppppPPPPPPrRRrrPKKK
.KpVVVVpppppppppppVppppppppPPPPrrReeRRrrPK
.KpVVVppppppppppppVpppppPPPPPPrReR..rReRrPK
.KpVVppppppppppppVVpppPPPKssKrrRr....rRRrPK
.KpVpppppppppppppVppPPPKLLssKrrReR..rReRrK
.KppppppppppppppVppPPPKLLssSSKrRReeReRRrPK
.KpppppppppppppVVppPPKssSSSKrRRRrrRRRrrPK
.KppppppppppppVVppPPPKKKSKrReRRrgggKKKKK
.KppppppppppVVVppPPPKttuuKrReReRrTTTK
..KpppppppVVVppPPPKttuUUUKrRReRRrTTTTK
..KpppppVVVVppPPPKttuUUUUUurRRrrTTTTTTK
...KppVVVVppPPPPKttuUUUUUuuurrttTTTTTTTK
....KggGGgggPPPKttuuUUUUuuuuttTTTTTTTTTK
.....KgggggPPPKttuuuUUUUuuuttTTTTTTTTTTTK
......KKKKKKKKttuuuuUUUuuuuttTTTTTTTTTTTK
""")
frame('skill_a',HEAD,SKIRT,FEET,SKILL_PREP_BODY)
SKILL_CAST_BODY=block(35,16,"""
................KKHHHHKPVLsSPppPK
.............KKKpVKKKKPVVLSPppppPKKK
...........KKpVVVVVVVVVVVLSPppppppppKK
..........KpVVVVVVVVVVVVVLSPpppppppppPK
.........KpVVVVVVVppVVVVVLLSPpppVVVVpppPKKK
........KpVVVVVVppppVVVVLLLSPppVVVVVVppppppKK
.......KpVVVVVVpppppVVVLLLpSPppVVVVVVVppppppPKK
......KpVVVVVVppppppVVLpppppSPppVVVVVVpppppppppKssK..g
.....KpVVVVVVpppppppVLpppppppSPppVVVVVpppppppppKLLsGGGGg
....KpVVVVVVppppppppVppppppppppPppVVVVppppppppppKLLsSGGGGgg
...KpVVVVVVppppppppVVppppppppppPPppVVpppppppppPPKssSGGGgg
..KpVVVVVVpppppppppVppppppppppPPPKppppppppppPPPKKKKggg
..KpVVVVVppppppppppVpppppppppPPPPPKppppppPPPPPK
.KpVVVVVppppppppppVVppppppppPPPPPPPKpppPPPPPPK
.KpVVVVpppppppppppVppppppppPPPPPPPPPKPPPPPPPK
.KpVVVppppppppppppVpppppPPPPPPPPPPPPPKPPPPPK
.KpVVppppppppppppVVpppPPPKssKKPPPPPPPPKKKKK
.KpVpppppppppppppVppPPPKLLssKrrRRrrggggKKK
.KppppppppppppppVppPPPKLLssSKrReRRrggggK
.KpppppppppppppVVppPPKssSSSKrReReRrgggK
.KppppppppppppVVppPPPKKKSKrRRReRRrKKKK
.KppppppppppVVVppPPPKttuuurRRRrrTTTTK
..KpppppppVVVppPPPKttuUUUUuuurrTTTTTTK
..KpppppVVVVppPPPKttuUUUUUuuutTTTTTTTTK
...KppVVVVppPPPPKttuUUUUUuuuuttTTTTTTTTK
....KggGGgggPPPKttuuUUUUuuuuttTTTTTTTTTK
.....KgggggPPPKttuuuUUUUuuuttTTTTTTTTTTTK
......KKKKKKKKttuuuuUUUuuuuttTTTTTTTTTTTK
""")
# Three ribbons begin at distinct authored points on the shuttle's forward tip.
# Their empty interiors are intentionally retained. Crossing = woven silk knot.
RIBBONS=Ink([
(23,86,'rRRRr'),(24,83,'rRReeRRr'),(25,81,'rRReR..rRRr'),
(26,79,'rRReR.....rRr'),(27,78,'rReR.......rRr'),
(28,77,'rReR........rRr'),(29,76,'rReR.........rRr'),
(30,75,'rReR.........rRr'),(31,74,'rReR.........rRr'),
(32,74,'rReR........rRr'),(33,74,'rReR......rRRr'),
(34,75,'rReR....rRRr'),(35,75,'rReR...rRRr'),
(36,75,'rReR..rRRr'),(37,74,'rReRRRRr'),(38,73,'rReRRRr'),
(39,72,'rReRRr'),(40,71,'rReR'),(41,71,'rReR'),
(42,72,'rReRRr'),(43,73,'rReeRRrrRRRr'),
(44,74,'rRReeRRReeRRRr'),(45,77,'rrRRrr....rReRRr'),
(46,85,'rReRRr'),(47,86,'rReRRr'),(48,86,'rReRRr'),
(49,85,'rReRRr'),(50,83,'rRReRRr'),(51,81,'rRReRRr'),
(52,79,'rRReRRr'),(53,79,'rReRRr'),(54,80,'rReRRr'),
(55,81,'rRReRRr'),(56,83,'rrRReRRr'),
(57,87,'rReR'),(58,88,'rReR'),(59,88,'rReR'),
(60,88,'rReR'),(61,87,'rReR'),(62,86,'rReR'),
(63,84,'rRReR'),(64,82,'rRReR'),(65,79,'rRReRRr'),
(66,77,'rRReRRr'),(67,75,'rRReRRr'),(68,75,'rReR'),
(69,75,'rReRRr'),(70,76,'rReRRr'),(71,78,'rReRRr'),
(72,80,'rrRReRRr'),(73,83,'rRRRr'),
# Lower root reaches out from the shuttle beneath the two other paths.
(46,70,'rRRr'),(47,71,'rReRr'),(48,72,'rReRRr'),
(49,74,'rReRRr'),(50,76,'rReRRr'),(51,78,'rReRRr'),
# Visible winding from rear fingers to the forward wrist.
(54,47,'rRRr'),(53,50,'rRRr'),(52,53,'rRRr'),
(51,56,'rRRr'),(50,59,'rRRr'),(49,62,'rRRr'),
(48,65,'rRRr'),(47,68,'rRRr')])
SKILL_CAST_HEM=block(84,20,"""
KttuuttTTTTTTtttuutttTTTTTTTTTttttTTTTTTTK
KttttTTTTTTTTTttttttTTTTTTTTTTTtttTTTTTTTK
.KTTTTTTTTTTTTTTKKKKTTTTTTTTTTTTTKKKKKKK
..KKKKKKKKKKKKKK....KKKKKKKKKKKKKK
.............KLLssK.........KLLssK
.............KLLssK.........KLLssK
............KHHssSK........KHHssSK
...........KHHHHHHHK.......KHHHHHHHK
...........KKKKKKKKK.......KKKKKKKKK
""")
frame('skill_b',HEAD,SKIRT,SKILL_CAST_BODY,SKILL_CAST_HEM,RIBBONS)
SKILL_RECALL_BODY=block(35,16,"""
................KKHHHHKPVLsSPppPK
.............KKKpVKKKKPVVLSPppppPKKK
...........KKpVVVVVVVVVVVLSPppppppppKK
..........KpVVVVVVVVVVVVVLSPpppppppppPK
.........KpVVVVVVVppVVVVVLLSPpppVVVppppPK
........KpVVVVVVppppVVVVLLLSPppVVVVVppppPK
.......KpVVVVVVpppppVVVLLLpSPppVVVVVppppPK
......KpVVVVVVppppppVVLpppppSPppVVVVppppPK...g
.....KpVVVVVVpppppppVLpppppppSPppVVVpppKsKggGGg
....KpVVVVVVppppppppVppppppppppPppVVppKLLsGGGGgg
...KpVVVVVVppppppppVVppppppppppPPppVpKLLsSGGGgg
..KpVVVVVVpppppppppVppppppppppPPPKpppKssSKggg
..KpVVVVVppppppppppVpppppppppPPPPPKppppKKK
.KpVVVVVppppppppppVVppppppppPPPPPPPKpppPK
.KpVVVVpppppppppppVppppppppPPPPPPPPPKppPK
.KpVVVppppppppppppVpppppPPPPPPPPPPPPPKPPK
.KpVVppppppppppppVVpppPPPKssKKPPPPPPPPKK
.KpVpppppppppppppVppPPPKLLssKrrRRrrgggK
.KppppppppppppppVppPPPKLLssSKrReRRrggggK
.KpppppppppppppVVppPPKssSSSKrReReRrgggK
.KppppppppppppVVppPPPKKKSKrRRReRRrKKKK
.KppppppppppVVVppPPPKttuuurRRRrrTTTTK
..KpppppppVVVppPPPKttuUUUUuuurrTTTTTTK
..KpppppVVVVppPPPKttuUUUUUuuutTTTTTTTTK
...KppVVVVppPPPPKttuUUUUUuuuuttTTTTTTTTK
....KggGGgggPPPKttuuUUUUuuuuttTTTTTTTTTK
.....KgggggPPPKttuuuUUUUuuuttTTTTTTTTTTTK
......KKKKKKKKttuuuuUUUuuuuttTTTTTTTTTTTK
""")
RECALL_THREADS=Ink([
(47,60,'rReR'),(48,61,'rReR'),(49,62,'rReR'),(50,61,'rReR'),
(51,60,'rReR'),(52,58,'rReR'),(53,55,'rRReR'),(54,52,'rRReR'),
(40,78,'rRRr'),(41,79,'rReR'),(42,80,'rReR'),(43,81,'rrRr'),
(47,86,'rRRr'),(48,87,'rReR'),(49,87,'rReR'),(50,86,'rRRr'),
(51,84,'rRRr'),(56,74,'rRRr'),(57,73,'rReR'),(58,73,'rReR'),
(59,74,'rReR'),(60,75,'rRRr'),(61,77,'rr')])
frame('skill_c',HEAD,SKIRT,FEET,SKILL_RECALL_BODY,RECALL_THREADS)

POISON_HEAD=block(24,34,"""
......KKKKK
.....KHhhHHK
....KHhhhhHHK
....KHHhhHHHK.........GG
...KHHHHHHHHKK.....GGGg
..KHHhhhhHHHHHKKGGGgg
.KHhhhhhhhHHHHHGgg
KHHhhhhHHHHHHHHHHK
KHhhhHHHHHssssssHHK
KHhhHHHHHLLLssssssHK
KHhHHHHHLLLLsssssssK
KHHHHHHHLLLssSSssssssK
KHHHHHHHLLLssPPsssSLsK
KHHHHHHHLLsssssPssssK
KHHHHHHHLLssSSsssssK
KHHHHHHHSssSSsssSSK
KHHHHHHHHSsssRrssK
KHHHHHHHHKSSsssSK
KHHhHHHHHKSSssK
KHHhHHHHHHKSSK
KHHhHHHHHHKssK
KHHHHHHHHKKssSK
.KHHHHHHKPLssSPK
.KHHHHHKPVLssSPpK
..KHHHHKPVLsSPppPK
""")
POISON_BODY=block(49,18,"""
..............KKKpVKKKKPVVLSPpppKK
............KKpVVVVVVVVVVLSPpppppKK
...........KpVVVVVVVVVVVLLSPpppppppKK
..........KpVVVVVVppVVVVLLLSPppppppppPK
.........KpVVVVVVpppVVVVLLLpSPppVVppppPK
........KpVVVVVVppppVVVLLpppSPpVVVVppppPK
.......KpVVVVVVpppppVVVLpppppSPVVVVpppppPK
......KpVVVVVVppppppVVVpppppppPVVVpppppppPK
.....KpVVVVVVppppppVVVpppppppppPPVVpppppppPK
....KpVVVVVVppppppVVVppppppppppPPPKppppppppPK
...KpVVVVVVppppppVVVppppppppppPPPPPKpppppppPK
..KpVVVVVVppppppVVVppppppppppPPPPPPPKpppppPPK
..KpVVVVVppppppVVVpppppppppPPPPPPPPPKppppPPK
.KpVVVVppppppVVVVppppppppPPPPPPPPPPPPKpppPPK
.KpVVVppppppVVVVpppPPPggGGgggKKKPPPPPPKppPPK
.KpVVpppppVVVVpppPPggGGGGgggggKssKKPPPKppPPK
.KpVppppVVVVpppPPPKgggggggKKttKLLssKrRRRrPPK
.KppppVVVVpppPPPKKKKKKKKKKttuKKssSsKrReRRrPK
..KppVVVpppPPPKttuuUUUUuuttttKKSKrReReRrPK
...KggGGgggPKKttuuUUUUUuuuttTTTTKrRReRRrPK
....KgggggPKttuuUUUUUuuuuttTTTTTTTTrRRrrK
.....KKKKKKttuuUUUUUuuuuttTTTTTTTTTTrrKssK
.........KttuuuUUUuuuuttTTTTTTTTTTTTKKLLssGGg
........KttuuuUUuuuuuttTTTTTTTTTTTTTKKssGGGGgg
""")
POISON_LOWER=block(73,20,"""
.....KttuuuuUuuuuuutttTTTTTTTTTTTTTTK...gggg
....KttuuuuuuuuuuuutttTTTTTTTTTTTTTTK...r
....KttuuuuuuuuuuuttttTTTTTTTTTTTTTTK..r
...KttuuuuuutuuuuttuuuttTTTTTTTTTTTTK.r
...KttuuuuuttuuuutuuuuttTTTTTTTTTTTTKr
..KttuuuuutttuuuutuuuutttTTTTTTTTTTrK
..KttuuuuutttuuuutuuuuutttTTTTTTTTrTK
.KttuuuuuttttuuuutuuuuutttTTTTTTTrTTTK
.KttuuuuuttttuuuutuuuuuttttTTTTTTrTTTK
KttuuuuttTTttttuuuutuuuuttTTttTTTTTTTK
KttuuttTTTTttttuuuutuuuttTTTtttTTTTTTK
KttttTTTTTttttuuutttttTTTTTTtttTTTTTTK
KttttTTTTTTtttuutttTTTTTTTTttttTTTTTTK
.KTTTTTTTTTTttttttTTTTTTTTTTtttTTTTTTK
..KTTTTTTTTTTTTKKKKTTTTTTTTTTTTTKKKKK
...KKKKKKKKKKKK....KKKKKKKKKKKKK
............KLLssK........KLLssK
...........KHHssSK........KHHssSK
..........KHHHHHHHK.......KHHHHHHHK
..........KKKKKKKKK.......KKKKKKKKK
""")
# Vapor leaves the visible lips; bubbles have hand selected broken rings.
POISON_VAPOR_A=Ink([
(40,52,'tu'),(39,54,'tu'),(38,56,'uT'),(37,58,'u'),
(33,71,'tut'),(34,70,'tU.uT'),(35,70,'tU.uT'),(36,71,'tut'),
(25,78,'tuut'),(26,77,'tUU.uT'),(27,77,'tU..uT'),
(28,78,'tutt')])
frame('poison_a',POISON_HEAD,POISON_BODY,POISON_LOWER,POISON_VAPOR_A)
POISON_B_ARMS=block(52,18,"""
..........KpVVVVVVppVVVVLLLSPppppppppPK
.........KpVVVVVVpppVVVVLLLpSPppVVppppPK
........KpVVVVVVppppVVVLLpppSPpVVVVppppPK
.......KpVVVVVVpppppVVVLpppppSPVVVVpppppPK
......KpVVVVVVppppppVVVpppppppPVVVpppppppPK
.....KpVVVVVVppppppVVVpppppppppPPVVpppppppPK
....KpVVVVVVppppppVVVpppppppKKssKKKppppppppPK
...KpVVVVVVppppppVVVppppppPKLLsssSKppppppppPK
..KpVVVVVVppppppVVVppppppKLLssSSSKrRRRrpppPPK
..KpVVVVVppppppVVVpppppPKssSSSKrReRRrppppPPK
.KpVVVVppppppVVVVpppppPPPKKKSKrReReRrppppPPK
.KpVVVppppppVVVVpppppPPPPPPPKrRReRRrPKpppPPK
.KpVVpppppVVVVpppppPPPPPPPPPPPrRRrrPPKpppPPK
.KpVppppVVVVpppppPPPPPPPPPPPPPPPrrPPPPKppPPK
.KppppVVVVpppppPPPPPPPggGGgggKKKPPPPPPKppPPK
..KppVVVpppppPPPPPPggGGGGgggggKKPPPPPPKppPPK
...KggGGgggPPPPPPPKgggggggKKttTTKKPPPPKppPPK
....KgggggPPPPPPPKKKKKKKKKttuuttTTKKKKKppPPK
.....KKKKKKKKKKKKttuuUUUUuuttttTTTTTTTKPPPK
..............KttuuUUUUUuuuuttTTTTTTTTKPPK
.............KttuuUUUUUuuuuttTTTTTTTTTKssK
............KttuuuUUUuuuuttTTTTTTTTTTKKLLssGGg
...........KttuuuUUuuuuuttTTTTTTTTTTTKKssGGGGgg
""")
POISON_B_FACE=Ink([(36,45,'Ls'),(36,47,'sPP'),(37,48,'ss'),(40,49,'ssK')])
POISON_VAPOR_B=Ink([
(41,52,'tu'),(40,55,'tu'),(39,57,'uT'),(38,60,'u'),
(30,73,'tuut'),(31,72,'tUU.uT'),(32,72,'tU..uT'),(33,73,'tutt'),
(22,83,'tut'),(23,82,'tU.uT'),(24,82,'tU.uT'),(25,83,'tut'),
(36,81,'uT'),(35,82,'u')])
frame('poison_b',POISON_HEAD,POISON_BODY,POISON_LOWER,POISON_B_ARMS,POISON_B_FACE,POISON_VAPOR_B)

STUN_HEAD=block(28,30,"""
.......KKKKK
......KHhhhHK
.....KHhhhhHHK
.....KHHhhHHHK.........GG
....KHHHHHHHHKK.....GGGg
...KHHhhhhHHHHHKKGGGgg
..KHhhhhhhhHHHHHGgg
.KHHhhhhHHHHHHHHHHK
.KHhhhHHHHHHHHHHHHHK
KHhhhHHHHHssssssHHHK
KHhhHHHHHLLLssssssHHK
KHhHHHHHLLLLsssssssHK
KHHHHHHHLLLssSSssssssK
KHHHHHHHLLLssPPsssSLsK
KHHHHHHHLLsssssPssssK
KHHHHHHHLLssSSsssssK
KHHHHHHHSssSSsssSSK
KHHHHHHHHSssssRssK
KHHHHHHHHKSSsssSK
KHHhHHHHHKSSssK
KHHhHHHHHHKSSK
KHHhHHHHHHKssK
KHHHHHHHHKKssSK
.KHHHHHHKPLssSPK
.KHHHHHKPVLssSPpK
..KHHHHKPVLsSPppPK
""")
STUN_BODY=block(54,18,"""
...........KKKpVKKKKPVVLSPpppKK
.........KKpVVVVVVVVVVLSPppppppKK
........KpVVVVVVVVVVVLLSPppppppppKK
.......KpVVVVVVppVVVVLLLSPpppppppppPK
......KpVVVVVVpppVVVVLLLpSPppVVppppppPK
.....KpVVVVVVppppVVVLLpppSPpVVVVppppppPK
....KpVVVVVVpppppVVVLpppppSPVVVVpppppppPK
...KpVVVVVVppppppVVVpppppppPVVVpppppppppPK
..KpVVVVVVppppppVVVpppppppppPPVVpppppppppPK
..KpVVVVVVppppppVVppppppppppPPPKppppppppppPK
.KpVVVVVVppppppVVpppppppppppPPPPKppppppppppPK
.KpVVVVVppppppVVpppppppppppPPPPPPKppppppppPPK
.KpVVVVppppppVVpppppppppppPPPPPPPPKppppppPPPK
.KpVVVppppppVVpppppppppppPPPPPPPPPPKpppppPPPK
.KpVVppppppVVppppppppppPPPPPPPPPPPPPKppppPPPK
.KpVppppppVVppppppppPPPPPPggGGgggKKPKppppPPPK
.KpppppppVVpppppppPPPPPggGGGGgggggKKKpppPPPK
.KppppppVVppppppPPPPPKKGgggggggKKttTKpppPPPK
.KpppppVVpppppPPPPPKKttuuUUUuutTTTTTKppPPPK
.KppppVVppppPPPPPKKttuuUUUUUuutTTTTTKppPPPK
.KpppVVpppPPPPPKKttuuuUUUUuuuuttTTTTTKpPPPK
.KppVVppPPPPPKKttuuuuuUUUuuuuttTTTTTTKPPPK
..KggGGgggPKKttuuuuuuuUUuuuuttTTTTTTTKPPK
...KgggggPKttuuuuuuuuuUuuuuttTTTTTTTTKsSK
....KKKKKKLLsKttuuuuuuuuuuuttTTTTTTTTKLLsK
.........KLLsKrRRRruuuuuttTTTTTTTTTTTKssGGg
.........KssSKrReRRruuuttTTTTTTTTTTTTK.KggGGg
.........KKKKrReReRruuttTTTTTTTTTTTTTK...ggGGg
............KrRReRRrttTTTTTTTTTTTTTTTK....gggg
..............rRRrrttTTTTTTTTTTTTTTTTTK...r
...............rrttTTTTTTTTTTTTTTTTTTTK..r
""")
STUN_HEM=block(85,20,"""
....KttttTTTTTTTTttttttTTTTTTTTTTTTTTTK.r
....KTTTTTTTTTTTTTTKKKKTTTTTTTTTTTTTTTKr
.....KKKKKKKKKKKKKK....KKKKKKKKKKKKKKKK
..............KLLssK.......KLLssK
..............KLLssK.......KLLssK
.............KHHssSK......KHHssSK
............KHHHHHHHK....KHHHHHHHK
............KKKKKKKKK....KKKKKKKKK
""")
STARS_A=Ink([
(15,39,'G'),(16,38,'GGG'),(17,36,'gGGGGGg'),(18,38,'GGG'),(19,39,'g'),
(22,65,'G'),(23,64,'GGG'),(24,62,'gGGGGGg'),(25,64,'GGG'),(26,65,'g')])
frame('stun_a',STUN_HEAD,STUN_BODY,STUN_HEM,STARS_A)
STUN_B_SLEEVE=block(70,18,"""
.KpppppppVVpppppppPPPPPggGGGGgggggKKKpppPPPK
.KppppppVVppppppPPPPPKKGgggggggKKttTKpppPPPK
.KpppppVVpppppPPPPPKKttuuUUUuutTTTTTKppPPPK
.KppppVVppppPPPPPKKttuuUUUUUuutTTTTTKppPPPK
.KpppVVpppPPPPPKKttuuuUUUUuuuuttTTTTTKpPPPK
.KppVVppPPPPPKKttuuuuuUUUuuuuttTTTTTTKPPPK
..KggGGgggPKKttuuuuuuuUUuuuuttTTTTTTTKPPPK
...KgggggPKttuuuuuuuuuUuuuuttTTTTTTTTKPPK
....KKKKKKLLsKttuuuuuuuuuuuttTTTTTTTTKsSK
.........KLLsKrRRRruuuuuttTTTTTTTTTTTKLLsK
.........KssSKrReeRruuuttTTTTTTTTTTTTKLLsGGg
.........KKKKrReReRruuttTTTTTTTTTTTTTKssGGGGg
............KrRRReRrttTTTTTTTTTTTTTTTKK.ggGGGg
..............rRRrrttTTTTTTTTTTTTTTTTTK...ggggg
...............rrttTTTTTTTTTTTTTTTTTTTK..r..ggg
""")
STARS_B=Ink([
(19,26,'G'),(20,25,'GGG'),(21,23,'gGGGGGg'),(22,25,'GGG'),(23,26,'g'),
(13,59,'G'),(14,58,'GGG'),(15,56,'gGGGGGg'),(16,58,'GGG'),(17,59,'g'),
(29,68,'GG'),(30,67,'gGGg'),(31,68,'gg')])
STUN_B_FACE=Ink([(40,42,'Ls'),(41,43,'sPP'),(42,44,'sss'),(45,44,'sSS')])
frame('stun_b',STUN_HEAD,STUN_BODY,STUN_HEM,STUN_B_SLEEVE,STUN_B_FACE,STARS_B)

SLEEP_HEAD=block(42,30,"""
.......KKKKK
......KHhhHHK
.....KHhhhhHHK
.....KHHhhHHHK.........GG
....KHHHHHHHHKK.....GGGg
...KHHhhhhHHHHHKKGGGgg
..KHhhhhhhhHHHHHGgg
.KHHhhhhHHHHHHHHHHK
.KHhhhHHHHHssssssHHK
KHhhhHHHHHLLLssssssHK
KHhhHHHHHLLLLsssssssK
KHhHHHHHHLLLssSSsssssK
KHHHHHHHHLLLssPPsssLsK
KHHHHHHHHLLsssssssssK
KHHHHHHHHSssSSsssSK
KHHHHHHHHSsssRsssK
KHHHHHHHHKssssSSK
KHHhHHHHHKSSsssK
KHHhHHHHHHKSSsK
KHHhHHHHHHKssK
KHHHHHHHHKKssSK
.KHHHHHHKPLssSPK
.KHHHHHKPVLssSPpK
..KHHHHKPVLsSPppPK
""")
SLEEP_BODY=block(66,18,"""
...........KKKpVKKKKPVVLSPpppKK
.........KKpVVVVVVVVVVLSPppppppKK
........KpVVVVVVVVVVVLLSPppppppppKK
.......KpVVVVVVppVVVVLLLSPppVVVppppPK
......KpVVVVVVpppVVVVLLLpSPpVVVVppppPK
.....KpVVVVVVppppVVVLLpppSPVVVVVpppppPK
....KpVVVVVVpppppVVVLpppppPVVVVpppppppPK
...KpVVVVVVppppppVVVpppppppPVVVppppppppPK
..KpVVVVVVppppppVVVpppppppppPPVVppppppppPK
..KpVVVVVVppppppVVppppppppppPPPKppppppppPK
.KpVVVVVVppppppVVpppppppppppPPPPKppppppPPPK
.KpVVVVVppppppVVpppppppppppPPPPPPKppppPPPPK
.KpVVVVppppppVVpppppppppppPPPPPPPPKppPPPPPK
.KpVVVppppppVVppppPPPggGGgggKKPPPPPKPPPPPK
.KpVVppppppVVppPPggGGGGgggggKssKKPPPKPPPKsK...g
.KpVppppppVVppPPPKgggggggKKKLLssKrRRRrKKLLssGGGGg
.KpppppppVVppPPPKKKKKKKKKKKssSsKrReRRr..KssSGGGGGgg
..KggGGgggPPPPPKttuuUUUUuttKKSKrReReRr...KKKgggggg
...KgggggPPPPPKttuUUUUUUuuutTTrRReRRrTTKKK
....KKKKKKKKKKttuuUUUUUuuuutTTTrRRrrTTtttKK
......KKttuuUUUUUUUUUuuuuuutttTTrrTTTTttttKK
....KKttuuuUUUUUUUUUuuuuuuttttTTTTTTTTTTtttKK
...KttuuuuuuuuuuuuuuuuuutttttTTTTTTTTTTTTtttK
..KttuuttTTttttuuuuuuuttttttTTTTTTTTTTTTTTttK
..KttttTTTTTTTTtttttttttttTTTTTTTTTTTTTTTTTTK
...KTTTTTTTTTTTTKKKKKKTTTTTTTTTTTTKKKKKKKKK
....KKKKKKKKKKKLLssKKKKKKKKKKKKKKLLssKKKK
""")
# Low shoes are embedded in the last seated hem rows, not floating legs.
SLEEP_GROUND=block(90,18,"""
..KttttTTTTTTTTtttttttttttTTTTTTTTTTTTTTTTTTK
...KTTTTTTTTTTTTKKKKKKTTTTTTTTTTTTKKKKKKKKK
....KKKKKKKKKKKHHHHKKKKKKKKKKKKKKHHHHKKKK
""")
frame('sleep_a',SLEEP_HEAD,SLEEP_BODY,SLEEP_GROUND)
SLEEP_B_BREATH=block(67,18,"""
.........KKpVVVVVVVVVVLLSPppppppKK
........KpVVVVVVVVVVVLLLSPppppppppKK
.......KpVVVVVVppVVVVLLLSPppVVVppppPK
......KpVVVVVVpppVVVVLLLpSPpVVVVppppPK
.....KpVVVVVVppppVVVLLpppSPVVVVVpppppPK
....KpVVVVVVpppppVVVLpppppPVVVVpppppppPK
...KpVVVVVVppppppVVVpppppppPVVVppppppppPK
..KpVVVVVVppppppVVVpppppppppPPVVppppppppPK
..KpVVVVVVppppppVVppppppppppPPPKppppppppPK
.KpVVVVVVppppppVVpppppppppppPPPPKppppppPPPK
.KpVVVVVppppppVVpppppppppppPPPPPPKppppPPPPK
""")
SLEEP_B_LAP=block(84,18,"""
...KgggggPPPPPKttuUUUUUUuuutTTrRReRRrTTKKK
....KKKKKKKKKKttuuUUUUUuuuutTTTrRRrrTTtttKK
......KKttuuUUUUUUUUUuuuuuuttTTTrrTTTTttttKK
....KKttuuuUUUUUUUUUuuuuuuttttTTTTTTTTTTtttKK
...KttuuuuuuuuuuuuuuuuuutttttTTTTTTTTTTTTtttK
..KttuuttTTttttuuuuuuuttttttTTTTTTTTTTTTTTttK
""")
frame('sleep_b',SLEEP_HEAD,SLEEP_BODY,SLEEP_GROUND,SLEEP_B_BREATH,SLEEP_B_LAP)

# Explicit visual repair, not connected-component filling: the skirt used to
# begin nine pixels farther right directly above the stun hem. Restore volume
# behind the lowered hand; retain the true gap between hand and shuttle.
STUN_A_LOWER_REPAIR=block(79,20,"""
....KttKLLsKrRRRruuuuuttTTTTTTTTTTTKssGGg
....KttKssSKrReRRruuuttTTTTTTTTTTTTK.KggGGg
....KttKKKKrReReRruuttTTTTTTTTTTTTTK...ggGGg
....KttuuuKrRReRRrttTTTTTTTTTTTTTTTK....gggg
....KttuuuuurRRrrttTTTTTTTTTTTTTTTTTK...r
....KttuuuuuurrttTTTTTTTTTTTTTTTTTTTK..r
""")
STUN_B_LOWER_REPAIR=block(79,20,"""
....KttKLLsKrRRRruuuuuttTTTTTTTTTTTKLLsK
....KttKssSKrReeRruuuttTTTTTTTTTTTTKLLsGGg
....KttKKKKrReReRruuttTTTTTTTTTTTTTKssGGGGg
....KttuuuKrRRReRrttTTTTTTTTTTTTTTTKK.ggGGGg
....KttuuuuurRRrrttTTTTTTTTTTTTTTTTTK...ggggg
....KttuuuuuurrttTTTTTTTTTTTTTTTTTTTK..r..ggg
""")
DEAD_FOOT_REPAIR=Ink([(86,18,'KLLssK'),(87,13,'KHHssSK'),(88,10,'KHHHHHHHK'),(89,10,'KKKKKKKKK')])
SEATED_FEET=Ink([
(90,31,'KLLsK'),(91,29,'KHHHHHK'),(92,29,'KKKKKKK'),
(90,58,'KLLsK'),(91,59,'KHHHHHHK'),(92,59,'KKKKKKKK')])
frame('stun_a',STUN_HEAD,STUN_BODY,STUN_HEM,STUN_A_LOWER_REPAIR,STARS_A)
frame('stun_b',STUN_HEAD,STUN_BODY,STUN_HEM,STUN_B_SLEEVE,STUN_B_FACE,STUN_B_LOWER_REPAIR,STARS_B)
frame('dead',DEAD,DEAD_FOOT_REPAIR)
frame('sleep_a',SLEEP_HEAD,SLEEP_BODY,SLEEP_GROUND,SEATED_FEET)
frame('sleep_b',SLEEP_HEAD,SLEEP_BODY,SLEEP_GROUND,SLEEP_B_BREATH,SLEEP_B_LAP,SEATED_FEET)

# Final cast: three separately readable open, curved silk ends. The roots cross
# at the shuttle, with independently chosen material highlights on each strand.
RIBBON_UPPER=Ink([
(42,72,'rReR'),(41,73,'rReR'),(40,74,'rReR'),(39,74,'rReR'),
(38,75,'rReR'),(37,76,'rReR'),(36,76,'rReR'),(35,76,'rReR'),
(34,77,'rReR'),(33,77,'rReR'),(32,78,'rReR'),(31,78,'rReR'),
(30,79,'rReR'),(29,80,'rReR'),(28,81,'rReRRr'),(27,83,'rReRRr'),
(26,85,'rRReRRr'),(25,87,'rRRRr'),
(27,89,'rReR'),(28,89,'rReR'),(29,88,'rReR'),(30,87,'rReR'),
(31,85,'rReRRr'),(32,83,'rReRRr'),(33,82,'rReR'),(34,81,'rReR'),
(35,81,'rReRRr'),(36,82,'rRReRRr'),(37,85,'rRRRr')])
RIBBON_MIDDLE=Ink([
(43,72,'rReR'),(42,75,'rRReRRr'),(41,79,'rReRRr'),(40,82,'rReRRr'),
(39,85,'rRReRRr'),(40,89,'rReR'),(41,90,'rReR'),(42,89,'rReR'),
(43,87,'rReRRr'),(44,84,'rReRRr'),(45,82,'rReRRr'),(46,81,'rReR'),
(47,82,'rReR'),(48,84,'rReRRr'),(49,87,'rrRRr')])
RIBBON_LOWER=Ink([
(45,72,'rReR'),(46,74,'rReR'),(47,76,'rReRRr'),(48,78,'rReRRr'),
(49,80,'rReRRr'),(50,82,'rReRRr'),(51,84,'rReRRr'),(52,86,'rReR'),
(53,87,'rReR'),(54,88,'rReR'),(55,88,'rReR'),(56,87,'rReR'),
(57,86,'rReR'),(58,84,'rReRRr'),(59,82,'rReRRr'),(60,80,'rReRRr'),
(61,79,'rReR'),(62,78,'rReR'),(63,78,'rReR'),(64,79,'rReR'),
(65,80,'rReRRr'),(66,82,'rReRRr'),(67,85,'rRRRr')])
CAST_WINDING=Ink([
(54,47,'rRRr'),(53,50,'rRRr'),(52,53,'rRRr'),(51,56,'rRRr'),
(50,59,'rRRr'),(49,62,'rRRr'),(48,65,'rRRr'),(47,68,'rRRr')])
frame('skill_b',HEAD,SKIRT,SKILL_CAST_BODY,SKILL_CAST_HEM,RIBBON_UPPER,RIBBON_MIDDLE,RIBBON_LOWER,CAST_WINDING)

# Advisory repair: explicit attack-only stepped thread; no automatic filling.
ATTACK_THREAD_REPAIR=Ink([
(47,81,'rr'),
(48,79,'rRrr'),
(49,78,'rr'),
(50,76,'rRr'),
(51,74,'rrr'),
(52,73,'Rr'),
(53,71,'rrr'),
(54,69,'rRr'),
(55,66,'rrrr'),
(56,62,'rrRrr'),
(57,61,'rr'),
(58,60,'Rr'),
(59,59,'rr'),
(60,57,'rrr'),
(61,56,'Rr'),
(62,54,'rrr'),
(63,52,'rRr'),
(64,46,'rrrRrrr'),
])
frame('attack',ATTACK_HEAD,ATTACK_BODY,ATTACK_SKIRT,ATTACK_THREAD_REPAIR)
if __name__=='__main__':save()
