"""Original, explicit native pixel clusters. Expand rows to literal 64x64 grids.

Each block has its own drawn silhouette. No geometry, interpolation, palette
swaps, tracing, or texture generator. Dots are transparent native pixels.
"""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parent.parent
PALETTES = {
    'jangseung-spirit': {
        'O':'#292831','D':'#3e343a','S':'#594b43','B':'#806558',
        'M':'#9b8470','H':'#baa17b','L':'#d8c391','C':'#8a5c48',
        'A':'#ab7959','K':'#1b222b','E':'#e4c57d','T':'#dfcb9e',
        'R':'#806440','r':'#b89a66',
    },
    'earthen-jar-fiend': {
        'O':'#292831','D':'#3e343a','S':'#604237','B':'#835638',
        'M':'#ad7649','H':'#c49760','L':'#d8b783','K':'#1b222b',
        'E':'#f5db8d','C':'#62353b','R':'#a34e45','r':'#c47354',
        'T':'#87715d',
    },
}

def save(slug, pose, x, y, block):
    rows = block.strip('\n').splitlines()
    grid = [['.'] * 64 for _ in range(64)]
    for dy, row in enumerate(rows):
        for dx, symbol in enumerate(row):
            assert symbol == '.' or symbol in PALETTES[slug], (slug, pose, symbol)
            assert 0 <= x + dx < 64 and 0 <= y + dy < 64
            grid[y + dy][x + dx] = symbol
    folder = ROOT / 'source' / slug
    folder.mkdir(parents=True, exist_ok=True)
    (folder / f'{pose}.pxgrid').write_text('\n'.join(''.join(row) for row in grid) + '\n')

for slug, palette in PALETTES.items():
    (ROOT / 'source').mkdir(parents=True, exist_ok=True)
    (ROOT / 'source' / f'{slug}.palette.json').write_text(json.dumps(palette, indent=2) + '\n')

# 46 hand drawn rows: splintered top, asymmetric carved face, trunk and roots.
save('jangseung-spirit', 'idle_a', 20, 15, """
...........OOO
.........OOBHLO
.......OOBMHHLBO
.......OBMMHHLBSO
......OBMMMHHLBCSO
......OMMMSMHLLCSO
......OMMMSMHLLCSO
......OBMMSMHHLCCSO
......OBSDDMMHHDCSO
......OBDDKDMHDKKDO
......OBSKEDMHDEKKO
......OBBSDMMHLCCSO
......OBBMMMHLLAASOO
......OBBSMMHLACLLLSO
......OBBSMMHLAACCSO
......OBBSMDKKKKKDO
......OBBMDDTKTKTDO
......OBBSDKTKTKTDO
......OBBBDDKKKKDDO
......OBBMMHAAAACSO
......OBSMHHHACCSSO
......OBSMHLCDBSSO
......OBSMHLDKBSSO
......OBSMHLCDBSSO
......OBSMHLCCBSSO
..OO..OBSMHLCCBSSO
.OBHO.OBSMHLCCBSSO....OO
.OBHHOOBSMHLCBBSSO...OACO
.OSMHOBSMHLCBSSSO..OOAHCO
..OSMOBSMHLCCBSSOOOAAHCSO
...OSOBSMHLCCBSSOAAHCSOO
....OOBSMHLCBBSSSSCSOO
......OBSMHLCCBSSSOO
......ORrrrRrrrRRRO
......OrrRRrrrRRrrO
......ORrrrRRrrrRRO
......OBSMHLCBBSSO
......OBSKHLCBBSSO
......OBSMHLCCBSSO
......OBSMHHCCBSSO
.....OOBBMHHCBSSSO
....OBBBMHLCBSSSSOO
...OBMMHLOOBBCSSBSBO
..OBMHLOO..OBBCSSBSBO
.OBHLOO....OBCSOOBSHBO
.OOOO......OOOO..OOOOO
""")

# 31 hand drawn rows. Eyes live in the dark opening, body remains ceramic.
save('earthen-jar-fiend', 'idle_a', 16, 30, """
..............OOOOOOOO
...........OOOBMHHHHMBOOO
..........OBMHHLLLLHHHMMBO
..........OSBMMHHHHMMMMBSO
.........OSDDKKKKKKKKKDDSSO
.........ODKKKKKKKKKKKKKKDO
.........ODKKKEKKKKKKEEKKDO
.........OSDKKEKKKKKKEKKDSO
..........OSDDKKKKKKKKDMBSO
.........OOBMHHHHHHHHHHLBSSO
........OBMHHLLLLHHHHMMMBSO
..OO...OBMHHLLLHHHMMMMMMBSSO...OO
.OBMO..OBMHHLLHHMMMMMBBMBBSSO.OHMO
.OBMMO.OBMHHLHHMMMMMMBMBBSSSOOHMMO
.OSBMO.OBMHHHHMMMSMMMMBBBSSSOMMBO
..OSBO.OBMHHHMMMMSMMMMBBBSSSOHBO
...OSOOOBMHHMMMMMSBMMMBBBSSSOSO
....OSSSBMHHMMMMMMSBMBBBSSSSO
.....OOSBMHHMMMMMMMMSBBBSSSSO
......OSBMHMMMMMMMMDMBBBSSSSO
.......OBMHMMMMMMMDMMBBSSSSO
.......OBMHMMMMMMDMMMBBSSSSO
.......OBMHMMMMMMMMMMBBSSSSO
........OBHMMMMMMMMMBRRRCSSO
........OBMHHMMMMMMBrrRCCSO
.........OBMMMMMMMBBRRCSSO
..........OBBMMMBBBBSSSSO
...........OSBBBBSSSSSO
..........OOBSSOOOOSSBSOO
.........OBMBSSO..OBMBBSSO
.........OOOOOOO..OOOOOOOO
""")

save('jangseung-spirit', 'idle_b', 20, 15, """
...........OOO
.........OOBHLO
.......OOBMHHLBO
.......OBMMHHLBSO
......OBMMMHHLBCSO
......OMMMSMHLLCSO
......OMMMSMHLLCSO
......OBMMSMHHLCCSO
......OBSDDMMHHDDDO
......OBDDKDMHDDKDO
......OBSKEDMHDEKKO
......OBBSDMMHLCCSO
......OBBMMMHLLAASOO
......OBBSMMHLACLLLSO
......OBBSMMHLAACCSO
......OBBSMDKKKKKDO
......OBBMDDTKTKTDO
......OBBSDKTKTKTDO
......OBBBDDKKKKDDO
......OBBMMHAAAACSO
......OBSMHHHACCSSO
......OBSMHLCDBSSO
......OBSMHLDKBSSO
......OBSMHLCDBSSO
......OBSMHLCCBSSO.....OO
......OBSMHLCCBSSO....OACO
..OO..OBSMHLCCBSSO...OAHCO
.OBHO.OBSMHLCBBSSO..OAAHCO
.OBMHOOBSMHLCBSSSO.OAAHCSO
..OBMOBSMHLCCBSSOOOAHCSOO
...OSOBSMHLCCBSSOAAHCSOO
....OOBSMHLCBBSSSSCSOO
......OBSMHLCCBSSSOO
......ORrrRRrrrRRRO
......OrrRRrrrRRrrO
......ORrrrRRrrrRRO
......OBSMHLCBBSSO
......OBSKHLCBBSSO
......OBSMHLCCBSSO
......OBSMHHCCBSSO
.....OOBBMHHCBSSSO
....OBBBMHLCBSSSSOO
...OBMMHLOOBBCSSBSBO
..OBMHLOO..OBBCSSBSBO
.OBHLOO....OBCSOOOBHBO
.OOOO......OOOO..OOOOO
""")

save('jangseung-spirit', 'idle_c', 20, 15, """
...........OOO
.........OOBHLO
.......OOBMHHLBO
.......OBMMHHLBSO
......OBMMMHHLBCSO
......OMMMSMHLLCSO
......OMMMSMHLLCSO
......OBMMSMHHLCCSO
......OBSDDMMHHDCSO
......OBDDKDMHDKKDO
......OBSKEDMHDEKKO
......OBBSDMMHLCCSO
......OBBMMMHLLAASOO
......OBBSMMHLACLLLSO
......OBBSMMHLAACCSO
......OBBSMDKKKKKDO
......OBBMDDTKTKTDO
......OBBSDKKKKKKDO
......OBBBDDTKTKDDO
......OBBMMHAAAACSO
......OBSMHHHACCSSO
......OBSMHLCDBSSO
......OBSMHLDKBSSO
......OBSMHLCDBSSO
..OO..OBSMHLCCBSSO
.OBHO.OBSMHLCCBSSO
.OBHHOOBSMHLCCBSSO
.OSMHOBSMHLCBBSSO
..OSMOBSMHLCBSSSO.....OO
...OSOBSMHLCCBSSO....OACO
....OOBSMHLCCBSSO..OOAHCO
......OBSMHLCBBSSOOAAHCSO
......OBSMHLCCBSSAAHCSOO
......ORrrrRrrrRRRSOO
......OrrRRrrrRRrrO
......ORrrrRRrrrRRO
......OBSMHLCBBSSO
......OBSKHLCBBSSO
......OBSMHLCCBSSO
......OBSMHHCCBSSO
.....OOBBMHHCBSSSO
....OBBBMHLCBSSSSOO
...OBMMHLOOBBCSSBSBO
..OBMHLOO..OBBCSSBSBO
.OBHLOO....OBCSOOBSHBO
.OOOO......OOOO..OOOOO
""")

# Windup: crown twists left, branch elbow pulled back, front root curls.
save('jangseung-spirit', 'windup', 18, 14, """
........OOO
......OOBHLO
.....OBMHHLBO
....OBMMHHLBSO
....OMMMHHLLCSO
....OMSMHHLACSO
....OMSMHHACCSO
....OBMMHHLCCSO
....OBDDMMHHDDO
....ODKDMHDKKDO
....OSKEDMHEKKO
....OBSDMHHLCSO
....OBMMHHLAASOO
....OBSMHLACLLLSO
....OBSMHLAACCSO
....OBSDKKKKKDO
....OBDDTKTKTDO
....OBDKKKKKKDO
....OBSDTKTKTDO
....OBMMHAAACSO
.....OBMHHACSSO
.....OBMHLCDBSO
.....OBMHLKDBSO
..OO.OBMHLCCBSSO
.OBHOBBMHLCCBSSO
.OHMMBMHHLCCBSSO
.OBHMMMHHLCCBSSO
..OBBMMMHHLCCBSSO
...OOBMMMHLCBBSSO
.....OBSMHLCBBSSO
.....OBSMHLCBBSSO....OO
......OBSMHLCCBSSO..OACO
......OBSMHLCCBSSOOOAHCO
......OBSMHLCCBSSOAAHCSO
......ORrrrRrrrRRRSSOO
......OrrRRrrrRRrrOOO
......ORrrrRRrrrRRO
......OBSMHLCBBSSO
......OBSKHLCBBSSO
......OBSMHLCCBSSO
......OBSMHHCCBSSO
.....OOBBMHHCBSSSO
....OBBBMHLCBSSSSOO
...OBMMHLOOBBCSSBSBO
..OBMHLOO..OBBCSSBBO
.OBHLOO....OBCSOOBBOO
.OOOO......OOOO..OOOOO
""")

# Move: back root lifts as front root stretches; branches counterbalance.
save('jangseung-spirit', 'move', 18, 15, """
.............OOO
...........OOBHLO
.........OOBMHHLBO
.........OBMMHHLBSO
........OBMMMHHLBCSO
........OMMMSMHLLCSO
........OMMMSMHLLCSO
........OBMMSMHHLCCSO
........OBSDDMMHHDCSO
........OBDDKDMHDKKDO
........OBSKEDMHDEKKO
........OBBSDMMHLCCSO
........OBBMMMHLLAASOO
........OBBSMMHLACLLLSO
........OBBSMMHLAACCSO
........OBBSMDKKKKKDO
........OBBMDDTKTKTDO
........OBBSDKTKTKTDO
........OBBBDDKKKKDDO
........OBBMMHAAAACSO
........OBSMHHHACCSSO
........OBSMHLCDBSSO
........OBSMHLDKBSSO
........OBSMHLCDBSSO...OO
........OBSMHLCCBSSO..OACO
........OBSMHLCCBSSO.OAHCO
........OBSMHLCCBSSOOAHCSO
...OO...OBSMHLCBBSSOAHCSO
..OBHO..OBSMHLCBSSSAHCSO
.OBMHHOOOBSMHLCCBSSCSOO
..OBBMSSOBSMHLCCBSSOO
...OOBSSOBSMHLCBBSSO
.....OOOOBSMHLCCBSSO
........ORrrrRrrrRRRO
........OrrRRrrrRRrrO
........ORrrrRRrrrRRO
........OBSMHLCBBSSO
........OBSKHLCBBSSO
........OBSMHLCCBSSO
.......OOBSMHHCCBSSO
......OBBBMHHCBSSSO
.....OBMMHHLCBSSSSO
....OBHLOOOBBCSSSSO
.....OO....OBBCSSSBOOO
...........OBBCSSBBBHBO
...........OOOOOOOOOOO
""")

# Attack: head lunges right and branch fist extends, trunk bows from root.
save('jangseung-spirit', 'attack', 18, 16, """
..................OOO
................OOBHLO
..............OOBMHHLBO
.............OBMMHHLBSO
............OBMMMHHLBCSO
............OMMMSMHLLCSO
...........OMMMSMHLLCCSO
...........OBMMSMHHLCCSO
..........OBSDDMMHHDDDSSO
..........OBDDKDMHDDKKDO
..........OBSKEDMHDEKKO
.........OBBSDMMHLCCSO
.........OBBMMMHLLAASOO
.........OBBSMMHLACLLLSO
........OBBSMMHLAACCSO
........OBBSMDKKKKKDO
.......OBBMDDTKTKTDO
.......OBBSDKKKKKKDO
.......OBBBDDTKTKDDO
.......OBBMMHAAAACSO
.......OBSMHHHACCSSO
......OBSMHLCDBSSO
......OBSMHLDKBSSO
......OBSMHLCDBSSO...........OOO
......OBSMHLCCBSSO.........OOAHCO
..OO..OBSMHLCCBSSO......OOOAAHHCO
.OBHO.OBSMHLCCBSSOOOOOOOAAAHLLHCO
.OBHHOOBSMHLCBBSSAAAHHHHHHAAHHCO
.OSMHOBSMHLCBSSSSCCAAAAAAAACCSO
..OSMOBSMHLCCBSSOOOOOOOOOOOOOO
...OSOBSMHLCCBSSO
....OOBSMHLCBBSSO
......OBSMHLCCBSSO
......ORrrrRrrrRRRO
......OrrRRrrrRRrrO
......ORrrrRRrrrRRO
......OBSMHLCBBSSO
......OBSKHLCBBSSO
......OBSMHLCCBSSO
......OBSMHHCCBSSO
.....OOBBMHHCBSSSO
....OBBBMHLCBSSSSOO
...OBMMHLOOBBCSSBSBO
..OBMHLOO..OBBCSSBSBO
.OOOOOO....OOOOOOOOOOO
""")

save('jangseung-spirit', 'recover', 20, 16, """
............OOO
..........OOBHLO
........OOBMHHLBO
........OBMMHHLBSO
.......OBMMMHHLBCSO
.......OMMMSMHLLCSO
.......OMMMSMHLLCSO
.......OBMMSMHHLCCSO
.......OBSDDMMHHDCSO
.......OBDDKDMHDKKDO
.......OBSKEDMHDEKKO
.......OBBSDMMHLCCSO
.......OBBMMMHLLAASOO
.......OBBSMMHLACLLLSO
.......OBBSMMHLAACCSO
.......OBBSMDKKKKKDO
.......OBBMDDTKTKTDO
.......OBBSDKTKTKTDO
.......OBBBDDKKKKDDO
.......OBBMMHAAAACSO
.......OBSMHHHACCSSO
......OBSMHLCDBSSO
......OBSMHLDKBSSO
......OBSMHLCDBSSO
......OBSMHLCCBSSO
......OBSMHLCCBSSO
..OO..OBSMHLCCBSSO
.OBHO.OBSMHLCBBSSO
.OBMHOOBSMHLCBSSSO
..OBMOBSMHLCCBSSO.....OO
...OSOBSMHLCCBSSO...OOACO
....OOBSMHLCBBSSOOOAAHCO
......OBSMHLCCBSSAAAHCSO
......ORrrrRrrrRRRSCSO
......OrrRRrrrRRrrOOO
......ORrrrRRrrrRRO
......OBSMHLCBBSSO
......OBSKHLCBBSSO
......OBSMHLCCBSSO
.....OOBSMHHCCBSSO
....OBBBMHHCBSSSO
...OBMMHHLCBSSSSOO
..OBMHLOOOBBCSSBSBO
.OBHLOO...OBBCSSBSBO
.OOOO.....OOOOOOOOOOO
""")

# Hit: carved crown recoils left, a light splinter is bounded by a dark cleft.
save('jangseung-spirit', 'hit', 18, 16, """
......OOO
....OOBHLO
...OBMHHLBO
..OBMMHHLBSO
..OMMMHHLBCSO
..OMSMHLLACSO
..OMSMHLLACSO
..OBMMSHHLCCSO
..OBSDDMMHHDCSO
..OBDDKDMHDKKDO
..OBSKKDMHDKKKO
..OBBSDMMHLCCSO
..OBBMMMHLLAASOO
..OBBSMMHLACLLLSO
..OBBSMMHLAACCSO
..OBBSMDKKKKKDO
..OBBMDDTKTKTDO
..OBBSDKKKKKKDO
..OBBBDDTKTKDDO
...OBBMMHAAAACSO
....OBSMHHHACCSSO
.....OBSMHLCDBSSO
.....OBSMHLDKBSSO......OO
.....OBSMHLCDBSSO.....OACO
.....OBSMHLDKBSSO....OAHCO
..OO.OBSMHLDKBSSO...OAHCO
.OBHOBBSMHLKLBSSO..OAAHCSO
.OHMMBBSMHLKLBSSO.OAAHCSO
.OBMMBBSMHLKDBSSOOAAHCSO
..OBBSBSMHLKDBSSAAHCSOO
...OOBBSMHLCCBSSCSOO
.....OBSMHLCBBSSOO
......OBSMHLCCBSSO
......ORrrrRrrrRRRO
......OrrRRrrrRRrrO
......ORrrrRRrrrRRO
......OBSMHLCBBSSO
......OBSKHLCBBSSO
......OBSMHLCCBSSO
......OBSMHHCCBSSO
.....OOBBMHHCBSSSO
....OBBBMHLCBSSSSOO
...OBMMHLOOBBCSSBSBO
..OBMHLOO..OBBCSSBSBO
.OOOOOO....OOOOOOOOOOO
""")

# Dead: two separate broken timber masses; sideways face remains visible.
save('jangseung-spirit', 'dead', 17, 39, """
......OOO
....OOBHLO
...OBMHHLBO
...OBMMHHLBO
..OBMMHHLLCSO
..OMMMHLLACSO
..OMSMHLLACSO
..OBMMHHLCCSO
..OBSDDMMHHDCSO
..OBDDKDMHDKKDO
..OBSKKDMHEKKKO
..OBBSDMMHLCCSO
..OBBMMMHLLAASOO
..OBBSMMHLACLLLSO
..OBBSMMHLAACCSO.....OOO
..OBBSMDKKKKKDO.....OBHLO
..OBBMDDTKTKTDO....OBMHLBOOO
..OBBSDKTKTKTDO...OBMMHLBBBSO
..OBBBDDKKKKDDO..OBMrRrrrBCSO
..OBBMMHAAAACSODOBMMrRrrBBSSO
...OBSMHLCBBSSOOBHHHrRRBSSSO
....OOOOOOOOOOOOOOOOOOOOOOO
""")

save('earthen-jar-fiend', 'idle_b', 16, 30, """
..............OOOOOOOO
...........OOOBMHHHHMBOOO
..........OBMHHLLLLHHHMMBO
..........OSBMMHHHHMMMMBSO
.........OSDDKKKKKKKKKDDSSO
.........ODKKKKKKKKKKKKKKDO
.........ODKKKEKKKKKKEEKKDO
.........OSDKKEKKKKKKEKKDSO
..........OSDDKKKKKKKKDMBSO
.........OOBMHHHHHHHHHHLBSSO
........OBMHHLLLLHHHHMMMBSO
.......OBMHHLLLHHHMMMMMMBSSO...OO
..OO...OBMHHLLHHMMMMMBBMBBSSO.OHMO
.OBMO..OBMHHLHHMMMMMMBMBBSSSOOHMMO
.OBMMO.OBMHHHHMMMSMMMMBBBSSSOMMBO
.OSBMO.OBMHHHMMMMSMMMMBBBSSSOHBO
..OSBOOOBMHHMMMMMSBMMMBBBSSSOSO
...OSSSSBMHHMMMMMMSBMBBBSSSSO
.....OOSBMHHMMMMMMMMSBBBSSSSO
......OSBMHMMMMMMMMDMBBBSSSSO
.......OBMHMMMMMMMDMMBBSSSSO
.......OBMHMMMMMMDMMMBBSSSSO
.......OBMHMMMMMMMMMMBBSSSSO
........OBHMMMMMMMMMBRRRCSSO
........OBMHHMMMMMMBrrRCCSO
.........OBMMMMMMMBBRRCSSO
..........OBBMMMBBBBSSSSO
...........OSBBBBSSSSSO
..........OOBSSOOOOSSBSOO
.........OBMBSSO..OBMBSSSO
.........OOOOOOO..OOOOOOOO
""")

save('earthen-jar-fiend', 'idle_c', 16, 30, """
..............OOOOOOOO
...........OOOBMHHHHMBOOO
..........OBMHHLLLLHHHMMBO
..........OSBMMHHHHMMMMBSO
.........OSDDKKKKKKKKKDDSSO
.........ODKKKKKKKKKKKKKKDO
.........ODKKKKEKKKKKEEKKDO
.........OSDKKKKKKKKKEKKDSO
..........OSDDKKKKKKKKDMBSO
.........OOBMHHHHHHHHHHLBSSO
........OBMHHLLLLHHHHMMMBSO
..OO...OBMHHLLLHHHMMMMMMBSSO
.OBMO..OBMHHLLHHMMMMMBBMBBSSO
.OBMMO.OBMHHLHHMMMMMMBMBBSSSO...OO
.OSBMO.OBMHHHHMMMSMMMMBBBSSSO.OHMO
..OSBO.OBMHHHMMMMSMMMMBBBSSSOOHMMO
...OSOOOBMHHMMMMMSBMMMBBBSSSOMMBO
....OSSSBMHHMMMMMMSBMBBBSSSSOHBO
.....OOSBMHHMMMMMMMMSBBBSSSSOSO
......OSBMHMMMMMMMMDMBBBSSSSOO
.......OBMHMMMMMMMDMMBBSSSSO
.......OBMHMMMMMMDMMMBBSSSSO
.......OBMHMMMMMMMMMMBBSSSSO
........OBHMMMMMMMMMBRRRCSSO
........OBMHHMMMMMMBrrRCCSO
.........OBMMMMMMMBBRRCSSO
..........OBBMMMBBBBSSSSO
...........OSBBBBSSSSSO
..........OOBSSOOOOSSBSOO
.........OBMBSSO..OBMBBSSO
.........OOOOOOO..OOOOOOOO
""")

# Windup: lid seals down; broad body squashes, bent arms tuck inward.
save('earthen-jar-fiend', 'windup', 16, 35, """
............OOOOOOOOOOOO
..........OOBMHHHHHHHHMBOO
.........OBMHHLLLLLLHHMMBBO
........OBMHHHHHHHHMMMMBBSSO
........OSBBMMMMMMMMBBBSSSSO
........ODDDDDDDDDDDDDDDDDO
.........ODKKEKKKKKKKEKKDO
.........OSDDDDDDDDDDDSSO
........OBMHHLLLLHHHHMMMBSO
.......OBMHHLLLHHHHMMMMMBSSO
......OBMHHLLLHHHMMMMBBMMBSSO
..OO..OBMHHHHHMMMMMMBMBBBSSSO...OO
.OBMO.OBMHHHHMMMSMMMMBBBBSSSO..OHMO
.OHMO.OBMHHHMMMMSMMMMBBBBSSSO..OHMO
.OBMO.OBMHHMMMMMSBMMMBBBSSSSOOOMBO
..OSOOOBMHHMMMMMMSBMBBBSSSSSOMMBO
...OSSSBMHHMMMMMMMMSBBBSSSSSSBSO
.....OOBMHMMMMMMMMDMBBBSSSSSOOO
......OBMHMMMMMMMDMMMBBSSSSSO
.......OBMHHMMMMDMMMMBBRRRSSO
.......OBMMMMMMMMMMMMBrrRCCSO
........OBMMMMMMMMMMBBRRCSSO
.........OBBMMMMMBBBBSSSSSO
..........OSBBBBBBSSSSSSO
.........OBMBSSOOOOBMBBSSO
.........OOOOOOO..OOOOOOOO
""")

# Move: slanted lid and rim, narrow back foot tucked, long front clay toe.
save('earthen-jar-fiend', 'move', 16, 28, """
.................OOOOOO
..............OOOBMHHHMBO
...........OOOBMHHLLLHHMBO
..........OBMHHLLLHHHMMBSSO
..........OSBMMHHMMMMBSSSO
..........ODDKKKKKKKKKDSSO
..........ODKKKKKKKKKKKKDO
..........ODKKKEEKKKKEEKKDO
..........OSDKKEKKKKKEKKDSO
...........OSDDKKKKKKKDDSSO
...........OBMHHHHHHHHHMBSSO
..........OBMHHLLLLHHHHMBBSSO
.........OBMHHLLLHHHMMMMBBSSSO
..OO.....OBMHHLLHHMMMMMBBMSSSO
.OBMO....OBMHHLHHMMMMMMBMBBSSO
.OBMMO...OBMHHHHMMMSMMMMBBBSSSO
.OSBMMOO.OBMHHHMMMMSMMMMBBBSSSO
..OSBMSSOOBMHHMMMMMSBMMMBBBSSSO
...OSSSSSBMHHMMMMMMSBMBBBSSSSO
.....OOOSBMHHMMMMMMMMSBBBSSSSO..OO
.......OSBMHMMMMMMMMDMBBBSSSSO.OHMO
........OBMHMMMMMMMDMMBBSSSSOOHMBO
........OBMHMMMMMMDMMMBBSSSSOHMBO
........OBMHMMMMMMMMMMBBSSSSOMBO
.........OBHMMMMMMMMMBRRRCSSOOSO
.........OBMHHMMMMMMBrrRCCSO.OO
..........OBMMMMMMMBBRRCSSO
...........OBBMMMBBBBSSSSO
...........OSBBBBSSSSSSO
..........OBSSOOOOSBBSSO
...........OO....OSBMSSOO
.................OBMMMBSBO
.................OOOOOOOOO
""")

# Attack: dark mouth expands, lower jaw lip rises at the near right corner.
# Near clay arm is drawn as a knuckled punch, far arm opens away from body.
save('earthen-jar-fiend', 'attack', 16, 27, """
...................OOOOOO
...............OOOOBMHHMBO
............OOOBMHHLLLLHMBO
...........OBMHHHLLLLHHMBSSO
...........OSBMMHHHMMMMBSSSO
..........OSDDKKKKKKKKKKDDSSO
..........ODKKKKKKKKKKKKKKKDO
..........ODKKKKEKKKKKKKEEKDO
..........ODKKKKEKKKKKKKEKKDO
..........ODKKKKKKKKKKKKKKKDO
..........ODKKKKKKKKKKKKKKKDO
..........ODKKKKKKKKKKKKKKKDO
..........ODKKKKKKKKKKKKKKDSO
..........ODKKKKKKKKKKDDSSOOO
.........OOBMHHHHHHHHLLLLHHMBOOO
........OBMHHLLLLLLLLLHHHHMMMMBSO
........OSBMMMMHHHHHMMMMBBBSSSSO
.......OBMHHLLLHHHMMMMMMMBBSSO
..OO...OBMHHLLHHMMMMMMBMBBSSSO.........OO
.OBMO..OBMHHLHHMMMMMMMBMBBSSSO.......OOHMO
.OBMMO.OBMHHHHMMMSMMMMMBBBSSSO......OHLLMO
.OSBMO.OBMHHHMMMMSMMMMMBBBSSSO....OOHLLHMO
..OSBOOOBMHHMMMMMSBMMMMBBBSSSSOOOOHHHMHMBO
...OSSSSBMHHMMMMMMSBMMBBBBSSSSMHMMMMMMBSO
.....OOSBMHHMMMMMMMMSMBBBBSSSSBBBBBBBSSSO
......OSBMHMMMMMMMMDMBBBBSSSSSOOOOOOOOOO
.......OBMHMMMMMMMDMMBBBSSSSSO
.......OBMHMMMMMMDMMMBBBSSSSSO
........OBHMMMMMMMMMBBRRRCSSO
........OBMHHMMMMMMBBrrRCCSO
.........OBMMMMMMMBBBRRCSSO
..........OBBMMMBBBBBSSSSO
.........OBMBSSOOOOBMBBSSO
.........OOOOOOO..OOOOOOOO
""")

# Recover: lip settles unevenly, arms droop with open hand tips.
save('earthen-jar-fiend', 'recover', 16, 31, """
...............OOOOOO
............OOOBMHHMBOO
..........OOBMHHLLLLHHMBO
..........OSBMMHHHHMMMBSO
.........OSDDKKKKKKKKKDDSSO
.........ODKKKKKKKKKKKKKKDO
.........ODKKKEKKKKKKEEKKDO
.........OSDKKEKKKKKKEKKDSO
..........OSDDKKKKKKKKDMBSO
.........OOBMHHHHHHHHHHLBSSO
........OBMHHLLLLHHHHMMMBSO
.......OBMHHLLLHHHMMMMMMBSSO
.......OBMHHLLHHMMMMMBBMBBSSO
.......OBMHHLHHMMMMMMBMBBSSSO
..OO...OBMHHHHMMMSMMMMBBBSSSO
.OBMO..OBMHHHMMMMSMMMMBBBSSSO
.OHMO..OBMHHMMMMMSBMMMBBBSSSO
.OBMO.OOBMHHMMMMMMSBMBBBSSSSOO
..OSOOSSBMHHMMMMMMMMSBBBSSSSSSOO
...OSSSBMHMMMMMMMMDMBBBSSSSSSMBO
.....OOOBMHMMMMMMMDMMBBSSSSOOMMBO
.......OBMHMMMMMMDMMMBBSSSSO.OMMO
.......OBMHMMMMMMMMMMBBSSSSO..OMO
........OBHMMMMMMMMMBRRRCSSO...OO
........OBMHHMMMMMMBrrRCCSO
.........OBMMMMMMMBBRRCSSO
..........OBBMMMBBBBSSSSO
...........OSBBBBSSSSSO
.........OBMBSSOOOOBMBBSSO
.........OOOOOOO..OOOOOOOO
""")

# Hit: body recoils left, lid hinges up to right, new angular ceramic split.
save('earthen-jar-fiend', 'hit', 14, 30, """
....................OOO
..................OOBHLO
................OOBMHHLBO
.............OOOBMHHHMMBO
..........OOOBMHHHMMBSSO
.........OBMMHHMMBSSSO
........OSDDKKKKDDSSO
........ODKKKKKKKKKKDO
........ODKKKKKKKKKKKKDO
........ODKKEKKKKKEKKKKDO
........OSDKKKKKKKKKKDSSO
.........OSDDKKKKKKDDSO......OO
........OOBMHHHHHHHMBSO.....OHMO
.......OBMHHLLLLHHMMMBSO...OHMMO
......OBMHHLLLHHMMMMMBSSO.OHMBO
..OO..OBMHHLLHHMMMMMBBBSSOOHMBO
.OBMO.OBMHHLHHMMMMDMMMBBSSOMBO
.OHMMOOBMHHHHMMMDKMMMMBBSSSOO
.OBMMSSBMHHHMMMDKMMMMBBSSSO
..OBBSSBMHHMMMMDMMMDMBBSSSO
...OOSSBMHHMMMMMMMDMMBBSSSO
......OBMHMMMMMMMMMDMBBSSSO
......OBMHMMMMMMMMMMDMBSSSO
......OBMHMMMMMMMMMMMBBSSSO
.......OBHMMMMMMMMMMBRRRCSSO
.......OBMHHMMMMMMMBrrRCCSO
........OBMMMMMMMMBBRRCSSO
.........OBBMMMMBBBBSSSSO
.........OSBBBBBBSSSSSO
........OBMBSSOOOOBMBBSSO
........OOOOOOO..OOOOOOOO
""")

# Dead: rim is crumpled and body sprawls; separate tipped lid at right.
save('earthen-jar-fiend', 'dead', 16, 44, """
...........................OOO
..........................OBHLO
.........................OBHLMBO
.......OOOOOOOOOO........OBHLMBSO
.....OOBMHHHHHMBSOO.....OBHMMBSSO
....OBMHHLLLHHMMBSSO...OBMMBSSSO
....OSBMMMMMMMMBBSSSO..OBMBSSSO
....ODDKKKKKKKKKKDSSO..OBBSSO
...ODKKKKKKKKKKKKKDSO...OOO
...OSDDKKKKKKKKKDDSSO
..OOBMHHHHHHHHHMMBBSSOO
.OBMHHLLHHMMMDMMMMBSSSSO
.OBMHHHHMMMMDMMMDMBBSSSSOO
.OSBMMMMMMMDMMMDMMBBRRRCSSO
..OSBBMMMMMMMMMMMBBrRRCSSSO
...OSBBBBMMMBBBBBBRSSSSSSO
....OOOOOOOOOOOOOOOOOOOOO
""")
