import fs from 'node:fs';import assert from 'node:assert/strict';
import {openLocalProjectStore} from '../../electron/local-store/store.ts';
import {repairBeodeulVillage50Roads} from '../content/lib/beodeul-village50.mts';
import {renderMapPng} from '../qa-game/render.mts';
const out='output/beodeul-village50',evidence='verify-shots/beodeul-village50-road-fix';fs.mkdirSync(evidence,{recursive:true});
const projectDir='/home/main/.local/share/oprn/assistant-house-entry-e7d2-20261004';
const store=await openLocalProjectStore({projectDir}),before=store.loadSnapshot()!;
assert.equal(before.revision,22);store.close();
const p=before.project,m=p.maps.map_beodeul_village50!,original=structuredClone(m);
fs.writeFileSync(`${evidence}/before-map.json`,JSON.stringify(original));
fs.writeFileSync(`${out}/before-store.json`,JSON.stringify({sha256:before.sha256,revision:before.revision}));
const result=JSON.parse(fs.readFileSync(`${out}/build-result.json`,'utf8'));
const fixed=repairBeodeulVillage50Roads(p,m.id,result);
const {lowerTiles:oldFloor,...oldRest}=original,{lowerTiles:floor,...rest}=m;
assert.deepEqual(rest,oldRest,'Only the ground layer may change.');
fs.writeFileSync(`${out}/preview-project.json`,JSON.stringify(p));
fs.writeFileSync(`${out}/build-result.json`,JSON.stringify({...result,...fixed},null,2));
fs.writeFileSync(`${evidence}/repair-proof.json`,JSON.stringify({...fixed.roadRepair,objectsEventsShadowsAndPalettePreserved:true},null,2));
fs.writeFileSync(`${evidence}/after.png`,renderMapPng({...p,startMapId:''},m).png);
console.log(JSON.stringify(fixed.roadRepair));
