// Focused corrections on real Beodeul stamps. Reads the existing QA fixture; no project writes.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {PNG} from 'pngjs';
import {SunlightField, sunlightField} from '../../src/project/sunlight';
import {rasterSunlightArt} from '../../src/project/sunlightArt';
import type {Project} from '../../src/project/types';
const p=JSON.parse(fs.readFileSync('.vite-cache/sunlight/project/project.json','utf8')) as Project;
const m=structuredClone(p.maps.houses_native!),t=p.tilesets[m.tilesetId]!;
const image=PNG.sync.read(fs.readFileSync('public/assets/beodeul-city/beodeul-city-chipset.png'));
const art=rasterSunlightArt(image,t.tileSize,t.tilesPerRow),checks:string[]=[];
m.sunlight={enabled:true,azimuth:135,altitude:24,opacity:.32,softness:2,heightScale:1};
const field=new SunlightField(m,t,art);assert.equal(field.casters.length,4);
const manor=field.casters.find(c=>c.id==='sp_a2ff01d4-09f0-4e24-a2c7-65a12be34406')!;
assert.equal(manor.volumes?.length,3);const main=manor.volumes!.reduce((a,b)=>a.w>b.w?a:b);
assert.ok(manor.volumes!.filter(v=>v!==main).every(v=>v.height<2));
assert.ok(Math.max(...main.high)-Math.min(...Array.from(main.high).filter(n=>n>0))>1.5);
checks.push('tower, chimney and main roof retain different column heights; detached statues stay below two tiles');
const cabin=field.casters.find(c=>c.id==='sp_dbe5965d-2ed8-410c-bf8a-109803471270')!;
const gable=cabin.volumes![0]!;assert.ok(Math.max(...gable.high)-Math.min(...Array.from(gable.high).filter(n=>n>0))>1);
checks.push('front gable has a pitched silhouette rather than a flat rectangular top');
const wide=field.casters.find(c=>c.id==='sp_4e36815d-5fed-4f58-acc9-253a9b2b5201')!;
const roof=wide.volumes![0]!;assert.ok(roof.w>14);assert.ok(roof.low[3]!>2);assert.equal(roof.low[30],0);
checks.push('15-tile roof retains nine-tile walls: air below the eaves and solid central walls');
const alpha=(x:number,y:number)=>{const row=field.row(Math.floor(y));const px=Math.floor(x*4-row.x),py=Math.floor(y*4-row.y);return row.rgba[(py*row.w+px)*4+3]!;};
assert.ok(alpha(18.125,44.125)>0);assert.equal(alpha(23.125,44.125),0);
checks.push('empty grass inside the stamp receives shadow while opaque wall art stays unchanged');
const erased=structuredClone(m);for(const s of erased.structurePlacements!)for(let y=s.y;y<s.y+s.h;y++)for(let x=s.x;x<s.x+s.w;x++)erased.upperTiles[y*erased.width+x]=-1;
assert.equal(new SunlightField(erased,t,art).casters.length,0);
checks.push('erased or repainted building tiles do not leave stamp-shaped ghost casters');
const cached=sunlightField(m,t,art);assert.equal(sunlightField(m,t,art),cached);assert.notEqual(sunlightField(m,t),cached);
checks.push('art source participates in cache identity; later image loading replaces approximate geometry');
const off=structuredClone(m);off.sunlight!.enabled=false;assert.equal(sunlightField(off,t,art),null);
checks.push('default/off remains allocation-free');
const observations={checks,casters:field.casters.map(({id,height,volumes})=>({id,height,components:volumes?.map(v=>({x:v.x,y:v.y,w:v.w,d:v.d,height:v.height,lowMin:Math.min(...v.low),lowMax:Math.max(...v.low)}))})),emptyGrassAlpha:alpha(18.125,44.125),opaqueWallAlpha:alpha(23.125,44.125),projectWrites:false};
fs.mkdirSync('verify-shots/building-shadow-shapes/contracts',{recursive:true});fs.writeFileSync('verify-shots/building-shadow-shapes/contracts/observations.json',JSON.stringify(observations,null,2)+'\n');console.log(JSON.stringify(observations,null,2));
