// Focused roof/house protection contracts; fixture-only, no project writes.
import fs from 'node:fs';import assert from 'node:assert/strict';import {runTool} from '../../src/editor/tools';import {quickBeodeulHouse,beodeulHouseStyles,beodeulHouseMinWidth} from '../../src/editor/beodeulQuickHouse';import {captureHouseProtection,assertHouseProtection} from '../../src/editor/tools/houseProtection';import {normalizeSunlight,patchSunlight} from '../../src/project/sunlight';
const before=JSON.parse(fs.readFileSync('.vite-cache/gabled-roof/before.json','utf8')),after=JSON.parse(fs.readFileSync('.vite-cache/gabled-roof/after.json','utf8')),ts=before.tilesets.beodeul_city,id='sp_4e36815d-5fed-4f58-acc9-253a9b2b5201';const checks:string[]=[];
const p=before.maps.houses_native.structurePlacements.find(p=>p.id===id),oldKit=ts.structureKits.find(k=>k.id===p.kitId);
const legacy=quickBeodeulHouse(ts,{style:'beodeul-manor-a',width:9,stories:2,roofWidth:11,roofForm:'hip'});assert.equal(legacy!.id,oldKit.id);assert.deepEqual(legacy!.rows,oldKit.rows);checks.push('legacy hip identifiers and artwork stay unchanged');
for(const style of beodeulHouseStyles(ts))for(const width of[beodeulHouseMinWidth(style),24])for(const stories of[1,2]){const k=quickBeodeulHouse(ts,{style,width,stories})!;assert.ok(k.rows.every(r=>r.tiles.length===k.width&&r.upperTiles!.length===k.width));assert.equal(k.id.endsWith('_gable'),style.startsWith('beodeul-manor-'));assert.equal(k.parts!.find(p=>p.id==='walls')!.h,(style.startsWith('beodeul-manor-')?3:2)+(stories-1)*2);}
checks.push('minimum/maximum widths and both floor bands retain complete native tiles; log houses keep their native roof');
const protections=captureHouseProtection(before);assert.doesNotThrow(()=>assertHouseProtection(protections,after,[]));const forged=structuredClone(after);forged.maps.houses_native.upperTiles[43*forged.maps.houses_native.width+20]=-1;assert.throws(()=>assertHouseProtection(protections,forged,[]));checks.push('exact roof form conversion is accepted; a wall change remains rejected');
for(const project of[before,after]){const ctx={project:structuredClone(project)},old=ctx.project.maps.houses_native.structurePlacements.find(p=>p.id===id);const result=runTool(ctx,'resize_terrain_house_roof',{mapId:'houses_native',placementId:id,roofWidth:13});assert.ok(result.ok,result.summary);assert.equal(ctx.project.maps.houses_native.structurePlacements.find(p=>p.id===id).kitId.endsWith('_gable'),old.kitId.endsWith('_gable'));}
checks.push('width-only resize preserves each existing hip/gable form');
const round={project:structuredClone(after)};const result=runTool(round,'resize_terrain_house_roof',{mapId:'houses_native',placementId:id,roofWidth:11,roofForm:'hip'});assert.ok(result.ok,result.summary);assert.deepEqual(round.project.maps.houses_native.upperTiles,before.maps.houses_native.upperTiles);assert.deepEqual(round.project.maps.houses_native.lowerTiles,before.maps.houses_native.lowerTiles);checks.push('gable to hip restores the roof fringe without leaving ghost tiles');
const painted={project:structuredClone(before)};painted.project.maps.houses_native.upperTiles[43*painted.project.maps.houses_native.width+20]=-1;assert.equal(runTool(painted,'resize_terrain_house_roof',{mapId:'houses_native',placementId:id,roofWidth:11,roofForm:'gable'}).ok,false);checks.push('human repaint is still protected');
assert.equal(normalizeSunlight().enabled,false);assert.equal(normalizeSunlight().altitude,65);assert.equal(patchSunlight({enabled:true,altitude:35},{enabled:false}).altitude,35);checks.push('short shadow default stays off and preserves explicitly authored low sun');
fs.mkdirSync('verify-shots/gabled-roof',{recursive:true});fs.writeFileSync('verify-shots/gabled-roof/contracts.json',JSON.stringify({checks,projectWrites:false},null,2));console.log({checks});
