import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createBlankProject } from '../../src/project/defaults';
import { PiMapVisualCoverage } from '../../src/ai/piAgent/mapVisualCoverage';
const base=createBlankProject(), p=structuredClone(base), id=p.startMapId, m=p.maps[id]!;
const c=new PiMapVisualCoverage();
assert.equal(c.inspect(p,base).length,0);
m.lowerTiles[0]=m.lowerTiles[0]===1?2:1;
assert.equal(c.inspect(p,base).length,1);
c.record(p,{mapId:id,x:0,y:0,w:m.width,h:5});
c.record(p,{mapId:id,x:0,y:0,w:m.width,h:5});
assert.equal(c.inspect(p,base).length,1,'repeated crop cannot cover the map');
c.record(p,{mapId:id,x:0,y:5,w:m.width,h:m.height-5});
assert.equal(c.inspect(p,base).length,0);
m.upperTiles[1]=3;
assert.equal(c.inspect(p,base).length,1,'write after preview invalidates evidence');
c.record(p,{mapId:id,x:0,y:0,w:m.width,h:m.height});
assert.equal(c.inspect(p,base).length,0);
p.tilesets[m.tilesetId]!.tileMeta[0]!.label='changed material';
assert.equal(c.inspect(p,base).length,1,'tileset revision invalidates preview');
const receipt={kind:'controlled-coverage-checks',modelCalls:0,checks:['unchanged map exempt','missing image rejected','repeated crop rejected','union accepted','later write invalidates','full image accepted','tileset change invalidates'],passed:true,artisticAcceptance:false};
fs.writeFileSync('verify-shots/asset-store/visual-coverage-controls.json',JSON.stringify(receipt,null,2));console.log(receipt);
