// Focused checks against actual saved model outputs; does not repaint canonical projects.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import { inspectInteriorPlacement } from '../../src/project/interiorPlacementAudit';
import { PiInteriorCompletion } from '../../src/ai/piAgent/interiorCompletion';
import { homeRequirements } from './pixel-art-world-home-requirements';
const root = process.argv[2] ?? 'output/paw-direct-v2'; fs.mkdirSync(root, {recursive:true});
const p = JSON.parse(fs.readFileSync('output/paw-direct-authoring/home-complete/result-project.json','utf8'));
const calls = JSON.parse(fs.readFileSync('output/paw-direct-authoring/home-complete/tool-calls.json','utf8'));
const last = calls.filter((c:any)=>c.name==='inspect_interior_layout').at(-1);
const original = JSON.stringify(p), a = last.args;
const report = inspectInteriorPlacement(p,a.mapId,a.wallMaterial,a.entry,a.rooms,homeRequirements);
assert.equal(JSON.stringify(p),original,'inspection mutated the project');
assert(report.issues.some(i=>i.code==='REQUIRED_OBJECT_COUNT'&&i.objectId?.includes('bath-tub')),'missing bathtub escaped');
assert(report.issues.some(i=>i.code==='CEILING_WALL_MISSING'));
assert(report.issues.some(i=>i.code==='OBJECT_FRONT_BLOCKED'));
const guard = new PiInteriorCompletion(true, {[a.mapId]:homeRequirements});
guard.record(p,{name:'inspect_interior_layout',args:{...a,requirements:{}},result:{ok:true,summary:'',data:{valid:true}}});
assert(guard.inspect(p,structuredClone(p)).length,'unchanged invalid map escaped a fixed requirement');
const base = structuredClone(p); base.maps[a.mapId].upperTiles.fill(-1);
assert(guard.inspect(p,base).some(r=>r.issues.some((i:any)=>i.code==='REQUIRED_OBJECT_COUNT')),'model weakened trusted requirements');
assert(guard.inspect(p,base).some(r=>r.issues.some((i:any)=>i.code==='CURRENT_FULL_PREVIEW_REQUIRED')));
guard.recordPreview(p,{mapId:a.mapId,x:0,y:0,w:p.maps[a.mapId].width,h:p.maps[a.mapId].height});
assert(!guard.inspect(p,base).some(r=>r.issues.some((i:any)=>i.code==='CURRENT_FULL_PREVIEW_REQUIRED')));
p.maps[a.mapId].upperTiles[0]=p.maps[a.mapId].upperTiles[0]===-1?90:-1;
assert(guard.inspect(p,base).some(r=>r.issues.some((i:any)=>i.code==='CURRENT_FULL_PREVIEW_REQUIRED')),'stale preview accepted');
delete p.maps[a.mapId];assert(guard.inspect(p,base).some(r=>r.issues.some((i:any)=>i.code==='REQUIRED_MAP_MISSING')));
const clinic=JSON.parse(fs.readFileSync('output/paw-direct-authoring/clinic-final/result-project.json','utf8'));
const cc=JSON.parse(fs.readFileSync('output/paw-direct-authoring/clinic-final/tool-calls.json','utf8')).filter((c:any)=>c.name==='inspect_interior_layout').at(-1).args;
assert(inspectInteriorPlacement(clinic,cc.mapId,cc.wallMaterial,cc.entry,cc.rooms).valid,'previous valid clinic regressed');
const proof={checks:9,pass:true,missingTubDetected:true,wallAndAccessErrorsDetected:true,requirementsCannotBeWeakened:true,previewFreshness:true,deletedRequiredMapRejected:true,priorClinicStillValid:true,readonly:true};
fs.writeFileSync(root+'/contract-check.json',JSON.stringify(proof,null,2));console.log(proof);
