import type { InventoryView } from '@/player/playerInventoryView';
import type { GrowthMenuTab, GrowthMenuMutation } from "@/player/playerGrowthMenu";
import type { PlaySession } from "@/project/session";
import type { ActorInitialEquipment, Project } from "@/project/types";
import type { SaveSlotIndex, SaveSlotReadResult } from "@/player/saveSlots";
import type { StatusMenuCommandId, StatusMenuGroupEntryId, StatusMenuRailId } from "@/player/playerStatusMenuModel";
import type { LifeLedgerTabId } from "@/player/lifeLedger";

export type PlayerStatusMenuActions = {
  readonly onInventoryViewChange?: (view: InventoryView) => void;
  readonly onOptionsChanged?: (message?: string) => void;
  readonly onCommand: (commandId: StatusMenuCommandId) => void;
  /** 접힌 그룹(기록/시스템)을 작업 영역에 펼친다. */
  readonly onOpenGroup: (entryId: StatusMenuGroupEntryId) => void;
  readonly onSaveSlot: (slot: SaveSlotIndex) => void;
  readonly onLoadSlot: (slot: SaveSlotIndex) => void;
  readonly onSelectItemTarget: (itemId: string) => void;
  readonly onUseItem: (itemId: string, actorId?: string, monsterInstanceId?: string) => void;
  readonly onOpenItemActions?: (itemId: string) => void;
  readonly onCombineItems?: (itemA: string, itemB: string) => void;
  readonly onUseItemOnFacedTarget?: (itemId: string) => void;
  readonly onToggleSkillLoadout?: (actorId: string, skillId: string) => void;
  readonly onSelectSkillActor: (actorId: string) => void;
  readonly onSelectGrowthTab?: (tab: GrowthMenuTab) => void;
  readonly onGrowthMutation?: (action: GrowthMenuMutation) => void;
  readonly onSelectSkill: (skillId: string) => void;
  readonly onSelectEquipmentActor: (actorId: string) => void;
  readonly onSelectEquipmentSlot: (actorId: string, slotId: keyof ActorInitialEquipment) => void;
  readonly onEquipItem: (actorId: string, slotId: keyof ActorInitialEquipment, equipmentId: string) => void;
  readonly onUnequipItem: (actorId: string, slotId: keyof ActorInitialEquipment) => void;
  readonly onOptimizeEquipment?: (actorId: string) => void;
  readonly onSelectBattleReport?: (index: number | undefined) => void;
  readonly onToggleRow: (actorId: string) => void;
  readonly onSelectFormationActor: (actorId: string) => void;
  readonly onMoveFormationActor: (actorId: string, targetIndex: number) => void;
  readonly onToggleMonsterView: () => void;
  readonly onMoveMonster: (instanceId: string, to: "party" | "box") => void;
  readonly onReplacePendingMonsterSkill?: (instanceId: string, pendingSkillId: string, replacedSkillId: string) => void;
  readonly onRejectPendingMonsterSkill?: (instanceId: string, pendingSkillId: string) => void;
  readonly onSelectLifeLedgerTab?: (tab: LifeLedgerTabId) => void;
  readonly onLifeLedgerMutation?: (ok: boolean, message: string) => void;
  readonly onToggleWait: () => void;
  readonly onToTitle: () => void;
};

export type PlayerStatusMenuOptions = {
  readonly project: Project;
  readonly session: PlaySession;
  readonly slots: readonly SaveSlotReadResult[];
  readonly message?: string;
  readonly elapsedMs?: number;
  readonly selectedCommand?: StatusMenuRailId;
  readonly mode?: "main" | "function";
  readonly selectedDetailActionIndex?: number;
  readonly inventoryView?: InventoryView;
  readonly targetItemId?: string;
  readonly itemActionId?: string;
  readonly canUseItemOnFacedTarget?: (itemId: string) => boolean;
  readonly skillActorId?: string;
  readonly selectedSkillId?: string;
  readonly growthTab?: GrowthMenuTab;
  readonly equipmentActorId?: string;
  readonly equipmentSlotId?: keyof ActorInitialEquipment;
  readonly formationActorId?: string;
  readonly battleReportIndex?: number;
  readonly monsterView?: "party" | "box";
  readonly lifeLedgerTab?: LifeLedgerTabId;
  readonly readLive?: import("@/project/spatialOccupancy").SpatialLiveContextReader;
  readonly placementDirection?: import("@/project/types").Dir;
  readonly getPlacementDirection?: () => import("@/project/types").Dir | undefined;
  readonly getScene?: () => import("@/player/lifePlacementScene").LifePlacementSceneSource | undefined;
  readonly confirmSaveSlot?: SaveSlotIndex;
  readonly confirmToTitle?: boolean;
  readonly saveEnabled?: boolean;
  readonly waitModeEnabled?: boolean;
  readonly actions: PlayerStatusMenuActions;
};
