"""Explicit ASCII rows and coordinate edits only. No procedural art or frame transforms.
Running this file rebuilds the complete literal pxgrid files from authored row records.
"""
from pathlib import Path
import json
ROOT = Path(__file__).resolve().parent
PALETTE = {'O':'#252b29','D':'#41463f','S':'#5c594d','B':'#817965','L':'#a39a7f','H':'#c7bf9f','v':'#465439','g':'#687a49','l':'#899861','h':'#acb77a','e':'#e6bc60','a':'#d0c29a','c':'#327b78','t':'#66c7af','w':'#caead1','p':'#755778','q':'#b28bb1'}
# Every record starts at x=0; trailing transparent canvas is initialized blank.
IDLE = {
22:'.....................OOOOOOOOOOOO',
23:'..................OOOHHHHLLLLLLLLOO',
24:'................OOLHHHHHHLLLLLLLLLBBO',
25:'..............OOLLLHHHHHHDLLLLLLLBBBBBO',
26:'............OOLLLLLHHHHDDDDLLLLLBBBBBBBO',
27:'...........OLLLLLLLLLDDLLLLDDLLBBBBBBBBBO',
28:'..........OLLLLLLLLDDLLLLLLLLDDBBBBBBBBBBO',
29:'.........OLLLLLLDDDLLLLLLLLLLLDDBBBBBBBBBO',
30:'.........OLLHLLDLLLLLLLLLLLLLLLLDBBBBBBBBBO',
31:'........OLLHLLLDLLLLLLLLLLLBBBBBDDBBBBBBBBO',
32:'........OLLHLLLDLLLLLLLLLBBBBBBBDDBBBBBBBBO',
33:'.......OLLHLLLLDLLLLLLLBBBBBBBBBDDBBBBBBBBBO',
34:'.......OLLHLLLLDDLLLLBBBBBBBBBBDDBBBBBBBBBBO',
35:'.......OLLLLLLLBDDDDBBBBBBBBBBDDBBBBBBBBBBO......OOOOOO',
36:'.......OLLLLLBBBDDBBDDDDDDDDDBBBBBBBBBBBBBO...OOlhhhhhOO',
37:'.......OLLLLBBBBDBBBBBBBBBBBBDDBBBBBBBBBBBO..OllhhhhhlllO',
38:'.......OLLLBBBBDBBBBBBBBBBBBBBDDBBBBBBBBBOOOllhhheeOlllgO',
39:'.......OLLBBBBDBBBBBBBBBBBBBBBBDDBBBBBBBBOllhhhhheOOllggO',
40:'.......OLBBBBDBBBBBBBBBBBBBBBBBBDDSSSBBBBOlhllllllgggggOO',
41:'.......OBBBBDBBBBBBBBBBBBBBBBBBDSDSSSSSSOOllgggggggOOOO',
42:'.......OBBBDDDDDDDDDDDDDDDDDDDDSSSDSSSSSOllgggvvvOO',
43:'.......OBBSSSSSSSSSSSSSSSSSSSSSSSSSSDSSSOllggvvOO',
44:'.....OOOBSSSSSBBBBSSSSSSSBBBBSSSSSSSSSDDOllggvO',
45:'....OlgOOSSSSSSBBBBBSSSSBBBBBBSSSSSSSSDOllggvvO',
46:'...OggvOOOSSSSSSBBBBBSSSBBBBBBSSSSSSSDOllggvvO',
47:'..OgvOO...OOSSSSSSSSSSSSSSSSSSSSSSSOOggggvvvO',
48:'..OOO.......OOODDDDDDDDDDDDDDDDDDOOggggvvOOgO',
49:'.............OlgggggOOOOvvvvvvvvOOllggggvOOgggO',
50:'............OllhllggvOOvvvvvvvvOllhhllggvOOgggvO',
51:'............OlhhllggvvOOvvvvvvOllhhllggvvOOggvvO',
52:'............OlhllggvvvOOgvvvOOOlhhhllggvvO.OggvO',
53:'............OllgggvvvOOggvvO..OlhllgggvvO..OgavO',
54:'............OllgggvvOOgggvvO..OllggggvvO..OgaaO',
55:'............OlggggvvOOgagavO..OllgggvvO...OOOOO',
56:'...........OlggggvvvO........OlggggvvO',
57:'..........OllggggvvO........OllggggvvO',
58:'..........OlggggvvOO.......OllggggvvvO',
59:'..........OlgggaaavO.......OlgggaaavvO',
60:'..........OOOOOOOOO........OOOOOOOOOO',
}

def canvas(records):
    rows = ['.' * 64 for _ in range(64)]
    for y,s in records.items():
        if len(s)>64: raise ValueError((y,len(s),s))
        rows[y] = s + '.' * (64-len(s))
    return rows

def revised(base, records):
    rows = list(base)
    for y,s in records.items():
        if len(s)>64: raise ValueError((y,len(s),s))
        rows[y]=s+'.'*(64-len(s))
    return rows

def dots(rows, edits):
    rows = list(rows)
    for x,y,s in edits:
        if x+len(s)>63: raise ValueError((x,y,s))
        rows[y]=rows[y][:x]+s+rows[y][x+len(s):]
    return rows

FRAMES = {'idle_a':canvas(IDLE)}

# Small idle changes are authored in the neck, cheek and shoulder, with fixed feet.
FRAMES['idle_b']=revised(FRAMES['idle_a'],{
40:'.......OLBBBBDBBBBBBBBBBBBBBBBBBDDSSSBBBBOlhhlllllggggOO',
41:'.......OBBBBDBBBBBBBBBBBBBBBBBBDSDSSSSSSOOllhggggggOOOO',
42:'.......OBBBDDDDDDDDDDDDDDDDDDDDSSSDSSSSSOllhggvvvOO',
50:'............OllhllggvOOvvvvvvvvOllhhhllgvOOgggvO',
51:'............OlhhllggvvOOvvvvvvOllhhhllgvvOOggvvO',
})
FRAMES['idle_c']=revised(FRAMES['idle_a'],{
38:'.......OLLLBBBBDBBBBBBBBBBBBBBDDBBBBBBBBBOOOllhhhhhllllgO',
39:'.......OLLBBBBDBBBBBBBBBBBBBBBBDDBBBBBBBBOllhhhhhOOlllggO',
40:'.......OLBBBBDBBBBBBBBBBBBBBBBBBDDSSSBBBBOlhllllllgggggOO',
43:'.......OBBSSSSSSSSSSSSSSSSSSSSSSSSSSDSSSOllgggvO',
51:'............OlhhllggvvOOvvvvvvOllhllgggvvOOggvvO',
})

FRAMES['windup']=revised(FRAMES['idle_a'],{
35:'.......OLLLLLLLBDDDDBBBBBBBBBBDDBBBBBBBBBBO',
36:'.......OLLLLLBBBDDBBDDDDDDDDDBBBBBBBBBBBBBO',
37:'.......OLLLLBBBBDBBBBBBBBBBBBDDBBBBBBBBBBBO',
38:'.......OLLLBBBBDBBBBBBBBBBBBBBDDBBBBBBBBBO',
39:'.......OLLBBBBDBBBBBBBBBBBBBBBBDDBBBBBBBBO..OOOOO',
40:'.......OLBBBBDBBBBBBBBBBBBBBBBBBDDSSSBBBBOOlhhhllO',
41:'.......OBBBBDBBBBBBBBBBBBBBBBBBDSDSSSSSSOOlhheOlggO',
42:'.......OBBBDDDDDDDDDDDDDDDDDDDDSSSDSSSSSOllgggggO',
43:'.......OBBSSSSSSSSSSSSSSSSSSSSSSSSSSDSSSOllgvvOO',
44:'.....OOOBSSSSSBBBBSSSSSSSBBBBSSSSSSSSSDDOggvvO',
45:'....OlgOOSSSSSSBBBBBSSSSBBBBBBSSSSSSSSDOggvvO',
46:'...OggvOOOSSSSSSBBBBBSSSBBBBBBSSSSSSSDOggvvO',
47:'..OgvOO...OOSSSSSSSSSSSSSSSSSSSSSSSOOggvvvO',
48:'..OOO.......OOODDDDDDDDDDDDDDDDDDOOllggvvO',
49:'............OllhhllgOOOOvvvvvvvOOllhhggvvO',
50:'...........OllhhllggvvOOvvvvvvOOllhllggvvO',
51:'...........OlhllggggvvvOOvvvvOOllhllggvvO',
52:'...........OllgggggvvvO.OOOOOllggggvvvO',
53:'...........OllggggvvvO..OgvvOllggggvvO',
54:'............OlggggvvO.OggvvOllggvvvO',
55:'............OlggggvvOOgggvvOlggvvvO',
56:'.............OlgggvvOOgaavvOlgggvO',
57:'.............OlgggvvOOOOOOOllggvvO',
58:'............OllgggvvO.....OlggaavvO',
59:'...........OllgggaavvO....OOOOOOOOO',
60:'...........OOOOOOOOOO',
})

FRAMES['move']=revised(FRAMES['idle_a'],{
23:'..................OOOHHHHLLLLLLLLOOO',
24:'................OOLHHHHHHLLLLLLLLLBBBO',
25:'..............OOLLLHHHHHHDLLLLLLLLBBBBBO',
26:'............OOLLLLLHHHHDDDDLLLLLLBBBBBBBBO',
27:'...........OLLLLLLLLLDDLLLLDDLLLBBBBBBBBBBO',
28:'..........OLLLLLLLLDDLLLLLLLLDDDBBBBBBBBBBBO',
35:'.......OLLLLLLLBDDDDBBBBBBBBBBDDBBBBBBBBBBBO.....OOOOOO',
36:'.......OLLLLLBBBDDBBDDDDDDDDDBBBBBBBBBBBBBBO..OOlhhhhhOO',
37:'.......OLLLLBBBBDBBBBBBBBBBBBDDBBBBBBBBBBBBO.OllhhhhlllgO',
38:'.......OLLLBBBBDBBBBBBBBBBBBBBDDBBBBBBBBBBOOllhhheOllggO',
39:'.......OLLBBBBDBBBBBBBBBBBBBBBBDDBBBBBBBBBBOlhhhheOllggO',
40:'.......OLBBBBDBBBBBBBBBBBBBBBBBBDDSSSBBBBBOllhllllgggggO',
41:'.......OBBBBDBBBBBBBBBBBBBBBBBBDSDSSSSSSSOOllgggggggOO',
42:'.......OBBBDDDDDDDDDDDDDDDDDDDDSSSDSSSSSSOllggvvvOO',
43:'.......OBBSSSSSSSSSSSSSSSSSSSSSSSSSSDSSSSOllggvvO',
44:'.....OOOBSSSSSBBBBSSSSSSSBBBBSSSSSSSSSDDDOllggvO',
45:'....OlgOOSSSSSSBBBBBSSSSBBBBBBSSSSSSSSSDOllggvvO',
46:'...OggvOOOSSSSSSBBBBBSSSBBBBBBSSSSSSSSDOllggvvO',
47:'..OgvOO...OOSSSSSSSSSSSSSSSSSSSSSSSOOllhggvvvO',
48:'..OOO.......OOODDDDDDDDDDDDDDDDDDOOllhhllggvvO',
49:'............OlhhllggOOOOvvvvvvvOOllhhhllggvvO',
50:'...........OllhllggvvOOvvvvvvvvOllhhllgggvvO',
51:'..........OllhllggvvvOOvvvvvvOOOllhllgggvvOOggO',
52:'.........OllggggvvvOO.OOOOOO....OllgggggvvOOggvO',
53:'........OllggggvvvO...OgvgvO.....OllggggvvOOggvO',
54:'.......OllggggvvvO....OggvvO......OlggggvvOOggvO',
55:'......OllggggvvvO.....OgaavO......OlggggvvOOgaaO',
56:'.....OllggggvvvO......OOOOOO......OllgggvvOOOOO',
57:'....OllgggaavvO.................OllggggvvO',
58:'....OllggaavvO..................OlgggggvvO',
59:'....OOOOOOOOO...................OlgggaavvO',
60:'................................OOOOOOOOO',
})

# Contact: the visible stone shoulder advances, chin withdraws, rear hock
# straightens leftward, and the front wrist carries a broad blunt clawed paw.
FRAMES['attack']=revised(FRAMES['idle_a'],{
24:'................OOLHHHHHHLLLLLLLLLBBOO',
25:'..............OOLLLHHHHHHDLLLLLLLBBBBBBOO',
26:'............OOLLLLLHHHHDDDDLLLLLBBBBBBBBBOO',
27:'...........OLLLLLLLLLDDLLLLDDLLBBBBBBBBBBBBO',
28:'..........OLLLLLLLLDDLLLLLLLLDDBBBBBBBBBBBBBO',
29:'.........OLLLLLLDDDLLLLLLLLLLLDDBBBBBBBBBBBBO',
30:'.........OLLHLLDLLLLLLLLLLLLLLLLDBBBBBBBBBBBBO',
31:'........OLLHLLLDLLLLLLLLLLLBBBBBDDBBBBBBBLLLBO',
32:'........OLLHLLLDLLLLLLLLLBBBBBBBDDBBBBBBLLLLBBO',
33:'.......OLLHLLLLDLLLLLLLBBBBBBBBBDDBBBBBBLLLLBBBO',
34:'.......OLLHLLLLDDLLLLBBBBBBBBBBDDBBBBBBBLLLBBBBO',
35:'.......OLLLLLLLBDDDDBBBBBBBBBBDDBBBBBBBLLBBBBBBO',
36:'.......OLLLLLBBBDDBBDDDDDDDDDBBBBBBBBBBBBBBBBBBO',
37:'.......OLLLLBBBBDBBBBBBBBBBBBDDBBBBBBBBBBBBBBBBO',
38:'.......OLLLBBBBDBBBBBBBBBBBBBBDDBBBBBBBBBBBBBBO',
39:'.......OLLBBBBDBBBBBBBBBBBBBBBBDDBBBBBBBBBBBBBOOOOO',
40:'.......OLBBBBDBBBBBBBBBBBBBBBBBBDDSSSBBBBBBBOlhhllO',
41:'.......OBBBBDBBBBBBBBBBBBBBBBBBDSDSSSSSSSSOOllheOgO',
42:'.......OBBBDDDDDDDDDDDDDDDDDDDDSSSDSSSSSSSOllggggO',
43:'.......OBBSSSSSSSSSSSSSSSSSSSSSSSSSSDSSSSSOllgvOO',
44:'.....OOOBSSSSSBBBBSSSSSSSBBBBSSSSSSSSSDDDDOlgvO',
45:'....OlgOOSSSSSSBBBBBSSSSBBBBBBSSSSSSSSSSDDOlggvO',
46:'...OggvOOOSSSSSSBBBBBSSSBBBBBBSSSSSSSSSDOOllggvO',
47:'..OgvOO...OOSSSSSSSSSSSSSSSSSSSSSSSSOOOllhhggvvO',
48:'..OOO.......OOODDDDDDDDDDDDDDDDDDDOOllhhhllggvvO',
49:'............OllhhllOOOOvvvvvvvvvOOllhhllggggvvO',
50:'...........OllhhllgvvOOvvvvvvvvOllhhllgggggvvO',
51:'..........OllhllggvvOOOvvvvvvOOOllhllggggvvvO',
52:'.........OllhllggvvO...OOOOOO....OllggggvvvO',
53:'........OllggggvvO....OggvvO......OllggvvvO',
54:'.......OllggggvvO.....OggvvO.......OllggvvOOO',
55:'......OllggggvvO......OggvvO.......OlhllllgggOO',
56:'.....OllggggvvO.......OgavvO.......OlhhhllllgggOO',
57:'....OllggggvvO........OOOOOO.......OllhhllllgggggO',
58:'...OllggggvvO.....................OllgggggggaaaO',
59:'...OlgggaavvO.....................OlggaaagaaaaO',
60:'...OOOOOOOOOO.....................OOOOOOOOOOOO',
})

FRAMES['recover']=revised(FRAMES['idle_a'],{
35:'.......OLLLLLLLBDDDDBBBBBBBBBBDDBBBBBBBBBBO',
36:'.......OLLLLLBBBDDBBDDDDDDDDDBBBBBBBBBBBBBO.......OOOOO',
37:'.......OLLLLBBBBDBBBBBBBBBBBBDDBBBBBBBBBBBO....OOlhhhllO',
38:'.......OLLLBBBBDBBBBBBBBBBBBBBDDBBBBBBBBBO...OllhhhellggO',
39:'.......OLLBBBBDBBBBBBBBBBBBBBBBDDBBBBBBBBOOOllhhheOllggO',
40:'.......OLBBBBDBBBBBBBBBBBBBBBBBBDDSSSBBBBOlhhhlllgggggO',
41:'.......OBBBBDBBBBBBBBBBBBBBBBBBDSDSSSSSSOOllgggggggOO',
42:'.......OBBBDDDDDDDDDDDDDDDDDDDDSSSDSSSSSOllgggvvOO',
49:'.............OlhllggOOOOvvvvvvvvOOllhhggvOOgggO',
50:'.............OllhllgvvOOvvvvvvvOllhllggvvOOgggvO',
51:'.............OllhllgvvvOOvvvvvOllhllgggvvOOggvvO',
52:'.............OllggggvvO.OOOOOOllgggggvvO.OggvO',
53:'.............OllgggvvO.OggvvOOllggggvvO..OgavO',
54:'.............OllgggvvOOgggvvO.OllgggvvO..OgaaO',
55:'.............OlggggvvOOgaavvO.OllgggvvO..OOOOO',
56:'.............OlggggvvOOOOOOO.OllggggvvO',
57:'............OllggggvvO......OllggggvvvO',
58:'............OlgggggvvO.....OllggggvvvO',
59:'...........OllgggaaavO.....OlgggaaavvO',
60:'...........OOOOOOOOOO.....OOOOOOOOOOO',
})

FRAMES['hit']=revised(FRAMES['idle_a'],{
22:'......................OOOOOOOOOO',
23:'...................OOOHHHHLLLLLLOO',
24:'................OOLHHHHHHLLLLLLLBBO',
25:'..............OOLLLHHHHHHDLLLLLLBBBBBO',
35:'.......OLLLLLLLBDDDDBBBBBBBBBBDDBBBBBBBBBBO',
36:'.......OLLLLLBBBDDBBDDDDDDDDDBBBBBBBBBBBBBO',
37:'.......OLLLLBBBBDBBBBBBBBBBBBDDBBBBBBBBBBBO',
38:'.......OLLLBBBBDBBBBBBBBBBBBBBDDBBBBBBBBBO..OOOOO',
39:'.......OLLBBBBDBBBBBBBBBBBBBBBBDDBBBBBBBBOOlhhlllO',
40:'.......OLBBBBDBBBBBBBBBBBBBBBBBBDDSSSBBBBOllhhOOlgO',
41:'.......OBBBBDBBBBBBBBBBBBBBBBBBDSDSSSSSSOOlhllggggO',
42:'.......OBBBDDDDDDDDDDDDDDDDDDDDSSSDSSSSSOllggggOO',
43:'.......OBBSSSSSSSSSSSSSSSSSSSSSSSSSSDSSSOllggvO',
44:'.....OOOBSSSSSBBBBSSSSSSSBBBBSSSSSSSSSDDOgggvO',
49:'.............OlgggggOOOOvvvvvvvvOOllggggvOOgggO',
50:'.............OlhlgggvvOOvvvvvvvOllhhllggvOOgggvO',
51:'..............OlhllggvvOOvvvvvOllhhllggvvOOggvvO',
52:'..............OllhllgvvOOOOOOOlhhhllggvvO.OggvO',
53:'...............OllgggvvOOgvvOOlhllgggvvO..OgavO',
54:'...............OllgggvvOggvvO.OllggggvvO..OgaaO',
55:'..............OllgggvvOOgaavO.OllgggvvO...OOOOO',
56:'.............OllggggvvOOOOOOO.OlggggvvO',
57:'............OllggggvvO......OllggggvvO',
58:'............OlggggvvO......OllggggvvvO',
59:'............OlgggaavvO.....OlgggaaavvO',
60:'............OOOOOOOOOO.....OOOOOOOOOO',
})

# Defeat is newly drawn at ground level, with a slack jaw and distinct folded feet.
FRAMES['dead']=canvas({
37:'..................OOOOOOOOOOO',
38:'..............OOOOHHHLLLLLLLLLOOO',
39:'...........OOOLLHHHHLLLLLLLLLBBBBBOO',
40:'.........OOLLLLHHHHDLLLLLLLLLBBBBBBBBO',
41:'........OLLLLLLLLDDDDLLLLLBBBBBBBBBBBBO',
42:'.......OLLLLLLLDDLLLLDDLLBBBBBBBBBBBBBBO',
43:'......OLLHLLLDDLLLLLLLLDDBBBBBBBBBBBBBBBO',
44:'......OLHHLLDLLLLLLLLLLLLDBBBBBBBBBBBBBBBO',
45:'.....OLHHLLLDLLLLLLLLLBBBBDDBBBBBBBBBBBBBO',
46:'.....OLLLLLLDDLLLLLBBBBBBBDDBBBBBBBBBBBBBO',
47:'.....OLLLLLBBBDDDDDDDDDDDDBBBBBBBBBBBBBBBO',
48:'.....OLLBBBBBDBBBBBBBBBBBBBDDBBBBBBBBBBBBO',
49:'.....OLBBBBBDBBBBBBBBBBBBBBBBDDBBBBBBBBBBO',
50:'.....OBBBBBDDBBBBBBBBBBBBBBBBBBDDSSSBBBBO',
51:'.....OBBBDDDDDDDDDDDDDDDDDDDDDDSSSDSSSSO',
52:'.....OBBSSSSSSSSSSSSSSSSSSSSSSSSSSSSDSSO',
53:'...OOOBSSSSBBBBBSSSSSSSSSBBBBBSSSSSSDDO...OOOOO',
54:'..OlgOOSSSSSBBBBBSSSSSSSBBBBBBSSSSSSDOO.OllhlllOO',
55:'.OggvO.OOSSSSSSSSSSSSSSSSSSSSSSSSSOOgOOllhhllgggO',
56:'.OgvOO...OOODDDDDDDDDDDDDDDDDDDDDOOllggggllOOlgggO',
57:'.OOO.......OllhhllggOOOOvvvvvOOOOllhhggggllgggggOO',
58:'..........OllhllggggggOOOOOOOOllhllggggvvOOOOOOO',
59:'.........OllggggaagggvvO....OllggggaagggvvO',
60:'.........OOOOOOOOOOOOOO....OOOOOOOOOOOOOO',
})

FRAMES['skill_a']=revised(FRAMES['idle_a'],{
33:'.......OLLHLLLLDLLLLLLLBBBBBBBBBDDBBBBBBBBBO.....OOOOO',
34:'.......OLLHLLLLDDLLLLBBBBBBBBBBDDBBBBBBBBBBO...OOlhhhlO',
35:'.......OLLLLLLLBDDDDBBBBBBBBBBDDBBBBBBBBBBO..OllhhhlllO',
36:'.......OLLLLLBBBDDBBDDDDDDDDDBBBBBBBBBBBBBO.OllhheOlggO',
37:'.......OLLLLBBBBDBBBBBBBBBBBBDDBBBBBBBBBBBOOllhhheOlgvO',
38:'.......OLLLBBBBDBBBBBBBBBBBBBBDDBBBBBBBBBOlhhhhllgggvO',
39:'.......OLLBBBBDBBBBBBBBBBBBBBBBDDBBBBBBBBOlhllllggggO',
40:'.......OLBBBBDBBBBBBBBBBBBBBBBBBDDSSSBBBBOllggggggOO',
41:'.......OBBBBDBBBBBBBBBBBBBBBBBBDSDSSSSSSOOllggggOO',
42:'.......OBBBDDDDDDDDDDDDDDDDDDDDSSSDSSSSSOllgggvO',
49:'.............OlgggggOOOOvvvvvvvvOOllhgggvOOgggO',
50:'............OllhhllgvOOvvvvvvvvOllhhhllgvOOgggvO',
51:'............OlhhhllgvvOOvvvvvvOllhhllggvvOOggvvO',
52:'............OlhhllgvvvOOgvvvOOOlhhllggvvO.OggvO',
})
FRAMES['skill_a']=dots(FRAMES['skill_a'],[
 (27,25,'c'),(26,26,'cttc'),(24,27,'ct'),(29,27,'tc'),
 (23,28,'tc'),(31,28,'tc'),(21,29,'ctc'),(33,29,'tc'),
 (15,33,'c'),(15,34,'ct'),(17,35,'cttc'),(30,34,'tc'),
 (22,36,'cctttttcc'),(35,39,'tc'),(34,40,'tc'),
 (14,42,'ccttttttttccccctttcc'),(29,43,'c')])

# Three irregular stone shields grow from different front/crown seams.
# These are literal effect rows, not scaling/rotating copies of one shape.
FRAMES['skill_b']=revised(FRAMES['idle_a'],{
6:'...............................cc',
7:'.............................ccHHcc',
8:'............................cHHHHLLc',
9:'...........................cHHHLLLLSc',
10:'...........................cHHLLLLBSc',
11:'...........................cHLLDLLBBSc',
12:'...........................cLLDDBBBBSc......cc',
13:'...........................cLLDBBBBSc.....cHHc',
14:'................cc.........cLDBBBBBSc....cHHLLc',
15:'..............ccHHc........cLDBBBBSSc...cHHLLLSc',
16:'.............cHHHLLc........cDBBBSSSc..cHLLDLLBSc',
17:'............cHHLLLLSc.......cBBBBSSSc.cHLLDLLBBSc',
18:'............cHHLLDBBSc.......cBBBSSct.cLLDDBBBBSc',
19:'............cHLLDDBBSc.......cBBSSctt.cLDBBBBBSc',
20:'............cLLDBBBBSc........cSScttw.cDBBBBBSSc',
21:'.............cDBBBBSc.........cttwt..cBBBBSSSc',
22:'..............cBBBSc..OOOOOOOcttwt....cBBSSSc',
23:'...............cSctOOHHHHLLLctwtLLOO..cSSct',
24:'................cttHHHHHLLLcttLLLLBBO.ctwt',
25:'..............OOLctwHHHHHDLcttLLLBBBBBctwt',
26:'............OOLLLctwHHDDDDcttLLLBBBBctwtO',
27:'...........OLLLLLLctwDLLLLcttDLLBBBBctwtBBO',
28:'..........OLLLLLLLLctwLLLLcttDDBBBBctwtBBBO',
29:'.........OLLLLLLDDDctwLLLcttLLDDcttwtBBBBO',
30:'.........OLLHLLDLLLLctwtcttLLLLLcttcBBBBBBO',
31:'........OLLHLLLDLLLLcttttLLBBBBBDDBBBBBBBBO',
32:'........OLLHLLLDLLLLLcccBBBBBBBBDDBBBBBBBBO',
35:'.......OLLLLLLLBDDDDBBBBBBBBBBDDBBBBBBBBBBO....OOOOO',
36:'.......OLLLLLBBBDDBBDDDDDDDDDBBBBBBBBBBBBBO..OOlhhhllO',
37:'.......OLLLLBBBBDBBBBBBBBBBBBDDBBBBBBBBBBBO.OllhheOlggO',
38:'.......OLLLBBBBDBBBBBBBBBBBBBBDDBBBBBBBBBOOllhhheOlgvO',
39:'.......OLLBBBBDBBBBBBBBBBBBBBBBDDBBBBBBBBOlhhllllggvO',
40:'.......OLBBBBDBBBBBBBBBBBBBBBBBBDDSSSBBBBOllggggggvO',
41:'.......OBBBBDBBBBBBBBBBBBBBBBBBDSDSSSSSSOOllgggggOO',
42:'.......OBBBDDDDDDDDDDDDDDDDDDDDSSSDSSSSSOllgggvOO',
49:'.............OlhllggOOOOvvvvvvvvOOllhhggvOOgggO',
50:'............OllhhllgvOOvvvvvvvvOllhhhllgvOOgggvO',
51:'............OlhhhllgvvOOvvvvvvOllhhllggvvOOggvvO',
52:'............OlhhllgvvvOOgvvvOOOlhhllggvvO.OggvO',
56:'...........OllggggvvO........OllggggvvO',
57:'..........OllggggvvvO.......OllggggvvvO',
58:'.........OllgggggvvvO......OllgggggvvvO',
59:'.........OlggggaaavvO......OlggggaaavvO',
60:'.........OOOOOOOOOOOO......OOOOOOOOOOOO',
})

FRAMES['skill_c']=revised(FRAMES['idle_a'],{
17:'...............................cLBc',
18:'...............................cBSc',
20:'...................cLc......................cLc',
21:'...................cSc...............cB.....cSc',
24:'................OOLHHHHHHLLLLLLLLLBBO........t',
25:'..............OOLLLHHHHHHDLLLLLLLBBBBBO..cLBc',
26:'............OOLLLLLHHHHDDDDLLLLLBBBBBBBO..cSc',
29:'.........OLLLLLLDDDLLLLLLLLLLLDDBBBBBBBBBO...c',
35:'.......OLLLLLLLBDDDDBBBBBBBBBBDDBBBBBBBBBBO.....OOOOOO',
36:'.......OLLLLLBBBDDBBDDDDDDDDDBBBBBBBBBBBBBO..OOlhhhhllO',
37:'.......OLLLLBBBBDBBBBBBBBBBBBDDBBBBBBBBBBBO.OllhhhhlllgO',
38:'.......OLLLBBBBDBBBBBBBBBBBBBBDDBBBBBBBBBOOllhhheOllggO',
39:'.......OLLBBBBDBBBBBBBBBBBBBBBBDDBBBBBBBBOlhhhheOllggO',
40:'.......OLBBBBDBBBBBBBBBBBBBBBBBBDDSSSBBBBOllhllllggggO',
41:'.......OBBBBDBBBBBBBBBBBBBBBBBBDSDSSSSSSOOllggggggOO',
50:'............OllhhllgvOOvvvvvvvvOllhhllggvOOgggvO',
51:'............OlhhllggvvOOvvvvvvOllhllgggvvOOggvvO',
})
FRAMES['skill_c']=dots(FRAMES['skill_c'],[
 (26,26,'cc'),(29,27,'tc'),(31,28,'c'),(33,29,'tc'),
 (33,32,'c'),(30,34,'c'),(22,36,'ccc'),(26,36,'tc'),
 (15,42,'cctcccc'),(27,42,'cctcc'),(18,43,'c')])

# Poison: lowered jaw, buckled foreleg, rear foot turned inward; bubbles are
# discrete changing clusters and the healthy shell colors remain unchanged.
FRAMES['poison_a']=revised(FRAMES['idle_a'],{
24:'................OOLHHHHHHLLLLLLLLLBBO..............ppp',
25:'..............OOLLLHHHHHHDLLLLLLLBBBBBO............pqqqp',
26:'............OOLLLLLHHHHDDDDLLLLLBBBBBBBO...........pqqpp',
27:'...........OLLLLLLLLLDDLLLLDDLLBBBBBBBBBO...........ppp',
31:'........OLLHLLLDLLLLLLLLLLLBBBBBDDBBBBBBBBO.............pp',
32:'........OLLHLLLDLLLLLLLLLBBBBBBBDDBBBBBBBBO............pqqp',
33:'.......OLLHLLLLDLLLLLLLBBBBBBBBBDDBBBBBBBBBO............pp',
35:'.......OLLLLLLLBDDDDBBBBBBBBBBDDBBBBBBBBBBO',
36:'.......OLLLLLBBBDDBBDDDDDDDDDBBBBBBBBBBBBBO',
37:'.......OLLLLBBBBDBBBBBBBBBBBBDDBBBBBBBBBBBO',
38:'.......OLLLBBBBDBBBBBBBBBBBBBBDDBBBBBBBBBO',
39:'.......OLLBBBBDBBBBBBBBBBBBBBBBDDBBBBBBBBO',
40:'.......OLBBBBDBBBBBBBBBBBBBBBBBBDDSSSBBBBO..OOOOO',
41:'.......OBBBBDBBBBBBBBBBBBBBBBBBDSDSSSSSSOOOllhhllO',
42:'.......OBBBDDDDDDDDDDDDDDDDDDDDSSSDSSSSSOllhhOlgO',
43:'.......OBBSSSSSSSSSSSSSSSSSSSSSSSSSSDSSSOlhllggggO',
44:'.....OOOBSSSSSBBBBSSSSSSSBBBBSSSSSSSSSDDOllgggggO',
45:'....OlgOOSSSSSSBBBBBSSSSBBBBBBSSSSSSSSDOlgggvvO',
46:'...OggvOOOSSSSSSBBBBBSSSBBBBBBSSSSSSSDOgggvvO',
47:'..OgvOO...OOSSSSSSSSSSSSSSSSSSSSSSSOOgggvvvO',
49:'.............OlhllggOOOOvvvvvvvvOOllhgggvOOgggO',
50:'.............OllhllgvvOOvvvvvvvOllhllggvvOOgggvO',
51:'.............OllhllgvvvOOvvvvvOOllhllggvvOOggvvO',
52:'.............OllggggvvO.OOOOOO.OllhllggvvO.OggvO',
53:'.............OllgggvvO.OggvvO...OllggggvvO..OgavO',
54:'.............OllgggvvOOgggvvO....OllgggvvO..OgaaO',
55:'.............OlggggvvOOgaavvO....OlgggvvO...OOOOO',
56:'.............OlggggvvOOOOOOO.....OllggvvO',
57:'.............OllgggvvO..........OllggvvO',
58:'..............OllgggvvO........OllgggvvO',
59:'..............OlgggaavvO......OlgggaaavO',
60:'..............OOOOOOOOOO......OOOOOOOOO',
})
FRAMES['poison_b']=revised(FRAMES['poison_a'],{
22:'.....................OOOOOOOOOOOO.....................pp',
23:'..................OOOHHHHLLLLLLLLOO..................pqqp',
24:'................OOLHHHHHHLLLLLLLLLBBO.................pp',
25:'..............OOLLLHHHHHHDLLLLLLLBBBBBO',
26:'............OOLLLLLHHHHDDDDLLLLLBBBBBBBO',
27:'...........OLLLLLLLLLDDLLLLDDLLBBBBBBBBBO',
28:'..........OLLLLLLLLDDLLLLLLLLDDBBBBBBBBBBO..........pppp',
29:'.........OLLLLLLDDDLLLLLLLLLLLDDBBBBBBBBBO.........pqqqqp',
30:'.........OLLHLLDLLLLLLLLLLLLLLLLDBBBBBBBBBO........pqqqpp',
31:'........OLLHLLLDLLLLLLLLLLLBBBBBDDBBBBBBBBO.........pppp',
32:'........OLLHLLLDLLLLLLLLLBBBBBBBDDBBBBBBBBO',
33:'.......OLLHLLLLDLLLLLLLBBBBBBBBBDDBBBBBBBBBO',
41:'.......OBBBBDBBBBBBBBBBBBBBBBBBDSDSSSSSSOOOllhlllO',
42:'.......OBBBDDDDDDDDDDDDDDDDDDDDSSSDSSSSSOllhOOlgO',
43:'.......OBBSSSSSSSSSSSSSSSSSSSSSSSSSSDSSSOlllgggggO',
44:'.....OOOBSSSSSBBBBSSSSSSSBBBBSSSSSSSSSDDOllgggggvO',
45:'....OlgOOSSSSSSBBBBBSSSSBBBBBBSSSSSSSSDOlgggggvO',
46:'...OggvOOOSSSSSSBBBBBSSSBBBBBBSSSSSSSDOgggvvvO',
52:'.............OllggggvvO.OOOOOO.OllggggvvO.OggvO',
53:'.............OllgggvvO.OggvvO...OllggggvvO..OgavO',
54:'.............OllgggvvOOgggvvO....OllggvvvO..OgaaO',
55:'.............OlggggvvOOgaavvO....OlgggvvvO..OOOOO',
})

FRAMES['stun_a']=revised(FRAMES['idle_a'],{
25:'..............OOLLLHHHHHHDLLLLLLLBBBBBO...........e',
26:'............OOLLLLLHHHHDDDDLLLLLBBBBBBBO..........a',
27:'...........OLLLLLLLLLDDLLLLDDLLBBBBBBBBBO.......eeaee',
28:'..........OLLLLLLLLDDLLLLLLLLDDBBBBBBBBBBO.........a',
29:'.........OLLLLLLDDDLLLLLLLLLLLDDBBBBBBBBBO.........e',
32:'........OLLHLLLDLLLLLLLLLBBBBBBBDDBBBBBBBBO...e',
33:'.......OLLHLLLLDLLLLLLLBBBBBBBBBDDBBBBBBBBBO..eae',
34:'.......OLLHLLLLDDLLLLBBBBBBBBBBDDBBBBBBBBBBO..e',
35:'.......OLLLLLLLBDDDDBBBBBBBBBBDDBBBBBBBBBBO',
36:'.......OLLLLLBBBDDBBDDDDDDDDDBBBBBBBBBBBBBO',
37:'.......OLLLLBBBBDBBBBBBBBBBBBDDBBBBBBBBBBBO',
38:'.......OLLLBBBBDBBBBBBBBBBBBBBDDBBBBBBBBBO',
39:'.......OLLBBBBDBBBBBBBBBBBBBBBBDDBBBBBBBBO',
40:'.......OLBBBBDBBBBBBBBBBBBBBBBBBDDSSSBBBBO',
41:'.......OBBBBDBBBBBBBBBBBBBBBBBBDSDSSSSSSOOO',
42:'.......OBBBDDDDDDDDDDDDDDDDDDDDSSSDSSSSSOllOO',
43:'.......OBBSSSSSSSSSSSSSSSSSSSSSSSSSSDSSSOlhllO',
44:'.....OOOBSSSSSBBBBSSSSSSSBBBBSSSSSSSSSDDOllhllO',
45:'....OlgOOSSSSSSBBBBBSSSSBBBBBBSSSSSSSSDOlhhlllO',
46:'...OggvOOOSSSSSSBBBBBSSSBBBBBBSSSSSSSDOllhllggO',
47:'..OgvOO...OOSSSSSSSSSSSSSSSSSSSSSSSOOgglhllggO',
48:'..OOO.......OOODDDDDDDDDDDDDDDDDDOOgggglOOgggO',
49:'.............OlgggggOOOOvvvvvvvvOOllgggglggggO',
50:'............OllhllggvOOvvvvvvvvOllhhllgvOgggO',
51:'............OlhhllggvvOOvvvvvvOllhhllgvvOOOOggO',
52:'............OlhllggvvvOOgvvvOOOlhhhllgvvO.OggvO',
56:'...........OlggggvvvO........OllggggvvO',
57:'..........OllggggvvvO.......OllggggvvvO',
58:'.........OllgggggvvvO......OllgggggvvvO',
59:'.........OlggggaaavvO......OlggggaaavvO',
60:'.........OOOOOOOOOOOO......OOOOOOOOOOOO',
})
FRAMES['stun_b']=revised(FRAMES['stun_a'],{
25:'..............OOLLLHHHHHHDLLLLLLLBBBBBO',
26:'............OOLLLLLHHHHDDDDLLLLLBBBBBBBO',
27:'...........OLLLLLLLLLDDLLLLDDLLBBBBBBBBBO',
28:'..........OLLLLLLLLDDLLLLLLLLDDBBBBBBBBBBO....e',
29:'.........OLLLLLLDDDLLLLLLLLLLLDDBBBBBBBBBO....a',
30:'.........OLLHLLDLLLLLLLLLLLLLLLLDBBBBBBBBBOeeaee',
31:'........OLLHLLLDLLLLLLLLLLLBBBBBDDBBBBBBBBO..a',
32:'........OLLHLLLDLLLLLLLLLBBBBBBBDDBBBBBBBBO..e........e',
33:'.......OLLHLLLLDLLLLLLLBBBBBBBBBDDBBBBBBBBBO.........eae',
34:'.......OLLHLLLLDDLLLLBBBBBBBBBBDDBBBBBBBBBBO.........e',
44:'.....OOOBSSSSSBBBBSSSSSSSBBBBSSSSSSSSSDDOlhlllO',
45:'....OlgOOSSSSSSBBBBBSSSSBBBBBBSSSSSSSSDOllhllO',
46:'...OggvOOOSSSSSSBBBBBSSSBBBBBBSSSSSSSDOlhhllgO',
47:'..OgvOO...OOSSSSSSSSSSSSSSSSSSSSSSSOOgllhllggO',
48:'..OOO.......OOODDDDDDDDDDDDDDDDDDOOgggglhlllggO',
49:'.............OlgggggOOOOvvvvvvvvOOllgggglOOgggO',
50:'............OllhllggvOOvvvvvvvvOllhhllgvOlggggO',
51:'............OlhhllggvvOOvvvvvvOllhhllgvvOOgggO',
52:'............OlhllggvvvOOgvvvOOOlhhhllgvvO.OOOvO',
})

# Stable sleep: lowered but upright shell, cheek resting on the folded front
# foot, two folded hind feet and the exposed tail tip remain throughout breathing.
FRAMES['sleep_a']=canvas({
28:'.....................OOOOOOOOOOOO',
29:'..................OOOHHHHLLLLLLLLOOO',
30:'................OOLHHHHHHLLLLLLLLLBBBO',
31:'..............OOLLLHHHHHHDLLLLLLLLBBBBBO',
32:'............OOLLLLLHHHHDDDDLLLLLLBBBBBBBO',
33:'...........OLLLLLLLLLDDLLLLDDLLLBBBBBBBBBO',
34:'..........OLLLLLLLLDDLLLLLLLLDDDBBBBBBBBBBO',
35:'.........OLLLLLLDDDLLLLLLLLLLLLDDBBBBBBBBBO',
36:'.........OLLHLLDLLLLLLLLLLLLLLLLLDBBBBBBBBO',
37:'........OLLHLLLDLLLLLLLLLLLBBBBBBDDBBBBBBBO',
38:'........OLLHLLLDLLLLLLLLLBBBBBBBBDDBBBBBBBO',
39:'.......OLLHLLLLDLLLLLLLBBBBBBBBBBDDBBBBBBBBO',
40:'.......OLLHLLLLDDLLLLBBBBBBBBBBBDDBBBBBBBBO',
41:'.......OLLLLLLLBDDDDBBBBBBBBBBBDDBBBBBBBBBO',
42:'.......OLLLLLBBBDDBBDDDDDDDDDDDBBBBBBBBBBBO',
43:'.......OLLLLBBBBDBBBBBBBBBBBBBBDDBBBBBBBBBO',
44:'.......OLLLBBBBDBBBBBBBBBBBBBBBBDDBBBBBBBBO',
45:'.......OLLBBBBDBBBBBBBBBBBBBBBBBBDDBBBBBBO',
46:'.......OLBBBBDBBBBBBBBBBBBBBBBBBBBBDDSSBBO',
47:'.......OBBBBDBBBBBBBBBBBBBBBBBBBBDSDSSSSO',
48:'.......OBBBDDDDDDDDDDDDDDDDDDDDDDSSSDSSSO',
49:'.......OBBSSSSSSSSSSSSSSSSSSSSSSSSSSSSDSSO..OOOOOO',
50:'.....OOOBSSSSSBBBBSSSSSSSBBBBBSSSSSSSSSDDOOllhhhhOO',
51:'....OlgOOSSSSSSBBBBBSSSSBBBBBBBSSSSSSSSDOllhhhOOOllO',
52:'...OggvOOOSSSSSSBBBBBSSSBBBBBBBSSSSSSSDOllhhlllllggO',
53:'..OgvOO...OOSSSSSSSSSSSSSSSSSSSSSSSSOOOllhllllggggOO',
54:'..OOO.......OOODDDDDDDDDDDDDDDDDDDOOggggllgggggOOO',
55:'.............OllhhllgOOOOvvvvvvvvOOllhhllggvvvvO',
56:'............OllhhllgggvOOvvvvvvOOllhhhllggvvOOO',
57:'............OllhllggggvvOOOOOOOOllhhllggvvvO',
58:'............OllggggggvvOOgaavvOOllggggggvvO',
59:'...........OllgggaaagvvOOOOOOOOllgggaaagvvO',
60:'...........OOOOOOOOOOOO......OOOOOOOOOOOOO',
})
FRAMES['sleep_b']=revised(FRAMES['sleep_a'],{
28:'.....................OOOOOOOOOOOO',
29:'..................OOOHHHHHLLLLLLLOOO',
30:'................OOLHHHHHHHLLLLLLLLBBBO',
31:'..............OOLLLHHHHHHDDLLLLLLLBBBBBO',
32:'............OOLLLLLHHHHDDDDLLLLLLBBBBBBBO',
50:'.....OOOBSSSSSBBBBSSSSSSSBBBBBSSSSSSSSSDDOOllhhhllOO',
51:'....OlgOOSSSSSSBBBBBSSSSBBBBBBBSSSSSSSSDOllhhhOOOllO',
52:'...OggvOOOSSSSSSBBBBBSSSBBBBBBBSSSSSSSDOllhhhllllggO',
54:'..OOO.......OOODDDDDDDDDDDDDDDDDDDOOgggglllggggOOO',
55:'.............OllhhllgOOOOvvvvvvvvOOllhhhllgvvvvO',
})

def save():
    (ROOT/'palette.json').write_text(json.dumps(PALETTE,indent=2)+'\n')
    for name,rows in FRAMES.items():
        folder=ROOT/('poses' if name in ('idle_a','idle_b','idle_c','windup','move','attack','recover','hit','dead') else 'actions')
        folder.mkdir(exist_ok=True)
        (folder/(name+'.pxgrid')).write_text('\n'.join(rows)+'\n')

if __name__=='__main__': save()
