16 32
a linen 1
b linen 6
c linen 5
l linen 3
d purple 1
e purple 5
f purple 3
g purple 2
k purple 6
h wood 5
i wood 2
j wood 1
m wood 6
---
.......aa.......
......abba......
......acla......
.....deaaed.....
.....dkeeed.....
......dffd......
.....dgggggd....
....dgkeeeefg...
...dgkeeeeefg...
...dgkeeeeffg...
....dgkeeffgd...
.....dgkeffgd...
.....dgkeffgd...
....dgkeeeffg...
....dgkeeeffg...
...dgkeeeeefg...
...dgkeeeeffg...
...dggkeeffgg...
....dddddddd....
.......mi.......
.......mi.......
.......mi.......
.......mi.......
.......mi.......
.......mi.......
.......mi.......
.......mi.......
.......mi.......
.......mi.......
.......mi.......
....hhhhhhhh....
....jjjjjjjj....
