16 32
j wood 1
m wood 6
h wood 5
i wood 2
n wood 3
o red 1
p red 2
q red 3
s red 4
t red 5
u linen 5
v linen 3
---
.......jj.......
......jmhj......
......jmhj......
......jhj.......
.......ii.......
....otuuvvpo....
...otsssssqpo...
...otsssssqpo...
....otsssqpo....
.....otsqpo.....
.....oqqppo.....
.....otsqpo.....
....ottssqpo....
....ottqsqpo....
...ottqssqqpo...
...ottqssqqpo...
..ottqssqssqpo..
..ottqssqssqpo..
..ottqssqssqpo..
.ottqssqssqsqpo.
.ottqssqssqsqpo.
.ottqssqssqsqpo.
.ouuuuuuvvvvvvo.
.......mi.......
.......mi.......
.......mi.......
.......mi.......
.......mi.......
.......hi.......
.......hi.......
....hhhhhhhh....
.~~~jjjjjjjj~~..
