import fs from 'node:fs';
import {configFromEnv} from './supabase-resource-root/supabaseRest.mjs';
import {listSupabaseProjects,loadProjectFromSupabase} from '../src/project/supabaseProjectSync';
import {serialize} from '../src/project/io';
const config=await configFromEnv();
const matches=(await listSupabaseProjects(config)).filter(p=>p.title.includes('고양이'));
console.log(JSON.stringify(matches));
if(matches.length!==1)throw new Error('Expected one 고양이 project');
const projectId=matches[0]!.projectId;
const project=await loadProjectFromSupabase({...config,projectId});
if(!project)throw new Error('Reference project unavailable');
fs.writeFileSync('output/evidence/house-studies/reference-project.json',serialize(project));
console.log(JSON.stringify({projectId,maps:Object.values(project.maps).map(m=>({id:m.id,name:m.name,width:m.width,height:m.height,tilesetId:m.tilesetId}))}));
