from pathlib import Path
import json
from PIL import Image
ROOT=Path(__file__).parent
PAL={'O':'#142232','n':'#1b3b50','b':'#245b75','t':'#287e89','j':'#399f99','l':'#71c7af','h':'#b8e6cf','g':'#805d44','G':'#bd914c','Y':'#edcb81','W':'#fff0cf','m':'#483342','R':'#90505a','p':'#d18b78','e':'#edfff7','c':'#95d9e4','a':'#4b84b1','v':'#b7b970'}
(ROOT/'palette.json').write_text(json.dumps(PAL,indent=2)+'\n')
def blank(): return [list('.'*128) for _ in range(128)]
def block(canvas,x,y,rows):
    for dy,row in enumerate(rows.strip('\n').splitlines()):
        assert x+len(row)<=128,(x,y+dy,len(row))
        canvas[y+dy][x:x+len(row)]=list(row)
def patches(canvas,items):
    for x,y,row in items:
        assert 0<=x and x+len(row)<=128
        canvas[y][x:x+len(row)]=list(row)
def save(name,canvas,action=False):
    path=ROOT/('actions' if action else 'poses')/(name+'.pxgrid')
    path.write_text('\n'.join(''.join(r) for r in canvas)+'\n')
def png(canvas,path,scale=1):
    im=Image.new('RGBA',(128,128))
    pixels=im.load()
    for y,row in enumerate(canvas):
        for x,s in enumerate(row):
            if s!='.': pixels[x,y]=tuple(bytes.fromhex(PAL[s][1:]))+(255,)
    if scale!=1: im=im.resize((128*scale,128*scale),Image.Resampling.NEAREST)
    im.save(path)

# The long lower body is one continuous authored coil. Each row is chosen literally.
COIL='''
..............OOOOO..................................OOOnnOO
............OOtjjjnOO...............................OntjjjbbnO
...........OtjllhlljnO.............................OntjllljjtbnO
..........OtjlhhllljtbO...........................OntjllllljttbnO
..........OtjlhljjjjttbO.........................OntjllllljjttbbnO
.........OtjlljjttttbbnO.......................OOntjlllljjjtttbbnO
.........OtjljtttbbnnnO......................OOntjlllljjjjtttbbnO
.........OtjjttbbnOOO......................OOntjlllljjjttttbbnnO
..........OtjttbnO......................OOOntjllllljjjttttbbbnnO
..........OnttbnO...................OOOOnntjlllllljjjttttbbbnnO
...........OntbnO...............OOOOnntjjlllllllljjjttttbbbnnO
............OnbnOO..........OOOOnntjjllllllllllljjjttttbbnnnO
.............OnbbnOOOOOOOOOOOnntjjlllllllllllljjjjtttbbbnnnO
..............OnbbbbnnnnnnttjjjlllllllllllljjjjttttbbnnnOO
...............OnbbttttjjjlllllllllllllljjjjttttbbnnnOO
..............OOnttjjllllllllllllllljjjjjttttbbbnnnOO
............OOntjjllhhhhhhlllllllljjjjtttttbbbnnnOOOOOOOOOO
...........OntjllhhhhhhhlllllllljjjttttttbbbnnnntttjjjtttbnOOO
..........OntjllhhllllllljjjjjjtttttbbbnnnnttjjlllllllllljjttbnOO
.........OntjllhllljjjjjtttttbbbbnnnnnttjjllllllhhhhhhlllljjttbbnOO
........OntjllhlljjjttttbbbnnnOOOnnttjjllllhhhhhhhhhhhhlllljjtttbbnOO
.......OntjllhlljttttbbnnOOOO....OntjjllllhhhhhhhhllllllhlllljjtttbbnOO
......OntjllhlljttbbnnOO........OntjllhhhhhhhlllljjjjjllllhlllljjtttbbnO
.....OntjllhlljttbnOO...........OntjllhhhllllljjjttttttjjllhlllljjtttbbnO
....OntjllhlljttbnO.............OntjllhhlllljjjtttbbbbtttjjllhlllljjttbbnO
...OntjllhlljttbnO..............OntjllhlllljjttbbnnnnnnbttjjllhlllljjttbbnO
..OntjllhlljttbnO...............OntjlllljjttbbnOOOOOOOOnnbtjjllhlllljjttbbnO
..OntjllhlljttbnO................OntjjjjttbbnOO........OnnbtjjllhlllljjttbbnO
.OntjllhlljttbnO..................OnttttbbnOO...........OnnbtjjllhlllljjttbbnO
.OntjllhlljttbnO...................OnbbbnnO..............OnnbtjjllhlllljjttbbnO
.OntjllhlljttbnO....................OOOOO................OnnbtjjllhlllljjttbbnO
.OntjllhlljttbnO........................................OnnbtjjllhlllljjttbbnO
.OntjllhlljttbnOO.......................................OnnbtjjllhlllljjttbbnO
.OntjllhlljtttbnOO.....................................OnnbtjjllhlllljjttbbnO
.OntjllhlljjtttbbnOO..................................OnnbtjjllhlllljjttbbnO
..OntjllhlljjjtttbbnOO...............................OnnbtjjllhlllljjttbbnO
..OntjllhhlljjjjtttbbnnOOOOOOO.......................OnnbtjjllhlllljjttbbnO
...OntjllhhhlllljjtttbbbbnnnnnOOOOOOOOOOOOOOOOOOOOOOOnnbtjjllhlllljjttbbnO
...OntjllhhhhlllljjjtttttbbbbbbnnnnnnnnnnnnnnnnnnnnbttjjllhlllljjttbbnO
....OntjlllhhhhlllljjjjtttttttttbbbbbbbbbbbbbbbbbbttjjllhlllljjttbbnnO
.....OntjjlllhhhhlllljjjjjjjtttttttttttttttttttttjjjllhlllljjttbbnnO
......OnttjjlllhhhhlllllljjjjjjjjjjjjjjjjjjjjjjjjjllhlllljjtttbbnnO
.......OnbttjjlllhhhhhllllllllllllllllllllllllllllhlllljjtttbbnnO
........OnbbttjjllllhhhhhhlllllllllllllllllllllhhlllljjtttbbnnO
.........OnbbttjjjlllllhhhhhhhhhhhhhhhhhhhhhhhhhhlllljjtttbbnnO
..........OnbbtttjjjjlllllllllllllllllllllllllllljjtttbbbnnO
...........OnbbttttjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjtttbbbnnO
............OnbbbttttttjjjjjjjjjjjjjjjjjjjjjjtttttbbbnnO
.............OngGGYYYYWWWWWWYYYYYYYYYYYYYYYYYYYYGGgnO
..............OgGYYYWWWWWWWWWWYYYYYYYYYYYYYYYYYGGgO
...............OgGYYYYYWWWWWWYYYYYYYYYYYYYYYYYGGgO
................OgGGYYYYYYYYYYYYYYYYYYYYYYYYGGgO
.................OgGGGYYYYYYYYYYYYYYYYYYYYYGGGgO
..................OngGGGGGGGGGGGGGGGGGGGGGGgnO
....................OnnggggggggggggggggggnnO
......................OOnnnnnnnnnnnnnnnOO
........................OOOOOOOOOOOOOOO
'''
# Neck leans up from the rear coil; ventral tiles turn along the right edge.
NECK='''
....................OOOOOOOO
.................OOOntjjjjbnOO
...............OOntjllhlljjtbngO
..............OntjllhhlljjttbngGO
.............OntjllhhlljjttbbngYO
............OntjllhhlljjttbbngGYO
...........OntjllhhlljjttbbngGYYO
..........OntjllhhlljjttbbngGYYWO
.........OntjllhhlljjttbbngGYYWWO
........OntjllhhlljjttbbngGYYWWYO
.......OntjllhhlljjttbbngGYYWWYG O
......OntjllhhlljjttbbngGYYWWYGgO
.....OntjllhhlljjttbbngGYYWWYGgO
....OntjllhhlljjttbbngGYYWWYGgO
....OntjllhhlljjttbbngGYYWWYGgO
...OntjllhhlljjttbbngGYYWWYGgO
...OntjllhhlljjttbbngGYYWWYGgO
..OntjllhhlljjttbbngGYYWWYGgO
..OntjllhhlljjttbbngGYYWWYGgO
..OntjllhhlljjttbbngGYYWWYGgO
..OntjllhhlljjttbbngGYYWWYGgO
..OntjllhhlljjttbbngGYYWWYGgO
..OntjllhhlljjttbbngGYYWWYGgO
..OntjllhhlljjttbbngGYYWWYGgO
..OntjllhhlljjttbbngGYYWWYGgO
..OntjllhhlljjttbbngGYYWWYGgO
...OntjllhhlljjttbbngGYYWWYGgO
...OntjllhhlljjttbbngGYYWWYGgO
....OntjllhhlljjttbbngGYYWWYGgO
....OntjllhhlljjttbbngGYYWWYGgO
.....OntjllhhlljjttbbngGYYWWYGgO
.....OntjllhhlljjttbbngGYYWWYGgO
......OntjllhhlljjttbbngGYYWWYGgO
......OntjllhhlljjttbbngGYYWWYGgO
.......OntjllhhlljjttbbngGYYWWYGgO
.......OntjllhhlljjttbbngGYYWWYGgO
........OntjllhhlljjttbbngGYYWWYGgO
.........OntjllhhlljjttbbngGYYWWYGgO
..........OntjllhhlljjttbbngGYYWWYGgO
...........OntjllhhlljjttbbngGYYWWYGgO
............OntjllhhlljjttbbngGYYWWYGgO
.............OntjllhhlljjttbbngGYYWWYGgO
..............OntjllhhlljjttbbngGYYWWYGgO
...............OntjllhhlljjttbbngGYYWWYGgO
................OntjllhhlljjttbbngGYYWWYGgO
.................OntjllhhlljjttbbngGYYWWYGgO
'''.replace(' ','g')
HEAD='''
...............OOOOOOOOOO
............OOOntjjllllllnOO
..........OOntjllhhhhhhhlljjO
.........OntjllhhhhhhhhlllljjOO
........OntjllhhhhlllllhlhllljnOO
.......OntjllhhhlljjllllhhhllllttnOO
......OntjllhhlljjjllllhhhhhlllllttnOOOOOO
.....OntjllhhlljjjllhhhhhhlllljjlllllljjjnOO
....OntjllhhlljjjlhhhlljjllljjjjllllhhhhlljnO
...OntjllhhlljjjlhhllOOOllljjjllllllhhhhlljnO
..OntjllhhlljjjlhhllOWpOlljjjlllllllhhhllljnO
..OntjllhhlljjjlhhllORROlljjllllljjjlllllljnO
.OntjllhhlljjjlhhlllOOOlljjlllljjjjjllOOlljnO
.OntjllhhlljjjlhhlllllljjjllljjttttjllOnlljnO
.Ontjllhhlljjjlhhlll jjjjlljjttbbbbtjjllljnO
.OntjllhhlljjjlhhlljjjjlljjttbbbbbbttjjjnOO
..OntjllhhlljjjlhhlljjlljjttbbnOOOOOOOnnOO
..OntjllhhlljjjlhhlljlljjttbbnOmRRRRmmOO
...OntjllhhlljjjlhhlllljjttbbnOgYYYYYYgO
....OntjllhhlljjjlhhlljjttbbnOgGYYYYGGgO
.....OntjllhhlljjjlhhlljjttbbnOgGGGGGggO
......OntjllhhlljjjlhhlljjttbbnOnggggnO
.......OntjllhhlljjjlhhlljjttbbnOOnnOO
........OntjllhhlljjjlhhlljjttbbnO
.........OntjllhhlljjjlhhlljjttbbnO
..........OntjllhhlljjjlhhlljjttbbnO
'''.replace(' ','j')
base=blank()
block(base,8,68,COIL)
block(base,44,33,NECK)
block(base,64,14,HEAD)
# Short jade mane: broad three flowing leaves, never horns.
block(base,43,23,'''................OOOOOO
.............OOOjllhhnO
.........OOOOnjllhhllnO
.....OOOOnjjllhhhlljnO
..OOOnjjllhhhhlljtnOO
.OjllhhhhhhlljjtnOO
OjhhhhlllljjttnOO
.OjjjtttttnOOO
..OOOOOOOO
''')
block(base,42,32,'''..........OOOOOO
.......OOOnjlhhnO
...OOOOnjllhhhjnO
.OOnjllhhhlljtnO
OjllhhhlljjtnOO
.OjjlljjttnOO
..OOOOnnOO
''')
block(base,43,41,'''.......OOOOO
....OOOnjlhhnO
.OOOnjllhlljnO
OjllhlljjtnOO
.OjjtttnOOO
..OOOOOO
''')
# Golden torc with large inset jade medallion, and segmented belly overlaps.
patches(base,[
(60,42,'gGGYYWWYYGGg'),(58,43,'gGYYYWWYYYYGGg'),(57,44,'gGYYWhllhWYYGGg'),
(56,45,'gGYYhjjjlhYYGGg'),(55,46,'gGYYljOjjlYYGGg'),(54,47,'gGYYhjtjlhYYGGg'),
(54,48,'gGGYYhllhYYGGg'),(53,49,'ngGGYYYYYYGGg'),(54,50,'nggGGGGGGGgn'),
(68,53,'gGGYYYYGg'),(67,59,'gGGYYYYGg'),(67,65,'gGGYYYYGg'),(70,71,'gGGYYYYGg'),
(76,77,'gGGYYYYGg'),(35,116,'gGGYYYYYYGg'),(50,118,'gGGYYYYYYGg'),
# Chosen scale plates: asymmetric facets occupy connected broad planes.
(70,21,'ljllllhll'),(72,22,'jjlllllj'),(72,23,'tjjlljj'),
(60,56,'llhhlj'),(59,57,'jllljt'),(59,58,'tjjjtb'),
(56,64,'lhhllj'),(55,65,'jllllt'),(55,66,'tjjjtb'),
(43,78,'lhhhhllj'),(43,79,'jllllljt'),(44,80,'tjjjjttb'),
(23,91,'llhhllj'),(22,92,'jlllljt'),(22,93,'tjjjttb'),
(23,102,'lhhhllj'),(24,103,'jlllljt'),(25,104,'tjjjttb'),
(40,108,'lhhhhhllj'),(41,109,'jlllllljt'),(42,110,'tjjjjjttb'),
(60,111,'lhhhhllj'),(61,112,'jllllljt'),(62,113,'tjjjjttb'),
(53,90,'lhhhllj'),(53,91,'jlllljt'),(54,92,'tjjjttb'),(72,91,'lhhhllj'),(73,92,'jlllljt'),(74,93,'tjjjttb'),(81,101,'lhhllj'),(81,102,'jllljt'),(81,103,'tjjttb'),
# Pearl beside the jaw and two independent long whiskers rooted in muzzle.
(110,42,'gGGg'),(109,43,'gYWYG'),(109,44,'gWWYG'),(110,45,'gGGg'),
(102,29,'YYg'),(105,28,'YYg'),(108,27,'Yg'),(110,26,'Yg'),(112,25,'Yg'),(114,24,'Yg'),(115,23,'Yg'),(116,22,'g'),
(101,35,'YYg'),(104,36,'YYg'),(107,37,'YYg'),(110,38,'Yg'),(112,39,'Yg'),(114,40,'Yg'),(115,41,'Yg'),(116,42,'Yg'),(116,43,'Yg'),(115,44,'g'),
])
save('idle_a',base)
png(base,ROOT/'progress/idle.png')
png(base,ROOT/'progress/idle-4x.png',4)
# Finishing idle clusters: broad, irregular blue scale shadows and carved gold edges.
patches(base,[
(77,18,'llhhhhhll'),(78,19,'llhhhhllll'),(77,20,'jlllllll'),
(83,23,'tjjjllll'),(84,24,'nntjjll'),(84,25,'bntjll'),
(99,23,'llhhhhhll'),(100,24,'llhhhhll'),(101,25,'jlllllj'),
(87,26,'gYYG'),(88,27,'gGGg'),(95,31,'bbbbnOOOO'),(98,32,'nOmRRRmmO'),(98,33,'OYWWYgO'),
(57,51,'llhlllljt'),(56,52,'llhllllljt'),(55,53,'llhhlllljt'),
(55,54,'llhhhlljt'),(54,55,'llhhhlljt'),(54,56,'llhhlljjt'),
(53,57,'llhhlljjtt'),(53,58,'llhllljttt'),(53,59,'llhlljjttt'),
(52,60,'llhlljjttt'),(52,61,'llhlljjtttb'),(52,62,'llhlljjtttb'),
(52,63,'llhlljjtttb'),(52,64,'llhllljtttb'),(53,65,'llhhlljtttb'),
(54,66,'llhhhlljtttb'),(55,67,'llhhhlljjttb'),(56,68,'llhhhhlljjtt'),
(58,69,'llhhhlljjtt'),(59,70,'llhhhlljjtt'),(61,71,'llhhlljjttt'),
(63,72,'llhlljjttt'),(64,73,'llhlljjttt'),
(64,54,'tjjlhlj'),(64,55,'btjlljt'),(64,56,'bbtjjtb'),
(63,61,'tjlhlj'),(63,62,'btjljt'),(63,63,'bbtttb'),
(69,70,'tjlhllj'),(69,71,'btjlljt'),(69,72,'bbtjjtb'),
(54,48,'gGYYWYYGGg'),(55,49,'gGWhlhWYGg'),(56,50,'gYljjlhYG'),
(57,51,'gYljhlYG'),(58,52,'gYhllYG'),(59,53,'gGYYGg'),(60,54,'gGGg'),
(27,87,'jllhhhhlllljj'),(30,88,'jllhhhhllljtt'),(35,89,'tjjlllljjttb'),
(29,106,'jlllhhhlll'),(30,107,'jlllhhlllljt'),(31,108,'tjjlllljjtt'),
(69,87,'llhhhhlll'),(70,88,'jllhhhllj'),(71,89,'tjjlllljt'),(73,90,'btjjjjtb'),
(74,108,'llhhhllj'),(73,109,'jllhhlljt'),(72,110,'tjjlljjtb'),
])
save('idle_a',base)
png(base,ROOT/'progress/idle.png'); png(base,ROOT/'progress/idle-4x.png',4)
# The right-hand coil is a heavy advancing volume, hand redrawn wider than the rear turn.
block(base,60,85,'''OOOOOOOOOO
nnttjjjjjjnnOOOO
jjllllllhhhllttnOOO
llllhhhhhhhhllljttnnOO
llhhhhhhhhhlllljjjttbnOO
hhhhhhlllllljjjtttjjttbnOO
hhlllljjjjtttbbbttjjlljttbnOO
lllljjjtttbbnnnnnbttjjlljjttbnO
lljjjtttbbnOOOOOOnnbttjjlljjttbnO
jjjtttbbnOO......OnnbttjjlljjttbnO
ttttbbnOO.........OnnbttjjlljjttbnO
bbbbbnnO...........OnnbttjjlljjttbnO
nnnnnOO.............OnnbttjjlljjttbnO
OOOOO...............OnnbttjjlljjttbnO
....................OnnbttjjlljjttbnO
....................OnnbttjjlljjttbnO
...................OnnbttjjlljjttbnO
..................OnnbttjjlljjttbnO
.................OnnbttjjlljjttbnO
................OnnbttjjlljjttbnO
..............OOnnbttjjlljjttbnO
............OOnnbttjjlljjttbbnO
.........OOOnnbttjjlljjttbbnnO
......OOOnnbttjjlljjtttbbnnOO
...OOOnnbttjjlljjtttbbbnnOO
OOOnnbttjjlljjttttbbbnnOO
nnbttjjlljjttttbbbnnOO
bttjjlljjttttbbbnnOO
jjlljjttttbbbnnnOO
lljjttttbbbnnnOO
jjttttbbbnnnOO
ttttbbbnnnOO
''')
block(base,32,116,'''gGGYYYYWWWWWWWWYYYYYYYYYYYYGGGgnOO
ngGGYYYYWWWWWWYYYYYYYYYYYYGGGGgnOO
.ngGGGYYYYYYYYYYYYYYYYYYGGGGGgnOO
..OngGGGYYYYYYYYYYYYYYGGGGGgnOO
...OngGGGGYYYYYYYYYYGGGGGgnOO
....OnngGGGGGGGGGGGGGGgnnOO
......OnnggggggggggggnnOO
........OOnnnnnnnnnnOO
..........OOOOOOOOOO
''')
# Two whisker curves are continuous at the diagonal steps; pearl hangs at the tip.
patches(base,[(104,29,'YYg'),(106,28,'YYg'),(108,27,'YYg'),(110,26,'YYg'),(112,25,'YYg'),(114,24,'YYg'),(115,23,'Yg'),(116,22,'g'),
(103,35,'YYg'),(105,36,'YYg'),(107,37,'YYg'),(109,38,'YYg'),(111,39,'YYg'),(113,40,'YYg'),(115,41,'Yg'),(116,42,'Yg'),(116,43,'Yg'),(115,44,'g'),
(86,99,'lhhhllj'),(86,100,'jlllljt'),(87,101,'tjjjttb'),(80,107,'lhhhllj'),(80,108,'jlllljt'),(81,109,'tjjjttb'),
(55,119,'gGGYYYYGg'),(42,119,'gGGYYYGGg'),(64,117,'gGGYYYYGg')])
save('idle_a',base)
png(base,ROOT/'progress/idle.png'); png(base,ROOT/'progress/idle-4x.png',4)
# Breathing is localized to throat, cheek, medallion, and resting coils.
idle_b=[r.copy() for r in base]
patches(idle_b,[
(80,29,'llhhhllj'),(81,30,'jllhhllj'),(68,55,'ngGYYWWYGg'),(67,56,'ngGYYWWWYGg'),
(67,57,'ngGYYWWYGg'),(67,58,'ngGYYYYGg'),(67,60,'ngGYYWWYGg'),
(67,61,'ngGYYWWWYGg'),(67,62,'ngGYYWWYGg'),(67,63,'ngGYYYYGg'),
(71,69,'tjllhhllj'),(71,70,'btjlllljt'),(72,71,'bbtjjjjtb'),
(75,109,'llhhhllj'),(74,110,'jllhhlljt'),(73,111,'tjjlljjtb'),
(110,43,'YWYG'),(110,44,'WWYG'),(114,41,'Yg.'),(115,42,'Yg.'),(115,43,'Yg.'),(114,44,'g..'),
])
save('idle_b',idle_b)
idle_c=[r.copy() for r in base]
patches(idle_c,[
(86,24,'gGGgg'),(86,25,'nOOOn'),(86,26,'tjllj'),
(57,56,'llhhlljj'),(56,57,'llhhlljj'),(55,58,'llhlljjt'),
(69,56,'gGYYWYGg'),(68,57,'gGYYWYGg'),(68,58,'gGYYYGg'),
(41,109,'jlllhhlljt'),(42,110,'tjjlllljtt'),(43,111,'bttjjjjttb'),
(60,51,'gYhlllYG'),(60,52,'gYhhlYG'),(60,53,'gGYYGg'),
(114,24,'Yg.'),(115,23,'g..'),(116,22,'...'),
(113,25,'Yg.'),(111,26,'Yg.'),(109,27,'Yg.'),
])
save('idle_c',idle_c)

def lower():
    c=blank()
    # Exact unchanged resting body pixels; no resampling or coordinate transformation.
    for y in range(80,125): c[y]=base[y].copy()
    for y in range(68,80): c[y][8:41]=base[y][8:41]
    return c

def record(name,c,action=False):
    save(name,c,action); png(c,ROOT/'progress'/(name+'.png'))

WIND_NECK='''
.............OOOOOOOOOOOO
..........OOOntjllhhhlljtnOO
........OOntjllhhhhhhlljttbnO
......OOntjllhhhhhlllljjttbnO
.....OntjllhhhhllllljjttbbnO
....OntjllhhhllllljjjttbbnO
...OntjllhhhlllljjtttbbnnO
..OntjllhhlllljjjttbbnnOO
.OntjllhhlllljjjttbbnnO
.OntjllhhlllljjtttbbnO
OntjllhhlllljjtttbbngO
OntjllhhlllljjtttbbngGO
OntjllhhlllljjtttbbngYO
OntjllhhlllljjtttbbngYYO
OntjllhhlllljjtttbbngYYWO
OntjllhhlllljjtttbbngYYWWO
OntjllhhlllljjtttbbngGYYWWO
OntjllhhlllljjtttbbngGYYWWYO
.OntjllhhlllljjtttbbngGYYWYgO
.OntjllhhlllljjtttbbngGYYWYgO
..OntjllhhlllljjtttbbngGYYWYgO
..OntjllhhlllljjtttbbngGYYWYgO
...OntjllhhlllljjtttbbngGYYWYgO
....OntjllhhlllljjtttbbngGYYWYgO
.....OntjllhhlllljjtttbbngGYYWYgO
......OntjllhhlllljjtttbbngGYYWYgO
.......OntjllhhlllljjtttbbngGYYWYgO
........OntjllhhlllljjtttbbngGYYWYgO
.........OntjllhhlllljjtttbbngGYYWYgO
..........OntjllhhlllljjtttbbngGYYWYgO
...........OntjllhhlllljjtttbbngGYYWYgO
............OntjllhhlllljjtttbbngGYYWYgO
.............OntjllhhlllljjtttbbngGYYWYgO
..............OntjllhhlllljjtttbbngGYYWYgO
...............OntjllhhlllljjtttbbngGYYWYgO
................OntjllhhlllljjtttbbngGYYWYgO
.................OntjllhhlllljjtttbbngGYYWYgO
..................OntjllhhlllljjtttbbngGYYWYgO
...................OntjllhhlllljjtttbbngGYYWYgO
....................OntjllhhlllljjtttbbngGYYWYgO
.....................OntjllhhlllljjtttbbngGYYWYgO
......................OntjllhhlllljjtttbbngGYYWYgO
.......................OntjllhhlllljjtttbbngGYYWYgO
........................OntjllhhlllljjtttbbngGYYWYgO
'''
WIND_HEAD='''
..............OOOOOOOOOO
...........OOOntjjllllllnOO
.........OOntjllhhhhhhhlljjO
........OntjllhhhhhhhhlllljjOO
.......OntjllhhhhlllllhhlllljtnOO
......OntjllhhhllllllhhhhlllljttnOO
.....OntjllhhlllllllhhhhhhlllljjttnOOOOOO
....OntjllhhllllllhhhhhhlllljjjlllllljjnOO
...OntjllhhllllllhhlljjjjlljjlllllhhhhlljnO
..OntjllhhllllllhhllgGGglljjjllllllhhhlljnO
.OntjllhhllllllhhllOOpOlljjlllljjjjlllllljnO
.OntjllhhllllllhhllORROlljjllltttjjllOOlljnO
OntjllhhllllllhhlllOOOlljjlllttbbbjjllOnlljnO
OntjllhhllllllhhlllllljjjlllttbbbbtjjlllljnO
OntjllhhllllllhhlllljjjlllttbbbbnnnntjjjnOO
.OntjllhhllllllhhlljjjlllttbbnOOOOOOOnnOO
.OntjllhhllllllhhlljjlllttbbnOmRRRRmmO
..OntjllhhllllllhhlljllttbbnOgYYYYYYgO
...OntjllhhllllllhhlllttbbnOgGYYYYGGgO
....OntjllhhllllllhhllttbbnOgGGGGGggO
.....OntjllhhllllllhhllttbbnOnggggnO
......OntjllhhllllllhhllttbbnOOnnOO
.......OntjllhhllllllhhllttbbnO
........OntjllhhllllllhhllttbbnO
'''
windup=lower();block(windup,33,42,WIND_NECK);block(windup,42,26,WIND_HEAD)
block(windup,22,35,'''..............OOOOOO
..........OOOOnjlhlO
......OOOOnjllhhllnO
..OOOOnjllhhhlljtnO
OOjllhhhhlljjttnOO
.OjjlljjttnOOOO
..OOOOOOOO
''')
block(windup,20,44,'''..........OOOOOO
......OOOOnjlhhnO
..OOOOnjllhhhjnO
OOjllhhhlljttnO
.OjjlljjtnOOO
..OOOOOOOO
''')
patches(windup,[
(52,51,'gGGYYWWYYYGGg'),(49,52,'gGYYYWhllhWYYGGg'),(48,53,'gGYYWljjjlhYYGGg'),
(47,54,'gGYYWljhllhYYGGg'),(46,55,'ngGYYWhllhWYYGGg'),(46,56,'ngGGYYYYYYGGGg'),
(47,57,'ngggGGGGGGggn'),(54,61,'gGGYYYYGg'),(58,66,'gGGYYYYGg'),(64,71,'gGGYYYYGg'),(69,77,'gGGYYYYGg'),
(38,57,'llhhhllj'),(38,58,'jllllljt'),(39,59,'tjjjjttb'),(45,64,'lhhhllj'),(45,65,'jlllljt'),(46,66,'tjjjttb'),
(65,79,'ljllllhhlll'),(65,80,'tjllllllltt'),(67,81,'btjjjjttbb'),
(76,38,'YYg'),(78,37,'YYg'),(80,36,'YYg'),(82,35,'YYg'),(84,34,'YYg'),(86,33,'Yg'),
(78,44,'YYg'),(80,45,'YYg'),(82,46,'YYg'),(84,47,'YYg'),(86,48,'YYg'),(88,49,'YYg'),(90,50,'Yg'),(91,51,'g'),
(86,52,'gGGg'),(85,53,'gYWYG'),(85,54,'gWWYG'),(86,55,'gGGg'),
(76,37,'llhhhllj'),(76,38,'llhhhhllj'),(78,39,'jlllllj'),
])
record('windup',windup)

MOVE_NECK='''
......................................OOOOOOOOOOOOOO
.................................OOOOOnnttjjllllllnnOO
............................OOOOOnnttjjllllhhhhhhhlljjnOO
.......................OOOOOnnttjjllllhhhhhhhhhhlllljjttnO
...................OOOOnnttjjllllhhhhhhhhllllllljjjjtttbbnO
...............OOOOnnttjjllllhhhhhhhllllljjjjjjjttttbbnnO
............OOOnnttjjllllhhhhhhhhlllljjjjttttttbbbnnnOO
.........OOOnnttjjllllhhhhhhhlllljjjjttttbbbnnnnnOOO
.......OOnttjjllllhhhhhhhlllljjjjttttbbbnnOOOOOOO
.....OOnttjjllllhhhhhhhlllljjjjttttbbbnnOO
....OnttjjllllhhhhhhhlllljjjjttttbbbnnOgGg
...OnttjjllllhhhhhhhlllljjjjttttbbbnnOgGYYGg
..OnttjjllllhhhhhhhlllljjjjttttbbbnnOgGYYWWYGg
.OnttjjllllhhhhhhhlllljjjjttttbbbnnOgGYYWWWYYGg
OnttjjllllhhhhhhhlllljjjjttttbbbnnOgGYYWWWWYYYGg
OnttjjllllhhhhhhhlllljjjjttttbbbnnOgGYYWWWWYYYYGg
OnttjjllllhhhhhhhlllljjjjttttbbbnnOgGYYWWWYYYYGGg
OnttjjllllhhhhhhhlllljjjjttttbbbnnOgGYYWWYYYYGGg
.OnttjjllllhhhhhhhlllljjjjttttbbbnnOgGYYYYYGGg
.OnttjjllllhhhhhhhlllljjjjttttbbbnnOngGGGGGgnO
..OnttjjllllhhhhhhhlllljjjjttttbbbnnOngggggnO
..OnttjjllllhhhhhhhlllljjjjttttbbbnnOOnnnOO
...OnttjjllllhhhhhhhlllljjjjttttbbbnnO
....OnttjjllllhhhhhhhlllljjjjttttbbbnnO
.....OnttjjllllhhhhhhhlllljjjjttttbbbnnO
......OnttjjllllhhhhhhhlllljjjjttttbbbnnO
.......OnttjjllllhhhhhhhlllljjjjttttbbbnnO
........OnttjjllllhhhhhhhlllljjjjttttbbbnnO
.........OnttjjllllhhhhhhhlllljjjjttttbbbnnO
'''
MOVE_HEAD='''
..........OOOOOOOOOO
.......OOOntjjllllllnOO
.....OOntjllhhhhhhhlljjO
....OntjllhhhhhhlllllljjOO
...OntjllhhhlllllhhhlllljtnOO
..OntjllhhllllllhhhhllllljttnOO
.OntjllhhllllllhhhhhlllllljjttnOOO
OntjllhhllllllhhlljjjjjlljjjjlllljnO
OntjllhhllllllhllgGgllljjjllllhhlljnO
OntjllhhllllllhllOWpOlljjlllllhhhlljnO
OntjllhhllllllhllORROlljjlllttjllOOjnO
OntjllhhllllllhlllOOOlljjllttbtjjOnjnO
OntjllhhllllllhlllllljjjllttbbbttjjjnO
.OntjllhhllllllhlllljjjllttbbnnOOOOOO
.OntjllhhllllllhllljjllttbbnOmRRRRmO
..OntjllhhllllllhlljjllttbbnOWWYWWYO
...OntjllhhllllllhlljllttbbnOgYYYYGgO
....OntjllhhllllllhlllttbbnOgGGGGgO
.....OntjllhhllllllhllttbbnOngggnO
......OntjllhhllllllhllttbbnOOnOO
.......OntjllhhllllllhllttbbnO
........OntjllhhllllllhllttbbnO
'''
move=lower();block(move,40,53,MOVE_NECK);block(move,88,43,MOVE_HEAD)
block(move,69,45,'''..............OOOOO
..........OOOOnjhlO
......OOOOnjllhhlnO
..OOOOnjllhhhlltnO
OOjllhhhhlljttnOO
.OjjlljjtnOOOO
..OOOOOO
''')
block(move,65,54,'''.............OOOOO
.........OOOOnjhlO
.....OOOOnjllhllnO
.OOOOnjllhhhlltnO
OjllhhhhlljttnOO
.OjjlljjtnOOOO
..OOOOOO
''')
patches(move,[
(78,65,'gGGYYWWYYYYGGg'),(76,66,'gGYYYWhllhWYYGGg'),(74,67,'gGYYWljjjlhYYGGg'),(73,68,'gGYYWljhllhYYGGg'),
(73,69,'ngGYYWhllhWYYGGg'),(74,70,'ngGGYYYYYYGGGg'),(75,71,'ngggGGGGGGggn'),
(45,74,'lhhhhllj'),(45,75,'jllllljt'),(46,76,'tjjjjttb'),(63,66,'lhhhllj'),(63,67,'jlllljt'),(64,68,'tjjjttb'),
(59,80,'llhhhlljj'),(60,81,'jlllllljt'),(61,82,'tjjjjjttb'),
(117,54,'YYg'),(119,53,'YYg'),(121,52,'Yg'),(122,51,'g'),
(117,59,'YYg'),(119,60,'YYg'),(121,61,'YYg'),(123,62,'g'),
(118,65,'gGGg'),(117,66,'gYWYG'),(117,67,'gWWYG'),(118,68,'gGGg'),
])
record('move',move)

ATTACK_HEAD='''
............OOOOOOOOOO
.........OOOntjjllllllnOO
.......OOntjllhhhhhhhlljjO
......OntjllhhhhhhlllllljjOO
.....OntjllhhhlllllhhhlllljtnOO
....OntjllhhllllllhhhhllllljttnOO
...OntjllhhllllllhhhhhlllllljjttnOO
..OntjllhhllllllhhlljjjjjlljjjjlljnO
.OntjllhhllllllhllgGgllljjjllllhhjnO
OntjllhhllllllhllOOpOlljjlllllhhhjnO
OntjllhhllllllhllORROlljjlllttjllOnO
OntjllhhllllllhlllOOOlljjllttbtjjOnO
OntjllhhllllllhlllllljjjllttbbbttjjnO
OntjllhhllllllhlllljjjllttbbnOOOOOOO
OntjllhhllllllhllljjllttbbnOOWWWYWWO
.OntjllhhllllllhlljjllttbnOmOWWYYWYO
.OntjllhhllllllhlljllttbnOmROWWYOWO
..OntjllhhllllllhlllttbnOmRROWWOmO
..OntjllhhllllllhllttbnOmRRRROWOmO
...OntjllhhllllllhllttbnOmRRRRRmmO
...OntjllhhllllllhllttbnOmRRRRRmmO
....OntjllhhllllllhllttbnOmRRRRmmO
....OntjllhhllllllhllttbnOmRRRRmmO
.....OntjllhhllllllhllttbnOmRRmmO
.....OntjllhhllllllhllttbnOmRmmO
......OntjllhhllllllhllttbnOmRmO
......OntjllhhllllllhllttbnOmRmO
.......OntjllhhllllllhllttbnOWOmO
.......OntjllhhllllllhllttbnOWWmO
........OntjllhhllllllhllttbnOYWmO
.........OntjllhhllllllhllttbnOYWWYO
..........OntjllhhllllllhllttbnOGYYYO
...........OntjllhhllllllhllttbnOgGGO
............OntjllhhllllllhllttbnOggO
.............OntjllhhllllllhllttbnOOO
'''
attack=lower()
# The advancing shoulder has its own chosen planes and belly crease.
block(attack,40,55,'''....................................OOOOOOOOOOOOOO
...............................OOOOOnnttjjllllllnnOO
..........................OOOOOnnttjjllllhhhhhhhlljjnOO
.....................OOOOOnnttjjllllhhhhhhhhhhlllljjttnO
.................OOOOnnttjjllllhhhhhhhhllllllljjjjtttbbnO
.............OOOOnnttjjllllhhhhhhhllllljjjjjjjttttbbnnO
..........OOOnnttjjllllhhhhhhhhlllljjjjttttttbbbnnnOO
.......OOOnnttjjllllhhhhhhhlllljjjjttttbbbnnnnnOOO
.....OOnttjjllllhhhhhhhlllljjjjttttbbbnnOOOOOOO
...OOnttjjllllhhhhhhhlllljjjjttttbbbnnOgGGg
..OnttjjllllhhhhhhhlllljjjjttttbbbnnOgGYYYGg
.OnttjjllllhhhhhhhlllljjjjttttbbbnnOgGYYWWYGg
OnttjjllllhhhhhhhlllljjjjttttbbbnnOgGYYWWWYYGg
OnttjjllllhhhhhhhlllljjjjttttbbbnnOgGYYWWWWYYYGg
OnttjjllllhhhhhhhlllljjjjttttbbbnnOgGYYWWWWYYYYGg
OnttjjllllhhhhhhhlllljjjjttttbbbnnOgGYYWWWYYYYGGg
OnttjjllllhhhhhhhlllljjjjttttbbbnnOgGYYWWYYYYGGg
.OnttjjllllhhhhhhhlllljjjjttttbbbnnOgGYYYYYGGg
.OnttjjllllhhhhhhhlllljjjjttttbbbnnOngGGGGGgnO
..OnttjjllllhhhhhhhlllljjjjttttbbbnnOngggggnO
..OnttjjllllhhhhhhhlllljjjjttttbbbnnOOnnnOO
...OnttjjllllhhhhhhhlllljjjjttttbbbnnO
....OnttjjllllhhhhhhhlllljjjjttttbbbnnO
.....OnttjjllllhhhhhhhlllljjjjttttbbbnnO
......OnttjjllllhhhhhhhlllljjjjttttbbbnnO
.......OnttjjllllhhhhhhhlllljjjjttttbbbnnO
........OnttjjllllhhhhhhhlllljjjjttttbbbnnO
.........OnttjjllllhhhhhhhlllljjjjttttbbbnnO
''')
block(attack,88,41,ATTACK_HEAD)
block(attack,65,47,'''..............OOOOO
..........OOOOnjhlO
......OOOOnjllhhlnO
..OOOOnjllhhhlltnO
OOjllhhhhlljttnOO
.OjjlljjtnOOOO
..OOOOOO
''')
block(attack,63,56,'''.............OOOOO
.........OOOOnjhlO
.....OOOOnjllhllnO
.OOOOnjllhhhlltnO
OjllhhhhlljttnOO
.OjjlljjtnOOOO
..OOOOOO
''')
patches(attack,[
(74,68,'gGGYYWWYYYYGGg'),(72,69,'gGYYYWhllhWYYGGg'),(70,70,'gGYYWljjjlhYYGGg'),(69,71,'gGYYWljhllhYYGGg'),
(69,72,'ngGYYWhllhWYYGGg'),(70,73,'ngGGYYYYYYGGGg'),(71,74,'ngggGGGGGGggn'),
(44,75,'lhhhhllj'),(44,76,'jllllljt'),(45,77,'tjjjjttb'),(60,67,'lhhhllj'),(60,68,'jlllljt'),(61,69,'tjjjttb'),
(117,52,'YYg'),(119,51,'YYg'),(121,50,'Yg'),(122,49,'g'),
(113,71,'YYg'),(115,73,'YYg'),(117,74,'YYg'),(119,75,'YYg'),(121,75,'YYg'),(123,74,'g'),
(117,80,'gGGg'),(116,81,'gYWYG'),(116,82,'gWWYG'),(117,83,'gGGg'),
])
record('attack',attack)
RECOVER_NECK='''
.......................OOOOOOOOOOOO
....................OOOntjjllllllnnOO
..................OOntjllhhhhhhhlljttnO
................OntjllhhhhhhhlllljjttbnO
..............OOntjllhhhhhhlllljjtttbbnO
............OOntjllhhhhhhlllljjtttbbnO
..........OOntjllhhhhhhlllljjtttbbnO
........OOntjllhhhhhhlllljjtttbbngO
......OOntjllhhhhhhlllljjtttbbngGO
.....OntjllhhhhhhlllljjtttbbngYYO
....OntjllhhhhhhlllljjtttbbngYYWO
...OntjllhhhhhhlllljjtttbbngGYYWWO
..OntjllhhhhhhlllljjtttbbngGYYWWYO
.OntjllhhhhhhlllljjtttbbngGYYWWYGgO
.OntjllhhhhhhlllljjtttbbngGYYWWYGgO
OntjllhhhhhhlllljjtttbbngGYYWWYGgO
OntjllhhhhhhlllljjtttbbngGYYWWYGgO
OntjllhhhhhhlllljjtttbbngGYYWWYGgO
OntjllhhhhhhlllljjtttbbngGYYWWYGgO
.OntjllhhhhhhlllljjtttbbngGYYWWYGgO
.OntjllhhhhhhlllljjtttbbngGYYWWYGgO
..OntjllhhhhhhlllljjtttbbngGYYWWYGgO
...OntjllhhhhhhlllljjtttbbngGYYWWYGgO
....OntjllhhhhhhlllljjtttbbngGYYWWYGgO
.....OntjllhhhhhhlllljjtttbbngGYYWWYGgO
......OntjllhhhhhhlllljjtttbbngGYYWWYGgO
.......OntjllhhhhhhlllljjtttbbngGYYWWYGgO
........OntjllhhhhhhlllljjtttbbngGYYWWYGgO
.........OntjllhhhhhhlllljjtttbbngGYYWWYGgO
..........OntjllhhhhhhlllljjtttbbngGYYWWYGgO
...........OntjllhhhhhhlllljjtttbbngGYYWWYGgO
............OntjllhhhhhhlllljjtttbbngGYYWWYGgO
.............OntjllhhhhhhlllljjtttbbngGYYWWYGgO
..............OntjllhhhhhhlllljjtttbbngGYYWWYGgO
...............OntjllhhhhhhlllljjtttbbngGYYWWYGgO
................OntjllhhhhhhlllljjtttbbngGYYWWYGgO
'''
RECOVER_HEAD='''
...............OOOOOOOOO
............OOOntjllllllnOO
..........OOntjllhhhhhhhlljO
.........OntjllhhhhhhlllllljnOO
........OntjllhhhllllhhhhhlljttnOO
.......OntjllhhlllllhhhhhhhlljtttnOOOOOO
......OntjllhhllllhhhhhhlllllljjjjlllljjnO
.....OntjllhhllllhhlljjjjjlljjjjllllhhlljnO
....OntjllhhllllhhllgGGgllljjjllllllhhlljnO
...OntjllhhllllhhllOWpOlljjjllllllljlllljnO
..OntjllhhllllhhllORROlljjlllllljttjllOOjnO
.OntjllhhllllhhlllOOOlljjllllljttbbjjjOnjnO
OntjllhhllllhhlllllljjjlllljjttbbbbttjjjnO
OntjllhhllllhhlllljjjlllljjttbbbbnnnnnnOO
OntjllhhllllhhllljjlllljjttbbnnOOOOOOOOO
.Ontjllhhllllhhlljjlll jjttbbnOmRRRRRRmmO
.OntjllhhllllhhlljjlljjttbbnOmROWYYWWYmO
..OntjllhhllllhhlljjlljttbbnOmRROWWYYOmO
...OntjllhhllllhhlljjllttbbnOmRRRmYYOmO
....OntjllhhllllhhlljjlttbbnOgYYYYYYgO
.....OntjllhhllllhhlljjttbbnOgGYYYYGGgO
......OntjllhhllllhhlljttbbnOgGGGGGggO
.......OntjllhhllllhhllttbbnOnggggnO
........OntjllhhllllhhllttbbnOOnnOO
.........OntjllhhllllhhllttbbnO
...........OntjllhhllllhhllttbbnO
'''.replace(' ','j')
recover=lower();block(recover,44,47,RECOVER_NECK);block(recover,73,29,RECOVER_HEAD)
block(recover,50,35,'''.................OOOOOO
.............OOOOnjlhlO
.........OOOOnjllhhllnO
.....OOOOnjllhhhlljtnO
.OOOOnjllhhhhlljjttnOO
OjllhhhhlljjttnOOOO
.OjjlljjtnOOOO
..OOOOOO
''')
block(recover,48,46,'''............OOOOO
........OOOOnjhlO
....OOOOnjllhllnO
OOOOnjllhhhlltnO
.OjllhhhhlljttnOO
..OjjlljjtnOOOO
...OOOOOO
''')
patches(recover,[
(70,55,'gGGYYWWYYYGGg'),(68,56,'gGYYYWhllhWYYGGg'),(66,57,'gGYYWljjjlhYYGGg'),(65,58,'gGYYWljhllhYYGGg'),
(65,59,'ngGYYWhllhWYYGGg'),(66,60,'ngGGYYYYYYGGGg'),(67,61,'ngggGGGGGGggn'),
(52,64,'llhhhhllj'),(52,65,'jlllllljt'),(53,66,'tjjjjjttb'),(59,72,'lhhhllj'),(59,73,'jlllljt'),(60,74,'tjjjttb'),
(76,66,'gGGYYYYGg'),(78,72,'gGGYYYYGg'),(80,78,'gGGYYYYGg'),
(108,41,'YYg'),(110,40,'YYg'),(112,39,'YYg'),(114,38,'Yg'),(115,37,'g'),
(107,48,'YYg'),(109,50,'YYg'),(111,51,'YYg'),(113,52,'YYg'),(115,53,'Yg'),(116,54,'Yg'),(116,55,'g'),
(112,57,'gGGg'),(111,58,'gYWYG'),(111,59,'gWWYG'),(112,60,'gGGg'),
])
record('recover',recover)

HIT_NECK='''
.............OOOOOOOOOOO
..........OOOntjjllllllnnOO
........OOntjllhhhhhhhhlljtnO
......OOntjllhhhhhhhlllljjttbnO
....OOntjllhhhhhhlllljjjtttbbnO
...OntjllhhhhhlllljjjtttbbnnO
..OntjllhhhhlllljjjtttbbnnOO
.OntjllhhhlllljjjtttbbnnOO
OntjllhhhlllljjjtttbbnnO
OntjllhhhlllljjjtttbbngGO
OntjllhhhlllljjjtttbbngYYO
OntjllhhhlllljjjtttbbngYYWO
OntjllhhhlllljjjtttbbngGYYWWO
.OntjllhhhlllljjjtttbbngGYYWWYO
.OntjllhhhlllljjjtttbbngGYYWWYGgO
..OntjllhhhlllljjjtttbbngGYYWWYGgO
...OntjllhhhlllljjjtttbbngGYYWWYGgO
....OntjllhhhlllljjjtttbbngGYYWWYGgO
.....OntjllhhhlllljjjtttbbngGYYWWYGgO
......OntjllhhhlllljjjtttbbngGYYWWYGgO
.......OntjllhhhlllljjjtttbbngGYYWWYGgO
........OntjllhhhlllljjjtttbbngGYYWWYGgO
.........OntjllhhhlllljjjtttbbngGYYWWYGgO
..........OntjllhhhlllljjjtttbbngGYYWWYGgO
...........OntjllhhhlllljjjtttbbngGYYWWYGgO
............OntjllhhhlllljjjtttbbngGYYWWYGgO
.............OntjllhhhlllljjjtttbbngGYYWWYGgO
..............OntjllhhhlllljjjtttbbngGYYWWYGgO
...............OntjllhhhlllljjjtttbbngGYYWWYGgO
................OntjllhhhlllljjjtttbbngGYYWWYGgO
.................OntjllhhhlllljjjtttbbngGYYWWYGgO
..................OntjllhhhlllljjjtttbbngGYYWWYGgO
'''
HIT_HEAD='''
............OOOOOOOOOO
.........OOOntjjllllllnOO
.......OOntjllhhhhhhhlljjO
......OntjllhhhhhhlllllljjOO
.....OntjllhhhlllllhhhlllljtnOO
....OntjllhhllllllhhhhllllljttnOO
...OntjllhhllllllhhhhhlllllljjttnOOOO
..OntjllhhllllllhhlljjjjjlljjjjlllljnnO
.OntjllhhllllllhllgGGgglljjjllllhhhlljnO
OntjllhhllllllhllnOOOOlljjllllllhhhlljnO
OntjllhhllllllhlljjjjjlljjllltttjllOOjnO
OntjllhhllllllhllljjjlljjllttbbtjjjOnjnO
OntjllhhllllllhlllllljjjllttbbbtttjjjjnO
.OntjllhhllllllhlllljjjllttbbnnOOOOOOOO
.OntjllhhllllllhllljjllttbbnOmRRRRmmO
..OntjllhhllllllhlljjllttbbnOmRROWYOmO
...OntjllhhllllllhlljllttbbnOmRROWWOmO
....OntjllhhllllllhlllttbbnOmRRRROmO
.....OntjllhhllllllhllttbbnOgYYYYYgO
......OntjllhhllllllhllttbbnOgGYYYGGgO
.......OntjllhhllllllhllttbbnOgGGGGggO
........OntjllhhllllllhllttbbnOngggnO
.........OntjllhhllllllhllttbbnOOnOO
..........OntjllhhllllllhllttbbnO
'''
hit=lower();block(hit,34,51,HIT_NECK);block(hit,45,34,HIT_HEAD)
block(hit,22,39,'''.................OOOOO
.............OOOOnjhlO
.........OOOOnjllhllnO
.....OOOOnjllhhhlltnO
.OOOOnjllhhhhlljttnOO
OjllhhhlljjttnOOOO
.OjjlljjtnOOOO
..OOOOOO
''')
block(hit,23,49,'''...........OOOOO
.......OOOOnjhlO
...OOOOnjllhllnO
OOOnjllhhhlltnO
.OjllhhlljttnOO
..OOjjjtnOOO
....OOOOO
''')
patches(hit,[
(49,58,'gGGYYWWYYYGGg'),(47,59,'gGYYYWhllhWYYGGg'),(45,60,'gGYYWljjjlhYYGGg'),(44,61,'gGYYWljhllhYYGGg'),
(44,62,'ngGYYWhllhWYYGGg'),(45,63,'ngGGYYYYYYGGGg'),(46,64,'ngggGGGGGGggn'),
(47,68,'llhhhhllj'),(47,69,'jlllllljt'),(48,70,'tjjjjjttb'),(54,75,'lhhhllj'),(54,76,'jlllljt'),(55,77,'tjjjttb'),
(65,70,'gGGYYYYGg'),(69,77,'gGGYYYYGg'),
(82,48,'YYg'),(84,49,'YYg'),(86,50,'YYg'),(88,51,'YYg'),(90,52,'Yg'),(91,53,'g'),
(80,54,'YYg'),(82,56,'YYg'),(84,58,'YYg'),(86,59,'YYg'),(88,60,'Yg'),(89,61,'Yg'),(89,62,'g'),
(88,65,'gGGg'),(87,66,'gYWYG'),(87,67,'gWWYG'),(88,68,'gGGg'),
])
record('hit',hit)

# Deflated, open lower coil: the throat is lying on the ground and the eye is closed.
dead=blank()
block(dead,10,88,'''........OOOOOOOOOOOO
.....OOOnttjjjjjjjjnnOO
...OOntjjlllllhhhhllljtnOO
..OntjllhhhhhhhhhhlllljttnOOOOOOOOOOO
.OntjllhhhhhhllllllljjjttbbnnntttjjjnnOOOO
OntjllhhhhlllllljjjtttbbbbttjjllllhhhlljttnOOOO
OntjllhhhlllljjjtttbbbnnnttjjllllhhhhhhlljjttnOO
OntjllhhlllljjtttbbnnOOOntjjllllhhhhlllljjjttbbnOO
OntjllhhlllljjttbbnnO...OntjjllllhhlllljjtttbbnnOO
.OntjllhhlllljjttbbnnO...OntjjllllllljjtttbbnnOO
.OntjllhhlllljjtttbbnnO...OntjjlllljjtttbbnnOO
..OntjllhhhlllljjtttbbnnO...OntjjjjtttbbnnOO
...OntjllhhhhlllljjtttbbnnO...OnttttbbnnOO
....OntjllhhhhhlllljjtttbbnnOOOOOnnnOOOOOOOOOOOO
.....OntjllhhhhhhlllljjtttbbbbnnnnnntttjjjjjjjnnOOOO
......OntjllhhhhhhhhlllljjjttttttjjllllhhhhhhhlljjttnOO
.......OntjllhhhhhhhhhhlllljjjllllhhhhhhhhhhlllljjttbnOO
........OntjllhhhhhllllllljjllllhhhhhhhhhllllljjjttbbnOO
.........OntjllhhlllllljjjjjllllhhhhhllllllljjjtttbbnOO
..........OntjllhlllljjjttttjjllllllljjjjjjjtttbbnnOO
...........OntjlllljjtttbbbbttjjjjjjjtttttttbbnnOO
............OntjjjjtttbbbbnnnbbbbbbbbbbbbbbnnOO
.............OntttttbbbnnOOOOOOOOOOOOOOOOOOOO
..............OnbbbnnOO
...............OOOOOO
''')
block(dead,27,109,'''..........OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
.......OOOnntttjjjllllllllllllllllllllllltttbbbbnnnOOOO
.....OOnttjjllllhhhhhhhhhhhhhhhhhhhhhhhlllljjtttbbnnnOO
...OOnttjjllllhhhhhhhhhhlllllllllllllhhhhlllljjtttbbnnOO
..Onttjjllllhhhhhhlllllljjjjjjjjjjjjjjlllllll jjtttbbnnO
.OnttjjllllhhlllllljjjjtttttttttttttttjjjjjjjtttbbnnO
OnttjjllllhlllljjjjttttbbbbbbbbbbbbbbttttjjjtttbbnnO
OnttjjlllllljjjttttbbbbnnnnnnnnnnnnnnbbbttttbbnnO
.OngGGYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYGGGGGggnnO
..OgGYYYYWWWWWWWWWWWWWWWWWWYYYYYYYYYYYGGGGgnO
...OgGYYYYYWWWWWWWWWWWWWWYYYYYYYYYYYYGGGGgnO
....OgGGYYYYYYYYYYYYYYYYYYYYYYYYYYGGGGGgnO
.....OngGGGGYYYYYYYYYYYYYYYYYYYGGGGGgnO
......OnngGGGGGGGGGGGGGGGGGGGGGGggnnO
........OOnnggggggggggggggggggnnOO
...........OOOOOOOOOOOOOOOOOOO
'''.replace(' ','j'))
block(dead,81,96,'''........OOOOOOOOOO
.....OOOntjjllllllnOO
...OOntjllhhhhhhhlljjO
..OntjllhhhhhhlllllljjOO
.OntjllhhhlllllhhhlllljtnOO
OntjllhhllllllhhhhllllljttnOO
OntjllhhllllllhhhhhlllllljjttnOOO
OntjllhhllllllhhlljjjjjlljjjjlllljnO
OntjllhhllllllhllggggllljjjllllhhlljnO
OntjllhhllllllhllOOOOlljjlllllhhhlljnO
OntjllhhllllllhlljjjjlljjlllttjllOOjnO
.OntjllhhllllllhllljjlljjllttbtjjOnjnO
.OntjllhhllllllhlllllljjjllttbbbttjjjnO
..OntjllhhllllllhlllljjjllttbbnnOOOOOO
...OntjllhhllllllhllljjllttbbnOmRmmO
....OntjllhhllllllhlljjllttbbnOYWWYO
.....OntjllhhllllllhlljllttbbnOgYYGgO
......OntjllhhllllllhlllttbbnOgGGGgO
.......OntjllhhllllllhllttbbnOnggnO
........OntjllhhllllllhllttbbnOOnO
''')
block(dead,62,102,'''.............OOOOO
.........OOOOnjhlO
.....OOOOnjllhllnO
.OOOOnjllhhhlltnO
OjllhhhhlljttnOO
.OjjlljjtnOOOO
..OOOOOO
''')
patches(dead,[
(73,114,'gGGYYWWYYYGGg'),(72,115,'gGYYYWhllhWYYGGg'),(71,116,'gGYYWljjjlhYYGGg'),
(71,117,'gGYYWljhllhYYGGg'),(72,118,'ngGYYWhllhWYYGGg'),(73,119,'ngGGYYYYYYGGGg'),
(74,120,'ngggGGGGGGggn'),(116,111,'YYg'),(118,112,'YYg'),(120,113,'YYg'),(122,114,'g'),
(113,116,'YYg'),(115,117,'YYg'),(117,118,'YYg'),(119,118,'YYg'),(121,117,'g'),
(110,121,'gGGg'),(109,122,'gYWYG'),(109,123,'gWWYG'),(110,124,'gGGg'),
(24,99,'lhhhllj'),(24,100,'jlllljt'),(25,101,'tjjjttb'),(46,116,'gGGYYYYGg'),(59,118,'gGGYYYYGg'),
])
record('dead',dead)
# Skill preparation: raised jaw and throat pouch, with a compact pearl-born white core.
SKILL_A_HEAD='''
...............OOOOOOOOO
............OOOntjllllllnOO
..........OOntjllhhhhhhhlljO
.........OntjllhhhhhhlllllljnOO
........OntjllhhhllllhhhhhlljttnOO
.......OntjllhhlllllhhhhhhhlljtttnOOOOOO
......OntjllhhllllhhhhhhlllllljjjjlllljjnO
.....OntjllhhllllhhlljjjjjlljjjjllllhhlljnO
....OntjllhhllllhhllgGGgllljjjllllllhhlljnO
...OntjllhhllllhhllOWpOlljjjllllllljlllljnO
..OntjllhhllllhhllORROlljjlllllljttjllOOjnO
.OntjllhhllllhhlllOOOlljjllllljttbbjjjOnjnO
OntjllhhllllhhlllllljjjlllljjttbbbbttjjjnO
OntjllhhllllhhlllljjjlllljjttbbbbnnnnnnOO
OntjllhhllllhhllljjlllljjttbbnnOOOOOOOOO
.OntjllhhllllhhlljjlllljjttbbnOmRRWWYYWmO
.OntjllhhllllhhlljjlljjttbbnOmRROWWYYOmO
..OntjllhhllllhhlljjlljttbbnOmRRROWWOmO
...OntjllhhllllhhlljjllttbbnOmRRRRROmO
....OntjllhhllllhhlljjlttbbnOmRRRmmO
.....OntjllhhllllhhlljjttbbnOmRRmmO
......OntjllhhllllhhlljttbbnOWWYmO
.......OntjllhhllllhhllttbbnOYWYYO
........OntjllhhllllhhllttbbnOgYYYgO
.........OntjllhhllllhhllttbbnOgGGgO
...........OntjllhhllllhhllttbbnOOO
'''
skill_a=lower();block(skill_a,44,47,RECOVER_NECK);block(skill_a,73,27,SKILL_A_HEAD)
block(skill_a,50,34,'''.................OOOOOO
.............OOOOnjlhlO
.........OOOOnjllhhllnO
.....OOOOnjllhhhlljtnO
.OOOOnjllhhhhlljjttnOO
OjllhhhhlljjttnOOOO
.OjjlljjtnOOOO
..OOOOOO
''')
patches(skill_a,[
(70,55,'gGGYYWWYYYGGg'),(68,56,'gGYYYWhllhWYYGGg'),(66,57,'gGYYWljjjlhYYGGg'),(65,58,'gGYYWljhllhYYGGg'),
(65,59,'ngGYYWhllhWYYGGg'),(66,60,'ngGGYYYYYYGGGg'),(67,61,'ngggGGGGGGggn'),
(52,64,'llhhhhllj'),(52,65,'jlllllljt'),(53,66,'tjjjjjttb'),
(76,66,'gGGYYYYGg'),(78,72,'gGGYYYYGg'),(80,78,'gGGYYYYGg'),
(108,38,'YYg'),(110,37,'YYg'),(112,36,'YYg'),(114,35,'YYg'),(116,34,'Yg'),(117,33,'g'),
(106,49,'YYg'),(108,50,'YYg'),(110,51,'YYg'),(112,52,'YYg'),(114,53,'Yg'),(115,54,'Yg'),(115,55,'g'),
])
block(skill_a,103,42,'''......ggGGg
....gGYYWWYGg
...gYYWWWWYYGg
..gYYWWeeWWWYGg
.gYYWWeeeeWWWYGg
.gYWWWeeeeWWYYGg
.gYYWWWeeWWYYGGg
..gGYYWWWWYYGGg
...gGGYYYYGGGg
.....ggGGggg
''')
# Folded water segments collect at the jaw without a generic circular aura.
block(skill_a,111,56,'''....OOO
..OOtccO
.OtceecO
OtceecatO
OtcecatO
.OtcatO
..OOO
''')
block(skill_a,99,52,'''..OO
.OtcO
OtcecO
OtccatO
.OtcatO
..OOO
''')
record('skill_a',skill_a,True)

CAST_NECK='''
...................OOOOOOOOOOOO
................OOOntjjllllllnnOO
.............OOOntjllhhhhhhhlljttnO
..........OOOntjllhhhhhhhlllljjttbnO
........OOntjllhhhhhhlllljjjtttbbnO
......OOntjllhhhhhhlllljjjtttbbnnO
.....OntjllhhhhhhlllljjjtttbbnnO
....OntjllhhhhhhlllljjjtttbbnnO
...OntjllhhhhhhlllljjjtttbbngGO
..OntjllhhhhhhlllljjjtttbbngYYO
.OntjllhhhhhhlllljjjtttbbngYYWO
OntjllhhhhhhlllljjjtttbbngGYYWWO
OntjllhhhhhhlllljjjtttbbngGYYWWYO
OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
.OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
.OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
..OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
...OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
....OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
.....OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
......OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
.......OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
........OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
.........OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
..........OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
...........OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
............OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
'''
CAST_HEAD='''
..........OOOOOOOOOO
.......OOOntjjllllllnOO
.....OOntjllhhhhhhhlljjO
....OntjllhhhhhhlllllljjOO
...OntjllhhhlllllhhhlllljtnOO
..OntjllhhllllllhhhhllllljttnOO
.OntjllhhllllllhhhhhlllllljjttnOOOO
OntjllhhllllllhhlljjjjjlljjjjlllljnnO
OntjllhhllllllhllgGgllljjjllllhhhlljnO
OntjllhhllllllhllOWpOlljjlllllhhhlljnO
OntjllhhllllllhllORROlljjlllttjllOOjnO
OntjllhhllllllhlllOOOlljjllttbtjjOnjnO
OntjllhhllllllhlllllljjjllttbbbttjjjnO
.OntjllhhllllllhlllljjjllttbbnOOOOOOO
.OntjllhhllllllhllljjllttbbnOmRRWWYYO
..OntjllhhllllllhlljjllttbbnOmRROWYOO
...OntjllhhllllllhlljllttbbnOmRRROmO
....OntjllhhllllllhlllttbbnOmRRROmO
.....OntjllhhllllllhllttbbnOmRROmO
......OntjllhhllllllhllttbbnOmROmO
.......OntjllhhllllllhllttbbnOmROmO
........OntjllhhllllllhllttbbnOWWO
.........OntjllhhllllllhllttbbnOYYO
..........OntjllhhllllllhllttbbnOgGO
...........OntjllhhllllllhllttbbnOOO
'''
skill_b=lower();block(skill_b,35,58,CAST_NECK);block(skill_b,61,39,CAST_HEAD)
block(skill_b,40,44,'''..............OOOOO
..........OOOOnjhlO
......OOOOnjllhhlnO
..OOOOnjllhhhlltnO
OOjllhhhhlljttnOO
.OjjlljjtnOOOO
..OOOOOO
''')
block(skill_b,38,54,'''.............OOOOO
.........OOOOnjhlO
.....OOOOnjllhllnO
.OOOOnjllhhhlltnO
OjllhhhhlljttnOO
.OjjlljjtnOOOO
..OOOOOO
''')
patches(skill_b,[
(56,66,'gGGYYWWYYYGGg'),(54,67,'gGYYYWhllhWYYGGg'),(52,68,'gGYYWljjjlhYYGGg'),(51,69,'gGYYWljhllhYYGGg'),
(51,70,'ngGYYWhllhWYYGGg'),(52,71,'ngGGYYYYYYGGGg'),(53,72,'ngggGGGGGGggn'),
(45,75,'llhhhhllj'),(45,76,'jlllllljt'),(46,77,'tjjjjjttb'),(68,76,'gGGYYYYGg'),(72,82,'gGGYYYYGg'),
(90,48,'YYg'),(92,47,'YYg'),(94,46,'YYg'),(96,45,'YYg'),(98,44,'Yg'),(99,43,'g'),
(90,63,'YYg'),(92,65,'YYg'),(94,66,'YYg'),(96,67,'YYg'),(98,68,'Yg'),(99,69,'Yg'),
(88,67,'gGGg'),(87,68,'gYWYG'),(87,69,'gWWYG'),(88,70,'gGGg'),
])
# A connected mouth-origin jet turns up into an overcurl and down into a heavy second sheet.
# Every contour, white crest and dark water underplane below is a literal row.
block(skill_b,92,32,'''..........................OOO
.......................OOOtccO
....................OOOtceeeccO
..................OOtceeeeeccatO
................OOtceeeeccaaatO
...............OtceeeeccaaattO
..............OtceeeccaaattnO
.............OtceeeccaaattnO
............OtceeeccaaattnO
............OtceeeccaatnnO
...........OtceeeeccaatnnO
...........OtceeeccaaatnnO
..........OtceeeccaaattnO
.........OtceeeccaaattnO
........OtceeeccaaatnnO
......OOtceeeeccaatnnO
....OOtceeeeccaaatnnO
..OOtceeeeeeccaaattnO
.OtceeeeeeeccaaattnO
OtceeeeeeecccaaattnO
OceeeeeeeccccaaattnO
OeeeeeeccccaaaattnOO
OeeeeccccaaaattnnOOO
OeeecccaaaattnnOOttnOO
OeecccaaattnnOOttjccaO
OeccaaattnnOOttjceeccaO
OccaaattnOOttjceeeeeccaO
OcaattnOOttjceeeeeeccaaO
OattnnOttjceeeeeeccaaatO
OnnnOOttjceeeeeccaaattnO
.OOOOttjceeeeccaaatttnO
....OtjceeeeccaaatttnO
.....OtjceeeeccaaatttnO
......OtjceeeeccaaatttnO
.......OtjceeeeccaaatttnO
........OtjceeeeccaaatttnO
.........OtjceeeeccaaatttnO
..........OtjceeeeccaaatttnO
...........OtjceeeeccaaatttnO
............OtjceeeeeccaaattnO
.............OtjceeeeeccaaattnO
..............OtjceeeeeccaaattnO
...............OtjceeeeeeccaaatO
................OtjceeeeeccaatO
.................OtjceeeccaatnO
..................OtjcceccaatO
...................OtjcccaaatO
....................OtjccaatO
.....................OtjaatO
......................OttnO
.......................OOO
''')
# A turned, torn edge rather than more concentric light bands.
patches(skill_b,[(121,36,'cceO'),(120,37,'ceeaO'),(121,39,'ccaO'),(120,40,'aatO'),
(108,49,'ccceeecc'),(108,50,'aceeeecc'),(106,51,'aaaceecc'),
(99,56,'ccceeecc'),(100,57,'aacceec'),(102,58,'taacce'),
(116,68,'ceeecc'),(117,69,'cceec'),(118,70,'aacc'),
(121,80,'cceO'),(120,81,'ccaO'),(119,82,'aatO')])
record('skill_b',skill_b,True)

# Residual skill: throat lifted partway, jaw relaxing, water separates into falling curls.
skill_c=[r.copy() for r in recover]
patches(skill_c,[
(103,45,'OmRRRmmO'),(103,46,'OmROWYYO'),(103,47,'OmROWWYO'),(102,48,'OgYYYYgO'),
(101,49,'OgGYYGGgO'),(100,50,'OgGGGggO'),
(70,60,'gGWhlllWYGg'),(70,61,'gYlhllhYGg'),(71,62,'gGYYYYGg'),
(77,65,'ngGYYWWYGg'),(78,66,'ngGYYWWWYGg'),(79,67,'ngGYYWWYGg'),
(66,74,'llhhllj'),(66,75,'jlllljt'),(67,76,'tjjjttb'),
])
block(skill_c,107,65,'''......OOO
....OOtccO
...OtceecO
..OtceecatO
.OtceccaatO
OtccaaatnO
OtcaattnO
.OttnnOO
..OOOO
''')
block(skill_c,117,74,'''..OO
.OtcO
OtcecO
OtccatO
.OtcatO
..OOO
''')
block(skill_c,102,82,'''..OOO
.OtccO
OtceecO
OtccatO
.OtatO
..OOO
''')
block(skill_c,115,88,'''..OO
.OtcO
OtcecO
OtccatO
.OtcatO
..OOO
''')
record('skill_c',skill_c,True)
POISON_NECK='''
....................OOOOOOOOOOOO
................OOOOnntjjllllllnnOO
.............OOOntjllhhhhhhhlljttnO
..........OOOntjllhhhhhhhlllljjttbnO
........OOntjllhhhhhhlllljjjtttbbnO
......OOntjllhhhhhhlllljjjtttbbnnO
.....OntjllhhhhhhlllljjjtttbbnnO
....OntjllhhhhhhlllljjjtttbbnnO
...OntjllhhhhhhlllljjjtttbbngGO
..OntjllhhhhhhlllljjjtttbbngYYO
.OntjllhhhhhhlllljjjtttbbngYYWO
OntjllhhhhhhlllljjjtttbbngGYYWWO
OntjllhhhhhhlllljjjtttbbngGYYWWYO
OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
.OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
.OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
..OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
...OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
....OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
.....OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
......OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
.......OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
........OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
.........OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
..........OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
...........OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
............OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
.............OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
..............OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
'''
POISON_HEAD='''
............OOOOOOOOOO
.........OOOntjjllllllnOO
.......OOntjllhhhhhhhlljjO
......OntjllhhhhhhlllllljjOO
.....OntjllhhhlllllhhhlllljtnOO
....OntjllhhllllllhhhhllllljttnOO
...OntjllhhllllllhhhhhlllllljjttnOO
..OntjllhhllllllhhlljjjjjlljjjjlljnOO
.OntjllhhllllllhllgGGgglljjjllllhhlljnO
OntjllhhllllllhllnOOpOlljjlllllhhhlljnO
OntjllhhllllllhllljjjlljjlllttjlllllljnOO
OntjllhhllllllhlllljjlljjllttbtjjjllOOjnO
OntjllhhllllllhlllllljjjllttbbbttjllOnjnO
.OntjllhhllllllhlllljjjllttbbnntttjllljnO
.OntjllhhllllllhllljjllttbbnnOOOOnnnnnOO
..OntjllhhllllllhlljjllttbbnOmRRRRmmO
...OntjllhhllllllhlljllttbbnOmRRWWYYO
....OntjllhhllllllhlllttbbnOmROWWYYO
.....OntjllhhllllllhllttbbnOmRRROOO
......OntjllhhllllllhllttbbnOgYYYYgO
.......OntjllhhllllllhllttbbnOgGYYYGGgO
........OntjllhhllllllhllttbbnOgGGGGggO
.........OntjllhhllllllhllttbbnOngggnO
..........OntjllhhllllllhllttbbnOOnOO
...........OntjllhhllllllhllttbbnO
............OntjllhhllllllhllttbbnO
'''
poison_a=lower();block(poison_a,37,60,POISON_NECK);block(poison_a,66,47,POISON_HEAD)
block(poison_a,46,53,'''...............OOOOO
...........OOOOnjhlO
.......OOOOnjllhllnO
...OOOOnjllhhhlltnO
OOOnjllhhhhlljttnOO
.OjjlljjtnOOOO
..OOOOOO
''')
block(poison_a,43,62,'''.............OOOOO
.........OOOOnjhlO
.....OOOOnjllhllnO
.OOOOnjllhhhlltnO
OjllhhhhlljttnOO
.OjjlljjtnOOOO
..OOOOOO
''')
patches(poison_a,[
(61,72,'gGGYYWWYYYGGg'),(59,73,'gGYYYWhllhWYYGGg'),(57,74,'gGYYWljjjlhYYGGg'),(56,75,'gGYYWljhllhYYGGg'),
(56,76,'ngGYYWhllhWYYGGg'),(57,77,'ngGGYYYYYYGGGg'),(58,78,'ngggGGGGGGggn'),
(45,80,'llhhhhllj'),(45,81,'jlllllljt'),(46,82,'tjjjjjttb'),
(70,81,'gGGYYYYGg'),(75,87,'gGGYYYYGg'),
(99,60,'YYg'),(101,61,'YYg'),(103,62,'YYg'),(105,63,'YYg'),(107,64,'YYg'),(109,65,'Yg'),(110,66,'g'),
(98,67,'YYg'),(100,69,'YYg'),(102,71,'YYg'),(104,72,'YYg'),(106,73,'Yg'),(107,74,'Yg'),(107,75,'g'),
(104,77,'gGGg'),(103,78,'gYWYG'),(103,79,'gWWYG'),(104,80,'gGGg'),
(101,65,'tvvt'),(102,66,'tvvt'),(103,67,'tvn'),(102,68,'tn'),
])
# Toxic bubbles emerge from the strained jaw; they have oily jade/vine edges, not a tint overlay.
block(poison_a,111,54,'''..nnn
.nvWvn
nvWWvtn
nvvvttn
.ntttn
..nnn
''')
block(poison_a,104,44,'''..nn
.nWvn
nvWvtn
.nvtn
..nn
''')
block(poison_a,112,70,'''..nn
.nWvn
nvWvtn
nvvttn
.nttn
..nn
''')
record('poison_a',poison_a,True)
poison_b=[r.copy() for r in poison_a]
# A weary exhale narrows the lid and crumples throat/belly; the old bubble clusters are explicitly erased.
block(poison_b,111,54,'''.......
.......
.......
.......
.......
.......
''')
block(poison_b,104,44,'''......
......
......
......
......
''')
block(poison_b,112,70,'''......
......
......
......
......
......
''')
patches(poison_b,[
(81,55,'gGGgg'),(81,56,'nOOOO'),(82,57,'jjjj'),
(64,71,'gGYYYGGg'),(63,72,'gGYYYYGGg'),(63,73,'gGGYYYGGg'),
(44,81,'llhhhllj'),(44,82,'jllllljt'),(45,83,'tjjjjttb'),
(72,84,'gGYYWWYGg'),(73,85,'gGYYWWYGg'),(74,86,'gGYYYYGg'),
(99,66,'tvvtn'),(100,67,'tvvtn'),(101,68,'tvn'),(101,69,'tn'),
(104,79,'gYYYG'),(104,80,'gGGg'),
])
block(poison_b,111,43,'''..nnn
.nvWvn
nvWWvtn
nvvvttn
.ntttn
..nnn
''')
block(poison_b,119,62,'''..nn
.nWvn
nvWvtn
nvvttn
.nttn
..nn
''')
block(poison_b,108,72,'''..n
.nvn
nvWvn
.nvn
..n
''')
record('poison_b',poison_b,True)

STUN_NECK='''
................OOOOOOOOOOOO
............OOOOnntjjllllllnnOO
.........OOOntjllhhhhhhhlljttnO
.......OOntjllhhhhhhhlllljjttbnO
.....OOntjllhhhhhhlllljjjtttbbnO
....OntjllhhhhhhlllljjjtttbbnnO
...OntjllhhhhhhlllljjjtttbbnnO
..OntjllhhhhhhlllljjjtttbbngGO
.OntjllhhhhhhlllljjjtttbbngYYO
OntjllhhhhhhlllljjjtttbbngYYWO
OntjllhhhhhhlllljjjtttbbngGYYWWO
OntjllhhhhhhlllljjjtttbbngGYYWWYO
.OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
..OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
...OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
....OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
.....OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
......OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
.......OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
........OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
.........OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
..........OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
...........OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
............OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
.............OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
..............OntjllhhhhhhlllljjjtttbbngGYYWWYGgO
'''
STUN_HEAD='''
...........OOOOOOOOOO
........OOOntjjllllllnOO
......OOntjllhhhhhhhlljjO
.....OntjllhhhhhhlllllljjOO
....OntjllhhhlllllhhhlllljtnOO
...OntjllhhllllllhhhhllllljttnOO
..OntjllhhllllllhhhhhlllllljjttnOO
.OntjllhhllllllhhlljjjjjlljjjjlljnOO
OntjllhhllllllhllgGGgglljjjllllhhlljnO
OntjllhhllllllhllnOOOOlljjlllllhhhlljnO
OntjllhhllllllhllljjjlljjlllttjlllllljnOO
OntjllhhllllllhlllljjlljjllttbtjjjllOOjnO
.OntjllhhllllllhlllllljjjllttbbbttjllOnjnO
.OntjllhhllllllhlllljjjllttbbnntttjllljnO
..OntjllhhllllllhllljjllttbbnnOOOOnnnnnOO
..OntjllhhllllllhlljjllttbbnOmRRRRWWYO
...OntjllhhllllllhlljllttbbnOmRROWWYO
...OntjllhhllllllhlllttbbnOmRRROWWO
....OntjllhhllllllhllttbbnOmRRRROWO
....OntjllhhllllllhllttbbnOmRRRROO
.....OntjllhhllllllhllttbbnOmRRmmO
.....OntjllhhllllllhllttbbnOmRRmO
......OntjllhhllllllhllttbbnOmRmO
......OntjllhhllllllhllttbbnOYYmO
.......OntjllhhllllllhllttbbnOYYYgO
........OntjllhhllllllhllttbbnOGYYGgO
.........OntjllhhllllllhllttbbnOgGGgO
..........OntjllhhllllllhllttbbnOggO
...........OntjllhhllllllhllttbbnOOO
'''
stun_a=lower();block(stun_a,35,63,STUN_NECK);block(stun_a,56,46,STUN_HEAD)
block(stun_a,35,55,'''..............OOOOO
..........OOOOnjhlO
......OOOOnjllhhlnO
..OOOOnjllhhhlltnO
OOjllhhhhlljttnOO
.OjjlljjtnOOOO
..OOOOOO
''')
block(stun_a,31,65,'''.............OOOOO
.........OOOOnjhlO
.....OOOOnjllhllnO
.OOOOnjllhhhlltnO
OjllhhhhlljttnOO
.OjjlljjtnOOOO
..OOOOOO
''')
patches(stun_a,[
(57,73,'gGGYYWWYYYGGg'),(55,74,'gGYYYWhllhWYYGGg'),(53,75,'gGYYWljjjlhYYGGg'),(52,76,'gGYYWljhllhYYGGg'),
(52,77,'ngGYYWhllhWYYGGg'),(53,78,'ngGGYYYYYYGGGg'),(54,79,'ngggGGGGGGggn'),
(40,78,'llhhhhllj'),(40,79,'jlllllljt'),(41,80,'tjjjjjttb'),(68,83,'gGGYYYYGg'),
(90,58,'YYg'),(92,60,'YYg'),(94,61,'YYg'),(96,62,'YYg'),(98,63,'Yg'),(99,64,'g'),
(89,72,'YYg'),(90,74,'YYg'),(91,76,'YYg'),(92,78,'Yg'),(92,79,'Yg'),(91,80,'g'),
(91,83,'gGGg'),(90,84,'gYWYG'),(90,85,'gWWYG'),(91,86,'gGGg'),
])
# Individually drawn small four-point golden stars, with different proportions.
block(stun_a,52,34,'''..g
..Y
.gWYg
YYWWWYY
.gWYg
..Y
..g
''')
block(stun_a,81,29,'''...g
...Y
..gWg
.gWWWg
YYWWWYY
..gWg
...Y
...g
''')
block(stun_a,102,41,'''..g
.gWg
YYWYY
.gWg
..g
''')
record('stun_a',stun_a,True)
stun_b=[r.copy() for r in stun_a]
block(stun_b,52,34,'''.......
.......
.......
.......
.......
.......
.......
''')
block(stun_b,81,29,'''.......
.......
.......
.......
.......
.......
.......
.......
''')
block(stun_b,102,41,'''.....
.....
.....
.....
.....
''')
patches(stun_b,[
(72,54,'gGGgg'),(72,55,'nOOOn'),(73,56,'tjjj'),
(90,68,'OmRRmmO'),(90,69,'OmRRmmO'),(91,70,'OmRmO'),(91,71,'OYYmO'),
(92,72,'OYYgO'),(93,73,'OGGgO'),(94,74,'OggO'),
(46,81,'llhhhllj'),(46,82,'jllllljt'),(47,83,'tjjjjttb'),
(66,83,'gGYYWWYGg'),(67,84,'gGYYWWYGg'),(68,85,'gGYYYYGg'),
(90,84,'gYYYG'),(90,85,'gYWYG'),
])
block(stun_b,63,28,'''..g
..Y
.gWYg
YYWWWYY
.gWYg
..Y
..g
''')
block(stun_b,95,32,'''...g
...Y
..gWg
.gWWWg
YYWWWYY
..gWg
...Y
...g
''')
block(stun_b,43,46,'''..g
.gWg
YYWYY
.gWg
..g
''')
record('stun_b',stun_b,True)

# Sleep: low tucked head resting across the coil, a broad relaxed throat, no upright neck.
sleep_a=blank()
for y in range(80,125): sleep_a[y]=base[y].copy()
block(sleep_a,18,74,'''........OOOOOOOOOO
.....OOOnttjjlllljnnOO
...OOntjllhhhhhhlljttnOO
..OntjllhhhhhhhhlllljttbnOO
.OntjllhhhhhlllllljjjttbbnOO
OntjllhhhhlllllljjjtttbbnnOO
OntjllhhlllljjjtttbbnnOOOO
OntjllhlllljjtttbbnnOO
.OntjlllljjtttbbnnOO
..OntjjjjttbbnnOO
...OntttbbnnOO
....OnnnOOO
.....OOOO
''')
block(sleep_a,64,93,'''..............OOOOOOOOOO
..........OOOOnnttjjllllnnOO
.......OOOntjllhhhhhhhlljttnO
.....OOntjllhhhhhhhhhllljjttbnO
...OOntjllhhhhhhlllllljjjtttbbnO
..OntjllhhhhhhllllljjjtttbbnnOO
.OntjllhhhhhlllljjjtttbbnnOO
OntjllhhhhlllljjjtttbbnnOO
OntjllhhhlllljjjtttbbnnO
OntjllhhlllljjjtttbbngGO
OntjllhhlllljjjtttbbngYYO
OntjllhhlllljjjtttbbngYYWO
.OntjllhhlllljjjtttbbngGYYWWO
..OntjllhhlllljjjtttbbngGYYWWYO
...OntjllhhlllljjjtttbbngGYYWWYGgO
....OntjllhhlllljjjtttbbngGYYWWYGgO
.....OntjllhhlllljjjtttbbngGYYWWYGgO
......OntjllhhlllljjjtttbbngGYYWWYGgO
.......OntjllhhlllljjjtttbbngGYYWWYGgO
........OntjllhhlllljjjtttbbngGYYWWYGgO
.........OntjllhhlllljjjtttbbngGYYWWYGgO
..........OntjllhhlllljjjtttbbngGYYWWYGgO
''')
SLEEP_HEAD='''
..............OOOOOOOOOO
...........OOOntjjllllllnOO
.........OOntjllhhhhhhhlljjO
........OntjllhhhhhhlllllljjOO
.......OntjllhhhlllllhhhlllljtnOO
......OntjllhhllllllhhhhllllljttnOO
.....OntjllhhllllllhhhhhlllllljjttnOOOOOO
....OntjllhhllllllhhlljjjjjlljjjjlllllljnnO
...OntjllhhllllllhllgGGgglljjjllllhhhhlljnO
..OntjllhhllllllhllnOOOOlljjllllllhhhhlljnO
.OntjllhhllllllhllljjjjlljjllltttjlllllljnO
OntjllhhllllllhlllljjjlljjllttbbtjjjllOOjnO
OntjllhhllllllhlllllljjjllttbbbbttjllOnlljnO
OntjllhhllllllhlllljjjllttbbnnnttjjlllljnO
.OntjllhhllllllhllljjllttbbnnOOOOOnnnnnOO
.OntjllhhllllllhlljjllttbbnOmRRmmOO
..OntjllhhllllllhlljllttbbnOgYYYYgO
...OntjllhhllllllhlllttbbnOgGYYYGGgO
....OntjllhhllllllhllttbbnOgGGGGggO
.....OntjllhhllllllhllttbbnOngggnO
......OntjllhhllllllhllttbbnOOnOO
.......OntjllhhllllllhllttbbnO
........OntjllhhllllllhllttbbnO
'''
block(sleep_a,44,85,SLEEP_HEAD)
block(sleep_a,26,93,'''.............OOOOO
.........OOOOnjhlO
.....OOOOnjllhllnO
.OOOOnjllhhhlltnO
OjllhhhhlljttnOO
.OjjlljjtnOOOO
..OOOOOO
''')
patches(sleep_a,[
(67,107,'gGGYYWWYYYGGg'),(66,108,'gGYYYWhllhWYYGGg'),(65,109,'gGYYWljjjlhYYGGg'),(65,110,'gGYYWljhllhYYGGg'),
(66,111,'ngGYYWhllhWYYGGg'),(67,112,'ngGGYYYYYYGGGg'),(68,113,'ngggGGGGGGggn'),
(73,96,'llhhhllj'),(73,97,'jllllljt'),(74,98,'tjjjjttb'),
(80,111,'gGGYYYYGg'),(83,117,'gGGYYYYGg'),
(81,99,'YYg'),(83,100,'YYg'),(85,101,'YYg'),(87,102,'YYg'),(89,103,'Yg'),(90,104,'g'),
(79,104,'YYg'),(81,106,'YYg'),(83,107,'YYg'),(85,108,'YYg'),(87,109,'Yg'),(88,110,'Yg'),(88,111,'g'),
(88,114,'gGGg'),(87,115,'gYWYG'),(87,116,'gWWYG'),(88,117,'gGGg'),
])
record('sleep_a',sleep_a,True)
sleep_b=[r.copy() for r in sleep_a]
patches(sleep_b,[
(78,106,'ngGYYWWYGg'),(79,107,'ngGYYWWWYGg'),(80,108,'ngGYYWWWYGg'),
(81,109,'ngGYYWWYGg'),(82,110,'ngGYYYYGg'),(83,111,'nggGGGgn'),
(62,100,'llhhhllj'),(62,101,'jllllljt'),(63,102,'tjjjjttb'),
(61,94,'gGGgg'),(61,95,'nOOOO'),(62,96,'jjjj'),
(38,110,'llhhhlljj'),(39,111,'jlllllljt'),(40,112,'tjjjjjttb'),
(26,80,'llhhhhllj'),(26,81,'jlllllljt'),(27,82,'tjjjjjttb'),
(85,108,'YYg'),(87,109,'YYg'),(89,110,'Yg'),(89,111,'g'),
(87,115,'gYYYG'),(87,116,'gWWYG'),
])
record('sleep_b',sleep_b,True)
# Final anatomical joins: chosen native rows turn the long throat into the upper coil.
# Right-padding here only clears the former truncated contour at these explicitly authored rows.
IDLE_JOIN='''
...............OntjllhhhlllljjttbbngGYYYGgO
.............OntjllhhhhlllljjjttbbngGYYYGgO
...........OntjllhhhhhlllljjjttbbngGYYYGgO
.........OntjllhhhhhhlllljjjttbbngGYYYGgO
.......OntjllhhhhhhlllljjjtttbbngGYYGgO
.....OntjllhhhhhhlllljjjtttbbngGYYGgO
...OntjllhhhhhhlllljjjtttbbngGYYGgO
..OntjllhhhhhhlllljjjtttbbngGYYGgO
.OntjllhhhhhllllljjjtttbbbngGGGgO
OntjllhhhhlllllljjjttttbbbnnnggO
'''
WIND_JOIN='''
...............OntjllhhhhlllljjjttbbngGYYYGgO
.............OntjllhhhhhlllljjjttbbngGYYYGgO
...........OntjllhhhhhhlllljjjttbbngGYYYGgO
.........OntjllhhhhhhhlllljjjttbbngGYYYGgO
.......OntjllhhhhhhhlllljjjtttbbngGYYGgO
.....OntjllhhhhhhhlllljjjtttbbngGYYGgO
...OntjllhhhhhhllllljjjtttbbngGYYGgO
..OntjllhhhhhlllllljjjtttbbngGYYGgO
.OntjllhhhhlllllljjjttttbbbngGGGgO
OntjllhhhlllllljjjttttbbbbnnnggO
'''
MOVE_JOIN='''
..OntjllhhhhhhhhlllllljjjtttbbnnO
..OntjllhhhhhhhlllllljjjttttbbnnO
..OntjllhhhhhhlllllljjjttttbbnnO
..OntjllhhhhhlllllljjjttttbbnnO
..OntjllhhhhlllllljjjttttbbnnO
..OntjllhhhlllllljjjttttbbnnO
..OntjllhhlllllljjjttttbbnnO
..OntjllhlllllljjjttttbbnnO
.Ontjlllllll jjjttttbbbnnO
OntjlllllljjjttttbbbnnO
'''.replace(' ','j')
RECOVER_JOIN='''
.......OntjllhhhhlllljjjttbbngGYYYGgO
......OntjllhhhhhlllljjjttbbngGYYYGgO
.....OntjllhhhhhhlllljjjttbbngGYYYGgO
....OntjllhhhhhhllllljjjttbbngGYYYGgO
...OntjllhhhhhhllllljjjtttbbngGYYGgO
..OntjllhhhhhhllllljjjtttbbngGYYGgO
.OntjllhhhhhlllllljjjtttbbngGYYGgO
OntjllhhhhlllllljjjttttbbngGYYGgO
OntjllhhhlllllljjjttttbbbngGGGgO
OntjllhhlllllljjjttttbbbbnnnggO
'''

def joined(c,x,y,rows,width):
    # Explicitly chosen row strings; the only generated characters are transparent padding.
    block(c,x,y,'\n'.join(row.ljust(width,'.') for row in rows.strip('\n').splitlines()))
for c in (base,idle_b,idle_c): joined(c,48,76,IDLE_JOIN,61)
joined(windup,48,76,WIND_JOIN,61)
for c in (move,attack): joined(c,48,76,MOVE_JOIN,61)
for c in (recover,skill_a,skill_c): joined(c,48,76,RECOVER_JOIN,61)
joined(hit,46,76,RECOVER_JOIN,63)
# Status throats relax into the SAME actual coil rather than leaving a hanging diagonal edge.
STATUS_JOIN='''
.......OntjllhhhhlllljjjttbbngGYYGgO
......OntjllhhhhhlllljjjttbbngGYYGgO
.....OntjllhhhhhhlllljjjttbbngGYYGgO
....OntjllhhhhhlllllljjjtttbbngYYGgO
...OntjllhhhhlllllljjjttttbbngYYGgO
..OntjllhhhlllllljjjttttbbbngGGgO
.OntjllhhlllllljjjttttbbbnnnggO
OntjllhlllllljjjttttbbbbnnnOO
'''
for c in (poison_a,poison_b): joined(c,46,82,STATUS_JOIN,50)
for c in (stun_a,stun_b): joined(c,45,81,STATUS_JOIN,51)
joined(skill_b,44,78,RECOVER_JOIN,44)
# Separate collars and facial ridges have large jade/gold clusters and material-specific dark edges.
patches(base,[(58,44,'gYYWhhhhWYYg'),(58,45,'gYWljjjlhWYG'),(59,46,'gYWljhlhWYG'),(60,47,'gYYWhlhWYG'),
(87,24,'gYYYGGg'),(87,25,'gGGgg'),(88,26,'OOpO'),(88,27,'ORRO'),
(96,21,'jlhhhhhll'),(97,22,'jllhhhhll'),(98,23,'tjjlllljt')])
for c in (idle_b,idle_c): patches(c,[(58,44,'gYYWhhhhWYYg'),(58,45,'gYWljjjlhWYG'),(59,46,'gYWljhlhWYG'),(60,47,'gYYWhlhWYG')])
# Mane roots: short thick jade roots physically connect each backward flowing leaf to skin.
for c in (base,idle_b,idle_c): patches(c,[(61,25,'tjjllj'),(60,26,'tjllj'),(60,27,'tjjl'),(58,34,'tjlljj'),(58,35,'tjjllj'),(55,43,'tjllj')])
patches(windup,[(40,35,'tjllllj'),(39,36,'tjjllj'),(38,37,'btjjj'),(34,45,'tjjllj'),(34,46,'tjllj'),
(48,66,'lhhhhllj'),(48,67,'jllllljt'),(49,68,'tjjjjttb'),
(30,81,'OOnnttjjllhhhlljjtt'),(31,82,'ntjllhhhhhhlljjtt'),(33,83,'tjllhhhhlllljjtt')])
patches(move,[(86,47,'tjlljj'),(85,48,'tjjllj'),(85,49,'tjjlj'),(81,55,'tjllj'),
(69,58,'lhhhllj'),(69,59,'jlllljt'),(70,60,'tjjjttb'),(53,69,'lhhhhllj'),(53,70,'jllllljt'),(54,71,'tjjjjttb')])
patches(attack,[(82,49,'tjjllllj'),(82,50,'tjjllllj'),(81,51,'tjjlllj'),(81,52,'btjjj'),
(76,57,'tjllj'),(76,58,'tjjl'),(66,62,'lhhhllj'),(66,63,'jlllljt'),(67,64,'tjjjttb'),
(49,70,'lhhhhllj'),(49,71,'jllllljt'),(50,72,'tjjjjttb')])
for c in (recover,skill_a,skill_c): patches(c,[(69,37,'tjjlllj'),(68,38,'tjllllj'),(67,39,'tjjllj'),
(64,47,'tjjllj'),(64,48,'tjllj'),(56,66,'lhhhhllj'),(56,67,'jllllljt'),(57,68,'tjjjjttb')])
patches(hit,[(41,41,'tjjlllj'),(40,42,'tjllllj'),(39,43,'tjjllj'),(37,50,'tjllj'),(37,51,'tjjl'),
(43,67,'lhhhhllj'),(43,68,'jllllljt'),(44,69,'tjjjjttb')])
for c in (poison_a,poison_b): patches(c,[(64,55,'tjjllllj'),(63,56,'tjllllj'),(63,57,'tjjllj'),(59,63,'tjlljj'),(58,64,'tjllj'),
(55,79,'lhhhllj'),(55,80,'jlllljt'),(56,81,'tjjjttb')])
for c in (stun_a,stun_b): patches(c,[(54,57,'tjjllllj'),(53,58,'tjllllj'),(52,59,'tjjllj'),(49,67,'tjlljj'),(48,68,'tjllj'),
(57,82,'lhhhllj'),(57,83,'jlllljt'),(58,84,'tjjjttb')])
patches(skill_b,[(59,46,'tjllllj'),(58,47,'tjjllj'),(58,48,'tjjlj'),(55,55,'tjlljj'),(54,56,'tjllj'),
(47,76,'lhhhhllj'),(47,77,'jllllljt'),(48,78,'tjjjjttb')])
patches(dead,[(79,104,'tjllllj'),(78,105,'tjjllj'),(77,106,'tjjlj')])
for c in (sleep_a,sleep_b):patches(c,[(43,95,'tjllllj'),(42,96,'tjjllj'),(41,97,'tjjlj')])
# Explicit large scale facets follow each anatomical bend, not a tiled stripe algorithm.
for c in (base,idle_b,idle_c): patches(c,[(52,83,'lhhhhllj'),(52,84,'jllllljt'),(53,85,'tjjjjttb')])
patches(windup,[(59,80,'lhhhhllj'),(59,81,'jllllljt'),(60,82,'tjjjjttb')])
for c in (move,attack): patches(c,[(56,79,'lhhhllj'),(56,80,'jlllljt'),(57,81,'tjjjttb')])
for c in (recover,skill_a,skill_c):patches(c,[(56,80,'lhhhllj'),(56,81,'jlllljt'),(57,82,'tjjjttb')])
# Preserve the separately authored breaths after joins replaced a shared belly area.
patches(idle_b,[(67,79,'gGYYWWYGg'),(65,80,'gGYYWWWYGg'),(63,81,'gGYYWWYGg')])
patches(idle_c,[(53,83,'lhhhllj'),(53,84,'jlllljt'),(54,85,'tjjjttb')])
patches(poison_b,[(64,84,'gGYYWWYGg'),(63,85,'gGYYWWYGg'),(62,86,'gGYYYYGg')])
patches(stun_b,[(62,83,'gGYYWWYGg'),(61,84,'gGYYWWYGg'),(60,85,'gGYYYYGg')])
# Sleep cheek curls are weight-bearing against the coil; trim the sharp throat end by hand.
for c in (sleep_a,sleep_b):
    block(c,82,112,'''tjllhhhlljjttbbngGYYYGgO
jllhhhlljjttbbngGYYYGgO
llhhhlljjttbbngGYYYGgO
llhhlljjttbbngGYYYGgO
lhhlljjttbbngGYYYGgO
hhlljjttbbngGYYYGgO
hlljjttbbngGYYGgO
lljjttbbngGYYGgO
ljjttbbngGYYGgO
jjttbbngGGGgO
''')
# Re-save all full literal grids after the selected final clusters.
for n,c in [('idle_a',base),('idle_b',idle_b),('idle_c',idle_c),('windup',windup),('move',move),('attack',attack),('recover',recover),('hit',hit),('dead',dead)]:record(n,c)
for n,c in [('skill_a',skill_a),('skill_b',skill_b),('skill_c',skill_c),('poison_a',poison_a),('poison_b',poison_b),('stun_a',stun_a),('stun_b',stun_b),('sleep_a',sleep_a),('sleep_b',sleep_b)]:record(n,c,True)
png(base,ROOT/'progress/idle.png');png(base,ROOT/'progress/idle-4x.png',4)
# Rounded throat return replaces the sharp initial elbow. Each row is hand-selected.
ROUND_RETURN='''
.................OntjllhhhhlllljjttbbngGYYGgO
...............OntjllhhhhhhlllljjttbbngGYYYGgO
.............OntjllhhhhhhhhlllljjttbbngGYYYGgO
...........OntjllhhhhhhhhhhlllljjttbbngGYYYGgO
.........OntjllhhhhhhhhhhhhlllljjttbbngGYYYGgO
........OntjllhhhhhhhhhhhllllljjttbbngGYYYGgO
.......OntjllhhhhhhhhhhlllllljjttbbngGYYYGgO
......OntjllhhhhhhhhlllllljjjttbbngGYYGgO
.....OntjllhhhhhhlllllljjjtttbbngGYYGgO
....OntjllhhhhlllllljjjtttbbngGYYGgO
...OntjllhhlllllljjjttttbbngGGGgO
..OntjllllllljjjttttbbbbnnnggO
'''
for c in (base,idle_b,idle_c,windup):joined(c,44,75,ROUND_RETURN,65)
# Retain three clearly different chest breaths while avoiding a rectangular patch of gold.
patches(idle_b,[(68,54,'ngGYYWWYGg'),(67,55,'ngGYYWWYGg'),(67,56,'ngGYYWYGg'),
(67,57,'ngGYYWYGg'),(67,58,'ngGYYYYGg'),(67,59,'ngGGYYGg'),
(67,60,'ngGYYWWYGg'),(67,61,'ngGYYWWYGg'),(67,62,'ngGYYWYGg'),
(67,63,'ngGYYYGg'),(67,64,'ngGGYGg'),(67,65,'ngGYYWWYGg'),
(67,66,'ngGYYWWYGg'),(68,67,'ngGYYWYGg'),(69,68,'ngGYYYGg'),
(70,69,'ngGGYGg'),(71,70,'ngGYYWYGg'),(72,71,'ngGYYYGg')])
patches(idle_c,[(50,82,'llhhhhlll'),(51,83,'jlllllljt'),(52,84,'tjjjjjttb')])
# Rounded resting throat: the lower jaw weight is borne by this curled body section.
SLEEP_RETURN='''
ntjllhhhlljjttbbngGYYYGgO
OntjllhhhlljjttbbngGYYGgO
.OntjllhhhlljjttbbngGYYGgO
..OntjllhhhlljjttbbngGYYGgO
..OntjllhhlljjttbbngGYYGgO
..OntjllhlljjttbbngGYYGgO
..OntjlllljjttbbngGYYGgO
.OntjlljjttbbngGYYGgO
OntjjjttbbngGYYGgO
OntttbbngGGGgO
OnbbnnngggnO
OnnnOOOOO
'''
for c in (sleep_a,sleep_b):joined(c,82,112,SLEEP_RETURN,26)
# Readable large scale cells: lit jade faces, broad blue lower facets, selected scalloped edges.
COIL_FACETS=[
(14,93,'llhhhhllj'),(13,94,'llhhhhhllj'),(13,95,'jllllllljt'),(14,96,'tjjlllljtb'),(15,97,'bbtjjjttbn'),
(16,98,'nbbbttbbn'),
(23,103,'llhhhhllj'),(23,104,'jlllllljt'),(24,105,'tjjlllljtb'),(25,106,'bbtjjjttbn'),(26,107,'nbbbttbbn'),
(39,110,'llhhhhhhllj'),(39,111,'jlllllllljt'),(40,112,'tjjllllljtb'),(41,113,'bbtjjjjttbn'),(42,114,'nbbbtttbbn'),
(61,111,'llhhhhhllj'),(61,112,'jllllllljt'),(62,113,'tjjlllljtb'),(63,114,'bbtjjjttbn'),
(86,99,'llhhhhllj'),(86,100,'jlllllljt'),(87,101,'tjjllljtb'),(87,102,'bbtjjttbn'),(87,103,'nbbbtbbn'),
(76,89,'llhhhhllj'),(77,90,'jlllllljt'),(78,91,'tjjllljtb'),(79,92,'bbtjjttbn'),(80,93,'nbbbtbbn'),
]
for c in (base,idle_b,idle_c,windup,move,attack,recover,hit,skill_a,skill_b,skill_c,poison_a,poison_b,stun_a,stun_b):patches(c,COIL_FACETS)
for c in (sleep_a,sleep_b):patches(c,COIL_FACETS[:17])
# Neck plates explicitly follow each bend; no repeated grid or stripes.
for c in (base,idle_b,idle_c):patches(c,[
(55,55,'llhhhllj'),(54,56,'llhhhhllj'),(54,57,'jlllllljt'),(55,58,'tjjllljtb'),(56,59,'bbtjjttbn'),
(57,60,'nbbbtbbn'),(59,66,'llhhhhllj'),(60,67,'jlllllljt'),(61,68,'tjjllljtb'),(62,69,'bbtjjttbn'),
(63,70,'nbbbtbbn'),(55,79,'llhhhhhllj'),(54,80,'jllllllljt'),(53,81,'tjjlllljtb'),(52,82,'bbtjjjttbn'),
(88,25,'gGGgg'),(88,26,'OWpOn'),(88,27,'ORROn')])
patches(windup,[
(36,56,'llhhhllj'),(36,57,'jllllljt'),(37,58,'tjjlljtb'),(38,59,'bbtjttbn'),(39,60,'nbbbtbn'),
(48,68,'llhhhhllj'),(49,69,'jlllllljt'),(50,70,'tjjllljtb'),(51,71,'bbtjjttbn'),
(61,78,'llhhhhhllj'),(60,79,'jllllllljt'),(59,80,'tjjlllljtb'),(58,81,'bbtjjjttbn')])
for c in (move,attack):patches(c,[
(65,61,'llhhhhhllj'),(65,62,'jllllllljt'),(64,63,'tjjlllljtb'),(63,64,'bbtjjjttbn'),
(52,69,'llhhhhllj'),(52,70,'jlllllljt'),(53,71,'tjjllljtb'),(54,72,'bbtjjttbn'),
(55,78,'llhhhllj'),(55,79,'jllllljt'),(56,80,'tjjlljtb'),(57,81,'bbtjttbn')])
for c in (recover,skill_a,skill_c):patches(c,[
(57,64,'llhhhllj'),(57,65,'jllllljt'),(58,66,'tjjlljtb'),(59,67,'bbtjttbn'),
(61,73,'llhhhhllj'),(62,74,'jlllllljt'),(63,75,'tjjllljtb'),(64,76,'bbtjjttbn')])
patches(hit,[(41,66,'llhhhllj'),(41,67,'jllllljt'),(42,68,'tjjlljtb'),(43,69,'bbtjttbn'),
(50,74,'llhhhhllj'),(51,75,'jlllllljt'),(52,76,'tjjllljtb'),(53,77,'bbtjjttbn')])
for c in (poison_a,poison_b):patches(c,[(45,77,'llhhhllj'),(45,78,'jllllljt'),(46,79,'tjjlljtb'),(47,80,'bbtjttbn'),
(56,83,'llhhhhllj'),(55,84,'jlllllljt'),(54,85,'tjjllljtb'),(53,86,'bbtjjttbn')])
for c in (stun_a,stun_b):patches(c,[(39,73,'llhhhllj'),(39,74,'jllllljt'),(40,75,'tjjlljtb'),(41,76,'bbtjttbn'),
(55,82,'llhhhhllj'),(54,83,'jlllllljt'),(53,84,'tjjllljtb'),(52,85,'bbtjjttbn')])
patches(skill_b,[(39,72,'llhhhllj'),(39,73,'jllllljt'),(40,74,'tjjlljtb'),(41,75,'bbtjttbn'),
(55,81,'llhhhhllj'),(56,82,'jlllllljt'),(57,83,'tjjllljtb'),(58,84,'bbtjjttbn')])
patches(dead,[(16,94,'llhhhhhllj'),(16,95,'jllllllljt'),(17,96,'tjjlllljtb'),(18,97,'bbtjjjttbn'),
(41,111,'llhhhhhhllj'),(41,112,'jlllllllljt'),(42,113,'tjjllllljtb'),(43,114,'bbtjjjjttbn')])
# Water has thick curling lobes and subordinate white crests, not straight icy shafts.
block(skill_b,111,28,'''........OOOO
.....OOOtcccO
...OOtceeeccaO
..OtceeeeccatO
.OtceeeeccaattO
OtceeeccaaattnO
OtceeccaattnOO
OtccecaatnOO
OtcccaatnO
.OttaatnO
..OnnnOO
...OOO
''')
block(skill_b,107,73,'''......OtjccccaattO
.....OtjceeccaattO
....OtjceecccaaatnO
...OtjceeeeccaaattnO
..OtjceeeeccaaattnnO
.OtjceeeeccaaatnnOO
OtjceeeccaaatnnOO
OtjceccaaattnnOO
OttccaaattnnOO
.OttaaattnnOO
..OnttattnOO
...OnnnOOO
....OOOO
''')
patches(skill_b,[
(108,44,'ccceccaat'),(108,45,'cceccaaat'),(107,46,'cceccaatt'),
(105,47,'ccceeccaat'),(104,48,'ccceeeccaat'),(102,49,'cccceeeccaat'),
(100,50,'cccceeeeccaat'),(99,51,'cccceeeeccaat'),(97,52,'cccceeeeccaat'),
(95,53,'ccceeecccaaat'),(94,54,'cceeeccccaat'),(94,55,'cceeecccaat'),
(104,60,'jcccecccaa'),(105,61,'jccceeccaa'),(106,62,'jccceeccaa'),
(108,63,'jccceeccaa'),(109,64,'jccceeccaa'),(110,65,'jccceeccaa'),
(110,66,'jccceeeccaa'),(111,67,'jccceeeccaa'),(112,68,'jccceeeccaa'),
(114,69,'jccceeecca'),(115,70,'jccceecca'),(115,71,'jccceecca'),
])
# Two slim subordinate spray curls on the dark underplane.
patches(skill_b,[(115,48,'jccaO'),(116,49,'jcaaO'),(117,50,'jtaaO'),(118,51,'nttO'),
(100,74,'tccaO'),(101,75,'tceaO'),(102,76,'tccaO'),(103,77,'ttnO')])
for n,c in [('idle_a',base),('idle_b',idle_b),('idle_c',idle_c),('windup',windup),('move',move),('attack',attack),('recover',recover),('hit',hit),('dead',dead)]:record(n,c)
for n,c in [('skill_a',skill_a),('skill_b',skill_b),('skill_c',skill_c),('poison_a',poison_a),('poison_b',poison_b),('stun_a',stun_a),('stun_b',stun_b),('sleep_a',sleep_a),('sleep_b',sleep_b)]:record(n,c,True)
png(base,ROOT/'progress/idle.png');png(base,ROOT/'progress/idle-4x.png',4)
# Final reviewer correction: keep the idle scale faces while breathing only the ventral contour.
block(idle_b,65,54,'''jjlhljgO..........
tjlljtgO..........
btjjtbgO..........
YYWWWYGgO.........
YYWWWYGgO.........
GYgGGYYYYGg.......
GYYWWWYGgO........
lhljWWWYGgO.......
jljtWWWYGgO.......
tttbYYWWYGgO......
ngGYYWWWYGgO......
bngGGYYYYGgO......
lljGYYWWWYGgO.....
lljtGYYWWYGgO.....
lljtbYYWWYGgO.....
jjttbnYYWWYGgO....
bbtbbnlhlljYGgO...
lljjbtjlljtYGggO..
hlljbbtjjtbWWYGgO.
''')
patches(idle_c,[(88,26,'nOOOn'),(88,27,'tjllj')])
# The two attack whiskers bend back INSIDE the cell. They retain independent muzzle/jaw roots.
# Old trailing tip and pearl pixels are erased only at these selected runs.
patches(attack,[(113,71,'...'),(115,73,'...'),(117,74,'...'),(119,75,'.....'),(123,74,'.'),
(117,80,'....'),(116,81,'.....'),(116,82,'.....'),(117,83,'....')])
patches(attack,[
(120,52,'YYg'),(122,53,'YYg'),(123,54,'YYg'),(124,55,'Yg'),(124,56,'Yg'),
(124,57,'Yg'),(124,58,'Yg'),(123,59,'Yg'),(122,60,'YYg'),(121,61,'YYg'),
(119,62,'YYg'),(117,63,'YYg'),(115,64,'YYg'),(113,65,'YYg'),(111,66,'YYg'),
(109,67,'Yg'),(108,68,'g'),
(120,70,'YYg'),(122,71,'YYg'),(123,72,'YYg'),(124,73,'Yg'),(124,74,'Yg'),
(123,75,'YYg'),(121,76,'YYg'),(119,77,'YYg'),(117,78,'YYg'),(115,79,'YYg'),
(113,80,'YYg'),(111,81,'YYg'),(109,82,'YYg'),(107,83,'Yg'),(106,84,'g'),
(113,84,'gGGg'),(112,85,'gYWYG'),(112,86,'gWWYG'),(113,87,'gGGg'),
])
record('idle_b',idle_b);record('idle_c',idle_c);record('attack',attack)
