import json
from pathlib import Path
from PIL import Image, ImageDraw
ROOT=Path(__file__).parent
PAL={'o':'#172730','d':'#2B404D','s':'#506977','v':'#819A9A','g':'#B2BFB3','w':'#D9DAC4','h':'#F2EDD4','i':'#FFF7E2','b':'#685135','c':'#AD8241','y':'#DDB95E','l':'#FFE59D','r':'#8E3443','p':'#DB8987','t':'#245E59','j':'#399B89','k':'#90D6B7','e':'#D5F4D2'}
(ROOT/'palette.json').write_text(json.dumps(PAL,indent=2)+'\n')
def blank(): return [list('.'*128) for _ in range(128)]
def rows(g,x,y,block):
    for yy,row in enumerate(block.strip('\n').split('\n'),y):
        if x+len(row)>128: raise ValueError((x,yy,len(row)))
        for xx,c in enumerate(row,x):
            if c!='.': g[yy][xx]=c

def patch(g,items):
    for x,y,row in items:
        g[y][x:x+len(row)]=row

def save(g,name,folder='poses'):
    out='\n'.join(''.join(row) for row in g)+'\n'
    (ROOT/folder/(name+'.pxgrid')).write_text(out)
    return g

def render(g,name):
    im=Image.new('RGBA',(128,128))
    pix=im.load()
    for y,row in enumerate(g):
        for x,c in enumerate(row):
            if c!='.': pix[x,y]=tuple(bytes.fromhex(PAL[c][1:]))+(255,)
    im.save(ROOT/'progress'/(name+'.png'))
    im.resize((512,512),Image.Resampling.NEAREST).save(ROOT/'progress'/(name+'-4x.png'))
    return im

def copy(g): return [r[:] for r in g]
base=blank()
# Long tail: individually chosen bands and an open hooked tip, behind the haunch.
rows(base,7,29,'''
..............oooo
............oowhioo
..........oowhhhhiio
.........owhhdohhhho
........owhddo.ohhho
.......owhddo..ohhho
......owhhdo...owhho
.....owhhdo....owhho
....owhhdo.....ogwgo
...owhhdo......ogwgo
..owhhdo.......ovggo
..owhho........osvgo
.owhho.........odvgo
.owhho.........odvgo
owhho...........oggo
owhho...........oooo
owhho
owhho
owdho
odddo
oddgo
odggo
owggo
owhgo
owhhgo
.owhhgo
.owhhgo
..owhhgo
..owdddgo
...oddddgo
...ogdddgo
....owggggo
.....owhhggo
......owhhhggo
.......owhhhggo
........owhhgggo
.........owhggggo
..........oggggggo
...........ogddgggo
............oddddgggo
.............ogdddgggo
..............owggggggo
...............owhhggggo
................owhhggggo
.................owhhggggo
..................owhgggggo
...................owggggggo
....................ogggggggo
.....................ogggggggo
......................oggggggo
.......................oggggo
........................oooo
''')
# Back, long belly and thick shoulder: contiguous native fur planes.
rows(base,24,48,'''
.............................................ooo
..........................................ooohhhooo
.......................................ooohhhiiiihhoo
....................................ooohhhhhhiiiihhhho
.................................ooohhhhhhhiihhhhhhhhho
..............................ooohhhhhhhhhiihhhhhhhhhhho
...........................ooohhhhhhhhhhhhhhhhhhhhhhhhhho
........................ooohhhhhhdddhhhhhhhhhhhhhhhhhhhhho
.....................ooohhhhhhhddssdhhhhhhhhhhhhhhhhhhhhhhho
..................ooohhhhhhhhhddssdhhhhhhhdddhhhhhhhhhhhhhhho
...............ooohhhhhhhhhhhhddsdhhhhhhhddssdhhhhhhhhhhhhhho
.............oohhhhhhhhhhhhhhhdsdhhhhhhhhddssdhhhhhhddhhhhhhho
...........oohhhhhhhhhhhhhhhhhddhhhhhhhhhddssdhhhhhhdddhhhhhho
.........oohhhhhhhhhhhhhhhhhhhddhhhhhhhhhhdddhhhhhhhddsdhhhhho
........oohhihhhhhhhhhhhhhhhhhdhhhhhhhhhhhddhhhhhhhddssdhhhhhho
.......ohhiiihhhhhddhhhhhhhhhhhdhhhhhhhhhhhhhhhhhhhddssdhhhhhhho
......ohhiiiihhhhddsdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddsdhhhhhhhho
.....ohhiiiihhhhddssdwhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddhhhhhhhhhhho
....ohhiiiihhhhddsssdwwhhhhhhhhhhhhhwwhhhhhhhhhhhhddhhhhhhhhhhho
...ohhiiiihhhhddsssdwwwwwhhhhhhhhhwwwwwhhhhhhhhhhhddhhhhhhhhhhhho
..ohhiiiihhhhddsssdwwwwwwwddddwhhwwwwwwwhhhhhhhhhhhhhhhhhhhhhho
..ohhiiihhhhddsssdwwwwwwdddssdwwwwwwwwwwwhhhhhhhhhhhhhhhhhhhho
.ohhiiihhhhhddssdwwwwwwddsssdwwwwwwwwwwwwwhhhhhhhhhhhhhhwwwwho
.ohhihhhhhhhddsdwwwwwwddsssdwwwwwwwwwwwwwwwhhhhhhhhhwwwwwwwho
.ohhhhhhhhhhdddwwwwwwwddssdwwwwwwwwwwwwwwwwwddddhhhwwwwwwwwwho
.ohhhhhhhhhhddwwwwwwwwddsdwwwwwwwwwwwwwwwwwddssdwwwwwwwwwwwho
.ohhhhhhhhhhdwwwwwwwwwdddwwwwwwwwwwwwwwwwwwddsssdwwwwwwwwwwho
.ohhhhhhhhhhwwwwwwwwwwwddwwwwwwwwwwwwwwwwwwwddsssdwwwwwwwwwho
.ohhhhhhwwwwwwwwwwwwwwwwdwwwwwwwwwwwwwwwwwwddssdwwwwwwwwwwgo
.ohhhhhwwwwwwwwwwwwwwwwwdwwwwwwwwwwwwwwwwwwwdddwwwwwwwwwwwgo
.ohhhhwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddwwwwwwwwwwwgo
.ohhhwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdwwwwwwwwwwwgo
.ohhwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwggwwwwwwwwwgo
.ohhwwwwwwggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgggwwwwwwwwgo
.ohwwwwwgggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgggggwwwwwwwgo
.ogwwwwgggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwggggggwwwwwgo
..ogwwggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwgggggggwwwwgo
..ogwggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwggggggggwwwgo
...oggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwgggggggggwwgo
...ogggggggvgggggggwwwwwwwwwwwwwwwwwwwwgggggggggggwgo
....ogggggvvvggggggggwwwwwwwwwwwwwwwwggggggggggggggo
....oggggvvvvgggggggggggwwwwwwwwwgggggggggggggggggo
.....oggvvvvvggggggggggggggggggggggggggggggggggggo
.....ogvvvvvvgggggggggggggggggggggggggggggggggggo
......ovvvvvvvgggggggggggggggggggggggggggggggggo
......ovvvvvvvvgggggggggggggggggggggggggggggggo
.......ovvvvvvvvgggggggggggggggggggggggggggggo
........ovvvvvvvvgggggggggggggggggggggggggggo
.........osvvvvvvvvvgggggggggggggggggggggggo
..........osvvvvvvvvvvgggggggggggggggggggo
...........oosvvvvvvvvvvvvgggggggggggggo
.............oosvvvvvvvvvvvvvvvvggggoo
...............ooosssssssssssssssooo
..................ooooooooooooooo
''')
# Far hind paw, planted obliquely under the abdomen.
rows(base,51,96,'''
...oosvvvvo
..osvggvvvo
..ovgggvvvo
..ovgggvvvo
..ovggvvvvo
..ovggvvvvo
..ovgvvvvo
..ovgvvvvo
..ovgvvvvo
..osvvvvo
..osvvvvo
..osvvvvo
..osvvvvo
..osvvvvo
..osvvvvo
..osvvvvo
..osvvvvo
..osvvvvo
..ovgggvooo
.ovggwwggvvo
ovgwwwggvvvvo
ogwwwggdggdvo
ogwwgggoggovoo
.oooooooooooo
''')
# Far shoulder leg, broad blue-gray sole.
rows(base,75,84,'''
...oovvggggvo
..ovvggggggvo
..ovgggggggvo
..ovgggggggvo
..ovggddgggvo
..ovgdddgggvo
..ovgdddgggvo
..ovggddgggvo
..ovgggggggvo
..ovgggggggvo
..ovgggggggvo
..ovgggggggvo
..ovgggggggvo
..ovgggggggvo
..ovgggggggvo
..ovgggggggvo
..ovgggggggvo
..ovgggggggvo
..ovgggggggvo
..ovgggggggvo
..ovggddgggvo
..ovgdddgggvo
..ovgdddgggvo
..ovggddgggvo
..ovgggggggvo
..ovgggggggvo
..ovgggggggvo
..ovgggggggvo
..ovgggggggvo
..ovgggggggvo
..ovgggggggvo
..ovgggggggvo
..ovgggggggvo
..ovgggggggvo
..ovgggggggvo
.ovgggggggggvooo
ovgwwwwwwwwgggvo
ogwwwwwwwggdggdvo
ogwwwwwwgggoggovoo
.oooooooooooooooo
''')
# Near haunch and folded hock. Limb flows down and then forward into a huge paw.
rows(base,27,83,'''
.....ohhwwwwwwwwwwggo
....ohhwwwwwwwwwwwgggo
...ohhwwwwwwwwwwwgggggo
..ohhwwwwwwwwwwwgggggggo
..ohwwwwwwwwwwwgggggggggo
.ohwwwwwwwwwwwgggggggggggo
.ohwwwwwwwwwwggggggggggggo
.ohwwwwwdddwwgggggggggggggo
.ohwwwwddssdwwggggggggggggo
.ohwwwddsssdwwgggggggggggggo
.ohwwwddssdwwwgggggggggggggo
.ohwwwddsdwwwwgggggggggggggo
.ohwwwdddwwwwwgggggggggggggo
.ohwwwwddwwwwwgggggggggggggo
.ohwwwwdwwwwwwgggggggggggggo
.ogwwwwwwwwwwwwgggggggggggo
..ogwwwwwwwwwwwgggggggggggo
..ogwwwwwwwwwwwggggggggggo
...ogwwwwwwwwwwgggggggggo
....ogwwwwwwwwwggggggggo
.....ogwwwwwwwwgggggggo
......ogwwwwwwwggggggo
.......ogwwwwwwgggggo
........ogwwwwwggggo
.........ogwwwwgggo
.........ogwwwgggo
.........ogwwwgggo
.........ogwwwgggo
.........ogwwgggo
........ogwwwgggo
.......ogwwwwgggo
......ogwwwwwgggo
.....ogwwwwwggggo
....ohwwwwwwggggo
....ohwwwwwwggggo
...ohhwwwwwwgggggooo
..ohhhwwwwwwwwwwggggo
.ohhhhwwwwwwwwwwwggggo
.ohhwwwdwwwwwdwwwwwgggo
.ogwwwwowwwwgowwwwwgggo
..ogwwwowwwwgowwwwggggo
...oooooooooooooooooo
''')
# Near foreleg: ivory load bearing column, defined elbow and large three-toed paw.
rows(base,91,73,'''
..ohhiiiiihhho
..ohhiiiihhhho
.ohhiiiihhhhho
.ohhiiihhhwwho
.ohhiiihhwwwho
.ohhiihhwwwwho
.ohhiihwwwwwho
.ohhihhwwwwwho
.ohhihwwwwwwho
.ohhhwwwwwwwwho
.ohhwwwwwwwwwho
.ohhwwwwwwwwwho
.ohhwwwwwwwwwho
.ohhwwdddwwwwho
.ohhwddssdwwwho
.ohhwddsssdwwho
.ohhwddsssdwwho
.ohhwwddssdwwho
.ohhwwwdddwwwho
.ohhwwwwddwwwho
.ohhwwwwwdwwwho
.ohhwwwwwwwwwho
.ohhwwwwwwwwwho
.ohhwwwwwwwwwho
.ohhwwwwwwwwwho
.ohhwwwwwwwwwho
.ohhwwwwwwwwwho
.ohhwwwwwwwwwho
.ohhwwwwwwwwwho
.ohhwwwwwwwwwho
.ohhwwwwwwwwwho
.ohhwwwwwwwwwho
.ohhwwddwwwwwho
.ohhwddsdwwwwho
.ohhwddssdwwwho
.ohhwwddsdwwwho
.ohhwwwdddwwwho
.ohhwwwwddwwwho
.ohhwwwwwdwwwho
.ohhwwwwwwwwwho
.ohhwwwwwwwwwho
.ohhwwwwwwwwwho
.ohhwwwwwwwwwho
.ohhwwwwwwwwwho
.ohhwwwwwwwwwho
.ohhwwwwwwwwwho
.ohhwwwwwwwwwho
.ohhiihwwwwwwhhooo
.ohiiiihwwwwwwwhhhho
ohiiiihwwwwwwwwwhhhho
ohhhwwwwdwwwwdwwwwwhho
ogwwwwwwowwwwowwwwwggo
''')
# Connected neck wedge and loaded front shoulder, behind collar and skull.
rows(base,76,49,'''
............ohhhiihho
...........ohhhiiihhho
..........ohhhiiiihhhho
.........ohhhhiiiihhhhho
........ohhhhhiiihhhhhhho
.......ohhhhhhiiihhhhhhho
......ohhhhhhhiiihhhhhhhho
.....ohhhhhhhhihhhhhhhhhho
....ohhhhhhhhhhhhhhhhhhhho
...ohhhhhhhhhhhhhhhhhhhhho
..ohhhhhhhhhhhhhhhhhhhhhho
.ohhhhhhhhhhhhhhhhhhhhhhho
ohhhhhhhhhhhhhhhhhhhhhhwho
ohhhhhhhhhhhhhhhhhhhhhhwho
ohhhhhhhhhhhhhhhhhhhhhwwho
ohhhhhhhhhhhhhhhhhhhhwwwho
ohhhhhhhhhhhhhhhhhhhwwwwho
ohhhhhhhhhhhhhhhhhhwwwwwho
ohhhhhhhhhhhhhhhhhwwwwwwho
ohhhhhhhhhhhhhhhhwwwwwwwho
ohhhhhhhhhhhhhhhwwwwwwwwho
ohhhhhhhhhhhhhhwwwwwwwwwho
ohhhhhhhhhhhhhwwwwwwwwwwho
ohhhhhhhhhhhhwwwwwwwwwwwho
ohhhhhhhhhhwwwwwwwwwwwwwho
ohhhhhhhhhwwwwwwwwwwwwwwho
ohhhhhhhhwwwwwwwwwwwwwwwho
ohhhhhhhwwwwwwwwwwwwwwwggo
ohhhhhhwwwwwwwwwwwwwwwgggo
ohhhhhwwwwwwwwwwwwwwwggggo
ohhhhwwwwwwwwwwwwwwwgggggo
ohhhwwwwwwwwwwwwwwwggggggo
ohhwwwwwwwwwwwwwwwgggggggo
ohwwwwwwwwwwwwwwwggggggggo
ogwwwwwwwwwwwwwwwggggggggo
ogwwwwwwwwwwwwwwgggggggggo
.ogwwwwwwwwwwwwwggggggggo
..ogwwwwwwwwwwwwgggggggo
...ogwwwwwwwwwwwggggggo
....ogwwwwwwwwwwgggggo
.....ogwwwwwwwwwggggo
......ogwwwwwwwwgggo
.......ogwwwwwwwggo
........ogwwwwwwgo
.........ogwwwwgo
..........oooooo
''')
# Collar: slanting bronze-gold plates with a large jade clasp.
rows(base,81,62,'''
.....obcylho
....obclllho
...obclllcho
..obcllycho
.obclyycbo
obclyycbo
obclyycbo
obclyycbo
obclyycbo
obclyycbo
obcllycbo
obcllycbo
.obcllycbo
.obclyycbo
..obcllycbo
...obclllycbo
....obcllllycbo
.....obclyjjjycbo
......obbyjekjycbo
.......objekkjtbo
........otjkjjtbo
.........otjjtbbo
..........obbbbo
''')
# Two substantial red cords, tied beneath the collar.
rows(base,84,83,'''
....orpro
...orpppro
..orrprrpro
..orprorpro
...orroorpro
....ro.orpro
...orpro.orro
..orppro.orpro
..orppro.orpro
..orrpro.orppro
..orrpro.orppro
..orrpro.orppro
..orprro.orrrro
..orprro.orrrro
..ororro.orrrro
...ooo...ororro
..........ooo
''')
# Broad tiger skull, ears, brow and pale muzzle. No lion mane.
rows(base,83,29,'''
........ooo
.......ohhho
......ohhiihho
.....ohhddiihho
.....ohdpddiho........ooo
.....ohdppdiho.......ohhho
.....ohdppdiho......ohddiho
.....ohvppvho.....ohhdddiho
.....ohwwwwhooooohhhhvvvho
....ohhwwwiiiiiiihhhhhwwho
...ohhhiiiiiiiiiiiiihhhwwho
..ohhhiiiiiiiiiiiiiiiihhwwho
.ohhhhiiiiiiihhhhhhhhhhhwwho
.ohhhiiiiiiihhdddwhhhhhhhwwho
.ohhhiiihhhhddssddhhhhhhwwwwho
.ohhiiihhhhddsssddhhhhhhwwwho
.ohhiiihhhddssssddhhhhhhwwwho
.ohhihhhhddssdddhhhhhhwwwwho
.ohhhhhhdddssdhhhhhhhwwwwwwho
.ohhhhhhhdddhhhhhhhwwwwwwwwho
.ohhhhhhhhhhhhhhhwwwwwwwwwwwho
.ohhhhddhhhhhhhhwwwwddddwwwwho
.ohhhddsdhhhhhhhwwwddlyldwwwho
.ohhddssdwhhhhhwwwdlyoldoowwho
.ohhddssddwhhhhwwwddooodhhhwho
.ohhddsssdwwhhhwwwwhhhhhhhhhhho
.ohhwdddssdwghhwwwhhhhhhhhiiiho
.ohhwwdddsdwggwwwhhhhhhiiiihhhho
.ohhwwwdddwgggwwwhhhhiiiihhhhp po
..ohwwwwddwgggwwwhhhiiihhhhppppo
..ohhwwwwdwggggwwhhhiiihhhhpppdo
..ohhhwwwwgggggwwhhhiiihhhhddo
...ohhhwwwwgggggwwhhiiihhhhoo
...ohhhwwwwgggggwwhhhhhhhhhho
....ohhhwwwwgggggwwwhhhhhhhho
.....ohhhwwwwggggggwwwhhhhwdo
......ohhhwwwwwgggggwwwwwddo
.......ohhhhwwwwwggggwwdddo
........ohhhhhwwwwwggwwwdo
.........ohhhhhhwwwwwwwwho
..........ohhhhhhwwwwwho
...........ohhhhhwwwho
............ohhhhwwho
.............ohhhwho
..............ohhho
...............ooo
'''.replace(' ',''))
# Explicit whisker clusters, lip contour and a single visible lower fang.
patch(base,[(113,57,'hhhiiiho'),(115,58,'hhhiippo'),(116,59,'hippppo'),(117,60,'hpppdo'),(115,61,'hddoo'),(114,62,'hhoodh'),(113,63,'hhhodih'),(112,64,'hhhoodh'),(112,65,'hhoooo'),(114,55,'ii...hhh'),(115,54,'...hh'),(113,67,'hhhh...hh'),(117,66,'..hhh'),(108,63,'wwwhh'),(108,64,'wwhhhh'),(106,66,'gwwwwh')])
# Short torn jade vapour, species ornament attached to the upper shoulder and brow.
rows(base,67,39,'''
..j
..jk
...jk
...jek
....jek
.....jk
......jkj
.......jtj
........tj
''')
rows(base,81,21,'''
..j
..jk
...jk
...jek
....jek
.....jk
......jt
.......t
''')
rows(base,96,24,'''
......j
.....jk
....jek
....jkj
...jjt
..jjt
..jt
.jt
''')
save(base,'idle_a')
render(base,'idle')
# Native pose edits use chosen row replacements. Dots erase earlier ink only;
# no frame moves, resampling, contour generators or inferred shading.
def replace(g,x,y,block,width):
    for yy,row in enumerate(block.strip('\n').split('\n'),y):
        if len(row)>width: raise ValueError(('replacement',yy,len(row),width))
        g[yy][x:x+width]=row.ljust(width,'.')
def erase(g,x,y,width,height):
    # Erasure is canvas housekeeping; all replacement ink is literal below.
    for yy in range(y,y+height): g[yy][x:x+width]='.'*width

# Nonuniform stripes following the scapula, not a repeated body pattern.
patch(base,[(77,57,'hddhh'),(76,58,'hddsdh'),(75,59,'hddssdh'),(74,60,'hddssdhh'),(74,61,'hddsdhhh'),(75,62,'hddhh'),(76,63,'hdhhh'),(77,64,'hhhhh'),(78,88,'wwdddww'),(77,89,'wwddssdw'),(77,90,'wdddssdw'),(77,91,'wddsssdw'),(78,92,'wddssdw'),(79,93,'wddsdw'),(80,94,'wddww')])
# Broad faceted upper collar plate with a clear metal lip.
rows(base,80,67,'''
...obcllycbo
..obclllyycbo
.obclllyyyycbo
obcllyjjjyycbo
obcllyjekjycbo
obclyjekkjycbo
.obcyjkkjjycbo
..obcyjjtjycbo
...obcyyyybcbo
....obcbbbcbo
.....obbbbo
''')
save(base,'idle_a'); render(base,'idle')
idle_b=copy(base)
patch(idle_b,[(93,80,'hiiihhwwwwh'),(93,81,'hiihhwwwwwh'),(93,82,'hihhwwwwwwh'),(93,83,'hhhwwwwwwwh'),(84,90,'orppro'),(84,91,'orppro'),(85,96,'orprro'),(115,66,'hhh....'),(115,67,'..hhh'),(20,30,'oowhhio'),(19,31,'owhhiihho'),(19,32,'whddiihho'),(107,51,'wwddddwww'),(107,52,'wdlyldwww')])
save(idle_b,'idle_b')
idle_c=copy(base)
patch(idle_c,[(93,81,'hhihhwwwwh'),(93,82,'hhhwwwwwgh'),(93,83,'hhwwwwwwgh'),(93,84,'hhwwwwwggh'),(85,88,'orpro.'),(85,89,'orppro'),(86,90,'orppro'),(87,91,'orrpro'),(87,92,'orrpro'),(113,63,'hhhodih'),(114,64,'hhoodh'),(115,65,'hhhhh'),(20,30,'oowhhho'),(19,31,'owhhiiho'),(18,32,'owhddiho'),(9,44,'ohhho'),(9,45,'ohhho'),(9,46,'ohhho')])
save(idle_c,'idle_c')

# Low broad head, with swept ears and an aggressive jaw. Entirely new rows.
LOW_HEAD='''
......ooo..............ooo
.....ohhho............ohhho
....ohhiiho..........ohddiho
...ohhddiihho.......ohdddiho
...ohdpddiihhoo....ohhvvvho
...ohdppdihhhhhoooohhhwwho
...ohvppvhhhhiiiiihhhhhhwho
..ohhwwwiiiiiiiiiiiihhhhhho
.ohhhiiiiiiiiiiiiiiiihhhhwho
.ohhiiiiiiihhdddhhhhhhhhwwho
ohhiihhhhdddssddhhhhhhhhwwwho
ohhhihhhddssssddhhhhhhwwwwwho
ohhhhhhddssdddhhhhhhhwwwwwwho
ohhhhhhdddssdhhhhhhhwwwwwwwwho
ohhhhhhhdddhhhhhhhhwwwddddwwho
ohhhhhhhhhhhhhhhhhhwwddlyldwho
ohhhhddhhhhhhhhhhwwwdlyoldoho
ohhhddsdhhhhhhhhhwwwddooodhho
ohhddssdwhhhhhhhwwwwhhhhhiiho
ohhddssddwhhhhhhwwwhhhiiiihhho
ohhwdddssdwghhhhwwwhhiiihhpppo
ohhwwdddsdwgwwwwwwwhhiiihpppdo
.ohhwwwddwggwwwwwwwghhhhdddo
..ohhwwwdwgggwwwwwwghhhddio
...ohhwwwwggggwwwwwwghhdio
....ohhwwwwggggwwwwwwwdo
.....ohhwwwwggggggwwwdo
......ohhhhwwwwwggwwwho
.......ohhhhhwwwwwwwwho
........ohhhhhwwwwwho
.........ohhhhwwwwho
..........ohhhhwwho
...........ohhhwho
............ohhho
.............ooo
'''
def low_front(g):
    erase(g,76,21,50,75)
    # Low scapula and a long slope into the neck.
    rows(g,72,59,'''
+...........ooohhhhhooo
+.........oohhhiiiihhhhoo
+.......oohhhhiiiihhhhhho
+.....oohhhhhiiiihhhhhhhho
+...oohhhhhhiiiihhhhhhhhhho
+.oohhhhhhhiiiihhhhhhhhhhho
+ohhhhhhhhiiiihhhhhhhhhhhho
+ohhhhhhhhhhddhhhhhhhhhhhho
+ohhhhhhhhhddsdhhhhhhhhhhhho
+ohhhhhhhhddssdwhhhhhhhhhhho
+ohhhhhhhddsssdwwhhhhhhhhhho
+ohhhhhhhddssdwwwhhhhhhhhhho
+ohhhhhhhhdddwwwwhhhhhhhhhho
+ohhhhhhhhddwwwwwhhhhhhhhhho
+ohhhhhhhhdwwwwwwwhhhhhhhhho
+ohhhhhhhhhwwwwwwwwhhhhhhhho
+ohhhhhhhhwwwwwwwwwwhhhhhhho
+ohhhhhhhwwwwwwwwwwwwhhhhho
+ohhhhhhwwwwwwwwwwwwwwhhho
+ohhhhhwwwwwwwwwwwwwwwwho
+ohhhhwwwwwwwwwwwwwwwwgo
+ohhhwwwwwwwwwwwwwwwwgo
+ohhwwwwwwwwwwwwwwwwgo
+ohwwwwwwwwwwwwwwwwgo
+ogwwwwwwwwwwwwwwwgo
+ogwwwwwwwwwwwwwwgo
+.ogwwwwwwwwwwwwgo
+..ogwwwwwwwwwwgo
+...ogwwwwwwwwgo
+....ogwwwwwwgo
+.....ogwwwwgo
+......ogwwgo
+.......oggo
+........oo
+'''.replace('+',''))
    rows(g,84,57,LOW_HEAD)
    rows(g,79,77,'''
+....obclllcbo
+...obclllyycbo
+..obcllyjjycbo
+.obcllyjekjycbo
+obcllyjekkjycbo
+obclyjkkjjycbo
+obclyyjjtyycbo
+.obclyyyycbo
+..obclyycbo
+...obbbbo
+....orpro.orpro
+...orpproorppro
+...orrproorrpro
+....orproorrpro
+.....orproorpro
+......orro.orro
+.......oo..oo
+'''.replace('+',''))

windup=copy(base); low_front(windup)
# Two paws gathered beneath a crouched shoulder; elbow bends outward.
erase(windup,74,94,39,31)
rows(windup,75,92,'''
..............ohhwwwwwggo
.............ohhwwwwwgggo
............ohhwwwwggggo
...........ohhwwwwggggo
..........ohhwwwwggggo
.........ohhwwwwggggo
........ohhwwdddgggo
.......ohhwwddsdggo
......ohhwwddssdggo
.....ohhwwwdddgggo
....ohhwwwwwggggo
...ohhwwwwwggggo
..ohhwwwwwggggo
.ohhwwwwwggggo
.ohhwwwwwggggo
..ohhwwwwggggo
...ohhwwwggggo
....ohhwwggggo
.....ohhwwgggo
......ohhwwgggo
.......ohhwwgggo
........ohhwwgggo
.........ohhwwgggo
..........ohhwwgggo
..........ohhhwwgggo
.........ohhiiiwwwggoo
........ohhiiiwwwwwwwggo
.......ohhwwdwwwwdwwwgggo
.......ogwwwowwwgowwwgggo
........ooooooooooooooo
''')
rows(windup,68,110,'''
....ovgggvo
...ovggggvo
..ovgggggvo
.ovggggggvo
ovgggggggvo
ovgggggggvo
.ogggggggvo
..oggggggvo
...ogggggvo
....oggggvo
....ovgggvoooo
...ovgwwwwgggvo
..ogwwwwwdggdvo
..ogwwwwwoggogvo
...oooooooooooo
''')
save(windup,'windup')

# Move: hind-leg extension and airborne forepaw reach, all separately authored.
move=copy(base); low_front(move)
erase(move,27,96,41,29)
rows(move,26,96,'''
..ohhwwwwwgggggo
..ohhwwwwwwgggggo
...ohhwwwwwwgggggo
....ohhwwwwwwgggggo
.....ohhwwwwwwgggggo
......ohhwwwwwwgggggo
.......ohhwwwwwgggggo
........ohhwwwwwggggo
.........ohhwwwwwggggo
..........ohhwwwwwggggo
...........ohhwwwwggggo
............ohhwwwggggo
.............ohhwwggggo
..............ohhwwggggo
...............ohhwwggggo
................ohhwwggggo
.................ohhwwggggo
..................ohhwwggggo
...................ohhwwggggo
....................ohhwwggggo
....................ohhwwggggo
...................ohhwwwggggo
..................ohhwwwwggggo
.................ohhwwwwwggggo
................ohhwwwwwggggo
................ohhhwwwggggo
................ohhwwwdggggo
.................ogwwwoggggo
..................ooooooooo
''')
erase(move,75,94,43,31)
rows(move,82,90,'''
...ohhwwwwwwwggo
..ohhwwwwwwwwgggo
.ohhwwwwwwwwwgggggo
ohhiwwwwwwwwwggggggo
ohhiwwdddwwwwgggggggo
ohhwwddssdwwwggggggggo
ohhwwddsssdwwgggggggggo
.ohhwwwdddwwwggggggggggo
..ohhwwwwwwwwgggggggggggo
...ohhwwwwwwwwggggggggggo
....ohhwwwwwwwwggggggggggo
.....ohhwwwwwwwwggggggggggo
......ohhwwwwwwwwggggggggggo
.......ohhwwwwwwwwggggggggggo
........ohhwwwwwwwwgggggggggo
.........ohhwwwwwwwwggggggggo
..........ohhwwwwwwwwggggggggo
...........ohhwwwwwwwwgggggggo
............ohhwwwwwwwwggggggo
.............ohhwwwwwwwwgggggo
..............ohhwwwwwwwwggggo
...............ohhiiiwwwwwggggo
................ohiiiwwwwwwgggo
.................ohwwdwwwdwwwggo
..................ogwowwgowwwwgo
...................oooooooooooo
''')
rows(move,72,99,'''
..ovgggvo
.ovggggvo
ovgggggvo
ovgggggvo
.ogggggvo
..oggggvo
...ogggvo
....ogggvo
.....ogggvo
......ogggvo
.......ogggvo
........ogggvo
.........ogggvo
..........ogggvo
...........ogggvooo
............ogwwwgvo
.............ogwdgdvo
..............ogogovo
...............ooooo
''')
save(move,'move')

attack=copy(move)
# Contact mouth: clearly parted jaw, lower fang and dark red mouth interior.
patch(attack,[(108,77,'hhhiihhpppo'),(107,78,'hhhiiihpppdo'),(108,79,'hhddddddoo'),(108,80,'hhdrrrrpdo'),(108,81,'hhdrrprpdo'),(108,82,'hhdrrrddio'),(108,83,'whhdddiio'),(109,84,'wwhhddoo'),(109,85,'wwhhhho'),(110,86,'whhhho'),(114,73,'..hhh'),(117,75,'..hhh'),(114,85,'hhhh')])
# A wide attacking paw unfolds horizontally into exactly three long claws.
erase(attack,96,98,30,25)
rows(attack,93,97,'''
.ohhwwwwwwggggggo
.ohhwwwwwwwwggggggo
.ohhwwwwwwwwwwggggggo
.ohhwwwwwwwwwwwwggggggo
.ohhwwwwwwwwwwwwwwggggggo
.ohhwwwwwwwwwwwwwwwwgggggo
..ohhwwwwwwwwwwwwwwwwwggggo
...ohhwwwwwwwwwwwwwwwwwgggo
....ohhwwwwwwwwwwwwwwwwwggo
.....ohhwwwwwwwwwwwwwwwwggo
......ohhwwwwwwwwwwwwwwwgo
.......ohhwwwwwwwdwwwwwhho
........ohhwwwwwwowwwwhhio
.........ohhwwwwwdwwwwhhio
..........ohhwwwwowwwhhio
...........ohhwwwdwwwhhio
............ohhwwowhhio
.............ohhwwhhio
..............ohhwwho
...............oggo
................oo
''')
# Three ivory tips at distinct heights, with dark roots.
patch(attack,[(118,107,'whhiiio'),(119,108,'hiiio'),(121,109,'iio'),(118,111,'whhiiio'),(120,112,'hiio'),(122,113,'io'),(118,115,'whhiio'),(120,116,'hiio'),(121,117,'io')])
save(attack,'attack')

recover=copy(windup)
# Weight returns into the near shoulder; the stretched paw flexes at the wrist.
patch(recover,[(91,94,'hhwwwwwwgggo'),(90,95,'hhwwwwwwgggo'),(89,96,'hhwwwwwwgggo'),(88,97,'hhwwwwwwgggo'),(87,98,'hhwwwddwgggo'),(86,99,'hhwwddsdggo'),(85,100,'hhwwddssdggo'),(84,101,'hhwwwdddgggo'),(83,102,'hhwwwwwwgggo'),(83,103,'hhwwwwwwgggo'),(84,104,'hhwwwwwwgggo'),(85,105,'hhwwwwwgggo'),(86,106,'hhwwwwgggo'),(87,107,'hhwwwgggo'),(88,108,'hhwwgggo'),(89,109,'hhwwgggo'),(90,110,'hhwwwggo'),(91,111,'hhwwwggo'),(92,112,'hhwwwggo'),(92,113,'hhwwwggo'),(92,114,'hhwwwggo'),(92,115,'hhwwwggo'),(91,116,'hhwwwwggo'),(90,117,'hhhwwwwwggo'),(89,118,'hhiiwwwwwwggo'),(89,119,'hiiwwwwwwwwggo'),(89,120,'hwwdwwwwdwwwggo'),(89,121,'gwwowwwgowwwggo'),(89,122,'oooooooooooooo')])
# Ears perk during recovery, mouth closes and cheek fur lifts.
patch(recover,[(89,57,'ohhho'),(88,58,'ohhiho'),(88,59,'ohddiho'),(114,78,'hhpppdo'),(113,79,'hhhddo'),(112,80,'hhhooo'),(110,84,'whhhhho'),(83,87,'orppro'),(84,88,'orrpro'),(85,89,'orpro'),(86,90,'orro')])
save(recover,'recover')
def sheet(names,folder='poses',filename='motion-sheet'):
    board=Image.new('RGB',(128*len(names),152),(34,41,48))
    draw=ImageDraw.Draw(board)
    for n,name in enumerate(names):
        g=[list(r) for r in (ROOT/folder/(name+'.pxgrid')).read_text().splitlines()]
        im=render(g,name)
        board.paste(im,(128*n,16),im)
        draw.text((128*n+4,2),name,fill=(236,229,207))
    board.resize((board.width*2,board.height*2),Image.Resampling.NEAREST).save(ROOT/'progress'/(filename+'.png'))
sheet(['idle_a','windup','move','attack','recover'])
# Sick posture: head is newly lowered and tilted, not an attack with bubbles.
SICK_HEAD='''
.....oooo
....ohhhhho
...ohhwwwwho............ooo
...ohhddwwhho..........ohhho
...ohdppdwwhho........ohvwho
....ohppvwwhhho......ohvvwho
....ohvvwwhhhhooooohhhwwwho
...ohhwwhhhhiiiiiiihhhhhhwho
..ohhhhiiiiiiiiiiiiihhhhhwho
.ohhhhiiiiiiiiiiiiiiihhhhwwho
.ohhhiiiiihhddddhhhhhhhhhwwho
ohhhiiihhhddssddhhhhhhhhwwwwho
ohhiihhhhddsssddhhhhhhhhwwwwho
ohhhihhhddssddhhhhhhhhhhwwwwho
ohhhhhhddssdhhhhhhhhhhhwwwwwho
ohhhhhhhdddhhhhhhhhhhhwwwwwwho
ohhhhhhhhhhhhhhhhhhhhwwwwwwwho
ohhhhhhhhhhhhhhhhhhhwwwdddwwho
ohhhhddhhhhhhhhhhhhhwwdddddwho
ohhhddsdhhhhhhhhhhhwwddyyyodho
ohhddssdwhhhhhhhhhwwwddoooowho
ohhddssddwhhhhhhhhwwwwhhhhhhho
ohhwdddssdwghhhhhhwwwhhhhhhiiho
ohhwwdddsdwgwwwwwwwghhhiiihhhho
.ohhwwwddwggwwwwwwwghhiiiihhhpo
..ohhwwwdwgggwwwwwwghhiiiihpppdo
...ohhwwwwggggwwwwwwghhiiihppdo
....ohhwwwwggggwwwwwwwghhhddo
.....ohhwwwwgggggwwwwwghhhdo
......ohhwwwwgggggwwwwghhdio
.......ohhhwwwwggggwwwghddo
........ohhhwwwwggggwwghhho
.........ohhhhwwwwggwwwghho
..........ohhhhhwwwwwwwwho
...........ohhhhhwwwwwwho
............ohhhhhwwwho
.............ohhhhwwho
..............ohhwwho
...............ohwho
................ooo
'''
# A broad sagging neck joins cheek, collar and weight-bearing forelimb.
SLUMP_NECK='''
..ohhwwwwwwwwwwwwggo
.ohhwwwwwwwwwwwwwgggo
ohhwwwwwwwwwwwwwwggggo
ohhwwwwwwwwwwwwwgggggo
ohhwwwwwwwwwwwwggggggo
ohhwwwwwwwwwwwgggggggo
ohhwwwwwwwwwwggggggggo
ohhwwwwwwwwwgggggggggo
ohhwwwwwwwwggggggggggo
ohhwwwwwwwgggggggggggo
ohhwwwwwwggggggggggggo
ohhwwwwwwggggggggggggo
ohhwwwwwwggggggggggggo
.ohhwwwwwggggggggggggo
.ohhwwwwwggggggggggggo
..ohhwwwwgggggggggggo
..ohhwwwwgggggggggggo
...ohhwwwggggggggggo
...ohhwwwggggggggggo
....ohhwwgggggggggo
....ohhwwgggggggggo
.....ohhwwgggggggo
.....ohhwwgggggggo
......ohhwwgggggo
......ohhwwgggggo
.......ohhwwgggo
.......ohhwwwggo
.......ohhwwwggo
.......ohhwwwggo
.......ohhwwwggo
.......ohhwwwggo
.......ohhwwwggo
.......ohhwwwggo
'''
def sick_posture():
    g=copy(base)
    erase(g,82,21,44,71)
    rows(g,81,61,'''
+......ohhhiiiihho
+.....ohhhhiiihhhho
+....ohhhhhiiihhhhhho
+...ohhhhhhihhhhhhhhho
+..ohhhhhhhhhhhhhhhhhho
+.ohhhhhhhhhhhhhhhhhhho
+ohhhhhhhhhhhhhhhhhhhho
+ohhhhhhhhhhddhhhhhhhho
+ohhhhhhhhhddsdhhhhhhhho
+ohhhhhhhhddssdwhhhhhhhho
+ohhhhhhhddsssdwwhhhhhhho
+ohhhhhhhddssdwwwhhhhhhho
+ohhhhhhhhdddwwwwhhhhhhho
+ohhhhhhhhddwwwwwwhhhhhho
+ohhhhhhhhdwwwwwwwWhhhhho
+ohhhhhhhhhwwwwwwwwhhhhho
+ohhhhhhhhwwwwwwwwwWhhho
+ohhhhhhhwwwwwwwwwwwwho
+ohhhhhhwwwwwwwwwwwwgo
+ohhhhhwwwwwwwwwwwwgo
+ohhhhwwwwwwwwwwwwgo
+ohhhwwwwwwwwwwwwgo
+ohhwwwwwwwwwwwwgo
+ohwwwwwwwwwwwwgo
+ogwwwwwwwwwwwgo
+.ogwwwwwwwwwgo
+..ogwwwwwwwgo
+...ogwwwwwgo
+....ogwwwgo
+.....ogwgo
+......ooo
+'''.replace('+','').replace('W','w'))
    rows(g,83,63,SLUMP_NECK)
    rows(g,85,43,SICK_HEAD)
    rows(g,81,75,'''
+...obclllcbo
+..obclllyycbo
+.obcllyjjycbo
+obcllyjekjycbo
+obclyjekkjycbo
+obclyjkkjjycbo
+.obcyyjjtycbo
+..obclyyycbo
+...obclycbo
+....obbbbo
+....orppro
+...orrprro.orpro
+...orprro.orppro
+....orpro.orrpro
+.....orro.orprro
+......oo..ororro
+...........ooo
+'''.replace('+',''))
    # Folded near wrist and unequal soles: weight no longer evenly planted.
    erase(g,91,98,24,27)
    rows(g,90,98,'''
+..ohhwwwwwwwggo
+..ohhwwwwwwwggo
+..ohhwwwdddgggo
+..ohhwwddsdgggo
+..ohhwwddssdggo
+...ohhwwddsdggo
+....ohhwwdddgggo
+.....ohhwwwwgggo
+......ohhwwwgggo
+.......ohhwwgggo
+........ohhwwggo
+.........ohhwwgo
+.........ohhwwgo
+.........ohhwwgo
+........ohhwwwgo
+.......ohhwwwwgo
+......ohhwwwwwgo
+.....ohhwwwwwggo
+....ohhwwwwwwggo
+...ohhwwwwwwwggo
+..ohhwwwwwwwwggoo
+.ohhiwwwwwwwwwwggo
+ohiiwwdwwwwdwwwwggo
+ohwwwwowwwwowwwwggo
+.ogwwwowwwwowwwwggo
+..oooooooooooooooo
+'''.replace('+',''))
    return g
poison_a=sick_posture()
rows(poison_a,75,35,'''
..ttt
.tjkkjt
tjkeejjt
tjkekjjt
.tjjjjt
..tttt
''')
rows(poison_a,119,47,'''
.ttt
tjkjt
tjkjt
.ttt
''')
patch(poison_a,[(78,32,'tjjt'),(77,33,'tkkjt'),(78,34,'ttt'),(87,95,'gwwwwwgg'),(87,96,'gwwwwggg'),(87,97,'ggwwgggg')])
save(poison_a,'poison_a','actions')
poison_b=sick_posture()
patch(poison_b,[(105,62,'wwddddddww'),(105,63,'wwddyyddww'),(105,64,'wwwdooowww'),(107,72,'whhhddio'),(108,73,'whhddio'),(109,74,'whhddo'),(110,75,'whhhho'),(92,100,'hhhwwwwgggo'),(92,101,'hhhwwwdgggo'),(93,102,'hhwwdddgggo'),(94,103,'hhwwddsdggo'),(95,104,'hhwwwdddgggo'),(85,89,'orppro'),(86,90,'orrpro'),(87,91,'orpro')])
rows(poison_b,74,29,'''
...ttt
..tjkjjt
.tjkeejjt
tjkeekjjt
tjkkkjjt
.tjjjjt
..tttt
''')
rows(poison_b,77,41,'''
.ttt
tjkjt
tjkjjt
.tjjt
..tt
''')
rows(poison_b,119,55,'''
..tt
.tjjt
tjkkjt
tjkejt
.tjjt
..tt
''')
save(poison_b,'poison_b','actions')

# Stunned skull: flattened ears, slack jaw, heavy half-shut eyes.
STUN_HEAD='''
...ooooo
..ohhwwhho...........oooo
.ohhddwwhho.........ohhwwho
.ohdppdwwhho.......ohddwwho
..ohppvwwhhho.....ohvvwwho
...ohvvwwhhhhoooohhhwwho
..ohhwwhhiiiiiiihhhhhhwho
.ohhhiiiiiiiiiiiiihhhhwwho
ohhhiiiiiiiiiiiiiiiihhhwwho
ohhiiiiihhddddhhhhhhhhhwwho
ohiiihhhddssddhhhhhhhhwwwho
ohihhhhddsssddhhhhhhhhwwwho
ohhhhhhddssddhhhhhhhhwwwwho
ohhhhhhddssdhhhhhhhhwwwwwho
ohhhhhhhdddhhhhhhhhhwwwwwho
ohhhhhhhhhhhhhhhhhhwwwwwwho
ohhhhddhhhhhhhhhhhhwwwddddwho
ohhhddsdhhhhhhhhhhhwwddddddho
ohhddssdwhhhhhhhhhhwwwdyydwho
ohhddssddwhhhhhhhhhwwwdooowho
ohhwdddssdwghhhhhhhwwwhhhhhho
ohhwwdddsdwgwwwwwwwwhhhhhiiho
.ohhwwwddwggwwwwwwwwhhiiiihhho
..ohhwwwdwgggwwwwwwwghhiiihpppo
...ohhwwwwggggwwwwwwwghhhpppdo
....ohhwwwwgggggwwwwwwghhdddo
.....ohhwwwwggggggwwwwwgddrrdo
......ohhwwwwggggggwwwwgdrppdo
.......ohhwwwwggggggwwwgdpppdo
........ohhhwwwwggggwwwgdddho
.........ohhhhwwwwggwwwghhhho
..........ohhhhhwwwwwwwwhhho
...........ohhhhhwwwwwwhhho
............ohhhhhwwwhhho
.............ohhhhwwhhho
..............ohhwwhhho
...............ohwhhho
................ohhho
.................ooo
'''
def stunned():
    g=sick_posture()
    erase(g,85,39,41,47)
    rows(g,83,63,SLUMP_NECK)
    rows(g,84,42,STUN_HEAD)
    rows(g,82,75,'''
...obcllycbo
..obclllyycbo
.obcllyjjycbo
obcllyjekjycbo
obclyjekkjycbo
obclyjkkjjycbo
.obcyyjjtycbo
..obclyyycbo
...obclycbo
....obbbbo
''')
    # Hock twists inward. Same haunch attached to a newly flexed joint.
    patch(g,[(36,103,'gwwwgggggg'),(36,104,'ggwwwggggg'),(37,105,'ggwwwgggg'),(38,106,'ggwwwggg'),(39,107,'gwwwggg'),(40,108,'wwwwggg'),(40,109,'wwwwggg'),(39,110,'hwwwggg'),(38,111,'hhwwwggg'),(37,112,'hhwwwwggg'),(36,113,'hhwwwwwggg'),(35,114,'hhwwwwwwggg'),(35,115,'hhwwwwwwggg'),(35,116,'hhwwwwwwggg')])
    return g
stun_a=stunned()
rows(stun_a,77,32,'''
...l
...l
..yly
lllylll
..yly
...y
''')
rows(stun_a,112,27,'''
..l
.lyl
lylyl
.lyl
..y
''')
save(stun_a,'stun_a','actions')
stun_b=stunned()
patch(stun_b,[(106,59,'wwdddddww'),(106,60,'wwddyydww'),(106,61,'wwwdoodww'),(110,68,'ghhddrdo'),(110,69,'ghddrppdo'),(110,70,'gddppppdo'),(111,71,'gddpppdo'),(111,72,'ghddddo'),(111,73,'ghhhhho'),(92,98,'hhwwwwwwwggo'),(93,99,'hhwwwwwwggo'),(94,100,'hhwwwdddgggo')])
rows(stun_b,80,26,'''
..l
.lyl
lllyll
.yly
..y
''')
rows(stun_b,113,34,'''
...l
..lyl
.llyll
lllylll
..yly
...y
''')
save(stun_b,'stun_b','actions')

hit=stunned()
# Recoil cheek closes hard, jaw pulls back, ear folds and front knee buckles.
patch(hit,[(88,44,'ohwwwwho'),(87,45,'ohddwwho'),(87,46,'ohppvwho'),(88,47,'ohvvwwho'),(104,59,'wwwddddddw'),(104,60,'wwddssddww'),(104,61,'wwwddddwww'),(108,65,'ghhiiiiho'),(110,66,'hhiiipppo'),(111,67,'hhpppdo'),(110,68,'hhddddo'),(110,69,'hhdrrdo'),(110,70,'hhddio'),(110,71,'whhdo'),(110,72,'wwhho'),(110,73,'whhho'),(105,92,'gwgggg'),(104,93,'wwgggg'),(103,94,'wwgggg'),(102,95,'wwwgggg'),(101,96,'wwwgggg'),(100,97,'wwwwgggg')])
save(hit,'hit')
# Reclining, curled feline: entirely new low contour and connected four paws.
SLEEP_BODY='''
........................oooooo
.....................ooohhhhhhoooo
..................ooohhhhiiiihhhhhhoo
...............ooohhhhhhiiiihhhhhhhhhoo
............ooohhhhhhhhiiiihhhhhhhhhhhhhoo
..........oohhhhhhhhhhiiiihhhhhhhhhhhhhhhhhoo
........oohhhhhhhhhhhiiiihhhhhhhhhhhhhhhhhhhhoo
......oohhhhhhhhhhhhiiiihhhhhhhhhhhhhhhhhhhhhhhhoo
.....ohhhhhhhhhhhhhiiihhhhhhhdddhhhhhhhhhhhhhhhhho
....ohhhhiiihhhhhhhhhhhhhhhddssdhhhhhhhhhhhhhhhhhhho
...ohhhhiiiihhhhhhhhhhhhhhddsssdhhhhhhhhhhhhhhhhhhhhho
..ohhhhiiiihhhddhhhhhhhhhhddssdhhhhhhhhdddhhhhhhhhhhhhho
.ohhhhiiiihhhddsdhhhhhhhhhddsdhhhhhhhddssdhhhhhhhhhhhhhhho
.ohhhiiiihhhddssdwhhhhhhhhdddwhhhhhhddsssdhhhhhhhhhhhhhhho
ohhhiiiihhhddsssdwwhhhhhhhddwwhhhhhhddssdwhhhhhhhhhhhhhhhho
ohhiiiihhhddsssdwwwwwhhhhhhwwwwhhhhhddsdwwhhhhhhhhhhhhhhhhho
ohhiiihhhhddssdwwwwwwwwhhhhwwwwwhhhhdddwwwwhhhhhhhhhhhhhhhho
ohhiihhhhhddsdwwwwwwwwwwwwwwwwwwwwwwwddwwwwwwhhhhhhhhhhhhhho
ohhhhhhhhhdddwwwwwwwwwwwwwwwwwwwwwwwwdwwwwwwwwhhhhhhhhhhhho
ohhhhhhhhhddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwhhhhhhhhhho
ohhhhhhhhhdwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwhhhhhhhho
ohhhhhhhhwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwhhhhhho
ohhhhhhhwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwWhhhho
ohhhhhhwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwWhhho
ohhhhhwwwwwwwggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwhho
ohhhhwwwwwwgggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwho
ohhhwwwwwwgggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgo
ohwwwwwwwgggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgo
ogwwwwwwggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgo
ogwwwwwgggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgo
.ogwwggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwgggo
.ogwgggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwgggggo
..ogggggggggggggggggggggggggggggggggggggggggggggggggo
...oggggggggggggggggggggggggggggggggggggggggggggggggo
....oggggggggggggggggggggggggggggggggggggggggggggggo
.....ogggggggggggggggggggggggggggggggggggggggggggo
......oggggggggggggggggggggggggggggggggggggggggggo
.......ogggggggggggggggggggggggggggggggggggggggo
........ogggggggggggggggggggggggggggggggggggggo
.........oggggggggggggggggggggggggggggggggggo
..........oogggggggggggggggggggggggggggggoo
............oooggggggggggggggggggggggooo
...............oooooooooooooooooooooo
'''.replace('W','w')
sleep_a=blank()
rows(sleep_a,15,78,SLEEP_BODY)
# Curled tail placed against the rump, its tip resting beside the hind foot.
rows(sleep_a,7,83,'''
........oooo
......oohhhhhoo
.....ohhiiihhhho
....ohhiidddhhho
...ohhiidssdhhho
..ohhiidssdhhhho
.ohhiiddsdhhhho
.ohhiidddhhhhho
ohhiidddhhhhhho
ohhiihhhhhhhhho
ohhihhhhhhhhwgo
ohhhwwwwwwwwggo
ohhwwwwwwwwggo
ohwwwwwwwwggo
ohwwwwwwwggo
ohwwwwwgggo
ohwwwwgggo
ohwwwwgggo
ohwwwwgggo
.ohwwwwgggo
.ohwwwwgggo
..ohwwwwgggo
..ohwwwwggggo
...ohwwddggggo
....ohwddsdgggo
.....ogddssdggo
......ogdddggggo
.......ogwwgggggo
........ogwwggggggo
.........ogwwgggggggo
..........ogwwggggggggo
...........ogwwgggggggggo
............ogwwggggggggggo
.............ogwwgggggggggggo
..............ogwwwwgggggggggo
...............ogwwwwwwgggggggo
................ogwwwwwwwgggggo
.................ogwwwdddgggggo
..................ogwddssdgggo
...................ogddsdgggo
....................ogdddgoo
.....................ooooo
''')
# Far limbs folded into the underside, soles underneath the chin.
rows(sleep_a,62,109,'''
..ovgggggggvo
.ovgggggggggvo
ovgggggggggggvo
ovggggggggggggvo
.ogggggggggggggvo
..ogggggggggggggvo
...ogggggggggggggvo
....ogggggggggggggvoooo
.....oggggggggggggggggvo
......ogwwwwwwwwwwgggggvo
.......ogwwwwdwwwwdggggvo
........ogwwwowwwgowgggvo
.........oooooooooooooo
''')
# Relaxed near forearm and massive under-chin paw.
rows(sleep_a,71,108,'''
..ohhwwwwwggo
.ohhhwwwwwgggo
ohhiwwwwwwgggggo
ohhwwwwwwwggggggo
ohhwwwwwwwgggggggo
ohhwwdddwwgggggggggo
.ohhwddsdwwggggggggggo
..ohhwddssdwwggggggggggo
...ohhwwdddwwwwwggggggggo
....ohhwwwwwwwwwwwwggggggooo
.....ohhwwwwwwwwwwwwwwwwhhhho
......ohhwwwwwwwwwwwwwwhhhhho
.......ohhwwdwwwwdwwwwwhhhhho
........ogwwowwwgowwwwgggggo
.........ogwowwwgowwwgggggo
..........oooooooooooooooo
''')
rows(sleep_a,63,89,'''
..............ooohhhho
............oohhiiiihho
..........oohhhiiiihhhho
........oohhhhiiiihhhhhho
......oohhhhhhiiihhhhhhhho
....oohhhhhhhhiiihhhhhhhhho
..oohhhhhhhhhhihhhhhhhhhhhho
.ohhhhhhhhhhhhhhhhhhhhhhhhho
ohhhhhhhhhhhhhhhhhhhhhhhhhho
ohhhhhhhhhhhhhhhhhhhhhhhwwho
ohhhhhhhhhhhhhhhhhhhhhhwwwho
ohhhhhhhhhhhhhhhhhhhhhwwwwho
ohhhhhhhhhhhhhhhhhhhhwwwwwho
ohhhhhhhhhhhhhhhhhhwwwwwwwho
ohhhhhhhhhhhhhhhhwwwwwwwwwho
ohhhhhhhhhhhhhhwwwwwwwwwwwho
ohhhhhhhhhhhhwwwwwwwwwwwwwho
oghhhhhhhhwwwwwwwwwwwwwwggo
ogwhhhhhwwwwwwwwwwwwwwgggo
ogwwhhhwwwwwwwwwwwwwwggggo
.ogwwhwwwwwwwwwwwwwwgggggo
.ogwwwwwwwwwwwwwwwwwgggggo
..ogwwwwwwwwwwwwwwwgggggo
...ogwwwwwwwwwwwwwgggggo
....ogwwwwwwwwwwwgggggo
.....ogwwwwwwwwwgggggo
......ogwwwwwwwgggggo
.......ogwwwwwgggggo
........ogwwwgggggo
.........ogggggggo
..........ooooooo
''')
# Resting tiger head with two fully closed eyes and chin supported by paws.
rows(sleep_a,84,82,'''
...oooo
..ohhwwhoo........oooo
.ohhddwwho.......ohhwwho
.ohdppdwwho.....ohddwwho
..ohppvwwhho...ohvvwwho
...ohvvwwhhhooohhwwho
..ohhwwhhhiiiihhhhhwho
.ohhhiiiiiiiiiiihhhhwho
ohhhiiiiiiiiiiiiihhhwwho
ohhiiiiihhdddhhhhhhhwwho
ohiiihhhddssddhhhhhhwwho
ohihhhhddsssddhhhhhhwwho
ohhhhhhddssddhhhhhhwwwho
ohhhhhhddssdhhhhhhhwwwho
ohhhhhhhdddhhhhhhhhwwwho
ohhhhhhhhhhhhhhhhhwwwddho
ohhhhddhhhhhhhhhhhwwdddwho
ohhhddsdhhhhhhhhhhhwwdddwho
ohhddssdwhhhhhhhhhhwwwhhhho
ohhddssddwhhhhhhhhhwwwhhhiiho
ohhwdddssdwghhhhhhhwwhhiiiihho
ohhwwdddsdwgwwwwwwwwhhiiihhpppo
.ohhwwwddwggwwwwwwwwhhiiihpppdo
..ohhwwwdwgggwwwwwwwghhhhhhddo
...ohhwwwwggggwwwwwwghhhhddo
....ohhwwwwgggggwwwwwghhhhhho
.....ohhwwwwggggggwwwwghhhhho
......ohhwwwwgggggggwwwghhhho
.......ohhhwwwwgggggwwwghhho
........ohhhhwwwwggggwwghho
.........ohhhhhwwwwwwwwho
..........ohhhhhhwwwwho
...........ohhhhhhwwho
............ohhhhwho
.............oooooo
''')
# Collar settles flat along the chest, still visibly gilded and jade-set.
rows(sleep_a,76,103,'''
..obclllycbo
.obclllyyycbo
obcllyjjjycbo
obclyjekjjycbo
obclyjekkjycbo
.obclyjjjyycbo
..obclyyyybcbo
...obcbbbbo
....obbbbo
....orproorpro
...orppprpppro
...orrrprrrpro
....orrrprrro
.....ooooooo
''')
patch(sleep_a,[(110,106,'hhh...hhh'),(113,108,'hh...hhh'),(38,113,'wwdddww'),(38,114,'wddssdww'),(38,115,'wddsssdw'),(39,116,'wddssdww'),(40,117,'wdddwww')])
save(sleep_a,'sleep_a','actions')
sleep_b=copy(sleep_a)
# Breathing lifts the connected flank and relaxes foretoe separation.
patch(sleep_b,[(53,96,'hhhhhwwwwww'),(53,97,'hhwwwwwwwww'),(54,98,'wwwwwwwwwww'),(56,99,'wwwwwwwwwww'),(98,119,'wwwwwwhhhhho'),(98,120,'wwwwwwhhhhho'),(98,121,'wwwwwwhwwhho'),(106,98,'wwwdddwho'),(106,99,'wwwdddwho'),(108,100,'whhhhho'),(78,114,'orprrpro'),(79,115,'orrprro'),(80,116,'oooooo'),(27,119,'ogwwwgggggo'),(28,120,'ogwddggggo'),(29,121,'ogdddgggo')])
save(sleep_b,'sleep_b','actions')

# Death is a stretched side-collapse, with shoulder and cheek on the ground.
dead=blank()
rows(dead,18,85,'''
.........................ooooooo
.....................oooohhhhhhhhoooo
..................ooohhhhhiiihhhhhhhhhoo
...............ooohhhhhhhiiiihhhhhhhhhhhhoo
............ooohhhhhhhhiiiihhhhhhhhhhhhhhhoo
.........ooohhhhhhhhhhiiiihhhhhhhhhhhhhhhhhhoo
.......oohhhhhhhhhhhhiiiihhhhhhhhhhhhhhhhhhhhhoo
.....oohhhhhhhhhhhhhiiihhhhhhhhhhhhhhhhhhhhhhhhoo
....ohhhhiiihhhhhhhhhhhhhhdddhhhhhhhhhhhhhhhhhhhhoo
...ohhhhiiiihhhhhhhhhhhhddssdhhhhhhhhhhhhhhhhhhhhhho
..ohhhhiiiihhhddhhhhhhhhddsssdhhhhhhhhhhhhhhhhhhhhhho
.ohhhhiiiihhhddsdhhhhhhhddssdhhhhhhhhdddhhhhhhhhhhhhho
ohhhhiiiihhhddssdwhhhhhhddsdhhhhhhhddssdhhhhhhhhhhhhhho
ohhhiiiihhhddsssdwwhhhhhdddwhhhhhhddsssdhhhhhhhhhhhhhho
ohhiiiihhhddsssdwwwwwhhhhddwwhhhhhddssdwhhhhhhhhhhhhhho
ohhiihhhhddssdwwwwwwwwhhhwwwwwhhhhddsdwwhhhhhhhhhhhhhho
ohhhhhhhhddsdwwwwwwwwwwwwwwwwwwwwwwdddwwwwhhhhhhhhhhhho
ohhhhhhhhdddwwwwwwwwwwwwwwwwwwwwwwwddwwwwwwhhhhhhhhhhho
ohhhhhhhhddwwwwwwwwwwwwwwwwwwwwwwwwdwwwwwwwwhhhhhhhhhho
ohhhhhhhhdwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwhhhhhhhhho
ohhhhhhhwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwWhhhhhho
ohhhhhhwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwhhhhhho
ohhhhhwwwwwwwggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwhhhho
ohhhhwwwwwwgggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwho
ohhhwwwwwwgggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgo
ohwwwwwwwgggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgo
ogwwwwwwggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgo
ogwwwwwgggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwgo
.ogwwggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwggo
.ogwgggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwgggo
..ogggggggggggggggggggggggggggggggggggggggggggggggo
...oggggggggggggggggggggggggggggggggggggggggggggggo
....oggggggggggggggggggggggggggggggggggggggggggggo
.....oggggggggggggggggggggggggggggggggggggggggggo
......oggggggggggggggggggggggggggggggggggggggggo
.......ogggggggggggggggggggggggggggggggggggggggo
........oggggggggggggggggggggggggggggggggggggo
.........oogggggggggggggggggggggggggggggggoo
...........oooggggggggggggggggggggggggooo
..............ooooooooooooooooooooooo
'''.replace('W','w'))
# Limp tail forms a low S rather than the standing hooked tail.
rows(dead,7,86,'''
....oooo
...ohhhhoo
..ohhiiihoo
.ohhiiddhho
ohhiidssdhho
ohhiidssdhho
.ohhiiddhho
..ohhiidhho
...ohhiihho
....ohhihho
.....ohhhho
......ohhhho
.......ohhhho
........ohhhho
.........ohhhho
..........ohhhho
...........ohhhho
............ohhhho
.............ohhhho
..............ohddho
...............odddho
................ogddho
.................ogwgho
..................ogwwho
...................ogwwho
....................ogwwho
.....................ogwwho
......................ogwwho
.......................ogwwho
........................ogwwo
.........................ogwo
..........................ooo
''')
# Stretched rear paw, slack toes.
rows(dead,27,112,'''
.ohhwwwwwwgggo
ohhwwwwwwwwgggo
ohhwwwwwwwwwwwggo
ohhwwwwwdddwwwwwwwggo
.ohhwwwddsdwwwwwwwwwwggo
..ohhwwwdddwwwwwwwwwwwwwggoo
...ohhwwwwwwwwwwwwwwwwwwwwwhho
....ohhwwwwwwwwwwwwwwwwwwhhhho
.....ohhwwwwwwwwwwwwwwwwwhhhho
......ogwwwwwwwdwwwwwdwwwwgggo
.......ogwwwwwwowwwwwowwwwggo
........ogwwwwwowwwwwowwwggo
.........ooooooooooooooooo
''')
# Far front leg visible below a fallen shoulder.
rows(dead,73,112,'''
..ovgggggggvo
.ovgggggggggvo
ovgggggggggggvo
ovggggggggggggvo
.oggggggggggggggvo
..ogggggggggggggggvo
...oggggggggggggggggvo
....ogggggggggggggggggvo
.....ogwwwwwwwwwwwwggggvo
......ogwwwwdwwwwdwwgggvo
.......ogwwwowwwgowwgggvo
........ooooooooooooooo
''')
rows(dead,84,111,'''
.ohhwwwwwwwggo
ohhwwwwwwwwgggo
ohhwwwwwwwwwwwggo
ohhwwwwwdddwwwwwwwggo
.ohhwwwddsdwwwwwwwwwwggo
..ohhwwwdddwwwwwwwwwwwwggo
...ohhwwwwwwwwwwwwwwwwwwggoo
....ohhwwwwwwwwwwwwwwwwwhhhho
.....ohhwwwwwwwwwwwwwwwwhhhho
......ogwwwdwwwwdwwwwwwwwggo
.......ogwwowwwwowwwwwwwggo
........ogwowwwwowwwwwwggo
.........ooooooooooooooo
''')
rows(dead,62,96,'''
..............ooohhhho
............oohhiiiihho
..........oohhhiiiihhhho
........oohhhhiiiihhhhhho
......oohhhhhhiiihhhhhhhho
....oohhhhhhhhiiihhhhhhhhho
..oohhhhhhhhhhihhhhhhhhhhhho
.ohhhhhhhhhhhhhhhhhhhhhhhhho
ohhhhhhhhhhhhhhhhhhhhhhhhhho
ohhhhhhhhhhhhhhhhhhhhhhhwwho
ohhhhhhhhhhhhhhhhhhhhhhwwwho
ohhhhhhhhhhhhhhhhhhhhhwwwwho
ohhhhhhhhhhhhhhhhhhhhwwwwwho
ohhhhhhhhhhhhhhhhhhwwwwwwwho
ohhhhhhhhhhhhhhhhwwwwwwwwwho
ohhhhhhhhhhhhhhwwwwwwwwwwwho
ohhhhhhhhhhhhwwwwwwwwwwwwwho
oghhhhhhhhwwwwwwwwwwwwwwggo
ogwhhhhhwwwwwwwwwwwwwwgggo
ogwwhhhwwwwwwwwwwwwwwggggo
.ogwwhwwwwwwwwwwwwwwgggggo
.ogwwwwwwwwwwwwwwwwwgggggo
..ogwwwwwwwwwwwwwwwgggggo
...ogwwwwwwwwwwwwwgggggo
....ogwwwwwwwwwwwgggggo
.....ogwwwwwwwwwgggggo
......ogwwwwwwwgggggo
.......ogwwwwwgggggo
........ooooooooooo
''')
# Flattened skull, shut eye, slack pink tongue on the ground.
rows(dead,84,89,'''
....oooo
...ohhwwhoo
..ohhddwwhhoo........oooo
.ohdppdwwhhhho......ohhwwho
..ohppvwwhhhhhooooohhhwwho
...ohvvwwhhiiiiiiihhhhwho
..ohhwwhiiiiiiiiiiihhhwwho
.ohhhiiiiiiiiiiiiiiiihhwwho
ohhhiiiiiiihhdddhhhhhhhwwho
ohhiiiiihhhhddssddhhhhhwwwho
ohiiihhhhhhddsssddhhhhhwwwho
ohihhhhhhhddssddhhhhhhwwwwho
ohhhhhhhhhddssdhhhhhhwwwwwho
ohhhhhhhhhhdddhhhhhhhwwwwwho
ohhhhhhhhhhhhhhhhhhhwwwdddho
ohhhhddhhhhhhhhhhhhhwwdddwwo
ohhhddsdhhhhhhhhhhhhwwwdddwho
ohhddssdwhhhhhhhhhhhwwwhhhho
ohhddssddwhhhhhhhhhhwwhhiiiho
ohhwdddssdwghhhhhhhhwwhhiiihho
ohhwwdddsdwgwwwwwwwwwghhiiihhpo
.ohhwwwddwggwwwwwwwwwghhiiipppdo
..ohhwwwdwgggwwwwwwwwghhhddrrdo
...ohhwwwwggggwwwwwwwwghddrppdo
....ohhwwwwgggggwwwwwwghdrpppdo
.....ohhwwwwggggggwwwwwgddppdo
......ohhhwwwwgggggwwwwghdddo
.......ohhhhwwwwggggwwwghhho
........ohhhhhwwwwwwwwwghho
.........ohhhhhhwwwwwwwgho
..........ohhhhhhwwwwwgo
...........ohhhhhwwwwgo
............ohhhhhwwgo
.............oooooooo
''')
rows(dead,74,106,'''
..obclllycbo
.obclllyyycbo
obcllyjjjycbo
obclyjekjjycbo
obclyjekkjycbo
.obclyjjjyycbo
..obclyyyybcbo
...obcbbbbo
....obbbbo
....orproorpro
...orppprpppro
...orrrprrrpro
....orrrprrro
.....ooooooo
''')
patch(dead,[(114,115,'hh...hh'),(112,117,'hhhh...hh'),(97,117,'gggwwhh'),(98,118,'ggwwhhh')])
save(dead,'dead')
# Roar: raised chest, tipped skull and a mouth-directed pressure source.
ROAR_HEAD='''
.......ooo
......ohhho
.....ohhiihho........ooo
....ohhddiihho......ohhho
....ohdpddiho......ohddiho
....ohdppdiho.....ohdddiho
....ohvppvho....ohhvvvho
....ohwwwwhoooohhhhwwho
...ohhwwiiiiiiihhhhhwho
..ohhhiiiiiiiiiiiihhhwho
.ohhhiiiiiiiiiiiiiihhhwho
.ohhiiiiihhdddhhhhhhhwwho
ohhiiihhhddssddhhhhhhwwho
ohhiihhhddsssddhhhhhhwwho
ohhhhhhddssddhhhhhhwwwwho
ohhhhhhddssdhhhhhhhwwwwho
ohhhhhhhdddhhhhhhhhwwwwho
ohhhhhhhhhhhhhhhhhhwwdddho
ohhhhddhhhhhhhhhhwwwddlyldho
ohhhddsdhhhhhhhhhwwdlyoldhho
ohhddssdwhhhhhhhhwwddooodhho
ohhddssddwhhhhhhhwwwhhhhhhho
ohhwdddssdwghhhhhwwwhhhiiiho
ohhwwdddsdwgwwwwwghhhiiihhppo
.ohhwwwddwggwwwwwghhhiiihpppdo
..ohhwwwdwgggwwwwghhhhddrrrdo
...ohhwwwwggggwwwghhddrrrppdo
....ohhwwwwggggwwghddrrrpppdo
.....ohhwwwwggggwgddrrrrpppdo
......ohhwwwwgggggdrrrrpppdo
.......ohhwwwwggggdrrrpppdo
........ohhhwwwwggdrrpppdo
.........ohhhhwwggddpppdo
..........ohhhhhwwdddhio
...........ohhhhhwwdhio
............ohhhhhwwho
.............ohhhhwwho
..............ohhhwho
...............ohhho
................ooo
'''
def roar_posture():
    g=copy(base)
    erase(g,76,21,50,75)
    rows(g,75,49,'''
+.........ohhiiiihho
+........ohhhiiiihhho
+.......ohhhhiiiihhhhho
+......ohhhhhiiiihhhhhho
+.....ohhhhhhiiihhhhhhhho
+....ohhhhhhhiiihhhhhhhhhho
+...ohhhhhhhhihhhhhhhhhhhhho
+..ohhhhhhhhhhhhhhhhhhhhhhhho
+.ohhhhhhhhhhhhhhhhhhhhhhhhho
+ohhhhhhhhhhhhhhhhhhhhhhhhhho
+ohhhhhhhhhhhhhhhhhhhhhhhhhho
+ohhhhhhhdddhhhhhhhhhhhhhhwwho
+ohhhhhhddssdhhhhhhhhhhhhhwwho
+ohhhhhddsssdhhhhhhhhhhhhwwwho
+ohhhhhddssdwhhhhhhhhhhhwwwwho
+ohhhhhhdddwwhhhhhhhhhhwwwwwho
+ohhhhhhhddwwwhhhhhhhhhwwwwwho
+ohhhhhhhhdwwwwhhhhhhhhwwwwwho
+ohhhhhhhhhwwwwwhhhhhhhwwwwwho
+ohhhhhhhhwwwwwwwwhhhhwwwwwwho
+ohhhhhhhwwwwwwwwwwhhwwwwwwwho
+ohhhhhhwwwwwwwwwwwwwwwwwwwggo
+ohhhhhwwwwwwwwwwwwwwwwwwwgggo
+ohhhhwwwwwwwwwwwwwwwwwwwggggo
+ohhhwwwwwwwwwwwwwwwwwwwgggggo
+ohhwwwwwwwwwwwwwwwwwwwggggggo
+ohwwwwwwwwwwwwwwwwwwwgggggggo
+ogwwwwwwwwwwwwwwwwwwggggggggo
+ogwwwwwwwwwwwwwwwwwgggggggggo
+.ogwwwwwwwwwwwwwwwwggggggggo
+..ogwwwwwwwwwwwwwwwgggggggo
+...ogwwwwwwwwwwwwwwggggggo
+....ogwwwwwwwwwwwwwgggggo
+.....ogwwwwwwwwwwwwggggo
+......ogwwwwwwwwwwwgggo
+.......ogwwwwwwwwwwggo
+........ogwwwwwwwwwgo
+.........ogwwwwwwwgo
+..........ogwwwwwgo
+...........ogwwwgo
+............ogwgo
+.............ooo
+'''.replace('+',''))
    erase(g,84,89,23,11)
    replace(g,86,80,'''
ohhwwwwwwwwwggggggo
ohhwwwwwwwwgggggggo
.ohhwwwwwwwgggggggo
.ohhwwwwwwggggggggo
..ohhwwwwwggggggggo
..ohhwwwwgggggggggo
...ohhwwwgggggggggo
...ohhwwwgggggggggo
....ohhwwwwgggggggo
....ohhwwwwwggggggo
....ohhwwwwwwgggggo
.....ohhwwwwwgggggo
.....ohhwwwwwwggggo
......ohhwwwwwwgggo
......ohhwwwwwwgggo
......ohhwwwwwwgggo
......ohhwwwwwwwggo
......ohhwwwwwwwwho
......ohhwwwwwwwwho
......ohhwwwwwwwwho
''',21)
    rows(g,77,88,'''
ovggggggggvo
ovggggggggvo
ovggddggggvo
ovgdddggggvo
ovgdddggggvo
ovggddggggvo
ovggggggggvo
ovggggggggvo
ovggggggggvo
ovggggggggvo
ovggggggggvo
ovggggggggvo
ovggggggggvo
''')
    rows(g,78,28,ROAR_HEAD)
    rows(g,78,62,'''
+.....obclllcbo
+....obclllyycbo
+...obclllyyycbo
+..obcllyjjjyycbo
+.obcllyjekjjycbo
+obcllyjekkkjycbo
+obclyjkkkkjjycbo
+obclyyjjjjtyycbo
+.obcllyyyyyycbo
+..obcllyyyycbo
+...obcllyycbo
+....obclycbo
+.....obbbbo
+......orpro.orpro
+.....orpproorppro
+.....orrproorrpro
+......orproorrpro
+.......orproorpro
+........orro.orro
+.........oo..oo
+'''.replace('+',''))
    # Claws dig into earth, each rooted at a toe, with angled wrist folds.
    patch(g,[(95,104,'hwwdddwwwho'),(95,105,'hwwddsdwwho'),(95,106,'hwwwdddwwho'),(95,107,'hwwwwddwwho'),(95,108,'hwwwwwdwwho'),(100,120,'wwdwwwwdwwwho'),(100,121,'wwowwwwowwwho'),(100,122,'whohwwhohwwho'),(100,123,'hiohhhiohhhho'),(99,124,'oiooooioooooo'),(76,121,'ogwwdwwdwwgvo'),(76,122,'ogwwowwowwgvo'),(76,123,'ohioohioooooo')])
    return g
skill_a=roar_posture()
# Preparation partially closes jaw around a compact turquoise pressure knot.
patch(skill_a,[(101,53,'hddrrrrdo'),(101,54,'hdrrrddo'),(101,55,'hddtttdo'),(101,56,'hdtjkjtdo'),(101,57,'hdjkeejdo'),(101,58,'hdjkkkjdo'),(101,59,'hdtjjjtdo'),(101,60,'hhdddih'),(101,61,'whhddho'),(101,62,'wwhhhho'),(101,63,'wwhhho'),(101,64,'whhho'),(101,65,'hhhh'),(101,66,'hhh')])
rows(skill_a,86,65,'''
..tjjjt
.tjekjjt
tjkeekjjt
.tjkkjjt
..tjjjt
...ttt
''')
rows(skill_a,106,54,'''
..jj
.jkkj
jkekj
.jkkj
..jj
''')
# Gathered vapour curls from the clasp into the actual jaw.
rows(skill_a,97,65,'''
.....jt
....jkj
...jkjt
..jkj
.jkj
jt
''')
save(skill_a,'skill_a','actions')

skill_b=roar_posture()
# Interior mouth remains visible behind the anchored bright pressure throat.
patch(skill_b,[(101,54,'drrrppdo'),(101,55,'drrpppdo'),(101,56,'drrptjjo'),(101,57,'drrjkeej'),(101,58,'drjkeeekj'),(101,59,'drrjkeej'),(101,60,'drrptjjo'),(101,61,'ddpppdo'),(102,62,'ddppdo')])
# Upper shockfront: broad convex right edge, torn concave inner pressure wall.
rows(skill_b,106,25,'''
............jk
............jkel
.............jkel
.............jkeely
..............jkeely
..............jkeely
.............jkeeelyc
............jkeeelycj
...........jkeeelycjj
...........jkeeelycjk
..........jkeeelycjkk
..........jkeeelycjkek
..........jkeeelycjkek
.........jkeeelycjkekj
.........jkeeelycjkekj
..........jkeelycjkekj
..........jkeelycjkekj
..........jkeelycjkekj
.........jkeelycjkekj
.........jkeelycjkekj
........jkeeelycjkekj
.......jkeeelycjkekj
......jkeeelycjkekj
.....jkeeelycjkekj
....jkeeelycjkekj
...jkeeelycjkekj
..jkeeelycjkekj
.jkeeelycjkekj
jkeeelycjkekj
jkeelycjkekj
jkeelycjkek
jkeelycjk
jkeelycj
''')
# Lower shockfront unfolds from the same mouth, with a fat white pressure plane.
rows(skill_b,106,60,'''
jeklyj
.jeklycj
..jeklycjj
...jeklycjkk
....jeklycjkek
.....jeklycjkekj
......jeklycjkekj
.......jeklycjkekj
........jeklycjkekj
.........jeklycjkekj
.........jkeelycjkekj
..........jkeelycjkekj
..........jkeelycjkekj
...........jkeelycjkek
...........jkeelycjkek
...........jkeelycjkk
...........jkeelycjk
..........jkeeelycj
.........jkeeelycjj
........jkeeelycjj
.......jkeeelycjj
......jkeeelycjj
.....jkeeelycjj
.....jkeelycjj
......jkeelycj
.......jkeelycj
........jkeelycj
.........jkeelycj
..........jkeelyc
...........jekly
............jekl
.............jek
..............jk
...............j
''')
# Teeth and whiskers brace against the plume, body remains fully readable.
patch(skill_b,[(105,52,'hiio'),(105,53,'dio'),(104,62,'dhio'),(104,63,'hio'),(104,49,'hhh'),(106,48,'hhh'),(105,65,'hhhh'),(109,66,'hh')])
# Individually clipped and re-edged outer crest pixels preserve the transparent border.
patch(skill_b,[(125,36,'kj.'),(125,37,'kj.'),(125,38,'kj.'),(125,39,'kj.'),(125,40,'kj.'),(125,41,'kj.'),(125,42,'kj.'),(125,71,'kj.'),(125,72,'kj.'),(125,73,'kj.'),(125,74,'kj.')])
save(skill_b,'skill_b','actions')

skill_c=copy(base)
erase(skill_c,83,21,43,57)
# Lowered chin after roar, closed warm gold eye and altered ear/fur orientation.
rows(skill_c,84,38,'''
.....ooo
....ohhho.............ooo
...ohhiihho..........ohhho
..ohhddiihho........ohddiho
..ohdpddiihho......ohdddiho
..ohdppdihhhhoo...ohhvvvho
..ohvppvhhhhhhhooohhhwwho
..ohhwwhhhhiiiiiiihhhhwho
.ohhhhiiiiiiiiiiiiihhhwwho
ohhhhiiiiiiiiiiiiiiiihhwwho
ohhhiiiiihhddddhhhhhhhhwwho
ohhiiihhhddssddhhhhhhhwwwho
ohiihhhhddsssddhhhhhhhwwwho
ohhhhhhhddssddhhhhhhhwwwwho
ohhhhhhhddssdhhhhhhhwwwwwho
ohhhhhhhhdddhhhhhhhhwwwwwho
ohhhhhhhhhhhhhhhhhhhwwwddddho
ohhhhddhhhhhhhhhhhhhwwddlyldho
ohhhddsdhhhhhhhhhhhhwwdlyoldoho
ohhddssdwhhhhhhhhhhhwwwddooodho
ohhddssddwhhhhhhhhhhwwwphhhhhho
ohhwdddssdwghhhhhhhhwwwhhiiiihho
ohhwwdddsdwgwwwwwwwwghhiiiihhhpo
.ohhwwwddwggwwwwwwwwghhiiiihpppdo
..ohhwwwdwgggwwwwwwwghhhhhhdddo
...ohhwwwwggggwwwwwwwghhdddio
....ohhwwwwgggggwwwwwghhddio
.....ohhwwwwggggggwwwwwghhdo
......ohhhwwwwggggggwwwwghhho
.......ohhhhwwwwgggggwwwghhho
........ohhhhhwwwwggggwwwghho
.........ohhhhhhwwwwwwwwwho
..........ohhhhhwwwwwwwho
...........ohhhhhhwwwwho
............ohhhhhhwwho
.............ohhhhhwho
..............ohhhhho
...............ooooo
''')
rows(skill_c,84,69,'''
..obclllyycbo
.obcllyjjjycbo
obcllyjekjjycbo
obclyjekkjjycbo
.obclyjjjyyycbo
..obcllyyyycbo
...obcllyycbo
....obclycbo
.....obbbbo
.....orpro.orpro
....orpproorppro
....orrproorrpro
.....orproorrpro
......orro.orro
.......oo..oo
''')
# Three distinct broken wave fragments, spaced along the previous two fronts.
rows(skill_c,115,30,'''
....jk
...jkel
..jkeely
.jkeelyc
jkeelycj
.jkelycj
..jklycj
...jlyc
....jc
''')
rows(skill_c,119,54,'''
..j
.jkel
jkeely
jkelyc
.jlycj
..ycj
...j
''')
rows(skill_c,115,83,'''
jkeelycj
.jkeelycj
..jkeelycj
...jkelycj
....jklyc
.....jyc
......j
''')
# Forepaw unclenches and the wrist drops after pressure release.
patch(skill_c,[(95,105,'hwwwwddwwho'),(95,106,'hwwwwwdwwho'),(95,107,'hwwwwwwwwho'),(95,108,'hwwwwwwwwho'),(95,109,'hwwwwwwwwho'),(95,110,'hwwwwwwwwho'),(100,120,'wwdwwwwdwwwho'),(100,121,'wwowwwwowwwgo'),(100,122,'wgowwwgowwwgo'),(100,123,'wggggggggggo'),(100,124,'oooooooooooo')])
save(skill_c,'skill_c','actions')
# Decode every final grid, then make diagnostic sheets; source rows are authoritative.
sheet(['idle_a','idle_b','idle_c'],filename='idle-sheet')
sheet(['windup','move','attack','recover','hit','dead'],filename='battle-sheet')
sheet(['skill_a','skill_b','skill_c'],'actions','skill-sheet')
sheet(['poison_a','poison_b','stun_a','stun_b','sleep_a','sleep_b'],'actions','status-sheet')
