// 묶음 a1 — 담당 에이전트만 이 파일을 쓴다. 규격: src/assets/retroRoster.ts 머리 주석, 스킬 형식은 retroClassSkills.ts(RetroClassSkill).
// 이 파일은 scripts/asset-gen/pixel-fx/lib_r2w1.py --emit a1 로 만든다(직업 모듈 r2w1_<classKey>.py 의 SKILLS 가 정본).
import type { RetroRosterBatch } from "@/assets/retroRoster";

export const BATCH: RetroRosterBatch = {
  skills: [
    { id: "skill_valkyrie_thrust", classId: "class_valkyrie", actorId: "actor_valkyrie", name: "질풍 찌르기", level: 1, motion: "dash-strike", description: "바람을 감은 창으로 일직선으로 꿰뚫는다", layers: [{ key: "valkyrie_thrust", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_valkyrie_feather", classId: "class_valkyrie", actorId: "actor_valkyrie", name: "깃털 베기", level: 3, motion: "flurry", description: "흰 깃털이 흩날리는 세 번의 베기", layers: [{ key: "valkyrie_feather", anchor: "target", frame: 64, frames: 9 }] },
    { id: "skill_valkyrie_javelin", classId: "class_valkyrie", actorId: "actor_valkyrie", name: "투창", level: 5, motion: "shoot", description: "손에서 창을 던져 꽂아 넣는다", layers: [{ key: "valkyrie_javelin", anchor: "projectile", frame: 32, frames: 4 }, { key: "valkyrie_javelin_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_valkyrie_wings", classId: "class_valkyrie", actorId: "actor_valkyrie", name: "날개 방벽", level: 7, motion: "buff", description: "날개를 펼쳐 몸을 감싸고 방어를 올린다", layers: [{ key: "valkyrie_wings", anchor: "user", frame: 64, frames: 10 }] },
    { id: "skill_valkyrie_dive", classId: "class_valkyrie", actorId: "actor_valkyrie", name: "급강하", level: 10, motion: "leap-strike", description: "하늘 높이 올라 창끝으로 내리꽂는다", layers: [{ key: "valkyrie_dive", anchor: "target", frame: 128, frames: 10 }] },
    { id: "skill_valkyrie_lance_rain", classId: "class_valkyrie", actorId: "actor_valkyrie", name: "창우", level: 12, motion: "cast", description: "하늘에서 수많은 창을 쏟아 붓는다", layers: [{ key: "valkyrie_lance_rain", anchor: "screen", frame: 128, frames: 10 }, { key: "valkyrie_lance_hit", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_valkyrie_gale", classId: "class_valkyrie", actorId: "actor_valkyrie", name: "바람의 축복", level: 16, motion: "buff", description: "아군 모두에게 바람이 감겨 속도가 오른다", layers: [{ key: "valkyrie_gale", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_valkyrie_valhalla", classId: "class_valkyrie", actorId: "actor_valkyrie", name: "발할라 강림", level: 22, motion: "finisher", description: "천상의 문이 열리고 황금 창이 내려꽂히는 필살기", layers: [{ key: "valkyrie_valhalla_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "valkyrie_valhalla_hit", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_paladin_holy_slash", classId: "class_paladin", actorId: "actor_paladin", name: "성광검", level: 1, motion: "dash-strike", description: "성스러운 빛을 두른 검으로 십자를 그리며 벤다", layers: [{ key: "paladin_holy_slash", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_paladin_shield_faith", classId: "class_paladin", actorId: "actor_paladin", name: "신앙의 방패", level: 3, motion: "buff", description: "빛의 방패를 앞세워 방어를 올린다", layers: [{ key: "paladin_shield", anchor: "user", frame: 64, frames: 8 }] },
    { id: "skill_paladin_smite", classId: "class_paladin", actorId: "actor_paladin", name: "사악 강타", level: 5, motion: "leap-strike", description: "하늘에서 빛의 검이 내리꽂혀 악을 벤다", layers: [{ key: "paladin_smite", anchor: "target", frame: 64, frames: 9 }] },
    { id: "skill_paladin_lay_hands", classId: "class_paladin", actorId: "actor_paladin", name: "안수", level: 7, motion: "cast", description: "두 손에서 따스한 빛이 흘러 아군 하나를 치유한다", layers: [{ key: "paladin_hands", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_paladin_consecrate", classId: "class_paladin", actorId: "actor_paladin", name: "성역 선포", level: 10, motion: "cast", description: "발밑에 금빛 마법진을 펼쳐 성스러운 기둥을 세운다", layers: [{ key: "paladin_consecrate", anchor: "screen", frame: 128, frames: 10 }] },
    { id: "skill_paladin_aegis", classId: "class_paladin", actorId: "actor_paladin", name: "신의 가호", level: 12, motion: "buff", description: "육각 결계가 아군 모두를 감싼다", layers: [{ key: "paladin_aegis", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_paladin_halo_whirl", classId: "class_paladin", actorId: "actor_paladin", name: "성검 회전", level: 16, motion: "spin", description: "빛의 검을 휘둘러 적진을 도는 황금 원을 그린다", layers: [{ key: "paladin_whirl", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_paladin_excalibur", classId: "class_paladin", actorId: "actor_paladin", name: "엑스칼리버", level: 22, motion: "finisher", description: "갈라진 하늘에서 거대한 성검이 내려오는 필살기", layers: [{ key: "paladin_excalibur_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "paladin_excalibur_hit", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_red_mage_riposte", classId: "class_red_mage", actorId: "actor_red_mage", name: "리포스트", level: 1, motion: "dash-strike", description: "가는 검끝으로 급소를 세 번 꿰뚫는다", layers: [{ key: "red_mage_riposte", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_red_mage_flare_blade", classId: "class_red_mage", actorId: "actor_red_mage", name: "플레어 블레이드", level: 3, motion: "blink-strike", description: "불꽃을 두른 레이피어로 대각선으로 벤다", layers: [{ key: "red_mage_flare_blade", anchor: "target", frame: 64, frames: 9 }] },
    { id: "skill_red_mage_frost_orb", classId: "class_red_mage", actorId: "actor_red_mage", name: "프로스트 오브", level: 5, motion: "cast", description: "푸른 얼음 구슬을 쏘아 가시 결정으로 터뜨린다", layers: [{ key: "red_mage_frost_orb", anchor: "projectile", frame: 32, frames: 4 }, { key: "red_mage_frost_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_red_mage_double_cast", classId: "class_red_mage", actorId: "actor_red_mage", name: "이중 영창", level: 7, motion: "buff", description: "붉고 푸른 마법진 두 개가 겹쳐 돌며 마력을 높인다", layers: [{ key: "red_mage_double_cast", anchor: "user", frame: 64, frames: 10 }] },
    { id: "skill_red_mage_fleche", classId: "class_red_mage", actorId: "actor_red_mage", name: "플레슈", level: 10, motion: "flurry", description: "화살처럼 파고들며 다섯 갈래로 찌른다", layers: [{ key: "red_mage_fleche", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_red_mage_twin_bolt", classId: "class_red_mage", actorId: "actor_red_mage", name: "쌍색 번개", level: 12, motion: "cast", description: "붉은 번개와 푸른 번개가 엮여 적 모두를 친다", layers: [{ key: "red_mage_twin_bolt", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_red_mage_convert", classId: "class_red_mage", actorId: "actor_red_mage", name: "마력 전환", level: 16, motion: "buff", description: "붉은 구슬과 푸른 구슬이 서로를 돌며 마력이 순환한다", layers: [{ key: "red_mage_convert", anchor: "user", frame: 64, frames: 10 }] },
    { id: "skill_red_mage_catastrophe", classId: "class_red_mage", actorId: "actor_red_mage", name: "듀얼 카타스트로프", level: 22, motion: "finisher", description: "붉은 혜성과 푸른 혜성이 부딪쳐 터지는 필살기", layers: [{ key: "red_mage_catastrophe_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "red_mage_catastrophe_hit", anchor: "allTargets", frame: 64, frames: 10 }] },
  ],
  partyPixel: []
};
