// 묶음 b3(Monster1 8) — 담당 에이전트만 이 파일을 쓴다. 규격: src/assets/retroRoster.ts 머리 주석, 스킬 형식은 retroClassSkills.ts(RetroClassSkill).
// 생성: scripts/asset-gen/pixel-fx/gen_r2w5_b3_ts.py (표를 고치고 다시 돌린다). 새 이펙트 시트 그림: scripts/asset-gen/pixel-fx/r2w5_<직업 키>.py + <키>.py.
// 비인간형 몸이므로 motion 은 dash-strike·leap-strike·flurry·spin·cast·shoot·buff·finisher 만 쓴다(런타임이 몬스터 몸 동작에 매핑).
import type { RetroRosterBatch } from "@/assets/retroRoster";

export const BATCH: RetroRosterBatch = {
  skills: [
    // ── 슬라임 (monster1-0) ──
    { id: "skill_slime_pal_tackle", classId: "class_slime_pal", actorId: "actor_slime_pal", name: "몸통 박치기", level: 1, motion: "dash-strike", description: "말랑한 몸을 통째로 부딪친다", layers: [{ key: "guard_bash", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_slime_pal_acid", classId: "class_slime_pal", actorId: "actor_slime_pal", name: "산성 방울", level: 3, motion: "shoot", description: "몸에서 떼어 낸 산성 방울을 뱉는다", layers: [{ key: "mon_acid_blob", anchor: "projectile", frame: 32, frames: 4 }, { key: "mon_acid_splash", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_slime_pal_jelly_wall", classId: "class_slime_pal", actorId: "actor_slime_pal", name: "젤리 방벽", level: 5, motion: "buff", description: "몸을 부풀려 탱글한 젤리 막을 두른다", layers: [{ key: "slime_pal_jelly", anchor: "user", frame: 64, frames: 10 }] },
    { id: "skill_slime_pal_absorb", classId: "class_slime_pal", actorId: "actor_slime_pal", name: "흡수", level: 7, motion: "cast", description: "적의 기운을 빨아들여 제 몸을 채운다", layers: [{ key: "mon_drain", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_slime_pal_split", classId: "class_slime_pal", actorId: "actor_slime_pal", name: "분열", level: 10, motion: "buff", description: "몸을 둘로 나눠 분신이 공격을 받아낸다", layers: [{ key: "ninja_clone_smoke", anchor: "user", frame: 64, frames: 6 }] },
    { id: "skill_slime_pal_press", classId: "class_slime_pal", actorId: "actor_slime_pal", name: "대점프 짓누르기", level: 12, motion: "leap-strike", description: "높이 뛰어올라 적진 위로 떨어진다", layers: [{ key: "guard_quake", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_slime_pal_mend", classId: "class_slime_pal", actorId: "actor_slime_pal", name: "치유 점액", level: 16, motion: "cast", description: "맑은 점액이 아군 전체의 상처를 덮는다", layers: [{ key: "heal", anchor: "allAllies", frame: 64, frames: 8 }] },
    { id: "skill_slime_pal_king", classId: "class_slime_pal", actorId: "actor_slime_pal", name: "킹 슬라임", level: 22, motion: "finisher", description: "동료 슬라임이 모여 왕관 쓴 거대 슬라임이 되는 필살기", layers: [{ key: "slime_pal_king_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "mon_acid_splash", anchor: "allTargets", frame: 64, frames: 8 }] },
    // ── 붉은 악마 (monster1-1) ──
    { id: "skill_demon_trident", classId: "class_demon", actorId: "actor_demon", name: "삼지창 찌르기", level: 1, motion: "dash-strike", description: "삼지창으로 날카롭게 찌른다", layers: [{ key: "hero_pierce", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_demon_hellfire", classId: "class_demon", actorId: "actor_demon", name: "지옥불", level: 3, motion: "cast", description: "손바닥 위 불덩이를 던져 터뜨린다", layers: [{ key: "mage_fireball_orb", anchor: "projectile", frame: 32, frames: 4 }, { key: "mage_fire_burst", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_demon_pact", classId: "class_demon", actorId: "actor_demon", name: "악마의 계약", level: 5, motion: "buff", description: "피의 계약서에 서명해 힘을 끌어올린다", layers: [{ key: "demon_pact", anchor: "user", frame: 64, frames: 10 }] },
    { id: "skill_demon_pillar", classId: "class_demon", actorId: "actor_demon", name: "화염 기둥", level: 7, motion: "cast", description: "적 전원의 발밑에서 불기둥을 솟구치게 한다", layers: [{ key: "mon_flame_pillar", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_demon_dive", classId: "class_demon", actorId: "actor_demon", name: "급강하 찌르기", level: 10, motion: "leap-strike", description: "날아올랐다가 거꾸로 내리꽂는다", layers: [{ key: "hero_rising", anchor: "target", frame: 64, frames: 9 }] },
    { id: "skill_demon_hex", classId: "class_demon", actorId: "actor_demon", name: "저주의 불꽃", level: 12, motion: "cast", description: "보라 불꽃으로 적 전원을 저주한다", layers: [{ key: "mon_hex_flame", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_demon_gale", classId: "class_demon", actorId: "actor_demon", name: "날개 열풍", level: 16, motion: "spin", description: "날개를 휘돌려 뜨거운 바람으로 적진을 태운다", layers: [{ key: "mon_gale_screen", anchor: "screen", frame: 128, frames: 8 }, { key: "mon_burn", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_demon_inferno", classId: "class_demon", actorId: "actor_demon", name: "연옥의 문", level: 22, motion: "finisher", description: "지옥문을 열어 불길을 쏟아붓는 필살기", layers: [{ key: "demon_inferno_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "mon_dark_burn", anchor: "allTargets", frame: 64, frames: 8 }] },
    // ── 꼬마 오거 (monster1-2) ──
    { id: "skill_ogre_kid_club", classId: "class_ogre_kid", actorId: "actor_ogre_kid", name: "몽둥이 휘두르기", level: 1, motion: "dash-strike", description: "큰 몽둥이로 힘껏 후려친다", layers: [{ key: "mon_slam_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_ogre_kid_smash", classId: "class_ogre_kid", actorId: "actor_ogre_kid", name: "내려찍기", level: 3, motion: "leap-strike", description: "뛰어올라 몽둥이로 땅째 내려찍는다", layers: [{ key: "monk_earth_palm", anchor: "target", frame: 128, frames: 10 }] },
    { id: "skill_ogre_kid_tantrum", classId: "class_ogre_kid", actorId: "actor_ogre_kid", name: "떼쓰기", level: 5, motion: "flurry", description: "주먹을 마구 휘둘러 두들긴다", layers: [{ key: "monk_fist_flurry", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_ogre_kid_rock", classId: "class_ogre_kid", actorId: "actor_ogre_kid", name: "바위 던지기", level: 7, motion: "shoot", description: "주운 바위를 번쩍 들어 던진다", layers: [{ key: "mon_boulder", anchor: "projectile", frame: 32, frames: 4 }, { key: "mon_rock_burst", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_ogre_kid_whirl", classId: "class_ogre_kid", actorId: "actor_ogre_kid", name: "회전 몽둥이", level: 10, motion: "spin", description: "몽둥이를 든 채 빙글빙글 돌며 적진을 친다", layers: [{ key: "hero_whirl", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_ogre_kid_guts", classId: "class_ogre_kid", actorId: "actor_ogre_kid", name: "배짱", level: 12, motion: "buff", description: "배를 두드리며 함성을 질러 힘을 올린다", layers: [{ key: "hero_warcry", anchor: "user", frame: 128, frames: 10 }] },
    { id: "skill_ogre_kid_quake", classId: "class_ogre_kid", actorId: "actor_ogre_kid", name: "땅 울리기", level: 16, motion: "leap-strike", description: "발을 구르고 뛰어 땅을 갈라 놓는다", layers: [{ key: "mon_quake_crack", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_ogre_kid_giant", classId: "class_ogre_kid", actorId: "actor_ogre_kid", name: "거인의 한 방", level: 22, motion: "finisher", description: "거인 조상의 그림자가 몽둥이를 내리치는 필살기", layers: [{ key: "ogre_kid_giant_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "guard_fortress_slam", anchor: "allTargets", frame: 64, frames: 8 }] },
    // ── 유령 (monster1-3) ──
    { id: "skill_ghost_pal_chill", classId: "class_ghost_pal", actorId: "actor_ghost_pal", name: "서늘한 손길", level: 1, motion: "dash-strike", description: "차가운 손으로 스쳐 기운을 빼앗는다", layers: [{ key: "weaken", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_ghost_pal_possess", classId: "class_ghost_pal", actorId: "actor_ghost_pal", name: "빙의", level: 3, motion: "cast", description: "적의 몸에 스며들어 잠시 조종한다", layers: [{ key: "ghost_pal_possess", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_ghost_pal_fade", classId: "class_ghost_pal", actorId: "actor_ghost_pal", name: "투명화", level: 5, motion: "buff", description: "몸을 흐리게 해 공격을 흘려보낸다", layers: [{ key: "scout_afterimage", anchor: "user", frame: 64, frames: 8 }] },
    { id: "skill_ghost_pal_grudge", classId: "class_ghost_pal", actorId: "actor_ghost_pal", name: "원한의 저주", level: 7, motion: "cast", description: "해골 저주로 적의 힘을 깎는다", layers: [{ key: "mon_curse_skull", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_ghost_pal_wail", classId: "class_ghost_pal", actorId: "actor_ghost_pal", name: "통곡", level: 10, motion: "cast", description: "구슬픈 울음이 적 전원을 떨게 한다", layers: [{ key: "mon_wail_sky", anchor: "screen", frame: 128, frames: 8 }, { key: "mon_screech_ring", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_ghost_pal_wisp", classId: "class_ghost_pal", actorId: "actor_ghost_pal", name: "도깨비불", level: 12, motion: "shoot", description: "푸른 도깨비불을 날려 얼린다", layers: [{ key: "mon_frost_orb", anchor: "projectile", frame: 32, frames: 4 }, { key: "mon_frost_burst", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_ghost_pal_siphon", classId: "class_ghost_pal", actorId: "actor_ghost_pal", name: "영혼 흡수", level: 16, motion: "cast", description: "적의 영혼을 빨아 제 힘으로 바꾼다", layers: [{ key: "mon_drain", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_ghost_pal_parade", classId: "class_ghost_pal", actorId: "actor_ghost_pal", name: "백귀야행", level: 22, motion: "finisher", description: "유령 행렬이 밤하늘을 가로지르는 필살기", layers: [{ key: "ghost_pal_parade_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "witch_nightmare_hit", anchor: "allTargets", frame: 64, frames: 8 }] },
    // ── 해골병 (monster1-4) ──
    { id: "skill_skeleton_pal_slash", classId: "class_skeleton_pal", actorId: "actor_skeleton_pal", name: "뼈 베기", level: 1, motion: "dash-strike", description: "날 세운 뼈로 크게 벤다", layers: [{ key: "mon_cleave_arc", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_skeleton_pal_bone_throw", classId: "class_skeleton_pal", actorId: "actor_skeleton_pal", name: "뼈 던지기", level: 3, motion: "shoot", description: "제 갈비뼈를 뽑아 빙글 던진다", layers: [{ key: "dog_bone", anchor: "projectile", frame: 32, frames: 4 }, { key: "dog_bone_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_skeleton_pal_rebuild", classId: "class_skeleton_pal", actorId: "actor_skeleton_pal", name: "재조립", level: 5, motion: "buff", description: "흩어진 뼈를 다시 맞춰 몸을 추스른다", layers: [{ key: "ninja_log_puff", anchor: "user", frame: 64, frames: 8 }] },
    { id: "skill_skeleton_pal_bone_arrow", classId: "class_skeleton_pal", actorId: "actor_skeleton_pal", name: "뼈 화살", level: 7, motion: "shoot", description: "뼈 화살을 날려 꿰뚫는다", layers: [{ key: "mon_bone_arrow", anchor: "projectile", frame: 32, frames: 4 }, { key: "mon_arrow_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_skeleton_pal_rattle", classId: "class_skeleton_pal", actorId: "actor_skeleton_pal", name: "해골 연타", level: 10, motion: "flurry", description: "달각거리며 쉴 새 없이 두들긴다", layers: [{ key: "scout_flurry", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_skeleton_pal_whirl", classId: "class_skeleton_pal", actorId: "actor_skeleton_pal", name: "뼈 회오리", level: 12, motion: "spin", description: "뼈를 흩뿌리며 회전해 적진을 벤다", layers: [{ key: "hero_whirl", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_skeleton_pal_death_curse", classId: "class_skeleton_pal", actorId: "actor_skeleton_pal", name: "죽음의 저주", level: 16, motion: "cast", description: "해골 저주로 적을 쇠약하게 한다", layers: [{ key: "mon_curse_skull", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_skeleton_pal_legion", classId: "class_skeleton_pal", actorId: "actor_skeleton_pal", name: "해골 군단", level: 22, motion: "finisher", description: "땅에서 해골 병사들이 일어나 화살을 퍼붓는 필살기", layers: [{ key: "skeleton_pal_legion_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "mon_arrow_hit", anchor: "allTargets", frame: 64, frames: 8 }] },
    // ── 좀비 (monster1-5) ──
    { id: "skill_zombie_pal_bite", classId: "class_zombie_pal", actorId: "actor_zombie_pal", name: "물어뜯기", level: 1, motion: "dash-strike", description: "달려들어 이빨로 물어뜯는다", layers: [{ key: "mon_fang_bite", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_zombie_pal_rot", classId: "class_zombie_pal", actorId: "actor_zombie_pal", name: "썩은 숨", level: 3, motion: "cast", description: "썩은 숨결을 뿜어 적 전원을 괴롭힌다", layers: [{ key: "mon_rot_cloud", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_zombie_pal_claw", classId: "class_zombie_pal", actorId: "actor_zombie_pal", name: "할퀴기", level: 5, motion: "flurry", description: "손톱으로 마구 할퀸다", layers: [{ key: "mon_claw_rake", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_zombie_pal_undying", classId: "class_zombie_pal", actorId: "actor_zombie_pal", name: "불사", level: 7, motion: "buff", description: "쓰러져도 다시 일어나는 끈질김으로 버틴다", layers: [{ key: "cleric_revive", anchor: "user", frame: 64, frames: 12 }] },
    { id: "skill_zombie_pal_pounce", classId: "class_zombie_pal", actorId: "actor_zombie_pal", name: "덮치기", level: 10, motion: "leap-strike", description: "몸을 던져 덮치고 물어뜯는다", layers: [{ key: "mon_devour_jaws", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_zombie_pal_plague", classId: "class_zombie_pal", actorId: "actor_zombie_pal", name: "역병", level: 12, motion: "cast", description: "독한 역병을 퍼뜨린다", layers: [{ key: "poison", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_zombie_pal_grave", classId: "class_zombie_pal", actorId: "actor_zombie_pal", name: "무덤 손", level: 16, motion: "cast", description: "땅을 가르고 무덤의 손들이 적을 붙잡는다", layers: [{ key: "mon_quake_crack", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_zombie_pal_horde", classId: "class_zombie_pal", actorId: "actor_zombie_pal", name: "좀비 떼", level: 22, motion: "finisher", description: "땅을 뚫고 좀비 무리가 밀려드는 필살기", layers: [{ key: "zombie_pal_horde_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "mon_rot_cloud", anchor: "allTargets", frame: 64, frames: 10 }] },
    // ── 사신 (monster1-6) ──
    { id: "skill_reaper_scythe", classId: "class_reaper", actorId: "actor_reaper", name: "낫 베기", level: 1, motion: "dash-strike", description: "커다란 낫으로 X자를 긋는다", layers: [{ key: "mon_scythe_x", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_reaper_harvest", classId: "class_reaper", actorId: "actor_reaper", name: "영혼 수확", level: 3, motion: "cast", description: "적의 영혼 일부를 거둬 간다", layers: [{ key: "mon_drain", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_reaper_mark", classId: "class_reaper", actorId: "actor_reaper", name: "사신의 표식", level: 5, motion: "cast", description: "해골 표식을 새겨 적을 죽음에 가깝게 한다", layers: [{ key: "reaper_mark", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_reaper_shadow", classId: "class_reaper", actorId: "actor_reaper", name: "그림자 베기", level: 7, motion: "flurry", description: "그림자처럼 스며들어 거듭 벤다", layers: [{ key: "scout_backstab", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_reaper_death_spin", classId: "class_reaper", actorId: "actor_reaper", name: "죽음의 회전", level: 10, motion: "spin", description: "낫을 크게 돌려 적진을 쓸어 벤다", layers: [{ key: "mon_cleave_arc", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_reaper_aura", classId: "class_reaper", actorId: "actor_reaper", name: "명계의 기운", level: 12, motion: "buff", description: "검은 기운을 둘러 힘을 올린다", layers: [{ key: "mon_demon_aura", anchor: "user", frame: 64, frames: 8 }] },
    { id: "skill_reaper_dread", classId: "class_reaper", actorId: "actor_reaper", name: "공포", level: 16, motion: "cast", description: "텅 빈 눈으로 노려봐 적 전원을 얼어붙게 한다", layers: [{ key: "mon_gaze_screen", anchor: "screen", frame: 128, frames: 8 }, { key: "weaken", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_reaper_doom", classId: "class_reaper", actorId: "actor_reaper", name: "즉사의 낫", level: 22, motion: "finisher", description: "거대한 달 앞에서 낫이 내려오는 필살기", layers: [{ key: "reaper_doom_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "mon_scythe_x", anchor: "allTargets", frame: 64, frames: 10 }] },
    // ── 수인 전사 (monster1-7) ──
    { id: "skill_minotaur_pal_axe", classId: "class_minotaur_pal", actorId: "actor_minotaur_pal", name: "도끼 내려치기", level: 1, motion: "dash-strike", description: "큰 도끼를 머리 위에서 내려친다", layers: [{ key: "mon_cleave_arc", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_minotaur_pal_horn", classId: "class_minotaur_pal", actorId: "actor_minotaur_pal", name: "뿔 돌진", level: 3, motion: "dash-strike", description: "뿔을 앞세워 흙먼지를 일으키며 들이받는다", layers: [{ key: "mon_tusk_hit", anchor: "target", frame: 64, frames: 8 }, { key: "mon_charge_dust", anchor: "user", frame: 64, frames: 6 }] },
    { id: "skill_minotaur_pal_rage", classId: "class_minotaur_pal", actorId: "actor_minotaur_pal", name: "광포", level: 5, motion: "buff", description: "콧김을 뿜으며 몸이 붉게 달아오른다", layers: [{ key: "hero_flame_aura", anchor: "user", frame: 64, frames: 6 }] },
    { id: "skill_minotaur_pal_split_earth", classId: "class_minotaur_pal", actorId: "actor_minotaur_pal", name: "대지 가르기", level: 7, motion: "leap-strike", description: "뛰어올라 도끼로 땅을 갈라 적진을 흔든다", layers: [{ key: "mon_quake_crack", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_minotaur_pal_pummel", classId: "class_minotaur_pal", actorId: "actor_minotaur_pal", name: "난타", level: 10, motion: "flurry", description: "주먹과 도끼 자루로 연달아 두들긴다", layers: [{ key: "monk_fist_flurry", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_minotaur_pal_whirl", classId: "class_minotaur_pal", actorId: "actor_minotaur_pal", name: "회전 도끼", level: 12, motion: "spin", description: "도끼를 든 채 회전해 모두를 벤다", layers: [{ key: "hero_whirl", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_minotaur_pal_bellow", classId: "class_minotaur_pal", actorId: "actor_minotaur_pal", name: "황소 포효", level: 16, motion: "cast", description: "땅을 울리는 포효로 적 전원을 움츠러들게 한다", layers: [{ key: "mon_roar_ring", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_minotaur_pal_labyrinth", classId: "class_minotaur_pal", actorId: "actor_minotaur_pal", name: "미궁의 분노", level: 22, motion: "finisher", description: "미궁의 벽이 무너지며 도끼가 떨어지는 필살기", layers: [{ key: "minotaur_pal_labyrinth_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "guard_fortress_slam", anchor: "allTargets", frame: 64, frames: 8 }] },
  ],
  partyPixel: [
    { chip: "monster1-0", cell: 48, motion: "hop", idleFrameMs: 220, rows: 5, art: 2 },
    { chip: "monster1-1", cell: 64, motion: "swoop", idleFrameMs: 150, rows: 5, art: 2 },
    { chip: "monster1-2", cell: 64, motion: "stomp", idleFrameMs: 300, rows: 5, art: 2 },
    { chip: "monster1-3", cell: 64, motion: "float", idleFrameMs: 200, rows: 5, art: 2 },
    { chip: "monster1-4", cell: 48, motion: "dash", idleFrameMs: 200, rows: 5, art: 2 },
    { chip: "monster1-5", cell: 64, motion: "stomp", idleFrameMs: 340, rows: 5, art: 2 },
    { chip: "monster1-6", cell: 64, motion: "float", idleFrameMs: 220, rows: 5, art: 2 },
    { chip: "monster1-7", cell: 64, motion: "stomp", idleFrameMs: 300, rows: 5, art: 2 },
  ]
};
