// 묶음 b5(Monster3 8) — 담당 에이전트만 이 파일을 쓴다. 규격: src/assets/retroRoster.ts 머리 주석, 스킬 형식은 retroClassSkills.ts(RetroClassSkill).
// 생성: scripts/asset-gen/pixel-fx/gen_r2w5_b5_ts.py (표를 고치고 다시 돌린다). 새 이펙트 시트 그림: scripts/asset-gen/pixel-fx/r2w5_<직업 키>.py + <키>.py.
// 비인간형 몸이므로 motion 은 dash-strike·leap-strike·flurry·spin·cast·shoot·buff·finisher 만 쓴다(런타임이 몬스터 몸 동작에 매핑).
import type { RetroRosterBatch } from "@/assets/retroRoster";

export const BATCH: RetroRosterBatch = {
  skills: [
    // ── 세이렌 (monster3-0) ──
    { id: "skill_siren_talon", classId: "class_siren", actorId: "actor_siren", name: "발톱 급습", level: 1, motion: "dash-strike", description: "날아들어 새 발톱으로 할퀸다", layers: [{ key: "mon_claw_rake", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_siren_song", classId: "class_siren", actorId: "actor_siren", name: "유혹의 노래", level: 3, motion: "cast", description: "달콤한 노랫소리가 적 전원을 잠재운다", layers: [{ key: "bard_notes_blue", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_siren_shriek", classId: "class_siren", actorId: "actor_siren", name: "고음 파열", level: 5, motion: "shoot", description: "귀를 찢는 고음을 쏘아 친다", layers: [{ key: "bard_sonic_wave", anchor: "projectile", frame: 32, frames: 4 }, { key: "bard_sonic_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_siren_charm", classId: "class_siren", actorId: "actor_siren", name: "매혹", level: 7, motion: "cast", description: "분홍 음표로 적을 홀려 한편을 치게 한다", layers: [{ key: "siren_charm", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_siren_feather", classId: "class_siren", actorId: "actor_siren", name: "깃털 폭풍", level: 10, motion: "spin", description: "날개를 휘돌려 깃털 칼날을 흩뿌린다", layers: [{ key: "mon_gale_screen", anchor: "screen", frame: 128, frames: 8 }, { key: "scout_knife_hit", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_siren_tide", classId: "class_siren", actorId: "actor_siren", name: "밀물의 노래", level: 12, motion: "cast", description: "바닷물이 밀려와 적진을 삼킨다", layers: [{ key: "mon_wave_screen", anchor: "screen", frame: 128, frames: 10 }, { key: "ninja_splash", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_siren_hymn", classId: "class_siren", actorId: "actor_siren", name: "바다의 찬가", level: 16, motion: "buff", description: "잔잔한 노래가 아군 전체를 치유한다", layers: [{ key: "bard_hymn", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_siren_aria", classId: "class_siren", actorId: "actor_siren", name: "침몰의 아리아", level: 22, motion: "finisher", description: "폭풍 바다 위 거대한 노래가 배를 가라앉히는 필살기", layers: [{ key: "siren_aria_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "bard_sonic_hit", anchor: "allTargets", frame: 64, frames: 8 }] },
    // ── 라미아 (monster3-1) ──
    { id: "skill_lamia_fang", classId: "class_lamia", actorId: "actor_lamia", name: "독니", level: 1, motion: "dash-strike", description: "뱀처럼 몸을 뻗어 독니를 박는다", layers: [{ key: "mon_sting", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_lamia_coil", classId: "class_lamia", actorId: "actor_lamia", name: "휘감기", level: 3, motion: "dash-strike", description: "긴 꼬리로 적을 휘감아 조인다", layers: [{ key: "lamia_coil", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_lamia_tail", classId: "class_lamia", actorId: "actor_lamia", name: "꼬리 채찍", level: 5, motion: "spin", description: "꼬리를 크게 휘둘러 적진을 후려친다", layers: [{ key: "monk_whirl_kick", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_lamia_venom", classId: "class_lamia", actorId: "actor_lamia", name: "독 안개", level: 7, motion: "cast", description: "독 안개를 퍼뜨려 적 전원을 중독시킨다", layers: [{ key: "mon_spore_cloud", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_lamia_gaze", classId: "class_lamia", actorId: "actor_lamia", name: "석화의 눈", level: 10, motion: "cast", description: "뱀의 눈으로 노려봐 몸을 굳힌다", layers: [{ key: "mon_gaze_screen", anchor: "screen", frame: 128, frames: 8 }, { key: "weaken", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_lamia_shed", classId: "class_lamia", actorId: "actor_lamia", name: "허물 벗기", level: 12, motion: "buff", description: "낡은 허물을 벗고 새 비늘로 회복한다", layers: [{ key: "druid_regrowth", anchor: "user", frame: 64, frames: 10 }] },
    { id: "skill_lamia_spit", classId: "class_lamia", actorId: "actor_lamia", name: "독액 뱉기", level: 16, motion: "shoot", description: "산성 독액을 뱉어 적을 녹인다", layers: [{ key: "mon_acid_blob", anchor: "projectile", frame: 32, frames: 4 }, { key: "witch_poison_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_lamia_serpent", classId: "class_lamia", actorId: "actor_lamia", name: "대사(大蛇) 강림", level: 22, motion: "finisher", description: "거대한 뱀의 혼이 똬리를 틀어 적을 조이는 필살기", layers: [{ key: "lamia_serpent_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "mon_bandage_wrap", anchor: "allTargets", frame: 64, frames: 10 }] },
    // ── 망령술사 (monster3-2) ──
    { id: "skill_wraith_mage_soul_bolt", classId: "class_wraith_mage", actorId: "actor_wraith_mage", name: "영혼탄", level: 1, motion: "shoot", description: "창백한 영혼 덩이를 쏘아 보낸다", layers: [{ key: "witch_drain_orb", anchor: "projectile", frame: 32, frames: 4 }, { key: "mon_ray_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_wraith_mage_drain", classId: "class_wraith_mage", actorId: "actor_wraith_mage", name: "영혼 흡수", level: 3, motion: "cast", description: "적의 영혼을 빨아 제 기운으로 삼는다", layers: [{ key: "wraith_mage_drain", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_wraith_mage_curse", classId: "class_wraith_mage", actorId: "actor_wraith_mage", name: "망령의 저주", level: 5, motion: "cast", description: "해골 저주로 적의 힘을 깎는다", layers: [{ key: "mon_curse_skull", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_wraith_mage_veil", classId: "class_wraith_mage", actorId: "actor_wraith_mage", name: "어둠의 장막", level: 7, motion: "buff", description: "검은 장막을 둘러 마법을 막는다", layers: [{ key: "witch_mirror", anchor: "user", frame: 64, frames: 10 }] },
    { id: "skill_wraith_mage_frost", classId: "class_wraith_mage", actorId: "actor_wraith_mage", name: "명계의 냉기", level: 10, motion: "cast", description: "명계의 찬 기운이 적 전원을 얼린다", layers: [{ key: "mon_frost_burst", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_wraith_mage_grasp", classId: "class_wraith_mage", actorId: "actor_wraith_mage", name: "망자의 손", level: 12, motion: "spin", description: "영혼들을 소용돌이치게 해 적진을 휘감는다", layers: [{ key: "mon_dark_crater", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_wraith_mage_wail", classId: "class_wraith_mage", actorId: "actor_wraith_mage", name: "망령의 곡소리", level: 16, motion: "cast", description: "망령의 울음이 하늘을 덮고 적을 떨게 한다", layers: [{ key: "mon_wail_sky", anchor: "screen", frame: 128, frames: 8 }, { key: "witch_nightmare_hit", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_wraith_mage_requiem", classId: "class_wraith_mage", actorId: "actor_wraith_mage", name: "영혼 수확제", level: 22, motion: "finisher", description: "수많은 영혼을 불러 모아 터뜨리는 필살기", layers: [{ key: "wraith_mage_harvest_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "mon_dark_burn", anchor: "allTargets", frame: 64, frames: 8 }] },
    // ── 서큐버스 (monster3-3) ──
    { id: "skill_succubus_claw", classId: "class_succubus", actorId: "actor_succubus", name: "손톱 할퀴기", level: 1, motion: "dash-strike", description: "날아들어 긴 손톱으로 할퀸다", layers: [{ key: "mon_backstab_slash", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_succubus_kiss", classId: "class_succubus", actorId: "actor_succubus", name: "입맞춤", level: 3, motion: "shoot", description: "하트를 날려 적을 홀린다", layers: [{ key: "succubus_kiss", anchor: "projectile", frame: 32, frames: 4 }, { key: "sleep", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_succubus_drain", classId: "class_succubus", actorId: "actor_succubus", name: "흡정", level: 5, motion: "cast", description: "적의 생기를 빨아 제 체력을 채운다", layers: [{ key: "witch_drain_beam", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_succubus_whip", classId: "class_succubus", actorId: "actor_succubus", name: "꼬리 채찍", level: 7, motion: "flurry", description: "뾰족한 꼬리로 연달아 찌른다", layers: [{ key: "scout_flurry", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_succubus_bats", classId: "class_succubus", actorId: "actor_succubus", name: "박쥐 떼", level: 10, motion: "cast", description: "박쥐 떼를 불러 적 전원을 물게 한다", layers: [{ key: "witch_bat_swarm", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_succubus_allure", classId: "class_succubus", actorId: "actor_succubus", name: "매혹의 향기", level: 12, motion: "cast", description: "분홍 안개가 적 전원을 흐리게 한다", layers: [{ key: "weaken", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_succubus_dance", classId: "class_succubus", actorId: "actor_succubus", name: "밤의 무도", level: 16, motion: "spin", description: "날개를 펴고 빙글 돌며 적진을 벤다", layers: [{ key: "samurai_petals", anchor: "screen", frame: 128, frames: 8 }, { key: "mon_backstab_slash", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_succubus_eclipse", classId: "class_succubus", actorId: "actor_succubus", name: "달그림자 연회", level: 22, motion: "finisher", description: "검은 달 아래 매혹의 연회를 여는 필살기", layers: [{ key: "witch_sabbath_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "witch_sabbath_hit", anchor: "allTargets", frame: 64, frames: 10 }] },
    // ── 개미귀신 (monster3-4) ──
    { id: "skill_mound_snap", classId: "class_mound", actorId: "actor_mound", name: "턱 물기", level: 1, motion: "dash-strike", description: "흙더미 속 집게 턱으로 덥석 문다", layers: [{ key: "mon_devour_jaws", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_mound_sand", classId: "class_mound", actorId: "actor_mound", name: "모래 뿌리기", level: 3, motion: "shoot", description: "모래 덩이를 뱉어 눈을 가린다", layers: [{ key: "mon_smoke_bomb", anchor: "projectile", frame: 32, frames: 4 }, { key: "mon_smoke_cloud", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_mound_shell", classId: "class_mound", actorId: "actor_mound", name: "흙 껍질", level: 5, motion: "buff", description: "흙을 두껍게 덮어 방어를 굳힌다", layers: [{ key: "mon_shell_barrier", anchor: "user", frame: 64, frames: 8 }] },
    { id: "skill_mound_pit", classId: "class_mound", actorId: "actor_mound", name: "모래 늪", level: 7, motion: "cast", description: "적 발밑을 모래 늪으로 바꿔 끌어당긴다", layers: [{ key: "mound_pit", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_mound_burrow", classId: "class_mound", actorId: "actor_mound", name: "땅속 습격", level: 10, motion: "leap-strike", description: "땅속으로 파고들었다가 적 밑에서 솟구친다", layers: [{ key: "earth", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_mound_boulder", classId: "class_mound", actorId: "actor_mound", name: "바위 토하기", level: 12, motion: "shoot", description: "삼킨 바위를 토해 던진다", layers: [{ key: "mon_boulder", anchor: "projectile", frame: 32, frames: 4 }, { key: "mon_rock_burst", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_mound_quake", classId: "class_mound", actorId: "actor_mound", name: "지반 붕괴", level: 16, motion: "leap-strike", description: "몸을 들썩여 땅을 무너뜨린다", layers: [{ key: "mon_quake_crack", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_mound_maw", classId: "class_mound", actorId: "actor_mound", name: "대지의 아가리", level: 22, motion: "finisher", description: "사막이 통째로 거대한 아가리가 되어 삼키는 필살기", layers: [{ key: "mound_maw_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "mon_rock_burst", anchor: "allTargets", frame: 64, frames: 8 }] },
    // ── 새끼 화룡 (monster3-5) ──
    { id: "skill_red_dragon_pal_bite", classId: "class_red_dragon_pal", actorId: "actor_red_dragon_pal", name: "물어뜯기", level: 1, motion: "dash-strike", description: "작은 송곳니로 힘껏 문다", layers: [{ key: "mon_fang_bite", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_red_dragon_pal_ember", classId: "class_red_dragon_pal", actorId: "actor_red_dragon_pal", name: "불씨 뱉기", level: 3, motion: "shoot", description: "입에서 불씨를 톡 뱉는다", layers: [{ key: "mage_fireball_orb", anchor: "projectile", frame: 32, frames: 4 }, { key: "fire", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_red_dragon_pal_breath", classId: "class_red_dragon_pal", actorId: "actor_red_dragon_pal", name: "화염 브레스", level: 5, motion: "cast", description: "숨을 모아 불길을 길게 뿜는다", layers: [{ key: "mon_fire_breath", anchor: "screen", frame: 128, frames: 10 }, { key: "mon_burn", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_red_dragon_pal_scale", classId: "class_red_dragon_pal", actorId: "actor_red_dragon_pal", name: "용린", level: 7, motion: "buff", description: "빛나는 비늘 방패를 세워 방어를 굳힌다", layers: [{ key: "guard_holy_shield", anchor: "user", frame: 64, frames: 10 }] },
    { id: "skill_red_dragon_pal_tail", classId: "class_red_dragon_pal", actorId: "actor_red_dragon_pal", name: "꼬리 휘두르기", level: 10, motion: "spin", description: "꼬리를 휘둘러 적진을 후려친다", layers: [{ key: "monk_whirl_kick", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_red_dragon_pal_wing", classId: "class_red_dragon_pal", actorId: "actor_red_dragon_pal", name: "날개 돌풍", level: 12, motion: "leap-strike", description: "날아올라 날개 바람과 함께 내리찍는다", layers: [{ key: "hero_meteor_impact", anchor: "target", frame: 128, frames: 10 }] },
    { id: "skill_red_dragon_pal_pillar", classId: "class_red_dragon_pal", actorId: "actor_red_dragon_pal", name: "화염 기둥", level: 16, motion: "cast", description: "적 전원의 발밑에서 불기둥이 솟는다", layers: [{ key: "mon_flame_pillar", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_red_dragon_pal_dragon", classId: "class_red_dragon_pal", actorId: "actor_red_dragon_pal", name: "화룡 각성", level: 22, motion: "finisher", description: "어미 용의 혼이 깨어나 불바다를 만드는 필살기", layers: [{ key: "red_dragon_pal_awaken_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "mage_meteor_blast", anchor: "allTargets", frame: 64, frames: 10 }] },
    // ── 업화 (monster3-6) ──
    { id: "skill_flame_spirit_flare", classId: "class_flame_spirit", actorId: "actor_flame_spirit", name: "불꽃 튀기", level: 1, motion: "dash-strike", description: "불꽃 몸으로 부딪쳐 태운다", layers: [{ key: "mage_fire_burst", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_flame_spirit_fireball", classId: "class_flame_spirit", actorId: "actor_flame_spirit", name: "화염구", level: 3, motion: "shoot", description: "몸에서 떼어 낸 불덩이를 던진다", layers: [{ key: "ranger_fire_arrow", anchor: "projectile", frame: 32, frames: 4 }, { key: "ranger_fire_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_flame_spirit_heat", classId: "class_flame_spirit", actorId: "actor_flame_spirit", name: "열기", level: 5, motion: "buff", description: "불꽃을 키워 공격을 끌어올린다", layers: [{ key: "hero_flame_aura", anchor: "user", frame: 64, frames: 6 }] },
    { id: "skill_flame_spirit_burn", classId: "class_flame_spirit", actorId: "actor_flame_spirit", name: "작열", level: 7, motion: "cast", description: "적 전원을 뜨거운 불꽃으로 감싼다", layers: [{ key: "mon_burn", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_flame_spirit_whirl", classId: "class_flame_spirit", actorId: "actor_flame_spirit", name: "불꽃 회오리", level: 10, motion: "spin", description: "불꽃 소용돌이가 되어 적진 발밑을 태운다", layers: [{ key: "mon_flame_pillar", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_flame_spirit_hellfire", classId: "class_flame_spirit", actorId: "actor_flame_spirit", name: "지옥불", level: 12, motion: "cast", description: "보라 불꽃으로 적을 저주한다", layers: [{ key: "mon_hex_flame", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_flame_spirit_meteor", classId: "class_flame_spirit", actorId: "actor_flame_spirit", name: "불비", level: 16, motion: "cast", description: "하늘에서 불타는 돌을 쏟아붓는다", layers: [{ key: "mage_meteor_rock", anchor: "projectile", frame: 32, frames: 4 }, { key: "mage_meteor_blast", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_flame_spirit_nova", classId: "class_flame_spirit", actorId: "actor_flame_spirit", name: "업화 폭발", level: 22, motion: "finisher", description: "몸을 태양처럼 부풀려 터뜨리는 필살기", layers: [{ key: "flame_spirit_nova_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "mon_burn", anchor: "allTargets", frame: 64, frames: 8 }] },
    // ── 마장군 (monster3-7) ──
    { id: "skill_demon_general_cleave", classId: "class_demon_general", actorId: "actor_demon_general", name: "암흑 베기", level: 1, motion: "dash-strike", description: "보랏빛 대검으로 크게 벤다", layers: [{ key: "mon_cleave_arc", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_demon_general_dark_wave", classId: "class_demon_general", actorId: "actor_demon_general", name: "암흑파", level: 3, motion: "shoot", description: "검을 휘둘러 암흑 검기를 날린다", layers: [{ key: "samurai_wind_wave", anchor: "projectile", frame: 32, frames: 4 }, { key: "mon_dark_burn", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_demon_general_command", classId: "class_demon_general", actorId: "actor_demon_general", name: "마군 호령", level: 5, motion: "buff", description: "호령으로 아군의 사기를 끌어올린다", layers: [{ key: "mon_howl_ring", anchor: "allAllies", frame: 64, frames: 8 }] },
    { id: "skill_demon_general_aura", classId: "class_demon_general", actorId: "actor_demon_general", name: "마기 해방", level: 7, motion: "buff", description: "몸에서 검은 마기를 뿜어 힘을 올린다", layers: [{ key: "mon_demon_aura", anchor: "user", frame: 64, frames: 8 }] },
    { id: "skill_demon_general_rush", classId: "class_demon_general", actorId: "actor_demon_general", name: "마검 연참", level: 10, motion: "flurry", description: "대검으로 쉴 새 없이 벤다", layers: [{ key: "samurai_moon", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_demon_general_whirl", classId: "class_demon_general", actorId: "actor_demon_general", name: "회전 대검", level: 12, motion: "spin", description: "대검을 크게 돌려 적진을 쓸어 벤다", layers: [{ key: "hero_whirl", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_demon_general_crater", classId: "class_demon_general", actorId: "actor_demon_general", name: "마계 강하", level: 16, motion: "leap-strike", description: "뛰어올라 대검으로 땅을 꿰뚫는다", layers: [{ key: "mon_dark_crater", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_demon_general_apocalypse", classId: "class_demon_general", actorId: "actor_demon_general", name: "종말의 검", level: 22, motion: "finisher", description: "하늘을 가르는 거대한 암흑 대검이 떨어지는 필살기", layers: [{ key: "demon_general_doom_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "mon_dark_crater", anchor: "allTargets", frame: 64, frames: 10 }] },
  ],
  partyPixel: [
    { chip: "monster3-0", cell: 64, rows: 5, motion: "swoop", idleFrameMs: 150 },
    { chip: "monster3-1", cell: 64, rows: 5, motion: "dash", idleFrameMs: 200 },
    { chip: "monster3-2", cell: 64, rows: 5, motion: "float", idleFrameMs: 240 },
    { chip: "monster3-3", cell: 64, rows: 5, motion: "swoop", idleFrameMs: 140 },
    { chip: "monster3-4", cell: 64, rows: 5, motion: "stomp", idleFrameMs: 340 },
    { chip: "monster3-5", cell: 64, rows: 5, motion: "breath", idleFrameMs: 260 },
    { chip: "monster3-6", cell: 64, rows: 5, motion: "float", idleFrameMs: 160 },
    { chip: "monster3-7", cell: 64, rows: 5, motion: "stomp", idleFrameMs: 300 },
  ]
};
