// 묶음 m4 — 3차 로스터(OPRN 자체 제작 Monster4 걷기 칩 8명: 숲·요괴). 담당 에이전트만 이 파일을 쓴다. 규격: src/assets/retroRoster.ts 머리 주석.
// 생성: python3 scripts/asset-gen/pixel-fx/gen_nm4_ts.py (표를 고치고 다시 돌린다). 새 이펙트 시트: scripts/asset-gen/pixel-fx/lib_nm4.py + <키>.py. 주의: 기믹(mechanic)은 이 TS 에 손으로 채웠다 — 생성기를 다시 돌리면 사라진다.
// 걷기 칩: scripts/asset-gen/oprn-charset/monster4.py, 전투 15칸: scripts/asset-gen/party-pixel/monster4-<i>.py (칩 × 1, 셀 48).
import type { RetroRosterBatch } from "@/assets/retroRoster";

export const BATCH: RetroRosterBatch = {
  skills: [
    // ── 트렌트 (monster4-0) ──
    { id: "skill_treant_branch_lash", classId: "class_treant", actorId: "actor_treant", name: "가지 채찍", level: 1, motion: "dash-strike", description: "굵은 가지 팔로 적을 후려친다", layers: [{ key: "druid_claw", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_treant_root_bind", classId: "class_treant", actorId: "actor_treant", name: "뿌리 휘감기", level: 3, motion: "cast", description: "땅속 뿌리가 솟아 적을 휘감아 묶는다", mechanic: { states: [{ id: "state_paralysis", chance: 45 }] }, layers: [{ key: "treant_roots", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_treant_bark_skin", classId: "class_treant", actorId: "actor_treant", name: "나무껍질", level: 5, motion: "buff", description: "두꺼운 나무껍질로 몸을 덮어 방어를 올린다", mechanic: { states: [{ id: "state_protect" }, { id: "state_defense_up" }] }, layers: [{ key: "druid_bark", anchor: "allAllies", frame: 64, frames: 8 }] },
    { id: "skill_treant_stomp", classId: "class_treant", actorId: "actor_treant", name: "고목 발구르기", level: 7, motion: "leap-strike", description: "뛰어올라 뿌리 발로 땅을 울린다", mechanic: { states: [{ id: "state_agility_down", chance: 45 }] }, layers: [{ key: "guard_quake", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_treant_taunt", classId: "class_treant", actorId: "actor_treant", name: "숲의 위압", level: 10, motion: "buff", description: "잎을 곤두세워 적의 시선을 끈다", mechanic: { states: [{ id: "state_defense_up" }, { id: "state_attack_up" }] }, layers: [{ key: "guard_taunt", anchor: "user", frame: 64, frames: 8 }] },
    { id: "skill_treant_thorn_spin", classId: "class_treant", actorId: "actor_treant", name: "가시 회전", level: 12, motion: "spin", description: "가시 돋친 가지를 휘돌려 적진을 쓸어 친다", mechanic: { hits: [0.4, 0.4, 0.4], states: [{ id: "state_deep_poison", chance: 40 }] }, layers: [{ key: "druid_thorn", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_treant_sap_heal", classId: "class_treant", actorId: "actor_treant", name: "수액 치유", level: 16, motion: "cast", description: "달콤한 수액으로 아군 전체를 치유한다", mechanic: { states: [{ id: "state_regen" }] }, layers: [{ key: "druid_regrowth", anchor: "target", frame: 64, frames: 10 }, { key: "cleric_mass_heal", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_treant_ancient_forest", classId: "class_treant", actorId: "actor_treant", name: "태고의 숲", level: 22, motion: "finisher", description: "땅에서 거대한 고목 숲이 솟아 적을 짓누르는 필살기", mechanic: { hits: [0.35, 0.35, 0.35, 0.35], states: [{ id: "state_agility_down", chance: 50 }] }, layers: [{ key: "treant_forest_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "druid_roots", anchor: "allTargets", frame: 64, frames: 10 }] },
    // ── 버섯 요정 (monster4-1) ──
    { id: "skill_mushroom_cap_bump", classId: "class_mushroom", actorId: "actor_mushroom", name: "갓 박치기", level: 1, motion: "dash-strike", description: "통통한 빨간 갓으로 들이받는다", layers: [{ key: "mon_slam_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_mushroom_heal_spore", classId: "class_mushroom", actorId: "actor_mushroom", name: "치유 포자", level: 3, motion: "cast", description: "금빛 포자를 뿌려 아군 하나를 치유한다", layers: [{ key: "mushroom_spores", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_mushroom_sleep_spore", classId: "class_mushroom", actorId: "actor_mushroom", name: "수면 포자", level: 5, motion: "cast", description: "보라 포자 구름으로 적 전원을 잠재운다", mechanic: { kind: "support", scope: "allEnemies", states: [{ id: "state_sleep", chance: 50 }] }, layers: [{ key: "mon_spore_cloud", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_mushroom_purify", classId: "class_mushroom", actorId: "actor_mushroom", name: "정화의 균사", level: 7, motion: "cast", description: "하얀 균사가 아군의 상태이상을 걷어낸다", mechanic: { states: [{ id: "state_poison", op: "remove" }, { id: "state_deep_poison", op: "remove" }, { id: "state_sleep", op: "remove" }, { id: "state_paralysis", op: "remove" }, { id: "state_silence", op: "remove" }] }, layers: [{ key: "cleric_purify", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_mushroom_poison_puff", classId: "class_mushroom", actorId: "actor_mushroom", name: "독버섯 연기", level: 10, motion: "shoot", description: "독 포자 덩이를 쏘아 적을 중독시킨다", mechanic: { states: [{ id: "state_poison", chance: 70 }] }, layers: [{ key: "mon_acid_blob", anchor: "projectile", frame: 32, frames: 4 }, { key: "poison", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_mushroom_ring_dance", classId: "class_mushroom", actorId: "actor_mushroom", name: "버섯 고리 춤", level: 12, motion: "spin", description: "빙글빙글 돌며 버섯 고리를 피워 적을 흩뜨린다", mechanic: { hits: [0.4, 0.4, 0.4], states: [{ id: "state_agility_down", chance: 40 }] }, layers: [{ key: "fairy_bloom", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_mushroom_mass_bloom", classId: "class_mushroom", actorId: "actor_mushroom", name: "포자 만개", level: 16, motion: "buff", description: "포자가 활짝 피어 아군 전체를 치유한다", mechanic: { states: [{ id: "state_regen" }] }, layers: [{ key: "heal", anchor: "allAllies", frame: 64, frames: 8 }] },
    { id: "skill_mushroom_fairy_ring", classId: "class_mushroom", actorId: "actor_mushroom", name: "요정의 버섯 고리", level: 22, motion: "finisher", description: "숲 전체에 버섯 고리가 피어 적을 잠재우고 생기를 빨아들이는 필살기", mechanic: { hits: [0.45, 0.45, 0.45], drain: 40, states: [{ id: "state_sleep", chance: 40 }] }, layers: [{ key: "mushroom_ring_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "sleep", anchor: "target", frame: 64, frames: 8 }] },
    // ── 갓파 (monster4-2) ──
    { id: "skill_kappa_sumo_butt", classId: "class_kappa", actorId: "actor_kappa", name: "스모 박치기", level: 1, motion: "dash-strike", description: "접시 머리를 앞세워 힘껏 들이받는다", layers: [{ key: "mon_slam_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_kappa_water_gun", classId: "class_kappa", actorId: "actor_kappa", name: "물대포", level: 3, motion: "shoot", description: "입으로 센 물줄기를 쏘아 맞힌다", mechanic: { states: [{ id: "state_wet", chance: 60 }] }, layers: [{ key: "kappa_water_jet", anchor: "projectile", frame: 32, frames: 4 }, { key: "ninja_splash", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_kappa_shell_guard", classId: "class_kappa", actorId: "actor_kappa", name: "등딱지 방어", level: 5, motion: "buff", description: "등딱지에 몸을 숨겨 방어를 올린다", mechanic: { states: [{ id: "state_protect" }, { id: "state_defense_up" }] }, layers: [{ key: "mon_shell_barrier", anchor: "user", frame: 64, frames: 8 }] },
    { id: "skill_kappa_palm_flurry", classId: "class_kappa", actorId: "actor_kappa", name: "손바닥 연타", level: 7, motion: "flurry", description: "물갈퀴 손바닥으로 빠르게 연달아 친다", mechanic: { hits: [0.4, 0.4, 0.4] }, layers: [{ key: "monk_whirl_kick", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_kappa_river_dive", classId: "class_kappa", actorId: "actor_kappa", name: "강물 다이빙", level: 10, motion: "leap-strike", description: "높이 뛰어 물을 튀기며 떨어진다", mechanic: { crit: 20, states: [{ id: "state_wet", chance: 50 }] }, layers: [{ key: "ninja_splash", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_kappa_cucumber", classId: "class_kappa", actorId: "actor_kappa", name: "오이 간식", level: 12, motion: "buff", description: "좋아하는 오이를 먹고 기운을 차린다", mechanic: { kind: "healing", scope: "self", power: 45, states: [{ id: "state_regen" }] }, layers: [{ key: "grandma_herb", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_kappa_whirlpool", classId: "class_kappa", actorId: "actor_kappa", name: "소용돌이", level: 16, motion: "cast", description: "적진에 물소용돌이를 일으켜 휩쓴다", mechanic: { formula: "b.hp / 5", element: "water", states: [{ id: "state_agility_down", chance: 40 }] }, layers: [{ key: "mon_wave_screen", anchor: "screen", frame: 128, frames: 10 }, { key: "ninja_splash", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_kappa_kappa_flood", classId: "class_kappa", actorId: "actor_kappa", name: "갓파 대홍수", level: 22, motion: "finisher", description: "접시의 물을 쏟아 강물이 적을 쓸어 가는 필살기", mechanic: { hits: [0.35, 0.35, 0.35, 0.35], hpCost: 15, element: "water", states: [{ id: "state_wet", chance: 60 }] }, layers: [{ key: "kappa_flood_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "ninja_splash", anchor: "allTargets", frame: 64, frames: 8 }] },
    // ── 구미호 (monster4-3) ──
    { id: "skill_kitsune_fox_claw", classId: "class_kitsune", actorId: "actor_kitsune", name: "여우 발톱", level: 1, motion: "dash-strike", description: "날렵하게 뛰어들어 발톱으로 할퀸다", layers: [{ key: "cat_claw", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_kitsune_foxfire", classId: "class_kitsune", actorId: "actor_kitsune", name: "여우불", level: 3, motion: "cast", description: "푸른 여우불을 날려 적과 그 둘레를 태운다", mechanic: { area: "circle" }, layers: [{ key: "kitsune_foxfire", anchor: "projectile", frame: 32, frames: 4 }, { key: "oni_warrior_ghostfire_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_kitsune_illusion", classId: "class_kitsune", actorId: "actor_kitsune", name: "환술", level: 5, motion: "cast", description: "환영을 보여 적의 눈을 속이고 혼란에 빠뜨린다", mechanic: { kind: "support", states: [{ id: "state_blind", chance: 70 }, { id: "state_berserk", chance: 40 }] }, layers: [{ key: "dancer_charm", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_kitsune_clone", classId: "class_kitsune", actorId: "actor_kitsune", name: "분신", level: 7, motion: "buff", description: "꼬리마다 분신을 만들어 회피를 올린다", mechanic: { kind: "support", scope: "self", states: [{ id: "state_evade" }] }, layers: [{ key: "ninja_clone_smoke", anchor: "user", frame: 64, frames: 6 }] },
    { id: "skill_kitsune_tail_spin", classId: "class_kitsune", actorId: "actor_kitsune", name: "꼬리 휘돌리기", level: 10, motion: "spin", description: "아홉 꼬리를 휘둘러 적진을 쓸어 친다", mechanic: { hits: [0.3, 0.3, 0.3, 0.3] }, layers: [{ key: "hero_whirl", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_kitsune_fox_wedding", classId: "class_kitsune", actorId: "actor_kitsune", name: "여우비", level: 12, motion: "cast", description: "해 뜬 날 비를 내려 아군 전체를 치유한다", mechanic: { states: [{ id: "state_regen" }] }, layers: [{ key: "heal", anchor: "allAllies", frame: 64, frames: 8 }] },
    { id: "skill_kitsune_spirit_shrine", classId: "class_kitsune", actorId: "actor_kitsune", name: "여우 신사", level: 16, motion: "buff", description: "신사의 여우 혼을 불러 마력을 모은다", mechanic: { kind: "healing", affects: "mp", scope: "self", power: 30 }, layers: [{ key: "shrine_maiden_fox", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_kitsune_nine_tails", classId: "class_kitsune", actorId: "actor_kitsune", name: "구미 염화", level: 22, motion: "finisher", description: "아홉 꼬리의 여우불이 원을 그려 적을 불사르는 필살기", mechanic: { hits: [0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16], hpCost: 12 }, layers: [{ key: "kitsune_ninefire_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "oni_warrior_ghostfire_hit", anchor: "target", frame: 64, frames: 8 }] },
    // ── 너구리 둔갑사 (monster4-4) ──
    { id: "skill_tanuki_belly_bump", classId: "class_tanuki", actorId: "actor_tanuki", name: "배치기", level: 1, motion: "dash-strike", description: "둥근 배로 퉁 튕겨 낸다", layers: [{ key: "mon_slam_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_tanuki_leaf_shuriken", classId: "class_tanuki", actorId: "actor_tanuki", name: "나뭇잎 표창", level: 3, motion: "shoot", description: "머리의 나뭇잎을 표창처럼 세 장 던진다", mechanic: { hits: [0.3, 0.3, 0.3] }, layers: [{ key: "tanuki_leaf", anchor: "projectile", frame: 32, frames: 4 }, { key: "scout_knife_hit", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_tanuki_belly_drum", classId: "class_tanuki", actorId: "actor_tanuki", name: "배 두드리기", level: 5, motion: "buff", description: "배를 둥둥 두드려 아군의 기운을 북돋는다", mechanic: { states: [{ id: "state_attack_up" }, { id: "state_agility_up" }] }, layers: [{ key: "bard_notes_red", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_tanuki_disguise", classId: "class_tanuki", actorId: "actor_tanuki", name: "둔갑", level: 7, motion: "buff", description: "연기 속에서 바위로 둔갑해 공격을 흘린다", mechanic: { states: [{ id: "state_protect" }, { id: "state_shell" }] }, layers: [{ key: "ninja_clone_smoke", anchor: "user", frame: 64, frames: 6 }] },
    { id: "skill_tanuki_lucky_coin", classId: "class_tanuki", actorId: "actor_tanuki", name: "행운의 동전", level: 10, motion: "shoot", description: "금화를 튕겨 적의 소지품을 슬쩍 훔친다", mechanic: { kind: "steal" }, layers: [{ key: "merchant_coin", anchor: "projectile", frame: 32, frames: 4 }, { key: "merchant_coin_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_tanuki_smoke_trick", classId: "class_tanuki", actorId: "actor_tanuki", name: "연기 장난", level: 12, motion: "cast", description: "둔갑 연기를 퍼뜨려 적 전원의 눈을 가린다", mechanic: { kind: "support", scope: "allEnemies", states: [{ id: "state_blind", chance: 70 }] }, layers: [{ key: "scout_smoke", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_tanuki_kettle_drop", classId: "class_tanuki", actorId: "actor_tanuki", name: "가마솥 낙하", level: 16, motion: "leap-strike", description: "가마솥으로 둔갑해 위에서 떨어져 둘레까지 덮친다", mechanic: { area: "circle" }, layers: [{ key: "mon_slam_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_tanuki_great_transform", classId: "class_tanuki", actorId: "actor_tanuki", name: "대둔갑", level: 22, motion: "finisher", description: "거대한 너구리로 둔갑해 나뭇잎 폭풍을 일으키는 필살기", mechanic: { hits: [0.28, 0.28, 0.28, 0.28, 0.28], states: [{ id: "state_blind", chance: 40 }] }, layers: [{ key: "tanuki_transform_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "scout_knife_hit", anchor: "allTargets", frame: 64, frames: 8 }] },
    // ── 이끼 골렘 (monster4-5) ──
    { id: "skill_golem_moss_rock_fist", classId: "class_golem_moss", actorId: "actor_golem_moss", name: "바위 주먹", level: 1, motion: "dash-strike", description: "무거운 바위 주먹으로 내려친다", layers: [{ key: "mon_rock_burst", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_golem_moss_earth_wall", classId: "class_golem_moss", actorId: "actor_golem_moss", name: "대지 방벽", level: 3, motion: "buff", description: "땅에서 이끼 돌벽을 세워 아군 전체를 지킨다", mechanic: { states: [{ id: "state_protect" }, { id: "state_defense_up" }] }, layers: [{ key: "golem_moss_wall", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_golem_moss_boulder", classId: "class_golem_moss", actorId: "actor_golem_moss", name: "바위 던지기", level: 5, motion: "shoot", description: "몸의 바위를 떼어 던진다", layers: [{ key: "mage_meteor_rock", anchor: "projectile", frame: 32, frames: 4 }, { key: "mon_rock_burst", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_golem_moss_moss_regen", classId: "class_golem_moss", actorId: "actor_golem_moss", name: "이끼 재생", level: 7, motion: "buff", description: "이끼가 자라 금 간 몸을 메운다", layers: [{ key: "druid_regrowth", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_golem_moss_quake", classId: "class_golem_moss", actorId: "actor_golem_moss", name: "지진", level: 10, motion: "leap-strike", description: "뛰어올라 땅을 내려찍어 모든 적을 흔든다", mechanic: { states: [{ id: "state_agility_down", chance: 45 }] }, layers: [{ key: "golem_pal_quake", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_golem_moss_stone_guard", classId: "class_golem_moss", actorId: "actor_golem_moss", name: "돌의 수호", level: 12, motion: "buff", description: "돌 방패로 아군을 감싸 지킨다", mechanic: { states: [{ id: "state_shell" }, { id: "state_protect" }] }, layers: [{ key: "guard_barrier", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_golem_moss_rune_pulse", classId: "class_golem_moss", actorId: "actor_golem_moss", name: "룬 파동", level: 16, motion: "cast", description: "가슴의 룬이 빛나 적 전원을 밀어내고 주문을 막는다", mechanic: { scope: "allEnemies", formula: "power * 0.5 + a.def * 1.5", states: [{ id: "state_silence", chance: 40 }] }, layers: [{ key: "guard_quake_ring", anchor: "screen", frame: 128, frames: 8 }, { key: "earth", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_golem_moss_mountain_fall", classId: "class_golem_moss", actorId: "actor_golem_moss", name: "산사태", level: 22, motion: "finisher", description: "산이 무너져 바위 가시가 적을 뒤덮는 필살기", mechanic: { hits: [0.28, 0.28, 0.28, 0.28, 0.28], states: [{ id: "state_paralysis", chance: 35 }] }, layers: [{ key: "golem_moss_landslide_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "mon_quake_crack", anchor: "allTargets", frame: 64, frames: 10 }] },
    // ── 얼음 요정 (monster4-6) ──
    { id: "skill_sprite_ice_ice_shard", classId: "class_sprite_ice", actorId: "actor_sprite_ice", name: "얼음 조각", level: 1, motion: "shoot", description: "뾰족한 얼음 조각을 쏘아 맞힌다", layers: [{ key: "mon_frost_orb", anchor: "projectile", frame: 32, frames: 4 }, { key: "mon_frost_burst", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_sprite_ice_freeze", classId: "class_sprite_ice", actorId: "actor_sprite_ice", name: "빙결", level: 3, motion: "cast", description: "적 하나를 얼음 속에 가둔다", mechanic: { states: [{ id: "state_stop", chance: 40 }] }, layers: [{ key: "sprite_ice_freeze", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_sprite_ice_wing_slap", classId: "class_sprite_ice", actorId: "actor_sprite_ice", name: "눈꽃 날개치기", level: 5, motion: "dash-strike", description: "날아들어 눈꽃 날개로 두 번 후려친다", mechanic: { hits: [0.5, 0.5] }, layers: [{ key: "mon_claw_rake", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_sprite_ice_frost_armor", classId: "class_sprite_ice", actorId: "actor_sprite_ice", name: "서리 갑옷", level: 7, motion: "buff", description: "서리 결정으로 몸을 둘러 방어를 올린다", mechanic: { states: [{ id: "state_shell" }, { id: "state_defense_up" }] }, layers: [{ key: "mage_mana_shield", anchor: "user", frame: 64, frames: 10 }] },
    { id: "skill_sprite_ice_blizzard", classId: "class_sprite_ice", actorId: "actor_sprite_ice", name: "눈보라", level: 10, motion: "cast", description: "모든 적 위에 눈보라와 얼음 기둥을 내린다", mechanic: { states: [{ id: "state_agility_down", chance: 60 }] }, layers: [{ key: "mage_blizzard", anchor: "allTargets", frame: 64, frames: 10 }, { key: "mage_snow", anchor: "screen", frame: 128, frames: 8 }] },
    { id: "skill_sprite_ice_ice_spin", classId: "class_sprite_ice", actorId: "actor_sprite_ice", name: "얼음 회오리", level: 12, motion: "spin", description: "빙글 돌며 얼음 조각을 흩뿌린다", mechanic: { hits: [0.3, 0.3, 0.3, 0.3] }, layers: [{ key: "dragonewt_frost", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_sprite_ice_snow_blessing", classId: "class_sprite_ice", actorId: "actor_sprite_ice", name: "눈의 축복", level: 16, motion: "buff", description: "하얀 눈이 내려 아군 전체를 치유한다", mechanic: { states: [{ id: "state_regen" }] }, layers: [{ key: "heal", anchor: "allAllies", frame: 64, frames: 8 }] },
    { id: "skill_sprite_ice_absolute_zero", classId: "class_sprite_ice", actorId: "actor_sprite_ice", name: "절대영도", level: 22, motion: "finisher", description: "세상을 얼리는 거대한 눈꽃이 피어 적을 얼리는 필살기", mechanic: { hits: [0.5, 0.5, 0.5], states: [{ id: "state_stop", chance: 40 }] }, layers: [{ key: "sprite_ice_zero_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "mon_frost_burst", anchor: "target", frame: 64, frames: 8 }] },
    // ── 만드라고라 (monster4-7) ──
    { id: "skill_mandrake_root_kick", classId: "class_mandrake", actorId: "actor_mandrake", name: "뿌리 발차기", level: 1, motion: "dash-strike", description: "잔뿌리 다리로 걷어찬다", layers: [{ key: "mon_tusk_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_mandrake_scream", classId: "class_mandrake", actorId: "actor_mandrake", name: "비명", level: 3, motion: "cast", description: "귀를 찢는 비명으로 적 전원을 기절시킨다", mechanic: { kind: "support", scope: "allEnemies", states: [{ id: "state_paralysis", chance: 50 }] }, layers: [{ key: "mandrake_scream", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_mandrake_herb", classId: "class_mandrake", actorId: "actor_mandrake", name: "약초", level: 5, motion: "cast", description: "잎을 떼어 아군 하나를 치유한다", mechanic: { states: [{ id: "state_poison", op: "remove" }] }, layers: [{ key: "grandma_herb", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_mandrake_leaf_blessing", classId: "class_mandrake", actorId: "actor_mandrake", name: "잎사귀 축복", level: 7, motion: "buff", description: "잎을 흔들어 아군 전체의 힘을 북돋는다", mechanic: { states: [{ id: "state_attack_up" }, { id: "state_regen" }] }, layers: [{ key: "cleric_blessing", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_mandrake_shriek_wave", classId: "class_mandrake", actorId: "actor_mandrake", name: "고음파", level: 10, motion: "shoot", description: "날카로운 음파를 쏘아 같은 줄의 적을 꿰뚫는다", mechanic: { area: "line", states: [{ id: "state_silence", chance: 40 }] }, layers: [{ key: "bard_sonic_wave", anchor: "projectile", frame: 32, frames: 4 }, { key: "bard_sonic_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_mandrake_uproot", classId: "class_mandrake", actorId: "actor_mandrake", name: "뿌리 뽑기", level: 12, motion: "spin", description: "땅에서 뛰쳐나와 뒹굴며 적진을 친다", mechanic: { hits: [0.45, 0.45, 0.45] }, layers: [{ key: "druid_roots", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_mandrake_toxic_sap", classId: "class_mandrake", actorId: "actor_mandrake", name: "독 수액", level: 16, motion: "cast", description: "쓴 독 수액을 뿌려 적의 힘을 깎는다", mechanic: { states: [{ id: "state_poison", chance: 70 }, { id: "state_attack_down", chance: 70 }] }, layers: [{ key: "weaken", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_mandrake_death_wail", classId: "class_mandrake", actorId: "actor_mandrake", name: "죽음의 울음", level: 22, motion: "finisher", description: "땅에서 뽑혀 나온 만드라고라의 대비명이 적을 쓰러뜨리는 필살기", mechanic: { formula: "b.hp / 3 + power / 2", hpCost: 20, states: [{ id: "state_doom", chance: 20 }] }, layers: [{ key: "mandrake_wail_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "mon_screech_ring", anchor: "allTargets", frame: 64, frames: 8 }] },
  ],
  partyPixel: [
    { chip: "monster4-0", cell: 48, motion: "stomp", idleFrameMs: 320, rows: 5 },
    { chip: "monster4-1", cell: 48, motion: "hop", idleFrameMs: 220, rows: 5 },
    { chip: "monster4-2", cell: 48, motion: "dash", idleFrameMs: 180, rows: 5 },
    { chip: "monster4-3", cell: 48, motion: "float", idleFrameMs: 200, rows: 5 },
    { chip: "monster4-4", cell: 48, motion: "hop", idleFrameMs: 240, rows: 5 },
    { chip: "monster4-5", cell: 48, motion: "stomp", idleFrameMs: 360, rows: 5 },
    { chip: "monster4-6", cell: 48, motion: "float", idleFrameMs: 160, rows: 5 },
    { chip: "monster4-7", cell: 48, motion: "hop", idleFrameMs: 200, rows: 5 },
  ]
};
