// 묶음 m5 — 3차 로스터(OPRN 자체 제작 Monster5 걷기 칩 8명: 저주받은 물건). 담당 에이전트만 이 파일을 쓴다. 규격: src/assets/retroRoster.ts 머리 주석.
// 걷기 칩: public/assets/generated/charsets/Monster5.png (scripts/asset-gen/oprn-charset/monster5.py).
// 전투 15칸: public/assets/generated/party-pixel/monster5-<i>.png (scripts/asset-gen/party-pixel/monster5-<i>.py + pp15_nm5.py).
// 새 이펙트 시트(<classKey>_ 접두): scripts/asset-gen/pixel-fx/<key>.py + lib_nm5.py. 나머지 레이어는 기존 시트 재사용(frame·frames 는 원 정의 그대로).
// 비인간형 몸이므로 blink-strike 는 쓰지 않는다.
import type { RetroRosterBatch } from "@/assets/retroRoster";

export const BATCH: RetroRosterBatch = {
  skills: [
    // ── 미믹 (monster5-0) ──
    { id: "skill_mimic_pal_snap", classId: "class_mimic_pal", actorId: "actor_mimic_pal", name: "뚜껑 물기", level: 1, motion: "dash-strike", description: "뛰어들어 뚜껑 이빨로 콱 문다", layers: [{ key: "mimic_pal_chomp", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_mimic_pal_tongue", classId: "class_mimic_pal", actorId: "actor_mimic_pal", name: "혀 채찍", level: 3, motion: "dash-strike", description: "긴 혀를 휘둘러 적을 후려친다", layers: [{ key: "mon_sting", anchor: "target", frame: 64, frames: 8 }, { key: "mon_charge_dust", anchor: "user", frame: 64, frames: 6 }] },
    { id: "skill_mimic_pal_lure", classId: "class_mimic_pal", actorId: "actor_mimic_pal", name: "보물 미끼", level: 5, motion: "buff", description: "금빛을 흘려 적의 시선을 끈다", layers: [{ key: "mimic_pal_lure", anchor: "user", frame: 64, frames: 8 }] },
    { id: "skill_mimic_pal_coin_spit", classId: "class_mimic_pal", actorId: "actor_mimic_pal", name: "금화 뱉기", level: 7, motion: "shoot", description: "삼켜 둔 금화를 쏘아 뱉는다", layers: [{ key: "merchant_coin", anchor: "projectile", frame: 32, frames: 4 }, { key: "merchant_coin_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_mimic_pal_lid_slam", classId: "class_mimic_pal", actorId: "actor_mimic_pal", name: "뚜껑 찍기", level: 10, motion: "leap-strike", description: "뛰어올라 무거운 몸으로 내려찍는다", layers: [{ key: "mon_slam_hit", anchor: "target", frame: 64, frames: 8 }, { key: "guard_quake_ring", anchor: "screen", frame: 128, frames: 8 }] },
    { id: "skill_mimic_pal_gnash", classId: "class_mimic_pal", actorId: "actor_mimic_pal", name: "이빨 난무", level: 12, motion: "flurry", description: "뚜껑을 딱딱 여닫으며 연달아 문다", layers: [{ key: "mimic_pal_gnash", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_mimic_pal_hoard", classId: "class_mimic_pal", actorId: "actor_mimic_pal", name: "보물 폭발", level: 16, motion: "spin", description: "몸을 굴려 금화와 보석을 적진에 흩뿌린다", layers: [{ key: "gambler_coin", anchor: "allTargets", frame: 64, frames: 8 }, { key: "hero_whirl", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_mimic_pal_devour", classId: "class_mimic_pal", actorId: "actor_mimic_pal", name: "통째로 삼키기", level: 22, motion: "finisher", description: "무대만 한 입을 벌려 적을 통째로 삼키는 필살기", layers: [{ key: "mimic_pal_maw_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "mon_devour_jaws", anchor: "target", frame: 64, frames: 10 }] },
    // ── 살아있는 갑옷 (monster5-1) ──
    { id: "skill_living_armor_cleave", classId: "class_living_armor", actorId: "actor_living_armor", name: "대검 내려베기", level: 1, motion: "dash-strike", description: "빈 갑옷이 대검을 크게 내려벤다", layers: [{ key: "mon_cleave_arc", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_living_armor_taunt", classId: "class_living_armor", actorId: "actor_living_armor", name: "철갑 도발", level: 3, motion: "buff", description: "투구 속 보라 눈을 빛내 적의 시선을 끈다", layers: [{ key: "guard_taunt", anchor: "user", frame: 64, frames: 8 }] },
    { id: "skill_living_armor_hollow", classId: "class_living_armor", actorId: "actor_living_armor", name: "빈 껍데기", level: 5, motion: "buff", description: "속이 빈 몸으로 공격을 흘려 방어를 높인다", layers: [{ key: "living_armor_hollow", anchor: "user", frame: 64, frames: 10 }] },
    { id: "skill_living_armor_soul_edge", classId: "class_living_armor", actorId: "actor_living_armor", name: "영혼 검", level: 7, motion: "dash-strike", description: "대검에 보라 영혼을 입혀 벤다", layers: [{ key: "living_armor_soul_edge", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_living_armor_guard_all", classId: "class_living_armor", actorId: "actor_living_armor", name: "망령 방진", level: 10, motion: "buff", description: "갑옷 망령들이 아군 전체 앞을 막아선다", layers: [{ key: "guard_barrier", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_living_armor_spin", classId: "class_living_armor", actorId: "actor_living_armor", name: "회전 대검", level: 12, motion: "spin", description: "몸통을 통째로 돌려 적 모두를 벤다", layers: [{ key: "berserker_whirl", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_living_armor_quake", classId: "class_living_armor", actorId: "actor_living_armor", name: "철갑 낙하", level: 16, motion: "leap-strike", description: "뛰어올라 쇳덩이 몸으로 땅을 울린다", layers: [{ key: "guard_quake", anchor: "allTargets", frame: 64, frames: 10 }, { key: "guard_quake_ring", anchor: "screen", frame: 128, frames: 8 }] },
    { id: "skill_living_armor_legion", classId: "class_living_armor", actorId: "actor_living_armor", name: "망령 군단", level: 22, motion: "finisher", description: "빈 갑옷 군단의 영혼 대검이 한꺼번에 떨어지는 필살기", layers: [{ key: "living_armor_legion_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "dark_knight_doom_hit", anchor: "allTargets", frame: 64, frames: 10 }] },
    // ── 초롱 귀신 (monster5-2) ──
    { id: "skill_lantern_ghost_wisp", classId: "class_lantern_ghost", actorId: "actor_lantern_ghost", name: "도깨비불", level: 1, motion: "cast", description: "푸른 도깨비불을 쏘아 태운다", layers: [{ key: "lantern_ghost_wisp", anchor: "projectile", frame: 32, frames: 4 }, { key: "oni_warrior_ghostfire_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_lantern_ghost_lick", classId: "class_lantern_ghost", actorId: "actor_lantern_ghost", name: "혀 핥기", level: 3, motion: "dash-strike", description: "긴 혀로 핥아 소름 돋게 한다", layers: [{ key: "mon_sting", anchor: "target", frame: 64, frames: 8 }, { key: "weaken", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_lantern_ghost_stare", classId: "class_lantern_ghost", actorId: "actor_lantern_ghost", name: "외눈 응시", level: 5, motion: "cast", description: "커다란 외눈으로 노려봐 적을 얼어붙게 한다", layers: [{ key: "lantern_ghost_eye", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_lantern_ghost_lure", classId: "class_lantern_ghost", actorId: "actor_lantern_ghost", name: "홀림불", level: 7, motion: "cast", description: "흔들리는 불빛으로 적 모두를 홀린다", layers: [{ key: "oni_warrior_parade_hit", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_lantern_ghost_light", classId: "class_lantern_ghost", actorId: "actor_lantern_ghost", name: "등불 인도", level: 10, motion: "buff", description: "따뜻한 초롱 빛이 아군을 감싸 회복시킨다", layers: [{ key: "lantern_ghost_glow", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_lantern_ghost_drain", classId: "class_lantern_ghost", actorId: "actor_lantern_ghost", name: "혼불 흡수", level: 12, motion: "cast", description: "적의 혼불을 빨아들여 자신을 채운다", layers: [{ key: "mon_drain", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_lantern_ghost_swarm", classId: "class_lantern_ghost", actorId: "actor_lantern_ghost", name: "여우불 무리", level: 16, motion: "cast", description: "도깨비불 무리가 적진을 휘돌며 태운다", layers: [{ key: "oni_warrior_ghostfire", anchor: "projectile", frame: 32, frames: 4 }, { key: "mon_hex_flame", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_lantern_ghost_parade", classId: "class_lantern_ghost", actorId: "actor_lantern_ghost", name: "백귀 초롱 행렬", level: 22, motion: "finisher", description: "밤하늘 가득 초롱 행렬이 지나가며 적을 불사르는 필살기", layers: [{ key: "lantern_ghost_parade_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "oni_warrior_parade_hit", anchor: "allTargets", frame: 64, frames: 8 }] },
    // ── 저주 인형 (monster5-3) ──
    { id: "skill_doll_scratch", classId: "class_doll", actorId: "actor_doll", name: "인형 할퀴기", level: 1, motion: "dash-strike", description: "실에 끌려 날아들어 할퀸다", layers: [{ key: "mon_claw_rake", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_doll_bind", classId: "class_doll", actorId: "actor_doll", name: "실 묶기", level: 3, motion: "cast", description: "흰 실로 적을 칭칭 묶어 움직임을 막는다", layers: [{ key: "doll_bind", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_doll_pin", classId: "class_doll", actorId: "actor_doll", name: "저주 바늘", level: 5, motion: "shoot", description: "저주 바늘을 던져 적의 힘을 깎는다", layers: [{ key: "ninja_needle", anchor: "projectile", frame: 32, frames: 4 }, { key: "doll_pin_curse", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_doll_puppet", classId: "class_doll", actorId: "actor_doll", name: "꼭두각시 조종", level: 7, motion: "buff", description: "아군에게 실을 이어 몸놀림을 빠르게 한다", layers: [{ key: "doll_strings", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_doll_mend", classId: "class_doll", actorId: "actor_doll", name: "꿰매기", level: 10, motion: "cast", description: "실과 바늘로 아군 하나의 상처를 꿰맨다", layers: [{ key: "doll_stitch", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_doll_hex_all", classId: "class_doll", actorId: "actor_doll", name: "짚인형 저주", level: 12, motion: "cast", description: "적 모두에게 저주의 표식을 새긴다", layers: [{ key: "sorceress_curse_mark", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_doll_mirror", classId: "class_doll", actorId: "actor_doll", name: "대신 받기", level: 16, motion: "buff", description: "인형이 아군 대신 저주와 상처를 받아낸다", layers: [{ key: "ninja_log_puff", anchor: "user", frame: 64, frames: 8 }, { key: "guard_barrier", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_doll_grand_puppet", classId: "class_doll", actorId: "actor_doll", name: "인형극의 막", level: 22, motion: "finisher", description: "하늘의 조종대가 적 모두를 실로 매달아 조종하는 필살기", layers: [{ key: "doll_theater_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "mon_curse_skull", anchor: "target", frame: 64, frames: 10 }] },
    // ── 마도서 (monster5-4) ──
    { id: "skill_book_demon_bite", classId: "class_book_demon", actorId: "actor_book_demon", name: "책장 물기", level: 1, motion: "dash-strike", description: "책장을 활짝 벌려 날아들어 문다", layers: [{ key: "mon_fang_bite", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_book_demon_rune_shot", classId: "class_book_demon", actorId: "actor_book_demon", name: "룬 탄환", level: 3, motion: "cast", description: "책장에서 룬 글자를 쏘아 보낸다", layers: [{ key: "book_demon_rune", anchor: "projectile", frame: 32, frames: 4 }, { key: "mage_missile_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_book_demon_paper_cut", classId: "class_book_demon", actorId: "actor_book_demon", name: "종이 칼날", level: 5, motion: "flurry", description: "날카로운 책장을 연달아 날려 벤다", layers: [{ key: "book_demon_paper_cut", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_book_demon_fire_page", classId: "class_book_demon", actorId: "actor_book_demon", name: "화염의 장", level: 7, motion: "cast", description: "불의 장을 펼쳐 불덩이를 날린다", layers: [{ key: "mage_fireball_orb", anchor: "projectile", frame: 32, frames: 4 }, { key: "mage_fire_burst", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_book_demon_frost_page", classId: "class_book_demon", actorId: "actor_book_demon", name: "빙결의 장", level: 10, motion: "cast", description: "얼음의 장을 읽어 적 모두에게 눈보라를 내린다", layers: [{ key: "mage_blizzard", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_book_demon_study", classId: "class_book_demon", actorId: "actor_book_demon", name: "금서 열람", level: 12, motion: "buff", description: "금지된 장을 읽어 아군의 마력을 끌어올린다", layers: [{ key: "scholar_runes", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_book_demon_barrage", classId: "class_book_demon", actorId: "actor_book_demon", name: "주문 난사", level: 16, motion: "cast", description: "펼친 모든 장의 주문을 한꺼번에 쏟아낸다", layers: [{ key: "book_demon_barrage", anchor: "allTargets", frame: 64, frames: 10 }, { key: "mage_chain_bolt", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_book_demon_apocrypha", classId: "class_book_demon", actorId: "actor_book_demon", name: "마지막 장", level: 22, motion: "finisher", description: "거대한 마도서가 하늘에서 펼쳐져 룬의 폭풍을 내리는 필살기", layers: [{ key: "book_demon_grimoire_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "mage_star_hit", anchor: "allTargets", frame: 64, frames: 8 }] },
    // ── 허수아비 (monster5-5) ──
    { id: "skill_scarecrow_reap", classId: "class_scarecrow", actorId: "actor_scarecrow", name: "낫질", level: 1, motion: "dash-strike", description: "기둥 발로 통통 다가가 낫을 휘두른다", layers: [{ key: "scarecrow_reap", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_scarecrow_crow_peck", classId: "class_scarecrow", actorId: "actor_scarecrow", name: "까마귀 쪼기", level: 3, motion: "shoot", description: "어깨의 까마귀를 날려 적을 쪼게 한다", layers: [{ key: "scarecrow_crow", anchor: "projectile", frame: 32, frames: 4 }, { key: "rooster_peck", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_scarecrow_glare", classId: "class_scarecrow", actorId: "actor_scarecrow", name: "불빛 눈", level: 5, motion: "cast", description: "자루 속 주황 눈빛으로 적 모두를 겁준다", layers: [{ key: "mon_gaze_screen", anchor: "screen", frame: 128, frames: 8 }, { key: "weaken", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_scarecrow_straw", classId: "class_scarecrow", actorId: "actor_scarecrow", name: "짚 채우기", level: 7, motion: "buff", description: "새 짚을 채워 넣어 아군 전체를 회복시킨다", layers: [{ key: "farmer_hay", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_scarecrow_harvest", classId: "class_scarecrow", actorId: "actor_scarecrow", name: "수확의 낫", level: 10, motion: "spin", description: "낫을 크게 휘돌려 적 모두를 벤다", layers: [{ key: "mon_scythe_x", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_scarecrow_crow_swarm", classId: "class_scarecrow", actorId: "actor_scarecrow", name: "까마귀 떼", level: 12, motion: "cast", description: "까마귀 떼를 불러 적 모두를 덮친다", layers: [{ key: "scarecrow_crow_swarm", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_scarecrow_pole_jump", classId: "class_scarecrow", actorId: "actor_scarecrow", name: "장대 도약", level: 16, motion: "leap-strike", description: "기둥 다리로 높이 튀어 올라 낫을 내려꽂는다", layers: [{ key: "mon_cleave_arc", anchor: "target", frame: 64, frames: 10 }, { key: "hero_dust", anchor: "user", frame: 64, frames: 6 }] },
    { id: "skill_scarecrow_harvest_moon", classId: "class_scarecrow", actorId: "actor_scarecrow", name: "추수의 달", level: 22, motion: "finisher", description: "붉은 보름달 아래 까마귀 떼와 거대한 낫이 휩쓰는 필살기", layers: [{ key: "scarecrow_moon_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "mon_scythe_x", anchor: "allTargets", frame: 64, frames: 10 }] },
    // ── 태엽 병정 (monster5-6) ──
    { id: "skill_clockwork_screw_shot", classId: "class_clockwork", actorId: "actor_clockwork", name: "나사 탄환", level: 1, motion: "shoot", description: "머스킷으로 나사 탄환을 쏜다", layers: [{ key: "clockwork_screw", anchor: "projectile", frame: 32, frames: 4 }, { key: "gunner_bullet_hit", anchor: "target", frame: 64, frames: 6 }] },
    { id: "skill_clockwork_bayonet", classId: "class_clockwork", actorId: "actor_clockwork", name: "총검 돌격", level: 3, motion: "dash-strike", description: "뚜벅뚜벅 돌진해 총검으로 찌른다", layers: [{ key: "valkyrie_thrust", anchor: "target", frame: 64, frames: 8 }, { key: "mon_charge_dust", anchor: "user", frame: 64, frames: 6 }] },
    { id: "skill_clockwork_wind_up", classId: "class_clockwork", actorId: "actor_clockwork", name: "태엽 감기", level: 5, motion: "buff", description: "등 태엽을 힘껏 감아 속도를 올린다", layers: [{ key: "clockwork_windup", anchor: "user", frame: 64, frames: 10 }] },
    { id: "skill_clockwork_aim", classId: "class_clockwork", actorId: "actor_clockwork", name: "정밀 조준", level: 7, motion: "shoot", description: "조준을 맞춰 급소에 나사를 박는다", layers: [{ key: "gunner_scope", anchor: "target", frame: 64, frames: 10 }, { key: "clockwork_screw", anchor: "projectile", frame: 32, frames: 4 }, { key: "tank_shell_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_clockwork_volley", classId: "class_clockwork", actorId: "actor_clockwork", name: "일제 사격", level: 10, motion: "shoot", description: "태엽 소리에 맞춰 적 모두에게 연달아 쏜다", layers: [{ key: "gunner_volley_hit", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_clockwork_march", classId: "class_clockwork", actorId: "actor_clockwork", name: "행진곡", level: 12, motion: "buff", description: "북소리 행진으로 아군 전체의 기세를 올린다", layers: [{ key: "general_banner", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_clockwork_gear_bomb", classId: "class_clockwork", actorId: "actor_clockwork", name: "톱니 폭탄", level: 16, motion: "cast", description: "태엽 폭탄을 던져 톱니를 사방에 터뜨린다", layers: [{ key: "gunner_grenade_spin", anchor: "projectile", frame: 32, frames: 4 }, { key: "clockwork_gear_blast", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_clockwork_parade", classId: "class_clockwork", actorId: "actor_clockwork", name: "장난감 대행진", level: 22, motion: "finisher", description: "태엽 병정 대열이 줄지어 일제사격하는 필살기", layers: [{ key: "clockwork_parade_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "gunner_volley_hit", anchor: "allTargets", frame: 64, frames: 8 }] },
    // ── 촛불 임프 (monster5-7) ──
    { id: "skill_candle_imp_ember", classId: "class_candle_imp", actorId: "actor_candle_imp", name: "불씨 던지기", level: 1, motion: "cast", description: "손끝의 불씨를 던져 태운다", layers: [{ key: "candle_imp_ember", anchor: "projectile", frame: 32, frames: 4 }, { key: "ranger_fire_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_candle_imp_wax", classId: "class_candle_imp", actorId: "actor_candle_imp", name: "뜨거운 촛농", level: 3, motion: "cast", description: "끓는 촛농을 끼얹어 적을 굳힌다", layers: [{ key: "candle_imp_wax", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_candle_imp_tail", classId: "class_candle_imp", actorId: "actor_candle_imp", name: "불꼬리 휘두르기", level: 5, motion: "dash-strike", description: "불붙은 꼬리로 후려친다", layers: [{ key: "mon_burn", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_candle_imp_flare", classId: "class_candle_imp", actorId: "actor_candle_imp", name: "심지 돋우기", level: 7, motion: "buff", description: "머리 불꽃을 키워 공격력을 높인다", layers: [{ key: "hero_flame_aura", anchor: "user", frame: 64, frames: 6 }] },
    { id: "skill_candle_imp_vigil", classId: "class_candle_imp", actorId: "actor_candle_imp", name: "밤샘 촛불", level: 10, motion: "cast", description: "따뜻한 촛불로 아군 하나를 치유한다", layers: [{ key: "nun_candles", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_candle_imp_melt", classId: "class_candle_imp", actorId: "actor_candle_imp", name: "녹이기", level: 12, motion: "cast", description: "뜨거운 열기로 적의 갑옷을 녹여 방어를 깎는다", layers: [{ key: "candle_imp_melt", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_candle_imp_pillar", classId: "class_candle_imp", actorId: "actor_candle_imp", name: "불기둥", level: 16, motion: "cast", description: "적 모두의 발밑에서 불기둥을 솟게 한다", layers: [{ key: "mon_flame_pillar", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_candle_imp_meltdown", classId: "class_candle_imp", actorId: "actor_candle_imp", name: "대촛농 붕괴", level: 22, motion: "finisher", description: "거대한 초가 불타 녹아내리며 적을 촛농에 가두는 필살기", layers: [{ key: "candle_imp_meltdown_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "dragonewt_inferno_hit", anchor: "allTargets", frame: 64, frames: 8 }] },
  ],
  partyPixel: [
    { chip: "monster5-0", cell: 48, motion: "hop", idleFrameMs: 220, rows: 5 },
    { chip: "monster5-1", cell: 48, motion: "stomp", idleFrameMs: 260, rows: 5 },
    { chip: "monster5-2", cell: 48, motion: "float", idleFrameMs: 240, rows: 5 },
    { chip: "monster5-3", cell: 48, motion: "hop", idleFrameMs: 200, rows: 5 },
    { chip: "monster5-4", cell: 48, motion: "float", idleFrameMs: 180, rows: 5 },
    { chip: "monster5-5", cell: 48, motion: "hop", idleFrameMs: 240, rows: 5 },
    { chip: "monster5-6", cell: 48, motion: "shoot", idleFrameMs: 200, rows: 5 },
    { chip: "monster5-7", cell: 48, motion: "hop", idleFrameMs: 160, rows: 5 },
  ],
};
