// 묶음 m6 — 3차 로스터(OPRN 자체 제작 Monster6 걷기 칩 8명: 전설의 괴수). 담당 에이전트만 이 파일을 쓴다. 규격: src/assets/retroRoster.ts 머리 주석.
// 생성: scripts/asset-gen/pixel-fx/gen_m6_ts.py (표를 고치고 다시 돌린다). 새 이펙트 시트: scripts/asset-gen/pixel-fx/<키>.py + lib_nm6.py.
// 걷기 칩 scripts/asset-gen/oprn-charset/monster6.py, 전투 15칸 scripts/asset-gen/party-pixel/monster6-<i>.py + pp15_nm6.py.
// 비인간형 몸이므로 motion 은 dash-strike·leap-strike·flurry·spin·cast·shoot·buff·finisher 만 쓴다(blink-strike 제외).
import type { RetroRosterBatch } from "@/assets/retroRoster";

export const BATCH: RetroRosterBatch = {
  skills: [
    // ── 예티 (monster6-0) ──
    { id: "skill_yeti_fist", classId: "class_yeti", actorId: "actor_yeti", name: "설원 주먹", level: 1, motion: "dash-strike", description: "털북숭이 주먹으로 힘껏 내리친다", layers: [{ key: "guard_bash", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_yeti_snowball", classId: "class_yeti", actorId: "actor_yeti", name: "눈덩이 던지기", level: 3, motion: "shoot", description: "단단히 뭉친 눈덩이를 던져 얼린다", layers: [{ key: "yeti_snowball", anchor: "projectile", frame: 32, frames: 4 }, { key: "mon_frost_burst", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_yeti_chest_beat", classId: "class_yeti", actorId: "actor_yeti", name: "가슴 두드리기", level: 5, motion: "buff", description: "가슴을 두드리며 포효해 공격력을 올린다", layers: [{ key: "berserker_roar", anchor: "user", frame: 64, frames: 8 }] },
    { id: "skill_yeti_frost_roar", classId: "class_yeti", actorId: "actor_yeti", name: "얼음 포효", level: 7, motion: "cast", description: "얼어붙은 숨결로 포효해 모든 적을 얼린다", layers: [{ key: "yeti_frost_roar", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_yeti_stomp", classId: "class_yeti", actorId: "actor_yeti", name: "설산 짓밟기", level: 10, motion: "leap-strike", description: "뛰어올라 짓밟아 얼음 땅을 쪼갠다", layers: [{ key: "mon_quake_crack", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_yeti_blizzard_hug", classId: "class_yeti", actorId: "actor_yeti", name: "눈보라 껴안기", level: 12, motion: "flurry", description: "파고들어 끌어안고 연달아 조인다", mechanic: { hits: [0.4, 0.4, 0.4] }, layers: [{ key: "mon_claw_rake", anchor: "target", frame: 64, frames: 8 }, { key: "mage_snow", anchor: "screen", frame: 128, frames: 8 }] },
    { id: "skill_yeti_big_snowball", classId: "class_yeti", actorId: "actor_yeti", name: "거대 눈덩이", level: 16, motion: "spin", description: "적진을 구르며 눈덩이를 키워 모두를 친다", layers: [{ key: "dragonewt_frost", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_yeti_avalanche", classId: "class_yeti", actorId: "actor_yeti", name: "대눈사태", level: 22, motion: "finisher", description: "설산을 무너뜨려 눈사태로 적을 덮는 필살기", layers: [{ key: "yeti_avalanche_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "mon_frost_burst", anchor: "target", frame: 64, frames: 8 }] },
    // ── 인어 전사 (monster6-1) ──
    { id: "skill_merfolk_thrust", classId: "class_merfolk", actorId: "actor_merfolk", name: "삼지창 찌르기", level: 1, motion: "dash-strike", description: "물결을 타고 미끄러져 삼지창으로 찌른다", layers: [{ key: "mon_spear_pierce", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_merfolk_water_jet", classId: "class_merfolk", actorId: "actor_merfolk", name: "물줄기", level: 3, motion: "shoot", description: "창끝에서 세찬 물줄기를 쏜다", layers: [{ key: "mon_wave_screen", anchor: "screen", frame: 128, frames: 10 }] },
    { id: "skill_merfolk_trident_throw", classId: "class_merfolk", actorId: "actor_merfolk", name: "삼지창 투척", level: 5, motion: "shoot", description: "삼지창을 던져 적을 꿰뚫는다", layers: [{ key: "merfolk_trident_throw", anchor: "projectile", frame: 32, frames: 4 }, { key: "hero_pierce", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_merfolk_bubble_guard", classId: "class_merfolk", actorId: "actor_merfolk", name: "거품 방패", level: 7, motion: "buff", description: "거품 막으로 아군 전체를 감싼다", layers: [{ key: "maid_bubbles", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_merfolk_tide_wave", classId: "class_merfolk", actorId: "actor_merfolk", name: "밀려오는 조수", level: 10, motion: "cast", description: "조수를 불러 모든 적을 휩쓴다", layers: [{ key: "merfolk_tide_wave", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_merfolk_sea_song", classId: "class_merfolk", actorId: "actor_merfolk", name: "바다의 노래", level: 12, motion: "cast", description: "잔잔한 노래로 아군 전체를 치유한다", layers: [{ key: "heal", anchor: "allAllies", frame: 64, frames: 8 }] },
    { id: "skill_merfolk_whirl_spear", classId: "class_merfolk", actorId: "actor_merfolk", name: "소용돌이 창", level: 16, motion: "spin", description: "물기둥 속에서 회전하며 모든 적을 찌른다", layers: [{ key: "skiff_wave", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_merfolk_maelstrom", classId: "class_merfolk", actorId: "actor_merfolk", name: "대해의 소용돌이", level: 22, motion: "finisher", description: "바다를 소용돌이로 뒤집어 적을 삼키는 필살기", layers: [{ key: "merfolk_maelstrom_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "skiff_wave", anchor: "allTargets", frame: 64, frames: 10 }] },
    // ── 사이클롭스 (monster6-2) ──
    { id: "skill_cyclops_smash", classId: "class_cyclops", actorId: "actor_cyclops", name: "거인의 주먹", level: 1, motion: "dash-strike", description: "큰 주먹으로 땅째 후려친다", layers: [{ key: "tank_crush", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_cyclops_rock_throw", classId: "class_cyclops", actorId: "actor_cyclops", name: "바위 던지기", level: 3, motion: "shoot", description: "바위를 뽑아 던져 짓누른다", layers: [{ key: "mon_boulder", anchor: "projectile", frame: 32, frames: 4 }, { key: "golem_pal_boulder_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_cyclops_eye_beam", classId: "class_cyclops", actorId: "actor_cyclops", name: "외눈 광선", level: 5, motion: "cast", description: "외눈에 빛을 모아 뜨거운 광선을 쏜다", layers: [{ key: "cyclops_eye_beam", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_cyclops_glare", classId: "class_cyclops", actorId: "actor_cyclops", name: "노려보기", level: 7, motion: "cast", description: "외눈으로 노려봐 모든 적을 움츠리게 한다", layers: [{ key: "mon_gaze_screen", anchor: "screen", frame: 128, frames: 8 }] },
    { id: "skill_cyclops_quake", classId: "class_cyclops", actorId: "actor_cyclops", name: "대지 강타", level: 10, motion: "leap-strike", description: "뛰어올라 두 주먹으로 땅을 내려친다", layers: [{ key: "golem_pal_quake", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_cyclops_rage", classId: "class_cyclops", actorId: "actor_cyclops", name: "거인의 분노", level: 12, motion: "buff", description: "핏발 선 눈으로 힘을 끌어올린다", layers: [{ key: "berserker_roar", anchor: "user", frame: 64, frames: 8 }] },
    { id: "skill_cyclops_rock_rain", classId: "class_cyclops", actorId: "actor_cyclops", name: "바위 비", level: 16, motion: "spin", description: "바위를 휘둘러 흩뿌려 모든 적을 친다", layers: [{ key: "mon_rock_burst", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_cyclops_titan_crash", classId: "class_cyclops", actorId: "actor_cyclops", name: "타이탄 크래시", level: 22, motion: "finisher", description: "산만 한 바위를 들어 내리꽂는 필살기", layers: [{ key: "cyclops_titan_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "hero_meteor_impact", anchor: "target", frame: 128, frames: 10 }] },
    // ── 나방 인간 (monster6-3) ──
    { id: "skill_mothman_claw", classId: "class_mothman", actorId: "actor_mothman", name: "나방 발톱", level: 1, motion: "dash-strike", description: "날아들어 가는 발톱으로 할퀸다", layers: [{ key: "mon_claw_rake", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_mothman_scale_dust", classId: "class_mothman", actorId: "actor_mothman", name: "인분 뿌리기", level: 3, motion: "cast", description: "날개의 인분을 흩뿌려 모든 적을 흐리게 한다", layers: [{ key: "mothman_scale_dust", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_mothman_dust_shot", classId: "class_mothman", actorId: "actor_mothman", name: "인분탄", level: 5, motion: "shoot", description: "빛나는 인분 덩어리를 쏜다", layers: [{ key: "fairy_dust", anchor: "projectile", frame: 32, frames: 4 }, { key: "fairy_dust_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_mothman_hallucination", classId: "class_mothman", actorId: "actor_mothman", name: "환각", level: 7, motion: "cast", description: "붉은 눈빛으로 적 하나를 환각에 빠뜨린다", layers: [{ key: "mothman_hallucination", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_mothman_sleep_powder", classId: "class_mothman", actorId: "actor_mothman", name: "수면 가루", level: 10, motion: "cast", description: "졸음 가루로 모든 적을 재운다", layers: [{ key: "mon_spore_cloud", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_mothman_wing_flurry", classId: "class_mothman", actorId: "actor_mothman", name: "날개 난타", level: 12, motion: "flurry", description: "큰 날개로 연달아 후려친다", mechanic: { hits: [0.4, 0.4, 0.4] }, layers: [{ key: "samurai_wind_hit", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_mothman_moth_charm", classId: "class_mothman", actorId: "actor_mothman", name: "불빛 유혹", level: 16, motion: "buff", description: "불빛처럼 흔들려 적의 시선을 끈다", layers: [{ key: "dancer_charm", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_mothman_moonwing", classId: "class_mothman", actorId: "actor_mothman", name: "달밤의 날개", level: 22, motion: "finisher", description: "달빛을 가린 거대한 날개로 환각의 밤을 여는 필살기", layers: [{ key: "mothman_moonwing_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "mon_spore_cloud", anchor: "allTargets", frame: 64, frames: 10 }] },
    // ── 바실리스크 (monster6-4) ──
    { id: "skill_basilisk_bite", classId: "class_basilisk", actorId: "actor_basilisk", name: "독니", level: 1, motion: "dash-strike", description: "재빨리 파고들어 독니로 문다", layers: [{ key: "mon_fang_bite", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_basilisk_venom_spit", classId: "class_basilisk", actorId: "actor_basilisk", name: "독침 뱉기", level: 3, motion: "shoot", description: "독을 뱉어 적을 중독시킨다", layers: [{ key: "dragonewt_venom", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_basilisk_petrify", classId: "class_basilisk", actorId: "actor_basilisk", name: "석화 시선", level: 5, motion: "cast", description: "볏을 세우고 노려봐 적 하나를 돌로 굳힌다", layers: [{ key: "basilisk_petrify", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_basilisk_crest", classId: "class_basilisk", actorId: "actor_basilisk", name: "왕관 볏", level: 7, motion: "buff", description: "왕관 볏을 세워 비늘을 단단히 한다", layers: [{ key: "mon_shell_barrier", anchor: "user", frame: 64, frames: 8 }] },
    { id: "skill_basilisk_tail_sweep", classId: "class_basilisk", actorId: "actor_basilisk", name: "꼬리 휩쓸기", level: 10, motion: "spin", description: "꼬리를 크게 돌려 모든 적을 쓸어버린다", layers: [{ key: "tiger_claw", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_basilisk_stone_gaze", classId: "class_basilisk", actorId: "actor_basilisk", name: "석화의 눈빛", level: 12, motion: "cast", description: "모든 적에게 석화의 눈빛을 흩뿌린다", layers: [{ key: "gargoyle_pal_gaze", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_basilisk_venom_rain", classId: "class_basilisk", actorId: "actor_basilisk", name: "독의 비", level: 16, motion: "leap-strike", description: "뛰어올라 독을 흩뿌리며 내려앉는다", layers: [{ key: "poison", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_basilisk_gorgon", classId: "class_basilisk", actorId: "actor_basilisk", name: "고르곤의 왕관", level: 22, motion: "finisher", description: "왕관의 눈을 열어 전장 전체를 돌로 만드는 필살기", layers: [{ key: "basilisk_gorgon_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "gargoyle_pal_gaze", anchor: "target", frame: 64, frames: 10 }] },
    // ── 지니 (monster6-5) ──
    { id: "skill_djinn_smoke_fist", classId: "class_djinn", actorId: "actor_djinn", name: "연기 주먹", level: 1, motion: "dash-strike", description: "연기 몸을 늘여 주먹을 뻗는다", layers: [{ key: "guard_bash", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_djinn_gust", classId: "class_djinn", actorId: "actor_djinn", name: "돌풍", level: 3, motion: "shoot", description: "손바닥에서 돌풍을 쏘아 밀쳐낸다", layers: [{ key: "samurai_wind_hit", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_djinn_wish", classId: "class_djinn", actorId: "actor_djinn", name: "소원의 빛", level: 5, motion: "cast", description: "소원을 들어줘 아군 전체를 치유한다", layers: [{ key: "djinn_wish", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_djinn_sandstorm", classId: "class_djinn", actorId: "actor_djinn", name: "모래 폭풍", level: 7, motion: "cast", description: "모래 폭풍을 일으켜 모든 적을 휩쓴다", layers: [{ key: "djinn_sandstorm", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_djinn_lamp_ward", classId: "class_djinn", actorId: "actor_djinn", name: "램프의 가호", level: 10, motion: "buff", description: "램프 연기로 아군 전체를 감싼다", layers: [{ key: "summoner_sylph", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_djinn_spirit", classId: "class_djinn", actorId: "actor_djinn", name: "정령 소환", level: 12, motion: "cast", description: "램프 속 정령을 불러 적을 치게 한다", layers: [{ key: "summoner_golem", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_djinn_tempest", classId: "class_djinn", actorId: "actor_djinn", name: "폭풍 회오리", level: 16, motion: "spin", description: "연기 몸을 회오리로 바꿔 모든 적을 휘감는다", layers: [{ key: "nomad_dust_devil", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_djinn_three_wishes", classId: "class_djinn", actorId: "actor_djinn", name: "세 가지 소원", level: 22, motion: "finisher", description: "마지막 소원으로 하늘을 가르는 황금 폭풍을 부르는 필살기", layers: [{ key: "djinn_genie_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "harpy_pal_storm_hit", anchor: "allTargets", frame: 64, frames: 8 }] },
    // ── 키메라 (monster6-6) ──
    { id: "skill_chimera_maul", classId: "class_chimera", actorId: "actor_chimera", name: "사자 이빨", level: 1, motion: "dash-strike", description: "사자 머리로 달려들어 물어뜯는다", layers: [{ key: "mon_fang_bite", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_chimera_goat_bolt", classId: "class_chimera", actorId: "actor_chimera", name: "염소 번개", level: 3, motion: "cast", description: "염소 머리가 번개를 불러 적에게 떨군다", layers: [{ key: "mage_chain_bolt", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_chimera_snake_venom", classId: "class_chimera", actorId: "actor_chimera", name: "뱀 꼬리 독", level: 5, motion: "shoot", description: "꼬리 뱀이 독을 뱉는다", layers: [{ key: "scout_venom", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_chimera_rampage", classId: "class_chimera", actorId: "actor_chimera", name: "삼두 난무", level: 7, motion: "flurry", description: "세 머리가 번갈아 연달아 공격한다", mechanic: { hits: [0.4, 0.4, 0.4] }, layers: [{ key: "tiger_claw", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_chimera_roar", classId: "class_chimera", actorId: "actor_chimera", name: "사자후", level: 10, motion: "buff", description: "포효로 아군의 기세를 올린다", layers: [{ key: "mon_howl_ring", anchor: "allAllies", frame: 64, frames: 8 }] },
    { id: "skill_chimera_pounce", classId: "class_chimera", actorId: "actor_chimera", name: "덮치기", level: 12, motion: "leap-strike", description: "높이 뛰어 적을 덮쳐 누른다", layers: [{ key: "mon_quake_crack", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_chimera_triple_breath", classId: "class_chimera", actorId: "actor_chimera", name: "삼중 브레스", level: 16, motion: "cast", description: "불·번개·독 세 가닥 숨결을 모든 적에게 뿜는다", layers: [{ key: "chimera_triple_breath", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_chimera_chaos", classId: "class_chimera", actorId: "actor_chimera", name: "혼돈의 삼두", level: 22, motion: "finisher", description: "세 머리의 숨결을 하나로 합쳐 전장을 태우는 필살기", layers: [{ key: "chimera_rampage_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "airship_flame", anchor: "allTargets", frame: 64, frames: 10 }] },
    // ── 타락 천사 (monster6-7) ──
    { id: "skill_dark_angel_wing_slash", classId: "class_dark_angel", actorId: "actor_dark_angel", name: "검은 날개베기", level: 1, motion: "dash-strike", description: "검은 날개로 스쳐 지나가며 벤다", layers: [{ key: "dark_knight_slash", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_dark_angel_black_feather", classId: "class_dark_angel", actorId: "actor_dark_angel", name: "흑우탄", level: 3, motion: "shoot", description: "검은 깃털을 쏘아 꿰뚫는다", layers: [{ key: "dark_angel_black_feather", anchor: "projectile", frame: 32, frames: 4 }, { key: "seraph_feather_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_dark_angel_fallen_smite", classId: "class_dark_angel", actorId: "actor_dark_angel", name: "타락의 빛", level: 5, motion: "cast", description: "더럽혀진 빛기둥을 적 하나에 내리꽂는다", layers: [{ key: "seraph_smite", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_dark_angel_dark_orb", classId: "class_dark_angel", actorId: "actor_dark_angel", name: "암흑 구체", level: 7, motion: "cast", description: "검은 구체를 쏘아 터뜨린다", layers: [{ key: "dark_lord_orb", anchor: "projectile", frame: 32, frames: 4 }, { key: "dark_lord_orb_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_dark_angel_broken_halo", classId: "class_dark_angel", actorId: "actor_dark_angel", name: "금 간 후광", level: 10, motion: "buff", description: "금 간 후광을 밝혀 마력을 끌어올린다", layers: [{ key: "mon_demon_aura", anchor: "user", frame: 64, frames: 8 }] },
    { id: "skill_dark_angel_gravity", classId: "class_dark_angel", actorId: "actor_dark_angel", name: "추락의 무게", level: 12, motion: "cast", description: "하늘에서 떨어진 무게로 모든 적을 짓누른다", layers: [{ key: "dark_knight_gravity", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_dark_angel_feather_storm", classId: "class_dark_angel", actorId: "actor_dark_angel", name: "흑우 폭풍", level: 16, motion: "spin", description: "적진 한가운데서 검은 깃털을 흩날린다", layers: [{ key: "mon_dark_flame", anchor: "screen", frame: 128, frames: 10 }] },
    { id: "skill_dark_angel_judgment", classId: "class_dark_angel", actorId: "actor_dark_angel", name: "심판의 빛", level: 22, motion: "finisher", description: "하늘을 가르고 검은 빛의 심판을 내리는 필살기", layers: [{ key: "dark_angel_judgment_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "cleric_judgment_hit", anchor: "allTargets", frame: 64, frames: 8 }] },
  ],
  partyPixel: [
    { chip: "monster6-0", cell: 64, motion: "stomp", idleFrameMs: 300, rows: 5 },
    { chip: "monster6-1", cell: 48, motion: "shoot", idleFrameMs: 220, rows: 5 },
    { chip: "monster6-2", cell: 64, motion: "stomp", idleFrameMs: 340, rows: 5 },
    { chip: "monster6-3", cell: 48, motion: "float", idleFrameMs: 160, rows: 5 },
    { chip: "monster6-4", cell: 48, motion: "breath", idleFrameMs: 260, rows: 5 },
    { chip: "monster6-5", cell: 64, motion: "float", idleFrameMs: 220, rows: 5 },
    { chip: "monster6-6", cell: 64, motion: "dash", idleFrameMs: 240, rows: 5 },
    { chip: "monster6-7", cell: 48, motion: "float", idleFrameMs: 200, rows: 5 },
  ],
};
