// 묶음 p2 — 담당 에이전트만 이 파일을 쓴다. 규격: src/assets/retroRoster.ts 머리 주석, 스킬 형식은 retroClassSkills.ts(RetroClassSkill).
// 생성 파일: scripts/asset-gen/pixel-fx/r2w3_emit.py (정본 목록은 r2w3_skills.py). 직접 고치지 말고 목록을 고친 뒤 다시 생성한다.
import type { RetroRosterBatch } from "@/assets/retroRoster";

export const BATCH: RetroRosterBatch = {
  skills: [
    { id: "skill_gypsy_tarot_flick", classId: "class_gypsy", actorId: "actor_gypsy", name: "타로 던지기", level: 1, motion: "shoot", description: "타로 카드를 부채질하듯 날려 적을 벤다", layers: [{ key: "gypsy_card", anchor: "projectile", frame: 32, frames: 4 }, { key: "gypsy_card_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_gypsy_crystal_gaze", classId: "class_gypsy", actorId: "actor_gypsy", name: "수정구의 환영", level: 3, motion: "cast", description: "수정구를 띄워 환영 광선을 쏘고 산산이 부순다", layers: [{ key: "gypsy_crystal", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_gypsy_curse_card", classId: "class_gypsy", actorId: "actor_gypsy", name: "저주 카드", level: 5, motion: "cast", description: "검은 카드를 내리꽂아 해골 독기로 저주한다", layers: [{ key: "gypsy_curse", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_gypsy_wheel_fortune", classId: "class_gypsy", actorId: "actor_gypsy", name: "운명의 수레바퀴", level: 7, motion: "cast", description: "황금 수레바퀴를 돌려 모든 적의 운을 뒤튼다", layers: [{ key: "gypsy_wheel", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_gypsy_veil_dance", classId: "class_gypsy", actorId: "actor_gypsy", name: "베일 춤", level: 10, motion: "buff", description: "베일 리본과 금화를 휘감아 몸을 가볍게 한다", layers: [{ key: "gypsy_dance", anchor: "user", frame: 64, frames: 10 }] },
    { id: "skill_gypsy_lovers_charm", classId: "class_gypsy", actorId: "actor_gypsy", name: "연인의 매혹", level: 12, motion: "cast", description: "붉은 하트와 보랏빛 하트가 얽혀 적의 마음을 사로잡는다", layers: [{ key: "gypsy_lovers", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_gypsy_card_storm", classId: "class_gypsy", actorId: "actor_gypsy", name: "카드 회오리", level: 16, motion: "spin", description: "카드 수십 장이 회오리로 적진을 갈아 버린다", layers: [{ key: "gypsy_cardstorm", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_gypsy_star_prophecy", classId: "class_gypsy", actorId: "actor_gypsy", name: "별의 점괘", level: 22, motion: "finisher", description: "「별」 카드를 세워 하늘의 별빛을 쏟아붓는 필살기", layers: [{ key: "gypsy_fate_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "gypsy_fate_hit", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_sword_dancer_twin_dance", classId: "class_sword_dancer", actorId: "actor_sword_dancer", name: "쌍검무", level: 1, motion: "flurry", description: "두 자루 검이 엇갈리며 초승달 궤적을 그린다", layers: [{ key: "sdance_twin", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_sword_dancer_crescent_step", classId: "class_sword_dancer", actorId: "actor_sword_dancer", name: "초승달 걸음", level: 3, motion: "dash-strike", description: "한 걸음에 파고들며 거대한 초승달로 가른다", layers: [{ key: "sdance_crescent", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_sword_dancer_ribbon_whirl", classId: "class_sword_dancer", actorId: "actor_sword_dancer", name: "리본 회전", level: 5, motion: "spin", description: "리본과 검날이 겹겹이 돌며 모든 적을 벤다", layers: [{ key: "sdance_ribbon", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_sword_dancer_sword_wave", classId: "class_sword_dancer", actorId: "actor_sword_dancer", name: "검기 날리기", level: 7, motion: "shoot", description: "초승달 검기를 날려 적을 가른다", layers: [{ key: "sdance_wave", anchor: "projectile", frame: 32, frames: 4 }, { key: "sdance_wave_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_sword_dancer_mirror_step", classId: "class_sword_dancer", actorId: "actor_sword_dancer", name: "잔영 걸음", level: 10, motion: "blink-strike", description: "잔영을 남기며 사라졌다가 X자로 벤다", layers: [{ key: "sdance_blur", anchor: "user", frame: 64, frames: 8 }, { key: "sdance_cross", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_sword_dancer_sword_rhythm", classId: "class_sword_dancer", actorId: "actor_sword_dancer", name: "검무 박자", level: 12, motion: "buff", description: "북 장단에 맞춘 검무로 아군 전체의 기세를 올린다", layers: [{ key: "sdance_rhythm", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_sword_dancer_moon_waltz", classId: "class_sword_dancer", actorId: "actor_sword_dancer", name: "월광 왈츠", level: 16, motion: "leap-strike", description: "보름달을 등지고 뛰어올라 쌍검을 내려꽂는다", layers: [{ key: "sdance_moon", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_sword_dancer_hundred_petals", classId: "class_sword_dancer", actorId: "actor_sword_dancer", name: "백화요란", level: 22, motion: "finisher", description: "꽃잎과 검날의 폭풍 속에서 화면을 가르는 필살기", layers: [{ key: "sdance_petal_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "sdance_petal_hit", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_gambler_dice_throw", classId: "class_gambler", actorId: "actor_gambler", name: "주사위 던지기", level: 1, motion: "shoot", description: "주사위를 굴려 적에게 꽂는다. 눈이 클수록 아프다", layers: [{ key: "gambler_dice", anchor: "projectile", frame: 32, frames: 4 }, { key: "gambler_dice_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_gambler_slot_spin", classId: "class_gambler", actorId: "actor_gambler", name: "슬롯 머신", level: 3, motion: "cast", description: "거대한 슬롯을 돌려 별 세 개를 맞추면 대폭발", layers: [{ key: "gambler_slot", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_gambler_coin_toss", classId: "class_gambler", actorId: "actor_gambler", name: "동전 세례", level: 5, motion: "dash-strike", description: "금화 한 줌을 뿌리며 파고들어 후려친다", layers: [{ key: "gambler_coin", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_gambler_poker_face", classId: "class_gambler", actorId: "actor_gambler", name: "포커페이스", level: 7, motion: "buff", description: "패를 펼쳐 표정을 숨기고 회피를 높인다", layers: [{ key: "gambler_bluff", anchor: "user", frame: 64, frames: 10 }] },
    { id: "skill_gambler_all_in", classId: "class_gambler", actorId: "actor_gambler", name: "올인", level: 10, motion: "leap-strike", description: "칩 더미를 통째로 걸고 뛰어올라 내려찍는다", layers: [{ key: "gambler_allin", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_gambler_ace_card", classId: "class_gambler", actorId: "actor_gambler", name: "에이스 카드", level: 12, motion: "cast", description: "숨겨 둔 에이스 카드 한 장으로 빛의 일격을 낸다", layers: [{ key: "gambler_ace", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_gambler_double_or_nothing", classId: "class_gambler", actorId: "actor_gambler", name: "두 배 아니면 빈손", level: 16, motion: "flurry", description: "동전 앞뒤에 걸고 연타를 몰아친다", layers: [{ key: "gambler_coin_flip", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_gambler_jackpot", classId: "class_gambler", actorId: "actor_gambler", name: "잭팟", level: 22, motion: "finisher", description: "릴이 777 로 멈추고 금화 폭포가 쏟아지는 필살기", layers: [{ key: "gambler_jackpot_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "gambler_jackpot_hit", anchor: "allTargets", frame: 64, frames: 8 }] },
  ],
  partyPixel: []
};
