// 묶음 p4 — 담당 에이전트만 이 파일을 쓴다. 규격: src/assets/retroRoster.ts 머리 주석, 스킬 형식은 retroClassSkills.ts(RetroClassSkill).
// 뱃사람·노승·귀부인·유목민·수녀·광대·꼬마 발명가·낭인 (People4-3 ~ People5-2, 직업 8 × 스킬 8 = 64).
// 이펙트 시트: public/assets/generated/pixel-fx/<key>.png, 생성기 scripts/asset-gen/pixel-fx/fx_<class>.py(공용 lib_r2w4.py).
// 스킬 하나당 새 시트는 최대 1장, 나머지 층은 기존 시트(retroClassSkills·retroMonsterSkills·같은 묶음)를 재사용한다.
import type { RetroRosterBatch } from "@/assets/retroRoster";

export const BATCH: RetroRosterBatch = {
  skills: [
    // ── 뱃사람(class_sailor, people4-3) — 닻·물대포·작살·크라켄
    { id: "skill_sailor_anchor_slam", classId: "class_sailor", actorId: "actor_sailor", name: "닻 내려치기", level: 1, motion: "dash-strike", description: "무거운 닻을 통째로 휘둘러 내려친다", mechanic: { crit: 20 }, layers: [{ key: "sailor_anchor_slam", anchor: "target", frame: 64, frames: 9 }] },
    { id: "skill_sailor_water_cannon", classId: "class_sailor", actorId: "actor_sailor", name: "물대포", level: 3, motion: "cast", description: "갑판 호스에서 물기둥을 쏘아 적을 밀어낸다", mechanic: { element: "water", states: [{ id: "state_wet" }] }, layers: [{ key: "sailor_jet", anchor: "projectile", frame: 32, frames: 4 }, { key: "sailor_jet_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_sailor_rope_whip", classId: "class_sailor", actorId: "actor_sailor", name: "밧줄 채찍", level: 5, motion: "spin", description: "굵은 밧줄을 빙 돌려 모든 적을 후려친다", layers: [{ key: "sailor_rope_whip", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_sailor_rum_toast", classId: "class_sailor", actorId: "actor_sailor", name: "럼주 한 모금", level: 7, motion: "buff", description: "진한 럼을 들이켜 힘과 배짱을 끌어올린다", mechanic: { kind: "support", scope: "self", states: [{ id: "state_attack_up" }, { id: "state_defense_up" }] }, layers: [{ key: "sailor_rum", anchor: "user", frame: 64, frames: 10 }] },
    { id: "skill_sailor_harpoon", classId: "class_sailor", actorId: "actor_sailor", name: "작살 투척", level: 10, motion: "shoot", description: "밧줄 달린 작살을 던져 꽂고 끌어당긴다", mechanic: { area: "line", states: [{ id: "state_agility_down", chance: 50 }] }, layers: [{ key: "sailor_harpoon", anchor: "projectile", frame: 32, frames: 4 }, { key: "sailor_harpoon_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_sailor_tidal_leap", classId: "class_sailor", actorId: "actor_sailor", name: "파도 타고 내려찍기", level: 12, motion: "leap-strike", description: "밀려온 파도를 타고 솟구쳐 적 위로 덮친다", mechanic: { element: "water", crit: 25, cooldown: 2 }, layers: [{ key: "sailor_tidal_crash", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_sailor_hoist_sail", classId: "class_sailor", actorId: "actor_sailor", name: "돛을 올려라", level: 16, motion: "buff", description: "돛을 활짝 펴 순풍으로 아군 전원을 재촉한다", mechanic: { kind: "support", scope: "allAllies", states: [{ id: "state_agility_up" }] }, layers: [{ key: "sailor_hoist_sail", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_sailor_kraken", classId: "class_sailor", actorId: "actor_sailor", name: "크라켄의 부름", level: 22, motion: "finisher", description: "심해의 크라켄이 촉수로 적진을 휩쓰는 필살기", mechanic: { hits: [0.5, 0.5, 0.5], element: "water", states: [{ id: "state_agility_down", chance: 50 }] }, layers: [{ key: "sailor_kraken_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "sailor_kraken_hit", anchor: "allTargets", frame: 64, frames: 10 }] },

    // ── 노승(class_monk_elder, people4-4) — 향·범종·연꽃·선정·열반
    { id: "skill_monk_elder_incense", classId: "class_monk_elder", actorId: "actor_monk_elder", name: "향불", level: 1, motion: "buff", description: "향 연기가 퍼져 아군 전원의 상처를 달랜다", mechanic: { kind: "healing", scope: "allAllies", power: 38, states: [{ id: "state_regen" }] }, layers: [{ key: "monk_elder_incense", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_monk_elder_staff_rings", classId: "class_monk_elder", actorId: "actor_monk_elder", name: "석장 고리", level: 3, motion: "dash-strike", description: "고리 달린 석장으로 때려 짤랑이는 소리로 흔든다", mechanic: { states: [{ id: "state_paralysis", chance: 30 }] }, layers: [{ key: "monk_elder_staff_rings", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_monk_elder_temple_bell", classId: "class_monk_elder", actorId: "actor_monk_elder", name: "범종", level: 5, motion: "cast", description: "커다란 범종을 떨어뜨려 종소리로 짓누른다", mechanic: { formula: "b.hp / 4", element: null, hitRate: 90, states: [] }, layers: [{ key: "monk_elder_temple_bell", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_monk_elder_lotus_bloom", classId: "class_monk_elder", actorId: "actor_monk_elder", name: "연꽃 개화", level: 7, motion: "cast", description: "연꽃을 피워 아군 한 명을 크게 회복시킨다", mechanic: { kind: "healing", scope: "ally", power: 48, states: [{ id: "state_poison", op: "remove" }, { id: "state_deep_poison", op: "remove" }] }, layers: [{ key: "monk_elder_lotus", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_monk_elder_lion_roar", classId: "class_monk_elder", actorId: "actor_monk_elder", name: "사자후", level: 10, motion: "spin", description: "일갈 한 번에 충격파를 뻗어 모든 적을 물러서게 한다", mechanic: { states: [{ id: "state_agility_down", chance: 50 }] }, layers: [{ key: "monk_elder_roar", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_monk_elder_vajra", classId: "class_monk_elder", actorId: "actor_monk_elder", name: "금강저", level: 12, motion: "leap-strike", description: "금강저에 번개를 실어 뛰어올라 내리친다", mechanic: { element: "thunder", crit: 25 }, layers: [{ key: "monk_elder_vajra", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_monk_elder_zen", classId: "class_monk_elder", actorId: "actor_monk_elder", name: "선정", level: 16, motion: "buff", description: "깊은 선정에 들어 마음을 비우고 기력을 되찾는다", mechanic: { kind: "healing", affects: "mp", scope: "self", power: 40, mp: 0, hpCost: 15 }, layers: [{ key: "monk_elder_zen", anchor: "user", frame: 64, frames: 12 }] },
    { id: "skill_monk_elder_nirvana", classId: "class_monk_elder", actorId: "actor_monk_elder", name: "열반의 빛", level: 22, motion: "finisher", description: "열반의 빛이 내려 쓰러진 아군 전원을 일으키는 필살기", mechanic: { kind: "healing", scope: "allAllies", power: 70, revive: true }, layers: [{ key: "monk_elder_nirvana_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "monk_elder_nirvana_light", anchor: "allAllies", frame: 64, frames: 10 }] },

    // ── 귀부인(class_noblewoman, people4-5) — 향수·부채·보석·왈츠·장미
    { id: "skill_noblewoman_perfume", classId: "class_noblewoman", actorId: "actor_noblewoman", name: "장미 향수", level: 1, motion: "cast", description: "달콤한 향수 안개로 적 전원의 정신을 흐린다", mechanic: { kind: "support", scope: "allEnemies", states: [{ id: "state_silence", chance: 60 }] }, layers: [{ key: "noblewoman_perfume", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_noblewoman_fan_slap", classId: "class_noblewoman", actorId: "actor_noblewoman", name: "부채 연타", level: 3, motion: "flurry", description: "접은 부채로 얄밉도록 빠르게 두들긴다", mechanic: { hits: [0.4, 0.4, 0.4] }, layers: [{ key: "noblewoman_fan_slap", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_noblewoman_gem_toss", classId: "class_noblewoman", actorId: "actor_noblewoman", name: "보석 세례", level: 5, motion: "shoot", description: "값비싼 보석을 던져 맞힌다", mechanic: { crit: 25 }, layers: [{ key: "noblewoman_gem", anchor: "projectile", frame: 32, frames: 4 }, { key: "noblewoman_gem_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_noblewoman_charm_glance", classId: "class_noblewoman", actorId: "actor_noblewoman", name: "추파", level: 7, motion: "cast", description: "요염한 눈길로 적 하나를 매혹한다", mechanic: { kind: "support", scope: "enemy", states: [{ id: "state_berserk", chance: 50 }] }, layers: [{ key: "noblewoman_charm", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_noblewoman_parasol_spin", classId: "class_noblewoman", actorId: "actor_noblewoman", name: "양산 회전", level: 10, motion: "spin", description: "펼친 양산을 빙글 돌려 모두 밀쳐낸다", mechanic: { states: [{ id: "state_agility_down", chance: 40 }] }, layers: [{ key: "noblewoman_parasol", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_noblewoman_waltz", classId: "class_noblewoman", actorId: "actor_noblewoman", name: "무도회 왈츠", level: 12, motion: "buff", description: "왈츠 선율로 아군 전원의 발걸음을 가볍게 한다", mechanic: { kind: "support", scope: "allAllies", states: [{ id: "state_agility_up" }] }, layers: [{ key: "noblewoman_waltz", anchor: "allAllies", frame: 64, frames: 12 }] },
    { id: "skill_noblewoman_chandelier", classId: "class_noblewoman", actorId: "actor_noblewoman", name: "샹들리에 낙하", level: 16, motion: "cast", description: "천장의 샹들리에를 떨어뜨려 적을 짓누른다", mechanic: { formula: "b.hp / 4", element: null, hitRate: 90, states: [] }, layers: [{ key: "noblewoman_chandelier", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_noblewoman_rose_garden", classId: "class_noblewoman", actorId: "actor_noblewoman", name: "붉은 장미 정원", level: 22, motion: "finisher", description: "가시 돋친 장미 덩굴이 무대를 뒤덮는 필살기", mechanic: { hits: [0.5, 0.5, 0.5], states: [{ id: "state_poison", chance: 50 }] }, layers: [{ key: "noblewoman_rose_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "noblewoman_rose_thorn", anchor: "allTargets", frame: 64, frames: 10 }] },

    // ── 유목민(class_nomad, people4-6) — 투창·모래·볼라·신기루·낙타
    { id: "skill_nomad_javelin", classId: "class_nomad", actorId: "actor_nomad", name: "투창", level: 1, motion: "shoot", description: "짧은 투창을 힘껏 던져 꿰뚫는다", mechanic: { area: "line" }, layers: [{ key: "nomad_javelin", anchor: "projectile", frame: 32, frames: 4 }, { key: "nomad_javelin_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_nomad_sand_toss", classId: "class_nomad", actorId: "actor_nomad", name: "모래 뿌리기", level: 3, motion: "cast", description: "한 줌 모래를 뿌려 적의 눈을 가린다", mechanic: { kind: "support", scope: "enemy", states: [{ id: "state_blind", chance: 70 }] }, layers: [{ key: "nomad_sand_toss", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_nomad_bolas", classId: "class_nomad", actorId: "actor_nomad", name: "볼라", level: 5, motion: "cast", description: "돌 달린 끈을 돌려 던져 다리를 얽는다", mechanic: { states: [{ id: "state_agility_down", chance: 80 }] }, layers: [{ key: "nomad_bolas", anchor: "projectile", frame: 32, frames: 4 }, { key: "nomad_bolas_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_nomad_mirage", classId: "class_nomad", actorId: "actor_nomad", name: "신기루", level: 7, motion: "buff", description: "아지랑이로 잔상을 세워 공격을 피한다", mechanic: { kind: "support", scope: "self", states: [{ id: "state_evade" }] }, layers: [{ key: "nomad_mirage", anchor: "user", frame: 64, frames: 10 }] },
    { id: "skill_nomad_dust_devil", classId: "class_nomad", actorId: "actor_nomad", name: "모래회오리", level: 10, motion: "spin", description: "작은 회오리를 일으켜 모든 적을 휘감는다", mechanic: { states: [{ id: "state_blind", chance: 40 }] }, layers: [{ key: "nomad_dust_devil", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_nomad_camel_charge", classId: "class_nomad", actorId: "actor_nomad", name: "낙타 돌격", level: 12, motion: "dash-strike", description: "사막의 낙타를 타고 창을 겨눠 돌진한다", mechanic: { crit: 30 }, layers: [{ key: "nomad_camel", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_nomad_oasis", classId: "class_nomad", actorId: "actor_nomad", name: "오아시스", level: 16, motion: "buff", description: "샘물과 야자수 그늘이 아군 전원을 회복시킨다", mechanic: { kind: "healing", scope: "allAllies", power: 52, states: [{ id: "state_regen" }] }, layers: [{ key: "nomad_oasis", anchor: "allAllies", frame: 64, frames: 12 }] },
    { id: "skill_nomad_desert_wrath", classId: "class_nomad", actorId: "actor_nomad", name: "사막의 분노", level: 22, motion: "finisher", description: "모래폭풍 속에서 창 소나기가 쏟아지는 필살기", mechanic: { hits: [0.35, 0.35, 0.35, 0.35], states: [{ id: "state_blind", chance: 40 }] }, layers: [{ key: "nomad_wrath_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "nomad_wrath_spears", anchor: "allTargets", frame: 64, frames: 10 }] },

    // ── 수녀(class_nun, people4-7) — 성가·성수·십자가·묵주·기적
    { id: "skill_nun_hymn", classId: "class_nun", actorId: "actor_nun", name: "성가", level: 1, motion: "buff", description: "맑은 성가가 아군 전원의 상처를 어루만진다", mechanic: { kind: "healing", scope: "allAllies", power: 38 }, layers: [{ key: "bard_hymn", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_nun_holy_water", classId: "class_nun", actorId: "actor_nun", name: "성수 투척", level: 3, motion: "cast", description: "성수 병을 던져 사악한 것을 태운다", mechanic: { element: "holy" }, layers: [{ key: "nun_vial", anchor: "projectile", frame: 32, frames: 4 }, { key: "holy", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_nun_cross_smash", classId: "class_nun", actorId: "actor_nun", name: "십자가 강타", level: 5, motion: "dash-strike", description: "은빛 십자가를 들고 달려들어 내리친다", mechanic: { element: "holy", states: [{ id: "state_defense_down", chance: 50 }] }, layers: [{ key: "nun_cross_smash", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_nun_candle_prayer", classId: "class_nun", actorId: "actor_nun", name: "촛불 기도", level: 7, motion: "cast", description: "촛불 다섯 개를 밝혀 아군 한 명을 치유한다", mechanic: { kind: "healing", scope: "ally", power: 48 }, layers: [{ key: "nun_candles", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_nun_purify", classId: "class_nun", actorId: "actor_nun", name: "정화", level: 10, motion: "cast", description: "맑은 파동이 퍼져 아군의 나쁜 상태를 씻어낸다", mechanic: { kind: "support", scope: "allAllies", states: [{ id: "state_poison", op: "remove" }, { id: "state_deep_poison", op: "remove" }, { id: "state_blind", op: "remove" }, { id: "state_silence", op: "remove" }, { id: "state_paralysis", op: "remove" }, { id: "state_sleep", op: "remove" }] }, layers: [{ key: "cleric_purify", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_nun_rosary", classId: "class_nun", actorId: "actor_nun", name: "묵주 결박", level: 12, motion: "spin", description: "빛나는 묵주를 휘돌려 모든 적을 옭아맨다", mechanic: { kind: "support", scope: "allEnemies", states: [{ id: "state_stop", chance: 30 }] }, layers: [{ key: "nun_rosary", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_nun_angel_wings", classId: "class_nun", actorId: "actor_nun", name: "천사의 날개", level: 16, motion: "buff", description: "흰 날개가 펼쳐져 아군 전원을 감싸 보호한다", mechanic: { kind: "support", scope: "allAllies", states: [{ id: "state_protect" }, { id: "state_shell" }] }, layers: [{ key: "cleric_blessing", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_nun_miracle", classId: "class_nun", actorId: "actor_nun", name: "성녀의 기적", level: 22, motion: "finisher", description: "스테인드글라스 빛이 쏟아져 아군을 일으키는 필살기", mechanic: { kind: "healing", scope: "allAllies", power: 70, revive: true }, layers: [{ key: "nun_miracle_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "cleric_mass_heal", anchor: "allAllies", frame: 64, frames: 10 }] },

    // ── 광대(class_jester, people5-0) — 저글링·색종이·상자·가면·카니발
    { id: "skill_jester_juggle", classId: "class_jester", actorId: "actor_jester", name: "저글링", level: 1, motion: "flurry", description: "색색의 공을 돌리다 연달아 던져 맞힌다", mechanic: { hits: [0.4, 0.4, 0.4] }, layers: [{ key: "jester_juggle", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_jester_confetti", classId: "class_jester", actorId: "actor_jester", name: "색종이 폭죽", level: 3, motion: "cast", description: "색종이 폭죽을 터뜨려 적 전원의 눈을 어지럽힌다", mechanic: { kind: "support", scope: "allEnemies", states: [{ id: "state_blind", chance: 50 }] }, layers: [{ key: "jester_confetti", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_jester_knives", classId: "class_jester", actorId: "actor_jester", name: "단검 저글링", level: 5, motion: "shoot", description: "돌리던 단검을 휙휙 날려 꽂는다", mechanic: { hits: [0.6, 0.6] }, layers: [{ key: "scout_knife", anchor: "projectile", frame: 32, frames: 4 }, { key: "scout_knife_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_jester_jack_box", classId: "class_jester", actorId: "actor_jester", name: "깜짝 상자", level: 7, motion: "blink-strike", description: "적 앞에 상자를 펑 열어 권투 장갑을 튀어나오게 한다", mechanic: { states: [{ id: "state_paralysis", chance: 40 }] }, layers: [{ key: "jester_jack_box", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_jester_mask_swap", classId: "class_jester", actorId: "actor_jester", name: "가면 바꾸기", level: 10, motion: "buff", description: "웃는 가면과 우는 가면을 바꿔 쓰며 변덕을 부린다", mechanic: { kind: "support", scope: "self", states: [{ id: "state_attack_up" }, { id: "state_defense_down" }] }, layers: [{ key: "jester_masks", anchor: "user", frame: 64, frames: 10 }] },
    { id: "skill_jester_balloon_pop", classId: "class_jester", actorId: "actor_jester", name: "풍선 폭죽", level: 12, motion: "cast", description: "풍선 다발을 띄워 한꺼번에 터뜨린다", layers: [{ key: "jester_balloons", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_jester_cartwheel", classId: "class_jester", actorId: "actor_jester", name: "공중제비", level: 16, motion: "spin", description: "재주넘기로 적진을 휘젓고 별똥을 흩뿌린다", mechanic: { states: [{ id: "state_berserk", chance: 30 }] }, layers: [{ key: "hero_whirl", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_jester_carnival", classId: "class_jester", actorId: "actor_jester", name: "대소동 카니발", level: 22, motion: "finisher", description: "서커스 천막이 펼쳐지고 파이가 날아다니는 필살기", mechanic: { hits: [0.35, 0.35, 0.35, 0.35], hpCost: 10, states: [{ id: "state_blind", chance: 40 }] }, layers: [{ key: "jester_carnival_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "bard_finale_hit", anchor: "allTargets", frame: 64, frames: 10 }] },

    // ── 꼬마 발명가(class_girl_alchemist, people5-1) — 폭죽·톱니·태엽·코일·로켓
    { id: "skill_girl_alchemist_firecracker", classId: "class_girl_alchemist", actorId: "actor_girl_alchemist", name: "꼬마 폭죽", level: 1, motion: "shoot", description: "심지에 불붙인 폭죽을 던져 펑 터뜨린다", mechanic: { element: "fire" }, layers: [{ key: "scout_bomb", anchor: "projectile", frame: 32, frames: 4 }, { key: "girl_alchemist_pop", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_girl_alchemist_gear_saw", classId: "class_girl_alchemist", actorId: "actor_girl_alchemist", name: "톱니 날리기", level: 3, motion: "dash-strike", description: "회전하는 톱니바퀴를 달고 달려들어 긁어낸다", mechanic: { states: [{ id: "state_defense_down", chance: 60 }] }, layers: [{ key: "girl_alchemist_gear_saw", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_girl_alchemist_windup_bot", classId: "class_girl_alchemist", actorId: "actor_girl_alchemist", name: "태엽 로봇", level: 5, motion: "cast", description: "태엽 로봇을 풀어 놓으면 적에게 달려가 자폭한다", mechanic: { area: "circle", element: "fire" }, layers: [{ key: "girl_alchemist_robot", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_girl_alchemist_spring_boots", classId: "class_girl_alchemist", actorId: "actor_girl_alchemist", name: "스프링 장화", level: 7, motion: "buff", description: "스프링 장화로 통통 튀며 속도를 끌어올린다", mechanic: { kind: "support", scope: "self", states: [{ id: "state_agility_up" }] }, layers: [{ key: "bard_tempo", anchor: "user", frame: 64, frames: 8 }] },
    { id: "skill_girl_alchemist_tesla", classId: "class_girl_alchemist", actorId: "actor_girl_alchemist", name: "전기 코일", level: 10, motion: "cast", description: "코일을 세워 모든 적에게 번개를 튀긴다", mechanic: { element: "thunder", states: [{ id: "state_paralysis", chance: 30 }] }, layers: [{ key: "mage_chain_bolt", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_girl_alchemist_rocket", classId: "class_girl_alchemist", actorId: "actor_girl_alchemist", name: "로켓 발사", level: 12, motion: "leap-strike", description: "등의 로켓을 점화해 솟구쳤다가 불꽃을 끌며 내리꽂힌다", mechanic: { element: "fire", hpCost: 12 }, layers: [{ key: "hero_dust", anchor: "user", frame: 64, frames: 6 }, { key: "hero_meteor_impact", anchor: "target", frame: 128, frames: 10 }] },
    { id: "skill_girl_alchemist_repair_kit", classId: "class_girl_alchemist", actorId: "actor_girl_alchemist", name: "수리 세트", level: 16, motion: "buff", description: "렌치와 톱니로 아군 전원을 척척 고쳐 준다", mechanic: { kind: "healing", scope: "allAllies", power: 52, states: [{ id: "state_defense_up" }] }, layers: [{ key: "girl_alchemist_repair", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_girl_alchemist_mecha", classId: "class_girl_alchemist", actorId: "actor_girl_alchemist", name: "거대 태엽 인형", level: 22, motion: "finisher", description: "거대한 태엽 인형이 일어나 철권을 내리꽂는 필살기", mechanic: { hits: [0.6, 0.7], states: [{ id: "state_stop", chance: 30 }] }, layers: [{ key: "girl_alchemist_mecha_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "guard_fortress_slam", anchor: "allTargets", frame: 64, frames: 8 }] },

    // ── 낭인(class_ronin, people5-2) — 거합·빗속·먼지·늑대·혈도
    { id: "skill_ronin_draw_cut", classId: "class_ronin", actorId: "actor_ronin", name: "거합 일섬", level: 1, motion: "blink-strike", description: "칼집에서 뽑는 한 줄기 가로 일섬", mechanic: { crit: 35 }, layers: [{ key: "ronin_draw", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_ronin_rain_cut", classId: "class_ronin", actorId: "actor_ronin", name: "우중 난도", level: 3, motion: "flurry", description: "빗줄기 속에서 비껴 치는 연속 베기", mechanic: { hits: [0.4, 0.4, 0.4] }, layers: [{ key: "ronin_rain_cut", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_ronin_dust_slash", classId: "class_ronin", actorId: "actor_ronin", name: "흙먼지 베기", level: 5, motion: "dash-strike", description: "낮게 미끄러져 흙먼지를 일으키며 벤다", mechanic: { states: [{ id: "state_blind", chance: 50 }] }, layers: [{ key: "hero_pierce", anchor: "target", frame: 64, frames: 8 }, { key: "hero_dust", anchor: "user", frame: 64, frames: 6 }] },
    { id: "skill_ronin_ash_stance", classId: "class_ronin", actorId: "actor_ronin", name: "재의 자세", level: 7, motion: "buff", description: "잿빛 불씨를 두르고 살기를 가라앉힌다", mechanic: { kind: "support", scope: "self", states: [{ id: "state_defense_up" }, { id: "state_shell" }] }, layers: [{ key: "ronin_ash_stance", anchor: "user", frame: 64, frames: 10 }] },
    { id: "skill_ronin_wolf_fang", classId: "class_ronin", actorId: "actor_ronin", name: "늑대 이빨", level: 10, motion: "leap-strike", description: "떠돌이 늑대의 혼이 이빨을 드러내며 덮친다", mechanic: { drain: 40 }, layers: [{ key: "mon_fang_bite", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_ronin_crimson_wind", classId: "class_ronin", actorId: "actor_ronin", name: "혈풍", level: 12, motion: "cast", description: "붉은 검풍을 날려 적진을 훑는다", mechanic: { scope: "enemy", area: "line" }, layers: [{ key: "samurai_wind_wave", anchor: "projectile", frame: 32, frames: 4 }, { key: "samurai_blood_hit", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_ronin_blood_path", classId: "class_ronin", actorId: "actor_ronin", name: "혈도 개방", level: 16, motion: "spin", description: "핏빛 문양이 번지며 적 전원의 기력을 갉는다", mechanic: { affects: "mp" }, layers: [{ key: "mon_cleave_arc", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_ronin_last_blade", classId: "class_ronin", actorId: "actor_ronin", name: "낭인의 마지막 검", level: 22, motion: "finisher", description: "모든 것을 버린 단 한 번의 검, 필살기", mechanic: { hpCost: 25, crit: 40 }, layers: [{ key: "ronin_last_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "samurai_final_slash", anchor: "target", frame: 64, frames: 10 }] }
  ],
  partyPixel: []
};
