// 묶음 p5 — 담당 에이전트만 이 파일을 쓴다. 규격: src/assets/retroRoster.ts 머리 주석, 스킬 형식은 retroClassSkills.ts(RetroClassSkill).
// 무녀·사막 전사·메이드·은자·노병 (People5-3 ~ People5-7, 직업 5 × 스킬 8 = 40).
// 이펙트 시트: public/assets/generated/pixel-fx/<key>.png, 생성기 scripts/asset-gen/pixel-fx/fx_<class>.py(공용 lib_r2w4.py).
// 스킬 하나당 새 시트는 최대 1장, 나머지 층은 기존 시트(retroClassSkills·retroMonsterSkills·같은 묶음)를 재사용한다.
import type { RetroRosterBatch } from "@/assets/retroRoster";

export const BATCH: RetroRosterBatch = {
  skills: [
    // ── 무녀(class_shrine_maiden, people5-3) — 부적·고헤이·결계·여우불·토리이
    { id: "skill_shrine_maiden_ofuda", classId: "class_shrine_maiden", actorId: "actor_shrine_maiden", name: "부적 던지기", level: 1, motion: "shoot", description: "주문이 적힌 부적을 날려 붙여 터뜨린다", layers: [{ key: "shrine_maiden_ofuda", anchor: "projectile", frame: 32, frames: 4 }, { key: "holy", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_shrine_maiden_gohei", classId: "class_shrine_maiden", actorId: "actor_shrine_maiden", name: "고헤이 정화", level: 3, motion: "cast", description: "고헤이를 흔들어 종이 술이 아군을 정화하고 치유한다", mechanic: { kind: "healing", scope: "allAllies", power: 40, states: [{ id: "state_poison", op: "remove" }, { id: "state_deep_poison", op: "remove" }, { id: "state_paralysis", op: "remove" }, { id: "state_silence", op: "remove" }] }, layers: [{ key: "shrine_maiden_gohei", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_shrine_maiden_barrier", classId: "class_shrine_maiden", actorId: "actor_shrine_maiden", name: "결계", level: 5, motion: "buff", description: "부적으로 육각 결계를 쳐 아군 전원을 지킨다", mechanic: { kind: "support", scope: "allAllies", states: [{ id: "state_protect" }, { id: "state_shell" }] }, layers: [{ key: "guard_barrier", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_shrine_maiden_fox_dash", classId: "class_shrine_maiden", actorId: "actor_shrine_maiden", name: "여우 돌진", level: 7, motion: "dash-strike", description: "여우 신령이 여우불을 끌며 달려들어 들이받는다", mechanic: { area: "line" }, layers: [{ key: "shrine_maiden_fox", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_shrine_maiden_kagura", classId: "class_shrine_maiden", actorId: "actor_shrine_maiden", name: "카구라 방울춤", level: 10, motion: "buff", description: "방울과 리본을 흔드는 신악 춤으로 기운을 북돋운다", mechanic: { kind: "support", scope: "self", states: [{ id: "state_agility_up" }, { id: "state_attack_up" }] }, layers: [{ key: "bard_tempo", anchor: "user", frame: 64, frames: 8 }] },
    { id: "skill_shrine_maiden_seal", classId: "class_shrine_maiden", actorId: "actor_shrine_maiden", name: "봉인 부적", level: 12, motion: "cast", description: "쇠사슬 무늬 부적으로 적 하나를 꽁꽁 봉인한다", mechanic: { states: [{ id: "state_silence", chance: 60 }] }, layers: [{ key: "shrine_maiden_seal", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_shrine_maiden_rain", classId: "class_shrine_maiden", actorId: "actor_shrine_maiden", name: "정화의 비", level: 16, motion: "cast", description: "맑은 빗방울이 내려 아군 전원을 씻고 회복시킨다", mechanic: { kind: "healing", scope: "allAllies", power: 52, states: [{ id: "state_regen" }, { id: "state_blind", op: "remove" }, { id: "state_sleep", op: "remove" }, { id: "state_poison", op: "remove" }] }, layers: [{ key: "cleric_mass_heal", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_shrine_maiden_divine", classId: "class_shrine_maiden", actorId: "actor_shrine_maiden", name: "천지 개벽 기도", level: 22, motion: "finisher", description: "거대한 토리이가 열리며 신의 빛이 내리는 필살기", mechanic: { kind: "damage", stat: "mind", scope: "allEnemies", power: 180, mp: 36, hits: [0.5, 0.5, 0.4], element: "holy", states: [] }, layers: [{ key: "shrine_maiden_torii_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "cleric_judgment_hit", anchor: "allTargets", frame: 64, frames: 8 }] },

    // ── 사막 전사(class_desert_warrior, people5-4) — 곡도·모래·전갈·태양
    { id: "skill_desert_warrior_crescent", classId: "class_desert_warrior", actorId: "actor_desert_warrior", name: "초승달 베기", level: 1, motion: "dash-strike", description: "곡도로 큼직한 초승달을 그리며 벤다", layers: [{ key: "desert_warrior_crescent", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_desert_warrior_sand_flurry", classId: "class_desert_warrior", actorId: "actor_desert_warrior", name: "모래 갈기", level: 3, motion: "flurry", description: "모래알을 흩뿌리며 곡도를 연달아 긋는다", mechanic: { hits: [0.4, 0.4, 0.4], states: [{ id: "state_blind", chance: 40 }] }, layers: [{ key: "nomad_sand_toss", anchor: "user", frame: 64, frames: 8 }, { key: "scout_flurry", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_desert_warrior_scorpion", classId: "class_desert_warrior", actorId: "actor_desert_warrior", name: "전갈 찌르기", level: 5, motion: "leap-strike", description: "전갈 꼬리처럼 뛰어올라 독침으로 내리꽂는다", mechanic: { states: [{ id: "state_poison", chance: 70 }] }, layers: [{ key: "desert_warrior_scorpion", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_desert_warrior_sunfire", classId: "class_desert_warrior", actorId: "actor_desert_warrior", name: "작열", level: 7, motion: "buff", description: "한낮의 태양 기운에 체력을 태워 공격력을 끌어올린다", mechanic: { kind: "support", scope: "self", hpCost: 15, states: [{ id: "state_attack_up" }] }, layers: [{ key: "desert_warrior_sunfire", anchor: "user", frame: 64, frames: 10 }] },
    { id: "skill_desert_warrior_whirl", classId: "class_desert_warrior", actorId: "actor_desert_warrior", name: "회오리 베기", level: 10, motion: "spin", description: "곡도를 든 채 회전해 모든 적을 벤다", mechanic: { hits: [0.6, 0.6] }, layers: [{ key: "nomad_dust_devil", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_desert_warrior_sun_orb", classId: "class_desert_warrior", actorId: "actor_desert_warrior", name: "태양탄", level: 12, motion: "cast", description: "손안에 모은 태양 불덩이를 던져 폭발시킨다", mechanic: { area: "circle", states: [{ id: "state_oiled", chance: 70 }] }, layers: [{ key: "mage_fireball_orb", anchor: "projectile", frame: 32, frames: 4 }, { key: "mage_fire_burst", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_desert_warrior_wall", classId: "class_desert_warrior", actorId: "actor_desert_warrior", name: "모래 방벽", level: 16, motion: "buff", description: "모래 바위벽이 솟아 아군 전원의 방어를 높인다", mechanic: { kind: "support", scope: "allAllies", states: [{ id: "state_defense_up" }, { id: "state_protect" }] }, layers: [{ key: "earth", anchor: "allAllies", frame: 64, frames: 8 }] },
    { id: "skill_desert_warrior_blades", classId: "class_desert_warrior", actorId: "actor_desert_warrior", name: "백만 곡도", level: 22, motion: "finisher", description: "하늘 가득 곡도가 비처럼 쏟아지는 필살기", mechanic: { hits: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25] }, layers: [{ key: "desert_warrior_blades_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "ninja_thousand_hit", anchor: "allTargets", frame: 64, frames: 10 }] },

    // ── 메이드(class_maid, people5-5) — 빗자루·접시·홍차·비눗방울
    { id: "skill_maid_broom", classId: "class_maid", actorId: "actor_maid", name: "빗자루 쓸기", level: 1, motion: "spin", description: "빗자루를 빙 돌려 모든 적을 먼지처럼 쓸어낸다", layers: [{ key: "maid_broom", anchor: "allTargets", frame: 64, frames: 8 }] },
    { id: "skill_maid_duster", classId: "class_maid", actorId: "actor_maid", name: "먼지떨이 난무", level: 3, motion: "flurry", description: "깃털 먼지떨이로 파고들어 톡톡 두드린다", mechanic: { hits: [0.3, 0.3, 0.3, 0.3] }, layers: [{ key: "maid_duster", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_maid_plate", classId: "class_maid", actorId: "actor_maid", name: "접시 던지기", level: 5, motion: "shoot", description: "식기 접시를 원반처럼 던져 깨뜨린다", mechanic: { area: "line" }, layers: [{ key: "maid_plate", anchor: "projectile", frame: 32, frames: 4 }, { key: "noblewoman_gem_hit", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_maid_tea_time", classId: "class_maid", actorId: "actor_maid", name: "홍차 한 잔", level: 7, motion: "cast", description: "따끈한 홍차를 내어 아군 한 명을 회복시킨다", mechanic: { kind: "healing", scope: "ally", power: 48, states: [{ id: "state_regen" }] }, layers: [{ key: "maid_tea", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_maid_cutlery", classId: "class_maid", actorId: "actor_maid", name: "은식기 난무", level: 10, motion: "dash-strike", description: "포크와 나이프를 양손에 쥐고 번갯불처럼 찌른다", mechanic: { hits: [0.4, 0.4, 0.4] }, layers: [{ key: "knife", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_maid_bubbles", classId: "class_maid", actorId: "actor_maid", name: "비눗물 파도", level: 12, motion: "cast", description: "비눗방울 파도가 밀려와 적 전원을 미끄러뜨린다", mechanic: { states: [{ id: "state_wet", chance: 80 }, { id: "state_agility_down", chance: 60 }] }, layers: [{ key: "maid_bubbles", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_maid_curtsy", classId: "class_maid", actorId: "actor_maid", name: "정중한 인사", level: 16, motion: "buff", description: "깍듯한 인사로 아군 전원의 나쁜 상태를 말끔히 닦아낸다", mechanic: { kind: "support", scope: "allAllies", states: [{ id: "state_poison", op: "remove" }, { id: "state_deep_poison", op: "remove" }, { id: "state_paralysis", op: "remove" }, { id: "state_silence", op: "remove" }, { id: "state_blind", op: "remove" }, { id: "state_sleep", op: "remove" }] }, layers: [{ key: "cleric_blessing", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_maid_spring_clean", classId: "class_maid", actorId: "actor_maid", name: "대청소 대작전", level: 22, motion: "finisher", description: "빨래·비누·먼지가 회오리치는 대청소 필살기", mechanic: { hits: [0.3, 0.3, 0.3, 0.3, 0.3], states: [{ id: "state_wet", chance: 60 }, { id: "state_blind", chance: 40 }] }, layers: [{ key: "maid_clean_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "sailor_tidal_crash", anchor: "allTargets", frame: 64, frames: 10 }] },

    // ── 은자(class_hermit, people5-6) — 돌·죽순·안개·명상·폭포·산
    { id: "skill_hermit_stone", classId: "class_hermit", actorId: "actor_hermit", name: "돌팔매", level: 1, motion: "shoot", description: "기운을 실은 바위를 던져 부순다", layers: [{ key: "mon_boulder", anchor: "projectile", frame: 32, frames: 4 }, { key: "mon_rock_burst", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_hermit_bamboo", classId: "class_hermit", actorId: "actor_hermit", name: "죽순 솟구침", level: 3, motion: "cast", description: "발밑에서 죽순이 뾰족하게 솟아 적을 꿰뚫는다", mechanic: { area: "line" }, layers: [{ key: "hermit_bamboo", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_hermit_mist", classId: "class_hermit", actorId: "actor_hermit", name: "산안개", level: 5, motion: "buff", description: "산안개를 불러 아군 전원을 감싸 마법과 충격을 흐려 놓는다", mechanic: { kind: "support", scope: "allAllies", states: [{ id: "state_shell" }, { id: "state_protect" }] }, layers: [{ key: "hermit_mist", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_hermit_meditate", classId: "class_hermit", actorId: "actor_hermit", name: "명상", level: 7, motion: "buff", description: "돌멩이를 띄우고 눈을 감아 마력을 되찾는다", mechanic: { kind: "healing", affects: "mp", scope: "self", power: 30, mp: 0, cooldown: 2, states: [] }, layers: [{ key: "monk_meditate", anchor: "user", frame: 64, frames: 10 }] },
    { id: "skill_hermit_spores", classId: "class_hermit", actorId: "actor_hermit", name: "포자 구름", level: 10, motion: "cast", description: "버섯 포자를 흩뿌려 적 전원을 졸리게 만든다", mechanic: { kind: "support", scope: "allEnemies", states: [{ id: "state_sleep", chance: 45 }] }, layers: [{ key: "mon_spore_cloud", anchor: "allTargets", frame: 64, frames: 10 }] },
    { id: "skill_hermit_falls", classId: "class_hermit", actorId: "actor_hermit", name: "폭포수", level: 12, motion: "cast", description: "하늘에서 폭포수를 통째로 쏟아 적 하나를 짓누른다", mechanic: { formula: "power * 0.5 + a.mind + b.hp / 6", states: [{ id: "state_wet", chance: 100 }] }, layers: [{ key: "hermit_falls", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_hermit_crane", classId: "class_hermit", actorId: "actor_hermit", name: "학의 날갯짓", level: 16, motion: "leap-strike", description: "흰 학이 날개를 펴고 내리꽂히며 바람을 가른다", mechanic: { hits: [0.6, 0.6], element: "wind" }, layers: [{ key: "hermit_crane", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_hermit_mountain", classId: "class_hermit", actorId: "actor_hermit", name: "산의 노래", level: 22, motion: "finisher", description: "산봉우리가 솟고 바위 기둥이 적진을 뚫는 필살기", mechanic: { hits: [0.5, 0.5, 0.4], states: [{ id: "state_paralysis", chance: 35 }] }, layers: [{ key: "hermit_mountain_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "guard_quake", anchor: "allTargets", frame: 64, frames: 10 }] },

    // ── 노병(class_old_warrior, people5-7) — 방패·찌르기·방어 태세·화약·훈장
    { id: "skill_old_warrior_bash", classId: "class_old_warrior", actorId: "actor_old_warrior", name: "방패 밀치기", level: 1, motion: "dash-strike", description: "낡은 둥근 방패로 어깨를 실어 밀쳐 넘어뜨린다", mechanic: { states: [{ id: "state_stop", chance: 35 }] }, layers: [{ key: "guard_bash", anchor: "target", frame: 64, frames: 8 }] },
    { id: "skill_old_warrior_thrust", classId: "class_old_warrior", actorId: "actor_old_warrior", name: "노련한 찌르기", level: 3, motion: "flurry", description: "군더더기 없는 찌르기를 빈틈에 연달아 꽂는다", mechanic: { hits: [0.4, 0.4, 0.4] }, layers: [{ key: "old_warrior_thrust", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_old_warrior_stance", classId: "class_old_warrior", actorId: "actor_old_warrior", name: "방어 태세", level: 5, motion: "buff", description: "발을 딛고 방패를 세워 어떤 공격도 버틴다", mechanic: { kind: "support", scope: "self", states: [{ id: "state_defense_up" }, { id: "state_protect" }] }, layers: [{ key: "old_warrior_stance", anchor: "user", frame: 64, frames: 10 }] },
    { id: "skill_old_warrior_story", classId: "class_old_warrior", actorId: "actor_old_warrior", name: "무용담", level: 7, motion: "buff", description: "옛 전장의 이야기로 아군 전원의 사기를 끌어올린다", layers: [{ key: "old_warrior_story", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_old_warrior_flask", classId: "class_old_warrior", actorId: "actor_old_warrior", name: "화약 항아리", level: 10, motion: "shoot", description: "심지 붙은 화약 항아리를 던져 폭발시킨다", mechanic: { area: "circle" }, layers: [{ key: "old_warrior_flask", anchor: "projectile", frame: 32, frames: 4 }, { key: "mage_fire_burst", anchor: "target", frame: 64, frames: 10 }] },
    { id: "skill_old_warrior_smash", classId: "class_old_warrior", actorId: "actor_old_warrior", name: "낙하 내려찍기", level: 12, motion: "leap-strike", description: "온 체중을 실어 뛰어내려 창끝으로 땅을 꿰뚫는다", mechanic: { formula: "power * 0.8 + a.def + a.level" }, layers: [{ key: "hero_meteor_impact", anchor: "target", frame: 128, frames: 10 }] },
    { id: "skill_old_warrior_medal", classId: "class_old_warrior", actorId: "actor_old_warrior", name: "훈장의 빛", level: 16, motion: "buff", description: "가슴의 훈장이 빛나 아군 전원을 북돋아 회복시킨다", mechanic: { kind: "healing", scope: "allAllies", power: 52, states: [{ id: "state_regen" }] }, layers: [{ key: "old_warrior_medal", anchor: "allAllies", frame: 64, frames: 10 }] },
    { id: "skill_old_warrior_ironwall", classId: "class_old_warrior", actorId: "actor_old_warrior", name: "불굴의 방패벽", level: 22, motion: "finisher", description: "옛 전우들의 환영 방패가 줄지어 서서 적을 짓누르는 필살기", mechanic: { hits: [0.5, 0.5, 0.4], states: [{ id: "state_attack_down", chance: 60 }] }, layers: [{ key: "old_warrior_ironwall_sky", anchor: "screen", frame: 128, frames: 12 }, { key: "guard_fortress_slam", anchor: "allTargets", frame: 64, frames: 8 }] }
  ],
  partyPixel: []
};
