/** Existing, reviewed artwork; complete buildings stay intact and props identify their use. */
export const beodeulFacilityPlans=[
 ['inn','여관','village-brick','휴식·교류','bench_wood','laundry_rack'],
 ['tavern','술집','cafe','휴식·교류','table_mugs','stall_jug_bottle'],
 ['cafe','찻집·식당','cafe','휴식·교류','parasol_table','bread_rack'],
 ['general-shop','잡화점','village-ochre','거래·장비','goods_pile','sandwich_board'],
 ['weapon-shop','무기점','village-brick','거래·장비','sword_barrel','goods_pile'],
 ['armour-shop','방어구점','village-cream','거래·장비','cloth_stand','sword_barrel'],
 ['smithy','대장간','smithy_town','거래·장비','@volcano-cave-anvil','@volcano-cave-ingots'],
 ['jeweller','보석상','village-stone','거래·장비','sandwich_board','planter_round'],
 ['apothecary','약초사 집','village-cream','마법·치료','@wizard-tower-herb-rack','@wizard-tower-bed-herb'],
 ['alchemist','연금술 공방','village-stone','마법·치료','@wizard-tower-athanor','@wizard-tower-herb-rack'],
 ['healer','치료소','village-ochre','마법·치료','door_pots','bench_wood'],
 ['chapel','예배당','village-church','신앙','flowerbox_long','bench_wood'],
 ['adventurers-guild','모험가 길드','village-brick','의뢰·성장','sandwich_board','sword_barrel'],
 ['training-house','훈련소','village-ochre','의뢰·성장','sword_barrel','bench_wood'],
 ['guardhouse','경비초소','village-stone','통치·치안','sword_barrel','lamp_crook'],
 ['prison','감옥','village-stone','통치·치안','sandwich_board','lamp_crook'],
 ['village-hall','촌장 집·회관','manor','통치·치안','sandwich_board','bench_wood'],
 ['bank','금고·은행','village-stone','거래·보관','sandwich_board','goods_pile'],
 ['stable','마구간·역참','cstable','이동·물류','+hay-barrels','bench_wood'],
 ['ferry-office','나루터 사무소','village-sage','이동·물류','anchor_display','mooring_bollard'],
 ['warehouse','항구 창고','ware0','이동·물류','goods_pile','fish_crates'],
 ['granary','곡물창고','ware0','생산·생활','+hay-barrels','goods_pile'],
 ['bakery','빵집','village-ochre','생산·생활','bread_rack','sandwich_board'],
 ['brewery','양조장','village-brick','생산·생활','stall_jug_bottle','table_mugs'],
 ['tailor','재단사 집','village-cream','생산·생활','cloth_stand','laundry_rack'],
 ['carpenter','목공소','village-ochre','생산·생활','+woodpile','goods_pile'],
 ['library','서점·도서관','village-brick','지식·문화','sandwich_board','bench_wood'],
 ['inventor','발명가 집','village-stone','특별한 이야기','@wizard-tower-armillary','@wizard-tower-orrery'],
 ['mage','마법사 거처','village-sage','특별한 이야기','@wizard-tower-athanor','@wizard-tower-globe'],
 ['fortune-teller','점술집','village-stone','특별한 이야기','@wizard-tower-globe','@wizard-tower-sundial'],
 ['retired-adventurer','은퇴한 모험가의 집','village-cream','특별한 이야기','sword_barrel','bench_wood'],
 ['missing-family','실종자 가족의 집','village-ochre','특별한 이야기','laundry_rack','flowerbox_long'],
] as const;
export const facilityPropId=(key:string)=>key.startsWith('@')?'bd-pick-'+key.slice(1):key.startsWith('+')?'bd-out-'+key.slice(1):'bd-prop-'+key;
