export type Cc0IconAsset = {
  readonly id: string;
  readonly name: string;
  readonly path: string;
  readonly sourceName: string;
  readonly sourceUrl: string;
  readonly license: "CC0-1.0" | "generated";
};

const JETREL_SOURCE_URL = "https://opengameart.org/content/16x16-rpg-items";
const JETREL_SOURCE_NAME = "Jetrel 16x16 RPG items";
const GENERATED_SOURCE_NAME = "RPG ZZU generated item icons";
const GENERATED_SOURCE_URL = "https://github.com/local/rpg-zzu";

function jetrelIcon(id: string, fileName: string, name: string): Cc0IconAsset {
  return { id, name, path: `assets/cc0/jetrel/icons/${fileName}`, sourceName: JETREL_SOURCE_NAME, sourceUrl: JETREL_SOURCE_URL, license: "CC0-1.0" };
}

function generatedIcon(id: string, fileName: string, name: string): Cc0IconAsset {
  return { id, name, path: `assets/cc0/jetrel/icons/${fileName}`, sourceName: GENERATED_SOURCE_NAME, sourceUrl: GENERATED_SOURCE_URL, license: "generated" };
}

export const CC0_ICON_ASSETS = [
  generatedIcon("cc0-jetrel-ale", "ale.png", "ale"),
  jetrelIcon("cc0-jetrel-antidote-green", "antidote-green.png", "antidote green"),
  generatedIcon("cc0-jetrel-antidote-plus", "antidote-plus.png", "antidote plus"),
  generatedIcon("cc0-jetrel-apple", "apple.png", "apple"),
  generatedIcon("cc0-jetrel-arrow-bundle", "arrow-bundle.png", "arrow bundle"),
  generatedIcon("cc0-jetrel-badge", "badge.png", "badge"),
  generatedIcon("cc0-jetrel-bandages", "bandages.png", "bandages"),
  generatedIcon("cc0-jetrel-battery", "battery.png", "battery"),
  generatedIcon("cc0-jetrel-bell", "bell.png", "bell"),
  generatedIcon("cc0-jetrel-bomb", "bomb.png", "bomb"),
  generatedIcon("cc0-jetrel-bone", "bone.png", "bone"),
  generatedIcon("cc0-jetrel-book-magic", "book-magic.png", "book magic"),
  generatedIcon("cc0-jetrel-book-sword", "book-sword.png", "book sword"),
  generatedIcon("cc0-jetrel-boots", "boots.png", "boots"),
  generatedIcon("cc0-jetrel-bread", "bread.png", "bread"),
  jetrelIcon("cc0-jetrel-bronze-sword", "bronze-sword.png", "bronze sword"),
  generatedIcon("cc0-jetrel-bullet", "bullet.png", "bullet"),
  generatedIcon("cc0-jetrel-camera", "camera.png", "camera"),
  generatedIcon("cc0-jetrel-candle", "candle.png", "candle"),
  generatedIcon("cc0-jetrel-candy", "candy.png", "candy"),
  generatedIcon("cc0-jetrel-capture-orb", "capture-orb.png", "capture orb"),
  generatedIcon("cc0-jetrel-cheese", "cheese.png", "cheese"),
  generatedIcon("cc0-jetrel-claw", "claw.png", "claw"),
  generatedIcon("cc0-jetrel-cloak", "cloak.png", "cloak"),
  generatedIcon("cc0-jetrel-clock", "clock.png", "clock"),
  generatedIcon("cc0-jetrel-coal", "coal.png", "coal"),
  generatedIcon("cc0-jetrel-coffee", "coffee.png", "coffee"),
  generatedIcon("cc0-jetrel-coin-pouch", "coin-pouch.png", "coin pouch"),
  generatedIcon("cc0-jetrel-compass", "compass.png", "compass"),
  generatedIcon("cc0-jetrel-cookie", "cookie.png", "cookie"),
  generatedIcon("cc0-jetrel-corn", "corn.png", "corn"),
  generatedIcon("cc0-jetrel-crystal", "crystal.png", "crystal"),
  generatedIcon("cc0-jetrel-earth-ore", "earth-ore.png", "earth ore"),
  generatedIcon("cc0-jetrel-egg", "egg.png", "egg"),
  generatedIcon("cc0-jetrel-elixir", "elixir.png", "elixir"),
  jetrelIcon("cc0-jetrel-ether-blue", "ether-blue.png", "ether blue"),
  generatedIcon("cc0-jetrel-eye-drops", "eye-drops.png", "eye drops"),
  generatedIcon("cc0-jetrel-fang", "fang.png", "fang"),
  generatedIcon("cc0-jetrel-fire-bomb", "fire-bomb.png", "fire bomb"),
  generatedIcon("cc0-jetrel-fish", "fish.png", "fish"),
  generatedIcon("cc0-jetrel-fishing-rod", "fishing-rod.png", "fishing rod"),
  generatedIcon("cc0-jetrel-flute", "flute.png", "flute"),
  jetrelIcon("cc0-jetrel-focus-charm", "focus-charm.png", "focus charm"),
  generatedIcon("cc0-jetrel-focus-ring", "focus-ring.png", "focus ring"),
  generatedIcon("cc0-jetrel-gear", "gear.png", "gear"),
  generatedIcon("cc0-jetrel-gem-emerald", "gem-emerald.png", "gem emerald"),
  generatedIcon("cc0-jetrel-gem-ruby", "gem-ruby.png", "gem ruby"),
  generatedIcon("cc0-jetrel-gem-sapphire", "gem-sapphire.png", "gem sapphire"),
  generatedIcon("cc0-jetrel-gloves", "gloves.png", "gloves"),
  generatedIcon("cc0-jetrel-gold-bar", "gold-bar.png", "gold bar"),
  generatedIcon("cc0-jetrel-herb-blue", "herb-blue.png", "herb blue"),
  generatedIcon("cc0-jetrel-herb-green", "herb-green.png", "herb green"),
  generatedIcon("cc0-jetrel-hi-potion", "hi-potion.png", "hi potion"),
  generatedIcon("cc0-jetrel-hide", "hide.png", "hide"),
  generatedIcon("cc0-jetrel-hoe", "hoe.png", "hoe"),
  generatedIcon("cc0-jetrel-holy-water", "holy-water.png", "holy water"),
  generatedIcon("cc0-jetrel-honey", "honey.png", "honey"),
  generatedIcon("cc0-jetrel-ice-shard", "ice-shard.png", "ice shard"),
  generatedIcon("cc0-jetrel-ink", "ink.png", "ink"),
  generatedIcon("cc0-jetrel-iron-ore", "iron-ore.png", "iron ore"),
  generatedIcon("cc0-jetrel-iron-shield", "iron-shield.png", "iron shield"),
  generatedIcon("cc0-jetrel-iron-sword", "iron-sword.png", "iron sword"),
  generatedIcon("cc0-jetrel-lantern", "lantern.png", "lantern"),
  jetrelIcon("cc0-jetrel-leather-armor", "leather-armor.png", "leather armor"),
  generatedIcon("cc0-jetrel-leather-patch", "leather-patch.png", "leather patch"),
  generatedIcon("cc0-jetrel-letter", "letter.png", "letter"),
  generatedIcon("cc0-jetrel-lucky-charm", "lucky-charm.png", "lucky charm"),
  generatedIcon("cc0-jetrel-mage-hat", "mage-hat.png", "mage hat"),
  jetrelIcon("cc0-jetrel-mage-staff", "mage-staff.png", "mage staff"),
  generatedIcon("cc0-jetrel-mana-tea", "mana-tea.png", "mana tea"),
  generatedIcon("cc0-jetrel-map", "map.png", "map"),
  generatedIcon("cc0-jetrel-meat", "meat.png", "meat"),
  generatedIcon("cc0-jetrel-medal", "medal.png", "medal"),
  generatedIcon("cc0-jetrel-milk", "milk.png", "milk"),
  generatedIcon("cc0-jetrel-mirror", "mirror.png", "mirror"),
  generatedIcon("cc0-jetrel-mushroom", "mushroom.png", "mushroom"),
  generatedIcon("cc0-jetrel-mystic-cloth", "mystic-cloth.png", "mystic cloth"),
  jetrelIcon("cc0-jetrel-mystic-robe", "mystic-robe.png", "mystic robe"),
  generatedIcon("cc0-jetrel-necklace", "necklace.png", "necklace"),
  generatedIcon("cc0-jetrel-net", "net.png", "net"),
  generatedIcon("cc0-jetrel-notebook", "notebook.png", "notebook"),
  jetrelIcon("cc0-jetrel-oak-shield", "oak-shield.png", "oak shield"),
  generatedIcon("cc0-jetrel-oil", "oil.png", "oil"),
  jetrelIcon("cc0-jetrel-old-key-scroll", "old-key-scroll.png", "old key scroll"),
  generatedIcon("cc0-jetrel-old-key", "old-key.png", "old key"),
  generatedIcon("cc0-jetrel-panacea", "panacea.png", "panacea"),
  generatedIcon("cc0-jetrel-pass", "pass.png", "pass"),
  generatedIcon("cc0-jetrel-pearl", "pearl.png", "pearl"),
  generatedIcon("cc0-jetrel-phoenix-down", "phoenix-down.png", "phoenix down"),
  generatedIcon("cc0-jetrel-pickaxe", "pickaxe.png", "pickaxe"),
  jetrelIcon("cc0-jetrel-poison-dart", "poison-dart.png", "poison dart"),
  generatedIcon("cc0-jetrel-poison-vial", "poison-vial.png", "poison vial"),
  generatedIcon("cc0-jetrel-potato", "potato.png", "potato"),
  jetrelIcon("cc0-jetrel-potion-red", "potion-red.png", "potion red"),
  generatedIcon("cc0-jetrel-quill", "quill.png", "quill"),
  generatedIcon("cc0-jetrel-radio", "radio.png", "radio"),
  generatedIcon("cc0-jetrel-repair-kit", "repair-kit.png", "repair kit"),
  generatedIcon("cc0-jetrel-rice-ball", "rice-ball.png", "rice ball"),
  generatedIcon("cc0-jetrel-ring", "ring.png", "ring"),
  generatedIcon("cc0-jetrel-rope", "rope.png", "rope"),
  generatedIcon("cc0-jetrel-scale", "scale.png", "scale"),
  jetrelIcon("cc0-jetrel-scout-dagger", "scout-dagger.png", "scout dagger"),
  generatedIcon("cc0-jetrel-screw", "screw.png", "screw"),
  generatedIcon("cc0-jetrel-scroll", "scroll.png", "scroll"),
  generatedIcon("cc0-jetrel-seed-bag", "seed-bag.png", "seed bag"),
  generatedIcon("cc0-jetrel-shell", "shell.png", "shell"),
  generatedIcon("cc0-jetrel-skill-book", "skill-book.png", "skill book"),
  generatedIcon("cc0-jetrel-sleeping-powder", "sleeping-powder.png", "sleeping powder"),
  generatedIcon("cc0-jetrel-smelling-salts", "smelling-salts.png", "smelling salts"),
  generatedIcon("cc0-jetrel-smoke-bomb", "smoke-bomb.png", "smoke bomb"),
  generatedIcon("cc0-jetrel-soap", "soap.png", "soap"),
  generatedIcon("cc0-jetrel-soup", "soup.png", "soup"),
  generatedIcon("cc0-jetrel-stamina-drink", "stamina-drink.png", "stamina drink"),
  generatedIcon("cc0-jetrel-steel-armor", "steel-armor.png", "steel armor"),
  generatedIcon("cc0-jetrel-steel-sword", "steel-sword.png", "steel sword"),
  generatedIcon("cc0-jetrel-stew", "stew.png", "stew"),
  generatedIcon("cc0-jetrel-strawberry", "strawberry.png", "strawberry"),
  generatedIcon("cc0-jetrel-talisman", "talisman.png", "talisman"),
  generatedIcon("cc0-jetrel-tea", "tea.png", "tea"),
  generatedIcon("cc0-jetrel-throwing-knife", "throwing-knife.png", "throwing knife"),
  generatedIcon("cc0-jetrel-thunder-stone", "thunder-stone.png", "thunder stone"),
  generatedIcon("cc0-jetrel-ticket", "ticket.png", "ticket"),
  generatedIcon("cc0-jetrel-tomato", "tomato.png", "tomato"),
  generatedIcon("cc0-jetrel-torch", "torch.png", "torch"),
  generatedIcon("cc0-jetrel-traveler-badge", "traveler-badge.png", "traveler badge"),
  jetrelIcon("cc0-jetrel-traveler-hat", "traveler-hat.png", "traveler hat"),
  generatedIcon("cc0-jetrel-trophy", "trophy.png", "trophy"),
  jetrelIcon("cc0-jetrel-wake-herb", "wake-herb.png", "wake herb"),
  generatedIcon("cc0-jetrel-warp-scroll", "warp-scroll.png", "warp scroll"),
  generatedIcon("cc0-jetrel-water-flask", "water-flask.png", "water flask"),
  generatedIcon("cc0-jetrel-watering-can", "watering-can.png", "watering can"),
  generatedIcon("cc0-jetrel-wind-feather", "wind-feather.png", "wind feather"),
  generatedIcon("cc0-jetrel-wine", "wine.png", "wine"),
  generatedIcon("cc0-jetrel-wood", "wood.png", "wood"),
] as const satisfies readonly Cc0IconAsset[];

export function resolveCc0IconAssetUrl(resourceId: string): string | null {
  const asset = CC0_ICON_ASSETS.find((entry) => entry.id === resourceId);
  return asset ? `/${asset.path}` : null;
}
