import { PRODUCT_BRAND } from "@/brand";
import sharedIconAssets from "./sharedItemIconAssets.json";

export type Cc0IconAsset = {
  readonly id: string;
  readonly name: string;
  readonly path: string;
  readonly sourceName: string;
  readonly sourceUrl: string;
  readonly license: "CC0-1.0" | "generated";
  readonly imageWidth: number;
  readonly imageHeight: number;
};

const GENERATED_SOURCE_NAME = `${PRODUCT_BRAND} generated item icons`;
const GENERATED_SOURCE_URL = "https://github.com/MovieHolic-Plex/OpenRPGMaker";

function jetrelIcon(id: string, fileName: string, name: string): Cc0IconAsset {
  // Keep historical IDs; the replacement illustrations are generated, not Jetrel art.
  return generatedIcon(id, fileName, name);
}

function generatedIcon(id: string, fileName: string, name: string): Cc0IconAsset {
  return { id, name, path: `assets/cc0/jetrel/icons/${fileName}`, sourceName: GENERATED_SOURCE_NAME, sourceUrl: GENERATED_SOURCE_URL, license: "generated", imageWidth: 32, imageHeight: 32 };
}

export const CC0_ICON_ASSETS = [
  generatedIcon("cc0-jetrel-ale", "ale.png", "ale"),
  jetrelIcon("cc0-jetrel-antidote-green", "antidote-green.png", "antidote green"),
  generatedIcon("cc0-jetrel-antidote-plus", "antidote-plus.png", "antidote plus"),
  generatedIcon("cc0-jetrel-apple", "apple.png", "apple"),
  generatedIcon("cc0-jetrel-arrow-bundle", "arrow-bundle.png", "arrow bundle"),
  generatedIcon("cc0-jetrel-badge", "badge.png", "badge"),
  generatedIcon("cc0-jetrel-bandages", "bandages.png", "bandages"),
  generatedIcon("cc0-jetrel-battery", "battery.png", "battery"),
  generatedIcon("cc0-jetrel-bell", "bell.png", "bell"),
  generatedIcon("cc0-jetrel-bomb", "bomb.png", "bomb"),
  generatedIcon("cc0-jetrel-bone", "bone.png", "bone"),
  generatedIcon("cc0-jetrel-book-magic", "book-magic.png", "book magic"),
  generatedIcon("cc0-jetrel-book-sword", "book-sword.png", "book sword"),
  generatedIcon("cc0-jetrel-boots", "boots.png", "boots"),
  generatedIcon("cc0-jetrel-bread", "bread.png", "bread"),
  jetrelIcon("cc0-jetrel-bronze-sword", "bronze-sword.png", "bronze sword"),
  generatedIcon("cc0-jetrel-bullet", "bullet.png", "bullet"),
  generatedIcon("cc0-jetrel-camera", "camera.png", "camera"),
  generatedIcon("cc0-jetrel-candle", "candle.png", "candle"),
  generatedIcon("cc0-jetrel-candy", "candy.png", "candy"),
  generatedIcon("cc0-jetrel-capture-orb", "capture-orb.png", "capture orb"),
  generatedIcon("cc0-jetrel-cheese", "cheese.png", "cheese"),
  generatedIcon("cc0-jetrel-claw", "claw.png", "claw"),
  generatedIcon("cc0-jetrel-cloak", "cloak.png", "cloak"),
  generatedIcon("cc0-jetrel-clock", "clock.png", "clock"),
  generatedIcon("cc0-jetrel-coal", "coal.png", "coal"),
  generatedIcon("cc0-jetrel-coffee", "coffee.png", "coffee"),
  generatedIcon("cc0-jetrel-coin-pouch", "coin-pouch.png", "coin pouch"),
  generatedIcon("cc0-jetrel-compass", "compass.png", "compass"),
  generatedIcon("cc0-jetrel-cookie", "cookie.png", "cookie"),
  generatedIcon("cc0-jetrel-corn", "corn.png", "corn"),
  generatedIcon("cc0-jetrel-crystal", "crystal.png", "crystal"),
  generatedIcon("cc0-jetrel-earth-ore", "earth-ore.png", "earth ore"),
  generatedIcon("cc0-jetrel-egg", "egg.png", "egg"),
  generatedIcon("cc0-jetrel-elixir", "elixir.png", "elixir"),
  jetrelIcon("cc0-jetrel-ether-blue", "ether-blue.png", "ether blue"),
  generatedIcon("cc0-jetrel-eye-drops", "eye-drops.png", "eye drops"),
  generatedIcon("cc0-jetrel-fang", "fang.png", "fang"),
  generatedIcon("cc0-jetrel-fire-bomb", "fire-bomb.png", "fire bomb"),
  generatedIcon("cc0-jetrel-fish", "fish.png", "fish"),
  generatedIcon("cc0-jetrel-fishing-rod", "fishing-rod.png", "fishing rod"),
  generatedIcon("cc0-jetrel-flute", "flute.png", "flute"),
  jetrelIcon("cc0-jetrel-focus-charm", "focus-charm.png", "focus charm"),
  generatedIcon("cc0-jetrel-focus-ring", "focus-ring.png", "focus ring"),
  generatedIcon("cc0-jetrel-gear", "gear.png", "gear"),
  generatedIcon("cc0-jetrel-gem-emerald", "gem-emerald.png", "gem emerald"),
  generatedIcon("cc0-jetrel-gem-ruby", "gem-ruby.png", "gem ruby"),
  generatedIcon("cc0-jetrel-gem-sapphire", "gem-sapphire.png", "gem sapphire"),
  generatedIcon("cc0-jetrel-gloves", "gloves.png", "gloves"),
  generatedIcon("cc0-jetrel-gold-bar", "gold-bar.png", "gold bar"),
  generatedIcon("cc0-jetrel-herb-blue", "herb-blue.png", "herb blue"),
  generatedIcon("cc0-jetrel-herb-green", "herb-green.png", "herb green"),
  generatedIcon("cc0-jetrel-hi-potion", "hi-potion.png", "hi potion"),
  generatedIcon("cc0-jetrel-hide", "hide.png", "hide"),
  generatedIcon("cc0-jetrel-hoe", "hoe.png", "hoe"),
  generatedIcon("cc0-jetrel-holy-water", "holy-water.png", "holy water"),
  generatedIcon("cc0-jetrel-honey", "honey.png", "honey"),
  generatedIcon("cc0-jetrel-ice-shard", "ice-shard.png", "ice shard"),
  generatedIcon("cc0-jetrel-ink", "ink.png", "ink"),
  generatedIcon("cc0-jetrel-iron-ore", "iron-ore.png", "iron ore"),
  generatedIcon("cc0-jetrel-iron-shield", "iron-shield.png", "iron shield"),
  generatedIcon("cc0-jetrel-iron-sword", "iron-sword.png", "iron sword"),
  generatedIcon("cc0-jetrel-lantern", "lantern.png", "lantern"),
  jetrelIcon("cc0-jetrel-leather-armor", "leather-armor.png", "leather armor"),
  generatedIcon("cc0-jetrel-leather-patch", "leather-patch.png", "leather patch"),
  generatedIcon("cc0-jetrel-letter", "letter.png", "letter"),
  generatedIcon("cc0-jetrel-lucky-charm", "lucky-charm.png", "lucky charm"),
  generatedIcon("cc0-jetrel-mage-hat", "mage-hat.png", "mage hat"),
  jetrelIcon("cc0-jetrel-mage-staff", "mage-staff.png", "mage staff"),
  generatedIcon("cc0-jetrel-mana-tea", "mana-tea.png", "mana tea"),
  generatedIcon("cc0-jetrel-map", "map.png", "map"),
  generatedIcon("cc0-jetrel-meat", "meat.png", "meat"),
  generatedIcon("cc0-jetrel-medal", "medal.png", "medal"),
  generatedIcon("cc0-jetrel-milk", "milk.png", "milk"),
  generatedIcon("cc0-jetrel-mirror", "mirror.png", "mirror"),
  generatedIcon("cc0-jetrel-mushroom", "mushroom.png", "mushroom"),
  generatedIcon("cc0-jetrel-mystic-cloth", "mystic-cloth.png", "mystic cloth"),
  jetrelIcon("cc0-jetrel-mystic-robe", "mystic-robe.png", "mystic robe"),
  generatedIcon("cc0-jetrel-necklace", "necklace.png", "necklace"),
  generatedIcon("cc0-jetrel-net", "net.png", "net"),
  generatedIcon("cc0-jetrel-notebook", "notebook.png", "notebook"),
  jetrelIcon("cc0-jetrel-oak-shield", "oak-shield.png", "oak shield"),
  generatedIcon("cc0-jetrel-oil", "oil.png", "oil"),
  jetrelIcon("cc0-jetrel-old-key-scroll", "old-key-scroll.png", "old key scroll"),
  generatedIcon("cc0-jetrel-old-key", "old-key.png", "old key"),
  generatedIcon("cc0-jetrel-panacea", "panacea.png", "panacea"),
  generatedIcon("cc0-jetrel-pass", "pass.png", "pass"),
  generatedIcon("cc0-jetrel-pearl", "pearl.png", "pearl"),
  generatedIcon("cc0-jetrel-phoenix-down", "phoenix-down.png", "phoenix down"),
  generatedIcon("cc0-jetrel-pickaxe", "pickaxe.png", "pickaxe"),
  jetrelIcon("cc0-jetrel-poison-dart", "poison-dart.png", "poison dart"),
  generatedIcon("cc0-jetrel-poison-vial", "poison-vial.png", "poison vial"),
  generatedIcon("cc0-jetrel-potato", "potato.png", "potato"),
  jetrelIcon("cc0-jetrel-potion-red", "potion-red.png", "potion red"),
  generatedIcon("cc0-jetrel-quill", "quill.png", "quill"),
  generatedIcon("cc0-jetrel-radio", "radio.png", "radio"),
  generatedIcon("cc0-jetrel-repair-kit", "repair-kit.png", "repair kit"),
  generatedIcon("cc0-jetrel-rice-ball", "rice-ball.png", "rice ball"),
  generatedIcon("cc0-jetrel-ring", "ring.png", "ring"),
  generatedIcon("cc0-jetrel-rope", "rope.png", "rope"),
  generatedIcon("cc0-jetrel-scale", "scale.png", "scale"),
  jetrelIcon("cc0-jetrel-scout-dagger", "scout-dagger.png", "scout dagger"),
  generatedIcon("cc0-jetrel-screw", "screw.png", "screw"),
  generatedIcon("cc0-jetrel-scroll", "scroll.png", "scroll"),
  generatedIcon("cc0-jetrel-seed-bag", "seed-bag.png", "seed bag"),
  generatedIcon("cc0-jetrel-shell", "shell.png", "shell"),
  generatedIcon("cc0-jetrel-skill-book", "skill-book.png", "skill book"),
  generatedIcon("cc0-jetrel-sleeping-powder", "sleeping-powder.png", "sleeping powder"),
  generatedIcon("cc0-jetrel-smelling-salts", "smelling-salts.png", "smelling salts"),
  generatedIcon("cc0-jetrel-smoke-bomb", "smoke-bomb.png", "smoke bomb"),
  generatedIcon("cc0-jetrel-soap", "soap.png", "soap"),
  generatedIcon("cc0-jetrel-soup", "soup.png", "soup"),
  generatedIcon("cc0-jetrel-stamina-drink", "stamina-drink.png", "stamina drink"),
  generatedIcon("cc0-jetrel-steel-armor", "steel-armor.png", "steel armor"),
  generatedIcon("cc0-jetrel-steel-sword", "steel-sword.png", "steel sword"),
  generatedIcon("cc0-jetrel-stew", "stew.png", "stew"),
  generatedIcon("cc0-jetrel-strawberry", "strawberry.png", "strawberry"),
  generatedIcon("cc0-jetrel-talisman", "talisman.png", "talisman"),
  generatedIcon("cc0-jetrel-tea", "tea.png", "tea"),
  generatedIcon("cc0-jetrel-throwing-knife", "throwing-knife.png", "throwing knife"),
  generatedIcon("cc0-jetrel-thunder-stone", "thunder-stone.png", "thunder stone"),
  generatedIcon("cc0-jetrel-ticket", "ticket.png", "ticket"),
  generatedIcon("cc0-jetrel-tomato", "tomato.png", "tomato"),
  generatedIcon("cc0-jetrel-torch", "torch.png", "torch"),
  generatedIcon("cc0-jetrel-traveler-badge", "traveler-badge.png", "traveler badge"),
  jetrelIcon("cc0-jetrel-traveler-hat", "traveler-hat.png", "traveler hat"),
  generatedIcon("cc0-jetrel-trophy", "trophy.png", "trophy"),
  jetrelIcon("cc0-jetrel-wake-herb", "wake-herb.png", "wake herb"),
  generatedIcon("cc0-jetrel-warp-scroll", "warp-scroll.png", "warp scroll"),
  generatedIcon("cc0-jetrel-water-flask", "water-flask.png", "water flask"),
  generatedIcon("cc0-jetrel-watering-can", "watering-can.png", "watering can"),
  generatedIcon("cc0-jetrel-wind-feather", "wind-feather.png", "wind feather"),
  generatedIcon("cc0-jetrel-wine", "wine.png", "wine"),
  generatedIcon("cc0-jetrel-wood", "wood.png", "wood"),
  // ── 생성 아이템 아이콘 100종 (scripts/asset-gen/manifest.mjs 의 ITEMS) ──
  // 회복 소비품
  generatedIcon("cc0-jetrel-gen-potion-small", "gen-potion-small.png", "작은 물약"),
  generatedIcon("cc0-jetrel-gen-potion-large", "gen-potion-large.png", "큰 물약"),
  generatedIcon("cc0-jetrel-gen-ether-vial", "gen-ether-vial.png", "에테르 병"),
  generatedIcon("cc0-jetrel-gen-ether-grand", "gen-ether-grand.png", "고급 에테르"),
  generatedIcon("cc0-jetrel-gen-elixir-gold", "gen-elixir-gold.png", "황금 엘릭서"),
  generatedIcon("cc0-jetrel-gen-panacea-jar", "gen-panacea-jar.png", "만능약"),
  generatedIcon("cc0-jetrel-gen-antidote-leaf", "gen-antidote-leaf.png", "해독 잎"),
  generatedIcon("cc0-jetrel-gen-eyedrops", "gen-eyedrops.png", "눈약"),
  generatedIcon("cc0-jetrel-gen-echo-bell", "gen-echo-bell.png", "메아리 종"),
  generatedIcon("cc0-jetrel-gen-revive-feather", "gen-revive-feather.png", "부활 깃털"),
  generatedIcon("cc0-jetrel-gen-phoenix-ash", "gen-phoenix-ash.png", "불사조 재"),
  generatedIcon("cc0-jetrel-gen-bandage-roll", "gen-bandage-roll.png", "붕대"),
  generatedIcon("cc0-jetrel-gen-herb-bundle", "gen-herb-bundle.png", "약초 다발"),
  generatedIcon("cc0-jetrel-gen-honey-jar", "gen-honey-jar.png", "꿀단지"),
  generatedIcon("cc0-jetrel-gen-milk-bottle", "gen-milk-bottle.png", "우유병"),
  // 공격 소비품
  generatedIcon("cc0-jetrel-gen-fire-bomb", "gen-fire-bomb.png", "화염탄"),
  generatedIcon("cc0-jetrel-gen-ice-shard", "gen-ice-shard.png", "얼음 조각"),
  generatedIcon("cc0-jetrel-gen-thunder-rod", "gen-thunder-rod.png", "번개 막대"),
  generatedIcon("cc0-jetrel-gen-poison-flask", "gen-poison-flask.png", "독 플라스크"),
  generatedIcon("cc0-jetrel-gen-smoke-ball", "gen-smoke-ball.png", "연막탄"),
  generatedIcon("cc0-jetrel-gen-throwing-knife", "gen-throwing-knife.png", "투척 단검"),
  generatedIcon("cc0-jetrel-gen-shuriken", "gen-shuriken.png", "수리검"),
  generatedIcon("cc0-jetrel-gen-holy-water", "gen-holy-water.png", "성수"),
  generatedIcon("cc0-jetrel-gen-net-trap", "gen-net-trap.png", "포획 그물"),
  generatedIcon("cc0-jetrel-gen-capture-sphere", "gen-capture-sphere.png", "포획 구슬"),
  // 무기
  generatedIcon("cc0-jetrel-gen-sword-bronze", "gen-sword-bronze.png", "청동 검"),
  generatedIcon("cc0-jetrel-gen-sword-iron", "gen-sword-iron.png", "철 검"),
  generatedIcon("cc0-jetrel-gen-sword-steel", "gen-sword-steel.png", "강철 검"),
  generatedIcon("cc0-jetrel-gen-sword-flame", "gen-sword-flame.png", "화염 검"),
  generatedIcon("cc0-jetrel-gen-sword-frost", "gen-sword-frost.png", "서릿 검"),
  generatedIcon("cc0-jetrel-gen-dagger-scout", "gen-dagger-scout.png", "정찰 단검"),
  generatedIcon("cc0-jetrel-gen-rapier-noble", "gen-rapier-noble.png", "귀족 레이피어"),
  generatedIcon("cc0-jetrel-gen-axe-battle", "gen-axe-battle.png", "전투 도끼"),
  generatedIcon("cc0-jetrel-gen-axe-great", "gen-axe-great.png", "대형 도끼"),
  generatedIcon("cc0-jetrel-gen-spear-iron", "gen-spear-iron.png", "철 창"),
  generatedIcon("cc0-jetrel-gen-halberd-guard", "gen-halberd-guard.png", "경비 할버드"),
  generatedIcon("cc0-jetrel-gen-mace-heavy", "gen-mace-heavy.png", "중형 철퇴"),
  generatedIcon("cc0-jetrel-gen-hammer-war", "gen-hammer-war.png", "전쟁 망치"),
  generatedIcon("cc0-jetrel-gen-bow-short", "gen-bow-short.png", "단궁"),
  generatedIcon("cc0-jetrel-gen-bow-long", "gen-bow-long.png", "장궁"),
  generatedIcon("cc0-jetrel-gen-crossbow-hand", "gen-crossbow-hand.png", "손 석궁"),
  generatedIcon("cc0-jetrel-gen-staff-oak", "gen-staff-oak.png", "떡갈나무 지팡이"),
  generatedIcon("cc0-jetrel-gen-staff-crystal", "gen-staff-crystal.png", "수정 지팡이"),
  generatedIcon("cc0-jetrel-gen-wand-spark", "gen-wand-spark.png", "불꽃 마법봉"),
  generatedIcon("cc0-jetrel-gen-katana-east", "gen-katana-east.png", "동방 도"),
  generatedIcon("cc0-jetrel-gen-claw-beast", "gen-claw-beast.png", "야수 발톱"),
  generatedIcon("cc0-jetrel-gen-whip-leather", "gen-whip-leather.png", "가죽 채찍"),
  generatedIcon("cc0-jetrel-gen-scythe-reaper", "gen-scythe-reaper.png", "사신 낫"),
  generatedIcon("cc0-jetrel-gen-gun-flint", "gen-gun-flint.png", "화승총"),
  generatedIcon("cc0-jetrel-gen-boomerang-wood", "gen-boomerang-wood.png", "부메랑"),
  // 방어구
  generatedIcon("cc0-jetrel-gen-shield-wood", "gen-shield-wood.png", "나무 방패"),
  generatedIcon("cc0-jetrel-gen-shield-iron", "gen-shield-iron.png", "철 방패"),
  generatedIcon("cc0-jetrel-gen-shield-tower", "gen-shield-tower.png", "타워 실드"),
  generatedIcon("cc0-jetrel-gen-shield-mirror", "gen-shield-mirror.png", "거울 방패"),
  generatedIcon("cc0-jetrel-gen-armor-leather", "gen-armor-leather.png", "가죽 갑옷"),
  generatedIcon("cc0-jetrel-gen-armor-chain", "gen-armor-chain.png", "사슬 갑옷"),
  generatedIcon("cc0-jetrel-gen-armor-plate", "gen-armor-plate.png", "판금 갑옷"),
  generatedIcon("cc0-jetrel-gen-armor-mythril", "gen-armor-mythril.png", "미스릴 갑옷"),
  generatedIcon("cc0-jetrel-gen-robe-cloth", "gen-robe-cloth.png", "천 로브"),
  generatedIcon("cc0-jetrel-gen-robe-mage", "gen-robe-mage.png", "마법사 로브"),
  generatedIcon("cc0-jetrel-gen-helm-leather", "gen-helm-leather.png", "가죽 투구"),
  generatedIcon("cc0-jetrel-gen-helm-iron", "gen-helm-iron.png", "철 투구"),
  generatedIcon("cc0-jetrel-gen-helm-horned", "gen-helm-horned.png", "뿔 투구"),
  generatedIcon("cc0-jetrel-gen-hat-traveler", "gen-hat-traveler.png", "여행자 모자"),
  generatedIcon("cc0-jetrel-gen-hat-witch", "gen-hat-witch.png", "마녀 모자"),
  generatedIcon("cc0-jetrel-gen-boots-leather", "gen-boots-leather.png", "가죽 장화"),
  generatedIcon("cc0-jetrel-gen-boots-swift", "gen-boots-swift.png", "신속 장화"),
  generatedIcon("cc0-jetrel-gen-gloves-iron", "gen-gloves-iron.png", "철 장갑"),
  generatedIcon("cc0-jetrel-gen-cloak-shadow", "gen-cloak-shadow.png", "그림자 망토"),
  generatedIcon("cc0-jetrel-gen-belt-champion", "gen-belt-champion.png", "챔피언 벨트"),
  // 장식
  generatedIcon("cc0-jetrel-gen-ring-silver", "gen-ring-silver.png", "은 반지"),
  generatedIcon("cc0-jetrel-gen-ring-power", "gen-ring-power.png", "힘의 반지"),
  generatedIcon("cc0-jetrel-gen-amulet-moon", "gen-amulet-moon.png", "달 부적"),
  generatedIcon("cc0-jetrel-gen-amulet-sun", "gen-amulet-sun.png", "태양 부적"),
  generatedIcon("cc0-jetrel-gen-brooch-rose", "gen-brooch-rose.png", "장미 브로치"),
  generatedIcon("cc0-jetrel-gen-earring-jade", "gen-earring-jade.png", "옥 귀걸이"),
  generatedIcon("cc0-jetrel-gen-charm-luck", "gen-charm-luck.png", "행운 부적"),
  generatedIcon("cc0-jetrel-gen-orb-mana", "gen-orb-mana.png", "마나 구슬"),
  generatedIcon("cc0-jetrel-gen-badge-guard", "gen-badge-guard.png", "경비 배지"),
  generatedIcon("cc0-jetrel-gen-mask-fox", "gen-mask-fox.png", "여우 가면"),
  // 재료
  generatedIcon("cc0-jetrel-gen-ore-copper", "gen-ore-copper.png", "구리 광석"),
  generatedIcon("cc0-jetrel-gen-ore-iron", "gen-ore-iron.png", "철 광석"),
  generatedIcon("cc0-jetrel-gen-ore-mythril", "gen-ore-mythril.png", "미스릴 광석"),
  generatedIcon("cc0-jetrel-gen-ingot-gold", "gen-ingot-gold.png", "금괴"),
  generatedIcon("cc0-jetrel-gen-gem-ruby", "gen-gem-ruby.png", "루비"),
  generatedIcon("cc0-jetrel-gen-gem-sapphire", "gen-gem-sapphire.png", "사파이어"),
  generatedIcon("cc0-jetrel-gen-gem-emerald", "gen-gem-emerald.png", "에메랄드"),
  generatedIcon("cc0-jetrel-gen-pelt-wolf", "gen-pelt-wolf.png", "늑대 가죽"),
  generatedIcon("cc0-jetrel-gen-fang-beast", "gen-fang-beast.png", "야수 이빨"),
  generatedIcon("cc0-jetrel-gen-scale-dragon", "gen-scale-dragon.png", "용의 비늘"),
  generatedIcon("cc0-jetrel-gen-feather-raven", "gen-feather-raven.png", "까마귀 깃털"),
  generatedIcon("cc0-jetrel-gen-thread-silk", "gen-thread-silk.png", "명주실"),
  generatedIcon("cc0-jetrel-gen-plank-oak", "gen-plank-oak.png", "떡갈 판자"),
  generatedIcon("cc0-jetrel-gen-slime-jelly", "gen-slime-jelly.png", "슬라임 젤리"),
  generatedIcon("cc0-jetrel-gen-mushroom-cave", "gen-mushroom-cave.png", "동굴 버섯"),
  // 열쇠·퀘스트
  generatedIcon("cc0-jetrel-gen-key-rusty", "gen-key-rusty.png", "녹슨 열쇠"),
  generatedIcon("cc0-jetrel-gen-key-gold", "gen-key-gold.png", "황금 열쇠"),
  generatedIcon("cc0-jetrel-gen-map-scroll", "gen-map-scroll.png", "지도 두루마리"),
  generatedIcon("cc0-jetrel-gen-letter-sealed", "gen-letter-sealed.png", "봉인된 편지"),
  generatedIcon("cc0-jetrel-gen-lamp-oil", "gen-lamp-oil.png", "기름 등불"),
  // 2세대 기능 확장 아이템
  generatedIcon("cc0-jetrel-gen2-war-draught", "gen2-war-draught.png", "전투의 묘약"),
  generatedIcon("cc0-jetrel-gen2-stone-salve", "gen2-stone-salve.png", "돌가죽 연고"),
  generatedIcon("cc0-jetrel-gen2-swift-incense", "gen2-swift-incense.png", "질풍 향"),
  generatedIcon("cc0-jetrel-gen2-life-dew", "gen2-life-dew.png", "생명 이슬"),
  generatedIcon("cc0-jetrel-gen2-nerve-tonic", "gen2-nerve-tonic.png", "신경 안정제"),
  generatedIcon("cc0-jetrel-gen2-purifying-serum", "gen2-purifying-serum.png", "정화 혈청"),
  generatedIcon("cc0-jetrel-gen2-voice-lozenge", "gen2-voice-lozenge.png", "목소리 사탕"),
  generatedIcon("cc0-jetrel-gen2-courage-tea", "gen2-courage-tea.png", "용기 차"),
  generatedIcon("cc0-jetrel-gen2-party-potion", "gen2-party-potion.png", "연대의 물약"),
  generatedIcon("cc0-jetrel-gen2-party-ether", "gen2-party-ether.png", "합창의 에테르"),
  generatedIcon("cc0-jetrel-gen2-party-elixir", "gen2-party-elixir.png", "조화의 영약"),
  generatedIcon("cc0-jetrel-gen2-party-cleanse", "gen2-party-cleanse.png", "맑은 종"),
  generatedIcon("cc0-jetrel-gen2-monster-kibble", "gen2-monster-kibble.png", "순한 사료"),
  generatedIcon("cc0-jetrel-gen2-monster-feast", "gen2-monster-feast.png", "영양 특식"),
  generatedIcon("cc0-jetrel-gen2-growth-feed", "gen2-growth-feed.png", "성장 배합식"),
  generatedIcon("cc0-jetrel-gen2-rope-toy", "gen2-rope-toy.png", "매듭 장난감"),
  generatedIcon("cc0-jetrel-gen2-rattle-ball", "gen2-rattle-ball.png", "방울 공"),
  generatedIcon("cc0-jetrel-gen2-training-frisbee", "gen2-training-frisbee.png", "훈련 원반"),
  generatedIcon("cc0-jetrel-gen2-turnip-seed", "gen2-turnip-seed.png", "순무 씨앗"),
  generatedIcon("cc0-jetrel-gen2-moonbean-seed", "gen2-moonbean-seed.png", "달콩 씨앗"),
  generatedIcon("cc0-jetrel-gen2-firepepper-seed", "gen2-firepepper-seed.png", "불고추 씨앗"),
  generatedIcon("cc0-jetrel-gen2-stargrain-seed", "gen2-stargrain-seed.png", "별보리 씨앗"),
  generatedIcon("cc0-jetrel-gen2-might-seed", "gen2-might-seed.png", "완력의 씨앗"),
  generatedIcon("cc0-jetrel-gen2-guard-seed", "gen2-guard-seed.png", "인내의 씨앗"),
  generatedIcon("cc0-jetrel-gen2-wisdom-seed", "gen2-wisdom-seed.png", "지혜의 씨앗"),
  generatedIcon("cc0-jetrel-gen2-haste-seed", "gen2-haste-seed.png", "민첩의 씨앗"),
  generatedIcon("cc0-jetrel-gen2-sun-relay", "gen2-sun-relay.png", "태양 기동석"),
  generatedIcon("cc0-jetrel-gen2-moon-relay", "gen2-moon-relay.png", "달 기동석"),
  generatedIcon("cc0-jetrel-gen2-bridge-relay", "gen2-bridge-relay.png", "교량 기동석"),
  generatedIcon("cc0-jetrel-gen2-seal-relay", "gen2-seal-relay.png", "봉인 기동석"),
  generatedIcon("cc0-jetrel-gen2-frost-vial", "gen2-frost-vial.png", "서리 유리병"),
  generatedIcon("cc0-jetrel-gen2-quake-stone", "gen2-quake-stone.png", "진동석"),
  generatedIcon("cc0-jetrel-gen2-gale-fan", "gen2-gale-fan.png", "돌풍 부채"),
  generatedIcon("cc0-jetrel-gen2-shadow-dust", "gen2-shadow-dust.png", "그림자 가루"),
  generatedIcon("cc0-jetrel-gen2-venom-ampoule", "gen2-venom-ampoule.png", "심독 앰풀"),
  generatedIcon("cc0-jetrel-gen2-paralysis-coil", "gen2-paralysis-coil.png", "마비 코일"),
  generatedIcon("cc0-jetrel-gen2-twin-dose-kit", "gen2-twin-dose-kit.png", "이중 약갑"),
  generatedIcon("cc0-jetrel-gen2-triple-aegis", "gen2-triple-aegis.png", "삼중 수호패"),
  generatedIcon("cc0-jetrel-gen2-five-spark-core", "gen2-five-spark-core.png", "오연 발화핵"),
  generatedIcon("cc0-jetrel-gen2-moonsilver-wire", "gen2-moonsilver-wire.png", "월은 철사"),
  generatedIcon("cc0-jetrel-gen2-frostglass-shard", "gen2-frostglass-shard.png", "서리유리 파편"),
  generatedIcon("cc0-jetrel-gen2-storm-sailcloth", "gen2-storm-sailcloth.png", "폭풍 돛천"),
  generatedIcon("cc0-jetrel-gen2-shadow-resin", "gen2-shadow-resin.png", "그림자 수지"),
  generatedIcon("cc0-jetrel-gen2-golem-core", "gen2-golem-core.png", "골렘 동력핵"),
  generatedIcon("cc0-jetrel-gen2-alchemist-seal", "gen2-alchemist-seal.png", "연금술사 인장"),
  generatedIcon("cc0-jetrel-gen2-sluice-key", "gen2-sluice-key.png", "수문 열쇠"),
  generatedIcon("cc0-jetrel-gen2-observatory-gear", "gen2-observatory-gear.png", "천문대 톱니"),
  generatedIcon("cc0-jetrel-gen2-dragonbone-clasp", "gen2-dragonbone-clasp.png", "용골 죔쇠"),
  ...sharedIconAssets.map((asset): Cc0IconAsset => ({
    ...asset,
    sourceName: GENERATED_SOURCE_NAME,
    sourceUrl: GENERATED_SOURCE_URL,
    license: "generated",
  })),
] as const satisfies readonly Cc0IconAsset[];

export function resolveCc0IconAssetUrl(resourceId: string): string | null {
  const asset = CC0_ICON_ASSETS.find((entry) => entry.id === resourceId);
  return asset ? `/${asset.path}` : null;
}
