// 아래를 향한 정지 프레임(direction down, pattern 1)을 보고 적은 외형 문장.
// 라벨·태그에 없는 머리·옷·장식을 적는다. 없는 것은 적지 않는다(「안경 없음」처럼
// 부정어가 검색에 걸리면 안 된다). 2026-09-22 시트 육안.

export const CHARSET_APPEARANCE: Readonly<Record<string, string>> = {
  "tex_easyrpg_charset_monster1#0": "작은 초록 젤리. 노란 눈이 하나.",
  "tex_easyrpg_charset_monster1#1": "빨간 피부, 검은 뿔 둘, 초록 눈. 작은 악마.",
  "tex_easyrpg_charset_monster1#2": "대머리, 노란 어깨 갑옷, 보라 허리띠, 맨다리.",
  "tex_easyrpg_charset_monster1#3": "흰 시트 유령. 검은 눈, 빨간 입.",
  "tex_easyrpg_charset_monster1#4": "흰 해골. 검은 눈구멍, 뼈로 된 몸.",
  "tex_easyrpg_charset_monster1#5": "초록 피부, 회색 머리, 파란 재킷, 노란 셔츠, 회색 바지.",
  "tex_easyrpg_charset_monster1#6": "보라 두건, 해골 얼굴, 파란 눈, 보라 로브.",
  "tex_easyrpg_charset_monster1#7": "갈색 뿔, 흰 수염, 빨간 눈, 회색 갑옷, 초록 바지.",

  "tex_easyrpg_charset_monster2#0": "초록 머리, 흰 날개, 맨가슴, 빨간 반바지.",
  "tex_easyrpg_charset_monster2#1": "파란 용. 흰 뿔, 날개, 갈색 배.",
  "tex_easyrpg_charset_monster2#2": "은발, 창백한 얼굴, 검은 코트에 금장, 보라 바지.",
  "tex_easyrpg_charset_monster2#3": "검은 갑옷, 빨간 뿔과 빨간 어깨, 노란 눈.",
  "tex_easyrpg_charset_monster2#4": "갈색 바위 몸. 빨간 눈만 있고 팔다리는 짧다.",
  "tex_easyrpg_charset_monster2#5": "초록 비늘, 흰 뿔, 날개, 보라 허리.",
  "tex_easyrpg_charset_monster2#6": "빨간 갈기, 흰 뿔, 검은 갑옷, 구부러진 검.",
  "tex_easyrpg_charset_monster2#7": "파란 피부, 빨간 뿔, 금장 갑옷, 큰 검.",

  "tex_easyrpg_charset_monster3#0": "붉은 긴 머리, 흰 날개, 보라 웃옷, 검은 치마.",
  "tex_easyrpg_charset_monster3#1": "긴 해골 턱, 회색 뼈 머리와 등, 둥글게 말린 황토색 뱀 모양 몸.",
  "tex_easyrpg_charset_monster3#2": "검은 얼굴을 가린 짙은 회색 두건, 금색 테두리, 찢어진 로브 밑단.",
  "tex_easyrpg_charset_monster3#3": "뾰족한 보라 투구와 보라 갑옷, 갈색 몸, 금색 어깨 장식과 초록 등판.",
  "tex_easyrpg_charset_monster3#4": "갈색 원뿔과 파란 띠, 분홍 얼굴. 걷기 패턴마다 작은 원뿔에서 얼굴이 있는 큰 몸으로 변한다.",
  "tex_easyrpg_charset_monster3#5": "빨간 비늘, 흰 뿔, 날개, 갈색 배의 용.",
  "tex_easyrpg_charset_monster3#6": "정지 패턴은 붉은 원형 마법진. 다른 패턴은 붉은 불꽃과 금장식 마법사로 변한다. 일반 걷기 그림이 아닌 변신 연출이다.",
  "tex_easyrpg_charset_monster3#7": "붉은 뿔이 있는 보라 투구, 보라 얼굴, 금색 어깨 갑옷, 검은 옷과 흰 장갑.",

  "tex_easyrpg_charset_monster4#0": "초록 잎이 무성한 갈색 나무 몸, 가지 팔과 뿌리 발, 밝은 눈과 입.",
  "tex_easyrpg_charset_monster4#1": "흰 점이 있는 커다란 빨간 버섯 갓, 연녹색 몸과 짧은 갈색 발.",
  "tex_easyrpg_charset_monster4#2": "초록 피부, 노란 부리, 머리 위 흰 접시, 갈색 등딱지.",
  "tex_easyrpg_charset_monster4#3": "주황 여우 귀와 여러 갈래 꼬리, 밝은 가슴털, 짧은 팔다리.",
  "tex_easyrpg_charset_monster4#4": "초록 잎을 얹은 갈색 삿갓, 갈색 너구리 몸, 밝고 둥근 배와 굵은 꼬리.",
  "tex_easyrpg_charset_monster4#5": "이끼가 붙은 회색 돌 몸, 네모난 머리와 큰 팔, 청록 눈과 가슴 무늬.",
  "tex_easyrpg_charset_monster4#6": "흰 얼음 머리, 하늘색 몸과 결정 모양 날개, 작게 늘어진 발.",
  "tex_easyrpg_charset_monster4#7": "머리 위 초록 잎, 갈색 뿌리 몸, 벌어진 입과 짧은 팔다리.",
  "tex_easyrpg_charset_monster5#0": "눈과 이빨, 긴 붉은 혀가 달린 갈색 나무 상자.",
  "tex_easyrpg_charset_monster5#1": "보라 장식의 회색 판금 갑옷, 검은 얼굴과 노란 눈, 옆에 긴 검.",
  "tex_easyrpg_charset_monster5#2": "외눈이 달린 노란 초롱, 빨간 띠, 파란 불꽃과 갈색 다리.",
  "tex_easyrpg_charset_monster5#3": "갈색 십자 막대에 줄로 매달린 인형, 흰 얼굴과 자주색 옷.",
  "tex_easyrpg_charset_monster5#4": "눈과 이빨이 달린 보라 책 표지, 흰 페이지와 긴 빨간 혀.",
  "tex_easyrpg_charset_monster5#5": "갈색 삿갓, 짚 얼굴, 파란 옷, 나무 기둥 다리와 옆에 긴 낫.",
  "tex_easyrpg_charset_monster5#6": "빨간 꼭지의 검은 병정 모자, 파란 제복과 흰 교차 띠, 긴 총과 등 태엽.",
  "tex_easyrpg_charset_monster5#7": "머리 위 주황 불꽃, 얼굴과 팔이 달린 크림색 촛농 몸, 짧은 갈색 발.",
  "tex_easyrpg_charset_monster6#0": "큰 흰 털 몸, 푸른 얼굴과 짧은 발, 길고 굵은 팔.",
  "tex_easyrpg_charset_monster6#1": "청록 몸과 꼬리, 분홍 지느러미, 파란 머리와 금색 삼지창.",
  "tex_easyrpg_charset_monster6#2": "외눈을 가진 큰 갈색 몸, 넓은 어깨와 굵은 팔, 짧은 다리.",
  "tex_easyrpg_charset_monster6#3": "갈색 몸, 밝은 무늬가 있는 큰 나방 날개, 붉은 눈과 더듬이.",
  "tex_easyrpg_charset_monster6#4": "초록 도마뱀 몸과 꼬리, 빨간 볏, 밝은 배와 네 발.",
  "tex_easyrpg_charset_monster6#5": "짙은 파란 머리, 파란 팔과 밝은 몸, 다리 대신 길게 말린 연기 꼬리.",
  "tex_easyrpg_charset_monster6#6": "황토색 사자 몸, 머리 옆 뿔, 등 위 다른 머리와 초록 뱀 꼬리.",
  "tex_easyrpg_charset_monster6#7": "흰 얼굴, 금색 머리 장식, 검보라 몸과 크게 접힌 검은 날개.",

  "tex_easyrpg_charset_people1#0": "짧은 갈색 머리, 검은 재킷에 흰 셔츠, 파란 바지, 갈색 신발.",
  "tex_easyrpg_charset_people1#1": "노란 단발에 분홍 리본, 연보라 원피스, 갈색 신발.",
  "tex_easyrpg_charset_people1#2": "파란 뾰족 머리, 초록 웃옷, 갈색 바지.",
  "tex_easyrpg_charset_people1#3": "긴 금발, 검은 재킷에 분홍 셔츠와 분홍 치마, 검은 바지.",
  "tex_easyrpg_charset_people1#4": "어두운 피부, 짧은 갈색 머리, 흰 셔츠에 갈색 조끼, 주황 바지.",
  "tex_easyrpg_charset_people1#5": "어두운 피부, 갈색 파마머리, 초록 눈, 흰 블라우스에 회색 조끼, 갈색 치마.",
  "tex_easyrpg_charset_people1#6": "대머리에 흰 수염, 초록 로브, 갈색 허리띠.",
  "tex_easyrpg_charset_people1#7": "주황 두건에 회색 앞머리, 주황 망토, 초록 치마.",

  "tex_easyrpg_charset_people2#0": "검은 중절모, 금장 검은 코트, 흰 셔츠, 갈색 머리.",
  "tex_easyrpg_charset_people2#1": "검은 베일 아래 흰 머리, 검은 수녀복에 흰 깃.",
  "tex_easyrpg_charset_people2#2": "대머리, 주황 가사, 흰 허리띠.",
  "tex_easyrpg_charset_people2#3": "보라 올림머리, 빨간 민소매, 초록 반바지, 검은 신발.",
  "tex_easyrpg_charset_people2#4": "검은 단발, 보라 조끼에 금장, 분홍 바지, 흰 신발.",
  "tex_easyrpg_charset_people2#5": "흰 토끼 귀, 금발, 검은 민소매, 갈색 반바지, 분홍 신발.",
  "tex_easyrpg_charset_people2#6": "붉은 긴 머리, 금색 왕관, 흰 날개, 하늘색 드레스에 노란 리본.",
  "tex_easyrpg_charset_people2#7": "짧은 초록 머리, 청록 날개, 초록 드레스, 갈색 신발.",

  "tex_easyrpg_charset_people3#0": "금관, 회색 머리와 수염, 빨간 망토, 금장 갑옷, 흰 털 깃.",
  "tex_easyrpg_charset_people3#1": "금관, 푸른 머리, 파란 로브에 금장, 노란 소매.",
  "tex_easyrpg_charset_people3#2": "단정한 주황 머리, 파란 옷에 노란 깃, 흰 장갑, 검은 바지.",
  "tex_easyrpg_charset_people3#3": "긴 금발에 작은 금관, 분홍 드레스에 흰 앞치마.",
  "tex_easyrpg_charset_people3#4": "은발, 갈색 코트, 흰 셔츠, 흰 바지, 갈색 신발.",
  "tex_easyrpg_charset_people3#5": "보라 머리에 흰 머리쓰개, 회색 메이드복, 흰 앞치마.",
  "tex_easyrpg_charset_people3#6": "어두운 보라 머리, 노란 스카프, 회색 코트, 갈색 바지.",
  "tex_easyrpg_charset_people3#7": "파란 투구에 흰 뿔, 파란 갑옷에 흰 십자, 검은 신발.",

  "tex_easyrpg_charset_people4#0": "회색 빵모자, 보라 옆머리, 빨간 조끼, 흰 셔츠, 회색 바지.",
  "tex_easyrpg_charset_people4#1": "삐죽한 갈색 머리, 빨간 테 안경, 초록 셔츠, 갈색 반바지.",
  "tex_easyrpg_charset_people4#2": "빨강과 파랑 체크 모자, 보라 머리, 빨간 코트, 주황 바지.",
  "tex_easyrpg_charset_people4#3": "주황 모자에 파란 리본, 주황 민소매, 파란 치마, 흰 장갑.",
  "tex_easyrpg_charset_people4#4": "대머리, 초록 셔츠, 갈색 바지.",
  "tex_easyrpg_charset_people4#5": "검은 머리에 노란 머리띠, 노란 드레스, 흰 소매.",
  "tex_easyrpg_charset_people4#6": "주황 터번, 흰 수염, 주황 로브.",
  "tex_easyrpg_charset_people4#7": "보라 머리수건, 빨간 로브, 노란 옷깃.",

  "tex_easyrpg_charset_people5#0": "파란 두건, 빨간 앞머리, 파란 옷에 노란 단추, 흰 바지.",
  "tex_easyrpg_charset_people5#1": "주황 양갈래, 보라 조끼, 초록 치마, 흰 양말.",
  "tex_easyrpg_charset_people5#2": "검은 뾰족 머리에 빨간 머리띠, 검붉은 옷, 갈색 바지.",
  "tex_easyrpg_charset_people5#3": "검은 머리에 분홍 꽃, 파란 기모노, 빨간 허리띠.",
  "tex_easyrpg_charset_people5#4": "작은 키, 금색 뿔 투구, 금발 수염, 파란 옷.",
  "tex_easyrpg_charset_people5#5": "붉은 단발, 보라 옷, 흰 앞치마, 파란 치마.",
  "tex_easyrpg_charset_people5#6": "대머리에 흰 수염, 보라 조끼, 베이지 바지, 갈색 가방.",
  "tex_easyrpg_charset_people5#7": "회색 머리, 둥근 안경, 초록 도포, 검은 바지.",

  "tex_easyrpg_charset_actor1#0": "갈색 머리, 파란 옷에 흰 깃, 빨간 장갑, 빨간 부츠.",
  "tex_easyrpg_charset_actor1#1": "긴 파란 머리, 빨간 로브, 흰 깃, 검은 부츠.",
  "tex_easyrpg_charset_actor1#2": "빨간 투구에 흰 뿔, 빨간 갑옷, 흰 허리.",
  "tex_easyrpg_charset_actor1#3": "빨간 투구에 흰 뿔, 갈색 머리, 빨간 갑옷에 노란 장식, 흰 장갑.",
  "tex_easyrpg_charset_actor1#4": "넓은 검은 모자, 파란 망토, 갈색 머리.",
  "tex_easyrpg_charset_actor1#5": "검은 마녀 모자, 보라 숄, 검은 드레스, 주황 부츠.",
  "tex_easyrpg_charset_actor1#6": "검은 단발, 파란 로브, 흰 소매, 회색 바지.",
  "tex_easyrpg_charset_actor1#7": "파란 챙모자, 검은 긴 머리, 파란 로브에 노란 단추.",

  "tex_easyrpg_charset_actor2#0": "검은 머리, 회색 웃옷, 빨간 허리띠, 맨발.",
  "tex_easyrpg_charset_actor2#1": "주황 단발, 하늘색 재킷, 빨간 장갑.",
  "tex_easyrpg_charset_actor2#2": "갈색 머리에 노란 머리띠, 초록 웃옷, 회색 바지.",
  "tex_easyrpg_charset_actor2#3": "초록 후드, 초록 망토, 하늘색 바지, 갈색 부츠.",
  "tex_easyrpg_charset_actor2#4": "갈색 머리에 빨간 머리띠, 노란 갑옷, 보라 바지.",
  "tex_easyrpg_charset_actor2#5": "보라 머리, 검은 민소매, 빨간 바지.",
  "tex_easyrpg_charset_actor2#6": "초록 머리, 뾰족한 귀, 흰 깃털, 초록 옷, 흰 망토.",
  "tex_easyrpg_charset_actor2#7": "초록 모자, 금발, 뾰족한 귀, 빨간 깃털, 초록 옷.",

  "tex_easyrpg_charset_actor3#0": "빨간 투구, 빨간 갑옷에 금장.",
  "tex_easyrpg_charset_actor3#1": "검은 긴 머리, 회색 옷에 노란 깃, 흰 셔츠.",
  "tex_easyrpg_charset_actor3#2": "회색 복면 후드. 눈만 보이고 회색 옷에 흰 띠.",
  "tex_easyrpg_charset_actor3#3": "검은 머리를 묶고 흰 머리띠, 주황 옷, 검은 바지.",
  "tex_easyrpg_charset_actor3#4": "빨간 모자에 초록 리본, 금발, 초록 코트.",
  "tex_easyrpg_charset_actor3#5": "파란 머리, 맨가슴에 노란 허리띠, 분홍 바지.",
  "tex_easyrpg_charset_actor3#6": "노란 챙모자, 갈색 머리, 검은 옷에 빨간 깃, 노란 소매.",
  "tex_easyrpg_charset_actor3#7": "금색 모자, 갈색 머리, 주황 옷에 금장.",

  "tex_easyrpg_charset_actor4#0": "파란 머리, 흰 셔츠에 검은 조끼, 초록 바지.",
  "tex_easyrpg_charset_actor4#1": "금발, 하늘색 재킷, 검은 바지.",
  "tex_easyrpg_charset_actor4#2": "금발에 빨간 머리띠, 회색 조끼, 초록 바지.",
  "tex_easyrpg_charset_actor4#3": "파란 단발, 검은 로브, 흰 깃, 노란 소매.",
  "tex_easyrpg_charset_actor4#4": "분홍 긴 머리, 노란 조끼, 갈색 바지.",
  "tex_easyrpg_charset_actor4#5": "금발, 초록 갑옷, 빨간 소매, 초록 부츠.",
  "tex_easyrpg_charset_actor4#6": "보라 긴 머리, 파란 로브, 노란 허리띠.",
  "tex_easyrpg_charset_actor4#7": "빨간 고깔모자, 청록 머리, 흰 블라우스, 노란 바지, 빨간 부츠.",

  "tex_easyrpg_charset_animal#0": "주황 고양이. 흰 가슴, 파란 눈.",
  "tex_easyrpg_charset_animal#1": "검은 고양이. 갈색 얼굴, 보라 귀.",
  "tex_easyrpg_charset_animal#2": "흰 닭. 빨간 벼슬, 노란 부리.",
  "tex_easyrpg_charset_animal#3": "흰 양. 검은 얼굴, 회색 털.",
  "tex_easyrpg_charset_animal#4": "흰 소. 분홍 코, 작은 뿔.",
  "tex_easyrpg_charset_animal#5": "갈색 말. 흰 발, 갈색 갈기.",
  "tex_easyrpg_charset_animal#6": "주황 호랑이. 노란 배.",
  "tex_easyrpg_charset_animal#7": "갈색 갈기에 노란 얼굴의 사자.",
  "tex_farming_charset_chicken#0": "흰 닭 몸, 빨간 벼슬, 노란 부리와 발.",
  "tex_farming_charset_cow#0": "갈색 얼룩의 흰 젖소 몸, 분홍 주둥이, 작은 뿔과 짧은 꼬리.",

  "tex_easyrpg_charset_object1#0": "갈색 나무문. 위아래 두 패널, 회색 경첩.",
  "tex_easyrpg_charset_object1#1": "세로 결의 갈색 판자문, 회색 경첩.",
  "tex_easyrpg_charset_object1#2": "위아래가 나뉜 나무 쌍문, 회색 철테.",
  "tex_easyrpg_charset_object1#3": "회색 철제 문. 사각 패널이 위아래로 둘, 회색 경첩.",
  "tex_easyrpg_charset_object1#4": "회색 철제 문. 사각 패널이 위아래로 둘, 회색 경첩.",
  "tex_easyrpg_charset_object1#5": "회색 철창 문. 세로 창살.",
  "tex_easyrpg_charset_object1#6": "빨간 보물상자, 금색 띠, 은색 자물쇠.",
  "tex_easyrpg_charset_object1#7": "네모난 갈색 나무 상자, 은색 자물쇠. 다른 패턴에서 위 뚜껑이 열린다.",

  "tex_easyrpg_charset_object2#0": "회색 대에 검은 막대, 빨간 손잡이.",
  "tex_easyrpg_charset_object2#1": "초록 밧줄 뭉치, 빨간 끝.",
  "tex_easyrpg_charset_object2#2": "회색 사각 테두리 안에 둥근 원판이 있는 납작한 바닥 판.",
  "tex_easyrpg_charset_object2#3": "회색 테두리에 흰 원판이 있는 사각 판.",
  "tex_easyrpg_charset_object2#4": "흰 사각 테두리에 회색 나선이 있는 바닥 판.",
  "tex_easyrpg_charset_object2#5": "둥근 갈색 바위.",
  "tex_easyrpg_charset_object2#6": "보라 빛 둥근 보석.",
  "tex_easyrpg_charset_object2#7": "갈색 나무 서랍장, 빨간 다리.",

  "tex_easyrpg_charset_vehicles#0": "작은 갈색 뗏목, 파란 물결, 초록 싹.",
  "tex_easyrpg_charset_vehicles#1": "갈색 나무배, 노란 기, 흰 돛, 파란 물.",
  "tex_easyrpg_charset_vehicles#2": "흰 철갑 함선, 파란 줄, 나무 갑판.",
  "tex_easyrpg_charset_vehicles#3": "빨간 줄무늬 풍선, 갈색 바구니.",
  "tex_easyrpg_charset_vehicles#4": "회색 비행선, 초록 지느러미, 보라 창문.",
  "tex_easyrpg_charset_vehicles#5": "초록 차체, 보라 무한궤도.",
  "tex_easyrpg_charset_vehicles#6": "갈색 비행정, 청록 조종석, 노란 등.",
  "tex_easyrpg_charset_vehicles#7": "갈색 선체, 초록 등, 파란 창.",

  "tex_scarloxy_charset_people1#0": "초록 모자에 주황 챙, 흰 재킷과 붉은 멜빵, 초록 바지, 주황 배낭.",
  "tex_scarloxy_charset_people1#1": "금발, 빨간 민소매, 흰 반바지.",
  "tex_scarloxy_charset_people1#2": "초록 벙거지, 보라 머리, 흰 민소매, 보라 바지.",
  "tex_scarloxy_charset_people1#3": "보라 긴 머리, 보라 웃옷에 밝은 별 무늬, 남색 바지.",
  "tex_scarloxy_charset_people1#4": "갈색 양갈래에 빨간 리본, 노란 웃옷, 파란 배낭, 빨간 신발.",
  "tex_scarloxy_charset_people1#5": "보라 머리, 민트 민소매, 남색 반바지, 흰 양말과 초록 신발.",
  "tex_scarloxy_charset_people1#6": "밀짚모자, 흰 민소매, 초록 반바지, 빨간 신발.",
  "tex_scarloxy_charset_people1#7": "긴 청록 머리, 분홍 귀, 파란 드레스, 분홍 치마.",

  "tex_scarloxy_charset_people2#0": "빨간 불꽃 머리, 검은 마스크, 빨간 코트에 노란 띠.",
  "tex_scarloxy_charset_people2#1": "초록 뾰족 머리, 초록 후드, 흰 셔츠, 초록 바지.",
};
