// Generated by scripts/sync-easyrpg-rtp-assets.mjs. Do not edit by hand.
// Source: https://github.com/EasyRPG/RTP/tree/993d88cbc78c658d348bbfa74a3b424d393d27e5

export const EASYRPG_RTP_COMMIT = "993d88cbc78c658d348bbfa74a3b424d393d27e5";
export const EASYRPG_RTP_SOURCE_URL = "https://github.com/EasyRPG/RTP";
export type EasyRpgRtpCategory =
  | "backdrop"
  | "battle"
  | "battleWeapon"
  | "charset"
  | "chipset"
  | "faceset"
  | "gameOver"
  | "monster"
  | "music"
  | "picture"
  | "sound"
  | "system"
  | "system2"
  | "title";
export type CharsetDirection = "down" | "left" | "right" | "up";

export type EasyRpgRtpAsset = {
  readonly category: EasyRpgRtpCategory;
  readonly id: string;
  readonly name: string;
  readonly sourcePath: string;
  readonly path: string;
  readonly fileName: string;
  readonly textureKey?: string;
  readonly group?: string;
};

export type EasyRpgCharsetAsset = EasyRpgRtpAsset & {
  readonly category: "charset";
  readonly textureKey: string;
  readonly group: string;
};
export const EASYRPG_RTP_ASSETS = [
  { category: "battle", id: "easyrpg-battle-arrow", name: "EasyRPG RTP Arrow Battle", sourcePath: "Battle/Arrow.png", path: "assets/easyrpg/battle/Arrow.png", fileName: "Arrow.png" },
  { category: "battle", id: "easyrpg-battle-blow", name: "EasyRPG RTP Blow Battle", sourcePath: "Battle/Blow.png", path: "assets/easyrpg/battle/Blow.png", fileName: "Blow.png" },
  { category: "battle", id: "easyrpg-battle-sword1", name: "EasyRPG RTP Sword1 Battle", sourcePath: "Battle/Sword1.png", path: "assets/easyrpg/battle/Sword1.png", fileName: "Sword1.png" },
  { category: "battleWeapon", id: "easyrpg-battle-weapon-weapon", name: "EasyRPG RTP Weapon BattleWeapon", sourcePath: "BattleWeapon/Weapon.png", path: "assets/easyrpg/battle-weapon/Weapon.png", fileName: "Weapon.png" },
  { category: "charset", id: "easyrpg-charset-actor1", name: "EasyRPG RTP Actor1 CharSet", sourcePath: "CharSet/Actor1.png", path: "assets/easyrpg/charset/Actor1.png", fileName: "Actor1.png", textureKey: "tex_easyrpg_charset_actor1", group: "Actor" },
  { category: "charset", id: "easyrpg-charset-actor2", name: "EasyRPG RTP Actor2 CharSet", sourcePath: "CharSet/Actor2.png", path: "assets/easyrpg/charset/Actor2.png", fileName: "Actor2.png", textureKey: "tex_easyrpg_charset_actor2", group: "Actor" },
  { category: "charset", id: "easyrpg-charset-actor3", name: "EasyRPG RTP Actor3 CharSet", sourcePath: "CharSet/Actor3.png", path: "assets/easyrpg/charset/Actor3.png", fileName: "Actor3.png", textureKey: "tex_easyrpg_charset_actor3", group: "Actor" },
  { category: "charset", id: "easyrpg-charset-actor4", name: "EasyRPG RTP Actor4 CharSet", sourcePath: "CharSet/Actor4.png", path: "assets/easyrpg/charset/Actor4.png", fileName: "Actor4.png", textureKey: "tex_easyrpg_charset_actor4", group: "Actor" },
  { category: "charset", id: "easyrpg-charset-animal", name: "EasyRPG RTP Animal CharSet", sourcePath: "CharSet/Animal.png", path: "assets/easyrpg/charset/Animal.png", fileName: "Animal.png", textureKey: "tex_easyrpg_charset_animal", group: "Animal" },
  { category: "charset", id: "easyrpg-charset-monster1", name: "EasyRPG RTP Monster1 CharSet", sourcePath: "CharSet/Monster1.png", path: "assets/easyrpg/charset/Monster1.png", fileName: "Monster1.png", textureKey: "tex_easyrpg_charset_monster1", group: "Monster" },
  { category: "charset", id: "easyrpg-charset-monster2", name: "EasyRPG RTP Monster2 CharSet", sourcePath: "CharSet/Monster2.png", path: "assets/easyrpg/charset/Monster2.png", fileName: "Monster2.png", textureKey: "tex_easyrpg_charset_monster2", group: "Monster" },
  { category: "charset", id: "easyrpg-charset-monster3", name: "EasyRPG RTP Monster3 CharSet", sourcePath: "CharSet/Monster3.png", path: "assets/easyrpg/charset/Monster3.png", fileName: "Monster3.png", textureKey: "tex_easyrpg_charset_monster3", group: "Monster" },
  { category: "charset", id: "easyrpg-charset-object1", name: "EasyRPG RTP Object1 CharSet", sourcePath: "CharSet/Object1.png", path: "assets/easyrpg/charset/Object1.png", fileName: "Object1.png", textureKey: "tex_easyrpg_charset_object1", group: "Object" },
  { category: "charset", id: "easyrpg-charset-object2", name: "EasyRPG RTP Object2 CharSet", sourcePath: "CharSet/Object2.png", path: "assets/easyrpg/charset/Object2.png", fileName: "Object2.png", textureKey: "tex_easyrpg_charset_object2", group: "Object" },
  { category: "charset", id: "easyrpg-charset-people1", name: "EasyRPG RTP People1 CharSet", sourcePath: "CharSet/People1.png", path: "assets/easyrpg/charset/People1.png", fileName: "People1.png", textureKey: "tex_easyrpg_charset_people1", group: "People" },
  { category: "charset", id: "easyrpg-charset-people2", name: "EasyRPG RTP People2 CharSet", sourcePath: "CharSet/People2.png", path: "assets/easyrpg/charset/People2.png", fileName: "People2.png", textureKey: "tex_easyrpg_charset_people2", group: "People" },
  { category: "charset", id: "easyrpg-charset-people3", name: "EasyRPG RTP People3 CharSet", sourcePath: "CharSet/People3.png", path: "assets/easyrpg/charset/People3.png", fileName: "People3.png", textureKey: "tex_easyrpg_charset_people3", group: "People" },
  { category: "charset", id: "easyrpg-charset-people4", name: "EasyRPG RTP People4 CharSet", sourcePath: "CharSet/People4.png", path: "assets/easyrpg/charset/People4.png", fileName: "People4.png", textureKey: "tex_easyrpg_charset_people4", group: "People" },
  { category: "charset", id: "easyrpg-charset-people5", name: "EasyRPG RTP People5 CharSet", sourcePath: "CharSet/People5.png", path: "assets/easyrpg/charset/People5.png", fileName: "People5.png", textureKey: "tex_easyrpg_charset_people5", group: "People" },
  { category: "charset", id: "easyrpg-charset-template", name: "EasyRPG RTP Template CharSet", sourcePath: "CharSet/Template.png", path: "assets/easyrpg/charset/Template.png", fileName: "Template.png", textureKey: "tex_easyrpg_charset_template", group: "Template" },
  { category: "charset", id: "easyrpg-charset-vehicles", name: "EasyRPG RTP Vehicles CharSet", sourcePath: "CharSet/Vehicles.png", path: "assets/easyrpg/charset/Vehicles.png", fileName: "Vehicles.png", textureKey: "tex_easyrpg_charset_vehicles", group: "Vehicles" },
  { category: "chipset", id: "easyrpg-chipset-dungeon", name: "EasyRPG RTP Dungeon ChipSet", sourcePath: "ChipSet/Dungeon.png", path: "assets/easyrpg/chipset/Dungeon.png", fileName: "Dungeon.png" },
  { category: "chipset", id: "easyrpg-chipset-exterior", name: "EasyRPG RTP Exterior ChipSet", sourcePath: "ChipSet/Exterior.png", path: "assets/easyrpg/chipset/Exterior.png", fileName: "Exterior.png" },
  { category: "chipset", id: "easyrpg-chipset-interior", name: "EasyRPG RTP Interior ChipSet", sourcePath: "ChipSet/Interior.png", path: "assets/easyrpg/chipset/Interior.png", fileName: "Interior.png" },
  { category: "chipset", id: "easyrpg-chipset-retro-dungeon", name: "EasyRPG RTP retro_Dungeon ChipSet", sourcePath: "ChipSet/retro_Dungeon.png", path: "assets/easyrpg/chipset/retro_Dungeon.png", fileName: "retro_Dungeon.png" },
  { category: "chipset", id: "easyrpg-chipset-retro-exterior", name: "EasyRPG RTP retro_Exterior ChipSet", sourcePath: "ChipSet/retro_Exterior.png", path: "assets/easyrpg/chipset/retro_Exterior.png", fileName: "retro_Exterior.png" },
  { category: "chipset", id: "easyrpg-chipset-retro-world", name: "EasyRPG RTP retro_World ChipSet", sourcePath: "ChipSet/retro_World.png", path: "assets/easyrpg/chipset/retro_World.png", fileName: "retro_World.png" },
  { category: "chipset", id: "easyrpg-chipset-ship", name: "EasyRPG RTP Ship ChipSet", sourcePath: "ChipSet/Ship.png", path: "assets/easyrpg/chipset/Ship.png", fileName: "Ship.png" },
  { category: "chipset", id: "easyrpg-chipset-world", name: "EasyRPG RTP World ChipSet", sourcePath: "ChipSet/World.png", path: "assets/easyrpg/chipset/World.png", fileName: "World.png" },
  { category: "faceset", id: "easyrpg-faceset-actor1", name: "EasyRPG RTP Actor1 FaceSet", sourcePath: "FaceSet/Actor1.png", path: "assets/easyrpg/faceset/Actor1.png", fileName: "Actor1.png" },
  { category: "faceset", id: "easyrpg-faceset-actor2", name: "EasyRPG RTP Actor2 FaceSet", sourcePath: "FaceSet/Actor2.png", path: "assets/easyrpg/faceset/Actor2.png", fileName: "Actor2.png" },
  { category: "faceset", id: "easyrpg-faceset-monster", name: "EasyRPG RTP Monster FaceSet", sourcePath: "FaceSet/Monster.png", path: "assets/easyrpg/faceset/Monster.png", fileName: "Monster.png" },
  { category: "faceset", id: "easyrpg-faceset-people1", name: "EasyRPG RTP People1 FaceSet", sourcePath: "FaceSet/People1.png", path: "assets/easyrpg/faceset/People1.png", fileName: "People1.png" },
  { category: "faceset", id: "easyrpg-faceset-people2", name: "EasyRPG RTP People2 FaceSet", sourcePath: "FaceSet/People2.png", path: "assets/easyrpg/faceset/People2.png", fileName: "People2.png" },
  { category: "gameOver", id: "easyrpg-game-over-game-over", name: "EasyRPG RTP Game Over GameOver", sourcePath: "GameOver/Game Over.png", path: "assets/easyrpg/game-over/Game Over.png", fileName: "Game Over.png" },
  { category: "monster", id: "easyrpg-monster-hornet", name: "EasyRPG RTP Hornet Monster", sourcePath: "Monster/Hornet.png", path: "assets/easyrpg/monster/Hornet.png", fileName: "Hornet.png" },
  { category: "music", id: "easyrpg-music-battle-1", name: "EasyRPG RTP Battle 1 Music", sourcePath: "Music/Battle 1.mid", path: "assets/easyrpg/music/Battle 1.mid", fileName: "Battle 1.mid" },
  { category: "music", id: "easyrpg-music-boss-3", name: "EasyRPG RTP Boss 3 Music", sourcePath: "Music/Boss 3.mid", path: "assets/easyrpg/music/Boss 3.mid", fileName: "Boss 3.mid" },
  { category: "music", id: "easyrpg-music-castle-1", name: "EasyRPG RTP Castle 1 Music", sourcePath: "Music/Castle 1.mid", path: "assets/easyrpg/music/Castle 1.mid", fileName: "Castle 1.mid" },
  { category: "music", id: "easyrpg-music-church", name: "EasyRPG RTP Church Music", sourcePath: "Music/Church.mid", path: "assets/easyrpg/music/Church.mid", fileName: "Church.mid" },
  { category: "music", id: "easyrpg-music-dungeon-1", name: "EasyRPG RTP Dungeon 1 Music", sourcePath: "Music/Dungeon 1.mid", path: "assets/easyrpg/music/Dungeon 1.mid", fileName: "Dungeon 1.mid" },
  { category: "music", id: "easyrpg-music-ending-2", name: "EasyRPG RTP Ending 2 Music", sourcePath: "Music/Ending 2.mid", path: "assets/easyrpg/music/Ending 2.mid", fileName: "Ending 2.mid" },
  { category: "music", id: "easyrpg-music-field-1", name: "EasyRPG RTP Field 1 Music", sourcePath: "Music/Field 1.mid", path: "assets/easyrpg/music/Field 1.mid", fileName: "Field 1.mid" },
  { category: "music", id: "easyrpg-music-game-over-1", name: "EasyRPG RTP Game Over 1 Music", sourcePath: "Music/Game Over 1.mid", path: "assets/easyrpg/music/Game Over 1.mid", fileName: "Game Over 1.mid" },
  { category: "music", id: "easyrpg-music-jdoubt", name: "EasyRPG RTP JDoubt Music", sourcePath: "Music/JDoubt.mid", path: "assets/easyrpg/music/JDoubt.mid", fileName: "JDoubt.mid" },
  { category: "music", id: "easyrpg-music-jend-of-battle-1", name: "EasyRPG RTP JEnd of Battle 1 Music", sourcePath: "Music/JEnd of Battle 1.mid", path: "assets/easyrpg/music/JEnd of Battle 1.mid", fileName: "JEnd of Battle 1.mid" },
  { category: "music", id: "easyrpg-music-jend-of-battle-2", name: "EasyRPG RTP JEnd of Battle 2 Music", sourcePath: "Music/JEnd of Battle 2.mid", path: "assets/easyrpg/music/JEnd of Battle 2.mid", fileName: "JEnd of Battle 2.mid" },
  { category: "music", id: "easyrpg-music-jend-of-battle-3", name: "EasyRPG RTP JEnd of Battle 3 Music", sourcePath: "Music/JEnd of Battle 3.mid", path: "assets/easyrpg/music/JEnd of Battle 3.mid", fileName: "JEnd of Battle 3.mid" },
  { category: "music", id: "easyrpg-music-jend-of-battle-4", name: "EasyRPG RTP JEnd of Battle 4 Music", sourcePath: "Music/JEnd of Battle 4.mid", path: "assets/easyrpg/music/JEnd of Battle 4.mid", fileName: "JEnd of Battle 4.mid" },
  { category: "music", id: "easyrpg-music-jfanfare-1", name: "EasyRPG RTP JFanfare 1 Music", sourcePath: "Music/JFanfare 1.mid", path: "assets/easyrpg/music/JFanfare 1.mid", fileName: "JFanfare 1.mid" },
  { category: "music", id: "easyrpg-music-jfanfare-2", name: "EasyRPG RTP JFanfare 2 Music", sourcePath: "Music/JFanfare 2.mid", path: "assets/easyrpg/music/JFanfare 2.mid", fileName: "JFanfare 2.mid" },
  { category: "music", id: "easyrpg-music-jfanfare-3", name: "EasyRPG RTP JFanfare 3 Music", sourcePath: "Music/JFanfare 3.mid", path: "assets/easyrpg/music/JFanfare 3.mid", fileName: "JFanfare 3.mid" },
  { category: "music", id: "easyrpg-music-jfanfare-4", name: "EasyRPG RTP JFanfare 4 Music", sourcePath: "Music/JFanfare 4.mid", path: "assets/easyrpg/music/JFanfare 4.mid", fileName: "JFanfare 4.mid" },
  { category: "music", id: "easyrpg-music-jfanfare-5", name: "EasyRPG RTP JFanfare 5 Music", sourcePath: "Music/JFanfare 5.mid", path: "assets/easyrpg/music/JFanfare 5.mid", fileName: "JFanfare 5.mid" },
  { category: "music", id: "easyrpg-music-jfanfare-6", name: "EasyRPG RTP JFanfare 6 Music", sourcePath: "Music/JFanfare 6.mid", path: "assets/easyrpg/music/JFanfare 6.mid", fileName: "JFanfare 6.mid" },
  { category: "music", id: "easyrpg-music-jinn-1", name: "EasyRPG RTP JInn 1 Music", sourcePath: "Music/JInn 1.mid", path: "assets/easyrpg/music/JInn 1.mid", fileName: "JInn 1.mid" },
  { category: "music", id: "easyrpg-music-jinn-2", name: "EasyRPG RTP JInn 2 Music", sourcePath: "Music/JInn 2.mid", path: "assets/easyrpg/music/JInn 2.mid", fileName: "JInn 2.mid" },
  { category: "music", id: "easyrpg-music-jitem", name: "EasyRPG RTP JItem Music", sourcePath: "Music/JItem.mid", path: "assets/easyrpg/music/JItem.mid", fileName: "JItem.mid" },
  { category: "music", id: "easyrpg-music-jjoke-1", name: "EasyRPG RTP JJoke 1 Music", sourcePath: "Music/JJoke 1.mid", path: "assets/easyrpg/music/JJoke 1.mid", fileName: "JJoke 1.mid" },
  { category: "music", id: "easyrpg-music-jjoke-2", name: "EasyRPG RTP JJoke 2 Music", sourcePath: "Music/JJoke 2.mid", path: "assets/easyrpg/music/JJoke 2.mid", fileName: "JJoke 2.mid" },
  { category: "music", id: "easyrpg-music-jmystery", name: "EasyRPG RTP JMystery Music", sourcePath: "Music/JMystery.mid", path: "assets/easyrpg/music/JMystery.mid", fileName: "JMystery.mid" },
  { category: "music", id: "easyrpg-music-mystery-1", name: "EasyRPG RTP Mystery 1 Music", sourcePath: "Music/Mystery 1.mid", path: "assets/easyrpg/music/Mystery 1.mid", fileName: "Mystery 1.mid" },
  { category: "music", id: "easyrpg-music-opening-2", name: "EasyRPG RTP Opening 2 Music", sourcePath: "Music/Opening 2.mid", path: "assets/easyrpg/music/Opening 2.mid", fileName: "Opening 2.mid" },
  { category: "music", id: "easyrpg-music-sorrow", name: "EasyRPG RTP Sorrow Music", sourcePath: "Music/Sorrow.mid", path: "assets/easyrpg/music/Sorrow.mid", fileName: "Sorrow.mid" },
  { category: "music", id: "easyrpg-music-town-1", name: "EasyRPG RTP Town 1 Music", sourcePath: "Music/Town 1.mid", path: "assets/easyrpg/music/Town 1.mid", fileName: "Town 1.mid" },
  { category: "music", id: "easyrpg-music-vehicle-1", name: "EasyRPG RTP Vehicle 1 Music", sourcePath: "Music/Vehicle 1.mid", path: "assets/easyrpg/music/Vehicle 1.mid", fileName: "Vehicle 1.mid" },
  { category: "backdrop", id: "easyrpg-backdrop-cosmos1", name: "EasyRPG RTP Cosmos1 Panorama", sourcePath: "Panorama/Cosmos1.png", path: "assets/easyrpg/backdrop/Cosmos1.png", fileName: "Cosmos1.png" },
  { category: "backdrop", id: "easyrpg-backdrop-dawn1", name: "EasyRPG RTP Dawn1 Panorama", sourcePath: "Panorama/Dawn1.png", path: "assets/easyrpg/backdrop/Dawn1.png", fileName: "Dawn1.png" },
  { category: "backdrop", id: "easyrpg-backdrop-dawn2", name: "EasyRPG RTP Dawn2 Panorama", sourcePath: "Panorama/Dawn2.png", path: "assets/easyrpg/backdrop/Dawn2.png", fileName: "Dawn2.png" },
  { category: "backdrop", id: "easyrpg-backdrop-dimension-rift", name: "EasyRPG RTP Dimension Rift Panorama", sourcePath: "Panorama/Dimension Rift.png", path: "assets/easyrpg/backdrop/Dimension Rift.png", fileName: "Dimension Rift.png" },
  { category: "backdrop", id: "easyrpg-backdrop-night-sky1", name: "EasyRPG RTP Night Sky1 Panorama", sourcePath: "Panorama/Night Sky1.png", path: "assets/easyrpg/backdrop/Night Sky1.png", fileName: "Night Sky1.png" },
  { category: "backdrop", id: "easyrpg-backdrop-night-sky2", name: "EasyRPG RTP Night Sky2 Panorama", sourcePath: "Panorama/Night Sky2.png", path: "assets/easyrpg/backdrop/Night Sky2.png", fileName: "Night Sky2.png" },
  { category: "backdrop", id: "easyrpg-backdrop-planet1", name: "EasyRPG RTP Planet1 Panorama", sourcePath: "Panorama/Planet1.png", path: "assets/easyrpg/backdrop/Planet1.png", fileName: "Planet1.png" },
  { category: "backdrop", id: "easyrpg-backdrop-planet2", name: "EasyRPG RTP Planet2 Panorama", sourcePath: "Panorama/Planet2.png", path: "assets/easyrpg/backdrop/Planet2.png", fileName: "Planet2.png" },
  { category: "backdrop", id: "easyrpg-backdrop-planet3", name: "EasyRPG RTP Planet3 Panorama", sourcePath: "Panorama/Planet3.png", path: "assets/easyrpg/backdrop/Planet3.png", fileName: "Planet3.png" },
  { category: "backdrop", id: "easyrpg-backdrop-sky1", name: "EasyRPG RTP Sky1 Panorama", sourcePath: "Panorama/Sky1.png", path: "assets/easyrpg/backdrop/Sky1.png", fileName: "Sky1.png" },
  { category: "backdrop", id: "easyrpg-backdrop-sky2", name: "EasyRPG RTP Sky2 Panorama", sourcePath: "Panorama/Sky2.png", path: "assets/easyrpg/backdrop/Sky2.png", fileName: "Sky2.png" },
  { category: "backdrop", id: "easyrpg-backdrop-sunset1", name: "EasyRPG RTP Sunset1 Panorama", sourcePath: "Panorama/Sunset1.png", path: "assets/easyrpg/backdrop/Sunset1.png", fileName: "Sunset1.png" },
  { category: "backdrop", id: "easyrpg-backdrop-sunset2", name: "EasyRPG RTP Sunset2 Panorama", sourcePath: "Panorama/Sunset2.png", path: "assets/easyrpg/backdrop/Sunset2.png", fileName: "Sunset2.png" },
  { category: "picture", id: "easyrpg-picture-cloud", name: "EasyRPG RTP Cloud Picture", sourcePath: "Picture/Cloud.png", path: "assets/easyrpg/picture/Cloud.png", fileName: "Cloud.png" },
  { category: "sound", id: "easyrpg-sound-absorb1", name: "EasyRPG RTP Absorb1 Sound", sourcePath: "Sound/Absorb1.wav", path: "assets/easyrpg/sound/Absorb1.wav", fileName: "Absorb1.wav" },
  { category: "sound", id: "easyrpg-sound-absorb2", name: "EasyRPG RTP Absorb2 Sound", sourcePath: "Sound/Absorb2.wav", path: "assets/easyrpg/sound/Absorb2.wav", fileName: "Absorb2.wav" },
  { category: "sound", id: "easyrpg-sound-attack1", name: "EasyRPG RTP Attack1 Sound", sourcePath: "Sound/Attack1.wav", path: "assets/easyrpg/sound/Attack1.wav", fileName: "Attack1.wav" },
  { category: "sound", id: "easyrpg-sound-attack2", name: "EasyRPG RTP Attack2 Sound", sourcePath: "Sound/Attack2.wav", path: "assets/easyrpg/sound/Attack2.wav", fileName: "Attack2.wav" },
  { category: "sound", id: "easyrpg-sound-barrier", name: "EasyRPG RTP Barrier Sound", sourcePath: "Sound/Barrier.wav", path: "assets/easyrpg/sound/Barrier.wav", fileName: "Barrier.wav" },
  { category: "sound", id: "easyrpg-sound-barrier1", name: "EasyRPG RTP Barrier1 Sound", sourcePath: "Sound/Barrier1.wav", path: "assets/easyrpg/sound/Barrier1.wav", fileName: "Barrier1.wav" },
  { category: "sound", id: "easyrpg-sound-barrier2", name: "EasyRPG RTP Barrier2 Sound", sourcePath: "Sound/Barrier2.wav", path: "assets/easyrpg/sound/Barrier2.wav", fileName: "Barrier2.wav" },
  { category: "sound", id: "easyrpg-sound-bell", name: "EasyRPG RTP Bell Sound", sourcePath: "Sound/Bell.wav", path: "assets/easyrpg/sound/Bell.wav", fileName: "Bell.wav" },
  { category: "sound", id: "easyrpg-sound-blind", name: "EasyRPG RTP Blind Sound", sourcePath: "Sound/Blind.wav", path: "assets/easyrpg/sound/Blind.wav", fileName: "Blind.wav" },
  { category: "sound", id: "easyrpg-sound-blow2", name: "EasyRPG RTP Blow2 Sound", sourcePath: "Sound/Blow2.wav", path: "assets/easyrpg/sound/Blow2.wav", fileName: "Blow2.wav" },
  { category: "sound", id: "easyrpg-sound-blow4", name: "EasyRPG RTP Blow4 Sound", sourcePath: "Sound/Blow4.wav", path: "assets/easyrpg/sound/Blow4.wav", fileName: "Blow4.wav" },
  { category: "sound", id: "easyrpg-sound-breath", name: "EasyRPG RTP Breath Sound", sourcePath: "Sound/Breath.wav", path: "assets/easyrpg/sound/Breath.wav", fileName: "Breath.wav" },
  { category: "sound", id: "easyrpg-sound-buff", name: "EasyRPG RTP Buff Sound", sourcePath: "Sound/Buff.wav", path: "assets/easyrpg/sound/Buff.wav", fileName: "Buff.wav" },
  { category: "sound", id: "easyrpg-sound-buzzer1", name: "EasyRPG RTP Buzzer1 Sound", sourcePath: "Sound/Buzzer1.wav", path: "assets/easyrpg/sound/Buzzer1.wav", fileName: "Buzzer1.wav" },
  { category: "sound", id: "easyrpg-sound-buzzer2", name: "EasyRPG RTP Buzzer2 Sound", sourcePath: "Sound/Buzzer2.wav", path: "assets/easyrpg/sound/Buzzer2.wav", fileName: "Buzzer2.wav" },
  { category: "sound", id: "easyrpg-sound-buzzer3", name: "EasyRPG RTP Buzzer3 Sound", sourcePath: "Sound/Buzzer3.wav", path: "assets/easyrpg/sound/Buzzer3.wav", fileName: "Buzzer3.wav" },
  { category: "sound", id: "easyrpg-sound-buzzer4", name: "EasyRPG RTP Buzzer4 Sound", sourcePath: "Sound/Buzzer4.wav", path: "assets/easyrpg/sound/Buzzer4.wav", fileName: "Buzzer4.wav" },
  { category: "sound", id: "easyrpg-sound-cancel1", name: "EasyRPG RTP Cancel1 Sound", sourcePath: "Sound/Cancel1.wav", path: "assets/easyrpg/sound/Cancel1.wav", fileName: "Cancel1.wav" },
  { category: "sound", id: "easyrpg-sound-cancel2", name: "EasyRPG RTP Cancel2 Sound", sourcePath: "Sound/Cancel2.wav", path: "assets/easyrpg/sound/Cancel2.wav", fileName: "Cancel2.wav" },
  { category: "sound", id: "easyrpg-sound-cat", name: "EasyRPG RTP Cat Sound", sourcePath: "Sound/Cat.wav", path: "assets/easyrpg/sound/Cat.wav", fileName: "Cat.wav" },
  { category: "sound", id: "easyrpg-sound-chime1", name: "EasyRPG RTP Chime1 Sound", sourcePath: "Sound/Chime1.wav", path: "assets/easyrpg/sound/Chime1.wav", fileName: "Chime1.wav" },
  { category: "sound", id: "easyrpg-sound-chime2", name: "EasyRPG RTP Chime2 Sound", sourcePath: "Sound/Chime2.wav", path: "assets/easyrpg/sound/Chime2.wav", fileName: "Chime2.wav" },
  { category: "sound", id: "easyrpg-sound-clock", name: "EasyRPG RTP Clock Sound", sourcePath: "Sound/Clock.wav", path: "assets/easyrpg/sound/Clock.wav", fileName: "Clock.wav" },
  { category: "sound", id: "easyrpg-sound-close1", name: "EasyRPG RTP Close1 Sound", sourcePath: "Sound/Close1.wav", path: "assets/easyrpg/sound/Close1.wav", fileName: "Close1.wav" },
  { category: "sound", id: "easyrpg-sound-collapse1", name: "EasyRPG RTP Collapse1 Sound", sourcePath: "Sound/Collapse1.wav", path: "assets/easyrpg/sound/Collapse1.wav", fileName: "Collapse1.wav" },
  { category: "sound", id: "easyrpg-sound-collapse2", name: "EasyRPG RTP Collapse2 Sound", sourcePath: "Sound/Collapse2.wav", path: "assets/easyrpg/sound/Collapse2.wav", fileName: "Collapse2.wav" },
  { category: "sound", id: "easyrpg-sound-combat1", name: "EasyRPG RTP Combat1 Sound", sourcePath: "Sound/Combat1.wav", path: "assets/easyrpg/sound/Combat1.wav", fileName: "Combat1.wav" },
  { category: "sound", id: "easyrpg-sound-combat2", name: "EasyRPG RTP Combat2 Sound", sourcePath: "Sound/Combat2.wav", path: "assets/easyrpg/sound/Combat2.wav", fileName: "Combat2.wav" },
  { category: "sound", id: "easyrpg-sound-confusion", name: "EasyRPG RTP Confusion Sound", sourcePath: "Sound/Confusion.wav", path: "assets/easyrpg/sound/Confusion.wav", fileName: "Confusion.wav" },
  { category: "sound", id: "easyrpg-sound-cursor1", name: "EasyRPG RTP Cursor1 Sound", sourcePath: "Sound/Cursor1.wav", path: "assets/easyrpg/sound/Cursor1.wav", fileName: "Cursor1.wav" },
  { category: "sound", id: "easyrpg-sound-cursor2", name: "EasyRPG RTP Cursor2 Sound", sourcePath: "Sound/Cursor2.wav", path: "assets/easyrpg/sound/Cursor2.wav", fileName: "Cursor2.wav" },
  { category: "sound", id: "easyrpg-sound-damage2", name: "EasyRPG RTP Damage2 Sound", sourcePath: "Sound/Damage2.wav", path: "assets/easyrpg/sound/Damage2.wav", fileName: "Damage2.wav" },
  { category: "sound", id: "easyrpg-sound-darkness3", name: "EasyRPG RTP Darkness3 Sound", sourcePath: "Sound/Darkness3.wav", path: "assets/easyrpg/sound/Darkness3.wav", fileName: "Darkness3.wav" },
  { category: "sound", id: "easyrpg-sound-darkness4", name: "EasyRPG RTP Darkness4 Sound", sourcePath: "Sound/Darkness4.wav", path: "assets/easyrpg/sound/Darkness4.wav", fileName: "Darkness4.wav" },
  { category: "sound", id: "easyrpg-sound-darkness5", name: "EasyRPG RTP Darkness5 Sound", sourcePath: "Sound/Darkness5.wav", path: "assets/easyrpg/sound/Darkness5.wav", fileName: "Darkness5.wav" },
  { category: "sound", id: "easyrpg-sound-debuff", name: "EasyRPG RTP Debuff Sound", sourcePath: "Sound/Debuff.wav", path: "assets/easyrpg/sound/Debuff.wav", fileName: "Debuff.wav" },
  { category: "sound", id: "easyrpg-sound-decision1", name: "EasyRPG RTP Decision1 Sound", sourcePath: "Sound/Decision1.wav", path: "assets/easyrpg/sound/Decision1.wav", fileName: "Decision1.wav" },
  { category: "sound", id: "easyrpg-sound-decision2", name: "EasyRPG RTP Decision2 Sound", sourcePath: "Sound/Decision2.wav", path: "assets/easyrpg/sound/Decision2.wav", fileName: "Decision2.wav" },
  { category: "sound", id: "easyrpg-sound-dog", name: "EasyRPG RTP Dog Sound", sourcePath: "Sound/Dog.wav", path: "assets/easyrpg/sound/Dog.wav", fileName: "Dog.wav" },
  { category: "sound", id: "easyrpg-sound-earth2", name: "EasyRPG RTP Earth2 Sound", sourcePath: "Sound/Earth2.wav", path: "assets/easyrpg/sound/Earth2.wav", fileName: "Earth2.wav" },
  { category: "sound", id: "easyrpg-sound-earth6", name: "EasyRPG RTP Earth6 Sound", sourcePath: "Sound/Earth6.wav", path: "assets/easyrpg/sound/Earth6.wav", fileName: "Earth6.wav" },
  { category: "sound", id: "easyrpg-sound-earth7", name: "EasyRPG RTP Earth7 Sound", sourcePath: "Sound/Earth7.wav", path: "assets/easyrpg/sound/Earth7.wav", fileName: "Earth7.wav" },
  { category: "sound", id: "easyrpg-sound-earth8", name: "EasyRPG RTP Earth8 Sound", sourcePath: "Sound/Earth8.wav", path: "assets/easyrpg/sound/Earth8.wav", fileName: "Earth8.wav" },
  { category: "sound", id: "easyrpg-sound-escape", name: "EasyRPG RTP Escape Sound", sourcePath: "Sound/Escape.wav", path: "assets/easyrpg/sound/Escape.wav", fileName: "Escape.wav" },
  { category: "sound", id: "easyrpg-sound-evade1", name: "EasyRPG RTP Evade1 Sound", sourcePath: "Sound/Evade1.wav", path: "assets/easyrpg/sound/Evade1.wav", fileName: "Evade1.wav" },
  { category: "sound", id: "easyrpg-sound-evade2", name: "EasyRPG RTP Evade2 Sound", sourcePath: "Sound/Evade2.wav", path: "assets/easyrpg/sound/Evade2.wav", fileName: "Evade2.wav" },
  { category: "sound", id: "easyrpg-sound-explosion1", name: "EasyRPG RTP Explosion1 Sound", sourcePath: "Sound/Explosion1.wav", path: "assets/easyrpg/sound/Explosion1.wav", fileName: "Explosion1.wav" },
  { category: "sound", id: "easyrpg-sound-fall1", name: "EasyRPG RTP Fall1 Sound", sourcePath: "Sound/Fall1.wav", path: "assets/easyrpg/sound/Fall1.wav", fileName: "Fall1.wav" },
  { category: "sound", id: "easyrpg-sound-fall2", name: "EasyRPG RTP Fall2 Sound", sourcePath: "Sound/Fall2.wav", path: "assets/easyrpg/sound/Fall2.wav", fileName: "Fall2.wav" },
  { category: "sound", id: "easyrpg-sound-fire1", name: "EasyRPG RTP Fire1 Sound", sourcePath: "Sound/Fire1.wav", path: "assets/easyrpg/sound/Fire1.wav", fileName: "Fire1.wav" },
  { category: "sound", id: "easyrpg-sound-fire2", name: "EasyRPG RTP Fire2 Sound", sourcePath: "Sound/Fire2.wav", path: "assets/easyrpg/sound/Fire2.wav", fileName: "Fire2.wav" },
  { category: "sound", id: "easyrpg-sound-fire3", name: "EasyRPG RTP Fire3 Sound", sourcePath: "Sound/Fire3.wav", path: "assets/easyrpg/sound/Fire3.wav", fileName: "Fire3.wav" },
  { category: "sound", id: "easyrpg-sound-fire4", name: "EasyRPG RTP Fire4 Sound", sourcePath: "Sound/Fire4.wav", path: "assets/easyrpg/sound/Fire4.wav", fileName: "Fire4.wav" },
  { category: "sound", id: "easyrpg-sound-fire5", name: "EasyRPG RTP Fire5 Sound", sourcePath: "Sound/Fire5.wav", path: "assets/easyrpg/sound/Fire5.wav", fileName: "Fire5.wav" },
  { category: "sound", id: "easyrpg-sound-fire6", name: "EasyRPG RTP Fire6 Sound", sourcePath: "Sound/Fire6.wav", path: "assets/easyrpg/sound/Fire6.wav", fileName: "Fire6.wav" },
  { category: "sound", id: "easyrpg-sound-fire7", name: "EasyRPG RTP Fire7 Sound", sourcePath: "Sound/Fire7.wav", path: "assets/easyrpg/sound/Fire7.wav", fileName: "Fire7.wav" },
  { category: "sound", id: "easyrpg-sound-flash1", name: "EasyRPG RTP Flash1 Sound", sourcePath: "Sound/Flash1.wav", path: "assets/easyrpg/sound/Flash1.wav", fileName: "Flash1.wav" },
  { category: "sound", id: "easyrpg-sound-flash3", name: "EasyRPG RTP Flash3 Sound", sourcePath: "Sound/Flash3.wav", path: "assets/easyrpg/sound/Flash3.wav", fileName: "Flash3.wav" },
  { category: "sound", id: "easyrpg-sound-fog1", name: "EasyRPG RTP Fog1 Sound", sourcePath: "Sound/Fog1.wav", path: "assets/easyrpg/sound/Fog1.wav", fileName: "Fog1.wav" },
  { category: "sound", id: "easyrpg-sound-glare", name: "EasyRPG RTP Glare Sound", sourcePath: "Sound/Glare.wav", path: "assets/easyrpg/sound/Glare.wav", fileName: "Glare.wav" },
  { category: "sound", id: "easyrpg-sound-holy2", name: "EasyRPG RTP Holy2 Sound", sourcePath: "Sound/Holy2.wav", path: "assets/easyrpg/sound/Holy2.wav", fileName: "Holy2.wav" },
  { category: "sound", id: "easyrpg-sound-holy3", name: "EasyRPG RTP Holy3 Sound", sourcePath: "Sound/Holy3.wav", path: "assets/easyrpg/sound/Holy3.wav", fileName: "Holy3.wav" },
  { category: "sound", id: "easyrpg-sound-holy5", name: "EasyRPG RTP Holy5 Sound", sourcePath: "Sound/Holy5.wav", path: "assets/easyrpg/sound/Holy5.wav", fileName: "Holy5.wav" },
  { category: "sound", id: "easyrpg-sound-holy6", name: "EasyRPG RTP Holy6 Sound", sourcePath: "Sound/Holy6.wav", path: "assets/easyrpg/sound/Holy6.wav", fileName: "Holy6.wav" },
  { category: "sound", id: "easyrpg-sound-holy7", name: "EasyRPG RTP Holy7 Sound", sourcePath: "Sound/Holy7.wav", path: "assets/easyrpg/sound/Holy7.wav", fileName: "Holy7.wav" },
  { category: "sound", id: "easyrpg-sound-ice1", name: "EasyRPG RTP Ice1 Sound", sourcePath: "Sound/Ice1.wav", path: "assets/easyrpg/sound/Ice1.wav", fileName: "Ice1.wav" },
  { category: "sound", id: "easyrpg-sound-ice2", name: "EasyRPG RTP Ice2 Sound", sourcePath: "Sound/Ice2.wav", path: "assets/easyrpg/sound/Ice2.wav", fileName: "Ice2.wav" },
  { category: "sound", id: "easyrpg-sound-ice5", name: "EasyRPG RTP Ice5 Sound", sourcePath: "Sound/Ice5.wav", path: "assets/easyrpg/sound/Ice5.wav", fileName: "Ice5.wav" },
  { category: "sound", id: "easyrpg-sound-ice6", name: "EasyRPG RTP Ice6 Sound", sourcePath: "Sound/Ice6.wav", path: "assets/easyrpg/sound/Ice6.wav", fileName: "Ice6.wav" },
  { category: "sound", id: "easyrpg-sound-ice7", name: "EasyRPG RTP Ice7 Sound", sourcePath: "Sound/Ice7.wav", path: "assets/easyrpg/sound/Ice7.wav", fileName: "Ice7.wav" },
  { category: "sound", id: "easyrpg-sound-ice9", name: "EasyRPG RTP Ice9 Sound", sourcePath: "Sound/Ice9.wav", path: "assets/easyrpg/sound/Ice9.wav", fileName: "Ice9.wav" },
  { category: "sound", id: "easyrpg-sound-item1", name: "EasyRPG RTP Item1 Sound", sourcePath: "Sound/Item1.wav", path: "assets/easyrpg/sound/Item1.wav", fileName: "Item1.wav" },
  { category: "sound", id: "easyrpg-sound-item2", name: "EasyRPG RTP Item2 Sound", sourcePath: "Sound/Item2.wav", path: "assets/easyrpg/sound/Item2.wav", fileName: "Item2.wav" },
  { category: "sound", id: "easyrpg-sound-key", name: "EasyRPG RTP Key Sound", sourcePath: "Sound/Key.wav", path: "assets/easyrpg/sound/Key.wav", fileName: "Key.wav" },
  { category: "sound", id: "easyrpg-sound-knock", name: "EasyRPG RTP Knock Sound", sourcePath: "Sound/Knock.wav", path: "assets/easyrpg/sound/Knock.wav", fileName: "Knock.wav" },
  { category: "sound", id: "easyrpg-sound-magic1", name: "EasyRPG RTP Magic1 Sound", sourcePath: "Sound/Magic1.wav", path: "assets/easyrpg/sound/Magic1.wav", fileName: "Magic1.wav" },
  { category: "sound", id: "easyrpg-sound-magic2", name: "EasyRPG RTP Magic2 Sound", sourcePath: "Sound/Magic2.wav", path: "assets/easyrpg/sound/Magic2.wav", fileName: "Magic2.wav" },
  { category: "sound", id: "easyrpg-sound-monster1", name: "EasyRPG RTP Monster1 Sound", sourcePath: "Sound/Monster1.wav", path: "assets/easyrpg/sound/Monster1.wav", fileName: "Monster1.wav" },
  { category: "sound", id: "easyrpg-sound-move", name: "EasyRPG RTP Move Sound", sourcePath: "Sound/Move.wav", path: "assets/easyrpg/sound/Move.wav", fileName: "Move.wav" },
  { category: "sound", id: "easyrpg-sound-poison", name: "EasyRPG RTP Poison Sound", sourcePath: "Sound/Poison.wav", path: "assets/easyrpg/sound/Poison.wav", fileName: "Poison.wav" },
  { category: "sound", id: "easyrpg-sound-pollen", name: "EasyRPG RTP Pollen Sound", sourcePath: "Sound/Pollen.wav", path: "assets/easyrpg/sound/Pollen.wav", fileName: "Pollen.wav" },
  { category: "sound", id: "easyrpg-sound-raise2", name: "EasyRPG RTP Raise2 Sound", sourcePath: "Sound/Raise2.wav", path: "assets/easyrpg/sound/Raise2.wav", fileName: "Raise2.wav" },
  { category: "sound", id: "easyrpg-sound-recovery5", name: "EasyRPG RTP Recovery5 Sound", sourcePath: "Sound/Recovery5.wav", path: "assets/easyrpg/sound/Recovery5.wav", fileName: "Recovery5.wav" },
  { category: "sound", id: "easyrpg-sound-recovery7", name: "EasyRPG RTP Recovery7 Sound", sourcePath: "Sound/Recovery7.wav", path: "assets/easyrpg/sound/Recovery7.wav", fileName: "Recovery7.wav" },
  { category: "sound", id: "easyrpg-sound-recovery8", name: "EasyRPG RTP Recovery8 Sound", sourcePath: "Sound/Recovery8.wav", path: "assets/easyrpg/sound/Recovery8.wav", fileName: "Recovery8.wav" },
  { category: "sound", id: "easyrpg-sound-sandstorm", name: "EasyRPG RTP Sandstorm Sound", sourcePath: "Sound/Sandstorm.wav", path: "assets/easyrpg/sound/Sandstorm.wav", fileName: "Sandstorm.wav" },
  { category: "sound", id: "easyrpg-sound-shot1", name: "EasyRPG RTP Shot1 Sound", sourcePath: "Sound/Shot1.wav", path: "assets/easyrpg/sound/Shot1.wav", fileName: "Shot1.wav" },
  { category: "sound", id: "easyrpg-sound-shot2", name: "EasyRPG RTP Shot2 Sound", sourcePath: "Sound/Shot2.wav", path: "assets/easyrpg/sound/Shot2.wav", fileName: "Shot2.wav" },
  { category: "sound", id: "easyrpg-sound-shot3", name: "EasyRPG RTP Shot3 Sound", sourcePath: "Sound/Shot3.wav", path: "assets/easyrpg/sound/Shot3.wav", fileName: "Shot3.wav" },
  { category: "sound", id: "easyrpg-sound-silence", name: "EasyRPG RTP Silence Sound", sourcePath: "Sound/Silence.wav", path: "assets/easyrpg/sound/Silence.wav", fileName: "Silence.wav" },
  { category: "sound", id: "easyrpg-sound-sleep", name: "EasyRPG RTP Sleep Sound", sourcePath: "Sound/Sleep.wav", path: "assets/easyrpg/sound/Sleep.wav", fileName: "Sleep.wav" },
  { category: "sound", id: "easyrpg-sound-song", name: "EasyRPG RTP Song Sound", sourcePath: "Sound/Song.wav", path: "assets/easyrpg/sound/Song.wav", fileName: "Song.wav" },
  { category: "sound", id: "easyrpg-sound-teleport2", name: "EasyRPG RTP Teleport2 Sound", sourcePath: "Sound/Teleport2.wav", path: "assets/easyrpg/sound/Teleport2.wav", fileName: "Teleport2.wav" },
  { category: "sound", id: "easyrpg-sound-wave1", name: "EasyRPG RTP Wave1 Sound", sourcePath: "Sound/Wave1.wav", path: "assets/easyrpg/sound/Wave1.wav", fileName: "Wave1.wav" },
  { category: "sound", id: "easyrpg-sound-wave2", name: "EasyRPG RTP Wave2 Sound", sourcePath: "Sound/Wave2.wav", path: "assets/easyrpg/sound/Wave2.wav", fileName: "Wave2.wav" },
  { category: "sound", id: "easyrpg-sound-wind8", name: "EasyRPG RTP Wind8 Sound", sourcePath: "Sound/Wind8.wav", path: "assets/easyrpg/sound/Wind8.wav", fileName: "Wind8.wav" },
  { category: "system", id: "easyrpg-system-royal", name: "EasyRPG RTP Royal System", sourcePath: "System/Royal.png", path: "assets/easyrpg/system/Royal.png", fileName: "Royal.png" },
  { category: "system", id: "easyrpg-system-system", name: "EasyRPG RTP System System", sourcePath: "System/System.png", path: "assets/easyrpg/system/System.png", fileName: "System.png" },
  { category: "system", id: "easyrpg-system-system-a", name: "EasyRPG RTP SystemA System", sourcePath: "System/SystemA.png", path: "assets/easyrpg/system/SystemA.png", fileName: "SystemA.png" },
  { category: "system", id: "easyrpg-system-system-b", name: "EasyRPG RTP SystemB System", sourcePath: "System/SystemB.png", path: "assets/easyrpg/system/SystemB.png", fileName: "SystemB.png" },
  { category: "system", id: "easyrpg-system-system-c", name: "EasyRPG RTP SystemC System", sourcePath: "System/SystemC.png", path: "assets/easyrpg/system/SystemC.png", fileName: "SystemC.png" },
  { category: "system2", id: "easyrpg-system2-system2-a", name: "EasyRPG RTP System2A System2", sourcePath: "System2/System2A.png", path: "assets/easyrpg/system2/System2A.png", fileName: "System2A.png" },
  { category: "system2", id: "easyrpg-system2-system2-b", name: "EasyRPG RTP System2B System2", sourcePath: "System2/System2B.png", path: "assets/easyrpg/system2/System2B.png", fileName: "System2B.png" },
  { category: "system2", id: "easyrpg-system2-system2-c", name: "EasyRPG RTP System2C System2", sourcePath: "System2/System2C.png", path: "assets/easyrpg/system2/System2C.png", fileName: "System2C.png" },
  { category: "title", id: "easyrpg-title-title1", name: "EasyRPG RTP Title1 Title", sourcePath: "Title/Title1.png", path: "assets/easyrpg/title/Title1.png", fileName: "Title1.png" },
  { category: "title", id: "easyrpg-title-title2", name: "EasyRPG RTP Title2 Title", sourcePath: "Title/Title2.png", path: "assets/easyrpg/title/Title2.png", fileName: "Title2.png" },
  { category: "title", id: "easyrpg-title-title3", name: "EasyRPG RTP Title3 Title", sourcePath: "Title/Title3.png", path: "assets/easyrpg/title/Title3.png", fileName: "Title3.png" },
  { category: "title", id: "easyrpg-title-title4", name: "EasyRPG RTP Title4 Title", sourcePath: "Title/Title4.png", path: "assets/easyrpg/title/Title4.png", fileName: "Title4.png" },
] as const satisfies readonly EasyRpgRtpAsset[];

export const EASYRPG_BACKDROP_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "backdrop");
export const EASYRPG_BATTLE_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "battle");
export const EASYRPG_BATTLE_WEAPON_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "battleWeapon");
export const EASYRPG_CHIPSET_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "chipset");
export const EASYRPG_FACESET_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "faceset");
export const EASYRPG_GAME_OVER_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "gameOver");
export const EASYRPG_MONSTER_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "monster");
export const EASYRPG_MUSIC_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "music");
export const EASYRPG_PICTURE_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "picture");
export const EASYRPG_SOUND_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "sound");
export const EASYRPG_SYSTEM_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "system");
export const EASYRPG_SYSTEM2_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "system2");
export const EASYRPG_TITLE_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "title");
export const EASYRPG_CHARSET_ASSETS = [
  { category: "charset", id: "easyrpg-charset-actor1", name: "EasyRPG RTP Actor1 CharSet", sourcePath: "CharSet/Actor1.png", path: "assets/easyrpg/charset/Actor1.png", fileName: "Actor1.png", textureKey: "tex_easyrpg_charset_actor1", group: "Actor" },
  { category: "charset", id: "easyrpg-charset-actor2", name: "EasyRPG RTP Actor2 CharSet", sourcePath: "CharSet/Actor2.png", path: "assets/easyrpg/charset/Actor2.png", fileName: "Actor2.png", textureKey: "tex_easyrpg_charset_actor2", group: "Actor" },
  { category: "charset", id: "easyrpg-charset-actor3", name: "EasyRPG RTP Actor3 CharSet", sourcePath: "CharSet/Actor3.png", path: "assets/easyrpg/charset/Actor3.png", fileName: "Actor3.png", textureKey: "tex_easyrpg_charset_actor3", group: "Actor" },
  { category: "charset", id: "easyrpg-charset-actor4", name: "EasyRPG RTP Actor4 CharSet", sourcePath: "CharSet/Actor4.png", path: "assets/easyrpg/charset/Actor4.png", fileName: "Actor4.png", textureKey: "tex_easyrpg_charset_actor4", group: "Actor" },
  { category: "charset", id: "easyrpg-charset-animal", name: "EasyRPG RTP Animal CharSet", sourcePath: "CharSet/Animal.png", path: "assets/easyrpg/charset/Animal.png", fileName: "Animal.png", textureKey: "tex_easyrpg_charset_animal", group: "Animal" },
  { category: "charset", id: "easyrpg-charset-monster1", name: "EasyRPG RTP Monster1 CharSet", sourcePath: "CharSet/Monster1.png", path: "assets/easyrpg/charset/Monster1.png", fileName: "Monster1.png", textureKey: "tex_easyrpg_charset_monster1", group: "Monster" },
  { category: "charset", id: "easyrpg-charset-monster2", name: "EasyRPG RTP Monster2 CharSet", sourcePath: "CharSet/Monster2.png", path: "assets/easyrpg/charset/Monster2.png", fileName: "Monster2.png", textureKey: "tex_easyrpg_charset_monster2", group: "Monster" },
  { category: "charset", id: "easyrpg-charset-monster3", name: "EasyRPG RTP Monster3 CharSet", sourcePath: "CharSet/Monster3.png", path: "assets/easyrpg/charset/Monster3.png", fileName: "Monster3.png", textureKey: "tex_easyrpg_charset_monster3", group: "Monster" },
  { category: "charset", id: "easyrpg-charset-object1", name: "EasyRPG RTP Object1 CharSet", sourcePath: "CharSet/Object1.png", path: "assets/easyrpg/charset/Object1.png", fileName: "Object1.png", textureKey: "tex_easyrpg_charset_object1", group: "Object" },
  { category: "charset", id: "easyrpg-charset-object2", name: "EasyRPG RTP Object2 CharSet", sourcePath: "CharSet/Object2.png", path: "assets/easyrpg/charset/Object2.png", fileName: "Object2.png", textureKey: "tex_easyrpg_charset_object2", group: "Object" },
  { category: "charset", id: "easyrpg-charset-people1", name: "EasyRPG RTP People1 CharSet", sourcePath: "CharSet/People1.png", path: "assets/easyrpg/charset/People1.png", fileName: "People1.png", textureKey: "tex_easyrpg_charset_people1", group: "People" },
  { category: "charset", id: "easyrpg-charset-people2", name: "EasyRPG RTP People2 CharSet", sourcePath: "CharSet/People2.png", path: "assets/easyrpg/charset/People2.png", fileName: "People2.png", textureKey: "tex_easyrpg_charset_people2", group: "People" },
  { category: "charset", id: "easyrpg-charset-people3", name: "EasyRPG RTP People3 CharSet", sourcePath: "CharSet/People3.png", path: "assets/easyrpg/charset/People3.png", fileName: "People3.png", textureKey: "tex_easyrpg_charset_people3", group: "People" },
  { category: "charset", id: "easyrpg-charset-people4", name: "EasyRPG RTP People4 CharSet", sourcePath: "CharSet/People4.png", path: "assets/easyrpg/charset/People4.png", fileName: "People4.png", textureKey: "tex_easyrpg_charset_people4", group: "People" },
  { category: "charset", id: "easyrpg-charset-people5", name: "EasyRPG RTP People5 CharSet", sourcePath: "CharSet/People5.png", path: "assets/easyrpg/charset/People5.png", fileName: "People5.png", textureKey: "tex_easyrpg_charset_people5", group: "People" },
  { category: "charset", id: "easyrpg-charset-template", name: "EasyRPG RTP Template CharSet", sourcePath: "CharSet/Template.png", path: "assets/easyrpg/charset/Template.png", fileName: "Template.png", textureKey: "tex_easyrpg_charset_template", group: "Template" },
  { category: "charset", id: "easyrpg-charset-vehicles", name: "EasyRPG RTP Vehicles CharSet", sourcePath: "CharSet/Vehicles.png", path: "assets/easyrpg/charset/Vehicles.png", fileName: "Vehicles.png", textureKey: "tex_easyrpg_charset_vehicles", group: "Vehicles" },
] as const satisfies readonly EasyRpgCharsetAsset[];

export const CHARSET_FRAME_WIDTH = 24;
export const CHARSET_FRAME_HEIGHT = 32;
export const CHARSET_SHEET_COLUMNS = 12;
export const CHARSET_SHEET_ROWS = 8;
export const CHARSET_CHARACTER_COLUMNS = 3;
export const CHARSET_CHARACTER_ROWS = 4;
export const CHARSET_CHARACTERS_PER_ROW = 4;
export const CHARSET_CHARACTER_COUNT = 8;
export const CHARSET_FRAME_COUNT = CHARSET_SHEET_COLUMNS * CHARSET_SHEET_ROWS;
export const CHARSET_DIRECTIONS = ["down", "left", "right", "up"] as const satisfies readonly CharsetDirection[];

export type CharsetFrameSelection = {
  readonly characterIndex: number;
  readonly direction: CharsetDirection;
  readonly pattern: number;
};

export type CharsetFrameSource = {
  readonly x: number;
  readonly y: number;
  readonly width: number;
  readonly height: number;
};

export function charsetFrameIndex(selection: CharsetFrameSelection): number {
  const characterIndex = boundedInt(selection.characterIndex, 0, CHARSET_CHARACTER_COUNT - 1);
  const pattern = boundedInt(selection.pattern, 0, CHARSET_CHARACTER_COLUMNS - 1);
  const directionRow = CHARSET_DIRECTIONS.indexOf(selection.direction);
  const characterColumn = characterIndex % CHARSET_CHARACTERS_PER_ROW;
  const characterRow = Math.floor(characterIndex / CHARSET_CHARACTERS_PER_ROW);
  const column = characterColumn * CHARSET_CHARACTER_COLUMNS + pattern;
  const row = characterRow * CHARSET_CHARACTER_ROWS + Math.max(directionRow, 0);
  return row * CHARSET_SHEET_COLUMNS + column;
}

export function decodeCharsetFrameIndex(frameIndex: number): CharsetFrameSelection {
  const normalized = boundedInt(frameIndex, 0, CHARSET_FRAME_COUNT - 1);
  const column = normalized % CHARSET_SHEET_COLUMNS;
  const row = Math.floor(normalized / CHARSET_SHEET_COLUMNS);
  const characterColumn = Math.floor(column / CHARSET_CHARACTER_COLUMNS);
  const characterRow = Math.floor(row / CHARSET_CHARACTER_ROWS);
  const direction = CHARSET_DIRECTIONS[row % CHARSET_CHARACTER_ROWS] ?? "down";
  return {
    characterIndex: characterRow * CHARSET_CHARACTERS_PER_ROW + characterColumn,
    direction,
    pattern: column % CHARSET_CHARACTER_COLUMNS,
  };
}

export function charsetFrameSource(selection: CharsetFrameSelection): CharsetFrameSource {
  const frameIndex = charsetFrameIndex(selection);
  const column = frameIndex % CHARSET_SHEET_COLUMNS;
  const row = Math.floor(frameIndex / CHARSET_SHEET_COLUMNS);
  return {
    x: column * CHARSET_FRAME_WIDTH,
    y: row * CHARSET_FRAME_HEIGHT,
    width: CHARSET_FRAME_WIDTH,
    height: CHARSET_FRAME_HEIGHT,
  };
}

function boundedInt(value: number, min: number, max: number): number {
  if (!Number.isFinite(value)) return min;
  return Math.min(max, Math.max(min, Math.trunc(value)));
}
