// Generated by scripts/sync-easyrpg-rtp-assets.mjs. Do not edit by hand.
// Source: https://github.com/EasyRPG/RTP/tree/993d88cbc78c658d348bbfa74a3b424d393d27e5

import { FACE_IMAGE_SIZE, RESOURCE_SLICING, type ResourceSlicingSpec } from "@/assets/resourceSlicing";

export const EASYRPG_RTP_COMMIT = "993d88cbc78c658d348bbfa74a3b424d393d27e5";
export const EASYRPG_RTP_SOURCE_URL = "https://github.com/EasyRPG/RTP";
export type EasyRpgRtpCategory =
  | "backdrop"
  | "battle"
  | "battleWeapon"
  | "charset"
  | "chipset"
  | "faceset"
  | "gameOver"
  | "monster"
  | "music"
  | "picture"
  | "sound"
  | "system"
  | "system2"
  | "title";
export type CharsetDirection = "down" | "left" | "right" | "up";

export type EasyRpgRtpAsset = {
  readonly category: EasyRpgRtpCategory;
  readonly id: string;
  readonly name: string;
  readonly sourcePath: string;
  readonly path: string;
  readonly fileName: string;
  readonly textureKey?: string;
  readonly group?: string;
};

export type EasyRpgCharsetAsset = EasyRpgRtpAsset & {
  readonly category: "charset";
  readonly textureKey: string;
  readonly group: string;
};
export const EASYRPG_RTP_ASSETS = [
  { category: "battleWeapon", id: "easyrpg-battle-weapon-weapon", name: "Weapon · 전투 무기 · EasyRPG", sourcePath: "BattleWeapon/Weapon.png", path: "assets/easyrpg/battle-weapon/Weapon.png", fileName: "Weapon.png" },
  { category: "charset", id: "easyrpg-charset-actor1", name: "Actor1 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Actor1.png", path: "assets/easyrpg/charset/Actor1.png", fileName: "Actor1.png", textureKey: "tex_easyrpg_charset_actor1", group: "Actor" },
  { category: "charset", id: "easyrpg-charset-actor2", name: "Actor2 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Actor2.png", path: "assets/easyrpg/charset/Actor2.png", fileName: "Actor2.png", textureKey: "tex_easyrpg_charset_actor2", group: "Actor" },
  { category: "charset", id: "easyrpg-charset-actor3", name: "Actor3 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Actor3.png", path: "assets/easyrpg/charset/Actor3.png", fileName: "Actor3.png", textureKey: "tex_easyrpg_charset_actor3", group: "Actor" },
  { category: "charset", id: "easyrpg-charset-actor4", name: "Actor4 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Actor4.png", path: "assets/easyrpg/charset/Actor4.png", fileName: "Actor4.png", textureKey: "tex_easyrpg_charset_actor4", group: "Actor" },
  { category: "charset", id: "easyrpg-charset-animal", name: "Animal · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Animal.png", path: "assets/easyrpg/charset/Animal.png", fileName: "Animal.png", textureKey: "tex_easyrpg_charset_animal", group: "Animal" },
  { category: "charset", id: "easyrpg-charset-monster1", name: "Monster1 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Monster1.png", path: "assets/easyrpg/charset/Monster1.png", fileName: "Monster1.png", textureKey: "tex_easyrpg_charset_monster1", group: "Monster" },
  { category: "charset", id: "easyrpg-charset-monster2", name: "Monster2 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Monster2.png", path: "assets/easyrpg/charset/Monster2.png", fileName: "Monster2.png", textureKey: "tex_easyrpg_charset_monster2", group: "Monster" },
  { category: "charset", id: "easyrpg-charset-monster3", name: "Monster3 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Monster3.png", path: "assets/easyrpg/charset/Monster3.png", fileName: "Monster3.png", textureKey: "tex_easyrpg_charset_monster3", group: "Monster" },
  { category: "charset", id: "easyrpg-charset-object1", name: "Object1 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Object1.png", path: "assets/easyrpg/charset/Object1.png", fileName: "Object1.png", textureKey: "tex_easyrpg_charset_object1", group: "Object" },
  { category: "charset", id: "easyrpg-charset-object2", name: "Object2 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Object2.png", path: "assets/easyrpg/charset/Object2.png", fileName: "Object2.png", textureKey: "tex_easyrpg_charset_object2", group: "Object" },
  { category: "charset", id: "easyrpg-charset-people1", name: "People1 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/People1.png", path: "assets/easyrpg/charset/People1.png", fileName: "People1.png", textureKey: "tex_easyrpg_charset_people1", group: "People" },
  { category: "charset", id: "easyrpg-charset-people2", name: "People2 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/People2.png", path: "assets/easyrpg/charset/People2.png", fileName: "People2.png", textureKey: "tex_easyrpg_charset_people2", group: "People" },
  { category: "charset", id: "easyrpg-charset-people3", name: "People3 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/People3.png", path: "assets/easyrpg/charset/People3.png", fileName: "People3.png", textureKey: "tex_easyrpg_charset_people3", group: "People" },
  { category: "charset", id: "easyrpg-charset-people4", name: "People4 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/People4.png", path: "assets/easyrpg/charset/People4.png", fileName: "People4.png", textureKey: "tex_easyrpg_charset_people4", group: "People" },
  { category: "charset", id: "easyrpg-charset-people5", name: "People5 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/People5.png", path: "assets/easyrpg/charset/People5.png", fileName: "People5.png", textureKey: "tex_easyrpg_charset_people5", group: "People" },
  { category: "charset", id: "easyrpg-charset-template", name: "Template · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Template.png", path: "assets/easyrpg/charset/Template.png", fileName: "Template.png", textureKey: "tex_easyrpg_charset_template", group: "Template" },
  { category: "charset", id: "easyrpg-charset-vehicles", name: "Vehicles · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Vehicles.png", path: "assets/easyrpg/charset/Vehicles.png", fileName: "Vehicles.png", textureKey: "tex_easyrpg_charset_vehicles", group: "Vehicles" },
  { category: "chipset", id: "easyrpg-chipset-dungeon", name: "Dungeon · 타일 그림판 · EasyRPG", sourcePath: "ChipSet/Dungeon.png", path: "assets/easyrpg/chipset/Dungeon.png", fileName: "Dungeon.png" },
  { category: "chipset", id: "easyrpg-chipset-exterior", name: "Exterior · 타일 그림판 · EasyRPG", sourcePath: "ChipSet/Exterior.png", path: "assets/easyrpg/chipset/Exterior.png", fileName: "Exterior.png" },
  { category: "chipset", id: "easyrpg-chipset-interior", name: "Interior · 타일 그림판 · EasyRPG", sourcePath: "ChipSet/Interior.png", path: "assets/easyrpg/chipset/Interior.png", fileName: "Interior.png" },
  { category: "chipset", id: "easyrpg-chipset-retro-dungeon", name: "retro_Dungeon · 타일 그림판 · EasyRPG", sourcePath: "ChipSet/retro_Dungeon.png", path: "assets/easyrpg/chipset/retro_Dungeon.png", fileName: "retro_Dungeon.png" },
  { category: "chipset", id: "easyrpg-chipset-retro-exterior", name: "retro_Exterior · 타일 그림판 · EasyRPG", sourcePath: "ChipSet/retro_Exterior.png", path: "assets/easyrpg/chipset/retro_Exterior.png", fileName: "retro_Exterior.png" },
  { category: "chipset", id: "easyrpg-chipset-retro-world", name: "retro_World · 타일 그림판 · EasyRPG", sourcePath: "ChipSet/retro_World.png", path: "assets/easyrpg/chipset/retro_World.png", fileName: "retro_World.png" },
  { category: "chipset", id: "easyrpg-chipset-ship", name: "Ship · 타일 그림판 · EasyRPG", sourcePath: "ChipSet/Ship.png", path: "assets/easyrpg/chipset/Ship.png", fileName: "Ship.png" },
  { category: "chipset", id: "easyrpg-chipset-world", name: "World · 타일 그림판 · EasyRPG", sourcePath: "ChipSet/World.png", path: "assets/easyrpg/chipset/World.png", fileName: "World.png" },
  { category: "faceset", id: "easyrpg-faceset-actor1", name: "Actor1 · 얼굴 그림 · EasyRPG", sourcePath: "FaceSet/Actor1.png", path: "assets/easyrpg/faceset/Actor1.png", fileName: "Actor1.png" },
  { category: "faceset", id: "easyrpg-faceset-actor2", name: "Actor2 · 얼굴 그림 · EasyRPG", sourcePath: "FaceSet/Actor2.png", path: "assets/easyrpg/faceset/Actor2.png", fileName: "Actor2.png" },
  { category: "faceset", id: "easyrpg-faceset-monster", name: "Monster · 얼굴 그림 · EasyRPG", sourcePath: "FaceSet/Monster.png", path: "assets/easyrpg/faceset/Monster.png", fileName: "Monster.png" },
  { category: "faceset", id: "easyrpg-faceset-people1", name: "People1 · 얼굴 그림 · EasyRPG", sourcePath: "FaceSet/People1.png", path: "assets/easyrpg/faceset/People1.png", fileName: "People1.png" },
  { category: "faceset", id: "easyrpg-faceset-people2", name: "People2 · 얼굴 그림 · EasyRPG", sourcePath: "FaceSet/People2.png", path: "assets/easyrpg/faceset/People2.png", fileName: "People2.png" },
  { category: "gameOver", id: "easyrpg-game-over-game-over", name: "Game Over · 게임오버 화면 · EasyRPG", sourcePath: "GameOver/Game Over.png", path: "assets/easyrpg/game-over/Game Over.png", fileName: "Game Over.png" },
  { category: "music", id: "easyrpg-music-battle-1", name: "Battle 1 · 음악 · EasyRPG", sourcePath: "Music/Battle 1.mid", path: "assets/easyrpg/music/Battle 1.mid", fileName: "Battle 1.mid" },
  { category: "music", id: "easyrpg-music-boss-3", name: "Boss 3 · 음악 · EasyRPG", sourcePath: "Music/Boss 3.mid", path: "assets/easyrpg/music/Boss 3.mid", fileName: "Boss 3.mid" },
  { category: "music", id: "easyrpg-music-castle-1", name: "Castle 1 · 음악 · EasyRPG", sourcePath: "Music/Castle 1.mid", path: "assets/easyrpg/music/Castle 1.mid", fileName: "Castle 1.mid" },
  { category: "music", id: "easyrpg-music-church", name: "Church · 음악 · EasyRPG", sourcePath: "Music/Church.mid", path: "assets/easyrpg/music/Church.mid", fileName: "Church.mid" },
  { category: "music", id: "easyrpg-music-dungeon-1", name: "Dungeon 1 · 음악 · EasyRPG", sourcePath: "Music/Dungeon 1.mid", path: "assets/easyrpg/music/Dungeon 1.mid", fileName: "Dungeon 1.mid" },
  { category: "music", id: "easyrpg-music-ending-2", name: "Ending 2 · 음악 · EasyRPG", sourcePath: "Music/Ending 2.mid", path: "assets/easyrpg/music/Ending 2.mid", fileName: "Ending 2.mid" },
  { category: "music", id: "easyrpg-music-field-1", name: "Field 1 · 음악 · EasyRPG", sourcePath: "Music/Field 1.mid", path: "assets/easyrpg/music/Field 1.mid", fileName: "Field 1.mid" },
  { category: "music", id: "easyrpg-music-game-over-1", name: "Game Over 1 · 음악 · EasyRPG", sourcePath: "Music/Game Over 1.mid", path: "assets/easyrpg/music/Game Over 1.mid", fileName: "Game Over 1.mid" },
  { category: "music", id: "easyrpg-music-jdoubt", name: "JDoubt · 음악 · EasyRPG", sourcePath: "Music/JDoubt.mid", path: "assets/easyrpg/music/JDoubt.mid", fileName: "JDoubt.mid" },
  { category: "music", id: "easyrpg-music-jend-of-battle-1", name: "JEnd of Battle 1 · 음악 · EasyRPG", sourcePath: "Music/JEnd of Battle 1.mid", path: "assets/easyrpg/music/JEnd of Battle 1.mid", fileName: "JEnd of Battle 1.mid" },
  { category: "music", id: "easyrpg-music-jend-of-battle-2", name: "JEnd of Battle 2 · 음악 · EasyRPG", sourcePath: "Music/JEnd of Battle 2.mid", path: "assets/easyrpg/music/JEnd of Battle 2.mid", fileName: "JEnd of Battle 2.mid" },
  { category: "music", id: "easyrpg-music-jend-of-battle-3", name: "JEnd of Battle 3 · 음악 · EasyRPG", sourcePath: "Music/JEnd of Battle 3.mid", path: "assets/easyrpg/music/JEnd of Battle 3.mid", fileName: "JEnd of Battle 3.mid" },
  { category: "music", id: "easyrpg-music-jend-of-battle-4", name: "JEnd of Battle 4 · 음악 · EasyRPG", sourcePath: "Music/JEnd of Battle 4.mid", path: "assets/easyrpg/music/JEnd of Battle 4.mid", fileName: "JEnd of Battle 4.mid" },
  { category: "music", id: "easyrpg-music-jfanfare-1", name: "JFanfare 1 · 음악 · EasyRPG", sourcePath: "Music/JFanfare 1.mid", path: "assets/easyrpg/music/JFanfare 1.mid", fileName: "JFanfare 1.mid" },
  { category: "music", id: "easyrpg-music-jfanfare-2", name: "JFanfare 2 · 음악 · EasyRPG", sourcePath: "Music/JFanfare 2.mid", path: "assets/easyrpg/music/JFanfare 2.mid", fileName: "JFanfare 2.mid" },
  { category: "music", id: "easyrpg-music-jfanfare-3", name: "JFanfare 3 · 음악 · EasyRPG", sourcePath: "Music/JFanfare 3.mid", path: "assets/easyrpg/music/JFanfare 3.mid", fileName: "JFanfare 3.mid" },
  { category: "music", id: "easyrpg-music-jfanfare-4", name: "JFanfare 4 · 음악 · EasyRPG", sourcePath: "Music/JFanfare 4.mid", path: "assets/easyrpg/music/JFanfare 4.mid", fileName: "JFanfare 4.mid" },
  { category: "music", id: "easyrpg-music-jfanfare-5", name: "JFanfare 5 · 음악 · EasyRPG", sourcePath: "Music/JFanfare 5.mid", path: "assets/easyrpg/music/JFanfare 5.mid", fileName: "JFanfare 5.mid" },
  { category: "music", id: "easyrpg-music-jfanfare-6", name: "JFanfare 6 · 음악 · EasyRPG", sourcePath: "Music/JFanfare 6.mid", path: "assets/easyrpg/music/JFanfare 6.mid", fileName: "JFanfare 6.mid" },
  { category: "music", id: "easyrpg-music-jinn-1", name: "JInn 1 · 음악 · EasyRPG", sourcePath: "Music/JInn 1.mid", path: "assets/easyrpg/music/JInn 1.mid", fileName: "JInn 1.mid" },
  { category: "music", id: "easyrpg-music-jinn-2", name: "JInn 2 · 음악 · EasyRPG", sourcePath: "Music/JInn 2.mid", path: "assets/easyrpg/music/JInn 2.mid", fileName: "JInn 2.mid" },
  { category: "music", id: "easyrpg-music-jitem", name: "JItem · 음악 · EasyRPG", sourcePath: "Music/JItem.mid", path: "assets/easyrpg/music/JItem.mid", fileName: "JItem.mid" },
  { category: "music", id: "easyrpg-music-jjoke-1", name: "JJoke 1 · 음악 · EasyRPG", sourcePath: "Music/JJoke 1.mid", path: "assets/easyrpg/music/JJoke 1.mid", fileName: "JJoke 1.mid" },
  { category: "music", id: "easyrpg-music-jjoke-2", name: "JJoke 2 · 음악 · EasyRPG", sourcePath: "Music/JJoke 2.mid", path: "assets/easyrpg/music/JJoke 2.mid", fileName: "JJoke 2.mid" },
  { category: "music", id: "easyrpg-music-jmystery", name: "JMystery · 음악 · EasyRPG", sourcePath: "Music/JMystery.mid", path: "assets/easyrpg/music/JMystery.mid", fileName: "JMystery.mid" },
  { category: "music", id: "easyrpg-music-mystery-1", name: "Mystery 1 · 음악 · EasyRPG", sourcePath: "Music/Mystery 1.mid", path: "assets/easyrpg/music/Mystery 1.mid", fileName: "Mystery 1.mid" },
  { category: "music", id: "easyrpg-music-opening-2", name: "Opening 2 · 음악 · EasyRPG", sourcePath: "Music/Opening 2.mid", path: "assets/easyrpg/music/Opening 2.mid", fileName: "Opening 2.mid" },
  { category: "music", id: "easyrpg-music-sorrow", name: "Sorrow · 음악 · EasyRPG", sourcePath: "Music/Sorrow.mid", path: "assets/easyrpg/music/Sorrow.mid", fileName: "Sorrow.mid" },
  { category: "music", id: "easyrpg-music-town-1", name: "Town 1 · 음악 · EasyRPG", sourcePath: "Music/Town 1.mid", path: "assets/easyrpg/music/Town 1.mid", fileName: "Town 1.mid" },
  { category: "music", id: "easyrpg-music-vehicle-1", name: "Vehicle 1 · 음악 · EasyRPG", sourcePath: "Music/Vehicle 1.mid", path: "assets/easyrpg/music/Vehicle 1.mid", fileName: "Vehicle 1.mid" },
  { category: "backdrop", id: "easyrpg-backdrop-cosmos1", name: "Cosmos1 · 배경 그림 · EasyRPG", sourcePath: "Panorama/Cosmos1.png", path: "assets/easyrpg/backdrop/Cosmos1.png", fileName: "Cosmos1.png" },
  { category: "backdrop", id: "easyrpg-backdrop-dawn1", name: "Dawn1 · 배경 그림 · EasyRPG", sourcePath: "Panorama/Dawn1.png", path: "assets/easyrpg/backdrop/Dawn1.png", fileName: "Dawn1.png" },
  { category: "backdrop", id: "easyrpg-backdrop-dawn2", name: "Dawn2 · 배경 그림 · EasyRPG", sourcePath: "Panorama/Dawn2.png", path: "assets/easyrpg/backdrop/Dawn2.png", fileName: "Dawn2.png" },
  { category: "backdrop", id: "easyrpg-backdrop-dimension-rift", name: "Dimension Rift · 배경 그림 · EasyRPG", sourcePath: "Panorama/Dimension Rift.png", path: "assets/easyrpg/backdrop/Dimension Rift.png", fileName: "Dimension Rift.png" },
  { category: "backdrop", id: "easyrpg-backdrop-night-sky1", name: "Night Sky1 · 배경 그림 · EasyRPG", sourcePath: "Panorama/Night Sky1.png", path: "assets/easyrpg/backdrop/Night Sky1.png", fileName: "Night Sky1.png" },
  { category: "backdrop", id: "easyrpg-backdrop-night-sky2", name: "Night Sky2 · 배경 그림 · EasyRPG", sourcePath: "Panorama/Night Sky2.png", path: "assets/easyrpg/backdrop/Night Sky2.png", fileName: "Night Sky2.png" },
  { category: "backdrop", id: "easyrpg-backdrop-planet1", name: "Planet1 · 배경 그림 · EasyRPG", sourcePath: "Panorama/Planet1.png", path: "assets/easyrpg/backdrop/Planet1.png", fileName: "Planet1.png" },
  { category: "backdrop", id: "easyrpg-backdrop-planet2", name: "Planet2 · 배경 그림 · EasyRPG", sourcePath: "Panorama/Planet2.png", path: "assets/easyrpg/backdrop/Planet2.png", fileName: "Planet2.png" },
  { category: "backdrop", id: "easyrpg-backdrop-planet3", name: "Planet3 · 배경 그림 · EasyRPG", sourcePath: "Panorama/Planet3.png", path: "assets/easyrpg/backdrop/Planet3.png", fileName: "Planet3.png" },
  { category: "backdrop", id: "easyrpg-backdrop-sky1", name: "Sky1 · 배경 그림 · EasyRPG", sourcePath: "Panorama/Sky1.png", path: "assets/easyrpg/backdrop/Sky1.png", fileName: "Sky1.png" },
  { category: "backdrop", id: "easyrpg-backdrop-sky2", name: "Sky2 · 배경 그림 · EasyRPG", sourcePath: "Panorama/Sky2.png", path: "assets/easyrpg/backdrop/Sky2.png", fileName: "Sky2.png" },
  { category: "backdrop", id: "easyrpg-backdrop-sunset1", name: "Sunset1 · 배경 그림 · EasyRPG", sourcePath: "Panorama/Sunset1.png", path: "assets/easyrpg/backdrop/Sunset1.png", fileName: "Sunset1.png" },
  { category: "backdrop", id: "easyrpg-backdrop-sunset2", name: "Sunset2 · 배경 그림 · EasyRPG", sourcePath: "Panorama/Sunset2.png", path: "assets/easyrpg/backdrop/Sunset2.png", fileName: "Sunset2.png" },
  { category: "picture", id: "easyrpg-picture-cloud", name: "Cloud · 그림 · EasyRPG", sourcePath: "Picture/Cloud.png", path: "assets/easyrpg/picture/Cloud.png", fileName: "Cloud.png" },
  { category: "sound", id: "easyrpg-sound-absorb1", name: "Absorb1 · 효과음 · EasyRPG", sourcePath: "Sound/Absorb1.wav", path: "assets/easyrpg/sound/Absorb1.wav", fileName: "Absorb1.wav" },
  { category: "sound", id: "easyrpg-sound-absorb2", name: "Absorb2 · 효과음 · EasyRPG", sourcePath: "Sound/Absorb2.wav", path: "assets/easyrpg/sound/Absorb2.wav", fileName: "Absorb2.wav" },
  { category: "sound", id: "easyrpg-sound-attack1", name: "Attack1 · 효과음 · EasyRPG", sourcePath: "Sound/Attack1.wav", path: "assets/easyrpg/sound/Attack1.wav", fileName: "Attack1.wav" },
  { category: "sound", id: "easyrpg-sound-attack2", name: "Attack2 · 효과음 · EasyRPG", sourcePath: "Sound/Attack2.wav", path: "assets/easyrpg/sound/Attack2.wav", fileName: "Attack2.wav" },
  { category: "sound", id: "easyrpg-sound-barrier", name: "Barrier · 효과음 · EasyRPG", sourcePath: "Sound/Barrier.wav", path: "assets/easyrpg/sound/Barrier.wav", fileName: "Barrier.wav" },
  { category: "sound", id: "easyrpg-sound-barrier1", name: "Barrier1 · 효과음 · EasyRPG", sourcePath: "Sound/Barrier1.wav", path: "assets/easyrpg/sound/Barrier1.wav", fileName: "Barrier1.wav" },
  { category: "sound", id: "easyrpg-sound-barrier2", name: "Barrier2 · 효과음 · EasyRPG", sourcePath: "Sound/Barrier2.wav", path: "assets/easyrpg/sound/Barrier2.wav", fileName: "Barrier2.wav" },
  { category: "sound", id: "easyrpg-sound-bell", name: "Bell · 효과음 · EasyRPG", sourcePath: "Sound/Bell.wav", path: "assets/easyrpg/sound/Bell.wav", fileName: "Bell.wav" },
  { category: "sound", id: "easyrpg-sound-blind", name: "Blind · 효과음 · EasyRPG", sourcePath: "Sound/Blind.wav", path: "assets/easyrpg/sound/Blind.wav", fileName: "Blind.wav" },
  { category: "sound", id: "easyrpg-sound-blow2", name: "Blow2 · 효과음 · EasyRPG", sourcePath: "Sound/Blow2.wav", path: "assets/easyrpg/sound/Blow2.wav", fileName: "Blow2.wav" },
  { category: "sound", id: "easyrpg-sound-blow4", name: "Blow4 · 효과음 · EasyRPG", sourcePath: "Sound/Blow4.wav", path: "assets/easyrpg/sound/Blow4.wav", fileName: "Blow4.wav" },
  { category: "sound", id: "easyrpg-sound-breath", name: "Breath · 효과음 · EasyRPG", sourcePath: "Sound/Breath.wav", path: "assets/easyrpg/sound/Breath.wav", fileName: "Breath.wav" },
  { category: "sound", id: "easyrpg-sound-buff", name: "Buff · 효과음 · EasyRPG", sourcePath: "Sound/Buff.wav", path: "assets/easyrpg/sound/Buff.wav", fileName: "Buff.wav" },
  { category: "sound", id: "easyrpg-sound-buzzer1", name: "Buzzer1 · 효과음 · EasyRPG", sourcePath: "Sound/Buzzer1.wav", path: "assets/easyrpg/sound/Buzzer1.wav", fileName: "Buzzer1.wav" },
  { category: "sound", id: "easyrpg-sound-buzzer2", name: "Buzzer2 · 효과음 · EasyRPG", sourcePath: "Sound/Buzzer2.wav", path: "assets/easyrpg/sound/Buzzer2.wav", fileName: "Buzzer2.wav" },
  { category: "sound", id: "easyrpg-sound-buzzer3", name: "Buzzer3 · 효과음 · EasyRPG", sourcePath: "Sound/Buzzer3.wav", path: "assets/easyrpg/sound/Buzzer3.wav", fileName: "Buzzer3.wav" },
  { category: "sound", id: "easyrpg-sound-buzzer4", name: "Buzzer4 · 효과음 · EasyRPG", sourcePath: "Sound/Buzzer4.wav", path: "assets/easyrpg/sound/Buzzer4.wav", fileName: "Buzzer4.wav" },
  { category: "sound", id: "easyrpg-sound-cancel1", name: "Cancel1 · 효과음 · EasyRPG", sourcePath: "Sound/Cancel1.wav", path: "assets/easyrpg/sound/Cancel1.wav", fileName: "Cancel1.wav" },
  { category: "sound", id: "easyrpg-sound-cancel2", name: "Cancel2 · 효과음 · EasyRPG", sourcePath: "Sound/Cancel2.wav", path: "assets/easyrpg/sound/Cancel2.wav", fileName: "Cancel2.wav" },
  { category: "sound", id: "easyrpg-sound-cat", name: "Cat · 효과음 · EasyRPG", sourcePath: "Sound/Cat.wav", path: "assets/easyrpg/sound/Cat.wav", fileName: "Cat.wav" },
  { category: "sound", id: "easyrpg-sound-chime1", name: "Chime1 · 효과음 · EasyRPG", sourcePath: "Sound/Chime1.wav", path: "assets/easyrpg/sound/Chime1.wav", fileName: "Chime1.wav" },
  { category: "sound", id: "easyrpg-sound-chime2", name: "Chime2 · 효과음 · EasyRPG", sourcePath: "Sound/Chime2.wav", path: "assets/easyrpg/sound/Chime2.wav", fileName: "Chime2.wav" },
  { category: "sound", id: "easyrpg-sound-clock", name: "Clock · 효과음 · EasyRPG", sourcePath: "Sound/Clock.wav", path: "assets/easyrpg/sound/Clock.wav", fileName: "Clock.wav" },
  { category: "sound", id: "easyrpg-sound-close1", name: "Close1 · 효과음 · EasyRPG", sourcePath: "Sound/Close1.wav", path: "assets/easyrpg/sound/Close1.wav", fileName: "Close1.wav" },
  { category: "sound", id: "easyrpg-sound-collapse1", name: "Collapse1 · 효과음 · EasyRPG", sourcePath: "Sound/Collapse1.wav", path: "assets/easyrpg/sound/Collapse1.wav", fileName: "Collapse1.wav" },
  { category: "sound", id: "easyrpg-sound-collapse2", name: "Collapse2 · 효과음 · EasyRPG", sourcePath: "Sound/Collapse2.wav", path: "assets/easyrpg/sound/Collapse2.wav", fileName: "Collapse2.wav" },
  { category: "sound", id: "easyrpg-sound-combat1", name: "Combat1 · 효과음 · EasyRPG", sourcePath: "Sound/Combat1.wav", path: "assets/easyrpg/sound/Combat1.wav", fileName: "Combat1.wav" },
  { category: "sound", id: "easyrpg-sound-combat2", name: "Combat2 · 효과음 · EasyRPG", sourcePath: "Sound/Combat2.wav", path: "assets/easyrpg/sound/Combat2.wav", fileName: "Combat2.wav" },
  { category: "sound", id: "easyrpg-sound-confusion", name: "Confusion · 효과음 · EasyRPG", sourcePath: "Sound/Confusion.wav", path: "assets/easyrpg/sound/Confusion.wav", fileName: "Confusion.wav" },
  { category: "sound", id: "easyrpg-sound-cursor1", name: "Cursor1 · 효과음 · EasyRPG", sourcePath: "Sound/Cursor1.wav", path: "assets/easyrpg/sound/Cursor1.wav", fileName: "Cursor1.wav" },
  { category: "sound", id: "easyrpg-sound-cursor2", name: "Cursor2 · 효과음 · EasyRPG", sourcePath: "Sound/Cursor2.wav", path: "assets/easyrpg/sound/Cursor2.wav", fileName: "Cursor2.wav" },
  { category: "sound", id: "easyrpg-sound-damage2", name: "Damage2 · 효과음 · EasyRPG", sourcePath: "Sound/Damage2.wav", path: "assets/easyrpg/sound/Damage2.wav", fileName: "Damage2.wav" },
  { category: "sound", id: "easyrpg-sound-darkness3", name: "Darkness3 · 효과음 · EasyRPG", sourcePath: "Sound/Darkness3.wav", path: "assets/easyrpg/sound/Darkness3.wav", fileName: "Darkness3.wav" },
  { category: "sound", id: "easyrpg-sound-darkness4", name: "Darkness4 · 효과음 · EasyRPG", sourcePath: "Sound/Darkness4.wav", path: "assets/easyrpg/sound/Darkness4.wav", fileName: "Darkness4.wav" },
  { category: "sound", id: "easyrpg-sound-darkness5", name: "Darkness5 · 효과음 · EasyRPG", sourcePath: "Sound/Darkness5.wav", path: "assets/easyrpg/sound/Darkness5.wav", fileName: "Darkness5.wav" },
  { category: "sound", id: "easyrpg-sound-debuff", name: "Debuff · 효과음 · EasyRPG", sourcePath: "Sound/Debuff.wav", path: "assets/easyrpg/sound/Debuff.wav", fileName: "Debuff.wav" },
  { category: "sound", id: "easyrpg-sound-decision1", name: "Decision1 · 효과음 · EasyRPG", sourcePath: "Sound/Decision1.wav", path: "assets/easyrpg/sound/Decision1.wav", fileName: "Decision1.wav" },
  { category: "sound", id: "easyrpg-sound-decision2", name: "Decision2 · 효과음 · EasyRPG", sourcePath: "Sound/Decision2.wav", path: "assets/easyrpg/sound/Decision2.wav", fileName: "Decision2.wav" },
  { category: "sound", id: "easyrpg-sound-dog", name: "Dog · 효과음 · EasyRPG", sourcePath: "Sound/Dog.wav", path: "assets/easyrpg/sound/Dog.wav", fileName: "Dog.wav" },
  { category: "sound", id: "easyrpg-sound-earth2", name: "Earth2 · 효과음 · EasyRPG", sourcePath: "Sound/Earth2.wav", path: "assets/easyrpg/sound/Earth2.wav", fileName: "Earth2.wav" },
  { category: "sound", id: "easyrpg-sound-earth6", name: "Earth6 · 효과음 · EasyRPG", sourcePath: "Sound/Earth6.wav", path: "assets/easyrpg/sound/Earth6.wav", fileName: "Earth6.wav" },
  { category: "sound", id: "easyrpg-sound-earth7", name: "Earth7 · 효과음 · EasyRPG", sourcePath: "Sound/Earth7.wav", path: "assets/easyrpg/sound/Earth7.wav", fileName: "Earth7.wav" },
  { category: "sound", id: "easyrpg-sound-earth8", name: "Earth8 · 효과음 · EasyRPG", sourcePath: "Sound/Earth8.wav", path: "assets/easyrpg/sound/Earth8.wav", fileName: "Earth8.wav" },
  { category: "sound", id: "easyrpg-sound-escape", name: "Escape · 효과음 · EasyRPG", sourcePath: "Sound/Escape.wav", path: "assets/easyrpg/sound/Escape.wav", fileName: "Escape.wav" },
  { category: "sound", id: "easyrpg-sound-evade1", name: "Evade1 · 효과음 · EasyRPG", sourcePath: "Sound/Evade1.wav", path: "assets/easyrpg/sound/Evade1.wav", fileName: "Evade1.wav" },
  { category: "sound", id: "easyrpg-sound-evade2", name: "Evade2 · 효과음 · EasyRPG", sourcePath: "Sound/Evade2.wav", path: "assets/easyrpg/sound/Evade2.wav", fileName: "Evade2.wav" },
  { category: "sound", id: "easyrpg-sound-explosion1", name: "Explosion1 · 효과음 · EasyRPG", sourcePath: "Sound/Explosion1.wav", path: "assets/easyrpg/sound/Explosion1.wav", fileName: "Explosion1.wav" },
  { category: "sound", id: "easyrpg-sound-fall1", name: "Fall1 · 효과음 · EasyRPG", sourcePath: "Sound/Fall1.wav", path: "assets/easyrpg/sound/Fall1.wav", fileName: "Fall1.wav" },
  { category: "sound", id: "easyrpg-sound-fall2", name: "Fall2 · 효과음 · EasyRPG", sourcePath: "Sound/Fall2.wav", path: "assets/easyrpg/sound/Fall2.wav", fileName: "Fall2.wav" },
  { category: "sound", id: "easyrpg-sound-fire1", name: "Fire1 · 효과음 · EasyRPG", sourcePath: "Sound/Fire1.wav", path: "assets/easyrpg/sound/Fire1.wav", fileName: "Fire1.wav" },
  { category: "sound", id: "easyrpg-sound-fire2", name: "Fire2 · 효과음 · EasyRPG", sourcePath: "Sound/Fire2.wav", path: "assets/easyrpg/sound/Fire2.wav", fileName: "Fire2.wav" },
  { category: "sound", id: "easyrpg-sound-fire3", name: "Fire3 · 효과음 · EasyRPG", sourcePath: "Sound/Fire3.wav", path: "assets/easyrpg/sound/Fire3.wav", fileName: "Fire3.wav" },
  { category: "sound", id: "easyrpg-sound-fire4", name: "Fire4 · 효과음 · EasyRPG", sourcePath: "Sound/Fire4.wav", path: "assets/easyrpg/sound/Fire4.wav", fileName: "Fire4.wav" },
  { category: "sound", id: "easyrpg-sound-fire5", name: "Fire5 · 효과음 · EasyRPG", sourcePath: "Sound/Fire5.wav", path: "assets/easyrpg/sound/Fire5.wav", fileName: "Fire5.wav" },
  { category: "sound", id: "easyrpg-sound-fire6", name: "Fire6 · 효과음 · EasyRPG", sourcePath: "Sound/Fire6.wav", path: "assets/easyrpg/sound/Fire6.wav", fileName: "Fire6.wav" },
  { category: "sound", id: "easyrpg-sound-fire7", name: "Fire7 · 효과음 · EasyRPG", sourcePath: "Sound/Fire7.wav", path: "assets/easyrpg/sound/Fire7.wav", fileName: "Fire7.wav" },
  { category: "sound", id: "easyrpg-sound-flash1", name: "Flash1 · 효과음 · EasyRPG", sourcePath: "Sound/Flash1.wav", path: "assets/easyrpg/sound/Flash1.wav", fileName: "Flash1.wav" },
  { category: "sound", id: "easyrpg-sound-flash3", name: "Flash3 · 효과음 · EasyRPG", sourcePath: "Sound/Flash3.wav", path: "assets/easyrpg/sound/Flash3.wav", fileName: "Flash3.wav" },
  { category: "sound", id: "easyrpg-sound-fog1", name: "Fog1 · 효과음 · EasyRPG", sourcePath: "Sound/Fog1.wav", path: "assets/easyrpg/sound/Fog1.wav", fileName: "Fog1.wav" },
  { category: "sound", id: "easyrpg-sound-glare", name: "Glare · 효과음 · EasyRPG", sourcePath: "Sound/Glare.wav", path: "assets/easyrpg/sound/Glare.wav", fileName: "Glare.wav" },
  { category: "sound", id: "easyrpg-sound-holy2", name: "Holy2 · 효과음 · EasyRPG", sourcePath: "Sound/Holy2.wav", path: "assets/easyrpg/sound/Holy2.wav", fileName: "Holy2.wav" },
  { category: "sound", id: "easyrpg-sound-holy3", name: "Holy3 · 효과음 · EasyRPG", sourcePath: "Sound/Holy3.wav", path: "assets/easyrpg/sound/Holy3.wav", fileName: "Holy3.wav" },
  { category: "sound", id: "easyrpg-sound-holy5", name: "Holy5 · 효과음 · EasyRPG", sourcePath: "Sound/Holy5.wav", path: "assets/easyrpg/sound/Holy5.wav", fileName: "Holy5.wav" },
  { category: "sound", id: "easyrpg-sound-holy6", name: "Holy6 · 효과음 · EasyRPG", sourcePath: "Sound/Holy6.wav", path: "assets/easyrpg/sound/Holy6.wav", fileName: "Holy6.wav" },
  { category: "sound", id: "easyrpg-sound-holy7", name: "Holy7 · 효과음 · EasyRPG", sourcePath: "Sound/Holy7.wav", path: "assets/easyrpg/sound/Holy7.wav", fileName: "Holy7.wav" },
  { category: "sound", id: "easyrpg-sound-ice1", name: "Ice1 · 효과음 · EasyRPG", sourcePath: "Sound/Ice1.wav", path: "assets/easyrpg/sound/Ice1.wav", fileName: "Ice1.wav" },
  { category: "sound", id: "easyrpg-sound-ice2", name: "Ice2 · 효과음 · EasyRPG", sourcePath: "Sound/Ice2.wav", path: "assets/easyrpg/sound/Ice2.wav", fileName: "Ice2.wav" },
  { category: "sound", id: "easyrpg-sound-ice5", name: "Ice5 · 효과음 · EasyRPG", sourcePath: "Sound/Ice5.wav", path: "assets/easyrpg/sound/Ice5.wav", fileName: "Ice5.wav" },
  { category: "sound", id: "easyrpg-sound-ice6", name: "Ice6 · 효과음 · EasyRPG", sourcePath: "Sound/Ice6.wav", path: "assets/easyrpg/sound/Ice6.wav", fileName: "Ice6.wav" },
  { category: "sound", id: "easyrpg-sound-ice7", name: "Ice7 · 효과음 · EasyRPG", sourcePath: "Sound/Ice7.wav", path: "assets/easyrpg/sound/Ice7.wav", fileName: "Ice7.wav" },
  { category: "sound", id: "easyrpg-sound-ice9", name: "Ice9 · 효과음 · EasyRPG", sourcePath: "Sound/Ice9.wav", path: "assets/easyrpg/sound/Ice9.wav", fileName: "Ice9.wav" },
  { category: "sound", id: "easyrpg-sound-item1", name: "Item1 · 효과음 · EasyRPG", sourcePath: "Sound/Item1.wav", path: "assets/easyrpg/sound/Item1.wav", fileName: "Item1.wav" },
  { category: "sound", id: "easyrpg-sound-item2", name: "Item2 · 효과음 · EasyRPG", sourcePath: "Sound/Item2.wav", path: "assets/easyrpg/sound/Item2.wav", fileName: "Item2.wav" },
  { category: "sound", id: "easyrpg-sound-key", name: "Key · 효과음 · EasyRPG", sourcePath: "Sound/Key.wav", path: "assets/easyrpg/sound/Key.wav", fileName: "Key.wav" },
  { category: "sound", id: "easyrpg-sound-knock", name: "Knock · 효과음 · EasyRPG", sourcePath: "Sound/Knock.wav", path: "assets/easyrpg/sound/Knock.wav", fileName: "Knock.wav" },
  { category: "sound", id: "easyrpg-sound-magic1", name: "Magic1 · 효과음 · EasyRPG", sourcePath: "Sound/Magic1.wav", path: "assets/easyrpg/sound/Magic1.wav", fileName: "Magic1.wav" },
  { category: "sound", id: "easyrpg-sound-magic2", name: "Magic2 · 효과음 · EasyRPG", sourcePath: "Sound/Magic2.wav", path: "assets/easyrpg/sound/Magic2.wav", fileName: "Magic2.wav" },
  { category: "sound", id: "easyrpg-sound-monster1", name: "Monster1 · 효과음 · EasyRPG", sourcePath: "Sound/Monster1.wav", path: "assets/easyrpg/sound/Monster1.wav", fileName: "Monster1.wav" },
  { category: "sound", id: "easyrpg-sound-move", name: "Move · 효과음 · EasyRPG", sourcePath: "Sound/Move.wav", path: "assets/easyrpg/sound/Move.wav", fileName: "Move.wav" },
  { category: "sound", id: "easyrpg-sound-poison", name: "Poison · 효과음 · EasyRPG", sourcePath: "Sound/Poison.wav", path: "assets/easyrpg/sound/Poison.wav", fileName: "Poison.wav" },
  { category: "sound", id: "easyrpg-sound-pollen", name: "Pollen · 효과음 · EasyRPG", sourcePath: "Sound/Pollen.wav", path: "assets/easyrpg/sound/Pollen.wav", fileName: "Pollen.wav" },
  { category: "sound", id: "easyrpg-sound-raise2", name: "Raise2 · 효과음 · EasyRPG", sourcePath: "Sound/Raise2.wav", path: "assets/easyrpg/sound/Raise2.wav", fileName: "Raise2.wav" },
  { category: "sound", id: "easyrpg-sound-recovery5", name: "Recovery5 · 효과음 · EasyRPG", sourcePath: "Sound/Recovery5.wav", path: "assets/easyrpg/sound/Recovery5.wav", fileName: "Recovery5.wav" },
  { category: "sound", id: "easyrpg-sound-recovery7", name: "Recovery7 · 효과음 · EasyRPG", sourcePath: "Sound/Recovery7.wav", path: "assets/easyrpg/sound/Recovery7.wav", fileName: "Recovery7.wav" },
  { category: "sound", id: "easyrpg-sound-recovery8", name: "Recovery8 · 효과음 · EasyRPG", sourcePath: "Sound/Recovery8.wav", path: "assets/easyrpg/sound/Recovery8.wav", fileName: "Recovery8.wav" },
  { category: "sound", id: "easyrpg-sound-sandstorm", name: "Sandstorm · 효과음 · EasyRPG", sourcePath: "Sound/Sandstorm.wav", path: "assets/easyrpg/sound/Sandstorm.wav", fileName: "Sandstorm.wav" },
  { category: "sound", id: "easyrpg-sound-shot1", name: "Shot1 · 효과음 · EasyRPG", sourcePath: "Sound/Shot1.wav", path: "assets/easyrpg/sound/Shot1.wav", fileName: "Shot1.wav" },
  { category: "sound", id: "easyrpg-sound-shot2", name: "Shot2 · 효과음 · EasyRPG", sourcePath: "Sound/Shot2.wav", path: "assets/easyrpg/sound/Shot2.wav", fileName: "Shot2.wav" },
  { category: "sound", id: "easyrpg-sound-shot3", name: "Shot3 · 효과음 · EasyRPG", sourcePath: "Sound/Shot3.wav", path: "assets/easyrpg/sound/Shot3.wav", fileName: "Shot3.wav" },
  { category: "sound", id: "easyrpg-sound-silence", name: "Silence · 효과음 · EasyRPG", sourcePath: "Sound/Silence.wav", path: "assets/easyrpg/sound/Silence.wav", fileName: "Silence.wav" },
  { category: "sound", id: "easyrpg-sound-sleep", name: "Sleep · 효과음 · EasyRPG", sourcePath: "Sound/Sleep.wav", path: "assets/easyrpg/sound/Sleep.wav", fileName: "Sleep.wav" },
  { category: "sound", id: "easyrpg-sound-song", name: "Song · 효과음 · EasyRPG", sourcePath: "Sound/Song.wav", path: "assets/easyrpg/sound/Song.wav", fileName: "Song.wav" },
  { category: "sound", id: "easyrpg-sound-teleport2", name: "Teleport2 · 효과음 · EasyRPG", sourcePath: "Sound/Teleport2.wav", path: "assets/easyrpg/sound/Teleport2.wav", fileName: "Teleport2.wav" },
  { category: "sound", id: "easyrpg-sound-wave1", name: "Wave1 · 효과음 · EasyRPG", sourcePath: "Sound/Wave1.wav", path: "assets/easyrpg/sound/Wave1.wav", fileName: "Wave1.wav" },
  { category: "sound", id: "easyrpg-sound-wave2", name: "Wave2 · 효과음 · EasyRPG", sourcePath: "Sound/Wave2.wav", path: "assets/easyrpg/sound/Wave2.wav", fileName: "Wave2.wav" },
  { category: "sound", id: "easyrpg-sound-wind8", name: "Wind8 · 효과음 · EasyRPG", sourcePath: "Sound/Wind8.wav", path: "assets/easyrpg/sound/Wind8.wav", fileName: "Wind8.wav" },
  { category: "system", id: "easyrpg-system-royal", name: "Royal · 시스템 그림 · EasyRPG", sourcePath: "System/Royal.png", path: "assets/easyrpg/system/Royal.png", fileName: "Royal.png" },
  { category: "system", id: "easyrpg-system-system", name: "System · 시스템 그림 · EasyRPG", sourcePath: "System/System.png", path: "assets/easyrpg/system/System.png", fileName: "System.png" },
  { category: "system", id: "easyrpg-system-system-a", name: "SystemA · 시스템 그림 · EasyRPG", sourcePath: "System/SystemA.png", path: "assets/easyrpg/system/SystemA.png", fileName: "SystemA.png" },
  { category: "system", id: "easyrpg-system-system-b", name: "SystemB · 시스템 그림 · EasyRPG", sourcePath: "System/SystemB.png", path: "assets/easyrpg/system/SystemB.png", fileName: "SystemB.png" },
  { category: "system", id: "easyrpg-system-system-c", name: "SystemC · 시스템 그림 · EasyRPG", sourcePath: "System/SystemC.png", path: "assets/easyrpg/system/SystemC.png", fileName: "SystemC.png" },
  { category: "system2", id: "easyrpg-system2-system2-a", name: "System2A · 시스템 그림 2 · EasyRPG", sourcePath: "System2/System2A.png", path: "assets/easyrpg/system2/System2A.png", fileName: "System2A.png" },
  { category: "system2", id: "easyrpg-system2-system2-b", name: "System2B · 시스템 그림 2 · EasyRPG", sourcePath: "System2/System2B.png", path: "assets/easyrpg/system2/System2B.png", fileName: "System2B.png" },
  { category: "system2", id: "easyrpg-system2-system2-c", name: "System2C · 시스템 그림 2 · EasyRPG", sourcePath: "System2/System2C.png", path: "assets/easyrpg/system2/System2C.png", fileName: "System2C.png" },
  { category: "title", id: "easyrpg-title-title1", name: "Title1 · 타이틀 화면 · EasyRPG", sourcePath: "Title/Title1.png", path: "assets/easyrpg/title/Title1.png", fileName: "Title1.png" },
  { category: "title", id: "easyrpg-title-title2", name: "Title2 · 타이틀 화면 · EasyRPG", sourcePath: "Title/Title2.png", path: "assets/easyrpg/title/Title2.png", fileName: "Title2.png" },
  { category: "title", id: "easyrpg-title-title3", name: "Title3 · 타이틀 화면 · EasyRPG", sourcePath: "Title/Title3.png", path: "assets/easyrpg/title/Title3.png", fileName: "Title3.png" },
  { category: "title", id: "easyrpg-title-title4", name: "Title4 · 타이틀 화면 · EasyRPG", sourcePath: "Title/Title4.png", path: "assets/easyrpg/title/Title4.png", fileName: "Title4.png" },
] as const satisfies readonly EasyRpgRtpAsset[];

export const EASYRPG_BACKDROP_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "backdrop");
export const EASYRPG_BATTLE_ASSETS: readonly EasyRpgRtpAsset[] = [];
export const EASYRPG_BATTLE_WEAPON_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "battleWeapon");
export const EASYRPG_CHIPSET_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "chipset");
// 분할 전 얼굴 시트 5장. 새 작업은 FACESET_FACE_ASSETS(낱장)를 쓴다 — 이 목록은
// 이미 이 id 를 저장한 프로젝트가 여전히 역직렬화되게 하기 위해 둔다.
export const LEGACY_FACESET_SHEET_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "faceset");
export const EASYRPG_GAME_OVER_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "gameOver");
export const EASYRPG_MONSTER_ASSETS: readonly EasyRpgRtpAsset[] = [];
export const EASYRPG_MUSIC_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "music");
export const EASYRPG_PICTURE_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "picture");
export const EASYRPG_SOUND_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "sound");
export const EASYRPG_SYSTEM_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "system");
export const EASYRPG_SYSTEM2_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "system2");
export const EASYRPG_TITLE_ASSETS = EASYRPG_RTP_ASSETS.filter((asset) => asset.category === "title");
export const EASYRPG_CHARSET_ASSETS = [
  { category: "charset", id: "easyrpg-charset-actor1", name: "Actor1 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Actor1.png", path: "assets/easyrpg/charset/Actor1.png", fileName: "Actor1.png", textureKey: "tex_easyrpg_charset_actor1", group: "Actor" },
  { category: "charset", id: "easyrpg-charset-actor2", name: "Actor2 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Actor2.png", path: "assets/easyrpg/charset/Actor2.png", fileName: "Actor2.png", textureKey: "tex_easyrpg_charset_actor2", group: "Actor" },
  { category: "charset", id: "easyrpg-charset-actor3", name: "Actor3 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Actor3.png", path: "assets/easyrpg/charset/Actor3.png", fileName: "Actor3.png", textureKey: "tex_easyrpg_charset_actor3", group: "Actor" },
  { category: "charset", id: "easyrpg-charset-actor4", name: "Actor4 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Actor4.png", path: "assets/easyrpg/charset/Actor4.png", fileName: "Actor4.png", textureKey: "tex_easyrpg_charset_actor4", group: "Actor" },
  { category: "charset", id: "easyrpg-charset-animal", name: "Animal · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Animal.png", path: "assets/easyrpg/charset/Animal.png", fileName: "Animal.png", textureKey: "tex_easyrpg_charset_animal", group: "Animal" },
  { category: "charset", id: "easyrpg-charset-monster1", name: "Monster1 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Monster1.png", path: "assets/easyrpg/charset/Monster1.png", fileName: "Monster1.png", textureKey: "tex_easyrpg_charset_monster1", group: "Monster" },
  { category: "charset", id: "easyrpg-charset-monster2", name: "Monster2 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Monster2.png", path: "assets/easyrpg/charset/Monster2.png", fileName: "Monster2.png", textureKey: "tex_easyrpg_charset_monster2", group: "Monster" },
  { category: "charset", id: "easyrpg-charset-monster3", name: "Monster3 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Monster3.png", path: "assets/easyrpg/charset/Monster3.png", fileName: "Monster3.png", textureKey: "tex_easyrpg_charset_monster3", group: "Monster" },
  { category: "charset", id: "easyrpg-charset-object1", name: "Object1 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Object1.png", path: "assets/easyrpg/charset/Object1.png", fileName: "Object1.png", textureKey: "tex_easyrpg_charset_object1", group: "Object" },
  { category: "charset", id: "easyrpg-charset-object2", name: "Object2 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Object2.png", path: "assets/easyrpg/charset/Object2.png", fileName: "Object2.png", textureKey: "tex_easyrpg_charset_object2", group: "Object" },
  { category: "charset", id: "easyrpg-charset-people1", name: "People1 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/People1.png", path: "assets/easyrpg/charset/People1.png", fileName: "People1.png", textureKey: "tex_easyrpg_charset_people1", group: "People" },
  { category: "charset", id: "easyrpg-charset-people2", name: "People2 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/People2.png", path: "assets/easyrpg/charset/People2.png", fileName: "People2.png", textureKey: "tex_easyrpg_charset_people2", group: "People" },
  { category: "charset", id: "easyrpg-charset-people3", name: "People3 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/People3.png", path: "assets/easyrpg/charset/People3.png", fileName: "People3.png", textureKey: "tex_easyrpg_charset_people3", group: "People" },
  { category: "charset", id: "easyrpg-charset-people4", name: "People4 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/People4.png", path: "assets/easyrpg/charset/People4.png", fileName: "People4.png", textureKey: "tex_easyrpg_charset_people4", group: "People" },
  { category: "charset", id: "easyrpg-charset-people5", name: "People5 · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/People5.png", path: "assets/easyrpg/charset/People5.png", fileName: "People5.png", textureKey: "tex_easyrpg_charset_people5", group: "People" },
  { category: "charset", id: "easyrpg-charset-template", name: "Template · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Template.png", path: "assets/easyrpg/charset/Template.png", fileName: "Template.png", textureKey: "tex_easyrpg_charset_template", group: "Template" },
  { category: "charset", id: "easyrpg-charset-vehicles", name: "Vehicles · 캐릭터 그림 · EasyRPG", sourcePath: "CharSet/Vehicles.png", path: "assets/easyrpg/charset/Vehicles.png", fileName: "Vehicles.png", textureKey: "tex_easyrpg_charset_vehicles", group: "Vehicles" },
] as const satisfies readonly EasyRpgCharsetAsset[];

export const EASYRPG_RTP_CATEGORY_SLICING = {
  backdrop: RESOURCE_SLICING.backdrop,
  battle: RESOURCE_SLICING.battle,
  battleWeapon: RESOURCE_SLICING.battleWeapon,
  charset: RESOURCE_SLICING.charset,
  chipset: RESOURCE_SLICING.chipset,
  faceset: RESOURCE_SLICING.faceset,
  gameOver: RESOURCE_SLICING.gameOver,
  monster: RESOURCE_SLICING.monster,
  music: RESOURCE_SLICING.music,
  picture: RESOURCE_SLICING.picture,
  sound: RESOURCE_SLICING.sound,
  system: RESOURCE_SLICING.system,
  system2: RESOURCE_SLICING.system2,
  title: RESOURCE_SLICING.title,
} as const satisfies Record<EasyRpgRtpCategory, ResourceSlicingSpec>;

export const CHIPSET_SLICING = RESOURCE_SLICING.chipset;
export const FACESET_SLICING = RESOURCE_SLICING.faceset;
export const CHARSET_SLICING = RESOURCE_SLICING.charset;

export const FACESET_FACE_WIDTH = FACE_IMAGE_SIZE;
export const FACESET_FACE_HEIGHT = FACE_IMAGE_SIZE;

export const CHARSET_FRAME_WIDTH = CHARSET_SLICING.cellWidth;
export const CHARSET_FRAME_HEIGHT = CHARSET_SLICING.cellHeight;
export const CHARSET_SHEET_COLUMNS = CHARSET_SLICING.columns;
export const CHARSET_SHEET_ROWS = CHARSET_SLICING.rows;
export const CHARSET_CHARACTER_COLUMNS = 3;
export const CHARSET_CHARACTER_ROWS = 4;
export const CHARSET_CHARACTERS_PER_ROW = 4;
export const CHARSET_CHARACTER_COUNT = 8;
export const CHARSET_FRAME_COUNT = CHARSET_SHEET_COLUMNS * CHARSET_SHEET_ROWS;
export const CHARSET_DIRECTIONS = ["up", "right", "down", "left"] as const satisfies readonly CharsetDirection[];

export type CharsetFrameSelection = {
  readonly characterIndex: number;
  readonly direction: CharsetDirection;
  readonly pattern: number;
};

export type CharsetFrameSource = {
  readonly x: number;
  readonly y: number;
  readonly width: number;
  readonly height: number;
};

export function charsetFrameIndex(selection: CharsetFrameSelection): number {
  const characterIndex = boundedInt(selection.characterIndex, 0, CHARSET_CHARACTER_COUNT - 1);
  const pattern = boundedInt(selection.pattern, 0, CHARSET_CHARACTER_COLUMNS - 1);
  const directionRow = CHARSET_DIRECTIONS.indexOf(selection.direction);
  const characterColumn = characterIndex % CHARSET_CHARACTERS_PER_ROW;
  const characterRow = Math.floor(characterIndex / CHARSET_CHARACTERS_PER_ROW);
  const column = characterColumn * CHARSET_CHARACTER_COLUMNS + pattern;
  const row = characterRow * CHARSET_CHARACTER_ROWS + Math.max(directionRow, 0);
  return row * CHARSET_SHEET_COLUMNS + column;
}

export function decodeCharsetFrameIndex(frameIndex: number): CharsetFrameSelection {
  const normalized = boundedInt(frameIndex, 0, CHARSET_FRAME_COUNT - 1);
  const column = normalized % CHARSET_SHEET_COLUMNS;
  const row = Math.floor(normalized / CHARSET_SHEET_COLUMNS);
  const characterColumn = Math.floor(column / CHARSET_CHARACTER_COLUMNS);
  const characterRow = Math.floor(row / CHARSET_CHARACTER_ROWS);
  const direction = CHARSET_DIRECTIONS[row % CHARSET_CHARACTER_ROWS] ?? "down";
  return {
    characterIndex: characterRow * CHARSET_CHARACTERS_PER_ROW + characterColumn,
    direction,
    pattern: column % CHARSET_CHARACTER_COLUMNS,
  };
}

export function charsetFrameSource(selection: CharsetFrameSelection): CharsetFrameSource {
  const frameIndex = charsetFrameIndex(selection);
  const column = frameIndex % CHARSET_SHEET_COLUMNS;
  const row = Math.floor(frameIndex / CHARSET_SHEET_COLUMNS);
  return {
    x: column * CHARSET_FRAME_WIDTH,
    y: row * CHARSET_FRAME_HEIGHT,
    width: CHARSET_FRAME_WIDTH,
    height: CHARSET_FRAME_HEIGHT,
  };
}

function boundedInt(value: number, min: number, max: number): number {
  if (!Number.isFinite(value)) return min;
  return Math.min(max, Math.max(min, Math.trunc(value)));
}
