// Generated by scripts/slice-faceset-sheets.mjs. Do not edit by hand.
// 얼굴 한 칸 = 파일 한 장. 시트를 물리 분할한 결과물 목록이다.
// 다시 만들기: node scripts/slice-faceset-sheets.mjs   검사: node scripts/slice-faceset-sheets.mjs --verify

export type FacesetFaceAsset = {
  readonly id: string;
  readonly name: string;
  /** public/ 아래 경로. 런타임 URL 은 `/${path}` 다(EASYRPG_RTP_ASSETS 와 같은 규약). */
  readonly path: string;
  /** 이 얼굴이 잘려 나온 레거시 시트의 리소스 id. */
  readonly sheetResourceId: string;
  /** 레거시 시트에서의 칸 번호(0..15). 마이그레이션 대조용으로만 남긴다. */
  readonly sheetIndex: number;
};

export const FACE_CELL_COUNT = 16;

/** 분할 전 시트 리소스 id. 저장된 프로젝트가 이 id 를 들고 있어 등록 자체는 유지한다. */
export const LEGACY_FACESET_SHEET_IDS: readonly string[] = [
  "easyrpg-faceset-actor1",
  "easyrpg-faceset-actor2",
  "easyrpg-faceset-monster",
  "easyrpg-faceset-people1",
  "easyrpg-faceset-people2",
  "generated-actor-hero-01-face",
  "generated-actor-hero-02-face",
];

export const FACESET_FACE_ASSETS: readonly FacesetFaceAsset[] = [
  { id: "easyrpg-faceset-actor1-00", name: "Actor1 얼굴 1 · EasyRPG", path: "assets/easyrpg/faceset/Actor1/00.png", sheetResourceId: "easyrpg-faceset-actor1", sheetIndex: 0 },
  { id: "easyrpg-faceset-actor1-01", name: "Actor1 얼굴 2 · EasyRPG", path: "assets/easyrpg/faceset/Actor1/01.png", sheetResourceId: "easyrpg-faceset-actor1", sheetIndex: 1 },
  { id: "easyrpg-faceset-actor1-02", name: "Actor1 얼굴 3 · EasyRPG", path: "assets/easyrpg/faceset/Actor1/02.png", sheetResourceId: "easyrpg-faceset-actor1", sheetIndex: 2 },
  { id: "easyrpg-faceset-actor1-03", name: "Actor1 얼굴 4 · EasyRPG", path: "assets/easyrpg/faceset/Actor1/03.png", sheetResourceId: "easyrpg-faceset-actor1", sheetIndex: 3 },
  { id: "easyrpg-faceset-actor1-04", name: "Actor1 얼굴 5 · EasyRPG", path: "assets/easyrpg/faceset/Actor1/04.png", sheetResourceId: "easyrpg-faceset-actor1", sheetIndex: 4 },
  { id: "easyrpg-faceset-actor1-05", name: "Actor1 얼굴 6 · EasyRPG", path: "assets/easyrpg/faceset/Actor1/05.png", sheetResourceId: "easyrpg-faceset-actor1", sheetIndex: 5 },
  { id: "easyrpg-faceset-actor1-06", name: "Actor1 얼굴 7 · EasyRPG", path: "assets/easyrpg/faceset/Actor1/06.png", sheetResourceId: "easyrpg-faceset-actor1", sheetIndex: 6 },
  { id: "easyrpg-faceset-actor1-07", name: "Actor1 얼굴 8 · EasyRPG", path: "assets/easyrpg/faceset/Actor1/07.png", sheetResourceId: "easyrpg-faceset-actor1", sheetIndex: 7 },
  { id: "easyrpg-faceset-actor1-08", name: "Actor1 얼굴 9 · EasyRPG", path: "assets/easyrpg/faceset/Actor1/08.png", sheetResourceId: "easyrpg-faceset-actor1", sheetIndex: 8 },
  { id: "easyrpg-faceset-actor1-09", name: "Actor1 얼굴 10 · EasyRPG", path: "assets/easyrpg/faceset/Actor1/09.png", sheetResourceId: "easyrpg-faceset-actor1", sheetIndex: 9 },
  { id: "easyrpg-faceset-actor1-10", name: "Actor1 얼굴 11 · EasyRPG", path: "assets/easyrpg/faceset/Actor1/10.png", sheetResourceId: "easyrpg-faceset-actor1", sheetIndex: 10 },
  { id: "easyrpg-faceset-actor1-11", name: "Actor1 얼굴 12 · EasyRPG", path: "assets/easyrpg/faceset/Actor1/11.png", sheetResourceId: "easyrpg-faceset-actor1", sheetIndex: 11 },
  { id: "easyrpg-faceset-actor1-12", name: "Actor1 얼굴 13 · EasyRPG", path: "assets/easyrpg/faceset/Actor1/12.png", sheetResourceId: "easyrpg-faceset-actor1", sheetIndex: 12 },
  { id: "easyrpg-faceset-actor1-13", name: "Actor1 얼굴 14 · EasyRPG", path: "assets/easyrpg/faceset/Actor1/13.png", sheetResourceId: "easyrpg-faceset-actor1", sheetIndex: 13 },
  { id: "easyrpg-faceset-actor1-14", name: "Actor1 얼굴 15 · EasyRPG", path: "assets/easyrpg/faceset/Actor1/14.png", sheetResourceId: "easyrpg-faceset-actor1", sheetIndex: 14 },
  { id: "easyrpg-faceset-actor1-15", name: "Actor1 얼굴 16 · EasyRPG", path: "assets/easyrpg/faceset/Actor1/15.png", sheetResourceId: "easyrpg-faceset-actor1", sheetIndex: 15 },
  { id: "easyrpg-faceset-actor2-00", name: "Actor2 얼굴 1 · EasyRPG", path: "assets/easyrpg/faceset/Actor2/00.png", sheetResourceId: "easyrpg-faceset-actor2", sheetIndex: 0 },
  { id: "easyrpg-faceset-actor2-01", name: "Actor2 얼굴 2 · EasyRPG", path: "assets/easyrpg/faceset/Actor2/01.png", sheetResourceId: "easyrpg-faceset-actor2", sheetIndex: 1 },
  { id: "easyrpg-faceset-actor2-02", name: "Actor2 얼굴 3 · EasyRPG", path: "assets/easyrpg/faceset/Actor2/02.png", sheetResourceId: "easyrpg-faceset-actor2", sheetIndex: 2 },
  { id: "easyrpg-faceset-actor2-03", name: "Actor2 얼굴 4 · EasyRPG", path: "assets/easyrpg/faceset/Actor2/03.png", sheetResourceId: "easyrpg-faceset-actor2", sheetIndex: 3 },
  { id: "easyrpg-faceset-actor2-04", name: "Actor2 얼굴 5 · EasyRPG", path: "assets/easyrpg/faceset/Actor2/04.png", sheetResourceId: "easyrpg-faceset-actor2", sheetIndex: 4 },
  { id: "easyrpg-faceset-actor2-05", name: "Actor2 얼굴 6 · EasyRPG", path: "assets/easyrpg/faceset/Actor2/05.png", sheetResourceId: "easyrpg-faceset-actor2", sheetIndex: 5 },
  { id: "easyrpg-faceset-actor2-06", name: "Actor2 얼굴 7 · EasyRPG", path: "assets/easyrpg/faceset/Actor2/06.png", sheetResourceId: "easyrpg-faceset-actor2", sheetIndex: 6 },
  { id: "easyrpg-faceset-actor2-07", name: "Actor2 얼굴 8 · EasyRPG", path: "assets/easyrpg/faceset/Actor2/07.png", sheetResourceId: "easyrpg-faceset-actor2", sheetIndex: 7 },
  { id: "easyrpg-faceset-actor2-08", name: "Actor2 얼굴 9 · EasyRPG", path: "assets/easyrpg/faceset/Actor2/08.png", sheetResourceId: "easyrpg-faceset-actor2", sheetIndex: 8 },
  { id: "easyrpg-faceset-actor2-09", name: "Actor2 얼굴 10 · EasyRPG", path: "assets/easyrpg/faceset/Actor2/09.png", sheetResourceId: "easyrpg-faceset-actor2", sheetIndex: 9 },
  { id: "easyrpg-faceset-actor2-10", name: "Actor2 얼굴 11 · EasyRPG", path: "assets/easyrpg/faceset/Actor2/10.png", sheetResourceId: "easyrpg-faceset-actor2", sheetIndex: 10 },
  { id: "easyrpg-faceset-actor2-11", name: "Actor2 얼굴 12 · EasyRPG", path: "assets/easyrpg/faceset/Actor2/11.png", sheetResourceId: "easyrpg-faceset-actor2", sheetIndex: 11 },
  { id: "easyrpg-faceset-actor2-12", name: "Actor2 얼굴 13 · EasyRPG", path: "assets/easyrpg/faceset/Actor2/12.png", sheetResourceId: "easyrpg-faceset-actor2", sheetIndex: 12 },
  { id: "easyrpg-faceset-actor2-13", name: "Actor2 얼굴 14 · EasyRPG", path: "assets/easyrpg/faceset/Actor2/13.png", sheetResourceId: "easyrpg-faceset-actor2", sheetIndex: 13 },
  { id: "easyrpg-faceset-actor2-14", name: "Actor2 얼굴 15 · EasyRPG", path: "assets/easyrpg/faceset/Actor2/14.png", sheetResourceId: "easyrpg-faceset-actor2", sheetIndex: 14 },
  { id: "easyrpg-faceset-actor2-15", name: "Actor2 얼굴 16 · EasyRPG", path: "assets/easyrpg/faceset/Actor2/15.png", sheetResourceId: "easyrpg-faceset-actor2", sheetIndex: 15 },
  { id: "easyrpg-faceset-monster-00", name: "Monster 얼굴 1 · EasyRPG", path: "assets/easyrpg/faceset/Monster/00.png", sheetResourceId: "easyrpg-faceset-monster", sheetIndex: 0 },
  { id: "easyrpg-faceset-monster-01", name: "Monster 얼굴 2 · EasyRPG", path: "assets/easyrpg/faceset/Monster/01.png", sheetResourceId: "easyrpg-faceset-monster", sheetIndex: 1 },
  { id: "easyrpg-faceset-monster-02", name: "Monster 얼굴 3 · EasyRPG", path: "assets/easyrpg/faceset/Monster/02.png", sheetResourceId: "easyrpg-faceset-monster", sheetIndex: 2 },
  { id: "easyrpg-faceset-monster-03", name: "Monster 얼굴 4 · EasyRPG", path: "assets/easyrpg/faceset/Monster/03.png", sheetResourceId: "easyrpg-faceset-monster", sheetIndex: 3 },
  { id: "easyrpg-faceset-monster-04", name: "Monster 얼굴 5 · EasyRPG", path: "assets/easyrpg/faceset/Monster/04.png", sheetResourceId: "easyrpg-faceset-monster", sheetIndex: 4 },
  { id: "easyrpg-faceset-monster-05", name: "Monster 얼굴 6 · EasyRPG", path: "assets/easyrpg/faceset/Monster/05.png", sheetResourceId: "easyrpg-faceset-monster", sheetIndex: 5 },
  { id: "easyrpg-faceset-monster-06", name: "Monster 얼굴 7 · EasyRPG", path: "assets/easyrpg/faceset/Monster/06.png", sheetResourceId: "easyrpg-faceset-monster", sheetIndex: 6 },
  { id: "easyrpg-faceset-monster-07", name: "Monster 얼굴 8 · EasyRPG", path: "assets/easyrpg/faceset/Monster/07.png", sheetResourceId: "easyrpg-faceset-monster", sheetIndex: 7 },
  { id: "easyrpg-faceset-monster-08", name: "Monster 얼굴 9 · EasyRPG", path: "assets/easyrpg/faceset/Monster/08.png", sheetResourceId: "easyrpg-faceset-monster", sheetIndex: 8 },
  { id: "easyrpg-faceset-monster-09", name: "Monster 얼굴 10 · EasyRPG", path: "assets/easyrpg/faceset/Monster/09.png", sheetResourceId: "easyrpg-faceset-monster", sheetIndex: 9 },
  { id: "easyrpg-faceset-monster-10", name: "Monster 얼굴 11 · EasyRPG", path: "assets/easyrpg/faceset/Monster/10.png", sheetResourceId: "easyrpg-faceset-monster", sheetIndex: 10 },
  { id: "easyrpg-faceset-monster-11", name: "Monster 얼굴 12 · EasyRPG", path: "assets/easyrpg/faceset/Monster/11.png", sheetResourceId: "easyrpg-faceset-monster", sheetIndex: 11 },
  { id: "easyrpg-faceset-monster-12", name: "Monster 얼굴 13 · EasyRPG", path: "assets/easyrpg/faceset/Monster/12.png", sheetResourceId: "easyrpg-faceset-monster", sheetIndex: 12 },
  { id: "easyrpg-faceset-monster-13", name: "Monster 얼굴 14 · EasyRPG", path: "assets/easyrpg/faceset/Monster/13.png", sheetResourceId: "easyrpg-faceset-monster", sheetIndex: 13 },
  { id: "easyrpg-faceset-monster-14", name: "Monster 얼굴 15 · EasyRPG", path: "assets/easyrpg/faceset/Monster/14.png", sheetResourceId: "easyrpg-faceset-monster", sheetIndex: 14 },
  { id: "easyrpg-faceset-monster-15", name: "Monster 얼굴 16 · EasyRPG", path: "assets/easyrpg/faceset/Monster/15.png", sheetResourceId: "easyrpg-faceset-monster", sheetIndex: 15 },
  { id: "easyrpg-faceset-people1-00", name: "People1 얼굴 1 · EasyRPG", path: "assets/easyrpg/faceset/People1/00.png", sheetResourceId: "easyrpg-faceset-people1", sheetIndex: 0 },
  { id: "easyrpg-faceset-people1-01", name: "People1 얼굴 2 · EasyRPG", path: "assets/easyrpg/faceset/People1/01.png", sheetResourceId: "easyrpg-faceset-people1", sheetIndex: 1 },
  { id: "easyrpg-faceset-people1-02", name: "People1 얼굴 3 · EasyRPG", path: "assets/easyrpg/faceset/People1/02.png", sheetResourceId: "easyrpg-faceset-people1", sheetIndex: 2 },
  { id: "easyrpg-faceset-people1-03", name: "People1 얼굴 4 · EasyRPG", path: "assets/easyrpg/faceset/People1/03.png", sheetResourceId: "easyrpg-faceset-people1", sheetIndex: 3 },
  { id: "easyrpg-faceset-people1-04", name: "People1 얼굴 5 · EasyRPG", path: "assets/easyrpg/faceset/People1/04.png", sheetResourceId: "easyrpg-faceset-people1", sheetIndex: 4 },
  { id: "easyrpg-faceset-people1-05", name: "People1 얼굴 6 · EasyRPG", path: "assets/easyrpg/faceset/People1/05.png", sheetResourceId: "easyrpg-faceset-people1", sheetIndex: 5 },
  { id: "easyrpg-faceset-people1-06", name: "People1 얼굴 7 · EasyRPG", path: "assets/easyrpg/faceset/People1/06.png", sheetResourceId: "easyrpg-faceset-people1", sheetIndex: 6 },
  { id: "easyrpg-faceset-people1-07", name: "People1 얼굴 8 · EasyRPG", path: "assets/easyrpg/faceset/People1/07.png", sheetResourceId: "easyrpg-faceset-people1", sheetIndex: 7 },
  { id: "easyrpg-faceset-people1-08", name: "People1 얼굴 9 · EasyRPG", path: "assets/easyrpg/faceset/People1/08.png", sheetResourceId: "easyrpg-faceset-people1", sheetIndex: 8 },
  { id: "easyrpg-faceset-people1-09", name: "People1 얼굴 10 · EasyRPG", path: "assets/easyrpg/faceset/People1/09.png", sheetResourceId: "easyrpg-faceset-people1", sheetIndex: 9 },
  { id: "easyrpg-faceset-people1-10", name: "People1 얼굴 11 · EasyRPG", path: "assets/easyrpg/faceset/People1/10.png", sheetResourceId: "easyrpg-faceset-people1", sheetIndex: 10 },
  { id: "easyrpg-faceset-people1-11", name: "People1 얼굴 12 · EasyRPG", path: "assets/easyrpg/faceset/People1/11.png", sheetResourceId: "easyrpg-faceset-people1", sheetIndex: 11 },
  { id: "easyrpg-faceset-people1-12", name: "People1 얼굴 13 · EasyRPG", path: "assets/easyrpg/faceset/People1/12.png", sheetResourceId: "easyrpg-faceset-people1", sheetIndex: 12 },
  { id: "easyrpg-faceset-people1-13", name: "People1 얼굴 14 · EasyRPG", path: "assets/easyrpg/faceset/People1/13.png", sheetResourceId: "easyrpg-faceset-people1", sheetIndex: 13 },
  { id: "easyrpg-faceset-people1-14", name: "People1 얼굴 15 · EasyRPG", path: "assets/easyrpg/faceset/People1/14.png", sheetResourceId: "easyrpg-faceset-people1", sheetIndex: 14 },
  { id: "easyrpg-faceset-people1-15", name: "People1 얼굴 16 · EasyRPG", path: "assets/easyrpg/faceset/People1/15.png", sheetResourceId: "easyrpg-faceset-people1", sheetIndex: 15 },
  { id: "easyrpg-faceset-people2-00", name: "People2 얼굴 1 · EasyRPG", path: "assets/easyrpg/faceset/People2/00.png", sheetResourceId: "easyrpg-faceset-people2", sheetIndex: 0 },
  { id: "easyrpg-faceset-people2-01", name: "People2 얼굴 2 · EasyRPG", path: "assets/easyrpg/faceset/People2/01.png", sheetResourceId: "easyrpg-faceset-people2", sheetIndex: 1 },
  { id: "easyrpg-faceset-people2-02", name: "People2 얼굴 3 · EasyRPG", path: "assets/easyrpg/faceset/People2/02.png", sheetResourceId: "easyrpg-faceset-people2", sheetIndex: 2 },
  { id: "easyrpg-faceset-people2-03", name: "People2 얼굴 4 · EasyRPG", path: "assets/easyrpg/faceset/People2/03.png", sheetResourceId: "easyrpg-faceset-people2", sheetIndex: 3 },
  { id: "easyrpg-faceset-people2-04", name: "People2 얼굴 5 · EasyRPG", path: "assets/easyrpg/faceset/People2/04.png", sheetResourceId: "easyrpg-faceset-people2", sheetIndex: 4 },
  { id: "easyrpg-faceset-people2-05", name: "People2 얼굴 6 · EasyRPG", path: "assets/easyrpg/faceset/People2/05.png", sheetResourceId: "easyrpg-faceset-people2", sheetIndex: 5 },
  { id: "easyrpg-faceset-people2-06", name: "People2 얼굴 7 · EasyRPG", path: "assets/easyrpg/faceset/People2/06.png", sheetResourceId: "easyrpg-faceset-people2", sheetIndex: 6 },
  { id: "easyrpg-faceset-people2-07", name: "People2 얼굴 8 · EasyRPG", path: "assets/easyrpg/faceset/People2/07.png", sheetResourceId: "easyrpg-faceset-people2", sheetIndex: 7 },
  { id: "easyrpg-faceset-people2-08", name: "People2 얼굴 9 · EasyRPG", path: "assets/easyrpg/faceset/People2/08.png", sheetResourceId: "easyrpg-faceset-people2", sheetIndex: 8 },
  { id: "easyrpg-faceset-people2-09", name: "People2 얼굴 10 · EasyRPG", path: "assets/easyrpg/faceset/People2/09.png", sheetResourceId: "easyrpg-faceset-people2", sheetIndex: 9 },
  { id: "easyrpg-faceset-people2-10", name: "People2 얼굴 11 · EasyRPG", path: "assets/easyrpg/faceset/People2/10.png", sheetResourceId: "easyrpg-faceset-people2", sheetIndex: 10 },
  { id: "easyrpg-faceset-people2-11", name: "People2 얼굴 12 · EasyRPG", path: "assets/easyrpg/faceset/People2/11.png", sheetResourceId: "easyrpg-faceset-people2", sheetIndex: 11 },
  { id: "easyrpg-faceset-people2-12", name: "People2 얼굴 13 · EasyRPG", path: "assets/easyrpg/faceset/People2/12.png", sheetResourceId: "easyrpg-faceset-people2", sheetIndex: 12 },
  { id: "easyrpg-faceset-people2-13", name: "People2 얼굴 14 · EasyRPG", path: "assets/easyrpg/faceset/People2/13.png", sheetResourceId: "easyrpg-faceset-people2", sheetIndex: 13 },
  { id: "easyrpg-faceset-people2-14", name: "People2 얼굴 15 · EasyRPG", path: "assets/easyrpg/faceset/People2/14.png", sheetResourceId: "easyrpg-faceset-people2", sheetIndex: 14 },
  { id: "easyrpg-faceset-people2-15", name: "People2 얼굴 16 · EasyRPG", path: "assets/easyrpg/faceset/People2/15.png", sheetResourceId: "easyrpg-faceset-people2", sheetIndex: 15 },
  { id: "generated-actor-hero-01-face-00", name: "hero-01-face 얼굴 1", path: "assets/generated/starter/hero-01-face/00.png", sheetResourceId: "generated-actor-hero-01-face", sheetIndex: 0 },
  { id: "generated-actor-hero-01-face-01", name: "hero-01-face 얼굴 2", path: "assets/generated/starter/hero-01-face/01.png", sheetResourceId: "generated-actor-hero-01-face", sheetIndex: 1 },
  { id: "generated-actor-hero-01-face-02", name: "hero-01-face 얼굴 3", path: "assets/generated/starter/hero-01-face/02.png", sheetResourceId: "generated-actor-hero-01-face", sheetIndex: 2 },
  { id: "generated-actor-hero-01-face-03", name: "hero-01-face 얼굴 4", path: "assets/generated/starter/hero-01-face/03.png", sheetResourceId: "generated-actor-hero-01-face", sheetIndex: 3 },
  { id: "generated-actor-hero-01-face-04", name: "hero-01-face 얼굴 5", path: "assets/generated/starter/hero-01-face/04.png", sheetResourceId: "generated-actor-hero-01-face", sheetIndex: 4 },
  { id: "generated-actor-hero-01-face-05", name: "hero-01-face 얼굴 6", path: "assets/generated/starter/hero-01-face/05.png", sheetResourceId: "generated-actor-hero-01-face", sheetIndex: 5 },
  { id: "generated-actor-hero-01-face-06", name: "hero-01-face 얼굴 7", path: "assets/generated/starter/hero-01-face/06.png", sheetResourceId: "generated-actor-hero-01-face", sheetIndex: 6 },
  { id: "generated-actor-hero-01-face-07", name: "hero-01-face 얼굴 8", path: "assets/generated/starter/hero-01-face/07.png", sheetResourceId: "generated-actor-hero-01-face", sheetIndex: 7 },
  { id: "generated-actor-hero-01-face-08", name: "hero-01-face 얼굴 9", path: "assets/generated/starter/hero-01-face/08.png", sheetResourceId: "generated-actor-hero-01-face", sheetIndex: 8 },
  { id: "generated-actor-hero-01-face-09", name: "hero-01-face 얼굴 10", path: "assets/generated/starter/hero-01-face/09.png", sheetResourceId: "generated-actor-hero-01-face", sheetIndex: 9 },
  { id: "generated-actor-hero-01-face-10", name: "hero-01-face 얼굴 11", path: "assets/generated/starter/hero-01-face/10.png", sheetResourceId: "generated-actor-hero-01-face", sheetIndex: 10 },
  { id: "generated-actor-hero-01-face-11", name: "hero-01-face 얼굴 12", path: "assets/generated/starter/hero-01-face/11.png", sheetResourceId: "generated-actor-hero-01-face", sheetIndex: 11 },
  { id: "generated-actor-hero-01-face-12", name: "hero-01-face 얼굴 13", path: "assets/generated/starter/hero-01-face/12.png", sheetResourceId: "generated-actor-hero-01-face", sheetIndex: 12 },
  { id: "generated-actor-hero-01-face-13", name: "hero-01-face 얼굴 14", path: "assets/generated/starter/hero-01-face/13.png", sheetResourceId: "generated-actor-hero-01-face", sheetIndex: 13 },
  { id: "generated-actor-hero-01-face-14", name: "hero-01-face 얼굴 15", path: "assets/generated/starter/hero-01-face/14.png", sheetResourceId: "generated-actor-hero-01-face", sheetIndex: 14 },
  { id: "generated-actor-hero-01-face-15", name: "hero-01-face 얼굴 16", path: "assets/generated/starter/hero-01-face/15.png", sheetResourceId: "generated-actor-hero-01-face", sheetIndex: 15 },
  { id: "generated-actor-hero-02-face-00", name: "hero-02-face 얼굴 1", path: "assets/generated/starter/hero-02-face/00.png", sheetResourceId: "generated-actor-hero-02-face", sheetIndex: 0 },
  { id: "generated-actor-hero-02-face-01", name: "hero-02-face 얼굴 2", path: "assets/generated/starter/hero-02-face/01.png", sheetResourceId: "generated-actor-hero-02-face", sheetIndex: 1 },
  { id: "generated-actor-hero-02-face-02", name: "hero-02-face 얼굴 3", path: "assets/generated/starter/hero-02-face/02.png", sheetResourceId: "generated-actor-hero-02-face", sheetIndex: 2 },
  { id: "generated-actor-hero-02-face-03", name: "hero-02-face 얼굴 4", path: "assets/generated/starter/hero-02-face/03.png", sheetResourceId: "generated-actor-hero-02-face", sheetIndex: 3 },
  { id: "generated-actor-hero-02-face-04", name: "hero-02-face 얼굴 5", path: "assets/generated/starter/hero-02-face/04.png", sheetResourceId: "generated-actor-hero-02-face", sheetIndex: 4 },
  { id: "generated-actor-hero-02-face-05", name: "hero-02-face 얼굴 6", path: "assets/generated/starter/hero-02-face/05.png", sheetResourceId: "generated-actor-hero-02-face", sheetIndex: 5 },
  { id: "generated-actor-hero-02-face-06", name: "hero-02-face 얼굴 7", path: "assets/generated/starter/hero-02-face/06.png", sheetResourceId: "generated-actor-hero-02-face", sheetIndex: 6 },
  { id: "generated-actor-hero-02-face-07", name: "hero-02-face 얼굴 8", path: "assets/generated/starter/hero-02-face/07.png", sheetResourceId: "generated-actor-hero-02-face", sheetIndex: 7 },
  { id: "generated-actor-hero-02-face-08", name: "hero-02-face 얼굴 9", path: "assets/generated/starter/hero-02-face/08.png", sheetResourceId: "generated-actor-hero-02-face", sheetIndex: 8 },
  { id: "generated-actor-hero-02-face-09", name: "hero-02-face 얼굴 10", path: "assets/generated/starter/hero-02-face/09.png", sheetResourceId: "generated-actor-hero-02-face", sheetIndex: 9 },
  { id: "generated-actor-hero-02-face-10", name: "hero-02-face 얼굴 11", path: "assets/generated/starter/hero-02-face/10.png", sheetResourceId: "generated-actor-hero-02-face", sheetIndex: 10 },
  { id: "generated-actor-hero-02-face-11", name: "hero-02-face 얼굴 12", path: "assets/generated/starter/hero-02-face/11.png", sheetResourceId: "generated-actor-hero-02-face", sheetIndex: 11 },
  { id: "generated-actor-hero-02-face-12", name: "hero-02-face 얼굴 13", path: "assets/generated/starter/hero-02-face/12.png", sheetResourceId: "generated-actor-hero-02-face", sheetIndex: 12 },
  { id: "generated-actor-hero-02-face-13", name: "hero-02-face 얼굴 14", path: "assets/generated/starter/hero-02-face/13.png", sheetResourceId: "generated-actor-hero-02-face", sheetIndex: 13 },
  { id: "generated-actor-hero-02-face-14", name: "hero-02-face 얼굴 15", path: "assets/generated/starter/hero-02-face/14.png", sheetResourceId: "generated-actor-hero-02-face", sheetIndex: 14 },
  { id: "generated-actor-hero-02-face-15", name: "hero-02-face 얼굴 16", path: "assets/generated/starter/hero-02-face/15.png", sheetResourceId: "generated-actor-hero-02-face", sheetIndex: 15 },
];

/** 생성 시리즈(hero-XX-face) 낱장 얼굴 id. 저장본 해석·검증을 위해 FACESET_FACE_ASSETS 등록은
 *  유지하지만, 저작 목록(리소스 관리자·얼굴 피커·AI 카탈로그)에는 올리지 않는다. */
export const GENERATED_FACESET_FACE_IDS: ReadonlySet<string> = new Set([
  "generated-actor-hero-01-face-00",
  "generated-actor-hero-01-face-01",
  "generated-actor-hero-01-face-02",
  "generated-actor-hero-01-face-03",
  "generated-actor-hero-01-face-04",
  "generated-actor-hero-01-face-05",
  "generated-actor-hero-01-face-06",
  "generated-actor-hero-01-face-07",
  "generated-actor-hero-01-face-08",
  "generated-actor-hero-01-face-09",
  "generated-actor-hero-01-face-10",
  "generated-actor-hero-01-face-11",
  "generated-actor-hero-01-face-12",
  "generated-actor-hero-01-face-13",
  "generated-actor-hero-01-face-14",
  "generated-actor-hero-01-face-15",
  "generated-actor-hero-02-face-00",
  "generated-actor-hero-02-face-01",
  "generated-actor-hero-02-face-02",
  "generated-actor-hero-02-face-03",
  "generated-actor-hero-02-face-04",
  "generated-actor-hero-02-face-05",
  "generated-actor-hero-02-face-06",
  "generated-actor-hero-02-face-07",
  "generated-actor-hero-02-face-08",
  "generated-actor-hero-02-face-09",
  "generated-actor-hero-02-face-10",
  "generated-actor-hero-02-face-11",
  "generated-actor-hero-02-face-12",
  "generated-actor-hero-02-face-13",
  "generated-actor-hero-02-face-14",
  "generated-actor-hero-02-face-15",
]);

/** 저작 목록에 보이는 낱장 얼굴 — 생성 시리즈를 뺀 목록이다. */
export const AUTHORABLE_FACESET_FACE_ASSETS: readonly FacesetFaceAsset[] =
  FACESET_FACE_ASSETS.filter((face) => !GENERATED_FACESET_FACE_IDS.has(face.id));

const FACE_ID_BY_SHEET_CELL = new Map<string, string>(
  FACESET_FACE_ASSETS.map((face) => [`${face.sheetResourceId}#${face.sheetIndex}`, face.id])
);

/**
 * 레거시 (시트 id, 칸 번호) 쌍을 낱장 얼굴 id 로 바꾼다. 모든 입력에 대해 정의된 함수다 — 절대 던지지 않는다.
 * - 시트 id 가 아니면(이미 낱장 id 이거나 남의 리소스면) 입력을 그대로 돌려준다.
 * - 칸 번호가 undefined·NaN·무한이면 0 (RM2K 계보의 "생략은 0칸" 계약).
 * - 범위를 벗어나면 0..15 로 가둔다.
 */
export function faceIdForSheetCell(sheetResourceId: string, legacySheetCell: number | undefined): string {
  const cell = clampFaceCell(legacySheetCell);
  return FACE_ID_BY_SHEET_CELL.get(`${sheetResourceId}#${cell}`) ?? sheetResourceId;
}

function clampFaceCell(legacySheetCell: number | undefined): number {
  if (legacySheetCell === undefined || !Number.isFinite(legacySheetCell)) return 0;
  return Math.max(0, Math.min(FACE_CELL_COUNT - 1, Math.trunc(legacySheetCell)));
}
