// Generated by scripts/build-opening-still-catalog.mjs. Do not edit by hand.
// 오프닝 스틸 릴리스 팩 — 런타임(게임) 전용 최소 정보. 검색어는 openingStillMoods.ts 가 담는다.
// 팩 그림은 레포에 없다. Release 태그 tar 를 설치기가 public/assets/stills/pack/ 에 푼다.

/** 재생(표시)에 필요한 최소 정보. */
export type OpeningStillPackEntry = {
  readonly fileName: string;
};

const OPENING_STILL_PACK_ENTRIES: readonly (readonly [string, OpeningStillPackEntry])[] = [
  ["oprn-pack-still-test-a", { fileName: "test-a.jpg" }],
  ["oprn-pack-still-test-b", { fileName: "test-b.jpg" }],
];

export const OPENING_STILL_PACK_COUNT = OPENING_STILL_PACK_ENTRIES.length;

const OPENING_STILL_PACK_INDEX: ReadonlyMap<string, OpeningStillPackEntry> = new Map(
  OPENING_STILL_PACK_ENTRIES,
);

/** 팩 소속이 아니면 undefined — 해석기가 다음 후보로 넘어간다. */
export function findOpeningStillPackEntry(resourceId: string): OpeningStillPackEntry | undefined {
  return OPENING_STILL_PACK_INDEX.get(resourceId);
}

export function listOpeningStillPackIds(): readonly string[] {
  return OPENING_STILL_PACK_ENTRIES.map(([id]) => id);
}
