# 미래 폐허 조각 목록 + 메타(굽는 스크립트가 읽는 partmeta.json 의 원본). 순서 = 조각 판 번호.
# (이름, 만드는 함수, kind, ko, desc, rules, brows, layer, role)
import fr_props as P, fr_mech as M, fr_struct as S, fr_dome as DM, fr_samples as X, fr_ground as G

PARTS = [
    # ---------------------------------------------------------------- 앵커
    ('glass_dome', lambda: DM.dome(), 'object', '반쯤 무너진 유리 돔',
     '철골 경선·위선 골조에 청록 유리를 끼운 큰 반구 돔. 오른쪽 위가 무너져 뒤가 비치고 휜 철골이 늘어졌다. 콘크리트 받침 고리, 앞 가운데 경고 띠 현관과 반쯤 내린 셔터.',
     '광장 한가운데 콘크리트 위에 하나만. 발자국은 받침 타원(아래 4줄, 가장자리 열은 2~3줄) 막힘, 현관 가운데 칸만 걷기(돔 안으로 가는 문). 위 칸은 걷기+가림. 무너진 쪽 발치에 dome_rubble·glass_shards 를 덩이로.', 4, None, 'building'),
    ('dome_rubble', lambda: S.dome_rubble(), 'object', '돔 잔해 더미',
     '무너진 돔에서 떨어진 휜 철골 호 둘, 큰 유리판 조각 셋, 콘크리트 덩이.', '돔의 무너진 쪽 발치에 붙여 한 번. 칸 전체 막힘. 둘레에 glass_shards 장식.', 2, None, 'prop'),
    ('robot_hulk', lambda: M.robot_hulk(), 'object', '주저앉은 거대 로봇 잔해',
     '다리를 앞으로 뻗고 앉은 채 오른쪽으로 기운 거대 기계 몸체. 머리가 떨어져 목 구멍에서 전선이 늘어지고 왼팔은 어깨째 뜯겼다. 바랜 황토 장갑·리벳 판·녹·이끼. 얼굴·눈 없음.',
     '광장 가장자리나 빈터에 하나. 아래 2줄 막힘, 위는 걷기+가림. 옆에 robot_arm 을 2~4칸 떨어뜨려 놓고 rust 오토타일로 바닥을 물들인다.', 2, None, 'prop'),
    ('robot_arm', lambda: M.robot_arm(), 'object', '떨어진 로봇 팔',
     '눕힌 위팔 원통·공 관절·장갑 아래팔·벌어진 세 갈래 집게, 잘린 어깨에서 쏟아진 전선.', '로봇 잔해 곁이나 빈터에. 아랫줄만 막힘. 일렬로 여러 개 금지.', 1, None, 'prop'),
    ('rust_machine', lambda: M.rust_machine(), 'object', '녹슨 대형 발전기',
     '콘크리트 받침 위 눕힌 큰 탱크(리벳 테), 배기 굴뚝과 김, 피스톤 둘, 압력계·어두운 조작판(글자 없음), 바퀴 밸브, 땅으로 내려가는 관.',
     '공장 마당·강철판 위에. 아래 2줄 막힘, 굴뚝·탱크 윗부분은 걷기+가림. 관 끝 쪽은 벽이나 다른 기계에 붙인다.', 2, None, 'prop'),
    ('sentry_wreck', lambda: M.sentry_wreck(), 'object', '쓰러진 경비 기계',
     '둥근 강철 껍데기·검은 궤도·부러진 안테나·작은 접시. 얼굴·눈 없음.', '빈터·광장 가장자리에 드물게. 아랫줄만 막힘.', 1, None, 'prop'),
    ('overpass_span', lambda: S.overpass_span(), 'object', '끊긴 고가 도로(상판 단면)',
     '교각 둘 위 고가 상판: 먼 난간·바랜 차선 도로·가까운 난간·거더 앞면. 양 끝이 부서졌고 오른쪽 끝에 철근에 매달린 상판 조각과 떨어진 잔해.',
     '도로 위나 옆을 가로지르게. 교각 밑동 두 칸씩과 오른쪽 잔해만 막힘, 상판 아래는 지나다닐 수 있다(상판 칸 걷기+가림). 끊긴 틈에 deck_fallen, 이어서 overpass_pier.', 1, None, 'building'),
    ('overpass_pier', lambda: S.overpass_pier(), 'object', '홀로 남은 교각',
     '망치머리 받침 위에 짧게 남은 상판 토막(양 끝 부서짐, 철근 삐죽), 몸통에 빗물 얼룩·이끼.', '끊긴 고가 도로의 연장선 위에. 밑동 가운데 칸만 막힘.', 1, None, 'building'),
    ('deck_fallen', lambda: S.deck_fallen(), 'object', '떨어진 상판 조각',
     '땅에 비스듬히 박힌 도로 상판(아스팔트·바랜 차선)과 콘크리트 두께, 깨진 끝 철근.', '고가 도로가 끊긴 틈 밑이나 빈터에. 칸 전체 막힘.', 2, None, 'prop'),
    ('factory_gate', lambda: S.factory_gate(), 'object', '지하 공장 입구(벙커)',
     '콘크리트 벙커: 지붕(환풍 팬·관·안테나), 엇갈린 판 앞면, 경고 띠 문틀의 큰 철문 — 반쯤 올린 셔터 아래로 어둠 속 내려가는 경사로와 호박색 띠등. 문 위 번개 세모 그림판(글자 없음), 표시등·통풍구·벽 관·김.',
     '공장 마당(강철판) 북쪽 끝에. 앞면 4줄 막힘, 문 아래 가운데 4칸은 걷기(지하 공장으로 가는 문). 지붕 2줄은 걷기+가림. 문 앞 2칸은 비워 둔다.', 4, None, 'building'),
    ('ruin_block_tall', lambda: S.ruin_block(4, 3, .6, seed=1, tank=True), 'object', '무너진 고층 건물(4층)',
     '층마다 콘크리트 바닥 띠와 깨진 창 줄, 오른쪽 위가 계단꼴로 무너져 철근이 삐죽, 지붕 물탱크, 1층 셔터 가게, 밑동 이끼.',
     '지도 가장자리·길가에 줄지어(사이에 ruin_wall·잔해). 앞면 7줄 막힘, 맨 위 무너진 윗면 줄은 걷기+가림. 좌우 뒤집어 변형.', 7, None, 'building'),
    ('ruin_block_low', lambda: S.ruin_block(3, 2, .5, seed=3), 'object', '무너진 건물(3층, 좁은)',
     '창 두 열 3층 건물 그루터기, 오른쪽 위 무너짐·철근, 1층 셔터.', '길가 가게 줄에. 앞면 6줄 막힘, 윗면은 걷기+가림.', 6, None, 'building'),
    ('ruin_block_small', lambda: S.ruin_block(2, 2, .4, seed=6, tank=True), 'object', '무너진 건물(2층)',
     '2층 건물 그루터기와 지붕 물탱크.', '빈터 가장자리·작은 블록에. 앞면 4줄 막힘.', 4, None, 'building'),
    ('ruin_wall', lambda: S.ruin_wall(3, 1), 'wall', '무너진 콘크리트 담',
     '갓돌 윗면과 엇갈린 판 앞면. 왼쪽은 기둥 끝으로 맺고 오른쪽은 계단꼴로 무너져 잔해 덩이로 끝난다.',
     '건물 사이를 잇거나 빈터 경계에. 앞면 아랫줄 막힘, 윗줄 걷기+가림. 뒤집어 무너진 쪽 방향을 바꾼다. 떠 있는 벽 금지 — 한쪽은 건물·기둥에 붙인다.', 1, None, 'wall'),
    ('storage_tank', lambda: S.storage_tank(), 'object', '녹슨 저장 탱크',
     '세운 큰 강철 원통(리벳 테, 녹물 줄), 낮은 둥근 지붕·맨홀·난간, 사다리, 관, 콘크리트 받침 고리.', '공장 둘레에 1~2개를 붙여서. 아래 2줄 막힘, 위는 걷기+가림. 높이 변형(h).', 2, None, 'building'),
    ('billboard_frame', lambda: S.billboard_frame(), 'object', '빈 광고판 틀',
     '격자 강철 다리 둘 위의 큰 판, 반쯤 찢겨 뒤 골조가 보인다. 남은 판은 바랜 색 띠뿐(글자·그림·상표 없음). 발판·난간·깨진 조명.',
     '길가·빈터에 드물게. 다리 밑동 두 칸만 막힘, 판 아래는 지나다닐 수 있다.', 1, None, 'prop'),
    # ---------------------------------------------------------------- 거리 소품
    ('power_pole', lambda: P.power_pole(), 'object', '전봇대',
     '콘크리트 기둥·강철 완목과 버팀대·사기 애자 셋·호박색 등 달린 함·땅으로 내려가는 선.', '길가를 따라 8~10칸 간격(정확한 줄 금지, 1칸 흔들기). 밑동 한 칸만 막힘, 위 칸 걷기+가림. 기둥 사이 전선은 cable_droop 또는 직접 처진 줄.', 1, None, 'prop'),
    ('power_pole_broken', lambda: P.power_pole(seed=2, lean=.12, broken=True), 'object', '기운 전봇대(끊긴 줄)',
     '비스듬히 기운 전봇대, 완목 양 끝에서 끊긴 전선이 늘어졌다.', '전봇대 줄의 끝이나 무너진 곳에. 밑동 두 칸 막힘.', 1, None, 'prop'),
    ('cable_droop', lambda: P.cable_droop(), 'decal', '늘어진 전선(위층)',
     '두 전봇대 완목 높이 사이에 처진 전선 세 가닥.', '전봇대 사이 위층(사람 위)에 놓는다. 걷기. 맨 윗줄이 완목 높이에 오게.', 0, None, 'decal'),
    ('sign_blink_on', lambda: P.sign_blink(True), 'object', '깜빡이는 표지(켜짐)',
     '강철 다리 둘 위 표지 상자, 청록으로 빛나는 아래쪽 갈매기 무늬(글자 없음). 꺼진 그림과 번갈아 깜빡인다.', '광장 입구·길 끝에. 다리 밑동 두 칸 막힘. sign_blink_off 와 같은 자리에서 프레임 교대.', 1, None, 'prop'),
    ('sign_blink_off', lambda: P.sign_blink(False), 'object', '깜빡이는 표지(꺼짐)', '같은 표지의 꺼진 프레임(무늬가 어둡다).', 'sign_blink_on 과 같은 자리·같은 규칙.', 1, None, 'prop'),
    ('signal_post_on', lambda: P.signal_post(True), 'object', '경고등 기둥(켜짐)', '강철 기둥 꼭대기 붉은 회전등과 붉은 빛 번짐, 아래 경고 띠.', '공장 마당 모서리·위험한 곳 앞에. 밑동 한 칸 막힘. off 프레임과 교대.', 1, None, 'prop'),
    ('signal_post_off', lambda: P.signal_post(False), 'object', '경고등 기둥(꺼짐)', '같은 기둥, 등이 꺼졌다.', 'signal_post_on 과 같은 규칙.', 1, None, 'prop'),
    ('toxic_drums', lambda: P.toxic_drums(), 'object', '새는 오염 드럼통 무리', '바랜 경고 도장 통·녹슨 통, 쓰러진 통에서 녹색 오염물이 흘러나온다.', '공장·잔해 곁에 덩이로. 아랫줄만 막힘. 오염 웅덩이 근처면 좋다.', 1, None, 'prop'),
    ('drum_single', lambda: P.drum_single(), 'object', '녹슨 드럼통', '옆구리가 찌그러진 녹슨 통 하나.', '무리 곁에 1~2개 흩어. 칸 막힘.', 1, None, 'prop'),
    ('container', lambda: P.container(), 'object', '녹슨 화물 컨테이너', '바랜 붉은 도장 골판 컨테이너, 문 잠금 막대, 찌그러짐·녹·밑동 이끼.', '공장 마당 둘레·빈터에. 아래 2줄 막힘, 윗면 줄은 걷기+가림.', 2, None, 'prop'),
    ('car_wreck', lambda: P.car_wreck(), 'object', '차 잔해', '바퀴 없이 주저앉은 각진 차체(바랜 흰 도장·녹), 깨진 유리, 지붕 이끼. 글자·상표 없음.', '도로 위·길가에 비스듬히 흩어(나란히 주차 금지). 아랫줄만 막힘. 좌우 뒤집어 변형.', 1, None, 'prop'),
    ('jersey_barrier', lambda: P.jersey_barrier(), 'object', '콘크리트 방호벽', '좁은 윗면·비스듬한 앞면·바랜 경고 띠.', '도로 가장자리·광장 입구에 1~3개 엇갈려. 칸 막힘.', 1, None, 'prop'),
    ('jersey_barrier_broken', lambda: P.jersey_barrier(True), 'object', '부서진 방호벽', '오른쪽이 깨져 철근이 삐죽한 방호벽.', '방호벽 줄의 끝에. 칸 막힘.', 1, None, 'prop'),
    ('streetlamp_bent', lambda: P.streetlamp_bent(), 'object', '휜 가로등', '꺾여 등머리가 매달린 강철 가로등, 깨진 등갓·끊긴 전선.', '광장 둘레·길가에 6~10칸 간격. 밑동 한 칸만 막힘. 뒤집어 휜 방향을 바꾼다.', 1, None, 'prop'),
    ('pipe_run', lambda: P.pipe_run(), 'object', '굵은 관 줄', '콘크리트 받침 위 굵은 강철관(지름 12)과 가는 놋쇠관(지름 6), 붉은 바퀴 밸브.', '공장 벽을 따라·마당 가장자리에. 받침 줄만 막힘. 끝은 벽·기계·땅(pipe_elbow)에 잇는다.', 1, None, 'prop'),
    ('pipe_elbow', lambda: P.pipe_elbow(), 'object', '솟아 꺾인 관', '땅에서 솟아 꺾여 끊긴 굵은 관, 끝 단면, 이음에서 새는 김.', '공장 마당에. 밑동만 막힘.', 1, None, 'prop'),
    ('vent_fan', lambda: P.vent_fan(), 'object', '환풍기 함', '윗면 둥근 팬 창살·앞면 통풍구 강철 상자, 위로 김.', '공장 마당·벙커 곁에. 아랫줄 막힘.', 1, None, 'prop'),
    ('floor_vent', lambda: P.floor_vent(), 'decal', '바닥 환기 창살', '강철 틀 가로 창살과 가는 김.', '강철판·콘크리트 바닥에 드문드문. 걷기, 사람 아래.', 0, None, 'decal'),
    ('manhole', lambda: P.manhole(), 'decal', '맨홀 뚜껑', '둥근 강철 뚜껑과 방사 홈.', '도로·광장에 드문드문. 걷기, 사람 아래.', 0, None, 'decal'),
    ('rubble_conc', lambda: P.rubble_conc(), 'object', '콘크리트 잔해 더미', '깨진 덩이 다섯과 녹슨 철근.', '무너진 건물·담 끝, 고가 도로 밑에. 아랫줄만 막힘.', 1, None, 'prop'),
    ('rubble_small', lambda: P.rubble_small(), 'object', '작은 잔해', '덩이 둘·철근 한 가닥.', '잔해 더미 곁에 흩어. 칸 막힘.', 1, None, 'prop'),
    ('girder_pile', lambda: P.girder_pile(), 'object', '철골 더미', 'H 단면이 보이는 형강 셋이 엇갈려 쌓였다.', '공사·잔해 자리에. 아랫줄만 막힘.', 1, None, 'prop'),
    ('cable_reel', lambda: P.cable_reel(), 'object', '전선 릴', '세운 나무 원판 둘 사이 감긴 검은 전선, 풀린 끝.', '공장 마당 가장자리에. 아랫줄만 막힘.', 1, None, 'prop'),
    ('fence_chain', lambda: P.fence_chain(), 'object', '찢긴 철망 울타리', '강철 기둥 사이 마름모 철망, 가운데가 찢겨 말렸다.', '마당 경계에 끊어진 토막으로(빈틈 두기). 밑동 줄 막힘.', 1, None, 'prop'),
    ('glass_shards', lambda: P.glass_shards(), 'decal', '깨진 유리 조각', '흩어진 청록 유리 삼각 조각.', '돔·건물 밑에 덩이로. 걷기, 사람 아래.', 0, None, 'decal'),
    ('oil_stain', lambda: P.oil_stain(), 'decal', '기름 얼룩', '검게 번진 기름과 무지개 막.', '도로·마당에 드물게. 걷기.', 0, None, 'decal'),
    ('weeds_sick', lambda: P.weeds_sick(), 'decal', '오염 잡초', '금 틈에서 자란 누런 풀 잎.', '포장 금·벽 밑에 2~5포기 덩이로. 걷기, 사람 아래.', 0, None, 'decal'),
    # ---------------------------------------------------------------- 기계 재질 표본
    ('mat_steel_panels', lambda: X.mat_steel_panels(), 'wall', '기계 재질 — 외장 강철판',
     '32x16 판 엇갈림·줄눈·리벳 6px 간격(규약 표본). 3x3 이어 붙임.', '벽·기계 몸통 앞면을 칠할 때 기준. 이 표본의 톤·줄눈 규칙을 따라 새 조각을 그린다.', 3, None, 'wall'),
    ('mat_rust_panels', lambda: X.mat_rust_panels(), 'wall', '기계 재질 — 녹슨 강철판',
     '같은 판에 녹 번짐 규약(줄눈·리벳에서 시작, 아래로 흐름).', '녹슨 벽·잔해 칠하기 기준.', 3, None, 'wall'),
    ('mat_pipe16', lambda: X.mat_pipe16(), 'object', '기계 재질 — 가는 관(16px)', '지름 6px, 16px 마다 이음 테(강철·놋쇠).', '가는 관 굵기·음영 기준. 가로로 이어 붙인다. 놓으면 칸 막힘.', 1, None, 'prop'),
    ('mat_pipe32', lambda: X.mat_pipe32(), 'object', '기계 재질 — 굵은 관(32px)', '지름 12px, 32px 마다 볼트 이음 테(강철·녹슨 관).', '굵은 관 기준. 가로로 이어 붙인다. 놓으면 아랫줄 막힘.', 1, None, 'prop'),
    ('mat_cable', lambda: X.mat_cable(), 'decal', '기계 재질 — 전선', '2px 고무 전선 세 가닥의 처짐.', '전선 굵기·처짐 기준. 위층, 걷기.', 0, None, 'decal'),
    ('mat_glass', lambda: X.mat_glass(), 'wall', '기계 재질 — 유리판', '강철 창살 틀 안 유리 넷(성한·금 간·깨진).', '유리창·돔 유리 기준. 벽 앞면에 얹는다.', 2, None, 'wall'),
    ('mat_hazard', lambda: X.mat_hazard(), 'decal', '기계 재질 — 경고 띠', '바랜 노랑·검정 사선 4px.', '문틀·기둥 밑동·위험 구역 테두리 기준. 글자 금지.', 0, None, 'decal'),
    # ---------------------------------------------------------------- 바닥 표본
    ('ground-concrete', lambda: G.ground_concrete(), 'floor', '콘크리트 판 바닥', '칩셋 모래흙 결을 콘크리트 램프로, 판 줄눈(군데 끊김)·가는 금·빗물 얼룩. 3x3 이음새 없음.', '광장·보도. 걷기.', 0, 'lower', 'terrain'),
    ('ground-asphalt', lambda: G.ground_asphalt(), 'floor', '아스팔트 바닥', '칩셋 잔 자갈 결을 흑회 램프로, 바랜 덩이·기름 얼룩. 3x3 이음새 없음.', '도로. 걷기. 차선은 바랜 노랑 점선(가운데 2px).', 0, 'lower', 'terrain'),
    ('ground-steelplate', lambda: G.ground_steelplate(), 'floor', '강철판 바닥', '16x16 판·모서리 리벳·미끄럼 돌기·옅은 녹. 3x3 이음새 없음.', '공장 마당·실내 기계실. 걷기.', 0, 'lower', 'terrain'),
    ('ground-sickgrass', lambda: G.ground_sickgrass(), 'floor', '오염 풀 바닥', '버들항 풀밭 결을 누런 오염 풀 램프로. 3x3 이음새 없음.', '폐허 빈터. 걷기.', 0, 'lower', 'terrain'),
    # ---------------------------------------------------------------- 오토타일
    ('autotile-crack', lambda: G.autotile_crack(), 'autotile', '깨진 포장 구멍(바닥↔균열)',
     '포장 위에 덧그리는 깨진 구멍: 속은 드러난 흙·잔돌·잡초, 가장자리는 깨진 포장 턱(밝은 모·어두운 틈), 바깥으로 뻗는 가는 금. 16변형.', '콘크리트·아스팔트 위 덩이로(2~6칸). 걷기. 일렬 금지.', 0, 'lower', 'terrain'),
    ('autotile-rust', lambda: G.autotile_rust(), 'autotile', '녹·오염 번짐',
     '강철판·콘크리트 위에 반투명 녹물이 번진 자리, 디더로 옅어지는 들쭉날쭉한 가장자리, 흘러내린 줄. 16변형.', '기계·잔해·드럼통 곁 바닥에 덩이로. 걷기.', 0, 'lower', 'terrain'),
    ('autotile-toxpool', lambda: G.autotile_toxpool(), 'autotile', '오염 웅덩이',
     '탁한 청록 물(기름띠·거품), 북쪽 물가는 진흙 앞면, 물가 누런 거품 띠·젖은 테. 16변형.', '꺼진 도로·빈터 낮은 곳에 덩이로. 막힘(물). 둘레에 잡초·드럼통.', 1, 'lower', 'water'),
]
