"""Only place explicitly authored ASCII row strings. No shape or pose math.
All final pxgrids are standalone 96-row literals. Fixed body rows may be
retained between cels; altered anatomy is separately written at native coordinates.
"""
from pathlib import Path
import json
ROOT = Path(__file__).resolve().parent
PALETTE = {'O':'#142928','K':'#0e151e','T':'#205048','S':'#287761',
'J':'#40a77c','L':'#79c58e','H':'#b1dfa2','W':'#e8f4c5',
'D':'#75532f','B':'#a77a37','G':'#dab853','Y':'#f7dd84','R':'#966941',
'E':'#217b7b','F':'#3cafad','C':'#83e5ce','P':'#625783','N':'#a695ce'}
(ROOT/'palette.json').write_text(json.dumps(PALETTE,indent=2)+'\n')

def rows(y, text):
    result=[]
    for line in text.strip().splitlines():
        x, ink=line.split(':',1)
        result.append((int(x), y, ink))
        y+=1
    return result

def save(name, *clusters):
    grid=[list('.'*96) for _ in range(96)]
    for cluster in clusters:
        for x,y,ink in cluster:
            if x<0 or y<0 or x+len(ink)>96 or y>=96: raise ValueError((name,x,y,ink))
            grid[y][x:x+len(ink)]=ink
    folder='poses' if name in ('idle_a','idle_b','idle_c','windup','move','attack','recover','hit','dead') else 'actions'
    (ROOT/folder/(name+'.pxgrid')).write_text('\n'.join(''.join(row) for row in grid)+'\n')

# Long upper-left-lit jade head and neck. Two eyes, oblique bridge and right snout.
IDLE_UP = rows(13, '''
51:OOOOOOOOOOO
48:OOOLLLHHHHHHLLLOOO
46:OOLLLHHHHHHHHLLLLLJJOO
45:OLLHHHHHHHLLLLLLLJJJJJOO
44:OLHHHHHHLLLLLLLLJJJJJJJSOO
43:OLHHHHLLLLLLLLLJJJJJJJSSSO
43:OHHHHLLLLLLLLJJJJJJJJSSSSOO
42:OLHHLLLLLLLJJJJJJJJJJJJJJJOO
42:OLHLLLLLLJJJJJTTOOJJJJJJJJJJOO
42:OLLLLLLLJJJJJTOKKKOJJJTOOJJJJJO
42:OLLLLLJJJJJJJTKKKKOJJTOKKOJJJJJO
42:OLLLLJJJJJJJJTKKKKOJJTOKKOJJJJSO
42:OLLJJJJJJJJJJJTOOOJJJJTOOJJJJSSO
42:OLJJJJJJJJJJJJJJJJJJJJJJJJJJSSSO
42:OJJJJJJJJJJJJJJJJJJJSSSSJJJJTTO
42:OJJJJJJJJJJJJSSSSSTTOOOOOOOOOTTO
42:OJJJJJJJJJJSSSSSTTTOBGGGGGGGBDO
42:OSJJJJJJJSSSSSTTTOBYYYYGGGGBDO
41:OLJJJJJJSSSSSTTTOBGYYYYGGBDOO
40:OLLJJJJSSSSSTTTOBGGYYGGBDOO
39:OLLLJJJSSSSSTTTOBGYYYGBDO
38:OLLLJJJJSSSSTTTOBGYYGBO
37:OLLLJJJJSSSSTTOBGYYYBO
36:OLLLJJJJSSSSTTOBGGYYBO
35:OLLLJJJJSSSSTTOBGYYYBO
34:OLLLLJJJSSSSTTOBGYYYBO
33:OLLLLJJJJSSSTTOBGGYYBO
33:OLLHLJJJJSSSTTOBGYYYBO
32:OLLHLLJJJSSSTTOBGYYYBO
32:OLLHLLJJJSSSTTOBGGYYBO
32:OLHHLLJJJSSSTTOBGYYYBO
32:OLHHLLJJJSSSTTOBGYYYBO
32:OLHHLLJJJSSSTTOBGGYYBO
32:OLHHLLJJJSSSTTOBGYYYBO
33:OLHHLLJJJSSSTTOBGYYYBO
33:OLHHLLJJJJSSSTTOBGGYYBO
34:OLHHLLJJJJSSSTTOBGYYYBO
34:OLLHLLLJJJSSSTTOBGYYYBO
35:OLLHLLLJJJJSSSTTOBGGYYBO
36:OLLHLLLLJJJSSSTTOBGYYYBO
37:OLLHLLLLJJJJSSSTTOBGYYYBO
38:OLLHLLLLJJJJSSSTTOBGGYYBO
39:OLLHLLLLJJJJSSSTTOBGYYYBO
40:OLLHLLLLJJJJSSSTTOBGYYYBO
40:OLLHLLLLJJJJSSSTTOBGGYYBO
40:OLLHLLLLJJJJSSSTTOBGYYYBO
40:OLLHLLLLJJJJSSSTTOBGYYYBO
39:OLLHLLLLJJJJSSSTTOBGGYYBO
38:OLLHLLLLJJJJJSSSTTOBGYYBO
37:OLLHLLLLJJJJJJSSSTTOBGYBO
36:OLLHLLLLJJJJJJJSSSTTOBGBO
35:OLLHLLLLJJJJJJJJSSSTTOBO
''')

# Resting coil: rear arch, intentional small center gap, front golden abdominal sweep.
COIL_REST = rows(64, '''
33:OOLLHLLLLJJJJJJJJJSSSTBGYYBO
30:OOLHHHLLLLLLJJJJJJJJSSSTBGYYYBO
28:OOLHHHHLLLLLLJJJJJJJJJSSSTBGYYGBO
26:OOLHHHHHLLLLLLJJJJJJJJJJSSSTBGYYYBO
25:OLHHHHHHLLLLLLJJJJJJJJJJJSSSTBGYYYBO
24:OLHHHHHLLLLLLJJJJJJJJJJJJSSSTBGGYYBO
23:OLHHHHLLLLLLJJJJJJJJJJJJJSSSTBGYYYBO
22:OLHHHHLLLLLJJJJJJJJJJJJJJSSSTBGYYYBO
21:OLHHHHLLLLJJJJSSSSSSSSSJJJJSSSTBGGYYBO
21:OLHHHLLLLJJJSTTOOOOOOOTTSSJJJSSSTBGYYYBO
20:OLHHHLLLLJJSTTO.......OTTSJJJJSSSTBGYYYBO
20:OLHHLLLLJJSTTO.........OTTSJJJSSSTBGGYYBO
20:OLHHLLLLJJSTO...........OTSJJJSSSTBGYYYBO
20:OLHLLLLLJJSTO...........OTSJJJSSSTBGYYYBO
20:OLHLLLLLJJSTTO.........OTTSJJJSSSTBGGYYBO
20:OLLLLLLLJJJSSTOO.....OOTTSJJJJSSSTBGYYYBO
21:OLLLLLLLJJJJSSSTOOOOOTTSSJJJJSSSTBGYYYBO
21:OLLHLLLLLJJJJSSSSSTTTSSSJJJJSSSTBGGYYBO
22:OLLHHLLLLLJJJJJJJJJJJJJJJJJJSSSTBGYYYBO
23:OLLHHLLLLLLJJJJJJJJJJJJJJJJJSSSTBGYYYBO
24:OLLHHHLLLLLLJJJJJJJJJJJJJJJSSSTBGGYYBO
25:OOLHHHLLLLLLLJJJJJJJJJJJJSSSTBGGYYBO
26:OOBGYYYGGBBGYYYGGBBGYYYGGBBGGGGTTOO
28:OOBGYYYYGGBGYYYYGGBGYYYYGGBGGGBTTOO
30:OOBGGYYGGBBGGYYGGBBGGYYGGBGGGTTOO
32:OOBBBBBBBBBBBBBBBBBBBBBBBBDDTOO
34:OOOTTTTTTTTTTTTTTTTTTTTTTTOOO
37:OOOOTTTTTTTTTTTTTTTTOOOOO
41:OOOOOOOOOOOOOOOO
''')

# Tail explicitly hooks up behind left coil and carries the lantern by a metal collar.
TAIL_REST = rows(62, '''
17:OOSSJO
17:OSLJJSO
18:OSLJJJSO
19:OSLLJJJSO
20:OSLLLJJJSO
21:OSLLLJJJSO
22:OSLLLJJJSSO
23:OSLLLJJJSSO
23:OSLLLJJJSSO
22:OSLLLJJJJSSO
21:OSLLLJJJJSSO
21:OSLLLJJJJSSO
21:OSLLLJJJJSSO
22:OSLLLJJJJSSO
23:OSLLLJJJSSO
24:OSLLJJJSSO
25:OSLJJSSO
26:OSJSSO
''')
LAMP_REST=rows(42, '''
16:OOOOO
15:OBYGBO
15:OBGGBO
13:OOBGGGBOO
11:OOBYGGGGGBBOO
9:OOBYYYYGGGGGGBBOO
8:OBGGGGGGGGGGGGGBDO
8:OORRRRRRRRRRRRRDOO
9:OEFFFFFCFFFFFEEO
9:OEFFFCCWCFFFFEEO
8:OEFFFFCWCFFFFFEEO
8:OEFFFCCWCCFFFFEEO
8:OEFFFCCWCCFFFFEEO
8:OEFFFCCWCCFFFFEEO
8:OEFFFCCWCCFFFFEEO
9:OEFFFFCWCCFFFEEO
9:OEFFFFCCCFFFFEEO
10:OEFFFFFFFFFEEO
10:OOBGGGGGGGBDOO
12:OOBYYYGBDOO
14:OOBGBOO
15:OBYBO
15:OBGBO
16:OBO
''')

# The retained resting loop's forward plates follow one continuous curved edge.
# Literal placement, including explicit transparent erasures, not contour cleanup.
COIL_REST += rows(64, '''
54:TBGYYYBO.....
54:TBGGYYBO.....
54:TBGYYYBO.....
55:TBGYYYBO.....
52:SSSTBGGYYBO.....
51:SSSSSTBGYYYBO.....
50:SSSSSSTBGYYYBO.....
49:SSSSSSSSTBGGYYBO.....
50:SSSSSSSTBGYYYBO.....
52:SSSSSTBGYYYBO.....
52:SSSSSTBGGYYBO.....
52:SSSSSTBGYYYBO.....
52:SSSSSTBGYYYBO.....
52:SSSSSTBGGYYBO.....
52:SSSSTBGYYYBO.....
52:SSSSTBGYYYBO.....
52:SSSTBGGYYBO.....
51:SSSSTBGYYYBO.....
51:SSSTBGYYYBO.....
51:SSSTBGGYYBO.....
51:SSTBGYYYBO.....
51:STBGGYYBO.....
51:BGGGGBDDOO....
51:GYYGGGBDTOO...
51:GGGGBBDTOO....
51:BBBBDDTOO.....
51:TTTTTOOO......
51:TTTOOO........
51:OOOO..........
''')

save('idle_a', IDLE_UP, COIL_REST, TAIL_REST, LAMP_REST)

# Local breathed crown, cheek and coil planes; never displace a frame.
IDLE_B_EDIT=rows(12, '''
51:OOOOOOOO
48:OOOLHHHHHHHHLLLOO
46:OOLHHHHHHHHLLLLLLJOOO
45:OLHHHHHHHHLLLLLLJJJJJOO
44:OLHHHHHHLLLLLLLLJJJJJJJOO
43:OLHHHHLLLLLLLLLJJJJJJJSSOO
43:OHHHHLLLLLLLLJJJJJJJJSSSSO
''')+rows(43, '''
31:OOLHHLLJJJJSSSTTOBGYYYBO
31:OLHHHLLJJJJSSSTTOBGYYYBO
31:OLHHHLLJJJJSSSTTOBGGYYBO
31:OLHHHLLJJJJSSSTTOBGYYYBO
32:OLHHHLLJJJJSSSTTOBGYYYBO
32:OLHHHLLJJJJSSSTTOBGGYYBO
''')+[(34,69,'LLLLLLLJJJJJ'),(34,70,'LLLLLLJJJJJJ'),(11,53,'FFCCWWCCF'),(11,54,'FFCCWWCCF'),(11,55,'FFFCCWCCF')]
IDLE_C_EDIT=rows(21, '''
42:OLHLLLLLLJJJJJTTOOJJJJJJJJJJOO
42:OLLLLLLLJJJJJTOKKKOJJJTOOJJJJJO
42:OLLLLLJJJJJJJTOKKKOJJTOKKOJJJJJO
42:OLLLLJJJJJJJJJTOOOJJJJTOOJJJJJJO
42:OLLJJJJJJJJJJJJJJJJJJJJJJJJJJSSO
''')+rows(50, '''
34:OLLHLLLJJJJSSSTTOBGYYYBO
35:OLLHLLLLJJJJSSSTTOBGGYYBO
36:OLLHLLLLJJJJSSSTTOBGYYYBO
37:OLLHLLLLJJJJJSSSTTOBGYYYBO
''')+[(43,84,'JJJJJJJSSSS'),(13,54,'FCCWCCF'),(14,55,'FCWCF')]
save('idle_b',IDLE_UP,COIL_REST,TAIL_REST,LAMP_REST,IDLE_B_EDIT)
save('idle_c',IDLE_UP,COIL_REST,TAIL_REST,LAMP_REST,IDLE_C_EDIT)

WINDUP_UP=rows(31, '''
46:OOOOOOOOOOOO
43:OOOLHHHHHLLLLLLLOOO
41:OOLHHHHHHLLLLLLLLJJJOO
40:OLHHHHHLLLLLLLLJJJJJJJOO
39:OLHHHHLLLLLLLJJJJJJJJJSSOO
38:OLHHHLLLLLLJJJJJJJJJJSSSSSO
37:OLHHLLLLLJJJJJJJJJJJJJJJJJJOO
36:OLHHLLLLJJJJJJJJTOOJJJJJJJJJJOO
35:OLHHLLLJJJJJJJTOKKKOJJJTOOJJJJJO
34:OLHHLLJJJJJJJJTKKKKOJJTOKKOJJJJJO
33:OLHHLLJJJJJJJJTKKKKOJJTOKKOJJJJSSO
32:OLHHLLJJJJJJJJJTOOOJJJJTOOJJJJSSSO
31:OLHHLLJJJJJJJJJJJJJJJJJJJJJJSSSTTO
30:OLHHLLJJJJJJJJJJSSSSSTTOOOOOOOOTTO
29:OLHHLLJJJJJJSSSSSTTTTOBGGGGGGGBDO
28:OLHHLLJJJJJSSSSSTTTOBGYYYYGGBDOO
27:OLHHLLJJJJSSSSSTTTOBGYYYGGBDOO
26:OLHHLLJJJJSSSSTTTOBGYYYGBOO
25:OLHHLLJJJJSSSTTTOBGYYGBOO
24:OLHHLLJJJJSSSTTOBGYYYBO
24:OLHHLLJJJJSSSTTOBGGYYBO
24:OLHHHLLJJJSSSTTOBGYYYBO
25:OLHHHLLJJJJSSSTTOBGYYBO
26:OLHHHLLLJJJJSSSTTOBGYBO
27:OLHHHLLLLJJJJSSSTTOBGBO
28:OLHHHLLLLLJJJJSSSTTOBBO
29:OLHHHLLLLLLJJJJSSSTTOBO
30:OLHHHLLLLLLLJJJJSSSTTTOO
30:OLHHHLLLLLLLLJJJJSSSTTTTOO
30:OLHHHLLLLLLLLLJJJJSSSTTTTTOO
29:OLHHHLLLLLLLLLLJJJJSSSTTTTTOO
28:OLHHHLLLLLLLLLLLJJJJSSSTTTTTOO
27:OLHHHLLLLLLLLLLLLJJJJSSSTTTTTOO
''')
COIL_COMPRESS=rows(64, '''
26:OOOLHHHLLLLLLLLJJJJJJJJSSSTTTOOO
24:OOLHHHHHLLLLLLLLJJJJJJJJJSSSTTTTOO
23:OLHHHHHHLLLLLLLLJJJJJJJJJJSSSTTTTTO
22:OLHHHHHHHLLLLLLLLJJJJJJJJJJSSSTTTTTO
21:OLHHHHHHHLLLLLLLLJJJJJJJJJJSSSTTTTTTO
20:OLHHHHHHHLLLLLLLJJJJJJJJJJJSSSTTTTTTO
19:OLHHHHHHLLLLLLLJJJJJJJJJJJJSSSTTTTTTTO
19:OLHHHHHLLLLLLJJJJJJJJJJJJJJSSSTTTTTTTO
18:OLHHHHLLLLLLJJJJSSSSSSSSJJJJSSSTTTTTTTO
18:OLHHHLLLLLLJJJSTTOOOOOOTSSJJJJSSSTTTTTO
18:OLHHLLLLLLJJSTTO......OTSSJJJJJSSSTTTTO
18:OLHHLLLLLJJSTO.........OTSJJJJJSSSTTTTO
18:OLHLLLLLLJJSTO.........OTSJJJJJSSSTTTTO
18:OLHLLLLLLJJSTO.........OTSJJJJJSSSTTTTO
18:OLHLLLLLLJJSTTO.......OTSSJJJJJSSSTTTTO
18:OLLLLLLLLJJJSSTOO...OOTSSJJJJJJSSSTTTTO
19:OLLLLLLLLJJJJSSSTOOOTTSSJJJJJJSSSTTTTO
19:OLLHLLLLLLJJJJSSSTTTSSSJJJJJJSSSTTTTO
20:OLLHHLLLLLLJJJJJJJJJJJJJJJJJSSSTTTTTO
21:OLLHHHLLLLLLJJJJJJJJJJJJJJJSSSTTTTTO
22:OLLHHHHLLLLLLJJJJJJJJJJJJJSSSTTTTTO
23:OOLHHHHLLLLLLLJJJJJJJJJJSSSTTTTTOO
24:OOBGYYYGGBBGYYYGGBBGYYYGGBBGGGGTTOO
26:OOBGYYYYGGBGYYYYGGBGYYYYGGBGGGBTTOO
28:OOBGGYYGGBBGGYYGGBBGGYYGGBGGGTTOO
30:OOBBBBBBBBBBBBBBBBBBBBBBBBDDTOO
32:OOOTTTTTTTTTTTTTTTTTTTTTTTOOO
35:OOOOTTTTTTTTTTTTTTTTOOOOO
39:OOOOOOOOOOOOOOOO
''')
save('windup',WINDUP_UP,COIL_COMPRESS,TAIL_REST,LAMP_REST)

# Propulsive hop: high front neck, flattened rear thrust coil and a lifted tail.
MOVE_UP=rows(22, '''
58:OOOOOOOOOO
55:OOOLHHHHHHLLLOOO
53:OOLHHHHHHHLLLLLLJJOO
52:OLHHHHHHLLLLLLLLJJJJOO
51:OLHHHHLLLLLLLLJJJJJJJSOO
50:OLHHHLLLLLLLLJJJJJJJSSSOO
49:OLHHLLLLLLJJJJJJJJJJJJJJOO
48:OLHHLLLLJJJJJJJTTOOJJJJJJJOO
47:OLHHLLLJJJJJJJTOKKKOJJJTOOJJJOO
46:OLHHLLJJJJJJJJTKKKKOJJTOKKOJJJJO
45:OLHHLLJJJJJJJJTKKKKOJJTOKKOJJJSSO
44:OLHHLLJJJJJJJJJTOOOJJJJTOOJJJSSSO
43:OLHHLLJJJJJJJJJJJJJJJJJJJJJJSSSTO
42:OLHHLLJJJJJJJJJJSSSSSTTOOOOOOOTTO
41:OLHHLLJJJJJJSSSSSTTTTOBGGGGGGBDO
40:OLHHLLJJJJJSSSSSTTTOBGYYYYGGBDO
39:OLHHLLJJJJSSSSSTTTOBGYYYGGBDOO
38:OLHHLLJJJJSSSSTTTOBGYYYGBOO
37:OLHHLLJJJJSSSTTTOBGYYGBOO
36:OLHHLLJJJJSSSTTOBGYYYBO
35:OLHHLLJJJJSSSTTOBGGYYBO
34:OLHHHLLJJJSSSTTOBGYYYBO
33:OLHHHLLJJJJSSSTTOBGYYBO
32:OLHHHLLLJJJJSSSTTOBGYBO
31:OLHHHLLLLJJJJSSSTTOBGBO
30:OLHHHLLLLLJJJJSSSTTOBBO
29:OLHHHLLLLLLJJJJSSSTTOBO
28:OLHHHLLLLLLLJJJJSSSTTTOO
27:OLHHHLLLLLLLLJJJJSSSTTTTOO
26:OLHHHLLLLLLLLLJJJJSSSTTTTTOO
25:OLHHHLLLLLLLLLLJJJJSSSTTTTTOO
24:OLHHHLLLLLLLLLLLJJJJSSSTTTTTOO
23:OLHHHLLLLLLLLLLLLJJJJSSSTTTTTOO
22:OLHHHLLLLLLLLLLLLLJJJJSSSTTTTTOO
21:OLHHHLLLLLLLLLLLLLLJJJJSSSTTTTTOO
21:OLHHHLLLLLLLLLLLLLLLJJJJSSSTTTTTOO
''')
COIL_PUSH=rows(58, '''
20:OOOLHHHHLLLLLLLLLLLLJJJJJJJSSSTTTOOO
18:OOLHHHHHLLLLLLLLLLLLLJJJJJJJJSSSTTTTOOO
17:OLHHHHHLLLLLLLLLLLLLJJJJJJJJJJJSSSTTTTTOO
16:OLHHHHLLLLLLLLLLLLLJJJJJJJJJJJJJJSSSTTTTTOO
16:OLHHHLLLLLLLLLLLLJJJJJJJJJJJJJJJJSSSTTTTTTOO
15:OLHHLLLLLLLLLLJJJJJJJJJJJJJJJJJJJJSSSTTTTTTO
15:OLHHLLLLLLLLJJJJJJSSSSSSSSSSSSJJJJJSSSTTTTTTO
15:OLHHLLLLLLJJJJJSSTTOOOOOOOOOOTTSSJJJJSSSTTTTTO
15:OLHHLLLLJJJJJSSTTO..........OTTSSJJJJSSSTTTTTO
16:OLHLLLLJJJJJSSTO.............OTSJJJJJSSSTTTTTO
16:OLLLLLJJJJJSSTO...............OTSJJJJSSSTTTTTO
17:OLLLLJJJJJSSTO................OTSJJJJSSSTTTTTO
18:OLLJJJJJJSSTO..................OTSJJJJSSSTTTTTO
19:OLJJJJJJSSTO...................OTSJJJJSSSTTTTTO
20:OSJJJJJSTTO....................OTSJJJJSSSTTTTTO
21:OSJJJJJSTTO...................OTSSJJJJSSSTTTTTO
22:OSJJJJJSTTO..................OTSSJJJJSSSTTTTTO
23:OSJJJJJJSTTOO..............OOTSSJJJJJSSSTTTTTO
24:OSJJJJJJJSSTTOOO........OOOTTSSJJJJJSSSTTTTTO
25:OSJJJJJJJJJSSSTTTOOOOOOOTTSSSJJJJJJSSSTTTTTO
26:OSJJJJJJJJJJJSSSSTTTTTTSSSJJJJJJJJSSSTTTTOO
27:OSJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJSSSTTTTOO
28:OSLJJJJJJJJJJJJJJJJJJJJJJJJJJJJJSSSTTTTOO
29:OSLLLJJJJJJJJJJJJJJJJJJJJJJJJJJSSSTTTTOO
30:OOBGYYYGGBBGYYYGGBBGYYYGGBBGYYGGBGGGTTOO
32:OOBGYYYYGGBGYYYYGGBGYYYYGGBGYYGGBGGBTTOO
34:OOBGGYYGGBBGGYYGGBBGGYYGGBBGGGGGBDTTOO
36:OOBBBBBBBBBBBBBBBBBBBBBBBBBBBDDTTOO
38:OOOTTTTTTTTTTTTTTTTTTTTTTTTTTTOOO
42:OOOOTTTTTTTTTTTTTTTTTTTOOOOO
''')
TAIL_PUSH=rows(58, '''
15:OOSSJO
15:OSLJJSO
16:OSLJJJSO
17:OSLLJJJSO
18:OSLLLJJJSO
19:OSLLLJJJSO
20:OSLLLJJJSSO
21:OSLLLJJJSSO
21:OSLLLJJJSSO
21:OSLLLJJJJSSO
22:OSLLLJJJJSSO
23:OSLLLJJJJSSO
24:OSLLLJJJJSSO
25:OSLLLJJJJSSO
26:OSLLLJJJSSO
27:OSLLJJJSSO
28:OSLJJSSO
29:OSJSSO
''')
LAMP_PUSH=rows(38, '''
14:OOOOO
13:OBYGBO
13:OBGGBO
11:OOBGGGBOO
9:OOBYGGGGGBBOO
7:OOBYYYYGGGGGGBBOO
6:OBGGGGGGGGGGGGGBDO
6:OORRRRRRRRRRRRRDOO
7:OEFFFFFCFFFFFEEO
7:OEFFFCCWCFFFFEEO
6:OEFFFFCWCFFFFFEEO
6:OEFFFCCWCCFFFFEEO
6:OEFFFCCWCCFFFFEEO
6:OEFFFCCWCCFFFFEEO
6:OEFFFCCWCCFFFFEEO
7:OEFFFFCWCCFFFEEO
7:OEFFFFCCCFFFFEEO
8:OEFFFFFFFFFEEO
8:OOBGGGGGGGBDOO
10:OOBYYYGBDOO
12:OOBGBOO
13:OBYBO
13:OBGBO
14:OBO
''')
save('move',MOVE_UP,COIL_PUSH,TAIL_PUSH,LAMP_PUSH)

# Bite at full neck extension: upper and lower jaws separate, fangs arise from gum.
ATTACK_UP=rows(34, '''
64:OOOOOOOOOOOO
60:OOOLHHHHHHHHHLLLOOOO
57:OOOLHHHHHHHHLLLLLLLJJJOO
55:OOLHHHHHHHLLLLLLLLJJJJJJJOO
53:OOLHHHHHLLLLLLLLJJJJJJJJJSSOO
51:OOLHHHHLLLLLLLJJJJJJJJJJSSSSSOO
49:OOLHHHLLLLLLJJJJJJJJJJJJJJJJJJJJOO
47:OOLHHHLLLLJJJJJJJJJTOOJJJJJJJJJJJJJOO
45:OOLHHHLLLJJJJJJJJJTOKKKOJJJJTOOJJJJJJJO
43:OOLHHHLLJJJJJJJJJJTKKKKOJJJTOKKOJJJJJJJO
41:OOLHHHLLJJJJJJJJJJTKKKKOJJJTOKKOJJJJJSSO
39:OOLHHHLLJJJJJJJJJJJTOOOJJJJJJTOOJJJJSSSO
37:OOLHHHLLJJJJJJJJJJJJJJJJJJJJJJJJJJSSSTTO
35:OOLHHHLLJJJJJJJJJJJJSSSSSSSSSSTTOOOOOOOO
33:OOLHHHLLJJJJJJJJJJSSSSSTTOOOOOODWWWDDDDO
31:OOLHHHLLJJJJJJJJSSSSTTTOO.......DWWD...O
30:OLHHHLLJJJJJJJJSSSSTTTO..........DW....O
29:OLHHHLLJJJJJJJSSSSTTTO.................O
28:OLHHHLLJJJJJJSSSSTTTO.................DO
27:OLHHHLLJJJJJJSSSTTTO...........DW...DDO
26:OLHHHLLJJJJJJSSSTTOBGBO.......DWWDDDO
25:OLHHHLLJJJJJJSSSTTOBGYGBOOOOODWWWDDO
24:OLHHHLLJJJJJJSSSTTOBGYYYGGGGGBBDDGO
23:OLHHHLLLJJJJJSSSTTOBGYYYYYYYYGGBDO
22:OLHHHLLLLJJJJSSSTTOBGGYYYYYGGGBOO
21:OLHHHLLLLLJJJSSSTTOBGGGGGGBBDOO
20:OLHHHLLLLLLJJSSSTTOBBBBBDDOO
20:OLHHHLLLLLLLJJSSSTTTTOOOOO
20:OLHHHLLLLLLLLJJSSSTTTTOO
21:OLHHHLLLLLLLLLJJSSSTTTTOO
22:OLHHHLLLLLLLLLLJJSSSTTTTOO
23:OLHHHLLLLLLLLLLLJJSSSTTTTOO
24:OLHHHLLLLLLLLLLLLJJSSSTTTTOO
25:OLHHHLLLLLLLLLLLLLJJSSSTTTTOO
''')
COIL_STRIKE=rows(68, '''
24:OOOLHHHHLLLLLLLLLLJJJJJJJJSSSTTTOOO
22:OOLHHHHHLLLLLLLLLLLJJJJJJJJJSSSTTTTOOO
20:OOLHHHHHLLLLLLLLLLLJJJJJJJJJJJSSSTTTTTOO
19:OLHHHHHHLLLLLLLLLLJJJJJJJJJJJJJSSSTTTTTTO
18:OLHHHHHLLLLLLLLLLJJJJJJJJJJJJJJSSSTTTTTTTO
17:OLHHHHLLLLLLLLLJJJJJJJJJJJJJJJJJSSSTTTTTTTO
17:OLHHHLLLLLLLLJJJJJJSSSSSSSSSJJJJJSSSTTTTTTO
17:OLHHLLLLLLJJJJJSSTTOOOOOOOTTSSJJJJSSSTTTTTO
17:OLHLLLLLLJJJJSTTO........OTTSSJJJJSSSTTTTTO
17:OLHLLLLLJJJJSTTO..........OTSJJJJJSSSTTTTTO
17:OLLLLLLJJJJSTTO............OTSJJJJSSSTTTTTO
17:OLLLLLJJJJJSTTO............OTSJJJJSSSTTTTTO
18:OLLLLJJJJJJSTTO...........OTSSJJJJSSSTTTTTO
19:OLLJJJJJJJJSTTOO........OOTSSJJJJJSSSTTTTO
20:OLJJJJJJJJJJSSTTOOOOOOOOTTSSJJJJJJSSSTTTTO
21:OSJJJJJJJJJJJSSSTTTTTTTSSSJJJJJJJSSSTTTTO
22:OSJJJJJJJJJJJJJJSSSSSSSJJJJJJJJJSSSTTTTO
23:OSLJJJJJJJJJJJJJJJJJJJJJJJJJJJJSSSTTTTO
24:OSLLLJJJJJJJJJJJJJJJJJJJJJJJJJSSSTTTTO
25:OOBGYYYGGBBGYYYGGBBGYYYGGBBGYYGGBGGGTTO
27:OOBGYYYYGGBGYYYYGGBGYYYYGGBGYYGGBGGBTTO
29:OOBGGYYGGBBGGYYGGBBGGYYGGBBGGGGGBDTTO
31:OOBBBBBBBBBBBBBBBBBBBBBBBBBBBDDTTOO
34:OOOTTTTTTTTTTTTTTTTTTTTTTTTTOOO
38:OOOOOTTTTTTTTTTTTTTTTOOOOO
''')
save('attack',ATTACK_UP,COIL_STRIKE,TAIL_REST,LAMP_REST)

RECOVER_UP=rows(19, '''
49:OOOOOOOOOOO
46:OOOLLLHHHHHHLLLOOO
44:OOLLLHHHHHHHHLLLLLJJOO
43:OLLHHHHHHHLLLLLLLJJJJJOO
42:OLHHHHHHLLLLLLLLJJJJJJJSOO
41:OLHHHHLLLLLLLLLJJJJJJJSSSO
41:OHHHHLLLLLLLLJJJJJJJJSSSSOO
40:OLHHLLLLLLLJJJJJJJJJJJJJJJOO
40:OLHLLLLLLJJJJJTTOOJJJJJJJJJJOO
40:OLLLLLLLJJJJJTOKKKOJJJTOOJJJJJO
40:OLLLLLJJJJJJJTKKKKOJJTOKKOJJJJJO
40:OLLLLJJJJJJJJTKKKKOJJTOKKOJJJJSO
40:OLLJJJJJJJJJJJTOOOJJJJTOOJJJJSSO
40:OLJJJJJJJJJJJJJJJJJJJJJJJJJJSSSO
40:OJJJJJJJJJJJJJJJJJJJSSSSJJJJTTO
40:OJJJJJJJJJJJJSSSSSTTOOOOOOOOOTTO
40:OJJJJJJJJJJSSSSSTTTOBGGGGGGGBDO
40:OSJJJJJJJSSSSSTTTOBYYYYGGGGBDO
39:OLJJJJJJSSSSSTTTOBGYYYYGGBDOO
38:OLLJJJJSSSSSTTTOBGGYYGGBDOO
37:OLLLJJJSSSSSTTTOBGYYYGBDO
36:OLLLJJJJSSSSTTTOBGYYGBO
35:OLLLJJJJSSSSTTOBGYYYBO
34:OLLLJJJJSSSSTTOBGGYYBO
33:OLLLJJJJSSSSTTOBGYYYBO
32:OLLLLJJJSSSSTTOBGYYYBO
31:OLLLLJJJJSSSTTOBGGYYBO
31:OLLHLJJJJSSSTTOBGYYYBO
31:OLLHLLJJJSSSTTOBGYYYBO
31:OLLHLLJJJSSSTTOBGGYYBO
32:OLHHLLJJJSSSTTOBGYYYBO
32:OLHHLLJJJJSSSTTOBGYYYBO
33:OLHHLLJJJJSSSTTOBGGYYBO
33:OLHHLLLJJJJSSSTTOBGYYYBO
34:OLHHLLLJJJJSSSTTOBGYYYBO
35:OLHHLLLLJJJJSSSTTOBGGYYBO
36:OLHHLLLLJJJJSSSTTOBGYYYBO
37:OLHHLLLLJJJJSSSTTOBGYYYBO
38:OLHHLLLLJJJJSSSTTOBGGYYBO
39:OLHHLLLLJJJJSSSTTOBGYYYBO
40:OLHHLLLLJJJJSSSTTOBGYYYBO
40:OLHHLLLLJJJJSSSTTOBGGYYBO
39:OLHHLLLLJJJJJSSSTTOBGYYBO
38:OLHHLLLLJJJJJJSSSTTOBGYBO
36:OOLHLLLLJJJJJJJJSSSTTOBO
''')
save('recover',RECOVER_UP,COIL_REST,TAIL_REST,LAMP_REST,[(43,69,'LLLLJJJJJJJ'),(58,31,'SSJSSS')])

HIT_UP=rows(18, '''
34:OOOOOOOOOO
31:OOOLHHHHHLLLOOO
29:OOLHHHHHHLLLLLJOO
28:OLHHHHHLLLLLLJJJJOO
27:OLHHHHLLLLLJJJJJJJOO
26:OLHHHLLLLLJJJJJJJJSSOO
25:OLHHLLLLJJJJJJJJJJSSSSO
24:OLHHLLLLJJJTOOOJJJJJJJJOO
24:OLHHLLLJJJTOKKOJJJTOOJJJJOO
24:OLHHLLJJJJJTOOOJJJTOKOJJJJJO
24:OLHHLLJJJJJJJJJJJJJTOJJJJJSSO
24:OLHHLLJJJJJJJJJJJJJJJJJJSSSTO
24:OLHHLLJJJJJJJJJSSSSSTTOOOOOTO
25:OLHHLLJJJJJJSSSSTTTOODWWDDDO
25:OLHHLLJJJJSSSSTTTO...DWD..O
26:OLHHLLJJJJSSSTTTO........DO
27:OLHHLLJJJJSSSTTOBGBO...DDO
28:OLHHLLJJJJSSSTTOBGYGBBBOO
29:OLHHLLJJJJSSSTTOBGYYYGBO
30:OLHHLLJJJJSSSTTOBGGYYBO
31:OLHHLLJJJJSSSTTOBGYYYBO
32:OLHHLLJJJJSSSTTOBGYYYBO
33:OLHHLLJJJJSSSTTOBGGYYBO
34:OLHHLLJJJJSSSTTOBGYYYBO
35:OLHHLLJJJJSSSTTOBGYYYBO
36:OLHHLLJJJJSSSTTOBGGYYBO
37:OLHHLLJJJJSSSTTOBGYYYBO
38:OLHHLLJJJJSSSTTOBGYYYBO
39:OLHHLLJJJJSSSTTOBGGYYBO
40:OLHHLLJJJJSSSTTOBGYYYBO
41:OLHHLLJJJJSSSTTOBGYYYBO
42:OLHHLLJJJJSSSTTOBGGYYBO
43:OLHHLLJJJJSSSTTOBGYYYBO
44:OLHHLLJJJJSSSTTOBGYYYBO
44:OLHHLLJJJJSSSTTOBGGYYBO
44:OLHHLLJJJJSSSTTOBGYYYBO
44:OLHHLLLJJJJSSSTTOBGYYYBO
44:OLHHLLLJJJJSSSTTOBGGYYBO
43:OLHHLLLLJJJJSSSTTOBGYYBO
42:OLHHLLLLJJJJJSSSTTOBGYBO
41:OLHHLLLLJJJJJJSSSTTOBGBO
40:OLHHLLLLJJJJJJJSSSTTOBO
39:OLHHLLLLJJJJJJJJSSSTTTOO
38:OLHHLLLLJJJJJJJJJSSSTTTTOO
37:OLHHLLLLJJJJJJJJJJSSSTTTTOO
36:OLHHLLLLJJJJJJJJJJJSSSTTTTOO
''')
HIT_COIL_EDIT=rows(66, '''
27:OOLHHHHHLLLLLJJJJJJJJJJJSSSTTTTTOO
25:OOLHHHHHHLLLLLJJJJJJJJJJJJSSSTTTTTOO
24:OLHHHHHHLLLLLLJJJJJJJJJJJJJSSSTTTTTOO
23:OLHHHHHLLLLLLJJJJJJJJJJJJJJJSSSTTTTTOO
''')
save('hit',HIT_UP,COIL_REST,TAIL_REST,LAMP_REST,HIT_COIL_EDIT,[(12,53,'FFCCCWCF'),(12,54,'FFFCCWCF')])

# Collapsed original body, tail loop and dim lamp; head lies on the front coil.
DEAD_BODY=rows(70, '''
42:OOOOOOOOOOOO
36:OOOOJJJJJJJSSSOOOOO
31:OOOJJJJLLLLLLJJJJSSSTTOOO
28:OOJJJLLLLLLLLLJJJJJJSSSTTTOOO
26:OJLLLLLLLLLLLLJJJJJJJJSSSTTTTOOO
24:OJLLLLLLLLLLLJJJJJJJJJJSSSTTTTTOOO
23:OLLLLLLLLLLJJJJJJJJJJJJJJSSSTTTTTTOO
22:OLLLLLLLLJJJJSSSSSSSSSSJJJJSSSTTTTTTOO
21:OLLLLLLJJJJSSTTOOOOOOTSSSJJJJSSSTTTTTTOO
20:OLLLLLJJJSSTTO......OTTSSJJJJJSSSTTTTTTOO
20:OLLLLJJJSSTO.........OTSJJJJJJSSSTTTTTTTOO
20:OLLJJJJJSSTO..........OTSJJJJJSSSTTTTTTTOO
20:OLJJJJJJSTTO..........OTSJJJJJSSSTTTTTTTOO
20:OSJJJJJJSTTO.........OTSSJJJJJSSSTTTTTTTOO
21:OSJJJJJJJSSTOO.....OOTSSJJJJJJSSSTTTTTTTOO
22:OSJJJJJJJJSSSTOOOOOTTSSJJJJJJJSSSTTTTTTTOO
23:OSJJJJJJJJJJSSSTTTSSSJJJJJJJJSSSTTTTTTTOO
24:OSLJJJJJJJJJJJJJJJJJJJJJJJJJSSSTTTTTTTOO
25:OOBGGGGGBBGGGGGGBBGGGGGGBBGGGGGGBDTTOO
27:OOBGGGGGGBGGGGGGGBGGGGGGGBGGGGGBDDTOO
29:OOBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDTOO
32:OOOTTTTTTTTTTTTTTTTTTTTTTTTTTTOOO
37:OOOOOOOOOOOOOOOOOOOOOOOOOOO
''')
DEAD_HEAD=rows(72, '''
65:OOOOOOOOOOO
62:OOOLLLLLLLLLJJOOO
60:OOLLLLLLLLLJJJJJJOOO
59:OLLLLLLLLJJJJJJJJJJSSOO
58:OLLLLLLJJJJJJJJJJJJSSSSOO
57:OLLLLLJJJJJJJJJJJJJJSSSSSOO
57:OLLLLJJJJJJJTTTJJJJJJJJJJJOO
56:OLLLLJJJJJJTTTTJJJJJTTJJJJJJO
56:OLLLJJJJJJJJJJJJJJJTTTJJJJJSSO
55:OLLLJJJJJJJJJJJJJJJJJJJJJJSSSO
54:OLLLJJJJJJJJJJJJJJSSSSJJJJSTTO
53:OLLLJJJJJJJJJSSSSTTTOOOOOOOTTO
52:OLLLJJJJJJSSSSTTTOBGGGGGGGBDO
51:OLLLJJJJSSSSTTTOBGGGGGGBDDOO
51:OSJJJJSSSTTTTOOBBBBBBDDOOO
52:OOSSSSSTTTOOOOTTTTTOOO
54:OOOTTTTTOOOOOOOOOO
''')
DEAD_TAIL=rows(75, '''
17:OOOOOO
15:OOSLJJSSOO
14:OSLLLJJJSSOO
13:OSLLLJJJJJSSO
13:OSLLJJJSTTJSSO
13:OSLJJSTTOOTJSSO
14:OSJJSTO..OTJSSO
15:OSJSTO..OTJJSSO
16:OSJSTOOOTJJJSSO
17:OSJJSSSJJJJSSO
18:OSLJJJJJJJSSO
19:OSLLJJJJJSSO
20:OSLLJJJJSSO
21:OSLJJJJSSO
22:OSJJJJSSO
''')
DEAD_LAMP=rows(78, '''
5:OOO
4:OBBOOO
4:OBGGBBOOOO
4:OBGGGBEFFEBOO
5:OBGGBEEFFFFEBO
6:OBGBEEFFCCFEBO
7:OBGEEFFFCCFEBO
7:OBGEEFFFFFFEBO
6:OBGGBEEFFFFEBO
5:OBGGGBEEEEBBO
5:OBBBBBBGBBBO
6:OOOOOOOBBO
''')
save('dead',DEAD_BODY,DEAD_TAIL,DEAD_LAMP,DEAD_HEAD)

# Tucked sleeping head: two short lids drawn in jade shadow, separated from nostril.
SLEEP_UP=rows(47, '''
49:OOOOOOOOOO
46:OOOLHHHHHLLLOOO
44:OOLHHHHHHLLLLLLJOO
42:OOLHHHHHLLLLLLLLJJOO
40:OOLHHHHLLLLLLLJJJJJJOO
39:OLHHHHLLLLLLJJJJJJJJJSOO
38:OLHHHLLLLLJJJJJJJJJJJSSSOO
37:OLHHLLLLJJJJJJJJJJJJJJJJJJOO
36:OLHHLLLLJJJJJJJJJJJJJJJJJJJJOO
35:OLHHLLLJJJJJJJJJJJJJJJJJJJJJJJOO
35:OLHHLLJJJJJJJTTTTJJJJJTTJJJJJJJO
35:OLHHLLJJJJJJJJJJJJJJJJJJJJJJJJSSO
35:OLHHLLJJJJJJJJJJJJJJJJJJJJJJJJSSO
35:OLHHLLJJJJJJJJJJJJJJJJSSSJJJJTTO
35:OLHHLLJJJJJJJJJJSSSSSTTOOOOOOOTTO
35:OLHHLLJJJJJJJSSSSTTTTOBGGGGGGBDO
36:OLHHLLJJJJJSSSSTTTOBGYYYGGBDOO
37:OLHHLLJJJJSSSSTTTOBGYYYGBOO
38:OLHHLLJJJJSSSTTTOBGYYGBOO
38:OLHHLLJJJJSSSTTOBGYYYBO
38:OLHHHLLJJJJSSSTTOBGYYBO
37:OLHHHLLLJJJJSSSTTOBGYBO
36:OLHHHLLLLJJJJSSSTTOBGBO
35:OLHHHLLLLLJJJJSSSTTOBBO
34:OLHHHLLLLLLJJJJSSSTTOBO
''')
SLEEP_COIL_EDIT=rows(72, '''
21:OLHHHHLLLLJJJJSSSSSSSSSJJJJJJJSSSTTTTTTTO
21:OLHHHLLLLJJJSTTOOOOOOOTTSSJJJJJJSSSTTTTTTO
''')
LAMP_SLEEP_EDIT=rows(50, '''
9:OEFFFFFFFFFFFEEO
9:OEFFFFFCCFFFFEEO
8:OEFFFFFCCFFFFFEEO
8:OEFFFFFCCFFFFFEEO
8:OEFFFFFCCFFFFFEEO
8:OEFFFFFCCFFFFFEEO
8:OEFFFFFCCFFFFFEEO
9:OEFFFFFCCFFFFEEO
9:OEFFFFFFFFFFFEEO
''')
save('sleep_a',COIL_REST,TAIL_REST,LAMP_REST,SLEEP_UP,SLEEP_COIL_EDIT,LAMP_SLEEP_EDIT)
SLEEP_B_EDIT=rows(49, '''
43:OOLHHHHHHLLLLLLLJJOO
41:OOLHHHHHLLLLLLLLLJJJOO
39:OOLHHHHLLLLLLLLJJJJJJJOO
38:OLHHHHLLLLLLLJJJJJJJJJSSOO
''')+rows(67, '''
38:OLHHHLLLJJJJSSSTTOBGYYBO
37:OLHHHLLLLJJJJSSSTTOBGYBO
36:OLHHHLLLLLJJJJSSSTTOBGBO
35:OLHHHLLLLLLJJJJSSSTTOBBO
34:OLHHHLLLLLLLJJJJSSSTTOBO
''')+[(34,81,'LLLLJJJJJJ'),(35,82,'LLLLLJJJJJ')]
save('sleep_b',COIL_REST,TAIL_REST,LAMP_REST,SLEEP_UP,SLEEP_COIL_EDIT,LAMP_SLEEP_EDIT,SLEEP_B_EDIT)

# Sick neck held tightly back, contracted throat and a slack, bruised-colored mouth.
POISON_UP=rows(29, '''
46:OOOOOOOOOOO
43:OOOLHHHHHHLLLOOO
41:OOLHHHHHHHLLLLLLJOO
40:OLHHHHHHLLLLLLLLJJJOO
39:OLHHHHLLLLLLLLJJJJJJJOO
38:OLHHHLLLLLLJJJJJJJJJJSSOO
37:OLHHLLLLLJJJJJJJJJJJJSSSSOO
36:OLHHLLLLJJJJJJJJJJJJJJJJJJJOO
35:OLHHLLLJJJJJJJJJTTTOJJJJJJJJJOO
34:OLHHLLJJJJJJJJJTOKKOJJJJTTOJJJJJO
33:OLHHLLJJJJJJJJJJTOOOJJJTTKOJJJJJSO
32:OLHHLLJJJJJJJJJJJJJJJJJJTOOJJJJSSO
31:OLHHLLJJJJJJJJJJJJJJJJJJJJJJJJSSSO
30:OLHHLLJJJJJJJJJJJSSSSSSJJJJJJJSTTO
29:OLHHLLJJJJJJJJSSSSSTTTOOOOOOOOOTTTO
28:OLHHLLJJJJJJSSSSSTTTOOPPPPPPPPDOO
27:OLHHLLJJJJJSSSSSTTTOBGGYYGGBDOO
26:OLHHLLJJJJSSSSTTTOBGYYYGGBDOO
25:OLHHLLJJJJSSSTTTOBGYYYGBOO
25:OLHHLLJJJJSSSTTOBGYYGBOO
25:OLHHHLLJJJSSSTTOBGYYYBO
25:OLHHHLLJJJSSSTTOBGGYYBO
26:OLHHHLLJJJJSSSTTOBGYYYBO
27:OLHHHLLLJJJJSSSTTOBGYYBO
28:OLHHHLLLLJJJJSSSTTOBGYBO
29:OLHHHLLLLLJJJJSSSTTOBGBO
30:OLHHHLLLLLLJJJJSSSTTOBBO
31:OLHHHLLLLLLLJJJJSSSTTOBO
32:OLHHHLLLLLLLLJJJJSSSTTTOO
33:OLHHHLLLLLLLLLJJJJSSSTTTTOO
34:OLHHHLLLLLLLLLLJJJJSSSTTTTTOO
34:OLHHHLLLLLLLLLLLJJJJSSSTTTTTOO
34:OLHHHLLLLLLLLLLLLJJJJSSSTTTTTOO
34:OLHHHLLLLLLLLLLLLLJJJJSSSTTTTTOO
34:OLHHHLLLLLLLLLLLLLLJJJJSSSTTTTTOO
''')
BUBBLES_A=rows(24, '''
77:PPPP
76:PNNPP
75:PN..PP
75:PN...P
75:PP..PP
76:PPPPP
77:PPP
''')+rows(45, '''
81:PPP
80:PNNPP
79:PN..PP
79:PN...P
79:PP..PP
80:PPPPP
81:PPP
''')+[(69,51,'PNP'),(68,52,'P.P'),(69,53,'PP'),(74,62,'PP'),(73,63,'PNP'),(74,64,'PP')]
POISON_COIL_EDIT=rows(68, '''
25:OLHHHHHLLLLLLLJJJJJJJJJJJJSSSTTTTTTO
24:OLHHHHLLLLLLLJJJJJJJJJJJJJSSSTTTTTTO
23:OLHHHHLLLLLLJJJJJJJJJJJJJJSSSTTTTTTTO
''')
save('poison_a',POISON_UP,COIL_REST,TAIL_REST,LAMP_REST,POISON_COIL_EDIT,BUBBLES_A)
POISON_B_UP=rows(31, '''
45:OOOOOOOOOOO
42:OOOLHHHHHHLLLOOO
40:OOLHHHHHHHLLLLLLJOO
39:OLHHHHHHLLLLLLLLJJJOO
38:OLHHHHLLLLLLLLJJJJJJJOO
37:OLHHHLLLLLLJJJJJJJJJJSSOO
36:OLHHLLLLLJJJJJJJJJJJJSSSSOO
35:OLHHLLLLJJJJJJJJJJJJJJJJJJJOO
34:OLHHLLLJJJJJJJJJTTTOJJJJJJJJJOO
33:OLHHLLJJJJJJJJJTOKKOJJJJTTOJJJJJO
32:OLHHLLJJJJJJJJJJTOOOJJJTTKOJJJJJSO
31:OLHHLLJJJJJJJJJJJJJJJJJJTOOJJJJSSO
30:OLHHLLJJJJJJJJJJJJJJJJJJJJJJJJSSSO
29:OLHHLLJJJJJJJJJJJSSSSSSJJJJJJJSTTO
28:OLHHLLJJJJJJJJSSSSSTTTOOOOOOOOOTTTO
27:OLHHLLJJJJJJSSSSSTTTOOPPPPNPPPDOO
26:OLHHLLJJJJJSSSSSTTTOBGGYYGGBDOO
25:OLHHLLJJJJSSSSTTTOBGYYYGGBDOO
25:OLHHLLJJJJSSSTTTOBGYYYGBOO
25:OLHHLLJJJJSSSTTOBGYYGBOO
26:OLHHHLLJJJSSSTTOBGYYYBO
27:OLHHHLLJJJSSSTTOBGGYYBO
28:OLHHHLLJJJJSSSTTOBGYYYBO
29:OLHHHLLLJJJJSSSTTOBGYYBO
30:OLHHHLLLLJJJJSSSTTOBGYBO
31:OLHHHLLLLLJJJJSSSTTOBGBO
32:OLHHHLLLLLLJJJJSSSTTOBBO
33:OLHHHLLLLLLLJJJJSSSTTOBO
34:OLHHHLLLLLLLLJJJJSSSTTTOO
34:OLHHHLLLLLLLLLJJJJSSSTTTTOO
34:OLHHHLLLLLLLLLLJJJJSSSTTTTTOO
34:OLHHHLLLLLLLLLLLJJJJSSSTTTTTOO
34:OLHHHLLLLLLLLLLLLJJJJSSSTTTTTOO
''')
BUBBLES_B=rows(19, '''
73:PPP
72:PNPPP
71:PN...P
71:P....P
71:PP..PP
72:PPPPP
''')+rows(36, '''
85:PPPP
84:PNNPPP
83:PN...PP
83:PN....P
83:PP...PP
84:PPPPPP
85:PPPP
''')+rows(57, '''
76:PPP
75:PNPP
75:P..P
75:PPPP
76:PP
''')+[(70,49,'PP'),(69,50,'PNP'),(70,51,'PP'),(79,68,'PP')]
save('poison_b',POISON_B_UP,COIL_REST,TAIL_REST,LAMP_REST,POISON_COIL_EDIT,BUBBLES_B,[(39,83,'JJJJSSSSS')])

STUN_UP=rows(30, '''
43:OOOOOOOO
40:OOOLHHHHLLLOO
38:OOLHHHHHHLLLLJOO
36:OOLHHHHHLLLLLLJJOO
35:OLHHHHHLLLLLLJJJJOO
34:OLHHHHLLLLLLJJJJJJOO
33:OLHHHLLLLLLJJJJJJJJJOO
32:OLHHLLLLLLJJJJJJJJJJJOO
31:OLHHLLLLLJJJJJJJJJJJJSSOO
30:OLHHLLLLJJJJJJJJJJJJJJSSSOO
29:OLHHLLLJJJJJJJJJJJJJJJJJJJOO
28:OLHHLLJJJJJJJJJJJJJJJJJJJJJJOO
28:OLHHLLJJJJJJJJJJJJTTJJJJJJJJJJO
28:OLHHLLJJJJJJJJJJJJJTTJJJJJJJJJJO
28:OLHHLLJJJJJJJJJJJJJJTTJJJJJTTJJJO
28:OLHHLLJJJJJJJJJJJJJJJJJJJJJJTTJJO
28:OLHHLLJJJJJJJJSSSJJJJJJJJJJJJJJSSO
28:OLHHLLJJJJJJSSSSTTSSJJJJJJJJJJSSSO
29:OLHHLLJJJJSSSSTTTOOTSSJJJJJJJSSSTO
30:OLHHLLJJJJSSSTTTOBGBOOTSJJJJSSTTO
31:OLHHLLJJJJSSSTTOBGYGBOOOTTTTOOTO
32:OLHHLLJJJJSSSTTOBGYYYGGBOOOOOOOO
33:OLHHLLJJJJSSSTTOBGGYYYYYGGBBDOO
34:OLHHLLJJJJSSSTTOBGYYYYGGBBDOO
35:OLHHLLJJJJSSSTTOBGYYGGBOOO
36:OLHHLLLJJJJSSSTTOBGYGBOO
37:OLHHLLLLJJJJSSSTTOBGBOO
38:OLHHLLLLJJJJSSSTTOBBO
39:OLHHLLLLJJJJSSSTTOBO
40:OLHHLLLLJJJJSSSTTTOO
40:OLHHLLLLLJJJJSSSTTTTOO
40:OLHHLLLLLLJJJJSSSTTTTTOO
39:OLHHLLLLLLLJJJJSSSTTTTTOO
38:OLHHLLLLLLLLJJJJSSSTTTTTOO
''')
STARS_A=rows(15, '''
42:D
41:DGD
40:DGYYD
38:DGGYYYYYGD
40:DGYYD
41:DGD
42:D
''')+rows(28, '''
77:G
77:Y
75:GYYYY
77:Y
77:G
''')+[(65,13,'GY'),(66,14,'YG'),(29,26,'GY'),(28,27,'YG')]
save('stun_a',STUN_UP,COIL_REST,TAIL_REST,LAMP_REST,STARS_A,[(13,53,'FFCCCF'),(13,54,'FFFFCF')])
STUN_B_EDIT=rows(41, '''
28:OLHHLLJJJJJJJJJJJJJJJJJJJJJJOO
28:OLHHLLJJJJJJJJJJJJJJJTJJJJJJJJO
28:OLHHLLJJJJJJJJJJJJJJTTJJJJJJJJJO
28:OLHHLLJJJJJJJJJJJJJTTJJJJJJJTJJJO
28:OLHHLLJJJJJJJJJJJJJJJJJJJJTTJJJJO
28:OLHHLLJJJJJJJJSSSJJJJJJJJJJJJJJSSO
28:OLHHLLJJJJJJSSSSTTSSJJJJJJJJJJSSSO
29:OLHHLLJJJJSSSSTTTOOTSSJJJJJJJSSSTO
30:OLHHLLJJJJSSSTTTOBGBOOTSJJJJSSTTO
31:OLHHLLJJJJSSSTTOBGYGBOOOTSJSSSTTO
32:OLHHLLJJJJSSSTTOBGYYYGGBOOOTTOOTO
33:OLHHLLJJJJSSSTTOBGGYYYYYGGBBDOOO
''')+[(37,67,'LLLLJJJJJJJ'),(37,68,'LLLJJJJJJJJ')]
STARS_B=rows(18, '''
68:D
67:DGD
66:DGYYD
64:DGGYYYYYGD
66:DGYYD
67:DGD
68:D
''')+rows(25, '''
35:G
35:Y
33:GYYYY
35:Y
35:G
''')+[(49,12,'YG'),(48,13,'GY'),(80,35,'YG'),(79,36,'GY')]
save('stun_b',STUN_UP,COIL_REST,TAIL_REST,LAMP_REST,STUN_B_EDIT,STARS_B,[(13,53,'FFFFCF'),(13,54,'FFFCCF')])

# Skill preparation: straighter throat, slight gape and a hot teal lamp core.
SKILL_A_UP=rows(16, '''
48:OOOOOOOOOOO
45:OOOLLLHHHHHHLLLOOO
43:OOLLLHHHHHHHHLLLLLJJOO
42:OLLHHHHHHHLLLLLLLJJJJJOO
41:OLHHHHHHLLLLLLLLJJJJJJJSOO
40:OLHHHHLLLLLLLLLJJJJJJJSSSO
40:OHHHHLLLLLLLLJJJJJJJJSSSSOO
39:OLHHLLLLLLLJJJJJJJJJJJJJJJOO
39:OLHLLLLLLJJJJJTTOOJJJJJJJJJJOO
39:OLLLLLLLJJJJJTOKKKOJJJTOOJJJJJO
39:OLLLLLJJJJJJJTKKKKOJJTOKKOJJJJJO
39:OLLLLJJJJJJJJTKKKKOJJTOKKOJJJJSO
39:OLLJJJJJJJJJJJTOOOJJJJTOOJJJJSSO
39:OLJJJJJJJJJJJJJJJJJJJJJJJJJJSSSO
39:OJJJJJJJJJJJJJJJJJJJSSSSJJJJTTO
39:OJJJJJJJJJJJJSSSSSTTOOOOOOOOOTTO
39:OJJJJJJJJJJSSSSSTTTOOCCWWCFFEDO
39:OSJJJJJJJSSSSSTTTOBGGCCCCCGBDO
38:OLJJJJJJSSSSSTTTOBGYYYYGGBDOO
37:OLLJJJJSSSSSTTTOBGGYYGGBDOO
36:OLLLJJJSSSSSTTTOBGYYYGBDO
35:OLLLJJJJSSSSTTTOBGYYGBO
34:OLLLJJJJSSSSTTOBGYYYBO
33:OLLLJJJJSSSSTTOBGGYYBO
32:OLLLJJJJSSSSTTOBGYYYBO
32:OLLLLJJJSSSSTTOBGYYYBO
32:OLLLLJJJJSSSTTOBGGYYBO
32:OLLHLJJJJSSSTTOBGYYYBO
32:OLLHLLJJJSSSTTOBGYYYBO
32:OLLHLLJJJSSSTTOBGGYYBO
33:OLHHLLJJJSSSTTOBGYYYBO
33:OLHHLLJJJSSSTTOBGYYYBO
33:OLHHLLJJJSSSTTOBGGYYBO
33:OLHHLLJJJSSSTTOBGYYYBO
34:OLHHLLJJJSSSTTOBGYYYBO
34:OLHHLLJJJJSSSTTOBGGYYBO
35:OLHHLLJJJJSSSTTOBGYYYBO
35:OLLHLLLJJJSSSTTOBGYYYBO
36:OLLHLLLJJJJSSSTTOBGGYYBO
37:OLLHLLLLJJJSSSTTOBGYYYBO
38:OLLHLLLLJJJJSSSTTOBGYYYBO
38:OLLHLLLLJJJJSSSTTOBGGYYBO
38:OLLHLLLLJJJJSSSTTOBGYYYBO
38:OLLHLLLLJJJJSSSTTOBGYYYBO
38:OLLHLLLLJJJJSSSTTOBGGYYBO
37:OLLHLLLLJJJJJSSSTTOBGYYBO
36:OLLHLLLLJJJJJJSSSTTOBGYBO
35:OLLHLLLLJJJJJJJSSSTTOBGBO
''')
LAMP_CHARGE=rows(50, '''
9:OEFFCCWWCCFFFEEO
9:OEFCCWWWCCCFFEEO
8:OEFCCWWWWCCCFFEEO
8:OEFCCWWWWCCCFFEEO
8:OEFCCWWWWCCCFFEEO
8:OEFCCWWWWCCCFFEEO
8:OEFCCWWWWCCCFFEEO
9:OEFCCWWWCCCFFEEO
9:OEFFCCWWCCFFFEEO
''')+[(20,63,'CC'),(21,64,'CCF'),(22,65,'CCFF'),(23,66,'CCF'),(24,67,'CCFF'),(25,68,'CCF'),(26,69,'CCF'),(27,70,'CF')]
save('skill_a',SKILL_A_UP,COIL_REST,TAIL_REST,LAMP_REST,LAMP_CHARGE)

# Cast body drawn separately from bite. Both gas roots terminate at the open mouth.
SKILL_B_UP=rows(26, '''
45:OOOOOOOOOO
42:OOOLHHHHHHLLLOOO
40:OOLHHHHHHHLLLLLLJOO
39:OLHHHHHHLLLLLLLLJJJOO
38:OLHHHHLLLLLLLLJJJJJJJOO
37:OLHHHLLLLLLJJJJJJJJJJSSOO
36:OLHHLLLLLJJJJJJJJJJJJSSSSOO
35:OLHHLLLLJJJJJJJJJJJJJJJJJJJOO
34:OLHHLLLJJJJJJJJTTOOJJJJJJJJJJOO
33:OLHHLLJJJJJJJJTOKKKOJJJTOOJJJJJO
32:OLHHLLJJJJJJJJTKKKKOJJTOKKOJJJJJO
31:OLHHLLJJJJJJJJJTOOOJJJJTOOJJJJSSO
30:OLHHLLJJJJJJJJJJJJJJJJJJJJJJJSSSO
29:OLHHLLJJJJJJJJJJJSSSSSJJJJJJJSTTO
28:OLHHLLJJJJJJJJSSSSSTTTOOOOOOOOTTTO
27:OLHHLLJJJJJJSSSSSTTTOOCCWWWCCFFEO
26:OLHHLLJJJJJSSSSSTTTOCCWWWWCCFFEEO
25:OLHHLLJJJJSSSSTTTOBGCCWWWCCFEDDO
24:OLHHLLJJJJSSSTTTOBGYCCCCCGBDDOO
24:OLHHLLJJJJSSSTTOBGYYGGGGBDOO
24:OLHHHLLJJJSSSTTOBGYYYGBOO
24:OLHHHLLJJJSSSTTOBGGYYBO
25:OLHHHLLJJJJSSSTTOBGYYYBO
26:OLHHHLLLJJJJSSSTTOBGYYBO
27:OLHHHLLLLJJJJSSSTTOBGYBO
28:OLHHHLLLLLJJJJSSSTTOBGBO
29:OLHHHLLLLLLJJJJSSSTTOBBO
30:OLHHHLLLLLLLJJJJSSSTTOBO
31:OLHHHLLLLLLLLJJJJSSSTTTOO
32:OLHHHLLLLLLLLLJJJJSSSTTTTOO
33:OLHHHLLLLLLLLLLJJJJSSSTTTTTOO
34:OLHHHLLLLLLLLLLLJJJJSSSTTTTTOO
35:OLHHHLLLLLLLLLLLLJJJJSSSTTTTTOO
35:OLHHHLLLLLLLLLLLLLJJJJSSSTTTTTOO
35:OLHHHLLLLLLLLLLLLLLJJJJSSSTTTTTOO
35:OLHHHLLLLLLLLLLLLLLLJJJJSSSTTTTTOO
35:OLHHHLLLLLLLLLLLLLLLLJJJJSSSTTTTTOO
35:OLHHHLLLLLLLLLLLLLLLLLJJJJSSSTTTTTOO
''')
# Native breath cels: broken smoky hooks above, thick lower plume with split curling tip.
BREATH_FORK=rows(18, '''
88:FF
87:FCCF
86:FCWCF
85:FCWWCF
84:FCWWWCF
83:FCWWCCFF
83:FCWCCFFF
83:FCCCCFFE
84:FCCCFFE
84:FFCCFFE
83:EFFCCCFFE
82:EFFCCCCFFE
81:EFFCCWCCFFE
80:EFFCCWWCCFFE
79:EFFCCWWWCCFFE
78:EFFCCWWWCCCFFE
77:EFFCCWWWCCCFFEE
76:EFFCCWWWWCCCFFEE
75:EFFCCWWWWCCCFFEE
74:EFFCCWWWWCCCFFEEE
73:EFFCCWWWWCCCCFFEEE
72:EFFCCWWWWCCCCFFEEE
68:EEFFFCCWWWWCCCCFFFEEE
65:EFFCCWWWWWCCCCFFFFEEE
64:EFFCCWWWWCCCCFFFFEEE
65:EFFCCWWWCCFFFFEEE
67:EFFCCWWCCFFFEEE
69:EFFCCWWCCCFFEEE
71:EFFCCWWWWCCFFFEE
73:EFFCCWWWWWCCFFFEE
75:EFFCCWWWWWCCCFFFEE
77:EFFCCWWWWCCCCFFFEE
79:EFFCCWWCCFFFEE
80:EFFCCWCCFFEE
81:EFFCCCCFFEE
82:EFFCCCFFEE
82:EFFCCCFFEE
82:EFFCCFFEE
81:EFFCCFFEE
80:EFFCCCFFEE
79:EFFCCWCCFEE
78:EFFCCWWCFEE
78:EFFCCWCFEE
79:EFFCCCFEE
80:EFFCCFEE
81:EFFCFEE
82:EFFEE
83:EEE
''')
save('skill_b',SKILL_B_UP,COIL_REST,TAIL_REST,LAMP_REST,LAMP_CHARGE,BREATH_FORK)

SKILL_C_UP=rows(21, '''
51:OOOOOOOOOO
48:OOOLHHHHHHLLLOOO
46:OOLHHHHHHHLLLLLLJJOO
45:OLHHHHHHLLLLLLLLJJJJOO
44:OLHHHHLLLLLLLLJJJJJJJSOO
43:OLHHHLLLLLLLLJJJJJJJSSSOO
42:OLHHLLLLLLJJJJJJJJJJJJJJOO
41:OLHHLLLLJJJJJJJTTOOJJJJJJJOO
40:OLHHLLLJJJJJJJTOKKKOJJJTOOJJJOO
39:OLHHLLJJJJJJJJTKKKKOJJTOKKOJJJJO
38:OLHHLLJJJJJJJJTKKKKOJJTOKKOJJJSSO
37:OLHHLLJJJJJJJJJTOOOJJJJTOOJJJSSSO
36:OLHHLLJJJJJJJJJJJJJJJJJJJJJJSSSTO
35:OLHHLLJJJJJJJJJJSSSSSTTOOOOOOOTTO
34:OLHHLLJJJJJJSSSSSTTTTOBGGGGGGBDO
33:OLHHLLJJJJJSSSSSTTTOBGYYYYGGBDO
32:OLHHLLJJJJSSSSSTTTOBGYYYGGBDOO
31:OLHHLLJJJJSSSSTTTOBGYYYGBOO
30:OLHHLLJJJJSSSTTTOBGYYGBOO
29:OLHHLLJJJJSSSTTOBGYYYBO
29:OLHHLLJJJJSSSTTOBGGYYBO
29:OLHHHLLJJJSSSTTOBGYYYBO
29:OLHHHLLJJJJSSSTTOBGYYBO
29:OLHHHLLLJJJJSSSTTOBGYBO
30:OLHHHLLLLJJJJSSSTTOBGBO
31:OLHHHLLLLLJJJJSSSTTOBBO
32:OLHHHLLLLLLJJJJSSSTTOBO
33:OLHHHLLLLLLLJJJJSSSTTTOO
34:OLHHHLLLLLLLLJJJJSSSTTTTOO
35:OLHHHLLLLLLLLLJJJJSSSTTTTTOO
36:OLHHHLLLLLLLLLLJJJJSSSTTTTTOO
37:OLHHHLLLLLLLLLLLJJJJSSSTTTTTOO
38:OLHHHLLLLLLLLLLLLJJJJSSSTTTTTOO
39:OLHHHLLLLLLLLLLLLLJJJJSSSTTTTTOO
39:OLHHHLLLLLLLLLLLLLLJJJJSSSTTTTTOO
39:OLHHHLLLLLLLLLLLLLLLJJJJSSSTTTTTOO
39:OLHHHLLLLLLLLLLLLLLLLJJJJSSSTTTTTOO
38:OLHHHLLLLLLLLLLLLLLLLLJJJJSSSTTTTTOO
37:OLHHHLLLLLLLLLLLLLLLLLLJJJJSSSTTTTTOO
36:OLHHHLLLLLLLLLLLLLLLLLLLJJJJSSSTTTTTOO
35:OLHHHLLLLLLLLLLLLLLLLLLLLJJJJSSSTTTTTOO
34:OLHHHLLLLLLLLLLLLLLLLLLLLLJJJJSSSTTTTTOO
33:OLHHHLLLLLLLLLLLLLLLLLLLLLLJJJJSSSTTTTTOO
''')
BREATH_RESIDUE=rows(24, '''
84:FF
83:FCCF
82:FCWCF
82:FCCFF
83:FCFFE
84:FEEE
''')+rows(34, '''
80:FFE
79:FCCFFE
78:FCWWCFFE
78:FCCCCFFE
79:FFFFEEE
81:EEEE
''')+rows(50, '''
86:FF
85:FCCF
85:FCWCF
86:FCCCFE
87:FCFFE
87:FEEE
''')+rows(59, '''
84:FFE
83:FCCFE
82:FCWCCFE
82:FCCCCFE
83:FFFFEE
85:EEE
''')
save('skill_c',SKILL_C_UP,COIL_REST,TAIL_REST,LAMP_REST,BREATH_RESIDUE,[(13,53,'FCCWCC'),(13,54,'FCCCFF'),(22,65,'LCCJ')])

# Explicit visual repair pass. Each neck was redrawn at its own native coordinates.
# Resting throat now folds smoothly into abdominal plates, without a pointed spur.
IDLE_A_THROAT=rows(51, '''
35:OLLHLLLJJJJSSSTBGYYYBO..
36:OLLHLLLLJJJSSSTBGYYYBO..
37:OLLHLLLLJJJJSSSTBGGYYBO..
38:OLLHLLLLJJJJSSSTBGYYYBO..
39:OLLHLLLLJJJJSSSTBGYYYBO..
39:OLLHLLLLJJJJSSSTBGGYYBO...
39:OLLHLLLLJJJJSSSTBGYYYBO...
39:OLLHLLLLJJJJSSSTBGYYYBO...
38:OLLHLLLLJJJJJSSSTBGGYYBO..
37:OLLHLLLLJJJJJJSSSTBGYYYBO..
36:OLLHLLLLJJJJJJJSSSTBGYYYBO..
35:OLLHLLLLJJJJJJJJSSSTBGGYYBO..
34:OLLHLLLLJJJJJJJJJSSSTBGYYYBO..
''')
IDLE_B_THROAT=rows(51, '''
35:OLLHHLLJJJJSSSTBGYYYBO..
36:OLLHHLLLJJJSSSTBGYYYBO..
37:OLLHHLLLJJJJSSSTBGGYYBO..
38:OLLHHLLLJJJJSSSTBGYYYBO..
39:OLLHHLLLJJJJSSSTBGYYYBO..
39:OLLHHLLLJJJJSSSTBGGYYBO...
39:OLLHHLLLJJJJSSSTBGYYYBO...
39:OLLHHLLLJJJJSSSTBGYYYBO...
38:OLLHHLLLJJJJJSSSTBGGYYBO..
37:OLLHHLLLJJJJJJSSSTBGYYYBO..
36:OLLHHLLLJJJJJJJSSSTBGYYYBO..
35:OLLHHLLLJJJJJJJJSSSTBGGYYBO..
34:OLLHHLLLJJJJJJJJJSSSTBGYYYBO..
''')
IDLE_C_THROAT=rows(51, '''
35:OLLHLLLLJJJJSSSTBGGYYBO..
36:OLLHLLLLJJJJSSSTBGYYYBO..
37:OLLHLLLLJJJJJSSSTBGYYYBO..
38:OLLHLLLLJJJJSSSTBGGYYBO..
39:OLLHLLLLJJJJSSSTBGYYYBO..
39:OLLHLLLLJJJJSSSTBGYYYBO...
39:OLLHLLLLJJJJSSSTBGGYYBO...
39:OLLHLLLLJJJJSSSTBGYYYBO...
38:OLLHLLLLJJJJJSSSTBGYYYBO..
37:OLLHLLLLJJJJJJSSSTBGGYYBO..
36:OLLHLLLLJJJJJJJSSSTBGYYYBO..
35:OLLHLLLLJJJJJJJJSSSTBGYYYBO..
34:OLLHLLLLJJJJJJJJJSSSTBGGYYBO..
''')
save('idle_a',IDLE_UP,COIL_REST,TAIL_REST,LAMP_REST,IDLE_A_THROAT,[(64,59,'.')])
save('idle_b',IDLE_UP,COIL_REST,TAIL_REST,LAMP_REST,IDLE_B_EDIT,IDLE_B_THROAT,[(64,59,'.')])
save('idle_c',IDLE_UP,COIL_REST,TAIL_REST,LAMP_REST,IDLE_C_EDIT,IDLE_C_THROAT,[(64,59,'.')])

RECOVER_THROAT=rows(53, '''
34:OLHHLLLLJJJJSSSTBGYYYBO..
35:OLHHLLLLJJJJSSSTBGYYYBO..
36:OLHHLLLLJJJJSSSTBGGYYBO..
37:OLHHLLLLJJJJSSSTBGYYYBO..
38:OLHHLLLLJJJJSSSTBGYYYBO..
39:OLHHLLLLJJJJSSSTBGGYYBO..
39:OLHHLLLLJJJJSSSTBGYYYBO...
39:OLHHLLLLJJJJSSSTBGYYYBO...
38:OLHHLLLLJJJJJSSSTBGGYYBO..
37:OLHHLLLLJJJJJJSSSTBGYYYBO..
35:OOLHLLLLJJJJJJJJSSSTBGYYYBO..
''')
save('recover',RECOVER_UP,COIL_REST,TAIL_REST,LAMP_REST,RECOVER_THROAT,[(43,69,'LLLLJJJJJJJ'),(58,31,'SSJSSS')])

HIT_THROAT=rows(54, '''
44:OLHHLLLJJJJSSSTBGYYYBO..
44:OLHHLLLJJJJSSSTBGGYYBO..
43:OLHHLLLLJJJJSSSTBGYYBO..
42:OLHHLLLLJJJJJSSSTBGYBO..
41:OLHHLLLLJJJJJJSSSTBGBO..
40:OLHHLLLLJJJJJJJSSSTBBO..
39:OLHHLLLLJJJJJJJJSSSTBGBO..
38:OLHHLLLLJJJJJJJJJSSSTBGBO..
37:OLHHLLLLJJJJJJJJJJSSSTBGBO..
36:OLHHLLLLJJJJJJJJJJJSSSTBGBO..
''')
save('hit',HIT_UP,COIL_REST,TAIL_REST,LAMP_REST,HIT_COIL_EDIT,HIT_THROAT,[(12,53,'FFCCCWCF'),(12,54,'FFFCCWCF')])

SKILL_A_THROAT=rows(54, '''
36:OLLHLLLJJJJSSSTBGGYYBO..
37:OLLHLLLLJJJSSSTBGYYYBO..
38:OLLHLLLLJJJJSSSTBGYYYBO..
38:OLLHLLLLJJJJSSSTBGGYYBO..
38:OLLHLLLLJJJJSSSTBGYYYBO..
38:OLLHLLLLJJJJSSSTBGYYYBO..
38:OLLHLLLLJJJJSSSTBGGYYBO..
37:OLLHLLLLJJJJJSSSTBGYYYBO..
36:OLLHLLLLJJJJJJSSSTBGYYYBO..
35:OLLHLLLLJJJJJJJSSSTBGGYYBO..
''')
save('skill_a',SKILL_A_UP,COIL_REST,TAIL_REST,LAMP_REST,LAMP_CHARGE,SKILL_A_THROAT)

# Remove the visible horizontal shelf at cast and recovery neck/coil overlaps.
SKILL_B_NECK_REPAIR=rows(51, '''
28:OLHHHLLLLLJJJJSSSTBGBO..
29:OLHHHLLLLLLJJJJSSSTBBO..
30:OLHHHLLLLLLLJJJJSSSTBGBO..
31:OLHHHLLLLLLLLJJJJSSSTBGGBO...
32:OLHHHLLLLLLLLJJJJSSSTBGYYBO...
33:OLHHHLLLLLLLLJJJJSSSTBGYYYBO....
34:OLHHHLLLLLLLJJJJSSSTBGGYYBO.....
35:OLHHHLLLLLLJJJJSSSTBGYYYBO......
35:OLHHHLLLLLLJJJJSSSTBGYYYBO.......
35:OLHHHLLLLLLJJJJSSSTBGGYYBO........
35:OLHHHLLLLLLJJJJSSSTBGYYYBO.........
35:OLHHHLLLLLLJJJJSSSTBGYYYBO..........
35:OLHHHLLLLLLJJJJSSSTBGGYYBO...........
''')
MOUTH_JET=[(49,40,'OCCWWWCCFFEEEFFFFEEE'),
(49,41,'FCCWWWWWCCCCFFFFFFEEE'),(48,42,'EFFCCWWWWCCCCFFFFEEE'),
(49,43,'EFFCCWWWCCCFFFFEEE'),(51,44,'EFFCCWWCCCFFFEEE')]
save('skill_b',SKILL_B_UP,COIL_REST,TAIL_REST,LAMP_REST,LAMP_CHARGE,BREATH_FORK,SKILL_B_NECK_REPAIR,MOUTH_JET)

SKILL_C_NECK_REPAIR=rows(47, '''
32:OLHHHLLLLLLJJJJSSSTBGBO...
33:OLHHHLLLLLLLJJJJSSSTBBO...
34:OLHHHLLLLLLLLJJJJSSSTBGBO...
35:OLHHHLLLLLLLLJJJJSSSTBGGBO....
36:OLHHHLLLLLLLLJJJJSSSTBGYYBO....
37:OLHHHLLLLLLLLJJJJSSSTBGYYYBO.....
38:OLHHHLLLLLLLJJJJSSSTBGGYYBO......
39:OLHHHLLLLLLJJJJSSSTBGYYYBO.......
39:OLHHHLLLLLLJJJJSSSTBGYYYBO........
39:OLHHHLLLLLLJJJJSSSTBGGYYBO.........
39:OLHHHLLLLLLJJJJSSSTBGYYYBO..........
38:OLHHHLLLLLLLJJJJSSSTBGYYYBO..........
37:OLHHHLLLLLLLLJJJJSSSTBGGYYBO..........
36:OLHHHLLLLLLLLLJJJJSSSTBGYYYBO..........
35:OLHHHLLLLLLLLLLJJJJSSSTBGYYYBO..........
34:OLHHHLLLLLLLLLLLJJJJSSSTBGGYYBO..........
33:OLHHHLLLLLLLLLLLLJJJJSSSTBGYYYBO..........
''')
save('skill_c',SKILL_C_UP,COIL_REST,TAIL_REST,LAMP_REST,BREATH_RESIDUE,SKILL_C_NECK_REPAIR,[(13,53,'FCCWCC'),(13,54,'FCCCFF'),(22,65,'LCCJ')])

# Final cast/recoil face-to-coil transitions: narrowed plates erase the former flange.
SKILL_B_FRONT=rows(57, '''
54:STBGGYYBO..............
54:STBGYYYBO...............
54:STBGYYYBO................
54:STBGGYYBO.................
54:STBGYYYBO..................
54:STBGYYYBO...................
54:STBGGYYBO....................
''')
SKILL_C_FRONT=rows(50, '''
53:SSSTBGYYBO................
54:SSSTBGYYBO.................
54:SSSTBGYYBO..................
54:SSSTBGGYBO...................
54:SSSTBGYYBO...................
54:SSSTBGYYBO....................
54:SSSTBGGYBO.....................
54:SSSTBGYYBO.....................
54:SSSTBGYYBO.....................
54:SSSTBGGYBO......................
54:SSSTBGYYBO......................
53:SSSTBGYYBO.......................
52:SSSTBGGYBO........................
52:SSSTBGYYBO........................
''')
save('skill_b',SKILL_B_UP,COIL_REST,TAIL_REST,LAMP_REST,LAMP_CHARGE,SKILL_B_NECK_REPAIR,SKILL_B_FRONT,BREATH_FORK,MOUTH_JET)
save('skill_c',SKILL_C_UP,COIL_REST,TAIL_REST,LAMP_REST,SKILL_C_NECK_REPAIR,SKILL_C_FRONT,[(13,53,'FCCWCC'),(13,54,'FCCCFF'),(22,65,'LCCJ')],BREATH_RESIDUE)

# Cross-pose PNG review caught retained lower-neck shelves in sickness and stun.
# Distinct rows below reshape the neck itself; the center coil opening is untouched.
POISON_A_ROOT=rows(55, '''
30:OLHHHLLLLLLJJJJSSSTBGBO............
31:OLHHHLLLLLLLJJJJSSSTBGGBO...........
32:OLHHHLLLLLLLLJJJJJSSSTBGYYBO.........
33:OLHHHLLLLLLLLJJJJJJSSSTBGYYYBO........
34:OLHHHLLLLLLLJJJJJJSSSTBGYYYBO.........
34:OLHHHLLLLLLLJJJJJJSSSTBGGYYBO..........
34:OLHHHLLLLLLLJJJJJJSSSTBGYYYBO...........
34:OLHHHLLLLLLLJJJJJJSSSTBGYYYBO............
34:OLHHHLLLLLLLJJJJJJSSSTBGGYYBO.............
''')
POISON_B_ROOT=rows(56, '''
31:OLHHHLLLLLJJJJSSSTBGBO.............
32:OLHHHLLLLLLJJJJSSSTBGGBO...........
33:OLHHHLLLLLLLJJJJJSSSTBGYYBO..........
34:OLHHHLLLLLLLLJJJJJSSSTBGYYYBO........
34:OLHHHLLLLLLLLJJJJJSSSTBGGYYBO.........
34:OLHHHLLLLLLLLJJJJJSSSTBGYYYBO..........
34:OLHHHLLLLLLLLJJJJJSSSTBGYYYBO...........
34:OLHHHLLLLLLLLJJJJJSSSTBGGYYBO............
''')
save('poison_a',POISON_UP,COIL_REST,TAIL_REST,LAMP_REST,POISON_A_ROOT,[(34,69,'LJJSSS'),(35,70,'JJSSSS')],BUBBLES_A)
save('poison_b',POISON_B_UP,COIL_REST,TAIL_REST,LAMP_REST,POISON_B_ROOT,[(34,69,'LLJJSS'),(35,70,'LJJSSS'),(39,83,'JJJJSSSSS')],BUBBLES_B)

STUN_A_ROOT=rows(57, '''
38:OLHHLLLLJJJJSSSTBGBO..........
39:OLHHLLLLJJJJSSSTBGGBO..........
40:OLHHLLLLJJJJSSSTBGYYBO..........
40:OLHHLLLLJJJJSSSTBGYYBO...........
39:OLHHLLLLJJJJJSSSTBGGYBO...........
38:OLHHLLLLJJJJJJSSSTBGYYBO...........
37:OLHHLLLLJJJJJJJSSSTBGYYBO...........
''')
STUN_B_ROOT=rows(57, '''
38:OLHHLLLLJJJJSSSTBGBO..........
39:OLHHLLLLJJJJSSSTBGGBO..........
40:OLHHLLLLJJJJSSSTBGYYBO..........
40:OLHHLLLLJJJJSSSTBGYYBO...........
39:OLHHLLLLLJJJJSSSTBGGYBO...........
38:OLHHLLLLLJJJJJSSSTBGYYBO...........
37:OLHHLLLLLJJJJJJSSSTBGYYBO...........
''')
save('stun_a',STUN_UP,COIL_REST,TAIL_REST,LAMP_REST,STUN_A_ROOT,STARS_A,[(13,53,'FFCCCF'),(13,54,'FFFFCF')])
save('stun_b',STUN_UP,COIL_REST,TAIL_REST,LAMP_REST,STUN_B_EDIT,STUN_B_ROOT,STARS_B,[(13,53,'FFFFCF'),(13,54,'FFFCCF')])
HIT_ROOT_FRONT=rows(59, '''
54:STBGGBO...........
54:STBGYYBO...........
54:STBGGYBO...........
54:STBGYYBO...........
54:STBGYYBO...........
''')
save('hit',HIT_UP,COIL_REST,TAIL_REST,LAMP_REST,HIT_THROAT,HIT_ROOT_FRONT,[(12,53,'FFCCCWCF'),(12,54,'FFFCCWCF')])

# Contact jaw refinement: extend both physical jaw rails, with fangs rooted in gum.
# Transparent mouth aperture is authored, rather than filled by a connectivity pass.
BITE_JAWS=[
(75,40,'JJJJJJSSOO'),(76,41,'JJJJJJJJJSSOO'),
(76,42,'JJJJJJJJJJSSO'),(76,43,'JJJJJJJJJJSSO'),
(75,44,'JJJJJJJJJJJSSO'),(74,45,'JJJJJJJJJJJSSSO'),
(72,46,'JJJJJJJJJJSSSSTO'),
(54,47,'OOOOODWWWDDDDDDDWWWDDDDDDDDDDDO'),
(54,48,'O....DWWD.......DWWD........O'),
(54,49,'O.....DW.........DW...........'),
(52,50,'O.............................'),
(51,51,'O..............................'),
(50,52,'O.........................DW....'),
(49,53,'OBGBO....................DWWD...'),
(48,54,'OBGYGBOOOOOOOOOOOOOOOOODWWWDDDDDDO'),
(46,55,'OBGYYYYYYYYYYYYYYYYYYYYYYYYGGGGGGBDO'),
(44,56,'OBGYYYYYYYYYYYYYYYYYYGGGGGGGGGGGGGBDO'),
(42,57,'OBGGYYYYYYYYYYYYYYGGGGGGGGGGGGBBDOO'),
(40,58,'OBGGGYYYYYYYYGGGGGGGGGGGGGGGGBDDOO'),
(38,59,'OBGGGGGGGGGGGGGGGGGGGGGGGGGBBDOO'),
(36,60,'OBBBBBBBBBBBBBBBBBBBBBBDDOO'),
(34,61,'OSSTTTTTTTTTTTTTTTTTOOO'),
(33,62,'OSSTTTTTTTTTTTTOOO'),
(32,63,'OSSTTTTTTTTTOOO'),
(31,64,'OSSTTTTTTTOOO')]
save('attack',ATTACK_UP,COIL_STRIKE,TAIL_REST,LAMP_REST,BITE_JAWS)

# Bounded reviewer correction: keep the two upper residue clusters only.
# Original lower cluster rows remain above and in history/skill_c-before-two-residue.txt.
SKILL_C_TWO_RESIDUE_ERASURES=[
(86,50,'..'), # previously FF
(85,51,'....'), # previously FCCF
(85,52,'.....'), # previously FCWCF
(86,53,'......'), # previously FCCCFE
(87,54,'.....'), # previously FCFFE
(87,55,'....'), # previously FEEE
(84,59,'...'), # previously FFE
(83,60,'.....'), # previously FCCFE
(82,61,'.......'), # previously FCWCCFE
(82,62,'.......'), # previously FCCCCFE
(83,63,'......'), # previously FFFFEE
(85,64,'...'), # previously EEE
]
save('skill_c',SKILL_C_UP,COIL_REST,TAIL_REST,LAMP_REST,SKILL_C_NECK_REPAIR,SKILL_C_FRONT,[(13,53,'FCCWCC'),(13,54,'FCCCFF'),(22,65,'LCCJ')],BREATH_RESIDUE,SKILL_C_TWO_RESIDUE_ERASURES)
