# 칩(걷기 스프라이트)을 눈으로 보고 적은 「머리 윗부분·머리장식」. 얼굴 컷은 정수리가 잘려서 모델이 대머리·탈모로 추측한다.
HEAD = {
 "actor2-blonde": "a red-and-green leaf-and-flower wreath bonnet on top of long wavy blonde hair",
 "actor2-blonde-man": "a full head of short tousled blonde hair, no hat",
 "actor2-blue-hat-woman": "a big red wide-brimmed witch hat with a gold buckle, worn over long pale-blue hair",
 "actor2-blue-man": "a full head of short dark-blue hair, no hat",
 "actor2-brown-woman": "a black-and-gold banded headpiece sitting on big spiky dark-brown hair",
 "actor2-brown-youth": "a flat black cap with a gold band on long dark-brown hair",
 "actor2-golden-woman": "a full head of messy golden-blonde hair, no hat",
 "actor2-long-blue": "a full head of long straight blue hair, no hat",
 "actor2-masked": "a black hood with a grey rim and a black cloth mask over the lower face",
 "actor2-mauve-woman": "a full head of long mauve-pink hair, no hat",
 "actor2-mustache": "a full head of messy black hair, no hat",
 "actor2-purple-woman": "a full head of long purple hair, no hat",
 "actor2-red-band-blonde": "a red bandana tied around spiky dark-blonde hair",
 "actor2-red-helmet": "a red-and-silver samurai helmet (kabuto) with a crest and side flaps",
 "actor2-teal-woman": "a full head of dark-teal hair pulled back, no hat",
 "actor2-white-band": "a white headband on long black hair tied into a high ponytail",
 "bearded-bandana": "a red bandana over a full head of spiky brown hair; a rugged older man with a full thick brown beard and moustache, exactly as in the face portrait",
 "black-headband": "a full head of long black hair, no hat",
 "black-martial": "a full head of black hair tied back, no hat",
 "blue-hat-woman": "a blue wide-brimmed hat with a gold band on long black hair",
 "blue-headband": "a black jester's cap with four drooping points tipped with orange bobbles, on top of long blue hair",
 "blue-traveler": "a full head of long blue hair, no hat",
 "brown-headband": "a white headband on a full head of reddish-brown hair",
 "green-bandana": "a red bandana with a red-and-white feather sticking up, on long wild green hair",
 "green-cap-blonde": "a green cap with a red-and-white feather on long wavy blonde hair; small pointed ears",
 "green-goggles": "aviator goggles pushed up on top of big curly green hair",
 "green-scholar": "a gold headband on long brown dreadlocks",
 "helmet-blonde": "a red-and-silver helmet with two short pointed tips on top, long blonde hair coming out below it",
 "helmet-guard": "a red-and-silver helmet with two short pointed tips on top",
 "monster-beast": "two curved horns and a shaggy dark-brown mane on a grey beast head",
 "monster-green-hair": "a full head of wild green hair; she is a harpy with large grey feathered wings instead of arms",
 "monster-green-scar": "spiky grey-green hair",
 "monster-hood-skeleton": "a purple hood",
 "monster-red-demon": "a bald red head with two brown horns and pointed ears",
 "monster-red-helm": "a red-and-black horned demonic helmet",
 "monster-skeleton": "a bare white skull; the whole body is a bare skeleton of bones with NO clothes, no scarf, no shoes",
 "monster-white-hair": "a full head of long white hair, no hat",
 "orange-woman": "a full head of short orange hair, no hat",
 "people1-bald-man": "a completely bald head",
 "people1-blonde-woman": "a full head of light-blonde hair, no hat",
 "people1-blue-man": "a full head of spiky dark-blue hair, no hat",
 "people1-boy": "a full head of brown hair, no hat",
 "people1-girl": "a full head of blonde hair, no hat",
 "people1-mustache": "a full head of short reddish-brown hair, no hat",
 "people1-nun": "a white-and-black nun's veil",
 "people1-old-man": "a bald crown with a white fringe of hair at the sides and a full white beard",
 "people1-old-woman": "an orange hooded headscarf over grey hair",
 "people1-purple-woman": "a big mass of curly purple hair, gold earrings",
 "people1-village-woman": "a full head of brown hair, no hat",
 "people2-auburn-man": "a full head of auburn hair, no hat",
 "people2-blonde-curls": "long blonde hair in drill curls",
 "people2-blue-guard": "a blue-and-silver knight's helmet",
 "people2-blue-ribbon": "a white ribbon headband on blue-violet hair",
 "people2-blue-woman": "a small gold crown on tall blue-teal hair",
 "people2-king": "a gold crown on white hair",
 "people2-mustache": "a full head of dark slicked-back hair, no hat",
 "people2-white-elder": "a FULL head of thick grey-white hair swept to one side, covering the whole top of the head (NOT bald, no receding hairline)",
 "pink-hat": "a purple turban-like cap with a gold band over long pink hair",
 "purple-mage": "a tall black pointed witch hat with blue dots, on curly magenta hair",
 # People1 얼굴 8·12 는 짝 칩 없음(얼굴만), 13~15 → People2 칩 5~7
 "people1-black-man": "a full head of short neat black hair, no hat; a plain dark high-collared coat",
 "people1-black-wave": "a full head of black hair with long wavy locks at the sides, no hat; a plain dark coat",
 "people1-blonde-wave": "a white bunny-ear headband on long wavy blonde hair; a black outfit with dark tights",
 "people1-red-woman": "an angel: a purple-and-gold halo ring floating above long red hair, large white feathered wings on her back, a pale blue-and-white robe",
 "people1-mint-woman": "an adult fairy woman: mint-green bob-cut hair, translucent cyan insect wings on her back, a green outfit; adult proportions, NOT a child",
}
