# 동양풍 성·닌자 마을 — 내보낼 새 조각 목록(이름, 그리는 함수, kind, 한글 이름, 설명, 놓는 법, 막는 아랫줄, 층, 역할).
# 버들항 원본 그림(덤불·활엽수·밭·풀 덩이)은 지도에만 다시 쓰고 내보내지 않는다.
import ek_build as B, ek_props as P, ek_ground as G
from ek_base import flip

_T = '키 큰 부드러운 물체: 맨 아랫줄(밑동)만 막히고 위 칸은 걷기 + 위층(가림). '
_S = '단단한 몸통: 아랫줄이 막히고 윗면은 걷기 + 위층. '
_BLD = '건물: 앞면 벽 줄이 막히고 지붕 칸은 걷기 + 위층(뒤로 지나가면 가린다), 문 칸은 걷기. 문 앞 한 칸은 비운다. '

PARTS = [
    # ---- 건물·구조물 (앵커)
    ('tenshu', B.tenshu, 'object', '천수각', '3층 천수각: 휜 돌 기단·검은 판벽·흰 회벽·격자창·층층 기와 처마·치도리 박공·금 귀면 장식 — 성 지도의 중심 앵커.',
     _BLD + '발자국 아래 5줄(기단 3 + 1층 2), 기단 문 1칸(가운데)만 걷기. 흰 자갈 광장 북쪽 끝에, 앞에 판석 길과 돌 등롱 둘.', 5, None, 'building'),
    ('yaguramon', B.yaguramon, 'object', '성문 망루(야구라몬)', '양쪽 돌담 위에 2층 망루가 얹힌 성문: 가운데 3칸 문길, 안으로 열린 검은 칠 문짝, 흰 벽 창 셋, 팔작지붕.',
     _BLD + '아래 3줄 막힘, 가운데 문길 3칸 x 6줄 걷기. 성 기단 돌담 줄(ishigaki_wall)과 흙벽 줄 사이에 끼우고 바로 남쪽에 해자 다리.', 3, None, 'building'),
    ('yagura', B.yagura, 'object', '모서리 망루', '2층 모서리 망루(스미야구라): 돌 기단 2줄 + 흰 벽·검은 판벽 + 처마 + 팔작지붕.',
     _BLD + '아래 4줄 막힘. 흙벽 줄이 꺾이는 모서리·끝에 둔다. 좌우 뒤집어 써도 된다.', 4, None, 'building'),
    ('yagura_flip', lambda: B.yagura(seed=5, flip_=True), 'object', '모서리 망루(뒤집음)', '모서리 망루 좌우 뒤집은 판(빛 방향 규칙 때문에 동쪽 끝용으로 따로 둔다).',
     _BLD + '아래 4줄 막힘. 동쪽 모서리.', 4, None, 'building'),
    ('dobei', lambda: B.dobei(4), 'wall', '흙벽(도베이)', '성 흙벽 가로 토막 4칸: 기와 덮개 + 흰 회벽 + 검은 판벽 띠 + 세모·네모·동그라미 총안. 이어 찍으면 이음새 없음.',
     '벽: 아랫줄 막힘, 덮개 줄 걷기 + 위층. 돌담(ishigaki_wall) 바로 위 줄에 가로로 이어 찍는다. 망루·성문과 맞닿게.', 1, None, 'wall'),
    ('dobei_ns', lambda: B.dobei_ns(3), 'wall', '흙벽(남북)', '남북으로 달리는 흙벽을 위에서 본 기와 덮개 줄(3칸). 남쪽 끝은 망루나 가로 흙벽에 닿게.',
     '칸 전부 막힘. 해자 안쪽 둑을 따라 세로로 이어 찍는다.', 3, None, 'wall'),
    ('ishigaki_wall', lambda: B.ishigaki_wall(4, 2), 'wall', '돌담 기단(이시가키)', '크기가 제각각인 막돌 줄쌓기 앞면 4x2칸(위 갓돌 빛, 아래 그늘). 성 기단·사당 언덕·해자 둑.',
     '칸 전부 막힘. 높은 땅의 남쪽 끝 2줄에 가로로 이어 찍고, 계단(stone_steps)·성문 자리만 비운다.', 2, None, 'wall'),
    ('kura', lambda: P.kura(4, seed=2), 'object', '흰 벽 곳간(구라)', '흰 회벽 곳간: 아래 해삼벽(검은 판 + 흰 마름모 줄눈), 높은 쇠 덧문 창, 두꺼운 흙 문, 기와 맞배 지붕.',
     _BLD + '아래 2줄 막힘(문은 닫힌 그림 — 들어가려면 문 칸에 이벤트). 성 마당·부잣집 뒤뜰에 1~3채 덩이.', 2, None, 'building'),
    ('kura_small', lambda: P.kura(3, seed=9), 'object', '작은 곳간', '3칸 폭 흰 벽 곳간(같은 규칙, 좁은 판).', _BLD + '아래 2줄 막힘.', 2, None, 'building'),
    ('minka_thatch', lambda: B.minka(5, seed=1, roof='thatch', door=2), 'object', '초가 민가', '짚 지붕 민가 5칸: 두툼한 초가(짚 결·누름 가위 막대 마루), 흙벽 + 판벽, 반쯤 연 장지문, 격자창, 툇마루.',
     _BLD + '아래 2줄 막힘, 문 칸(가운데) 걷기. 마을에 간격 두고, 집마다 폭·문 위치를 바꾼다.', 2, None, 'building'),
    ('minka_thatch_b', lambda: B.minka(5, seed=3, roof='thatch', door=1, lit=True), 'object', '초가 민가(불 켠 창)', '초가 민가 변형: 문이 왼쪽, 창에 불빛.', _BLD + '아래 2줄 막힘.', 2, None, 'building'),
    ('minka_plank', lambda: B.minka(4, seed=2, roof='plank', door=1), 'object', '너와 지붕 민가', '돌로 눌러 둔 바랜 너와 판자 지붕 민가 4칸(누름대 + 누름돌), 흙벽 + 판벽, 장지문.',
     _BLD + '아래 2줄 막힘. 산골·닌자 마을 집.', 2, None, 'building'),
    ('dojo', B.dojo, 'object', '도장(수련장)', '넓은 기와 팔작지붕(가운데 큰 박공) + 장지문 여섯(가운데 둘 열림) + 높은 툇마루 + 돌 계단 + 글자 없는 나무 걸개판.',
     _BLD + '아래 3줄 막힘, 계단 앞 가운데 2칸 걷기(문). 앞에 흙 수련 마당과 단련 기둥.', 3, None, 'building'),
    ('mill_hut', B.mill_hut, 'object', '물레방아 오두막', '너와 지붕 판벽 오두막 4칸. 동쪽 벽 바로 옆 개울에 물레방아 바퀴를 붙인다.', _BLD + '아래 2줄 막힘, 문 칸 걷기.', 2, None, 'building'),
    ('water_wheel', B.water_wheel, 'object', '물레방아 바퀴', '나무 바퀴(두 겹 테·바큇살 여덟·물받이 판·굴대) + 흘러내리는 물. 개울 물 칸 위에 얹는다.',
     '물 위 장식: 물 칸이 이미 막히므로 따로 막지 않는다. 오두막 동쪽 벽에 붙인다. frame 인자로 돌아가는 판(16장)을 더 뽑을 수 있다.', 0, None, 'prop'),
    ('hokora', B.hokora, 'object', '작은 사당(호코라)', '돌 받침 두 단 위 나무 사당: 붉은 칠 테, 격자문, 방울 끈, 기와 맞배 지붕.', _S + '아래 2줄 막힘. 언덕 위, 앞에 시주함과 판석 길.', 2, None, 'prop'),
    ('torii', B.torii, 'object', '도리이', '붉은 칠 도리이 4칸: 기둥 둘(검은 밑동), 끝이 휜 검은 갓돌, 시마기, 꿰뚫은 누키, 글자 없는 가운데 받침.',
     _T + '기둥 밑동 두 칸만 막히고 가운데 두 칸은 걸어서 지나간다. 사당 길 입구·돌계단 아래.', 1, None, 'prop'),
    ('well_roofed', B.well, 'object', '지붕 우물', '돌 테 우물(어두운 물) + 작은 맞배 지붕 + 도르래·두레박.', _S + '아래 2줄 막힘. 마을 갈림길 곁, 둘레는 흙.', 2, None, 'prop'),
    ('plank_fence', lambda: B.plank_fence(4), 'wall', '판자벽', '세로 널 판자벽 4칸(위 끝 들쭉날쭉, 띠목 둘, 기둥). 숨은 마을 둘레.', '아랫줄 막힘, 윗줄 걷기 + 위층. 일렬로 이어 찍는다.', 1, None, 'wall'),
    ('hidden_door', lambda: B.plank_fence(1, seed=56, door=0), 'object', '숨은 회전문(닫힘)', '판자벽과 똑같아 보이는 1칸 회전 문: 가는 세로 틈 둘과 옹이 같은 손잡이 홈만 다르다.',
     '판자벽 줄 한 칸에 끼운다. 걷기 칸(이벤트로 회전 연출). 「아는 사람만」 보이도록 주변에 단서를 두지 않는다.', 0, None, 'prop'),
    ('hidden_door_open', lambda: B.plank_fence(1, seed=56, door=0, door_open=True), 'object', '숨은 회전문(도는 중)', '회전 중인 문 판: 판이 옆으로 돌아 두께만 보이고 양옆 틈이 어둡다(회전 연출 둘째 판).',
     '닫힌 판과 같은 자리. 이벤트에서 닫힘 → 도는 중 → 닫힘으로 바꿔 끼운다.', 0, None, 'prop'),
    ('bridge_moat', lambda: B.bridge_ns(3, 3), 'object', '해자 다리', '남북 판자 다리 3x3칸: 가로 널 + 붉은 칠 난간(금 의보주 기둥 머리) + 남쪽 끝 교각 그늘.',
     '다리 칸 전부 걷기(밑의 물 칸 막힘을 덮는다). 성문 문길과 해자 건너 둑을 잇는다.', 0, None, 'prop'),
    ('plank_bridge', lambda: B.plank_bridge(4), 'object', '널다리', '개울 위 동서 널다리 4x2칸(양 끝 둑에 걸친 받침 + 가로 널).', '다리 칸 걷기. 양 끝 한 칸은 둑(땅)에 걸친다.', 0, None, 'prop'),
    ('stone_steps', lambda: P.stone_steps(3, 2), 'object', '돌계단(이시단)', '돌담 언덕을 오르는 돌계단 3x2칸(단마다 윗면 빛 + 챌면 어둠, 양옆 막돌 볼).',
     '걷기. 돌담 기단 줄에 끼우고 아래·위 끝에 길을 잇는다. 시트 모양 그대로(돌리지 않는다).', 0, None, 'prop'),
    # ---- 식생
    ('bamboo', lambda: P.bamboo(1), 'tree', '대나무 덤불', '줄기 여섯(마디·빛 턱) + 처진 가는 잎 다발 + 뒤 잎 덩이. 3x6칸.',
     _T + '밑동 두 칸만 막힌다. 대숲은 크기 다른 덤불을 엇갈려 겹치고 일렬로 세우지 않는다. 가장자리는 어린 대나무로.', 1, None, 'tree'),
    ('bamboo_small', lambda: P.bamboo(2, n=5, w=2, h=5), 'tree', '대나무 덤불(작음)', '2x5칸 작은 대나무 덤불.', _T + '밑동만 막힘.', 1, None, 'tree'),
    ('bamboo_young', P.bamboo_young, 'tree', '어린 대나무', '가는 줄기 둘 + 잎 줄 1x3칸. 대숲 가장자리를 부드럽게.', _T + '밑동 1칸만 막힘.', 1, None, 'tree'),
    ('matsu', lambda: P.matsu(1), 'tree', '정원 소나무', '굽은 줄기 + 옆으로 뻗은 가지 끝 평평한 구름 잎뭉치(짙은 소나무 잎). 4x5칸.',
     _T + '줄기 밑 두 칸만 막힌다. 성 마당·사당·물가에 하나씩, 좌우 뒤집어 섞는다.', 1, None, 'tree'),
    ('matsu_b', lambda: P.matsu(5, True), 'tree', '정원 소나무(변형)', '잎뭉치 배치가 다른 소나무(뒤집음).', _T + '줄기 밑 두 칸만 막힘.', 1, None, 'tree'),
    ('azalea', P.azalea, 'tree', '철쭉 덤불', '둥글게 다듬은 철쭉(분홍 꽃 점) 2x2칸.', _T + '아랫줄 두 칸 막힘. 정원 돌 곁·사당 곁에 덩이로.', 1, None, 'tree'),
    ('garden_rock', P.garden_rock, 'object', '정원 바위', '이끼 낀 윗면 정원 바위 2칸. 갈퀴 모래 마당에 셋씩 덩이로.', _S + '아랫줄 막힘.', 1, None, 'prop'),
    # ---- 소품
    ('toro', P.toro, 'object', '돌 등롱', '가스가형 돌 등롱(받침·기둥·중대·불 켠 불집·휜 갓·보주) 1x3칸.', _T + '밑동 1칸만 막힘. 길 양옆에 짝으로, 사당 앞에.', 1, None, 'prop'),
    ('chozubachi', P.chozubachi, 'object', '돌 물확', '손 씻는 돌 물통 + 대나무 홈통·국자.', _S + '아랫줄 막힘. 사당 입구 곁.', 1, None, 'prop'),
    ('saisen_box', P.saisen_box, 'object', '시주함', '나무 시주함(윗면 살, 글자 없음).', '칸 막힘. 사당 바로 앞.', 1, None, 'prop'),
    ('komainu', P.komainu, 'object', '사당 지킴 짐승 돌상', '돌 받침 위 앉은 네발짐승 돌상(갈기·말린 꼬리).', _T + '밑동만 막힘. 사당 길 양옆에 짝(하나는 뒤집어).', 1, None, 'prop'),
    ('ema_rack', P.ema_rack, 'object', '소원 판 걸이', '지붕 얹은 걸이 틀 + 오각 나무 판 열(글자 없음, 붉은 끈).', _S + '아랫줄 막힘. 사당 곁.', 1, None, 'prop'),
    ('tawara', P.tawara, 'object', '쌀가마 더미', '짚 쌀가마 셋(아래 둘 위 하나).', '칸 전부 막힘. 곳간·집 옆.', 2, None, 'prop'),
    ('taru', P.taru, 'object', '술통', '짚 거적 감은 나무 술통.', _S + '밑동 막힘.', 1, None, 'prop'),
    ('firewood', P.firewood, 'object', '장작 더미', '마구리가 보이게 쌓은 장작 + 위 짚 거적.', '칸 막힘. 집 벽 곁.', 1, None, 'prop'),
    ('makiwara', P.makiwara, 'object', '단련 기둥(마키와라)', '짚 감은 주먹 단련 기둥.', _T + '밑동만 막힘. 도장 앞 마당.', 1, None, 'prop'),
    ('mokujin', P.mokujin, 'object', '나무 대련 기둥', '팔 막대 셋이 꽂힌 굵은 통나무(얼굴 없음).', _T + '밑동만 막힘. 수련 마당.', 1, None, 'prop'),
    ('target_board', P.target_board, 'object', '표창 과녁', '짚 둥근 과녁 + 다리 셋 + 꽂힌 표창 둘.', _T + '밑동만 막힘. 닌자 은신 마당·도장 마당.', 1, None, 'prop'),
    ('weapon_rack', P.weapon_rack, 'object', '봉·창 걸이', '나무 틀에 기댄 긴 봉 다섯(쇠 촉 둘).', _S + '아랫줄 두 칸 막힘.', 1, None, 'prop'),
    ('chochin_post', P.chochin_post, 'object', '붉은 종이 등 기둥', '나무 기둥에 매단 붉은 종이 등(글자 없음, 불빛).', _T + '밑동만 막힘. 길가·도장 문 앞에 드문드문.', 1, None, 'prop'),
    ('drying_rack', P.drying_rack, 'object', '곶감 말림대', '기둥 둘 + 장대에 매단 곶감 줄 + 아래 짚 멍석.', _S + '아랫줄 막힘. 민가 앞뜰.', 1, None, 'prop'),
    ('stepping_stone', P.stepping_stone, 'decal', '디딤돌', '납작한 둥근 디딤돌 둘(땅 장식).', '걷기 + 사람 아래. 흙 오솔길·정원 길에 한 칸 건너 하나씩 엇갈리게.', 0, None, 'decal'),
    # ---- 실내
    ('inner_wall_fusuma', lambda: B.inner_wall(3, 'fusuma'), 'wall', '실내 벽(맹장지)', '나게시 들보 + 회벽 띠 + 금 안개 띠 맹장지 + 문지방 3x3칸.', '칸 전부 막힘. 실내 북쪽 벽 3줄(천장 바로 밑).', 3, None, 'wall'),
    ('inner_wall_shoji', lambda: B.inner_wall(3, 'shoji'), 'wall', '실내 벽(장지)', '나무 살 + 흰 종이 장지 벽 3x3칸.', '칸 전부 막힘. 다다미 방 북쪽 벽.', 3, None, 'wall'),
    ('partition', B.partition, 'wall', '칸막이 벽', '남북 칸막이 1칸 폭: 위 8칸 = 벽 윗면(천장 띠), 아래 3칸 = 남쪽 끝 맹장지 앞면.', '발자국 칸 전부 막힘. 남쪽 끝 아래 칸을 비워 방 사이 통로로(ㅁ자 고립 금지).', 3, None, 'wall'),
    ('tokonoma', P.tokonoma, 'object', '도코노마', '벽 감실: 나무 테 + 먹 산수 족자(글자 없음) + 꽃병. 북쪽 벽 줄에 끼운다.', '칸 전부 막힘(벽).', 3, None, 'wall'),
    ('jodan', B.jodan, 'object', '상단 다다미 단', '높인 다다미 단 9x3칸(앞 끝 검은 칠 턱 + 금 징).', '걷기(단 위에 올라선다). 대청 북쪽 벽 앞, 가운데에 병풍과 방석.', 0, None, 'prop'),
    ('hashira', B.hashira, 'object', '대청 기둥', '굵은 네모 나무 기둥 + 받침돌 1x3칸.', _T + '밑동 1칸만 막힘. 대청에 줄 맞춰 짝으로.', 1, None, 'prop'),
    ('byobu', P.byobu, 'object', '병풍', '접은 여섯 폭 금박 병풍(먹 산·소나무 그림, 글자 없음) 3x2칸.', _S + '아랫줄 세 칸 막힘. 방 벽 앞·상단 뒤.', 1, None, 'prop'),
    ('zen_table', P.zen_table, 'object', '낮은 상과 찻그릇', '검은 칠 낮은 상 + 찻주전자·찻잔.', '아랫줄 막힘. 다다미 가운데, 둘레에 방석 넷.', 1, None, 'prop'),
    ('zabuton', P.zabuton, 'decal', '방석', '네모 솜 방석(가운데 술).', '걷기 + 사람 아래. 상 둘레·상단 앞에 줄 맞춰.', 0, None, 'decal'),
    ('andon', P.andon, 'object', '종이 등(안돈)', '나무 틀 종이 등(불빛).', _T + '밑동만 막힘. 방 모서리.', 1, None, 'prop'),
    ('katana_kake', P.katana_kake, 'object', '칼걸이', '검은 칠 받침 + 칼집 두 자루.', _S + '아랫줄 막힘. 대청 벽 앞.', 1, None, 'prop'),
    ('yoroi', P.yoroi, 'object', '갑옷 장식', '검은 칠 궤 위 갑옷·투구(얼굴 자리는 빈 어둠) + 금 뿔 장식.', _S + '아랫줄 막힘. 대청 벽 앞.', 1, None, 'prop'),
    ('tansu', P.tansu, 'object', '서랍장(단스)', '나무 서랍장 서랍 셋 + 검은 쇠 손잡이.', _S + '아랫줄 막힘. 방 벽 곁.', 1, None, 'prop'),
    ('hibachi', P.hibachi, 'object', '화로', '둥근 도기 화로(재 + 숯불) + 쇠 젓가락.', '칸 막힘.', 1, None, 'prop'),
    ('ikebana', P.ikebana, 'object', '꽃꽂이 수반', '낮은 도기 수반 + 소나무 가지·붉은 꽃.', '칸 막힘. 방 구석.', 1, None, 'prop'),
    # ---- 바닥·벽면·천장 표본
    ('ground-suna', G.ground_suna, 'floor', '흰 자갈', '성 마당 흰 자갈(칩셋 모래 결 + 굵은 자갈 점). 3x3 이음새 없음.', '걷기. 천수각 앞 광장·성 안 길.', 0, None, 'terrain'),
    ('ground-raked', G.ground_raked, 'floor', '갈퀴 모래', '마른 정원 갈퀴 자국 모래(물결 줄).', '걷기(정원은 보통 연석으로 둘러 들어가지 않게).', 0, None, 'terrain'),
    ('ground-flagpath', G.ground_flagpath, 'floor', '판석 길', '크기 제각각 네모 판석 길(이시다타미).', '걷기. 성문 → 천수각 길, 사당 앞.', 0, None, 'terrain'),
    ('ground-tatami', G.ground_tatami, 'floor', '다다미', '다다미 깔기 48x48 주기(가로 둘·세로 하나·가로·반 장), 짚 결 + 검은 테두리 띠.', '걷기. 방 크기를 3칸 배수로 하면 깔기가 맞는다.', 0, None, 'terrain'),
    ('ground-board', G.ground_board, 'floor', '마루 널', '닦인 대청 마루(가로 긴 널, 엇갈린 이음, 드문 옹이).', '걷기. 대청·복도.', 0, None, 'terrain'),
    ('face_ishigaki', lambda: G.ishigaki_sample(), 'wall', '돌담 앞면 표본', '막돌 줄쌓기 앞면 3x3(이음새 없이 이어진다).', '칸 막힘.', 3, None, 'wall'),
    ('face_fusuma', lambda: G.face_sample('fusuma'), 'wall', '맹장지 벽면 표본', '실내 북쪽 벽 3줄 표본(맹장지).', '칸 막힘.', 3, None, 'wall'),
    ('face_shoji', lambda: G.face_sample('shoji'), 'wall', '장지 벽면 표본', '실내 북쪽 벽 3줄 표본(장지).', '칸 막힘.', 3, None, 'wall'),
    ('ceiling_coffered', lambda: G.ceiling_sample() if hasattr(G, 'ceiling_sample') else None, 'wall', '격자 천장', '검은 칠 살 격자 천장(벽 위·실내 둘레 어둠 띠).', '칸 막힘.', 3, None, 'wall'),
    # ---- 오토타일
    ('autotile-takegaki', G.autotile_takegaki, 'autotile', '대나무 울타리', '대나무 살 울타리 16변형(동서 = 앞에서 본 살 + 묶음대, 남북 = 윗면 줄).', '위층 투명 오토타일, 모든 칸 막힘. 집 마당 둘레·밭 둘레에 붓으로.', 1, 'upper', 'fence'),
    ('autotile-flagpath', G.autotile_flagpath, 'autotile', '판석 오솔길', '풀 위 판석 길 16변형(이웃 없는 쪽은 풀이 먹어 든 들쭉날쭉 끝).', '아래층 투명 오토타일, 걷기. 정원·사당 길.', 0, 'lower', 'terrain'),
    ('autotile-sunabed', G.autotile_sunabed, 'autotile', '자갈 마당 연석', '흰 자갈 마당 가장자리 작은 둥근 돌 줄 16변형(안쪽 투명).', '아래층, 걷기. 마른 정원·자갈 마당 테두리.', 0, 'lower', 'terrain'),
]
