"""Original hand-authored native pixel rows. Dots are transparent.
Offsets only place each original drawing in a 64x64 cell; no resampling.
Run to preserve expanded .pxgrid sources; bake.py performs direct RGBA writes.
"""
from pathlib import Path
import json
ROOT = Path(__file__).resolve().parent
COMMON = {'O':'#292831','D':'#3e343a','K':'#1b222b'}
ART = {
'wild-boar': ((8,22), {
**COMMON,'S':'#58413e','B':'#795642','M':'#99724e','L':'#b39667','H':'#d1ba85',
'T':'#f0e5bc','C':'#b8afa0','N':'#9d6a58','P':'#c78c70','R':'#613c3e','E':'#ead4a1'}, '''
............................SS...........
......................SS...SLSS..........
.............SSSS....SMMSS.SLMBSS.........
...........SSMLLSSSSSMMLLMSSMBBDO.........
.........SSMLLMMMLLMMMMMLLMBBBBDD.........
........SMLLHLLMMLLMMMMLMMMBBSMBDO........
.......SMLLHMMLMMMBMMMLLMMMBSMLBBO........
......SMLLMMMBMMMBBSMMMLLMMBSLMBBO........
.....SMLMMMBBBMLLMBBSMLLMMMBBLBBBO........
....SMMMBMMMMLLHLLMBBSMMMMMBBBBBBBO.......
...SMMBBBMMMLLMMMLMBBSMMBBMBBSSMBBO......
...SMMBBSMMMLMMBBBBBBSMMBLMBSSBBMBBO.....
..SMMMBBSMMLMMBBMMBBSMMLLMBSDDKBMBO.....
..SMBBBSMMMLMBBMLMBBSMLLMBBSDKEMBBBO....
..SMBBSMMMLMBBBMLMBBSMLMMBBSBBBMMBBBO...
..SBBBSMMMLBBBMMLMBBSMMMMBBBMLLMNNPPNO..
..SBBBSMMMBBSMMMLBBBSMMMBBBMMLMNPPTPPNO.
..SBBBBMMMBSMLLLMBBSSMMMBBBBMMMNPNTPKKNO
..SBBBBBMBBSMLMMBSSSMBBBSSSBBMNNNCTNRRO
..OSBBBBBSSMLMMBSSSMMBBSSSBBBNNNNCTNRO.
.SOOSBBBBBSMLMBBSSMMMBBSSBBBBBNNTTTRO..
SLSSOSBBBBSSMMBBBSSMMBBSSBBBBSSBCCTO...
SLBSS.OSBBSSSBBSSSSMMBBSSSSSSSSOOO.....
.SBS..OSBBSSSSSSSSSMBBBSSSBSOOO........
..S....OSSSDDSSSSSSBBBDSSBBO...........
........ODSSBDDDSSBBBDSSBBDO...........
.........OBBBBDDDDBBD.SBBBDO...........
.........OBMBBODDDBBD.SBBMBO............
........OBMMBO.ODDBBO..SBMBO............
.......OBMMBO..ODDBO...SBBBO............
.......OKKKO...OKKKO...OKKKKO...........
........OOO.....OOO....OOOOO...........
'''),
'straw-dokkaebi': ((12,12), {
**COMMON,'S':'#5d5040','B':'#827b53','M':'#a19a65','L':'#c0b477','H':'#d9c993',
'a':'#705139','b':'#9b7949','c':'#bda46a','d':'#dbca87','R':'#784047','r':'#b95f50',
'T':'#ece0b7','E':'#e9c683','C':'#684938'}, '''
...............SS.......................
..............STTS......................
..............SLTTS.....................
...............SLTS.....................
..........SSSSSSLBSSS...................
.........SMLLLLLMMMBBS..................
........SMLHHLLLMMLMBBS.................
........SMLLLMMMMLLMMBBS................
........SMMMLSSSMMSSSBBS.............CC.
........SMMLSDKBMMDKMBBS............CbbC
........SMMMSLEBMMSEBBBS...........CbcbbC
........SMMMLMMMLMBBBBS...........CbdcbbC
.........SMLMMMLLLMBBS...........CbcdbbSC
.........SMMBBTTBMMBS...........CbcbbSSC.
..........SMMSSSSMBBS...........CbbSSSC..
........abbSSMMMMBSbbaa..........CbSSC..
......abccdbaSSSSabbccdba.........CSSC..
.....abddccbcbbaabbccddcba........CbC...
....abddccbbcddbccddcccbba.......CbC....
...abcccbbccddbcccbbccccbba......CbC....
...abcdcbcccbbccbbccbbccbba.....CbC.....
..SbcddbcbbccbbccbbccbcbbaSS...CbC......
.SMLbccbbccbbccbbccbbbcbaMMBS.CbC.......
SMLLMbbccbbccbbccbbccbbaMLMBSCbC........
SMLLMBabcbbccbbccbbcbbaMMLMBSMC.........
SMMLBBSaabbccbbccbbbaaSSMLLMBS..........
SMMMBBS..aaabbbbbaaa..SMMMLMBS..........
.SMBBS...ORrrrrrrRO...SMMBBBS...........
..SSS....ORrrRrrrRO....SBBBS............
.........OSRRrrrrRO.....SSS.............
.........OSBBSSBBBO.....................
.........OSBMBSBBBO.....................
.........OSBMBSBBBO.....................
.........OSMBBSBBBO.....................
........OSMMBBSBBBBO....................
........OSMMBBSBBBBO....................
........OSMBBOSBBBBO....................
........OSMBO.OSBBBO....................
.......OSMMBO..OSBBO....................
......OSMLMBO..OSBBBO...................
......OSMMMBO..OSBMBO...................
.....OSMMMBBBO.OSBMMBO..................
.....OKKKKKKKO.OKKKKKKO.................
......OOOOOOO...OOOOOO..................
'''),
'maiden-ghost': ((17,12), {
**COMMON,'S':'#4e5265','B':'#6b7080','M':'#91949e','L':'#b8beb8','H':'#d8dcce','T':'#f1ead2',
'a':'#aaa8a0','b':'#d3c7b0','c':'#eee0c4','R':'#835054','r':'#b66e66','E':'#ead4a1'}, '''
............OOOOO.............
..........OOSSSSDOO...........
.........OSBBSSSSDDO..........
.........OBMMBSSSSDDO.........
........OSMBBSSSbbSDDO........
........OBBBSSSbccbaDO........
........OBBSSDSbccbaDO........
........OBSSDDSbbKbaDO........
........OBSSDDSSbEbaDO........
........OBSDDDSSbbbaDO........
........OBSDDDSabbbaDO........
........OBSDDDSaRbaDO.........
........OBSDDDSabbaDO.........
........OBSDDDSSbaDDO.........
.......OSBSDDDSSbbSDDO........
......OSMBSDSDHLbbLHSDO.......
.....OSMHBSDSHLTHLTHSDDO......
....OSMHHBSDSHTTHLTHLSDDO.....
...OSLHHLBSDSHTTLHTHLSSDO.....
..OSLHHHLBSDSHHLTLHHLSSDO.....
.OSLHTTHLBSDSHLHbbHTHLSDO.....
OSLHTTTHMBSDSHLHbaHTTHMSDO....
OSLHTTHMBSDSHLTLHMHTTHLMSDO...
OSLHHHMBSDDSHLLHMMLHTTHLMSDO..
.OSMMLBBDDSHHTHMBBMLHTHLLSDO..
..OSMBaabSHLHTHRrRBMLHHLLSDO..
..OSabccabSLHHRrRHHBMHHLLSDO..
...OSbbaOSLHHHHHLHHBMHLHLSDO..
.....OOOSLHTTHHLLHHBMHLHMSDO..
.......OSLHTTHMLHHHBMHLHMSDO..
.......OSHTTHHMLHHHBMHLHMSDO..
......OSLHTTHMLHHHLBMHLHMSDO..
......OSHTTHHMLHHHLBMHLHMSDO..
.....OSLHTTHMLHHHHLBMHLHMSDO..
.....OSHTTHHMLHHHHLBMHLHMSDO..
....OSLHTTHMLHHHHHLBMHLHMSDO..
....OSHTTHHMLHHHHHLBMHLHMSDO..
...OSLHTTHMLHHHHHHLBMHLHMSDO..
...OSHTTHHMLHHHHHHLBMHLHMSDO..
..OSLHTTHMLHHHHHHLMBMHLHMSDO..
..OSHTTHHMLHHHHHHLMBMHLHMSSDO.
..OSLHHHMLHHHHHHHLMBMHLMSDDO..
...OSLLLMMHHHHHLLMMBMLMSDO....
....OSSSSLLLLLLLSSSMLSSDO.....
........OOaDOOOO..OOaDO.......
.........OOO........OOO.......
''')
}
if __name__ == "__main__":
    for name,(offset,palette,raw) in ART.items():

        rows = raw.strip('\n').splitlines()
        x,y=offset
        expanded=['.'*64 for _ in range(64)]
        for dy,row in enumerate(rows):
            row=row.rstrip()
            if len(row)+x>64: raise ValueError((name,dy,len(row)))
            if set(row)-set(palette)-{'.'}: raise ValueError((name,dy,set(row)-set(palette)-{'.'}))
            expanded[y+dy]='.'*x+row+'.'*(64-x-len(row))
        (ROOT/(name+'.pxgrid')).write_text('\n'.join(expanded)+'\n')
        (ROOT/(name+'.palette.json')).write_text(json.dumps(palette,indent=2)+'\n')
